### ISSUE TITLE
Exit code / http error documentation

### ISSUE THREAD

**Issue by Req** [wkhtmltopdf/wkhtmltopdf#1502]
When testing I kept getting exit code 1 quite often due to http error 1005 or 1xxx. Is there any documentation on exit codes and http error codes? It seems like exit code 1 usually can be ignored and happens only when something doesn't return 200 or such on the page. But what about the http errors? Http error 1005 doesn't really tell me anything

From looking at https://github.com/wkhtmltopdf/wkhtmltopdf/blob/master/src/lib/utilities.cc it would look to me like anything returning 404 would mean a returncode 2 and 401 would be 3 and anythign else is 1. Error 1005 doesn't sound like any http error I know. If I didn't fail it comes from PdfConverter's httpErrorCode() and there it comes from pageLoader.httpErrorCode(), but that's as far as I got tracing them from the source.

Documentation would be helpful in knowing which errors to ignore, currently it would seem to me like exit codes 0, 1, 2 and 3 can just be ignored quite safely.

**Comment by omrqs** [comment]
This error occurs when url are defined as //url... in place of https://url....
Keep the protocol. 
wkhtmltopdf try find double slash as local path...

Solved for me.
