### ISSUE TITLE
Pdf.js

### ISSUE THREAD

**Issue by gracile-fr** [wkhtmltopdf/wkhtmltopdf#1506]
Hi,
Not sure that you could do anything but there's an issue when I use pdf.js to open some PDFs created with wkhtmltopdf : if you copy and paste the textcontent of the PDF, each character is separated by a line break.

Cf. https://github.com/mozilla/pdf.js/issues/2569

Is there anything you can do on your own ? Thank you.

**Comment by denya-vs** [comment]
Hi, I have same problem.
A year has passed, it may already have some solution?

**Comment by geeckmc** [comment]
mupdf render can't annotate the generated with phpwkhtmltopdf (mupdf android crash when you try to open only phpwkhtmltopdf generated pdf)

PdfExplore an simple tool for analyze pdf structure (PdfExplore android crash when you try to open only phpwkhtmltopdf generated pdf)

**Adobe Acrobat ** And more tools.....
