### ISSUE TITLE
Example of using the --viewport-size option

### ISSUE THREAD

**Issue by Jimbobnz** [wkhtmltopdf/wkhtmltopdf#1508]
OS: Centos 6.5
wkhtmltopdf: Version 0.12.0

Please can I have  working example of using the viewport option. I've tried the following command: 

wkhtmltopdf --page-size A4 --viewport-size 1280x1024  http://www.whatismyscreenresolution.com/ whatismyscreenresolution.pdf

I get the following result stating it only 800x600
![whatismyscreenresolution com](https://f.cloud.github.com/assets/5185138/2119327/71fa9174-915d-11e3-9add-d5c2c4ac5e53.png)

**Comment by Emmanuel-K** [comment]
Thanks!
It works like a charm...

**Comment by Pagise** [comment]
@mufaddalmw That kind of works, however, you force the output to be in landscape format instead of the regular portrait... which is what makes it work. This may not be the appropriate solution for (most) people though...

**Comment by eved42** [comment]
I had the same problem, the generated PDF was the mobile version of my website.
Thanks to @mufaddalmw for your answer !

In a Symfony3 project, the config is : 
```
// app/config/config.yml

knp_snappy:
    pdf:
        enabled:    true
        binary:     %kernel.root_dir%/../vendor/wemersonjanuario/wkhtmltopdf-windows/bin/64bit/wkhtmltopdf.exe
        options:
           orientation: Landscape
           viewport-size: 1280x1024
```

**Comment by AvinashSKaranth** [comment]
Setting dpi works very well. You get the same effect as changing viewport 
--dpi 72 is default, --dpi 36 is for half width , --dpi 144 is for double width 
```{r, engine='bash', count_lines}
./wkhtmltopdf -T 6 -B 6 -L 6 -R 6 --dpi 36 'https://en.m.wikipedia.org/wiki/Game_of_Thrones' 'got.pdf'
```

**Comment by kironet** [comment]
I'm having the same problem with Bootstrap 4. Its like i'm in mobile version of the website.
Tried landscape but it didn't help at all :(

**Comment by Lagily** [comment]
I still have the problem @kironet stated, anyone found a fix for this? I am using viewport as stated above and also col-md- classes with Bootstrap 4!

**Comment by RailsCod3rFuture** [comment]
Where do you set the the viewport size? I'm also using Bootstrap 4, and the layout is being pulled to the far left due to the confusion between mobile and desktop resolutions

**pdfkit.rb**
```
PDFKit.configure do |config|
  if ["development"].include?(Rails.env)
    config.wkhtmltopdf = ENV['WKHTMLTOPDF_PATH'] || "C:\\wkhtml_setup\\wkhtmltopdf\\bin\\wkhtmltopdf.exe"
  else
    #if your site is hosted on heroku or any other hosting server which is 64bit
    config.wkhtmltopdf = Rails.root.join('bin', 'wkhtmltopdf-amd64').to_s
  end

  config.verbose = true
  config.default_options = {
      :encoding=>"UTF-8",
      #:page_size=>"A4", #or "Letter" or whatever needed
      :disable_smart_shrinking => false,
      dpi: 400
  }
end
```

**books_controller**

```
  def show
    impressionist(@book)
    respond_to do |format|
      format.html
      format.pdf do
     
        html = render_to_string(:action => "show.pdf.erb")
        kit = PDFKit.new(html, :orientation => 'Portrait')
        send_data(kit.to_pdf, :filename => "book.pdf", :type => 'application/pdf', :disposition => "inline")
      end
    end
  end
```

**Comment by targalimited** [comment]
> Thanks!
> It works like a charm...

it's not working!!!!

**Comment by poonai** [comment]
Is is possible to use viewport while using stdin as as input instead of url?
