### ISSUE TITLE
repeating CSS backgrounds broken for floating elements

### ISSUE THREAD

**Issue by fjoho** [wkhtmltopdf/wkhtmltopdf#1518]
Rendering repeating css backgrounds fails. See example below:
HTML:
![html](https://f.cloud.github.com/assets/6659004/2147151/bcfba25e-93cd-11e3-95eb-8f06f5ebd7db.png)
PDF:
![pdf](https://f.cloud.github.com/assets/6659004/2147152/bcfd106c-93cd-11e3-8995-06ff47d63b8c.png)
Background:
![bg](https://f.cloud.github.com/assets/6659004/2147179/15036252-93ce-11e3-8be0-0970fb6f1401.png)

HTML source:
https://gist.github.com/fjoho/8952929#file-repeatingcssbackgroundsfails

**Comment by sciolini** [comment]
I have the same problem with background images. Anybody could fix it? Thanks
