### ISSUE TITLE
Zoom effect

### ISSUE THREAD

**Issue by benique** [wkhtmltopdf/wkhtmltopdf#1520]
<b>What's the problem?</b>
Using the old version I could specify a hight zoom level to get more precise renderings of lines and fonts. It's possible to use lines which are 0.25pt thick.

Using the new version the zoom level just makes the document bigger which results in the content being spread over a lot of pages. If I don't specify the zoom level then the thin lines are not appearing in the PDF.

<b>What version of wkhtmltopdf was used?</b>
New version:
https://github.com/npinchot/wkhtmltopdf/releases/download/0.12.1/wkhtmltox-macosx-10.9.1-x86_64-0.12.1-b766b33.tar.xz

Old version:
wkhtmltopdf 0.10.0 rc2

<b>How were the PDFs generated?</b>

<pre><code>./wkhtmltopdf --zoom 100 'http://localhost/test.html' test.pdf</code></pre>

**Comment by schungx** [comment]
`--zoom x` seems like:

- if `x < 1`, shrinks the page proportionally
- if `x > 1.6`, magnifies the page proportionally
- if `x between 1-1.6`, page stays the same, but 1.3 seems to have highest character spacing quality
