### ISSUE TITLE
wkhtmltopdf fails to print pages, is killed

### ISSUE THREAD

**Issue by kyleconroy** [wkhtmltopdf/wkhtmltopdf#1521]
On certain URLs, printing fails half way through

```
$ wkhtmltopdf http://deckbrew.com/api/index.html ~/api.pdf
Loading pages (1/6)
QSslSocket: cannot resolve SSLv2_client_method               ] 10%
QSslSocket: cannot resolve SSLv2_server_method
Counting pages (2/6)                                               
Resolving links (4/6)                                                       
Loading headers and footers (5/6)                                           
Printing pages (6/6)
Killed=====================>                                  ] Page 3 of 7
```

OS: Ubuntu 12.04 64bit running in a VM
Version: 0.12.0, downloaded today from the website

**Comment by joshuapinter** [comment]
I ran into the exact same thing. This only occurred with very large PDFs. Initially I was getting the "Too many open files" error but after increasing my open file limits, I started getting this non-descript `Killed` message. 

To investigate, I ran `htop` while running a very large PDF generation and low and behold, this thing was so massive it ended up eating through my 32GBs of RAM and then started working on my Swap file. It's on Ubuntu so it's not a dynamic Swap file. You specify what size the Swap file is and it doesn't grow. 

Once the `wkhtmktopdf` command ate through all of the Swap file, it would quit with `Killed`. 

Ah ha!

So I increased the Swap file by a whopping 100GBs with the following commands: 

```bash
sudo dd if=/dev/zero of=/swapfile.img bs=1024 count=100M # Create 100GB Swap file at /swapfile.img.
sudo mkswap /swapfile.img                                # Setup the Swap filesystem for the file.
sudo echo "/swapfile.img swap swap sw 0 0" >> /etc/fstab # Add to filesystem config so it persists.
sudo reboot                                              # Reboot to take effect.
# ...reconnect...
free -mh                                                 # To confirm increased Swap size.
```

After doing this, the `wkhtmltopdf` command was able to finish successfully. This might be an edge case but we were generating PDFs that were 10,000+ pages.

**Comment by rupesh-patel-2** [comment]
> I ran into the exact same thing. This only occurred with very large PDFs. Initially I was getting the "Too many open files" error but after increasing my open file limits, I started getting this non-descript `Killed` message.
> 
> To investigate, I ran `htop` while running a very large PDF generation and low and behold, this thing was so massive it ended up eating through my 32GBs of RAM and then started working on my Swap file. It's on Ubuntu so it's not a dynamic Swap file. You specify what size the Swap file is and it doesn't grow.
> 
> Once the `wkhtmktopdf` command ate through all of the Swap file, it would quit with `Killed`.
> 
> Ah ha!
> 
> So I increased the Swap file by a whopping 100GBs with the following commands:
> 
> ```shell
> sudo dd if=/dev/zero of=/swapfile.img bs=1024 count=100M # Create 100GB Swap file at /swapfile.img.
> sudo mkswap /swapfile.img                                # Setup the Swap filesystem for the file.
> sudo echo "/swapfile.img swap swap sw 0 0" >> /etc/fstab # Add to filesystem config so it persists.
> sudo reboot                                              # Reboot to take effect.
> # ...reconnect...
> free -mh                                                 # To confirm increased Swap size.
> ```
> 
> After doing this, the `wkhtmltopdf` command was able to finish successfully. This might be an edge case but we were generating PDFs that were 10,000+ pages.

Thanks, this worked for me aswell
