### ISSUE TITLE
using OpenType fonts results in non-selectable text on Windows

### ISSUE THREAD

**Issue by mn4367** [wkhtmltopdf/wkhtmltopdf#1539]
If I use an Opentype font on Windows 7 the text in the PDF is no longer selectable and the PDF gets very big. Reminds me of older versions on OS X.

Checked with wkhtmltox-win64_0.12.1-development-773cad3.exe from Sourceforge.

**Comment by ashkulz** [comment]
`0.12.2` has been released, which includes changes related to this issue.
