### ISSUE TITLE
Inexact size of elements

### ISSUE THREAD

**Issue by mn4367** [wkhtmltopdf/wkhtmltopdf#1540]
Using

```
./wkhtmltopdf -T 2cm -R 2cm -B 2cm -L 2cm test.html test.pdf
```

with the following HTML

```
<html>
<head>
    <meta charset="utf-8"/>
    <style type="text/css">
        body {
            width: 17cm;
            margin: 0;
        }
    </style>
</head>
<body>
  <div style="margin: 0; background-color: green; width: 100mm;">100mm</div>
</body>
```

should produce a green <div> element with a width of exactly 100mm.

On OS X this was the case with previous versions but with the current build the <div> has a width of about 103 mm.

On Windows you have to use `--zoom 1.3` to get the correct width (`--zoom` was always necessary with previous versions on Windows). Is there any reason for the different behavior on both platforms?

Checked with wkhtmltox-win64_0.12.1-development-773cad3.exe and wkhtmltox-macosx-10.9.1-x86_64-0.12.1-development-593ac96.tar.xz from Sourceforge.

**Comment by eric-wieser** [comment]
What is this closed as a duplicate of?

**Comment by waltersteinlein** [comment]
This is still an issue for me. The provided hml page above results in an element just shy of 103mm with wkhtmltox-0.12.1 (which is the latest is could find pre-built rpms for) and exactly 80mm with a custom posix-local build from master.
