### ISSUE TITLE
PDFs rendering without embedded fonts on OS X

### ISSUE THREAD

**Issue by dan-mesa** [wkhtmltopdf/wkhtmltopdf#1545]
Rendering a completely blank HTML file on OS X:
- 0.12.1 generates a 4 KB file
- 0.10.0 RC2 generates a 1 KB file

Pages with more HTML see a similar ratio:
- 0.12.1 generates a 648 KB file
- 0.10.0 RC2 generates a 111 KB file

**Comment by ashkulz** [comment]
This is likely to be fixed for the 64-bit Cocoa build as well, see #2151 for details.

**Comment by ashkulz** [comment]
I would appreciate feedback on the [64-bit Cocoa build](http://downloads.sourceforge.net/project/wkhtmltopdf/0.12.2.1/wkhtmltox-0.12.2.1-rc-bfe5111_osx-cocoa-x86-64.pkg) to confirm whether this issue has been resolved.

**Comment by ashkulz** [comment]
`0.12.2.1` has been released, which includes changes related to this issue.

**Comment by dan-mesa** [comment]
Website | Version | File Size
------------ | ------------- | -------------
google.com | 0.12.1 (593a...4e83) | 67 KB
google.com | 0.12.2.1 | 37 KB

Looks like it's resolved. Thanks, @ashkulz, much appreciated - as always! You're a rockstar.
