### ISSUE TITLE
problem with non-ASCII characters in output path on Windows

### ISSUE THREAD

**Issue by nsilve** [wkhtmltopdf/wkhtmltopdf#1546]
When I run "wkhtmltopdf.exe" from cmd and the output path contains greek characters, the response is:

QPainter::begin(): Returned false
Error: Unable to write to destination
Exit with code 1, due to unknown error.

When only the output filename has greek characters, the filename looks like "������������.pdf"

There is no problem when only the input path contains greek characters.

Thank you very much!

**Comment by Darshdnd** [comment]
Windows 10 64 bit 
System Locale:             4009
Input Locale:              no;Norwegian (Bokmal)

unable to save/ download PDF file name when some norwegian  characters are available ..

please give me solution
