### ISSUE TITLE
page-breaks ignored

### ISSUE THREAD

**Issue by vandersonmota** [wkhtmltopdf/wkhtmltopdf#1551]
Hi guys, i am using the current stable version (0.12) and i'm having issues with page-breaks in tables.

it seems 

``` css
page-break-inside: avoid;
```

and

``` css
  page-break-after: always;
```

are being ignored when rendering the pdf. 

[]'s

**Comment by geri777** [comment]
For me page-break-after and page-break-before are totally ignored. There's no page break in the PDF. I am using the latest release (0.12.2.2). Is there anybody who can confirm that page-breaks are working at all?

	<p>Text page 1</p>
	<div style="page-break-after:always; border:1px solid blue;"></div>
	<div style="page-break-before:always; border:1px solid red;"></div>
	<p>Text page 2</p>

Thank you,
Geri

**Comment by mistajase** [comment]
Im also facing the same issue - page breaks work in v11 but not in v12

**Comment by geri777** [comment]
I could fix the problem by using the latest codebase (12.2.1) from the official project website. It did not work when I was trying to install the software via the ubuntu repository with "apt-get install wkhtmltopdf".
The version from http://wkhtmltopdf.org/downloads.html works. However it's about 5 times slower than the version in the repository. Can you confirm this?

**Comment by imjustd** [comment]
I also have the same issue with the page break directives in version 0.12.2.2 for windows. They all get ignored and the page is not broken as expected.

**Comment by dominicfollett** [comment]
Also encountering the same problem, but I have the latest code-base. Will this be fixed in the 13.x series?

**Comment by yhwu** [comment]
wkhtmltopdf 0.12.2.1 (with patched qt) works with ```<P style="page-break-before: always">```.  <br/>  wkhtmltopdf 0.9.9 used to work with ```<hr/>``` to produce a new page.

**Comment by jesobreira** [comment]
I could get it to work by using @yhwu 's tip (`<P style="page-break-before: always">`) and `--print-media-type` argument.

**Comment by rudza** [comment]
> I could get it to work by using @yhwu 's tip (<P style="page-break-before: always">) and --print-media-type argument.

This worked for me too! :)

**Comment by mikeglaz** [comment]
What is the --print-media-type argument?

**Comment by rudza** [comment]
@mikeglaz Add it to the options Object: `      var options = {
          pageSize: 'A4',
          marginLeft: '0',
          marginRight: '0',
          marginTop: '0',
          printMediaType: true
      };`

**Comment by brpaz** [comment]
Cant get it to work even with --print-media-type option and the solution proposed by @yhwu 

Using  wkhtmltopdf 0.12.3 (with patched qt) on Linux mint 18.

**Comment by fatuhoku** [comment]
Are we masters of our technology or are they masters of us?

A part of me cannot believe that it's 2016 and we have no good way to tell the computer to put some text on the next page.

**Comment by Stibila** [comment]
In wkhtmltopdf 0.12.3 (with patched qt) page breaking works as long as style _"page-break-before: always"_ is use on **p** element. Doesn't work with **div** element (and probably with other elements as well).
```
<!-- This works -->
<p style="page-break-before: always"></p>

<!-- This doesn't work -->
<div style="page-break-before: always"></div>
```

Argument _--print-media-type_ is not necessary.

**Comment by leonardoteck** [comment]
I spend many, many days on this problem, I read the comments above nearly a thousand times, and finally I found a solution. I'm using v0.12.3.2 and my advice is:
* Use the `--print-media-type` argument
* Don't use `<table>, <tr>, <td>` nor `display: table, display: table-cell...`
* Create a class with `page-break-inside: avoid !important;`, and use it in every single element, independent of it's type, that forms a line or block of content

**Comment by peaeater** [comment]
@Stibila I just tried wkhtmltopdf 0.12.4, and page breaking seems to work with **div** elements. I'm not using the `--print-media-type` argument.

```
<!-- works in 0.12.4 -->
<div style="page-break-before: always"></div>
```

**Comment by DarshanKsheerasagar** [comment]
Hello @peaeater

I am also using V 12.4 but still issue is there 
![issueimage](https://cloud.githubusercontent.com/assets/24871149/23055611/c6e95b0a-f50c-11e6-8494-f19deb76be65.JPG)

**Comment by michaelmartinnz** [comment]
wkhtmltopdf 0.12.2.1 (with patched qt)
<div style="width: 100%; page-break-inside: avoid;"><table>...</div>
works

**Comment by gmkhussain** [comment]
use this classes for page break :
```
<style type="text/css" media="screen,print">
       /* Page Breaks */

/***Always insert a page break before the element***/
       .pb_before {
           page-break-before: always !important;
       }

/***Always insert a page break after the element***/
       .pb_after {
           page-break-after: always !important;
       }

/***Avoid page break before the element (if possible)***/
       .pb_before_avoid {
           page-break-before: avoid !important;
       }

/***Avoid page break after the element (if possible)***/
       .pb_after_avoid {
           page-break-after: avoid !important;
       }

/* Avoid page break inside the element (if possible) */
       .pbi_avoid {
           page-break-inside: avoid !important;
       }

   </style>
   
```
   
   
   
   
How to write html code see example.
```
<div class="page1 pb_after">
   content 1...
</div>
<div class="page2 pb_before pb_after">
   content 2.... <table>...</table> 
</div>
```

Table rows break... It works :)

**Comment by hkraji** [comment]
After a lot of debugging turns out that page breaks don't play nice with `overflow: hidden`.

This worked for me

```css
* {
  overflow: visible !important;
}
```
Needless to say, this is just to check if that is the issue, track it down once you confirm it.

**Comment by gastonmastra** [comment]
> Hello @peaeater
> 
> I am also using V 12.4 but still issue is there ![issueimage](https://cloud.githubusercontent.com/assets/24871149/23055611/c6e95b0a-f50c-11e6-8494-f19deb76be65.JPG)

Hi! could you fix it?
