### ISSUE TITLE
wkhtmltopdf 0.12 builds against patched qt

### ISSUE THREAD

**Issue by ferdiga** [wkhtmltopdf/wkhtmltopdf#1556]
Hello!
the binaries (amd64) on
http://wkhtmltopdf.org/
are apparently not build using the patched qt 
- hence OpenERP webkit reports  which require  --header-html to work, can't be used out of the box. 
  Question - can static binaries be produced using the patched qt
  BTW using
  wkhtmltox-linux-amd64_0.12.1-development-773cad3.tar.xz
  works as expected

**Comment by imaayush** [comment]
I am trying to install wkhtmtopdf with patched qt on ubuntu 16.04  but it alway install without patched qt

**Comment by poolerMF** [comment]
I ahve same problem as @imaayush
