### ISSUE TITLE
Glibc not found

### ISSUE THREAD

**Issue by shorif2000** [wkhtmltopdf/wkhtmltopdf#1558]
I am using centos 5.5. 32bit and have downloaded v0.12 and copied it over to /usr/bin dir. I am getting the following error

Could not create PDF: Could not run command '/usr/bin/wkhtmltopdf' --no-outline --margin-top '10' --margin-right '5' --margin-bottom '10' --margin-left '5' --orientation 'landscape' /tmp/tmp_WkHtmlToPdf_JaseZp.html /tmp/tmp_WkHtmlToPdf_lCfR4X:
/usr/bin/wkhtmltopdf: /lib/libc.so.6: version `GLIBC_2.9' not found (required by /usr/bin/wkhtmltopdf)
/usr/bin/wkhtmltopdf: /lib/libc.so.6: version`GLIBC_2.10' not found (required by /usr/bin/wkhtmltopdf)
/usr/bin/wkhtmltopdf: /lib/libc.so.6: version `GLIBC_2.7' not found (required by /usr/bin/wkhtmltopdf)

**Comment by Cywaithaka** [comment]
One of the old builds worked for me. Here's what I did:
yum remove wkhtmltopdf
yum remove wkhtmltox
rpm -ivh http://liquidtelecom.dl.sourceforge.net/project/wkhtmltopdf/0.12.2.1/wkhtmltox-0.12.2.1_linux-centos5-amd64.rpm

**Comment by ashkulz** [comment]
@Cywaithaka: that is the latest version :smile:

**Comment by Cywaithaka** [comment]
:-) Okay. I guess my issue was as a result of trying to run the centos6 wkhtmltox version on centos 5. Thanks for the link
