### ISSUE TITLE
consuming too much memory

### ISSUE THREAD

**Issue by ushavimal** [wkhtmltopdf/wkhtmltopdf#1562]
I am using wkhtmltopdf to generate pdfs with huge number of records in tables(400k). I am able to generate the pdf successfully for 200k records(memory utilization increases by about 1.5 GB). But when I  generate for 400k, memory increases rapidly after the html is generated in the /tmp folder(~20MB per second). It keeps increasing until it runs out of memory and the process fails with the following error

```
"***************\"/usr/bin/wkhtmltopdf\" -q     --margin-top 10 --margin-bottom 0  --disable-javascript    \"file:////tmp/wicked_pdf20140224-25879-g3y5ad.html\" \"/tmp/wicked_pdf_generated_file20140224-25879-1kd3fc9.pdf\" ***************"
2014-02-24T21:38:13Z 25879 TID-1aqes6 PdfWorker JID-9173aa7ccf2f122ed184f0ad ERROR: RuntimeError: Failed to execute:
"/usr/bin/wkhtmltopdf" -q     --margin-top 10 --margin-bottom 0  --disable-javascript    "file:////tmp/wicked_pdf20140224-25879-g3y5ad.html" "/tmp/wicked_pdf_generated_file20140224-25879-1kd3fc9.pdf" 
Error: PDF could not be generated!
```

Any idea why it uses so much memory?

**Comment by nathantechie9** [comment]
I am running into similar issue. I have 64 gb of ram. But it keeps segmentation faulting error 14. Where can I set wkhtmltopdf --load-error-handling ignore in the Rails config initializer? I can't find it in the docs. Also, is there a way to tell wicked to break up the job into pieces?
