### ISSUE TITLE
Unable to write to destination

### ISSUE THREAD

**Issue by pedro0alves** [wkhtmltopdf/wkhtmltopdf#1568]
The application is running in IIS and the NETWORKSERVICE user can write on  C://metodekort/PDF/ directory. Do you know why got I "Unable to write to destination" message?      

2014-02-27 10:55:12,296 [40] ERROR DigitaleMetodekort.Controllers.PdfController 'C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe http://intern/Metodekort/Pdf/ShowHtml?name=c6bdff63-d7d9-4417-a257-76656fc77ee9 PDF.pdf' finished with exit code = 1: Loading pages (1/6)
[>                                                           ] 0%
[======>                                                     ] 10%
[=======>                                                    ] 12%
[=========>                                                  ] 16%
[==========>                                                 ] 18%
[=============>                                              ] 23%
[===============>                                            ] 26%
[==================>                                         ] 31%
[=====================>                                      ] 36%
[========================>                                   ] 41%
[===========================>                                ] 45%
[==============================>                             ] 50%
[======================================>                     ] 64%
[==========================================>                 ] 71%
[==============================================>             ] 77%
[================================================>           ] 80%
[=================================================>          ] 83%
[===================================================>        ] 85%
[====================================================>       ] 87%
[============================================================] 100%
QPainter::begin(): Returned false
Error: Unable to write to destination  
Exit with code 1, due to unknown error.

**Comment by linlin-coder** [comment]
it not can works
