### ISSUE TITLE
letter-spacing does not work as intended!

### ISSUE THREAD

**Issue by AnderssonPeter** [wkhtmltopdf/wkhtmltopdf#1575]
Same issue as 138 on google code.

This issue still persist in 0.12.0 Final (QT Patched) Windows 7 64 bit

``` html
<!DOCTYPE html>
<h1 style="letter-spacing: 10px">Testing letter spacing</h1>
<div style="width: 10px; height: 10px; background: red"> </div>
```

The space between the letters should be the same size as the red box, but its not!

**Comment by vstoykov** [comment]
@rainabba can you tell us what is your reset CSS that will fix the `letter-spacing` issue. If it is possible only with CSS to fix this problem, probably there can be a solution of embedding reset CSS in `wkhtmltopdf` which will resolve the issue.

**Comment by ygwain** [comment]
@vstoykov see my comment, might help:
https://github.com/wkhtmltopdf/wkhtmltopdf/issues/2372#issuecomment-203037983

**Comment by tejastank** [comment]
Soluion is here: https://stackoverflow.com/a/46034207/1635700

**Comment by mirkhamidov** [comment]
This solutions is not work!

**Comment by DanHibbert** [comment]
It doesn't solve it but I found 
body { 
    font-kerning: normal; 
    text-rendering: optimizeLegibility;
   ....}

in the css

and the --dpi 200 switch helped me.

**Comment by VahidAssadi** [comment]
non of above solution diden't help me;
please help me.
there is a problem always. its so tireing...
