### ISSUE TITLE
Blank page printing if --header-html option is used 

### ISSUE THREAD

**Issue by bpbhat77** [wkhtmltopdf/wkhtmltopdf#1593]
C:\Program Files\wkhtmltopdf\bin>wkhtmltopdf  --header-line --footer-line --head
er-html head.html  HOM.html test.pdf &&  test.pdf

i used --javascript-delay 500 also still its printing blank page 

OS:Windows xp(32bit)
version :0.12.0

same HOM.html will print correctly if --header-html option is not used

**Comment by jabellcit** [comment]
Holy Christ, why the hell is this not in the documentation?! I spent 5hrs trying to figure out why this crap doesn't work, and here the answer is, working fine once DOCTYPE is specified!

**Comment by Yelnik** [comment]
@jabellcit Yes very irritating for me as well. Extra silly because you are specifying header-**HTML** and the file you're passing it is usually header.**html**. But nope, better tell it three times for good measure!

**Comment by anga20** [comment]
hey how to specify doctype

**Comment by anga20** [comment]
please give examples

**Comment by salimhb** [comment]
@anga20, you need to have a complete html file starting with the doctype:
```html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html><head><script>
function subst() {
  var vars={};
  var x=document.location.search.substring(1).split('&');
  for(var i in x) {var z=x[i].split('=',2);vars[z[0]] = unescape(z[1]);}
  var x=['frompage','topage','page','webpage','section','subsection','subsubsection'];
  for(var i in x) {
    var y = document.getElementsByClassName(x[i]);
    for(var j=0; j<y.length; ++j) y[j].textContent = vars[x[i]];
  }
}
</script></head><body style="border:0; margin: 0;" onload="subst()">
<table style="border-bottom: 1px solid black; width: 100%">
  <tr>
    <td class="section"></td>
    <td style="text-align:right">
      Page <span class="page"></span> of <span class="topage"></span>
    </td>
  </tr>
</table>
</body></html>
```

**Comment by conr** [comment]
Working example for a header/footer:

```html
<!DOCTYPE html>
<html>
  <head>
    <script></script>
  </head>
  <body>
    <!--Your header/footer code goes here-->
  </body>
</html>
```
