### ISSUE TITLE
Failed to load file (absolute paths in Windows)

### ISSUE THREAD

**Issue by chrisgallacher** [wkhtmltopdf/wkhtmltopdf#1594]
wkhtmltopdf 0.12.0 final
Windows XP SP3/Windows Vista Business SP2

Images linked using file:// in html document are not appearing in PDF, wkhtmltopdf exiting with "Failed to load" error.

For example, I created a simple html file (test.html):
`<html>
    <body>
        
        <img src="file://c:/test/test.png" />
    </body>
</html>`

And tried to convert this to PDF:

`C:\test>wkhtmltopdf test.html test.pdf
Loading pages (1/6)
Warning: Failed to load file://c/test/test.png (ignore)
Counting pages (2/6)
Resolving links (4/6)
Loading headers and footers (5/6)
Printing pages (6/6)
Done`

The error suggests wkhtmltopdf is omitting the ":" after the drive name. Replacing the ":" with "|" does not throw an error but the image still does not appear in PDF.

(Edit: Markdown)

**Comment by jqn** [comment]
This took me forever to figure out but if you using a mac machine this is how to get wkhtmltopdf to find your images in your template.
`<img src="/Users/my-user/Sites/testsite/pdf_generator/static/images/logo.png">`
