### ISSUE TITLE
Text getting cut off on the right margin

### ISSUE THREAD

**Issue by j-manu** [wkhtmltopdf/wkhtmltopdf#1595]
On some pages, text is getting cut off on the right margin. 

Sample Page - http://storage.googleapis.com/pf-web/test_cases/wkhtmltopdf_text_cutoff/text_cut_off_in_the_right.html

Screenshot of the problem - https://cloudup.com/crH4TMXBDWG

wkhtmltopdf command

```
wkhtmltopdf --print-media-type --margin-top 10mm --margin-bottom 10mm  --page-size Letter http://storage.googleapis.com/pf-web/test_cases/wkhtmltopdf_text_cutoff/text_cut_off_in_the_right.html result.pdf
```

wkhtmltopdf versions affected: 
OS X: 0.12.1-fef236e8444bf2db7cbbc5c82a752b7b71f0b954
Linux: 0.12.0

This is a regression. OS X 0.10.0 beta4 & linux 0.10.0 are not affected by this

**Comment by kartofelek007** [comment]
I reproduce this isue when I generate pdf with "Times New Roman"

Without Times New Roman
![without](https://cloud.githubusercontent.com/assets/2007669/18871538/13f5bf0a-84b6-11e6-96c9-3b25a56b5e99.png)

With Times New Roman
![with](https://cloud.githubusercontent.com/assets/2007669/18871551/207bb086-84b6-11e6-8b8b-c1dcbf78f90d.png)

No styles or options has change.

**Comment by Spencerooni** [comment]
I have the same issue as @kartofelek007. With justified text and using certain fonts, the right hand side of the document is truncated. Examples: Courier new, Tahoma are fine. Arial is not.

**Comment by Spencerooni** [comment]
Since my comment above, I've done some investigation and discovered this is fixed for me in the alpha 0.13.0. I assume it's the newer version of qtwebkit.

**Comment by vannicktrinquier** [comment]
I have exactly the same as @Spencerooni , is there any other workaround without having to updgrade wkthmltopdf to the version 0.13.0 alpha ?

**Comment by xmarkclx** [comment]
This fixes it without upgrading to 0.13.0 @vannicktrinquier .

```js
.main-content{
  max-width: 99%;
}
```

**Comment by kyletolle** [comment]
I've also run into this issue with text being truncated on the right margin. I'm generating a PDF with wkhtmltopdf 0.12.3 through pandoc 2.1.3. wkhtmltopdf 0.12.4 has issues with text scaling, as mentioned in #3241, so I downgraded to 0.12.3. I'm able to get around it via CSS with what @xmarkclx suggested by setting max-width on the body tag.  This seems to fix the truncation, but has the downside of increasing the margins of the pages. On longer documents, a smaller body width translates into more pages. A value of 99.9% solved a lot of problems, but there were still a few places where the lines truncated. It might be possible to fiddle with a value like 99.5%, 99.8%, etc to figure out the exact minimum you need, but each time the lines change it introduces new chances for a line to be truncated, which complicates matters. Even then, the exact values likely differ depending on your content, font size, or other details. Bummer.

**Comment by xmarkclx** [comment]
@kyletolle You can adjust the margins using the

```
margin-right
```

option. Then adjust the max-width % accordingly.

That should solve your issue, although would require a bit of trial and error.

**Comment by Eyewash01** [comment]
Just to add, I'm also still getting this issue - tested on Windows with 0.12.5

**Comment by huangjinshe** [comment]
wkhtmltox 0.12.6 still has this problem.

**Comment by joshuapinter** [comment]
### Set `width` on `body` that matches your page content size (i.e. page size minus horizontal margins).

We were seeing this on 0.12.6. The the right side of text was being cut off and not wrapping to the next line properly.

We dabbled with a number of the other solutions, like changing the `max-width` to `99%`. That certainly works but feels like a bit of a hack.

We ended up specifying the `width` in the `body` tag that we wanted to use. This forces the HTML to render correctly.

We exclusively use Letter page sizes in portrait and landscape so we have a width for each of those, wrapping it in a helper to keep it DRY.

For portrait, we used `width: 7.64in` and for landscape, we used `width: 10.2in`.

You'll want to test this yourself, especially the landscape to make sure it works well.

Additionally, when using `show_as_html`, you can set a page height and a border style like `border: 1px dashed #333` to roughly see how your content will layout on the page when it is printed to PDF.

**Comment by ved7** [comment]
> ```js
> .main-content{
>   max-width: 99%;
> }
> ```

this works for me. Thanks @xmarkclx

**Comment by rg-08** [comment]
> ### Set `width` on `body` that matches your page content size (i.e. page size minus horizontal margins).
> We were seeing this on 0.12.6. The the right side of text was being cut off and not wrapping to the next line properly.
> 
> We dabbled with a number of the other solutions, like changing the `max-width` to `99%`. That certainly works but feels like a bit of a hack.
> 
> We ended up specifying the `width` in the `body` tag that we wanted to use. This forces the HTML to render correctly.
> 
> We exclusively use Letter page sizes in portrait and landscape so we have a width for each of those, wrapping it in a helper to keep it DRY.
> 
> For portrait, we used `width: 7.64in` and for landscape, we used `width: 10.2in`.
> 
> You'll want to test this yourself, especially the landscape to make sure it works well.
> 
> Additionally, when using `show_as_html`, you can set a page height and a border style like `border: 1px dashed #333` to roughly see how your content will layout on the page when it is printed to PDF.

I know it's quite old, but we have the same issue. (exactly the same described by @Spencerooni).
We tried the max-width hack, but with no success.
We'd like to try you suggestion; you wrote you are using width: 7.64in for portrait in the body tag.
Something like this? <body style="width: 7.64in">
What about left and right margins? Have you specified some values when invoking WK?
We want to use A4 size with 10mm L and R margins.
We are trying to use: <body style="width: 190mm"> and passing -L 10 -R 10 to WK, but in this way le right margin is too big, leaving a lot a space.
Any suggestion?

**Comment by rg-08** [comment]
@joshuapinter Thank you so much.

In the end we used this configuration:

`body{
font-family: Verdana;
text-rendering: geometricPrecision;
width: 205mm;
}`

with args: `--page-size A4 -L 15 -R 15`
