### ISSUE TITLE
Bold text with @font-face make double character

### ISSUE THREAD

**Issue by joakar** [wkhtmltopdf/wkhtmltopdf#1601]
I have some text in bold and I am using Open Sans font. 
When I try to copy the text, then there will be duplicates of the character.

<b>HTML:</b>
<code>&lt;p&gt;This &lt;strong&gt;example text&lt;/strong&gt; is not okay&lt;/p&gt;</code>

<b>Image from pdf:</b>
<code>![open sans bold](https://f.cloud.github.com/assets/1263404/2522855/886cbe8a-b4c8-11e3-9cf6-d36dcb98abc0.png)</code>

<b>Text from clipboard:</b>
<code>This eexxaamplee teexxt is not okay</code>

**Comment by besciualex** [comment]
This is still an issue in my opinion.
```
       @font-face {
            font-family: "Enzo";
            src: url('/public/fonts/Enzo-Regular.otf') format('opentype');
            font-style: normal;
            font-weight: 400;
        }
        @font-face {
            font-family: "Enzo";
            src: url('/public/fonts/Enzo-Bold.otf') format('opentype');
            font-style: normal;
            font-weight: 700;
        }
```
Is not workin. I checked multiple times, and it seems like it is seeing both fonts, but the bolded one is always dubled. Even when it's alone by itself on the whole PDF.

**Comment by theo4u** [comment]
check my comment here #1542
