### ISSUE TITLE
"page-break-after: always;" is ignored when parent div floats

### ISSUE THREAD

**Issue by cspitzlay** [wkhtmltopdf/wkhtmltopdf#1604]
I tracked down the reason why "page-break-before: always;" and "page-break-after: always;" are ignored when printing our pages. Page-breaks do not happen when the parent div floats.
Removing the "float: left;" from the parent fixed the issue for us.

This is with version 0.12.x. 
We are seeing this on 
- MacOSX with the current download (version string wkhtmltopdf 0.12.1-fef236e8444bf2db7cbbc5c82a752b7b71f0b954) 
- an earlier dev version that was built with brew 
- on Debian (wkhtmltopdf 0.12.0-ebf9b6cfc4c58a31349fb94c568b254fac37b3d3)

This used to work with the 0.11 Debian build that was available from google code. 

I'll attach two test cases (one good and one bad), for the sake of simplicity with inline styles.
Good:

```
<!DOCTYPE html>
<head>
<meta charset="utf-8" />
</head>
<body>
<div style="float: none;">
  <div>Foo (supposed to appear on first page).</div>
  <div style="page-break-before:always;">Bar (supposed to appear on the second page).</div>
</div>
</body>
```

Bad:

```
<!DOCTYPE html>
<head>
<meta charset="utf-8" />
</head>
<body>
<div style="float: left;">
  <div>Foo (supposed to appear on first page).</div>
  <div style="page-break-before:always;">Bar (supposed to appear on the second page but doesn't).</div>
</div>
</body>
```

**Comment by DarshanKsheerasagar** [comment]
Hi ,

I am also Applying the page-break-after:always; but it not proper generating pdf ,below is the pdf image .


![pdfimage](https://cloud.githubusercontent.com/assets/24871149/24642263/d7e992a4-1923-11e7-94a6-0fa18ac3f264.JPG)

**Comment by hiteshgarg1994** [comment]
Its been three year and the issue is still there...
page break css attribute either after or before is not working under floating environment...
Applying 'clear' css property to your div may help in breaking the page but not every time...
Example -  <div style="page-break-after: always ; clear:both" > </div>

Please tell me if anyone have the confirm solution.

**Comment by viswa18** [comment]
I am also having the same issue, if anyone know the solution, please post here.

**Comment by firesh** [comment]
Please try use this code force page break!
`<div style="float: none;"><div style="page-break-after: always;"></div></div>`

**Comment by darshan-odoo** [comment]
Snapped by this Similar Issue, page-break misbehaves under float CSS property!

Any workaround alternative solution to this?

**Comment by sergshu** [comment]
> Please try use this code force page break! `<div style="float: none;"><div style="page-break-after: always;"></div></div>`
> 
> @viswa18 @hiteshgarg1994

in works for me. Thanks!
