### ISSUE TITLE
CSS margins are not applied at the start of document

### ISSUE THREAD

**Issue by piotrwoj** [wkhtmltopdf/wkhtmltopdf#1606]
Rendering:

```
<body>
<div style="margin-top: 3in;">
test
</div>
</body>
```

gives no margin on top!
(wkhtmltopdf 0.12 64-bit, Ubuntu)

**Comment by shashank-agg** [comment]
For anyone else facing the same issue, you can try this as a workaround: Wrap the div with the margins in a parent div. Give 
```position: relative```
 to the parent, and 
```position: absolute```  to the child div.

**Comment by ElijahGM** [comment]
Try Padding-top instead.. worked for me..

**Comment by yoursdearboy** [comment]
I've fixed this using `body { padding: 1px 0; }`, but now there's a problem with tables spanning multiple pages - there's empty space before the first row on the second page.

**Comment by RezaZR** [comment]
I think i found the "solution" for this, I use this:
```
<div class="template"> //doesnt work if i put here
  <div style="margin: 2em; padding-top: 2em"> //margin-top doesn't work, instead I'm using padding-top
  </div>
</div>
```
hope this help
