### ISSUE TITLE
Post request error with http authentication

### ISSUE THREAD

**Issue by valery-eliseev** [wkhtmltopdf/wkhtmltopdf#1611]
wkhtmltopdf 0.12.0 on Debian Linux 2.6.32-5-amd64

If access to the resource requires http authentication by password (AuthType Basic) and a request is made by the POST method to transfer parameter values, for example:

wkhtmltopdf  --username 'wkhtml' --password 'pass' --post 'postname' 'postdata' "https://aaa.bbb/data.php" "out.pdf"

An error occurs, pdf file contains no data:

Error: Failed loading page https://aaa.bbb/data.php (sometimes it will work just to ignore this error with --load-error-handling ignore)
Exit with code 1 due to http error: 1205

The protocol to the request Apache returns error 401

x.x.x.x - - [01/Apr/2014:15:35:30 +0400] "POST /data.php HTTP/1.1" 401 5900 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/534.34 (KHTML, like Gecko) Qt/4.8.5 Safari/534.34"

If the same request is made without option "--post", or HTTP authorization is not required, no error occurs, the output pdf file is generated correctly.

**Comment by wladiston** [comment]
Im getting the same problem here on **0.12.2.1**.
``` terminal
C:\>wkhtmltopdf.exe --username myuser --password 123456 --post-file file
C:\log.txt http://localhost:22797/xcontroller/testepost testew.pdf
Loading pages (1/6)
Error: Failed loading page http://localhost:22797/xcontroller/testepost
 (sometimes it will work just to ignore this error with --load-error-handling ig
nore)
Exit with code 1 due to network error: ContentReSendError
```
But everything works fine when I try GET or POST without the Authentication.

**Comment by rarunkumar454** [comment]
Hi, i am using wkhtmltopdf dll. I have an issue, It is working perfectly on loginpage and unauthenticated pages, but for any logged pages it could not be able to convert to that logged page.
