### ISSUE TITLE
Warning: Received createRequest signal on a disposed ResourceObject's NetworkAccessManager

### ISSUE THREAD

**Issue by darlingm** [wkhtmltopdf/wkhtmltopdf#1613]
---

Warning: Received createRequest signal on a disposed ResourceObject's NetworkAccessManager. This migth be an indication of an iframe taking to long to load.------- (migth misspelling in code)

I receive this error in about 1 out of 4 runs, even on pages without iframes.  Like http://commons.wikimedia.org/wiki/File:Polarlicht_2.jpghttp://commons.wikimedia.org/wiki/File:Polarlicht_2.jpg -- But issue happens on other non-wiki sites also.

CentOS 5.  Running wkhtmltox-0.12.1-61b740e for CentOS 5.

Biggest issue is the PDF file changes a bit depending on if this warning came up.  And, regardless of warning, it exits saying "Done" with exit value 0.

**Comment by tierrarara** [comment]
Hi guys, i received the same message, after debug script with QTbrowser to fixed some error
not matter how many seconds set into delay, alwasy received the messages,  exist another way to log what is the real problem

**Comment by richmahn** [comment]
How many seconds are you setting it to? I set it to 2000 (2 seconds) and it worked.

**Comment by begonaalvarezd** [comment]
I found that the delay needed to be proportional to the number of documents i was processing.
since i was processing ~20 documents at a time, i used 10000ms (10 seconds)

**Comment by tierrarara** [comment]
> How many seconds are you setting it to? I set it to 2000 (2 seconds) and it worked.

the problem for me no was the  delay time, the problem for me was the fonts that i  use, i create a css simple version without google fonts for wkhtml page request.  I detect the problem in QTBrowser console tool
