### ISSUE TITLE
ContentNotFoundError, QFont::setPixelSize: Pixel size <= 0 (0)

### ISSUE THREAD

**Issue by darlingm** [wkhtmltopdf/wkhtmltopdf#1614]
wkhtmltox-0.12.1-61b740e, for CentOS 5.

wkhtmltopdf http://www.artclon.com/paintings/woman-arranging-her-hair_10709.html test.pdf

Re-running it always winds up the same.  Page loads in web browsers nearly instantly.

Same error often comes up on http://www.lib-art.com/artgallery/12748-female-head-la-scapigliata-leonardo-da-vinci.html -- although that page bounces between ContentNotFoundError and ContentOperationNotPermittedError, always exiting code 1.

---

Loading pages (1/6)
QFont::setPixelSize: Pixel size <= 0 (0)=======>             ] 77%
QFont::setPixelSize: Pixel size <= 0 (0)
QFont::setPixelSize: Pixel size <= 0 (0)==============>      ] 89%
QFont::setPixelSize: Pixel size <= 0 (0)
Counting pages (2/6)
QFont::setPixelSize: Pixel size <= 0 (0)=====================] Object 1 of 1
QFont::setPixelSize: Pixel size <= 0 (0)
QFont::setPixelSize: Pixel size <= 0 (0)
QFont::setPixelSize: Pixel size <= 0 (0)
QFont::setPixelSize: Pixel size <= 0 (0)
QFont::setPixelSize: Pixel size <= 0 (0)
QFont::setPixelSize: Pixel size <= 0 (0)
QFont::setPixelSize: Pixel size <= 0 (0)
Resolving links (4/6)
Loading headers and footers (5/6)
Printing pages (6/6)
QFont::setPixelSize: Pixel size <= 0 (0)                     ] Preparing
QFont::setPixelSize: Pixel size <= 0 (0)
QFont::setPixelSize: Pixel size <= 0 (0)
QFont::setPixelSize: Pixel size <= 0 (0)
QFont::setPixelSize: Pixel size <= 0 (0)=====================] Page 5 of 5
QFont::setPixelSize: Pixel size <= 0 (0)
QFont::setPixelSize: Pixel size <= 0 (0)
QFont::setPixelSize: Pixel size <= 0 (0)
Done
Exit with code 1 due to network error: ContentNotFoundError

**Comment by harpreetsinghhora** [comment]
Well, I'm facing similar issue
