### ISSUE TITLE
cannot use OpenType fonts if they are installed locally on Windows and same font is loaded via WOFF

### ISSUE THREAD

**Issue by rainabba** [wkhtmltopdf/wkhtmltopdf#1620]
My development environment was working great but when I ran the EXACT same Node.js app using wkhtmltox-win64_0.12.0-03c001d.exe to generate PDFs on my production machine, the PDFs I got were effectively blank. There were hints of structure though so I suspected it was a font issue.

In the end, I found that my workstation started doing the exact same thing right after I installed the fonts locally (c:\windows\fonts\) so I uninstalled the fonts locally and the issue went away. When I uninstalled on the production machine (Windows Server 2012 R2), the issue also resolved itself there.

My pages are using .woff (built from the same .ttf files that were installed using the same name) included through CSS. It didn't matter if the declaration was made on the page in the critical rendering path or if it was a linked CSS file. It also didn't matter if I used externally hosted files or local to my site (I tested all this in the hopes something would resolve the issue).

I'm going to test further to see if I can name the local fonts differently without an issue but I can't imagine why this would create a problem. If anything, I'd think that having the fonts installed locally should be better and if such a thing is problematic, why isn't it for default fonts like Arial?

If I can provide any more info to help, please let me know what.

The following sound EXACTLY like my issue though they're all unresolved so I wonder if it is related or not:

https://code.google.com/p/wkhtmltopdf/issues/detail?id=688

**Comment by ashkulz** [comment]
Can you verify if the output is better with `0.13-alpha` available from the [downloads page](http://wkhtmltopdf.org/downloads.html)?

**Comment by rainabba** [comment]
The following screenshot show the same test code in Chrome 41 dev-m (looks as I'd expect) and a PDF generated with alpha-13.0 (note the highlighted areas). It looks like there has been some improvement from the previous version, but there are still some issues in both Arial and Roboto. I also undid my "rename-font.ttf" trick and reinstalled the Roboto fonts locally and I'm not getting blank pages now so I think the original bug has been resolved in 0.13, but not the kerning one that came up later in this disscussion.

![image](https://cloud.githubusercontent.com/assets/553630/5849543/fd0aebf4-a1a3-11e4-881c-8377166e0abc.png)

**Comment by ashkulz** [comment]
Kerning issue is tracked in #1527, marking this issue closed for 0.13.x
