### ISSUE TITLE
wkhtmltopdf can't access CDN hosted js file

### ISSUE THREAD

**Issue by gregpinero** [wkhtmltopdf/wkhtmltopdf#1634]
wkhtmltopdf can't seem to access this CDN:

<script src="//cdnjs.cloudflare.com/ajax/libs/numeral.js/1.4.5/numeral.min.js"></script>

When I install that library and host it locally it works fine, so I believe it's something about accessing that URL.  (Interestingly I also can't seem to access that URL directly through my browser either.)

I'm on version   wkhtmltopdf 0.12.0 03c001de254b857f08eba80b62d4b6490ffed41d

Here are my messages from wkhtmltopdf:

```
Loading pages (1/6)
Warning: undefined:0 ReferenceError: Can't find variable: numeral 
Warning: Failed to load file:///static/images/gray_logo.png (ignore)
Counting pages (2/6)                                               
Resolving links (4/6)                                                       
Loading headers and footers (5/6)                                           
Printing pages (6/6)
Done                                                                      
Exit with code 1 due to http error: 1302 
```

If it helps here's my code I'm running:

```
<script src="//cdnjs.cloudflare.com/ajax/libs/numeral.js/1.4.5/numeral.min.js"></script>
<script>
$(function() {
$('.data_table:first tbody tr td:nth-child(3)').each(function(i,val){
    $(val).html( numeral(val.innerHTML).format('0,0'));
});
});
</script>
```

**Comment by taqtiqa-mark** [comment]
This still seems to be an [issue](https://github.com/bryanbraun/franklin/issues/2)
