### ISSUE TITLE
incorrect rendering of JPEG images on Windows Server 2008 x64

### ISSUE THREAD

**Issue by ashkulz** [wkhtmltopdf/wkhtmltopdf#1638]
_This was originally reported as #1512 and has been split off from it._

HTML:

``` html
<!DOCTYPE html>
<html>
<body>
<img src="bill_gates_400.jpg"/>
</body>
</html>
```

Image:
![bill_gates_400](https://f.cloud.github.com/assets/6648348/2135960/3817fbca-9308-11e3-8d23-d51ca85f4181.jpg)

This results in a PDF where the image comes out as corrupt or not rendered properly:

![corrupt](https://cloud.githubusercontent.com/assets/854352/2705795/6365ccc8-c484-11e3-846e-b62ac9f221f2.jpg)

This testcase was originally made by @DomusMaximus and affects @boeserwolf and @denu as well.

**Comment by ispir2000** [comment]
Hi friends, 
I m trying 0.13 Alpha and 0.12 for my project.  
there is a problem with images. I created 2 pdf file both of version for same html file. 
you will understand me when see image as attach.
please help me, 

![ekran alintisi](https://cloud.githubusercontent.com/assets/10434011/5644801/4203b450-9670-11e4-9055-7cdcc932e2de.PNG)

I can sent some code samples or more image, too.

thanks,
V.Ispir

**Comment by ashkulz** [comment]
`0.12.2` has been released, which includes changes related to this issue.
