### ISSUE TITLE
--disable-local-file-access is ignored on Windows when using invalid URLs

### ISSUE THREAD

**Issue by mctart** [wkhtmltopdf/wkhtmltopdf#1639]
On Windows, 0.12.1 x64 Dev and Windows 0.11.x x64, the flag --disable-local-file-access  appears to be ignored.  The command line issued was:

C:\Program Files (x86)\wkhtmltopdf\bin>wkhtmltopdf.exe --disable-local-file-access c:\regvercheck.txt c:\temp\blah2.pdf

which produces a file c:\temp\blah2.pdf rather than error or access denied type message.  

My dev machine is Win 7 pro x64 running with admin rights.  Fresh install of wkhtmltopdf 0.12.1 dev.

Excellent application BTW

Thanks

**Comment by ashkulz** [comment]
A release candidate [0.12.2-rc-71e97c1](http://wkhtmltopdf.org/downloads.html#testing) is available, which should fix this issue. Please report back if your issue is not solved with the above build.

**Comment by ashkulz** [comment]
`0.12.2` has been released, which includes changes related to this issue.
