### ISSUE TITLE
large gaps and undesirable page breaking for tables

### ISSUE THREAD

**Issue by tenshon** [wkhtmltopdf/wkhtmltopdf#1640]
After the latest patch to fix blank pages that occur with large nested tables, there are no more blank pages at the start of the document, but in certain scenarios there are large gaps between tables within pages (not always a page break), and even medium sized nested tables (<50% page height) are being put onto the next page.

Could we fix this by only breaking the page if the TD (that will be moved to the next page) contains no nested tables? Isn't this really what we're trying to achieve?

**Comment by repher** [comment]
Just stumbled accross this discussion after having the same issue as most of you (overlapping, line cut in half). After installing ```0.12.2-dev-5dea253``` and adding ```tr { page-break-inside: avoid; }``` everything works for me. Even with an extrem use of ```rowspan="x"``` compinations.

Thanks for your work!

**Comment by hendricius** [comment]
Unfortunately I am having the same issues as @Ognian. The fix @repher mentioned does not work for me.

@ashkulz thanks for the awesome work. I am also not using nested tables. I am just using a default table.

```
  table.table
    thead
      tr
        th.span-1 WID
        th.span-4 Work Item Description
        th.span-2 Unit
        th.span-1 Price
        th.span-1 Quantity
        th.span-1 Discount
        th.span-1 Subtotal
    tbody
      - section.line_items.each do |li|
        tr
          td= li.wid
          td= li.description
          td= li.unit
          td= humanized_money_with_symbol @report.convert_money(li.price)
          td= li.quantity
          td= number_to_percentage li.discount, precision: 2
          td= humanized_money_with_symbol @report.convert_money(li.budget)
        - if li.custom_description.present?
          tr
            td colspan="7"
              .pre-wrap= li.custom_description

```

**Comment by ashkulz** [comment]
@hendricius: Please post actual HTML and CSS so that I can verify it.

**Comment by hendricius** [comment]
@ashkulz sure. Done: https://gist.github.com/hendricius/5a3ebf71318ca7cc52b4

**Comment by ashkulz** [comment]
`0.12.2` has been released, which includes changes related to this issue.

**Comment by Ognian** [comment]
I tried with 0.12.2 but unfortunately it doesn't solve my issues...
Any idea when a 0.13 alpha for OS X will be available, so that I can test with that?
Thanks
Ognian

**Comment by ashkulz** [comment]
`0.13 alpha` won't help you, see the release plan. I'll have to port all these patches to the 0.13 version (which should be done at `0.13 rc`). Your problem is basically that

> when `page-break-inside: avoid` for rows is used, lines within a row may break in between pages

which is a consequence of the way the patch was done -- in [`RenderBlock::layoutRunsAndFloats`](https://github.com/wkhtmltopdf/qt/commit/e5bcc99edbc87c45bb80dc3c8e7360431f090d16#diff-6f2658c9f6a6282a9f960e39e313a132R970) the position of the line is not adjusted if it is a table cell which has pagination -- which causes the break. There's no easy way to avoid it.

Please open up a new issue to track this.

**Comment by richardwan** [comment]
was having the same issue, everything fixes when i add a style `table tr {page-break-inside: avoid}`

**Comment by ghprod** [comment]
Thanks @repher , your solution works for me 

```css
tr { page-break-inside: avoid; }
```

Its nice ..

![image](https://cloud.githubusercontent.com/assets/1922652/12722795/28741758-c939-11e5-9c35-ee2427d6f0ac.png)

Even with `tfoot`

![image](https://cloud.githubusercontent.com/assets/1922652/12722818/44d60578-c939-11e5-8c6b-72a4f492e6df.png)


:+1:

**Comment by montao** [comment]
Your "solutions" don't work in my case. I get both your issues (1) Overlapping table headers (2) Lineabreaks which b0rk the table content. I regret becoming a programmer because of CSS.

**Comment by akhileshsaipangallu** [comment]
I was facing the same issue add after a lot of trial n errors this css solved the issue

tr {
    display: inline-table;
}

**Comment by sekhar548** [comment]
I am also having the same issue .Your following solutions don't work in my case. 

1. tr { page-break-inside: avoid; }
2. tr {display: inline-table;}

My wkhtmltopdf version is 0.12.6

please give me your suggestions if any one having solution
