### ISSUE TITLE
Cannot use local file for --header-html and --footer-html

### ISSUE THREAD

**Issue by xavierzwirtz** [wkhtmltopdf/wkhtmltopdf#1645]
I am attempting to use a local file for the `--header-html` and `--footer-html` arguments, and have not been able to get it to load them, with a number of different paths.

`wkhtmltopdf.exe .\sample.html .\test.pdf --header-html file:///C:/FullPath/header.html --load-error-handling ignore` 
reports the following and does not load the header:

```
Loading pages (1/6)
Warning: Failed loading page http: (ignored)
Counting pages (2/6)
Resolving links (4/6)
Loading headers and footers (5/6)
Printing pages (6/6)
Done
Exit with code 1 due to http error: 1003
```

If instead I remove one of the 3 forward slashes following `file`, changing `file:///` to `file://`, I get the following error:

```
Loading pages (1/6)
Warning: Failed loading page file://c/BirdDog/HTMLToPDF/header.html (ignored)
Warning: Failed loading page http: (ignored)
Counting pages (2/6)
Resolving links (4/6)
Loading headers and footers (5/6)
Warning: Failed loading page file://c/BirdDog/HTMLToPDF/header.html?page=3&section=Section 2&sitepage=1&title=&subsection=&frompage=1&subsubsection=&topage=3&doctitle=PDF Test&sitepages=1&webpage=.\test.pdf&time=12:38:50 PM&date=4/15/2014 (ignored)
Printing pages (6/6)
Done
Exit with code 1 due to http error: 1203
```

This is on a Windows 8 64 bit machine, running wkhtmltopdf 0.12.0 final.

**Comment by webdevilopers** [comment]
Thanks @tszpinda  and @xavierzwirtz for mentioning the missing `<!doctype html>`.
Made my day in https://github.com/KnpLabs/snappy/issues/97#issuecomment-137088664.

**Comment by danemacaulay** [comment]
:+1:  for `<!doctype html>`!

**Comment by lagunawebdesign** [comment]
+1: for <!doctype html>!

**Comment by webgio** [comment]
I have a different problem. But I guess it can be related. All works ok as long as I don't add a png image in the header html. If I do, the footer is printed but the page number and page total are no longer there. If I put an absolute URL for the image then it's ok again.

**Comment by sanit1001** [comment]
Hi,
I am facing a strange issue while generating a pdf from html,
My project is using wkhtmltopdf utility to convert html to pdf successfully in the past. I have a new requirement where i need to include page no at footer of every page for which i have created html file containing java script that read the page parameter and display page no at footer(Html attached).
The problem I am facing is with deployment, I am hosting this application on iis, works fine for any arbitrary location but my application is for some reasons deploy under program files in c:\ drive in windows where it doesn't work.
I am  using asp.net to call the utility exe and pass parameters like:
if (!string.IsNullOrEmpty(document.HeaderUrl))
            {
		paramsBuilder.AppendFormat("--header-html {0} ", document.HeaderUrl);
                paramsBuilder.Append("--margin-top 25 ");
                paramsBuilder.Append("--header-spacing 5 "); 
            }
	if (!string.IsNullOrEmpty(document.FooterUrl))
            {
		paramsBuilder.AppendFormat("--footer-html {0} ", document.FooterUrl);
                paramsBuilder.Append("--margin-bottom 25 ");
                paramsBuilder.Append("--footer-spacing 5 ");               
            }
 to utility. Earlier when we were not using footer html everything works but the issue start appearing once it has footer html url. please note the footer html path is absolute and I have tried with giving everyone permission also on the application root level folder. if I host application outside programe file everything works smoothly.

![image](https://cloud.githubusercontent.com/assets/19711573/15748801/d32753da-28fd-11e6-8597-46feb4816f83.png)

**Comment by alusev** [comment]
worked for me with an option 
`--enable-local-file-access`

**Comment by mprandot** [comment]
I have same issue here with <!doctype html>:

```error
The process "/usr/local/bin/wkhtmltox/bin/wkhtmltopdf --lowquality --footer-html 'http://localhost:8000/footer' --header-html 'http://localhost:8000/header' '/tmp/knp_snappy58236be828af44.40909377.html' '/tmp/knp_snappy58236be828b7a0.69395813.pdf'" exceeded the timeout of 60 seconds.
```
Header : 
```html
<!DOCTYPE html>
<html>
<head>
<title>test</title>
</head>
<body>
    <header>
        <h3>Header</h3>
    </header>
</body>
       
</html>
```

Footer:
```html
<!DOCTYPE html>
<html>
<head>
<title>test</title>
</head>
<body>
    <header>
        <h3>footer</h3>
    </header>
</body>
       
</html>
```

**Comment by easterism** [comment]
Just make sure your file (header or footer) has an extention, such as .html

**Comment by hekep** [comment]
Hi,

I am stuggling with footer-html output

` /linux/abs/path/to/Vendor/wkhtmltopdf/wkhtmltox/bin/wkhtmltopdf /linux/abs/path/to/tmp/printWkHtmltoPdfFromHtml_1509974114.3359.html   	--footer-html /linux/abs/path/to/webroot/tmp/printWkHtmltoPdfFromHtml_1509974114.3377_footer.html   --header-right "[page]/[toPage]"   --encoding UTF8  /linux/abs/path/to/tmp/printWkHtmlToPdf_1509974114.3397.pdf`

The command works, but it procuses empty page.

wkhtmltopdf 0.12.4 (with patched qt)

**Comment by hekep** [comment]
> I am stuggling with footer-html output

> The command works, but it produces empty page.

I figured out that /linux/abs/path/to/webroot/tmp/printWkHtmltoPdfFromHtml_1509974114.3377_footer.html -file was missing <!DOCTYPE html>  and  <footer></footer> -tags 

So it is essential to have those.

**Comment by hekep** [comment]
Another bug:

`  --header-right "[page]/[toPage]" `  stopped working, when I add 	`--footer-html  source_file.html` . Is there something we can do about it?

**Comment by mprandot** [comment]
The best way i've find:

$snappy->setOption('header-html', view('view.path')->render());

**Comment by TarasHots** [comment]
I know this is kind of old topic, but I stuck on this for several days. I was receiving really strange error like:
`Exit with code 1 due to network error: HostNotFoundError` in combination with `QSslSocket: cannot resolve SSLv3_server_method` and `Error: Failed loading page http:/css">`. So I will describe every one error and the reason I found in my case:

- `Exit with code 1 due to network error: HostNotFoundError` - check are your files that you want to include inside of your html/headers/footers/scrits have known and accessible host.

- `QSslSocket: cannot resolve SSLv3_server_method`  on my Debian I just installed `libssl1.0-dev`

- `Error: Failed loading page http:/css">` the weirdest and trickiest: my html file wasn't saved as a file, and was starting from <style="text/css">...... Adding `<html>` or `<!DOCTYPE html>` didn't helped me. 

`# wkhtmltopdf -V`
`wkhtmltopdf 0.12.4 (with patched qt)`

**Comment by ashkulz** [comment]
can you try with 0.12.5?

**Comment by tomfbenevides** [comment]
Someone can help me? I got some errors with headers and footers.

In **0.12.5** version, I run the command `wkhtmltopdf --header-html header.html example.html example.pdf` and got only blank pages.

header.html
```html
<html>
  <body style="background-color: red;color:white">
    <b>Header</b>
  </body>
</html>
```

example.html
```html
<html>
   <body>
      Test: Random text
   </body>
</html>
```

**Comment by mortb** [comment]
@tomfbenevides late reply, <!DOCTYPE html> is needed in beginning of header html
document

**Comment by tomfbenevides** [comment]
Yeah, right! =) .. thnx @mortb
