### ISSUE TITLE
-webkit-filter: sepia(100%); and -webkit-filter: greyscale(100%); not rendering when generating an image

### ISSUE THREAD

**Issue by arslan344** [wkhtmltopdf/wkhtmltopdf#1650]
I have created a simple html file with an image tag, and set an inline style. Both of these webkit filters don't seem to be working when generating an image -webkit-filter: sepia(100%); or -webkit-filter: greyscale(100%);

I have attached my html file and my sample output image.
![untitled](https://cloud.githubusercontent.com/assets/7318798/2724201/4326c3b6-c59e-11e3-9bab-f65a2684b817.JPG)
![sample](https://cloud.githubusercontent.com/assets/7318798/2724206/4962c824-c59e-11e3-9a50-7e5b844cada0.png)

My Expected output is this
![untitled](https://cloud.githubusercontent.com/assets/7318798/2724231/9fbed122-c59e-11e3-99ef-91907623187f.JPG)

**Comment by bmw748** [comment]
Hey ashkulz.
I hope to make blur effected image.
but this css doesn't work on PDF after using this wkhtmltopdf.
    -webkit-filter: blur(20px);
    -ms-filter: blur(20px);
    -moz-filter: blur(20px);
    filter: blur(20px);
Please tell me the solution.
Thanks.
