### ISSUE TITLE
WKhtmltopdf not working in Raspberry PI

### ISSUE THREAD

**Issue by ianmen** [wkhtmltopdf/wkhtmltopdf#1657]
After running the command sudo wkhtmltopdf http://google.com google.pdf
On my Raspberry PI I get the following error messages:

/usr/local/bin/wkhtmltopdf: 1: /usr/local/bin/wkhtmltopdf: ?~: not found
/usr/local/bin/wkhtmltopdf: 1: /usr/local/bin/wkhtmltopdf: cannot create ?@????@/0??I8
ik?O@?ݦ??O??w?[?@
`?n??@9???u{go???W?/?0/???o?C}?i?PAi????@k?: Directory nonexistent
/usr/local/bin/wkhtmltopdf: 1: /usr/local/bin/wkhtmltopdf: ELF: not found
/usr/local/bin/wkhtmltopdf: 3: /usr/local/bin/wkhtmltopdf: Syntax error: word unexpected (expecting ")")

Does this have to do with the architecture difference ?

Bob.

**Comment by gdunghi** [comment]
how can make it work ? please help me

**Comment by tnawut** [comment]
I'm try to compile on Pi3.
