### ISSUE TITLE
Having problems with libXrender.so.1

### ISSUE THREAD

**Issue by alisamii** [wkhtmltopdf/wkhtmltopdf#1665]
wkhtmltopdf Version 0.12.0
Operating System and Version CENTOS 6.5 x86_64 on cPanel/WHM 11.42.1 (build 12)

Attempting to generate a pdf with wkhtmltopdf version 0.12.*
I've tried to reinstall the library, and it doesn't help. I tried using the 32 and 64 bit version of wkhtmltopdf and none of them worked. 

The 32 bit version complained: 
RuntimeException
The exit status code '127' says something went wrong: stderr: "/home/placeneu/sites/clients/gsmn-hr/vendor/h4cc/wkhtmltopdf-i386/bin/wkhtmltopdf-i386: error while loading shared libraries: libXrender.so.1: cannot open shared object file: Error 40 " stdout: "" command: /home/placeneu/sites/clients/gsmn-hr/vendor/h4cc/wkhtmltopdf-i386/bin/wkhtmltopdf-i386 --lowquality --orientation 'landscape' '/tmp/knp_snappy5358840ce52184.09970389.html' '/tmp/knp_snappy5358840ce56478.54163249.pdf'.

The 64 bit one generated status 11 code.
Here's the runtime exception:
The process has been signaled with signal "11". in /home/placeneu/sites/clients/gsmn-hr/vendor/symfony/process/Symfony/Component/Process/Process.php on line 330

Steps to reproduce:

Log in on : http://gsmn-hr.placeneuve.net/
user: ce142801
pass: 142801ce

Go to http://gsmn-hr.placeneuve.net/evaluations/evaluation/31/download

We have installed wkhtmltopdf both using composer to install the latest 64bit and 32 bit versions as well as download binaries for the same (for centos5, as there do not appear to be any centos6 binaries available).

The composer install installs the latest version.

There are more up to date versions available for wkhtmltopdf but they require a newer version of glibc than that which is installed (installed version appears to be 2.12). According to the following page : http://wkhtmltopdf.org/downloads.html it says that in order to install Linux (Debian Wheezy)  32-bit   64-bit   for recent distributions (i.e. glibc 2.13 or later) is required.

I have a different server which is cPanel as well (hostgator is the hosting provider). That installation has cPanel/WHM version: CENTOS 5.10 x86_64 virtuozzo – tri WHM 11.42.1 (build 12)

wkhtmltopdf works on the CentOS 5.1 x86_64 without a problem.

Please advise.

**Comment by gianfrasoft** [comment]
@iEnrico did you solve this problem?
