### ISSUE TITLE
float: right, deform my text

### ISSUE THREAD

**Issue by sanchobouillant** [wkhtmltopdf/wkhtmltopdf#1666]
Hi,

I want to fill a pdf with a html form. I want the contact adress on the right of the document.

In HTML it work, but when i use wkhtmltopdf it "break" my text.

Example code:

```
<html>
<head></head>
<body>
  <div style="float:right">Example with 5 words</div>
</body>
</html>
```

It generate a pdf like the example jpg
![test](https://cloud.githubusercontent.com/assets/5731199/2791413/8a3b8bdc-cbc6-11e3-8551-d47373f2b5a5.jpg)

how can i avoid to have the text on 2 lines ?

**Comment by MaximilianoFelice** [comment]
I am too experiencing the same issue on 0.12.2.4 Ubuntu Trusty 64-bit. Any known workarounds for this?
