### ISSUE TITLE
--user-style-sheet does not work on Windows

### ISSUE THREAD

**Issue by veptune** [wkhtmltopdf/wkhtmltopdf#1686]
Hello,

I double check, my CSS is OK, i just try to do a display-none; on a div which as no other css code related.

But it seems that the CSS file is ignored.

Here is the whole command line i use :

wkhtmltopdf.exe -L 0 -R 0 --viewport-size 1366x768 --user-style-sheet http://www.qcsasia.com/style-pdf.css http://www.qcsasia.com/product/square-zamac-rubber-loop-keychain-zss/  d.pdf

And the content of my style-pdf.css :
# slider-pdf

{
    display:none !important;
}

Any idea ?

Thanks

**Comment by khan789** [comment]
Hi , Can someone help , how could I pass multiple css files. 

Using user style sheet, I assume it takes only one parameter. Is there a way to pass array of style sheet paths?

--user-style-sheet "file:///C:/style-pdf.css"

cheers,
Irfan

**Comment by shenyanxi** [comment]
我也遇到了这个问题，但是按照你们上面说的还是没起作用
