### ISSUE TITLE
Font size arnormaly too big with Linux version

### ISSUE THREAD

**Issue by veptune** [wkhtmltopdf/wkhtmltopdf#1687]
Hello all,

When i run :
wkhtmltopdf.exe -L 0 -R 0 --viewport-size 1366x768 http://www.qcsasia.com/product/square-zamac-rubber-loop-keychain-zss/  c.pdf

Under windows, everything is perfect

But if i run the same command under linux, font size is anormaly too big

I think this is a big issue, as all pdf generated with the linux version are messed up just because of the wrong font size.

I heard --dpi has effect on X11 based systems but i want to run wkhtmltopdf on my server, where there is no X11. Is there a work around in this case ?

Any idea ?

Thaknks again

**Comment by KKSzymanowski** [comment]
I was experiencing this behaviour when I developed on Windows and the production app ran on Ubuntu.
On Windows font sizes were normal, but on Ubuntu they were too big.

To solve this I switched from `woff` fonts to `ttf` and updated `wkhtmltopdf` from `0.12.3` to `0.12.4`. Now it looks almost exactly the same in both environments.

**Comment by rodolfotr** [comment]
Hi, I had an overlapping text problem in certain fonts **and i solved it with converting the original font to another type.**

![Overlap](https://user-images.githubusercontent.com/17615874/59769943-7f8c9e00-927d-11e9-94fe-b8de3b625006.png)

The font with problem was '.otf'. To solve that problem i had to convert the font to others extension. The one which did it was '.svg'. The problem didn't occur in other fonts '.otf' when converting.
The '159' value had the font with problem. The ',67' value had another one.
I just converted the one with problem.

![noOverlap](https://user-images.githubusercontent.com/17615874/59770168-eca03380-927d-11e9-9e42-75a42a983062.png)
