### ISSUE TITLE
Table with fixed header and rowspan

### ISSUE THREAD

**Issue by jeyvi** [wkhtmltopdf/wkhtmltopdf#1688]
Hello,

When I export a table with rowspans, the text stands middle of the cell above the table header.
And the line in column with rowspan drawn on, but the table is already divided.

Used 0.12.1, Windows x64

![bug](https://cloud.githubusercontent.com/assets/7487294/2876961/9644c9e8-d440-11e3-97fa-ad97bd01ddc0.png)

**Comment by jluispuc** [comment]
using thead, tfoot { display: table-row-group }, tr, td {
  page-break-inside: avoid !important;
}
It does not work for me with td with rowspan property

You know from a solution? 

In version 0.12.4

**Comment by theinarasu91** [comment]
there is any solution for this issue ?
