### ISSUE TITLE
C-binding with multiple threads

### ISSUE THREAD

**Issue by laszbalo** [wkhtmltopdf/wkhtmltopdf#1711]
Hi,

I am trying to create a Node.js C++ binding for wkhtmltopdf.
This is what I would like to achieve:
1. initialize wkhtmltopdf only once inside main: wkhtmltopdf_init(false);
   I assume that I can achieve some performance gain by reusing one instance of QApplication among worker threads.
2. start a new thread for every conversion task, this way Node's main event loop won't block

My issues are the followings: 
1. after calling wkhtmltopdf_init in main, and starting the thread, it is just idling at 10%. It seems to me that the thread may see QApplication uninitialized or can not see it at all. Was wkhtmltopdf implemented that way that it can only be used in a single thread or am I doing something wrong? (nodejs uses libuv which utilizes phtread on Linux)
2. why is 'out' a global setting instead of an object level one like 'page'? Even if I can run multiple worker threads parallel, I can not see how could I send their results into different files easily.

I know that I can use processes (I am using a node module which exactly does this) instead of threads, however, I found that approach a little slow. I reckon because of IPC and the need to start a new QApplication for every task.

Could you please shed some light on these issues?

With thanks,
Laszlo

**Comment by DylanYoung** [comment]
Was this ever resolved?

**Comment by ashkulz** [comment]
Unfortunately, no :slightly_frowning_face:

**Comment by brytonbeesley** [comment]
My team is using wkhtmltopdf to print invoices in a multi-threaded context and the logo is occasionally missing.  After a week of troubleshooting, the most likely explanation is that when this happens the logo asset was locked by another thread that was actively using it.  Has this been resolved in wkhtmltopdf yet?

**Comment by ashkulz** [comment]
Nope, using it in a multi-threaded context is not supported as mentioned earlier.

**Comment by brytonbeesley** [comment]
Thanks for replying, @ashkulz.  I refactored my code to use a multi-process mechanism (instead of multi-threaded), however, the random issue still persists.  Regarding your earlier comment "that multiple Qt event loops are [not] possible in a single process", is the same true in a multi-process context as well?
