### ISSUE TITLE
The footer of the table is being placed in every page and it's getting over the content

### ISSUE THREAD

**Issue by rodrigomf24** [wkhtmltopdf/wkhtmltopdf#1718]
I've tried the margin-bottom option but its not working and the footer-spacing should be supposed to leave a space between the footer and the content and its not doing it.
![screenshot from 2014-05-14 21 44 11](https://cloud.githubusercontent.com/assets/3925338/2980172/31a64c46-dbe3-11e3-95be-c2ce30e61ddd.png)

**Comment by Leprosy** [comment]
the `thead, tfoot { display: table-row-group }` fix solved the issue for me...

**Comment by manish786786** [comment]
tfoot { display: table-row-group } is not working for me. what to do ?

**Comment by asheekakp** [comment]
tr { page-break-inside: avoid }
