### ISSUE TITLE
dependency on libwinpthread-1.dll for the MinGW-w64 build

### ISSUE THREAD

**Issue by SamuelMarks** [wkhtmltopdf/wkhtmltopdf#1723]
You need to build the Windows binaries statically linking this DLL.

Alternatively you can include it from their sourceforge:
1. Go to: http://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win64/Personal%20Builds/mingw-builds/4.9.0/threads-posix/seh/
2. Download and extract: `x86_64-4.9.0-release-posix-seh-rt_v3-rev1.7z`
3. Head to `mingw64\bin` directory
4. Extract the `libwinpthread-1.dll` file 
5. Put said file inside `wkhtmltopdf\bin`; add that to package script, release new installers

Thanks

**Comment by RowelOJT** [comment]
where exactly is the wkhtmltopdf\bin

**Comment by ashkulz** [comment]
@RowelOJT: what do you mean?

**Comment by RowelOJT** [comment]
I cant find the location to put the downloaded file. That is why I'm asking where to find that directory.

**Comment by SamuelMarks** [comment]
@RowelOJT >.<

It's created in the build process
