### ISSUE TITLE
--window-status doesn't work with --header-html

### ISSUE THREAD

**Issue by levent-gal** [wkhtmltopdf/wkhtmltopdf#1725]
--windowstatus and --header-html argumnets are incompatible, the following command doesn't stop.

`wkhtmltopdf.exe --window-status myrandomstring --header-html C:\icCube\ts\head.html http://localhost:63342/test.html test.pdf`

The content of `test.html` is:

``` html
<!DOCTYPE html>
<html style="height: 100%;">
<head>
</head>
<body style="margin:0;height:100%">

<script type="text/javascript">
    setTimeout(function(){
        var div = document.createElement('div');
        div.style.width = '300px';
        div.style.height = '300px';
        div.style.backgroundColor = '#123456';

        document.body.appendChild(div);

        window.status = 'myrandomstring';
    }, 2000);
</script>

</body>
</html>
```

I'm using `Windows 7` and `wkhtmltopdf v 0.12.0 final`

**Comment by ashkulz** [comment]
A release candidate [0.12.2-rc-71e97c1](http://wkhtmltopdf.org/downloads.html#testing) is available, which should fix this issue. Please report back if your issue is not solved with the above build.
