### ISSUE TITLE
Images width max-width/max-height not displayed

### ISSUE THREAD

**Issue by FValetudie** [wkhtmltopdf/wkhtmltopdf#1726]
Hi !
I've been working with wkhtmltopdf for a few weeks now, and I just found a weird, annoying, bug : images that have a max-width and/or max-height in % are not displayed on the generated pdf...

As you can see in the first image, both images are in max-width: 100% and, in the PDF (screenshot), none of them appears. On the other image, screen shot of the second PDF that I created after removing css rules on img, both images are well.

I tried using wkhtmltopdf 0.11-rc1, 0.12 and 0.12.1 on Windows 7 x64.

Is there a quick fix I can apply ? Can we expect an improvement on that issue anytime soon ?

PS : I already sent that on groups.google : https://groups.google.com/forum/#!topic/wkhtmltopdf-general/y0Igyce7x3M
PPS : I saw a similar issue on code.google (https://code.google.com/p/wkhtmltopdf/issues/detail?id=583), but it's 3 years old so I chose to put it there to.

![missing-images](https://cloud.githubusercontent.com/assets/1698035/3028449/26b68402-e02c-11e3-96e1-f3a915bab558.png)
![missing-images-after](https://cloud.githubusercontent.com/assets/1698035/3028450/26bd7316-e02c-11e3-94d9-3ac767743329.png)

**Comment by vgeirnaert** [comment]
I just ran into this problem again with wkhtmltopdf 0.12.3, an image that had max-width: 100%; max-height: 100%; refused to render. Removing these two settings caused it to appear.

**Comment by nbalsamo** [comment]
I'm also seeing this issue. I'm attempting to build a 3x3 grid of images that vary in size., The images are not rendered in the pdf when I use the max-height style. When i remove that style the images are rendered (some will overflow their container as expected without max-height.) I'm using version 0.12.3.2

**Comment by dodlhuat** [comment]
this is still happening in 0.12.4
