### ISSUE TITLE
Support for hyphens:auto

### ISSUE THREAD

**Issue by hertling** [wkhtmltopdf/wkhtmltopdf#1730]
I can't find any documentation about whether hyphens:auto is supported or not in wkhtmltopdf 0.12 release. If it is supported, I can't seem to get it to work, despite ensuring the language is set and hyphenation is specified.

```
<html lang="en" xml:lang="en">
  <head>
    <meta http-equiv="Content-Language" content="en"/>

p {
  text-align:justify;
  hyphens: auto;
  orphans: 2;
  widows: 2;
  text-indent: 0.25in;
}
```

**Comment by JanningSG** [comment]
Webkit supports auto-hyphenation with vendor-prefix:
`-webkit-hyphens: auto;` works fine in current Safari Browsers for Mac and iOS, even for german content. I couldn't find out, which webkit version was the first to support this.

But in wkhtmltopdf this does *not* work! I might temporarily inject hyphenator.js into the documents to be printed, but I'd prefer the CSS to “just work” ;-)

**Comment by ashkulz** [comment]
@JanningSG: you might want to see if the situation is better with the `0.13.x` series.
