### ISSUE TITLE
Different results between 64 & 32 bit Windows (MSVC 2013) 0.12.1-rc

### ISSUE THREAD

**Issue by JamoCA** [wkhtmltopdf/wkhtmltopdf#1749]
After running the 64bit executable, I installed the 32bit on a different PC and discovered that the top margin spacing in the header & footer was different than the result from the 64bit version even though the HTML was exactly the same.  **In fact, the only thing that is rendered different between 64 &32bit are the header/footers.**

```
"c:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe" --header-html header.htm --header-spacing 0 --page-size letter -T 34.925mm -R 0mm -B 28.575mm -L 0mm --disable-smart-shrinking --footer-html footer.htm --footer-spacing 0 body.htm Final64.pdf

"c:\Program Files (x86)\wkhtmltopdf\bin\wkhtmltopdf.exe" --header-html header.htm --header-spacing 0 --page-size letter -T 34.925mm -R 0mm -B 28.575mm -L 0mm --disable-smart-shrinking --footer-html footer.htm --footer-spacing 0 body.htm Final32.pdf
```

The following inline CSS (for a header) renders correctly on 32bit, but it's smaller when generated using 64bit.

```
<img src="./image.png" style="height:0.75in;" alt="">
```

On 32bit, I haven't been successful at adding an space (using a div w/CSS or a transparent GIF) before an image so that it can be centered in the header section.  (It displays correctly when using 64bit.)

I noticed that the user agents are different, so I'm going to attempt to use it to generate different HTML/CSS.  Is this standardized or will this change?  (I'd think that the 32bit would indicate 32bit instead of 64bit.)

**64bit:** Mozilla/5.0 (Windows NT 6.2; Win64; x64) AppleWebKit/534.34 (KHTML, like Gecko) Qt/4.8.5 Safari/534.34

**32bit:** Mozilla/5.0 (Windows NT 6.2; Win64; x64) AppleWebKit/534.34 (KHTML, like Gecko) wkhtmltopdf Safari/534.34

**Comment by anuradhawick** [comment]
Please do fix this error, we are still getting different results in the version we download from apt-get . Thanks
