### ISSUE TITLE
Linux works, but Windows has problems

### ISSUE THREAD

**Issue by Jerrill** [wkhtmltopdf/wkhtmltopdf#1763]
UPDATED: Clarified files included and description to assist reproducing the issue.

I've uploaded files to reproduce the issue in 0.12.1 Windows MVSC version here: 

https://github.com/Jerrill/files-for-issues/tree/master/wkhtmltopdf-0.12.1/00

**html.zip** - contains the files that exhibit the issue when input into the tool. 
**CenconReferenceManual.5.1.0.3494 (Linux generated).pdf** - PDF generated on Ubuntu 12.04.4 using 0.12.1
**CenconReferenceManual.5.1.0.3494 (Windows generated).pdf** - PDF generated on Windows 7 using the MSVC build of 0.12.1
**create_pdf_linux** - text file containing command line used to perform Linux build
**create_pdf_windows.bat** - Windows batch file that performs the Windows build

The script and batch file assume that the test folder contain a **bin** folder containing the tool and a **html** folder containing the unzipped **html.zip** file. 

You'll notice the Windows PDF is smaller, but more obviously the background image is missing, etc. I'm still not sure why it works fine under Linux, but not under Windows. I would understand if it were the other way around (casing issues, etc.)

More importantly though is I occasionally get the following error with running the Windows version and the output PDF is corrupted, but not all the time:

```
Loading pages (1/6)
Warning: Received createRequest signal on a disposed ResourceObject's NetworkAccessManager. This migth be an indication of an iframe taking to long to load.
libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
Counting pages (2/6)
Resolving links (4/6)
Loading headers and footers (5/6)
Printing pages (6/6)
Done
Exit with code 1 due to network error: ProtocolUnknownError
```

NOTE: Sometime it's does exit with code 0 and say Done. But not always. I'm not sure if this is related to the differences in the output between Windows and Linux though.

**Comment by Eyewash01** [comment]
This might not be relevant to anyone else, but I was getting this issue too - my situation:

Windows Server 2008
A single input (but resulting in a large number of pages)
A header and footer on each page, referring to a remote URL

The problem was that as WK was making a request to the web server for every header and footer, this resulted in a lot of HTTP request - and on IIS, a limit was set for the maximum connections to a site.  I upped this, and worked fine from them on.
