### ISSUE TITLE
support for chinese character set is missing

### ISSUE THREAD

**Issue by yourNameIsGood** [wkhtmltopdf/wkhtmltopdf#1764]
The page i m about to deal with is encoding of GBK, which is a kind of Chinese charset .
It seems like wkhtmltopdf works in utf-8 or something like that by default. So i get the pdf of something not able to read.
Is there any thing i can do to make this work ?

**Comment by mrpmorris** [comment]
I am still seeing this behaviour in 12.2.1 - I get an empty square when I try to print the Chinese word 圣

**Comment by ashkulz** [comment]
Do you have the necessary font installed?

**Comment by mrpmorris** [comment]
Which font? It appears okay in IE & Chrome

**Comment by ashkulz** [comment]
Read up on "font substitution", I don't know which font actually gets used to render that character.

**Comment by dengzhichao** [comment]
@yourNameIsGood 我看您的例子标点符号没有在行首，请问您是怎么实现的，谢谢，真心困了好久了。

**Comment by dengzhichao** [comment]
@ashkulz 
thx for you do that,is handsome.i ues wkhtmltopdf latest version ,i find  chinese character: "。" in line center ，use google ,i konw is due to the chinese character is hongkong ,please add chinese character。please add Chinese characters not Hongkong or Taiwan
thx!
```

![image](https://cloud.githubusercontent.com/assets/15209805/20216760/59d370d4-a857-11e6-855a-cb470e4edd7c.png)

```

**Comment by yourNameIsGood** [comment]
@dengzhichao 什么标点不在行首？？没看明白

**Comment by dengzhichao** [comment]
@yourNameIsGood 生成pdf后，每行的行首有可能出现标点符号，我们国家是不允许标点符号出现在行首的，您没有碰到在生成pdf的时候标点符号出现在行首这个问题吗？我之前一直被这问题困扰好久，后面升级了这个gem包的版本，解决了，但是出现句号在字的中间位置，而不是在字下方。好悲催，求解！！

**Comment by dengzhichao** [comment]
@yourNameIsGood 
![2016-11-14 17 00 13](https://cloud.githubusercontent.com/assets/15209805/20258754/14e7daaa-aa8c-11e6-9ea5-ffec275bd6f7.png)

**Comment by yourNameIsGood** [comment]
@dengzhichao  sorry  真的没有遇到过； 句号飘在中间的问题，只能找作者问问了；

**Comment by cheeses** [comment]
> @yourNameIsGood 生成pdf后，每行的行首有可能出现标点符号，我们国家是不允许标点符号出现在行首的，您没有碰到在生成pdf的时候标点符号出现在行首这个问题吗？我之前一直被这问题困扰好久，后面升级了这个gem包的版本，解决了，但是出现句号在字的中间位置，而不是在字下方。好悲催，求解！！



> @yourNameIsGood 生成pdf后，每行的行首有可能出现标点符号，我们国家是不允许标点符号出现在行首的，您没有碰到在生成pdf的时候标点符号出现在行首这个问题吗？我之前一直被这问题困扰好久，后面升级了这个gem包的版本，解决了，但是出现句号在字的中间位置，而不是在字下方。好悲催，求解！！

标点符号在行首的问题解决了吗？ 遇到了相同的问题， 求解！期待回复！

**Comment by cheeses** [comment]
> @yourNameIsGood 生成pdf后，每行的行首有可能出现标点符号，我们国家是不允许标点符号出现在行首的，您没有碰到在生成pdf的时候标点符号出现在行首这个问题吗？我之前一直被这问题困扰好久，后面升级了这个gem包的版本，解决了，但是出现句号在字的中间位置，而不是在字下方。好悲催，求解！！

标点符号在行首的问题解决了吗？ 遇到了相同的问题， 求解！期待回复！
