### ISSUE TITLE
Donating money

### ISSUE THREAD

**Issue by elirani** [wkhtmltopdf/wkhtmltopdf#1775]
I'm using it and it's great. How do I donate money ?

Thanks,

Eliran.

**Comment by simplias1** [comment]
I would also like to donate, because you have helped our solution a lot with the recent changes.

**Comment by alloylab** [comment]
@ashkulz we look into this.. Thanks.

**Comment by ashkulz** [comment]
Please see the [project status](https://wkhtmltopdf.org/status.html#summary) -- I'd prefer donations went to QtWebKit instead, to ensure that there is a maintained browser engine for wkhtmltopdf to use.
