### ISSUE TITLE
Margin top problem

### ISSUE THREAD

**Issue by Superdrac** [wkhtmltopdf/wkhtmltopdf#1780]
Hi, I try to convert some html to pdf with wkhtmltopdf but i have an error. Even if i put margin-top at 0 i have a margin at the top on the first page (only on the first page). I tried to add a 
 body {margin:0; padding:0;} but no change.

My html elements doesnt have css.

What is the problem ?

**Comment by ashkulz** [comment]
Duplicate of #1606
