### ISSUE TITLE
Checkbox and Radio button form fields not rendering - also custom svg does not show up

### ISSUE THREAD

**Issue by driswadkar** [wkhtmltopdf/wkhtmltopdf#1784]
Specifying the options for radiobutton  and checkbox svg image files do render the input fields properly. I am using the following command:

wkhtmltopdf.exe  --enable-forms --checkbox-svg checkbox_unchecked.svg --checkbox-checked-svg checkbox_checked.svg --radiobutton-svg checkbox_unchecked.svg --radiobutton-checked-svg checkbox_checked.svg "D:/demo.html" "D:/test.pdf"

the SVG Files are copied in the wkhtmltopdf bin folder.

Using the windows 32 bit version on the Windows 8.1... Installed using 
wkhtmltox-0.12.1-9615f00_msvc2013-win32

``` html
------------------------ HTML File ----------------------------

    <html>
    <body>
    <form>
    <input type="text" width="500px" />
    <br />
    <br />
    <input type="checkbox" name="cb1"/>Option 1
    <input type="checkbox" name="cb1"/>Option 2
    <input type="checkbox" name="cb1"/>Option 3
    <br />
    <br />
    <input type="radio" name="rb1"/>Radio Option 1
    <input type="radio" name="rb1"/>Radio Option 2
    <input type="radio" name="rb1"/>Radio Option 3
    </form> 
    </body>

    </html>

![untitled](https://cloud.githubusercontent.com/assets/7922350/3312886/67827d32-f6da-11e3-8112-7d44346cae6d.png)


```

**Comment by mohdmohsin** [comment]
I am unable to testb checkbox-svg option. kindly find below the command

wkhtmltopdf --checkbox-svg "C:/Users/Documents/WKHTMLToIMAGETesting/nxt-checkbox-checked-ok.svg" C:/Users/Documents/WKHTMLToIMAGETesting/ImageTest.html C:/Users/Documents/WKHTMLToIMAGETesting/ImageTestL.pdf

Please let me know how to run this optional value. While conversion I was getting below details on console.

Loading pages (1/6)
Counting pages (2/6)
Resolving links (4/6)
Loading headers and footers (5/6)
Printing pages (6/6)
link svg_9 hasn't been detected!                             ] Preparing
Done

**Comment by dpjain** [comment]
Thanks @mn4367 
"If you want to create a PDF form all your input elements must have a unique name."
This resolved my issue of editable pdf with null values.
