### ISSUE TITLE
C API - TempFiles seem to be deleted early

### ISSUE THREAD

**Issue by tuespetre** [wkhtmltopdf/wkhtmltopdf#1790]
Reference:

https://github.com/tuespetre/TuesPechkin/issues/23

When using the C API, creating a converter and adding multiple objects with HTML byte data results in only the last object being printed with the others showing up blank. The temp files that wkhtmltopdf creates to store the HTML byte data seem to be deleted early, resulting in an error similar to the following for each of the previous objects:

```Conversion Warning: Failed loading page file:///C:/Users/grayd/AppData/Local/Temp/wktemp-f19b085a-e516-4151-8786-9dc351d4baa7.html (ignored)```

**Comment by ashkulz** [comment]
Please test the changes and let me know if you encounter an issue, as I'm planning to make the `0.12.2` release in the next week.

**Comment by ashkulz** [comment]
A release candidate [0.12.2-rc-71e97c1](http://wkhtmltopdf.org/downloads.html#testing) is available, which should fix this issue. Please report back if your issue is not solved with the above build.

**Comment by tuespetre** [comment]
This one is all kosher and baller and etc., thank you!

**Comment by ashkulz** [comment]
`0.12.2` has been released, which includes changes related to this issue.
