### ISSUE TITLE
CSS background image repeat not resetting position

### ISSUE THREAD

**Issue by pcorey** [wkhtmltopdf/wkhtmltopdf#1799]
I've ran into some issues using repeating background images with wkhtmltopdf (0.9.9).

I created multiple elements (divs) with the same repeating background image, but the images are not vertically repeating as I would expect them to.  The background position is not "resetting" when it reaches a new element. It seems as if the repeating image is layed out across the entire page and then just clipped/blitted onto the elements. Comparing this to other browsers (Chrome/Firefox), this behavior is not correct. It should "reset" the background position for each new element.

Interestingly, this only happen if the image begins to repeat. If the elements are small enough so that no vertically repeat is necessary, the images reset on each new element as expected.

Check out this gist for a minimal working example: https://gist.github.com/pcorey/a6008a111fd03e75fcef

Change the bg-test height to 200px to see how the image resets if there is no repeat.

Build the pdfs normally: wkhtmltopdf bug.html bug.pdf

See attached screenshots:

![bug](https://cloud.githubusercontent.com/assets/3384035/3364686/c45fae70-fb22-11e3-9b85-7ba8fb875ed3.png)

**Comment by getriebesand** [comment]
I have exactly the same issue with background-images if they are repeated. I testet with 0.12.1 and 0.12.2.4

**Comment by getriebesand** [comment]
same with 0.13.0-alpha-7b36694
