### ISSUE TITLE
Exit with code 1 due to network error: ProtocolFailure - HTTP 302 redirects from IIS

### ISSUE THREAD

**Issue by senyahnoj** [wkhtmltopdf/wkhtmltopdf#1807]
Using 0.12.1-rc3 Windows (MSVC 2013) 32-bit.

I am getting the following error and exit code 1 when pointing wkhtmltopdf.exe at a HTTP 302 redirect to another URL which then returns HTTP 200.

The output of the PDF doesn't appear to be affected.

```
wkhtmltopdf.exe http://localhost/redirect.php test.pdf

Loading pages (1/6)
Counting pages (2/6)
Resolving links (4/6)
Loading headers and footers (5/6)
Printing pages (6/6)
Done
Exit with code 1 due to network error: ProtocolFailure
```

I've written the redirect test scripts in PHP:

redirect.php

``` php
<?php
header('location: target.php', true, 302);
```

target.php

``` php
<?php
echo 'Hello Worl... errr... wkhtmltopdf';
```

My webserver on the localhost is IIS which returns the following headers:

```
HTTP/1.1 302 Moved Temporarily
Content-Length: 137
Content-Type: text/html; charset=UTF-8
Location: target.php
Server: Microsoft-IIS/7.5
X-Powered-By: ASP.NET
X-UA-Compatible: IE=Edge
Date: Thu, 26 Jun 2014 09:53:51 GMT
Connection: close
```

However I don't get the error message when I host the same script on Linux/Apache which returns the redirect with the following headers.

```
HTTP/1.1 302 Found
Date: Thu, 26 Jun 2014 09:55:21 GMT
Server: Apache/2.2.22 (Debian)
X-Powered-By: PHP/5.5.12
location: target.php
X-UA-Compatible: IE=Edge
Vary: Accept-Encoding
Connection: close
Content-Type: text/html
```

Could it be that there is some problem in the way that wkhtmltopdf handles redirect headers from IIS?

**Comment by alloylab** [comment]
have you tried this on 0.12.5?

**Comment by alloylab** [comment]
We are closing this out since we haven't heard from you. If you are still having this issue please feel free to re-open it. Thanks.

**Comment by senyahnoj** [comment]
Tried on version 0.12.5 - still an issue
