### ISSUE TITLE
[sitepage] and [sitepages] not working without HTML headers/footers

### ISSUE THREAD

**Issue by gstern** [wkhtmltopdf/wkhtmltopdf#1808]
I am using the 64 bit MSVC build of 0.12.1-rc3 on a windows 7 machine and I find that when I try to use the [sitepage] and [sitepages] variables in my header or footer, they do not replace with the values when I specify them with plain text arguments using the header-text option. 
For example: --header-text="Page [sitepage] / [sitepages]"
The variables do work when they are in an html document that is specified using the header-html and footer-html options.

**Comment by ashkulz** [comment]
`0.12.2` has been released, which includes changes related to this issue.
