### ISSUE TITLE
border-style in svg

### ISSUE THREAD

**Issue by kachkaev** [wkhtmltopdf/wkhtmltopdf#1812]
It seems like dashed and dotted borders render incorrectly during an export to svg. An example:

``` html
<html>
<head>
    <style>
        div {
            display:block;
            border: 1px black;
            margin-bottom: 10px;
        }
    </style>
</head>
<body>
    <div style="border-style: solid">solid</div>
    <div style="border-style: dashed">dashed</div>
    <div style="border-style: dotted">dotted</div>
    <div style="border-style: dashed; opacity: 0.5">dashed + opacity</div>
    <div style="border-style: dotted; opacity: 0.5">dotted + opacity</div>
</body>
</html>
```

`wkhtmltoimage --width 140 test.html test.png` (same result as for `wkhtmltopdf`)
![test](https://cloud.githubusercontent.com/assets/608862/3427951/0d1879e6-003a-11e4-9d79-c271484bb243.png)

`wkhtmltoimage --width 140 test.html test.svg` (zoomed)
![test_zoomed svg](https://cloud.githubusercontent.com/assets/608862/3427967/6c693d4a-003a-11e4-8935-202d2bc98059.png)

Dashed and dotted borders are lost except when the objects are rasterized.

I understand that rasterization is not something `wkhtmltoimage` can control, but it would be nice if it converted bits of non-solid borders into small individual shapes when opacity is 100%. These objects are vector in generated PDFs.

P.S.: Rendering was done on Mac OS 10.9 with wkhtmltopdf 0.12.1.

**Comment by ashkulz** [comment]
Can someone check if this works with `0.13 alpha`, only available for Windows right now?
