### ISSUE TITLE
binaries for 0.12.1 release do not work on Ubuntu 10.04

### ISSUE THREAD

**Issue by pallymore** [wkhtmltopdf/wkhtmltopdf#1817]
Hello,

I just upgrade the binary to 0.12.1 stable but I'm getting broken pipe errors when generating pdf. Tried both ubuntu 64bit binaries but still no luck.

btw I was using 0.12.1rc1 previously and it was working fine. 

has anyone here run into the same issue with the latest stable? 

Thanks,

**Comment by biswajeetparida** [comment]
Is this binary file works ? I just downloaded it and when i am run a link it ask me superuser privilege and other wise permition denied. When i run it with sudo it is throwing error. comand not found.
