### ISSUE TITLE
When setting --no-background white fonts become gray.

### ISSUE THREAD

**Issue by gnovos** [wkhtmltopdf/wkhtmltopdf#1818]
When I turn on off background my white-colored text becomes a kind of light gray.  Here are two screen shots, the _only_ difference is one is run with --no-background and the other is not:

w/background

![screen shot 2014-06-30 at 5 25 18 pm](https://cloud.githubusercontent.com/assets/56965/3437703/5896c9aa-00b6-11e4-83be-ab5fd648b43b.png)

--no-background

![screen shot 2014-06-30 at 5 24 12 pm](https://cloud.githubusercontent.com/assets/56965/3437702/58968292-00b6-11e4-91df-79f81c15ac6a.png)

**Comment by zampa89** [comment]
Same problem here, the grey text becomes almost black. 

Another detail about this issue: the --no-background parameter affects also the text insode of the input boxes

**Comment by alloylab** [comment]
is this still an issue for 0.12.5?

**Comment by alloylab** [comment]
We are closing this out since we haven't heard from you. If you are still having this issue please feel free to re-open it. Thanks.

**Comment by gnovos** [comment]
This is from many years ago.
