### ISSUE TITLE
Google Maps only partially shown in PDF

### ISSUE THREAD

**Issue by safar** [wkhtmltopdf/wkhtmltopdf#1820]
Hi, I'm having an issue with wkhtmltopdf 0.12.1-9615f00 (with patched qt) on Debian 7.5

I'm trying to get a PDF of my test application's home page which has a Google Map object in it. I have tried setting javascript-delay option up to 30 secs but that didn't help with this issue. Any other ideas?

Here's a print screen of generated PDF file opened in document viewer:
![screenshot from 2014-07-01 11 30 22](https://cloud.githubusercontent.com/assets/2071358/3441251/6bf6f578-0102-11e4-96ef-185eae4b0df9.png)

**Comment by worenklein** [comment]
I was never able to overcome this problem with wkhtmltopdf, but phantomjs seems to render the page successfully.

**Comment by ashkulz** [comment]
@worenklein: did you try PhantomJS 2 or 1.9? PhantomJS 2 is roughly corresponding to wkhtmltopdf 0.13 and has an updated browser engine.
