### ISSUE TITLE
Please provide static linked Linux Binaries for amd64 and i386

### ISSUE THREAD

**Issue by h4cc** [wkhtmltopdf/wkhtmltopdf#1822]
With the newest Release 0.12.1, there seem to be no static compiled linux binaries.
Could you please provide them for download?

I need them to make wkhtml binaries installable via PHP's Composer https://github.com/h4cc/wkhtmltopdf-amd64

**Comment by kvz** [comment]
We were keeping stack builds in `/srv/stack/<release-version>/bin/`and have been happy users. It seems though we can't upgrade to newer versions as it relies on dpkg which works globally?

**Comment by ashkulz** [comment]
Well, the `0.12.3` builds are static linux binaries which should work everywhere.

**Comment by kvz** [comment]
Hm,

Sorry, I'm a bit lost.

- https://github.com/wkhtmltopdf/wkhtmltopdf/releases points to sources
- http://download.gna.org/wkhtmltopdf/0.12 has no 0.12.3
- it does have a http://download.gna.org/wkhtmltopdf/0.12/0.12.2.3/ but that only has windows builds
- http://wkhtmltopdf.org/downloads.html mentions 0.12.3 is a preview..

Am I correctly assuming you're suggesting we use a preview build? (honest question, we could do that if you recommend it)

**Comment by ashkulz** [comment]
`0.12.3` has been released a few days ago with static linux binaries.

**Comment by martin-koroudjiev** [comment]
Hi @kvz and @ashkulz sorry for the lame question but where do I find the static versions? My hosting provider doesn't have libX 2.7 or higher. I would love a binary with *all* dependencies statically built. Or any advice on compiling such myself? What options should I provide? Thank you!

**Comment by JeremyNikolic** [comment]
@martin-koroudjiev I would be interested in this information as well, in case you found a way.

**Comment by AKARTHEESWARAN** [comment]
"The exit status code '127' says something went wrong:\nstderr: \"sh: 1: /usr/local/bin/wkhtmltopdf: not found\n\"\nstdout: \"\"\ncommand: /usr/local/bin/wkhtmltopdf --lowquality 'http://ourcodeworld.com' '/tmp/knp_snappy5b162bfc4d0622.24438523.pdf'.",
I have the above mentioned error please some help me
