### ISSUE TITLE
wkhtmltopdf 0.12.1 ignores non-ascii characters in command-line arguments

### ISSUE THREAD

**Issue by harmant** [wkhtmltopdf/wkhtmltopdf#1825]
Linux (Debian 7 x32, Ubuntu 14.04 x64):

wkhtmltopdf https://www.google.com/ Cyrillic_Тест.pdf
As result, Cyrillic_.pdf file created (not Cyrillic_Тест.pdf)

wkhtmltopdf 0.12.0, wkhtmltopdf 0.12.1-c22928d worked correctly with this example

**Comment by ashkulz** [comment]
`0.12.2` has been released, which includes changes related to this issue.
