### ISSUE TITLE
sporadic failures in Windows builds with many HTML files in a single PDF

### ISSUE THREAD

**Issue by Jerrill** [wkhtmltopdf/wkhtmltopdf#1827]
Continuing issue #1763 ...

We've tried the MinGW version of 0.12.1 (release June 26, 2014) and when it succeeds the PDF generated looks great now! Thank you!

However we're still sporadically getting the following:

```
Exit with code 1 due to network error: ProtocolUnknownError
```

Does anyone have a workaround for this sort of scenario?

**Comment by gr22** [comment]
I ended up here facing the same issue in Odoo using wkhtmltopdf 0.12.5. Sometimes I need to print invoices in batch and I ended up with some elements (images) missing on random pages. Using --javascript-delay eventually fixes the issue but this is a delay and not timeout. Meaning I'll have to wait 20sec even for a one page simple pdf. I would say this is rather a workaround than a fix.  Is there a timeout option in wkhtmltopdf?
