### ISSUE TITLE
Page Break issue Version0.12.1

### ISSUE THREAD

**Issue by rakesh-saharan** [wkhtmltopdf/wkhtmltopdf#1834]
Hi I am using wkhtmltopdf version 0.12.1, I am having an HTML with with nested tables inside div. Table has hundreds of  tr lines. now when i am genrating pdf the last line on each page get torned between current page and the next page. Data is show on both the pages like the data has been cutoff to the next page.

I also tried to uset table tr{page0break-inside:avoid !important!}, it doesn't work.

Its very urgent an any body have an Idea:

![pdf](https://cloud.githubusercontent.com/assets/5144266/3491933/4c01261a-05a0-11e4-8504-8c55b88dfb01.png)

Attached is the genrated PDf

**Comment by gmkhussain** [comment]
use this classes for page break :
```
<style type="text/css" media="screen,print">
       /* Page Breaks */

/***Always insert a page break before the element***/
       .pb_before {
           page-break-before: always !important;
       }

/***Always insert a page break after the element***/
       .pb_after {
           page-break-after: always !important;
       }

/***Avoid page break before the element (if possible)***/
       .pb_before_avoid {
           page-break-before: avoid !important;
       }

/***Avoid page break after the element (if possible)***/
       .pb_after_avoid {
           page-break-after: avoid !important;
       }

/* Avoid page break inside the element (if possible) */
       .pbi_avoid {
           page-break-inside: avoid !important;
       }

   </style>
   
```
   
   
   
   
How to write html code see example.
```
<div class="page1 pb_after">
   content 1...
</div>
<div class="page2 pb_before pb_after">
   content 2.... <table>...</table> 
</div>
```

Table rows break... It works :)

**Comment by NimeshJadav** [comment]
> Hi I am using wkhtmltopdf version 0.12.1, I am having an HTML with with nested tables inside div. Table has hundreds of tr lines. now when i am genrating pdf the last line on each page get torned between current page and the next page. Data is show on both the pages like the data has been cutoff to the next page.
> 
> I also tried to uset table tr{page0break-inside:avoid !important!}, it doesn't work.
> 
> Its very urgent an any body have an Idea:

I'm Also getting this issue. Can someone please help me.
Thanks in advance.
