### ISSUE TITLE
font-face unicode-range doesn't work

### ISSUE THREAD

**Issue by yushyuen** [wkhtmltopdf/wkhtmltopdf#1837]
Does wkhtmltopdf suppose unicode-range? It doesn't seems to be working. My example:

<style>
@font-face {
    font-family: 'MyFonts';
    src: local('biaukai'), local("DFKai-SB"), url('fonts/kaiu.ttf') format('truetype');
    unicode-range: U+4E00-9FFF;
}

@font-face {
    font-family: 'ArialN';
    src: local('Arial Narrow');
    unicode-range: U+0000–U+007F;
}

@page {
    size:210mm 297mm;
    margin:10mm;
}
.body {
    font-family: 'MyFonts';
    font-size: 20pt;
}
</style>

</head>
<body class='body'>
中文字 English
<body>
Attached are screenshot of what it looks like on Chrome. 
![screen shot 2014-07-07 at 9 42 38 pm](https://cloud.githubusercontent.com/assets/8082058/3505296/dfca3980-065a-11e4-97d7-f55524225039.png)
And the pdf that doesn't look right (don't worry about the size):
![screen shot 2014-07-07 at 9 47 33 pm](https://cloud.githubusercontent.com/assets/8082058/3505300/06151f2e-065b-11e4-9f3c-ec5265b8648f.png)

**Comment by phalgun** [comment]
@ashkulz Does this problem still exist? I am able to render unicode fonts on my local mac but not on my ubuntu servers.
