### ISSUE TITLE
Make possible the limitation of the number of generated pages

### ISSUE THREAD

**Issue by zouabimourad** [wkhtmltopdf/wkhtmltopdf#1844]
It would be nice to limit the number of generated pages ( preview mode ) with a command line argument.

**Comment by var1ap-WA** [comment]
This functionality will be very useful! Please do it!

**Comment by Sicos1977** [comment]
https://github.com/Sicos1977/ChromeHtmlToPdf/blob/master/ChromeHtmlToPdfConsole/Options.cs
