### ISSUE TITLE
Availability of pre-compiled version for amd64?

### ISSUE THREAD

**Issue by dpfrommer** [wkhtmltopdf/wkhtmltopdf#1850]
Hi,

For the 0.12.0 version, a pre-compiled version (wkhtmltox-linux-amd64_0.12.0-03c001d.tar.xz) was made available.

For 0.12.1 and 0.12.2, will this pre-compiled version be made available in lieu having to compile in a debian/ubuntu environment or download the RPM?

Thanks

**Comment by hedii-mejri** [comment]
qxqxqx
