### ISSUE TITLE
Crash on large number of remote inputs

### ISSUE THREAD

**Issue by mmb** [wkhtmltopdf/wkhtmltopdf#1851]
wkhtmltopdf dumps core when trying to generate a PDF with a lot of remote inputs. This seems to be made worse by using `--header-html` because it causes more requests.

Tested with latest master on 64-bit linux.

Script to reproduce problem:

``` sh
#!/bin/bash

mkdir -p /tmp/wktest

echo -e "<!DOCTYPE html>\n<p>header</p>" > /tmp/wktest/header.html

for i in {1..500}
do
  echo "<p>$i</p>" > /tmp/wktest/$i.html
done

cd /tmp/wktest
python -m SimpleHTTPServer &
pid=$!

wkhtmltopdf \
  http://localhost:8000/{1..500}.html \
  --header-html http://localhost:8000/header.html \
  /tmp/wktest/test.pdf
kill $pid
```

**Comment by fmdl** [comment]
Dear

When you try to generate a big pdf (over 200 pages) with header and footer, you are an error -11. It is a limitation of max handle file per process. (default is 256 for mac). But the wkhtmltopdf open for each page the header and the footer. to change this value : http://stackoverflow.com/questions/16526783/python-subprocess-too-many-open-files

In terminal do : `ulimit -n 10000`
Check : `ulimit -a`
