### ISSUE TITLE
RunTime Exception on HHVM/NGINX not with Apache

### ISSUE THREAD

**Issue by cie101** [wkhtmltopdf/wkhtmltopdf#1853]
I am using the same code to generate the PDF on both web servers one is using NGINX and HHVM and the other is using just Apache, but i run the code in Apache it works fine to generate the PDF. In the HHVM/NGINX i get this error: 

<code>
RuntimeException
The exit status code '1' says something went wrong: stderr: "Loading pages (1/6) [> ] 0% [======> ] 10% [====================> ] 34% Warning: Failed to load http://www.recordsynergy.com/css/bootstrap.css (ignore) [============================================================] 100% Counting pages (2/6) [============================================================] Object 1 of 1 Resolving links (4/6) [============================================================] Object 1 of 1 Loading headers and footers (5/6) Printing pages (6/6) [> ] Preparing [======> ] Page 1 of 9 [=============> ] Page 2 of 9 [===================> ] Page 3 of 9 [==========================> ] Page 4 of 9 [=================================> ] Page 5 of 9 [=======================================> ] Page 6 of 9 [==============================================> ] Page 7 of 9 [====================================================> ] Page 8 of 9 [============================================================] Page 9 of 9 Done Exit with code 1 due to network error: ConnectionRefusedError " stdout: "" command: wkhtmltopdf --lowquality '/tmp/knp_snappy53c1488ed38a85.63159835.html' '/tmp/knp_snappy53c1488ed3a030.04280509.pdf'.
</code>

It also generates a PDF in my /tmp directory which if i download it works fine. I am unsure how to proceed in fixing this.

Specs: 
OS: Ubuntu 14.04 headless server
WKHTMLTOPDF: binary from website 64-bit 0.12.1 for Trusty

Thanks!

**Comment by vincekovacs** [comment]
I got same error. In which host file do you added the domain name?

Now I working on localhost and I already have entry in `/etc/hosts` for localhost:
`127.0.0.1       localhost`

**Comment by eved42** [comment]
@cie101 : what exactly did you do to solve this problem ??
I have the same error, see [here](https://github.com/wkhtmltopdf/wkhtmltopdf/issues/3244).

**Comment by omrqs** [comment]
This error occurs when url are defined as //url... in place of https://url....
Keep the protocol. 
wkhtmltopdf try find double slash as local path...

Solved for me.
