### ISSUE TITLE
blank page or crash with low DPI on Windows

### ISSUE THREAD

**Issue by DeepSilver** [wkhtmltopdf/wkhtmltopdf#1863]
Windows wkhtmltopdf version 0.12.1 creates a pdf with a blank page (or error) with PDI 95 and below

wkhtmltopdf --dpi 95 http://wkhtmltopdf.org/usage/wkhtmltopdf.txt wkhtmltopdf-test.pdf

![wkhtmltopdf](https://cloud.githubusercontent.com/assets/3600848/3611775/0eb68d24-0da0-11e4-8eb6-b7a178a6b12c.png)

![wkhtmltopdf-02](https://cloud.githubusercontent.com/assets/3600848/3611776/15652ebe-0da0-11e4-84e0-b07b2eb3a33c.png)

Running the same command but on google page result in a blank page

wkhtmltopdf --dpi 95 http://google.com wkhtmltopdf-test.pdf

![wkhtmltopdf-04](https://cloud.githubusercontent.com/assets/3600848/3611791/2f83146e-0da0-11e4-8a2a-639563fcc166.png)

http://www.bkkba.com/wkhtmltopdf-test.pdf

**Comment by ashkulz** [comment]
A release candidate [0.12.2-rc-71e97c1](http://wkhtmltopdf.org/downloads.html#testing) is available, which should fix this issue. Please report back if your issue is not solved with the above build.

**Comment by ashkulz** [comment]
`0.12.2` has been released, which includes changes related to this issue.
