### ISSUE TITLE
Failed loading page when there is a number at the end of the file name

### ISSUE THREAD

**Issue by 00AK** [wkhtmltopdf/wkhtmltopdf#1866]
Using wkhtmltopdf_0.9.9-3_amd64.deb on ubuntu 12.04, also confirmed on a more recent ubuntu installation (don't know exactly which one)

Seems to me this is a bug:

user@user:~$ wkhtmltopdf  test.html test.pdf
Loading page (1/2)
Printing pages (2/2)  
Done  
user@user:~$ mv test.html test.html5
user@user:~$ wkhtmltopdf  test.html5 test.pdf
Loading page (1/2)
Error: Failed loading page file:///home/user/test.html5 (sometimes it will work just to ignore this error with --ignore-load-errors)
user@user:~$ ================================================] 100%

**Comment by danielson317** [comment]
I'm surprised at the close mindedness in response to this request. 

I am also having a problem with this limitation on the file extension. For my specific use case I am writing an html file to the temporary files directory then converting it to pdf. Temporary files default to a file extension of .tmp. 

Also file extensions are generally unreliable and can be customized by the user at their whim. Most command line utilities get around this with a `--input-format` option. 

Can we revisit this as a feature request to allow any file extension with the `--input-format` option to notify the engine of the file type.
