### ISSUE TITLE
The servlet response of the image is not as command line image.

### ISSUE THREAD

**Issue by radhakri555** [wkhtmltopdf/wkhtmltopdf#1867]
The servlet generated image contains only the colors not the content.
Below is the image generated using servlet (wkhtmltoimage)
![vpdl 11](https://cloud.githubusercontent.com/assets/8208998/3634808/dd2c6570-0f49-11e4-989f-56c87737639c.png)
## Below is my servlet code:

 Runtime rt = Runtime.getRuntime();
        String url = request.getParameter("url");
        String filename = request.getParameter("filename");
        String type = request.getParameter("type");
        Process p=null;
        if (filename != null) {
            response.addHeader("Content-Disposition", "attachment; filename=\""+filename +"\"");
        }

```
        if(type.equalsIgnoreCase("IMAGE"))
            p = rt.exec(this.getClass().getResource("/wkhtmltoimage.exe").getPath()+ " --quality 100 " + url +" -");
        else if(type.equalsIgnoreCase("PDF"))
            p = rt.exec(this.getClass().getResource("/wkhtmltopdf.exe").getPath() + " " + url +" -");


        IOUtils.copy(p.getInputStream(), response.getOutputStream());

        p.getInputStream().close();

        response.getOutputStream().close();
```

---

The above behavior is a expected one?

Please address my issue. Thanks in Advance

**Comment by ashkulz** [comment]
`0.12.2` has been released, which includes changes related to this issue.
