### ISSUE TITLE
Columns

### ISSUE THREAD

**Issue by jdus** [wkhtmltopdf/wkhtmltopdf#1872]
hello,

the change log states current testing builds are based on qt-4.8. I figure 4.8 contains a more recent version of  qtwebkit, which supports "-webkit-column-count" and friends. however, with 0.12.2-6a13a51 the commands are either ignored or still not supported.

could someone shed some light on this?

greetings,
j

**Comment by EugeneTikhonov** [comment]
It works if you know exactly hot much text you have so you can set height and that is ok. But what if you have too much text to place it on one page hot would you implement columns?

Let's say I have such html document:
<p>
<pre>
1
2
3
...
9999999
</pre>
</p>
In html I can just say "column-count: 3;" and it will set layout like this:
1   7   13
2   8   14
3   9   15
4  10  16
5  11  17
6  12  18
What I expect to see in PDF:
(page1)
1   4  7
2   5  8
3   6  9
(page2)
10  13  16
11  14  17
12  15  18
...
So it just fill it column by column page by page.

But when I try to generate a PDF file with this html it depends in height which I set and it's impossible to split it by pages.
Is it possible to generate PDF document like I described?

**Comment by maciejlew** [comment]
@mn4367 hack works good if content is limited to one page. What to do if I have more content?

**Comment by dangelsaurus** [comment]
@maciejlew Good question, same problem here.  Looks like I have to dynamically set the height.

**Comment by inferiorhumanorgans** [comment]
This has been implemented in blink but not webkit

https://bugs.chromium.org/p/chromium/issues/detail?id=99358
https://bugs.webkit.org/show_bug.cgi?id=122214
https://bugs.webkit.org/show_bug.cgi?id=156300
https://bugs.webkit.org/show_bug.cgi?id=15546

**Comment by christian-forgacs** [comment]
Any solution for more than one page?

**Comment by arjunsuresh** [comment]
As I'm not getting any solution for multi-page PDF with multiple columns, easiest way is to use "Print" button in latest chrome.

**Comment by bryantwells** [comment]
After a couple days searching the net and trying to get a multi-column / multi-page pdf going with Wkhtmltopdf this is what I came up with... works great and I haven't seen the solution around. It requires each column having a set width and height. The columns are cloned, it's contents position are offset to show the next span of text. Repeat until the entirety of the content has been displayed.

https://jsfiddle.net/pa2k6wj5/

HTML
```
<section class="parent">
    <div class="column">
        <div class="content">
            (longform text goes here...)
        </div>
    </div>
</section>
```

CSS
```
.column {
    position: relative;
    width: 3in;
    height: 5in;
    display: inline-block;
    overflow: hidden;
    vertical-align: top;
}
.content {
    width: 3in;
}
```

JS
```
// get elements
var parent = document.querySelector('.parent');
var column = document.querySelector('.column');
var content = document.querySelector('.content');

// calculate height values of column and it's content
var columnHeight = column.offsetHeight;
var contentHeight = content.offsetHeight;

// create an array of offset values
var offsetValues = [];
for (var i = columnHeight; i < contentHeight; i+= columnHeight) {
    offsetValues.push(i);
}

// create a new column for each offset value
offsetValues.forEach( function(offsetValue, i) {

    // init clone and add classes
    var cloneColumn = document.createElement('div');
    var cloneContent = document.createElement('div');
    cloneColumn.classList.add('column');
    cloneContent.classList.add('content');
    
    // populate the DOM
    cloneContent.innerHTML = content.innerHTML;
    cloneColumn.appendChild(cloneContent);
    parent.appendChild(cloneColumn); 
    
    // apply position and offset styles
    cloneContent.style.position = 'relative';
    cloneContent.style.top = '-' + offsetValue + 'px';
});
```

**Comment by adeliton** [comment]
Finally got this working using this jQuery plugin: https://welcome.totheinter.net/columnizer-jquery-plugin/
Cheers.

**Comment by langebangen** [comment]
Hey @adeliton, I am very interested in how you got wkhtmltopdf to work with columnizer jquery plugin. Do you have an example? I can't get it to work.

Thanks!

**Comment by madamadami** [comment]
Dear @adeliton I am interested how you did it as well!

**Comment by adeliton** [comment]
Hello. You can use [Sample 10](https://adamwulf.me/autocolumn/sample10.html).

For example:
1. First create a div that represents a page:
```html
<div id="page_template">

</div>
```
2. Then you can create a header that will repeat in all pages:
```html
<div id="page_template">
    <div class='header'>
        My Header here
    </div>
</div>
```
3. After adding header, you'll need add an empty div with a class. In my example my class is .content. You can even add a footer.
```html
<div id="page_template">
    <div class='header'>
        My header here
    </div>
    <div class='content'></div>
    <div class='footer' style="text-align: center; padding-top: 10px; padding-bottom: 10px">
        My footer here
    </div>
</div>
```
4. Now you have to add your real content in a new div outside #page_template. Just like this:
```html
<div id="page_template">
    <div class='header'>
        My header here
    </div>
    <div class='content'></div>
    <div class='footer' style="text-align: center; padding-top: 10px; padding-bottom: 10px">
        My footer here
    </div>
</div>
<div id="newsletterContent">
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer ultricies aliquam dolor, ut feugiat neque vestibulum id. Aliquam pulvinar feugiat rutrum. Aliquam erat volutpat. Vivamus in maximus orci. Quisque in metus sed purus imperdiet egestas nec nec dolor. Aliquam orci nisi, pellentesque in facilisis ac, ornare sit amet purus. 
</div>
```
5. That is it. In the end, you'll need call the javascript code. Just like this:
```html
<script src="/columnizer/jquery.js"></script>
<script src="/columnizer/jquery.columnizer.js"></script>
```

```js
        $(function() {
            // the height of the content, discluding the header/footer
            var content_height = 1240; /* For a commom A4 page, the height will be something next to this */
            // the beginning page number to show in the footer
            var page = 1;

            function buildNewsletter() {
                if ($('#newsletterContent').contents().length > 0) {
                    // when we need to add a new page, use a jq object for a template
                    // or use a long HTML string, whatever your preference
                    $page = $("#page_template").clone().addClass("page").css("display", "block");

                    // append the page number to the footer
                    $page.find(".footer span").append(page);
                    $("body").append($page);
                    page++;

                    // here is the columnizer magic
                    $('#newsletterContent').columnize({
                        columns: 2,
                        target: ".page:last .content",
                        overflow: {
                            height: content_height,
                            id: "#newsletterContent",
                            doneFunc: function() {
                                buildNewsletter();
                            }
                        }
                    });
                }
            }
            setTimeout(buildNewsletter, 1000);
        });
```
