### ISSUE TITLE
wkhtmltopdf failed to re-init for second time.

### ISSUE THREAD

**Issue by ghost** [wkhtmltopdf/wkhtmltopdf#1890]
1. call wkhtmltopdf_init() 
2. call  wkhtmltopdf_deinit()
3. call wkhtmltopdf_init() again.
4. But it failed to re-init and convert pdf.

Thank you.

**Comment by TroudhuK** [comment]
Hello,

I try to correctly use wkhtmltopdf in a singleton to do several HTML to PDF conversions. v0.12.5.

I tried:

> wkhtmltopdf_init
> wkhtmltopdf_global_settings
> wkhtmltopdf_create_converter
> wkhtmltopdf_set_error_callback
> wkhtmltopdf_set_warning_callback
> wkhtmltopdf_object_settings
> wkhtmltopdf_set_global_setting("out"...)
> wkhtmltopdf_set_object_setting("page"...)
> wkhtmltopdf_set_object_setting
> wkhtmltopdf_add_object
> wkhtmltopdf_convert
> wkhtmltopdf_destroy_converter
> wkhtmltopdf_deinit

Several times => this bug.

> wkhtmltopdf_init
> (
> wkhtmltopdf_global_settings
> wkhtmltopdf_create_converter
> wkhtmltopdf_set_error_callback
> wkhtmltopdf_set_warning_callback
> wkhtmltopdf_object_settings
> wkhtmltopdf_set_global_setting("out"...)
> wkhtmltopdf_set_object_setting("page"...)
> wkhtmltopdf_set_object_setting
> wkhtmltopdf_add_object
> wkhtmltopdf_convert
> wkhtmltopdf_destroy_converter
> ) [several times]
> wkhtmltopdf_deinit

=> The second time, it's blocked at wkhtmltopdf_convert (full charged CPU core).

So what is the good way to perform several conversions, needing to change only source/destination ?
