### ISSUE TITLE
--window-status causes endless loop with --header-html

### ISSUE THREAD

**Issue by tkes** [wkhtmltopdf/wkhtmltopdf#1892]
As soon as `--header-html` and/or `--footer-html` is used together with `--window-status`, no data is returned, the command never stops.

Found the problem/solution by studying the sourcecode...

The html of `--header-html` and/or `--footer-html` also has to set the `window.status` to the same value as main page, e.g. with `<script>window.status = 'myrandomstring';</script>`. Then  `--window-status` feature works as expected.

The problem can be seen in file `multipageloader.cc` in `void ResourceObject::loadFinished()`, it is connected to all resources in `pdfconverter.cc`, including header and footer (`hfLoader`) and compares `(windowStatus != settings.windowStatus)` for all resources, btw. also for toc `--xsl-style-sheet` if used.

Would suggest to use the current `ResourceObject::loadFinished()` for `pageLoader` and a different one without `waitWindowStatus()` check for `measuringHFLoader` `hfLoader` `tocLoader1` and `tocLoader2`.

This also solves https://github.com/wkhtmltopdf/wkhtmltopdf/issues/1725 and an old ticket https://code.google.com/p/wkhtmltopdf/issues/detail?id=938

`wkhtmltopdf 0.12.1, 32-bit for Windows XP/2003 or later`

**Comment by ashkulz** [comment]
A release candidate [0.12.2-rc-71e97c1](http://wkhtmltopdf.org/downloads.html#testing) is available, which should fix this issue. Please report back if your issue is not solved with the above build.

**Comment by ashkulz** [comment]
`0.12.2` has been released, which includes changes related to this issue.
