### ISSUE TITLE
Mimicking wkhtmltoimage rendering

### ISSUE THREAD

**Issue by chmdznr** [wkhtmltopdf/wkhtmltopdf#1895]
How can I mimic wkhtmltoimage rendering of a webpage using wkhtmltopdf command line?
Example case:
target URL: `http://www.reddit.com/r/php`
wkhtmltoimage command: `/usr/local/bin/wkhtmltoimage -f png --disable-smart-width --width 1366 "http://reddit.com/r/php" reddit_t.png`
PNG output result: http://www.mediafire.com/view/xtwgm5h95cvhg4i/reddit_t.png

the closest one I can think of is this wkhtmltopdf command (yup, even I use --dpi and virtual frame buffer):
`xvfb-run -a /usr/local/bin/wkhtmltopdf --dpi 165 --use-xserver --no-outline --no-print-media-type  --enable-plugins  --no-stop-slow-scripts "http://www.reddit.com/r/php" reddit_t2.pdf`
PDF output result: http://www.mediafire.com/view/rrn9a03arp0b014/reddit_t2.pdf

As you can see, the PNG output has minor problem rendering the header text logo while the PDF have more awful rendering results such as the header text log, the "Submit a new link", the "Submit a new text post" and the "subscribe" button.

Testing system:

```
root@debian:~# uname -a
Linux debian 3.2.0-4-amd64 #1 SMP Debian 3.2.60-1+deb7u1 x86_64 GNU/Linux
root@debian:~# /usr/local/bin/wkhtmltopdf --version
wkhtmltopdf 0.12.2-6a13a51 (with patched qt)
root@debian:~# /usr/local/bin/wkhtmltoimage --version
wkhtmltoimage 0.12.2-6a13a51 (with patched qt)
```

**Comment by alloylab** [comment]
have you tried this with the latest version? also why are you running xvfb if you are using the patched qt version?
