### ISSUE TITLE
Cannot set "load.stopSlowScript" object settings

### ISSUE THREAD

**Issue by ghost** [wkhtmltopdf/wkhtmltopdf#1897]
when i set wkhtmltopdf_set_object_setting(os, "load.stopSlowScript", "false");
it is not working and still stop the script.

But, if i use command line wkhtmltopdf --no-stop-slow-scripts, it works well and do not stop the script.

**Comment by alloylab** [comment]
are you having this issue on the latest version?

**Comment by ashkulz** [comment]
It should be `stopSlowScripts`, not `stopSlowScript`.
