### ISSUE TITLE
--header-html and footer-html not getting displayed and drag font-awesome icons with them

### ISSUE THREAD

**Issue by standemchuk** [wkhtmltopdf/wkhtmltopdf#1898]
Hi guys,

Can someone help me out with following issue?

When I run wkhtmltopdf without `--header-html` and `--footer-html` parameters, I get a perfectly valid PDF with font-awesome icons displayed.

But as soon as I add `--header-html` and `--footer-html`:
1. They are not displayed
    \* Header is just an image inside the `<table>` tag. Doctype is specified as well.
    \* Footer is a string with some styling and JS code to get page numbers inside the `<table>` tag. 
2. For some reason, if I enable those two, icons by _font-awesome_ don't show up as well.

I first thought that this is something related to a Node.JS wrapper for wkhtmltopdf but then executed the command from the console and the result was the same.

Please let me know if you need additional info.

wkhtmlktopdf version is: `wkhtmltopdf 0.12.1-79f3688 (with patched qt)`

**Comment by alloylab** [comment]
issue seems to be resolved... if you are still having issues please let us know

**Comment by ameteshov** [comment]
Hi there, I have the same issue with `style` tag - I got blank pdf when include styles in `style` tag.
My html template for footer
```html
<!DOCTYPE html>
<html>
<head>
    <style>
        @import url('https://fonts.googleapis.com/css?family=Roboto+Condensed:400,700');
        body, html {background: #fff; font-size: 15px; font-family: 'Roboto Condensed', Arial, sans-serif;
            padding: 0; margin: 0;
        }
        html {height: 100%;}
        body {height: 100%; padding: 30px; position: relative;}

        h1 {font-size: 4rem; text-align: center; font-weight: normal;}
        h2 {font-size: 2rem; font-weight: normal; margin: 0 0 2rem 0;}

        .poweredby {position: fixed; bottom: 30px; left: 30px; right: 30px; text-align: center; color: #999;}
    </style>
</head>
<body>
    <div class="poweredby">Powered by ...</div>
</body>
</html>
```

When remove --footer-html option it works fine
wkhtmltopdf 0.12.5 (with patched qt)
High Sierra 10.13.5
