### ISSUE TITLE
.deb packages don't conform to Debian package naming guidelines

### ISSUE THREAD

**Issue by amituttam** [wkhtmltopdf/wkhtmltopdf#1905]
For example, the package from wkthmltopdf.org has the name:

wkhtmltox-0.12.1_linux-precise-amd64.deb

This does not confirm to the debian packaging guidelines: See Section 7.3 of https://www.debian.org/doc/manuals/debian-faq/ch-pkg_basics.en.html

This causes problems for dpkg-query and dpkg-deb commands.

The package name should be:

wkhtmltox_0.12.1-linux-precise_amd64.deb

**Comment by ashkulz** [comment]
So, the packages I am building with the `wkhtmltopdf/packaging` repository, preview builds available [here](https://builds.wkhtmltopdf.org/0.12.5-dev/) will be using the proper DEB naming convention.
