### ISSUE TITLE
lib/reflect.hh:149: possible bad while test ?

### ISSUE THREAD

**Issue by dcb314** [wkhtmltopdf/wkhtmltopdf#1906]
../lib/reflect.hh:149:33: warning: logical 'or' of collectively exhaustive tests is always true [-Wlogical-op]

```
    while (name[parmsize] != '\0' || name[parmsize] != '.' || name[parmsize] != '[') ++parmsize;
```

Suggest swap || for &&.

**Comment by ashkulz** [comment]
`0.12.2` has been released, which includes changes related to this issue.
