### ISSUE TITLE
wkhtmltoimage does not honor rotateZ or translate3d or transform-style

### ISSUE THREAD

**Issue by kazimzaidi** [wkhtmltopdf/wkhtmltopdf#1909]
I'm trying to wrap an image around a mug in HTML using CSS3 transforms, and then using wkhtmltoimage to capture an image.

The HTML shows good in browser, but image turns out flattened. It seems 3d transforms failed to work.

Is this known? I'm using:
wkhtmltoimage 0.12.1 (with patched qt)
on Linux 3.13.0-32-generic Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
Ubuntu 14.04 64-bit

**Comment by agsachdev** [comment]
Using This Type Of CSS transform: translate3d(577px, 307px, 0px);
