### ISSUE TITLE
Image truncated during pdf rendering

### ISSUE THREAD

**Issue by caro86** [wkhtmltopdf/wkhtmltopdf#1910]
Hi,

I have an issue with the version 0.12 and later of wkhtmltopdf.

The picture is truncated like this example.
This is my original html with a large picture :
![originalhtml](https://cloud.githubusercontent.com/assets/6873690/3920681/13469b70-23b9-11e4-9b63-4ce847cd3a41.JPG)

And this is the result I obtain with wkhtmltopdf :
![resultpdf](https://cloud.githubusercontent.com/assets/6873690/3920682/136a0b64-23b9-11e4-8d96-769b5e12be0d.JPG)

I don't have this issue with the version 0.11.0-rc1, the picture is correctly integrated to the pdf.

Is there an option that I can use to fix it ? I tried to put a zoom or to change the page format, but it reduces all the document and it looks rather hacky to me.

Thanks !

**Comment by alloylab** [comment]
are you still having this issue with the latest version?
