### ISSUE TITLE
Can't Read Named Pipe

### ISSUE THREAD

**Issue by jonahbron** [wkhtmltopdf/wkhtmltopdf#1913]
I'm trying to pass data to the PDF via a named pipe.  I can create one with `mkfifo test.html`, and then run:

```
wkhtmltopdf test.html test.pdf
```

And wkhtmltopdf will block, as expected.  However, after I write to the pipe, the PDF is generated without the text that I wrote to it.  Is there something different about how wkhtmltopdf reads files?

**Comment by alloylab** [comment]
What version? have you tried this on 0.12.5?

**Comment by jonahbron** [comment]
@alloylab Not sure, I haven't touched this system in ages.  But I know it's running, so I must have figured something out :)
