### ISSUE TITLE
Putting content on top of margins

### ISSUE THREAD

**Issue by jordansinger** [wkhtmltopdf/wkhtmltopdf#1923]
I have ":margin_bottom => 26.98, :margin_top => 26.98" specified to add 128px to the top and bottom of the PDF, the issue is there is a special case where I need to offset the top margin on the first page by setting margin-top: -128px on body. What happens is that the body seems to go underneath the margin which is just a 128px tall white rectangle. Any way that I can put the content on top of the margin?

**Comment by ashkulz** [comment]
Duplicate of #1606
