### ISSUE TITLE
CentOS/RHEL packages do not follow packaging conventions..

### ISSUE THREAD

**Issue by pruiz** [wkhtmltopdf/wkhtmltopdf#1928]
Currently our packages are named like: wkhtmltox-0.12.1_linux-centos5-i386.rpm
However, packaging conventions on rh-derived distros are more like: %{name}-%{version}-%{release}.%{arch}.rpm

Not following such conventions break redistribution of packages when using configuration change management software like puppet, etc. Is there any reason not to follow standard packaging conventions?

**Comment by ashkulz** [comment]
So, the packages I am building with the `wkhtmltopdf/packaging` repository, preview builds available [here](https://builds.wkhtmltopdf.org/0.12.5-dev/) will be using the proper RPM naming convention.
