### ISSUE TITLE
Border with opacity (rgba color) - nested elements opacity problem

### ISSUE THREAD

**Issue by tszturmaj** [wkhtmltopdf/wkhtmltopdf#1932]
I'm using last version of wkhtmltopdf and when I set border style - "border: 1px solid rgba(57, 117, 0, 0.60);" then nested image inherits opacity from parent border opacity! - alpha channel from border color

Cmd command: "whkhtmltopdf.exe --page-width 949px --page-height 592px --dpi 96 --disable-smart-shrinking --margin-bottom 0 --margin-top 0 --margin-left 0 --margin-right 0 http://localhost:43433/ test.pdf"

Take a look at attachments.

html:

![html](https://cloud.githubusercontent.com/assets/8568811/4060471/fad98070-2def-11e4-8e7a-5a77cb11c953.PNG)

pdf:
![pdf](https://cloud.githubusercontent.com/assets/8568811/4060472/fae5379e-2def-11e4-9b60-97c229d472fc.PNG)

**Comment by alloylab** [comment]
What version? have you tried this on 0.12.5?

**Comment by Tomsgu** [comment]
Closing as there is no response. Please re-open this issue if you can add more information like minimal test case with specified version etc.
