### ISSUE TITLE
Incorrect font-family detection

### ISSUE THREAD

**Issue by fon60** [wkhtmltopdf/wkhtmltopdf#1938]
Recently I had problem with font "DejaVu Sans Condensed". On old wkhtmltopdf 0.11rc everything worked fine and on 0.12.1 didn't attach this font to pdf and used "Times New Roman"

CSS [not working]:

```
body { font-family: 'DejaVu Sans Condensed';}
```

When I was looking if I have installed DejaVu on server I noticed that some fonts wkhtmltopdf detects correctly and some not. The difference is that DejaVu's name in font-file is 'DejaVu Sans,DejaVu Sans Condensed'. And I tried other CSS:

```
body { font-family: 'DejaVu Sans,DejaVu Sans Condensed', 'DejaVu Sans Condensed';}
```

That didin't work as well.

I don't know if this is bug of wkhtmltopdf or Qt but I suspect that something doesn't recognize multiple family names in font files.

---
##### Edit

I tested it on Ubuntu 12.04 and 14.04. I do not have Windows to test if there is the same error.

**Comment by alloylab** [comment]
have you tried this on 0.12.5?

**Comment by fon60** [comment]
I'm sorry, but I can't check this anymore. I don't work for the company using this project anymore. Thus I don't have access to it.
