### ISSUE TITLE
absolute urls from a tag 

### ISSUE THREAD

**Issue by hzlajx** [wkhtmltopdf/wkhtmltopdf#1942]
Version wkhtmltopdf 0.12.1 (with patched qt)

I would expect that absolute urls like 
&lt;a href="/my/page.html"/> or &lt;a href="../page.html"/> 
in a web page are translated to 
&lt;a href="http://domain/my/page.html"/> or &lt;a href="http://domain/page.html"/>.
it works as the src from image

**Comment by alloylab** [comment]
have you tried this on 0.12.5?
