### ISSUE TITLE
Setting list settings via C API

### ISSUE THREAD

**Issue by tuespetre** [wkhtmltopdf/wkhtmltopdf#1944]
I've mentally stepped through the source code in reflect.h and reflect.cc to see how I should use it but I'm having some issues. If I call wkhtmltopdf_set_object_setting and try to set "load.cookies.append", I get a response of 1, indicating success. That should mean an element was added. So then, I call the method and try to set "load.cookies[0]" to a comma separated value like "my_cookie_name,mycookievalue" but I get a response of 0, indicating failure.

It seems from the source that the QPair<QString, QString> reflection implementation might be faulty, in that it seemingly returns false unless the length of the splitted value is 0, when it should check that the length is greater than 1 or maybe equal to 2 to support the subsequent lines of code. 

Let me know if I'm doing something wrong. I might also get brave and try to contribute ;)

**Comment by ashkulz** [comment]
Please test the changes and let me know if you encounter an issue, as I'm planning to make the `0.12.2` release in the next week.

**Comment by tuespetre** [comment]
Cool beans; will you have precompiled copies of 0.12.2-rc up on the website today? I see you bumped the version today.

**Comment by ashkulz** [comment]
It may take a day or so, as I will be making some more changes. Note that deployment might be more complicated for you as the CRT is not linked statically (but is handled in installer).

**Comment by ashkulz** [comment]
A release candidate [0.12.2-rc-71e97c1](http://wkhtmltopdf.org/downloads.html#testing) is available, which should fix this issue. Please report back if your issue is not solved with the above build.

**Comment by tuespetre** [comment]
Reporting back to say... thanks for this one too, it's all working well

**Comment by ashkulz** [comment]
Please make a build yourself and see that it works, as I will release 0.12.2 final in a day or two unless more breaking changes are made.

**Comment by tuespetre** [comment]
I see that you've done a lot with the build configuration/process since I last tried to do my own build. I'll see what I can pull together this evening.

**Comment by ashkulz** [comment]
No need, 0.12.2 final will be released in 12 hours or so (builds are happening right now).

**Comment by ashkulz** [comment]
`0.12.2` has been released, which includes changes related to this issue.
