### ISSUE TITLE
@page formatting elements

### ISSUE THREAD

**Issue by jjsarton** [wkhtmltopdf/wkhtmltopdf#1952]
I have wrote a simple html 5 file in order to check the rendering on variious html to pdf converter. There are no tables and no images within the html file.

I have set header line and footer line so that I can control where the elelemt are printed out.
on weasyprint and prince the <h?> and <p> element at the top of the page are printed approx 5 mm below the header line. For wkhtmltopdf there is no space between the header line an the element.
If I set the --header-spacing I can not set a real unit and the line is shifted up. For me it will be more logical to shift the begin of the content area down.

page-break-after: avoid don't work as expected.  I have 2 header (h2 and h3) which have this attribute. The following element (ul) is non breakable and is placed on the next page. I expect that the 2 headers are put also put to the next page. Weasyprint and prince and firefox do this. 

The parameters for the pages  are within the html file s that normally they will not be needed to pass these arguments via the command line. If no special arguments are passed you may put them after scanning the css part to ReflectClass. The same may apply for the text printed on the header or the footer.

**Comment by ashkulz** [comment]
Please reopen the issue with HTML/CSS and screenshots of what you expect.
