### ISSUE TITLE
OS X 32-bit installer has non 32-bit xz

### ISSUE THREAD

**Issue by stevedes77** [wkhtmltopdf/wkhtmltopdf#1955]
wkhtmltopdf 0.12.1
Mac OS X 10.6.8 (32 bit)

Ran the pkg, appears to succeed but binary does not appear in /usr/local/bin
After manually extracting the pkg file and running the postinstall commands one-by-one, running xz gave the error: "./xz: Bad CPU type in executable".

**Comment by ashkulz** [comment]
`0.12.2` has been released, which includes changes related to this issue.
