### ISSUE TITLE
Style: opacity generates segfault in QPainter	

### ISSUE THREAD

**Issue by guikubivan** [wkhtmltopdf/wkhtmltopdf#1959]
Copied from https://code.google.com/p/wkhtmltopdf/issues/detail?id=821. Posting here to see if there any updates... a proposed solution was to use 0.10.0_rc2, but would love to be on latest version if this is fixed.

Reported by p...@intern1.dk, Jan 13, 2012
What steps will reproduce the problem?
1. Running wkhtmltopdf on pages with elements with text content and using opacity as style 

What is the expected output? What do you see instead?

I expect a pdf as result, but it generates a segfault

What version of wkhtmltopdf are you using?
`wkhtmltopdf --version'

  wkhtmltopdf 0.11.0 rc1 - AMD64 version. Using the static version

(If the issue is with wkhtmltoimg please specify the wkhtmltoimage tag)

On what operating system? Debian
Windows version/ Linux distro (uname -a)  5.0.9 (.6.26-2-amd64 #1 SMP Tue Jan 25 05:59:43 UTC 2011 x86_64 GNU/Linux)

Please provide any additional information below.

The following html file consistently crashes wkhtmltopdf:

    <!DOCTYPE html>
    <html>
    <head>
    <title>Test</title>
    </head>
    <body>
      <div style='opacity: .5; '>a</div>
    </body>
    </html>

Commandline used:

/usr/local/wkhtmltopdf-amd64 test.html test.pdf

Output:

Loading pages (1/6)
Counting pages (2/6)                                               
Resolving links (4/6)                                                       
Loading headers and footers (5/6)                                           
Printing pages (6/6)
QPixmap: Cannot create a QPixmap when no GUI is being used===] Page 1 of 1
QPixmap: Cannot create a QPixmap when no GUI is being used
QPainter::begin: Paint device returned engine == 0, type: 2
QPainter::setRenderHint: Painter must be active to set rendering hints
QPainter::translate: Painter not active
QPainter::setPen: Painter not active
QPainter::setBrush: Painter not active
QPainter::setWorldTransform: Painter not active
QPainter::setOpacity: Painter not active
QPainter::setFont: Painter not active
Segmentation fault
Jan 13, 2012

**Comment by tony-cocco** [comment]
Just ran into this same issue ourselves. Running on Linux with the same version as well.

Any progress on this? Or just get the newer version?

**Comment by ashkulz** [comment]
Versions older than 0.12.0 are not supported, so please reopen if this happens with the current stable version.
