### ISSUE TITLE
All text showing up as blocks only. Centos 6.5 Binary

### ISSUE THREAD

**Issue by robp2175** [wkhtmltopdf/wkhtmltopdf#1961]
Downloaded the Centos 6.5 binary and installed it, but whenever I do a conversion the text only shows up as blocks. Any help is appreciated.
![html2pdf](https://cloud.githubusercontent.com/assets/8832179/4334680/38eb3764-3ff2-11e4-9aea-24ad8f20f1c6.jpg)

**Comment by ashkulz** [comment]
`0.12.2` has been released, which includes changes related to this issue.
