### ISSUE TITLE
css3 rotate not workling as expected

### ISSUE THREAD

**Issue by bitconym** [wkhtmltopdf/wkhtmltopdf#1965]
The rotated letters are not displayed like in the html. Tried to convert https://docraptor.com/samples/invoice.html and everything seems fine except the rotated paid label. See image
![rotation_problem](https://cloud.githubusercontent.com/assets/590260/4348388/7b0e8d1a-4189-11e4-89b6-d2453b104b53.jpg)

Also I noticed that the Qt version used now is 4.8, is there a problem with upgrading the whole project to the latest 5.3 version? Maybe this will solve most css3 issues.

I'm on Windows using wkhtmltopdf 0.12.1.1 with patched Qt

**Comment by jrm2k6** [comment]
Any update on this? The workaround doesn't work well. There is a big difference between the html version and the pdf generated.

**Comment by ashkulz** [comment]
Until `0.13` is released (no ETA for it), there is no better solution.

**Comment by perficientsushil** [comment]
Does 0.13 released? as CSS3 workarround is not working properly.
