### ISSUE TITLE
Error: Unable to write to destination

### ISSUE THREAD

**Issue by xlsmile** [wkhtmltopdf/wkhtmltopdf#1966]
Hello!

I'm trying to convert html to pdf on Windows 8.1 Pro. However, I am getting 'Unable to write to destination' Error. Both path to wkhtmltopdf and to the localhost are correct. Screencast attached.
![wk-error](https://cloud.githubusercontent.com/assets/6753355/4350290/d33f03f4-41e1-11e4-93c9-284275f50dfb.jpg)

What's the remedy, please?

Cheers!

**Comment by rach8garg** [comment]
Works by specifying the full output path. 
Cool Tool ...!!! 👍 

http://google.com C:\Personal\google.pdf

**Comment by mohittyagi6677** [comment]
But wkhtmltopdf doesn't create directories . If the output path is "C:\Personal\Directory\file.pdf" and if the "Directory" folder is not present, then it gives the same error: "unable to write to destination".
This could be a issue as we have to take care of this first , and then call wkhtmltopdf

**Comment by cgaete** [comment]
efectivamente hay que especificar la salida al fichero.

**Comment by ningdianxin** [comment]
I am the same. Thank you for solving this problem

**Comment by ningdianxin** [comment]
I'm the same. I've solved it. Thank you

**Comment by darknessproduction** [comment]
I used file:///home/.. which is incorrect for output!
