### ISSUE TITLE
Document only get header and footer on toc, not rest of document 

### ISSUE THREAD

**Issue by ghost** [wkhtmltopdf/wkhtmltopdf#1969]
I use wkhtmltopdf 0.12.1 (with patched qt) with the wickedpdf ruby gem (from master) on OSX 10.9.4. 
For headers and footers it links to a html page using the --footer-html "file:////var/folders/q6/grsgnrs931l4bs_hhtwr3wgr0000gn/T/wicked_footer_pdf20140922-73422-1wosr9a.html" parameter (the equivalent for header). 
The header and footer is rendered fine for the TOC, but not for the rest of the pages. 
I have tried what is suggested on the wickedpdf-site, including <!DOCTYPE html> and playing around with different margins.
Any idea what could be wrong?

Edit: I removed the TOC and the cover, and then it worked fine. If I add either TOC or cover the headers and footers are missing from the main part of the document.

**Comment by alloylab** [comment]
have you tried this on 0.12.5?

**Comment by Tomsgu** [comment]
Closing as there is no feedback from the author.

**Comment by stratoss** [comment]
With latest version 0.12.6 I can confirm the issue still exists.
