### ISSUE TITLE
wkhtmltopdf process sometimes not terminated, error 500 returned

### ISSUE THREAD

**Issue by JayEn84** [wkhtmltopdf/wkhtmltopdf#1977]
Hey out there,

I have trouble setting `wkhtmltopdf` up on my local Windows development machine using Apache, PHP (as FCGI module) and the wrapper `phpwkhtmltopdf`.
I **sometimes** get 500 errors when I try to create PDF files that `wkhtmltopdf` does not seem to be able to process because of its content, e.g. long headers set in `--html-header`, long tables which have to be split on multiple pages, or nested tables.
In those cases, the `wkhtmltopdf.exe` process is loaded, and it is _working_ for maybe one or two seconds, but then it seems to hang(?), because nothing happens until the `FcgidIOTimeout` time limit is hit. During that time, the web server does not process any other requests, so I am not sure if the root of that problem is `wkhtmltopdf` or my server config. However, I do not know how to debug this, since Apache's log files do not help. Here is what's being logged when I run one of these requests:

```
[Fri Sep 26 16:02:06.385259 2014] [fcgid:debug] [pid 4352:tid 364] fcgid_pm_main.c(357): mod_fcgid: gracefully terminated 1 processes
[Fri Sep 26 16:02:12.385602 2014] [fcgid:warn] [pid 4352:tid 364] mod_fcgid: process 2304 graceful kill fail, sending SIGKILL
[Fri Sep 26 16:02:18.387945 2014] [fcgid:info] [pid 4352:tid 364] mod_fcgid: process c:/dev/prog/php/php-cgi.exe(2304) exit(communication error), return code 9
```

Since `wkhtmltopdf` process is a child process of `PHP`, the two processes are killed at the same time.
Does anyone have an idea what I could try to fix this? Any help is gladly appreciated!

**Comment by flynetworks** [comment]
I've the same problem, my process hangs with this output:

Loading pages (1/6)
QFont::setPixelSize: Pixel size <= 0 (0)                     ] 40%
Warning: http://ngapp.ks-dev.huberlan.de/components/angular/angular.js:11593 AngularPHP
[======================================================>     ] 91%

**Comment by sebpat** [comment]
How do i implement this changes on my actual version (wkhtmltopdf 0.12.2.1 on Centos 6.3.)
I have the same problem with large pdf´s

**Comment by alloylab** [comment]
have you tried this on 0.12.5?

**Comment by alloylab** [comment]
We are closing this out since we haven't heard from you. If you are still having this issue please feel free to re-open it. Thanks.

**Comment by sychsych** [comment]
asp classic
shell script

set xShell = CreateObject("WScript.Shell")
strCmd = Server.Mappath("/js") & "\wkhtmltopdf.exe --encoding euc-kr --no-collate --print-media-type " _
   localhost/index.asp " " & Server.Mappath("/html2pdf") _ 

sever hang

localhost -> www.google.com  success
localhost -> 127.0.0.1 hang 
sever dns xxx.xxx.com hang
why
windows cmd 
wkhmtltopdf localhost/index.asp aaa.pdf -> success
ver 0.12.5 & 0.12.4 same problem

**Comment by sychsych** [comment]
classic asp 
com+ aspexec component install
localhost -> success
but slow 8 ~ 9 sec
other site 2~3 sec success
