### ISSUE TITLE
Output is written to stderr instead of stdout

### ISSUE THREAD

**Issue by jorgenfb** [wkhtmltopdf/wkhtmltopdf#1980]
Output not related to errors are written to stderr instead of stdout. This includes progress information like:
Loading pages (1/6),
Counting pages (2/6)

**Comment by pedrofurtado** [comment]
@ashkulz Is it right? Putting log informations (not related to errors) in stderror? It is a bug, right? 👍

**Comment by ashkulz** [comment]
You can control it by `--log-level warn` (default is info, which includes the progress reports).

**Comment by pedrofurtado** [comment]
@ashkulz Thanks for feedback! 👍
