### ISSUE TITLE
Temp PDF files are not removed after execution

### ISSUE THREAD

**Issue by lkm** [wkhtmltopdf/wkhtmltopdf#1981]
Using newest binary (wkhtmltox-0.12.1.1_msvc2013-win64.exe) on Windows 2012 server with params: "--zoom 1.4 --margin-top 0 --disable-javascript --margin-right 0 --margin-bottom 0 --margin-left 0 --quiet - -"

I am sending HTML file through stdin and getting PDF directly with stdout. The temp HTML files are removed, but PDFs remain in C:\Windows\Temp

This presents a problem when using it in production as disk slowly fills up (or quite rapidly in our case).

**Comment by zachtib** [comment]
Has there been any movement on this?

**Comment by ashkulz** [comment]
A preview for the next release [`0.12.3-dev-79ff51e`](http://wkhtmltopdf.org/downloads.html#testing) is available, which should contain the fix for this issue. Please report back if it is not solved with the above version.

*Please note that the above downloads will be removed after the `0.12.3` release*.

**Comment by zachtib** [comment]
Sounds great. Unfortunately, I don't know if I'll have time to get around
to this before release, but I'll try to report back when I do. We have a
workaround in place clearing out the temporary files so I'll probably have
to go in and disable that in order to properly test the fix.

**Comment by ironman1964** [comment]
The latest version 0.12.2.4 still does not remove the temp PDF files from c:/windows/temp
Is the 0.12.3-dev-79ff51e version deleting temp files ??

**Comment by ashkulz** [comment]
@ironman1964: Yep, it should.

**Comment by ashkulz** [comment]
[`0.12.3`](http://wkhtmltopdf.org/downloads.html#stable) has been released, which should contain the fix for this issue. Please report back if it is not solved with the above version.

*Note that the preview downloads mentioned above have been removed*.

**Comment by ironman1964** [comment]
Found it and I can confirm it is working. 
No more temp files !

**Comment by quidproquo** [comment]
Event with latest version wktemp files seem to be created on Linux when using wkhtmltoimage. I'm using the wkhtmltox-0.12.4_linux-generic-amd64.tar.xz version on 3.13.0-53-generic #89-Ubuntu.

**Comment by SynZhang** [comment]
I'm using wkhtmltoimage in wkhtmltox-0.12.4_linux-generic-amd64.tar.xz, and wktemp files still not deleted.

**Comment by robinbetts** [comment]
If anyone is still seeing wktemp files left behind and are using the c bindings, rather than the command line, see pull request #3930

**Comment by 2E0PGS** [comment]
I made a batch script which is called via task scheduler. 

It deletes any files older than 1 day in the `C:\Windows\Temp` folder if their filename begin with `wktemp`:

```
@echo off

FORFILES /p "C:\Windows\Temp" /m "wktemp-*" /d -1 /c "cmd /c if not @isdir==TRUE del @file"
```
