### ISSUE TITLE
Performance issues with complex border-color styles

### ISSUE THREAD

**Issue by nfm** [wkhtmltopdf/wkhtmltopdf#1994]
Had a weird issue where wkhtmltopdf was using up way too much RAM and taking ages to render a relatively simple file. Turns out that using complex `border-color` styles on an element makes things really slow - about 20x slower for me on the simplest reproduction I could put together.

``` html
<!-- ok.html -->
<!DOCTYPE html>
  <html lang='en'>
    <head>
      <meta charset='utf-8'>
      <title>This is fine</title>
    </head>
  <body>
    <hr style='' />
  </body>
</html>
```

``` html
<!-- bad.html -->
<!DOCTYPE html>
  <html lang='en'>
    <head>
      <meta charset='utf-8'>
      <title>Super slow</title>
    </head>
  <body>
    <hr style='border-color: rgba(10,10,0,0.08) transparent rgba(255, 255, 255, 0.6) transparent;' />
  </body>
</html>
```

``` sh
$ wkhtmltopdf --version
wkhtmltopdf 0.12.1 (with patched qt)
$ uname -a
Linux lab 3.13.0-36-generic #63-Ubuntu SMP Wed Sep 3 21:30:07 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
$ time wkhtmltopdf ok.html out.pdf
wkhtmltopdf ok.html out.pdf  0.32s user 0.04s system 64% cpu 0.570 total
$ time wkhtmltopdf bad.html out.pdf
wkhtmltopdf bad.html out.pdf  10.80s user 0.23s system 98% cpu 11.248 total
```

Very weird!

**Comment by nfm** [comment]
@ashkulz I'm not sure that really explains it. A simple rgba value seems to slow wkhtmltopdf down about 20x, from 0.5 seconds to a little over 11 seconds to render the simple HTML file above.

While the article you linked to mentions that rgba values are relatively slow, they look to be an order of magnitude faster than box-shadow and border-radius properties, neither of which seem to have the same affect on wkhtmltopdf. A simple HTML file with a single `<div style='width: 100px; height: 100px; border: 1px solid black; border-radius: 3px;' />` renders as fast as an unstyled div for me, clocking in at around 0.5s.

Also, the article looks to be talking about performance improvements in the tens/hundreds of milliseconds region, which is a few orders of magnitude off explaining the discrepancy I'm seeing with the rgba value.

I think something else must be at play for the rgba example to be taking 11s to render, but I don't know anything about wkhtmltopdf internals. Could there be some color specific handling at play?

**Comment by ashkulz** [comment]
Can you try with 0.13 alpha what time it takes (Windows only builds for now)? I think that one of the code paths taken for headless conversion makes it ultra slow, but not sure if that is the case with Qt5.

**Comment by nfm** [comment]
@ashkulz Sorry for the slow reply, took me a while to sort out access to a Windows box.

It looks like `wkhtmltopdf 0.13.0-alpha-391fd34` 32-bit fixes the problem on Windows 7. The same bad.html file from above took under a second when run through that version of wkhtmltopdf. Unfortunately my cmd.exe-fu isn't good enough to measure the exact time it took to execute the command though! But it's definitely sub-second, rather than 10+ seconds for wkhtmltopdf 0.12.1 on Linux.

Does that mean if I built a Linux binary of the 0.13 alpha you'd expect this issue to be solved?

Thanks!

**Comment by ashkulz** [comment]
The script has not been updated to add support for Linux builds as yet. Additionally, those builds will not be headless and will require running under `xvfb`.

**Comment by javierdechile** [comment]
Other bootstrap feature that increase rendering times are border-radius, I render several panels, and just setting border-radius:0px increased performance from 80 seconds to 25 seconds when rendering. The size of the document went from 1.7Mb to 700Kb. Does anybody knows other css styling tips for faster rendering when using bootstrap?

**Comment by endyourif** [comment]
@javierdechile Thanks for the border-radius tip.  This also saved me.  Also had big performance gains by going to the 0.13 alpha version.

**Comment by ashkulz** [comment]
The link posted above ([Profiling CSS for fun and profit](http://perfectionkills.com/profiling-css-for-fun-and-profit-optimization-notes/)) has a complete analysis of which CSS features cause a lot of slowdown in the rendering.

**Comment by khan789** [comment]
@javierdechile Thank dude. removed all border-radius from bootstrap has increased 30x performance in printing. 
Does any come came up with the solution to fix this issue yet? or anyone one know how to remove exclude border-radius options while printing?

Thank you.

**Comment by Rav23** [comment]
Can someone provide me with a bootstrap file with all border radius removed?
