### ISSUE TITLE
0.12.1 static binary requested

### ISSUE THREAD

**Issue by stivni** [wkhtmltopdf/wkhtmltopdf#1995]
We ship wkhtmltopdf within our application.
In the past we had a static binary, one single file.
With version 0.12.1 we don't have the possibility anymore to download this static binary.

Could it be possible distribute such a version?
Or point out how I can repackage wkhtmltopdf to a static binary?
I've already unpacked the debian package and I tried to use the /usr/local/bin/wkhtmltopdf binary in it, but then I'm missing some dependencies like libjpeg.so.

**Comment by ashkulz** [comment]
A preview for the next release [`0.12.3-dev-79ff51e`](http://wkhtmltopdf.org/downloads.html#testing) is available, which has generic linux binaries with minimal dependencies. Please report back whether it works for you without any issues.

*Please note that the above downloads will be removed after the `0.12.3` release*.
