### ISSUE TITLE
Poodle vulnerability required disabling of SSLv3.   wkhtmltopdf now fails to access secure content

### ISSUE THREAD

**Issue by pkbarbiedoll** [wkhtmltopdf/wkhtmltopdf#1999]
Per title, removed SSLv3 support from my Apache config to address the newly announced Poodle vulnerability on October 15, 2014 (google it).   I restarted Apache and tested that the site works fine in web browsers.

wkhtmltopdf is now failing to generate content over a secure connection.   

CentOS 6.5
Apache 2.2.15
wkhtmltopdf 0.9.6

**Comment by scampcat** [comment]
It's still broken. I'm using the latest OpenSSL for the distro (1.0.1e-42.el6) and can absolutely confirm that without SSLv3, it won't work.  Looks like it tries multiple remote IP's over and over, trying to get one to resolve.  My site uses only TLS, so this is a major issue. We've tried all sorts of things suggested by others, but unless we enable SSLv3, we can't get it to execute correctly.  Please take this seriously. I see in your answers that you don't seem to take this very seriously (ex: it *should not be vulnerable*). Please verify your claims before waiving the issue off. I'm happy to provide any data you need, but please take this more seriously.  Security is important to most of us.

**Comment by OlivierGuilloux** [comment]
Same issue with 
openssl-1.0.1e-30.el6_6.4.x86_64
and 
wkhtmltopdf 0.12.2.1 (with patched qt)

**Comment by alexbowers** [comment]
Same issue here:

```
OpenSSL 1.0.2l  25 May 2017
wkhtmltopdf 0.12.4 (with patched qt)
```

**Comment by rleroi** [comment]
This is still not fixed?...

**Comment by jilenloa** [comment]
I am also facing ssl issues

**Comment by ashkulz** [comment]
If you're facing an issue with the latest version of wkhtmltopdf, please open a new issue.
