### ISSUE TITLE
meta data for author, title, subject, generator / creator / producer

### ISSUE THREAD

**Issue by matzke** [wkhtmltopdf/wkhtmltopdf#2000]
see https://code.google.com/p/wkhtmltopdf/issues/detail?id=1095

**Comment by matrixise** [comment]
ok closed, but what's the solution for this problem ? I think there is no solution ? is it right ?

**Comment by ashkulz** [comment]
Correct, there is no solution unless changes are made upstream in Qt.

**Comment by matzke** [comment]
@ashkulz do you know where i could write a ticket/feature request for that issue?

**Comment by ashkulz** [comment]
On the [Qt issue tracker](https://bugreports.qt.io).

**Comment by matzke** [comment]
ok thanks - there is already a ticket - https://bugreports.qt.io/browse/QTBUG-44451

**Comment by ashkulz** [comment]
It is correct. You might want to watch the issue in Qt to get notified when it gets fixed.

**Comment by garex** [comment]
Vote for the issue in upstream: https://bugreports.qt.io/browse/QTBUG-44451

**Comment by chris-scheurle** [comment]
In case anyone else wants meta data support *without* having to wait for any upstream fixes: I wrote this little script. Yes, it's messy but it works at least for me (`OS X 10.11.6`, on Linux you'd maybe need to install `php` (or rewrite that part)). 😄 
It uses `wkhtmltopdf` to do the conversion to pdf, then `exiftool` to add the meta data, then `qpdf` to relinearize and write protect the file.

`html2pdf.sh`
```bash
#!/bin/bash

# run: . html2pdf.sh input.html output.pdf

if [[ "$#" > 1 ]]; then
	title="$(php -r 'echo html_entity_decode($argv[1], ENT_QUOTES|ENT_HTML5, "UTF-8")."\n";' "$(sed -En -e 's/^.*<title>(.*)<\/title>.*$/\1/p' "${1}")")"
	author="$(php -r 'echo html_entity_decode(rawurldecode($argv[1]), ENT_QUOTES|ENT_HTML5, "UTF-8")."\n";' "$(sed -En -e 's/^.*<link rel="author" href="mailto:([^"]*)".*/\1/p' "${1}")")"
	if [ -z "${author}" ]; then
		author="$(php -r 'echo html_entity_decode($argv[1], ENT_QUOTES|ENT_HTML5, "UTF-8")."\n";' "$(sed -En -e 's/^.*<meta name="author" content="([^"]*)".*/\1/p' "${1}")")"
	fi
	subject="$(php -r 'echo html_entity_decode($argv[1], ENT_QUOTES|ENT_HTML5, "UTF-8")."\n";' "$(sed -En -e 's/^.*<meta name="description" lang="[^"]*" content="([^"]*)".*/\1/p' "${1}")")"
	keywords="$(php -r 'echo implode("|[SEPARATOR]|", preg_split("/\s*,[\s,]*/", html_entity_decode($argv[1], ENT_QUOTES|ENT_HTML5, "UTF-8"), -1, PREG_SPLIT_NO_EMPTY))."\n";' "$(sed -En -e 's/^.*<meta name="keywords" lang="[^"]*" content="([^"]*)".*/\1/p' "${1}")")"
	generator="$(php -r 'echo html_entity_decode($argv[1], ENT_QUOTES|ENT_HTML5, "UTF-8")."\n";' "$(sed -En -e 's/^.*<meta name="generator" lang="[^"]*" content="([^"]*)".*/\1/p' "${1}")")"
	if [[ -z "${generator}" ]]; then
		generator='-'
	fi
	wkhtmltopdf \
		--load-error-handling 'abort' --load-media-error-handling 'abort' \
		--print-media-type --minimum-font-size 1 \
		-B 10mm -L 10mm -R 10mm -T 10mm -O Landscape -s A4 \
		--no-stop-slow-scripts \
		--run-script 'window.setTimeout(function(){window.status = "FOOBAR";}, 1000);' --window-status 'FOOBAR' \
		--title "${title}" "${1}" "${tmp}" \
	&& exiftool \
		-z -P -sep "|[SEPARATOR]|" \
		-XMP:Format="application/pdf" \
		-Title="${title}" \
		-PDF:Subject="${subject}" -XMP:Description="${subject}" \
		-PDF:Author="${author}" -XMP:Creator="${author}" \
		-XMP:Keywords="${keywords//|\[SEPARATOR\]|/, }" -PDF:Keywords="${keywords//|\[SEPARATOR\]|/, }" \
		-XMP:Subject="${keywords//"\""/}" -AppleKeywords="${keywords//|\[SEPARATOR\]|/, }" \
		-XMP:Marked=True \
		-XMP:DocumentID="$([ -f "${2}" ] && exiftool -q -z -P -s3 -XMP:DocumentID "${2}" || exiftool -q -z -P -p 'uuid:$ExifTool:newguid' "${tmp}")" \
		-XMP:InstanceID="uuid:$(exiftool -q -z -P -s3 -ExifTool:newguid "${tmp}")" \
		-PDF:Creator="${generator}" -XMP:CreatorTool="${generator}" \
		-Producer="$(exiftool -q -z -P -p '$PDF:Creator / $PDF:Producer' "${tmp}")" \
		-CreateDate="$([ -f "${2}" ] && exiftool -q -z -P -s3 -PDF:CreateDate "${2}" || exiftool -q -z -P -s3 -PDF:CreateDate "${tmp}")" '-ModifyDate<PDF:CreateDate' '-XMP:MetadataDate<PDF:CreateDate' \
		-overwrite_original_in_place "${tmp}" \
	&& qpdf \
		--suppress-recovery \
		--linearize --stream-data=compress \
		--encrypt "" "$(md5 -q -s "${RANDOM}$(( x=RANDOM, y=RANDOM, x>=y?x-y:y-x ))$(( $(date +%s) % RANDOM ))$(( x=RANDOM, y=RANDOM, x>=y?x-y:y-x ))${RANDOM}")" 128 \
		--accessibility=y --extract=y --print=full --modify=none -- \
		"${tmp}" "${tmp2}"
	if [[ $? -lt 1 ]]; then
		cp -f "${tmp2}" "${2}"
	else
		echo 'Some error occured' 1>&2
	fi
	if [[ -f "${tmp}" ]]; then
		rm -f "${tmp}"
	fi
	if [[ -f "${tmp2}" ]]; then
		rm -f "${tmp2}"
	fi
else
	echo "2 parameters expected, only got $#" 1>&2
fi
```
turns
```html
<!DOCTYPE html>
<html lang="de">
	<head>
		<meta charset="utf-8">
		<title>Some Page</title>
		<meta name="author" content="Foo Bar">
		<link rel="author" href="mailto:Foo%20Bar%20%3cfoo%40bar.com%3e">
		<meta name="description" lang="en" content="Some really nice page">
		<meta name="keywords" lang="en" content="foo,bar,page,pdf,wkhtmltopdf,exiftool,qpdf">
		<meta name="generator" lang="en" content="Brackets">
	</head>
	<body style="font-family:sans-serif; font-size:200%;">
		<h1>Foobar!</h1>
		<p>Lorem… <em>you know the drill.</em></p>
	</body>
</html>
```
into
![screenshot01](https://cloud.githubusercontent.com/assets/6209236/17798585/cd77dace-65d2-11e6-8c6f-69a724531a9f.png)
![screenshot02](https://cloud.githubusercontent.com/assets/6209236/17798600/f41a19a8-65d2-11e6-8265-f01a88d184ff.png)

**Comment by jeacksmcione** [comment]
can you tell me how to run into windows 7?

**Comment by mikeponco** [comment]
helo chris can you tell me it`s work for another web? example wkhtmltopdf.exe http://google.com/ google.pdf? please answer thx

**Comment by chris-scheurle** [comment]
@jeacksmcione commented 2 days ago:
> can you tell me how to run into windows 7?

I'm afraid I can't. But the programs I mentioned also run on windows, so you should at least be able to do each of these steps, manually.

**Comment by chris-scheurle** [comment]
@mikeponco commented:
> helo chris can you tell me it`s work for another web?

No, it does not.

You *could* try to use a tool like `curl` to download the file, first. Or use a headless browser like `phantomjs` to get the meta data.

**Comment by mikeponco** [comment]
owww thanks chris i think wktopdf same with mpdf can create metadata but great tools wktopd:D

**Comment by inetbiz** [comment]
> In case anyone else wants meta data support _without_ having to wait for any upstream fixes: I wrote this little script. Yes, it's messy but it works at least for me (`OS X 10.11.6`, on Linux you'd maybe need to install `php` (or rewrite that part)). 😄
> It uses `wkhtmltopdf` to do the conversion to pdf, then `exiftool` to add the meta data, then `qpdf` to relinearize and write protect the file.
> 
> `html2pdf.sh`
> 
> ```shell
> #!/bin/bash
> 
> # run: . html2pdf.sh input.html output.pdf
> 
> if [[ "$#" > 1 ]]; then
>     title="$(php -r 'echo html_entity_decode($argv[1], ENT_QUOTES|ENT_HTML5, "UTF-8")."\n";' "$(sed -En -e 's/^.*<title>(.*)<\/title>.*$/\1/p' "${1}")")"
>     author="$(php -r 'echo html_entity_decode(rawurldecode($argv[1]), ENT_QUOTES|ENT_HTML5, "UTF-8")."\n";' "$(sed -En -e 's/^.*<link rel="author" href="mailto:([^"]*)".*/\1/p' "${1}")")"
>     if [ -z "${author}" ]; then
>         author="$(php -r 'echo html_entity_decode($argv[1], ENT_QUOTES|ENT_HTML5, "UTF-8")."\n";' "$(sed -En -e 's/^.*<meta name="author" content="([^"]*)".*/\1/p' "${1}")")"
>     fi
>     subject="$(php -r 'echo html_entity_decode($argv[1], ENT_QUOTES|ENT_HTML5, "UTF-8")."\n";' "$(sed -En -e 's/^.*<meta name="description" lang="[^"]*" content="([^"]*)".*/\1/p' "${1}")")"
>     keywords="$(php -r 'echo implode("|[SEPARATOR]|", preg_split("/\s*,[\s,]*/", html_entity_decode($argv[1], ENT_QUOTES|ENT_HTML5, "UTF-8"), -1, PREG_SPLIT_NO_EMPTY))."\n";' "$(sed -En -e 's/^.*<meta name="keywords" lang="[^"]*" content="([^"]*)".*/\1/p' "${1}")")"
>     generator="$(php -r 'echo html_entity_decode($argv[1], ENT_QUOTES|ENT_HTML5, "UTF-8")."\n";' "$(sed -En -e 's/^.*<meta name="generator" lang="[^"]*" content="([^"]*)".*/\1/p' "${1}")")"
>     if [[ -z "${generator}" ]]; then
>         generator='-'
>     fi
>     wkhtmltopdf \
>         --load-error-handling 'abort' --load-media-error-handling 'abort' \
>         --print-media-type --minimum-font-size 1 \
>         -B 10mm -L 10mm -R 10mm -T 10mm -O Landscape -s A4 \
>         --no-stop-slow-scripts \
>         --run-script 'window.setTimeout(function(){window.status = "FOOBAR";}, 1000);' --window-status 'FOOBAR' \
>         --title "${title}" "${1}" "${tmp}" \
>     && exiftool \
>         -z -P -sep "|[SEPARATOR]|" \
>         -XMP:Format="application/pdf" \
>         -Title="${title}" \
>         -PDF:Subject="${subject}" -XMP:Description="${subject}" \
>         -PDF:Author="${author}" -XMP:Creator="${author}" \
>         -XMP:Keywords="${keywords//|\[SEPARATOR\]|/, }" -PDF:Keywords="${keywords//|\[SEPARATOR\]|/, }" \
>         -XMP:Subject="${keywords//"\""/}" -AppleKeywords="${keywords//|\[SEPARATOR\]|/, }" \
>         -XMP:Marked=True \
>         -XMP:DocumentID="$([ -f "${2}" ] && exiftool -q -z -P -s3 -XMP:DocumentID "${2}" || exiftool -q -z -P -p 'uuid:$ExifTool:newguid' "${tmp}")" \
>         -XMP:InstanceID="uuid:$(exiftool -q -z -P -s3 -ExifTool:newguid "${tmp}")" \
>         -PDF:Creator="${generator}" -XMP:CreatorTool="${generator}" \
>         -Producer="$(exiftool -q -z -P -p '$PDF:Creator / $PDF:Producer' "${tmp}")" \
>         -CreateDate="$([ -f "${2}" ] && exiftool -q -z -P -s3 -PDF:CreateDate "${2}" || exiftool -q -z -P -s3 -PDF:CreateDate "${tmp}")" '-ModifyDate<PDF:CreateDate' '-XMP:MetadataDate<PDF:CreateDate' \
>         -overwrite_original_in_place "${tmp}" \
>     && qpdf \
>         --suppress-recovery \
>         --linearize --stream-data=compress \
>         --encrypt "" "$(md5 -q -s "${RANDOM}$(( x=RANDOM, y=RANDOM, x>=y?x-y:y-x ))$(( $(date +%s) % RANDOM ))$(( x=RANDOM, y=RANDOM, x>=y?x-y:y-x ))${RANDOM}")" 128 \
>         --accessibility=y --extract=y --print=full --modify=none -- \
>         "${tmp}" "${tmp2}"
>     if [[ $? -lt 1 ]]; then
>         cp -f "${tmp2}" "${2}"
>     else
>         echo 'Some error occured' 1>&2
>     fi
>     if [[ -f "${tmp}" ]]; then
>         rm -f "${tmp}"
>     fi
>     if [[ -f "${tmp2}" ]]; then
>         rm -f "${tmp2}"
>     fi
> else
>     echo "2 parameters expected, only got $#" 1>&2
> fi
> ```
> 
> turns
> 
> ```
> <!DOCTYPE html>
> <html lang="de">
>     <head>
>         <meta charset="utf-8">
>         <title>Some Page</title>
>         <meta name="author" content="Foo Bar">
>         <link rel="author" href="mailto:Foo%20Bar%20%3cfoo%40bar.com%3e">
>         <meta name="description" lang="en" content="Some really nice page">
>         <meta name="keywords" lang="en" content="foo,bar,page,pdf,wkhtmltopdf,exiftool,qpdf">
>         <meta name="generator" lang="en" content="Brackets">
>     </head>
>     <body style="font-family:sans-serif; font-size:200%;">
>         <h1>Foobar!</h1>
>         <p>Lorem… <em>you know the drill.</em></p>
>     </body>
> </html>
> ```
> 
> into
> ![screenshot01](https://cloud.githubusercontent.com/assets/6209236/17798585/cd77dace-65d2-11e6-8c6f-69a724531a9f.png)
> ![screenshot02](https://cloud.githubusercontent.com/assets/6209236/17798600/f41a19a8-65d2-11e6-8265-f01a88d184ff.png)

@chris-scheurle Could you turn this into a github project and also add licensing and licensing URL?

**Comment by sunnybear** [comment]
at least field /Application (which is filled with wkhtmltopdf 0.12.5) can be changed inside wkhtmltopdf :)
