### ISSUE TITLE
UTF-8 in header/footer (skipping non-ASCII characters)

### ISSUE THREAD

**Issue by rootshell-do** [wkhtmltopdf/wkhtmltopdf#2002]
Hi,
just compile last git version wkhtmltopdf 0.12.2-b2b18ad3 (with patched qt). Compilation was okay, but when I generate page the non-ASCII characters are skipped.

From "página 1" to "pgina 1". Have tried the --utf8 with no luck.

Locale:
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=

**Comment by alnour-altegani** [comment]
same problem here (arabic) characters not showing in the header or footer of the pdf

**Comment by alnour-altegani** [comment]
arabic characters not showing in header and footer . 
i386
ubuntu
➜ locale
LANG=en_US.UTF-8
LANGUAGE=en_US
LC_CTYPE=en_US.UTF-8
LC_NUMERIC=en_US.UTF-8
LC_TIME=en_US.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=en_US.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=en_US.UTF-8
LC_NAME=en_US.UTF-8
LC_ADDRESS=en_US.UTF-8
LC_TELEPHONE=en_US.UTF-8
LC_MEASUREMENT=en_US.UTF-8
LC_IDENTIFICATION=en_US.UTF-8
LC_ALL=

**Comment by ashkulz** [comment]
@alnour-altegani: check that you are using the latest version; if so post the command-line, version you are using and the HTML/CSS.

**Comment by hubertperron** [comment]
I'm having the same problem on Linux CentOS using version "wkhtmltopdf 0.12.2.1 (with patched qt)"

**Comment by ashkulz** [comment]
@hubertperron: without the information requested above, I can't really help you out.

**Comment by l3pp4rd** [comment]
in my case it was a cause by lack of fonts **msttcorefonts** or **adobe-source-han-sans**.

**Comment by rafwell** [comment]
+1 in version 0.12.4 (with patched qt)

**Comment by enwood** [comment]
Four years on from the original issue, and I'm still seeing this problem with version 0.12.3 (with patched qt) operating under Red Hat Enterprise Linux 7.3. 

I can see the accented (UTF-8) footer text ("Issué") being passed in the command line:

```
"***************[\"/apps/webapps/lts/vendor/bundle/ruby/2.2.0/bin/wkhtmltopdf\", \"-q\", 
\"--encoding\", \"UTF-8\", 
\"--margin-top\", \"25\", 
\"--margin-bottom\", \"15\", 
\"--margin-left\", \"0\", 
\"--margin-right\", \"0\", 
\"--header-spacing\", \"6\", 
\"--header-html\", 
\"file:////var/folders/cl/7g4qxvd15jq_fcsvbzwgzxtm0000gn/T/wicked_header_pdf20190110-8066-vu8w2k.html\", 
\"--footer-center\", \"Issued/Issué: 2019-01-10 11:02\\nPage: [page]/[topage]\", 
\"--footer-font-size\", \"8\", 
\"file:////var/folders/cl/7g4qxvd15jq_fcsvbzwgzxtm0000gn/T/wicked_pdf20190110-8066-ef1jne.html\", \"/var/folders/cl/7g4qxvd15jq_fcsvbzwgzxtm0000gn/T/wicked_pdf_generated_file20190110-8066-umsc0g.pdf\"]***************"
```
but the resulting PDF continues to be missing the "é" in "Issué" when it appears in the footer. 

Red Hat Enterprise Linux Server release 7.3 (Maipo)
[apps@vapp02t lts]$ locale
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
