### ISSUE TITLE
PDF -> Form Fields -> VALUE !print

### ISSUE THREAD

**Issue by stickypages** [wkhtmltopdf/wkhtmltopdf#2004]
Not sure the possibility here, but would like to be able make the fields contents printable. I know if I edit the PDF in Acrobat, it says, the field is visible but NOT printable. This would be a huge bonus if we could get that feature..... Possible?

**Comment by ashkulz** [comment]
[`0.12.4`](http://wkhtmltopdf.org/downloads.html#stable) has been released, which should contain the fix for this issue. Please report back if it is not solved with the above version.

**Comment by be-cloud-js** [comment]
Hello,

I did some test and I have the following behavior.

When I open the pdf in Chrome, no problem, the fields are editable and printable, nice.

When I open the pdf in Acrobat Reader though, the fields are not editable anymore.

I am on OS X Acrobat Reader 2015.023.20056

Does anyone have the same ? Any idea how to fix this ?

Best regards,

Jerome

**Comment by ashkulz** [comment]
Which version of wkhtmltopdf did you use?

**Comment by be-cloud-js** [comment]
0.12.4

**Comment by be-cloud-js** [comment]
Any update ? I still have the problem, can you reproduce it ?

**Comment by be-cloud-js** [comment]
Any luck on this ?

**Comment by ashkulz** [comment]
I don't have Acrobat Reader (on Linux), so can't really verify. Looks like your problem is similar to #3025, can we continue discussion there?
