### ISSUE TITLE
HTML Input text controls doesn't print the value in PDF

### ISSUE THREAD

**Issue by amitsofticon** [wkhtmltopdf/wkhtmltopdf#2005]
Hi

I have a problem converting HTML Input controls to PDF. The value excludes when the PDF is generated. Only a blank box is printed. Suppose the following HTML shows like a blanks box in PDF.

Thanks in advance.

**Comment by ashkulz** [comment]
Duplicate of #2004.

**Comment by ashkulz** [comment]
[`0.12.4`](http://wkhtmltopdf.org/downloads.html#stable) has been released, which should contain the fix for this issue. Please report back if it is not solved with the above version.
