### ISSUE TITLE
Non-breaking Hypen rendered as pipe

### ISSUE THREAD

**Issue by jjwillis** [wkhtmltopdf/wkhtmltopdf#2012]
wkhtmltopdf Version: wkhtmltopdf-0.12.1

Operating System and Version: Windows 7 Ultimate (64bit) with SP1

Issue:
When the source documnet contains a non-breaking hypen (`&#8209;`), it is rendered as a pipe.
To reproduce this, create an html document using the following html:
`
<html>C25240&#8209;002</html>
`
Here is what that looks like in a browser:
<html>C25240&#8209;002</html>

Convert to PDF using wkhtmltopdf.
wkhtmltopdf-0.12.1 NonBreaking.html NonBreaking.pdf

**Comment by alloylab** [comment]
have you tried this on 0.12.5?

**Comment by Tomsgu** [comment]
Closing as there is no feedback from the user.
