### ISSUE TITLE
Problems with libpng12.so.0 on CentOS 7

### ISSUE THREAD

**Issue by maurice-does-software** [wkhtmltopdf/wkhtmltopdf#2014]
We just migrated our Rails application from a CentOS 6 server to a new CentOS 7 and installed from the binary at http://downloads.sourceforge.net/project/wkhtmltopdf/0.12.1/wkhtmltox-0.12.1_linux-centos6-amd64.rpm (the same one I had used to install on the CentOS 6 machine ). Our application uses the gem wicked_pdf. Since the server change, attempts to generate a pdf within the app give this error:

Command Error: /usr/local/bin/wkhtmltopdf: error while loading shared libraries: libpng12.so.0: cannot open shared object file: No such file or directory

When running these examples from the documentation

wkhtmltopdf http://www.google.com google.pdf
wkhtmltopdf http://geekz.co.uk/lovesraymond/archive/eler-highlights-2008 eler2.pdf

it works without error.

**Comment by englianhu** [comment]
@maurice-does-software 
```
> pJS <- phantom(paste0(getwd(),'/phantomjs'))
/home/usr/phantomjs: error while loading shared libraries: libpng12.so.0: wrong ELF class: ELFCLASS32
```
