### ISSUE TITLE
Support User Agent for web browsing

### ISSUE THREAD

**Issue by asmanmmsj** [wkhtmltopdf/wkhtmltopdf#2020]
Hi
i have 2 request for add to wkhtml
1- add a parameter for disable save image and just load and complie web request
2-add a parameter for support User Agent in web requests
some website check user agent in web requests
please add a new parameter like  --UserAgent  xxx(URL Encoded string)

xxx: my costume user agent string ...
like this
Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/34.0.1847.137 Safari/537.36

Mozilla/5.0 (Linux; Android 4.2.2; GT-N5100 Build/JDQ39) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/34.0.1847.114 Safari/537.36

Mozilla/5.0 (Windows NT 6.2; ARM; Trident/7.0; Touch; rv:11.0; WPDesktop; NOKIA; Lumia 520) like Gecko

Thanks and Best regards.
ALi

**Comment by mitchellkrogza** [comment]
Brilliant @ashkulz you guys really thought of everything, such a great tool which I use on a daily basis.

**Comment by jplevene** [comment]
Tried 
`--custom-header "User-Agent" "my user agent name" --custom-header-propagation`
but it doesn't seem to work when I query the user agent in JavaScript inside the document.
