### ISSUE TITLE
text cut-off at bottom

### ISSUE THREAD

**Issue by YoSev** [wkhtmltopdf/wkhtmltopdf#2029]
hey there,

i try to create a pdf (A4) from a html file with the following cmd:
```
/usr/sbin/wkhtmltopdf --cookie PHPSESSID thesession --print-media-type  --margin-top 15mm --margin-bottom 15mm --margin-left 15mm --margin-right 15mm --encoding utf8 --footer-right 'Seite [page] von [toPage]' -s A4 --post content 'content' --post WIDTH 'width' --post title 'title' http://source-url file.pdf
```
Somehow, the text is cut off at the bottom line, do i miss a setting or seomthing?

That's how it looks like:
http://s7.bro7.com/view/9d66d0787a34e7342cb74529855d09f5cbc6f372/fb6d1bc5f97f902df2103248b37c4d759974c6ca/1b276f4d13874a6ac73ac262f8a47fe33e595472/direct/bildschirmfoto_-_15:12:39_31.10.2014.png

thanks

**Comment by mtpultz** [comment]
I'm using 0.12.1 and I also get the last line of text on PDF pages cut and distributed between the current and next page using Ubuntu 12.04.5 on production server, this doesn't occur using Windows where the project was being developed.

**Comment by mtpultz** [comment]
Updated to 0.12.2.1 and it no longer occurs

**Comment by john-dev** [comment]
Well, i just upgraded to version 0.12.2-dev (with patched qt) and i still have this problem..

**Comment by john-dev** [comment]
Looks like text floating around images cause problems

**Comment by sgnann** [comment]
I got the same problem with version wkhtmltopdf 0.12.2.1 (with patched qt) on Ubuntu 14.04.1 .
Are there any news?
Any hint will be appreciable!

**Comment by sgnann** [comment]
Maybe i´ll describe a little bit "my" pages.
There is a header and a footer on each page.
The pdf documents exists of more than two pages.
The cut-off problem is always between the first and the second page. All other page breaks are fine.
Hope this information helps a little bit to identify the error?

**Comment by sgnann** [comment]
when i add a style
```
table tr {page-break-inside: avoid}
```
i´ll fix the issue

**Comment by ashwaniare** [comment]
@sgnann you are a life saver!

**Comment by alehro** [comment]
I had this problem for h3 tags. Solved it by css:
h3 {
    -webkit-margin-before: 0;
    -webkit-margin-after: 0;
    padding: 1em 0;
}

**Comment by kamalsamra** [comment]
The cut-off problem occur for every line.

**Comment by kobruleht** [comment]
Similar issue is in https://github.com/wkhtmltopdf/wkhtmltopdf/issues/3141 it occurs in latest alpha version also.

**Comment by chudesno** [comment]
Using --zoom 0.8 flag resolves similar issue for me. The source of such workaround is the fact that we only have cropping occuring on Unix while Windows produces proper PDFs. People say that this is due to the fact that default dpi differs for the platforms.

**Comment by kobruleht** [comment]
--zoon 0.8 produces narrow pdfs. Using this there is too many white space in right side. How to remove this white space at right if this zoom is used? This issue occurs both in Windows and Linux.

**Comment by nathansams** [comment]
I found that it helped to use a CSS reset (e.g. http://meyerweb.com/eric/tools/css/reset/).

**Comment by kobruleht** [comment]
I added this style to start of report. Report does not change: first line in some pages is still only partially visible.

**Comment by bobf** [comment]
@sgnann Thank you - your suggestion worked for me and saved me a headache, much appreciated (2 years later).

**Comment by neverthemachineforever** [comment]
Using a CSS reset fixed things for me (thanks @nathansams), so I dug a little deeper and in my case (h3 with an image floating left) applying a font-size of 100% to the h3 was the specific fix. Anything other than 100% would cause the text, which would otherwise flow around the float, to essentially disappear.

**Comment by vishaltps** [comment]
So after researching 4 hours i found total 2 solutions .

with css
tr{ page-break-before: avoid; display: "inline-block"; //or display: "inline-table" }

This solution worked for me. but it also changes the design of my page. because of display: inline-block and page-break-before: avoid; not working with out display: inline-block; in tr.

updated the gem version of wkhtmltopdf-binary
Very effective solution. because from my older wkhtmltopdf's version was 0.9 in which the page break issue is common. So i updated gem version of wkhtmltopdf-binary.

Replace this gem gem **'wkhtmltopdf-binary' with gem 'wkhtmltopdf-binary', '~> 0.12.3'

**Comment by carkod** [comment]
I was using 0.12.4 with patched Qt and only the `table tr {page-break-inside: avoid}` worked

**Comment by ogrosko** [comment]
Looks like this works for me https://github.com/ariya/phantomjs/issues/13524#issuecomment-259384439

**Comment by MikeCaputo** [comment]
I scoured the internet for a couple of weeks, trying to overcome this issue. None of the solutions I found worked for me, but something else did.

I had a two column layout where the text was getting cut off mid-text. In the broken state, my basic structure looked like this:

```
.col-9{
  display: inline-block;
  width: 70%;
}
.col-9{
  display: inline-block;
  width: 25%;
}

<div class="col-9">
  [a lot of text here, that would spill over multiple pages]
</div>
<div class="col-3">
  [a short sidebar here]
</div>
```
I fixed it by changing it to:
```
@media print {
  * {
    page-break-inside: avoid;
    page-break-after: avoid;
    page-break-before: avoid;
  }
}

.col-9{
  display: block;
  float: left;
  width: 70%;
}
.col-9{
  display: block;
  float: left;
  width: 25%;
}
.clear{
  clear: both;
}

<div class="col-9">
  [a lot of text here, that no longer split mid-line.]
</div>
<div class="col-3">
  [a short sidebar here]
</div>
<div class="clear"></div>
```
For some reason, the tool could not handle the display: inline-block setup. It works with floats. I'm running version 0.12.4.

**Comment by roman-kuleshov** [comment]
Hello, I had the same issue. I remove 
**transform: translateY(-30px)** on print version

Make sure you are not using css3 transform related properties on print version.

**Comment by ferrall** [comment]
>   * {
>     page-break-inside: avoid;
>     page-break-after: avoid;
>     page-break-before: avoid;
>   }
I added just this and it fixed the problem for me.  Thanks!

**Comment by kobruleht** [comment]
What is the first chartacter in this style ?  It looks like automatic formatting was applied and this changed first character to bullet.

**Comment by ferrall** [comment]
Just notice this reply.  It is the asterisk "*"  and is apparently the usual grep "all" selector.  
I'm always surprised how much is in CSS.

**Comment by AimanMRT** [comment]
Avoid to use thead. it work also..

**Comment by Norris1z** [comment]
Adding 
`    html,
    body {
        margin: 0;
        padding: 0;
        border: 0;
        font-size: 100%;
        font: inherit;
        vertical-align: baseline;
    }`

Fixed it for me.
