### ISSUE TITLE
Can't write on STDOUT

### ISSUE THREAD

**Issue by Ange7** [wkhtmltopdf/wkhtmltopdf#2036]
Hi all,

i have a problem with wkhtmltopdf (from wkhtmltox package on debian, version 0.12.1). 

If i run command line : 

> /usr/bin/xvfb-run wkhtmltopdf http://www.google.fr -

to write result on stdout, but i have this error message : 

> Loading pages (1/6)
> QPainter::begin(): Returned false============================] 100%
> Error: Unable to write to destination  
> Exit with code 1, due to unknown error.

If i specify one file to destination file, it work rightly. But i need to have result on stdout. 

If someone have one idea ? 

Thank you,

AnGe7

**Comment by joonas-fi** [comment]
I am having this same issue.

- stdout works if I'm invoking directly from shell
- stdout does not work if I'm invoking from a node.js process (even if calling proxy shell script which itself invokes wkhtmltopdf)

strace gives me this:

	open("/dev/stdout", O_WRONLY|O_CREAT|O_TRUNC|O_CLOEXEC, 0666) = -1 ENXIO (No such device or address)
	write(2, "QPainter::begin(): Returned fals"..., 34QPainter::begin(): Returned false) = 34
	write(2, "Error: Unable to write to destin"..., 37Error: Unable to write to destination) = 37

My command line (exact same which works from Shell but not from node.js):

	wkhtmltopdf --page-size A4 /tmp/WeGjP1DZJ_SO7wQ5dsLLlfKw.html -

**Comment by docteurklein** [comment]
same here: 

```
 % socat tcp-l:6667,reuseaddr,fork exec:'wkhtmltopdf - -' &; echo test | socat - TCP4:localhost:6667
[1] 3336
Loading page (1/2)
Printing pages (2/2)
QPainter::begin(): Returned false
Done
```

However, this works: 

```
 % echo test | wkhtmltopdf - -
```

Any clue?

**Comment by graingert** [comment]
@ashkulz I'm getting the same issue with `wkhtmltopdf 0.12.3 (with patched qt)`

**Comment by graingert** [comment]
@ashkulz can you re-open?

**Comment by miccarr** [comment]
Same issue as @joonas-fi. But it works on my Mac, not on Docker.

**Comment by vinyll** [comment]
[Same issue here](https://github.com/tutorcruncher/pydf/issues/12).

Works on my MacOSX and a CentOS.
Meeting this issue with Ubuntu. 18.10 freshly installed and latest stable wkhtmltopdf.
