### ISSUE TITLE
Representation of the HTML ℜ symbol in utf8 encoding is not OK.

### ISSUE THREAD

**Issue by clpippel** [wkhtmltopdf/wkhtmltopdf#2040]
![Uploading @real.jpg . . .]()

Representation of the HTML ℜ symbol in utf8 encoding is not OK.
System: Windows 8.1
Command:

d:\wkhtmltopdf\bin\wkhtmltopdf.exe --encoding utf8 @real.html @real.pdf

**Comment by alloylab** [comment]
What version? have you tried this on 0.12.5?

**Comment by Tomsgu** [comment]
Closing as there is no feedback from the author, neither there is any example.
