### ISSUE TITLE
Adding unrelated last page

### ISSUE THREAD

**Issue by ulugbekov** [wkhtmltopdf/wkhtmltopdf#2041]
My head is blowing up.
wkhtmltopdf --print-media-type  -L 0mm -R 0mm -T 0mm -B 0mm toc html book.pdf
OR
wkhtmltopdf --print-media-type  -L 0 -R 0 -T 0 -B 0 toc html book.pdf
I have 2 pages. After this code, it is adding Table Content, My 2 pages and 1 unrelated blank page at the end. Whether documentation is really bad.
I hope it gets solved.

**Comment by alloylab** [comment]
What version? have you tried this on 0.12.5?

**Comment by Tomsgu** [comment]
Closing as there is no feedback from the author.
