### ISSUE TITLE
rendering of Thai symbols is very slow

### ISSUE THREAD

**Issue by luesak** [wkhtmltopdf/wkhtmltopdf#2055]
I reopened this because the previous one was closed.... and I can't find a way to reopen!!!

Any how, converting files using utf-8 is extremely slow... I have attached a download with a comparison test. Hope this helps!

I'm using the latest version: 
wkhtmltopdf 0.12.1.2 (with patched qt)

Attached are some test files... notice the slowness... you have to wait about 5-6 minutes.. only 38 pages or so... I am running i7-3930K with 6 cores x 2 threads... WIndows 7 64bit MSVC2013 version.

The non-utf8 one completes in an instant.

Sample files with the batch file I use: 
https://www.dropbox.com/s/dd3mteb8h9i5de3/wkhtmltopdf.rar?dl=1

Thanks

Kim

**Comment by ashkulz** [comment]
`0.12.2` has been released, which includes changes related to this issue.

**Comment by luesak** [comment]
Thanks!

Kim
