### ISSUE TITLE
Spaces in url path break image generation

### ISSUE THREAD

**Issue by danielsokolowski** [wkhtmltopdf/wkhtmltopdf#2062]
I am on a Windows 8.1 64bit, I believe white spaces in my project name 'Client Limited (Dev) [SBX]' are preventing images from being rendered properly in the PDF. 

```
<body>
        <p><img src="../assets/STG.jpg" alt="Stantive Technologies Group logo" title="STG"></p>
<h1 id="mcgrath-real-estate">... Real Estate</h1>
```

Renders into: 

![missing images due to white space in path](https://cloud.githubusercontent.com/assets/273413/5110180/7f5c7b46-6fe4-11e4-869c-4ff7f4599ac8.png)

**Comment by Tomsgu** [comment]
Closing as solutions were provided.
