### ISSUE TITLE
Library exits main application

### ISSUE THREAD

**Issue by mewa** [wkhtmltopdf/wkhtmltopdf#2065]
The library when used in a Qt project exits the application when it's done with the workload.

Commenting out the qApp exits did the trick fixing it, but is it right to do so?

**Comment by huy-cong** [comment]
Hi, 
I ran into the same issue myself. The question is if I want to integrate wktmltopdf in my Qt application as shared library, what should I do to separate the QApplication process of wkhtmltopdf and the one of my main app?
Thanks in advance
