### ISSUE TITLE
wkhtmltopdf issue with specific wingdings character

### ISSUE THREAD

**Issue by pdas77** [wkhtmltopdf/wkhtmltopdf#2068]
I am facing issue with Wingdings character. Few unicode characters are not coming properly in the PDF output. Below two characters are present in Wingdings font, but it is not coming when I use wkhtmltopdf, while other Wingdings characters come in PDF document .

ý (U+00FD) 
þ (U+00FE)

http://www.alanwood.net/demos/wingdings.html

Any help is appreciated!

**Comment by alloylab** [comment]
What version? have you tried this on 0.12.5?

**Comment by Tomsgu** [comment]
Closing as there is no feedback and the provided link are rendered correctly in a newest version.
