### ISSUE TITLE
Crash with HTML containing an image with dimensions 932x287

### ISSUE THREAD

**Issue by salsifis** [wkhtmltopdf/wkhtmltopdf#2072]
Hello

I tried to get a minimal example for this report. Let us consider the following HTML file:

```
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
</head>
<body>
<img src="image.jpg">
</body>
</html>
```

I am running Windows 7, 64 bit architecture, with latest 32-bit binaries from http://wkhtmltopdf.org/downloads.html

When I try to run `wkhtmltopdf.exe --page-size A4 input.htm output.pdf` the application crashes at that moment:

![Screenshot of crash](http://i.imgur.com/xnZ8RQL.png)

The image is a completely blank image of width 932 or 933px and height 287px. The bug seems to reproduce when these dimensions are not altered, and to vanish when. The image located at [http://i.imgur.com/3WKRCM3.jpg](http://i.imgur.com/3WKRCM3.jpg) can be used to reproduce the problem on my workstation.

Thanks

**Comment by kboronka** [comment]
I had a similar issue with v0.12.2.  Finally resolved by enabling the the Volume Shadow Copy service.  Weird, and perhaps a unique issue but it may be helpful to somebody out else there.
