### ISSUE TITLE
100mm aren't exactly 100mm

### ISSUE THREAD

**Issue by jochenonline** [wkhtmltopdf/wkhtmltopdf#2074]
Given the following file `test.html`:

``` html
<DOCTYPE html>
<html>
<head></head>
<body>
    <table style="width:100mm;border:1px solid">
        <tr><td>test</td></tr>
    </table>
</body>
</html>
```

converted with

```
wkhtmltopdf ./test.html ./test.pdf
```

produces a pdf which when printed contains a box that is `100mm` wide in **no case**. Depending on the os (Win/Mac/Linux) and the parameter `--disable-smart-shrinkink` I get different results. Some longer than 100mm, some shorter. But no one exactly 100mm long.

Is there any chance to get an os independent and exact result?

**Comment by mn4367** [comment]
In my opinion this isn't really an issue (or a bug). To get exact measurings you have to "set up the right things" :smile:, if the document is under your control (please see the comments in the CSS):

```html
<!DOCTYPE html>
<html>
<head>
    <style type="text/css">
     body {
        /* = page width minus left margin minus right margin
          (via wkhtmltopdf command line, in this case -s A4 -L 4cm -R 4cm ) */
        width: 13cm;
        /* the following ones are important! */
        margin: 0;
        border: none;
        border-width: 0;
        /* makes the background transparent */
        background-color: white;
    }
    </style>
</head>
<body>
<div style="width: 100mm; height: 50mm; background-color: red;">
</div>
</body>
</html>
```

If you render this document with

```
wkhtmltopdf -s A4 -L 4cm -R 4cm -T 2cm -B 2cm test.html test.pdf
```

you'll get a pretty exact `div`on OS X. On Windows you should run:

```
wkhtmltopdf.exe -s A4 -L 4cm -R 4cm -T 2cm -B 2cm --zoom 1.33 test.html test.pdf
```

Please note that the value for `--zoom` on Windows depends on the settings for your display DPI. `1.33` fits the default Windows settings.

With the following trick you'll achieve the same result but additionally you can use a negative left margin via CSS for elements which should appear in the page border area, for example sidenotes:

```html
/* Just add this to the CSS above */
padding: 0 4cm 0 4cm;

/* Sample class for sidenotes */
.sidenote {
  margin-left: -2.5cm;
}
```

The settings for left and right margins now have to be set to zero on the command line:

```
wkhtmltopdf -s A4 -L 0 -R 0 -T 2cm -B 2cm test.html test.pdf
```
![bildschirmfoto 2015-01-31 um 23 30 31](https://cloud.githubusercontent.com/assets/6379696/5990082/5633b6c0-a9a1-11e4-969d-d183ba1cd8e6.png)
