### ISSUE TITLE
Width for character x in font 'XYZ' does not match.

### ISSUE THREAD

**Issue by Vad1mo** [wkhtmltopdf/wkhtmltopdf#2075]
Adobe Preflight pdf-tools pdfa validation report both:
The width for character x in font 'XYZ' does not match. 
http://www.pdf-tools.com/pdf/validate-pdfa-online.aspx

https://www.dropbox.com/s/f2jttv8ov4wrbvz/just_a_sample.pdf?dl=0

when comparing the is with what should be, there is always a constant difference 
576/581.055 = 0.9913
492/496.04 = 0.991855
452/456.055 = 0.991109
..  
how come there is this 10% gap? Is it possible to create a pdf without this gap?

the page was created with latest wkhtmltopdf and option no links, no toc, outline, form what. nothing with scale what so ever. 

also it is reproducible on win,mac,and linux

**Comment by Dr4K4n** [comment]
Any news on this topic? I'm trying to use wkhtmltopdf to create valid PDF/A3a documents and this is the only problem left. Is there a workaround to scale the text correctly?

**Comment by ashkulz** [comment]
@Dr4K4n: the tag "UpstreamChangeNeeded" says it all ...
