### ISSUE TITLE
Page Breaks Occur Mid-Image

### ISSUE THREAD

**Issue by masterchiefaragorn** [wkhtmltopdf/wkhtmltopdf#2078]
Hi,

wkhtmltopdf 0.12.1 (with patched qt) is inserting page breaks in the middle of my images when they are in a two-column table.  0.12.2-dev-5dea253 is also doing the same.  I'm using no command-line options, simply:

```
wkhtmltopdf test.html test.pdf
```

What I'm expecting to see is for wkhtmltopdf to put the first 6 images (3 in each column) on the first page, and the last 4 images (2 in each column) on the second page.  But what is happening is that it is putting some amount of space after the first 6 images (3 in each column) as if it is trying to do a page break (it's almost like qt measured the size of the page incorrectly) and then the next two images get cut in half (part on page 1 and the rest on page 2).  Here is the HTML:

``` html
<!DOCTYPE html>
<html>
<body>
    <table>
        <tr>
            <td>
                <img src="https://build.iqcoordinator.com:8002/customers/esimon/test.png" /><br />
                <img src="https://build.iqcoordinator.com:8002/customers/esimon/test.png" /><br />
                <img src="https://build.iqcoordinator.com:8002/customers/esimon/test.png" /><br />
                <img src="https://build.iqcoordinator.com:8002/customers/esimon/test.png" /><br />
                <img src="https://build.iqcoordinator.com:8002/customers/esimon/test.png" /><br />
            </td>
            <td>
                <img src="https://build.iqcoordinator.com:8002/customers/esimon/test.png" /><br />
                <img src="https://build.iqcoordinator.com:8002/customers/esimon/test.png" /><br />
                <img src="https://build.iqcoordinator.com:8002/customers/esimon/test.png" /><br />
                <img src="https://build.iqcoordinator.com:8002/customers/esimon/test.png" /><br />
                <img src="https://build.iqcoordinator.com:8002/customers/esimon/test.png" /><br />
            </td>
        </tr>
    </table>
</body>
</html>
```

**Comment by amoskaliov** [comment]
Hello,

i've got just the same problem. I used masterchiefaragorn's code, but changed the image link as the original link is currently broken:

```
<!DOCTYPE html>
<html>
<body>
    <table>
        <tr>
            <td>
                <img src="https://s-media-cache-ak0.pinimg.com/736x/92/9d/3d/929d3d9f76f406b5ac6020323d2d32dc.jpg" /><br />
                <img src="https://s-media-cache-ak0.pinimg.com/736x/92/9d/3d/929d3d9f76f406b5ac6020323d2d32dc.jpg" /><br />
                <img src="https://s-media-cache-ak0.pinimg.com/736x/92/9d/3d/929d3d9f76f406b5ac6020323d2d32dc.jpg" /><br />
                <img src="https://s-media-cache-ak0.pinimg.com/736x/92/9d/3d/929d3d9f76f406b5ac6020323d2d32dc.jpg" /><br />
                <img src="https://s-media-cache-ak0.pinimg.com/736x/92/9d/3d/929d3d9f76f406b5ac6020323d2d32dc.jpg" /><br />
            </td>
            <td>
                <img src="https://s-media-cache-ak0.pinimg.com/736x/92/9d/3d/929d3d9f76f406b5ac6020323d2d32dc.jpg" /><br />
                <img src="https://s-media-cache-ak0.pinimg.com/736x/92/9d/3d/929d3d9f76f406b5ac6020323d2d32dc.jpg" /><br />
                <img src="https://s-media-cache-ak0.pinimg.com/736x/92/9d/3d/929d3d9f76f406b5ac6020323d2d32dc.jpg" /><br />
                <img src="https://s-media-cache-ak0.pinimg.com/736x/92/9d/3d/929d3d9f76f406b5ac6020323d2d32dc.jpg" /><br />
                <img src="https://s-media-cache-ak0.pinimg.com/736x/92/9d/3d/929d3d9f76f406b5ac6020323d2d32dc.jpg" /><br />
            </td>
        </tr>
    </table>
</body>
</html>
```

Now I'm trying to convert to pdf with using the current development version:

```
[a.moskalev@devpdfmaker01 ~]$ wkhtmltopdf -V
wkhtmltopdf 0.13.0-alpha-7b36694
[a.moskalev@devpdfmaker01 ~]$ xvfb-run wkhtmltopdf example.html example-devel.pdf
xkbcommon: ERROR: failed to add default include path auto
Qt: Failed to create XKB context!
Use QT_XKB_CONFIG_ROOT environmental variable to provide an additional search path, add ':' as separator to provide several search paths and/or make sure that XKB configuration data directory contains recent enough contents, to update please see http://cgit.freedesktop.org/xkeyboard-config/ .
Loading page (1/2)
Printing pages (2/2)
Done
```

And this is what I get
![default](https://cloud.githubusercontent.com/assets/22944004/26192442/56b49436-3bba-11e7-8a45-1a4e380cc3ae.png)

I also tried the last stable version
```
[a.moskalev@devpdfmaker01 ~]$ wkhtmltox/bin/wkhtmltopdf -V
wkhtmltopdf 0.12.4 (with patched qt)
[a.moskalev@devpdfmaker01 ~]$ wkhtmltox/bin/wkhtmltopdf example.html example-stable.pdf
Loading pages (1/6)
Counting pages (2/6)
Resolving links (4/6)
Loading headers and footers (5/6)
Printing pages (6/6)
Done
```

And this is what I got
![default](https://cloud.githubusercontent.com/assets/22944004/26192515/b2f10fae-3bba-11e7-9a5d-ee1ccb36663a.png)

I also tried to launch 0.12.4 via xvfb-run, but got wuite the same result.

I'm using CentOS 7.

**Comment by ogrosko** [comment]
Hi any news about this issue I'm getting same result with `wkhtmltopdf 0.12.4 (with patched qt)`

**Comment by sayajin101** [comment]
Also getting the same issue with 0.13.0-alpha-7b36694

**Comment by RaulTsc** [comment]
Any updates on this one? :)

**Comment by mgbvox** [comment]
Can we reopen this? Still an issue.

**Comment by masterchiefaragorn** [comment]
@ashkulz, I believe we felt this issue wasn't going to away until QT5.  What QT is the latest wkhtmltopdf running?

**Comment by ashkulz** [comment]
It's still on Qt4.

**Comment by bhaveshselarka** [comment]
@ashkulz any chnace to relaese new version with QT5 ?

**Comment by ashkulz** [comment]
See #3217 on the efforts required to port the patches to Qt5. If you don't use any features specific to the patched version, you can use it now -- the version packaged by most distributions is already using Qt5.

As an example, [wkhtmltopdf in debian](https://packages.debian.org/buster/wkhtmltopdf) depends on [libqt5webkit5](https://packages.debian.org/buster/libqt5webkit5) -- this would be the case for most distributions as they refuse to include a patched version of Qt, asking that patches should be upstreamed.

I'll be updating the project status in a few days on the website with more details before the 0.12.6 release.

**Comment by masterchiefaragorn** [comment]
Just wanted to finish this thread by saying that I've confirmed that this works in 0.12.6 release.  Thank you!

**Comment by JohnRobson** [comment]
wkhtmltopdf still cutting images between pages.
