### ISSUE TITLE
wkhtmltopdf clips the html document.

### ISSUE THREAD

**Issue by rajagopalkanchi** [wkhtmltopdf/wkhtmltopdf#2079]
wkhtmltopdf 0.11.0 rc2, converts the test.html to pdf  without clipping the content as shown in the converted pdf document test2PDFFrom_0_11_0_rc2.pdf.
while,
 wkhtmltopdf 0.12.1, converts the test.html to pdf  by  clipping the content as shown in the converted pdf document test2PDFFrom_0_12_1.pdf.

Command line options for both the versions are same 

  --proxy <proxy server> --disable-smart-shrinking

but the version 0.12.1 clips the content as seen in the output pdf test2PDFFrom_0_12_1.pdf.

Is the behavior difference expected? 

Have attached the original file and the generated pdfs from both version.

![test2pdffrom_0_11_0_rc2](https://cloud.githubusercontent.com/assets/10022825/5243437/2d784d7a-796a-11e4-9a01-8aa52f4080f9.png)
![test2pdffrom_0_12_1](https://cloud.githubusercontent.com/assets/10022825/5243438/2d7cb144-796a-11e4-83ed-f7511e264290.png)
![original_html](https://cloud.githubusercontent.com/assets/10022825/5243463/54f34c56-796a-11e4-81f2-a421541ae192.png)

**Comment by danielspaniel** [comment]
This is going to sound like hokus pokus, but I got the shrink to fit ( width ) to work by wrapping the content  like this

<div class="html-wrapper" style="position:absolute">
  
  <div class='the-content-I-want-to-shrink-to-fit">
  </div>
</div>

For reasons I can not explain, the "position:absolute" in the wrapper did the trick. 

I tried this with  v0.9.9.3 and v0.12.2.1

**Comment by dcworldwide** [comment]
@danielspaniel Does this workaround work if `<div class='the-content-I-want-to-shrink-to-fit">` spans multiple pages?

**Comment by danielspaniel** [comment]
I don't remember @dcworldwide. ( Been so long ) 
Maybe you can give it a try ( does not take long ) and see what happens?

**Comment by dcworldwide** [comment]
Thanks, will do. My issues appear to have been solved by the following config

`-margin-top 8 --margin-bottom 8 --margin-left 4 --margin-right 4 --disable-smart-shrinking`

Will try your fix if clipping re-appears.
