### ISSUE TITLE
High Memory Usage

### ISSUE THREAD

**Issue by ghost** [wkhtmltopdf/wkhtmltopdf#2090]
To generate a pdf with 4250 page consumes something around 5GB. And it is time consuming. Is this normal? Its optimize?

Thank you.

**Comment by aguegu** [comment]
I have a 5880 page doc, and wkhtmltopdf consume 2197972 kb memory.

After it taken up all my memory and swap, it was killed by system...

It can be easily test by '/usr/bin/time -v wkhtmltopdf ... ... '

**Comment by suvit** [comment]
I have 1 page html file. wkhtmltopdf eat 1,5 gb memory to convert to pdf. This is very big memory usage.

```shell
root@vm-ab001018:~# uname -a
Linux vm-ab001018 3.12-0.bpo.1-amd64 #1 SMP Debian 3.12.6-2~bpo70+1 (2014-01-07) x86_64 x86_64 x86_64 GNU/Linux
root@vm-ab001018:~# wkhtmltopdf -V
wkhtmltopdf 0.12.2.1 (with patched qt)
root@vm-ab001018:~# /usr/bin/time -v wkhtmltopdf http://krikcentre.ru/offer/c1923b33-f1d1-49f1-8ea4-654e9053c6b8/pdf/ out.pdf
Loading pages (1/6)
QFont::setPixelSize: Pixel size <= 0 (0)                     ] 47%
Counting pages (2/6)
Resolving links (4/6)
Loading headers and footers (5/6)
Printing pages (6/6)
Done
        Command being timed: "wkhtmltopdf http://krikcentre.ru/offer/c1923b33-f1d1-49f1-8ea4-654e9053c6b8/pdf/ out.pdf"
        User time (seconds): 6.97
        System time (seconds): 0.75
        Percent of CPU this job got: 92%
        Elapsed (wall clock) time (h:mm:ss or m:ss): 0:08.37
        Average shared text size (kbytes): 0
        Average unshared data size (kbytes): 0
        Average stack size (kbytes): 0
        Average total size (kbytes): 0
        Maximum resident set size (kbytes): 1544812
        Average resident set size (kbytes): 0
        Major (requiring I/O) page faults: 0
        Minor (reclaiming a frame) page faults: 420183
        Voluntary context switches: 138
        Involuntary context switches: 1490
        Swaps: 0
        File system inputs: 0
        File system outputs: 456
        Socket messages sent: 0
        Socket messages received: 0
        Signals delivered: 0
        Page size (bytes): 4096
        Exit status: 0
```

Link is working for tests in example (http://krikcentre.ru/offer/c1923b33-f1d1-49f1-8ea4-654e9053c6b8/).

**Comment by mhohai** [comment]
I need to convert one large html2pdf, but my pc's memory not enough.
so i split html to html1, html2, html3 ... , and then `$ wkhtmltopdf html1 html2 html3 out.pdf` it's didn't work!
but I run `$ wkhtmltopdf html1 out.pdf` one by one it's ok.

I think `$ wkhtmltopdf html1 html2 html3 out.pdf` Memory should less than `$ wkhtmltopdf html out.pdf`...  (set the Max memory use will great)

**Comment by Tomsgu** [comment]
Is this still an issue with a newest versions?

**Comment by Tomsgu** [comment]
Closing as there is no feedback. Please let us know if the issue persists in `0.12.5`.

**Comment by jklemm** [comment]
I'm trying to generate a PDF using HTML, it's only a table with data, and one image per line.

It uses 1,2 Gb to generate each file.  These spikes are the memory grown.

![image](https://user-images.githubusercontent.com/5324645/58282381-f4061700-7d7b-11e9-8e97-cfd7815aa399.png)
