### ISSUE TITLE
Strange box character in PDF

### ISSUE THREAD

**Issue by aliw77** [wkhtmltopdf/wkhtmltopdf#2094]
Seeing strange box characters in PDF.  Using  wkhtmltopdf 0.12.1 (with patched qt).  The html does not have any special characters.  It is plain string.  The box character appears towards the end of some wrapped lines, not all.  Tried various other themes and the shape and size of the character changes.  They are 4-8 on every page of the generated pdf.

![image](https://cloud.githubusercontent.com/assets/1495303/5371072/b57c923c-7ffd-11e4-898d-fdddd83919b8.png)

**Comment by joshuapinter** [comment]
:+1: Same thing here. 

The suggestion solution of adding `text-rendering: geometricPrecision;` to the `body` class worked great. 

Cheers!
