### ISSUE TITLE
Page Breaks Inside Table Row With page-break-inside:avoid

### ISSUE THREAD

**Issue by jjanusch** [wkhtmltopdf/wkhtmltopdf#2099]
I'm currently using wkhtmltopdf to generate large PDFs that include a large number of tables. We were having issues getting pages to break properly in table rows, so we ended up splitting each row into its own table. We've managed to make it work fairly well, honestly, but we cannot seem to fix this one issue.

Basically, if the page breaks prior to the table, it will leave 1-2px of the table row from the next page on the previous page. See the image below (text blurred due to confidential information):

![screen shot 2014-12-11 at 2 37 12 pm](https://cloud.githubusercontent.com/assets/3516836/5402830/a6834a12-8144-11e4-8830-cc71e664a346.png)

The two visible rows are both individual tables that have page-break-inside: avoid; set on them. Table 2 is too long to fit entirely under Table 1, so it gets moved to a new page, which is more-or-less what we want. But the beginning of table 2 is actually displayed on the previous page.

A similar issue I have encountered int he past is throwing a page-break-after:always on a table row doesn't create a full page break all the time. It will occasionally work, but more often than not it will produce this result, where the table at the top has a page-break-after:always on the last row:

![screen shot 2014-12-11 at 2 54 07 pm](https://cloud.githubusercontent.com/assets/3516836/5402973/e8e2d318-8145-11e4-9b6c-80b8b10f722f.png)

That is part of the reason we split out rows into tables; we needed a tool that could allow us to manually modify the generated HTML to push a page break. Adding it to a tr element, no matter what the display setting was, was next to impossible.

Both of these problems do not exist in the Print dialog for Chrome, Safari, and Chromium.

I'm running:
- Debian Wheezy 7.6
- wkhtmltopdf 0.12.2-dev-5dea253 (with patched qt)
- Apache/2.2.22 (Debian)
- PHP 5.4.4-14+deb7u14
- Running the wkhtmltopdf binary through PHP's exec command
- wkhtmltopdf --footer-center '- [page] -' --enable-javascript --no-stop-slow-scripts --margin-top 40 --margin-bottom 20 --footer-spacing 10 --page-size Letter --orientation landscape --header-spacing 4 --header-html header.html cover cover.html toc -xsl-style-sheet toc-style-sheet.xsl test.html test.pdf

**Comment by vinayagamrs** [comment]
Hi, Have you found any solution for the reported issue, we are facing the similar kind of issue, posting the solution helps me. please do the favour :)

**Comment by bakerstreetsystems** [comment]
I agree with vinayagamrs... any solution would be appreciated.

**Comment by fatuhoku** [comment]
Almost a year on... yes a solution would be really appreciated here too!

**Comment by ashkulz** [comment]
If you still face this problem with the latest version and after specifying `page-break-inside: avoid`, please post your sample HTML.

**Comment by dnprock** [comment]
I have a similar issue with `page-break-inside: avoid`. I posted my issue with details here:

https://github.com/wkhtmltopdf/wkhtmltopdf/issues/3002

**Comment by dnprock** [comment]
I end up converting my table structure into divs. Using css copy, I can get my divs to look like nested table. Printing divs works.
