### ISSUE TITLE
no compression and stdout

### ISSUE THREAD

**Issue by geach** [wkhtmltopdf/wkhtmltopdf#2102]
I can't seem to get no compression and stdout to work at the same time.

I am using version wkhtmltox-0.12.1.2_msvc2013-win64 on windows 7 pro 64 bit.

The command and output look like this:
C:\download\wkhtmltox-0.12.1.2_msvc2013-win64\bin>wkhtmltopdf.exe --no-pdf-compression "https://www.google.com" -
Loading pages (1/6)
Counting pages (2/6)
Resolving links (4/6)
Loading headers and footers (5/6)
Printing pages (6/6)
Error: Count not write to stdout
Exit with code 1, due to unknown error.

If I take off the compression option stdout works as expected.

Are there any workarounds for this?

**Comment by leij9857** [comment]
I'm experiencing the same error message with 0.12.3.2 when using stdin stdout without any options or switches. Only when the jpg was reduced in size from 880kb to 38kb the pdf was created.

**Comment by Tomsgu** [comment]
Do you still experience this issue in 0.12.5?

**Comment by Tomsgu** [comment]
Thanks for the feedback. I am closing the issue as it seems to be resolved. Please feel free to reopen if you think the issue still persists.
