### ISSUE TITLE
New release v0.12.2 ?

### ISSUE THREAD

**Issue by werne** [wkhtmltopdf/wkhtmltopdf#2105]
Any plans doing a new release v0.12.2 ?

There seems to be many changes since v0.12.1

tnx.

**Comment by ashkulz** [comment]
A release candidate [0.12.2-rc-71e97c1](http://wkhtmltopdf.org/downloads.html#testing) is available, the final release should happen sometime next week.

**Comment by evildav** [comment]
will that include a default support for tiff images?

**Comment by ashkulz** [comment]
Not sure, it's possible to add it but will have to remove it for `0.13` (as there is no easy way to just enable TIFF without bringing in a lot of unwanted image formats).
