### ISSUE TITLE
--minimum-font-size

### ISSUE THREAD

**Issue by beconceptit** [wkhtmltopdf/wkhtmltopdf#2107]
The switch --minimum-font-size does not seems to have any effect
for instance --minimum-font-size 34 or --minimum-font-size 6 does not change result

while
--zoom 0.7 or --zoom 2 does make a difference

**Comment by alloylab** [comment]
What version? have you tried this on 0.12.5?

**Comment by Tomsgu** [comment]
Closing as there is no feedback and it works in `0.12.5`.
