### ISSUE TITLE
Can't load external images

### ISSUE THREAD

**Issue by jfi** [wkhtmltopdf/wkhtmltopdf#2115]
I've been encountering an issue where linking to an image using an absolute URL meant that the image did not show and PDF generation is very slow (~30s in my testing). After some Googling, I found this issue:

https://github.com/pdfkit/pdfkit/issues/28

I've been getting exactly the same using both http://github.com/mikehaertl/phpwkhtmltopdf and the binary (0.12.1 on CentOS) - and setting the hosts file is a fix, but a workaround. Is this a known issue?

**Comment by hejiaji** [comment]
@Tomsgu why do you just close the issue without solving it at all??? it's a common situation that we cannot generate pdf with external images.
