### ISSUE TITLE
C API - Multiple library use cycles fail with objects loaded via URL

### ISSUE THREAD

**Issue by tuespetre** [wkhtmltopdf/wkhtmltopdf#2117]
(Using 0.12.1) 
Using the C API I can convert multiple objects sequentially with an init/deinit cycle. Here's some pseudo-code to demonstrate:

```
wkhtmltopdf_init(0);
wkhtmltopdf_create_global_settings();
wkhtmltopdf_create_converter(global);
wkhtmltopdf_create_object_settings();
wkhtmltopdf_add_object(converter, object, "<p>Hello world!</p>");
wkhtmltopdf_convert(converter);
wkhtmltopdf_destroy_converter(converter);
wkhtmltopdf_deinit();

// later in the same process
wkhtmltopdf_init(0);
wkhtmltopdf_create_global_settings();
wkhtmltopdf_create_converter(global);
wkhtmltopdf_create_object_settings();
wkhtmltopdf_add_object(converter, object, "<p>Hello world!</p>");
wkhtmltopdf_convert(converter);
wkhtmltopdf_destroy_converter(converter);
wkhtmltopdf_deinit();
```

If I instead set page urls for the objects to load instead of passing in raw HTML, I get an `AccessViolationException.`

**Comment by TroudhuK** [comment]
Hello,

I try to correctly use wkhtmltopdf in a singleton to do several HTML to PDF conversions. v0.12.5.

I tried:

> wkhtmltopdf_init
> wkhtmltopdf_global_settings
> wkhtmltopdf_create_converter
> wkhtmltopdf_set_error_callback
> wkhtmltopdf_set_warning_callback
> wkhtmltopdf_object_settings
> wkhtmltopdf_set_global_setting("out"...)
> wkhtmltopdf_set_object_setting("page"...)
> wkhtmltopdf_set_object_setting
> wkhtmltopdf_add_object
> wkhtmltopdf_convert
> wkhtmltopdf_destroy_converter
> wkhtmltopdf_deinit

Several times => this bug.

> wkhtmltopdf_init
> (
> wkhtmltopdf_global_settings
> wkhtmltopdf_create_converter
> wkhtmltopdf_set_error_callback
> wkhtmltopdf_set_warning_callback
> wkhtmltopdf_object_settings
> wkhtmltopdf_set_global_setting("out"...)
> wkhtmltopdf_set_object_setting("page"...)
> wkhtmltopdf_set_object_setting
> wkhtmltopdf_add_object
> wkhtmltopdf_convert
> wkhtmltopdf_destroy_converter
> ) [several times]
> wkhtmltopdf_deinit

=> The second time, it's blocked at wkhtmltopdf_convert (full charged CPU core).

So what is the good way to perform several conversions, needing to change only source/destination ?
