### ISSUE TITLE
bold/italic text near end of line has too little space before it

### ISSUE THREAD

**Issue by mslgam** [wkhtmltopdf/wkhtmltopdf#2118]
Italicized/bolded words that appear late in a line (not paragraph) don't have enough space before them - they join with the previous word. I'm using "wkhtmltopdf 0.12.1 (with patched qt)" (output of -V) on Kubuntu 14.04. I'm not using any command-line options.

The below sample file has 5 paragraphs. The first paragraph displays correctly in the PDF, but the other 4 don't.

``` html
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=us-ascii">
  <meta http-equiv="Content-Style-Type" content="text/css">
</head>
<body>
<p>The quick brown fox jumped over the lazy dog. The quick brown fox jumped over the lazy dog. a The quick brown fox jumped over the lazy dog. The quick brown fox jumped over the lazy dog.</p>
<p>The quick brown fox <em>jumped</em> over the lazy dog. The quick brown fox <em>jumped</em> over the lazy dog. a The quick brown fox <em>jumped</em> over the lazy dog. The quick brown fox <em>jumped</em> over the lazy dog.</p>
<p>The quick brown fox <strong>jumped</strong> over the lazy dog. The quick brown fox <strong>jumped</strong> over the lazy dog. a The quick brown fox <strong>jumped</strong> over the lazy dog. The quick brown fox <strong>jumped</strong> over the lazy dog.</p>
<p>The quick brown fox <i>jumped</i> over the lazy dog. The quick brown fox <i>jumped</i> over the lazy dog. a The quick brown fox <i>jumped</i> over the lazy dog. The quick brown fox <i>jumped</i> over the lazy dog.</p>
<p>The quick brown fox <b>jumped</b> over the lazy dog. The quick brown fox <b>jumped</b> over the lazy dog. a The quick brown fox <b>jumped</b> over the lazy dog. The quick brown fox <b>jumped</b> over the lazy dog.</p>
</body>
</html>
```

**Comment by Qronicle** [comment]
I'm having the same issue, though you can fix it by removing the space in front of the em/b/strong tag and putting it right after the tag.
Should still be fixed though :)

**Comment by dforrer** [comment]
We are having the same issue with this. Very annoying bug because it is unpredictable.

wkhtmltopdf 0.12.3 (with patched qt)

**Comment by kamalsamra** [comment]
I am also facing same issue even after removing the space from front of the em/b/strong tag and putting it right after the tag.

**Comment by gabrielps** [comment]
I'm also having this problem with <strong> tags

**Comment by wwalc** [comment]
The following solution helped in my case to workaround the issue:
https://github.com/wkhtmltopdf/wkhtmltopdf/issues/2372#issuecomment-203037983

I had to add a line break after the opening tag to preserve space:
```
		<strong>
			you</strong>, as a member of...
```

**Comment by begonaalvarezd** [comment]
Hello, I am experiencing this issue with the version `0.12.6-dev`. 
See the following example when using the `strong` tag. 

`<p># Do I have to repeat system identification after <strong>attaching a load to the system</strong>.</p>`

![Screenshot from 2019-04-25 17-29-38](https://user-images.githubusercontent.com/3624944/56748222-b9f72480-677f-11e9-88fa-b6a912550036.png)

Any idea how to solve it?

**Comment by mira-kovar** [comment]
> Hello, I am experiencing this issue with the version `0.12.6-dev`.
> See the following example when using the `strong` tag.
> 
> `<p># Do I have to repeat system identification after <strong>attaching a load to the system</strong>.</p>`
> 
> ![Screenshot from 2019-04-25 17-29-38](https://user-images.githubusercontent.com/3624944/56748222-b9f72480-677f-11e9-88fa-b6a912550036.png)
> 
> Any idea how to solve it?

I Have exacty same problem with vertsion `0.12.5` (Qt `4.8.7`). Please some one any idea?

**Comment by elioschmutz** [comment]
Still have this issue `wkhtmltopdf 0.12.5 (with patched qt)`

**Comment by mira-kovar** [comment]
> > Hello, I am experiencing this issue with the version `0.12.6-dev`.
> > See the following example when using the `strong` tag.
> > `<p># Do I have to repeat system identification after <strong>attaching a load to the system</strong>.</p>`
> > ![Screenshot from 2019-04-25 17-29-38](https://user-images.githubusercontent.com/3624944/56748222-b9f72480-677f-11e9-88fa-b6a912550036.png)
> > Any idea how to solve it?
> 
> I Have exacty same problem with vertsion `0.12.5` (Qt `4.8.7`). Please some one any idea?

The problem was with my setup of debian. Fix it with font config like this one:
```
<?xml version='1.0'?>
<!DOCTYPE fontconfig SYSTEM 'fonts.dtd'>
<fontconfig>
<match target="font">
 <edit mode="assign" name="antialias">
  <bool>true</bool>
 </edit>
</match>
 <match target="font">
   <edit mode="assign" name="lcdfilter">
     <const>lcddefault</const>
   </edit>
 </match>
</fontconfig>
```

**Comment by geoffrey-xelians** [comment]
Hello, I still have this issue wkhtmltopdf 0.12.6 (with patched qt). fontconfig just above didn't fix it on CentOs7. Any other idea ?
![image](https://user-images.githubusercontent.com/69241149/89396873-66f47700-d70f-11ea-8f2e-b412d90dbc5b.png)

**Comment by mira-kovar** [comment]
> Hello, I still have this issue wkhtmltopdf 0.12.6 (with patched qt). fontconfig just above didn't fix it on CentOs7. Any other idea ?
> ![image](https://user-images.githubusercontent.com/69241149/89396873-66f47700-d70f-11ea-8f2e-b412d90dbc5b.png)

Did try change content of file `/usr/share/fontconfig/conf.avail/11-lcdfilter-light.conf`? My problem was with rendering light font (light in width).

example:
```xml
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<fontconfig>
  <its:rules xmlns:its="http://www.w3.org/2005/11/its" version="1.0">
    <its:translateRule translate="no" selector="/fontconfig/*[not(self::description)]"/>
  </its:rules>

  <description>Use lcdlight as default for LCD filter</description>
<!--  Use lcdlight as default for LCD filter -->
  <match target="pattern">
    <!--
      This configuration is available on the major desktop environments.
      We shouldn't overwrite it with "assign" unconditionally.
      Most clients may picks up the first value only. so using "append"
      may simply works to avoid it.
    -->
    <edit mode="append" name="lcdfilter">
      <!-- THIS IS WHAT MAKES BOLD TEXT WITHOUT SPACE
      <const>lcdlight</const>
      -->
      <const>lcddefault</const>
    </edit>
  </match>
</fontconfig>
```

**Comment by vitorreus** [comment]
I had the same issue using the [`ubuntu:18.04`](https://hub.docker.com/_/ubuntu/?tab=tags&page=1&name=18.04) docker image. Removing `/etc/fonts/conf.d/10-hinting-slight.conf` solved the issue.

The configuration file had the follwing content:

```xml
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<fontconfig>
  <match target="pattern">
    <!--
      This configuration is available on the major desktop environments.
      We shouldn't overwrite it with "assign" unconditionally.
      Most clients may picks up the first value only. so using "append"
      may simply works to avoid it.
    -->
    <edit name="hintstyle" mode="append"><const>hintslight</const></edit>
  </match>
</fontconfig>
```
