### ISSUE TITLE
Warning: SSL error ignored & Failed to load https://*.css

### ISSUE THREAD

**Issue by cyberdots** [wkhtmltopdf/wkhtmltopdf#2120]
Have installed wkhtmltopdf (wkhtmltopdf 0.12.1 (with patched qt)) on CentOS 6 (2.6.32-042stab094.7 x86_64 x86_64 x86_64).

When i try to make pdf from html, i got:

/usr/local/bin/wkhtmltopdf eric.html eric.pdf
Loading pages (1/6)
Warning: SSL error ignored
Warning: SSL error ignored
Warning: SSL error ignored
Warning: Failed to load https://testeric.gobadmin.nl/css/font-awesome.css (ignore)
Warning: Failed to load https://testeric.gobadmin.nl/bootstrap/css/bs_pdf.css (ignore)
Warning: Failed to load https://testeric.gobadmin.nl/css/base-admin.css (ignore)
Warning: Failed to load https://testeric.gobadmin.nl/css/main.css (ignore)
Counting pages (2/6)
Resolving links (4/6)
Loading headers and footers (5/6)
Printing pages (6/6)
Done
Exit with code 1 due to network error: ContentNotFoundError

Here it's comes: The PDF is created, but without image (logo) and without css (ofcourse, it didn't loaded). But why?

The htmlfile:
https://testeric.gobadmin.nl/eric.html
The pdffile:
https://testeric.gobadmin.nl/eric.pdf

**Comment by pandeyvishal1986** [comment]
I am using C# Pechkin wrapper for wkhtmltopdf. The style and script is not loading while exporting from View to Pdf. This only occurs when working with ` https://`. Could someone help me on this. Thanks in advance.

**Comment by ashkulz** [comment]
Raise an issue in the Pechkin repository? I can't help you unless it's reproducible from the CLI.
