### ISSUE TITLE
Error: Could not save image

### ISSUE THREAD

**Issue by shestero** [wkhtmltopdf/wkhtmltopdf#2122]
With wkhtmltopdf.exe 32-bit XP version reading source HTML from standard input and writing output PDF into file I have "Error: Could not save image" (no matter which file name I have).
Redirecting PDF through standart output ("- - >file.pdf") I have no errors but unreadable PDF file.
(I tried -q and -n options).
When I specify -f pdf option or try others (in case of standratd output) I also have got internal error.

**Comment by bae43** [comment]
I have same issue as well with latest Windows 64bit

"Error: could not save image
Exit with code 1, due to unknown error"

**Comment by ashkulz** [comment]
Unfortunately, without a minimal/reproducible test case and environment/command line details as requested in the [support page](http://wkhtmltopdf.org/support.html) this issue cannot be investigated further. Please reopen this issue once you have provided the details instead of creating a new issue.

**Comment by PatriceBG** [comment]
I have the same issue with Windows 10. I downloaded the most recent version and here is what I get:
 
C:\WINDOWS\system32>"c:\Program Files\wkhtmltopdf\bin\wkhtmltoimage.exe" http://www.google.com c:\temp\google.pdf
Loading page (1/2)
Rendering (2/2)
Error: Could not save image
Done
Exit with code 1, due to unknown error.

The file is created but with 0 size. I checked the event viewer but there is no related event that I could find. Is there some form of diagnostic I can run to figure out what is going on?

Thanks,

Patrice

**Comment by Crossmotion** [comment]
Under windows, try running the Command Promt as Administrator. That solved the problem for me.

**Comment by arnolambert** [comment]
Same error
tried 64 and 32 table version on Windows 8.1

**Comment by Teppichratte** [comment]
same error on Win 10 Prof. 64 Bit

**Comment by jemaf** [comment]
Any news about this problem? Got the same error on Windows 10 64bits, running powershell with both common user and admin privileges.

    > wkhtmltoimage.exe --version
    wkhtmltoimage 0.12.5 (with patched qt)

    > wkhtmltoimage.exe http://www.google.com google.pdf
    Loading page (1/2)
    Rendering (2/2)
    Error: Could not save image
    Done
    Exit with code 1, due to unknown error.

**Comment by ashkulz** [comment]
@jemaf: which folder are you running this in? Try doing it in your home folder.

**Comment by jemaf** [comment]
Hi @ashkulz, 

Just executed inside my User folder, and result was the same as before.

**Comment by ashkulz** [comment]
Sorry, don't use Windows anymore so can't really help you. Does using a temp path help? e.g. `%TEMP%\dummy.png`?

**Comment by seekM** [comment]
I have the same problem:

```
C:\WINDOWS\system32>"C:\Program Files\wkhtmltopdf\bin\wkhtmltoimage.exe" --version
wkhtmltoimage 0.12.5 (with patched qt)
```

```
C:\WINDOWS\system32>"C:\Program Files\wkhtmltopdf\bin\wkhtmltoimage.exe" https://www.google.com %TEMP%\test.pdf
Loading page (1/2)
Rendering (2/2)
Error: Could not save image
Done
Exit with code 1, due to unknown error.

```
(tried it with adminstrator prompt)

**Comment by lynren** [comment]
same error on Win10 pro 64bit

**Comment by ashkulz** [comment]
Just as a data point: were you using the MSVC 2015 version or the MXE version? Does using the other version help you, if so? I'm a bit stumped, as it's been years since I'm actively using Windows.

**Comment by seekM** [comment]
I used wkhtmltox-0.12.5-1.msvc2015-win64.exe. I haven't tried the other option yet.

**Comment by lynren** [comment]
I encountered the error on MSVC 2015. MXE version works fine

**Comment by ashkulz** [comment]
That's great to know, but I'm stumped why this would occur. I assume that this is due to some change in Windows 10 which doesn't play well with the application manifest generated by MSVC 2015?

**Comment by AndreasWWylach** [comment]
As of Feb 2, I also can confirm this issue mentioned above using "MSVC 2015" on Windows 10 Pro with the same error message: "Could not save image", thus the generated PDF is 0 bytes.

Is there any fix in the works? Unfortunately I develop a Pimcore project on a Windows 10 machine ( normally I develop on Linux / Unix ). So I am really stuck with this issue.

**Comment by HenryT88** [comment]
Hello - If anyone else is directed here from Google, looking for an answer to this issue...
Please ensure you are running  wkhtmltopdf.exe and not wkhtmltoimage.exe as specified above several times.
wkhtmltopdf.exe is a converter to PDF.  wkhtmltoimage.exe is a converter to PNG (ie Image Converter)

**Comment by Gavo34** [comment]
I had to use full root save path using wkhtmltoimage

**Comment by Mykola-Veriga** [comment]
I got the same error 
You can reproduce that with this Docerfile

```
FROM surnet/alpine-wkhtmltopdf:3.9-0.12.5-full as wkhtmltopdf
FROM wodby/drupal-php:7.4-dev-4.15.3

RUN sudo su root
USER root
# Install dependencies for wkhtmltopdf
RUN apk add --no-cache \
  libstdc++ \
  libx11 \
  libxrender \
  libxext \
  libssl1.1 \
  ca-certificates \
  fontconfig \
  freetype \
  ttf-dejavu \
  ttf-droid \
  ttf-freefont \
  ttf-liberation \
  ttf-ubuntu-font-family \
&& apk add --no-cache --virtual .build-deps \
  msttcorefonts-installer \
\
# Install microsoft fonts
&& update-ms-fonts \
&& fc-cache -f \
\
# Clean up when done
&& rm -rf /tmp/* \
&& apk del .build-deps

# Copy wkhtmltopdf files from docker-wkhtmltopdf image
COPY --from=wkhtmltopdf /bin/wkhtmltopdf /usr/bin/wkhtmltopdf
COPY --from=wkhtmltopdf /bin/wkhtmltoimage /usr/bin/wkhtmltopdf
COPY --from=wkhtmltopdf /bin/libwkhtmltox* /usr/bin/

```

**Comment by kangarooo** [comment]
Still not fixed.
Now downloaded this app and tried
wkhtmltoimage.exe --enable-local-file-access lv.html lv.pdf
Error: Could not save image
Done
Exit with code 1, due to unknown error.
