### ISSUE TITLE
Setting background color for the whole PDF file

### ISSUE THREAD

**Issue by kyriakos** [wkhtmltopdf/wkhtmltopdf#2123]
From the tests I've run its impossible to set the background color of the whole file. All works well with zero margins but once an html header is introduced the gap between the header and the page content is always white. If what i'm saying doesn't make much sense I can provide an example.

**Comment by ashkulz** [comment]
Normally, the background is transparent since `0.12.2.1`. If you want some different behavior, reopen the issue with some examples.

**Comment by kamalsamra** [comment]
I want background color on multiple pages of pdf so for that i use background color on body but if content goes to second page then second page have background color till content.

**Comment by santhoshmanikandan** [comment]
Yes this has been an issue with wkhtmltopdf. Have added the output of a simple html with background color. Is it possible to extend the color to the whole page even if the content is not available?
[testbgcolor.pdf](https://github.com/wkhtmltopdf/wkhtmltopdf/files/803446/testbgcolor.pdf)
