### ISSUE TITLE
QFont::setPixelSize: Pixel size <= 0

### ISSUE THREAD

**Issue by zentheme** [wkhtmltopdf/wkhtmltopdf#2124]
I've been periodically getting a `QFont::setPixelSize: Pixel size <= 0 (0)` error on certain webpages, I managed to reproduce it by wrapping an `<img>` tag in a container with `font-size: 0`. I've seen this issue mentioned occasionally so hopefully that might help someone!

**Comment by ashkulz** [comment]
It's a harmless warning, it shouldn't cause an error. It would be solved by the upgrade to Qt5 where it has been fixed, see [webkit bug 114175](https://bugs.webkit.org/show_bug.cgi?id=114175).

**Comment by ashkulz** [comment]
A release candidate for the **0.12.6** release is [now available for download](https://wkhtmltopdf.org/downloads.html#release-candidate), which should contain changes which possibly address this issue.

Would appreciate downloading the package and reporting back if any issues are encountered during testing. Assuming all goes well, I plan to release 0.12.6 on the 2-year anniversary of the previous release i.e. June 11, 2020.

**Comment by justuseapen** [comment]
just a heads up i get this error on 0.12.6 as well... it does cause errors in libraries like EmlToPdf which depend on wkhtmltopdf

**Comment by w455im** [comment]
I am getting a blank white page when converting an html page to pdf and in the console I get the warning message `QFont::setPixelSize: Pixel size <= 0 (0)` multiple times... Not sure if that's what's causing it but I have no other warning sor errors displayed 😕
