### ISSUE TITLE
Rendering (2/2) Killed==========>  

### ISSUE THREAD

**Issue by iMboya** [wkhtmltopdf/wkhtmltopdf#2127]
I use the following command：
wkhtmltoimage --disable-smart-width --width 462 --user-style-sheet http://www.digi-wo.com/cwb/css/dgw_article.css http://www.digi-wo.com/article-68-1.html /cwb/images/cwb_68.jpg

Loading page (1/2)
Rendering (2/2)  
Killed==========>    

---

The environment of the system I is centos 6.5 and wkhtmltoimage 0.12.1 (with patched qt)

No problem with the other page, but this page, and
http://www.digi-wo.com/article-171-1.html
http://www.digi-wo.com/article-74-1.html
The two page, also will appear killed error

How can i get the error log?
Thanks~

**Comment by Tomsgu** [comment]
Do you still have this problem using the newest version 0.12.5?

On archlinux with wkhtmltoimage 0.12.5 it is working perfectly.

**Comment by Tomsgu** [comment]
Closing as there is no feedback.

**Comment by joshuapinter** [comment]
I ran into the exact same thing. This only occurred with very large PDFs. Initially I was getting the "Too many open files" error but after increasing my open file limits, I started getting this non-descript `Killed` message. 

To investigate, I ran `htop` while running a very large PDF generation and low and behold, this thing was so massive it ended up eating through my 32GBs of RAM and then started working on my Swap file. It's on Ubuntu so it's not a dynamic Swap file. You specify what size the Swap file is and it doesn't grow. 

Once the `wkhtmktopdf` command ate through all of the Swap file, it would quit with `Killed`. 

Ah ha!

So I increased the Swap file by a whopping 100GBs with the following commands: 

```bash
sudo dd if=/dev/zero of=/swapfile.img bs=1024 count=100M # Create 100GB Swap file at /swapfile.img.
sudo mkswap /swapfile.img                                # Setup the Swap filesystem for the file.
sudo echo "/swapfile.img swap swap sw 0 0" >> /etc/fstab # Add to filesystem config so it persists.
sudo reboot                                              # Reboot to take effect.
# ...reconnect...
free -mh                                                 # To confirm increased Swap size.
```

After doing this, the `wkhtmltopdf` command was able to finish successfully. This might be an edge case but we were generating PDFs that were 10,000+ pages.
