### ISSUE TITLE
Support for Chinese font

### ISSUE THREAD

**Issue by resting** [wkhtmltopdf/wkhtmltopdf#2128]
I've been trying to get a sample screenshot of a chinese webpage with
```
wkhtmltoimage --encoding "utf8" http://www.baidu.com/cache/sethelp/index.html baidu.jpg
```
However, the fonts are all rendered in blocks.
I can see the chinese characters when I do a `curl` of that page.
What am I missing?

Using amazon linu. with wkhtmltoimage 0.12.1 (with patched qt)
Also, running the same command on my mac works well.

**Comment by ashkulz** [comment]
You'll have to ensure that the Chinese fonts are installed locally.
