### ISSUE TITLE
Table td background gradients fail when td heights vary

### ISSUE THREAD

**Issue by kodeo** [wkhtmltopdf/wkhtmltopdf#2129]
When a CSS background gradient is applied to td elements which vary in height, gradients appear erroneously offset and wrapped.

e.g.

    <style>
      table {
        width: 400px;
        border-collapse: collapse;
      }
      td {
        height: 100px;
        background: -webkit-linear-gradient(top, #ccc 0%, #888 100%);
        border: 1px solid Black;
      }
      td.alt {
        height: 60px;
        background: none;
      }
    </style>

    <table>
      <tr>
        <td></td>
      </tr>
      <tr>
        <td class="alt"></td>
      </tr>
      <tr>
        <td></td>
      </tr>
    </table>

http://jsfiddle.net/b3k5m08k/

Expected:
![wk-issue-chrome-html](https://cloud.githubusercontent.com/assets/996340/5615429/29957896-94f3-11e4-8e77-0593eca63fed.png)

Observed:
![wk-issue-wk-pdf](https://cloud.githubusercontent.com/assets/996340/5615435/35111cd4-94f3-11e4-9080-a06d1aad16a4.png)

**Comment by ashkulz** [comment]
Please check if this gives a correct result with `0.13`.

**Comment by kodeo** [comment]
With 0.13 the issue is different but still not correct. The gradient appears to span all shaded tds rather than each one individually.

**Comment by ashkulz** [comment]
Then that is a bug in Qt/WebKit, as `0.13` uses the latest Qt version.

**Comment by kodeo** [comment]
I don't understand how the fact there's a different bug in 0.13 proves that the original issue is with Qt/Webkit. Can this theory be tested properly? The issue is not in evidence using https://code.google.com/p/qtweb/ for example.
