### ISSUE TITLE
Mapbox maps not loading correctly

### ISSUE THREAD

**Issue by xdhmoore** [wkhtmltopdf/wkhtmltopdf#2132]
In our application, mapbox maps will not load all of their tiles when using wkhtmltopdf, while they load correctly in Chrome with the same sizing settings.  Any idea of why this might be?  Here's another page that isn't working with wkhtmltopdf, though I can't be sure it's the same cause:

 https://www.openstreetmap.org/#map=7/43.253/-73.872
```Batchfile
wkhtmltopdf --javascript-delay 30000 --no-stop-slow-scripts https://www.openstreetmap.org/#map=7/43.253/-73.872 out.pdf
```

**Comment by ashkulz** [comment]
See [How to tell when all visible tiles have fully loaded?](http://stackoverflow.com/questions/22288933/how-to-tell-when-all-visible-tiles-have-fully-loaded) and use a custom `--window-status` to wait till everything is loaded.

**Comment by xdhmoore** [comment]
I don't think it's a matter of not waiting long enough.  On our page I can set `--javavascript-delay 600000` to wait 10 minutes and it still doesn't load all of the tiles.

**Comment by xdhmoore** [comment]
Perhaps there is a limit to the # of ajax requests or a memory bug associated with them?  I often get errors like 
>>Warning: Received createRequest signal on a disposed ResourceObject's NetworkAccessManager.  This migth be an indication of an iframe taking to long to load."

I've also tried `--debug-javascript`, but that didn't show any errors.  Is it possible there are js errors that aren't getting recorded and displayed when using the `--debug-javascript` option?
