### ISSUE TITLE
How can we use the wkhtmltox.dll with VB6?

### ISSUE THREAD

**Issue by fonzmark** [wkhtmltopdf/wkhtmltopdf#2133]
I wrote a VB6 to loop through any folder and find all HTM files and convert them to PDFs. I am looping through the folder and doing a commandline call to wkhtmltopdf.exe passing the page size, input and output files/path.  This is working well except for one issue. 

The wkhtmltopdf.exe opens a command or "DOS" window for each conversion and on a large run it causes a lot of screen activity with blinking when the window opens and closes. It is disturbing because it is hard to select any minimized application. I am running this in Win 7/64Bit

1.  Is there a way to suppress the command window blinking or how can I use /call the DLL? 
2.  What declaration to I need and what are the functions to call? 

Please help. 

Regards
Mark

**Comment by ashkulz** [comment]
Please ask usage questions on StackOverflow or the mailing list, this is not a help forum.
