### ISSUE TITLE
Get a lot of "cmap table of format 10 not implemented" when html has ☑︎ or ☐ chars

### ISSUE THREAD

**Issue by josephks** [wkhtmltopdf/wkhtmltopdf#2138]
This bug is present in the master branch (as of fcde6eabb61d7bdff761623e580481e345d98960).

When I run wkhtmltopdf on this html file:
```
<html><head>
<meta charset="utf-8">
<title>title ho</title></head>
<body>
 checkbox: ☑︎
 empty box: ☐ 
  →
½⌘↓
</body>
</html>
```

I get a bunch of "cmap table of format 10 not implemented" output to STDERR.  Doing a `wc -l` on the STDERR output counts 65543 lines (around 5 of those are not this message).

The other unicode chars are not a problem, only the checkbox and the empty box.

My system:

`Darwin <snip> 13.4.0 Darwin Kernel Version 13.4.0: Sun Aug 17 19:50:11 PDT 2014; root:xnu-2422.115.4~1/RELEASE_X86_64 x86_64`

**Comment by ashkulz** [comment]
Which platform are you on? It looks like a bug in Qt itself, the latest code still [has this issue](https://github.com/qtproject/qtbase/blob/5c5f43e95b8f56d2bdf34cf5c11aae9d5102f9c6/src/gui/text/qfontengine.cpp#L1324). You might want to report a bug upstream.

**Comment by josephks** [comment]
That looks like a debug message, so maybe part of the issue is that my qt library isn't configured/compiled correctly.

**Comment by josephks** [comment]
My copy of wkhtmltopdf came from http://wkhtmltopdf.googlecode.com/files/wkhtmltopdf-0.9.9-OS-X.i368

**Comment by josephks** [comment]
OK I tried with wkhtml built from source and I just downloaded http://sourceforge.net/projects/wkhtmltopdf/files/0.12.2/wkhtmltox-0.12.2_osx-carbon-i386.pkg/download and both have the same problem.

**Comment by ashkulz** [comment]
It is specific to the font you are using, it is using some different encoding.
