### ISSUE TITLE
is bug or not?  -  images are negative but html img is perfect at 0.13

### ISSUE THREAD

**Issue by ispir2000** [wkhtmltopdf/wkhtmltopdf#2139]
Hi friends, 
I m trying 0.13 Alpha and 0.12 for my project.  
there is a problem with images. I created 2 pdf file both of version for same html file. 
is bug or not?  -  images are negative but html img is perfect at 0.13alpha
you will understand me when see image as attach.
please help me, 

![ekran alintisi](https://cloud.githubusercontent.com/assets/10434011/5644801/4203b450-9670-11e4-9055-7cdcc932e2de.PNG)

I can sent some code samples or more image, too.
platform is vs2013 - IIS7 - win8.1pro

so, 0.13a is better than 0.12 for memory management. it kill self from memory. 0.12 is still live and continue to use memory.

thanks,
V.Ispir

**Comment by ashkulz** [comment]
Do not report any bugs against 0.13 alpha (see what is said on the downloads page).
