### ISSUE TITLE
wkhtmltopdf - Can't copy images from output pdf

### ISSUE THREAD

**Issue by riteshjha** [wkhtmltopdf/wkhtmltopdf#2140]
Hi Friends,

The pdf generated from a HTML file with images is successfully created (and the image object is correctly added) but the user is not able to copy the image using acrobat reader. I could not find any option for it, however, it can be copied through adobe illustrator and can be saved to the drive successfully using acrobat pro (not an option in reader). 

When we reviewed the problem it seems there is a layer just above the image, a second image object of the same dimensions which may cause the behavior although we have not confirmed this.  This issue was originally created as issue #606 on the google group which has been shut down. We would appreciate any help or advice on compiling a binary that allows the user to copy images from the document via acrobat reader, etc.

Thanks,
Ritesh

**Comment by ashkulz** [comment]
It's most likely a problem with the Qt PdfWriter implementation, you can verify by seeing if it does the same thing with `0.13` alpha (in which case you are advised to report an issue upstream).

**Comment by riteshjha** [comment]
thanks for quick reply, i will check 0.13 and will let you know
