### ISSUE TITLE
wkhtmltoimage ignores --javascript-delay and --window-status

### ISSUE THREAD

**Issue by mo-gr** [wkhtmltopdf/wkhtmltopdf#2142]
Setting either --javascript-delay or --window-status has no effect in wkhtmltoimage. Regardless of the parameter value, the image seems to be always generated immediately. (wkhtmltopdf works as expected).

This is a problem for us because javascript based page setup is not complete when wkhtmltoimage generates the image.

**Comment by ashkulz** [comment]
Version? Platform? Example HTML/CSS which reproduces this issue?

**Comment by mo-gr** [comment]
Sorry for not giving you this info right away.

I can reproduce this with the 12.2 binaries for OSX (64 bit) and the official linux rpm builds.

Reproducible with the following html

```<html>
<body>
  <div id="main">
    foo
  </div>
  <script type="text/javascript" charset="utf-8">
    setTimeout(function(){
      document.getElementById('main').innerHTML = "bar";
    }, 1000);
  </script>
</body>
</html>
```

and the following command line

    wkhtmltoimage --javascript-delay 2000 index.html bar.png

I would expect the png to contain "bar" but it contains "foo"

**Comment by mo-gr** [comment]
Apparently the loader is not configured as a `mainLoader` in wkhtmltoimage. Therefore `--javascript-delay` and `--window-status` are not evaluated in `ResourceObject::loadFinished()`. I've patched the image converter to be a `mainLoader` and wkhtmltoimage works as expected. But the project is too complex for me to be sure, that this doesn't have any unwanted side effects.

So be a bit careful with the pull request ;-)

**Comment by ashkulz** [comment]
PR looks OK, this is a regression because of #1892. Good catch!

**Comment by stratosilva** [comment]
I have exactly the same problem described and I really need the fix urgently. I currently use the Windows x64 version and I have no way to build it myself, so I would appreciate if you could share with me somehow the files I need to patch to make --javascript-delay work for wkhtmltoimage. Thanks

**Comment by ashkulz** [comment]
The instructions on how to build your version are crystal clear and require only freely available tools. If it is that urgent, you should try to do it yourself. After all, this is an open source project :smile:

**Comment by stratosilva** [comment]
Indeed I could, but that would take time... Something scarce at present (I am involved in an Ebola Emergency project within my organization). I thought that it would be just one click to build it for someone who has all development environment ready, that's the reason I asked. In any case, I downloaded version 0.11 and it seems to work now, so it is not that urgent anymore. Thanks.

**Comment by ashkulz** [comment]
@stratosilva: use `0.12.1.2` instead, but it won't have the latest OpenSSL.

**Comment by ashkulz** [comment]
`0.12.2.1` has been released, which includes changes related to this issue.
