### ISSUE TITLE
font dependency failing

### ISSUE THREAD

**Issue by mindola** [wkhtmltopdf/wkhtmltopdf#2143]
On install, Im getting a font dependency error:
Failed dependencies: xorg-x11-fonts-75dpi is needed by wkhtmltox-1:0.12.2-1.x86_64

Using the following binary:
http://downloads.sourceforge.net/project/wkhtmltopdf/0.12.2/wkhtmltox-0.12.2_linux-centos6-amd64.rpm

The dpkg grep on our aws instance reveals:
dejavu-serif-fonts-2.33-5.8.amzn1.noarch
dejavu-sans-fonts-2.33-5.8.amzn1.noarch
xorg-x11-fonts-Type1-7.2-9.1.5.amzn1.noarch
urw-fonts-2.4-10.7.amzn1.noarch
ghostscript-fonts-5.50-23.1.6.amzn1.noarch
dejavu-fonts-common-2.33-5.8.amzn1.noarch

Is there another, specific font package that needs to be installed?

**Comment by maninzoo** [comment]
$ yum search 75dpi

maybe
======
xorg-x11-fonts-75dpi.noarch : A set of 75dpi resolution fonts for the X Window System.
xorg-x11-fonts-ISO8859-1-75dpi.noarch : A set of 75dpi ISO-8859-1 fonts for X.
xorg-x11-fonts-ISO8859-14-75dpi.noarch : ISO8859-14-75dpi fonts
xorg-x11-fonts-ISO8859-15-75dpi.noarch : ISO8859-15-75dpi fonts
xorg-x11-fonts-ISO8859-2-75dpi.noarch : A set of 75dpi Central European language fonts for X.
xorg-x11-fonts-ISO8859-9-75dpi.noarch : ISO8859-9-75dpi fonts

and then

$ sudo yum install xorg-x11-fonts-75dpi.noarch

**Comment by ashkulz** [comment]
So what is the issue? You need to install the pre-requisities ...

**Comment by mindola** [comment]
Thanks
