### ISSUE TITLE
I could not understand from the docs if there is a way to build a fully portable binary?is it possible?

### ISSUE THREAD

**Issue by elico** [wkhtmltopdf/wkhtmltopdf#2145]
Hey,
I have tried to build the application so it would be portable for another system but have not succeeded.
I ran "build.py posix-local", is it supported to build a fully portable version?

Thanks

**Comment by ashkulz** [comment]
Portable for another distro? You can't, see the download FAQ. You should be able to run it on same distro version across machines ... it should work with the next version as well, but it all depends on the versioning policies of your distribution.

**Comment by ashkulz** [comment]
A preview for the next release [`0.12.3-dev-79ff51e`](http://wkhtmltopdf.org/downloads.html#testing) is available, which has generic linux binaries with minimal dependencies. Please report back whether it works for you without any issues.

*Please note that the above downloads will be removed after the `0.12.3` release*.
