### ISSUE TITLE
--zoom doesn't work

### ISSUE THREAD

**Issue by juzzlin** [wkhtmltopdf/wkhtmltopdf#2147]
I can't see any difference when rendering e.g. www.google.com with different zoom values. 

There's also https://bugs.launchpad.net/ubuntu/+source/wkhtmltopdf/+bug/1391456 which indicates that this is a regression bug.

**Comment by ashkulz** [comment]
Try installing the official packages instead of the distribution-supplied packages, which are hopelessly outdated.

**Comment by juzzlin** [comment]
I used the latest official build for Windows myself. I just came across that Launchpad bug report when I was googling about the issue.

**Comment by juzzlin** [comment]
Never mind, it works now. It was just an issue with the PDF reader. This bug is invalid. Sorry.
