### ISSUE TITLE
How Can I Install wkhtmltopdf Silently on Windows 7?

### ISSUE THREAD

**Issue by AlexZhouAA** [wkhtmltopdf/wkhtmltopdf#2149]
I need to install wkhtmltopdf silently on Windows.
I've searched a lot, but no luck.

Please help me out.
Thanks

**Comment by ashkulz** [comment]
See [NSIS documentation]( http://nsis.sourceforge.net/Docs/Chapter3.html#installerusage) for that.

**Comment by abhishek77in** [comment]
Was figuring out the same. `wkhtmltopdf-0.9.9-installer.exe /S` does the silent install.
