### ISSUE TITLE
bundle OpenSSL for the Mac OS X target

### ISSUE THREAD

**Issue by ashkulz** [wkhtmltopdf/wkhtmltopdf#2150]
OpenSSL on OS X has been [deprecated since OS X 10.7](http://stackoverflow.com/questions/7406946/why-is-apple-deprecating-openssl-in-macos-10-7-lion) and is not updated anymore. We need to compile and link OpenSSL as a static library (similar to what is done for Windows) -- however, the version shipped with OS X has the ability to verify SSL certificates against the CA list in the system keychain [which would be not available](http://bugs.python.org/issue17128#msg181664).

There are solutions for this (e.g. [openssl-osx-ca](https://github.com/raggi/openssl-osx-ca), [certsync](http://landonf.bikemonkey.org/code/macosx/certsync.20130514.html)) but an evaluation needs to be done as to what is the best approach.

**Comment by ashkulz** [comment]
@npinchot, @mn4367: any inputs that you can provide would be appreciated :smile:

**Comment by ashkulz** [comment]
[Qt 5.5](https://wiki.qt.io/New_Features_in_Qt_5.5) introduced a new backend for SSL based on Secure Transport, compiling with it would be ideal rather than trying to bundle OpenSSL.

**Comment by ashkulz** [comment]
This has been implemented in the [new packaging system](https://github.com/wkhtmltopdf/packaging).

**Comment by rhuanbarreto** [comment]
So, this issue is solved on wkhtmltopdf 0.12.5?

**Comment by ashkulz** [comment]
Yes.
