### ISSUE TITLE
PDFs rendering without embedded fonts on 64-bit Cocoa build for OS X

### ISSUE THREAD

**Issue by ashkulz** [wkhtmltopdf/wkhtmltopdf#2151]
This is a continuation of #1545 as a fix for [QTBUG-10094](https://bugreports.qt.io/browse/QTBUG-10094) has been [merged for Qt 5.5](https://github.com/qtproject/qtbase/commit/517fb9026896f7ac20376f253babae5a7c57721d).

**Comment by ashkulz** [comment]
Already [submitted upstream](https://codereview.qt-project.org/103858) for inclusion in `Qt 4.8.7`.

**Comment by ashkulz** [comment]
@mn4367, @npinchot: I would appreciate feedback on the [64-bit Cocoa build](http://downloads.sourceforge.net/project/wkhtmltopdf/0.12.2.1/wkhtmltox-0.12.2.1-rc-bfe5111_osx-cocoa-x86-64.pkg) to confirm whether this issue has been resolved. Thanks :smile:

**Comment by ashkulz** [comment]
`0.12.2.1` has been released, which includes changes related to this issue.

**Comment by mn4367** [comment]
I did a quick test with a quite long document and I can confirm that fonts are now selectable :smile:.
