### ISSUE TITLE
text is corrupted while printing

### ISSUE THREAD

**Issue by eckovation** [wkhtmltopdf/wkhtmltopdf#2154]
I generate pdf file using the command below,

/usr/local/bin/wkhtmltopdf --page-width 72 --page-height 200 --margin-top 0 --margin-right 0 --margin-bottom 0 --margin-left 0 --encoding 'utf-8' [full_path_html] [full_path_pdf]

The output when I print it (using Java), comes something like below

![bug](https://cloud.githubusercontent.com/assets/5313561/5811839/3624dfd4-a083-11e4-9b5c-c6e91f7cd104.png)

Note : Printing using Adobe's reader seems fine.

Is this an encoding issue, or wkhtmltopdf issue or java-printing issue?

**Comment by ashkulz** [comment]
If it works fine with Adobe, can you try with a different reader e.g. MuPDF/Foxit Reader or a linux-based reader? If it works OK on all of them, it is very likely to be limitations in the Java printing (you might generate an image and print that instead).

**Comment by eckovation** [comment]
Thanks Ashish, for your reply. Will check that out.
