### ISSUE TITLE
When use --footer-spacing, html text body pass over the footer text.

### ISSUE THREAD

**Issue by hamacker** [wkhtmltopdf/wkhtmltopdf#2157]
I create a page with footer with text :
wkhtmltopdf.exe  --no-collate ^
 --images ^
 --enable-smart-shrinking ^
 --title "Fechamento de proposta" ^
 --page-size A4^
 --page-height 267mm^
 --page-width 200mm^
 --margin-bottom 5mm^
 --margin-left 5mm^
 --margin-right 5mm^
 --margin-top 30mm^
 --header-line ^
 --header-html cabecalho.html^
 --footer-font-size 8^
 --footer-spacing -5^
 --footer-line ^
 --footer-left "Fechamento de proposta"^
 --footer-right "fqpve007-rev01 - Pagina [page] de [topage]"^
 --print-media-type ^
 --background ^
 "sample.htm"^
 "sample.pdf"
But, ever --footer-left and --footer-right will be pass over with the html body text.  Like this:

![sample](https://cloud.githubusercontent.com/assets/9573776/5818922/9764320a-a0a0-11e4-8399-ba2d4febc0bc.png)

**Comment by ashkulz** [comment]
Use a larger `--margin-bottom` e.g. `2cm`

**Comment by hamacker** [comment]
Not ok.
When I use --margin-bottom, the bottom just go up, 20mm, 30mm, 40mm...
But the html text body still over the footer text, body text stay on top over footer text.
I try to use --page-height to decrease body text, but no results.

**Comment by hamacker** [comment]
--margim-bottom does not run fine with --footer-spacing in the same instruction.
I dont know why, but only remove  --footer-spacing and append --margim-bottom as 20mm then runs fine.

Thanks.
