### ISSUE TITLE
Footers of different sizes and --margin-bottom issue

### ISSUE THREAD

**Issue by garygreen** [wkhtmltopdf/wkhtmltopdf#2163]
If your using a callback url for `--footer-html=<url>` which decides the footer to use (depending on e.g. the page number) these footers might be of varying heights/sizes and therefore cut off/have to much spacing. This is an issue due to having to set the bottom margin at a per-document level. Is there any way / suggestions around this?

**Comment by ashkulz** [comment]
Nope, you have to specify a margin which is enough for the generated HTML.

**Comment by garygreen** [comment]
@ashkulz Having a fixed margin size for the *whole document* doesn't make sense if footers across your pages can have varying height sizes..... why can this not be done at a per-page level?

**Comment by leeroybrun** [comment]
@garygreen Did you find a solution? I'm facing the same problem.
