### ISSUE TITLE
conversion problem -> some elements at the wrong position in document

### ISSUE THREAD

**Issue by ozkankaa** [wkhtmltopdf/wkhtmltopdf#2165]
The document is valid in the v0.11rc1 and v0.13 alpha. But v0.12.x is not convert correctly. Some element displaying at wrong position in document. Screenshot attached in this post

![1](https://cloud.githubusercontent.com/assets/9528471/5856091/6c80a132-a248-11e4-9384-148b6074e3b1.png)
![2](https://cloud.githubusercontent.com/assets/9528471/5856092/6cff676a-a248-11e4-9bae-0ecc7ee09aef.png)

**Comment by alloylab** [comment]
have you tried this on 0.12.5?

**Comment by alloylab** [comment]
We are closing this out since we haven't heard from you. If you are still having this issue please feel free to re-open it. Thanks.
