### ISSUE TITLE
header/footer auto calculation height problem

### ISSUE THREAD

**Issue by sitobcn82** [wkhtmltopdf/wkhtmltopdf#2166]
I'm using wkhtmltopdf and I want to auto calculate the height of header-html files, the problem is that all the headers and footers of the pages, are dynamically added by user, and these headers contain images, so i can't fix the header height with 'header-spacing','footer-spacing' and 'margin-top' options because i don't know this values. 

I'm using version wkhtmltopdf 0.12.2.1 (with patched qt) in a linux based system. I see that in the past this problem was solved

wkhtmltopdf --lowquality --image-quality '100' --footer-html 'http://localhost/cc2/web/app.php/admin/report/footer_report/10/' --header-html 'http://localhost/cc2/web/app.php/admin/report/header_report/10/' 'http://localhost/cc2/web/app.php/admin/site/23/report_pdf/15-01-16/15-01-23/' '/var/www/html/cc2/web/reports/report_322.pdf'

**Comment by vdboor** [comment]
Do you have `<!doctype html>` in the header/footer templates too? When webkit renders those parts in quirks mode, many heights go wrong.

**Comment by ashkulz** [comment]
What @vdboor said is correct, please post your sample HTML/CSS if it doesn't work correctly with those changes.
