### ISSUE TITLE
Header Text Wrap

### ISSUE THREAD

**Issue by carr2424** [wkhtmltopdf/wkhtmltopdf#2170]
Hi,

I'm generating a PDF that contains a long string for the header text.  Is it possible to get the header text to wrap?  Right now the header text is getting cutoff.  

Thanks,
Mike

**Comment by alloylab** [comment]
What version? have you tried this on 0.12.5?

**Comment by alloylab** [comment]
We are closing this out since we haven't heard from you. If you are still having this issue please feel free to re-open it. Thanks.
