### ISSUE TITLE
Overlapping Images after automatic page break

### ISSUE THREAD

**Issue by simplias1** [wkhtmltopdf/wkhtmltopdf#2174]
First of all I want to thank you for your current developement. I have been using wkhtmltopdf successfully now since 4 years. Recently there have been some changes regarding ssl3 which forced me to switch to a newer version. My trouble now is:

My whole document has in total 40 pages:

1.) Version 11 of WkHTMLToPDF is having troubles with ssl3
2.) Version 12.0 is adding huge gaps and even creates empty pages.  I have not found a pattern here.
3.) Version 12.2.1 is having no issues with gaps any more, but now images are sometimes overlapping the text. :-(

What is good: Version 12.2 are now supporting a correct footer and header. 

If you want I can send you the footer, header and the body. => jan.hoeppner@simplias.com

the command I call : wkhtmltopdf.exe --header-spacing 10 --margin-bottom 10 --footer-html footer.html --header-html header.html body.html Document.pdf

I was glad if you could help me.

**Comment by rsteinwand** [comment]
Have you tried 13? That's where most of the development is now.

**Comment by simplias1** [comment]
Yes I have tried to work with Version 13 and the Qt 5.4. Unfortunately I was not able to find a patched qt 5.4 version. If you have it compiled for windows I was glad if you could provide it.

Results: Footer and Header are not working. The font is totally ignored and the images are somehow inverted from the color ?

We are now going back to version 11 and are also willing to contribute to this project, to get it to a state, that it works again. 

Do you have any hints on how to compile the local qt version that is referenced from the git project?

**Comment by Tomsgu** [comment]
I know this is an old issue, but is this working in 0.12.5?

**Comment by Tomsgu** [comment]
Closing as there is no feedback.
