### ISSUE TITLE
13.0-alpha THEAD not repeating on each page

### ISSUE THREAD

**Issue by rainabba** [wkhtmltopdf/wkhtmltopdf#2175]
Compared to 12.2, 13.0 has broken thead/table-header-group behavior (no header on n>1 pages).

This is code that's worked for me since IE6 and has worked with WKHTMLTOPDF since 11.x and is nothing special. I've confirmed this on a few other use-cases with the same table-header-group behavior but different code (to be sure it wasn't an isolated instance).

While checking for other instances, I found some major, new issues with page margin/padding and everything in all cases looks to be zoomed strangely (like 80%) compared to previous versions and how other browsers print (IE/FF). The latter two issues I wanted to run by you here before submitted new ones. Are those familiar, or should I edit this and submit them separately? I realize that 0.13 is alpha so I'm wondering if it's even too early to drop all this on you.

**Comment by ashkulz** [comment]
See the `0.13` roadmap, this is expected to happen in the 0.13-rc stage.

**Comment by ashkulz** [comment]
OTOH if you find rendering issues which are regressions compared to `0.12.x` which have nothing to do with the patched Qt, please do post them as that could be a blocker for upgrading to `0.13`.
