### ISSUE TITLE
html page incorrectly rendered

### ISSUE THREAD

**Issue by skatkov** [wkhtmltopdf/wkhtmltopdf#2176]
My html ends up being totally different from that you would expect it to be :)

https://gist.github.com/skatkov/db0490ce577230572d6c

here is that i get:
https://copy.com/r1zmnfxH0mQNqeZH

i'm totally clueless about reasons for such error, everything looks smooth during conversion:

```
$ wkhtmltopdf activity.html act2.pdf
Loading pages (1/6)
Counting pages (2/6)
Resolving links (4/6)
Loading headers and footers (5/6)
Printing pages (6/6)
Done
```

info:

```
$ brew cask info wkhtmltopdf
wkhtmltopdf: 0.12.2.1
wkhtmltopdf
http://wkhtmltopdf.org/
/opt/homebrew-cask/Caskroom/wkhtmltopdf/0.12.2.1 (14M)
https://github.com/caskroom/homebrew-cask/blob/master/Casks/wkhtmltopdf.rb
==> Contents
  wkhtmltox-0.12.2.1_osx-cocoa-x86-64.pkg (pkg)
```

**Comment by alloylab** [comment]
have you tried this on 0.12.5?

**Comment by alloylab** [comment]
We are closing this out since we haven't heard from you. If you are still having this issue please feel free to re-open it. Thanks.
