### ISSUE TITLE
outputing empty pdf

### ISSUE THREAD

**Issue by jujukid** [wkhtmltopdf/wkhtmltopdf#2177]
When running wkhtmltopdf on some phishing sites, I receive a blank pdf 1KB in size. 

Warning, this url is to a phishing site!!

```
$ wkhtmltopdf --encoding UTF-8 http://accountdept8.wix.com/openwebmail evil_phishing.pdf
Loading pages (1/6)
Counting pages (2/6)                                               
Resolving links (4/6)                                                       
Loading headers and footers (5/6)                                           
Printing pages (6/6)
Done                 
```

```
$ wkhtmltopdf -V
wkhtmltopdf 0.12.2.1 (with patched qt)
```

Am I just overlooking something simple or?

Julian

**Comment by pluobikis** [comment]
try --javascript-delay 5000 command. I always get blank pages on mine when this argument is not specified.

**Comment by Er3VoS** [comment]
I have the exact same issue even with -javascript-delay 5000 command.
Of course my html is generated by a pdf file that i wanted to parse and edit.
The initial conversion was made by pdf2htmlex.

When i was converting the initial pdf with http://pdftohtml.sourceforge.net/  i didn't have an issue but the html result wouldn't keep the pdfs format.

Any other solutions apart from --javascript-delay?

**Comment by Tomsgu** [comment]
`--javascript-delay` should work in this case.
