### ISSUE TITLE
border not rendered correctly

### ISSUE THREAD

**Issue by AbdoDabbas** [wkhtmltopdf/wkhtmltopdf#2178]
Hi
I'm using SVG inside html and want to convert the html to pdf.
Inside SVG i'm using "foreignobject" to write some html tags, when I put "border" and "background-color" for those elements it doesn't show when converting the html to PDF, I tried v11.0 rc2 it rendered them correctly but other things goes wrong, I need to use v0.12.x or v0.13 with the ability to render the border and background-color.

used wkhtmltopdf: v0.13 - 32bit
OS: windows 8.1

**Comment by alloylab** [comment]
have you tried this on 0.12.5?

**Comment by alloylab** [comment]
We are closing this out since we haven't heard from you. If you are still having this issue please feel free to re-open it. Thanks.
