### ISSUE TITLE
Different printing on windows and linux

### ISSUE THREAD

**Issue by lanlan-yang** [wkhtmltopdf/wkhtmltopdf#2184]
Same command:
wkhtmltopdf --page-size a3 http://localhost:8080/PDFTest/create_PDF.action /var/www/webapps/PDFTest/pdfFile/order.pdf

result for windows 8.1:
![image](https://cloud.githubusercontent.com/assets/9528957/5971059/a39d199e-a878-11e4-98b2-abf5b155a77c.png)

result for centos 5.5
![image](https://cloud.githubusercontent.com/assets/9528957/5971071/c99b1b1e-a878-11e4-93d9-b1592450e33a.png)

**Comment by lanlan-yang** [comment]
![image](https://cloud.githubusercontent.com/assets/9528957/5971968/dc2587f2-a88b-11e4-8c9b-1459cae7fbcc.png)

**Comment by fnicollet** [comment]
Hello,

Have you found a solution to this issue? I get the same kind of error. When I print in A4 on Windows, it fits perfectly, while on linux, it seems like everything is zoomed in

Thanks,
Fabien

**Comment by ashkulz** [comment]
It's the other way round, on Linux it prints at 75 dpi (native for WebKit) while on Windows it uses the desktop's DPI (which is normally 96 dpi). You can use `--zoom 0.78125` to get the same effect on Linux.

**Comment by fnicollet** [comment]
@ashkulz Thanks, that's perfect :)
