### ISSUE TITLE
Table of content - version 0.12.2.1

### ISSUE THREAD

**Issue by TiagoMestre-ChallengeIT** [wkhtmltopdf/wkhtmltopdf#2188]
I was trying the new version of wkhtmltopdf (0.12.2.1) and notice the toc option stop working, doesn't show a error or anything, the toc inst generated. I re-installed the version 0.12.1.2 and its working fine.

**Comment by ashkulz** [comment]
Can you post sample HTML/CSS with the command lines used?

**Comment by TiagoMestre-ChallengeIT** [comment]
I tried again today and it seems to be working. Most likely a problem on my end. Sorry for any inconvenience
