### ISSUE TITLE
dependancy issue : libicu48 on debian wheezy (7)

### ISSUE THREAD

**Issue by ncapeyron** [wkhtmltopdf/wkhtmltopdf#2190]
The dependancy to libicu48 is missing on debian 7 in the precompiled package provided.

+

make a link to /usr/local/bin/wkhtmltopdf in /usr/bin 

It's better :)

Thx

**Comment by ashkulz** [comment]
> The dependancy to libicu48 is missing on debian 7 in the precompiled package provided.

Let me check this, it could be because I was reusing the same chroot environment for the upgrade to Qt5 (where there is a dependency on it). 

> make a link to /usr/local/bin/wkhtmltopdf in /usr/bin 

That will never be done, as `wkhtmltox` is a foreign package (not in official repos) and hence should be installed in a separate hierarchy.

**Comment by ncapeyron** [comment]
> That will never be done, as wkhtmltox is a foreign package (not in official repos) and hence should be installed in a separate hierarchy.

Ok for the binary install directory but I think a symlink in /usr/bin is allowed... 
Anyway, it's a great piece of software :)

Thank you

**Comment by ashkulz** [comment]
A preview for the next release [`0.12.3-dev-79ff51e`](http://wkhtmltopdf.org/downloads.html#testing) is available, which has generic linux binaries with minimal dependencies. Please report back whether it works for you without any issues.

*Please note that the above downloads will be removed after the `0.12.3` release*.

**Comment by ashkulz** [comment]
[`0.12.3`](http://wkhtmltopdf.org/downloads.html#stable) has been released, which should contain the fix for this issue. Please report back if it is not solved with the above version.

*Note that the preview downloads mentioned above have been removed*.
