### ISSUE TITLE
Install failure on Ubuntu 14.04.1 LTS

### ISSUE THREAD

**Issue by dhughesbc** [wkhtmltopdf/wkhtmltopdf#2192]
Attempting to install on Ubuntu 14.04.1 LTS
```
wget http://downloads.sourceforge.net/project/wkhtmltopdf/0.12.2.1/wkhtmltox-0.12.2.1_linux-trusty-amd64.deb
sudo dpkg -i wkhtmltox-0.12.2.1_linux-trusty-amd64.deb
(Reading database ... 227800 files and directories currently installed.)
Preparing to unpack wkhtmltox-0.12.2.1_linux-trusty-amd64.deb ...
Unpacking wkhtmltox (0.12.2.1) over (0.12.2.1) ...
dpkg: dependency problems prevent configuration of wkhtmltox:
 wkhtmltox depends on xfonts-base; however:
  Package xfonts-base is not installed.
 wkhtmltox depends on xfonts-75dpi; however:
  Package xfonts-75dpi is not installed.

dpkg: error processing package wkhtmltox (--install):
 dependency problems - leaving unconfigured
Processing triggers for man-db (2.6.7.1-1) ...
Errors were encountered while processing:
 wkhtmltox
```

**Comment by ashkulz** [comment]
Use `apt-get install -f`, as there are additional dependencies.

**Comment by dhughesbc** [comment]
Thanks for the quick response. That fixed it.

**Comment by davidperezgar** [comment]
Hello, for me it didn't work, becous it showing
 sudo apt-get -f install wkhtmltox

gets errors:
Reading package lists... Done
Building dependency tree
Reading state information... Done
wkhtmltox is already the newest version.
You might want to run 'apt-get -f install' to correct these:
The following packages have unmet dependencies:
 wkhtmltox : Depends: xfonts-base but it is not going to be installed
             Depends: xfonts-75dpi but it is not going to be installed
E: Unmet dependencies. Try 'apt-get -f install' with no packages (or specify a solution).

Any idea? Thanks!

**Comment by nagarjunadn** [comment]
Use like this:
