### ISSUE TITLE
wkhtmltopdf 0.12.2.1 rendering ugly pixelated text / fonts (didn't happen in 0.11)

### ISSUE THREAD

**Issue by glfabro** [wkhtmltopdf/wkhtmltopdf#2193]
Greetings!

I'm having an issue with wkhtmltopdf, running on RHEL 6.6. Consider this HTML:

```html
<html>
<body>
 this is a text
 <h1> this is a bigger text </h1>
</body>
</html>
```
With static wkhtmltopdf version 0.11.0 rc1, running without ant extra parameters, I got this pdf:

![screenshotadobeoldtext](https://cloud.githubusercontent.com/assets/10851670/6044844/3eb3a6c0-ac7d-11e4-94e9-1b1343ad834f.png)

Which was perfectly fine. Now let's upgrade the wkhtmltopdf version. Since there aren't "generic" static builds available anymore, I downloaded wkhtmltopdf for CentOS 6 (the "equivalent" of my RHEL6). I installed the 64-bit RPM successfully and run it. 

So with the CentOS 6 64-bit wkhtmltopdf 0.12.2.1 (with patched qt), I get this: 

![screenshotadobenewtext](https://cloud.githubusercontent.com/assets/10851670/6044868/65019fee-ac7d-11e4-9d01-59d8826359f1.png)

As you can see, the font is very pixelated. 

I run strace on both executables and compared the results. I believe I caught the relevant part that's causing the difference, here: 

(left is 0.11.0 rc1, right is 0.12.2.1 (with patched qt):

![stracecompare](https://cloud.githubusercontent.com/assets/10851670/6044895/849b062e-ac7d-11e4-8bd6-88f826ed813a.png)

As you can see, for some reason while the 0.11 version uses the LiberationSans-Regular.ttf font as a "default" font (since my html has no css at all), the 0.12.2.1 version uses this timR12-ISO8859-1.pcf.gz font, which I think it's what is causing the problem. 

If I open the 0.11 generated PDF in Adobe Reader and go to File, Properties, Fonts, I see the LiberationSans (Embedded Subset) there:

![screenshotadobeold](https://cloud.githubusercontent.com/assets/10851670/6044911/9a593300-ac7d-11e4-9f60-67967e4c8796.png)

If I open the 0.12 and do the same, I just see a blank entry:

![screenshotadobenew](https://cloud.githubusercontent.com/assets/10851670/6044912/9e77fc32-ac7d-11e4-9485-73c20ac89999.png)

So:

- Why is wkhtmltopdf behaving this way? 
- Can I change the "default" font that wkhtmltopdf uses, in order to tell it to use the LiberationSans-Regular.ttf font if another font wasn't specified?

Thank you very much,
Gustavo

**Comment by ashkulz** [comment]
@glfabro: I really appreciate your detailed bug report :+1: The Qt/WebKit engine was upgraded in the `0.12.x` series. What does `fc-match sans-serif` and `fc-match serif` return? If it shows the other font, you'll have to change the fontconfig configuration to use the Liberation fonts.

**Comment by glfabro** [comment]
Thank you for the reply! 

Hmmm it returns another font:

<pre>
# fc-match sans-serif
n019003l.pfb: "Nimbus Sans L" "Regular"
# fc-match serif
n021003l.pfb: "Nimbus Roman No9 L" "Regular"
</pre>

By using 

<pre>
fc-list | grep -i "nimbus"
</pre>

I found that this font is indeed installed into the system. By checking where this particular font file is with

<pre>
fc-list -v > fonts.txt
</pre>

and then searching in the file for these two fonts I got this:

<pre>
        family: "Nimbus Sans L"(s)
        style: "Regular"(s)
        slant: 0(i)(s)
        weight: 80(i)(s)
        width: 100(i)(s)
        foundry: "urw"(s)
        file: "/usr/share/fonts/default/Type1/n019003l.pfb"(s)
        index: 0(i)(s)
</pre>

and

<pre>
        family: "Nimbus Roman No9 L"(s)
        style: "Regular"(s)
        slant: 0(i)(s)
        weight: 80(i)(s)
        width: 100(i)(s)
        foundry: "urw"(s)
        file: "/usr/share/fonts/default/Type1/n021003l.pfb"(s)
        index: 0(i)(s)
</pre>

which indicates the fonts are installed in the system. And by searching for the files indicated by strace (timR12-ISO8859-1.pcf.gz and timB24-ISO8859-1.pcf.gz) I got:

<pre>
Pattern has 17 elts (size 32)
        family: "Times"(s)
        style: "Regular"(s)
        slant: 0(i)(s)
        weight: 80(i)(s)
        width: 100(i)(s)
        pixelsize: 17(f)(s)
        foundry: "Adobe"(s)
        antialias: FcFalse(s)
        file: "/usr/share/X11/fonts/100dpi/timR12-ISO8859-1.pcf.gz"(s)
        index: 0(i)(s)
        outline: FcFalse(s)
        scalable: FcFalse(s)
        charset:
        0000: 00000001 ffffffff ffffffff 7fffffff 00000000 ffffffff ffffffff ffffffff
(s)
        lang: aa|ast|ay|bi|br|ch|da|de|en|es|eu|fj|fo|fur|fy|gd|gl|gv|ho|ia|id|ie|io|is|it|lb|mg|nb|nds|nl|nn|no|nr|oc|om|pt|rm|sma|smj|so|sq|ss|st|sv|sw|tl|ts|uz|vo|wa|xh|yap|zu|an|fil|ht|jv|kj|kwm|li|ms|ng|pap-an|pap-aw|rn|rw|sc|sg|sn|su|za(s)
        fontversion: 0(i)(s)
        fontformat: "PCF"(s)
        decorative: FcFalse(s)
</pre>

and

<pre>
Pattern has 17 elts (size 32)
        family: "Times"(s)
        style: "Bold"(s)
        slant: 0(i)(s)
        weight: 200(i)(s)
        width: 100(i)(s)
        pixelsize: 34(f)(s)
        foundry: "Adobe"(s)
        antialias: FcFalse(s)
        file: "/usr/share/X11/fonts/100dpi/timB24-ISO8859-1.pcf.gz"(s)
        index: 0(i)(s)
        outline: FcFalse(s)
        scalable: FcFalse(s)
        charset:
        0000: 00000001 ffffffff ffffffff 7fffffff 00000000 ffffffff ffffffff ffffffff
(s)
        lang: aa|ast|ay|bi|br|ch|da|de|en|es|eu|fj|fo|fur|fy|gd|gl|gv|ho|ia|id|ie|io|is|it|lb|mg|nb|nds|nl|nn|no|nr|oc|om|pt|rm|sma|smj|so|sq|ss|st|sv|sw|tl|ts|uz|vo|wa|xh|yap|zu|an|fil|ht|jv|kj|kwm|li|ms|ng|pap-an|pap-aw|rn|rw|sc|sg|sn|su|za(s)
        fontversion: 0(i)(s)
        fontformat: "PCF"(s)
        decorative: FcFalse(s)
</pre>

So from what I could understand, it appears the font being used to render the file is "Times", possibly not TrueType (because it is fixed at 100dpi), so that's why the render appears "ugly". 

But the fc-match command returns Nimbus, which again by what I could understand is a Type1 font, which is Vector based -> it would result in a good file. Why isn't wkhtmltopdf using it, and instead it is looking for this Times "bad" font?

**Comment by ragusa87** [comment]
I got the same issue with font beeing pixelated. The font used for Arial was not scalable:

```bash
$ fc-match "Arial"
LiberationSans-Regular.ttf: "Liberation Sans" "Regular"
```

However, I added a fontconfig directive to fix it.

```bash
nano /etc/fonts/conf.avail/70-no-bitmaps.conf
```
Then paste this
```xml
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<fontconfig>
<!-- Reject bitmap fonts -->
 <selectfont>
  <rejectfont>
   <pattern>
     <patelt name="scalable"><bool>false</bool></patelt>
   </pattern>
  </rejectfont>
 </selectfont>
</fontconfig>
```
Add a Symlink to enable the config
```bash
ln -s /etc/fonts/conf.avail/70-no-bitmaps.conf /etc/fonts/conf.d/70-no-bitmaps.conf
```
Clear cache
```bash
fc-cache
```

**Comment by cubells** [comment]
@ragusa87: your solution solve my problem on debian Jessie.

Thanks a lot!

**Comment by Maypeur** [comment]
@ragusa87 Wow, it solve my problem too, i'm on Debian Jessie too.
But file 70-no-bitmaps.conf already exists but it is empty. 
The symlink already exists.

**Comment by ragusa87** [comment]
@maypeur always happy to help.

**Comment by hectorh30** [comment]
@ragusa87 thanks a lot! Got me going here on a Debian 8 as well

**Comment by glfabro** [comment]
Just as a follow up, the sysadmins eventually upgraded the server to RHEL7 and this was no longer a problem with that OS.

Anyhow, I was happy to see that other people were facing this problem with Debian here and ragusa87's solution solved those issues, so that was nice! :)

**Comment by toupeira** [comment]
Also see https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=776801

The proper workaround is to run `dpkg-reconfigure fontconfig-config`, which fixes the symlink to point to `/usr/share/fontconfig/conf.avail/70-no-bitmaps.conf`

**Comment by seanwmitchell** [comment]
> I got the same issue with font beeing pixelated. The font used for Arial was not scalable:
> 
> ```shell
> $ fc-match "Arial"
> LiberationSans-Regular.ttf: "Liberation Sans" "Regular"
> ```
> 
> However, I added a fontconfig directive to fix it.
> 
> ```shell
> nano /etc/fonts/conf.avail/70-no-bitmaps.conf
> ```
> 
> Then paste this
> 
> ```
> <?xml version="1.0"?>
> <!DOCTYPE fontconfig SYSTEM "fonts.dtd">
> <fontconfig>
> 
>  <selectfont>
>   <rejectfont>
>    <pattern>
>      <patelt name="scalable"><bool>false</bool></patelt>
>    </pattern>
>   </rejectfont>
>  </selectfont>
> </fontconfig>
> ```
> 
> Add a Symlink to enable the config
> 
> ```shell
> ln -s /etc/fonts/conf.avail/70-no-bitmaps.conf /etc/fonts/conf.d/70-no-bitmaps.conf
> ```
> 
> Clear cache
> 
> ```shell
> fc-cache
> ```

Thanks, that fixed my issue
