### ISSUE TITLE
Debugging QT in a static build

### ISSUE THREAD

**Issue by TripleEmcoder** [wkhtmltopdf/wkhtmltopdf#2194]
I have compiled wkhtmltopdf with `scripts\build.py msvc2013-win64 -clean -debug` and I am able to nicely step through `wkhtmltopdf.cc` and other project source files, but whenever I reach anything in QT, like trying to step into `QWebPage` from `multipageloader.cc` the debugger just steps over. Is it possible to build the static version of wkhtmltopdf with QT debug-enabled?

We are facing a serious, seemengly random bug that only repros in our environment, so debugging is probably the only option of solving this.

**Comment by ashkulz** [comment]
Can you check if you can debug `0.12.1` as I am pretty sure it worked earlier? Will only be able to check over the weekend.

**Comment by TripleEmcoder** [comment]
I did a clean debug build of 0.12.1 and unfortunately it behaves the way I described.

**Comment by perorumov** [comment]
Any update on this ?

**Comment by ashkulz** [comment]
@perorumov: does it not work for you?

**Comment by perorumov** [comment]
No. It is same situation as TripleEmcoder  described. Maybe -webkit-debug is missing.

**Comment by ashkulz** [comment]
This was due to a bug in Qt, which I will try to upstream although it is unlikely to be merged as Qt 4.8.7 is the last release in the 4.8.x series.

**Comment by ashkulz** [comment]
@TripleEmcoder: sorry about getting to this so late, it slipped off my radar. Were you able to diagnose your random bug?
