### ISSUE TITLE
all text is rendered as squares even when fonts are installed locally on linux

### ISSUE THREAD

**Issue by er1catr1pp** [wkhtmltopdf/wkhtmltopdf#2197]
I'm using an aws linux server, and I have the latest version of wkhtmltopdf with patched qt.

[ec2-user@ip-172-31-32-100 ~]$ wkhtmltopdf --version
wkhtmltopdf 0.12.2.1 (with patched qt)

Even a simple test.html (shown below) renders the font as squares:

```
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Hello World</title>
    </head>
    <body>
        <h1>Hello World</h1>
    </body>
</html>
```

I have made sure that I have fonts installed locally, and I've even tried packaging fonts within a rails app and using wicked_pdf.

[ec2-user@ip-172-31-32-100 menuzest]$ fc-list
Verdana:style=Regular,Normal,obyčejné,Standard,Κανονικά,Normaali,Normál,Normale,Standaard,Normalny,Обычный,Normálne,Navadno,Arrunta
Candara:style=Italic
Consolas:style=Italic
Utopia:style=Bold Italic
Nimbus Sans L:style=Regular Italic
DejaVu Serif,DejaVu Serif Condensed:style=Condensed,Book
Times New Roman:style=Regular,Normal,obyčejné,Standard,Κανονικά,Normaali,Normál,Normale,Standaard,Normalny,Обычный,Normálne,Navadno,thường,Arrunta
Webdings:style=Regular
...

Here are the results of my simple command line test:

```
[ec2-user@ip-172-31-32-100 ~]$ wkhtmltopdf test.html test.pdf
Loading pages (1/6)
Counting pages (2/6)                                               
Resolving links (4/6)                                                       
Loading headers and footers (5/6)                                           
Printing pages (6/6)
Done                  
```

![test](https://cloud.githubusercontent.com/assets/2181975/6098376/ec0c8802-b00e-11e4-8216-931752f63022.png)

Thanks for the help and for the great tool!

**Comment by alloylab** [comment]
have you tried this on 0.12.5?

**Comment by alloylab** [comment]
We are closing this out since we haven't heard from you. If you are still having this issue please feel free to re-open it. Thanks.
