### ISSUE TITLE
Problem with building from source on Debian 8

### ISSUE THREAD

**Issue by andrewshkovskii** [wkhtmltopdf/wkhtmltopdf#2198]
For now i'am trying to build wkhtmltopdf from source code ad debian 8

LSB Version:	core-2.0-amd64:core-2.0-noarch:core-3.0-amd64:core-3.0-noarch:core-3.1-amd64:core-3.1-noarch:core-3.2-amd64:core-3.2-noarch:core-4.0-amd64:core-4.0-noarch:core-4.1-amd64:core-4.1-noarch:security-4.0-amd64:security-4.0-noarch:security-4.1-amd64:security-4.1-noarch
Distributor ID:	Debian
Description:	Debian GNU/Linux 8.0 (jessie)
Release:	8.0
Codename:	jessie

And at step ./build.sh i got an error:
`LD_LIBRARY_PATH=../../bin/ ../../bin/wkhtmltoimage --manpage | gzip > /var/projects/declarations/tmp/wkhtmltopdf/static-build/jessie-amd64/dist/share/man/man1/wkhtmltoimage.1.gz
install -m 755 -p "../../bin/wkhtmltoimage" "/var/projects/declarations/tmp/wkhtmltopdf/static-build/jessie-amd64/dist/bin/wkhtmltoimage"
strip "/var/projects/declarations/tmp/wkhtmltopdf/static-build/jessie-amd64/dist/bin/wkhtmltoimage"
make[1]: Leaving directory '/var/projects/declarations/tmp/wkhtmltopdf/static-build/jessie-amd64/app/src/image'
./build.sh: line 20: /fpm_package.sh: No such file or directory`

And there is no fpm_package.sh file on FS. fpm gem installed for schroot and my user.
Where should i get fpm_package.sh ?

**Comment by ashkulz** [comment]
Did you set up the schroot environments correctly? Read the build instructions for linux, they are very detailed (you are not building in `/home`).
