### ISSUE TITLE
Set page size from CSS @page size

### ISSUE THREAD

**Issue by shaunlebron** [wkhtmltopdf/wkhtmltopdf#2200]
CSS3 allows the definition of [page size](http://www.w3.org/TR/css3-page/#page-size-prop):

```html
<html>
<head>
<style>
@page {
  size: letter;
}
</style>
</head>
<body>
Hello World
</body>
</html>
```

Ideally, we could run `wkhtmltopdf --page-size css` to use the page's own size preference.

**Comment by shaunlebron** [comment]
Spitballing here, but I suppose we can retrieve this value in the JS context of the page. We can the page size by searching for `i` and `j` such that:

```js
document.styleSheets[i].cssRules[j].selectorText == "@page"
```

And then retrieve the size:

```js
document.styleSheets[i].cssRules[j].style.size
```

Haven't done much digging on how to get that value back out of the JS context

**Comment by shaunlebron** [comment]
This is also supported by Prince:
http://www.princexml.com/doc/page-size/

**Comment by ashkulz** [comment]
This is not supported in WebKit, so no chance of it being implemented in wkhtmtlopdf.

**Comment by leducvin** [comment]
As per https://webkit.org/css-status/#, this is now supported in WebKit. So, it should work in wkhtmltopdf? Or it needs implementation on the wkhtmltopdf side?
