### ISSUE TITLE
Using an unsupported DPI option results in crash

### ISSUE THREAD

**Issue by J4G-** [wkhtmltopdf/wkhtmltopdf#2203]
I was experimenting with wkhtmltopdf and noticed that using a non-standard DPI value (such as 50) results in a crash.

**Comment by ashkulz** [comment]
Which version are you using?

**Comment by J4G-** [comment]
Originally found on 0.12.0 (Win 64 bit) and later tested on 0.12.2.1 which does not have the problem. My apologies, I didn't realize I was a couple versions behind.
