### ISSUE TITLE
Empty string in PDF

### ISSUE THREAD

**Issue by alemih** [wkhtmltopdf/wkhtmltopdf#2205]
I'm trying wkhtmltopdf 0.12.2.1 (with patched qt) on Centos 6.6.

I make simple html with large text (to fill whole page A4):

`<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">`
`<html>`
`<head>`
`<meta http-equiv="Content-Type" content="text/html; charset=utf-8">`
`<style type='text/css'>`
`td  {font-family:Arial; font-size:11px; text-align:justify;}`
`</style>`
`</head>`
`<body>`
`<table border="0" cellspacing="0" cellpadding="0" style="width:180mm;" align="center">`
`<tr><td>Test test ..... (many words to fill a whole page)</td></tr>`
`</table>`
`</body>`
`</html>`

command: wkhtmltopdf --zoom 1.25 test.html test.pdf.
In the result pdf near the end of the page (for me it was about 15 lines before) I've an emty string in the middle of a text.
I've trying to use --zoom because in issue #1527 was an advice how to improve kerning of smaller fonts. And it's really improve(become much better), but appears another problem...
Thanks.

**Comment by alloylab** [comment]
have you tried this on 0.12.5?

**Comment by alloylab** [comment]
We are closing this out since we haven't heard from you. If you are still having this issue please feel free to re-open it. Thanks.
