### ISSUE TITLE
viewBox injection 

### ISSUE THREAD

**Issue by DKanarsky** [wkhtmltopdf/wkhtmltopdf#2206]
Hello! I use wkhtmltoimage to convert html pages to svg. It's a great issue! 
However, i noticed that an output svg document had different from origin html page size in browser. And the reason is because of injection of viewBox. Something like that: <svg width="370.417mm" height="1721.91mm"
 viewBox="0 0 1050 4881" ...

Is there any way to avoid it through settings? 

Thank you and sorry for my English...

**Comment by alloylab** [comment]
What version? have you tried this on 0.12.5?

**Comment by alloylab** [comment]
We are closing this out since we haven't heard from you. If you are still having this issue please feel free to re-open it. Thanks.
