### ISSUE TITLE
Version 0.12 stream crash issue

### ISSUE THREAD

**Issue by marmie1** [wkhtmltopdf/wkhtmltopdf#2209]
Code below:

StreamWriter stdin;
            ProcessStartInfo psi = new ProcessStartInfo();
            psi.FileName = this.workingDirectory + "wkhtmltopdf.exe";
            psi.UseShellExecute = false;
            psi.CreateNoWindow = true;
            psi.RedirectStandardInput = true;
            psi.RedirectStandardOutput = true;
            psi.RedirectStandardError = false;
            psi.Arguments = arguments;
            
            try
            {
                this.PrintingProcess = Process.Start(psi);
                this.OutputStream = new MemoryStream();
                stdin = PrintingProcess.StandardInput;
                stdin.AutoFlush = true;
                var rendered = this.BodyContents.Render();
                stdin.Write(rendered);                              
                stdin.Dispose();
                PrintingProcess.StandardOutput.BaseStream.CopyTo(this.OutputStream);
                PrintingProcess.WaitForExit(120000); 
            }
            catch (Exception e)
            {
                return;
            }

The problem is that wkhtmltopdf crashed everytime I copy Stream to outputStream. Worked well with 0.11 but not with 0.12.2. It did worked well with cmd so the issue must be at the Stream handling.

I've tried to modify psi's and the configuration. Also tried to write Stream in multiple different ways but it didn't work. Any ideas?

**Comment by ashkulz** [comment]
What is the crash? Please make a debug build and post the stack trace/exception, see `INSTALL.md` on how to make such a build.

**Comment by marmie1** [comment]
Found issue elsewhere. Wkhtmltopdf still rocks!
