### ISSUE TITLE
wkhtmltopdf  loading pages error

### ISSUE THREAD

**Issue by aravindsmg** [wkhtmltopdf/wkhtmltopdf#2211]
i am running the wkhtmltopdf from a powershell script.
the command i am using is 

& "C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe"    "C:\Desktop\Test.htm"  "C:\Desktop\Report.pdf"

the pdf file is getting created but it is also throwing an error as :Exception: Loading pages (1/6)
due to which i am unable to proceed further as the script is returning error.
please suggest help on this.

**Comment by alloylab** [comment]
What version? have you tried this on 0.12.5?

**Comment by alloylab** [comment]
We are closing this out since we haven't heard from you. If you are still having this issue please feel free to re-open it. Thanks.
