### ISSUE TITLE
Building binary in centos fails

### ISSUE THREAD

**Issue by evildav** [wkhtmltopdf/wkhtmltopdf#2212]
Hey Ashish,

I tried to build binary in centos 6 with tiff library support and the below is what I get.

~/build/wkhtmltox-0.12.2.1> sudo scripts/build.py setup-schroot-centos6
Traceback (most recent call last):
File "scripts/build.py", line 1289, in <module>
main()
File "scripts/build.py", line 1286, in main
globals()['build_%s' % BUILDERS[config]](final_config, basedir)
File "scripts/build.py", line 771, in build_setup_schroot
install_packages('git', 'debootstrap', 'schroot', 'rinse', 'debian-archive-keyring')
File "scripts/build.py", line 752, in install_packages
lines = get_output('dpkg-query', '--list').split('\n')
AttributeError: 'NoneType' object has no attribute 'split'

I think this is because install_packages uses 'dpkg-query' to find the list of installed packages which sadly isn't the one available in centos. It should be using 'rpm -q'. 

I was just wondering if the INSTALL.md file isn't rightly updated. Were you planning on building the support for centos in the later versions(0.13 may be)?

**Comment by ashkulz** [comment]
Read the second paragraph, which states
> Building is supported only on 64-bit Debian Jessie (i.e. testing release)
