### ISSUE TITLE
php + apache chroot environment, loading header/footer stops at %20

### ISSUE THREAD

**Issue by antuxity** [wkhtmltopdf/wkhtmltopdf#2216]
I try to generate 150+  pages PDF document with a footer.html (below) running chroot apache.  The footer has some JS to render page number.  When I try to run it through php exec(), it will stop at 

Loading headers and footers (5/6)
[=======>                                     ] 20%.  

This works fine if to generate only 7 pages.   This also works fine if I removed the javascript part (with 150+ pages).  I did try `-javascript-delay <msec>` `--no-stop-slow-scripts`, but no luck

Using  command line in terminal works fine, but doesn't work with chroot apache + PHP.  Also font-family does not work, it only generates pdf using default San-serif, i suspect because the chroot environment does not have the font file, but where does wkhtmltopdf look for font files?

Any ideas? Any helps would be great. 
Thanks

footer.html

``` html
<!DOCTYPE html>
<html>
    <head>
<script>
window.onload = function() {
    var vars={};
    var x=window.location.search.substring(1).split('&');
    for (var i in x) {var z=x[i].split('=',2);vars[z[0]] = unescape(z[1]);}
    var x=['frompage','topage','page','webpage','section','subsection','subsubsection'];
    for (var i in x) {
        var y = document.getElementsByClassName(x[i]);
        for (var j=0; j<y.length; ++j) 
            y[j].textContent = vars[x[i]];
    }
};
</script>
<style>
.circle{
    font-weight:bold;
    background:white;
    color: #005bab;
    border-radius: 20px;
    vertical-align:middle;
    text-align:center;
    vertical-align:middle;
    position:relative;
    height:40px;
    width: 40px;
    font-size: 12pt;
}
table{
    font-size: 9pt;
        color: white;
    background:#005bab;
    height: 60px;
    width:105%;
    position:relative;
    left: -10px;
    top: 10px;
}
td.l{
    padding-left: 80px;
}
td.m{
    text-align:right;
}
td.r{
    width: 5%;
    padding-right: 100px;
    text-align:right;
}
.page{
    position: relative;
    top: 8px;
    vertical-align:middle;
}
strong{
    padding: 0 5px;
}
</style>
</head>
<body style="border:0; margin: 10px;">
<table>
    <tr>
        <td class="l">TEXT</td>
        <td class="m">TEXT</td>
        <td class="r"><div class="circle"><span class="page">999<span></div></td>
    </tr>
</table>
</body>
</html>
```

**Comment by DamienMure** [comment]
I've been ask to make wkhtmltopdf to work in php-fpm chroot under debian jessie.

I had to bind "/etc/fonts", "/usr/share/fontconfig" and "/usr/share/fonts" into my chroot in order to get nice characters instead of blacks squares...

You can trace syscall using "strace" to learn what wkhtmltopdf is looking for and what is missing.

**Comment by antuxity** [comment]
thanks, I will try your suggestion.

**Comment by Tomsgu** [comment]
Closing as the answer was provided.
