### ISSUE TITLE
--window-status not working, is ignored

### ISSUE THREAD

**Issue by pyriand3r** [wkhtmltopdf/wkhtmltopdf#2217]
Hi,
I'm using wkhtmltopdf / wkhtmltoimage 0.12.2.1 to generate images from a webpage. The page has to load a bunch of javascript files which render the page and paint objects, do some request and stuff, so it takes a time for the page to ready for the image. To be dynamic i tried the `--window-status 'ready'` flag and inside one of my javascript files i set `window.status = 'ready'` to trigger the capturing. But wkhtmltopdf/image does not wait for this to happen. It runs through the html template of the page and when it reaches the end it takes the picture. Even if i set inside the html-file inside script-tags the `window.status = 'ready'` it will ignore it and go on with the execution of the scripts until it reaches the end of the html-file. So am i doing something wrong or is it a bug?

Note: I'm on sles11 so i had to install the libjpeg8 library manually. wkhtmltopdf/image comes via composer.

Here are some of the shell commands i tried:

    /path/to/vendor/h4cc/wkhtmltopdf-amd64/bin/wkhtmltopdf-amd64 --window-status ready https://127.0.0.1/rest/private/map/standalone/0022/0 /home/test/test.pdf

    /path/to/vendor/h4cc/wkhtmltoimage-amd64/bin/wkhtmltoimage-amd64 --format png --no-stop-slow-scripts --javascript-delay 10000 --window-status ready --debug-javascript https://127.0.0.1/rest/private/map/standalone/0022/0 /home/test/test.png

**Comment by pyriand3r** [comment]
Any comments on this? Really need the info about this problem (or better a solution :) )

**Comment by ashkulz** [comment]
Post the actual HTML which doesn't work for you.

**Comment by pyriand3r** [comment]
Oh well, the file is very large, so here's only a short version of it:

    <!DOCTYPE html>
    <html>
    <head lang="en">
        <meta charset="UTF-8">
        <title>SNAG-View Map Standalone</title>
        <style type="text/css">
            #date {
                position: fixed;
                top: 5px;
                left: 5px;
                z-index: 1000;
            }
        </style>
    </head>
    <body>
    <div id="date">{{ date }}</div>

    </body>
    <script src="../../../../../../modules/map/include/assets/0-ext5/ext-all-sandbox-debug.js"></script>

    <script>
        /**
         * here are some javascript namespaces defined that the js-classes expect to be defined
         */
        var Ext = Ext5;

        /**
         *  ...
         */

    </script>

    <script src="../../../../../../js/system/ux/util/AutoLoader/AutoLoader.js"></script>

    <script src="../../../../../../modules/map/include/assets/1-lib/canvg.js"></script>
    <script src="../../../../../../modules/map/include/assets/1-lib/Class.js"></script>
    <script src="../../../../../../modules/map/include/assets/1-lib/jquery-1.10.2.min.js"></script>
    <script src="../../../../../../modules/map/include/assets/1-lib/jquery.autoresize.js"></script>
    <script src="../../../../../../modules/map/include/assets/1-lib/jquery.contextmenu.js"></script>
    <script src="../../../../../../modules/map/include/assets/1-lib/jquery-touch_punch.js"></script>
    <script src="../../../../../../modules/map/include/assets/1-lib/json2.js"></script>
    <script src="../../../../../../modules/map/include/assets/1-lib/pathfinding-browser.min.js"></script>
    <script src="../../../../../../modules/map/include/assets/1-lib/raphael.js"></script>
    <script src="../../../../../../modules/map/include/assets/1-lib/rgbcolor.js"></script>
    <script src="../../../../../../modules/map/include/assets/1-lib/shifty.js"></script>
    <script src="../../../../../../modules/map/include/assets/1-lib/StackBlur.js"></script>
    <script src="../../../../../../modules/map/include/assets/2-draw2d/draw2d.js"></script>

    


    <script>
        /**
         * Bootstrap the drawPanel with a provided svid of a map and set servertime if provided
         */
        (function (Ext3, Ext) {
            Ext.Ajax.on('beforerequest', function (connection, options) {
                options.headers = {
                    Authorization: 'Basic ' + btoa('name:pass')
                }
            });


            Ext.onReady(function () {
                Ext.create('pyriand3r.drawPanel.DrawPanel', {
                    renderTo: Ext.getBody(),
                    viewOnly: true,
                    svid: '{{ svid }}'
                });
            });

        })(Ext, Ext5);

    </script>

    </html>

Inside one of the javascript files i set window.status to 'ready', but this is not recognized by wkhtmltopdf/image.

**Comment by ashkulz** [comment]
Without a small reduced testcase which can show the problem, I'm more inclined to believe it is a problem in your code and not in `wkhtmltopdf`.

**Comment by Davidhw** [comment]
I had this problem and was able to avoid it by moving where I added my toc (table of contents) parameter. By going from
./wkhtmltopdf toc --window-status THISSTATUSWONTHAPPEN http://google.com out.pdf
to
./wkhtmltopdf --window-status THISSTATUSWONTHAPPEN toc http://google.com out.pdf
I was able to get the proper behavior (it should hang indefinitely).
