### ISSUE TITLE
Assess for alternative links

### ISSUE THREAD

**Issue by stevenmills** [wkhtmltopdf/wkhtmltopdf#2218]
I am trying to capture a mobile version of a site by setting --width, which normally works, but there is a site that uses an alternative link (below) that wkhtmltopdf doesn't follow.  I have tried setting user agent to the latest iPhone 6 agent as well.

```<link rel="alternate" media="only screen and (max-width: 640px)" href="https://examples.com/m/" />```

**Comment by ashkulz** [comment]
I don't think media queries are supported in the version of webkit currently used, please try if you get better results with 0.13 alpha.
