### ISSUE TITLE
Watermark not appearing properly on Windows server 2008 R2 and localhost

### ISSUE THREAD

**Issue by er-ankit** [wkhtmltopdf/wkhtmltopdf#2219]
I previously opened issue #2213 and was asked to update wkhtmltopdf to the latest version.
So after updating it to v0.12.2.1, watermark is appearing on Windows server 2008 R2 but is appearing partly on the upper right corner(see attached screenshot of the pdf).
I tried editing the css for watermark to edit its position but it did not worked.
![server](https://cloud.githubusercontent.com/assets/11057662/6324446/330e16ce-bb60-11e4-83e2-c2fb26abad5b.png)
Also after updating to the latest version the watermark stopped appearing completely, earlier it was working fine before updating on localhost.
Please help..

**Comment by alloylab** [comment]
have you tried this on 0.12.5?

**Comment by alloylab** [comment]
We are closing this out since we haven't heard from you. If you are still having this issue please feel free to re-open it. Thanks.
