### ISSUE TITLE
"Your player does not support this audio format"

### ISSUE THREAD

**Issue by szelk** [wkhtmltopdf/wkhtmltopdf#2220]
I want to render a fixed layout epub pages (with wkhtmltoimage), it goes well, but some page I get a "Your player does not support this audio format" warning message on the image. It is created by PubCoder, and contains audio tracks which started when it has loaded.
I couldn't find any parameter which hide that message.
How could I eliminate this message without modified the epub? Where do I search in source code?
![6](https://cloud.githubusercontent.com/assets/1913382/6348889/7b2accee-bc24-11e4-8afe-01644c97b040.jpg)

**Comment by alloylab** [comment]
What version? have you tried this on 0.12.5?

**Comment by Tomsgu** [comment]
Old issue I know but I don't think there is a way to do this. The best would be to fix the html.
