### ISSUE TITLE
Including Header Footers and page Numbers in the .html file

### ISSUE THREAD

**Issue by kumarakartheek** [wkhtmltopdf/wkhtmltopdf#2222]
Hello 

I am new-bee to converting Html to PDF using WebKitHtmltoPdf tool.
I have a scenario where i need to send three different requests/ Files  to the prism server( where the webkitHtmltoPdf engine is located ) which converts files into pdf.

I am facing an issue to generate a pdf file with headers and footers. 
As I mentioned,I am sending three different files which are in same format
1. Header
2 Body
3.Footer
When i generate the pdf on local machine using the command  
C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf --header-html header.html body.html --footer-html footer.html output.pdf , 
the pdf is generated fine but when i send these files to the prism the headers footers and body are displayed in separate pages (header - page 1 , body page 2 , footer page 3)

![image](https://cloud.githubusercontent.com/assets/11236421/6424906/841a65b6-bed2-11e4-81f4-2f48f241e9e9.png)

![image](https://cloud.githubusercontent.com/assets/11236421/6424910/9627d8ec-bed2-11e4-8054-594735673393.png)

![image](https://cloud.githubusercontent.com/assets/11236421/6424911/a19ef476-bed2-11e4-8f27-212298bb17e0.png)

I am just wondering is there a way to include "--header-html" ,  "--footer-html" and other format options like frompage , topage , headerline, footerline enclosed in the html document. or any other file formats advised.  

My file formats are as below.

![image](https://cloud.githubusercontent.com/assets/11236421/6424895/3385f3fe-bed2-11e4-8ce5-2aef4e1d6b2b.png)
![image](https://cloud.githubusercontent.com/assets/11236421/6424896/43e6752a-bed2-11e4-9245-4435b6d513ac.png)

I appreciate your time Thank you in advance.

**Comment by ashkulz** [comment]
Ask this on StackOverflow, as this is nothing to do with wkhtmltopdf (it looks like you are trying to convert an MHT).
