### ISSUE TITLE
Fonts on 0.12.0

### ISSUE THREAD

**Issue by romainPina** [wkhtmltopdf/wkhtmltopdf#2223]
Hi,

I have a problem with my fonts when generating a PDF.
They are included as follows:

        @font-face{
            font-family : "gothambook";
            font-weight: normal;
            font-style: normal;
            src : url(my_url/gothambook.ttf') format("truetype");
        }

        @font-face{
            font-family : "gothamrndbold";
            font-weight: normal;
            font-style: normal;
            src : url('myUrl/gothamrndbold.otf') format("truetype");
        }

        @font-face{
            font-family : "gothamrndbook";
            font-weight: normal;
            font-style: normal;
            src : url('my_url/gothamrndbook.ttf') format("truetype");
        }

It seems I can not use the 2 fonts "gothamrndbold" and "gothamrndbook" simultaneously. These two fonts are another variation "gothamrnd."

When generating a pdf on windows, it does not pose a problem, but when I generate the PDF on a Linux server (Ubuntu 14.04) only the bold is used for both.

solution?
Cheers.

![src_htm](https://cloud.githubusercontent.com/assets/1382435/6440520/fd9bda5c-c0dd-11e4-8f50-9b6d1cd87812.png)
![pdf_test](https://cloud.githubusercontent.com/assets/1382435/6440534/33479678-c0de-11e4-8213-ecc1865c7f31.jpg)

**Comment by rsteinwand** [comment]
0.12.0 is no longer supported. You should update to the v. 0.12.2.1 to see if your issue is resolved.

http://wkhtmltopdf.org/downloads.html

**Comment by ashkulz** [comment]
Also, looks like it is a known problem: see #1542
