### ISSUE TITLE
thead - show additional content when repeated over a page break

### ISSUE THREAD

**Issue by sammich** [wkhtmltopdf/wkhtmltopdf#2224]
Table headers repeat on the following page if the table is split over a page break. What I'm wondering is if it's possible to show additional content (like the text: "(cont'd)") so the user knows it's a continuation.

I've only had a quick look at the CSS spec for this, and I've tried using CSS Counters, but the spec doesn't seem to suggest anything and the Counter just uses the first header's counter value.

Just in case my point isn't clear enough:
---- page 1 ----
thead [ "Table Content 1" ]
tbody tr#row1
---- page 2 ----
thead [ "Table Content 1 (cont'd) ]
tbody tr#row2

Cheers.

**Comment by ashkulz** [comment]
If it isn't supported by the CSS spec, how do you expect it to be implemented here?
