### ISSUE TITLE
pure virtual method called error

### ISSUE THREAD

**Issue by clecorre** [wkhtmltopdf/wkhtmltopdf#2226]
Hello, got this error several times, with the 0.12.2.1 version (with the 0.12.1.2 too), on a Microsoft Windows Server 2003 R2 Enterprise x64 Edition Service Pack 2:

pure virtual method called
This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
terminate called without an active exception

**Comment by ashkulz** [comment]
Please ensure that you use the mingw-w64 version on Windows 2003, as the MSVC 2013 version is unlikely to work.

**Comment by clecorre** [comment]
Hello,

Thanks for your reply.
This is the version I use. I re-installed it, just to be 100% sure.

Thank you.
