### ISSUE TITLE
border size limited to 4095px

### ISSUE THREAD

**Issue by olegskl** [wkhtmltopdf/wkhtmltopdf#2227]
It seems that there's 4095px limit imposed by wkhtmltopdf on border size. The following works:

    border: 4095px solid red;

But the following (and beyond) does not display the border at all:

    border: 4096px solid red;

There's no such limitation in browsers such as Chrome, Firefox, and even IE9. Can this limitation be removed from wkhtmltopdf?

**Comment by ashkulz** [comment]
Why do you want such a huge border size?

**Comment by olegskl** [comment]
I knew you'd ask :)

I'm just generating some triangles (which could be half a screen large), so I just went ahead with `border-width: 9999px;` which worked fine in browsers but was transparent in wkhtmltopdf. It works fine for us after getting in down to `4095px` so it's probably a non-issue.
