### ISSUE TITLE
please add support for css3

### ISSUE THREAD

**Issue by JigarJoshi** [wkhtmltopdf/wkhtmltopdf#2235]
http://stackoverflow.com/questions/28847859/html-divide-page-into-two-column-and-overflow-content-from-first-column-to-secon

    -webkit-column-count: 2; /* Chrome, Safari, Opera */
    -moz-column-count: 2; /* Firefox */
    column-count: 2;

is not rendered properly in pdf

**Comment by rsteinwand** [comment]
Have you tried 0.13?

**Comment by JigarJoshi** [comment]
I can try, is there a build for mac available for 0.13 ?

**Comment by rsteinwand** [comment]
Doesn't look like it. http://wkhtmltopdf.org/downloads.html

I know 0.13 has a newer webkit so should support more css3 features.

Are you on 0.12.2.1?

**Comment by JigarJoshi** [comment]
$ wkhtmltopdf --version
    wkhtmltopdf 0.12.2.1 (with patched qt)

**Comment by ashkulz** [comment]
Try out `0.13`, but basically we depend on the upstream for CSS support so unless it is present in Qt5 it is unlikely to get implemented.

**Comment by raoulus** [comment]
+1

**Comment by camdenb** [comment]
+1 - Would love to get the CSS updated.

**Comment by bavanyo** [comment]
Is there any word on if this is getting in soon?  I could REALLY use column-count!

**Comment by gosupernova** [comment]
This would be amazing, is there any news of an eta?
