### ISSUE TITLE
Won't install on Mac

### ISSUE THREAD

**Issue by burtondav** [wkhtmltopdf/wkhtmltopdf#2236]
I have a MacBook Pro running OSX Yosemite 10.10.2

I downloaded wkhtmltox-0.12.2.1_osx-cocoa-x86-64.pkg.
Then ran the package.
This install finish with OK.

I look in "Macintosh HD/Applications - and it's not installed.
![2015-03-07_09-21-47](https://cloud.githubusercontent.com/assets/1197501/6542091/8369de1a-c4ab-11e4-9e83-218ccff4d64f.png)

**Comment by burtondav** [comment]
Is it installing to usr/local/bin/  ??

**Comment by wellebee** [comment]
I installed on Yosemite 10.10.2 a couple days ago, and I don't have your problem.

$ wkhtmltopdf -V
wkhtmltopdf 0.12.2.1 (with patched qt)
$ which wkhtmltopdf
/usr/local/bin/wkhtmltopdf

**Comment by burtondav** [comment]
I uninstalled the gem wkhtmtopdf-binary - and now $ which wktmltopdf shows /usr/local/bin/wkhtmltopdf.
