### ISSUE TITLE
Avoid page break for table rows or divs

### ISSUE THREAD

**Issue by snadra** [wkhtmltopdf/wkhtmltopdf#2239]
I know avoiding page breaking is not a new issue, but I've scoured the forums and can't find an answer that will work for me.  I've managed to strip my code down to a very simple example to make it as clear as possible, and am hoping this will be a good way to get some help with solving it.

I'm using phpwkhtmltopdf version 1.2.1 (but have also tried version 1.2.6), called from a PHP web page, to call wkhtmltopdf version 12.1 on a Ubuntu server.

Here is my completely stripped down HTML:

```
$html = "<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Strict//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd\">";
$html .= "<html xmlns=\"http://www.w3.org/1999/xhtml\" xml:lang=\"en-GB\">";
$html .= "<style type=\"text/css\">";
$html .= "  @media print { table, tr, td { background-color:#cccccc; page-break-inside:avoid; }} ";
$html .= "</style>";
$html .= "<table>";
$html .= "<tr><td style=\"border:1px solid #000000;height:700px;\">First</td></tr>";
$html .= "<tr><td style=\"border:1px solid #000000;height:700px;\">Second</td>";
$html .= "</table>";
$html .= "</html>";
```

I then call generate the PDF with:

```
$pdf_doc->addPage($html);
$pdf_doc->send($pdf_filename);
```

The results are two tall, grey rows, and the second one breaks across two pages even though I've told it not to.  Attached is a screenshot of the PDF, showing the first and second pages.  
![breaking-table-rows](https://cloud.githubusercontent.com/assets/11409996/6578643/b91e08e8-c71b-11e4-9f11-18d18afba788.jpg)

**Comment by snadra** [comment]
P.S. I've also tried this with divs instead of table rows, and I get the same results.

**Comment by SimonErich** [comment]
This might be a stupid question, but maybe related:
You don't have neither <head> nor <body> tags in your code?
Can you try adding them, because I had a related issue with wkhtmltopdf and my solution was to make the html code w3 valid.

**Comment by yozzz** [comment]
#2141

**Comment by fatuhoku** [comment]
Same issue. I don't see any solutions! :(

**Comment by kobruleht** [comment]
Similar issue which occurs without using table:

https://github.com/wkhtmltopdf/wkhtmltopdf/issues/3141
