### ISSUE TITLE
Mandarin characters are replaced by spaces

### ISSUE THREAD

**Issue by im4ravi** [wkhtmltopdf/wkhtmltopdf#2241]
In centos though the stix fonts are available the mandarin characters are replaced by empty sapces.

The same pdf if generated in windows7 the font picked by the wkhtmltopdf is "MSUIGothicRegular".

Will it be possible to know how the wkhtmltopdf will pick the fonts...?

**Comment by pallymore** [comment]
are the fonts correctly installled in centos?

**Comment by Tomsgu** [comment]
Closing as there is no feedback since 2015.
