### ISSUE TITLE
Cannot load library icui18n

### ISSUE THREAD

**Issue by arthurkirkosa** [wkhtmltopdf/wkhtmltopdf#2242]
Using 
ubuntu 14.04
wkhtmltopdf 0.12.2.1 (with patched qt)

```
[2015-03-12 12:14:02] production.ERROR: The exit status code '1' says something went wrong:
stderr: "Unable to load library icui18n "Cannot load library icui18n: (icui18n: cannot open shared object file: No such file or directory)"
Loading pages (1/6)
Counting pages (2/6)
Resolving links (4/6)
Loading headers and footers (5/6)
Printing pages (6/6)
Done
Exit with code 1 due to network error: ProtocolInvalidOperationError
"
stdout: ""
command: /var/www/app/vendor/h4cc/wkhtmltopdf-amd64/bin/wkhtmltopdf-amd64 --lowquality --print-media-type --header-right '[page]/[toPage]' '/tmp/knp_snappy550166ea59e7c9.04040940.html' '/tmp/knp_snappy550166ea59f572.23047693.pdf'. [] []
```

**Comment by ashkulz** [comment]
You should use the binary for Ubuntu Trusty; the binary for Debian Wheezy has a dependency on libicu: you can fix this by installing the `libicu52` package (for Ubuntu Trusty).

**Comment by divdax** [comment]
I've installed ```libicu52``` but get the same error again. (Ubuntu 14)

**Comment by ashkulz** [comment]
Which binary did you use?

**Comment by divdax** [comment]
wkhtmltopdf 0.12.2.1 (with patched qt)

**Comment by ashkulz** [comment]
What was the exact URL you used? There are different versions for different platforms, although version is the same.

**Comment by divdax** [comment]
I'm using the amd64 version: https://github.com/h4cc/wkhtmltopdf-amd64/

**Comment by ashkulz** [comment]
Use the Ubuntu version from the downloads page.

**Comment by divdax** [comment]
I've downloaded and installed the .deb package from the download page like you mentioned:
http://downloads.sourceforge.net/wkhtmltopdf/wkhtmltox-0.12.2.1_linux-trusty-amd64.deb (Ubuntu 14.04.1)

I still get the following error:
```
[2015-06-08 10:16:07] local.ERROR: exception 'RuntimeException' with message 'The exit status code '1' says something went wrong:
stderr: "Unable to load library icui18n "Cannot load library icui18n: (icui18n: cannot open shared object file: No such file or directory)" 
Loading pages (1/6)
```

**Comment by ashkulz** [comment]
What is the output of the following commands?
```
which wkhtmltopdf
ldd `which wkhtmltopdf`
```

**Comment by divdax** [comment]
```
$ which wkhtmltopdf
/usr/local/bin/wkhtmltopdf

$ wkhtmltopdf --version
wkhtmltopdf 0.12.2.1 (with patched qt)

$ ldd `which wkhtmltopdf`
	linux-vdso.so.1 =>  (0x00007fff232d6000)
	libjpeg.so.8 => /usr/lib/x86_64-linux-gnu/libjpeg.so.8 (0x00007f38b2d2d000)
	libpng12.so.0 => /lib/x86_64-linux-gnu/libpng12.so.0 (0x00007f38b2b07000)
	libXrender.so.1 => /usr/lib/x86_64-linux-gnu/libXrender.so.1 (0x00007f38b28fc000)
	libfontconfig.so.1 => /usr/lib/x86_64-linux-gnu/libfontconfig.so.1 (0x00007f38b26c0000)
	libfreetype.so.6 => /usr/lib/x86_64-linux-gnu/libfreetype.so.6 (0x00007f38b241d000)
	libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007f38b20e7000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f38b1ece000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f38b1cca000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f38b1ac1000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f38b18a3000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f38b159f000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f38b1298000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f38b1082000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f38b0cbc000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f38b2f8d000)
	libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007f38b0a91000)
	libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007f38b0872000)
	libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007f38b066d000)
	libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007f38b0467000)
```

**Comment by ashkulz** [comment]
There is no dependency on `libicu`, which is also confirmed by `ldd`. If you run it from the command-line, does it still give the error? Make sure you are running the version from `/usr/local/bin` and not any other version present in your system.

**Comment by rdpascua** [comment]
I'm having this exact issue on Ubuntu 14.04 (x64)

**Comment by imanzuk** [comment]
I'm also having this exact issue on Ubuntu 14.04 (x64)

ldd has the same output as divdax wrote

```
$ dpkg -l | grep libicu
ii  libicu-dev:amd64  52.1-3ubuntu0.3   amd64   Development files for International Components for Unicode
ii  libicu52:amd64    52.1-3ubuntu0.3   amd64   International Components for Unicode
```

**Comment by ashkulz** [comment]
I'm pretty sure you're not using the command-line version but a version packaged into composer/other source.

**Comment by Oliboy50** [comment]
Exact same issue as @divdax , this should not be closed IMHO.

I just downloaded and use the amd64 binary source from this repository, installed `libxrender1` and `libicu52`, nothing more.

**Comment by Oliboy50** [comment]
Hey, I just realized that I downloaded the binary source from the wrong (I guess) repository (h4cc/wkhtmltopdf-amd64)...

So I fixed this issue with the following installation process:
```
wget -q http://download.gna.org/wkhtmltopdf/0.12/0.12.2.1/wkhtmltox-0.12.2.1_linux-trusty-amd64.deb
dpkg --install wkhtmltox-0.12.2.1_linux-trusty-amd64.deb
# I ran into issues here, so I add to force download dependencies
apt-get --yes --fix-broken install
# Then test
/usr/local/bin/wkhtmltopdf http://www.google.com test.pdf
```

**Comment by be-codified** [comment]
Hi, can somebody help me please?

I keep getting:

	RuntimeException in AbstractGenerator.php line 333:
	The exit status code '1' says something went wrong:
	stderr: "Unable to load library icui18n "Cannot load library icui18n: (icui18n: cannot open shared object file: No such file or directory)" 
	...
	Done 
	Exit with code 1 due to network error: ContentNotFoundError
	"
	stdout: ""
	command: ../vendor/h4cc/wkhtmltopdf-amd64/bin/wkhtmltopdf-amd64 --lowquality --margin-bottom '20' --margin-left '25' --margin-right '15' --margin-top '10' --page-size 'a4' --footer-font-size '8' --footer-html 'http://someurl/partials/pdfFooter.html' 'http://someurl/offers/view/98/pdf' '/tmp/knp_snappy55bf98100d38f7.63414943.pdf'.

**Comment by Oliboy50** [comment]
@be-codified I guess you're using the wrong binary too...
Either the `apt-get install wkhtmltopdf` and the one from `h4cc` repository are causing this issue.
You'll have to get the binary directly from http://download.gna.org/wkhtmltopdf/0.12/0.12.2.1/wkhtmltox-0.12.2.1_linux-trusty-amd64.deb if you want the last working version.

Would be great if we just have to `apt-get install wkhtmltopdf` though...

**Comment by be-codified** [comment]
@Oliboy50 thank you for your effort.

I have downloaded binary, upload it to server and used commands:

sudo dpkg -i wkhtmltox-0.12.2.1_linux-trusty-amd64.deb

    (Reading database ... 188833 files and directories currently installed.)
    Preparing to unpack wkhtmltox-0.12.2.1_linux-trusty-amd64.deb ...
    Unpacking wkhtmltox (0.12.2.1) over (0.12.2.1) ...
    Setting up wkhtmltox (0.12.2.1) ...
    Processing triggers for man-db (2.6.7.1-1ubuntu1) ...

sudo apt-get install -f

    Reading package lists... Done
    Building dependency tree
    Reading state information... Done
    The following packages were automatically installed and are no longer required:
      libaudio2 libavahi-client3 libavahi-common-data libavahi-common3 libcups2
      libgstreamer-plugins-base1.0-0 libgstreamer1.0-0 liborc-0.4-0
      libqt4-declarative libqt4-network libqt4-opengl libqt4-script libqt4-sql
      libqt4-sql-mysql libqt4-xml libqt4-xmlpatterns libqtcore4 libqtdbus4
      libqtgui4 libqtwebkit4 linux-headers-3.13.0-32
      linux-headers-3.13.0-32-generic linux-headers-3.13.0-36
      linux-headers-3.13.0-36-generic linux-headers-3.13.0-37
      linux-headers-3.13.0-37-generic linux-image-3.13.0-32-generic
      linux-image-3.13.0-36-generic linux-image-3.13.0-37-generic
      linux-image-extra-3.13.0-32-generic linux-image-extra-3.13.0-36-generic
      linux-image-extra-3.13.0-37-generic qtcore4-l10n
    Use 'apt-get autoremove' to remove them.
    0 upgraded, 0 newly installed, 0 to remove and 34 not upgraded.

Though, I still get same error. Is there something else I can do?

**Comment by ashkulz** [comment]
@be-codified: look at the error. It says very clearly
> `command: ../vendor/h4cc/wkhtmltopdf-amd64/bin/wkhtmltopdf-amd64`
That's wrong, it should be `/usr/local/bin/wkhtmltopdf` or just `wkhtmltopdf`. If you don't **use** the package that you have installed, what's the point?

**Comment by be-codified** [comment]
@ashkulz I am using Snappy wrapper for Laravel:

https://github.com/barryvdh/laravel-snappy

PDF create was fully working on my local machine. As I have copied files to development server, I am having this issue.

**Comment by ashkulz** [comment]
Configure the wrapper, or if it doesn't support it report an issue there.

**Comment by janzenz** [comment]
@Oliboy50 Thanks for that solution. I was using `h4cc` as well. Now I can run and generate the pdf via command line. However, when I use it on my page it throws another error:

`
The exit status code '1' says something went wrong:
stderr: "Loading pages (1/6)
[> ] 0%
[======> ] 10%
[============> ] 20%
Warning: SSL error ignored 
`

Looks like an SSL issue. What can I do to solve this?

**Comment by janzenz** [comment]
It's the `<img>` tag causing the problem. The src path can't find the file. Should this be a bug with `wkhtmltopdf`?

**Comment by Oliboy50** [comment]
@janzenz I experienced something similar on my first try. 
I finally understood that I had to use "server relative" file paths instead of "url relative" file paths.

Instead of 
```
http://mydomain.com/uploads/image.png
```
use
```
/var/www/html/uploads/image.png
```

@ashkulz am I right?

**Comment by ballaevi** [comment]
I had the same issue The problem was with the links in the html not with the icui18n, you need to use full path links like 'http://my-site/assets/css/style.css'.
Hope this solves your problem :)

**Comment by janzenz** [comment]
That's confusing. @Oliboy50 suggested different against @ballaevi

**Comment by Oliboy50** [comment]
@janzenz Maybe you can do both ways if your images are accessible through the internet. @ashkulz could answer this for sure :)

**Comment by janzenz** [comment]
@Oliboy50 but the question is can't this be improved in `wkhtmltopdf` where it just displays blank `img` instead of stopping the compilation and just show no specific errors. Could help save hours for users who don't know about this.

**Comment by Lets-a-go** [comment]
I just hit this same issue with a new root cause: I was installing my development setup on a new device and had just put Nordic's command line tools plus JLink on an Ubuntu arm64 desktop installation on a Raspberry Pi 400. Attempting to run JLinkExe:
SEGGER J-Link Commander V7.70 (Compiled Aug  3 2022 17:27:31)
DLL version V7.70, compiled Aug  3 2022 17:27:15

Connecting to J-Link via USB...Unable to load library icui18n "Cannot load library icui18n: (icui18n: cannot open shared object file: No such file or directory)" 
FAILED: Cannot connect to J-Link.

Yet all the software was installed properly and in its proper locations. Turned out that with the latest software, this error now happens when there is no USB debugger connected, a different behavior than what happens on my older V7.58-based system.
