### ISSUE TITLE
Text defined within the tags H1, H2 are narrowed into the png generated

### ISSUE THREAD

**Issue by cmoulliard** [wkhtmltopdf/wkhtmltopdf#2243]
Version used on MacOS X : 0.12.2.1
Project : html page with css & js available here : https://www.dropbox.com/sh/gvo8pa0yugklb72/AADgCPUgKnk0HVMz3GyYoC_Za?dl=0

Command used `wkhtmltoimage --width 1280 --height 800 --zoom 1 cover.html cover.png`

The issue is that the png image generated contains narrowed text

Screenshot of the HTML page (Chrome) - resolution 1280 x 800: 
![screenshot 2015-03-12 21 52 02](https://cloud.githubusercontent.com/assets/463790/6628044/a35e6bd6-c902-11e4-9d4c-b01a167442ce.png)

png file generated : 
![screenshot 2015-03-12 21 57 38](https://cloud.githubusercontent.com/assets/463790/6628072/ddaf2f5a-c902-11e4-842b-6a6a632cc5f1.png)

I can use the zoom option `wkhtmltoimage --width 1280 --height 800 --zoom 4 cover.html cover.png` but the logo of the image generated is degraded
![zoomed](https://cloud.githubusercontent.com/assets/463790/6628198/d5b90644-c903-11e4-9959-fa1c2ba08a66.png)

**Comment by alloylab** [comment]
have you tried this on 0.12.5?

**Comment by Tomsgu** [comment]
Closing as there is no feedback and links aren't active (old issue).
