### ISSUE TITLE
How to use wkhtmltopdf with Node webkit

### ISSUE THREAD

**Issue by mahavirjain** [wkhtmltopdf/wkhtmltopdf#2244]
Please provide a working example with all requires, so that i can use wkhtmltopdf to generate pdf from HTML document.

Thanks in advance :)

**Comment by mahavirjain** [comment]
I am getting this error : 

Uncaught node.js Error 

Error: spawn ENOENT
    at exports._errnoException (util.js:742:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1027:32)
    at child_process.js:1110:20
    at process._tickCallback (node.js:382:11)



Here is my code : 
i installed module by using this command : npm install wkhtmltopdf

then created a html file and here is my code : 

<html>
<head>
	<script type="text/javascript" src="js/jquery.js"></script>
    <script type="text/javascript" src="js/app.js"></script>
    <script type="text/javascript">
    var wkhtmltopdf = require('wkhtmltopdf');
    function generatePdfFile()
    {
    	 //  wkhtmltopdf('<h1>Test</h1><p>Hello world</p>', { output: 'out.pdf' });
         wkhtmltopdf('<h1>Test</h1><p>Hello world</p>', { pageSize: 'letter' }).pipe(fs.createWriteStream('out.pdf'));
    }
    </script>
</head>
<body style="background-color:#fff;">
    This is test
    <h1>Another PDF HTML Test</h1>
<table border="1">
<tr>
    <th>Id</th>
    <th>Name</th>
</tr>
<tr>
    <td>Id</td>
    <td>Name</td>
</tr>
<tr>
    <td>Id</td>
    <td>Name</td>
</tr>
</table>
<button onclick="generatePdfFile()">Generate PDF</button>
</body>
</html>

**Comment by pallymore** [comment]
hmmm which library are you using? it seems you are using server side nodejs code in your HTM.

**Comment by ashkulz** [comment]
Nothing to do with `wkhtmltopdf`, contact the authors of the library you are using.
