### ISSUE TITLE
wkhtmltopdf always using default sans-serif font

### ISSUE THREAD

**Issue by ojdavey** [wkhtmltopdf/wkhtmltopdf#2246]
I'm using a Django wrapper with wkhtmltopdf however I'm having the problem that regardless of the fonts I use in my CSS it always just shows a default sans-serif font. It works locally and also works on the server when I just generate the HTML without converting it to the PDF.

This (http://grab.by/FBcq) is how it shows on the server in the PDF and this (http://grab.by/FBcA) is how it shows locally in the PDF. The font is a custom font base64 encoded, however it doesn't matter what font I use as none make a difference.

Is it something to do with the server setup?

**Comment by pallymore** [comment]
could you share part of your css here? 
I'd avoid using fallback fonts in the css, it seems wkthtmltopdf always picks the fallback font. (not sure if it is fixed or not)

**Comment by ojdavey** [comment]
Thanks for replying @pallymore.

I was using some fallback fonts, however I've removed them and the same issue is still happening.

The relevant CSS is very simple:

@font-face  {
     font-family:  'TrajanBold';
     src:  url(data:application/x-font-woff;charset=utf-8;base64,d09GRgA................9kDfOAAFVBjrLAAA=) format('woff')
     font-weight:  normal;
     font-style:  normal;
 }

#generate-pdf .page header.middle .main-heading {
    background-color: transparent;
    font-family: TrajanBold;
    font-size: 32px;
    text-align: center;
    text-transform: uppercase;
}

**Comment by pallymore** [comment]
I've had similar problem before...i ended up installing the font in the environment which wkhtmltopdf is being used, and removed the base64 fonts from the css files. It is possible that `x-font-woff` is not supported properly in this version. 

http://stackoverflow.com/questions/24724712/rails4-pdfkit-fonts-heroku-not-working/24744183#24744183

**Comment by jeroenkruis** [comment]
The CSS you supplied should work. Can you try out [this](https://github.com/jeroenkruis/dmp-style-garamond/blob/master/src/fonts.styl) CSS? Because that is working fine for me. I'm not using a Django wrapper though.

**Comment by Tomsgu** [comment]
Closing as solutions were provided and there is no feedback, so it seems to be resolved.

**Comment by atipico** [comment]
Same issue here. Eve if I write this simple css `p { font-family: serif; }` it renders sans-serif font. I Am using "wkhtmltopdf 0.12.5 (with patched qt)" under Ububtu 18.04.

**Comment by arunkumarpadmaneri** [comment]
> Same issue here. Eve if I write this simple css `p { font-family: serif; }` it renders sans-serif font. I Am using "wkhtmltopdf 0.12.5 (with patched qt)" under Ububtu 18.04.
> 
> According to [mileszs/wicked_pdf#46](https://github.com/mileszs/wicked_pdf/issues/46)
> All I had to do is to quote serif, like this: `p { font-family: 'serif'; }`

i have applied the style like this for the `simple` paragraph, but it doesn't work for ubuntu 18.04 with wkhtmltopdf 0.12.5 . code [code link](https://drive.google.com/file/d/1SecrXUl5UwbOCQjI9CwsJ49LR9ZFLP5n/view?usp=sharing) 
output pdf [link](https://drive.google.com/file/d/1xRUWPyU2c6CoKQm4_pPn6T8my0b7pRby/view?usp=sharing)
Have I missed anything?

**Comment by jeffisnotdead** [comment]
Same problem for me, trying to display chinese bold character
@font-face {
font-family: 'Noto Sans SC', sans-serif;
src: url('https://fonts.googleapis.com/css2?family=Noto+Sans+SC:wght@900&display=swap');
}

.cn-name{
    font-family: 'Noto Sans SC', sans-serif !important;
    font-size:12px;
    font-weight: 900 !important;

It's work perfectly in html, but in pdf only sans-serif font is render
Any one find a way to solve it?

**Comment by cdfwebsolutions** [comment]
It looks like wkhtmltopdf looks in `/usr/share/fonts` for system-installed fonts to embed. In our case, we were trying to use a generic serif font (like Times New Roman) by specifying `font-family: serif`, but this did not work. Looking in the shared fonts directory, we have a similar serif font, Nimbus Roman No9 L. Adding `font-family: "Nimbus Roman No9 L"` did the trick for embedding this font. (It took some Googling to find the css name of the font for the font file.)

We did not try uploading additional fonts to the shared fonts directory, so I'm not sure if that would work and if you would also need to update the `fonts.dir` file there or anything else. But hopefully this will help someone escape the sans-serif default font trap.
