### ISSUE TITLE
Honor margins from CSS @page declaration by default

### ISSUE THREAD

**Issue by aapierce0** [wkhtmltopdf/wkhtmltopdf#2247]
Currently, any margins set by the @page CSS declaration are ignored in favor of the command-line arguments (including the default values of those arguments if no value is explicitly set).

Additionally, wkhtmltopdf should be able to correctly handle the pseudo-classes :left, :right, and :first

http://www.w3.org/TR/CSS21/page.html#page-margins

**Comment by ashkulz** [comment]
That isn't possible as it is not supported by the underlying browser engine (WebKit).

**Comment by aapierce0** [comment]
Wow, [you're right](https://bugs.webkit.org/show_bug.cgi?id=15548).

It works in Chrome, so I assumed that it was supported by WebKit (even though I know they forked over to Blink a while ago).

Thanks for the quick response!

**Comment by pwuertz** [comment]
This _page-margins from CSS_ feature can be implemented by retrieving the CSS properties via javascript and applying the page margins using QPageLayout. I'm using this method in a small Qt5 WebEngine based PDF tool.

`getCssPageLayout()` in [qtwehtmltopdf/main.cpp](https://github.com/pwuertz/qtwehtmltopdf/blob/master/main.cpp)
