### ISSUE TITLE
Help needed to install wkhtmltox rpm package on Oracle Linux box

### ISSUE THREAD

**Issue by mohdmohsin** [wkhtmltopdf/wkhtmltopdf#2250]
I am trying to install wkhtmltox-0.12.2.1_linux-centos6-amd64.rpm package(Downloaded from : http://downloads.sourceforge.net/project/wkhtmltopdf/0.12.2.1/wkhtmltox-0.12.2.1_linux-centos6-amd64.rpm ) into the Linux box (Oracle Linux 6.3). I am unable to install and getting some dependency to install some font package. Could you please help us to install this package.

**Comment by ashkulz** [comment]
Install the dependent packages; you can [try this](https://ask.fedoraproject.org/en/question/7162/how-to-fix-rpm-package-has-missing-requires-of-errors/?answer=15320#post-id-15320) and see if it works for you.
