### ISSUE TITLE
Dont change /usr/local owner to root in mac

### ISSUE THREAD

**Issue by Paxa** [wkhtmltopdf/wkhtmltopdf#2252]
After I install wkhtmltopdf from package homebrew stop working.

As I find out /usr/local, /usr/local/bin, /usr/local/lib, /usr/local/share, ... was owned by root, but suppose to be owned by current user and have group admins.

**Comment by metaljoe** [comment]
I was wondering what had happened with my homebrew installation recently - the permissions in /usr/local have changed. It broke around the time I installed wkhtmltopdf, so I seem to have experienced the same problem as you.

**Comment by ashkulz** [comment]
What were the exact permissions (`ls -al`) before and after installation?

**Comment by scottjacobsen** [comment]
My exact directory ownership for /usr/local and everything underneath was "scott:admin". After installing wkhtmltopdf /usr/local and several subdirectories (lib, man, share, etc) had their ownership changed to "root:wheel"

The wkhtmltopdf installer should not change ownership of directories.

Re https://github.com/caskroom/homebrew-cask/issues/12093

**Comment by ashkulz** [comment]
@scottjacobsen: I don't have or use a Mac, so can you confirm if `tar` accepts the flag described below:
```
 --no-overwrite-dir
           preserve metadata of existing directories
```
If so, can you check if changing `scripts/build.py:1219` to 
```sh
tar xf --no-overwrite-dir $BASEDIR/app.tar
```
and rebuilding the package does not change the permissions?

**Comment by scottjacobsen** [comment]
Sadly no

    scott@endor ~% tar --version
    bsdtar 2.8.3 - libarchive 2.8.3
    scott@endor ~% which tar
    /usr/bin/tar

**Comment by ashkulz** [comment]
Hmm, according the [manpage](https://www.freebsd.org/cgi/man.cgi?query=bsdtar&sektion=1) the equivalent flag seems to be `--no-same-owner`, can you try changing it as mentioned above and see if the owner/group does not get changed?

**Comment by scottjacobsen** [comment]
No such option. That is the FreeBSD version of tar. [OSX Tar](https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man1/tar.1.html)

I don't see anything in that documentation that really addresses this
issue.

There are a lot of different tars out there :)

Maybe rather than trying to work around all the different versions of
tar you could untar to a tmp directory, and then use `cp -r` to copy
into place?

**Comment by ashkulz** [comment]
I think that the equivalent option is `-o`, can you try with that? I'm not too comfortable with the `cp` approach, as there is a small window of opportunity for someone to copy files into the `/tmp` subdirectory and finally end up in `/usr/local/`.

**Comment by scottjacobsen** [comment]
-o appears to do the right thing. I tested with a few tar files. Building
the project seems to be non trivial, so I haven't done that yet.

**Comment by ashkulz** [comment]
Not too sure about the syntax that `tar` on OS X accepts, does it have to be `tar -o xf $BASEDIR/app.tar` or something else?

**Comment by scottjacobsen** [comment]
`tar oxf $BASEDIR/app.tar` works for me.

**Comment by Paxa** [comment]
Thank you

**Comment by ashkulz** [comment]
A preview for the next release [`0.12.3-dev-79ff51e`](http://wkhtmltopdf.org/downloads.html#testing) is available, which should contain the fix for this issue. Please report back if it is not solved with the above version.

*Please note that the above downloads will be removed after the `0.12.3` release*.

**Comment by ashkulz** [comment]
[`0.12.3`](http://wkhtmltopdf.org/downloads.html#stable) has been released, which should contain the fix for this issue. Please report back if it is not solved with the above version.

*Note that the preview downloads mentioned above have been removed*.
