### ISSUE TITLE
Access page content from header and footer?

### ISSUE THREAD

**Issue by mauvm** [wkhtmltopdf/wkhtmltopdf#2255]
Is there a way to access page content from the header and footer? Or alternatively use the substitution variables in the page content itself?

This would help with styling and determining wether to show a header or footer based on the page's content.

Thanks in advance!

**Comment by ashkulz** [comment]
Sorry, neither are really possible. You can try to dynamically generate the HTML header so it has the necessary knowledge before passing it to wkhtmltopdf.

**Comment by mauvm** [comment]
Unfortunately, that won't be an option for me since the dynamic part of the header will be based on the page's content.

How is rendering of the header/footer implemented? Are these fixed height so that the content can be determined beforehand? And how hard would it be to make the page's HTML elements available to the header/footer?

**Comment by ashkulz** [comment]
@mauvm: go through the code in `src/lib/pdfconverter.cc` and let me know if you have an idea to implement it; in my opinion it isn't possible.
