### ISSUE TITLE
Runtime Error with wkhtmltopdf on Heroku

### ISSUE THREAD

**Issue by PatrickatPaperlessPCS** [wkhtmltopdf/wkhtmltopdf#2256]
I'm having trouble with wkthmltopdf in production on Heroku.  I'm getting a Runtime error associated with sizing and margins:
`RuntimeError (command failed (exitstatus=0): /app/vendor/bundle/ruby/2.1.0/bin/wkhtmltopdf --page-size Letter --margin-top 0.75in --margin-right 0.75in --margin-bottom 0.75in --margin-left 0.75in --encoding UTF-8 --print-media-type - -):`

Having trouble finding a solution on my own - does anyone have experience with this error?

**Comment by ashkulz** [comment]
Is this with the latest version of `wkhtmltopdf`? From the path it looks like you are using the `gem` version, which still uses `0.9.9` and is not supported.
