### ISSUE TITLE
Wkhtmltopdf is not working for https.

### ISSUE THREAD

**Issue by Orangescrum** [wkhtmltopdf/wkhtmltopdf#2258]
Error: Failed loading page https://www.facebook.com/ (sometimes it will work just to ignore this error with --load-error-handling ignore)

Please help!

**Comment by keithslater** [comment]
What version are you using? I personally use it on sites that are https and it works fine. I just tested it with https://www.facebook.com and it worked fine.

**Comment by enr-beck** [comment]
I have the same issue on live server which is using version 0.10.0 rc1. On my staging server it works with version 0.12.2. I can't find a changelog for 0.10 and 0.11 versions - maybe rendering of https content was buggy in 0.10.0?

**Comment by Orangescrum** [comment]
Hi enr-beck,
You are right its not working for https.
Please change the path to htpp, it will work.

**Comment by ashkulz** [comment]
HTTPS is not working due to SSLv3 being disabled, which is all that the old versions support. Upgrading to the latest version should fix this issue.
