### ISSUE TITLE
Windows basic example, no pdf output

### ISSUE THREAD

**Issue by MrDanielBell** [wkhtmltopdf/wkhtmltopdf#2260]
Hi.

Running a basic example of wkhtmltopdf.

Basic example....

C:\Program Files (x86)\wkhtmltopdf>wkhtmltopdf.exe http://www.google.com google.pdf
Loading pages (1/6)
Counting pages (2/6)
Resolving links (4/6)
Loading headers and footers (5/6)
Printing pages (6/6)
Done

This is on Windows 7. The folder does not contain google.pdf

**Comment by rsteinwand** [comment]
You can't write to the program files folder with default permissions. Try specifying a valid path for your pdf elsewhere.
