### ISSUE TITLE
Lines cut in the pdf at page breaks

### ISSUE THREAD

**Issue by GayathriJayakumar** [wkhtmltopdf/wkhtmltopdf#2261]
I am creating PDF from a html using wkhtmltopdf. The pdf created is having lines cut into half at page breaks. Please refer the below screen shot.

How we could avoid this. 

![image](https://cloud.githubusercontent.com/assets/9604929/6824332/430bf270-d317-11e4-8995-c32833b7dc94.png)

**Comment by mewlabs** [comment]
I have similar problem, but with tables
![9ad738754c](https://cloud.githubusercontent.com/assets/1019853/6865090/fdcb9366-d472-11e4-99c9-3ce9bfd86e8f.png)

**Comment by yozzz** [comment]
There are similar issues #2141

**Comment by ashkulz** [comment]
Duplicate of #2141
