### ISSUE TITLE
Hidden h* tags won't show in TOC

### ISSUE THREAD

**Issue by BenjaminWenzel** [wkhtmltopdf/wkhtmltopdf#2262]
I'm trying to generate a PDF Catalog including a table of contens. To achieve this I create a toc dump, and read it's content through PHP. So long - no problem...

Now I have some headers, that have to be display inside the TOC, but not in the rendered PDF. So I set the mentioned headers to "display: none". If I do so, they don't appear in the TOC.

I need a possibility to render some headers into the TOC without displaying them in the PDF document.

**Comment by ashkulz** [comment]
See #1554 on an explanation of why making it `display: none` breaks things, as it is no longer present in the WebKit render tree.

**Comment by mrmunch** [comment]
For those who are running in the same problem (like me), here is a workaround to solve this:
HTML:
`<h1 class="h1_none">My Title</h1>`
CSS (for example):
`.h1_none{size:0pt;color:white;margin:0px;padding:0px}`
