### ISSUE TITLE
Only first 6 pages printed

### ISSUE THREAD

**Issue by mcicolella** [wkhtmltopdf/wkhtmltopdf#2263]
Hi
when I try to convert an html file to pdf only the first 6 pages are printed correctly. The others (4 in my case) are all white. The same html file printed with acrobat distiller is OK. Any idea? 
Thanks

**Comment by alloylab** [comment]
What version? have you tried this on 0.12.5?

**Comment by Tomsgu** [comment]
Closing as there is no response and the issue is missing important information.
