### ISSUE TITLE
install as headless

### ISSUE THREAD

**Issue by clarkk** [wkhtmltopdf/wkhtmltopdf#2264]
How to use and install wkhtmltopdf headless without display?

Installation on Debian Wheezy
`apt-get install wkhtmltopdf`

Command
`wkhtmltopdf --title "$SUBJECT" -q $SOURCEFILE $OUTPUTFILE`

Error
`QXcbConnection: Could not connect to display`

**Comment by ashkulz** [comment]
Just install the package from the [official downloads page](http://wkhtmltopdf.org/downloads.html#stable) instead of the distro-supplied package, which is very old and does not use the patched Qt.
