### ISSUE TITLE
Centos 6 wkhtmltopdf is not working using php exec()

### ISSUE THREAD

**Issue by mgsukhon** [wkhtmltopdf/wkhtmltopdf#2267]
wkhtmltopdf is working using php exec() function in ubuntu 14.04. wkhtmltopdf is not working using php exec() function none of Centos 6.6 and 6.5 64 bit OS. The following is my Scripts:

$output1 = exec('/usr/local/bin/wkhtmltopdf http://google.com /var/www/html/a.pdf 2>&1', $o1,  $r1);
var_dump($o1);
Returns: array(2) { [0]=> string(19) "Loading pages (1/6)" [1]=> string(132) "[> ] 0% [======> ] 10%" } 
This stopped after 10%. 

--------------------------Using xvfb---------------------------------------
$output2 = exec('xvfb-run --server-args="-screen 0, 1024x768x24" /usr/local/bin/wkhtmltopdf http://google.com /var/www/html/b.pdf 2>&1', $o,  $r);
var_dump($o2);
Returns: array(3) { [0]=> string(19) "Loading pages (1/6)" [1]=> string(242) "[> ] 0% [======> ] 10% /usr/bin/xvfb-run: line 166: 26991 Segmentation fault DISPLAY=:$SERVERNUM XAUTHORITY=$AUTHFILE "$@" 2>&1" [2]=> string(60) "/usr/bin/xvfb-run: line 171: kill: (26989) - No such process" } 

Please let me get help.

**Comment by ramanirohit** [comment]
it may be issue of writing , i had also same problem , 

so i have tried with giving the write permission but it still not worked 

so finally i have set following using terminal

setenforce 0 

Note : fire above command using terminal and try to run the script...

May be this will help you..

**Comment by mgsukhon** [comment]
I have executed "setenforce 0" but no luck
I got a solution: execute "sudo setsebool httpd_execmem on" but SElinux need to be enabled first.
In my VPS, Virtuozzo disabled SElinux that's why I am looking for an alternate solution to permit Apache to execute exec().

**Comment by ashkulz** [comment]
In case it works from the command line, then I cannot help to figure out why it doesn't work under PHP exec (a setup which I have never used).

**Comment by juancastaeda06** [comment]
Hope it helps anybody: I solved it removing the 64 bit and installing the 32 bit (i686) version. I had to install all the dependencies in their 32 bit versions using `yum whatprovides LIBRARY-NAME` to get the full name of the package and then just installing it with `yum install LIBRARY-PACKAGE-NAME.i686`

In my case I had a Centos 6 x86_64 with SELinux disabled because it interferes with CPanel and WHM.

**Comment by mgomezbuceta** [comment]
I tried to remove the 64-bit version and install the 32-bit, with all its dependencies, and still fails the call through php exec command.
Any more ideas that can make it work?

Dependencies:
yum install fontconfig-2.8.0-5.el6.i686 libXrender-0.9.8-2.1.el6.i686 libXext-1.3.2-2.1.el6.i686  xorg-x11-fonts-Type1 xorg-x11-fonts-75dpi libpng-1.2.49-1.el6_2.i686 zlib-1.2.3-29.el6.i686 libjpeg-turbo-1.2.1-3.el6_5.i686 libstdc++-4.4.7-11.el6.i686 libzip-0.9-3.1.el6.i686 openssl-1.0.1e-30.el6.11.i686 freetype-2.3.11-15.el6_6.1.i686

Library:
wkhtmltox-0.12.2.1_linux-centos6-i386.rpm

Thanks

**Comment by mgsukhon** [comment]
Enable SELinuxEnable memory excess
this will work.
 Best regards, M G Sukhon, Project Manager, 
Software Shell, 
Skype- mgsukhon,Yahoo- mgsukhon,Mob- +8801710975034, +8801820069990Address- House#34, Level#4, Road#2, Nikunjo#2, Dhaka, 
Bangladesh.

 


     On Wednesday, August 5, 2015 4:42 PM, Marcos Gómez Buceta <notifications@github.com> wrote:
   

 I tried to remove the 64-bit version and install the 32-bit, with all its dependencies, and still fails the call through php exec command.
Any more ideas that can make it work?Dependencies:
yum install fontconfig-2.8.0-5.el6.i686 libXrender-0.9.8-2.1.el6.i686 libXext-1.3.2-2.1.el6.i686 xorg-x11-fonts-Type1 xorg-x11-fonts-75dpi libpng-1.2.49-1.el6_2.i686 zlib-1.2.3-29.el6.i686 libjpeg-turbo-1.2.1-3.el6_5.i686 libstdc++-4.4.7-11.el6.i686 libzip-0.9-3.1.el6.i686 openssl-1.0.1e-30.el6.11.i686 freetype-2.3.11-15.el6_6.1.i686Library:
wkhtmltox-0.12.2.1_linux-centos6-i386.rpmThanks—

**Comment by mgomezbuceta** [comment]
Thank you mgsukhon!!!. It works great !!!

**Comment by jan-edge** [comment]
@mgsukhon , could you elaborate plz?

**Comment by mgsukhon** [comment]
Wkhtmltopdf requires to access memory to create PDF. So, you have to enable memory access by command "sudo setsebool httpd_execmem on". You could not enable memory access without enabling SELinux.

KVM virtualization in Linux only permits to enable SELinux. 
After enabling SELinux, you have to run command "sudo setsebool httpd_execmem on" to access memory. 

If you need code, you will get code how to create PDF using wkhtmltopdf by googling.

**Comment by jan-edge** [comment]
Thanks

**Comment by MissMyCat** [comment]
@mgsukhon after enable SELinuxEnable memory excess, the xvfb still print the error.
[root@name ~/data/soft]# getsebool httpd_execmem
httpd_execmem --> on

and 

/usr/bin/xvfb-run: line 181:  2228 Segmentation fault      DISPLAY=:$SERVERNUM XAUTHORITY=$AUTHFILE "$@" 2>&1

I need help ....

**Comment by mgsukhon** [comment]
xvfb-run is not supported or installed. Try without xvfb in your script. Or
Install the latest version of wkhtmltopdf
Hope, it will work.
