### ISSUE TITLE
Compile issue

### ISSUE THREAD

**Issue by clarkk** [wkhtmltopdf/wkhtmltopdf#2268]
Debian Wheezy

```
apt-get install git
git clone --recursive https://github.com/wkhtmltopdf/wkhtmltopdf.git
cd /root/wkhtmltopdf/scripts
build.py wheezy-amd64
````

returns
```
-bash: build.py: command not found
```

but the file exists
```
~/wkhtmltopdf/scripts # dir
build.py  release.py  sync-headers.sh
```

**Comment by exap** [comment]
If you really used this:
```build.py wheezy-amd64```

Try this:
```./build.py wheezy-amd64```

[Here](http://www.linfo.org/dot_slash.html) and [here](https://stackoverflow.com/questions/6331075/why-do-you-need-dot-slash-before-script-name-to-run-it-in-bash) you can find good explanations for this "dot slash" convention.

**Comment by clarkk** [comment]
```
~/wkhtmltopdf/scripts # ./build.py wheezy-amd64
sh: 1: schroot: not found
schroot -c wkhtmltopdf-wheezy-amd64 -- gcc --version
command failed: exit code 32512
```

**Comment by clarkk** [comment]
`apt-get install schroot`

`./build.py wheezy-amd64`

```
~/wkhtmltopdf/scripts # ./build.py wheezy-amd64
W: No chroots are defined in ‘/etc/schroot/schroot.conf’ or ‘/etc/schroot/chroot.d’
E: wkhtmltopdf-wheezy-amd64: Chroot not found
schroot -c wkhtmltopdf-wheezy-amd64 -- gcc --version
command failed: exit code 256
```

**Comment by Neurotec** [comment]
try first, need root
~~~bash
# ./build.py setup-schroot-wheezy
~~~

and
~~~bash
$ ./build.py wheezy-amd64
~~~
El mar 29, 2015 4:04, "clarkk" <notifications@github.com> escribió:
>
> apt-get install schroot
>
> ./build.py wheezy-amd64
>
> ~/wkhtmltopdf/scripts # ./build.py wheezy-amd64
> W: No chroots are defined in ‘/etc/schroot/schroot.conf’ or
‘/etc/schroot/chroot.d’

**Comment by ashkulz** [comment]
Please read the contents of the Linux section of `INSTALL.md` line-by-line. You are:

* using `wheezy` when only `jessie` (testing) is supported
* have not setup the chroot environments
* are running as root (which is explicitly **not recommended**) instead of normal user
* do not have sudo setup properly for your normal user

**Comment by polomoshnov** [comment]
Instead of `build.py wheezy-amd64` run `python build.py wheezy-amd64`. But before that also run `sudo python build.py setup-schroot-wheezy`.
