### ISSUE TITLE
Text rendering is broken in some pages

### ISSUE THREAD

**Issue by katananja** [wkhtmltopdf/wkhtmltopdf#2270]
Using windows 7 64bit, wkhtmltopdf v0.12.2.1.
The spacing between letters it's too much or too little in some cases, for example this one:
bin\wkhtmltopdf -s A4 -n --load-error-handling ignore --cache-dir D:\tmp --disable-javascript  --minimum-font-size 13 -L 5 -R 5 "http://bevcooks.com/2013/09/grilled-hawaiian-pizza-burritos/" "Grilled Hawaiian Pizza Burritos.pdf"

![sample_text](https://cloud.githubusercontent.com/assets/9029191/6886079/a3137398-d608-11e4-97d8-de7406e89793.jpg)

**Comment by ashkulz** [comment]
Looks like the page uses `letter-spacing` which breaks text rendering, see #1575.

**Comment by katananja** [comment]
Hello,
if 'letter-spacing' is the issue, why not add an option to just ignore it or make it default until the issue is fixed??

**Comment by ashkulz** [comment]
Read the other issue for details. Change the CSS at your end or use `--user-style-sheet` to override it.
