### ISSUE TITLE
compilation failure on OS X 10.10

### ISSUE THREAD

**Issue by BradGalway** [wkhtmltopdf/wkhtmltopdf#2272]
After doing the following:

git init
git clone --recursive https://github.com/wkhtmltopdf/wkhtmltopdf.git
sudo gem install fpm --no-ri --no-rdoc
cd wkhtmltopdf/
./scripts/build.py osx-cocoa-x86-64

I get:

1 error generated.
make[2]: *** [.obj/release-static/qcocoaapplicationdelegate_mac.o] Error 1
make[2]: *** Waiting for unfinished jobs....
1 warning generated.
/Users/bg/PDF/wkhtmltopdf/qt/src/gui/widgets/qmainwindowlayout_mac.mm:451:33: warning: incompatible pointer types sending 'QCocoaToolBarDelegate *' to parameter of type
      'id<NSToolbarDelegate>' [-Wincompatible-pointer-types]
        [macToolbar setDelegate:[[QT_MANGLE_NAMESPACE(QCocoaToolBarDelegate) alloc] initWithMainWindowLayout:this]];
                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../include/QtGui/private/../../../../../../qt/src/gui/widgets/qcocoatoolbardelegate_mac_p.h:69:1: note: instance method 'initWithMainWindowLayout:' is assumed to return an instance of its receiver
      type ('QCocoaToolBarDelegate *')
- (id)initWithMainWindowLayout:(QT_PREPEND_NAMESPACE(QMainWindowLayout) *)layout;
^
1 warning generated.
make[1]: *** [release] Error 2
make: *** [sub-gui-make_default-ordered] Error 2
make -j8
command failed: exit code 512

Not too sure what the issue is.

**Comment by ashkulz** [comment]
What is the version of OS X and XCode you are using?

**Comment by MichaelKubovic** [comment]
same problem here. osx yosemite 10.10.2, xcode 6.2

**Comment by ashkulz** [comment]
@MichaelKubovic: building via brew is not supported, only via the build script. I build in a OS X 10.7 VM (to ensure that it works on 10.6+) and I don't have or use OS X otherwise. Maybe @npinchot or @mn4367 can help out here?

**Comment by ashkulz** [comment]
Hmm, looks like it is due to [QTBUG-39644](https://bugreports.qt.io/browse/QTBUG-39644) and is fixed via qtproject/qt@997d626173d9aba5b01b35e4d95ad162771ba789. Upgrading to Qt 4.8.7 should fix the issue, which will be done for the `0.12.3` release.

**Comment by ashkulz** [comment]
Should be fixed via 279a3f653ecd65f6d09d6ac7ec5634aefff7dd5b, let me know if you encounter any other compilation issues on 10.10.
