### ISSUE TITLE
Question: If the process is stuck, is there any default timeout of the wkhtmltopdf?

### ISSUE THREAD

**Issue by k-siddharatha** [wkhtmltopdf/wkhtmltopdf#2273]
If the process is stuck, is there any default timeout for wkhtmltopdf when it will try to close the process and come out of the hung state?

Or is there anyway to configure that from the default settings. I am sure we can kill it from outside the process though is there any default time wkhtmltopdf will try to create the pdf and if not succeeded it will come out of it?

**Comment by ashkulz** [comment]
Do you mean something similar to #1888 or #1879?

**Comment by k-siddharatha** [comment]
I saw those issues, though my question is.. If the process stuck in between after loading the images/script while creating the PDF is it possible to timeout the process?

Or can we deicide the maximum time the process will take to covert the HTML to PDF after loading all the script and images.

**Comment by ashkulz** [comment]
There is no timeout option available, you can `kill` the process as per your own definition.
