### ISSUE TITLE
Table header repeated on second page without table content

### ISSUE THREAD

**Issue by hansyu-pos** [wkhtmltopdf/wkhtmltopdf#2274]
I am trying to get a table header to repeat on page break if the table content goes beyond a page. This works in most cases, but when the content exactly reaches the bottom of the page, the header gets repeated on the next page but has no content.

I tried many CSS fixes that I've found online but none of them solved the problem. I've also double checked the source HTML and it does not have any blank content that may break the page at the end.

EDIT: It seems like this issue only occurs when the content of the table reaches a very particular pixel value. Simply changing the height of the content by a pixel gets rid of the problem. Maybe there's a small computation error in the page height calculation?

**Comment by ashkulz** [comment]
Reopen the issue if you can give a minimal test case which demonstrates this issue.
