### ISSUE TITLE
wkhtmltopdf (0.12.2.1 with patched qt) is not working with authenticated web URLS. 

### ISSUE THREAD

**Issue by dishadutta26** [wkhtmltopdf/wkhtmltopdf#2275]
I am trying to use wkhtmltopdf along with CQ5/AEM. I have an url which can be accessed only with a particular user. I tried with the command: 
wkhtmltopdf --username <> --password <> <url> <target pdf>

**Comment by ashkulz** [comment]
Reopen if you can provide more information.
