### ISSUE TITLE
Extra blank pages

### ISSUE THREAD

**Issue by artix75** [wkhtmltopdf/wkhtmltopdf#2279]
Hello, i'm using wkhtmltopdf inside a Web Application that allows user to create ebooks in various format (EPUB, PDF). When users want to generate the PDF of their book, wkhtmltopdf generates it using the same HTML/CSS used for the EPUB.

The result is very fine, and i'm very happy with the quality of the final PDF. Anyway sometimes wkhtmltopdf adds extra blank pages when the content of a chapter completely fits into one page.
I've tried setting bottom margin/padding to 0 but nothing changes.

You can download the HTML/CSS source and the convert script (containing the wkhtmltopdf CLI line) from here:

https://www.dropbox.com/s/jimr10gd6m3wvzz/wk_book.tar.gz?dl=0

In the example above you can see that a blank page is added after page 2.

Here's some detail about the executing environment:

**Software Version**
wkhtmltopdf 0.12.2.1 (with patched qt) 

**Operating System**
Ubuntu 12.04.5 LTS

**Comment by jerry1970** [comment]
I have the same problem. Every PDF has a blank page at the end. CentOS6 64 bits version of wkhtmltopdf.

**Comment by ZAJDAN** [comment]
did somebody somehow solved this problem? I am facing to the same :(

**Comment by Tomsgu** [comment]
Is this still an issue in `0.12.5`?

**Comment by Tomsgu** [comment]
Closing as there is no feedback. Please feel free to comment if you still experience this problem.

**Comment by khatrirohan80** [comment]
I am facing same problem, in my output pdf, there is one extra blank page in middle of pdf.
but, when i generate pdf, sometimes one extra page added in the middle of pdf.

**Comment by ashkulz** [comment]
For blank pages at the end, #2711 should've fixed it. Not sure about in the middle, maybe open a new issue with full details?
