### ISSUE TITLE
Fundamental alignment issue with wkhtmltopdf or webkit

### ISSUE THREAD

**Issue by jammy-git** [wkhtmltopdf/wkhtmltopdf#2281]
I had some alignment and page break issues with a not-so complex layout containing a few divs and a long table (200 rows). Through my investigations into this issue I've come across this problem:
http://jsbin.com/xujaqajufi/2/

One relatively positioned div, one absolutely positioned, both should align at the bottom of a page, 210mm in height. But in Chrome, there is a 1px gap.
![Alignment problem](http://thecode.company/alignment_issue.png)

The layout is much much worse as a PDF:
http://thecode.company/alignment_issue.pdf
The absolutely aligned div ends up half way off the bottom of the page once you get to page 100!
![Alignment problem PDF](http://thecode.company/alignment_issue_pdf.png)

Ultimately I'm trying to write a JavaScript solution to the page break issue with table rows, but finding it impossible as I can't accurately work out where the bottom of each page is.

Using wkthmltopdf version 0.12.2.1

**Comment by ashkulz** [comment]
Why are you trying to re-implement layout algorithms in Javascript?

**Comment by jammy-git** [comment]
Mainly because the page breaking over table rows still isn't sorted for me, though I'm going to be upgrading the version of wkhtmltopdf today now we have a public holiday here in the UK.

However there are a couple of other reasons:
1 - A particular requirement for this project is that a page break can only occur after every *other* table row.
2 - page-break-inside: avoid isn't working.

**Comment by jammy-git** [comment]
Having upgraded to 0.12.2.1 today (the rpm file available from the downloads page) I found the page-breaking to be both better and worse.

The automatic page breaks no longer occur within text.

However, the page break css I had no longer works either (mostly), some stuff did work, mainly:

    table {
    	page-break-inside: auto;
    }
    thead {
    	display: table-header-group;
    }
    tr {
	page-break-inside: avoid;
    }

Seemed to work OK. However I had some helper classes along the lines of:

    .page-break-before-avoid {
    	page-break-before: avoid !important;
    	page-break-after: auto;
    }

Which no longer worked. Not had time today to get gists and examples together but I'd be amazed if someone else hasn't already reported that issue.

The original issue still stands though. Being able to accurately calculate the bounds of every page would open up a world of possibilities for web publishing.

**Comment by ashkulz** [comment]
Hmm, `page-break-before: avoid` and `page-break-after: avoid` are not implemented in WebKit even now. And I don't think it is possible to calculate layout everything in JS ... if you want perfect layout, you'll be better off using PrinceXML.
