### ISSUE TITLE
Overlapping characters at particular font sizes

### ISSUE THREAD

**Issue by awestbha** [wkhtmltopdf/wkhtmltopdf#2286]
I'm getting weird character-overlapping issues, but only at particular font sizes:

![result](https://drive.google.com/uc?id=0B5j9ZbkpU3FXT0xGaFBya2lkcFU)

from: 

```
<html>
  <head>
  	<style>
  		body { font-family: Calibri; }
  	</style>
  </head>
  
  <body>
		<p style="font-size:8px;">Test at 8</p>
		<p style="font-size:9px;">Test at 9</p>
		<p style="font-size:10px;">Test at 10</p>
		<p style="font-size:11px;">Test at 11</p>
		<p style="font-size:12px;">Test at 12</p>
		<p style="font-size:13px;">Test at 13</p>
		<p style="font-size:14px;">Test at 14</p>
		<p style="font-size:15px;">Test at 15</p>
		<p style="font-size:16px;">Test at 16</p>
		<p style="font-size:17px;">Test at 17</p>
		<p style="font-size:18px;">Test at 18</p>
		<p style="font-size:19px;">Test at 19</p>
		<p style="font-size:20px;">Test at 20</p>
	</body>
	
</html>
```

* I tested a bunch of fonts, and it only happens in Calibri and Cambria
* It works fine in Ubuntu 14.04, using the same font files and the same wkhtmltopdf version (0.12.2)
* But is broken in CentOS 6

I'm totally out of ideas on this one, and am going slightly mad - anybody have any ideas?

**Comment by ashkulz** [comment]
Hmm, I suspect that either the fontconfig/freetype libraries are too old or not configured correctly in CentOS 6. See [this comment](https://github.com/wkhtmltopdf/wkhtmltopdf/issues/45#issuecomment-53485578) for a possible solution.

**Comment by awestbha** [comment]
Thanks! I had already implemented that fix for the kerning problem mentioned in that thread. Turning it off does indeed fix the above! But the kerning issue returns. Will google around - thanks for the help.
