### ISSUE TITLE
Leading only works up to 75% of font size.

### ISSUE THREAD

**Issue by joshuaand** [wkhtmltopdf/wkhtmltopdf#2289]
Hi,

I use wkhtmltopdf for a professional application where leading is critical.

It has just come to our attention that when leading is set to more than 75% of the font size, leading becomes unreliable and incorrect.

Is this able to be resolved quickly, I am happy to pay for this to be corrected, hopefully its a simple fix?

**Comment by ashkulz** [comment]
Please provide a detailed explanation (with screenshots) of what the issue is, preferably with a self-contained and minimal test-case with complete HTML/CSS/JS.
