### ISSUE TITLE
Font sizes changing on PDF creation

### ISSUE THREAD

**Issue by tomcardoso** [wkhtmltopdf/wkhtmltopdf#2290]
I have a D3.js-generated SVG I'm running through wkthmltopdf (using the [Node.js wrapper](https://github.com/devongovett/node-wkhtmltopdf)). I'm finding that when I run an export, font sizes that were declared in my print stylesheet as one value are coming out as a totally different value.

Example: I generated [this PDF](https://dl.dropboxusercontent.com/u/9087109/nw-na-tories-print-2col%20%2827%29.pdf) (ignore the spacing issues, etc.) and set the headline to be 9pt in my css:

```
@media print {
  .chart .headline {
    font-size: 9pt;
  }
}
```

Yet as you can see, the PDF actually comes out with the font as 11.52pt. That's a huge difference, particularly since I'm looking to generate assets at small sizes. Have you seen this before?

Here are the flags I'm passing. Width and height are set dynamically, but always evaluate as an integer:

```
var options = {
  pageWidth: width + "mm",
  pageHeight: height + "mm",
  marginTop: 0,
  marginRight: 0,
  marginBottom: 0,
  marginLeft: 0,
  noOutline: true,
  dpi: dpi,
  disableSmartShrinking: true,
  printMediaType: true,
  zoom: 1
};
```

**Comment by tomcardoso** [comment]
Oh, I've also found that i can't just scale down the font sizes easily. If I try to pass a half-point value like `7.5pt`, it'll return both the wrong size *and* the result will be the same as using `8pt`. Very strange.

**Comment by ashkulz** [comment]
Can you produce a self-contained, minimal testcase which can reproduce this issue?

**Comment by tomcardoso** [comment]
Yep. Here it is:
https://github.com/tomcardoso/wkhtmltest

Includes the basic, bare-bones html file, the wkhtmltopdf command and a sample PDF. The bug I mentioned is pretty clear in the PDF, if you open it up in Illustrator and take a look at the glyphs.

If you select type for "9.5" or "10.0", they're both the same, incorrect font size: 12.48pt.

Thanks for your help, Ashish!

**Comment by tomcardoso** [comment]
And actually, I've just noticed the same problem occurring with the declared width and height. In the repo I linked above, I'm setting `--page-width 98mm` and  `--page-height 65.79mm` and margins to zero, yet the test PDF actually comes out with a width of 98.07mm and a height of 65.62mm. Think it might be part of the same problem? Perhaps some calculations or conversions being done improperly by the library?

**Comment by ashkulz** [comment]
Sorry, haven't got around to looking into yet ... possibly this weekend :smile:

**Comment by tomcardoso** [comment]
Been doing some digging, think I might have a potential culprit. In https://github.com/wkhtmltopdf/qt/pull/12#issuecomment-66266658 @pvandertak mentions using a `zoom` setting of `0.78125`. I'm running `wkhtmltopdf` on my Mac for dev, and in Ubuntu (Trusty) in production, so the default dpi being used is 75. Per my first comment, the chart headline (supposed to be 9pt) came out as `11.52pt` with a zoom of 1. 11.52 * 0.78125 is 9, so this might be it. Not sure it explains the width & height issues though, or why half-units like `9.5pt` return the same font-size as `10pt`. If I get some time today I'll explore this further.

**Comment by tomcardoso** [comment]
Nevermind, that didn't help :(

**Comment by buffpojken** [comment]
I seem to be experiencing the same issue. Fonts are rendered in -slightly- bigger sizes than configured on Ubuntu, while the 32-bit build on Mac renders just fine.

**Comment by AssafLiebstein** [comment]
We are also experiencing same issue. Fonts are slightly bigger in windows 7, ver: 0.12.2.1.
Also given --dpi 96 and --disable-smart-shrinking as arguments.

**Comment by tomcardoso** [comment]
Wondering what the status of this is — will the pull request @pvandertak referenced above do it, possibly?

**Comment by pvandertak** [comment]
Yes it should. I tried it with your test case back then. The fractional font sizes worked consistently (e.g. 9.5 and 10 no longer appeared at the same size). I don't think I specifically compared whether the font sizes in the PDF generated from your test case match the expected values. I guess they would, but otherwise you can now at least scale the font size down reliably.

**Comment by tomcardoso** [comment]
Sorry @pvandertak, to be clear: which version of wkhtmltopdf is this included in? 0.13? Also, thank you!

**Comment by pvandertak** [comment]
I don't think it was merged in yet, so it's probably not in any official version. You'd need to apply the patch and compile it yourself. As for the status, someone else should answer that. I don't know anything other than what's written in this thread.

**Comment by ashkulz** [comment]
PR has been merged.
