### ISSUE TITLE
Speed issue

### ISSUE THREAD

**Issue by AbdoDabbas** [wkhtmltopdf/wkhtmltopdf#2293]
Hi
This is a very beautiful project and very very helpful, the problem is it takes a longer time than other libraries to generate the PDF.
For example one HTML page, which contains only SVG image (which contains words and images inside it) it takes 2Sec from the beginning to the end of generating and saving file.
Is this normal or it's really slow ?
Another tool I used which has a special way to design the reports and custom files, it took only 1 sec to get the same result.

Finally, thanks a lot for developing and supporting such a tool.

**Comment by ashkulz** [comment]
It's a full browser engine -- it will take more time rather than a focused library. see #1510 on certain HTML constructs which do take more time.

**Comment by stimcon-dev** [comment]
Hi @AbdoDabbas,
Which tool you had used which take less time?
I am using wkhtmltopdf and my pdf contain many highcharts(approx 60-80 highcharts svg) svg and text thus pdf generation is working slow.  

by the way @ashkulz very beautiful project thanks a lot!!
