### ISSUE TITLE
Header Footer HTML issue

### ISSUE THREAD

**Issue by stevmon** [wkhtmltopdf/wkhtmltopdf#2294]
First of all version is (on Windows XP Professional SP3 32bit):

C:\wkhtmltopdf\bin>wkhtmltopdf.exe --version
wkhtmltopdf 0.12.2.1 (with patched qt)

I am having trouble getting an html header to appear in my PDF document.

I have tried everything including local files and have simplified the header to simply:

<html>
<head>
</head>
<body>
This is a test
</body>
</html>

When I use this html for a footer it appears correctly.

C:\wkhtmltopdf\bin>wkhtmltopdf -s Letter -T 10 -B 10 -L 10 -R 10 --header-spacin
g 5 --header-html http://test1sitea.exioreports.com/footer.asp --footer-spacing
5 --footer-html http://test1sitea.exioreports.com/footer.asp http://test1sitea.e
xioreports.com/HeaderFooterTest.asp testdoc.pdf

The above command will display the footer (This is a test) correctly but will not display the header in the output doc.

I have tried all kinds of variations of the above including no margin specs, no Letter size spec, Local files, removing the spacing for header and/or footer, specifying just the header or just the footer.
If I use the (--header-right "Page [page] of [toPage]") command in place of the (--html-header ...) I can see both the header and the footer in the PDF.
Sometimes I see some (not necessarily round) dots at where a header would be but doing a selection and pasting into a text editor shows no header text although the footer text will be there.
Note that although the above command specifies ASP pages I have also used HTML.  They are actually the same content.

One other note that I am not sure if it is related.  If I try to use HTML from the extended help page (exact copy) or from several examples from the internet that include a <table></table> block in the header OR the footer I get absolutely NO content in the PDF although no errors are reported and it has all of the same Command Line output from the command listed above.

I apologize if this was covered somewhere else but I went through everything posted here and did not see any solution(s).

The above URLs will function to serve my content to the application (you should be able to copy and paste to test.)

Any ideas?

Thanks in advance.

**Comment by ashkulz** [comment]
See if using `<!DOCTYPE html>` as mentioned in #46 helps you.

**Comment by stevmon** [comment]
Unbelievable!  I know I had done this at one point but might have had some other issue going on.  I even almost replied that I had done this but thought I better code it just in case before replying.  I mean seriously I tried everything I could think of or mentioned on the forums before asking this question.

But hey!  This was it - I even pasted the code from the extended help in place of the simple HTML I had and that works too!

Thanks Much!
