### ISSUE TITLE
Pipe HTML to stdin, receive PDF on stdout

### ISSUE THREAD

**Issue by jhftrifork** [wkhtmltopdf/wkhtmltopdf#2302]
I wish to use `wkhtmltopdf` programmatically, and avoid creating temporary files. To accomplish this I would expect to be able to pipe HTML to standard in, and receive raw PDF bytes on stdout. The `--help` documentation does not tell me how to do this. Is this possible and if so how do I do it?

**Comment by ashkulz** [comment]
Use the [API for libwkhtmltox](http://wkhtmltopdf.org/libwkhtmltox/) or use the bindings for various languages.
