### ISSUE TITLE
wkhtmltopdf - Printing website secured with Windows authentication is not possible

### ISSUE THREAD

**Issue by KapitanH** [wkhtmltopdf/wkhtmltopdf#2303]
We have a website hosted on an IIS, which is protected by Windows Authentication. We use the parameters --username and --password to pass the Windows credentials to wkhtml.

PDF generation worked flawlessly with version 0.11, but fails in 0.12. It just generates an empty PDF without giving any hints what might be wrong.

We did not change anything else, just switched from version 0.11 to 0.12.

**Comment by ashkulz** [comment]
What is the error you are getting? Some way of reproducing the issue would help diagnosing it.

**Comment by KapitanH** [comment]
We are currently in the process of reproducing this with a very simple website (which I should have done beforehand). As I get a different behaviour there, I close this until I have further info.

**Comment by ashkulz** [comment]
Please reopen it if you are able to provide further information on reproducing it. Thanks!
