### ISSUE TITLE
How to run wkhtmltopdf under root?

### ISSUE THREAD

**Issue by gaokun-mp** [wkhtmltopdf/wkhtmltopdf#2304]
For some reason, I have to start node server with 'sudo forever start server.js'.

In this case, wkhtmltopdf dose not work.
I tried: sudo wkhtmltopdf.   Got : no this command.
I think 'sudo forever' upgrade the privilege. so can't find 'wkhtmltopdf'.

Anyone can get me out of this?   ^0^.  
Thanks in advance!!

**Comment by mauvm** [comment]
Please check if the root user has the wkhtmltopdf command available:

```bash
which wkhtmltopdf    # get path for current user, e.q. /usr/local/bin/wkhtmltopdf
sudo su -            # login as root user
which wkhtmltopdf    # this should give you the binary's file path
```

If not, simply add the path (/usr/local/bin?) to your PATH variable ([manual for Mac/Linux](http://www.cyberciti.biz/faq/appleosx-bash-unix-change-set-path-environment-variable/)).

**Comment by ashkulz** [comment]
If you can run `wkhtmltopdf` as a normal user, then you should check the `$PATH` for `root`. Ask a question of StackOverflow instead of here for such questions in future :smile:
