### ISSUE TITLE
How to stop wkhtmltopdf.exe pop-up while running it with Python

### ISSUE THREAD

**Issue by anishagupta0505** [wkhtmltopdf/wkhtmltopdf#2305]
Hello,

I am using wkhtmltopdf.exe for converting html to pdf using python. The pop-up window of wkhtmltopdf.exe making it very difficult for me to work on other things while running it in background. I have convert some 200K+ files and have to work on something else simultaneously. But its really not letting me work on anything else.

Is there a way of stopping this or running it in background?
I really appreciate your help.

PS. Sorry I am new to Python, don't know any other way to stop it.

**Comment by ashkulz** [comment]
Ask on StackOverflow, this has nothing to do with `wkhtmltopdf`.

**Comment by anishagupta0505** [comment]
I have asked on stackoverflow and have done whatever i could do, there they are also suggesting me to contact the owner of the library. I would really appreciate if you could help me in this.

Thanks
