### ISSUE TITLE
Absolute positioned element renders more height than specified by element style

### ISSUE THREAD

**Issue by HilkiahMakemo** [wkhtmltopdf/wkhtmltopdf#2306]
In pdf the bars on the left are more than in the html. As shown below, anything I can do?
PDF:
![image](https://cloud.githubusercontent.com/assets/11683173/7164706/5fb0b12e-e35f-11e4-9284-7b2a319cc97e.png)

HTML:
![image](https://cloud.githubusercontent.com/assets/11683173/7164678/2ed2828a-e35f-11e4-8abd-93eeb9c215df.png)

**Comment by ashkulz** [comment]
Without the details requested in the [support page](http://wkhtmltopdf.org/support.html), it cannot be investigated further.
