### ISSUE TITLE
Image doesn't appear on the pdf

### ISSUE THREAD

**Issue by anthonyav** [wkhtmltopdf/wkhtmltopdf#2311]
Hello,

I'm trying to convert some html files into one pdf file. Some html contains image (png or jpg).
In some case i don't know why the image doesn't appear.

If i try to convert only the html that doesn't work, this work. I mean for example i have 10 files html and test3.html contains image. So if i try to convert all the files together, the image of test3.html doesn't appear but if i convert only test3.html to pdf, there is the image.

wkhtmltopdf -V
wkhtmltopdf 0.12.2.1 (with patched qt)

Thanks for your help.

**Comment by ashkulz** [comment]
Without the details requested in the [support page](http://wkhtmltopdf.org/support.html), it cannot be investigated further.
