### ISSUE TITLE
(CSS) Footer not anchored to bottom

### ISSUE THREAD

**Issue by thomasbennett** [wkhtmltopdf/wkhtmltopdf#2312]
I'm on CentOS 6 using wkhtmltopdf 0.12.2-6a13a51 (with patched qt).

I've got a footer rendering perfectly at the bottom of the one page of my browser. WKHTMLTOPDF seems to ignore this even though it is a full CSS solution. 

Does anyone have any advice?

**Comment by ashkulz** [comment]
Without the details requested in the [support page](http://wkhtmltopdf.org/support.html), it cannot be investigated further.

**Comment by thomasbennett** [comment]
Can I reopen with these details?

http://api-pa2.thomasgbennett.com/entry-employee-profile-test
