### ISSUE TITLE
System fonts not rendering when using other custom truetype font

### ISSUE THREAD

**Issue by pYThMik** [wkhtmltopdf/wkhtmltopdf#2313]
I had a strange problem when using wkhtmlpdf 0.12.2.1 with qt.
My HTML page uses a CSS sheet starting like this:

@font-face{
    font-family: "Code EAN13";
    src: url("../Fonts/ean13.ttf") format("truetype");
}
body{
    font-family: "Segoe UI";
}
.barCode{
    font-family: "Code EAN13";
}

The Barcode font renders nicely in PDF. But the rest of the page is rendered as "Arial" and the Segoe UI is not embedded into the PDF. If I remove the @font-face, the document renders correctly with SegoeUI.

Fortunately my font was available as eot (OpenType), and when I declared the @font-face like this, the PDF rendered OK too.

@font-face{
    font-family: "Code EAN13";
    src: url("../Fonts/ean13.eot?#iefix") format("embedded-opentype");
}

Strange, isn't it?

**Comment by alloylab** [comment]
have you tried this on 0.12.5?

**Comment by alloylab** [comment]
We are closing this out since we haven't heard from you. If you are still having this issue please feel free to re-open it. Thanks.
