### ISSUE TITLE
Getting error trying to use XSLTProcessor

### ISSUE THREAD

**Issue by Velocedge** [wkhtmltopdf/wkhtmltopdf#2315]
I have a page that I'm trying to convert to .pdf that uses the XSLTProcessor to transform the xml and stylesheets retrieved with AJAX.  I'm getting an error when it tries to create an instance of it (processor = new XSLTProcessor()).  How do I do such transformations using the latest version of wkhtmltopdf?

**Comment by alloylab** [comment]
What version? have you tried this on 0.12.5?

**Comment by alloylab** [comment]
We are closing this out since we haven't heard from you. If you are still having this issue please feel free to re-open it. Thanks.
