### ISSUE TITLE
image convert error

### ISSUE THREAD

**Issue by softguy888** [wkhtmltopdf/wkhtmltopdf#2316]
![i](https://cloud.githubusercontent.com/assets/2452938/7246283/45fa2d32-e82d-11e4-8b1a-d6ccdd4e3b9d.jpg)

when i use wkhtmltopdf to convert a html with an image attached above, it failed, please explain the reason of this .thanks!

**Comment by alloylab** [comment]
What version? have you tried this on 0.12.5?

**Comment by alloylab** [comment]
We are closing this out since we haven't heard from you. If you are still having this issue please feel free to re-open it. Thanks.
