### ISSUE TITLE
Any way to make table header repeat on page breaks?

### ISSUE THREAD

**Issue by Velocedge** [wkhtmltopdf/wkhtmltopdf#2317]
I have a number of displays/reports on the web that are pages of tables created from sql queries.   I'd like the option to turn these into .pdf's.  It would be great if the table header was displayed on every page break so it would look appropriate in print.  Is there a way to do that?

**Comment by fredericosilva** [comment]
Add a thead on the table

```
<table>
 <thead>
  <tr>
     <th>Month</th>
     <th>Savings</th>
  </tr>
 </thead>
 <tbody>
  <tr>
     <td>January</td>
     <td>$100</td>
  </tr>
  <tr>
     <td>February</td>
     <td>$80</td>
  </tr>
  ...
 </tbody>
</table>
```

It should do the trick :)

**Comment by ashkulz** [comment]
Thanks for the answer, @fredericosilva.

**Comment by Velocedge** [comment]
I neglected to say, this worked perfectly!  Many thanks!
