### ISSUE TITLE
wkhtmltopdf image corrupted 

### ISSUE THREAD

**Issue by mlhATWriber** [wkhtmltopdf/wkhtmltopdf#2318]
Hi,

I'm currently having a problem with corrupted image. 

My html code is exactly as the following (the file only contains this one line): 
<div><img src="http://www.thesaleslion.com/wp-content/uploads/2012/04/Hubspot-Logo-3.jpg">
</div>

(a random image from internet) 

This is what it suppose to look like :
![pp6jyntjleye0dxhhn4gfqyspylo8uxkvlzjl8kgk4wwaozz8yam9wvrh98r0](https://cloud.githubusercontent.com/assets/10483833/7257779/0da465a8-e826-11e4-8eca-09c5af3575c2.jpg)

but it actually look like this:
![untitled](https://cloud.githubusercontent.com/assets/10483833/7257795/2e9f0772-e826-11e4-91f2-1882720a3aad.png)

when I converted this using 

> wkhtmltopdf -q --margin-bottom 5 --margin-top 5 --margin-left 3 --margin-right 3 a.html a.pdf

and same when i use command 

> wkhtmltopdf -q --margin-bottom 5 --margin-top 5 --margin-left 3 --margin-right 3 --disable-smart-shrinking a.html a.pdf

I'm using wkhtmltopdf version:
 wkhtmltopdf 0.12.2.2 (with patched qt)

**Comment by seanmccaffery** [comment]
I'm having what I think is the same issue.  Try displaying the image with background-image as a workaround.

**Comment by ashkulz** [comment]
What is the OS you are on? There were a few bugs related to processing of JPEG images on Windows 2008 x64, which were fixed before `0.12.2.1`.

**Comment by mlhATWriber** [comment]
i'm using Windows 7 professional

**Comment by alloylab** [comment]
have you tried this on 0.12.5?

**Comment by Tomsgu** [comment]
Closing since there is no response.
