### ISSUE TITLE
(CSS) Footer not anchored to bottom

### ISSUE THREAD

**Issue by thomasbennett** [wkhtmltopdf/wkhtmltopdf#2319]
I'm on CentOS 6 using wkhtmltopdf 0.12.2-6a13a51 (with patched qt).

An example of the code is found here: http://api-pa2.thomasgbennett.com/entry-employee-profile-test

I've got a footer rendering perfectly at the bottom of the one page of my browser. WKHTMLTOPDF seems to ignore this even though it is a full CSS solution.

Does anyone have any advice?

**Comment by thomasbennett** [comment]
You need to use a fixed/absolute position to make this work. It looks like it processes the layout too fast to determine any other way to float the elements on the bottom of the page.

**Comment by MrCrankHank** [comment]
Can you maybe post an example? I'm kind of stuck here...

**Comment by thomasbennett** [comment]
For CSS something like this:

.footer { position: fixed; bottom: 0; }

**Comment by MrCrankHank** [comment]
Ahh, thanks. That worked. :+1:
