### ISSUE TITLE
Can't analysis [page]/[toPage] in --header-html URL?page=[page]ztopage=[toPage]

### ISSUE THREAD

**Issue by lehu3000** [wkhtmltopdf/wkhtmltopdf#2320]
this is my cmd line:
`wkhtmltopdf --debug-javascript --cookie JSESSIONID 751586CD3B0DB12085D909991AE01107 --header-html C:\pdftest\headtest.html?page=[page]ztopage=[toPage] --footer-html C:\pdftest\foot.xhtml  http://192.168.2.62/in/rapport_v1.xhtml ./HeaderNumberTest.pdf`

console output:
```
Warning: c:%5Cpdftest%5Cheadtest.html?page=%5Bpage%5Dztopage=%5Btopage%5D:6 x>>>  page=%5Bpage%5D,topage=%5Btopage%5D
Warning: c:%5Cpdftest%5Cheadtest.html?page=%5Bpage%5Dztopage=%5Btopage%5D:6 xxxx>>>>[page]
Warning: c:%5Cpdftest%5Cheadtest.html?page=%5Bpage%5Dztopage=%5Btopage%5D:6 yyyy>>>>[toPage]
- require: I custom split symbol from '&' to 'z' in url parameter, and then I deal with it by javascript.
## but I got result "pdf":

|                                                                                                                            |
## |                                                                               page [page] topage [toPage]|
```
so, does any one has a idea for it?

**Comment by lehu3000** [comment]
When I used :
wkhtmltopdf --debug-javascript --cookie JSESSIONID 751586CD3B0DB12085D909991AE01107 --header-html C:\pdftest\headerScript.html?page=1ztopage=2 --footer-html C:\pdftest\foot.xhtml  http://192.168.2.62/in/faces/dashboard_rapport_v1.xhtml ./HeaderPageNumber.pdf

the result on pdf : 
page 1 topage 2

it works well.

**Comment by alloylab** [comment]
is this still an issue on 0.12.5?

**Comment by Tomsgu** [comment]
Closing as there is no feedback.
