### ISSUE TITLE
Why I can't print the SVG file?

### ISSUE THREAD

**Issue by harikk** [wkhtmltopdf/wkhtmltopdf#2321]
Hello,
I am just wondering why I cant generate PDF of a particular SVG file by wkhtmltopdf a.svg a.pdf.
Can anybody help me? I can view and print it from chrome perfectly.

Please have a look at the file here.
https://drive.google.com/file/d/0B2SWQPqbIKKQWFc1bkV6Z0hQLVU/view?usp=sharing

**Comment by ashkulz** [comment]
You need to put it inside a HTML file.

**Comment by harikk** [comment]
It is not necessary. because SVG is a browser displayable stuff and it is working with other images.
