### ISSUE TITLE
Debug build of 0.13 fails on windows with missing sicuind.lib

### ISSUE THREAD

**Issue by poizan42** [wkhtmltopdf/wkhtmltopdf#2322]
It's the release version of ICU that is built whether -debug is specified or not, but the build of tools/qlalr tries to link with the debug version.

**Comment by ashkulz** [comment]
Does this patch generate both the debug and release libraries? Can't check this right now, unfortunately.
```diff
diff --git a/scripts/build.py b/scripts/build.py
index 7fe3411..8d15a42 100755
--- a/scripts/build.py
+++ b/scripts/build.py
@@ -411,7 +417,7 @@ DEPENDENT_LIBS = {
             'msvc*': {
                 'result': ['include/unicode/ucnv.h', 'include/unicode/ustring.h', 'lib/sicuin.lib', 'lib/sicuuc.lib', 'lib/sicudt.lib'],
                 'commands': [
-                    'bash source/runConfigureICU Cygwin/MSVC --enable-release --disable-debug --enable-static --disable-shared --disable-tests --disable-samples --prefix=%(cygdest)s',
+                    'bash source/runConfigureICU Cygwin/MSVC --enable-release --enable-debug --enable-static --disable-shared --disable-tests --disable-samples --prefix=%(cygdest)s',
                     'make', 'make install'
                 ]
             },
@@ -420,7 +426,7 @@ DEPENDENT_LIBS = {
                 'commands': [
                     'cp -R source source.host',
                     'cd source.host; ./configure; make',
-                    'source/configure --host=%(mingw_w64)s --enable-release --disable-debug --enable-static --disable-shared --disable-tests --disable-samples --prefix=%(destdir)s --with-cross-build=`pwd`/source.host',
+                    'source/configure --host=%(mingw_w64)s --enable-release --enable-debug --enable-static --disable-shared --disable-tests --disable-samples --prefix=%(destdir)s --with-cross-build=`pwd`/source.host',
                     'make install']
             }
         }
```

**Comment by poizan42** [comment]
Unfortunately no. Enabling debug regardless of whether release is enabled results in linking of icu4c/tools/genrb failing with an undefined reference to __imp__CrtDbgReportW. Sounds like it's an issue with ICU.

**Comment by ashkulz** [comment]
Does just using `--disable-release --enable-debug` work? Looks like ICU will have to be special cased in case that works.

**Comment by poizan42** [comment]
Nope, as I just said enabling debug regardsless of whether release is enabled fails.

**Comment by ashkulz** [comment]
Sorry didn't read carefully :frowning: will need to check it in detail over the weekend.

**Comment by poizan42** [comment]
FYI that link error is expected if you compile against the debug version of the crt (with /MD I think it is), but then link against the release version. So it seems like the build system for ICU gives different flags to cl and link.

**Comment by ashkulz** [comment]
I suspect it is something to do with the other libraries (specifically `zlib`), I'll have to check and confirm.

**Comment by ashkulz** [comment]
Please try the latest `0.13` branch, it works (at least goes past building of `tools/qlalr`) -- if there are any more problems, please reopen the issue. Looking forward to your contributions on wkhtmltopdf/qt#10 :smile:
