### ISSUE TITLE
Wkhtmltoimage does not show --debug-javascript

### ISSUE THREAD

**Issue by GDmac** [wkhtmltopdf/wkhtmltopdf#2323]
I'm trying to embed a twitter timeline on a simple html page. But it doesn't render.
I tried explicit `--enable-javascript` and even `--javascript-delay 2400`. I tried 
`--debug-javascript` which works for **wkhtmltopdf** but doesn't seem to work for **wkhtmltoimage**?

Test a twitter timeline from: https://twitter.com/settings/widgets/new
which generates something like:

``` html
<a class="twitter-timeline" href="//twitter.com/search?q=%40twitterdev" data-widget-id="486744238403489792" width="400" height="300">
     Tweets about "</a><a href="https://twitter.com/intent/user?screen_name=twitterdev">@twitterdev</a>"
 
 
!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");
```

**Comment by alloylab** [comment]
What version? have you tried this on 0.12.5?

**Comment by alloylab** [comment]
We are closing this out since we haven't heard from you. If you are still having this issue please feel free to re-open it. Thanks.
