### ISSUE TITLE
PDF creation BEFORE page fully rendered

### ISSUE THREAD

**Issue by richnwilson** [wkhtmltopdf/wkhtmltopdf#2328]
Hi Folks,
Sorry for the rookie question. I've scanned the submitted issues and can't seem to find an answer.

I'm rendering a complicated HTML page that uses Highcharts API to render over 100+ charts. It takes about 20-30 seconds for the page to fully render.

On some occasions I've noticed that the converted PDF's are missing some of the % sign labels on the charts (always on the last but one page). Is it possible the conversion process is starting before the page has fully rendered ? If so, is there a way around this.

If not, does the HTML have to be 'well-formed' -- perhaps there is an invalid character or tag -- would that cause the issue ... if so, how do I best investigate this. ( I did try to search for any references to this in relation to QT web rendering engine, but couldn't find anything).

Any advice or suggestions appreciated.

Kind regards
Rich

**Comment by ashkulz** [comment]
Use the `--window-status` flag and/or the `--javascript-delay` flag.
