### ISSUE TITLE
Auto calculate footer height on different page error

### ISSUE THREAD

**Issue by windy** [wkhtmltopdf/wkhtmltopdf#2329]
I have a pdf generate requirement that only the first page will show a full info footer ( with banner info, and pages info, higher than others ), other pages only show a simple footer( just pages info is enough ).

The problem is that lots of margin are found in other pages.

I just tried various methods, like: 
1. specified margin.( it's not suitable for my requirement )
2. using auto calculate. and I had added  js file in footer for other pages hide other unnecessary info. ( I'm very sure that js works fine, new height is setted to correct value )
3. found lots of resources but not useful for me.

But I found the auto calculate method will only calculate footer height once. Then it will use it on every page.

How to solve this problem?  Or is there anything wrong for me?

I try to read the source code but I am a newie to c++. And have no time to do this.

Can you help me to point  it out?

ps:  the version is: wkhtmltopdf 0.12.2.1 (with patched qt),  os is OS X 10.10.3

Very thanks for this good pdf generation tool :+1:

**Comment by alloylab** [comment]
have you tried this on 0.12.5?
