### ISSUE TITLE
wkhtmltopdf.exe sometimes gets stuck

### ISSUE THREAD

**Issue by PeterPanino** [wkhtmltopdf/wkhtmltopdf#2330]
wkhtmltopdf.exe 0.12.2.1, MD5 is: 53569D983934330066D0FA30073C4C56

These are the files from the package:
wkhtmltoimage.exe
wkhtmltopdf.exe
libgcc_s_sjlj-1.dll
libstdc++-6.dll
libwinpthread-1.dll
wkhtmltox.dll

This is the commandline which caused the error:
wkhtmltopdf.exe http://text-mining-tool.com/ R:\test.pdf

This is the error message:
![error](https://cloud.githubusercontent.com/assets/5140376/7333946/a789b8fe-eb81-11e4-89cd-d682e6b6c2df.png)

OS: Windows 7 x64 SP1

Sometimes wkhtmltopdf.exe works just fine, and then sometimes it gets stuck in the middle of the process. Don't know why.

**Comment by alloylab** [comment]
have you tried this on 0.12.5?

**Comment by Tomsgu** [comment]
Closing as there is no feedback from the author.
