### ISSUE TITLE
Can I get paid support?

### ISSUE THREAD

**Issue by geri777** [wkhtmltopdf/wkhtmltopdf#2332]
@ashkulz - is it possible to get paid support? Thanks.

**Comment by ashkulz** [comment]
For what, exactly? For limitations in the WebKit rendering engine, nothing is possible. For Qt bugs, KDAB does consulting related to that. For wkhtmltopdf, post what you need.

**Comment by geri777** [comment]
Thank you for your reply. I am not sure on the split between Qt and WebKit in this project.
My problems which I would like to have solved are:

- CSS page-break-before/after does not work - there is no page break.
- CSS letter-spacing looks differently than in the browser (Chrome). The spacing is much wider in the PDF than in the html.

Many thanks,
Geri

**Comment by geri777** [comment]
@ashkulz - could you please tell me if you have any suggestion on my issues above - and if they are rather Webkit or rather Qt related?

Thanks,
Geri

**Comment by ashkulz** [comment]
Sorry, I thought I had already replied.
* CSS `page-break-after: always` does work - can you show a minimal testcase where it doesn't work? If you are trying to use `avoid`, [it may not work](https://bugs.webkit.org/show_bug.cgi?id=5097).
* That is a known issue, see #1575 -- it is most likely WebKit related (integration with Qt font system).

**Comment by geri777** [comment]
Hi ashkulz,
many thanks for your answer. This is my page-break test:
http://54.68.118.18/print2pdf/?url=http://54.68.118.18/print2pdf/test.htm
(the html file URL can be found in the link above)

Thanks,
Geri

**Comment by ashkulz** [comment]
Please use the binaries from the official website, they are likely to provide better output.

**Comment by geri777** [comment]
Thank you, ashkulz, that was it! I downloaded and installed wkhtmltopdf from http://wkhtmltopdf.org/downloads.html

**Comment by ashkulz** [comment]
Closing issue as it seems to be fixed for you.
