### ISSUE TITLE
custom icon fonts

### ISSUE THREAD

**Issue by dreerr** [wkhtmltopdf/wkhtmltopdf#2333]
When using custom icon fonts, there seems to be some kind of problem, as all the font icons are displayed wrong. When parsing a Tweet like https://twitter.com/mrpalacz/status/592622002940293120 all the icons are displayed wrong. 

![file](https://cloud.githubusercontent.com/assets/1454661/7345990/63e7b97a-ecda-11e4-9860-15fce6173c33.jpg)

also tried to alter the css file and base64 encode it, but it with no luck.

Parsing the icons from FontAwesome works fine…

**Comment by matrixise** [comment]
Have you found the solution for the bad rendering of your icon ? I have the same problem with the fontawesome package and the fa-phone icon.

**Comment by mrpalacz** [comment]
No unfortunatly not, I'm not able to pin down the problem, please tell me if you found a solution



Mag.art. Julian Palacz / julian.palacz.at / +43 699 1414 2135
Weintraubengasse 15, 1020 Vienna, Austria

**Comment by BigMurry** [comment]
I have faced the same problem. I've managed to find that I've used two different css file with each one importing a distinct icon font file. Here is the problem, the two icon font files content two different icon but with the same content, say '\e61f'. And unfortunately wkhtmltopdf chooses the wrong font icon file to find the icon. I did a test for removing one css file, then wkhtmltopdf found the right icon.

**Comment by stil4m** [comment]
I had the same problem on my OS X (10.10) machine. On Ubuntu 14.04.1 I was able to to render the icons correctly. Both machines are running `wkhtmltopdf  0.12.2.1` (with patched qt). 
Maybe this helps to drill down the problem.

**Comment by jlove73071** [comment]
Is anyone able to get google's Material Icons to work with wkhtmltopdf? I've been base64 encoding the truetype and woff versions with no luck, as well as pointing to them directly via url() in the css. Works when rendered using browser, doesn't work with WK.

**Comment by arenoir** [comment]
@jlove73071 material icons work for me using css src data with base64 string.

https://gist.github.com/arenoir/812e44c743285dc29974

**Comment by Tomsgu** [comment]
Closing as the given link works fine in 0.12.5. I assumed it was fixed in newer versions.
