### ISSUE TITLE
Upgraded Tomcat, wkhtmltopdf will not work

### ISSUE THREAD

**Issue by srbonham1** [wkhtmltopdf/wkhtmltopdf#2334]
We upgraded from Tomcat 6.0.33 to Tomcat 8.0.22 to address SSL issues.  The WKHTMLTOPDF stopped working.   It states there is an "ssl error" and gives the option to supress it with the flag as a parameter.  Even if I supress it, it still prints a white screen.  We reverted back to 6.0.33 and low and behold we were printing PDF's again.

Can you direct me regarding this issue?  Any way of putting wkhtmltopdf into verbose to see where it is choking?

Thanks,
Shawn

**Comment by ashkulz** [comment]
Nothing to do with wkhtmltopdf.

**Comment by srbonham1** [comment]
I did not say it was a direct issue with wkhtmltopdf.  Is there a way to identify the error message (the reason it will not print off a website using Tomcat 8)?

**Comment by ashkulz** [comment]
I don't use Tomcat, can't help with anything other than the command line. Ask on StackOverflow or a tomcat help forum.
