### ISSUE TITLE
print-media-type

### ISSUE THREAD

**Issue by hilmak01** [wkhtmltopdf/wkhtmltopdf#2336]
I have an html file that uses one css file. Inside this file at the very bottom i use this for styles that need to be applied ONLY to the printer version of the page

@media print{
   ....print styles here...
}
When I call wkhtmltopdf --print-media-type input.html output.pdf, it renders the pdf with styles that are only in the @media print enclosure and ignores the rest of the styles - which DO NOT have @media type specified

Is this normal, or what am i doing wrong here? Do I need to specify all styles for print inside @media print?

**Comment by alloylab** [comment]
What version? have you tried this on 0.12.5?

**Comment by alloylab** [comment]
We are closing this out since we haven't heard from you. If you are still having this issue please feel free to re-open it. Thanks.

**Comment by engrmahabub** [comment]
I have same issue for wkhtmltopdf django .
My print media css is following.
@media print {
        .new-page {
            page-break-before: always;
        }
    }

But when i generate **pdf** above css not affect on the pdf file.
