### ISSUE TITLE
Compiling examples fails

### ISSUE THREAD

**Issue by samuelcolvin** [wkhtmltopdf/wkhtmltopdf#2337]
Cloning the repo today (7494522bfe4b37bf741bbd7417f1e4c81148fd4d) and compiled as per the instructions in INSTALL.md and all went fine.

I then installed via the generated `.deb` file.

When i run `make` form inside the examples dir I get:

	cc -I ../include   -L ../bin -lwkhtmltox -Wall -ansi -pedantic -ggdb  pdf_c_api.c   -o pdf_c_api
	/tmp/cc1bRiqu.o: In function `phase_changed':
	/home/samuel/repos/wkhtmltopdf/examples/pdf_c_api.c:35: undefined reference to `wkhtmltopdf_current_phase'
	/home/samuel/repos/wkhtmltopdf/examples/pdf_c_api.c:36: undefined reference to `wkhtmltopdf_phase_description'
	/tmp/cc1bRiqu.o: In function `main':
	/home/samuel/repos/wkhtmltopdf/examples/pdf_c_api.c:56: undefined reference to `wkhtmltopdf_init'
	/home/samuel/repos/wkhtmltopdf/examples/pdf_c_api.c:63: undefined reference to `wkhtmltopdf_create_global_settings'
	/home/samuel/repos/wkhtmltopdf/examples/pdf_c_api.c:65: undefined reference to `wkhtmltopdf_set_global_setting'
	/home/samuel/repos/wkhtmltopdf/examples/pdf_c_api.c:67: undefined reference to `wkhtmltopdf_set_global_setting'
	/home/samuel/repos/wkhtmltopdf/examples/pdf_c_api.c:73: undefined reference to `wkhtmltopdf_create_object_settings'
	/home/samuel/repos/wkhtmltopdf/examples/pdf_c_api.c:75: undefined reference to `wkhtmltopdf_set_object_setting'
	/home/samuel/repos/wkhtmltopdf/examples/pdf_c_api.c:78: undefined reference to `wkhtmltopdf_create_converter'
	/home/samuel/repos/wkhtmltopdf/examples/pdf_c_api.c:81: undefined reference to `wkhtmltopdf_set_progress_changed_callback'
	/home/samuel/repos/wkhtmltopdf/examples/pdf_c_api.c:84: undefined reference to `wkhtmltopdf_set_phase_changed_callback'
	/home/samuel/repos/wkhtmltopdf/examples/pdf_c_api.c:87: undefined reference to `wkhtmltopdf_set_error_callback'
	/home/samuel/repos/wkhtmltopdf/examples/pdf_c_api.c:90: undefined reference to `wkhtmltopdf_set_warning_callback'
	/home/samuel/repos/wkhtmltopdf/examples/pdf_c_api.c:97: undefined reference to `wkhtmltopdf_add_object'
	/home/samuel/repos/wkhtmltopdf/examples/pdf_c_api.c:100: undefined reference to `wkhtmltopdf_convert'
	/home/samuel/repos/wkhtmltopdf/examples/pdf_c_api.c:104: undefined reference to `wkhtmltopdf_http_error_code'
	/home/samuel/repos/wkhtmltopdf/examples/pdf_c_api.c:107: undefined reference to `wkhtmltopdf_destroy_converter'
	/home/samuel/repos/wkhtmltopdf/examples/pdf_c_api.c:110: undefined reference to `wkhtmltopdf_deinit'
	collect2: error: ld returned 1 exit status
	<builtin>: recipe for target 'pdf_c_api' failed
	make: *** [pdf_c_api] Error 1

Am I doing something dumb?

OS: ubuntu 14.10 64 bit.

**Comment by ashkulz** [comment]
The package will install in `/usr/local`, so you'll have to fix the `Makefile` to specify the include and library paths correctly.

**Comment by samuelcolvin** [comment]
Ok, i've tried what you suggested and am still getting the above "undefined reference" errors. I'm also tried the `schroot` approach you suggested in #1680 with the same result.

With the `.so` files copied in to `~/wkhtmltopdf/bin`, from the examples dir:
```
sl:examples || gcc -I../include -L../bin -lwkhtmltox -Wall -ansi -pedantic -ggdb  pdf_c_api.c -o pdf_c_api
/tmp/cc2cAOEV.o: In function `phase_changed':
/home/samuel/wkhtmltopdf/examples/pdf_c_api.c:35: undefined reference to `wkhtmltopdf_current_phase'
/home/samuel/wkhtmltopdf/examples/pdf_c_api.c:36: undefined reference to `wkhtmltopdf_phase_description'
/tmp/cc2cAOEV.o: In function `main':
/home/samuel/wkhtmltopdf/examples/pdf_c_api.c:56: undefined reference to `wkhtmltopdf_init'
/home/samuel/wkhtmltopdf/examples/pdf_c_api.c:63: undefined reference to `wkhtmltopdf_create_global_settings'
/home/samuel/wkhtmltopdf/examples/pdf_c_api.c:65: undefined reference to `wkhtmltopdf_set_global_setting'
/home/samuel/wkhtmltopdf/examples/pdf_c_api.c:67: undefined reference to `wkhtmltopdf_set_global_setting'
/home/samuel/wkhtmltopdf/examples/pdf_c_api.c:73: undefined reference to `wkhtmltopdf_create_object_settings'
/home/samuel/wkhtmltopdf/examples/pdf_c_api.c:75: undefined reference to `wkhtmltopdf_set_object_setting'
/home/samuel/wkhtmltopdf/examples/pdf_c_api.c:78: undefined reference to `wkhtmltopdf_create_converter'
/home/samuel/wkhtmltopdf/examples/pdf_c_api.c:81: undefined reference to `wkhtmltopdf_set_progress_changed_callback'
/home/samuel/wkhtmltopdf/examples/pdf_c_api.c:84: undefined reference to `wkhtmltopdf_set_phase_changed_callback'
/home/samuel/wkhtmltopdf/examples/pdf_c_api.c:87: undefined reference to `wkhtmltopdf_set_error_callback'
/home/samuel/wkhtmltopdf/examples/pdf_c_api.c:90: undefined reference to `wkhtmltopdf_set_warning_callback'
/home/samuel/wkhtmltopdf/examples/pdf_c_api.c:97: undefined reference to `wkhtmltopdf_add_object'
/home/samuel/wkhtmltopdf/examples/pdf_c_api.c:100: undefined reference to `wkhtmltopdf_convert'
/home/samuel/wkhtmltopdf/examples/pdf_c_api.c:104: undefined reference to `wkhtmltopdf_http_error_code'
/home/samuel/wkhtmltopdf/examples/pdf_c_api.c:107: undefined reference to `wkhtmltopdf_destroy_converter'
/home/samuel/wkhtmltopdf/examples/pdf_c_api.c:110: undefined reference to `wkhtmltopdf_deinit'
collect2: error: ld returned 1 exit status
```

The thing is if I change either the `-I` or `-L` paths I get errors saying either `...pdf.h cannot be found` or   `cannot find -lwkhtmltox` which indicates it is finding both the header file and the shared library.

A clear explanation on how exactly to build these examples would be really appreciated.

**Comment by samuelcolvin** [comment]
Ok I at last got it to compile by switching the order of the arguments, apparently this is a recent change in gcc:

    gcc -I../include pdf_c_api.c -o pdf_c_api -lwkhtmltox -Wall -ansi -pedantic -ggdb

worked. (the `-L...` argument turned out to be superfluous in my case)

**Comment by ashkulz** [comment]
Are you sure you needed the `-I../include`? It should have picked it up from `/usr/local/include`.

**Comment by iman4000** [comment]
i did what @samuelcolvin said and it compile without error but when i want to run the program i got this error:
./image_c_api: error while loading shared libraries: libwkhtmltox.so.0: cannot open shared object file: No such file or directory

**Comment by irontoolki** [comment]
same problem  as @iman4000  reported. 
`~/wkhtmltopdf/examples$ ./output.out 
./a.out: error while loading shared libraries: libwkhtmltox.so.0: cannot open shared object file: No such file or directory
`

**Comment by undying** [comment]
> same problem as @iman4000 reported.
> `~/wkhtmltopdf/examples$ ./output.out ./a.out: error while loading shared libraries: libwkhtmltox.so.0: cannot open shared object file: No such file or directory `

Hello!
There is a two possible solutions:
1. If you are using library installed by .deb package, then pass `-Wl,-rpath,/usr/local/lib` to gcc:
```
  gcc  \ 
    -Wall -ansi -pedantic -ggdb \
    html_to_pdf.c \
    -o html_to_pdf \
    -lwkhtmltox \
    -Wl,-rpath,/usr/local/lib
```
2. or when running binary, you may set environment variable `LD_LIBRARY_PATH=/usr/local/lib`
```
LD_LIBRARY_PATH=/usr/local/lib/ ./html_to_pdf
```

**Comment by irontoolki** [comment]
Thnaks @undying, it's work.
