### ISSUE TITLE
Customized Internal Link form html page to TOC 

### ISSUE THREAD

**Issue by railsfactory-arunkumar-n** [wkhtmltopdf/wkhtmltopdf#2340]
Is there is any possibility to provide internal link between our html page to TOC(table of content) page.

**Comment by alloylab** [comment]
What version? have you tried this on 0.12.5?

**Comment by alloylab** [comment]
We are closing this out since we haven't heard from you. If you are still having this issue please feel free to re-open it. Thanks.
