### ISSUE TITLE
international characters in URL

### ISSUE THREAD

**Issue by wshatford** [wkhtmltopdf/wkhtmltopdf#2342]
I get a HostNotFoundError with (file is on local drive :: Zorin OS9 - Unbuntu :: wkhtmltopdf 0.12.2.1 : 
wkhtmltopdf "SchönebergBerlinDE.html" "SchönebergBerlinDE.pdf"          

I think it is trying to open: schnebergberlinde-g03.html

**Comment by alloylab** [comment]
have you tried this on 0.12.5?

**Comment by alloylab** [comment]
We are closing this out since we haven't heard from you. If you are still having this issue please feel free to re-open it. Thanks.
