### ISSUE TITLE
Problem with page not rendering

### ISSUE THREAD

**Issue by raypitmon** [wkhtmltopdf/wkhtmltopdf#2347]
Hi,

I am trying to use it on a certain page from a leftronic dashboard, but only half of the page ends up in the image.
## ![out](https://cloud.githubusercontent.com/assets/11006921/7461010/d5facb96-f26c-11e4-879d-25ca6c8720b1.png)

I'm wondering if there are any switches I should try or if there is any other debug settings that would help troubleshoot the problem.

I am using 0.12.2.1 (with patched qt) on Debian Wheezy (and I've tried on Mac with the same results).

Here is the command I'm running (with obfuscated url):

wkhtmltoimage --javascript-delay 2000 https://www.leftronic.com/share/xxxx out.png

I appreciate any help or thoughts!

Thanks,

-Ray

**Comment by alloylab** [comment]
have you tried this on 0.12.5?

**Comment by alloylab** [comment]
We are closing this out since we haven't heard from you. If you are still having this issue please feel free to re-open it. Thanks.
