### ISSUE TITLE
Add header & footer to cover 0.12.2.1

### ISSUE THREAD

**Issue by marmie1** [wkhtmltopdf/wkhtmltopdf#2351]
Hi,

I'm having a problem to add header and footer to cover page since in this patch it's being removed from cover page. Tried editing header & footer javascript files but couldn't do it. Does anybody has a solutions or a script for this one?

Thank you!

**Comment by Maxyme** [comment]
My solution was to generate 2 separate pdf in C#, as byte[], then merge together using ItextSharp, a pdf library. I believe it can also be done with PdfTk, merge the cover pdf as the first document.

**Comment by ashkulz** [comment]
There is no sense in having a header and footer on a cover page -- if you want to do so, just make it a normal HTML page.

**Comment by Harolder** [comment]
I'm having the same problem.
