### ISSUE TITLE
Text overlaid in PDF but not in original html

### ISSUE THREAD

**Issue by graham12357** [wkhtmltopdf/wkhtmltopdf#2354]
The following html displays differently in Chrome Browser and PDF created from it:

``` html
<style>
@media screen {
   CENTER {page-break-before: always}
   BODY {font-family: "Tahoma";
         font-size: 10pt; font-weight: 400;
         }
   .DrillDown {width: 157ex; }
 }
 </style>
<head>
<META http-equiv="Content-Type" content="text/html; charset=UTF-8">
</head>
<body>
<br>
<CENTER> <HR> </CENTER>
<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
<div class="DrillDown">
<div style="position: absolute">Material:</div>
<br>
<div style="position: absolute">SPECIAL</div>
</div>
</body>
```

In the browser the text is in separate lines: e.g
![image](https://cloud.githubusercontent.com/assets/12322843/7556754/e381a41a-f7c1-11e4-8cd2-dab572324f3b.png)

In the PDF, viewed with Foxit,, the first page is blank and the second page looks like:
![image](https://cloud.githubusercontent.com/assets/12322843/7556667/d94a46e8-f7bf-11e4-8250-762059bb9d57.png)

Reducing the width, or reducing the number of '<br>' s before the text cause the problem to go away. 

wkhtmltopdf version: wkhtmltopdf 0.12.2.1 (with patched qt)
This is a linux system: uname -a =>Linux supportdata 2.6.32-504.el6.x86_64 #1 SMP Wed Oct 15 04:27:16 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

The windows exe downloaded from the site generates the correct PDF i.e the fields not overlaid

**Comment by alloylab** [comment]
have you tried this on 0.12.5?

**Comment by Tomsgu** [comment]
Closing as there is no response and the given example is working fine in 0.12.5.
