### ISSUE TITLE
Compile for ARMV71 & ARM6l

### ISSUE THREAD

**Issue by GM-Script-Writer-62850** [wkhtmltopdf/wkhtmltopdf#2356]
I'd like to run this on a raspberry pi, is there a way to?

**Comment by ashkulz** [comment]
See #1868 for an earlier attempt, I don't have a Pi so can't really test anything.

**Comment by GM-Script-Writer-62850** [comment]
you can get a used one pretty cheap, there are 2 different architectures for them
the A, A+, B, and B+ are ARM6l while the raspberry pi 2 B is ARM7l
