### ISSUE TITLE
How is "--cache-dir" working in practice?

### ISSUE THREAD

**Issue by Vad1mo** [wkhtmltopdf/wkhtmltopdf#2357]
We enabled "--cache-dir" to improve the performance but it only works partly mainly because we don't understand  how is working.

What is cached and how. Is HTML, CSS and JS cached?
How is it controlled? Cache-Control in response Header?

Out goal is to cache and reuse CSS and JS as they are always stay the same. Can this be controlled via response header?

**Comment by garex** [comment]
+1

**Comment by Vad1mo** [comment]
@ashkulz can you enlighten us on how cache is working especially if the process stops and starts.

**Comment by SunHuawei** [comment]
```
This patch adds a --cache-dir option.

It creates a QNetworkDiskCache if the option is specified.

Deleting the directory is left to the user, as he might want to re-use the cache for a later invocation.
```

Check it here: [https://github.com/wkhtmltopdf/wkhtmltopdf/pull/9]

**Comment by BigNerd** [comment]
Can we share the same cache-dir between multiple wkhtmltopdf processes running in parallel?

**Comment by NiR-** [comment]
[Citing Qt documentation](http://blog.qt.io/blog/2011/04/29/http-caching-with-qt/) about `PreferNetwork` value of `QNetworkRequest::CacheLoadControlAttribute`, used by wkhtml (it doesn't set any value and this one is the default):

> If the resource can be found in the cache and the age of the cached resource is less than the maximum age (used headers: “Age“, “Cache-Control: max-age“) or the resource has not expired (used header: “Expires“), then it is loaded from the cache. If the resource has expired or has exceeded its maximum age, it is loaded from the server, if possible with modification information (used headers: “If-Modified-Since” if “Last-Modified” was given, and “If-None-Match” if “ETag” was given).

[Also note that][http://doc.qt.io/qt-4.8/qnetworkdiskcache.html#details):

> you have to set the cache directory before it will work.

@BigNerd If both of your processes write the exact same file at the exact same time there might problem. But there should not be any other problem.

**Comment by Tomsgu** [comment]
Closing as answers were provided.
