### ISSUE TITLE
Support for src=/ and src=//

### ISSUE THREAD

**Issue by kenorb** [wkhtmltopdf/wkhtmltopdf#2359]
I've remote URL such as [this](http://www.scribd.com/doc/15049545/Saxo-Trader-2-Walk-Through) one.

However when I'm downloading, it's showing the following warnings:

    Loading pages (1/6)
    Warning: Failed to load file://cdn.optimizely.com/js/653710485.js (ignore)
    Warning: Failed to load file://pagead2.googlesyndication.com/pagead/js/google_top_exp.js (ignore)
    Warning: Failed to load file://www.google-analytics.com/analytics.js (ignore)
    Warning: Failed to load file:///images/filetypes/pdf.png (ignore)
    Warning: Failed to load file:///images/filetypes/txt.png (ignore)
    Warning: Failed to load file://www.googletagservices.com/tag/js/gpt.js (ignore)
    Warning: Failed to load file://connect.facebook.net/en_US/sdk.js (ignore)

The files in the source are like:

    <script src="//cdn.optimizely.com/js/653710485.js">
    <script src="//pagead2.googlesyndication.com/pagead/js/google_top_exp.js">
    <img src="/images/filetypes/txt.png">

Is there any way that `wkhtmltopdf` can assume automatically that these files are http by default (the same protocol as it's used during downloading) and if host is missing, they're on the same host?

Tested with: wkhtmltopdf 0.12.2.1 (with patched qt) on OS X

**Comment by kenorb** [comment]
I've fixed the file with `ex`:

    ex -V1 page.html <<-EOF
      %s,'//,'http://,ge 
      %s,"//,"http://,ge 
      %s,'/,'http://www.scribd.com/,ge
      %s,"/,"http://www.scribd.com/,ge
      wq " Update changes and quit.
    EOF

but it didn't solve all of them (some of them were broken somewhere on remote links).
But after fix, I've got another error (see: #2187):

> Exit with code 1 due to network error: UnknownContentError

**Comment by ashkulz** [comment]
Protocol relative URLs are not supported in Qt, see #1634

**Comment by kenorb** [comment]
So that mean cannot be fixed? Or it's reported already somewhere against Qt?

**Comment by ashkulz** [comment]
Not sure if it is reported against Qt, but it definitely doesn't work. You might want to report it upstream, if you have a suggestion on how to implement it [inside Qt or QtWebKit] I'd be willing to push the patch upstream.

**Comment by kenorb** [comment]
Reported in here: [QTBUG-46240](https://bugreports.qt.io/browse/QTBUG-46240).

**Comment by C-Duv** [comment]
My $0.02 but: it works with v0.9.6 (at least no error is thrown and PDF is generated).

**Comment by ashkulz** [comment]
That uses a very old version of Qt/Webkit, newer versions improve both in features & validations :smile:

**Comment by C-Duv** [comment]
You're right but it:
* may help someone willing to use older version to solve it's relative URL issues
* is weird to break such feature when releasing new version

PS: version 0.11.0 rc1 also does not have the problem.
