### ISSUE TITLE
The header of the table is being placed over the content, when thead have more then 1 tr

### ISSUE THREAD

**Issue by liorSolcito** [wkhtmltopdf/wkhtmltopdf#2360]
Hello.
I try make pdf from huge html table.
When i have only one row (tr) on thead element, the wkhtmltopdf generate beautiful pdf!
But when the thead element contain 3 rows (3 tr elements), after the first page the thead placed over the content.

Any solution please :)

**Comment by ashkulz** [comment]
Looks like related to #1524, use the workaround mentioned in it.
