### ISSUE TITLE
OnDemand images are missing (http://www.flipkart.com and www.cnn.com)

### ISSUE THREAD

**Issue by georgeli2010** [wkhtmltopdf/wkhtmltopdf#2362]
Hi Team,

I am trying to convert the below mentioned website to PDF, but the ondemand images are missing in the converted PDF. Can you please let me know, any tweaks or tricks that acquire images in the output PDF.

http://www.cnn.com
http://www.flipkart.com

Command line -  wkhtmltopdf.exe http://www.cnn.com/ G:/test/wkhtmlcnn.pdf
WKHTML version - wkhtmltopdf 0.12.2.1 (with patched qt)
OS and version - Windows 8.1

Thanks,
George

**Comment by DanielCeregatti** [comment]
Add the --javascript-delay argument. From wkhtmltopdf -H:
      --javascript-delay <msec>       Wait some milliseconds for javascript

**Comment by georgeli2010** [comment]
Thanks daniel,

I have already tried giving -javascript-delay 30000. but still no improvement. Any other options to acquire on demand images or this is a QtWebKit bug?

**Comment by ashkulz** [comment]
Use the `--window-status` flag and set `window.status` when all the on-demand images have been loaded.

**Comment by georgeli2010** [comment]
Thanks ashkulz,

I cannot set window.status to public websites like (cnn.com, flipkart.com and etc.) Any other options to achieve my requirement?
