### ISSUE TITLE
Amazon EC2 Linux issue

### ISSUE THREAD

**Issue by devua2014** [wkhtmltopdf/wkhtmltopdf#2363]
Hello guys,

I installed wkhtmltopdf on default Amazon EC2 Linux instance:
sudo yum install ~/install/wkhtmltox-0.12.2.1_linux-centos6-amd64.rpm

It works well with the different URLs but I permanently receive the same error for these links:
http://www.vitals.com/doctors/Dr_Richard_A_Weiss.html
http://www.vitals.com/doctors/Dr_Richard_A_Weiss/reviews

Here is an example of the command I ran:

wkhtmltopdf --load-error-handling ignore --load-media-error-handling ignore --disable-external-links --disable-internal-links --javascript-delay 1000 "http://www.vitals.com/doctors/Dr_Richard_A_Weiss.html" "/home/ec2-user/1.pdf"

Error:
QImage: out of memory, returning null image                  ] Page 1 of 7
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted

However, it works well with these URLs on Windows.
Tried to find an answer on the different sites but no luck. Any help would be appreciated.

Best regards,
A.

**Comment by ashkulz** [comment]
see #2338 on how to compile and run it on Amazon Linux.
