### ISSUE TITLE
Generate Image and PDF with custom fonts using wkhtmltoimage and wkhtmltopdf (Linux centos6 64-bit, hostgator )

### ISSUE THREAD

**Issue by akashvarlani** [wkhtmltopdf/wkhtmltopdf#2365]
Suffering from custom fonts with wkhtmltoimage and wkhtmltoimage and i have posted the detailed question on stackoverflow i.e http://stackoverflow.com/questions/30292203/generate-image-and-pdf-with-custom-fonts-using-wkhtmltoimage-and-wkhtmltopdf-li

**Comment by alloylab** [comment]
What version? have you tried this on 0.12.5?

**Comment by Tomsgu** [comment]
Closing as the answer were provided on stackoverflow.
