### ISSUE TITLE
wkhtmltopdf does not respect &nbsp;  

### ISSUE THREAD

**Issue by lucasmpereira** [wkhtmltopdf/wkhtmltopdf#2366]
I have the following content: 

39990.0CSB7&nbsp;&nbsp;21436.101527&nbsp;&nbsp;04294.-60019&nbsp;&nbsp;2&nbsp;&nbsp;64750000000045

When I try to convert to pdf and instead of have a single row the pdf returns the content in two lines. Theres something I can configure?

**Comment by alloylab** [comment]
What version? have you tried this on 0.12.5?

**Comment by Tomsgu** [comment]
Closing as there is no feedback and I can reproduce this issue.

**Comment by nitinsmartsense** [comment]
Not working with `wkhtmltoimage 0.12.5 (with patched qt)`
You can find test files [here](https://github.com/nitinsmartsense/wkhtmltest)

**Comment by nitinsmartsense** [comment]
Not working with `wkhtmltoimage 0.12.5 (with patched qt)`
You can find test files [here](https://github.com/nitinsmartsense/wkhtmltest)
