### ISSUE TITLE
Soft hyphens (either as &shy; or using the utf-8 codepoint itself) result in unknown glyph squares

### ISSUE THREAD

**Issue by klondi** [wkhtmltopdf/wkhtmltopdf#2368]
This was already pointed in #1722 but I can't reopen the issue. When using soft hyphens (the provided test uses the utf-8 code point but the issue arises also with &shy;) the character is replaced by a strange unknown character box (which may or may not be followed by the hyphen itself).

Attached are test files and the resulting output with the packaged wkhtmltopdf 12.2.1 for Centos 7 (`wkhtmltopdf 0.12.2.1 (with patched qt)`).

**Comment by klondi** [comment]
Seems I can't upload the files :( 
Here are on my own hosting: http://klondike.es/wkhtmltopdf_shy_bug_sample.zip

**Comment by jobe451** [comment]
same problem here, also on 12.2.1 for Centos 7

**Comment by ashkulz** [comment]
This normally happens if the character is not present in the font you are specifying. Make sure to have the necessary font packages installed.

**Comment by neufeind** [comment]
Why does a non-displayed &shy; (in the middle of a word, ...) need to be displayed? One installation that I had the problem with lately used webfonts.
