### ISSUE TITLE
It broken down when i run image_c_api the second time

### ISSUE THREAD

**Issue by BrightWind** [wkhtmltopdf/wkhtmltopdf#2373]
I download the binary distribution from sourceforge.net. And I try to test the wkhtmltoimage functionlity in windows.  then I rename the 'main()' function to an normal function like 'HtmlToImage()'; but It broken down when i call HtmlToImage() the second time, it broken down at :

/* Perform the actual convertion */
if (!wkhtmltoimage_convert(c))
	fprintf(stderr, "Convertion failed!");

**Comment by ashkulz** [comment]
You can call `wkhtmltoimage_init` and `wkhtmltoimage_deinit` only once per process. Doing it again is not guaranteed to work.
