### ISSUE TITLE
Url encoded spaces in link references are replaced by real spaces in resulting PDF

### ISSUE THREAD

**Issue by lumpidu** [wkhtmltopdf/wkhtmltopdf#2374]
For the following html link fragment, the url encoded spaces are replaced by real spaces in generated PDF:

``` html
<li><a href="http://localhost/wiki/System%20Requirements/SYRS%20PrjA">SYRS PrjA</a></li>
```

wkhtmltopdf generates PDF's with clickable but broken links. I'd expect that links are kept as-is, so when clicking on them the links are still valid and URL encoded.

wkhtmltopdf version: 0.12.2.1

**Comment by brendon** [comment]
Any pointers for solving this one? Should we double-encode the links?

**Comment by UnConundrum** [comment]
Any chance this issue will be addressed?

**Comment by brendon** [comment]
I just have to double-encode the links unfortunately (well the `href` part anyway). Makes things a bit awkward.

**Comment by Tomsgu** [comment]
Does this happen still in 0.12.5 version?

**Comment by brendon** [comment]
I'm unsure.

**Comment by Tomsgu** [comment]
I can't reproduce this issue in a newest version. Please feel free to re-open it if you still have these kind of problems.

**Comment by brendon** [comment]
I can confirm that it doesn't seem to occur in 0.12.5 anymore.
