### ISSUE TITLE
Lacks speed and increase file size 10 times

### ISSUE THREAD

**Issue by verma-neeraj-in** [wkhtmltopdf/wkhtmltopdf#2375]
When I provide opacity to background using common css rules. Wkhtmltopdf takes lots of time to generate PDF and also increase the file size 10 times if i do not apply opacity to background.

**Comment by ashkulz** [comment]
This is a known issue, see [this comment](https://github.com/wkhtmltopdf/wkhtmltopdf/issues/1510#issuecomment-70362184).
