### ISSUE TITLE
Chinese characters seem to be overlapped in the output PDF (CentOS 6.2)

### ISSUE THREAD

**Issue by Thangaraj-Ramasamy** [wkhtmltopdf/wkhtmltopdf#2376]
https://groups.google.com/d/msg/wkhtmltopdf-general/_c6P4qImM1g/YERovqXh10sJ

![chinesefontsmerged](https://cloud.githubusercontent.com/assets/3590878/7782942/90db0866-014c-11e5-9295-99e7f2f6b224.png)

Please help me fix this issue.

**Comment by Thangaraj-Ramasamy** [comment]
![chineseandjapanesefontsoverlap](https://cloud.githubusercontent.com/assets/3590878/7796166/339f2f06-02fa-11e5-93a8-e1fff8da550b.png)

It seems to be a problem with font-size.

**Comment by Thangaraj-Ramasamy** [comment]
It works fine with the following changes in `/etc/fonts/fonts.conf`. Not sure about the fix though.
```javascript
       <match target="font">
                <edit name="hintstyle" mode="assign">
                        <const>hintnone</const>
                </edit>
        </match>
        <match target="font">
                <test qual="any" name="family" compare="eq">
                        <string>MS Gothic</string>
                </test>
                <edit name="hintstyle" mode="assign">
                        <int>3</int>
                </edit>
        </match>
```

**Comment by ashkulz** [comment]
What does hintstyle=3 mean?

**Comment by Thangaraj-Ramasamy** [comment]
`hintstyle=3` (*full hint*) is for font kerning.

Ref: http://www.freedesktop.org/software/fontconfig/fontconfig-user.html

**Comment by Tomsgu** [comment]
Is this still an issue in 0.12.5?

**Comment by Tomsgu** [comment]
Closing as there is no feedback, so it seems to be fixed. Please feel free to reopen this issue if you have the same problem.
