### ISSUE TITLE
After Debian Install: postgresql server stops working

### ISSUE THREAD

**Issue by planctron** [wkhtmltopdf/wkhtmltopdf#2379]
Current install scripts for debian repository (apt-get) caused severe problem.
Apparently postgresql server version 9.4 was installed  in addition to previous  9.1  (Why?)
and 9.1 ist NOT STARTING any more.
Debian 7.8

**Comment by ashkulz** [comment]
So how is this an issue with wkhtmltopdf?

**Comment by planctron** [comment]
Here some more detail:
I am using Odoo 8.0. There are hints when creating reports, that wkhtmltopdf  has to be in version 0.12.x and should be upgraded to support some header or footer function.
=> I installed on Debian 7.8 with  "apt-get install wkhtmltopdf".
I confirmed the installation of a huge number of packages, thinking this will be fine.
During install my Odoo systems went down.
I restarted and saw that postgresq 9.1, the previous version did not start.

So the first thing seemed obvious:  the packages contained some postgresql 9.4 installation.
If this does not make sense, or I was wrong, I am sorry.
Is it possible that the another pending step of  apt-get install  was run only then?
I did not get any question about confirming this.

The reason why psql 9.1 was not starting was  scary.
Some binaries  in  ...9.1/bin/ were missing.   Not all of them, but some.
I have no trace of what caused this, but it "must" have happened during this  9.4 install.

I did not find any hint about such problems related to postresql 9.4 in general.

If you are sure, this problem cannot be related to the   Debian wkhtmltopdf packages,
you leave this closed.

**Comment by ashkulz** [comment]
If you have a problem with the Debian packages, please get in touch with the Debian Developer who prepared this package (Emmanuel Bouthenot). Direct support will be provided on this tracker only for binaries installed from the [downloads page](http://wkhtmltopdf.org/downloads.html)

**Comment by planctron** [comment]
thank you
will do.
