### ISSUE TITLE
Can you post the possible exit codes?

### ISSUE THREAD

**Issue by onassar** [wkhtmltopdf/wkhtmltopdf#2380]
I've received 134 before when a PDF couldn't be (properly) created
And every now and then receive 1 (unsure at the moment what that means)

**Comment by gokulk16** [comment]
ExitCode | Explanation
-- | --
0 | All OK
1 | PDF generated OK, but some request(s) did not return HTTP 200
2 | Could not something something
X | Could not write PDF: File in use
Y | Could not write PDF: No write permission
Z | PDF generated OK, but some JavaScript requests(s) timeouted
A | Invalid arguments provided
B | Could not find input file(s)
C | Process timeout


As I believe code 1 and Z can be excepted by your wrapper.

**Comment by Tomsgu** [comment]
Closing as the answer was provided.

**Comment by mariusneo** [comment]
@Tomsgu  what would be the error code corresponding to `134` ?

The exit codes enumerated above are alphanumeric, on the other hand the wkhtmltopdf process gives back only numeric error codes.

**Comment by Tomsgu** [comment]
@mariusneo See this answer on stackoverflow: https://stackoverflow.com/questions/23098695/strange-return-value-134-to-call-gawk-in-bash-script?answertab=active#tab-top
