### ISSUE TITLE
HTML to PDF conversion with Bootstrap 3 CSS causing malformed text

### ISSUE THREAD

**Issue by matisoffn** [wkhtmltopdf/wkhtmltopdf#2382]
I have the snippet below that's using this gem as well as the "wkhtmltopdf_binary" gem:

```ruby
def template
	respond_to do |format|
		@case = Case.find(params[:id])

		format.pdf do
			render :pdf => "template",
				   :template => "emails/cases/" + params[:tpl].downcase.tr(' ', '_') + ".html.erb"
		end
	end
end
```

When I view the PDF that it generates, the tables in the HTML template (simple tables using Bootstrap CSS) look great, however, the text is malformed and looks like this:

![](http://i.imgur.com/x0XOIe1.png)

What's causing this?  Is it the CSS, or something I should be doing differently in the markup?  Here's a snippet of the markup that looks like the picture above:

```html
<h2>
  Your application <a href="https://myapp.com/#/cases/<%= @case.id %>"><%= @case.name  %></a> can be viewed online at <a href="https://myapp.com">https://myapp.com</a>
</h2>
<hr />
```

**Comment by wouterbulten** [comment]
Had this issue today too. Try resetting the letter spacing for text that is not rendered correctly. In my case it was as easy as:

```css
h1, h2 {
    letter-spacing: normal !important;
}
```

**Comment by ashkulz** [comment]
@matisoffn: please reopen the issue if the solution suggested by @wouterbulten does not work for you.

**Comment by matisoffn** [comment]
@wouterbulten Sorry for not getting back sooner, busy with other projects, but it worked perfectly.  Had to switch to wkhtmltopdf 0.9.9, but after doing so I got the desired PDF.

Thanks!
