### ISSUE TITLE
wkhtmltoimage 0.12.2.1 incorrect image

### ISSUE THREAD

**Issue by GrahamLock** [wkhtmltopdf/wkhtmltopdf#2383]
I'm running wkhtmltoimage 0.12.2.1 against http://www.thecolchestercakery.co.uk and getting an incorrect image. I have tried 0.12.2.1 against several other sites and the images produced are good.

Using the demo at http://www.hiqpdf.com/demo/ConvertHtmlToImage.aspx for example produces a good image of http://www.thecolchestercakery.co.uk so I'm guessing the problem is not the site code structure as such.

We're looking to use this in an automated fashion for heat map plotting - any help appreciated.

Thanks.

**Comment by alloylab** [comment]
have you tried this on 0.12.5?

**Comment by Tomsgu** [comment]
Closing as there is no feedback and it works well in `0.12.5`?
