### ISSUE TITLE
[request for support] how to build wkhtmltopdf based on patched qt5 for different OS than my own?

### ISSUE THREAD

**Issue by Evertt** [wkhtmltopdf/wkhtmltopdf#2385]
So I'd like to use a build of wkhtmltopdf based on qt5 on my server. Now I'm not used to building sources and the few times I did try I often got errors I didn't know how to fix. But now the extra challenge is that I'm on OS X and my server is on linux (and I don't have ssh access to my server). So I have no idea how to make a build of wkhtmltopdf for linux while I'm on OS X.

Would someone please help me with that?

**Comment by ashkulz** [comment]
Use a VM with Debian Wheezy and follow the instructions in `INSTALL.md` on the `0.13` branch. Please note that there is no "patched" qt5 as yet, just a plain vanilla build -- see the [release plan](https://github.com/wkhtmltopdf/wkhtmltopdf/blob/0.13/README.md#release-plan) on how the `0.13` release will be achieved.
