### ISSUE TITLE
Text is rendered in low quality

### ISSUE THREAD

**Issue by oliversalzburg** [wkhtmltopdf/wkhtmltopdf#2386]
I have the following document (but the issue applies to any document I tested with):

```
> cat pdf.html
<html>
        <style>
                body {
                        font-family: Arial, Helvetica, sans-serif;
                }
        </style>
        <body>
                Hello World!
        </body>
</html>
```

I convert that document with `wkhtmltopdf pdf.html pdf.pdf`. The text in the resulting document has very low quality:

![](http://i.imgur.com/j97XVuV.png)

This is on Debian Jessie (8):

``` shell
> wkhtmltopdf --version
wkhtmltopdf 0.12.2.1 (with patched qt)
```

**Comment by oliversalzburg** [comment]
After running `dpkg-reconfigure fontconfig-config` and accepting all the default values, the issue was resolved.

**Comment by cosmopolit** [comment]
I searched the wolf in sheep's clothing. Thank you very much!
