### ISSUE TITLE
Issue using datepicker js object

### ISSUE THREAD

**Issue by mhavez** [wkhtmltopdf/wkhtmltopdf#2387]
Hi, 

I am using wkhmtltopdf to automate a daily report from a web aplication using Shiny (_a web application framework for R_). I am not a web developper or a js expert (this is why I am using Shiny) so please ask me if I have to provide more details.

My dashboard contains a date input which is basically a datepicker (a js object from **bootstrap-datepicker.min.js**) to which I always provide a default value. 

When I open the application via a browser it works properly (current date : **"2015-05-29"**). The html element contains the following:

``` html
<div id="today" class="shiny-date-input form-group shiny-input-container shiny-bound-input">
            <label class="control-label" for="today">Date</label>
            <input class="form-control datepicker" data-date-language="en" data-date-weekstart="0" data-date-format="yyyy-mm-dd" data-date-start-view="month" data-initial-date="2015-05-29" type="text">
</div>
```

However, when I use wkhmtltopdf the date which is picked up is **always one day before**. In that case it would be : "2015-05-28". This is anoying because all the report is based on this date obviously.

```
wkhtmltopdf --page-width 20in --javascript-delay 2000 http://127.0.0.1:3944 ~/Desktop/test2.pdf
```

Do you have any idea? I encounter this issue on several environment. 

Thanks,
Maxime HAVEZ

**Comment by alloylab** [comment]
What version? have you tried this on 0.12.5?

**Comment by Tomsgu** [comment]
Closing as there is no feedback.
