### ISSUE TITLE
RemoteHostClosedError when connecting to TLSv1.1/1.2 HTTPS server on OS X

### ISSUE THREAD

**Issue by morgant** [wkhtmltopdf/wkhtmltopdf#2388]
I'm running `wkhtmltopdf` 0.12.2.1 on a Mac OS X 10.6.8 Tiger Server as well as an OS X 10.9.5 Mavericks and am attempting to connect to an HTTPS apache 2.2.29 server with a fairly secure setup, incl. disabling SSLv3 & TLS1.0 and using [Mozilla's suggested intermediate compatibility ciphersuite](https://wiki.mozilla.org/Security/Server_Side_TLS#Intermediate_compatibility_.28default.29), configured as follows:

    SSLProtocol -ALL +TLSv1.1 +TLSv1.2
    SSLCompression off
    SSLHonorCipherOrder On
    SSLCipherSuite ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:AES:CAMELLIA:DES-CBC3-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA

Unfortunately, with this setup, `wkhtmltopdf` fails with the following error (on both 10.6.8 & 10.9.5):

    Exit with code 1 due to network error: RemoteHostClosedError

As soon as TLSv1.0 support is enabled on in apache (`SSLProtocol -ALL +TLSv1 +TLSv1.1 +TLSv1.2`), it is able to connect successfully. The [0.12.2.1 release notes](https://github.com/wkhtmltopdf/wkhtmltopdf/releases/tag/0.12.2.1) say it's using OpenSSL 1.0.1l, which does support TLSv1.1 & TLSv1.2, so why does it appear that `wkhtmltopdf` is still trying to use TLS1.0/SSLv3?

At this point, due to TLSv1.0 & RC4 weaknesses, it is advised not to use even TLSv1.0 and is even now a PCI DSS failure.

**Comment by ashkulz** [comment]
@morgant: That's only on Windows, on Linux and OS X the system-installed version of OpenSSL is used. For OS X, it is deprecated and not updated (see #2150) but I do not have a OS X machine to do any development/change related to this.

**Comment by morgant** [comment]
@ashkulz Thanks, that makes sense, esp. since the built-in OpenSSL version on OS X is from the 0.9.8 branch which does not support TLSv1.1 or TLSv1.2. I was aware of some of the OpenSSL changes in OS X, but had missed Issue #2150.

**Comment by ashkulz** [comment]
Do you know which approaches are better to start fixing #2150?

**Comment by ashkulz** [comment]
At this point, it is best to document it as a known issue until someone provide helps regarding the linked issue.
