### ISSUE TITLE
Issue with PDF conversion with # in query for website and also links (file:/// instad of http://)

### ISSUE THREAD

**Issue by debian00001** [wkhtmltopdf/wkhtmltopdf#2391]
Hello,

I am using Windows 7 64 bit with wkhtmltopdf.exe version 0.12.2.2.

I am trying to do a craigslist query like this.

http://chicago.craigslist.org/search/chc/sss?sort=date&postedToday=1&query=cb2&hasPic=1#grid

The problem is wkhtmltopdf doesn't seem to respect the #grid.

C:\Users\USER> "C:\PROGRA~1\wkhtmltopdf\bin\wkhtmltopdf.exe" 'http://chicago.craigslist.org/search/chc/sss?sort=date"&"postedToday=1"&"query=cb2"&"hasPic=1#grid' "C:\Users\USER\Downloads\test5.pdf"
Loading pages (1/6)
Counting pages (2/6)
Resolving links (4/6)
Loading headers and footers (5/6)
Printing pages (6/6)
Done

The output is below but I should see the gallery instead, see second screenshot.

Also, I notice all the links in the PDF point to my machine... is there a way to keep the links to the internet? I checked the switches and couldn't find anything. See third screenshot. 
https://groups.google.com/group/wkhtmltopdf-general/attach/ec789646ffb9bb12/1.png?part=0.3&authuser=0&view=
![1](https://cloud.githubusercontent.com/assets/12676920/7899336/02b67c70-06e5-11e5-8526-e20f98991a9a.png)
![2](https://cloud.githubusercontent.com/assets/12676920/7899337/02c087d8-06e5-11e5-926c-d3fa8bb0a665.png)
![3](https://cloud.githubusercontent.com/assets/12676920/7899338/02cffd26-06e5-11e5-8a28-398582be77ac.png)

1

**Comment by ashkulz** [comment]
For the second point, see #1843 which has already been fixed. For the first part, use
```
wkhtmltopdf "http://chicago.craigslist.org/search/chc/sss?sort=date&postedToday=1&query=cb2&hasPic=1#grid" craigslist.pdf
```
i.e. it was a command-line quoting issue at your end, with the above command output looks like
![2391](https://cloud.githubusercontent.com/assets/854352/7906501/ebcff750-0849-11e5-8732-32ec145e69be.png)

**Comment by ashkulz** [comment]
A preview for the next release [`0.12.3-dev-79ff51e`](http://wkhtmltopdf.org/downloads.html#testing) is available, which should contain the fix for this issue. Please report back if it is not solved with the above version.

*Please note that the above downloads will be removed after the `0.12.3` release*.
