### ISSUE TITLE
mix-blend-mode support?

### ISSUE THREAD

**Issue by mloenow** [wkhtmltopdf/wkhtmltopdf#2392]
Hi,

I've been trying to get `mix-blend-mode` and `background-blend-mode` (and their `-webkit-*` equivalents) to work, but without success. Is this currently supported?

Setup: wkhtmltoimage v0.12.2.1 (with patched qt) on OS X 10.10.3.

Thanks

**Comment by ashkulz** [comment]
wkhtmltopdf currently uses a very old version of WebKit (roughly equivalent to Chrome 13), so you'll have to try the 0.13 alpha builds which have an updated rendering engine (unfortunately there isn't one for OS X as yet).

**Comment by mloenow** [comment]
Is there an issue here (or some place else) where I can subscribe to any updates made to the OS X build script support? :)

**Comment by ashkulz** [comment]
Not really, but I'd announce new snapshots on the mailing list or twitter. I don't have a Mac, so cannot really develop for it :frowning:

**Comment by mloenow** [comment]
Ok. I wish I could help out, but I have no idea where to start :confused:

Although not ideal, I did find this provider online: https://www.macincloud.com/pricing/all-plans. It includes a 24h trial for $0.99, weekly charges from $12 to $19, which I wouldn't mind donating (1 week) if you're interested. However, I guess you need admin/root access (e.g. for dependencies)? That requires a dedicated plan, which is more expensive, unfortunately.
