### ISSUE TITLE
don't change cwd

### ISSUE THREAD

**Issue by mozeq** [wkhtmltopdf/wkhtmltopdf#2393]
wkhtmltopdf changes CWD to the directory with the source html file. This fails in case when you want to pass the html through pipe (it changes CWD to /tmp) or when you simply have the source html in different directory then the static files. In my case the static files are on read-only storage, so I generate the html in memory, pass it to the whtmltopdf and set the CWD of the process to the directory with the static files. wk changes CWD to /tmp and fails to find the files.

**Comment by ashkulz** [comment]
Can you post an example script which can reproduce this?

**Comment by mozeq** [comment]
My observation was wrong, it doesn't change the CWD, it just looks for the static files in the same directory where is the source html, which doesn't work when your piping the input (it tries to find the static files in /tmp). Would it be possible to add an option to specify the root of the relative paths for static files?

I can reproduce it running this:
```
cd ~/bin/apache-tomcat-8.0.18/webapps/ROOT/WEB-INF/classes/templates/report
cat ~/sandbox/Mrkvickova_Jozefina.html | wkhtmltopdf - output.pdf
loaded the Generic plugin 
Loading page (1/2)
Warning: Failed to load file:///tmp/css/styl.css (ignore)         
Warning: Failed to load file:///tmp/design/logo.png (ignore)
Printing pages (2/2)                                               
Done                                            
```

the static files are in ~/bin/apache-tomcat-8.0.18/webapps/ROOT/WEB-INF/classes/templates/report/{css,design}

**Comment by ashkulz** [comment]
Try using the BASE tag.

**Comment by mozeq** [comment]
Works flawlesly, thx!

**Comment by ChrisK2** [comment]
I'm running into the same issue and using the <base> tag is a quite ugly workaround, as it requires the HTML document to "know" the absolute location of other files that could just be linked relatively. It'd prefer if wkhtmlto* just stays in the cwd of the shell, at least when reading from STDIN.
