### ISSUE TITLE
--read-args-from-stdin and server mode ?

### ISSUE THREAD

**Issue by matrixise** [wkhtmltopdf/wkhtmltopdf#2394]
I would like to use wkhtmltopdf in a server mode, is it possible ?

I think yes, but not sure, because we can use --read-args-from-stdin
```
--read-args-from-stdin          Read command line arguments from stdin
```
Normally, we can send the html content to STDIN via ```wkhtmltopdf - -```
The process will read from STDIN and will generate the output on STDOUT.

But can we mix it with --read-args-from-stdin ?
```
cat demo.html | wkhtmltopdf --read-args-from-stdin - - > demo.pdf
```
?

Thanks

**Comment by ashkulz** [comment]
Nope, because there is only one `stdin`. You might try named pipes, but YMMV.
