### ISSUE TITLE
Segmentation fault on Red Hat 4.4.6-3

### ISSUE THREAD

**Issue by pierrowang** [wkhtmltopdf/wkhtmltopdf#2397]
stack info:

Core was generated by `./wkhtmltopdf ./index.html test.jpg'.
Program terminated with signal 11, Segmentation fault.
#0  0x00007f69e84f77ab in init_one_static_tls (map=0x2c6ae50) at allocatestack.c:1179
1179      dtv[map->l_tls_modid].pointer.val = dest;
Missing separate debuginfos, use: debuginfo-install wkhtmltox-0.12.2.1-1.x86_64
(gdb) bt
#0  0x00007f69e84f77ab in init_one_static_tls (map=0x2c6ae50) at allocatestack.c:1179
#1  __pthread_init_static_tls (map=0x2c6ae50) at allocatestack.c:1196
#2  0x00007f69e9dcfd60 in _dl_scope_free () from /lib64/ld-linux-x86-64.so.2
#3  0x00007f69e9dcb071 in _dl_map_object_deps () from /lib64/ld-linux-x86-64.so.2
#4  0x00007f69e9dd0b62 in dl_open_worker () from /lib64/ld-linux-x86-64.so.2
#5  0x00007f69e9dcc266 in _dl_catch_error () from /lib64/ld-linux-x86-64.so.2
#6  0x00007f69e9dd05aa in _dl_open () from /lib64/ld-linux-x86-64.so.2
#7  0x00007f69e8929f66 in dlopen_doit (a=0x7f69a398d520) at dlopen.c:67
#8  0x00007f69e9dcc266 in _dl_catch_error () from /lib64/ld-linux-x86-64.so.2
#9  0x00007f69e892a2dc in _dlerror_run (operate=0x7f69e8929f00 <dlopen_doit>, args=0x7f69a398d520)

**Comment by ashkulz** [comment]
Looks like you used another binary hoping it will run on RHEL 4.x -- please upgrade your distribution to something more modern. If you want to make it run there, you'll have to compile it yourself.
