### ISSUE TITLE
adding --footer-html results in incorrect 2nd page margin-top

### ISSUE THREAD

**Issue by NicoJuicy** [wkhtmltopdf/wkhtmltopdf#2398]
I have uploaded 2 html files
- content
- footer

The javascript file ( i removed splitTable code) and the generated pdf to https://drive.google.com/open?id=0B_b8p-_V2xV1fjZtRGxpd240clc3ZHRkNkR3dmpwT1lId3RnUkwxNUZzOWVGOE00UTZQWEk&authuser=2

The problem is, that on the second page, the table hasn't got a margin-top... The problem only arrises when i add the footer.

This is the command to generate the pdf:

wkhtmltopdf.exe 190.html --footer-html 190-footer.html 190.pdf

I'm using 0.12.2.1 (updated the binary) and have been messing with "correct displaying invoices" for the last year or so --> never got it fully working in all circumstances.

This is a screenshot of the problem, the black color is to indicate a new page. The repeated table is obviously on top of the page.

![screenshot-wkhtmltopdf](https://cloud.githubusercontent.com/assets/445937/7955429/8fdc14de-09d8-11e5-9ca7-bd88427b4c8e.png)

Is there anyone who can help me fix the problem ( eg. displaying the footer without the 2nd page margin-top problem)

**Comment by GitteHubert** [comment]
Did you set explicite page margins via command line (e.g. -T 30 - B 20)?
If you didn't - try that first.

**Comment by ghprod** [comment]
using margin top and bottom fix this issue ..

Thanks :+1:
