### ISSUE TITLE
option to skip background graphics as in chrome browser

### ISSUE THREAD

**Issue by evildav** [wkhtmltopdf/wkhtmltopdf#2399]
Hi, 

Is there a way I could get pdfs using --print-media-type but without including the background colors as in chrome > printing console(you might see it under the options heading at the left pane)? Would be great to print things in B/W printers w/o the annoying greyscale images if there is such an option  

Thanks!

**Comment by ashkulz** [comment]
Maybe the `--no-background` option will help you out here?

**Comment by evildav** [comment]
Yea it worked. Thanks!
