### ISSUE TITLE
wkhtmltopdf exited with non-zero code 1. error:

### ISSUE THREAD

**Issue by snomula12** [wkhtmltopdf/wkhtmltopdf#2401]
I tried to use wkhtmltopdf and it worked on my local when i try to test this on a secure site it gives me this error wkhtmltopdf exited with non-zero code 1. error: 

The exit_code is 1 but stderr.decode("utf-8") is empty, with this being empty its tough to debug. I have Python 2.6.5 running on the AWS ubuntu server.
 
THis is my script i am running
options = {
        'page-size': 'A4',
        'margin-top': '0.50in',
        'margin-right': '0.50in',
        'margin-bottom': '0.50in',
        'margin-left': '1.25in',
        'orientation':'Landscape',
        'encoding': "UTF-8",
    }
 url = "https://securetest.eduplanet21.com/reports/dashboard/print/certificate/506/12332/"
 pdfkit.from_url(url, "Eduplanet21-Certificate.pdf", options=options)

Any Help would be really appreciated.

Thanks

**Comment by ashkulz** [comment]
Please open a issue in PDFKit, unless you can reproduce it on the command-line.
