### ISSUE TITLE
Japanese encoding produces garbage characters every other run

### ISSUE THREAD

**Issue by bcldemjen** [wkhtmltopdf/wkhtmltopdf#2402]
Converting the following URL causes the Japanese text to come out as garbage every second time:
wkhtmltopdf.exe "https://www.tripforyou.net/t4u/Auth.do?id=36hvEBZTGKIQlyGaqGI7GJIS5bHFpyXu" c:\temp\output.pdf
(Note: I got permission to include that URL here)
If you keep executing this command over and over, every second output is incorrect, meaning the Shift_JIS characters come out as WinAnsi:
bad: "Š”Ž®‰ïŽÐ @ƒGƒX EƒeƒB [ Eƒ [ƒ‹ƒh"
good: "株式会社　エス・ティー・ワールド"
Chrome, Safari, Internet Explorer etc. don't have this issue.

Reproduced with the following builds on Windows 7 and 8.1 64-bit:
wkhtmltox-0.12.2.2_mingw-w64-cross-win64.exe
wkhtmltox-0.12.2.2_msvc2013-win64.exe
wkhtmltox-0.13.0-alpha-7b36694_mingw-w64-cross-win64.exe

The issue cannot be reproduced with this build:
wkhtmltox-0.13.0-alpha-7b36694_msvc2013-win64.exe

**Comment by alkatank** [comment]
Were you able to solve this issue?

**Comment by bcldemjen** [comment]
No, it's still not working with the latest Windows build (Stable or Bleeding Edge, 64-bit or 32-bit, MSVC or MinGW). This is a major bug, because Japanese websites cannot be converted via wkhtmltopdf.

**Comment by bcldemjen** [comment]
Thanks @PhilterPaper. The following workaround seems to fix the issue:
`wkhtmltopdf.exe --encoding shift_jis "https://www.tripforyou.net/t4u/Auth.do?id=36hvEBZTGKIQlyGaqGI7GJIS5bHFpyXu" c:\temp\output.pdf`
