### ISSUE TITLE
Blank PDF after converting

### ISSUE THREAD

**Issue by phanmn** [wkhtmltopdf/wkhtmltopdf#2403]
Hi!
- I try to convert this HTML file at local, but the result is blank. (https://86c5dba97f6a810940242015176358b18e9e7a8b.googledrive.com/host/0B2sn4vO_u90RfjhlZUVHWlJpVzVxZnB0UkJmek5GT2VOT1JmVTFNNTBrYzRpX25Xd3hKclU/)
- I'm using 0.12.2.2 version on Windows 8.1 64 bit.
- I think that wkhtmltopdf cannot wait for CSS to load completely.

Thanks!

**Comment by verma-neeraj-in** [comment]
The request should return text/html mime type to generate PDF. As with your link its not.

**Comment by phanmn** [comment]
Thanks for your response, Verma!

- Please use: https://86c5dba97f6a810940242015176358b18e9e7a8b.googledrive.com/host/0B2sn4vO_u90RfjhlZUVHWlJpVzVxZnB0UkJmek5GT2VOT1JmVTFNNTBrYzRpX25Xd3hKclU/
- I tried --javascript-delay but no hope :(

**Comment by Tomsgu** [comment]
Closing as examples are not available and there is no other information in this issue.
