### ISSUE TITLE
Links containing images doesn't generate properly

### ISSUE THREAD

**Issue by SzaboAdamImre** [wkhtmltopdf/wkhtmltopdf#2404]
Hello!

I have the following HTML:

``` html
<!DOCTYPE html>
<html>
<body >
            <a href="http://localhost:9000//">Localhost</a><br/>
            <a href="http://www.google.com">Google</a><br/>
            <a href="http://www.google.com">
                     <img src="https://www.google.hu/images/srpr/logo11w.png"/>
            </a><br/>
</body>
</html>
```

And I want to generate it to pdf with the following command:
wkhtmltopdf file:///tmp/tmp.html tmp.pdf

The generated PDF has the links for the two textual links, but on the image, only the bottom part is clickable.

Is there some way to make the entire image clickable?

WkHtmlToPdf Version: 0.12.2.1
OS: Ubuntu 14.04

Thx

**Comment by rosantoz** [comment]
Interesting.

I'm having the exactly same problem.

**Comment by rosantoz** [comment]
SzaboAdamImre,

I solved this problem with css:

```
a {
    display: block;
}
```

I hope it helps.

**Comment by matthiaz** [comment]
@rosantoz thanks for sharing.
That workaround works for me.

**Comment by stuarteske** [comment]
@rosantoz thanks for the info.
Working.

**Comment by sofrom** [comment]
@rosantoz thanks for the info.
It works well.

**Comment by ashkulz** [comment]
Can someone verify it works properly with the 0.13 builds?

**Comment by el-timm** [comment]
I am still having this issue on 0.12.4.  Using the following markup, only the bottom portion of the images are linked in the PDF.  The ```display:block``` trick won't work here, because I don't want the images to incur a newline between them.

```html
<a href="https://farm4.staticflickr.com/3748/9783751846_11ac9076a7.jpg"><img src="https://farm4.staticflickr.com/3748/9783751846_11ac9076a7_t.jpg" alt=""></a>
<a href="https://farm4.staticflickr.com/3727/9783750986_47c199bc46.jpg"><img src="https://farm4.staticflickr.com/3727/9783750986_47c199bc46_t.jpg" alt=""></a>
<a href="https://farm4.staticflickr.com/3731/9783742834_a1156a9f8a.jpg"><img src="https://farm4.staticflickr.com/3731/9783742834_a1156a9f8a_t.jpg" alt=""></a>
<a href="https://farm3.staticflickr.com/2816/9640881938_91177c7cb5.jpg"><img src="https://farm3.staticflickr.com/2816/9640881938_91177c7cb5_t.jpg" alt=""></a>
```

**Comment by farkasmate** [comment]
Thanks @rosantoz for the workaround

@el-timm try `display: inline-block;` it works for me

**Comment by titame** [comment]
Thanks for sharing workaround @rosantoz . It's working for me.

**Comment by Tomsgu** [comment]
Closing this in expense of #2276.

**Comment by GangaprasadK** [comment]
Thanks a lot mate
