### ISSUE TITLE
Odd Issue on Windows Server/PHP Rendering Backbone app

### ISSUE THREAD

**Issue by Iceman52489** [wkhtmltopdf/wkhtmltopdf#2407]
So the issue ONLY occurs when I run the command through PHP. If I run it through command line on the same machine, it downloads all the resources that RequireJS throws at it depending on the javascript-delay setting. When outputting the log in PHP, it stops no matter what (I've tried increasing the delay, going through cmd.exe AND powershell.exe) at two javascript files (There's roughly 5 more small javascript files afterwards). I've confirmed it's a problem with passing these two initial javascript loads using a combination of increased delay and window-status.

So where it works is:

Windows 8.1 (My local development environment) both through PHP and manual input through cmd.

Windows Server 2012R2 (AWS development server) through cmd. It just doesn't work through any of PHP's exec/system/proc_open functions.

Any ideas?

**Comment by Iceman52489** [comment]
Also have tried the latest 32-bit and 64-bit builds

**Comment by ashkulz** [comment]
Looks like a problem with the PHP integration, can't help you out if it works from the command-line :frowning:
