### ISSUE TITLE
wkhtmltoimage can't calculate page height and crashes

### ISSUE THREAD

**Issue by magp** [wkhtmltopdf/wkhtmltopdf#2408]
Hi all,

I am running wkhtmltoimage 0.12.2.1 (with patched qt) on bash 4.3.33 on a Mac OSX 10.9.5 for the following page:

http://imasdemase.com/en/programacion-2/tablas-cruzadas-en-postgresql-pivotmytable/

Though I can achieve expected behaviour with the options _--disable-smart-width --height 4000 -n_ my idea is to execute the command within a bash script to run through different pages. 

Getting wkhtmltoimage's "determine page height" functionality to work would be ideal as having to manually guess and introduce the page height per page is not an option.

From my trials to find a solution (detailed below) I suspect that this is an issue with the javascript from the [crayon syntax highlighter wordpress plugin](https://wordpress.org/plugins/crayon-syntax-highlighter/developers/), but I could be entirely wrong as I am no programmer.

Here is the run through of what I've done. 

**a. Running the plain command results in a crash.**

```
wkhtmltoimage http://imasdemase.com/en/programacion-2/tablas-cruzadas-en-postgresql-pivotmytable/ ~/Desktop/test.png
```

Output:

```
Loading page (1/2)
QFont::setPixelSize: Pixel size <= 0 (0)                     ] 48%

... (Extremely long output)

QPainter::save: Painter not active
QPainter::setClipRect: Painter not active
QPainter::restore: Unbalanced save/restore
QPainter::save: Painter not active
QPainter::setClipRect: Painter not active
QPainter::restore: Unbalanced save/restore
QPainter::brush: Painter not active
QPainter::setBrush: Painter not active
QPainter::setRenderHint: Painter must be active to set rendering hints
Segmentation fault: 11
```

Result: Creates a file with no content.

**b. Disabling javascript by adding the -n doesn't change output**

```
wkhtmltoimage -n http://imasdemase.com/en/programacion-2/tablas-cruzadas-en-postgresql-pivotmytable/
```

Same output and result as above.

**c. Set height to 4000 actually creates a very wide image**

```
wkhtmltoimage --height 4000 http://imasdemase.com/en/programacion-2/tablas-cruzadas-en-postgresql-pivotmytable/ ~/Desktop/test.png
```

Output:

```
Loading page (1/2)
QFont::setPixelSize: Pixel size <= 0 (0)                     ] 49%
QFont::setPixelSize: Pixel size <= 0 (0)
QFont::setPixelSize: Pixel size <= 0 (0)                     ] 53%
QFont::setPixelSize: Pixel size <= 0 (0)                     ] 59%
QFont::setPixelSize: Pixel size <= 0 (0)==============>      ] 89%
QFont::setPixelSize: Pixel size <= 0 (0)==============>      ] 89%
QFont::setPixelSize: Pixel size <= 0 (0)===============>     ] 90%
Rendering (2/2)
QFont::setPixelSize: Pixel size <= 0 (0)                     ] 25%
Done
```

Result: Creates extremely wide, low quality, image. Not sure what the image contains as quality of content is low due to size.

**d. Disable smart width and set height results in a nearly ok image, but content is cut**

```
wkhtmltoimage --disable-smart-width --height 4000 http://imasdemase.com/en/programacion-2/tablas-cruzadas-en-postgresql-pivotmytable/ ~/Desktop/test.png
```

Output:

```
Loading page (1/2)
QFont::setPixelSize: Pixel size <= 0 (0)                     ] 48%
QFont::setPixelSize: Pixel size <= 0 (0)
QFont::setPixelSize: Pixel size <= 0 (0)                     ] 48%
QFont::setPixelSize: Pixel size <= 0 (0)=============>       ] 87%
QFont::setPixelSize: Pixel size <= 0 (0)===============>     ] 90%
QFont::setPixelSize: Pixel size <= 0 (0)===============>     ] 90%
QFont::setPixelSize: Pixel size <= 0 (0)
QFont::setPixelSize: Pixel size <= 0 (0)
Rendering (2/2)
QFont::setPixelSize: Pixel size <= 0 (0)                     ] 25%
Done
```

Result: Image of 4000 pixels height with the last shown element being extended to the end of the image, effectively cutting out the last part of content. Looking into what the nature of the element led me to a block of code rendered by the "[crayon syntax highlighter wordpress plugin](https://wordpress.org/plugins/crayon-syntax-highlighter/developers/)". This led me to believe that there was some part of their code that was messing with wkhtmltoimage height calculations. 

**e. Disable smart width, javascript and set height works wonders**

```
wkhtmltoimage --disable-smart-width --height 4000 -n http://imasdemase.com/en/programacion-2/tablas-cruzadas-en-postgresql-pivotmytable/ ~/Desktop/test.png
```

Output:

```
Loading page (1/2)
QFont::setPixelSize: Pixel size <= 0 (0)                     ] 43%
QFont::setPixelSize: Pixel size <= 0 (0)
QFont::setPixelSize: Pixel size <= 0 (0)=============>       ] 87%
Rendering (2/2)
QFont::setPixelSize: Pixel size <= 0 (0)                     ] 25%
Done
```

Result: The resulting file is what I was expecting from the command in "a." So this led me to believe that if I removed the height option and left the other two it might still work.

**f. Disable smart width, javascript crashes like in "a."**

```
wkhtmltoimage --disable-smart-width -n http://imasdemase.com/en/programacion-2/tablas-cruzadas-en-postgresql-pivotmytable/ ~/Desktop/test.pngLoading page (1/2)
```

Output:

```
QFont::setPixelSize: Pixel size <= 0 (0)                     ] 43

... (Extremely long output)

QPainter::setClipRect: Painter not active
QPainter::restore: Unbalanced save/restore
QPainter::save: Painter not active
QPainter::setClipRect: Painter not active
QPainter::restore: Unbalanced save/restore
QPainter::brush: Painter not active
QPainter::setBrush: Painter not active
QPainter::setRenderHint: Painter must be active to set rendering hints
Segmentation fault: 11
```

Result: Creates a file with no content. Back to square 1 ("a.").

---

**Conclusion:** 
The only command that results in expected behaviour is "e.". However, this requires the user to guess and specify a height. For use in a script where some of the pages might have similar elements, inputing heights is not viable. 

However, I do understand that wkhtmltox can't work with _all_ the webpages on the web and their related kinks but hopefully we can all help to make the tool more robust.

Let me end by expressing my gratitude to the creators of wkhtmltox for an awesome command line tool. I use it extensively and really find it very useful.

Thanks in advance for your time and help and do excuse any logical errors I may have committed due to my inexperience. 

Don't hesitate to ask for any further information you may require.

Best,

Michael

PS: In earlier stages of testing I could get wkhtmltoimage to hang but I can't reproduce at time of writing.

EDIT: Corrected... The only command that results in expected behaviour is "f.".-> The only command that results in expected behaviour is "e.".

**Comment by alloylab** [comment]
is this still an issue on 0.12.5?
