### ISSUE TITLE
Non English characters

### ISSUE THREAD

**Issue by jspinsanti** [wkhtmltopdf/wkhtmltopdf#2411]
**Environment**

**wkhtmltopdf version**
```
wkhtmltopdf 0.12.2.1 (with patched qt)
```
**OS**
```
Description: Ubuntu 12.04.5 LTS
Release: 12.04
```

**Description**
If the html file doesn't include the charset, the transformation generates wrong characters.

**Steps to reproduce**
Wrong transformation
```
wkhtmltopdf latin-no-meta.html latin-no-meta.pdf
```
Good transformation
```
wkhtmltopdf latin.html latin.pdf
```
**Question**
Is it possible to use a parameter invocation to force the charset?
Example:
```
wkhtmltopdf --charset=UTF-8 source.html target.html
```

**Files**
![latin-html png](https://cloud.githubusercontent.com/assets/12845908/8108382/6249a096-1026-11e5-8132-d46bc2a60682.png)
![latin-nometa-html png](https://cloud.githubusercontent.com/assets/12845908/8108381/624883fa-1026-11e5-9c1e-87a86ccf8e12.png)

**Comment by jspinsanti** [comment]
I found --encoding parameter to fix the problem.

**Comment by ihippik** [comment]
**wkhtmltopdf 0.12.2.4**

i use plain cyrillic text without "meta charset" , but  "--encoding utf8" in params.
text is not displayed correctly

in wkhtmltopdf 0.9.. work fine.
why is that?
