### ISSUE TITLE
Footers and Headers are not transparent, while body is.

### ISSUE THREAD

**Issue by Maxyme** [wkhtmltopdf/wkhtmltopdf#2416]
This issue appears when applying a pdf as background to a wkhtmltopdf generated pdf. It seems transparency is applied to the body, but not to the footer and headers.

This was tested with 0.12.2.2. The background was applied using PdftkServer.

![errorfooter](https://cloud.githubusercontent.com/assets/8309513/8204464/18717940-14e9-11e5-9242-391da97485af.png)

**Comment by ashkulz** [comment]
Can you post the sample HTML/image so that I can verify the fix?

**Comment by Maxyme** [comment]
Included are the html files that make the testFooter.pdf with wkhtmltopdf, using the following command:wkhtmltopdf.exe --footer-html footer.html body.html testFooter.pdf.

Also included is the background.pdf used with pdftk server and the following command:
pdftk.exe testFooter.pdf background ColorBackground.pdf output finalPdf.pdf.

Finally, the final document with non-transparent footer is included

All the files are here:
https://www.dropbox.com/sh/1ivfts2vya6z1sh/AABaI0kvnUIfyWHaX-OlVWjGa?dl=0

**Comment by Qronicle** [comment]
Just letting you guys know I have the same issue on a Ubuntu server (wkhtml version 0.12.2.1). 
(Was adding backgrounds with pdflib, didn't know about the tool Maxyme uses, will definitely try it out)

**Comment by jspath** [comment]
Is there any update on this issue?  We're currently experiencing it in 0.12.3.

We are going to try building 0.12.4-dev

**Comment by ashkulz** [comment]
Nope, it's not yet fixed.

**Comment by ashkulz** [comment]
I have a fix, but unfortunately the dropbox folder created by @Maxyme seems to be empty. Does anyone have a sample I can verify before committing the fix?

**Comment by ashkulz** [comment]
Used the testcase posted in #2084 to verify the fix.

**Comment by buffcode** [comment]
Is there any kind of HTML/CSS/command-line workaround / hotfix for the time being? As 0.12.4 is unreleased.

**Comment by ashkulz** [comment]
@buffcode: you can build it yourself, it would be stable for regular usage. I'm planning on releasing `0.12.4` within a month or two.

**Comment by jspath** [comment]
@buffcode I built the header/footer page as a standalone page.  I then used Perl's PDF::API2 to combine the header page and the content page.

I also used PDF::API2 for per page background colors and images.

**Comment by Formalizer** [comment]
@ashkulz as per your recommendation, I'm now trying to build it, but got this when Setting Up the Build Environment (on Debian 8 Jessie) like this:

> sudo scripts/build.py setup-schroot-jessie
.....
W: Failed to fetch http://ppa.launchpad.net/pov/wkhtmltopdf/ubuntu/dists/lucid/main/binary-amd64/Packages  404  Not Found
W: Failed to fetch http://winswitch.org/dists/VERSION/main/binary-amd64/Packages  404  Not Found
.....

Any recommendations?

**Comment by ashkulz** [comment]
[`0.12.4`](http://wkhtmltopdf.org/downloads.html#stable) has been released, which should contain the fix for this issue. Please report back if it is not solved with the above version.

**Comment by ktrzos** [comment]
This problem still occurs on v0.12.4. Does any tag from header should have any CSS styles related to `background-color: transparent;`?

My header HTML code:

```
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8"/>
    </head>
    <body style="overflow:hidden;margin:0;padding:0 0 0 10mm;">
        <img
            src="/images/logo.png"
            style="width: 250px; height: auto; float: left; margin-top: 20px;"
        />
    </body>
</html>
```
