### ISSUE TITLE
Segfault when javascript enabled

### ISSUE THREAD

**Issue by triomen** [wkhtmltopdf/wkhtmltopdf#2420]
Hi,

Wkhtmltopdf seems to have a problem when I activate javascript. It returns 11 and the following error in "message" log :
> wkhtmltopdf[25372]: segfault at bbadbeef ip 00000000004dce69 sp 00007fffc8cdde50 error 6 in 
> wkhtmltopdf[400000+2093000]

**The environment is :**
* CentOs 6.5
* wkhtmltopdf 0.12.2.1 (with patched qt)
* PHP 5.4.16, Apache 2.0

**Here is my test script :**
```php
<?php
system("/usr/local/bin/wkhtmltopdf http://www.google.com google.pdf ", $a);
var_dump($a); 
```
prints
> string(0) "" int(11)

plus, in "messages" logs the following error : 
> wkhtmltopdf[25372]: segfault at bbadbeef ip 00000000004dce69 sp 00007fffc8cdde50 error 6 in 
> wkhtmltopdf[400000+2093000]

If I redirect the error to a file : 
```php
system("/usr/local/bin/wkhtmltopdf http://www.google.com google.pdf 2 > error.log", $a);
```

The error in error.log is : 
> Loading pages (1/6)
>                 ] 10%

If I execute the command line directly from the shell : 
> /usr/local/bin/wkhtmltopdf http://www.google.com google.pdf

The PDF generated is ok. 

If I change my script to (note the _disable-javascript_ option) : 
```php
<?php
system("/usr/local/bin/wkhtmltopdf --disable-javascript http://www.google.com google.pdf ", $a);
var_dump($a); 
```

It works well (pdf ok and prints "0" )
So the problem should be specific to Apache & javascript enabled wkhtmltopdf. 

Any advice ?

**Comment by ashkulz** [comment]
If it works from the command-line, then I can't help you why it doesn't work from under Apache.
