### ISSUE TITLE
Table "tbody" content is superimposed in "thead"

### ISSUE THREAD

**Issue by yobrx** [wkhtmltopdf/wkhtmltopdf#2423]
Hi,

In 0.12.2.1 version of wkhtmltopdf, tbody is superimposed with thead on a continuous table of a next page.
![image](https://cloud.githubusercontent.com/assets/292402/8254125/249623a2-1696-11e5-93fc-cfa3b553df69.png)

The bug does not occur with an older version (0.12.1) of wkhtmltopdf

**Comment by ashkulz** [comment]
see the workaround mentioned in #1524 i.e. use the CSS `thead { display: table-row-group }`
