### ISSUE TITLE
Strange encoding issue

### ISSUE THREAD

**Issue by cmodijk** [wkhtmltopdf/wkhtmltopdf#2426]
I'm using https://github.com/KnpLabs/snappy/issues/162 to generate my PDF's an since there last version. If i execute the commands on the shell it works fine but it looks like a environment issue. I'm hoping any one could help me solve this. 
 
![Strange encoding](https://cloud.githubusercontent.com/assets/771041/8210950/c9c7667a-1514-11e5-9391-cb537722840d.png)

![Normale encoding](https://cloud.githubusercontent.com/assets/771041/8210951/c9c7f6ee-1514-11e5-8e17-0c52fdad9f53.png)

**Comment by ashkulz** [comment]
If it works from the command-line, I can't really help you ... please reopen if it is reproducible on the command-line.

**Comment by rpestana** [comment]
Hi!
I had the same problem.
Do this on you server (if it is a CentOS): yum install urw-fonts

**Comment by cmodijk** [comment]
Tnx @rpestana it's fixed!
