### ISSUE TITLE
OutputStream bugged

### ISSUE THREAD

**Issue by andytlim** [wkhtmltopdf/wkhtmltopdf#2428]
Hi,

OS: Windows 7 64-bit
Version: 12.2.2 (with patched qt)

When I do the command 

wkhtmltopdf [htmlFilePath] [pdfFilePath]

I get a perfect pdf. If I use this command to get the binary data on stdout:

wkhtmltopdf [htmlFilePath] "-" 

I get corrupted binary data when I copy and paste it into a file.

Is there some type of encoding I have to consider when reading the stdout?

If anyone has an example of doing it in Java, that would be superb as well.

**Comment by andytlim** [comment]
Also, is there a way to remove the info messages that get written to stdout as well? I always have to remove the "Loading pages (1/6)..." text

**Comment by ashkulz** [comment]
@andytlim: redirect it to a file instead of copy-pasting it, should work OK. Use a java wrapper instead of trying to write your own.

**Comment by andytlim** [comment]
Issue was resolved. I ended up fixing my own java code to get the output I wanted.
