### ISSUE TITLE
QSslSocket: cannot resolve SSLv2_client_method while displaying images from amazon s3 server.

### ISSUE THREAD

**Issue by sansarp** [wkhtmltopdf/wkhtmltopdf#2431]
I am using gem 'wkhtmltopdf-binary-edge', '~> 0.12.2.1'  but pdf is not  displaying my https:// images from my amazon s3 server.  I get the correct image url 
in my console. The link is fine and has the image but is not rendered in the pdf.
The error says: QSslSocket: cannot resolve SSLv2_client_method.

**Comment by ashkulz** [comment]
Please report it to the owners of the `wkhtmtlopdf-binary-edge` gem, as this is a packaging issue (they have bundled a binary which doesn't work in your environment).

**Comment by sansarp** [comment]
Finally solved that error using this command. sudo apt-get install libssl0.9.8
But still I cannot see the images in the pdf.

**Comment by tuanmai** [comment]
@sansarp I got the same problem with you. I used `pdfkit (0.8.2) ` and `wkhtmltopdf-binary (0.9.9.3)` . I tried to add images from S3 to it have error `QSslSocket: cannot resolve SSLv2_client_method`.

**Comment by ashkulz** [comment]
Using such old versions of wkhtmltopdf (`0.9.9`) is not supported, please use the 0.12 series.
