### ISSUE TITLE
ppc64 compile error

### ISSUE THREAD

**Issue by jstdoit** [wkhtmltopdf/wkhtmltopdf#2433]
My project is using wkhtmltopdf in power pc 64 arch, but I cannot find any binary build for it, how can I build from source for it?

**Comment by jstdoit** [comment]
I run `build.py posix-local` it appears error with follows:
```
/usr/bin/ld: final link failed: Bad value
collect2: ld returned 1 exit status
```

**Comment by ashkulz** [comment]
You probably need to compile with `-fno-optimize-sibling-calls`.

**Comment by jstdoit** [comment]
@ashkulz  to execute as this: `build.py posix-local -fno-optimize-sibling-calls` ?

**Comment by jstdoit** [comment]
sorry，i changed file `qt/mkspecs/linux-g++-64/qmake.conf`, where I modify `-m64` to `-mminimal-toc -fno-optimize-sibling-calls -m64`, and compile , still get same errors.

**Comment by ashkulz** [comment]
Looks like a [binutils bug](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=47279), see [this patch](https://sourceware.org/ml/binutils/2011-01/msg00403.html) for the fix -- it should work on binutils >= 2.11 as per the information in the patch. According to [this message](http://lists.freebsd.org/pipermail/freebsd-ppc/2014-November/007296.html), `-mminimal-toc` should work. Try asking out on a ppc64 mailing list as I can't really help you out.

**Comment by ashkulz** [comment]
Do let me know if you are able to solve this, so I can update the installation instructions with a reference to your steps on solving it.

**Comment by jstdoit** [comment]
@ashkulz No problem. But, should I modify `qt/mkspecs/linux-g++-64/qmake.conf` or all anywhere? any suggestions？Thanks

**Comment by ashkulz** [comment]
I'd suggest a ppc64 mailing list/IRC channel, as I don't have a clue why it did not work for you. Did you do a clean build after you changed the mkspecs?

**Comment by jstdoit** [comment]
yeah, i run `build.py posix-local -clean`

**Comment by jstdoit** [comment]
@ashkulz I just set the env and compile succeed. as follows:
`CXXFLAGS=-mminimal-toc CFLAGS=-mminimal-toc ./scripts/build.py posix-local`

**Comment by ashkulz** [comment]
Was this after reverting the Qt changes?

**Comment by jstdoit** [comment]
yes, since many library occur the same error, so I set the system wide flags.

**Comment by jstdoit** [comment]
@ashkulz Wow! Error happens again! When I exec `wkhtmltopdf`, it appears error with `Segmentation fault`...

**Comment by ashkulz** [comment]
@jstdoit: so possibly it was not compiled properly, take it up on a mailing list related to ppc64?

**Comment by jstdoit** [comment]
@ashkulz I disabled javascript, and it works now!

**Comment by ashkulz** [comment]
You might want to recompile with `export WKHTMLTOX_QT_CONFIG=--disable-javascript-jit` set, as the JIT on ppc64 is likely to be buggy.

**Comment by jstdoit** [comment]
@ashkulz Thanks, I may recompile it later, cos it works fine for now.

**Comment by weehock** [comment]
Hi @jstdoit , 

I face the same problem with wkhtmltopdf. I deployed odoo on IBM Powerpc running RHEL 6 & 7. 

would you be able to share with me the steps of compiling wkhtmltopdf or share your static library?

**Comment by anant-sharma** [comment]
Hi @jstdoit 

Please share how you compiled for ppc.

Thanks

**Comment by andrewquach** [comment]
Hi @jstdoit . Please share how you compiled for ppc. Your help is much needed.

**Comment by jstdoit** [comment]
@anant-sharma @andrewquach Sorry to response so late. I didnot try to recompile, but just set `disable_javascript: true` when I render response.
