### ISSUE TITLE
have a TODO list 

### ISSUE THREAD

**Issue by shirishag75** [wkhtmltopdf/wkhtmltopdf#2434]
Hi there, 
Would be nice to have a TODO /Roadmap list, somethings that you would like to do. It's a wishlist bug.

**Comment by alloylab** [comment]
@shirishag75 I agree can you submit a pr?

**Comment by alloylab** [comment]
We are closing this out since we haven't heard from you. If you are still having this issue please feel free to re-open it. Thanks.
