### ISSUE TITLE
getting issue while converting html to pdf in oriya language

### ISSUE THREAD

**Issue by jeeturocksin24** [wkhtmltopdf/wkhtmltopdf#2437]
my html contains english and oriya language ,but while converting the html o pdf i am getting the issue like in place of oriya character the black squre is comming.chould you please resove this issue 

![jitu](https://cloud.githubusercontent.com/assets/13134598/8453882/e08d53a0-2037-11e5-8a48-80e3e134c2aa.PNG)
![jitu1](https://cloud.githubusercontent.com/assets/13134598/8453881/e020954e-2037-11e5-8e05-ad3675e34adf.png)

**Comment by jeeturocksin24** [comment]
please check the html and the pdf created .

**Comment by ashkulz** [comment]
Where is the HTML? It looks like the necessary fonts are not installed/configured correctly.

**Comment by ashkulz** [comment]
Also, posting your aadhar ID in public is not really advisable.

**Comment by alok5290** [comment]
I hope that is dummy UID.
@ashkulz  : Is it related with Font installtion ?
I think,he has pasted the correct one also.

@jeeturocksin24 : Could you please explain about both the file ?

**Comment by Tomsgu** [comment]
Closing as the issue is missing the html and there is no feedback.
