### ISSUE TITLE
Blank/empty pages inside generated pdf file

### ISSUE THREAD

**Issue by tfaruk2** [wkhtmltopdf/wkhtmltopdf#2439]
Hi,

Input html files:

https://www.dropbox.com/s/4m31azqxp4yfaue/fp.html?dl=0
https://www.dropbox.com/s/0lfg1tbb2sbgmq2/main.html?dl=0

Output file:

https://www.dropbox.com/s/dvofmeyvabjcj9x/aaa.pdf?dl=0

Pdf file is generated like this:

"wkhtmltopdf" --footer-font-size 8 --footer-left 'Page [page] of [toPage]' --encoding 'utf-8' --orientation Landscape ~/fp.html toc ~/main.html ~/aaa.pdf

wkhtmltopdf 0.12.2.1 (with patched qt)

Page #7 is blank/empty.

Do you know how to avoid this ?

Thank you in advance for your responses

Best,
Lukasz

**Comment by alloylab** [comment]
is this still an issue on 0.12.5?
