### ISSUE TITLE
Multiple headers rendering issue

### ISSUE THREAD

**Issue by kpashka** [wkhtmltopdf/wkhtmltopdf#2441]
I have a necessity to render different headers - big one for first page and small ones for all other. I'm passing `--header-html header.html` parameter with contents of `header.html`:

```html
<!DOCTYPE html>
<html>
<head lang="en">
    <script>
        var mainHeader = "test<br>test<br>test<br>test<br>test<br>test<br>test<br>test<br>test<br>";
        var secondHeader = "test<br>";

        function selectHeader() {
            var vars = {};
            var x = document.location.search.substring(1).split('&');
            for(var i in x) {
                var z = x[i].split('=',2);
                vars[z[0]] = decodeURIComponent(z[1]);
            }

            if (vars["page"] > 1) {
                document.getElementById('main').innerHTML = secondHeader
            } else {
                document.getElementById('main').innerHTML = mainHeader
            }
        }
    </script>
</head>
<body onload="selectHeader()">
    <div id="header"></div>
</body>
</html>
```

In resulting PDF file, pages with second header have same size with main header - they're being prepended with some invisible spacing. Looks like, after first script execution, renderer saves first header height and pre-allocates it for every next page.

Is this possible to fix? I've tried to find some workarounds (e.g. hiding headers via css, instead of overwriting DOM node), but had no luck with it.

**Comment by ashkulz** [comment]
That isn't really possible. What happens is that the maximum header height is calculated and used (unless you specify an explicit `margin`). This is then used as the page margins for the `QPrinter` instance, and when rendering the page the headers/footers are directly rendered using graphics primitives (and not the WebKit rendering of the main document). You can't have different margins for each page, as that would change the layout (i.e. more content shown on page 2, changing this further on).

What can be done is render the document in two stages, page1 and the rest using two separate HTML files with different headers. Then the headers and page margins can be different, but you have to do the splitting at your end when generating the pages.

**Comment by korny** [comment]
> when rendering the page the headers/footers are directly rendered using graphics primitives (and not the WebKit rendering of the main document)

Can you elaborate on what "graphics primitives" is? Or point me to the right part of the documentation ;-) I'm trying to debug why my CSS is working differently well in headers versus page content, and couldn't find much about this except for your comment here.

**Comment by ashkulz** [comment]
@korny: can you check if your issue is reproducible with `0.12.3-dev`, if not post a test case?

**Comment by porebskk** [comment]
@ashkulz i just encountered the same problem with wkhtmltopdf using Windows 10 MSVC 2015 x64 when I tried to render a similar problem @pavel-kiselyov mentioned. How can I help with providing a test case?
