### ISSUE TITLE
Exit with code 1 due to network error: UnknownNetworkError

### ISSUE THREAD

**Issue by deniz1304** [wkhtmltopdf/wkhtmltopdf#2443]
Hi everybody,

My problem looks like very simple but I took it :(.
When I run the below code I take "Exit with code 1 due to network error: UnknownNetworkError" error, how could I solve this issue?
Thanks a lot.

Code: wkhtmltoimage --load-error-handling ignore http://www.google.com google.png
Note: The program installed below "C:\Program Files\wkhtmltopdf" directory and "C:\Program Files\wkhtmltopdf\bin" is added to path variable.

**Comment by vladnosferatu** [comment]
i have the same error .. any fix ?

**Comment by yehudahkay** [comment]
+1

**Comment by Tomsgu** [comment]
`wkhtmltoimage --load-error-handling ignore http://www.google.com google.png` works fine for me. This usually happens if the resource cannot be find. Try to also check if links are absolute links.
