### ISSUE TITLE
wkhtmltoimage  has something wrong with checked-Checkbox

### ISSUE THREAD

**Issue by yywng** [wkhtmltopdf/wkhtmltopdf#2446]
In windows.
for a checked checkbox ,wkhtmltopdf is OK. I can get a right pdf file(the checked checkbox is good). 
but, when I use wkhtmltoimage, I can not get right picture(the checked checkbox is wrong，the uncheck checkbox is good).
html tag like that:
   < input name="checkbox1"  checked="checked" type="checkbox" value="checkbox"   / >

the OPTIONS --checkbox-checked-svg is not work for   wkhtmltoimage. 
but it is work for  wkhtmltopdf .

help

**Comment by alloylab** [comment]
is this still an issue on 0.12.5?
