### ISSUE TITLE
Footer-html is requested with HTTP headers larger than 8k

### ISSUE THREAD

**Issue by fnicollet** [wkhtmltopdf/wkhtmltopdf#2449]
Hello and thanks for this very useful library! I have tried Flying Saucer and PhantomJS which were too limited for my needs and wkhtmltopdf gives great results

I have an issue with a document of about 90 pages with a cover, a toc and a footer. The issue is with the footer, which is a HTTP url.
Here is the command line I run:

> wkhtmltopdf --footer-html "http://localhost:9001/helpcenter/app/product/documentation_footer/539?format=pdf&lang=fr" --disable-smart-shrinking --margin-top 20mm --margin-bottom 15mm --margin-left 0 --margin-right 0 --cookie "PLAY_HELPCENTER_SESSION" "f600125d8151174e2aed22ffba3970cbb22f16a2-___ID=102750a2-9748-46c0-9797-516833ff4e70&username=admin&___AT=717844f6624eecb3db6b0ee2dbe2ec2f34dbe90d" cover "http://localhost:9001/helpcenter/app/product/documentation/539?format=pdf&lang=fr&cover_only=true" toc --xsl-style-sheet documentation_toc.xsl "http://localhost:9001/helpcenter/app/product/documentation/539?format=pdf&lang=fr" bug_report.pdf

which can be reduced in this case to:

> wkhtmltopdf --footer-html "http://localhost:9001/helpcenter/app/product/documentation_footer/539?format=pdf&lang=fr" --cookie "PLAY_HELPCENTER_SESSION" "f600125d8151174e2aed22ffba3970cbb22f16a2-___ID=102750a2-9748-46c0-9797-516833ff4e70&username=admin&___AT=717844f6624eecb3db6b0ee2dbe2ec2f34dbe90d" page "http://localhost:9001/helpcenter/app/product/documentation/539?format=pdf&lang=fr" bug_report.pdf

So I call a page with a session cookie, and I give it a html footer. When I run this, I get these errors:
```
D:\temp\testspdf>wkhtmltopdf --footer-html "http://localhost:9001/helpcenter/app
/product/documentation_footer/539?format=pdf&lang=fr" --cookie "PLAY_HELPCENTER_
SESSION" "f600125d8151174e2aed22ffba3970cbb22f16a2-___ID=102750a2-9748-46c0-9797
-516833ff4e70&username=admin&___AT=717844f6624eecb3db6b0ee2dbe2ec2f34dbe90d" pag
e "http://localhost:9001/helpcenter/app/product/documentation/539?format=pdf&lan
g=fr" bug_report.pdf
Loading pages (1/6)
Counting pages (2/6)
Resolving links (4/6)
Loading headers and footers (5/6)
Error: Failed loading page http://localhost:9001/helpcenter/app/product/document
ation_footer/539?format=pdf&lang=fr&page=52&section=Vue Applications&sitepage=52
&title=Business Geografic - Online Docs&subsection=Ressource Application&frompag
e=1&subsubsection=Editer une application&isodate=2015-07-08&topage=65&doctitle=B
usiness Geografic - Online Docs&sitepages=65&webpage=http://localhost:9001/helpc
enter/app/product/documentation/539?format=pdf&lang=fr&time=15:35:52&date=08/07/
2015 (sometimes it will work just to ignore this error with --load-error-handlin
g ignore)
Error: Failed loading page http://localhost:9001/helpcenter/app/product/document
ation_footer/539?format=pdf&lang=fr&page=49&section=Vue CartothÞque&sitepage=49&
title=Business Geografic - Online Docs&subsection=Publication de services&frompa
ge=1&subsubsection=Utiliser un service dans un logiciel SIG&isodate=2015-07-08&t
opage=65&doctitle=Business Geografic - Online Docs&sitepages=65&webpage=http://l
ocalhost:9001/helpcenter/app/product/documentation/539?format=pdf&lang=fr&time=1
5:35:52&date=08/07/2015 (sometimes it will work just to ignore this error with -
-load-error-handling ignore)
Error: Failed loading page http://localhost:9001/helpcenter/app/product/document
ation_footer/539?format=pdf&lang=fr&page=50&section=Vue Applications&sitepage=50
&title=Business Geografic - Online Docs&subsection=Ressource Application&frompag
e=1&subsubsection=Consulter une application&isodate=2015-07-08&topage=65&doctitl
e=Business Geografic - Online Docs&sitepages=65&webpage=http://localhost:9001/he
lpcenter/app/product/documentation/539?format=pdf&lang=fr&time=15:35:52&date=08/
07/2015 (sometimes it will work just to ignore this error with --load-error-hand
ling ignore)
```
There are more errors, basically, after page 47, the footers fail to load. On my server (a Play Framework application), I get dropped request because the HTTP request headers are larger than 8K

This is deep down in the framework so I didn't manage to see which headers was at fault here but there is something wrong here.

Is there a reason why at some point wkhtmltopdf would start requesting headers with big HTTP headers? The only header I think of is the session cookie but it shouldn't be repeated and is smaller than 8K

Thanks for your help,
Fabien

**Comment by fnicollet** [comment]
I have been digging further, it looks like wkhtmltopdf  *concatenates* the cookie header for each request, I end up with 

Cookie=PLAY_HELPCENTER_SESSION=f600125d8151174e2aed22ffba3970cbb22f16a2-___ID=102750a2-9748-46c0-9797-516833ff4e70&username=admin&___AT=717844f6624eecb3db6b0ee2dbe2ec2f34dbe90d; PLAY_HELPCENTER_SESSION=f600125d8151174e2aed22ffba3970cbb22f16a2-___ID=102750a2-9748-46c0-9797-516833ff4e70&username=admin&___AT=717844f6624eecb3db6b0ee2dbe2ec2f34dbe90d; PLAY_HELPCENTER_SESSION=f600125d8151174e2aed22ffba3970cbb22f16a2-___ID=102750a2-9748-46c0-9797-516833ff4e70&username=admin&___AT=717844f6624eecb3db6b0ee2dbe2ec2f34dbe90d; PLAY_HELPCENTER_SESSION=f600125d8151174e2aed22ffba3970cbb22f16a2-___ID=102750a2-9748-46c0-9797-516833ff4e70&username=admin&___AT=717844f6624eecb3db6b0ee2dbe2ec2f34dbe90d; PLAY_HELPCENTER_SESSION=f600125d8151174e2aed22ffba3970cbb22f16a2-___ID=102750a2-9748-46c0-9797-516833ff4e70&username=admin&___AT=717844f6624eecb3db6b0ee2dbe2ec2f34dbe90d; PLAY_HELPCENTER_SESSION=f600125d8151174e2aed22ffba3970cbb22f16a2-___ID=102750a2-9748-46c0-9797-516833ff4e70&username=admin&___AT=717844f6624eecb3db6b0ee2dbe2ec2f34dbe90d; PLAY_HELPCENTER_SESSION=f600125d8151174e2aed22ffba3970cbb22f16a2-___ID=102750a2-9748-46c0-9797-516833ff4e70&username=admin&___AT=717844f6624eecb3db6b0ee2dbe2ec2f34dbe90d

After just a few pages, so after 50, the cookie must be too big. 

It is because of the way I pass the parameters or is it a bug ?

Thanks

**Comment by fnicollet** [comment]
This seems to be a duplicated of #1870, didn't find it before, sorry

**Comment by fnicollet** [comment]
Using the workaround from the other thread works, if anyone has the same issue:
https://github.com/wkhtmltopdf/wkhtmltopdf/issues/1870#issuecomment-69510075

**Comment by ashkulz** [comment]
Marking as duplicate.
