### ISSUE TITLE
Deforming number "0" and other rounded letters in PDF

### ISSUE THREAD

**Issue by malekjaroslav** [wkhtmltopdf/wkhtmltopdf#2454]
I have an issue with certain fonts that are deformed in PDF viz. image. I can't find a way how to fix it.
![screen shot 2015-07-09 at 22 54 20](https://cloud.githubusercontent.com/assets/7753942/8606692/add05ae6-268d-11e5-9d51-58f6a3121726.png)

**Comment by JayBizzle** [comment]
Same as #2022

**Comment by Tomsgu** [comment]
Duplicate of #2022.
