### ISSUE TITLE
Cant compile new wkhtmltopdf.exe file

### ISSUE THREAD

**Issue by kristinlyt** [wkhtmltopdf/wkhtmltopdf#2455]
Hi, im having issues trying to build the codes to .exe in Windows. I have followed the documentation to install VisualStudio, Perl, Python etc and installed them into my PC. 
The error given when i attempt to run 'scripts/build.py msvc2013-win32' was :
- msvc2013 does not seem to be installed.

Will be great if anyone could advice on this. 
Thanks.

**Comment by ashkulz** [comment]
Well, it may not be installed properly ... on installation, a new environment variable `VS120COMNTOOLS` gets defined with the correct path. Reboot and try again (make sure you install 2013 and not any earlier version).
