### ISSUE TITLE
Images are not rendered with the URL that is being redirected from HTTP to HTTPS in PDF

### ISSUE THREAD

**Issue by swamypendli** [wkhtmltopdf/wkhtmltopdf#2456]
Hi Team,

We have been using the WkHTMLtoPDF binary(wkhtmltopdf-0.10.0-amd64) to convert the HTML file into PDF file from the past 2 years. Recently we found that some of the external images are not displayed in pdf, because these URLs are being redirected from "HTTP" to "HTTPS" protocols.

For Example:-
Original URL: http://example.com/test.png
Redirected URL: https://example.com/test.png

Please provide the resolution ASAP. If resolution is not available for this issue, kindly suggest a work around at least.

**Comment by ashkulz** [comment]
Issue reported against an old version, which is not supported. Please note that this is a limitation of Qt (301 Redirects are not followed), so you'll have to ensure that it doesn't occur in the source HTML.

**Comment by swamypendli** [comment]
Hi Ashish,

Thank you very much for clarifying this issue, but please let us know
whether this 301 redirect issue is resolved in latest version of
wkhtmltopdf or not.

Thanks
Veera

**Comment by ashkulz** [comment]
Try it and see, but it is unlikely to be solved -- this is a limitation in Qt, based on which wkhtmltopdf is developed.

**Comment by SeidChr** [comment]
i could imagine a bruteforce solution. parsing the html for images, download them with powershell following the redirects, also replace the image tag sources with references to the local file. then use the tool
lille hazzle though.
