### ISSUE TITLE
toPage to high by one

### ISSUE THREAD

**Issue by ArturBertram** [wkhtmltopdf/wkhtmltopdf#2458]
When i generate a pdf from the following html with the following command, the page number is to high by one. It only occurs when the last entry (123456 123456 1234567) of the body has a word or chars seperated by blank space which are longer than 6.

HTML:
https://www.dropbox.com/s/53hgdiw86ey922w/report.zip?dl=0

Command:
wkhtmltopdf -d 90 --header-html report.header.html --footer-html report.footer.html --page-size A4 --margin-top 60 --dpi 90 --header-spacing 55 --margin-left 17 --margin-bottom 23 --margin-right 17 --orientation Portrait report.body.html test.pdf

Using 0.12.2.1 for Debian 8.

**Comment by Tomsgu** [comment]
Is this still an issue in 0.12.5?

**Comment by ashkulz** [comment]
I suspect this was fixed by #2711, please reopen with details if this is still an issue.
