### ISSUE TITLE
I can't get wkhtmltopdf to generate a PDF if there are broken images in the HTML

### ISSUE THREAD

**Issue by shyamdadimuni** [wkhtmltopdf/wkhtmltopdf#2460]
Using WKHTMLTOPDF to generate PDF's and but it won't generate a PDF for me if there is a broken image on the HTML page I am generating the PDF from.

Is there a way to get it to ignore these broken images and generate a PDF anyways?

FYI I am pulling HTML in from webpages, so I cannot control if there are broken images or not.

Thanks

**Comment by Tomsgu** [comment]
You can try `--load-error-handling <handler>` option.
