### ISSUE TITLE
Compile wkhtmltopdf with Docker without schroot.

### ISSUE THREAD

**Issue by matrixise** [wkhtmltopdf/wkhtmltopdf#2461]

**Comment by ashkulz** [comment]
Without a description, how do you expect me to understand the issue? If you mean that you want to use Docker instead of an `schroot`, I don't see a huge advantage of using that approach.

**Comment by matrixise** [comment]
Because I use docker with my CI server and I would like to build the last version of wkhtmltopdf for Jessie on this server without an installation of VM, to secure my installation.

**Comment by ashkulz** [comment]
Use the tarballs for 0.12.3-dev, they are good enough to use in production. For 0.12.3 onwards, there won't be distro-specific releases.

**Comment by matrixise** [comment]
yep, but I wanted to have a .deb file and not a tarball. I have my own apt repository for my "private" packages.

**Comment by ashkulz** [comment]
I won't be removing the distro-specific targets from the build script, just not building them for the official release.
