### ISSUE TITLE
Banner image not able to load with wkhtmltopdf

### ISSUE THREAD

**Issue by kindadolf** [wkhtmltopdf/wkhtmltopdf#2465]
I am trying to take a screen shot of the following webpage http://www.abbeagency.com.

So, I tried the following command. 

`wkhtmltoimage --no-stop-slow-scripts --javascript-delay 15000  --width 1000 --height 1800 http://www.abbeagency.com test.jpg`

I also tried to tweak a couple of the parameters/options. But, the images being captured are all different from what I see when opening the URL from a browser. More specifically, the banner image is not shown.

(if it helps, I am on CentOS 6.4 using wkhtmltoimage 0.12.2.1 (with patched qt))

**image from wkhtmltoimage**

![image](https://cloud.githubusercontent.com/assets/3445649/8710800/8096029c-2b1a-11e5-9860-f6edd5974b46.png)

**image from browser**

![image](https://cloud.githubusercontent.com/assets/3445649/8710829/bef73f88-2b1a-11e5-9cf5-cfd4a47d5eba.png)

**Comment by alloylab** [comment]
is this still an issue on 0.12.5?
