### ISSUE TITLE
wkhtmltopdf VS sharepoint

### ISSUE THREAD

**Issue by elmata5** [wkhtmltopdf/wkhtmltopdf#2466]
Bonjour, 

Merci pour cet "outil" puissant et gratuit qui répond à la majeure partie de mes besoins.
Cependant j'ai un cas de figure où l'outil ne marche pas très bien. Vous saurez peut être me dire.
Pour une raison que j'ignore quand je lance wkhtmltopdf dans un site sous sharepoint, le flux se coupe.
C'est à dire que le rendu est partiel, je n'ai que le bandeau du haut. Si j'applique un style je peux agir sur mes éléments mais le flux est toujours coupé juste après le header. Je pense que le problème vient des appels de script qu'il y a dans la page. Avez-vous déjà rencontré ce souci. Existe t-il une commande qui dise de ne pas prendre les scripts de la page (pour tester) : 

Voici ma commande : 
"C:\chemin\wkhtmltopdf\bin\"wkhtmltopdf --load-error-handling ignore --user-style-sheet file:///C:/mon_style_css_local.css --proxy http://xx.xx.xx.xx --username "moije" --password "password" https://serveursharepoint/site/page.aspx c:/rendu.pdf

D'avance merci pour votre aide.

**Comment by ashkulz** [comment]
Désolé, je ne comprends pas le français (I don't understand French -- got it from Google Translate).
