### ISSUE TITLE
wkhtmltopdf sharepoint cut broken content 

### ISSUE THREAD

**Issue by elmata5** [wkhtmltopdf/wkhtmltopdf#2467]
Hi, ok I'm really sorry.

I said :
Thanks a lot for this powerful and free tool. It meets most of my needs...

However I have a case where the tool does not work very well . You'll be telling me .

For whatever reason when I run wkhtmltopdf in a site running under sharepoint, flow is cut.
This means that the rendering is partial, I have only the upper part (banner/header site)

I think the problem is about the scripts called into the page. Have you ever met this concern.
Is there an option or a command that prevents run the page scripts ? (to test)

Here's my command : 
"C:\mypath\wkhtmltopdf\bin\"wkhtmltopdf --load-error-handling ignore --user-style-sheet file:///C:/localhost.css --proxy http://xx.xx.xx.xx --username "myusername" --password "mypassword" https://serversharepoint/site/page.aspx c:/rendering.pdf

In advance thank you for your help.

**Comment by alloylab** [comment]
is this still an issue on 0.12.5?
