### ISSUE TITLE
Bookmark: Out of range in Acrobat reader

### ISSUE THREAD

**Issue by melhadad** [wkhtmltopdf/wkhtmltopdf#2468]
See sample data in http://tmp.barzilay.org/bookmark.zip

We generate a PDF file from HTML with multiple sections.
A bookmark is generated for each section.
When we open the generated PDF in Acrobat Reader under Windows (all versions up to 11.0.12)
and click on one of the bookmarks, we get an error:  "A number is out of range".

We looked in the generated PDF and found that the bookmarks are generated with the following
PDF destination objects:

```
22 0 obj
[2 /XYZ -37471.5000  
721.250000  0]
endobj
```

The "number out of range" comes from the X value used in this declaration.
As soon as this value is out of the range [-32768, 32767] we get the error.

This is clearly a bug in Adobe Acrobat Reader  - but given the prevalence of this tool
it would be better to generate PDF files that don't make it fail.

Generating simply a fixed -1 seems to work just fine (make the bookmark centered on the left 
side of the page):

```
22 0 obj
[2 /XYZ -1 
721.250000  0]
endobj
```

**Comment by alloylab** [comment]
What version? have you tried this on 0.12.5?

**Comment by alloylab** [comment]
We are closing this out since we haven't heard from you. If you are still having this issue please feel free to re-open it. Thanks.
