### ISSUE TITLE
Segmentation faults when using both headers and footers

### ISSUE THREAD

**Issue by ecokisoli** [wkhtmltopdf/wkhtmltopdf#2470]
Hi,

wkhtmltopdf: 0.12.2.1 (with patched qt)
OS: Debian GNU/Linux 7 (wheezy)

I've got a "Segmentation fault" when using both headers and footers. Works fine when headers and footers are not added, or when adding either headers or footers.

This happened so far only three times over 1000 conversions. Headers/footers are always the same, contents template is the same, contents length varies.

One odd thing I've noticed in the output is that current page is greater than total number of pages:
Segmentation fault===========================================] Page 5 of 4

I can submit source files (contents, header and footer) on request.

Thanks.
Seb.

**Comment by ashkulz** [comment]
Try if it works for you with `0.12.3-dev`, if not post the full test case and commandline args.

**Comment by Tomsgu** [comment]
Closing as there is no feedback from the author.
