### ISSUE TITLE
Misleading error message when supplying only one --margin-??? global option

### ISSUE THREAD

**Issue by bgadoury** [wkhtmltopdf/wkhtmltopdf#2472]
I haven't looked, but judging from the docs on the margin options stating the defaults in mm, that the defaults are getting mixed with my single "--margin-top 1.0in" internally, then raising this misleading error message. (Clearly this is a rather minor issue/complaint. I'm loving wkhtmltopdf overall!)

$ wkhtmltopdf --margin-top 1.0in http://google.com/ /tmp/test.pdf
Loading pages (1/6)
Error: Currently all margin units must be the same!
Exit with code 1, due to unknown error.

**Comment by alloylab** [comment]
is this still an issue on 0.12.5?

**Comment by taulant01** [comment]
> is this still an issue on 0.12.5?

yes it is still an issue. I am using 0.12.5 and I am getting the same error
