### ISSUE TITLE
Misc problems on Centos 7.

### ISSUE THREAD

**Issue by elirani** [wkhtmltopdf/wkhtmltopdf#2475]
Hi. Thanks for the tool, using it allot.

Problems. The problem is on Centos 7 x64, more then one machine, all without GUI, with X installed, tested with wkhtmltopdf-0.12.1-1.el7.x86_64 and with 12.1-3 (rpm)
converting the attached file on Centos 7 causes the right part to be cut, and the header that usually shows only on the first page now shows on every page, above the expected table on that page (problem starts from page 2).

No problem on a Fedora machine with wkhtmltopdf-0.12.2.1-1.fc21.x86_64.
No problem on a Centos 7 machine with wkhtmltopdf-0.12.2.1-1.fc21.x86_64 (!).

Files :
normal pdf (as expected) - https://filetea.me/t1s7SdkDbSeSpOCNZbeGNz4Xw
broken pdf - https://filetea.me/t1sBmxJ2F0WRDSORiaxSyq1ug
html - https://filetea.me/t1s6BhkD4CmTqmEg2jZDgOAJA

Thanks.

**Comment by elirani** [comment]
Sorry. files are here, ignore the older links.

http://dropcanvas.com/txhs0

**Comment by alloylab** [comment]
is this still an issue on 0.12.5?

**Comment by Tomsgu** [comment]
Closing as there is no feedback and the attached files are not available anymore.
