### ISSUE TITLE
some bookmarket unicode error

### ISSUE THREAD

**Issue by mhohai** [wkhtmltopdf/wkhtmltopdf#2479]
at Adobe PDF:
![img](http://img.vim-cn.com/24/ed5c54484b5d8a6e8509932799bb5764d36caa.png)
服务 display 朊务

**Comment by ashkulz** [comment]
Without a minimal, reproducible test case as requested in the [support page](http://wkhtmltopdf.org/support.html) this issue cannot be investigated further.
