### ISSUE TITLE
Exit with code 1 due to http error: 1006

### ISSUE THREAD

**Issue by rfhayashi** [wkhtmltopdf/wkhtmltopdf#2480]
I'm getting this error when trying to convert some "https" urls. Curiously if we change the url to http it works (the server is set to redirect http to https). The webserver used to be JBoss, but we moved to Apache recently when the error started to pop up. We think that could be some sort of handshaking problem. Curl and wget work fine. Any ideas?

**Comment by ashkulz** [comment]
Are you using the latest stable or testing version?

**Comment by rfhayashi** [comment]
Indeed, using the latest version the problem doesn't happen. We found that the problem is related to Server Name Indication, the ServerName in apache is set to www.domain.com, and we were trying to hit domain.com. The latest version works anyway. Thank you for your help.
