### ISSUE TITLE
target-counter() supported?

### ISSUE THREAD

**Issue by PhilterPaper** [wkhtmltopdf/wkhtmltopdf#2484]
64-bit MinGW wkhtmltopdf 0.12.2.4 with patches on Windows 7 SP1

I am trying to convert HTML test reports that have a built-in Table of Contents already (just links), and would like to avoid using the "toc" object (and separating out a cover page) to minimize disruption to the current workflow and because I have several "List of ..." subTOCs. Anyway, I've been trying

a.toc::after { content: " . . . . . " target-counter(attr(href), page); }

but nothing happens (no error reported... there is nothing added to the link text). This is in top-level CSS, as **@page** and **@media print** sections seem to be ignored (the .css file is included only for PDF generation). If I change the content to something fixed, it *does* print, so it's processing this CSS entry. Incidentally, if I use counter(page) instead, it always shows 0 as the page number. If I can get this to work, I'll try leader('.'). I also want to use similar CSS to add " [page NN]" after all other links.

My primary question: is **target-counter()** supported? If not, is there another way to grab the page number of the target and stick it in the text? If it *is* supported, any idea what might have gone wrong? As I said, the **page** counter seems to be always 0, and **@page** seems to be ignored.

I've googled all over the place, and everyone gives different information. I've tried attr(href), attr(href url), and attr(href, url) per many postings, with no difference. I'm not (re)setting or incrementing "page" anywhere -- does that need to be done explicitly? Some sources say it works fine, others say it was a CSS3 dream and never worked!

**Comment by ashkulz** [comment]
As you've already found out, it's not part of the specifications which have been implemented by most browsers, including WebKit. Additionally, wkhtmtlopdf currently uses a very old version of WebKit, so unless it works with the 0.13 alpha builds it is unlikely to be supported in future as well.

**Comment by PhilterPaper** [comment]
OK, if I can't get a link's target page via target-counter(), is there any other way? Or am I stuck with using a toc object and forget about putting page numbers on internal links? I can do *minor* changes to the HTML, if that's needed to implement something.

**Comment by ashkulz** [comment]
If you absolutely need it, it should be available in Prince and possibly FlyingSaucer. Otherwise, there is no real solution.

**Comment by PhilterPaper** [comment]
I've been discussing this with my client, and the inability to add page numbers to links is a deal killer.  They want leader dots and page for the TOC, and [page NN] on internal links. I've been looking for a way to do this, so long as it is completely automated. I looked at building something in Perl's **PDF::API2** library, but so far I am unable to disassemble a page to the point where I can 1) determine what page a link target is on, and 2) modify the link text to include the page number.

I then looked at using **pdftk** to unpack a PDF file produced by wkhtmltopdf. I think I can locate link targets in the unpacked PDF (clumsy, but possible), but I can't find the clickable link text. It appears that all text is given a character at a time, plus it's an indirect reference to a font set entry. Is this correct, and if so, it's almost impossible to search for text. Do you have any suggestions? Fixed length page numbers (say, 3 digits) are fine, so that line lengths don't change.

One thing I *can* do is take the information about target page locations and modify the HTML to add the page numbers to the links, and then run wkhtmltopdf again. Repeat until page numbers stop drifting, or some reasonable limit is reached. Is this the best way, or is there some simple free tool that will change specific text patterns in one operation? Thanks!

**Comment by PhilterPaper** [comment]
I've done it. I have a Perl language utility that modifies the input HTML to add page references (TOC and internal links), converts to PDF (wkhtmltopdf), unpacks it (pdftk), finds all internal link targets and the page each is on, updates the HTML with the latest page numbers. Repeat until nothing changes. So far, it does it within 2 loops. @ashkulz, if you're interested in looking at this with thoughts of either bundling it with wkhtmltopdf, converting it to an .exe file, or even extending wkhtmltopdf to do this, I'll be happy to send it to you. The resulting PDF files are quite nice.

**Comment by ashkulz** [comment]
@PhilterPaper: can you post it as a gist?

**Comment by PhilterPaper** [comment]
Let's see if this works: https://gist.github.com/PhilterPaper/a466f8d33e865b5b341b
It's two files: HTML2PDF.pl and toPDF.bat (Windows)
run: perl HTML2PDF.pl <inputHTML> <outputPDF>
