### ISSUE TITLE
@page and @media supported?

### ISSUE THREAD

**Issue by PhilterPaper** [wkhtmltopdf/wkhtmltopdf#2485]
64-bit MinGW wkhtmltopdf 0.12.2.4 with patches on Windows 7 SP1

I have CSS with a **@page { }** section and a **@media print { }** section, and both seem to be ignored. The CSS settings within media print I can simply pull out into a separate .css file and <link> that file only when PDF is to be generated, and the media size I can set in the command line rather than in @page, but it would be nice to know if these sections are unsupported or if I'm doing something wrong. Incidentally, the "page" counter is always 0, if that's useful information.

**Comment by ashkulz** [comment]
Can you check if this works with the `0.13 alpha` builds?

**Comment by djlerman** [comment]
Is there an answer to this issue?  

Is it possible or not supported?

**Comment by ashkulz** [comment]
Unlikely, but did you try the build mentioned above?

**Comment by PhilterPaper** [comment]
I have not yet been able to get to the alpha build. I hope to try some time in the near future.

**Comment by sikko** [comment]
I'd be really interested to know if this works on 0.13 alpha, unfortunately i'm running OSX and there's no build for it at the moment... Does anyone know? It would be really useful if we could control everything with @page. I just found out how powerful it can be:
http://www.smashingmagazine.com/2015/01/designing-for-print-with-css/

Thanks

**Comment by Jmuccigr** [comment]
If I'm not mistaken, at least the @media issue is taken care of with the `--print-media-type` flag.

**Comment by Tomsgu** [comment]
Is this still an issue in 0.12.5?

**Comment by PhilterPaper** [comment]
Unfortunately I am no longer involved with the affected project, and no longer have this need. Perhaps some day I'll have some time to check this out on 0.12.5, or someone else will, but for now I have no need for this capability. You can close this if it's not of general interest.

**Comment by leducvin** [comment]
According to official [WebKit website](https://webkit.org/css-status/#), CSS Paged Media is now supported.

I'm using wkhtmltopdf 0.12.6 and it doesn't seem to work.
