### ISSUE TITLE
remapping of problem entities

### ISSUE THREAD

**Issue by PhilterPaper** [wkhtmltopdf/wkhtmltopdf#2487]
64-bit MinGW wkhtmltopdf 0.12.2.4 with patches on Windows 7 SP1

This is probably more of a feature request. In my HTML input, there are a number of "exotic" HTML entities used, such as & lang (&lang;) and & rang (&rang;) (left and right shallow angle brackets, not < and > or French angled quotation marks). wkhtmltopdf is rendering them as empty boxes, which doesn't look good.

What if wkhtmltopdf (or Qt, whoever is handling HTML entities) were to look in a user-supplied table mapping various problem HTML entities (named or numeric) to something else, such as ASCII characters, other entities which PDF can support? For example, &lang; might be mapped to & lsaquo (&lsaquo;) or (worst case) & lt (<). Only if the processor has no idea how to render this entity should it output the empty box.

**Comment by ashkulz** [comment]
Are you sure those characters are supported in the font you have specified? Try using a font which has support for almost all characters e.g. `Arial Unicode MS`.

**Comment by PhilterPaper** [comment]
I tried Arial Unicode MS, and it was also missing the (at least, so far) 3 special characters I use: left and right angle brackets &lang; and &rang; (which can be replaced by lsaquo &lsaquo; and rsaquo &rsaquo;), and a double right arrow &#8658; (which might be replaced with =>).

**Comment by PhilterPaper** [comment]
I've been going through my HTML source in finer detail, and find that wkhtmltopdf is missing quite a few entities. One of the most important is something to break long ID names (at _, -, or /) for which I use zero-width-space (&#8203;) in HTML. I have also tried &shy;/&#173; and &thinsp;, but all give a narrow box character. If I don't use anything, extra long ID names simply make the table columns wider, which is why I wanted to break them in the first place. Any ideas? Using Arial Unicode MS, as suggested, doesn't help.

I have workarounds for some things (=&gt; for double right arrow, &lsaquo;&rsaquo; for l/r angle brackets, <sup>SM</sup> for service mark, etc.) but I need the filled left and right triangles (9664 and 9654). I'm also still looking for heavy X and checkmark symbols.

**Comment by PhilterPaper** [comment]
Update: I found some good left and right filled triangles at 9668 &#9668; and 9658 &#9658; that wkhtmltopdf supports, so I'm good there. I've got some mediocre substitutes for X and checkmark (&cross; and &check;), using times (***&times;***) and italic bold Greek "nu" (***&nu;***), but a nu doesn't make a good checkmark so I'm still looking. I tried the radic (&radic;) but it refused to take bold or italic.

I'm still looking for some sort of soft break marker for long names. 8203/zwsp, 173/shy, and thinsp all failed. If I get desperate enough, I might just stick a regular space in to split long names! At least, spaces are fairly narrow in proportional fonts, so it doesn't look horribly broken up. If anyone has some suggestions to try, I'm listening! A soft hyphen is OK to insert at the break.

**Comment by FilB90** [comment]
Just for the benefit of anyone else who may stumble across this... This was a problem for me too - in the end I used a CSS font (Font Awesome, but there are others) to replace special symbols with corresponding `<i></i>` tags prior to rendering as PDF. Gives a good result.

**Comment by Tomsgu** [comment]
Is this still an issue in 0.12.5?

**Comment by PhilterPaper** [comment]
Unfortunately I am no longer involved with the affected project, and no longer have this need. Perhaps some day I'll have some time to check this out on 0.12.5, or someone else will, but for now I have no need for this capability. You can close this if it's not of general interest.
