### ISSUE TITLE
Using --window-status and --javascript-delay never returns

### ISSUE THREAD

**Issue by ddumont** [wkhtmltopdf/wkhtmltopdf#2490]
Windows 64 bit: wkhtmltopdf 0.12.2.4 (with patched qt)

I have `--javascript-delay 2000 --window-status print` as args.   I was expecting that it would time out at 2000 if the condition were not met, but it seems to wait forever.

Taking out --window-status makes it render in 2 seconds as expected.

It would be great if there were more debug feedback... perhaps if it polled to standard output the value of window.status so I knew it was checking.  When I load my page in chrome, I see the timeout with my window.status message being set, so it should be working here.

Note: I do believe that only using --window-status alone (without delay) will also wait forever so maybe it's just --window-status that's broken.

**Comment by ddumont** [comment]
Update: I managed to fix my page, apparently there was something wrong with the code setting the status.  

I still do not know why it waited forever if I included the delay... but I have worked around that by having my launching process kill the child after a max timeout.  You can close this if you want.

**Comment by ddumont** [comment]
Another update.  I have a sneaking suspicion that I'm running into #1855 

My use case is not an image that's failing.  I think I might be generating too many simultaneous requests?  I don't get a error in chrome, but I do get the ContentOperationNotPermittedError error.

(In the previous comment I had refactored my code that relied on the network requests to always set status instead of only on success, and now I'm not blocking forever)

Is there any way to dump network debug to a file to inspect?

**Comment by ddumont** [comment]
Found my issue.   Thanks for having a --debug-javascript!
All set, had a request returning a 403.

**Comment by ashkulz** [comment]
Can you let me know what kind of debugging output you'd like to see? An example would be helpful.
