### ISSUE TITLE
Text elements being split across pages

### ISSUE THREAD

**Issue by ddumont** [wkhtmltopdf/wkhtmltopdf#2491]
![image](https://cloud.githubusercontent.com/assets/482734/8948548/770869ac-3576-11e5-9e1d-c6e96f65ca5a.png)

Is it possible to have it force certain elements displayed across a page boundary to appear on the next page intact?

**Comment by ashkulz** [comment]
This can happen in a row with `page-break-inside: avoid`.

**Comment by ddumont** [comment]
@ashkulz I'm not sure what you mean.   Are you saying I need to apply that css to element I **do not** want to be split in the middle?

I tried that and it did not help, I still have headers being cut in half.

**Comment by ddumont** [comment]
Looks like I have to vastly simplify my DOM.

**Comment by ashkulz** [comment]
If you don't use `tr { page-break-inside: avoid }`, rows may split across pages. If you **do** use, text in a line may get split across pages in rare scenarios (see #2141). Really unfortunate situation, but this is due to a limitation in the WebKit engine itself, see comments in linked issue.

**Comment by BruceEckel** [comment]
`tr { page-break-inside: avoid }` Did not help. Is it because the problem I'm having is within code listings?

**Comment by cristian100** [comment]
This continues to be an issue on version 0.12.3 (with patched qt)

**Comment by montao** [comment]
I too have this issue. It makes my whole scenario useless. Nothing works. I read every conversation about it and I tried every "solution" that you mentioned. Nothing works.

**Comment by vsoundar** [comment]
Any progress/ideas on this issue please?
