### ISSUE TITLE
First page is blank and last page is labelled Page 3 / 2 

### ISSUE THREAD

**Issue by mathlarocque** [wkhtmltopdf/wkhtmltopdf#2493]
Hi, I got a weird case (that doesn't happen every time).
What happens is that my pdf is supposed to be 2 page long but it come out with 3 pages, the first one contains a div with minimal information (height of 30 px), followed by a table which is the main content (with a page-break-before: avoid !important and a page-break-inside: avoid !important) followed by another small div (around 250 px in height).

My case append when the table start on the second page, that leave the first div on the first page, the table and the second div are on the second page and goes over to the third. Since they would normally enter in the 2 first page (because there is enough space), the total page is calculated to 2 but 3 are generated.

I fixed this by removing the table page-break-inside: avoid !important. 

I simply wanted to report this in case it may help someone else and so that you can fix the page number issue eventually. Here is a screenshot of the average rendering of page which show the issue.

![bug_page_3_of_2](https://cloud.githubusercontent.com/assets/3694948/8962006/521c32e8-35e6-11e5-80ce-71ac4c616742.png)

**Comment by ashkulz** [comment]
Can you post a test case, command line and the platform/version?

**Comment by mathlarocque** [comment]
I'm using wkhtmltopdf version 0.12.1, with ruby-on-rails 4.2.1 
I will send you the html for a test case tomorrow.

**Comment by mathlarocque** [comment]
I send you an email with the information you requested. it contains the html with command to generate the pdf, the rendered pdf with the problem and some info about my ruby-on-rails version (which is not useful in this case but anyways...) Hope this help.

**Comment by ashkulz** [comment]
Can you add it as a gist, so that it is available in public? Either way, I don't have time to look into this right now due to a personal emergency. Can you check if the behavior is better in 0.12.3-dev (testing release)?

**Comment by Tomsgu** [comment]
Closing as it was fixed in newer versions.
