### ISSUE TITLE
Cannot render Thai font on Amazon Linux

### ISSUE THREAD

**Issue by Techbrunch** [wkhtmltopdf/wkhtmltopdf#2496]
I'm trying to convert this simple html file containing thai characters to pdf but all thai characters are rendered as square on our ec2 instance.

```html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title></title>
    </head>
    <body>
        <h1>ท่านลงทะเบียนข้อตกลงที่พักกับ Booking.com เสร็จสมบูรณ์แล้ว หลังดำเนินการเสร็จสิ้นเราได้ส่งอีเมลยืนยันข้อมูลและสำเนาข้อตกลงสกุลไฟล์ PDF ไปให้ท่าน

            หากท่านต้องการรับสำเนาของข้อตกลงที่พักนี้อีกครั้ง โปรดคลิกที่นี่</h1>
    </body>
</html>
```

I have tested it with all the CentOS versions and nothing works (centos 5, 6, 7 32bits and 64bits). I also tried with the Testing version and it does not work either.

I had the same problem on my local Ubuntu (14.04.2 LTS) machine but I was able to solve it by installing `libthai0` and `xfonts-thai`.

I tried to do the same on the Amazon linux machine by installing the `libthai` package but the `xfonts-thai`package is not available.

If I look at the currently available locale I can find the thai one:

    $ locale -a | grep th
    thai
    th_TH
    th_TH.tis620
    th_TH.utf8

Any ideas how I can solve this ?

**Comment by ashkulz** [comment]
Without the required fonts being available and registered with fontconfig, there is nothing Ithat can be done. Look at the files installed by debian package and search which package provides them in your distro or install manually.

**Comment by Techbrunch** [comment]
@ashkulz  I tried to manually install the fonts provided by the `xfonts-thai` package:

```
wget ftp://linux.thai.net/pub/thailinux/software/thaixfonts/thaixfonts-1.2.7.tar.xz
cd cd thaixfonts-1.2.7
./configure
make
sudo make install
```

The fonts are installed in `/usr/local/share/fonts/X11/misc`.

Update the font information cache:

`sudo fc-cache /usr/local/share/fonts -fv`

    /usr/local/share/fonts: caching, new cache contents: 0 fonts, 1 dirs
    /usr/local/share/fonts/X11: caching, new cache contents: 0 fonts, 1 dirs
    /usr/local/share/fonts/X11/misc: caching, new cache contents: 14 fonts, 0 dirs
    /var/cache/fontconfig: cleaning cache directory
    /root/.fontconfig: not cleaning non-existent cache directory
    fc-cache: succeeded

But then when I do `fc-list` I don't see them ...

**Comment by ashkulz** [comment]
That's a fontconfig problem, please ask on a mailing list/forum/IRC for help. If you do get an answer, would appreciate an update.

Also, please report the missing package to amazon so that they may package it in future...

**Comment by Techbrunch** [comment]
Ok I finally solved it:

```
wget ftp://linux.thai.net/pub/thailinux/software/fonts-tlwg/fonts-tlwg-0.6.1.tar.xz
tar -xf fonts-tlwg-0.6.1.tar.xz
cd fonts-tlwg-0.6.1
sudo yum install fontforge
./configure
make
make install
cd ..
mkdir thai
find . -name '*.ttf' | cpio -pdm ./thai
cd thai
sudo cp -R fonts-tlwg-0.6.1/ /usr/share/fonts/
fc-cache -frv /usr/share/fonts/
```

Now I need to package it, I'll update this comment.

**Comment by ashkulz** [comment]
Good to know that it worked for you.

**Comment by icecoll** [comment]
Ubunut:
```
apt-get install -y fonts-thai-tlwg-ttf
```
