### ISSUE TITLE
Bytes comparison are not identical

### ISSUE THREAD

**Issue by jspinsanti** [wkhtmltopdf/wkhtmltopdf#2501]
Hi team,

My configuration:
wkhtmltopdf --version
wkhtmltopdf 0.12.2.1 (with patched qt)

uname -a
Linux 3.11.0-26-generic #45~precise1-Ubuntu SMP Tue Jul 15 04:02:35 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

Steps:
1) use same source file
2) transform twice obtaining result1.pdf and result2.pdf
3) result1.pdf and result2.pdf are not identical byte per byte. I think this is produced because the translation timestamp is put on the binary.

Are there a flag to avoid this condition? Is it an issue or an expected behavior?

Regards.

**Comment by ashkulz** [comment]
This is expected behavior.

**Comment by jspinsanti** [comment]
One more question: can I avoid this situation using a flag in conversion?
We have a test for comparison. For this expected behavior, we need to relax the test using a compatibility less than 100% between expected and current pdf.

**Comment by ashkulz** [comment]
There's no such flag at the moment, as I suspect this difference comes as part of the PDF support present in Qt (underlying framework used). If you can identify the exact field(s) which are different using a PDF structure editor or hexdump, I can try to identify where exactly they get generated in the PDF.

**Comment by jspinsanti** [comment]
Source: test.html
Target: test-1.pdf, test-2.pdf
Diff attached ("creation date").
![diff](https://cloud.githubusercontent.com/assets/12845908/9060816/bc0f768c-3a8d-11e5-87e9-d41652f2ed24.png)

**Comment by ashkulz** [comment]
You can make a custom build by [removing these lines](https://github.com/wkhtmltopdf/qt/blob/wk_4.8.7/src/gui/painting/qprintengine_pdf.cpp#L1289-L1307) and replacing them with `xprintf("\n");`
