### ISSUE TITLE
overlapping text when repeating headers/footers in pdf using html2pdf

### ISSUE THREAD

**Issue by sarnali** [wkhtmltopdf/wkhtmltopdf#2502]
I convert a invoice page as a pdf. through HTML2PDF converter
my code is in below

<page backtop="14mm" backbottom="14mm" backleft="10mm" backright="10mm" style="font-size: 12pt">
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1000/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Untitled Document</title>
</head>
<style type="text/css">

    table.page_header {width: 100%; border: none; padding: 2mm }
    div.page_footer {width: 100%; border: none; padding: 2mm}

    div.niveau
    {
        padding-left: 5mm;
    }
	

</style>

<body style="font-size:12px; color:#000; font-weight:bold;">
<page_header>
<div style="border-bottom:5px solid #000; border-top:5px solid #000; padding:10px 0px; margin-bottom:30px;>

<table cols="3" width="740" align="center" style="text-align:center; margin-top:30px" class="page_header">
    	<tr>
    	<td align="center" width="740" style="font-size:30px; text-align:center; " ><?php echo $_POST['company'];?></td>
        </tr>
        
</table>

<table width="740" style="margin-top:60px">
	<tr>
        <td width="246" align="left">ACN:<?php echo $_POST['acn'];?></td>
        <td width="246" align="center"><?php echo $_POST['email'];?></td>
        <td width="246" align="right">ABN:<?php echo $_POST['abn'];?></td>
    </tr>
</table>
</div>
</page_header>

<div class="container" style="margin-top:200px">
<table width="740" height="300">
	<tr>
		<td width="246" align="left"> 
            <table>
            	<tr><td><?php echo $_POST['street'];?></td></tr>
                <tr><td><?php echo $_POST['town'];?></td></tr>
                <tr><td><?php echo $_POST['address'];?></td></tr>
            </table>
        </td>
        <td width="246" align="center">
            <table>
            	<tr><td style="font-size:36px; font-family:Arial, Helvetica, sans-serif">Tax Invoice</td></tr>
                <tr><td><?php echo $_POST['tax_invoice_no'];?></td></tr>
            </table>
        </td>
        <td align="left" width="246">
            <table align="right">
            	<tr><td><?php echo $_POST['phone'];?></td></tr>
                
                <tr><td><?php echo $_POST['date'];?></td></tr>
            </table>
        </td>

</tr>
</table>

<table width="740" height="200" style="margin:30px 0" >
	<tbody>
    	<tr>
        <td align="left" width="370">
		<table>
        	<tr>
            	<td>Payment Mode:</td>
                <td style="word-break: break-all;"><?php echo $_POST['payment_terms'];?></td>
            </tr>
        </table>
		
		<?php //echo $_POST['customers'];?></td>
        <td align="right" width="370">Deliver To: <?php echo $_POST['deliver_name'];?> <?php echo $_POST['deliver_code'];?></td>
        </tr>
    </tbody>
</table>

<p><?php echo $_POST['ponumber'];?></p>

<table class="span-24 last" style="width:740px; margin:0; font-size:12px;border-collapse: separate;border-spacing: 0;   vertical-align: middle; border:1px solid #aaa; font-family:Arial, Helvetica, sans-serif; margin:30px 0 30px 0; border:1px solid #000">
	<thead>
	<tr>
		<th class="span-4" style="width:120px; background: #DFDFDE; border-right:1px solid #aaa; font-family:Arial, Helvetica, sans-serif; padding:5px 0 " > <?php echo $_POST['product_code'];?></th>
        
    	<th class="span-8" style="width:260px; background: #DFDFDE; border-right:1px solid #aaa; font-family:Arial, Helvetica, sans-serif; line-height: 24px; text-indent: 10px; padding:5px 0"><?php echo $_POST['item_description'];?></th>
        
    	<th class="span-4" style="width:120px; background: #DFDFDE; border-right:1px solid #aaa; font-family:Arial, Helvetica, sans-serif; line-height: 24px; text-indent: 10px; padding:5px 0"><?php echo $_POST['quantity'];?></th>
        
    	<th class="span-4" style="width:120px; background: #DFDFDE; border-right:1px solid #aaa; font-family:Arial, Helvetica, sans-serif; line-height: 24px; text-indent: 10px; padding:5px 0"><?php echo $_POST['unit_price'];?></th>
    	<th class="span-4" style="width:120px; background: #DFDFDE; border-right:1px solid #aaa; font-family:Arial, Helvetica, sans-serif; line-height: 24px; text-indent: 10px; padding:5px 0"><?php echo $_POST['total'];?></th>
	</tr>
	</thead>
	<tbody>
     <?php 
	 if($_POST['hidd2']!='edit'){
	 $subtotal = 0;$sal_tax = 0;
	 for($i=0,$j=1;$i<=count($_POST['qua_val']);$i++,$j++){
		 if(!empty($_POST['qua_val'][$i])){
			 $subtotal = $subtotal + $_POST['qua_val'][$i] * $_POST['unit_val'][$i];
			 $sal_tax = $subtotal * 20/100;
		 ?>
	
	<tr <?php if($i%2==0) {?>style=" background: #EBEBEA;"<?php }?>>
		<td title="This field is done automatically" style="height: 25px; border-right:1px solid #aaa; font-size:13px"><?php echo $j;?></td>	
    	<td style="font-size:13px; border-right:1px solid #aaa;"><?php echo $_POST['val_item_detail'][$i];?></td>
    	<td style="font-size:13px; border-right:1px solid #aaa;"><?php echo $_POST['qua_val'][$i];?></td>
    	<td style="font-size:13px; border-right:1px solid #aaa;"><?php echo $_POST['unit_val'][$i];?></td>
    	<td style="font-size:13px; border-right:1px solid #aaa;" ><?php echo ($_POST['qua_val'][$i]*$_POST['unit_val'][$i]);?></td>            
	</tr>
<?php }}}elseif($_POST['hidd2']=='edit'){
	 $subtotal = 0;$sal_tax = 0;
	 for($i=0,$j=1;$j<=$_POST['product_count'];$i++,$j++){
		 if(!empty($_POST['qua_val'.$j])){
			 $subtotal = $subtotal + $_POST['qua_val'.$j] * $_POST['unit_val'.$j];
			 $sal_tax = $subtotal * 20/100;
		 ?>
	
	<tr <?php if($i%2==0) {?>style=" background: #EBEBEA;"<?php }?>>
		<td title="This field is done automatically" style="height: 25px; border-right:1px solid #aaa; font-size:13px"><?php echo $j;?></td>	
    	<td style="font-size:13px; border-right:1px solid #aaa;"><?php echo $_POST['val_item_detail'.$j];?></td>
    	<td style="font-size:13px; border-right:1px solid #aaa;"><?php echo $_POST['qua_val'.$j];?></td>
    	<td style="font-size:13px; border-right:1px solid #aaa;"><?php echo $_POST['unit_val'.$j];?></td>
    	<td style="font-size:13px; border-right:1px solid #aaa;" ><?php echo ($_POST['qua_val'.$j]*$_POST['unit_val'.$j]);?></td>            
	</tr>
<?php }}}?>
	</tbody>												
	</table>
    <br />
    <table cols="3" width="740" style="width:600px;border-top:5px solid #000; border-left:1px solid #000; border-right:1px solid #000; padding: 20px 4px 20px 4px; margin:30px 0 0 0">
    	<tr>
    	<td width="740"><?php echo $_POST['comments'];?></td>
        </tr>
    </table>
   
   <div style="border-bottom:5px solid #000; padding:0px 0 20px">
    <div style="border:1px solid #000; padding:0px 0">
    <table  cols="3" width="740" align="center" >
    	<tr>
        	<td width="370" align="left">
              <div style="border-right:1px solid #000; height:100px">
            	<table>
                	<tr>
                    	<td>Please forword payment to:</td>
                    </tr>
                    <tr>
                    	<td width="300" style="height:100px; word-break: break-all;" valign="top"><p><?php echo $_POST['payment_to'];?></p></td>
                    </tr>
                    <tr>
                    	<td valign="bottom"><?php echo $_POST['bsb'];?> </td>
                     </tr>
                    <tr>
                    	<td valign="bottom"><?php echo $_POST['accout_no'];?></td>
                    </tr>
                  </table>
               </div>                
            </td>
            <td width="370" align="right">
            	<table width="340" height="200" style="margin:0px 0;" align="right" >
	
                    <tbody>
                     
                    
                    <tr bgcolor="#fff">
                        <td width="300" align="left" style=" width:240px; height: 25px;font-size:13px"><?php echo $_POST['subtotal'];?></td>	
                        <td width="70" align="left" style="font-size:13px;"><?php echo $subtotal;?></td>
                                   
                    </tr>
                
                    <tr bgcolor="#EBEBEA">
                        <td width="300" align="left"  style="height: 25px;font-size:13px"><?php echo $_POST['sales'];?></td>	
                        <td width="70" align="left" style="font-size:13px; "><?php echo $sal_tax;?></td>
                                    
                    </tr>
                    <tr bgcolor="#EBEBEA">
                        <td width="300" align="left" style="height: 25px; font-size:13px"><?php echo $_POST['total_result'];?></td>	
                        <td width="70" align="left" style="font-size:13px; ;"><?php echo ($subtotal+$sal_tax);?></td>
                                    
                    </tr>
                    </tbody>												
	</table>
            </td>
    	</tr>
    </table>
    </div>
   </div>
  </div>
   <div style="font-size:11px; margin:10px 0">CUSTOMERS PLEASE NOTE: EFTPOS DEBIT AND CREDIT CARD PAYMENTS INCUR 1.5% CHARGE ABOVE INVOICE TOTAL</div> 
  <page_footer>
        <table class="page_footer">
            <tr>
                <td style="width: 100%; text-align: right">
                    page [[page_cu]]/[[page_nb]]
                </td>
            </tr>
        </table>
    </page_footer>
</body>
</html>

 
</page>
![index_pdf_convert php_-_2015-08-04_14 53 28](https://cloud.githubusercontent.com/assets/13639923/9057844/7754e432-3aba-11e5-9658-25110f65497a.png)
![index_pdf_convert php_-_2015-08-04_14 53 28](https://cloud.githubusercontent.com/assets/13639923/9057848/8384cdd0-3aba-11e5-851d-681347a08f7d.png)

but its showing like the image.. please help to findout the problem

**Comment by ashkulz** [comment]
See the workaround documented in #1524.
