### ISSUE TITLE
Overlapped H1 text but shadow is rendered correctly

### ISSUE THREAD

**Issue by clausavram** [wkhtmltopdf/wkhtmltopdf#2503]
All the letters from **`<H1>` headers** are rendered one over the other (as if letter width were too small), but text shadow (CSS: text-shadow: 2px 2px 3px #ccc) is rendered correctly
Don't know if it's related but this is similar to Issue #2376 or #2354
URL: http://www.tutorialspoint.com/csharp/

[PDF]
![image](https://cloud.githubusercontent.com/assets/4466789/9086956/8151dd10-3b90-11e5-9ca3-0cb179a52f4a.png)

[HTML]
![image](https://cloud.githubusercontent.com/assets/4466789/9087041/f3745832-3b90-11e5-9912-421a08d478c2.png)

Side note: Left column from HTML ("C# Basic Tutorial" on orange) is rendered aforehand on a separate page because of page-width.

What can be done so the text (eg: "C# Tutorial") will be rendered correctly?

Specs:
wkhtmltopdf 0.12.2.4 (with patched qt)
Windows 7 x64

**Comment by PhilterPaper** [comment]
Have you confirmed that no **letter-spacing** property with a large negative width is being applied to your headings?

**Comment by Tomsgu** [comment]
Is this still an issue in 0.12.5? On my localhost it works fine now.

**Comment by clausavram** [comment]
​​
Gave up on wkhtmltopdf in the mean time, but will check this when I get the
chance.

**Comment by Tomsgu** [comment]
Ok, good. Feel free to open a new issue if you still have this problem.
