### ISSUE TITLE
Can´t use a variable in the "input" path

### ISSUE THREAD

**Issue by mikemo089** [wkhtmltopdf/wkhtmltopdf#2504]
Hi! I have the following Problem:
I want to write a script which i Need for my Company.
we have some reports of the Monitoring of our customers
I Need to test the creationtime of a specified path. If the specified path is newer than the actually date +(-5 days), the script should convert that html in that path into the pdf.

Here is the script....

#PDFConverter

param([String] $pfad,[int] $monat,$new?)

$monat = Get-Date -Format MM
$path = "\\sv-fs01\usAG-Data\Kunden\ATEC\Reporting\IntelliPool\" + $monat + "\index.htm"
$new? = Test-Path $path -NewerThan (Get-Date).AddDays(-5)

function get-pdf ($new,$monat,$path)    
{
    
   if ($new? -eq "true")
   {
  
  # wkhtmltopdf.exe doesn´t allow, that i use variables in the "input-path".

  C:\test\wkhtmltopdf\bin\wkhtmltopdf.exe "\\sv-fs01\usAG-Data\Kunden\ATEC\Reporting\IntelliPool\" + $monat + "\index.htm"C:\test\Report.pdf

  Write-Host "Pdf konvertiert und abgespeichert"    
   }
     else
   {
     Write-Host "Report ist nicht neu, es wurde KEINE PDf erstellt."   
   
   } 
 
}

Is it possible to use variables in the path  (C:\test\wkhtmltopdf\bin\wkhtmltopdf.exe "\\sv-fs01\usAG-Data\Kunden\ATEC\Reporting\IntelliPool\" + $monat + "\index.htm"C:\test\Report.pdf)

Thanks 4 help!

**Comment by ashkulz** [comment]
This has nothing to do with wkhtmltopdf, it is related to PowerShell.
