### ISSUE TITLE
Wkhtmltopdf failed (error code: -11) 

### ISSUE THREAD

**Issue by mafarij** [wkhtmltopdf/wkhtmltopdf#2507]
Wkhtmltopdf version : 0.12.1
System : Ubuntu server 14.04.03
App reporting the issue : Odoo

Hi,
When i've installed Odoo, Wkhtmltopdf was installed automatically with 0.9.9 version, and i found in forums that this version is not compatible with this version of Odoo (8.0), then i installed the latest version of Wkhtmltopdf, wich is the 0.12.2 version, but still not working, i also tried the previous version 0.12.1, without any improvement.
the error message i got every time i try to print an invoice on odoo is : Wkhtmltopdf failed (error code: -11) Message.
Please help me, i tried every thing google proposed to me.
thanks.

**Comment by ashkulz** [comment]
Unless you can provide a [minimal test case](http://wkhtmltopdf.org/support.html) which is reproducible from the command-line, this issue cannot be investigated further. Please request help via the preferred support mechanism of the project which is calling wkhtmltopdf (Odoo) to identify it as an actual issue in wkhtmltopdf, in which case please reopen this issue with those details.

**Comment by mafarij** [comment]
Hi,

Can you help me provide the test case with the command line please ?!
I'm sort of newbie in this and i dont know what to do.

best regards,

2015-08-06 6:14 GMT+01:00 Ashish Kulkarni <notifications@github.com>:

**Comment by ashkulz** [comment]
Ask help from the Odoo team :smile:

**Comment by mafarij** [comment]
:) Thanks for answering quickly, i did post this issue in odoo forums
without geting a solution :

https://www.odoo.com/fr_FR/forum/help-1/question/wkhtmltopdf-failed-error-code-11-87819

if you have any other suggestions let me know.

best regards

2015-08-06 13:42 GMT+01:00 Ashish Kulkarni <notifications@github.com>:

**Comment by ashkulz** [comment]
Can't help you with Odoo, sorry :frowning:

**Comment by mafarij** [comment]
thanks anyway man ;).

2015-08-07 9:21 GMT+01:00 Ashish Kulkarni <notifications@github.com>:

**Comment by fjbatresv** [comment]
Hello i have the same problem executing aprox 400 pages calculated previously on a python function. Can someone say what is the code -11?

**Comment by bhaymore** [comment]
Seems to be an issue with odoo itself. We found this same issue (with Odoo v8, Ubuntu 14.04, wkhtmltpdf 12.2) but only when we run Odoo with multiprocessing mode enabled. If we set the number of worker processes to 0, disabling multiprocessing mode, the issue disappears. As soon as we enable it by setting the worker processes to say 2, the issue with wkhtmltopdf starts again. We found through some trial and errors that this issue also stops while using multiprocesses when we set the soft and hard memory limits really high. The soft had to be set to 1GB and the hard to about 1.5GB. Once we set those numbers high the issue again stops happening.

**Comment by MohammedAuneor** [comment]
thank you for your help it works fine for me

**Comment by fjbatresv** [comment]
Yes @bhaymore that problem is fro odoo monitoring the processes on the server I saw that odoo/python consume all the ram and the wkhtmltopdf stay out of that obviously killing the process....

**Comment by yelizariev** [comment]
The reason in memory shortage.
Check my answer how to fix it in odoo https://www.odoo.com/forum/ayuda-1/question/wkhtmltopdf-failed-error-code-11-75795#answer_98751

**Comment by fjbatresv** [comment]
Yes, that is true @yelizariev 

Odoo is really a hard consumer of memory and s for this that when you see the documentation of deploy this say that the recommended is 1GB of RAM by 2 users.

**Comment by mlaitinen** [comment]
This may also occur with small reports that don't require lots of memory. In our case – with a custom report – the problem didn't have anything to do with memory. wkhtmltopdf was unable to handle Bootstrap CSS style for a small well in some cases and changing it's padding from `9px` to `11px` solved the issue.

This is of course just one case, but the point is that the culprit could be found in CSS styles used in custom reports.

**Comment by Bric91** [comment]
Hi mlaitinen, maybe I have the same problem.
How can I find my reports CSS style?

thanks

**Comment by mlaitinen** [comment]
@Bric91 Enable the Odoo developer mode and open your browser's developer console. Enabling the developer mode in Odoo will prevent compression of the CSS files.

If you don't have custom CSS styles in place, it could be that your problem is not CSS-related.

**Comment by fmdl** [comment]
Dear, When you try to generate a big pdf (over 200 pages) with header and footer, you are an error -11. It is a limitation of max handle file per process. (default is 256 for mac). But the wkhtmltopdf open for each page the header and the footer. to change this value : http://stackoverflow.com/questions/16526783/python-subprocess-too-many-open-files 

In terminal do : `ulimit -n 10000`
Check : `ulimit -a`
