### ISSUE TITLE
The line is broken when using Arial, sans-serif, Helvetica fonts

### ISSUE THREAD

**Issue by Hirurg103** [wkhtmltopdf/wkhtmltopdf#2508]
We have the following html:
```html
<html>
  <head>
  <style>
    .label { font-family: Arial; }
    .name{ display: inline-block; }
  </style>
  </head>
<body>
  <div class='label'>
    <div class='name' style='background-color: #f9def9;'>Label &gt; 1</div>
  </div>

  <div class='label'>
    <div class='name' style='background-color: #ccde12;'>Label &gt; Sub &gt; 1</div>
  </div>
</body>
</html>
```
For some reason wkhtmltopdf v.0.12.2.1 breaks the label's text on `&gt;` when we add the css rule `font-family: Arial` (the same with sans-serif, Helvetica) for the label. We didn't have this issue with wkhtmltopdf v0.9.9.3.

![screen shot 2015-08-06 at 10 54 25 am](https://cloud.githubusercontent.com/assets/2171773/9106803/8bf68248-3c2b-11e5-9445-93fc74f0cb5e.png)

**Comment by ashkulz** [comment]
Please don't open new issues and continue the discussion in #2505

**Comment by Hirurg103** [comment]
Ok, no problem at all. I tried to reopen #2505, but seems that I don't have right to it
