### ISSUE TITLE
malware reported

### ISSUE THREAD

**Issue by PhilterPaper** [wkhtmltopdf/wkhtmltopdf#2513]
wkhtmltopdf 0.12.2.4 patched qt on Windows XP SP3

I was running wkhtmltopdf today, and my anti-malware package raised an alarm that wkhtmltopdf was trying to download something from the Internet. This worries me, for my client is going to kill the project if I require freeware that does mysterious downloads. 

Anyway, has anyone else seen this kind of thing? Is it documented anywhere what kinds of accesses (if any) that wkhtmltopdf goes to the Web for? This only happened this one time, so it's possible it was a fluke or false positive. However, I'm dead meat if my client gets alarms that something is trying to go through the firewall, and I can't give a reasonable explanation for it!

**Comment by ashkulz** [comment]
Is it Symantec? It could be a false positive, see the download FAQ.

**Comment by PhilterPaper** [comment]
EmsiSoft. It was based on behavior (running process trying to access the outside network), not a virus byte pattern.

If wkhtmltopdf or QT is *supposed* to be periodically calling home for update or security information, that's fine. I just need to be able to tell the client it's OK and harmless. Even better if it can be turned off (depending on exactly what it's doing, and how security critical it is).

**Comment by ashkulz** [comment]
What was the URL? Unless you have it in the webpage, there is no network access

**Comment by PhilterPaper** [comment]
The source HTML being converted, and the CSS, images, etc. are all local files, so it shouldn't have gone to the network for anything. *Within* the HTML there are links to a half dozen or so external sites (Java, Selenium, and a few others) -- would those have been accessed at all? If so, why didn't I get the malware warning each time? The warning said only that htmltopdf was trying to access the network, and didn't give the URL it was supposedly trying to reach.

Is QT or wkhtmltopdf periodically trying to reach a site for updates or news? That would be acceptable, so I can at least reassure my client that nothing nasty is going on.

**Comment by PhilterPaper** [comment]
As it only happened once, I've told the client it was apparently a fluke and they should not see this, at least not on any regular basis. They will let me know if they see it.
