### ISSUE TITLE
additional top/bottom margin when using headers, footers

### ISSUE THREAD

**Issue by PhilterPaper** [wkhtmltopdf/wkhtmltopdf#2514]
wkhtmltopdf 0.12.2.4 qt patched, Win XP SP3

I define a header (page number at upper right) and footer (centered security notice) in the wkhtmltopdf command line. I also have 0.5 inch top and bottom margins on Letter paper (8.5in x 11in). I notice a cosmetic problem in that there is no margin below the header or above the footer. The header text descenders (e.g., "page [page]") touch the top of the text below (or a thead box), and descenders on the last line touch the top of the footer text. A little extra space in both places would be nice looking.

**Comment by PhilterPaper** [comment]
NVM. I found --header-spacing and --footer-spacing do a fine job of this. It would be nice to permit any unit besides mm, but that's minor. Closing.

**Comment by diguage** [comment]
@PhilterPaper I had a same problem. Could you show me you command line configration ?

**Comment by PhilterPaper** [comment]
What have you tried? What does something like `"C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe" --footer-spacing 5 input.html output.pdf` do for you? That would insert 5mm of space between the bottom of the text and the footer.

**Comment by diguage** [comment]
I have tried many option. I used the following option at last.

```
$wkhtmltopdf --page-size A4 \
             --header-left "DocName" \
             --header-right "[subsection]" \
             --header-spacing 3 \
             --header-font-size 10 \
             --header-line \
             --footer-line \
             --footer-spacing 4 \
             --footer-left "D瓜哥 · https://www.diguage.com/" \
             --footer-right '[page] / [toPage]' \
             --footer-font-size 10 \
             --margin-top 20mm \
             --margin-bottom 20mm \
             --margin-left 15mm \
             --margin-right 15mm \
             $pdf_html_file_name $pdf_file_name
```

But, I want to show the header line and the footer line. But I don't know how to set the space of between the header content and the header line.

**Comment by PhilterPaper** [comment]
So, you see the header line and the footer line, but the header is touching (or overlapping) the first content line, and the last content line is touching (or overlapping) the footer? All I can suggest at this point is to temporarily try a much larger spacing, to confirm that the requested amount of space actually does (or does not) get inserted, and report it here as a bug if there is no (or too little) space added as requested. You will need to provide all the relevant information, including the wkHTMLtoPDF version, operating system and version, etc. If you _are_ getting some spacing, but it isn't enough, check if the page is being auto-scaled or not.

**Comment by PhilterPaper** [comment]
duplicate thread opened in #3757. reclosing this one.

**Comment by kavishatalsania** [comment]
@PhilterPaper I am generating pdf with `wkhtmltopdf --margin-left "0mm" --margin-right "0mm" --no-outline --page-size "letter" --header-html "path" --footer-html "path"`

I am getting a thin line between content and footer as shown in image.

![image](https://user-images.githubusercontent.com/32358748/79341003-b76d7c00-7f48-11ea-8d27-4164e9b361d8.png)

I've tried `--footer-spacing 0` and `--no-footer-line` still not work.

Thank you for your help.

**Comment by PhilterPaper** [comment]
Are you talking about the thick white line about halfway down? I'm not sure what that is. Are you using a background color (non-white) on your page? If so, it looks like there is a little gap between the body and the footer. I don't think it's really the footer margin. Do you have anything else with a non-white background, such as a `<div>` with possibly padding or margin?

**Comment by kavishatalsania** [comment]
Yeah I am talking about the gap between body and footer. I am using grey background in body and also in footer. So basically my whole page has grey background. HTML file renders properly without any gap between body and footer, but PDF is showing gap. I am not sure what that gap is!

**Comment by rajeshkr7** [comment]
@kavishatalsania  have you solve that body and footer gap (spacing) issue?
Thanks

**Comment by kavishat** [comment]
@rajeshkr7 I add the option --footer-spacing -1 which solved my problem.

**Comment by rajeshkr7** [comment]
@kavishat this is my command
wkhtmltopdf -B 40 -L 10 -R 10 -T 85mm --footer-spacing -1 --header-html header.html --footer-html footer.htmlbody.html pdf-44.pdf

but issue still there.
thanks

**Comment by kavishat** [comment]
@rajeshkr7 try adding --footer-spacing -5mm. It should fill the gap between body and footer content. Increase/decrease footer spacing based on the gap.

**Comment by rajeshkr7** [comment]
@kavishat actually the space depend on the body.html data, I mean if data is full for the page than footer will come correct but data is less than it shows the gap between body and footer.

by using --footer-spacing -20 it decrease the the gap but in first page it comes over the body data.
So if I can set body data part close to footer than it could solve.
so is there any command for that?

thanks

**Comment by kavishat** [comment]
@rajeshkr7 Are you using background color for the whole page? If so just use <div style="page-break-after: always;"></div> before body content completed in body.html file. And use --footer-spacing -1mm/-2mm if needed.

**Comment by rajeshkr7** [comment]
@kavishat not using any color for background but color for particular section of the body and footer.
I am using this
```
*{
     page-break-inside: avoid;
     page-break-after: avoid;
     page-break-before: avoid;
  }
```

**Comment by davidbuckleyni** [comment]
I am having a strange issue with margin between my column headers and headings is that what you encountered here @PhilterPaper
