### ISSUE TITLE
repeating headers do not have text when text is rotate

### ISSUE THREAD

**Issue by Balnian** [wkhtmltopdf/wkhtmltopdf#2516]
When my header is repeated the rotated text inside is lost.

fiddle: https://jsfiddle.net/2oygzp21/
html+css+js in one file (easier to test render): https://gist.github.com/Balnian/e211c453932646d0b048

and i'm using this command : wkhtmltopdf -O Landscape -s Letter <file.html> <file.pdf>

**Comment by mshs013** [comment]
I've same problem 1st page show rotated text but 2nd page does not show.

**Comment by Tomsgu** [comment]
Works completely fine in 0.12.5, so I am closing the issue
