### ISSUE TITLE
Segmentation fault generating PDF from html with embedded google-maps image

### ISSUE THREAD

**Issue by OscarDev-** [wkhtmltopdf/wkhtmltopdf#2519]
Hi,

I have build an apache module, that handles calls trough an web-service, which also has support for generating an PDF of an html-page. 
On most requests the PDF is generated just fine but in some cases I get an segmentation fault.

I have generated the following stacktrace:

> # 0  0x00007f457ecb9c2b in QNetworkConfigurationManagerPrivate::enablePolling() () from /lib64/libQtNetwork.so.4
> # 1  0x00007f457ecb8057 in QNetworkConfigurationManager::QNetworkConfigurationManager(QObject*) () from /lib64/libQtNetwork.so.4
> # 2  0x00007f457ec86f3d in QNetworkAccessManager::createRequest(QNetworkAccessManager::Operation, QNetworkRequest const&, QIODevice*) () from /lib64/libQtNetwork.so.4
> # 3  0x00007f4584971e12 in wkhtmltopdf::MyNetworkAccessManager::createRequest(QNetworkAccessManager::Operation, QNetworkRequest const&, QIODevice*) () from /lib64/libwkhtmltox.so.0
> # 4  0x00007f457ec83d24 in QNetworkAccessManager::get(QNetworkRequest const&) () from /lib64/libQtNetwork.so.4
> # 5  0x00007f4581212a63 in WebCore::QNetworkReplyHandler::sendNetworkRequest(QNetworkAccessManager*, WebCore::ResourceRequest const&) () from /lib64/libQtWebKit.so.4
> # 6  0x00007f4581213b34 in WebCore::QNetworkReplyHandler::start() () from /lib64/libQtWebKit.so.4
> # 7  0x00007f4581212f3f in WebCore::QNetworkReplyHandlerCallQueue::flush() [clone .part.56]() from /lib64/libQtWebKit.so.4
> # 8  0x00007f4581212f8b in WebCore::QNetworkReplyHandlerCallQueue::push(void (WebCore::QNetworkReplyHandler::*)()) () from /lib64/libQtWebKit.so.4
> # 9  0x00007f4581213107 in WebCore::QNetworkReplyHandler::QNetworkReplyHandler(WebCore::ResourceHandle*, WebCore::QNetworkReplyHandler::LoadType, bool) () from /lib64/libQtWebKit.so.4
> # 10 0x00007f458120c2b5 in WebCore::ResourceHandle::start(WebCore::NetworkingContext*) () from /lib64/libQtWebKit.so.4
> # 11 0x00007f4580fe58ad in WebCore::ResourceHandle::create(WebCore::NetworkingContext_, WebCore::ResourceRequest const&, WebCore::ResourceHandleClient_, bool, bool) () from /lib64/libQtWebKit.so.4
> # 12 0x00007f4580ebeadf in WebCore::MainResourceLoader::loadNow(WebCore::ResourceRequest&) () from /lib64/libQtWebKit.so.4
> # 13 0x00007f4580ebf5e3 in WebCore::MainResourceLoader::load(WebCore::ResourceRequest const&, WebCore::SubstituteData const&) () from /lib64/libQtWebKit.so.4
> # 14 0x00007f4580e9391a in WebCore::DocumentLoader::startLoadingMainResource() () from /lib64/libQtWebKit.so.4
> # 15 0x00007f4580eaaf30 in WebCore::FrameLoader::continueLoadAfterNavigationPolicy(WebCore::ResourceRequest const&, WTF::PassRefPtrWebCore::FormState, bool) () from /lib64/libQtWebKit.so.4
> # 16 0x00007f4580eaaf7f in WebCore::FrameLoader::callContinueLoadAfterNavigationPolicy(void*, WebCore::ResourceRequest const&, WTF::PassRefPtrWebCore::FormState, bool) () from /lib64/libQtWebKit.so.4
> # 17 0x00007f4580ec7831 in WebCore::PolicyCallback::call(bool) () from /lib64/libQtWebKit.so.4
> # 18 0x00007f4580ecdc1b in WebCore::PolicyChecker::continueAfterNavigationPolicy(WebCore::PolicyAction) () from /lib64/libQtWebKit.so.4
> # 19 0x00007f458091f8f0 in WebCore::FrameLoaderClientQt::dispatchDecidePolicyForNavigationAction(void (WebCore::PolicyChecker::*)(WebCore::PolicyAction), WebCore::NavigationAction const&, WebCore::ResourceRequest const&, WTF::PassRefPtrWebCore::FormState) () from /lib64/libQtWebKit.so.4
> # 20 0x00007f4580ecc9a9 in WebCore::PolicyChecker::checkNavigationPolicy(WebCore::ResourceRequest const&, WebCore::DocumentLoader_, WTF::PassRefPtrWebCore::FormState, void (_)(void_, WebCore::ResourceRequest const&, WTF::PassRefPtrWebCore::FormState, bool), void_) () from /lib64/libQtWebKit.so.4
> # 21 0x00007f4580eac3e2 in WebCore::FrameLoader::loadWithDocumentLoader(WebCore::DocumentLoader*, WebCore::FrameLoadType, WTF::PassRefPtrWebCore::FormState) () from /lib64/libQtWebKit.so.4
> # 22 0x00007f4580eaead0 in WebCore::FrameLoader::load(WebCore::DocumentLoader*) () from /lib64/libQtWebKit.so.4
> # 23 0x00007f4580eaf290 in WebCore::FrameLoader::load(WebCore::FrameLoadRequest const&) () from /lib64/libQtWebKit.so.4
> # 24 0x00007f45808d9e0d in QWebFrame::load(QNetworkRequest const&, QNetworkAccessManager::Operation, QByteArray const&) () from /lib64/libQtWebKit.so.4
> # 25 0x00007f4584972ee6 in wkhtmltopdf::ResourceObject::load() () from /lib64/libwkhtmltox.so.0
> # 26 0x00007f4584973fb9 in wkhtmltopdf::MultiPageLoaderPrivate::load() () from /lib64/libwkhtmltox.so.0
> # 27 0x00007f458498b4cc in wkhtmltopdf::PdfConverterPrivate::beginConvert() () from /lib64/libwkhtmltox.so.0
> # 28 0x00007f4584975bc6 in wkhtmltopdf::ConverterPrivate::convert() () from /lib64/libwkhtmltox.so.0
> # 29 0x00007f45849974ad in wkhtmltopdf_convert () from /lib64/libwkhtmltox.so.0
> # 30 0x00007f45865bc2a6 in PDFConverter::startConversion (this=0x7fff6362dcd0) at src/PDFConverter.cpp:176

**Comment by alloylab** [comment]
is this still an issue on 0.12.5?
