### ISSUE TITLE
Top margin disappears when using html footer

### ISSUE THREAD

**Issue by tomasjav** [wkhtmltopdf/wkhtmltopdf#2523]
Today I noticed this strange behaviour.

At first I run: `wkhtmltopdf http://facebook.com test.pdf`

Everything's looking good: there are margins, everything fits.

But if I try `wkhtmltopdf --footer-html http://google.com/ http://facebook.com go.pdf` strange thing happends - top margin is gone. At first I though that footer content causes this issue but then I tried adding blank html file to footer and behaviour didn't change.

Version: 0.12.2.1 (with patched qt) on OS X 10.10

**Comment by darles** [comment]
+1

**Comment by sergey-verevkin** [comment]
+1

**Comment by shekky** [comment]
+1

**Comment by Tomsgu** [comment]
Closing in expense of #2561.
