### ISSUE TITLE
No way to securely download the packages

### ISSUE THREAD

**Issue by magicgoose** [wkhtmltopdf/wkhtmltopdf#2527]
They are hosted on `http://download.gna.org/wkhtmltopdf/…`, it doesn't support HTTPS _and_ there is no way to check downloaded file integrity (there are no checksums nor GPG signatures). The package itself is not signed, this _is_ a problem when there's no way to download it securely, and also it causes additional hassle when trying to install (see screenshot).

<img width="420" alt="screen shot 2015-08-19 at 7 19 04 am" src="https://cloud.githubusercontent.com/assets/1442206/9348667/0a869e74-4643-11e5-97a9-781701883fb1.png">

That means, if an attacker does MitM attack on the network and modifies the package in some evil way, there's no way for user to detect it — this is a **big security flaw.** Please, fix it ASAP.

Probably the easiest solution is to host the packages together with source archives on github "releases". It's also possible to automate this.

**Comment by graingert** [comment]
@ashkulz can you release signed versions of http://download.gna.org/wkhtmltopdf/0.12/0.12.4/SHA256SUMS http://download.gna.org/wkhtmltopdf/0.12/0.12.4/SHA1SUMS and http://download.gna.org/wkhtmltopdf/0.12/0.12.4/SHA256SUMS http://download.gna.org/wkhtmltopdf/0.12/0.12.4/MD5SUMS

**Comment by ashkulz** [comment]
Downloads are now at Github, and checksums will be signed.

**Comment by ashkulz** [comment]
Packages for 0.12.5 [are available](https://wkhtmltopdf.org/downloads.html#stable) using signed checksums.
