### ISSUE TITLE
Encoding issue for Korean/Chinese on Windows

### ISSUE THREAD

**Issue by gsulca** [wkhtmltopdf/wkhtmltopdf#2534]
Hi,

I tryed to create a pdf from an html page. The page has the metadata defined but I'm not able to generated a pdf with the special characters. I set the --encoding 'utf-8' on the command line but it didn't work. I recieved a file with white squares.
Can you help me on this?
I'm using:
- Windows 8. 
- cmd
- wkhtmltox-0.12.2.4_msvc2013-win64

The command line is: wkhtmltopdf --encoding 'utf-8' example-korean.html example.pdf

The korean language was installed on my compurer.
Thanks and Regards,
Geannina Sulca

**Comment by alloylab** [comment]
is this still an issue on 0.12.5?
