### ISSUE TITLE
Slow execution first time

### ISSUE THREAD

**Issue by bernex** [wkhtmltopdf/wkhtmltopdf#2535]
I run command: wkhtmltopdf.exe 2.html 2.pdf

And freeze for 4sec on: Loading pages (1/6)

Html is simple without JS and border-radiuses and heavy css, fonts...

Why?

**Comment by ashkulz** [comment]
If it is not freezing after the first time, it is very likely that a virus scanner is examining the executable. Check if it runs faster with the virus scanner disabled.

**Comment by BeSolver** [comment]
Hi Ashkul,

Need Help!!

I am using your tool to convert html to pdf
