### ISSUE TITLE
Headers stop rendering midway through document

### ISSUE THREAD

**Issue by keveh** [wkhtmltopdf/wkhtmltopdf#2536]
I'm having an issue where I have introduced a header in to a PDF that we create, this all works fine however we've come across an issue with some documents that have a large amount of pages where the header stops rendering. In its place is either nothing, but in some cases there is the following part of an array displayed:
`
 'topage' => '82',
 'doctitle' => 'Liquid Plastics',
 'sitepages' => '82',
 'webpage' => 'http://specifications.uk.sika.com/htmldoc/generate/id/12754/ispdf/true',
 'time' => '07:28:51',
 'date' => '21 Aug 2015',
) 
`
Is there a known issue of this happening?

Thanks

**Comment by alloylab** [comment]
is this still an issue on 0.12.5?
