### ISSUE TITLE
wkhtmltopdf content-type missing in HTTP POST

### ISSUE THREAD

**Issue by BCSTECH** [wkhtmltopdf/wkhtmltopdf#2541]
Hi,

I'm using wkhtmltopdf and i want to access the action that has authorization. I tried to use this command line below but i recieved and error.

wkhtmltopdf --post Username xxx --post Password test http://localhost:49323/Monitor/Report?id=23232123 c:\temp\sample.pdf

loading page (1/6)
content-type missing in HTTP POST, defaulting to application/x-www-form-urlencoded. Use QNetworkRequest::setHeader() to fix this problem.
Counting pages (2/6)
Resolving Links(4/6)
Loading headers and footers (5/6)
Printing pages (6/6)

Can you help me with this?..or is there another way to access the site with authentication?

Thanks,
Kevin

**Comment by alloylab** [comment]
What version? have you tried this on 0.12.5?

**Comment by alloylab** [comment]
We are closing this out since we haven't heard from you. If you are still having this issue please feel free to re-open it. Thanks.

**Comment by demidenkoalex12** [comment]
The problem recurred. 
Call:
wkhtmltoimage --cache-dir /tmp/cache --enable-local-file-access --post content-type application/x-www-form-urlencoded  --debug-javascript --cookie-jar /opt/test/digital.formobile.com.br.cookie -q --quality 100 --height 10080 digital.formobile.com.br /opt/test/digital.formobile.com.br.jpg

Error:
content-type missing in HTTP POST, defaulting to application/x-www-form-urlencoded. Use QNetworkRequest::setHeader() to fix this problem.

wkhtmltoimage -V
wkhtmltoimage 0.12.5 (with patched qt)

Tryed whith version 0.12.6.
