### ISSUE TITLE
Tables are not coming in  proper manner , it is overwriting

### ISSUE THREAD

**Issue by Goels08** [wkhtmltopdf/wkhtmltopdf#2546]
Hello Champ,

I am using your html to pdf tool i.e wkhtmltpdf and i  have downloaded this tool in my local computer and using with below code.

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;

public class Java_pdf {

   public static void main(String[] args) throws IOException {
        try 
        {
            String htmlFilePath = "D:/html2pdf/a.html";
            String pdfFilePath = "D:/html2pdf/test.pdf";
            ProcessBuilder pb = new ProcessBuilder("C:/Program Files/wkhtmltopdf/wkhtmltopdf.exe", htmlFilePath, pdfFilePath); 
            pb.redirectErrorStream(true); 
            Process process = pb.start(); 
            BufferedReader inStreamReader = new BufferedReader(new InputStreamReader(process.getInputStream())); 
            
            String line = inStreamReader.readLine(); 
            
                    while(line != null) 
                    { 
                        System.out.println(line); 
                        line = inStreamReader.readLine(); 
                    }
        }
        catch(Exception e)
        {
            System.out.println("coming-->"+e.getMessage() );
        }
    }

} 

issue:-  After converting html to PDF my  tables are not coming in proper manner ,its header part are overwriting.

This below image is the  html content  which is as my input

This below image is my output  and i am taking as  pdf format  but above mentioned error.

Based on my analysis if content inside the table is big than in pdf it will take whole table in two pages and not able to set headers properly. Can you please resolve this ASAP.. 

Thanks ,
Besolver

**Comment by PhilterPaper** [comment]
Take a look at issue 2530 (and many others). There have been many reports of problems with tables that split across pages for whatever reason, where by default the first row overwrites the table header (th). One solution seems to be to forbid splitting within rows (see 2530). Since your rows seem to be only one or two lines, that could work for you.

**Comment by BeSolver** [comment]
tr { page-break-inside: avoid; } 
 Can you please tell where i can add this line,Just to inform you i am getting html file from 3rd partySo not able to do any changes in html format

**Comment by PhilterPaper** [comment]
It is a CSS entry. You would have to have access to some place (.css file or in the .html file `<style>` tag) to add this entry.
