### ISSUE TITLE
Process wkhtmltopdf is blocked with particular img url

### ISSUE THREAD

**Issue by bcroquin** [wkhtmltopdf/wkhtmltopdf#2551]
Hi,
Thanks for providing us wkhtmltopdf.

I have an issue when launching wkhtmltopdf on a particular img url : 

My test.html file content is : 
```html
<IMG src="http://impfr.tradedoubler.com/imp?type(img)g(22776768)a(1488062)" height="1" width="1" >
```

When i launch wkhtmtopdf test.html test.pdf, the wkhtmltopdf process is stuck and never ends.

Would you please try to reproduce this issue and tell me if there is a bug ?

Thanks in advance

Benoit

**Comment by linqingtao123** [comment]
I have the same problem

My test.html file content is : 

<img src="http://www.***.com.cn/servlet/getImageServlet?id=987987987"/>

Thanks in advance


xiaoxin

**Comment by Tomsgu** [comment]
Without an example we can't reproduce the issue. Please feel free to re-open the issue if you can post an example that is not working in 0.12.5.
