### ISSUE TITLE
Printing generated pdfs result in a blank page

### ISSUE THREAD

**Issue by unewochialat** [wkhtmltopdf/wkhtmltopdf#2553]
Hello,

i don't know if its a bug or a feature but printing the generated pdfs results in blank pages when i use Osx Preview.app.
os: osx 10
wkhtmltopdf 0.12.2.1 (with patched qt)

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

</head>
<body>
<div>
    <p>
       test
   </p>
</div>
</body>
</html>
```

Generate the pdf with
    wkhtmltopdf http://example.html ./output.pdf
and printing these pdf results in a blank page

has anyone the same issue?

**Comment by sooraj-raveendran-t** [comment]
Even I am phasing same issue. Can anyone please suggest any solution.

**Comment by PhilterPaper** [comment]
Neither of these reports is very clear about what's happening. The HTML looks reasonable. Does it display OK in a browser? When you generate a PDF, does it _display_ properly, but fail to _print_ from the Reader? Or is it producing a blank page when you _display_ it in, say, Adobe Reader? I'm a bit suspicious about your `http://example.html` -- normally something like that would not be found by a browser or by wkHTMLtoPDF. You would need a domain in there (something like "localhost" or a real site).

**Comment by sooraj-raveendran-t** [comment]
the html is proper it is getting displayed on browser properly but somehow one additional page is getting added.

**Comment by Tomsgu** [comment]
@sooraj-raveendran-t Is this still an issue in 0.12.5? Do I understand well the problem is that wkhtmltopdf adds extra blank pages to the output?

**Comment by unewochialat** [comment]
i have tested this again and it's working with 0.12.5.
sorry for the confusion with http://example.html it was a $variable for any website i have tested.
My problem was no content on printed pages if i printed these with Preview.app! In Adobe Reader there was no problem for me. The display on screen was never a problem.
