### ISSUE TITLE
Help needed for alpine-wkhtmltopdf

### ISSUE THREAD

**Issue by LoicMahieu** [wkhtmltopdf/wkhtmltopdf#2554]
I am currently trying to get `wkhtmltopdf` working on [Alpine Linux](http://www.alpinelinux.org/), specially in a Docker container.
Source: https://github.com/LoicMahieu/alpine-wkhtmltopdf
Docker image: [loicmahieu/alpine-wkhtmltopdf](https://hub.docker.com/r/loicmahieu/alpine-wkhtmltopdf/)

Current version is working fine but there is some differences between rendering compared to other platform... Let try this example:

```
docker run --rm -it \
  -v `pwd`:/data \
  loicmahieu/alpine-wkhtmltopdf:latest \
  wkhtmltopdf http://google.com /data/file2.pdf
```

Rendered PDF is: https://cloudup.com/cBRKJVIl_jR

We can easily compare the result when it is executed on Ubuntu:

```
docker run --rm -it \
  -v `pwd`:/data \
  openlabs/docker-wkhtmltopdf \
  wkhtmltopdf --load-error-handling ignore http://google.com /data/file.pdf
```

Rendered: https://cloudup.com/c9CUwr4rAR8
##### Notable differences are:
- Margin are smaller on Alpine
- Fonts are smaller and pixelated

I think there is some dependencies that are missing... Anybody has advice for helping me to getting the render better ?

Links:
- [APKBUILD](http://git.alpinelinux.org/cgit/aports/commit/?id=05b96ec9d84aee92aab7567191daee2e4925a338)

---

> **Why Alpine ?** [Image size](https://imagelayers.io/?images=openlabs%2Fdocker-wkhtmltopdf:latest,loicmahieu%2Falpine-wkhtmltopdf:latest)
> ubuntu:14.04 : 736mb
> alpine:3.2 : 155mb

**Comment by ashkulz** [comment]
First, use the 0.12.3-dev binary. Also, make sure that you install the necessary fonts and have fontconfig configured properly.

**Comment by chdanielmueller** [comment]
Hi @LoicMahieu 

Did you get a result which you were happy with?
I am currently working on my own Docker container. Could you take a look at the config and give me some inputs?
https://github.com/Surnet/alpine-node-wkhtmltopdf

Thanks,
Daniel

**Comment by bhgames** [comment]
@LoicMahieu I am actually having similar issues, I get things like:

http://optionsgrid-production-web-1.us-east-1.elasticbeanstalk.com/a/6u2ujg.pdf on production(alpine)
vs 
https://screencast.com/t/xZpw6GetuA locally(mac)

**Comment by Tomsgu** [comment]
You can get some inspirations here: https://github.com/Surnet/docker-wkhtmltopdf. There is also [this](https://github.com/wkhtmltopdf/packaging/issues/2) issue about alpine linux support.
