### ISSUE TITLE
HTML imports are not resolved

### ISSUE THREAD

**Issue by xandar** [wkhtmltopdf/wkhtmltopdf#2555]
Hello,

When I try to use HTML imports, wkhtmltopdf doesn't seem to resolve the href location in the link tag.

**bar.html**
```html
<html>
	<head></head>
	<body>
		<style>
			div#foo {
				background-color: red;
				
			}
			div#foo:after {
				content : 'and bar';
			}
		</style>
	</body>
</html>
```

**foo.html**
```html
<!DOCTYPE html>
<html>
<head>
	<link rel="import" href="http://localhost/test/bar.html">
</head>
<body>
	<div id="foo" style="width: 100%; height: 200px;">
		foo
	</div>
</body>
</html>
```

The page rendered in Chrome 44 :
![foo](https://cloud.githubusercontent.com/assets/2962214/9635242/d2f96668-5195-11e5-8ba7-e059d662f810.jpg)

The PDF rendered by wkhtmltopdf (0.12.2.4 with patched qt):
![bar](https://cloud.githubusercontent.com/assets/2962214/9635243/d2fc8e38-5195-11e5-8dec-696391a126a6.jpg)

**Comment by ashkulz** [comment]
This is not supported by the version of WebKit used right now, try if it is better with 0.13 alpha. If it doesn't work, you're out of luck...
