### ISSUE TITLE
Segmentation fault on OS X 10.10.4

### ISSUE THREAD

**Issue by jmlacroix** [wkhtmltopdf/wkhtmltopdf#2556]
I've been using `wkhtmltopdf` for a while and everything was working fine. I made a clean Yosemite install recently, and I just noticed the problem.

I get a segfault on my local dev environment (Yosemite 10.10.4, wkhtmltopdf 0.12.3-dev-79ff51e (with patched qt), installed from homebrew). I could not reproduce it on an "external" website, so I shared access to the faulty page in my dev environment through ngrok so you can access it.

Here's the call I make: 

```
$ wkhtmltopdf "http://518c2840.ngrok.io/app/project/94ae0ec8/report/f7e11cc92107d8e93e49c8f7effffe595281fb2e43f81f45d2bd07be6a025ea7" output.pdf
Loading pages (1/6)
Warning: SSL error ignored
Warning: SSL error ignored
2015-09-02 20:30:51.799 wkhtmltopdf[37340:1551278] __agent_connection_block_invoke_2: Connection error - Connection invalid
Counting pages (2/6)
Resolving links (4/6)
Loading headers and footers (5/6)
Printing pages (6/6)
Done
QMutex::lock: mutex unlock failure: Invalid argument
Segmentation fault: 11
```

Here's the crash log: https://gist.github.com/jmlacroix/af61a838596f35c7951e

Thanks for any help and let me know if I can provide anything else to help find the issue.

**Comment by wmertens** [comment]
I'm seeing the same on El Capitan with a pre-build 64 bit binary, and https://github.com/NitMedia/wkhtml2pdf/issues/45 apparently as well…

**Comment by wmertens** [comment]
I finally solved the issue in nodejs by not using streams to communicate with wkhtmltopdf but instead just files and the `child_process.execFile` call.

**Comment by ashkulz** [comment]
Looks like a bug in OpenSSL, the default version in OS X is not supported anymore. Upstream Qt will use Secure Transport from Qt 5.6, but we're still stuck on 4.8.

**Comment by ashkulz** [comment]
#2150 is also related.
