### ISSUE TITLE
wkhtmltopdf convertor

### ISSUE THREAD

**Issue by raob2006** [wkhtmltopdf/wkhtmltopdf#2557]
I have the Windows 2008 server and IE8 is installed. My application is able to convert html to pdf. I have upgraded IE8 to IE11. After upgrade my application is failing to convert html file to pdf. What is the latest version of IE is supported by wkhtmlpdf?
Thanks,
Bhaskara.

**Comment by ashkulz** [comment]
IE is not used by wkhtmltopdf at all.
