### ISSUE TITLE
Amazon Linux - terminate called after throwing an instance of 'std::bad_alloc'

### ISSUE THREAD

**Issue by blackdynamo** [wkhtmltopdf/wkhtmltopdf#2559]
## Problem
Getting the following error and can't make any sense as to why:
```
terminate called after throwing an instance of 'std::bad_alloc'
 what():  std::bad_alloc
Aborted
```

## Steps to reproduce
1. Create an index.html file with the contents from this <a href="https://gist.github.com/blackdynamo/6e64287fe48d49a60122">gist</a>
2. Run this wkhtmltopdf command `wkhtmltopdf --quiet --page-size "legal" -R 0 -L 0 -T 3.96875 -B 3.96875 ./index.html -`

**Note 1:** Switching the commented sections on line 20-21 and 24-26 will cause the command to work. Notice the difference is the *space* vs no *space*.

**Note 2:** Running the command with the "Doesn't work" code and removing -R 0 from the wkhtmltopdf command will also work.

**Note 3:** All seems to work fine on OSX Yosemite. Just seems to fail on Amazon Linux. 

## Hardware/Software Info

`wkhtmltopdf 0.12.2.1 (with patched qt)`
```
NAME="Amazon Linux AMI"
VERSION="2015.03"
ID="amzn"
ID_LIKE="rhel fedora"
VERSION_ID="2015.03"
PRETTY_NAME="Amazon Linux AMI 2015.03"
ANSI_COLOR="0;33"
CPE_NAME="cpe:/o:amazon:linux:2015.03:ga"
HOME_URL="http://aws.amazon.com/amazon-linux-ami/"
Amazon Linux AMI release 2015.03

Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                1
On-line CPU(s) list:   0
Thread(s) per core:    1
Core(s) per socket:    1
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 62
Model name:            Intel(R) Xeon(R) CPU E5-2670 v2 @ 2.50GHz
Stepping:              4
CPU MHz:               2500.092
BogoMIPS:              5000.18
Hypervisor vendor:     Xen
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              25600K
```

**Comment by ashkulz** [comment]
How did you compile the binary? If you didn't compile it but used a CentOS binary, use the 0.12.3-dev build instead, it will work as-is.

**Comment by blackdynamo** [comment]
@ashkulz So is this a viable production option? Is there an estimate as to when a stable release will be coming?

Thanks :)

**Comment by ashkulz** [comment]
@blackdynamo: Yep. No idea for a release date -- it'll get done when it gets done :smile:
