### ISSUE TITLE
Start rendering when ID exist (FeatureRequest)

### ISSUE THREAD

**Issue by j-schulz** [wkhtmltopdf/wkhtmltopdf#2563]
Hello together,

thank you very much for your great work!

I have a feature request:

I know that there is the option --javascript-delay, but for javascript applications it would be much better if wkhtmlto* would wait until a specified ID exists. Example:

wkhtmltopdf --wait-for-id 'finished' https://mysite.test/ test.pdf

Then wkhtmltopdf waits until it found the id '#finished'.

Regards
Jonny

**Comment by DanielCeregatti** [comment]
That's what the --window-status argument is for.

**Comment by j-schulz** [comment]
Oh great. Thank you for the hint.
