### ISSUE TITLE
I can't showing an image on pdf report

### ISSUE THREAD

**Issue by Janneth-Ofelia** [wkhtmltopdf/wkhtmltopdf#2564]
Hi

I have the issue with jpg image showing on html but not on pdf report.

HTML: 
![1](https://cloud.githubusercontent.com/assets/10760604/9723359/1e5d4cda-5585-11e5-9d06-8613ce02970e.jpg)

PDF: 
![2](https://cloud.githubusercontent.com/assets/10760604/9723360/210ccfa0-5585-11e5-9593-474ae9fcd2d8.jpg)

I'm using wkhtmltopdf 0.12.1 

Can anybody help me?

Thanks

**Comment by sneakernets** [comment]
Is this on your local machine? I remember having to provide absolute paths once to images to get around  this. also, I learned the hard way that using "localhost" on files can cause problems, most things expect a numerical IP address like 127.0.0.1.

**Comment by sneakernets** [comment]
Can you show a snippet of the HTML from wkhtmltopdf temp file  around where the image is? it might help.

**Comment by Janneth-Ofelia** [comment]
Hi sneakernets, thank you for help me, this is my code on where is called the image:
     <img class="img img-responsive" src="/formatos/static/src/img/logoIfa.jpg"/>

**Comment by sneakernets** [comment]
Ah ok I think I know what's going on and I ran into this earlier this year... The HTML has a path that works on your machine when you run it but when wkhtmltopdf runs it runs as a browser that expects paths like on the internet (http://...)

Let's try this, in the command to run wkhtmltopdf, add `--allow /formatos/static/src/img`, and that should grab the images when you run it.

**Comment by Janneth-Ofelia** [comment]
Thank you very much for your help, I could work it out with your instructions :)

![3](https://cloud.githubusercontent.com/assets/10760604/9766962/4c113878-56e1-11e5-91c5-d3abf2f52826.jpg)

**Comment by sneakernets** [comment]
Yay! I'm glad it worked! :cake:

**Comment by Janneth-Ofelia** [comment]
![large](https://cloud.githubusercontent.com/assets/10760604/9767908/2fe00e68-56e6-11e5-92b9-0c9547b903be.jpg)

**Comment by Tomsgu** [comment]
Closing as the issue was resolved.
