### ISSUE TITLE
PDF rendering randomly stops

### ISSUE THREAD

**Issue by fnicollet** [wkhtmltopdf/wkhtmltopdf#2565]
Hello,

I am experiencing a strange issue with wkhtmltopdf. Randomly, the rendering of the PDF is incorrect and shows only the cover and a blank page instead of cover + toc + content. Then I just refresh the page to get a new PDF and it will work. And maybe after 20 refreshes, the rendering will be stopped.
Sometime, I also get the rendering with no text (custom font) and no images but the document is still produced.
This is the real document:
![image](https://cloud.githubusercontent.com/assets/1240481/9734528/0ab255ea-5634-11e5-92cf-24fe37254063.png)

This is a rendering I randomly get, with no fonts nor images:
![image](https://cloud.githubusercontent.com/assets/1240481/9734543/22031586-5634-11e5-8afb-0bc2dc103354.png)

And sometimes only the cover with a blank page:
![image](https://cloud.githubusercontent.com/assets/1240481/9734569/5e4022a0-5634-11e5-8f3d-7e5185bb6187.png)

When it fails, I don't have anything special in the console, just sometimes, when rendering succeeds, I get 2 warnings:
```
Warning: Received createRequest signal on a disposed ResourceObject's NetworkAccessManager. This might be an indication of an iframe taking too long to load.
Warning: Received createRequest signal on a disposed ResourceObject's NetworkAccessManager. This might be an indication of an iframe taking too long to load.
```

Could it be that wkhtmltopdf has some kind of leak with the network manager and sometimes, it can't request images or the HTML page and just fails with no error?

Thanks for your help,
Fabien

**Comment by PhilterPaper** [comment]
I'm a bit confused by your terminology. When you say "the **rendering** is incorrect", do you mean that you try redisplaying *the same PDF file* and it succeeds, or are you *regenerating* the PDF file (without error messages, possibly multiple times) until it's a good PDF, or is the *conversion* falling over dead? The first case would suggest it's a problem with Adobe Reader/Acrobat/some other renderer (possibly aggravated by an improper PDF), while the other two are that wkhtmltopdf is choking. You mentioned "new PDF", so I'm guessing that it's not the first case, but it's not clear to me.

**Comment by fnicollet** [comment]
Hello,

Every time I refresh the page, I sent a wkhtmltopdf command line, wait for the result and return it to the browser.
So I am no redisplaying the same PDF, I am regenerating the PDF file multiple times until it's a good PDF

Does that make sense?

Fabien

**Comment by fnicollet** [comment]
Note that I had those PDF using "--load-error-handling skip". But if I remove load-error-handling, I still don't get more information in the console when it fails
The behaviour might be similar to unresolved issue #2346

**Comment by fnicollet** [comment]
Hum, I have changed the "javascript-delay" to 2000 and it seems to fix the issue, maybe when the javascript takes longer than 200ms to execute, a thread is stopped and the rendering fails without further informations
Anyway, this issue can be considered closed, maybe there is something better to log / do when javascript execution takes longer than 200ms thought

Fabien
