### ISSUE TITLE
(featureRequest) direct XML+XSL (=HTML) to pdf support

### ISSUE THREAD

**Issue by wireless82** [wkhtmltopdf/wkhtmltopdf#2566]
Often, XML documents are transformed to HTML via a XSL ad-hoc file. 
Then you can use wkhtmltopdf to trasform the html file into a pdf one. 
It could be useful to add a feature the allow to do these operations directly: through a parameter, the software understood that it has first to transform xml into tempFile.html using a specified xsl; then, he perform the trasformation html to pdf as usual.

**Comment by ashkulz** [comment]
XSLT support in Qt is not great, and in addition it is under maintenance mode only. So it is better to do this transformation outside and then convert the HTML.

**Comment by bschollnick** [comment]
Any chance of a re-review of this?  Is XSL + XML -> HTML still not a viable path with wkhtmltoPDF?
