### ISSUE TITLE
Load error

### ISSUE THREAD

**Issue by roelof1** [wkhtmltopdf/wkhtmltopdf#2568]
I use scripcase to create a pdf using wkhtmltopdf. It generates a file not found error. When I use the command from Ssh on my Vps box with centos7 it generates a load error. It is suggested to swich load error ignore.  When I try that it generates an empty pdf. I can read the html with wget. No errors there. I can write a pdf on my destination path. Generating a test with https Google is perfect. But it will not load html from scriptcase. I have tested the chained css files with fullpath links and wget. The strangest thing is that everything works fine with exactly the same enviroment without ssl. I need ssl so I have to find a solution. Any suggestion Will be highly appreciated. 

Roelof (Rotterdam,  the Netherlands)

**Comment by alloylab** [comment]
is this still an issue on 0.12.5?
