### ISSUE TITLE
Segmentation faults on large document

### ISSUE THREAD

**Issue by iffy** [wkhtmltopdf/wkhtmltopdf#2569]
I've been slowly building a report (markdown -> pandoc -> html -> wkhtmltopdf -> pdf).  It has now reached about 119 pages and I'm consistently getting segmentation faults when I do random things such as:
- Add/remove CSS `page-break-inside: avoid;` to certain elements.
- Add/remove CSS `overflow-x: auto;` to certain elements.

```
$ wkhtmltopdf --version
wkhtmltopdf 0.12.2.1 (with patched qt)
```

OS X 10.10.5 (14F27)

Here's what I'm seeing:

```
$ wkhtmltopdf --enable-internal-links --print-media-type -s Letter --margin-bottom 1in --margin-top 1in --margin-left 1in --margin-right 1in --footer-html pdf_footer.html --footer-spacing 10 --header-html pdf_header.html --header-spacing 10 pdf_coverpage.html report.html report.pdf
Loading pages (1/6)
Counting pages (2/6)                                               
Resolving links (4/6)                                                       
Loading headers and footers (5/6)                                           
Segmentation fault: 11                                       ] 10%
$ echo $?
139
```

As it's a private report, I'll work on creating a safe-to-share version that duplicates the bug consistently and post it here.

**Comment by iffy** [comment]
Alright, I have a gist up that demonstrates the problem: https://gist.github.com/iffy/4f9e12ea0d9f6b317f33

Steps to duplicate:
1. Clone the gist: `git clone git@gist.github.com:4f9e12ea0d9f6b317f33.git && cd 4f9e12ea0d9f6b317f33`
2. Check out the `failing-1` tag: `git checkout failing-1`
3. See that it segfaults: `bash genpdf.sh`
4. Check out the `passing-1` tag: `git checkout passing-1`
5. See that it succeeds: `bash genpdf.sh`
6. See the diff: `git diff failing-1...passing-1`

The difference between the two is that `passing-1` has several lines removed.  Anything else I can provide to help debug this?

**Comment by Tomsgu** [comment]
Closing as there is no segfault anymore in 0.12.5. Please feel free to re-open this issue if you still experience this problem.
