### ISSUE TITLE
Sustained High CPU Usage and Slow to Generate a Simple PDF

### ISSUE THREAD

**Issue by bohlian** [wkhtmltopdf/wkhtmltopdf#2574]
I have an issue with using PDFKIT via Python (which at the background uses WKHTMLTOPDF). For some strange reason generating a simple PDF takes > 17s which honestly shouldnt be the case. 

Further diagnosis reveals that the WKHTMLTOPDF process runs at 99% - 100% CPU utilization for the period of time that the PDF is being generated.

Using CPROFILE for Python, I can narrow down to the following that seems to be the root cause (this runs for 17s+):

69   17.196    0.249   17.196    0.249 {built-in method poll} 

Some environment details are as follows:
- Host OS: VMWare ESXi 5.1
- Guest OS: Ubuntu 14.04.3 LTS 64 bit
- Guest CPU: 4 x Cores Intel Xeon E5506
- Guest RAM: 4GB
- WKHTMLTOPDF Version: 0.12.2.1 (with patched qt) 64 bit

Does anyone have any idea what this "built-in method poll" item is any why it may be contributing to slow PDF generation and high CPU usage?

Thanks.

**Comment by shamitv** [comment]
Does it happen with a specific URL ? Can you reproduce this issue with simple Html/JS page.

**Comment by bohlian** [comment]
@shamitv after deeper investigation I have found out that the root cause is not WKHTMLTOPDF instead it is related to PDFKIT. I haven't found a solution yet and am trying to get help from the PDFKIT authors on this. Thanks very much.
