### ISSUE TITLE
PDF Generation exceeded the timeout of 60 seconds - Symfony

### ISSUE THREAD

**Issue by Uzarkan** [wkhtmltopdf/wkhtmltopdf#2575]
Hello,

I am currently working on a project based on symfony, and trying to use your library to generate some pdf files. I am using the 0.12.2.1 version.
It actually works, but only some times.
When it works, the pdf is succesfully created in 2-3 seconds.
But sometimes, it just fails, whereas I am calling the same function. The script loads during 60 seconds and then, I have an error 500 with the following stack :

request.CRITICAL: Uncaught PHP Exception Symfony\Component\Process\Exception\ProcessTimedOutException: "The process "/usr/local/bin/wkhtmltopdf --image-quality '100' --margin-left '5' --enable-javascript --javascript-delay '1500' --disable-smart-shrinking --no-stop-slow-scripts --footer-html '/tmp/knp_snappy55f2deb3770102.57227710.html' --header-html '/tmp/knp_snappy55f2deb376fab7.83772812.html' '/tmp/knp_snappy55f2deb376f2e5.88879791.html' '/myproject/htdocs/files/estimates/BTB-20150911-C-00436.pdf'" exceeded the timeout of 60 seconds." at /myproject/vendor/symfony/symfony/src/Symfony/Component/Process/Process.php line 1219 {"exception":"[object] (Symfony\\Component\\Process\\Exception\\ProcessTimedOutException(code: 0): The process \"/usr/local/bin/wkhtmltopdf --image-quality '100' --margin-left '5' --enable-javascript --javascript-delay '1500' --disable-smart-shrinking --no-stop-slow-scripts --footer-html '/tmp/knp_snappy55f2deb3770102.57227710.html' --header-html '/tmp/knp_snappy55f2deb376fab7.83772812.html' '/tmp/knp_snappy55f2deb376f2e5.88879791.html' '/myproject/htdocs/files/estimates/BTB-20150911-C-00436.pdf'\" exceeded the timeout of 60 seconds. at /myproject/vendor/symfony/symfony/src/Symfony/Component/Process/Process.php:1219)"} []

I have already done some research around the web to find a solution, but none of them was actually helpful.

Thank you by advance,

Alexandre B.H

**Comment by ashkulz** [comment]
Unfortunately, without a minimal/reproducible test case and environment/command line details as requested in the [support page](http://wkhtmltopdf.org/support.html) this issue cannot be investigated further. Please reopen this issue once you have provided the details instead of creating a new issue.

**Comment by 100phel** [comment]
Try to set a different timeout after creating a snappy instance like so:

`$snappy = new Pdf('/usr/local/bin/wkhtmltopdf.sh');

$snappy->setTimeout(600);  // 600 seconds`
