### ISSUE TITLE
wkhtmltopdf for using in Php function

### ISSUE THREAD

**Issue by fabianbartsch** [wkhtmltopdf/wkhtmltopdf#2576]
Hey guys!

Working on a project which uses the wkhtmltopdf to create pdfs in a php function, like this:

$cmd=t3lib_extMgm :: extPath('ik_lkwdb') . 'res/lib/wkhtmltopdf --page-size A4 --page-width 210 --page-height 297 -B 5 -L 5 -R 5 -T 5  --footer-right "[page]/[topage]" --footer-font-size 8 '.$tempFile.' '.$pdfname.'  	2>&1';

I just found this wkhtmltopdf file in the res/lib/ folder, dont know what it is. Now I assume I have to update it, could you please tell me where to get a new version of that file from?

Thanks and kind regards, 
Fabian

**Comment by PhilterPaper** [comment]
Visit wkhtmltopdf.org for downloads of either prebuilt executables or C++ (I think) source. You'd have to ask whoever put together your system and installed (or built) res/lib/wkhtmltopdf whether they installed something already built, or built it themselves. Presumably this is on a Unixy system, and would more likely have to be built from source.
