### ISSUE TITLE
Incorrect format, also returning error message

### ISSUE THREAD

**Issue by fenghuadong** [wkhtmltopdf/wkhtmltopdf#2577]
https://issues.apache.org/jira/browse/AMQ-219

I was trying to download this page as a pdf, it returns me Exit with code 1 due to network error: AuthenticationRequiredError as an error message. 

Also, the page that it created, it is not in the correct format, big space inbetween.

**Comment by alloylab** [comment]
is this still an issue on 0.12.5?
