### ISSUE TITLE
background size property results in no image when used shorthand

### ISSUE THREAD

**Issue by jgardynik** [wkhtmltopdf/wkhtmltopdf#2584]
Using wkhtmltopdf 0.12.2.1 on debian, when setting the background size of an image using the background: property, the image fails to render. When setting it via the background-size: property, it works. Here's a simple use-case to illustrate. the first and third images will render properly. The second one is empty.

```
<!DOCTYPE html>
<html>
<head>
    <title>wkhtmltopdf test</title>
    <meta charset='utf-8'>
</head>
<body>
    <div style='width: 200px; height: 200px; margin: 10px; background: #999 url("flower.jpg") no-repeat center center'>
    </div>
    <div style='width: 200px; height: 200px; margin: 10px; background: #999 url("flower.jpg") center center/contain no-repeat'>
    </div>
    <div style='width: 200px; height: 200px; margin: 10px; background-color: #999; background-image: url("flower.jpg"); background-repeat: no-repeat; background-position: center center; background-size: contain'>
    </div>
</body>
</html>
```

**Comment by alloylab** [comment]
have you tried this on 0.12.5?

**Comment by alloylab** [comment]
We are closing this out since we haven't heard from you. If you are still having this issue please feel free to re-open it. Thanks.
