### ISSUE TITLE
Creating a PDF/A document 

### ISSUE THREAD

**Issue by katszwn** [wkhtmltopdf/wkhtmltopdf#2585]
Hi, 
Does your software make it possible to generate a PDF/A file? Are PDFs generated by wkhtmltopdf read only?

**Comment by ashkulz** [comment]
Related to #1573

**Comment by zmajew** [comment]
@ashkulz Hi. I did not find the strait answer on katszwn question in #1573.

**Comment by febinct** [comment]
any update on this ticket? I am also looking for the same couldn't find any way
