### ISSUE TITLE
Error in OSX El Capitan

### ISSUE THREAD

**Issue by sul4bh** [wkhtmltopdf/wkhtmltopdf#2588]
I get this error in OSX El Capitan:
qt_mac_loadMenuNib: could not create nib directory in temp 

Anyone else having this issue?

**Comment by pgmassari** [comment]
I'm having the same error with the following setup:
- a fresh update to El Capitan
- a CakePHP project, working as expected in WAMP (didn't try it on osx before updating)
- XAMPP 5.6.12 (I've also tried MAMP)
- **wkhtmltpdf 0.12.2.1** (I've also tried the 0.13 preview)

The error shows up when accessing `/usr/local/bin/wkhtmltopdf` through `proc_open()` with the following cmd, plus some valid html:
`/usr/local/bin/wkhtmltopdf --quiet --print-media-type --orientation 'portrait' --page-size 'A7' --encoding 'UTF-8' --margin-bottom '1mm' --margin-left '1mm' --margin-right '1mm' --margin-top '3mm' - -`

This is the output before dying:
```php
Array
(
    [stdout] => 
    [stderr] => qt_mac_loadMenuNib: could not create nib directory in temp
Error: Unable to create temporary file

    [return] => 11
)
```

I'm accessing wkhtmltopdf through the following plugin, which works as expected on the same project running on WAMP:
https://github.com/FriendsOfCake/CakePdf

Note 1:
wkhtmltopdf works fine when invoked in command line: `$ wkhtmltopdf www.google.com google.pdf`

Note 2:
wkhtmltopdf is in a default global path: `/usr/local/bin/wkhtmltopdf` and folders are accessible/writable by httpd user. Also, all the other parts of the CakePHP project work fine.

Note 3:
Also, in the OSX error console i see the following:
>10/10/15 21:47:14,902 wkhtmltopdf[7378]: WARNING: The Gestalt selector gestaltSystemVersion is returning 10.9.0 instead of 10.11.0. This is not a bug in Gestalt -- it is a documented limitation. Use NSProcessInfo's operatingSystemVersion property to get correct system version number.
Call location:
10/10/15 21:47:14,904 wkhtmltopdf[7378]: 0   CarbonCore                          0x00007fff99fc179f ___Gestalt_SystemVersion_block_invoke + 113
10/10/15 21:47:14,904 wkhtmltopdf[7378]: 1   libdispatch.dylib                   0x00007fff91680453 _dispatch_client_callout + 8
10/10/15 21:47:14,904 wkhtmltopdf[7378]: 2   libdispatch.dylib                   0x00007fff9168034b dispatch_once_f + 67
10/10/15 21:47:14,904 wkhtmltopdf[7378]: 3   CarbonCore                          0x00007fff99f4e09c _Gestalt_SystemVersion + 987
10/10/15 21:47:14,904 wkhtmltopdf[7378]: 4   CarbonCore                          0x00007fff99f4d8b0 Gestalt + 139
10/10/15 21:47:14,905 wkhtmltopdf[7378]: 5   wkhtmltopdf                         0x00000001018c9fca _ZN16QSettingsPrivate6createEN9QSettings6FormatENS0_5ScopeERK7QStringS5_ + 74
10/10/15 21:47:14,905 wkhtmltopdf[7378]: 6   wkhtmltopdf                         0x00000001018abe74 _ZN9QSettingsC1ENS_5ScopeERK7QStringS3_P7QObject + 20
10/10/15 21:47:14,931 launchservicesd[79]: SecTaskLoadEntitlements failed error=22
10/10/15 21:47:14,947 launchservicesd[79]: SecTaskLoadEntitlements failed error=22
10/10/15 21:47:14,954 launchservicesd[79]: SecTaskLoadEntitlements failed error=22
10/10/15 21:47:18,582 diagnosticd[108]: error evaluating process info - pid: 7378, puniqueid: 7378
10/10/15 21:47:18,606 com.apple.xpc.launchd[1]: (com.apple.ReportCrash.Root[7389]) Endpoint has been activated through legacy launch(3) APIs. Please switch to XPC or bootstrap_check_in(): com.apple.ReportCrash.DirectoryService
10/10/15 21:47:19,999 ReportCrash[7389]: Saved crash report for wkhtmltopdf[7378] version ??? to /Library/Logs/DiagnosticReports/...

**Comment by sul4bh** [comment]
For me, this was not an issue with wkhtmltopdf. The temporary folder
returned by sys_get_temp_dir ( void ) was not writable(weird issue, it had
correct permissions but was not writable. Some new security feature in El
Capitan, I guess).

**Comment by pgmassari** [comment]
Thanks @sul4bh.

How did you overcome the writing problem, then?

Did you disable anything in OSX's System Preferences? Did you re-run a chmod on the parent of your temp folder? Or did you just changed the place where that temp were generate?

**Comment by sul4bh** [comment]
I used a different temp folder. I could not figure out what the real issue
with sys_get_temp_dir ( void ) was.

**Comment by pgmassari** [comment]
Thanks again @sul4bh.

Actually, as an attempt, I went to the temp folder and made an explicit `chmod 777` again, and now it works: i see my pdf as expected.

Also, the warning I reported is still there, but of course it's not related to the problem

So definitely it's not a wkhtmltopdf problem and this can be closed.

**Comment by sul4bh** [comment]
Great.

I will go ahead and closw this.
