### ISSUE TITLE
PDF security

### ISSUE THREAD

**Issue by blicksem** [wkhtmltopdf/wkhtmltopdf#2589]
Hello,

First of all, I have to say that wkhtmltopdf is a beautiful application, and it's fast...
At this moment there is only one feature that I'm missing... Security.

Is it possible to add the possibility to protect pdfpages for editing?

Thanks in advance

Niels

**Comment by woutermijle** [comment]
Any feedback on this?

**Comment by Sicos1977** [comment]
Just use iText or Ghostscript or any other "opensource" app to do this. It's not that difficult.

**Comment by Tomsgu** [comment]
As Sicos1977 proposed use another app for this task. I don't think there will be support for this in near future.
