### ISSUE TITLE
--page-width and --page-height don't work together

### ISSUE THREAD

**Issue by dibyendra** [wkhtmltopdf/wkhtmltopdf#2590]
Hi,

I want the PDF output to be 56mm long (height) and 88mm wide (width).

I have tried `wkhtmltopdf -d 300 -L 0 -R 0 -T 0 -B 0 -s Custom -–page-height 56 --page-width 88 page.html out.pdf` but it doesn't execute. 

But if I specify only the width, it executes but with the following output along with error:

```
wkhtmltopdf -d 300 -L 0 -R 0 -T 0 -B 0 –-page-width 88 page.html out.pdf
Loading pages (1/6)
Error: Failed loading page http://xn---page-width-lg3f (sometimes it will work just to ignore this error with --load-err
or-handling ignore)
Error: Failed loading page http://88 (sometimes it will work just to ignore this error with --load-error-handling ignore
)
Exit with code 1 due to network error: HostNotFoundError
```

This means, does this mean the -page-width and --page-height options are not available to the wkhtmltopdf 0.12.2.4?

Thanks!

**Comment by Loess** [comment]
try to  specify width before height:
./wkhtmltopdf -d 300 -L 0mm -R 0mm -T 0mm -B 0mm --page-width 88mm --page-height 56mm http://habrahabr.ru out.pdf
works well

**Comment by Tomsgu** [comment]
Closing as there is no feedback and solutions were provided.

**Comment by gusbemacbe** [comment]
Hello @Tomsgu 

I still am facing the problem. Here is the error:

```
Unknown long argument --page-height '56mm'
```

I am using the latets version of `wkhtmltopdf`. I was running `pandoc`:

```
pandoc -s -V margin-top=0mm -V margin-left=0mm -V margin-right=0mm -V margin-bottom=0mm --pdf-engine=wkhtmltopdf --pdf-engine-opt="--page-height '56mm'" -f markdown-raw_tex -t html5 --metadata title="Biografia" --css /assets/css/colours.css --css /assets/css/fonts.css --css /assets/css/global.css *.md -o combined.pdf --verbose
```
