### ISSUE TITLE
Error code -11

### ISSUE THREAD

**Issue by fjbatresv** [wkhtmltopdf/wkhtmltopdf#2592]
Hello i have the same problem that the issue #2507  executing aprox 400 pages calculated previously on a python function. Can someone say what is the code -11?

**Comment by l-arnold** [comment]
I just got the same error.  Have been running a functioning Odoo 8.0 using wkhtmltox for several months.  Did not change anything in the setup though I am working with a new install.

Is full wkhtmltopdf now supported with Odoo 8.0?

What is error code -11 ?

**Comment by fjbatresv** [comment]
I have received an answer in the odoo forum and is here: https://www.odoo.com/forum/help-1/question/error-code-11-wkhtmltopdf-91256

The user say me that this happens when you top the RAM of the server and exactly this is true. When i make that locale on my pc there aren't problems (this have 8 GB of RAM) and when i execute that on server (this have 1 GB of RAM) this give me the error code.

**Comment by l-arnold** [comment]
Thank you!  I will test.

**Comment by fmdl** [comment]
Dear

When you try to generate a big pdf (over 200 pages) with header and footer, you are an error -11. It is a limitation of max handle file per process. (default is 256 for mac). But the wkhtmltopdf open for each page the header and the footer. to change this value : http://stackoverflow.com/questions/16526783/python-subprocess-too-many-open-files

In terminal do : `ulimit -n 10000`
Check : `ulimit -a`

**Comment by Tomsgu** [comment]
Closing as the solution was provided.
