### ISSUE TITLE
Segmentation fault - has to do with page breaks?

### ISSUE THREAD

**Issue by jcsmith-bds** [wkhtmltopdf/wkhtmltopdf#2593]
wkhtmltopdf is having segmentation faults on some of my HTML input.  The issue sometimes goes away when I (1) manually add a div with page-break-after: always, (2) tweak the length of the content, (3) tweak the header and footer spacing/margins, or (4) change the widths of the bootstrap columns in the input file.  It's very touchy, and it's hard to detect a clear pattern, but given the types of tweaks that fix the issue, I suspect it has something to do with page breaks.

Sample input files are here:  https://gist.github.com/jcsmith-bds/fb43086b9ebf1f7df460

The following command causes a segmentation fault:

`wkhtmltopdf --disable-forms --page-size Letter --margin-bottom 13mm --margin-top 10mm --header-spacing 12 --footer-spacing 0 --encoding utf-8 --header-html "header.html" --footer-html "footer.html" content.html out.pdf 2>&1`

The same command runs fine when executed on a slightly altered input file:

`wkhtmltopdf --disable-forms --page-size Letter --margin-bottom 13mm --margin-top 10mm --header-spacing 12 --footer-spacing 0 --encoding utf-8 --header-html "header.html" --footer-html "footer.html" content-safe.html out.pdf 2>&1`

The original command run on the original file also finishes without a problem with slightly different margin and spacing arguments:

`wkhtmltopdf --disable-forms --page-size Letter --margin-bottom 14mm --margin-top 11mm --header-spacing 13 --footer-spacing 0 --encoding utf-8 --header-html "header.html" --footer-html "footer.html" content.html out.pdf 2>&1`

**Comment by ashkulz** [comment]
This should be fixed with `0.12.5-rc`, see #2711 for details.
