### ISSUE TITLE
Converting local file with remote references (resolving references via proxy)

### ISSUE THREAD

**Issue by tmcdonnell87** [wkhtmltopdf/wkhtmltopdf#2596]
Hi,

I have html files stored locally that contain resources like "/styles/main.css". These reference files that are stored on a web server (e.g. http://localhost:3000/styles/main.css). If I load the _html_ from the web server (e.g. wkhtmltopdf  "http://127.0.0.1:3000/test.html" test.pdf), all of the links are resolved correctly. 

Is there any way run wkhtmltopdf on a local file and point it to where to resolve files? I've tried various options like:

> > wkhtmltopdf --proxy "http://127.0.0.1:3000" test.html test.pdf
> > Loading pages (1/6)
> > Warning: Failed to load file:///images/test-logo.png (ignore)
> > Counting pages (2/6)
> > Resolving links (4/6)
> > Loading headers and footers (5/6)
> > Printing pages (6/6)
> > Done

As shown above, it doesn't work. :-(

Any suggestions?

Thanks!

**Comment by potz** [comment]
I was also hoping that this could somehow be achieved.

**Comment by MichaelSp** [comment]
Maybe this helps you: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base

In short: add something like this to your html
`<base href="http://www.example.com/">`

**Comment by potz** [comment]
I never heard about the base tag before. Quite cool  @MichaelSp thanks.

**Comment by Tomsgu** [comment]
Closing as the solution was provided.
