### ISSUE TITLE
Wkhtmltopdf works with javascript enabled from command line, but not from php

### ISSUE THREAD

**Issue by katcoder** [wkhtmltopdf/wkhtmltopdf#2598]
I am not able to get wkhtmltopdf to work with javascript enabled from my php script. If I run it from the command line, wkhtmltopdf does work with javascript enabled. The reason I need javascript enabled is to include some javascript charts in my pdf that are on my webpage. Any help to get this resolved would be appreciated. Thank  you!

My problem is very similar to the problem described here: http://stackoverflow.com/questions/30915197/wkhtmltopdf-segfault-when-javascript-enabled

My environment:
-  x86 CentOS 64-bit Linux on a shared HostGator server 
- PHP 5.4.43 
- wkhtmltopdf 0.13 static binary

Running the following command from the command line works from my $HOME/bin directory (I don't have write access to /usr/local/bin in my shared Linux environment), and produces the google home page as a pdf with images.

./wkhtmltopdf http://www.google.com google.pdf 2 > error.log

![image](https://cloud.githubusercontent.com/assets/8229225/10055186/afbd26ee-61e9-11e5-8786-d45fe4377744.png)

However, when I try to run this from within php, the command only works if javascript is disabled.

Using the following php script:
```php
function generate_a_pdf()
{  
    error_reporting(E_ALL);
    ini_set('display_errors', 0);
    ini_set('log_errors', 1);


// Get the HTML to convert to a PDF
$url = "http://www.google.com";
$html = file_get_contents($url);
$cwd = '/home4/megagirl/bin';
$error_log = $cwd . '/error_log';
$pdf_filename = $cwd . '/google.pdf';


// Run wkhtmltopdf
$descriptorspec = array(
    0 => array('pipe', 'r'), // stdin
    1 => array("file", $pdf_filename , "w"),  // stdout
    2 => array("file", $error_log, "a")  // stderr
 ); 
 $command = $cwd . "/wkhtmltopdf --disable-javascript - - ";
 //echo "<br>$command</br>";
 $process = proc_open($command, $descriptorspec, $pipes, $cwd);

if (is_resource($process)) {
  $status = proc_get_status($process); // This sends output to screen, not stdout
  // Send the HTML on stdin
  fwrite($pipes[0], $html);
  fclose($pipes[0]);

  $return_value = proc_close($process);

  // Output the results
  if ($return_value || $status['exitcode']) {
      error_log("PDF generation failed for respondent $respondent_id: rc = $return_value, status = " . serialize($status));
  } 

} // end if is_resource
else {
    error_log("PDF generation failed: Process not a resource");
}    

} 

```

(google.pdf file is generated but has no images)
## Output in error_log with --disable-javascript is below:
```
Loading pages (1/6)
[>                                                           ] 0%
[======>                                                     ] 10%
[================>                                           ] 28%
Warning: Failed to load file://ssl.gstatic.com/gb/images/b_8d5afc09.png (ignore)
Warning: Failed to load file:///images/icons/product/chrome-48.png (ignore)
Warning: Failed to load file:///logos/doodles/2015/first-day-of-fall-2015-northern-hemisphere-6003706315145216-hp.gif (ignore)
Warning: Failed to load file:///images/srpr/nav_logo80.png (ignore)
[============================================================] 100%
Counting pages (2/6)  
[============================================================] Object 1 of 1
Resolving links (4/6)  
[============================================================] Object 1 of 1
Loading headers and footers (5/6)  
Printing pages (6/6)
[>                                                           ] Preparing
[============================================================] Page 1 of 1
Done                                                                      

```

(Google.pdf file created with 0 bytes)
## Output in error_log without --disable-javascript (below):
```
Loading pages (1/6)
[>                                                           ] 0%
[======>                                                     ] 10%
```
![image](https://cloud.githubusercontent.com/assets/8229225/10055101/486e61ec-61e9-11e5-86d4-37ffe854f92c.png)

**Comment by bgadoury** [comment]
The missing images are almost certainly going to be specified in the Google page as URLs that start with a slash or a directory name. If I'm reading your PHP correctly, it looks like you're fetching the HTML then piping that to wkhtmltopdf as STDIN. This isn't going to work because wkhtmltopdf is going to treat all URLs as being local to your filesystem, which of course they are not.

If you really need to grab the HTML using PHP (I'm guessing because you need to inject your charts somehow?) then you'll have to tweak the HTML in memory to fix the URLs by prepending the "https://www.google.com" to them. This will indicate to wkhtmltopdf that they are remote resources rather than files on your filesystem.

**Comment by Tomsgu** [comment]
Closing as the answer was provided.
