### ISSUE TITLE
Upgrading from wkhtmltopdf 0.9.6 -> 0.12.2.1 & resulting pdf resolution

### ISSUE THREAD

**Issue by caleshious** [wkhtmltopdf/wkhtmltopdf#2599]
So we had been using wkhtmltopdf 0.9.6 for a long time, but were forced to upgrade to the latest stable cause we needed support for SSLv3 (images started disappearing from our pdfs).

While this upgrade solved the issue of disappearing images and caused some styling issues (as expected), it appears the images in the pdf and now of a lower resolution.

We are still calling wkhtmltopdf with the same options (nothing image specific):
--orientation
--page-size
--margin-top
--margin-bottom
--margin-left
--margin-right
--header-spacing
--footer-spacing

I'm aware there are some image related options available, and was wondering if perhaps some default values have changed or if anyone could shed some light on why upgrading to a newer version of wkhtmltopdf would cause the same image to now appear in the resulting pdf at a lower resolution.

Cheers

**Comment by alloylab** [comment]
What version? have you tried this on 0.12.5?

**Comment by alloylab** [comment]
We are closing this out since we haven't heard from you. If you are still having this issue please feel free to re-open it. Thanks.
