### ISSUE TITLE
Full size cover page creates an issue in the footer position for the remaining pages

### ISSUE THREAD

**Issue by niravpatel2008** [wkhtmltopdf/wkhtmltopdf#2600]
I am using wkhtmltopdf 0.12.2.1 (with patched qt) on ubuntu.

While adding full size cover page, it creates issue in footer position for all other remaining pages.
removing cover page works perfectly.

i have alternate solution, if i mentioned footer-html for all pages individually then it will works as expected but its not permanent solution as application will hit url & load header-html for each page.

Any kind of help would be appreciated.

CMD look likes : 

wkhtmltopdf --header-spacing 10 --header-html "http://www.myhost.com/test/header.html" --footer-html "http://www.myhost.com/test/footer.html" cover "http://www.myhost.com/test/index.html" "http://www.myhost.com/test/page1.html" "http://www.myhost.com/test/page2.html" "http://www.myhost.com/test/page3.html" "http://www.myhost.com/test/page4.html" "http://www.myhost.com/test/page5.html" "http://www.myhost.com/test/page6.html" "http://www.myhost.com/test/page7.html" "http://www.myhost.com/test/page8.html" "http://www.myhost.com/test/page9.html" test1.pdf

**Comment by krazyest** [comment]
I believe this is related to discussion at the at of https://github.com/wkhtmltopdf/wkhtmltopdf/issues/1676 and affects headers too.

**Comment by krazyest** [comment]
and https://github.com/wkhtmltopdf/wkhtmltopdf/issues/2282
