### ISSUE TITLE
wkhtmltoimage_syslog flading

### ISSUE THREAD

**Issue by martinceti** [wkhtmltopdf/wkhtmltopdf#2603]
program: wkhtmltoimage 
version: Linux(Debian Jessie) 64 bit
There is an error by calling: wkhtmltoimage http://google.com /var/test.jpg

/var/log/syslog is full with messages:
Loading kernel module for a network device with CAP_SYS_MODULE (deprecated).  Use CAP_NET_ADMIN and alias netdev- instead.
Thank you very much for fixing this issue.
  Martin

**Comment by raulp** [comment]
i have the same issue on centos7 using the latest static binaries
