### ISSUE TITLE
Garbled page

### ISSUE THREAD

**Issue by DiagonalArg** [wkhtmltopdf/wkhtmltopdf#2605]
wkhtmltopdf "https://theintercept.com/2015/09/25/gchq-radio-porn-spies-track-web-users-online-identities/" output.pdf

Errors in the fist two pages of the pdf.

**Comment by alloylab** [comment]
is this still an issue on 0.12.5?

**Comment by DiagonalArg** [comment]
Looks good.  Thanks.
