### ISSUE TITLE
viewportSize not reflected in API

### ISSUE THREAD

**Issue by bornste** [wkhtmltopdf/wkhtmltopdf#2609]
The setting `viewportSize` cannot be set by the API because it is missing in the `ReflectImpl<PdfGlobal>` struct.

**Comment by rdvojmoc** [comment]
Can we expect setting viewportSize to come back to API at some point?

**Comment by ashkulz** [comment]
@rdvojmoc: would be happy to receive a PR, it's a very small fix :smile:

**Comment by OskarStark** [comment]
@ashkulz as this this issue already has a merged PR (#3440) we can close is.

After closing this issue, the [Milestone for 0.12.5](https://github.com/wkhtmltopdf/wkhtmltopdf/milestone/8) is completed. A new release would be great 👍

**Comment by danger89** [comment]
YEA release 0.12.5!

**Comment by OskarStark** [comment]
can you please create a release?

**Comment by MrMitch** [comment]
@ashkulz Hi, thanks for your work on this project.
It seems that PR #3440 implements this, and it has been merged. This was the last issue for the 0.12.5 milestone, so do you know if there's anything more that needs to be contributed for a release ?
The 0.12.5 release is especially awaited because it solves #3241 which has be problematic on Linux and Mac for more than a year now.
How can we help ?

**Comment by OskarStark** [comment]
Can you guys please create a release? ping @wkhtmltopdf/contributors

**Comment by ashkulz** [comment]
Currently working on a reworked packaging system in the `wkhtmltopdf/packaging` repository, you can download preview builds [for linux](https://builds.wkhtmltopdf.org/0.12.5-dev/). For OS X and Windows, trying to automate the build using vagrant so a release can be created easily.

Planning to release a `-rc` by next weekend, and a release after a week .. so expect May 15 for the 0.12.5 release.

**Comment by ashkulz** [comment]
A release candidate [is available](https://wkhtmltopdf.org/downloads.html#release-candidate) which includes the fixes made in PR #3440 -- please test and report your findings before the final release.

**Comment by OskarStark** [comment]
hey @ashkulz thank you 👍 

could you make the RC available on github releases:
https://github.com/wkhtmltopdf/wkhtmltopdf/releases

**Comment by OskarStark** [comment]
ok thank you
