### ISSUE TITLE
Missing command options on the Windows (MSVC 2013) 64-bit flavor

### ISSUE THREAD

**Issue by alinmiron** [wkhtmltopdf/wkhtmltopdf#2612]
I tried to use the options defined in this documentation:
http://wkhtmltopdf.org/usage/wkhtmltopdf.txt like --page-size, --header-center 'test', --header-line and I get the following error: Unknown long argument 'option'. For example:
Unknown long argument --page-size
Using Windows 7 x64 and wkhtmltopdf 0.12.2.1 Windows (MSVC 2013) 64-bit.

**Comment by alloylab** [comment]
is this still an issue on 0.12.5?
