### ISSUE TITLE
Unknown long argument --disable-smart-width

### ISSUE THREAD

**Issue by kenorb** [wkhtmltopdf/wkhtmltopdf#2615]
I'm trying to use `--disable-smart-width` as below:

```
wkhtmltopdf --disable-smart-width --page-height 100m http://example.com/ example.pdf
```

but it's showing the error:

> Unknown long argument --disable-smart-width

I've seen this option used in here #2408 with the same version which I've (which is: 0.12.2.1 with patched qt) and also suggested to use it in [here](http://superuser.com/questions/958988/how-to-convert-html-into-endless-one-page-pdf-via-wkhtmltopdf#comment1350312_981082).

The same when tested with the recent dev version: v0.12.3-dev-8f03630 on OSX.

Any idea why this options is missing?

**Comment by alloylab** [comment]
is this still an issue on 0.12.5?

**Comment by gusbemacbe** [comment]
@alloylab 

I still am facing the problem. Here is the error:

```
Unknown long argument --page-height '56mm'
```
I am using the latest version of `wkhtmltopdf`. I was running `pandoc`:

```bash
pandoc -s -V margin-top=0mm -V margin-left=0mm -V margin-right=0mm -V margin-bottom=0mm --pdf-engine=wkhtmltopdf --pdf-engine-opt="--page-height '56mm'" -f markdown-raw_tex -t html5 --metadata title="Biografia" --css /assets/css/colours.css --css /assets/css/fonts.css --css /assets/css/global.css *.md -o combined.pdf --verbose
```
