### ISSUE TITLE
Support docx

### ISSUE THREAD

**Issue by ittayd** [wkhtmltopdf/wkhtmltopdf#2617]
PDF is great, but some users may want a docx document. Can this be done using the same framework?

**Comment by PhilterPaper** [comment]
A google search shows several HTML-to-docx converters out there already, so I'm not sure it would be worthwhile for anyone to write an entirely new backend for this product. Besides, it appears that WebKit may have been a poor choice as an HTML rendering engine, as it keeps breaking things on each update. Anyway, the source is there if anyone wants to take a shot at it...

**Comment by bgadoury** [comment]
@ittayd I'm working on a project that uses wkhtmltopdf to generate PDF, but I'm using PhantomJS (and a lot of supporting code and additional HTML) to generate a MHTML document that Word will accept as a .DOC file. I looked at implementing a true DOCX export, and it would require a fair amount of work. There's very little currently in wkhtmltopdf that could be used to generate a DOCX file, so I highly doubt anyone is going to build that into wkhtmltopdf.
