### ISSUE TITLE
Problems with Query Params in URL

### ISSUE THREAD

**Issue by LandonSchropp** [wkhtmltopdf/wkhtmltopdf#2619]
I'm having trouble with an anchor whose URL contains query parameters. Here's the offending HTML:

``` html
<a href="https://unravelingflexbox.com/?utm_source=Sample%20Book&amp;utm_medium=Broken%20Example&amp;utm_campaign=Broken%20Example" class="button">Purchase Unraveling Flexbox</a>
```

The link works fine in the browser, but it doesn't do anything when clicked in the PDF.

**Comment by alloylab** [comment]
is this still an issue on 0.12.5?
