### ISSUE TITLE
Can I pass html string arrays to wkhtmltopdf?

### ISSUE THREAD

**Issue by msyesyan** [wkhtmltopdf/wkhtmltopdf#2620]
@ashkulz Now we can pass file url arrays, or pass one page htmlString to wkhtmltopdf, I have a requirement to pass html strings to wkhtmltopdf to implement pagination, can you help me?

**Comment by alinmiron** [comment]
My solution to this problem was to create a script that would save the html string into a temp file and then pass the url of the temp file to the wkhtmltopdf.

**Comment by jesobreira** [comment]
I use PHP to do it. Take a look: https://github.com/jesobreira/themecli

**Comment by Tomsgu** [comment]
Closing as answers were provided.
