### ISSUE TITLE
libpng error: IDAT: CRC error

### ISSUE THREAD

**Issue by jaredvacanti** [wkhtmltopdf/wkhtmltopdf#2622]
When I run wkhtmltopdf and the html has `HTTPS` loading images shows `libpng error: IDAT: CRC error` with no other information. Can I enable verbose output, or does anyone know of this issue?

**Comment by ashkulz** [comment]
Please open a new issue in [wkhtmltopdf/packaging](https://github.com/wkhtmltopdf/packaging) if this is still relevant.
