### ISSUE TITLE
Old version via `apt-get`

### ISSUE THREAD

**Issue by shaneparsons** [wkhtmltopdf/wkhtmltopdf#2623]
I'm not sure whether or not you have control over this, as I'm not very familiar with APT, but the version that gets downloaded via `sudo apt-get install wkhtmltopdf` is `0.9.9-4`, which is causing me some serious issues.. particularly related to x-server.

Please fix this if you can.. if not, let me know and I'll stop wasting my time.

**Comment by alejandro-fiore** [comment]
Every software download via "apt-get", "yum" or something like this, is controlled by the Operating System Creator (Ubuntu, Debian, etc.).

**Comment by shaneparsons** [comment]
Ah okay, good to know
