### ISSUE TITLE
Hangs on 10% and does not generate PDF

### ISSUE THREAD

**Issue by jesobreira** [wkhtmltopdf/wkhtmltopdf#2628]
I've always used wkhtmltopdf to generate many documents here at my work, in applications coded by ourselves just for internal use. However, today, wkhtmltopdf just stopped working. Suddenly, with no changes.

Truly, it worked today. But I had to restart my computer (due to external reasons), and then I realized all the applications I made with wkhtmltopdf bundle just stopped working.

I took wkhtmltopdf.exe from one of the applications and realized that, whatever I try to convert to PDF (whether a webpage or a local HTML file), it always hangs on 10%. I tried downloading wkhtmltopdf.exe from the official webpage again, and I had the same problem with the newly downloaded exe.

Our applications runs wkhtmltopdf through [ShellExecute](https://msdn.microsoft.com/pt-br/library/windows/desktop/bb762153%28v=vs.85%29.aspx) and we never had problems (we use wkhtmltopdf in our applications for 1 to 2 years here). Some of our applications are developed using [AutoIt3](http://www.autoitscript.com) and [wkhtmltox-au3](https://github.com/jesobreira/wkhtmltox-au3), which is just a wrapper (class). All stopped working. But the problem also appears when I try to run it directly, just from the command line, as you can see in the image below.

All our machines are Windows 8 32 bits. It's too weird, since nothing was changed on the EXE and it started just after restarting the computers. And it stopped working on all machines, but each machine has its own installation (the applications does not run under a network share).

I tried:
- Cleaning %TEMP% folder
- Adding option --disable-javascript

But nothing works.

It does not look like a network problem, since we have no proxy (we're a small company, we just use a Wi-Fi router, just like you do in your house) and we can open anything on browsers.

BTW, wkhtmltoimage works well. without any problem.

![printscreen](http://s10.postimg.org/vk3xwcttl/wkbug.png)

**Comment by jesobreira** [comment]
Strangely, today everything "woke up" well (as well as the server, that never power off, and also showed that problem yesterday, seems to be working now). Guys, I'm scared...

**Comment by jesobreira** [comment]
Okay, today everything stopped working again. That's weird.

**Comment by chris-griffin** [comment]
I had a similar issue at work. It turned out to be that the folder I had wkhtmltopdf installed was 'locked' down and did not have permission to access the Internet. Since you are on windows one way to check if this is the same problem for you is to navigate to the folder using the file explorer, right click on the folder, select open command prompt here, and then try 'ping https://google.com' with no apostrophes. If it succeeds at least you know you don't have a network access error.

**Comment by jesobreira** [comment]
Hi, @chris-griffin ! Thanks for your response!

Today it's back working hahaha

On the occasion it stopped working, I tried copying and downloading wkhtmltopdf.exe to many places, like Desktop, Downloads folder and some subfolders. Nothing worked. Might my user folder be locked on these machines? We don't use network settings for Windows/users.

On the next opportunity, when it stops working again, I will take a look if it will work on the disk root, or from an external device.

**Comment by jesobreira** [comment]
It didn't work. It stopped working, so I tried running it on the disk roots (I have two partitions, but none worked) as well as an external HD (also did not work).

When I restarted the computer, it started working again...

**Comment by jesobreira** [comment]
It stopped working again (many times, as well as worked for many times). It looks like it's choosing when to work and when not to work. I already don't know what to do...

**Comment by matthewvukomanovic** [comment]
I'm getting this exact same issue on windows 10, where it had been working it's stopped working

**Comment by Tomsgu** [comment]
Is this still an issue in 0.12.5?

**Comment by matthewvukomanovic** [comment]
@jesobreira I will have to get back to you on that one since I'm also working on something different. From memory though this ended up being because we were installing our app in Program Files so of course when it tries to extract it's files it was not working for users or computer where they didn't have permission. Instead I changed it to using a folder in the LocalAppData and it worked fine after that.

**Comment by jesobreira** [comment]
I see... so perhaps it's a good idea to close this issue and, if someone faces this again, this issue gets reopened?

**Comment by Tomsgu** [comment]
Thanks for the feedback @jesobreira and @matthewvukomanovic. Please feel free to re-open the issue if you still face the same problem.

**Comment by Tooraj20** [comment]
Same issue here, It sopped working on the server and also my local pc (linux) but was working on flight mode :|  so i think it checks my company website domain because we were moving host and everything start working again when domain start working. Interesting .

**Comment by bweston92** [comment]
Getting this on Debian and MacOS sometimes it works and sometimes it stalls at 10%. No internet restrictions at all.

**Comment by MrMuMu** [comment]
I am getting this problem as well but with one difference, it works in the first run, but if I send the html again to convert to pdf, it hangs forever.

**Comment by bweston92** [comment]
Ended up just execing the wkhtmltopdf passing the HTML to it.

**Comment by fatfrog** [comment]
```
Rendered admin/documents/letter.html.erb within admin/layouts/letters (85.6ms)
Loading pages (1/6)
[======>                           ] 11%
```

**Comment by deathbyjer** [comment]
Just a note for future me and others who may be coming across this problem.

One possible reason ( as it was the reason for me ) is that something is preventing wkhtmltopdf from reading the original source material. For me, it was a WAF rule flagging my system (correctly) as a robot and blocking it from making the request. When I routed around the firewall, it worked fine.

**Comment by McGern** [comment]
@deathbyjer How did you get around the WAF rule? I'm wondering if I have the same issue, but don't have clue about how to diagnose it i.e. it starts to run, does the 10%, then just stops without any error.  Just trying a single example pointing to https://google.com (also tried some http sites I found), but it doesn't do anything. 0.12.3.2 with qt
