### ISSUE TITLE
Links with children elements not working

### ISSUE THREAD

**Issue by sieira** [wkhtmltopdf/wkhtmltopdf#2631]
This is a widget in a web-page that I want to convert to pdf:

![Contact-me](https://cloud.githubusercontent.com/assets/13233859/10526388/d7057910-738a-11e5-8a37-258acc16c81b.png)

The markup (jade) is this:

``` jade
            dt.nav-title Contactez-moi
            dd.nav-item
              a.media(href='mailto:myemailadress@spacebar.fr')
                .media-left.media-middle
                  .media-object.fa.fa-envelope-square.fa-2x
                .media-body
                  b e-mail
```

Which roughly translates to html (ignoring classes) as:

``` html
<dt>Contactez-moi</dt>
<dd>
  <a href="mailto:luis.sieira@spacebar.fr">
    <div>
      <div>
           fontawesome-icon
      </div>
    </div>
    <div>
        <b>e-mail</b>
    </div>
  </a>
</dd>
```

This will not work, the link will just not exist on the output. I can put the link on the e-mail b, but the effect is not the same, since it will not include the white-spaces between the envelope and the text, adding this extra `<a>` badly break my css anyway.

Should this be working? Ain't possible to make such a link in a PDF?

I'm using 
wkhtmltopdf 0.12.2.1 (with patched qt)

Under (my uname -a)
Linux domain 3.19.0-30-generic #34-Ubuntu SMP Fri Oct 2 22:08:41 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by alloylab** [comment]
is this still an issue on 0.12.5?
