### ISSUE TITLE
changelog.md doesn't have release notes of 0.12.2.4 

### ISSUE THREAD

**Issue by shirishag75** [wkhtmltopdf/wkhtmltopdf#2633]
Hi all, 

Changelog.md only has notes of v0.12.2.1 (2015-01-19) and then jumps directly to v0.12.3 .  While releases shows at least 3 releases in the interim. Even those changes should come in changelog.md (even if it makes the changelog a bit bigger. 

0.12.2.2 
0.12.2.3 and 
0.12.2.4  ( the latest entry )

https://github.com/wkhtmltopdf/wkhtmltopdf/blob/master/CHANGELOG.md

**Comment by ashkulz** [comment]
The only changes were the recompiled Windows binaries to use updated OpenSSL, which is documented on the releases page. Considering they're now obsolete, I'm going to close this issue.
