### ISSUE TITLE
Sharp memory spike while generating pdf

### ISSUE THREAD

**Issue by kaushik90** [wkhtmltopdf/wkhtmltopdf#2635]
wkhtmltopdf version: 0.12.2.1
Operating System: OS X Yosemite version 10.10.5

I have shared a html code snippet. While creating a pdf out of this file, wkhtmltopdf process shows sharp memory spike. What could be the possible reason behind this?

``` html
<style>
.outer {
  border-radius: 5px;
  border: 1px solid #000000;
  background-color: #FF0000;
}
.outer .inner {
  height: 100%; /* memory spike depends on height. 3gb for 100% and 600mb for 10% on my local system */
  background-color: #66CCFF;
}
</style>

<div class="outer">
   <div class="inner">test</div>
</div>
```

**Comment by alloylab** [comment]
is this still an issue on 0.12.5?
