### ISSUE TITLE
core dump if /proc missing

### ISSUE THREAD

**Issue by warpfork** [wkhtmltopdf/wkhtmltopdf#2638]
wkhtmltopng will core dump if used in an environment where `/proc` is not available (this often comes up when operating in a chroot, for example).

(I'm trying to run wkhtmltox in a restrictive security environment where we may not `mount -t proc proc /proc`.)

As discovered in #1513, adding "--disable-javascript" to flags dodges the issue, but I'd like to have my javascript and skip the core dumps too :)

**Comment by DamienMure** [comment]
Hello.
I'm facing the exact same problem. Is there any solutions/fixes better than mounting "/proc" into the chroot ?

Regards.

**Comment by ashkulz** [comment]
Unlikely to be ever supported.
