### ISSUE TITLE
Support for URIs like unix in cygwin

### ISSUE THREAD

**Issue by siht** [wkhtmltopdf/wkhtmltopdf#2640]
Before than anything thanks for your software.
I had a trouble with URI's.
I have an archive in cygwin path /tmp but when I tried to convert the file in this format file:///tmp/archive.html wkhtmltopdf was unable to reach that file because it searches in file://localhost/&lt;my_drive&gt;:/my/path/where/I/installed/cygwin/tmp and it casues troubles with anything in cygwin especially with django-wkhtmltopdf.

**Comment by alloylab** [comment]
is this still an issue on 0.12.5?
