### ISSUE TITLE
PDF generate very slow with bootstrap css version 3.3.5

### ISSUE THREAD

**Issue by dontfight** [wkhtmltopdf/wkhtmltopdf#2642]
CentOS 6.7
wkhtmltopdf 0.12.3-dev-79ff51e (with patched qt)
```$ wkhtmltopdf http://getbootstrap.com abc.pdf```

**Comment by Leprosy** [comment]
I'm having the same issue. I've trimmed the files (CSS is ~46KB, HTML is ~129KB) and the rendering takes 3 minutes, versus 2 seconds with an empty CSS.

Here are some details about the issue: https://github.com/wkhtmltopdf/wkhtmltopdf/issues/1994

**Comment by khan789** [comment]
I was having the same issue; but just figured out that what is causing the problem.
1. Remove all border-radius from the bootstrap.css (should increase 30x speed in printing)
also again 
2. Remove all rgb and rgba from the bootstrap.css should also slightly increase your speed in printing.

Thanks for #1994  for giving good description and helping me.
Cheers,
