### ISSUE TITLE
Table headers (thead) rendered alone (orphaned) on some pages

### ISSUE THREAD

**Issue by slickorange** [wkhtmltopdf/wkhtmltopdf#2643]
I use <thead> so that table headings repeat on every page when tables are split across multiple pages.

If there is enough space at the end of the page to render the <thead>, it gets rendered - even if there is not enough space to render the first row of the table. The result is that some pages have only a "orphaned" <thead> at the bottom of the page.

The <thead> gets rendered normally again on the next page followed by the remaining table rows.

I have tried using page-break-after: avoid on the <thead>, and experimented with page-break-before, page-break-inside etc... Nothing seems to work. 

Any ideas? I am really stuck and would greatly appreciate any help.

See example:

![footer](https://cloud.githubusercontent.com/assets/7785924/10714827/6da5c9e0-7b08-11e5-972e-7361a6e859eb.jpg)

**Comment by PhilterPaper** [comment]
Also reported in #2486 but the extra left and right borders to the bottom of the page seem to have been fixed since.
