### ISSUE TITLE
Width and height set to 0

### ISSUE THREAD

**Issue by cetra3** [wkhtmltopdf/wkhtmltopdf#2644]
Seems like a number of element variables should be set to correct dimensions and are set to 0:

https://github.com/wkhtmltopdf/wkhtmltopdf/issues/1940
https://github.com/wkhtmltopdf/wkhtmltopdf/issues/2419

This causes no end of issues with graphing libraries that rely on these values to be set.

We should at least allow a `virtual screen size` to be set, or at least use the default (800x600)

**Comment by alloylab** [comment]
is this still an issue on 0.12.5?

**Comment by HexCodeFFF** [comment]
Yeah it is
