### ISSUE TITLE
Password

### ISSUE THREAD

**Issue by PatrickSolms** [wkhtmltopdf/wkhtmltopdf#2646]
Great program! Could I please get a password function? So that a created pdf can only be opened with a password?

**Comment by nrhirani** [comment]
wkhtmltopdf does not support password protection, you need to do it in a second pass. i.e, convert html --> pdf using wkhtmltopdf and then use [qpdf](http://qpdf.sourceforge.net) or similar libraries to convert pdf --> password protected pdf.  If you are using [nodejs](http://nodejs.org/en) then there is a wrapper around it [node-qpdf](https://github.com/nrhirani/node-qpdf)

**Comment by sameerAhmad9291** [comment]
I found simple solution on stackoverflow using PDFSharp. Here is link
https://stackoverflow.com/questions/12383409/password-protecting-a-pdf-file
