### ISSUE TITLE
QFont::setPixelSize: Pixel size <= 0 (0) getting error with bootstrap class [hidden-xs class]

### ISSUE THREAD

**Issue by eperez01** [wkhtmltopdf/wkhtmltopdf#2653]
I've been getting a QFont::setPixelSize: Pixel size <= 0 (0) error on webpages build with bootstrap class. Don't show the logo image until to remove hyphen in class, in this --->  hidden(-)xs for working correctly. At last show 

Warning: Received createRequest signal on a disposed ResourceObject's NetworkAccessManager. This migth be an indication of an iframe taking to long to load.

<div class="container">
    <div class="hidden-xs hexagon"> 
        <div class="logo-brand"></div> 
    </div>
    <div class="hidden-xs navbar-header navbar-right"></div>
</div>

![2015-10-29 11_44_40-greenshot capture form](https://cloud.githubusercontent.com/assets/15384298/10827193/30abe168-7e33-11e5-9ba4-c06a597b104b.png)

![2015-10-29 11_44_40-greenshot capture form](https://cloud.githubusercontent.com/assets/15384298/10827160/095e3282-7e33-11e5-841b-e84e0978afb9.png)

My version is 0.12.2.1.

**Comment by alloylab** [comment]
is this still an issue on 0.12.5?
