### ISSUE TITLE
Wrong text selection and wrong wrapping

### ISSUE THREAD

**Issue by omcg33** [wkhtmltopdf/wkhtmltopdf#2655]
I am use  "knplabs/knp-snappy-bundle": "dev-master"   for symfony 2.7

I generate pdf by using 

```
$this->knp_snappy_pdf->generateFromHtml( $html,  $file_path, $options);
```

Then i open pdf in chrome and try selection text i see this

![1](https://cloud.githubusercontent.com/assets/3978952/10868673/2e72c59a-80a6-11e5-84a6-97801e4fa50f.jpg)

But if i use http://pdfcrowd.com/    and the same html i see this 

![2](https://cloud.githubusercontent.com/assets/3978952/10868709/cedbe3e4-80a7-11e5-89c1-5faa8df4966a.jpg)

My $options

```
 array(
                'images' => true,
                'no-pdf-compression' => true,
                'page-width' => '150mm',
                'page-height' => '180mm',
                'minimum-font-size' => '2',
                'dpi' => 300,
                'disable-smart-shrinking' => true,
                'zoom' => '0.6',
            )
```

**Comment by denya-vs** [comment]
I have the same зкщидфьу, someone knows a solution?

**Comment by omcg33** [comment]
I decided not to use this package. Later I will write name of new package

**Comment by denya-vs** [comment]
What  package you use?

**Comment by omcg33** [comment]
OOpps! I forgot about you. Sorry.

I use  "tfox/mpdf-port-bundle": "1.2.*"

**Comment by denya-vs** [comment]
Thanks, but mpdf ignoring javascript code and have limitation on rendering tags(

**Comment by omcg33** [comment]
In my case it was the best solution.

**Comment by SuperSeb92** [comment]
Also seeing this issue, tried using wkhtmltopdf both on my mac with the OSX download, and on ubuntu trusty built from source

**Comment by Tomsgu** [comment]
Closing as the issue misses important details to be able to reproduce it.
