### ISSUE TITLE
Header overlapping when cell is longer than page

### ISSUE THREAD

**Issue by fverbist** [wkhtmltopdf/wkhtmltopdf#2657]
Hi,
I consistently have an issue with the header overlaying the content after a page break if the cell is so long it overlaps 2 pages.
example html here: http://pastebin.com/z18UJSKc

I have this with 0.12.3-dev-79ff51e as well as 0.12.2.1
can you advice?

thanks

**Comment by jangor** [comment]
I guess this is also a duplicate of #1524.
