### ISSUE TITLE
Embedded fonts, cant have more than one variation

### ISSUE THREAD

**Issue by alastair-todd** [wkhtmltopdf/wkhtmltopdf#2658]
I attach a simple html page which uses the @font-face directive and embeds the binary string for the font, one for each variation: Signika @ 300 weight and Signika @ 400 weight (downloaded from font squirrel). (src: url(data:font/truetype;charset=utf-8;base64...)

The page displays correctly in chrome and FF. The page can be downloaded as a pdf from chrome's print dialogue and display perfectly. However when running through wkhtmlpdf, the @300 weight is ignored.

I have looked at chrome's version of the pdf and the tool's version to see the file's properties > fonts embedded, and there is a discrepancy:

1) Chrome says > Signika (Embedded Subset)
2) WKHtmlToPDF version says > SignikaRegular (Embedded Subset)

OK - so i cannot upload the necessary files...."Attaching documents requires write permission to this repository.  Choose Files Try again with a PNG, GIF, or JPG."

**Comment by suburbiaboy** [comment]
Take a look at https://github.com/wkhtmltopdf/wkhtmltopdf/issues/2435 that'll help you work around the issue.

**Comment by Tomsgu** [comment]
Closing in expense of #2435.
