### ISSUE TITLE
error on gem

### ISSUE THREAD

**Issue by l2** [wkhtmltopdf/wkhtmltopdf#2659]
Hi I am trying to compile from the git repository. I execute `sudo scripts/build.py setup-schroot-trusty` and I obtain the foolowing error:
>    ERROR:  While executing gem ... (OptionParser::InvalidOption)
>       invalid option: -N
>    gem install -V fpm -N
>   command failed: exit code 256

Do you know why I obtain this error?

I am working on Ubuntu 14.04

**Comment by l2** [comment]
You can close it. This issue was only due to not updating rb.

**Comment by hedii** [comment]
i have the same issue, even if I updated ruby
````
Welcome to Ubuntu 14.04.3 LTS (GNU/Linux 3.13.0-55-generic x86_64)

~$ ruby -v
ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-linux]

~$ cd wkhtmltopdf/
~/wkhtmltopdf$ sudo scripts/build.py setup-schroot-trusty
ERROR:  While executing gem ... (OptionParser::InvalidOption)
    invalid option: -N
gem install -V fpm -N
command failed: exit code 256
````

**Comment by emil-perhinschi** [comment]
same on Mint 17.2

worked around by running 

gem install -V fpm 

and then restarting the build

**Comment by ashkulz** [comment]
[`0.12.4`](http://wkhtmltopdf.org/downloads.html#stable) has been released, which should contain the fix for this issue. Please report back if it is not solved with the above version.
