### ISSUE TITLE
Text overlaping

### ISSUE THREAD

**Issue by vluzrmos** [wkhtmltopdf/wkhtmltopdf#2661]
When I convert HTML to PDF some text appears overlapped

HTML:
![image](https://cloud.githubusercontent.com/assets/450848/10921173/cf60a898-8252-11e5-837b-66fd8b138289.png)

PDF:
![image](https://cloud.githubusercontent.com/assets/450848/10921030/0d571336-8252-11e5-8f87-58aea3207240.png)

**Comment by alloylab** [comment]
is this still an issue on 0.12.5?
