### ISSUE TITLE
Is it possible to use wkhtmltopsd with smart-shriking and hyphenator.js?

### ISSUE THREAD

**Issue by demonking** [wkhtmltopdf/wkhtmltopdf#2662]
Like the headline is saying, is it possible to smart-shriking a pdf document and execute the 
Javascript Script hyphenator.js (https://github.com/mnater/hyphenator) ?

I need this for one project, but i have tried everything, but nothing worked.

--enable-smart-shrinking
--enable-javascript
--javascript-delay 2000
--run-script ./Hypenator.js

It's a big table which is very hard to format with css because of the dynamic content(text)

or is there an other solution?

**Comment by alloylab** [comment]
is this still an issue on 0.12.5?
