### ISSUE TITLE
Page break fails when there is table with more number of columns.

### ISSUE THREAD

**Issue by SRGajjala** [wkhtmltopdf/wkhtmltopdf#2664]
I have applied below css for page break 

```html
 <style type="text/css" media="screen,print">
    .break{
          display: block;
          clear: both;
          page-break-after: always;
    }
</style>
```

and included element div with css class .break 
when I applied with smart-shrinking-enabled, page-break  does not apply,next page shifts to previous pages.

**Comment by PhilterPaper** [comment]
Is this what you meant for the CSS?

    .break {
      display: block;
      clear: both;
      page-break-after: always;
    }

Please don't use Dreamweaver or other page markup to write posts (or even worse, edit code and CSS files with such HTML editors).

Now, when you use `<div class="break">`, are you saying that it does not force a page break right after the div? Always, or sometimes? Is that the behavior you want? Does it work in HTML, but fail in wkHTMLtoPDF? What version? When you say "next page shifts to previous pages", does that mean that you expected the next div or whatever to be on a new page, but it's failing to break before it (after *this* div with the break class)?

**Comment by Tomsgu** [comment]
Closing as there is no feedback.
