### ISSUE TITLE
CSS not honored in pdf output

### ISSUE THREAD

**Issue by ryan-gavurin** [wkhtmltopdf/wkhtmltopdf#2666]
Hi

I've been outputting a HTML page to PDF, it contains texts, images, tables and SVG's. It doesn't seem to render the CSS rules correctly, particularly with the SVG. I'll upload some image examples to illustrate this. Here is my call to create the PDF,

``` javascript
return new PartialViewAsPdf("_OutputReport", model)
            {
                FileName = model.Report.Title != null && !String.IsNullOrWhiteSpace(model.Report.Title) ? model.Report.Title + ".pdf" : "Untitled Report.pdf", 
                PageWidth = 210, 
                PageHeight = 297, 
                PageMargins = new Rotativa.Options.Margins(0, 0, 0, 0),
                CustomSwitches = "--image-quality 100 --javascript-delay 1000 --load-error-handling ignore --dpi 72 --disable-smart-shrinking --no-stop-slow-scripts --viewport-size 1920x1080 --enable-plugins --no-outline"
            };

```

Is this a know issue? Is there a way to debug the CSS? Am i missing a tag?

Can you see the discrepancies in the files, borders added on the svg legend where it is almost non-existent on the html, also table borders and font is much thicker.

![pdf1](https://cloud.githubusercontent.com/assets/5487160/11063609/cd069d20-87af-11e5-87bf-8f08b87a594b.png)
![pdf2](https://cloud.githubusercontent.com/assets/5487160/11063610/cd0982ec-87af-11e5-8407-ba70f2d6e5e5.png)
![html1](https://cloud.githubusercontent.com/assets/5487160/11063611/cd0d9a80-87af-11e5-81f9-de37cc969f30.png)
![html2](https://cloud.githubusercontent.com/assets/5487160/11063608/cd053174-87af-11e5-8784-dd4b4e2fdde6.png)

Thanks

**Comment by alloylab** [comment]
is this still an issue on 0.12.5?
