### ISSUE TITLE
Unable to render dhtmlx content

### ISSUE THREAD

**Issue by brian-schick** [wkhtmltopdf/wkhtmltopdf#2667]
I can't get wkhtmltopdf to render any content at all from the commercial dhtmlx Scheduler application. For example, the following sample page http://docs.dhtmlx.com/scheduler/samples/06_timeline/03_tree.html just results in a blank PDF. 

I've tried virtually every JavaScript and sizing option in wkhtmltopdf with no luck. I can confirm that the JavaScript is being correctly evaluated, but that nothing at all gets drawn to the PDF.

What can I do to resolve this?

**Comment by alloylab** [comment]
is this still an issue on 0.12.5?
