### ISSUE TITLE
Use wkhtmltopdf as a gem

### ISSUE THREAD

**Issue by nasht00** [wkhtmltopdf/wkhtmltopdf#2672]
I use bundler, which gets executed in a travis build.

I would love to simply be able to write `gem 'wkhtmltopdf'` in my Gemfile. I don't see any documentation on this anywhere.

I decided to try anyways, and it kinda worked except that it said `Installing wkhtmltopdf 0.1.2`, and running `bundle exec wkhtmltopdf --version` gave me `wkhtmltopdf 0.8.3 using wkhtmltopdf patched qt`.

None of those numbers seem to match the latest stable release.

I've also tried with `wkhtmltopdf-binary`, which produces: `Using wkhtmltopdf-binary 0.9.9.3`

**Comment by Swistaku** [comment]
I guess you are looking for https://github.com/mileszs/wicked_pdf

**Comment by nasht00** [comment]
It says it's a plugin for "Ruby on Rails". I'm not using Rails, just Ruby (A Jekyll plugin).

**Comment by stania1** [comment]
WickedPDF can be used on a non-Rails project as well. Check out the `pdf_from_*` (`pdf_from_string`, `pdf_from_html`, etc.) methods (some examples are provided [here](https://github.com/mileszs/wicked_pdf) in the "Super Advanced Usage" section.

**Comment by nasht00** [comment]
WickedPDF requires wkhtmltopdf. So it's the same problem.

**Comment by stania1** [comment]
The latest stable release for wkhtmltopdf is 0.12.2.1. If you want this version, you can use the gem [wkhtmltopdf-binary-edge](https://github.com/pallymore/wkhtmltopdf-binary-edge).

I don't think you can use wkhtmltopdf directly in your Ruby code however - got to use WickedPDF for that.
