### ISSUE TITLE
build fails

### ISSUE THREAD

**Issue by pepa65** [wkhtmltopdf/wkhtmltopdf#2673]
This worked (after doing "sudo gem install -V fpm" as the -N option in "gem install -V fpm -N" wasn't recognized):
sudo scripts/build.py setup-schroot-trusty

But this failed immediately:
scripts/build.py trusty-amd64

Output:
gcc (Ubuntu 4.8.4-2ubuntu1~14.04) 4.8.4
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

sh: 1: /home/pp/git/wkhtmltopdf/static-build/../qt/configure: not found
/home/pp/git/wkhtmltopdf/static-build/../qt/configure -opensource -confirm-license -fast -release -static -graphicssystem raster -webkit -exceptions -xmlpatterns -system-zlib -system-libpng -system-libjpeg -no-libmng -no-libtiff -no-accessibility -no-stl -no-qt3support -no-phonon -no-phonon-backend -no-opengl -no-declarative -no-script -no-scripttools -no-sql-ibase -no-sql-mysql -no-sql-odbc -no-sql-psql -no-sql-sqlite -no-sql-sqlite2 -no-mmx -no-3dnow -no-sse -no-sse2 -no-multimedia -nomake demos -nomake docs -nomake examples -nomake tools -nomake tests -nomake translations -silent -xrender -largefile -iconv -openssl -no-javascript-jit -no-rpath -no-dbus -no-nis -no-cups -no-pch -no-gtkstyle -no-nas-sound -no-sm -no-xshape -no-xinerama -no-xcursor -no-xfixes -no-xrandr -no-mitshm -no-xinput -no-xkb -no-glib -no-gstreamer -no-icu -no-openvg -no-xsync -no-audio-backend -no-sse3 -no-ssse3 -no-sse4.1 -no-sse4.2 -no-avx -no-neon --prefix=/home/pp/git/wkhtmltopdf/static-build/trusty-amd64/qt
command failed: exit code 32512
command inside chroot failed: exit code 256

**Comment by onlyone0001** [comment]
Same problem.

**Comment by ashkulz** [comment]
did you use `git clone --recursive`?

**Comment by onlyone0001** [comment]
Just downloaded master.zip

**Comment by ashkulz** [comment]
Instructions in `INSTALL.md` are very clear.

**Comment by jieter** [comment]
Although the docs are clear, this might be a nice place to display a kind error message rather than fail bluntly. Would you consider merging a PR adding such a warning?

**Comment by ashkulz** [comment]
Yep :+1:

**Comment by ashkulz** [comment]
[`0.12.4`](http://wkhtmltopdf.org/downloads.html#stable) has been released, which should contain the fix for this issue. Please report back if it is not solved with the above version.

**Comment by lmanuel-exa** [comment]
Hello,

The compile doesn't working for me. Can you help me ?
My configuration:
OS: Centos 7.4.1708

My commands:
mkdir /packages ; cd /packages
git clone https://github.com/wkhtmltopdf/wkhtmltopdf.git
git clone https://github.com/qt/qtbase.git
cd wkhtmltopdf
cp -r ../qtbase/* qt/
scripts/build.py setup-schroot-centos7
Result:

**Comment by lmanuel-exa** [comment]
Hello,

The compile doesn't working for me. Can you help me ?
My configuration:
OS: Centos 7.4.1708

My commands:
mkdir /packages ; cd /packages
git clone https://github.com/wkhtmltopdf/wkhtmltopdf.git
git clone https://github.com/qt/qtbase.git
cd wkhtmltopdf
cp -r ../qtbase/* qt/
scripts/build.py setup-schroot-centos7
Result:
Usage: scripts/build.py <target> [-clean] [-debug]

The supported targets are:
* linux-generic-amd64
* linux-generic-i386
* mingw-w64-cross-win32
* mingw-w64-cross-win64
* msvc2013-win32
* msvc2013-win64
* msvc2015-win32
* msvc2015-win64
* osx-carbon-i386
* osx-cocoa-x86-64
* posix-local
* setup-mingw-w64
* setup-schroot-generic
* source-tarball
* update-all-schroots

After I try thtis command:
scripts/build.py linux-generic-amd64
Result:
Traceback (most recent call last):
  File "scripts/build.py", line 1185, in <module>
    main()
  File "scripts/build.py", line 1181, in main
    globals()['check_%s' % BUILDERS[config]](final_config)
  File "scripts/build.py", line 938, in check_linux_generic
    chroot_shell(chroot_env, 'gcc --version')
  File "scripts/build.py", line 419, in chroot_shell
    distro  = get_chroot_list().get(name)
  File "scripts/build.py", line 613, in get_chroot_list
    for line in get_output('schroot', '--list').split('\n'):
AttributeError: 'NoneType' object has no attribute 'split'
