### ISSUE TITLE
dont show header in first page and last page

### ISSUE THREAD

**Issue by ehsandod** [wkhtmltopdf/wkhtmltopdf#2675]
i dont wanna show header and footer on first and last page 
how can i remove them?
plz help me

**Comment by yourpalal** [comment]
If you're using html headers/footers, you can achieve this fairly easily by checking the `page` parameter. Here is an example header that should work for you:

        <!DOCTYPE html>
        <html>
        <body class="page-header">
          <span>failed to render</span>
          <script>
              var x=document.location.search.substring(1).split('&');
              var vars = {};
              for(var i in x) {var z=x[i].split('=',2);vars[z[0]] = unescape(z[1]);}
              if (vars.page == vars.frompage || vars.page == vars.topage) {
                document.body.innerHTML = "";
              } else {
                document.body.innerHTML = "Page " + (vars.page || "");
                // uncomment the next line for debugging
                // document.body.innerHTML = JSON.stringify(vars);
              }
          </script>
        </body></html>

That's using `frompage` and `topage`vars, which I believe should be available. If that doesn't work, try uncommenting the appropriate line in the example above to see all available variables and their values.

If the header shows "failed to render", then the script has probably crashed. Good luck!

**Comment by Tomsgu** [comment]
Closing as the answer was provided.
