### ISSUE TITLE
Debug images in wkhtmltopdf

### ISSUE THREAD

**Issue by nasht00** [wkhtmltopdf/wkhtmltopdf#2676]
I am using PDFKit (https://github.com/pdfkit/pdfkit), which in turn uses wkhtmltopdf to generate PDF files from HTML.

The images in the PDF appear as a blank little square.

I am trying to play with the path in various places, but I would like to be able to debug what is happening. I want to see what path is wkhtmltopdf trying to load, so that at least I can adjust my fiddling accordingly, and not play blind.

**Comment by brendon** [comment]
It's likely that your paths are relative. Try using absolute paths including the protocol: `http://etc...`.

**Comment by nasht00** [comment]
My paths are like this `/path/to/image`. It does not include the protocol and hostname on purpose, as the same site is hosted on several servers (staging, local, prod, etc.).

Isn't there a way to specify where to look for the files? Like defining the root?

**Comment by PhilterPaper** [comment]
#2687 is a discussion of files not being found when using absolute paths (starting with /). Maybe you're having the same problem? Relative paths are known to work.

**Comment by nasht00** [comment]
That's me on the other issue as well ;)

No easy solution that I can see... I may need to abandon this project...

**Comment by PhilterPaper** [comment]
As I said on your other thread, a solution may be to preprocess the HTML file(s) to turn absolute paths either into relative paths, or into absolute paths to the filesystem root. Other than that, unless someone spies a flag or setting in wkhtmltopdf to add some path prefix to absolute paths, you may be out of luck. Maybe that would make a good enhancement to wkhtmltopdf?

**Comment by brendon** [comment]
How about the `<base>` tag? I haven't tested it but it could be a goer?

http://www.w3schools.com/tags/tag_base.asp

**Comment by PhilterPaper** [comment]
If your paths are *absolute* (start with a /), the `<base>` tag should have no effect. It is supposed to be only for *relative* paths.

**Comment by Swistaku** [comment]
@nasht00 use wicked_pdf gem for this, it provides helper methods like `wicked_pdf_image_tag` that generates full paths to your assets

**Comment by brendon** [comment]
@Swistaku, it does, but I've found the helpers are a bit buggy with newer versions of Rails 4. It's definitely best to ensure all your assets (including those referenced within stylesheets) are getting proper paths appended.

**Comment by nasht00** [comment]
My workaround was to generate a full copy of my site with a complete file path in each images. Not ideal, but it got the job done.

**Comment by Tomsgu** [comment]
Closing in expense of #2687.
