### ISSUE TITLE
Ubuntu 12.04.5 - QXcbConnection: Could not connect to display

### ISSUE THREAD

**Issue by dsketch21** [wkhtmltopdf/wkhtmltopdf#2677]
I've installed the 64bit deb file onto my Ubuntu server with the following command:

sudo dpkg -i wkhtmltox-0.13.0-alpha-7b36694_linux-precise-amd64.deb

I then install the dependencies with :

sudo apt-get -f install

Then when I run a test to generate a pdf from a blank html file with just a single line of text I get this error:

Command: wkhtmltoimage index.html test.jpg

Output: 
QXcbConnection: Could not connect to display 
Aborted

Do I need to install another piece of software or configure something specific? Please advise.

**Comment by dsketch21** [comment]
Resolution posted here:

https://github.com/wkhtmltopdf/wkhtmltopdf/issues/2037

**Comment by LaGhyoute** [comment]
Is Debian still not supported ? Because xvfb takes seconds to render image.
