### ISSUE TITLE
OS X install displays error re default connection to Window Server

### ISSUE THREAD

**Issue by hwitten** [wkhtmltopdf/wkhtmltopdf#2681]
_RegisterApplication(), FAILED TO establish the default connection to the Window Server, _CGSDefaultConnectiuon() is NULL.

User that installed does not have a problem but another user in same group displays this message. Operation seems ok. PDF is created.
I assume it's a permission problem, but where?

![2015-11-20_18-29-55](https://cloud.githubusercontent.com/assets/5926239/11316172/ce3ca556-8fb4-11e5-96e5-4114694cd353.png)

**Comment by ashkulz** [comment]
Please reopen if this is still occurring with the latest releases.
