### ISSUE TITLE
segmentation fault

### ISSUE THREAD

**Issue by karlfr** [wkhtmltopdf/wkhtmltopdf#2682]
I have got some segmentation faults using wkhtmltopdf version 0.12.2.1 binary for CentOS 7 but it was not reproducible. any ideas?
best, Karl Frischengruber

**Comment by Paulsky** [comment]
I have the same problem on CentOS 6. The only fix for me is to disable Javascript with the --disable-javascript parameter or -n parameter. Unfortunately, I need to use Javascript.

**Comment by Tomsgu** [comment]
Closing as the issue misses important details to be able to reproduce the issue. The used version is also quite old.
