### ISSUE TITLE
woff font not supported in wkhtmltopdf

### ISSUE THREAD

**Issue by ghost** [wkhtmltopdf/wkhtmltopdf#2686]
while converting html to pdf using wkhtmltopdf source with qtwebkit 5.5.0 woff font not supported it shows qwarning " WOFF support requires QtWebKit to be built with zlib support." i hvae tried -system-zlib with my configure command but woff not yet supported kindly share your ideas

**Comment by premjis** [comment]
hi all

i got solution for WOFF font not supported in qtwebkit 5.5.0 .add -L C:\zlib128\lib -I C:\zlib128\include -system-zlib with your configure command and make sure using fresh qt source .becoz if u r using already build source zlib support not updated.
