### ISSUE TITLE
Text overlapping while converting html to pdf

### ISSUE THREAD

**Issue by ghost** [wkhtmltopdf/wkhtmltopdf#2688]
I have try to convert html to pdf using wkhtmltopdf. In result output document texts are overlapped and some white spaces are added in some places.. 
I have attached sample for text overlapping and white space pdf document.
[flipkart-textoverlap-whitespace.pdf](https://github.com/wkhtmltopdf/wkhtmltopdf/files/45460/flipkart-textoverlap-whitespace.pdf) please see textoverlap by zooming the content. please see white spaces at last page by zooming the content.
I have use wkhtmltopdf 12.2.4

**Comment by viswa18** [comment]
Any update on this??

**Comment by alloylab** [comment]
is this still an issue on 0.12.5?
