### ISSUE TITLE
Getting wkhtmltopdf to run on shared hosting

### ISSUE THREAD

**Issue by marvoh** [wkhtmltopdf/wkhtmltopdf#2691]
My application is deployed on a shared hosting without ssh or shell access. Is there any way I can get this to work?

I developed my app on a windows box for quite some time didn't think far ahead as into deployment environment being a problem.

**Comment by PhilterPaper** [comment]
Is the question whether you can *install* wkhtmltopdf on your server, or how to *run* it once installed? Note that many shared-server hosts may not permit such tools to be installed, for fear they will bog down the server and inconvenience other customers, or be a security risk. You may want to consider running the HTML-to-PDF conversion offline on your PC, and uploading the PDF(s). I'm trying to imagine what you might be doing on your site that requires the conversion to be done on the server, that will also meet with approval from your host.

If you don't have SSH or shell access, a fallback may be to run a one-time "cron" job. This gives you a command-line run of the tool (or its installation). Just remember to remove the cron job once it has run, or it will be run repeatedly!

**Comment by marvoh** [comment]
Thanks for your response, first part went ok:
wget https://wkhtmltopdf.googlecode.com/files/wkhtmltopdf-0.10.0_rc2-static-amd64.tar.bz2

when I run this to install
tar -xvzf wkhtmltopdf-0.10.0_rc2-static-amd64.tar.bz2 -C /opt

i get the following error
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now

**Comment by marvoh** [comment]
solved it by running:

tar -xjvf wkhtmltopdf-0.10.0_rc2-static-amd64.tar.bz2 -C /opt

Thanks, I am now about to test

**Comment by PhilterPaper** [comment]
Be prepared to encounter lots of missing tools (such as compilers) on a shared server. Most hosts don't like their customers running such things on their webservers, and will remove lots of common tools. 

.BZ2 is apparently a different "zip" format from GZIP. You were lucky to find a flag in "tar" that handles it. The alternative would have been to find some utility to unzip .BZ2 on your PC, and either upload the files individually or repack with gzip before uploading.

**Comment by JeremyNikolic** [comment]
I know this is old but I'm facing the challenge of getting wkhtmltopdf to work on an OVH shared hosting.
Provider confirmed that it would work with a dependencyless (static ?) version of the librar, built for Debian jessie x86.. I have ssh access on the server.

As per now I haven't been able to make it work, as the downloadables seem to not include some libraries (e.g libXrender).

In case you got it working, could you share your knowledge on the matter ?

**Comment by marvoh** [comment]
Hi,


Sorry to hear about your predicament. I managed to get it to run but then later moved to a shared server. Let me see if I can remember how I got it to work then I'll reach out in the morning.


But I think I downloaded the files through windows then pushed to server via ftp.




Get Outlook for Android






On Tue, Sep 20, 2016 at 11:37 AM +0300, "Jeremy Nikolic" <notifications@github.com> wrote:












I know this is old but I'm facing the challenge of getting wkhtmltopdf to work on an OVH shared hosting.

Provider confirmed that it would work with a dependencyless (static ?) version of the librar, built for Debian jessie x86.. I have ssh access on the server.



As per now I haven't been able to make it work, as the downloadables seem to not include some libraries (e.g libXrender).



In case you got it working, could you share your knowledge on the matter ?

**Comment by JeremyNikolic** [comment]
@marvoh Thanks man! At the moment I've built a vm matching the server setup and trying to push the missing libraries to the server, still not working 100% though

**Comment by kenprogrammer** [comment]
Shared hosting no ssh or shell access?

Here is how i did it;

1. Visit https://wkhtmltopdf.org/downloads.html and download the appropriate stable release for Linux. For my case I chose 32-bit
which is wkhtmltox-0.12.4_linux-generic-i386.tar.xz
2. Unzip to a folder on your local drive.
3. Upload the folder to public_html (or whichever location fits your need) using an FTP program just like any other file(s)
4. Change the binary paths in snappy.php file to point the appropriate files in the folder you just uploaded.
Bingo! there you have it. You should be able to generate PDF files.

**Comment by antoniogaldo** [comment]
hi kenprogrammer , 
I uploaded the wkhtmltox folder on the same level as public_html by ftp and changed the binary to home / usr / wkhtmltox / bin / wkhtmlpdf but it does not work

**Comment by kenprogrammer** [comment]
@antoniogaldo
Check whether you've downloaded for right architecture e.g 32bit. Also make you've included snappy dependencies in your project.

**Comment by antoniogaldo** [comment]
hi kenprogrammer ,
I try another 32bit but i have 500 error server .
I put wkhtmtox in the public_html and in the config of symfony (then stay out public_html) is 
knp_snappy:
    pdf:
        enabled:    true
        binary:     /public_html/wkhtmltox/bin/wkhtmltopdf
but not work

**Comment by antoniogaldo** [comment]
hi @kenprogrammer ,
I try another 32bit but i have 500 error server .
I put wkhtmtox in the public_html and in the config of symfony (then stay out public_html) is 
knp_snappy:
    pdf:
        enabled:    true
        binary:     /public_html/wkhtmltox/bin/wkhtmltopdf
but not work

**Comment by adriencohen** [comment]
Just to add to @kenprogrammer's anwser, don't forget to switch your FTP client to transfer in Binary Mode or the binary file might not work.

**Comment by Ajahuanex** [comment]
I was running wkhtmltopdf on my Windows local machine which was working fine. But now I hosted my website on aws(CentOS server) and tried to run, here it's not creating the .pdf file using wkhtmltppdf.

So Does it make a difference in installing wkhtmltopdf on windows and aws (linux I suppose) with same windows flavored version.

**Comment by kelvinthiongo** [comment]
@ajahuanex I hope this will get to you . There is no difference at all if you using simmilar versions of wkhtmltox.
Nevertheless, I have a solution to this to all those who can access composer or such a software on the shared host. Those without composer, continue reading - I gat your back!
Run composer require h4cc/wkhtmltopdf-i386 "0.12.4" and that way you will get the binaries.
Open bash to the directory of this file(usually "/vendor/h4cc/wkhtmltopdf-amd64/bin") and run ./wkhtmltopdf-amd64 --version.

If you cannot use composer, download it from here(https://github.com/kelvinthiongo/wkhtmltopdf) and upload it to your server in the directory of your choice. Then run ./wkhtmltopdf-amd64 while you on that directory. 

You done!

**Comment by ashkulz** [comment]
If you can manage to match the versions installed with your shared hosting, that's great! Otherwise, that's not a supported scenario -- especially when it's so easy to get a VPS these days 👍
