### ISSUE TITLE
Different Margin per Page

### ISSUE THREAD

**Issue by adisembiring** [wkhtmltopdf/wkhtmltopdf#2692]
I have long HTML content. I need to make first page have no margin and the second page to the rest have margin `14`. is it possible in wkhtmltopdf ?

**Comment by PhilterPaper** [comment]
I'm not aware of any way to change margins "on the fly", but maybe someone else knows if there is.

You might be better off taking a look at your HTML and seeing if you can rearrange it or do something to use normal margins. If nothing else, the PDF document is going to look strange (and sloppy) with content running over the right margin. Is there anything you can do about it? Are you talking about "words" so long that they exceed the length of a line? What happens during display in a browser (as HTML)? I'm not sure that soft hyphens (`&SHY;`) work in wkHTMLtoPDF (they didn't used to); same for `&thinsp;` and other narrow spaces that a browser will break a line on.

If this is confined to the very first page, can you make that your "cover" page, with its own margins?

**Comment by RonB** [comment]
+1

**Comment by ajtis** [comment]
+1

**Comment by inakrin** [comment]
+1

**Comment by ajsjunior** [comment]
+1

**Comment by sajjadrad** [comment]
+1

**Comment by cristian100** [comment]
+1

**Comment by katesowles** [comment]
+1

**Comment by ajtis** [comment]
Some related work done on : https://github.com/wkhtmltopdf/wkhtmltopdf/issues/3635

**Comment by Tomsgu** [comment]
Closing in expense of #3635 as there is some discussion and PR (incomplete) attached.
