### ISSUE TITLE
wkhtmltoimage_destroy_global_settings() is not available.

### ISSUE THREAD

**Issue by richng01** [wkhtmltopdf/wkhtmltopdf#2694]
Hi all,

For convert to pdf, there is a wkhtmltopdf_destroy_global_settings() to destroy global setting.
For convert to image, there is no function to destroy global setting. It caused my application to have memory leak. 

Thanks.

**Comment by carsonreinke** [comment]
Oddly handled here: https://github.com/wkhtmltopdf/wkhtmltopdf/blob/master/src/lib/image_c_bindings.cc#L83.

All the documentation states that providing settings to converter transfers ownership.  Even the `wkhtmltopdf_destroy_global_settings` states "Normally one would not need to call this".
