### ISSUE TITLE
Server security changes killed pdf generation

### ISSUE THREAD

**Issue by Mark-Nugent** [wkhtmltopdf/wkhtmltopdf#2697]
After being hacked, our server people have hardened up everything. One of the changes seems to limit the number of special characters allowed in a query string.
Our PDFs are made up of a body, header and footer.
As I understand it, wkhtmltopdf uses a GET request to get the footer html file. It seems that this request contains much information related to the html body. 
The server security system thinks there are way too many special characters so must be a hack attempt. The end result is a pdf brochure with a 403 forbidden message in the footer.
Is all the information in the query string necessary? Is there some way I could switch off some of it so it does not trigger the security response.

**Comment by alloylab** [comment]
what os?

**Comment by Tomsgu** [comment]
Closing as there is no additional information provided. E.g. how the get request from wkhtnltopdf looks like. Please feel free to comment if you have more information about the issue.
