### ISSUE TITLE
QPen:setWidth neg value

### ISSUE THREAD

**Issue by SisMap** [wkhtmltopdf/wkhtmltopdf#2698]
Hello
I'm new to wkhtmlto pdf. I'd like to store https://pas.titlis.ch/titlis/sismap/1/html/winter/de/?showaccordion=0&wegweiser=0 aus an image.
I use 
wkhtmltoimage.exe --javascript-delay 2000 https://pas.titlis.ch/titlis/sismap
/1/html/winter/de/?showaccordion=0 sisag.jpg
And i got plenty of errors like: 
QPen::setWidthF: Setting a pen width with a negative value is not defined
I wonder because I never use negative values, but we use raphael.js to display some svg values.
Has anyone excperience in this case?
Thanks

**Comment by alloylab** [comment]
is this still an issue on 0.12.5?
