### ISSUE TITLE
convert part of html to pdf

### ISSUE THREAD

**Issue by sharikaitahari** [wkhtmltopdf/wkhtmltopdf#2703]
Currently I am pulling the data from weather app, converting to pdf and sending email to user with converted pdf as an attachment. I have used some of the wkhtmltopdf arguments. Sometimes it loads fine and sometimes not. Someday, the attachment will be blank. Now, I want to send only the first page of converted pdf to user. Is that possible?

**Comment by PhilterPaper** [comment]
Are you asking for several different things here? Failure to convert HTML to a PDF is one issue. Have you looked for a return code to tell you what happened? To send just the first page of the PDF, you could use a tool (such as PDFtk) to extract just page 1 into a new file. I don't know if there's anything in wkHTMLtoPDF itself to select a range of pages, although that might be a useful tool, as conversion could often stop after the last page (what to do about forward references? how to number the pages?).

**Comment by sharikaitahari** [comment]
Thank you. Yes, i am asking for two different things:
1. intermittent failure while converting html to pdf
2. Send only first page to the user

For 1, If i run it locally, it runs fine. So, hard to trubleshoot. For 2, need to think about it.

**Comment by Tomsgu** [comment]
Closing as 1. Issue cannot be reproduced. And 2. Is out of scope of this library. Use another tool after pdf generation as @PhilterPaper suggests.
