### ISSUE TITLE
wrong zoom result with percent dimensions

### ISSUE THREAD

**Issue by GregoireMidi** [wkhtmltopdf/wkhtmltopdf#2705]
It seems that when a zoom ratio is applied (--zoom), all html dimensions are multiplied by this ratio (which is right), even dimensions in percent, which is wrong. 
For example, for a ratio of 0.5, everything happens as if a div with the style attribute : style="width:100%" would see its attribute become : style="width:50%"

**Comment by alloylab** [comment]
is this still an issue on 0.12.5?
