### ISSUE TITLE
Error from sRGB profile on Fedora 21

### ISSUE THREAD

**Issue by bnvk** [wkhtmltopdf/wkhtmltopdf#2707]
The following error bubbles up when trying to use wkhtmltopdf accessed via the NodeJS module. The stack trace points to:

```
Error: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
```

I am using the following:

```
Fedora 21
wkhtmltopdf 0.12.2.1
```

**Comment by ashkulz** [comment]
Please open a new issue in [wkhtmltopdf/packaging](https://github.com/wkhtmltopdf/packaging) if this is still relevant.
