### ISSUE TITLE
Some sites don't work

### ISSUE THREAD

**Issue by infestdead** [wkhtmltopdf/wkhtmltopdf#2708]
I run 
wkhtmltoimage --width 1920 --javascript-delay 2000 $site asd1.png

(wkhtmltoimage:9103): GLib-GObject-WARNING *_: cannot register existing type 'GdkDisplayManager'
(wkhtmltoimage:9103): GLib-CRITICAL *_: g_once_init_leave: assertion 'result != 0' failed
(wkhtmltoimage:9103): GLib-GObject-CRITICAL **: g_object_new: assertion 'G_TYPE_IS_OBJECT (object_type)' failed

and wkhtmltoimage hands for hour if need be.

Most sites work as expected, but for some - this happens.

Version:
wkhtmltoimage 0.12.3-dev
Fedora 23

**Comment by alloylab** [comment]
is this still an issue on 0.12.5?
