### ISSUE TITLE
Weird spacing issue - details provided

### ISSUE THREAD

**Issue by Blastnsmash** [wkhtmltopdf/wkhtmltopdf#2709]
What is causing the "Contact Us" text to get pushed down (see pdf at bottom)? Any help?

Here is the html page:

http://office.condoresorts.com/Printing/SuiteInfoPage.html?JSON=%7B%22CondoNum%22%3A%222194%20Bulding%2015%20at%20Pillars%22%2C%22CheckIn%22%3A%22Arrival%20Date%3A%20Wednesday%2C%20December%209%2C%202015%22%2C%22CheckOut%22%3A%22Departure%20Date%3A%20Wednesday%2C%20December%209%2C%202015%22%2C%22Phone%22%3A%22%20480-525-4790%22%2C%22NetworkName%22%3A%22%20Meridian%22%2C%22NetworkPW%22%3A%22holeinone%22%2C%22ParkingList%22%3A%5B%22Parking%3A%20Garage%22%2C%22The%20number%20to%20your%20parking%20space%20is%20printed%20on%20the%20awning%20above%20the%20space.%20You%20may%20park%20in%20any%20uncovered%20parking%20spot%20throughout%20the%20complex.%20DO%20NOT%20park%20in%20any%20covered%20spot%2C%20other%20than%20the%20one%20assigned%20to%20your%20suite%2C%20or%20your%20car%20may%20be%20towed%20and%20your%20account%20charged%20in%20excess%20of%20%24100.00.%22%5D%2C%22AccessList%22%3A%5B%222%20(two)%20keys%20to%20the%20condo%22%2C%221%20(one)%20key%20to%20the%20pool%20and%20fitness%20center%22%2C%221%20(one)%20garage%20remote%22%5D%7D

Here are the parameters:
{ "-O portrait", "--zoom 1.0", "--margin-bottom 27", "--margin-left 0", "--margin-right 0", "--margin-top 15", "--load-error-handling ignore" }

Here is the output pdf:

http://office.condoresorts.com/PDFPrinting/4a9f3145-aa69-4f46-8249-5b91555dc61e/2194_20151209104447650/SuiteInfo_PlacesNearCondo.pdf

Here is the version being used:
0.12.2.4 (with patched qt)

**Comment by alloylab** [comment]
is this still an issue on 0.12.5?
