### ISSUE TITLE
 Crashes while generating pdfs a certain page on a client website (while most work perfectly)

### ISSUE THREAD

**Issue by badrange** [wkhtmltopdf/wkhtmltopdf#2710]
We are using wkhtmltopdf 0.12.2.1 (with patched qt) on a CentOS server to generate PDF versions of product specifications on a customer website. 

For a certain product, wkhtmltopdf segfaults and generates a corrupt pdf. I am attaching the html code that segfaults, the command we use is: 

```
wkhtmltopdf  --footer-html print-footer.html crashes.html crash.pdf
```

[testcase.tar.gz](https://github.com/wkhtmltopdf/wkhtmltopdf/files/57878/testcase.tar.gz)
[crash.pdf](https://github.com/wkhtmltopdf/wkhtmltopdf/files/57873/crash.pdf)

**Comment by alloylab** [comment]
is this still an issue on 0.12.5?

**Comment by badrange** [comment]
Thank you for getting back. I only have 0.2.14 available here: I ran the test above and I got a pdf. Some of the javascript and css files are not available any more, so who knows. Let's keep this closed.
