### ISSUE TITLE
Problem loading page with port 6000.

### ISSUE THREAD

**Issue by pwasiewicz** [wkhtmltopdf/wkhtmltopdf#2712]
I've tried to convert page of url: http://localhost:6000
An wkhtmltopdf report an error about loading page. 

When added additional port to website (5999, so the same website was available under both 5999 and 6000 ports) converting http://localhost:5999 to pdf worked without any problems.

Looks like port 6000 is handled in a special way in code. (web server doesn't detect any requests when converting http://localhost:6000, so why wkhtmlpdf says that connection fails).

Commands used:
- wkhtmltopdf.exe "http://localhost:6000" out.pdf 
- wkhtmltopdf.exe "http://localhost:5999" out.pdf 

Server:
IIS 8.0, Windows 10 x64
Website: MVC 5.0, .NET 4.5.2
Newest version of wkhtmltopdf.

**Comment by alloylab** [comment]
is this still an issue on 0.12.5?
