### ISSUE TITLE
Problem while building qt-wkhtmltopdf

### ISSUE THREAD

**Issue by mstrd308** [wkhtmltopdf/wkhtmltopdf#2715]
I get the following error message while building qt-wkhtmltopdf.
Does anybody know what's the cause?

g++ -c -pipe -O2 -D_REENTRANT -Wall -W -DGL_SUPPORTED -DQT_NO_CAST_FROM_ASCII -DQT_NO_CAST_TO_ASCII -DQT_DECLARATIVE_DEBUG -DQT_NO_DEBUG -DQT_DECLARATIVE_LIB -DQT_SCRIPT_LIB -DQT_SQL_LIB -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_HAVE_MMX -DQT_HAVE_3DNOW -DQT_HAVE_SSE -DQT_HAVE_MMXEXT -DQT_HAVE_SSE2 -DQT_HAVE_SSE3 -DQT_HAVE_SSSE3 -DQT_HAVE_SSE4_1 -DQT_HAVE_SSE4_2 -DQT_HAVE_AVX -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -DQT_SHARED -I../../mkspecs/linux-g++ -I. -I../../include/QtCore -I../../include/QtNetwork -I../../include/QtGui -I../../include/QtOpenGL -I../../include/QtSql -I../../include/QtScript -I../../include/QtDeclarative -I../../include -I. -I../../include/QtDeclarative -I../../src/declarative/util -I../../src/declarative/graphicsitems -I.uic/release-shared -I/usr/X11R6/include -I.moc/release-shared -o .obj/release-shared/loggerwidget.o loggerwidget.cpp
In file included from ../../include/QtCore/qstring.h:1:0,
                 from ../../include/QtCore/../../src/corelib/kernel/qobject.h:48,
                 from ../../include/QtCore/qobject.h:1,
                 from ../../include/QtGui/../../src/gui/kernel/qevent.h:46,
                 from ../../include/QtGui/qevent.h:1,
                 from ../../include/QtGui/QMouseEvent:1,
                 from ./qdeclarativetester.h:46,
                 from qdeclarativetester.cpp:42:
../../include/QtCore/../../src/corelib/tools/qstring.h:597:5: error: âQString::QString(const char_)â is private
     QString(const char *ch);
     ^
In file included from ../../include/QtGui/qpainter.h:1:0,
                 from ../../include/QtGui/../../src/gui/graphicsview/qgraphicsview.h:46,
                 from ../../include/QtGui/qgraphicsview.h:1,
                 from ../../include/QtDeclarative/../../src/declarative/util/qdeclarativeview.h:48,
                 from ../../include/QtDeclarative/qdeclarativeview.h:1,
                 from qdeclarativetester.cpp:45:
../../include/QtGui/../../src/gui/painting/qpainter.h:458:60: error: within this context
     void addTextField(const QRectF &r, const QString &text="", const QString &name="", bool multiLine=false, bool password=false, bool readOnly=false, int maxLength=-1);
                                                            ^
In file included from ../../include/QtCore/qstring.h:1:0,
                 from ../../include/QtCore/../../src/corelib/kernel/qobject.h:48,
                 from ../../include/QtCore/qobject.h:1,
                 from ../../include/QtGui/../../src/gui/kernel/qevent.h:46,
                 from ../../include/QtGui/qevent.h:1,
                 from ../../include/QtGui/QMouseEvent:1,
                 from ./qdeclarativetester.h:46,
                 from qdeclarativetester.cpp:42:
../../include/QtCore/../../src/corelib/tools/qstring.h:597:5: error: âQString::QString(const char_)â is private
     QString(const char _ch);
     ^
In file included from ../../include/QtGui/qpainter.h:1:0,
                 from ../../include/QtGui/../../src/gui/graphicsview/qgraphicsview.h:46,
                 from ../../include/QtGui/qgraphicsview.h:1,
                 from ../../include/QtDeclarative/../../src/declarative/util/qdeclarativeview.h:48,
                 from ../../include/QtDeclarative/qdeclarativeview.h:1,
                 from qdeclarativetester.cpp:45:
../../include/QtGui/../../src/gui/painting/qpainter.h:458:84: error: within this context
     void addTextField(const QRectF &r, const QString &text="", const QString &name="", bool multiLine=false, bool password=false, bool readOnly=false, int maxLength=-1);
                                                                                    ^
In file included from ../../include/QtCore/qstring.h:1:0,
                 from ../../include/QtCore/../../src/corelib/kernel/qobject.h:48,
                 from ../../include/QtCore/qobject.h:1,
                 from ../../include/QtGui/../../src/gui/kernel/qevent.h:46,
                 from ../../include/QtGui/qevent.h:1,
                 from ../../include/QtGui/QMouseEvent:1,
                 from ./qdeclarativetester.h:46,
                 from qdeclarativetester.cpp:42:
../../include/QtCore/../../src/corelib/tools/qstring.h:597:5: error: âQString::QString(const char_)â is private
     QString(const char _ch);
     ^
In file included from ../../include/QtGui/qpainter.h:1:0,
                 from ../../include/QtGui/../../src/gui/graphicsview/qgraphicsview.h:46,
                 from ../../include/QtGui/qgraphicsview.h:1,
                 from ../../include/QtDeclarative/../../src/declarative/util/qdeclarativeview.h:48,
                 from ../../include/QtDeclarative/qdeclarativeview.h:1,
                 from qdeclarativetester.cpp:45:
../../include/QtGui/../../src/gui/painting/qpainter.h:459:79: error: within this context
     void addCheckBox(const QRectF &r, bool checked=false, const QString &name="", bool readOnly=false);
                                                                               ^
In file included from ../../include/QtCore/qstring.h:1:0,
                 from ../../include/QtCore/../../src/corelib/kernel/qobject.h:48,
                 from ../../include/QtCore/qobject.h:1,
                 from ../../include/QtGui/../../src/gui/kernel/qevent.h:46,
                 from ../../include/QtGui/qevent.h:1,
                 from ../../include/QtGui/QMouseEvent:1,
                 from ./qdeclarativetester.h:46,
                 from qdeclarativetester.cpp:42:
../../include/QtCore/../../src/corelib/tools/qstring.h:597:5: error: âQString::QString(const char_)â is private
     QString(const char _ch);
     ^
In file included from ../../include/QtGui/qpainter.h:1:0,
                 from ../../include/QtGui/../../src/gui/graphicsview/qgraphicsview.h:46,
                 from ../../include/QtGui/qgraphicsview.h:1,
                 from ../../include/QtDeclarative/../../src/declarative/util/qdeclarativeview.h:48,
                 from ../../include/QtDeclarative/qdeclarativeview.h:1,
                 from qdeclarativetester.cpp:45:
../../include/QtGui/../../src/gui/painting/qpainter.h:460:64: error: within this context
     void addRadioButton(const QRectF &r, const QString & group="",  bool checked=false, const QString &name="", bool readOnly=false);;
                                                                ^
In file included from ../../include/QtCore/qstring.h:1:0,
                 from ../../include/QtCore/../../src/corelib/kernel/qobject.h:48,
                 from ../../include/QtCore/qobject.h:1,
                 from ../../include/QtGui/../../src/gui/kernel/qevent.h:46,
                 from ../../include/QtGui/qevent.h:1,
                 from ../../include/QtGui/QMouseEvent:1,
                 from ./qdeclarativetester.h:46,
                 from qdeclarativetester.cpp:42:
../../include/QtCore/../../src/corelib/tools/qstring.h:597:5: error: âQString::QString(const char_)â is private
     QString(const char *ch);
     ^
In file included from ../../include/QtGui/qpainter.h:1:0,
                 from ../../include/QtGui/../../src/gui/graphicsview/qgraphicsview.h:46,
                 from ../../include/QtGui/qgraphicsview.h:1,
                 from ../../include/QtDeclarative/../../src/declarative/util/qdeclarativeview.h:48,
                 from ../../include/QtDeclarative/qdeclarativeview.h:1,
                 from qdeclarativetester.cpp:45:
../../include/QtGui/../../src/gui/painting/qpainter.h:460:109: error: within this context
     void addRadioButton(const QRectF &r, const QString & group="",  bool checked=false, const QString &name="", bool readOnly=false);;
                                                                                                             ^

**Comment by alloylab** [comment]
is this still an issue on 0.12.5?
