### ISSUE TITLE
You need to specify atleast one input file, ...

### ISSUE THREAD

**Issue by GeorgesThuot** [wkhtmltopdf/wkhtmltopdf#2716]
What's wrong with the following command line

wkhtmltopdf http://quote.morningstar.ca/quicktakes/Fund/f_ca.aspx?t=F0CAN05OYD&region=CAN&culture=fr-CA C:\Users\Georges\Desktop\demo.pdf

**Comment by PhilterPaper** [comment]
Try wrapping the input page http:... fr-CA in " (quotation marks). Maybe something with the / or ? or & is being interpreted in an unexpected way.

    wkhtmltopdf "http://quote.morningstar.ca/quicktakes/Fund/f_ca.aspx?t=F0CAN05OYD&region=CAN&culture=fr-CA" C:\Users\Georges\Desktop\demo.pdf

**Comment by wsharten** [comment]
The following still produce the need input file error:

wkhtmltopdf "index.html"
wkhtmltopdf index.html
wkhtmltopdf -

The index.html file exists.
Using version 0.12.5 (with patched qt), mac/osx, just installed it.
