### ISSUE TITLE
wkhtmltopdf in Visual Studio

### ISSUE THREAD

**Issue by AndrewGsnv** [wkhtmltopdf/wkhtmltopdf#2717]
Hello, on the website http://wkhtmltopdf.org is collected by the compiler of Visual Studio 2013 binaries, please tell me whether there is a project to build wkhtmltopdf in Visual Studio, and is it even possible to assemble it in the Visual Studio?

**Comment by ashkulz** [comment]
Nope, all building happens via the command-line as that is the only mode supported by Qt (the underlying framework used by wkhtmltopdf).
