### ISSUE TITLE
Burmese Unicode Font Not Rendered Correctly (Patched in Qt 5.2)

### ISSUE THREAD

**Issue by minhngocd** [wkhtmltopdf/wkhtmltopdf#2722]
Hi,

We are trying to generate a pdf with Burmese text, and the glyphs are not being rendered correctly. We had a look around, and found out that Qt had [a fix for the issue in version 5.2](https://bugreports.qt.io/browse/QTBUG-14590).

Is using Qt 5.5 in the plan?

If not, would it be possible to try applying the patch in wkhtmltopdf's fork of Qt 4.8?

Thanks.

**Comment by alloylab** [comment]
is this still an issue on 0.12.5?

**Comment by polynn** [comment]
Yes, It is.
