### ISSUE TITLE
Internal links named within html headings are broken

### ISSUE THREAD

**Issue by wsfulton** [wkhtmltopdf/wkhtmltopdf#2723]
```
$ wkhtmltopdf --version
wkhtmltopdf 0.12.2.1 (with patched qt)
$ wkhtmltopdf http://swig.org/Doc2.0/SWIGDocumentation.html SWIGDocs.pdf
```
This html file has many internal links and the majority do not work in the generated pdf file. An example of one of the internal links within the document that is not found is:
```html
<H2><A name="Preface_nn2"></A>1.1 Introduction</H2>
```
but this one is found:
```html
<H2><A NAME="1_1">Sections</A></H2>
```
The difference between the two is simply the positioning of the heading text within the A and H2 elements. The links to these two are right near the beginning of the page and are respectively:
```html
<LI><A HREF="#Preface_nn2">1.1 Introduction</A></LI>
```
```html
<LI><A HREF="#1_1">Sections</A>
```

**Comment by PhilterPaper** [comment]
Is the first case with no text (before the `</A>`) even legal HTML? There's no text to associate with the link anchor, so I could imagine that it doesn't work with *some* browser engines (e.g., WebKit used in this product). Perhaps some lenient engines will permit it, but it's probably rather non-standard.

**Comment by wsfulton** [comment]
I certainly don't know the html standard very well, but we've used htmltidy to validate the pages for many years and all the browsers I've come across over the last 15 years or so have worked with it like this. However, I've just looked it up in the standard and this page: http://www.w3.org/TR/html4/struct/links.html#h-12.1.1 shows ```<A>``` and ```<H2>``` examples that works with wkhtmltopdf. So, I'll change our code to the way the standard specifies it and then it'll work with wkhtmltopdf. I'm closing this issue but I guess it can be re-opened if any more evidence that the bug reported is actually standards compliant.

**Comment by PhilterPaper** [comment]
By the way, the <A> tag with the NAME attribute is considered obsolete HTML, although it's doubtful that support for it will disappear any time soon. The preferred way is to use an ID attribute:

    <H2 ID="Preface_nn2">1.1 Introduction</H2>

It might not be worth changing over an existing system, but you might give consideration to changing over in future documents.

**Comment by jasonb-vbt** [comment]
No issue here. Just wanted to say thanks for this thread. You helped me fix what was wrong with my internal links-to-anchors.
