### ISSUE TITLE
brew install doesn't work

### ISSUE THREAD

**Issue by aladagemre** [wkhtmltopdf/wkhtmltopdf#2724]
$ brew install wkhtmltopdf
Error: No available formula with the name "wkhtmltopdf"
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
This formula was found in a tap:
Caskroom/cask/wkhtmltopdf
To install it, run:
  brew install Caskroom/cask/wkhtmltopdf

$ brew install Caskroom/cask/wkhtmltopdf
==> brew cask install Caskroom/cask/wkhtmltopdf
Error: Cask 'wkhtmltopdf' definition is invalid: Bad header line: parse failed

**Comment by aladagemre** [comment]
I guess it's due to old version of brew/cask.

**Comment by sumdimsum** [comment]
Run ```brew update && brew uninstall --force brew-cask```

**Comment by mikeghen** [comment]
:+1: @sumdimsum
