### ISSUE TITLE
Only get blank pdf file in asp.net

### ISSUE THREAD

**Issue by derrickxiang** [wkhtmltopdf/wkhtmltopdf#2731]
I tried to call wkhtmltopdf via c# in my asp.net web project, and it only generate an empty pdf file, but when I manually run the same command in command prompt, it's working fine. And I tried capture the process errors and output, I got the exit code 0 and output "QFont::setPixelSize: Pixel size <= 0 (0)  QFont::setPixelSize: Pixel size <= 0 (0) ", can help to lighten me where could go wrong?

**Comment by alloylab** [comment]
is this still an issue on 0.12.5?
