### ISSUE TITLE
Javascript Parsing errors when trying parse from a URL

### ISSUE THREAD

**Issue by leif013** [wkhtmltopdf/wkhtmltopdf#2734]
I'm having problems getting the javascripts to parse when I try to pull a URL currently.  

The best information I can get is as follows:
Warning: http://localhost/AccountableCare.Web/_cassette/scriptbundle/HighchartsReference_942d279f2dbb21e825afca0884f0dc33d936ed0e:1 SyntaxError: Parse error

I get one of these errors for pretty much every javascript.

This only seems to happen when cassette (version 1) is enabled.  If I disable cassette I don't get any parsing issues.

Is there anything else I can do to troubleshoot this further (i.e. to gain insight into what /where the parsing error is)?

Thanks,

Alex

**Comment by bgadoury** [comment]
Could you try viewing that URL with a web browser with Chrome dev tools open, or Firebug running on Firefox? I don't think you're going to get any more detail out of wkhtmltopdf directly, based on my experience.

**Comment by leif013** [comment]
Thanks for the reply.  We were able to do a quick upgrade to the newest version of Cassette and that actually cleared up the issue...so it seems that something in the minification of the javascript in Cassette 1.0 just isn't compatible with wkhtmltopdf.
