### ISSUE TITLE
Extra margin

### ISSUE THREAD

**Issue by drewlag** [wkhtmltopdf/wkhtmltopdf#2737]
I tried to rendere an html page to pdf with margin 0 -T 0mm -B 0mm -L 0mm -R 0mm --page-size A4, but it doesn't work. The page has an extra margin on the right and on the bottom.
Anyone knows why?

Thanks

**Comment by bgadoury** [comment]
Please post the HTML and wkhtmltopdf command line you're using.

**Comment by AndrewLag** [comment]
./wkhtmltopdf -T 20mm -B 30mm -L 10mm -R 5mm /documents/print.php mypdf.pdf 2>&1

**Comment by ceap80** [comment]
I'm having the same problem.

Version: `wkhtmltopdf 0.12.3 (with patched qt)`
OS Version: `Ubuntu 12.04.5 LTS 32 Bits`

Command: `/wkhtmltopdf -B 0 -R 0 -T 0 -L 0  --disable-smart-shrinking 'template.html'  sample.pdf`

I tried without ` --disable-smart-shrinking` with the same result


My HTML:

```html
<html>
<head>
	<title>Template</title>
</head>
<style type="text/css">
body {
	background-color: black;
}
</style>
<body>
</body>
</html>
```

I've attached the resulting PDF.

If you need any other info just let me know.

[sample.pdf](https://github.com/wkhtmltopdf/wkhtmltopdf/files/230882/sample.pdf)

**Comment by Tomsgu** [comment]
Closing as it works completely fine in 0.12.5. Update to a newest version. Please feel free to re-open this issue if you still experience this bug.
