### ISSUE TITLE
Can we use wkhtltopdf convertor to convert ppt to pdf?

### ISSUE THREAD

**Issue by evivz** [wkhtmltopdf/wkhtmltopdf#2739]
Can we use wkhtltopdf convertor to convert ppt to pdf?

**Comment by PhilterPaper** [comment]
Supposedly, PPT can be saved as HTML. There are also free and paid tools to do such conversions. Then you could try converting the HTML to PDF. You should get *something*, although no promises as to how good it will be. There are also supposedly some tools to directly convert PPT to HTML, but as far as I know that does not include wkHTMLtoPDF.

**Comment by Sicos1977** [comment]
I made something to convert Microsoft Office formats to PDF. But this needs Microsoft office on the server. You can find it overhere --> https://github.com/Sicos1977/OfficeConverter

**Comment by Tomsgu** [comment]
This is html to pdf/image converter.
