### ISSUE TITLE
PDF document security 

### ISSUE THREAD

**Issue by RiddP** [wkhtmltopdf/wkhtmltopdf#2742]
Hello
How can we set document security ? i.e how can make below all/some changes to disallow before or after pdf generates and available for download ?
![capture](https://cloud.githubusercontent.com/assets/11499792/12098503/08ccb9d6-b323-11e5-9df3-17e82989be5b.PNG)

**Comment by lorenzos** [comment]
I don't think this is for `wkhtmltopdf`.
You can try using [`pdftk`](https://www.pdflabs.com/tools/pdftk-server/) **after** the PDF generation. Have a look at [`allow` permissions](https://www.pdflabs.com/docs/pdftk-man-page/#dest-output-enc-perms) and related [examples](https://www.pdflabs.com/docs/pdftk-cli-examples/).

**Comment by RiddP** [comment]
Dear Lorenzo,

Thanks a lot for replying. Your option has given us some hope.  We have used Rotativa in MVC to allow PDF "Save" option from browser.
So we just use below code to  

 var pdfResult = new Rotativa.ViewAsPdf("GeneratePDF", p)
                    {
                         FileName = "test.pdf",
                         CustomSwitches = cusomtSwitches
                   };
                    return pdfResult;

So how we can fit pdftk here as we dont have pdf softcopy saved at any place on server.

**Comment by Tomsgu** [comment]
Closing as the @lorenzos's answer has given a solution to this issue.
