### ISSUE TITLE
Empty pdf output. Input html contains two frames but output pdf was empty

### ISSUE THREAD

**Issue by viswa18** [wkhtmltopdf/wkhtmltopdf#2743]
I have attached my input html files that contains frames . But ouput pdf was empty I dont know why?
Here I have attached input and output files. 

[frame.zip](https://github.com/wkhtmltopdf/wkhtmltopdf/files/78204/frame.zip)

**Comment by bgadoury** [comment]
Your <!DOCTYPE> declaration is declaring HTML5, which does not support frames. You need this instead:

    <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Frameset//EN" "http://www.w3.org/TR/html4/frameset.dtd">

**Comment by Prakash222** [comment]
I have add the above line in my html but it does not work. 
In web browsers this document working fine.

**Comment by bgadoury** [comment]
I must have made a mistake. Fixing the doctype does **not** work for me either. I was going through a bunch of wkhtmltopdf issues last night and I must have mixed up test results and thought the doctype fixed this. 

Judging from #2131 as well as StackOverflow, it doesn't sound like wkhtmltopdf supports frames. Considering how deprecated framesets are, I'd guess it never will.

**Comment by Prakash222** [comment]
Thanks And I think Webkit cannot find the height of the document..

**Comment by viswa18** [comment]
If I have set height to some value. It converts upto the height. How can find the original height website that contains frames.
