### ISSUE TITLE
'Arial Narrow' font rendered in the generated PDF

### ISSUE THREAD

**Issue by sushmithakm1** [wkhtmltopdf/wkhtmltopdf#2746]
I have arial narrow.ttf placed in the /.fonts folder on linux machine. 
below is my input HTML, the generated PDF document embeds 'times new roman' font instead of 'Arial narrow' font. Can someone please let me know is some thing overriding ?
```html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <TITLE> New WKHTMLTOPDF Document </TITLE>
        <meta http-equiv="content-type" content="text/html; charset=UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=IE6" />


</head>
<body>


<table cellspacing='0'>

    <tr><td style="font-family: 'Arial Narrow'; ">  Arial Narrow 
        ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyz 1234567890! @ # $ % ^ * () {} []'""?<>iui
    </td></tr>
    <tr><td style="font-family: 'Arial Narrow'; font-weight:bold;">  Arial Narrow
        ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyz 1234567890! @ # $ % ^ * () {} []'""?<>iui
    </td></tr>
    <tr><td style="font-family: 'Arial Narrow'; font-style:italic;"> Arial Narrow
        ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyz 1234567890! @ # $ % ^ * () {} []'""?<>iui
    </td></tr>
    <tr><td style="font-family: 'Arial Narrow'; font-weight:bold; font-style:italic;"> Arial Narrow
        ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyz 1234567890! @ # $ % ^ * () {} []'""?<>iui
    </td></tr>
    


    
    
</table>



</body>


</html>
```

**Comment by PhilterPaper** [comment]
Where are you telling HTML to use the Arial Narrow font family? When you made the above post, did it eat some HTML codes such as `<font>` or style= ? Use backticks around HTML tags you post.

**Comment by sushmithakm1** [comment]
Yes i think, my input HTML has modified. Let me upload the files.
when i run wkhtmltopdf convert command  (/wkhtmltox/bin/wkhtmltopdf /FO.html /FO.pdf) it works fine, but i am facing this issue when i set 'FONTCONFIG_FILE' variable to my custom /fonts.conf file and ran the command (/wkhtmltox/bin/wkhtmltopdf /FO.html /FO.pdf)

I am unable to upload HTML/ZIP, hence uploaded the screenshot of HTML and outputs generated after and before execution of  export FONTCONFIG_FILE=/fonts.conf  command.

[FO_before_export.pdf](https://github.com/wkhtmltopdf/wkhtmltopdf/files/85361/FO_before_export.pdf)
[FO1_after_export.pdf](https://github.com/wkhtmltopdf/wkhtmltopdf/files/85362/FO1_after_export.pdf)


![fo](https://cloud.githubusercontent.com/assets/16610331/12227808/67080228-b858-11e5-96f1-f1059995b55c.png)

Thanks,

**Comment by PhilterPaper** [comment]
No need to post images. Just indent your code by 4 spaces:

    <html>
      <head>
        <title>My Problem</title>
      </head>
      <body>
    <b>Some bold text.</b>
      </body>
    </html>

And click the "Preview" tab to see if you overlooked anything, to see if it formats correctly.

**Comment by sushmithakm1** [comment]
Thankyou, Please check my below HTML and suggest me
   
    <div><font style="font-family: 'Arial Narrow'; "> 17. Arial Narrow 
		ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyz 1234567890! 
	</font></div>

**Comment by PhilterPaper** [comment]
`<font>` tags are obsolete, and you're not using it correctly anyway. Change it to a `<span>` tag. It should then recognize the style= CSS.

**Comment by bgadoury** [comment]
This looks like the same issue (specified font not getting used) as issue #2747. It's probably not helpful to create multiple Github issues for the same problem.

**Comment by Tomsgu** [comment]
Closing as there is no feedback since 2016.
