### ISSUE TITLE
Realtor Website not showing images anymore

### ISSUE THREAD

**Issue by bartekd123** [wkhtmltopdf/wkhtmltopdf#2749]
Hello,
I was using this command for the last year, and it has worked great. Now when I run it, it doesn't output the images to the PDF file. Below is an example of a website that is doing this. Anyone have any ideas?

wkhtmltopdf --print-media-type "https://www.realtor.ca/propertyDetails.aspx?PropertyId=16093172" "C:\realtor\test123.pdf"

**Comment by bartekd123** [comment]
[test123.pdf](https://github.com/wkhtmltopdf/wkhtmltopdf/files/85905/test123.pdf)

**Comment by bgadoury** [comment]
When I run this:

`wkhtmltopdf --debug-javascript --javascript-delay 9000 --no-stop-slow-scripts "https://www.realtor.ca/propertyDetails.aspx?PropertyId=16093172" --print-media-type realtor.pdf`

I get 2 JavaScript errors that are unique to wkhtmltopdf output, as well as 1 JavaScript error related to analytics that **does** appear in Firefox:

`Warning: undefined:0 TypeError: 'null' is not an object`
`Warning: undefined:0 TypeError: 'null' is not an object`
`Warning: https://analytics.crea.ca/LogEvents.svc/LogEvents?&DestinationID=384&UUID=f1b1a66f-1ee1-41f6-b6c7-9a440360786c&IP=128.103.64.117&ListingID=16093172&EventType=view&LanguageId=1&ActiveOpenHouse=0&callback=jQuery17205460787361953408_1452641871128&_=1452641872140:1 SyntaxError: Parse error`

Any of those could be your breaking your page in the context of wkhtmltopdf. 

Also note that I got 2 errors related to "ResourceObject" before I added the --no-stop-slow-scripts switch. That might not be relevant, but I figured I'd mention it.

**Comment by bartekd123** [comment]
Thanks. That's probably the issue then. Do you know if it looks like an issue on the end of the website, or is there something I can do on my end to make it work? 

When I print the actual page to my printer, it works fine. 



On Tue, Jan 12, 2016 at 3:52 PM -0800, "bgadoury" <notifications@github.com> wrote:












When I run this:



wkhtmltopdf --debug-javascript --javascript-delay 9000 --no-stop-slow-scripts "https://www.realtor.ca/propertyDetails.aspx?PropertyId=16093172" --print-media-type realtor.pdf



I get 2 JavaScript errors that are unique to wkhtmltopdf output, as well as 1 JavaScript error related to analytics that does appear in Firefox:



Warning: undefined:0 TypeError: 'null' is not an object

Warning: undefined:0 TypeError: 'null' is not an object

Warning: https://analytics.crea.ca/LogEvents.svc/LogEvents?&DestinationID=384&UUID=f1b1a66f-1ee1-41f6-b6c7-9a440360786c&IP=128.103.64.117&ListingID=16093172&EventType=view&LanguageId=1&ActiveOpenHouse=0&callback=jQuery17205460787361953408_1452641871128&_=1452641872140:1 SyntaxError: Parse error



Any of those could be your breaking your page in the context of wkhtmltopdf. 



Also note that I got 2 errors related to "ResourceObject" before I added the --no-stop-slow-scripts switch. That might not be relevant, but I figured I'd mention it.

**Comment by bgadoury** [comment]
It looks like it's an issue with the site and there's nothing you can do short of letting them know their website is kicking up the above errors.

**Comment by bartekd123** [comment]
Ok thank you. 

Thanks,

Bartek
----------------------
Sent from Outlook




On Wed, Jan 13, 2016 at 6:39 AM -0800, "bgadoury" <notifications@github.com> wrote:












It looks like it's an issue with the site and there's nothing you can do short of letting them know their website is kicking up the above errors.

**Comment by bgadoury** [comment]
It would be great if you would close this issue on Github so it doesn't hang around forever. :heart:

**Comment by bartekd123** [comment]
I will wait a bit to see if anyone else has any other suggestions, or maybe this can be overcome some way in code. If no one replies, Ill close it in a little while.

**Comment by bartekd123** [comment]
I am closing this because it seems that the issue is on the side of the website that is hosting the page. if anyone has any work around, please let me know.

**Comment by meuwka** [comment]
@bartekd123 How did you solve the problem? I got the same

**Comment by bartekd123** [comment]
I never really did find out a way around it. I sent them an email to try and get them to fix it but I just gave up. If you find a workaround let me know.

Thanks,

Bart

________________________________
