### ISSUE TITLE
Unpatched QT help

### ISSUE THREAD

**Issue by ChubbyNinja** [wkhtmltopdf/wkhtmltopdf#2752]
I am trying to use the wkhtmltopdf patched qt - but i am really struggling to understand what I need to do to get this working;

`wkhtmltopdf --help` gives me:

```
Reduced Functionality:
  This version of wkhtmltopdf has been compiled against a version of QT without
  the wkhtmltopdf patches. Therefore some features are missing, if you need
  these features please use the static version.
```

I have looked around but a lot of examples of how to get patched QT are outdated and links broken.

Any advice on how to apply the patched QT on the already installed wkhtmltopdf?

wkhtmltopdf version `wkhtmltopdf 0.13.0-alpha-7b36694`

**Comment by stania1** [comment]
Where did you get this wkhtmltopdf binary? Did you compile it yourself?

As far as I know, the patched qt should be compiled to the wkhtmltopdf binary already. You could try either getting a new binary (via wkhtmltopdf-binary, wkhtmltopdf-binary-edge, etc.) or, if needed, recompiling with the patched qt.
