### ISSUE TITLE
"Failed loading page" error when over 120 pages with '--header-html' and '--footer-html'

### ISSUE THREAD

**Issue by dot** [wkhtmltopdf/wkhtmltopdf#2754]
I found error when generating over 120 pages. In this version.

```
$ wkhtmltopdf --version
wkhtmltopdf 0.12.3-dev-79ff51e (with patched qt)
```

I run this command

```
$ wkhtmltopdf --print-media-type --orientation Portrait --header-html ./header.html --footer-html ./footer.html body.html out.pdf
```

occurs error like this

```
Error: Failed loading page file:///Users/kondo/Desktop/test/header.html?page=121&section=&sitepage=121&title=&subsection=&frompage=1&subsubsection=&isodate=2016-01-13&topage=126&doctitle=&sitepages=126&webpage=main.html&time=20:03&date=2016/01/13 (sometimes it will work just to ignore this error with --load-error-handling ignore)
```

This is minimum repro code.
https://gist.github.com/dot/df3a23a3b7111b78ae86

When snip html to make less than 120 pages, not occurs "Failed loading page" error. It seems to 120 pages was threshold.
 In addition, remove --header-html or --footer-html argument, not occurs error.

**Comment by lorenzos** [comment]
See https://github.com/wkhtmltopdf/wkhtmltopdf/issues/1681#issuecomment-169968102, if it fails try to see if you can implement this workaround: https://github.com/wkhtmltopdf/wkhtmltopdf/issues/2093#issuecomment-167955213

**Comment by roshan-lrn** [comment]
I have experienced the same issue. If wkhtmltopdf command takes more than 60 seconds, then it throws this error.

**Comment by fmdl** [comment]
Dear, When you try to generate a big pdf (over 200 pages) with header and footer, you are an error -11. It is a limitation of max handle file per process. (default is 256 for mac). But the wkhtmltopdf open for each page the header and the footer. to change this value : http://stackoverflow.com/questions/16526783/python-subprocess-too-many-open-files

In terminal do : ulimit -n 10000
Check : ulimit -a

**Comment by Tomsgu** [comment]
Closing as @fmdl solution should fix the issue. Please let us know if the solution foesnt make any difference.
