### ISSUE TITLE
Chinese characters are not displayed on Amazon Linux

### ISSUE THREAD

**Issue by max-konin** [wkhtmltopdf/wkhtmltopdf#2760]
I try to create pdf from html. On ubuntu, all right. But on amazon linux, chinese characters are not displayed (other langs is ok).

**Comment by patrick-riemer** [comment]
Had the same problem. Installing a font package for chinese on the server solved the problem for me. I have used the package "ttf-wqy-zenhei".

**Comment by max-konin** [comment]
Hi.Yes. The problem was resolved by installing packages. But I installed other packages. From https://forums.aws.amazon.com/thread.jspa?threadID=140987
