### ISSUE TITLE
Is wkhtmltopdf dead?

### ISSUE THREAD

**Issue by majksner** [wkhtmltopdf/wkhtmltopdf#2762]
Is this project actively maintained, I see that last release was more then a 6 months ago and there is more then 400 issues?

**Comment by ashkulz** [comment]
I've been the primary developer for the last few years. I'm

* burnt out
* don't have too much time to look into issues
* busy with work and a 2-year old kid

so time for this project has been non-existent recently. If someone volunteers with [issue triaging](http://words.steveklabnik.com/how-to-be-an-open-source-gardener) it would really free up time and energy for me to get back on track.

So yes, you can say that the current maintainer is on hiatus :frowning:

**Comment by ashkulz** [comment]
Well, at least I got a release out of the door. For the future, who knows? I'll be sending a call for help on the mailing list and on Twitter.
