### ISSUE TITLE
Where to download binaries for v0.12.3

### ISSUE THREAD

**Issue by ironman1964** [wkhtmltopdf/wkhtmltopdf#2763]
This version seem to have solved the "temporary files not being deleted" ...
Any help appreciated !

**Comment by ashkulz** [comment]
Check the downloads page in a few hours.

**Comment by ironman1964** [comment]
I've just used the testversion and that already works :+1: 
But I will use the stable version if it is published !!

**Comment by ashkulz** [comment]
It's now available from the downloads page.
