### ISSUE TITLE
wkhtmltopdf shrinks height of document to fit content

### ISSUE THREAD

**Issue by Glurak** [wkhtmltopdf/wkhtmltopdf#2768]
This is a simple test page layout: http://pastebin.com/BUHiujQk

Inside browser it looks like this: http://i.imgur.com/BHkeuwz.png

Notice how word "bottom" is at the bottom. This is what I wanted. Also if I print it from the browser, it prints on the bottom of the paper.

But after using wkhtmltopdf to turn it into pdf it looks like this: http://i.imgur.com/2wP38J6.png

Bottom is no longer bottom.

The only workaround I can think of is setting constant height to document using CSS, but I'd like to avoid non-dynamic solution as that could give more problems then solve.

**Comment by alloylab** [comment]
is this still an issue on 0.12.5?
