### ISSUE TITLE
crash when adding html headers (QList<T>::operator[]", "index out of range)

### ISSUE THREAD

**Issue by e-dot** [wkhtmltopdf/wkhtmltopdf#2769]
We're using wkhtmltopdf and it's working great. We have experienced a crash (quite difficult to reproduce) since we added html headers (using --header-html). The crash occurs on x64 windows (Windows 7, Windows 8.1, Windows Server 2008 R2).

We built a debug version of the program and got the following stack trace:

`  wkhtmltopdf.exe!qt_message_output(QtMsgType msgType, const char * buf) Line 2411	C++
 	wkhtmltopdf.exe!qt_message(QtMsgType msgType, const char * msg, char * ap) Line 2469	C++
 	wkhtmltopdf.exe!qFatal(const char * msg, ...) Line 2653	C++
 	wkhtmltopdf.exe!qt_assert_x(const char * where, const char * what, const char * file, int line) Line 2127	C++
 	wkhtmltopdf.exe!QList<QWebPage * __ptr64>::operator[](int i) Line 477	C++
 	wkhtmltopdf.exe!wkhtmltopdf::PdfConverterPrivate::printDocument() Line 999	C++
 	wkhtmltopdf.exe!wkhtmltopdf::PdfConverterPrivate::headersLoaded(bool ok) Line 811	C++
 	wkhtmltopdf.exe!wkhtmltopdf::PdfConverterPrivate::qt_static_metacall(QObject * _o, QMetaObject::Call _c, int _id, void * * _a) Line 61	C++
 	wkhtmltopdf.exe!QMetaObject::activate(QObject * sender, const QMetaObject * m, int local_signal_index, void * * argv) Line 3567	C++
 	wkhtmltopdf.exe!wkhtmltopdf::MultiPageLoader::loadFinished(bool _t1) Line 118	C++
 	wkhtmltopdf.exe!wkhtmltopdf::MultiPageLoaderPrivate::loadDone() Line 502	C++
 	wkhtmltopdf.exe!wkhtmltopdf::ResourceObject::loadDone() Line 314	C++
 	wkhtmltopdf.exe!wkhtmltopdf::ResourceObject::qt_static_metacall(QObject * _o, QMetaObject::Call _c, int _id, void * * _a) Line 292	C++
 	wkhtmltopdf.exe!QMetaObject::activate(QObject * sender, const QMetaObject * m, int local_signal_index, void * * argv) Line 3567	C++
 	wkhtmltopdf.exe!QSingleShotTimer::timeout() Line 97	C++
 	wkhtmltopdf.exe!QSingleShotTimer::timerEvent(QTimerEvent * __formal) Line 322	C++
 	wkhtmltopdf.exe!QObject::event(QEvent * e) Line 1185	C++
 	wkhtmltopdf.exe!QApplicationPrivate::notify_helper(QObject * receiver, QEvent * e) Line 4565	C++
 	wkhtmltopdf.exe!QApplication::notify(QObject * receiver, QEvent * e) Line 3947	C++
 	wkhtmltopdf.exe!QCoreApplication::notifyInternal(QObject * receiver, QEvent * event) Line 955	C++
 	wkhtmltopdf.exe!QCoreApplication::sendEvent(QObject * receiver, QEvent * event) Line 231	C++
 	wkhtmltopdf.exe!QEventDispatcherWin32Private::sendTimerEvent(int timerId) Line 658	C++
 	wkhtmltopdf.exe!qt_internal_proc(HWND__ * hwnd, unsigned int message, unsigned __int64 wp, __int64 lp) Line 502	C++
 	[External Code]	
 	wkhtmltopdf.exe!QEventDispatcherWin32::processEvents(QFlags<enum QEventLoop::ProcessEventsFlag> flags) Line 823	C++
 	wkhtmltopdf.exe!QGuiEventDispatcherWin32::processEvents(QFlags<enum QEventLoop::ProcessEventsFlag> flags) Line 1216	C++
 	wkhtmltopdf.exe!QCoreApplication::processEvents(QFlags<enum QEventLoop::ProcessEventsFlag> flags) Line 1143	C++
 	wkhtmltopdf.exe!wkhtmltopdf::ConverterPrivate::convert() Line 94	C++
 	wkhtmltopdf.exe!wkhtmltopdf::Converter::convert() Line 150	C++
 	wkhtmltopdf.exe!main(int argc, char * * argv) Line 187	C++
`

It seems that the number of headers is mis-calculated (just a guess)...

File wkhtmltopdf\src\lib\pdfconverter.cc line 997+ we have this code:
`			for(int i=0; i < pageCount; ++i) {
				if (!objects[d].headers.empty())
					handleHeader(objects[d].headers[i], i);
				if (!objects[d].footers.empty())
					handleFooter(objects[d].footers[i], i);
			}
`

The QList object raises an exception because headers[i] is out of range (note that the document is supposed to have 3 pages and when i == 2 the program crashes (just if the program allocated only 2 headers, index 0 and 1).

We will try to post a full test case but without our full environment it's not easy.

Please advise on how to work around/fix this bug.

Regards,

E.

**Comment by ashkulz** [comment]
Looks to be the same as #1806, if you can post a test case that is reproducible on Windows that would be great (uploading somewhere and sending a link privately would also do).

**Comment by e-dot** [comment]
Right - same error, I will post a test case so you can investigate on #1806

**Comment by e-dot** [comment]
Here's a zip containing minimal test case. 
[BUG.REPORT.zip](https://github.com/wkhtmltopdf/wkhtmltopdf/files/110091/BUG.REPORT.zip)
