### ISSUE TITLE
Absolute positioning at bottom, does not seem to work 

### ISSUE THREAD

**Issue by gwene** [wkhtmltopdf/wkhtmltopdf#2770]
When I position something absolutely at bottom, it seems to always show way at the top:
For example, text within a div assigned the following class, appears at the top of a page
```css
.authornote {
    position: absolute;
    bottom: 0;
}
```

Is there a way to get absolute positioning at bottom to work with wkhtmltopdf? I can't seem to find information on it, other than others that have the issue: http://stackoverflow.com/questions/31265841/wkhtmltopdf-aligning-logo-to-bottom-without-using-a-footer?newreg=bbba9242d19d44f591a552c40cfb3f03  Thanks!

**Comment by carlotrimarchi** [comment]
Probably a bit late, but I was experiencing the same issue and solved by adding `width: 100%;`

**Comment by Tomsgu** [comment]
Closing as the answer was provided.
