### ISSUE TITLE
Stable Windows MinGW builds

### ISSUE THREAD

**Issue by mintsoft** [wkhtmltopdf/wkhtmltopdf#2776]
Hey,

I notice that a stable MinGW build doesn't appear to be available for 0.12.3.1 when it was for older versions and bleeding edge. Is it permanently removed? We find it useful to be able to deploy all the dependencies in one go without having to ship the VC runtime so we much prefer the MinGW builds!

Thanks

**Comment by ashkulz** [comment]
@mintsoft: are you getting errors while deploying the regular builds? Since f5efb5e2a1732e4df06f226170d4c821952d677b (i.e. the `0.12.2` release) the MSVC runtime is bundled and installed if it is not present in the target machine.

I'm planning to remove support for those builds, as Windows 2003/Windows XP aren't supported anymore and they were useful mostly for that reason.

**Comment by mintsoft** [comment]
@ashkulz We don't install the application directly, we have it packaged with an internal C# tool that shells out to it; and the executable and associated assemblies are shipped too.  We've found it generally difficult to deploy MSVC runtimes, hence why we used the MinGW builds

**Comment by fredericosilva** [comment]
Hello,

I'm also using the MinGW build to avoid requiring elevated permissions on setup installation. Maybe we can add some SxS voodoo and ship it without the MSVC runtime installer. @mintsoft have you tried that?

**Comment by mintsoft** [comment]
@fredericosilva We've not tried that yet; we've just stayed on the previous stable release with MinGW (0.12.2.4) for the moment.

**Comment by fredericosilva** [comment]
It seems to work fine by just adding those files on the same directory
```
msvcp120.dll`
msvcr120.dll
vccorlib120.dll
```
So, no need of any fancy SxS :)

**Comment by mintsoft** [comment]
@fredericosilva that's a good suggestion actually, we could just ship those assemblies out with it the same as we used to with the MinGW ones

**Comment by ashkulz** [comment]
If you're not using the official installer, I can't really help you. Or you can compile the MinGW builds yourself using the instructions provided in `INSTALL.md` for that specific release.
