### ISSUE TITLE
Incorrect page count

### ISSUE THREAD

**Issue by nigareps** [wkhtmltopdf/wkhtmltopdf#2783]
I am trying to merge multiple bills into single pdf. Every bill has multiple pages and every bill has unique header and footer. To print out page count I use javascript code from documentation example. When I build pdf from a single bill, page count is correct, bet when I pass in all bills, page count is total sum of every bill page. Headers are printed ok, they ar unique for every bill, only page count is summed together. Is there a way to fix this?

**Comment by alloylab** [comment]
is this still an issue on 0.12.5?
