### ISSUE TITLE
build.py fails with "qt/configure: No such file or directory" on OSX

### ISSUE THREAD

**Issue by omero72** [wkhtmltopdf/wkhtmltopdf#2784]
Hello
As I wanted to try this program called wkhtmltopdf on my OSX 10.7.4; I've run into an installation problem:

./scripts/build.py osx-cocoa-x86-64
(required a Ruby gem called fpm, I 've installed it and reentered the build.py script)
Curiously, the build script couldn't find those 3 packages/libraries

libpng
jpeg src
xz
even though they are all installed, mainly under /usr/local/bin

Eventually it stopped with

`sh: ../../../qt/configure: No such file or directory
../../../qt/configure -opensource -confirm-license -fast -release -static -graphicssystem raster -webkit -exceptions -xmlpatterns -system-zlib -system-libpng -system-libjpeg -no-libmng -no-libtiff -no-accessibility -no-stl -no-qt3support -no-phonon -no-phonon-backend -no-opengl -no-declarative -no-script -no-scripttools -no-sql-ibase -no-sql-mysql -no-sql-odbc -no-sql-psql -no-sql-sqlite -no-sql-sqlite2 -no-mmx -no-3dnow -no-sse -no-sse2 -no-multimedia -nomake demos -nomake docs -nomake examples -nomake tools -nomake tests -nomake translations -silent -no-framework -no-dwarf2 -xrender -openssl -largefile -no-rpath -cocoa -platform unsupported/macx-clang --prefix=/Users/wanzohanzo/wkhtmltopdf/static-build/osx-cocoa-x86-64/qt -I /Users/wanzohanzo/wkhtmltopdf/static-build/osx-cocoa-x86-64/deplibs/include -L /Users/wanzohanzo/wkhtmltopdf/static-build/osx-cocoa-x86-64/deplibs/lib
command failed: exit code 32512`

I guess it might have something to do with "fpm" rather than qt, but not sure. Any help is appreciated, thanks.

**Comment by PhilterPaper** [comment]
I'm not familiar with this build process, but the message you listed is telling you that the `../../../qt/configure` script can't be found. Check where you are running this configure script versus where "configure" is actually located. 

I don't see any mention of libpng (or png.*), "jpeg src", or "xz". Did they appear in earlier error messages? If so, I would concentrate on fixing those before you get to looking at "configure". It's conceivable that an earlier error may have left you in the wrong directory, and thus the "configure" error.

**Comment by ashkulz** [comment]
Read `INSTALL.md` -- you should clone with the `--recursive` option, qt does not seem to have been downloaded.
