### ISSUE TITLE
Not able to create snapshot for http://money.cnn.com/2015/10/29/technology/google-now-on-tap

### ISSUE THREAD

**Issue by mjalan** [wkhtmltopdf/wkhtmltopdf#2789]
This is the error "*\* (process:654123): DEBUG: NP_Initialize==============>     ] 90%
*\* (process:654123): DEBUG: NP_Initialize succeeded
"

**Comment by alloylab** [comment]
We are closing this out since we haven't heard from you. If you are still having this issue please feel free to re-open it. Thanks.
