### ISSUE TITLE
WKHTML decreasing spacing between characters when smart shrink is disabled.

### ISSUE THREAD

**Issue by ganeshvyas** [wkhtmltopdf/wkhtmltopdf#2790]
Hi

I have an issue with wkhtml while converting html to pdf. When I enable smart shrinking which is enabled by default, the resultant pdf has very small font size which is some time not legible. But when I disable smart shrinking it it generate big or normal font size but characters are so close to the each other, some characters fuse into each other. Ideally it should generate normal pdf having font size and characters spacing equal to the one in html file without bothering about the size of input file. If input file content exceed the size of pdf page size it should ignore that as user himself has disabled the smart shrinking option.

Attached is the screenshot of a string from wkhtml generated pdf file having fused characters. Any kind of help will be highly appreciated.

Regards,
Ganesh

![image](https://cloud.githubusercontent.com/assets/17141230/12924072/583eafa2-cf7e-11e5-9f13-652ecdbbfc81.png)

**Comment by alloylab** [comment]
is this still an issue on 0.12.5?
