### ISSUE TITLE
Build on Raspberrypi?

### ISSUE THREAD

**Issue by random-robbie** [wkhtmltopdf/wkhtmltopdf#2791]
Hi Guys,

The current version on raspbian is 0.9.9.

is there any guides on building for a raspberry pi.

```
Linux  4.1.10-v7+  armv7l
```

**Comment by PhilterPaper** [comment]
Have you looked at #1868 yet? There might be useful information there.

**Comment by ashkulz** [comment]
Duplicate of #1868
