### ISSUE TITLE
Signature field

### ISSUE THREAD

**Issue by xelab** [wkhtmltopdf/wkhtmltopdf#2792]
Hello, is it possible to create signature fields (for digital signature by another application) with wkhtmltopdf? I tried using the "enable-forms" option and a simple textarea but it does not work.

**Comment by ashkulz** [comment]
This is something best done as a post-processing tool after the PDF is generated.

**Comment by muziekklas** [comment]
@ashkulz  We are also searching for the possibility to generate a signature field which can be picked up by our digital signature partner but we are not post-processing the PDFs by hand. We've enabled forms and added two input[type=text] with an unique name and id but we cannot use the field. Any sights on when this will be on the roadmap? We can use it for multiple projects in our organisation.

**Comment by ashkulz** [comment]
It will probably require changes to Qt, and that's going to be tough ... please read the [project status](https://wkhtmltopdf.org/status.html) on what else needs to be done :disappointed:

**Comment by xrevenge** [comment]
@muziekklas ,
Hello, We would like to do the same thing. Have you find any solution ? We use wkhtmltopdf by snappy to generate pdf .
Regards,

**Comment by muziekklas** [comment]
@xrevenge I had to use absolute positioning on the digital Signature WebAPI we've used for this, which is not the best solution but yea.. it kinda works out?
