### ISSUE TITLE
Text overflow when move to following page

### ISSUE THREAD

**Issue by lertoo** [wkhtmltopdf/wkhtmltopdf#2794]
When the content in a table cell get moved to the following page because of page-break-inside = avoid; and there is no enough height for it, it is printed overflow over the table.

It can be re-produce by saving following content to a HTML file, then converting to PDF using the latest WkHtmlToPdf (v0.12.3.1):

<xmp>
<!DOCTYPE html>

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <title>Overflow testing</title>
</head>
<body style="font-family: Arial; font-size: 11px;">
    <div style="height: 1100px; border: solid 1px gray;">
        Space holder
    </div>
    <br />
    <table border="1" cellpadding="0" cellspacing="0" style="border-collapse: collapse;">
        <tr>
            <td style="vertical-align: middle; width: 150px;">
                <div style="page-break-inside: avoid; background-color: red; height: 200px;">
                    Box A:
                    This box will be moved to the 2nd page as page break inside it is avoid. But it is printed overflow out of the table.
                </div>
            </td>
            <td>
                <table border="0" cellpadding="0" cellspacing="0" style="border-collapse: collapse; height: 300px;">
                    <tr style="page-break-inside: avoid;">
                        <td><div style="height: 90px;">Box B:
                            The 1st row in the 1st page.
                            The height is less than the Box A.</div></td>
                    </tr>
                    <tr style="page-break-inside: avoid; border-top: solid 1px;">
                        <td><div style="height: 90px; background-color: #ddd;">Box C:
                             The 2nd row in the 2nd page. The height is less than the Box A.</div></td>
                    </tr>
                </table>
            </td>
        </tr>
    </table>
</body>
</html>
</xmp>

![overflow](https://cloud.githubusercontent.com/assets/4444524/12994921/adaed0b6-d177-11e5-9557-f8438fd3eac8.JPG)

**Comment by alloylab** [comment]
is this still an issue on 0.12.5?
