### ISSUE TITLE
Unknown character at the end of a table field

### ISSUE THREAD

**Issue by bigasbespip** [wkhtmltopdf/wkhtmltopdf#2797]
When generating a pdf file with the following HTML

`<!DOCTYPE html><html><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><style>html {font-family: sans-serif;}</style></head><body><table><tbody><tr><td colspan="5">No fi&nbsp;</td></tr></tbody></table></body></html>`

The pdf file has a square at the end of the table field, indicating an unknown unicode character.

I have attached the a screen shot of the pdf, as well as the generated PDF
[test12.pdf](https://github.com/wkhtmltopdf/wkhtmltopdf/files/130573/test12.pdf)

![screen shot 2016-02-15 at 11 25 04](https://cloud.githubusercontent.com/assets/5161383/13047411/c8c8f55a-d3d6-11e5-96ff-a261854344f8.png)

Running
wkhtmltopdf 0.12.2.1 (with patched qt)

with the following command

`wkhtmltopdf --print-media-type --page-size A4 133.html test12.pdf`

**Comment by InkUisitor** [comment]
I don't see any problem with wkhtmltopdf 0.12.3.1
And No fi is written on the same line. You have a really strange rendering...
