### ISSUE TITLE
0.5px not displayed in PDF.

### ISSUE THREAD

**Issue by Alantoo** [wkhtmltopdf/wkhtmltopdf#2798]
Hello,
I trying to render 0.5px, but it's not displayed. How can I render values with dot?
Here is my HTML:
```
<html style="width: 200pt;margin: 0;padding: 0;display: block;height: 10px;overflow: hidden;">
<head>

</head>
<body style="width: 200pt;margin: 0;padding: 0;overflow: hidden;height: 10px;">
    <div style="width: 100pt; height: 0.5px; margin: 0;padding: 0;box-sizing: border-box; background: #000;">

    </div>
</body>
</html>
```

Used command line arguments: 
`--disable-smart-shrinking --no-outline --disable-internal-links --exclude-from-outline --no-pdf-compression -T 0 -B 0 -L 0 -R 0 --page-height 835pt --page-width 695pt --dpi 1200 --zoom 1 --page-offset -1 --header-spacing 0 --footer-spacing 0 --minimum-font-size 1 "my-url-here" resultPdfNameHere.pdf`

wkhtmltopdf version - 0.12.3.1 (with patched qt)

OS: windows 7 x64 enterprise sp1

Thanks for help.

**Comment by halfnibble** [comment]
You know, I've never thought to assign a value of half a pixel. Does the line render if you change it to 1px?

**Comment by Alantoo** [comment]
Yes, integer values renders fine, but if I put decimal value it's does not render value after point. 
For example: 1.5px rendered as 1px, 15.65px rendered as 15px.

**Comment by halfnibble** [comment]
What happens if you use an **em** value like 0.05em?

**Comment by Alantoo** [comment]
If value after conversion to pixel is floating point number, then it casts to integer value.
For example: 0.75pt = 1px, 1pt = 1.33px rendered as 1px. Same situation with em.

**Comment by PhilterPaper** [comment]
Then perhaps the code should be changed to *round* to the nearest integer, rather than *truncating*. This will probably hit quite a few places. Is the conversion in question in QT or in wkHTMLtoPDF itself?

**Comment by Alantoo** [comment]
> Then perhaps the code should be changed to round to the nearest integer, rather than truncating.

Yes, I think so too.

> Is the conversion in question in QT or in wkHTMLtoPDF itself?

I don't know in what of components conversion problem.

**Comment by Yaowenjie** [comment]
Anyone still have question on this issue? (I met this problem as well)

**Comment by Lozik** [comment]
Yes having the same issue over here. I which to print out some decoration-lines which should be a lot smaller than one pixel. I'd need a 0.1mm line, 0.3 is the maximum displayed...

**Comment by PhilterPaper** [comment]
Given that one pixel is the minimum displayable entity (it's on or off, in its entirety), drawing "half a pixel" makes no sense. Half a _Point_, or half a _millimeter_, may make sense, if the result in pixels is at least 0.5. In my opinion, I would have to say that rounding **pixels** to the nearest integer value is the only thing that makes sense, unless you want to adjust the color/gray level to emulate a smaller pixel (and even then, you have to worry about addressability -- what do you do with two "half pixel" dots half a pixel apart?).

Note that a "pixel"'s size depends upon the display technology used. It could vary widely in size on a printer or display, which makes it a bad idea to use it for sizes. If you want predictable results on different printers or displays, use a length, not pixels.
