### ISSUE TITLE
Better verbose options

### ISSUE THREAD

**Issue by davidrojo** [wkhtmltopdf/wkhtmltopdf#2799]
Hello,

I have a process that generates a big pdf file from several html pages. Then I have other process that checks the status of the first process.

Watching the command ouput i can know in which step the process is as it shows "Loading pages (1/6)" but in this steps the command shows a progress bar from 0 to 100% but doesn't show wich page is processing, as when processing a new html page the progress bar returns to zero.

It could be interesting to show something like this:

```
Loading pages (1/6)
File 1/10 [==============] 100%
File 2/10 [==============] 100%
File 3/10 [======>       ] 50%
```

So we can see wich page is being processed and the overall process completed status.

**Comment by alloylab** [comment]
We are closing this out since we haven't heard from you. If you are still having this issue please feel free to re-open it. Thanks.
