### ISSUE TITLE
SSL handshake error when loading jQuery over https

### ISSUE THREAD

**Issue by wbrefvem** [wkhtmltopdf/wkhtmltopdf#2800]
The HTML I'm converting has some javascript that uses jQuery. If I load the jQuery script over [http](http://code.jquery.com/jquery-1.11.3.min.js), everything works fine, but if I use [https](https://code.jquery.com/jquery-1.11.3.min.js), I get an SSL handshake error:
`Exit with code 1 due to network error: SslHandshakeFailedError`  

The issue occurs on Ubuntu 14.04.3 as well as OS X 10.11.3 with multiple versions of wkhtmltopdf, and it did not occur prior to last week (i.e., https worked without incident on both platforms). Other JS libraries load just fine over https. These facts would make me inclined to blame an expired cert on jQuery's side, but browsers don't complain when loading the same url, so that seems unlikely. I'm well stumped and have no further insight.

**Comment by alloylab** [comment]
is this still an issue on 0.12.5?

**Comment by wbrefvem** [comment]
Not sure. I was working on this two jobs ago and haven't touched it in awhile. :)

**Comment by alloylab** [comment]
Okay well if you come across this issue again please let us know
