### ISSUE TITLE
wkhtmltoimage_global_settings Will Not Allow crop.*, load.*, web.* settings

### ISSUE THREAD

**Issue by carsonreinke** [wkhtmltopdf/wkhtmltopdf#2802]
`wkhtmltoimage_set_global_setting` and `wkhtmltoimage_get_global_setting` always returns 0 for [crop._, load._, web.*](http://wkhtmltopdf.org/libwkhtmltox/pagesettings.html) settings via the C API.  The "dot" settings do work for wkhtmltopdf though.

I tested with master using the example and it also returned 0 for these.  I tried the binary with `--crop-w` and that worked just fine.

**Comment by alloylab** [comment]
is this still an issue on 0.12.5?
