### ISSUE TITLE
Sprite Images are not working in svg

### ISSUE THREAD

**Issue by viswa18** [wkhtmltopdf/wkhtmltopdf#2805]
Hi
I have convert html to svg using 12.4 binaries in windows 8. In svg output sprite images are not working properly.

Thanks
Viswa

**Comment by viswa18** [comment]
I have attached input and output document

[spritesproblem.zip](https://github.com/wkhtmltopdf/wkhtmltopdf/files/137500/spritesproblem.zip)

**Comment by viswa18** [comment]
Here I have attached input and output documents
[spritesproblem.zip](https://github.com/wkhtmltopdf/wkhtmltopdf/files/137503/spritesproblem.zip)

**Comment by Abubakr077** [comment]
what was the solution? 
same happened with me in windows but working fine in Linux
