### ISSUE TITLE
Optimize pdf containing 100-120 pages and many svg 

### ISSUE THREAD

**Issue by stimcon-dev** [wkhtmltopdf/wkhtmltopdf#2807]
Hi @ashkulz,

We are using wkhtmltopdf for pdf generation it's working fine for less than 60-80 pages.
But we need to generate single pdf with 100-120 page and pdf is containing many highcharts svg(approx 90-100) and html tables so how can we optimize pdf generation ?

Thanks in advance

**Comment by PhilterPaper** [comment]
What do you mean by "optimize"? Is wkHTMLtoPDF *failing* to produce a PDF for the larger input? Are there any specific error messages? I believe there have been a number of discussions about such failures, so you may want to move this discussion to an existing thread, or at least cross reference it. On the other hand, is it producing a correct PDF for the larger input, but there's something undesirable about the finished product (thus the need to *optimize* it)?
