### ISSUE TITLE
Can wkhtmltopdf password protect the PDF?

### ISSUE THREAD

**Issue by victropolis** [wkhtmltopdf/wkhtmltopdf#2808]
Can wkhtmltopdf password protect the PDF?

**Comment by victropolis** [comment]
Can wkhtmltopdf password protect the PDF?

**Comment by nrhirani** [comment]
wkhtmltopdf does not support password protection, you need to do it in a second pass. i.e, convert html --> pdf using wkhtmltopdf and then use [qpdf](http://qpdf.sourceforge.net) or similar libraries to convert pdf --> password protected pdf.  If you are using [node.js](http://nodejs.org/en) then there is a wrapper around it [node-qpdf](https://github.com/nrhirani/node-qpdf)
