### ISSUE TITLE
Remove spaces from all four sides of pdf

### ISSUE THREAD

**Issue by revathyradhakrishnan** [wkhtmltopdf/wkhtmltopdf#2810]
I am using wkhtmltopdf to convert html to pdf. Html page also contains information to be displayed as footer. Hence no need to set footer using wkhtmltopdf. But the problem I am facing is , the pdf page has got spaces on all four sides( I think default margins). How can I fit the content to the page so that the footer comes exactly at the bottom.

**Comment by apoorvapakhle-porter** [comment]
-B, --margin-bottom <unitreal>      Set the page bottom margin
  -L, --margin-left <unitreal>        Set the page left margin (default 10mm)
  -R, --margin-right <unitreal>       Set the page right margin (default 10mm)
  -T, --margin-top <unitreal>         Set the page top margin

options = {
            'page-size': 'A4',
            'margin-top': '0in',
            'margin-right': '0in',
            'margin-bottom': '0in',
            'margin-left': '0in',
            'encoding': "UTF-8",
            'no-outline': None
        }
 

> pdfkit.from_file(inputFile,

 outputFile, options=options)
You can change the height and width of your page if your data does not fit.
'page-width' : '8.26in',
'page-height' :  '11.8in',
The default sizes are given on ['Paper Size Constants'](http://doc.qt.io/qt-4.8/qprinter.html#PaperSize-enum)
The documentation for wkhtmltopdf is available on [`wkhtmltopdf Documentation`](https://wkhtmltopdf.org/usage/wkhtmltopdf.txt)

**Comment by Tomsgu** [comment]
Closing as the response was provided.
