### ISSUE TITLE
White ribbon between pages

### ISSUE THREAD

**Issue by ZSimon** [wkhtmltopdf/wkhtmltopdf#2817]
When exporting html to pdf there is about 2 mm white ribbon at the end of the page.
I have split the content on 2 pages but even then, there is 2 mm white space between pages as you can see from the image:

![image](https://cloud.githubusercontent.com/assets/5880095/13379998/8ba2c7b8-de36-11e5-8ed2-c871fa92fc11.png)

When exporting, I have parameters: -T 0 -B 0 -L 0 -R 0

Any idea?

**Comment by alloylab** [comment]
is this still an issue on 0.12.5?

**Comment by 1pavanb** [comment]
yes @alloylab 

wkhtmltopdf 0.12.6 (with patched qt)

```
echo "<body style='background-color:black;padding=0;margin=0'>" | wkhtmltopdf -T 0 -B 0 -L 0 -R 0 --disable-smart-shrinking - bad.pdf
```
