### ISSUE TITLE
Update auto-generated docs wkhtmltopdf.txt

### ISSUE THREAD

**Issue by kapsiR** [wkhtmltopdf/wkhtmltopdf#2818]
Please provide updated docs for 0.12.3.1 at wkhtmltopdf.org/usage/wkhtmltopdf.txt

Missing flags (with default value documentation):
--bypass-proxy-for 
--keep-relative-links 
--resolve-relative-links

Thanks for your great work!

**Comment by tractorcow** [comment]
I too am looking for --bypass-proxy-for documentation, thank you. :)

Added https://github.com/wkhtmltopdf/wkhtmltopdf/commit/7ffec76429e5db82f24293ac441efe2a9f2bb1d4

**Comment by ashkulz** [comment]
I think these are already documented?
