### ISSUE TITLE
TOC "--xsl-style-sheet" not working when used with "cover"

### ISSUE THREAD

**Issue by hocongly** [wkhtmltopdf/wkhtmltopdf#2821]
I'm using wkhtml 0.12.3 and I can't get table of contents working when I include a cover page and specify my custom XSL file. 

Without specifying a cover page, my TOC works fine.
ex: wkhtmltopdf toc --xsl-style-sheet custom.xsl test.html test.pdf 

With a cover page, the cover page renders but I get a blank page for TOC.
ex. wkthmltopdf cover cover.html toc --xsl-style-sheet test.html test.pdf

Has anyone encountered this issue and know of a resolution?

Thank you,
Lee

**Comment by icnocop** [comment]
It seems you forgot to pass `custom.xsl` in your command line arguments.

For example, `wkthmltopdf cover cover.html toc --xsl-style-sheet custom.xsl test.html test.pdf`

**Comment by Tomsgu** [comment]
Closing as there is no feedback.

**Comment by yishaistreamline** [comment]
Maybe someone can answer [my question](https://stackoverflow.com/questions/69366504/generate-table-of-contents-with-pdfkit-for-python). Thank you!
