### ISSUE TITLE
Indefinite hang on webpages with certain kinds of javascript

### ISSUE THREAD

**Issue by Tenari** [wkhtmltopdf/wkhtmltopdf#2822]
I have seen this sporadically work but it mostly fails.

```
Daniels-MacBook-Pro:dash tenari$ wkhtmltopdf --debug-javascript --print-media-type app.peoplepattern.com/signin blah.pdf
Loading pages (1/6)
Warning: undefined:0 TypeError: 'undefined' is not a function
Warning: https://maps.google.com/maps-api-v3/api/js/24/1/util.js:22 Google Maps API warning: SensorNotRequired https://developers.google.com/maps/documentation/javascript/error-messages#sensor-not-required
content-type missing in HTTP POST, defaulting to application/x-www-form-urlencoded. Use QNetworkRequest::setHeader() to fix this problem.
content-type missing in HTTP POST, defaulting to application/x-www-form-urlencoded. Use QNetworkRequest::setHeader() to fix this problem.
^C===================================================>       ] 88%
Daniels-MacBook-Pro:dash tenari$ ./bin/wkhtmltopdf-osx --debug-javascript --print-media-type app.peoplepattern.com/signin blah.pdf
Loading pages (1/6)
Warning: undefined:0 TypeError: 'undefined' is not a function
content-type missing in HTTP POST, defaulting to application/x-www-form-urlencoded. Use QNetworkRequest::setHeader() to fix this problem.
Warning: https://maps.google.com/maps-api-v3/api/js/24/1/util.js:22 Google Maps API warning: SensorNotRequired https://developers.google.com/maps/documentation/javascript/error-messages#sensor-not-required
^C====================================================>      ] 89%
Daniels-MacBook-Pro:dash tenari$ wkhtmltopdf -V
wkhtmltopdf 0.12.2.1 (with patched qt)
Daniels-MacBook-Pro:dash tenari$ ./bin/wkhtmltopdf-osx -V
wkhtmltopdf 0.12.3 (with patched qt)
```

As you can see I tried it with two recent versions on the 64-bit mac osx binaries. I can get the page to render perfectly if I disable javascript with the `-n` option, but that does not work for all pages on our site, as some need javascript to run. If you need more information I will be happy to provide. This might be a duplicate of https://github.com/wkhtmltopdf/wkhtmltopdf/issues/2254, I am not sure. At any rate this should be a reproducible test case.

**Comment by PhilterPaper** [comment]
I would start combing through the JS to see why one or more variables are "undefined". Are their declarations missing? Are they never given values? Can you find why they work in some instances and not in others (perhaps a timing issue)? After that's fixed, if you still seem to have some issues with bad calls to the Google Maps interface, or maybe a form submission, you would have to fix those.

**Comment by Tenari** [comment]
So all javascript on the page has to work+load fully for the page to render? That seems a little brittle

I tried a time allowance and got the same hang:
```
Daniels-MacBook-Pro:dash tenari$ ./bin/wkhtmltopdf-osx --debug-javascript --javascript-delay 5000 --print-media-type app.peoplepattern.com/signin blah.pdf
Loading pages (1/6)
Warning: undefined:0 TypeError: 'undefined' is not a function
Warning: https://maps.google.com/maps-api-v3/api/js/24/1/util.js:22 Google Maps API warning: SensorNotRequired https://developers.google.com/maps/documentation/javascript/error-messages#sensor-not-required
content-type missing in HTTP POST, defaulting to application/x-www-form-urlencoded. Use QNetworkRequest::setHeader() to fix this problem.
[=====================================================>      ] 89%
```

**Comment by DanielCeregatti** [comment]
Brittle? You have to understand what wkhtmltopdf (which is effectively just a web browser) can, and can't, do. A normal web page issues the DOMContentLoaded event when the DOM is done. As I understand it, this is what causes wkhtmltopdf to consider the page as being "done" by default. If your page relies on javascript to render elements, then yes, you must wait for javascript to finish. To do that you must specify either an arbitrary delay (--javascript-delay 5000) or a more deterministic method (--window-status foo).

Anyhow, sounds like you're running into #2254.

**Comment by jhonplanner** [comment]
Hey @Tenari @DanielCeregatti is there any workaround for this issue? i am also getting the same issue.

**Comment by Tenari** [comment]
yeah, @jhonplanner, use http://phantomjs.org/screen-capture.html

**Comment by Tomsgu** [comment]
Closing as it's a duplicate.
