### ISSUE TITLE
umlauts issue in IE

### ISSUE THREAD

**Issue by manishjaingit** [wkhtmltopdf/wkhtmltopdf#2824]
Hello geeks, 
        I am using wkhtmltopdf since a while and for most of the browser is supporting umlauts " NoäötwoüßÄrkÖiÜánàg " as it is , but in case of IE it is not going to have this, as in place of this umlauts text it showing " notworking ". i am using core wkhtmltopdf tool directly with shell_exec function in php. 
`$cmd = "--header-html ";
$cmd .= " \"$url\" ";
$cmd .= "  --header-spacing 0 --footer-line --footer-spacing 5 --footer-left ";
$cmd .= ' "company name" ';
$cmd .= " --footer-center ";
$cmd .= ' "[page] / [toPage]" ';
$cmd .= " --orientation Portrait --user-style-sheet bootstrap.css --page-size A4 --encoding utf-8 --margin-top 0mm --margin-bottom 2mm --margin-left 5mm --margin-right 5mm ";
$cmd .= "  \"$url\" ";
$cmd .= " $filePath && $filePath ";`

**Comment by PhilterPaper** [comment]
What do you mean by "not working"? Are you seeing a ?-in-black-diamond glyph in place of an accented character? That means your text is actually Latin-1 (or Windows-1252) encoded, but you're trying to display it in UTF-8. Get the page fixed so browsers show it correctly, before trying to get wkHTMLtoPDF working. Be careful of punctuation marks and a few accented characters found in the x80-x9F "Smart Quotes" range of Windows-1252, which doesn't match Latin-1.

By the way, what you show are not "umlauts". They are accented (non-ASCII) characters. "Umlaut" is the German name for the double-dot accent mark (more generally, a "diaeresis"), or more technically, its usage to modify a vowel sound.

Finally, please use markdown to cleanly show code (blank line before and after, and indented 4 spaces, ***or*** surrounded by backticks).

    $cmd = "--header-html "; 
    $cmd .= " \"$url\" "; 
    $cmd .= " --header-spacing 0 --footer-line --footer-spacing 5 --footer-left "; 
    $cmd .= ' "company name" '; 
    $cmd .= " --footer-center "; 
    $cmd .= ' "[page] / [toPage]" '; 
    $cmd .= " --orientation Portrait --user-style-sheet bootstrap.css --page-size A4 --encoding utf-8 --margin-top 0mm --margin-bottom 2mm --margin-left 5mm --margin-right 5mm "; 
    $cmd .= " \"$url\" "; 
    $cmd .= " $filePath && $filePath ";

**Comment by Tomsgu** [comment]
Closing as there is no feedback.
