### ISSUE TITLE
How to use Multiple CSS 

### ISSUE THREAD

**Issue by khan789** [wkhtmltopdf/wkhtmltopdf#2826]
Hi ,
I'm having trouble with multiple css. Is there a option to specifiy multiple style sheets in the command line.

Currently I tried 2 different ways, but it only considering the last style sheet specified in the argument
1. specifiying option multiple times

.\wkhtmltopdf.exe --user-style-sheet file:///C:{mypath}\styles\application.min.css --user-style-sheet file:///C:{mypath}\styles\react-datagrid.min.css C:\temp\TestPage\TestPage.html C:\temp\TestPage\TestPage02.pdf
1. using quotations

.\wkhtmltopdf.exe --user-style-sheet "file:///C:{mypath}\styles\application.min.css file:///C:\LIC\minda\reports{mypath}\styles\react-datagrid.min.css" C:\temp\TestPage\TestPage.html C:\temp\TestPage\TestPage02.pdf

Please can some one tell how to specify multiple style sheets?

Note: {mypath} is actual path, I just called mypath,intentionally to not to write physical path on this page.

**Comment by djlerman** [comment]
I am also looking for a solution to this.

**Comment by NicoBarbaros** [comment]
why not have a structure like this. 

main.css
_partial1.css
_partial2.css

And then import this 2 partials in the main file.
