### ISSUE TITLE
Building from source for Ubuntu Vivid (v.15)

### ISSUE THREAD

**Issue by mmattdugan** [wkhtmltopdf/wkhtmltopdf#2828]
I am trying to build wkhtmltopdf from source on Ubuntu Vivid (v.15) due to the "QXcbConnection: Could not connect to display" error

INSTALL.md says "for linux distributions not listed above use the posix-local target" however there is no other information given regarding what the posix-local target is. But there is a 'generic' target listed. Would that be it?

**Comment by msavoury** [comment]
@mmattdugan - Did you ever get this working?

**Comment by mmattdugan** [comment]
Yes, but I don't remember how. You have the same problem, or trying to help?

**Comment by mmattdugan** [comment]
I believe I used the generic target I mentioned above, and it worked.

**Comment by msavoury** [comment]
No, I am having a different problem and if you figured this problem out I thought it might make sense to ask you for some assistance

**Comment by mmattdugan** [comment]
You can try but I dont have much experience with it either :)
