### ISSUE TITLE
Use wkhtmltopdf to gernate pdf from xml file? 

### ISSUE THREAD

**Issue by grassit** [wkhtmltopdf/wkhtmltopdf#2829]
Is it possible to use wkhtmltopdf to gernate pdf from xml file? 

I tried the following example, but the pdf file doesn't look right.

```bash
wkhtmltopdf http://google.github.io/styleguide/shell.xml ../shell.pdf
```

Thanks.`

**Comment by DuyguC** [comment]
Hi,
I have the same problem, does anyone have a solution?
Thanks in advance.

**Comment by PhilterPaper** [comment]
I can get that .xml to render under Firefox, but it dies in wkHTMLtoPDF at 10% of page load. How are you running it, and what wkHTMLtoPDF version? How far does it get that it "doesn't look right"?

wkHTMLtoPDF uses an old WebKit browser engine, and it's possible that it simply chokes on XML input. I'm not aware of its having been updated to handle XML input, but perhaps it gets further than it used to...

**Comment by Tomsgu** [comment]
Closing as there is no feedback and no example.
