### ISSUE TITLE
table page-break not display well

### ISSUE THREAD

**Issue by Awakening-j** [wkhtmltopdf/wkhtmltopdf#2831]
table cross page, wkhtmltopdf will add header automatically, but it looks not well  
like the screenshot below, how to fix it?  
![1 pic](https://cloud.githubusercontent.com/assets/8085088/13728501/f05440a4-e955-11e5-839d-26ccfb2c0044.jpg)

**Comment by PhilterPaper** [comment]
If what you're seeing is table cell content overprinting a table header (after a page break), that is a well known problem. There are many bug reports open for it, and you might want to look at some of them.

**Comment by Awakening-j** [comment]
@PhilterPaper Oh my god......

**Comment by Awakening-j** [comment]
find solution https://github.com/wkhtmltopdf/wkhtmltopdf/issues/2756
