### ISSUE TITLE
wkhtmltopdf -H in Chinese

### ISSUE THREAD

**Issue by alloylab** [wkhtmltopdf/wkhtmltopdf#2833]
the wkhtmltopdf -H command output is in Chinese... any ideas how to change it to English?

compiled qt & wkhtmltopdf from github on Alpine Linux 3.3

Thanks

**Comment by alloylab** [comment]
still having no luck resolving this issue... tried setting the following env vars
LC_ALL=en_US.utf8
LANG=en_US.utf8

any ideas?

**Comment by PhilterPaper** [comment]
Is this with a vanilla (stock) wkHTMLtoPDF install? Mine (on Windows) gives English. Is your machine set up to use Chinese as its default language? Are you sure it's Chinese (e.g., a sample of it translates correctly on Google Translate) and not just random gibberish that looks "Chinese"?

**Comment by alloylab** [comment]
yes vanilla stock install of wkhtmltopdf with patched qt
git clone --recursive https://github.com/wkhtmltopdf/wkhtmltopdf.git /tmp/wkhtmltopdf

no my machine is set to use english

it very well could be gibberish... google translate can make heads or tails of it
Here is come of the ouput running wkhtmltopdf -H
/ # wkhtmltopdf -H
You need to specify at least one input file, and exactly one output file
Use - for stdin or stdout

一愀洀攀:
  眀欀栀琀洀氀琀漀瀀搀昀 　⸀㄀㈀⸀㐀ⴀ搀攀瘀 ⠀眀椀琀栀 瀀愀琀挀栀攀搀 焀琀⤀

匀礀渀漀瀀猀椀猀:
  眀欀栀琀洀氀琀漀瀀搀昀 嬀䜀䰀伀䈀䄀䰀 伀倀吀䤀伀一崀⸀⸀⸀ 嬀伀䈀䨀䔀䌀吀崀⸀⸀⸀ 㰀漀甀琀瀀甀琀 昀椀氀攀㸀
  
䐀漀挀甀洀攀渀琀 漀戀樀攀挀琀猀:
  眀欀栀琀洀氀琀漀瀀搀昀 椀猀 愀戀氀攀 琀漀 瀀甀琀 猀攀瘀攀爀愀氀 漀戀樀攀挀琀猀 椀渀琀漀 琀栀攀 漀甀琀瀀甀琀 昀椀氀攀Ⰰ 愀渀 漀戀樀攀挀琀 椀猀
  攀椀琀栀攀爀 愀 猀椀渀最氀攀 眀攀戀瀀愀最攀Ⰰ 愀 挀漀瘀攀爀 眀攀戀瀀愀最攀 漀爀 愀 琀愀戀氀攀 漀昀 挀漀渀琀攀渀琀⸀  吀栀攀 漀戀樀攀挀琀猀
  愀爀攀 瀀甀琀 椀渀琀漀 琀栀攀 漀甀琀瀀甀琀 搀漀挀甀洀攀渀琀 椀渀 琀栀攀 漀爀搀攀爀 琀栀攀礀 愀爀攀 猀瀀攀挀椀昀椀攀搀 漀渀 琀栀攀
  挀漀洀洀愀渀搀 氀椀渀攀Ⰰ 漀瀀琀椀漀渀猀 挀愀渀 戀攀 猀瀀攀挀椀昀椀攀搀 漀渀 愀 瀀攀爀 漀戀樀攀挀琀 戀愀猀椀猀 漀爀 椀渀 琀栀攀 最氀漀戀愀氀
  漀瀀琀椀漀渀猀 愀爀攀愀⸀ 伀瀀琀椀漀渀猀 昀爀漀洀 琀栀攀 䜀氀漀戀愀氀 伀瀀琀椀漀渀猀 猀攀挀琀椀漀渀 挀愀渀 漀渀氀礀 戀攀 瀀氀愀挀攀搀 椀渀
  琀栀攀 最氀漀戀愀氀 漀瀀琀椀漀渀猀 愀爀攀愀

**Comment by PhilterPaper** [comment]
I'm not sure what's going on, but I did discover something interesting about the "text" you posted. Starting with **Name:**, each character is the 16-bit UTF-16 code *byte swapped*. "Name" should be 0046 0061 006D 0065, but the boxes on my screen are 4600 6100 6D00 6500, which are all in the CJK section of Unicode (used in Chinese and Japanese Kanji). I don't have any Chinese/CJK fonts installed, so I only see the boxes with 4 hex digits. Oddly enough, the first two lines of the error message display fine, as does the colon : after Name!

Not all the character boxes line up with the regular English text, so it may be that some are being interpreted as escape codes or something. Why else would ASCII text be turned into 16-bit Unicode? All I can guess at this point is that your wkHTMLtoPDF image got very corrupted at some point, possibly during FTP. You might try reinstalling with a fresh copy, being very careful about file transfer. I don't know what the help text was originally -- I would suppose it's pure ASCII (single byte characters), so how it got into 16-bit Unicode *and* byte swapped is ....?

If this is a Linux box, maybe your terminal definition is screwy or corrupted. Does anything like this happen with other programs that write to the console (STDOUT)?

**Comment by alloylab** [comment]
I have no idea how it got into 16-bit Unicode and byte swapped

its an alpine linux 3.3 box and qmake -H displays just fine when outputting to the console... and I installed qmake from wkhtmltopdf/qt

I just tried re-downloading it instead of using git clone --rescursive on an image where I had already compiled and installed patched qt. Also did an md5 hash of the zip file to verify the download and tried installing it with no luck... still getting the same 16-bit Unicode and byte swapped text

when I install it from the repo (apk add wkhtmltopdf) it works just fine... except its using vanilla QT... and I need the patched qt

**Comment by alloylab** [comment]
solved, issue had to do with byte order...little endian vs. big endian

new code, wkhtmltopdf/qt/src/corelib/codecs/qiconvcodec.cpp 
if defined(Q_OS_HPUX)
#  define NO_BOM
#  define UTF16 "ucs2"
#elif defined(Q_OS_AIX)
#  define NO_BOM
#  define UTF16 "UCS-2"
#elif defined(Q_OS_FREEBSD) || defined(Q_OS_MAC) || (defined(Q_OS_LINUX) && !defined(__GLIBC__))
#  define NO_BOM
#  if Q_BYTE_ORDER == Q_BIG_ENDIAN
#    define UTF16 "UTF-16BE"
#  else
#    define UTF16 "UTF-16LE"
#  endif
#else
#  define UTF16 "UTF-16"
#endif

patch
--- ./src/3rdparty/webkit/Source/WebCore/platform/graphics/qt/FontPlatformDataQt.cpp.orig
+++ ./src/3rdparty/webkit/Source/WebCore/platform/graphics/qt/FontPlatformDataQt.cpp	
@@ -45,7 +45,8 @@
     QFont& font = m_data->font;
     int requestedSize = qRound(description.computedPixelSize());
     font.setFamily(familyName);
-    font.setPixelSize(qRound(requestedSize));
+    if (requestedSize)
+    	font.setPixelSize(qRound(requestedSize));
     font.setItalic(description.italic());
     font.setWeight(toQFontWeight(description.weight()));
     font.setWordSpacing(wordSpacing);
