### ISSUE TITLE
checksum mismatch for x, aborting

### ISSUE THREAD

**Issue by golightlyb** [wkhtmltopdf/wkhtmltopdf#2837]
I can build successfully for Linux targets from debian stable.

Trying to target windows using `scripts/build.py mingw-w64-cross-win64` (and the 32 bit version as well) gives me:

`Checksum mismatch for openssl-1.0.2f.tar.gz, aborting.`

The checksum in build.py seems correct, it matches the one given on the OpenSSL website.

What's the best way to proceed? Can I replace this file manually, and if so where?

Many thanks

**Comment by alloylab** [comment]
is this still an issue on 0.12.5?
