### ISSUE TITLE
Apache Error Log

### ISSUE THREAD

**Issue by sesgue** [wkhtmltopdf/wkhtmltopdf#2838]
Hi, everything I render a html file, in the error log file appears this: 
"Loading pages (1/6)
Counting pages (2/6)
Resolving links (4/6)
Loading headers and footers (5/6)
Printing pages (6/6)
Done "

How to avoid it?

Thnks in advance

**Comment by PhilterPaper** [comment]
If these "Loading pages" messages are being output to STDERR (to avoid buffering delays), perhaps you can just redirect them into a file, or even to the trash (`2>stderrmsg.log` or `2>&1` or `2>/dev/null`). On your system, they may be logged ("error log") by default. You probably *want* to see them on the screen, so maybe you can do something with your OS configuration to avoid capturing STDERR to an error log file (in just this case). On some OS's, you might "tee" STDERR output to both a file and the screen. You'll probably have to play around a bit with it, but I suspect the primary problem is that STDERR output is being logged (by default) by your OS.

**Comment by Tomsgu** [comment]
Closing as the answer should be clear.
