### ISSUE TITLE
--footer-html chops the content line-by-line 

### ISSUE THREAD

**Issue by maxaug** [wkhtmltopdf/wkhtmltopdf#2841]
Hello there,

I am trying to use the newest version of the wkhtmltopdf to generate PDFs based on bootstrap. 
It works fine unless I include --footer-html because then the main content gets chopped line by line as you can see in this picture. Do you know any workaround for this issue?

This is on OS X 10.11.3

**Screenshot.**

<img width="656" alt="zrzut ekranu 2016-03-17 o 17 52 30" src="https://cloud.githubusercontent.com/assets/9210039/13853871/125fdb16-ec69-11e5-8f42-8ffabbd507c3.png">

**Footer code.**
It breaks after insertion of any HTML tag. 

```
<head>
    <link rel="stylesheet" type="text/css" href="./css/bootstrap.css">
    <link rel="stylesheet" type="text/css" href="./css/bootstrap-theme.css">
    <link href='https://fonts.googleapis.com/css?family=Lato:400,300,700' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="./css/reports.css">
    <link rel="stylesheet" href="./css/flag-icon.min.css">
</head>
<body>
        <footer class="container">
            <div class="row">
                <div class="col-xs-9"><p><small>Created on 03/14/2016 </small></p></div>
                <div class="col-xs-3" class="bottom_buffer">
                    <img src="./img/logo.png" alt="">
                </div>
            </div>
            </footer>
        </div>

    </div>
</body>
```

**Comment by alloylab** [comment]
is this still an issue on 0.12.5?
