### ISSUE TITLE
Pass x-access-token HTTP Header

### ISSUE THREAD

**Issue by intensite** [wkhtmltopdf/wkhtmltopdf#2845]
The page I would like to render to pdf is on a server that expects a JSON Web Token in the request HTTP header :  x-access-token.

Is it possible to pass a x-access-token HTTP Header as an option to wkhtmltopdf along with the url.

Thanks for your wonderful software.

Stephen..

**Comment by DanielCeregatti** [comment]
$ wkhtmltopdf -H
...
--custom-header <name> <value>  Set an additional HTTP header (repeatable)
...

**Comment by ashkulz** [comment]
Thanks, @DanielCeregatti.
