### ISSUE TITLE
Image settings crop does not work with wkhtmltoimage_set_global_setting

### ISSUE THREAD

**Issue by jimmytaker** [wkhtmltopdf/wkhtmltopdf#2849]
I expected to set this using:
wkhtmltoimage_set_global_setting(gSett, "crop.width", "20");
This however does not work.
My workaround is:
struct CropSettings {
    //! Cropping left/x coord
    int left;
    //! Cropping top/y coord
    int top;
    //! Cropping width/w dime
    int width;
    //! Cropping height/h dime
    int height;
};
and then
CropSettings\* crop = (CropSettings*) gSett;
after which:
crop->height = 50;
works.
You might want to look into these 
set_global_setting functions as they seem to have many shortcomings. See also my report on viewportSize

**Comment by alloylab** [comment]
is this still an issue on 0.12.5?
