### ISSUE TITLE
wkhtmltopdf_set_global_setting(gSett, "viewportSize", "1280x1024") returns 0

### ISSUE THREAD

**Issue by jimmytaker** [wkhtmltopdf/wkhtmltopdf#2850]
I came to need this, when I tried to convert www.maxqda.de and got the mobile version. Then I found a report somewhere that setting --viewport-size 1280x1024 fixes it. And it does, but this is not usable with the .dll.
wkhtmltopdf_set_global_setting(gSett, "viewportSize", "1280x1024")
returns 0
I tried debugging this in the code, but could not do it, because my qtcreator hangs for some reason every time i try something with: ReflectImpl
I built a workaround:
bool PdfGlobal::set(const char \* name, const QString & value) {
    if (QString(name) == "viewportSize") {
        viewportSize = value;
        return true;
    }
    ReflectImpl<PdfGlobal> impl(*this);
    return impl.set(name, value);
}
This works for my case, but I would not propose it to be added to git... You might want to look into the set_global_setting functions as these leave a lot to be desired. See also my report on CropSettings for Images.

**Comment by alloylab** [comment]
is this still an issue on 0.12.5?
