### ISSUE TITLE
Build errors openssl and moc

### ISSUE THREAD

**Issue by jimmytaker** [wkhtmltopdf/wkhtmltopdf#2851]
Due to the shortcoming I found in set_global_setting function for viewportSize I ended up patching and building from source. Not without trouble. 2 problems:
1. Openssl has obviously changed location - simple enough fix for this in build.py:
-        'url'   : 'https://openssl.org/source/openssl-1.0.2f.tar.gz',
-        'url'   : 'https://openssl.org/source/old/1.0.2/openssl-1.0.2f.tar.gz',
- The second I could not fix - I get 3 compile errors like this:
  tmp\moc\release_static\moc_SocketStreamHandlePrivate.cpp(9) : fatal error C1083:
  Cannot open include file: '../../../../../../../../../../../../qt/src/3rdparty/
  webkit/Source/WebCore/platform/network/qt/SocketStreamHandlePrivate.h': No such
  Weird enough, the file is there...
  I get this error for: moc_SocketStreamHandlePrivate.cpp, moc_NotificationPresenterClientQt.cpp and moc_NetworkStateNotifierPrivate.cpp.
  My workaround is editing the files and putting the absolute path instead of the relative one, but this is no fix for git, as these are generated files... To me it seems as if so many "../../.." do not work. I used VS 2013 Community edition Update 4 from the link you provided in INSTALL.md.

**Comment by ashkulz** [comment]
I suspect you have a problematic build environment, as I am able to download the file from the location. Also, not able to reproduce the error -- can you post the complete build log as a gist so that it can be verified?

**Comment by ashkulz** [comment]
Please open a new issue in [wkhtmltopdf/packaging](https://github.com/wkhtmltopdf/packaging) if you want to continue this discussion.
