### ISSUE TITLE
Compile error on OS X 10.11 CMGetProfileByAVID

### ISSUE THREAD

**Issue by jimmytaker** [wkhtmltopdf/wkhtmltopdf#2852]
The error is described here:
https://github.com/Homebrew/homebrew/issues/40585
Solution is here:
https://gist.github.com/ejtttje/7163a9ced64f12ae9444

**Comment by ashkulz** [comment]
Can you create a PR for this? wkhtmltopdf/qt#19 by @c9s targeted the wrong branch.

**Comment by ashkulz** [comment]
Fixed via wkhtmltopdf/qt@6f025714379c0c004395fcde47396780b84716e3
