### ISSUE TITLE
Mac Crash / Hang

### ISSUE THREAD

**Issue by jimmytaker** [wkhtmltopdf/wkhtmltopdf#2853]
[WkhtmltopdfBugDemo.zip](https://github.com/wkhtmltopdf/wkhtmltopdf/files/189089/WkhtmltopdfBugDemo.zip)
This application demonstrates a bug in wkhtmltox which makes the dylib unusable from within a Qt 5 application.
To reproduce simply, copy libwkhtmltox.0.12.3.dylib in the bin dir or fix the path in the .pro file, compile and run with Qt 5 (I have 5.5).
Read my comment in Dialog::Release.

**Comment by alloylab** [comment]
is this still an issue on 0.12.5?
