### ISSUE TITLE
Unicode support for the .dll is not there

### ISSUE THREAD

**Issue by jimmytaker** [wkhtmltopdf/wkhtmltopdf#2856]
Most problematic with the param "out":
CAPI(int) wkhtmltopdf_set_global_setting(wkhtmltopdf_global_settings \* settings, const char \* name, const char \* value) {
    return reinterpret_cast<settings::PdfGlobal *>(settings)->set(name, value); //This is implicitly QString(value), which is QString::fromLatin1(value).
}
I suggest the following change:
- \param value The new value for the setting (UTF-8 encoded)
- \returns 1 if the setting was updated successfully and 0 otherwise.
  */
  CAPI(int) wkhtmltopdf_set_global_setting(wkhtmltopdf_global_settings \* settings, const char \* name, const char \* value) {
  return reinterpret_cast<settings::PdfGlobal *>(settings)->set(name, QString::fromUtf8(value));
  }

**Comment by alloylab** [comment]
is this still an issue on 0.12.5?
