### ISSUE TITLE
border around appearing in PDF while no in html page

### ISSUE THREAD

**Issue by hoshoo21** [wkhtmltopdf/wkhtmltopdf#2859]
Hi 
I have page http://cvldev.isni.co/Print.aspx?p=eyJBc3NldExpc3QiOiI3MiIsIlJlcG9ydENvZGUiOiJBQ0FOIiwiRGF0ZUZyb20iOiIxOC8xMS8yMDE1IDAwOjAwIiwiRGF0ZVRvIjoiMTgvMTEvMjAxNSAyMzo1OSIsIkxhc3RSZXBvcnRlZCI6IjI0IiwiU2hvd0FsbCI6ZmFsc2UsIlNwZWVkVHJlc2hvbGQiOjAsIlJlcG9ydFR5cGUiOiIiLCJGdWVsUHJpY2VQZXJMaXRlciI6MSwiQ2hhcnRUeXBlIjoiQ29sdW1uM0QifQ==
For which i have generated PDF but borders are appearing on charts in PDF .
![borders](https://cloud.githubusercontent.com/assets/4757063/14065162/78285114-f3d3-11e5-9308-530aedc7bc06.png)

**Comment by PhilterPaper** [comment]
Just a wild guess, but I notice that on my browser, the page loads Flash and animates the display. Maybe WebKit by default puts a border around Flash (media) objects? If so, you might be able to define CSS to override that behavior.

**Comment by hoshoo21** [comment]
Any idea how to do this?

**Comment by PhilterPaper** [comment]
Unfortunately, nothing definite. My browser requests activation of Flash when the page loads, so it may be involved somewhere. There are a ton of Javascript files loaded, including some JSON and some FusionCharts stuff. Looking with Firebug, the charts themselves seem to be SVG and the `<svg>` tags seem to correspond with where the unwanted border is. I don't see any explicit CSS for a border around the SVG. You could try adding somewhere CSS something like

    svg { border: none; }

and see if it has any effect (maybe WebKit is putting a border around SVG graphics by default, and this might suppress it). Worth a try. If that doesn't do it, I don't know -- there's no border in some browsers (maybe all).

**Comment by Tomsgu** [comment]
Closing as there is no response and the original html example does not work anymore. Please feel free to reopen if the issue persists.
