### ISSUE TITLE
wkhtmltopdf cuts off everything beyond 1425px in Windows

### ISSUE THREAD

**Issue by nunorguedes** [wkhtmltopdf/wkhtmltopdf#2863]
Hello everyone,

After we upgraded from 0.9.9 to 0.12.3.2 on Windows we have experiencing an issue that some PDF's are being cut off even with --enable-smart-shriking.

After a variety of tests we have concluded that wkhtmltopdf is cutting off the page after it reaches a width of 1425px+ but this did not happen in previous version as the shrink worked well independently of the width of the page.

A simple test case
[test.html.txt](https://github.com/wkhtmltopdf/wkhtmltopdf/files/193077/test.html.txt)

Result:

[test.pdf](https://github.com/wkhtmltopdf/wkhtmltopdf/files/193071/test.pdf)

Can this be fixed in this latest versions?

We tested the new 0.13 version as well but the issue remains for pages larger than 1525px

Thanks, Nuno Guedes.

**Comment by kurttheviking** [comment]
For what it's worth, I confirmed a similar pattern on the linux builds (running Ubuntu 14.04.4 LTS)

**Comment by Tomsgu** [comment]
It seems working fine on `0.12.5`. Please feel free to reopen this issue if it still persists.
