### ISSUE TITLE
Document range.getBoundingClientRects() does not return expected value

### ISSUE THREAD

**Issue by heymath** [wkhtmltopdf/wkhtmltopdf#2864]
Hello,
I have a script that needs to be run in HTML before getting the result as PDF. This script use and manipulates selection and range (window.getSelection and document.createRange).
My problem is, after creating the range and setting its start / end, `range.getBoundingClientRects()` return `null`, so the rest of the script fails. This script works out of wkhtmltopdf context, by the way.
Is it _normal_ or is there something specific to do to make it work?

**Comment by alloylab** [comment]
is this still an issue on 0.12.5?
