### ISSUE TITLE
Un-neccessary  border

### ISSUE THREAD

**Issue by hoshoo21** [wkhtmltopdf/wkhtmltopdf#2865]
@ashkulz  

When I am trying to create PDF from 
 http://cvldev.isni.co/Print.aspx?p=eyJBc3NldExpc3QiOiI3MiIsIlJlcG9ydENvZGUiOiJBQ0FOIiwiRGF0ZUZyb20iOiIxOC8xMS8yMDE1IDAwOjAwIiwiRGF0ZVRvIjoiMTgvMTEvMjAxNSAyMzo1OSIsIkxhc3RSZXBvcnRlZCI6IjI0IiwiU2hvd0FsbCI6ZmFsc2UsIlNwZWVkVHJlc2hvbGQiOjAsIlJlcG9ydFR5cGUiOiIiLCJGdWVsUHJpY2VQZXJMaXRlciI6MSwiQ2hhcnRUeXBlIjoiQ29sdW1uM0QifQ== 

it is creating PDF but it is creating  border around graphic 
Here  is what i am passing arguments , 
wkhtmltopdf --run-script "javascript: setTimeou
t( alert(document.getElementsByTagName('svg').length),500000)" --javascript-dela
y 120000 --no-stop-slow-scripts --enable-javascript  --debug-javascript "http://
cvldev.isni.co/Print.aspx?p=eyJBc3NldExpc3QiOiI3MiIsIlJlcG9ydENvZGUiOiJBQ0FOIiwi
RGF0ZUZyb20iOiIxOC8xMS8yMDE1IDAwOjAwIiwiRGF0ZVRvIjoiMTgvMTEvMjAxNSAyMzo1OSIsIkxh
c3RSZXBvcnRlZCI6IjI0IiwiU2hvd0FsbCI6ZmFsc2UsIlNwZWVkVHJlc2hvbGQiOjAsIlJlcG9ydFR5
cGUiOiIiLCJGdWVsUHJpY2VQZXJMaXRlciI6MSwiQ2hhcnRUeXBlIjoiQ29sdW1uM0QifQ==" test8o
utput.pdf
[test8output.pdf](https://github.com/wkhtmltopdf/wkhtmltopdf/files/193730/test8output.pdf)

**Comment by PhilterPaper** [comment]
#2859. You already opened a bug report for this problem, so please close this one.

**Comment by hoshoo21** [comment]
But i haven't get any feedback yet
