### ISSUE TITLE
you guys open to documentation?

### ISSUE THREAD

**Issue by mustmodify** [wkhtmltopdf/wkhtmltopdf#2871]
I have used two different pieces of software for turning html into PDFs: [Prince](http://www.princexml.com) and wkhtmltopdf. And obviously I prefer open source... but without documentation, the process seems to be "ask google and he'll show you 5 ways not to do what you want." Which is sort of a bummer.

If I were to create more useful documentation, would you guys be willing to include it as your README? I would have just started, but it seems like a lot of work to potentially hear "no thanks."

**Comment by joonas-fi** [comment]
I was frustrated with the lack of documentation as well.

**Comment by ashkulz** [comment]
I'd love it! You can send PRs for the website using the `gh-pages` branch.

**Comment by ashkulz** [comment]
Since I haven't gotten PRs, I assume that you didn't find the time to contribute ... although I'd still love PRs. Meanwhile, I'm closing the issue since there's been no action for 4 years 🤷‍♂️

**Comment by mustmodify** [comment]
I'm embarrassed I didn't take the time to do this. :(

**Comment by ashkulz** [comment]
@mustmodify no need for any guilt, it's all volunteer work 😄 

_(says the maintainer who's been AWOL for 2 years)_
