### ISSUE TITLE
Unicode characters should not be in fillable field names

### ISSUE THREAD

**Issue by oliverm2112** [wkhtmltopdf/wkhtmltopdf#2872]
From what I understand, unicode field names are not supported in PDF 1.4 When converting HTML form fields, the input's name attribute should not be converted to unicode.

Here's what's generated for a field with HTML input name "[Signer.Capture1.label1.Name]"
/T(��[Signer.Capture1.label1.Name])

(Move your cursor between the letters to see double-byte behavior)

It should look like this (plain ascii):
/T([Signer.Capture1.label1.Name])

The unicode naming prevents online eSign services such as Silanis and DocuSign from correctly identifying field names of uploaded documents (for conversion to signature fields on their servers).

**Comment by alloylab** [comment]
is this still an issue on 0.12.5?

**Comment by oliverm2112** [comment]
Thanks for the follow-up. Sorry - old project from over 2 years ago - I don't have access to client code any more - pls close.
