### ISSUE TITLE
Some characters don't display

### ISSUE THREAD

**Issue by liuyug** [wkhtmltopdf/wkhtmltopdf#2875]
Image don't display some special characters, but it is right in firefox.

such as:

𐌀    𐌁    𐌂    𐌃    𐌄    𐌅    𐌆    𐌇    𐌈    𐌉    𐌊    𐌋    𐌌    𐌍    𐌎    𐌏    𐌐    𐌑    𐌒    𐌓    𐌔    𐌕    𐌖    𐌗    𐌘    𐌙    𐌚    𐌛    𐌜    𐌝    𐌞    

𝌀    𝌁    𝌂    𝌃    𝌄    𝌅    𝌆    𝌇    𝌈    𝌉    𝌊    𝌋    𝌌    𝌍    𝌎    𝌏    𝌐    𝌑    𝌒    𝌓    𝌔    𝌕    𝌖    𝌗    𝌘    𝌙    𝌚    𝌛    𝌜    𝌝    𝌞    𝌟    𝌠    𝌡    𝌢    𝌣    𝌤    𝌥    𝌦    𝌧    𝌨    𝌩    𝌪    𝌫    𝌬    𝌭    𝌮    𝌯    𝌰    𝌱    𝌲    𝌳

**Comment by alloylab** [comment]
is this still an issue on 0.12.5?
