### ISSUE TITLE
Link points to wrong page if reference uses file name only AND referenced file is 2 pages or longer

### ISSUE THREAD

**Issue by TokyoAussie** [wkhtmltopdf/wkhtmltopdf#2878]
Don't know if this has been reported before.
I had a link that pointed to the wrong page in the resulting PDF output, and I have traced the problem.

If a link in file_A.html references only the file name of file B (file_B.html, without an "id" or "name" target) and file_B ends up being longer than 2 pages in the resulting PDF, the link ends up pointing to the next page. If file_B.html ends up being 4 pages long, the link points to the 3rd page, and so on.

However, if there is a named reference (such as "file_B.html#top"), links work correctly every time. There is more description in the attached files. PDF file demonstrates the problem.

[link_issue.zip](https://github.com/wkhtmltopdf/wkhtmltopdf/files/205773/link_issue.zip)

.

**Comment by alloylab** [comment]
is this still an issue on 0.12.5?
