### ISSUE TITLE
Why not pass html as a string to header-html and footer-html?

### ISSUE THREAD

**Issue by michael-iclinic** [wkhtmltopdf/wkhtmltopdf#2879]
It would be nice the `--header-html` and `--footer-html` params accept an html as a string instead of a path to a file on the system or an url.

**Comment by stguitar** [comment]
completely agree with you here.

**Comment by sgil-carecloud** [comment]
i also agree.

**Comment by ashkulz** [comment]
See #2280 on a discussion of why it is not possible.
