### ISSUE TITLE
ClipPath does not work with local file.

### ISSUE THREAD

**Issue by BangBoy** [wkhtmltopdf/wkhtmltopdf#2883]
Currently I can successfully export the page like [ny times] which has svg within clipPath. (http://www.nytimes.com/interactive/2012/09/06/us/politics/convention-word-counts.html#g-clip-democrat-38)

However when I try to copy all html tags into the local file, such as this [example](https://drive.google.com/file/d/0By7cw85YjITLNDU1Z1pOalpqMmc). Although the page can still opened in the browser. The clipPath part does disappear with exported file. Not sure how I can fix the problem.

Thanks!

**Comment by alloylab** [comment]
is this still an issue on 0.12.5?
