### ISSUE TITLE
Font-face not render correctly with different platform

### ISSUE THREAD

**Issue by duchoang** [wkhtmltopdf/wkhtmltopdf#2884]
Hi, I'm trying to use the embed font in css and use `wkhtmltopdf` to print the website to pdf. At first it works perfectly on my Mac, but when running on Ubuntu (with the same version), the pdf is slightly different. 

For example, I create simple html using the embed font: Futura-CondensedMedium in css: http://hoanglenghiaduc.com/debug/index.htm
```
@font-face {
    font-family: 'Futura-CondensedMedium';
    src: url('Futura-CondensedMedium.otf') format('opentype'); 
}
```
Then using version 0.12.3 to print the pdf on mac with commands (on mac I must install this font locally  [Futura-CondensedMedium](http://hoanglenghiaduc.com/debug/Futura-CondensedMedium.otf))
```
$ wkhtmltopdf --version
wkhtmltopdf 0.12.3 (with patched qt)

$ wkhtmltopdf http://hoanglenghiaduc.com/debug/index.htm debug_mac-os.pdf.
```
In ubuntu, I don't need to install the font locally, just run the following command:
```
$ wget http://download.gna.org/wkhtmltopdf/0.12/0.12.3/wkhtmltox-0.12.3_linux-generic-amd64.tar.xz
$ tar xf wkhtmltox-0.12.3_linux-generic-amd64.tar.xz
$ ./wkhtmltox/bin/wkhtmltopdf --version
wkhtmltopdf 0.12.3 (with patched qt)

$ ./wkhtmltox/bin/wkhtmltopdf http://hoanglenghiaduc.com/debug/index.htm debug_ubuntu.pdf
```
The result pdf is here: [debug_mac-os.pdf](https://github.com/wkhtmltopdf/wkhtmltopdf/files/213383/debug_mac-os.pdf), [debug_ubuntu.pdf](https://github.com/wkhtmltopdf/wkhtmltopdf/files/213385/debug_ubuntu.pdf).

It seems normal at a first glance, but if you zoom in more, the font is slightly different. For the version generated on mac, it's ok:
<img width="839" alt="screen shot 2016-04-11 at 16 53 59" src="https://cloud.githubusercontent.com/assets/3921326/14433630/f4ed4792-0006-11e6-9e81-2bb9961239d5.png">

But on ubuntu, it seems it prints twice with a shift on the right slightly, note at those characters: `>`, `C`, `S`
<img width="840" alt="screen shot 2016-04-11 at 16 54 14" src="https://cloud.githubusercontent.com/assets/3921326/14433633/fa78caec-0006-11e6-96aa-0cb38d688985.png">

Much appreciate if anyone can give some hint how to get rid of this issue on ubuntu.
Thank you
Duc

**Comment by PhilterPaper** [comment]
Interesting. Can you tell if this on a per-character basis (indicating a possible font rendering problem), or does your source actually print everything twice in (almost) the same place? If the latter case, that brings up the question of why is it misaligned by a few pixels on one system and not the other. If only Ubuntu is double printing the whole line (misaligned), that's yet another issue. Anyway, if you can unpack the resulting PDF and see if **>ACTIONS** appears twice or just once, and if this is just Ubuntu, or both, that could be useful information.

**Comment by duchoang** [comment]
@PhilterPaper if you look at the above 2 images, all the symbol in `debug_ubuntu.pdf` seem a little bit bigger than on mac os and it is obvious on some character: `>`, `C`, `S`. One thing I notice is that: in ubuntu, for a page using the embed font-face, it can generate pdf with correct font (even this embed font doesn't exist in system). Whereas in mac it's not the case, I must install the font manually to make this work.

Can you recommend me some tool to unpack/debug the pdf file?

**Comment by PhilterPaper** [comment]
What I was pointing out was that the text appears to be "double struck" -- that is, the line was printed twice, with the second time offset to the right (or left) by a few pixels. That might show a problem in WebKit's font rendering, but I was asking you to examine the PDF to make sure that the line wasn't actually printed twice (which could be a different WebKit problem).

PDFtk is a good tool that can "uncompress" streams.

**Comment by shinryuurey** [comment]
@duchoang Did you manage to fix the overlapping of text when printed to pdf?

**Comment by duchoang** [comment]
yap, I found the problem in this styling of css:
```
font-weight: bold;
```
Removing that solved this issue.

**Comment by PhilterPaper** [comment]
A "bold" font-weight should normally *not* cause characters to be double-struck. It should select a different font file instead. If none is available, I suppose that double-striking might be used, but that's a poor way to do it, as you would get the effects you see. At any rate, it would have to increase the spacing between characters to avoid their touching. Something strange is going on if removing `font-weight: bold;` did the trick.

**Comment by CrtLF** [comment]
If you think you have font rendering differences depending of the platform, also check if you didn't miss the `line-height` CSS property. I though I had big font rendering issues but it seems macOS and Ubuntu doesn't print text the same way by default, and it looked like Ubuntu was stretching my font.

**Comment by PhilterPaper** [comment]
If only _some_ platforms are rendering **bold** as double-struck characters, there is some problem with the font file(s) on those platforms, where they can't find a "bold" version that should be there. Rather than disabling "bold" everywhere it's used, maybe take a look at your font files and whatever configuration files in Linux font handling is processing them. There's probably an error in there somewhere. I wouldn't be surprised if the problem also occurred in browsers (i.e., is generic font handling, not just with wkHTMLtoPDF).
