### ISSUE TITLE
wkhtmltopdf_set_object_setting can not deal with Chinese characters

### ISSUE THREAD

**Issue by neohope** [wkhtmltopdf/wkhtmltopdf#2885]
It seems that "wkhtmltopdf_set_object_setting" function can not deal with Chinese characters.

I hava tried ansi, unicode and utf-8. 

Did I miss something?

    //ansi or gbk    
    wkhtmltopdf_set_object_setting(os, "header.left", "测试");

    //unicode
    int outLength = MultiByteToWideChar(CP_ACP, 0, "测试", -1, NULL, 0);
    WCHAR *wbuff = (WCHAR *)malloc(outLength+1);
    memset(wbuff, 0, outLength+1);
    outLength = MultiByteToWideChar(CP_ACP, 0, "测试", -1, wbuff, outLength);
    wkhtmltopdf_set_object_setting(os, "header.left", wbuff);

    //utf-8
    outLength = WideCharToMultiByte(CP_UTF8, 0, wbuff, -1, NULL, 0, NULL, NULL);
    char* ubuff = (WCHAR *)malloc(outLength + 1);
    memset(ubuff, 0, outLength + 1);
    outLength = WideCharToMultiByte(CP_UTF8, 0, wbuff, -1, ubuff, outLength, NULL, NULL);
    wkhtmltopdf_set_object_setting(os, "header.left", ubuff);

**Comment by neohope** [comment]
The render result:

**Comment by neohope** [comment]
The render results:

![utf-8](https://cloud.githubusercontent.com/assets/1729598/14485803/e4af63fc-018b-11e6-8912-47f60294a63a.png)
![gbk](https://cloud.githubusercontent.com/assets/1729598/14485806/e5297d7c-018b-11e6-9421-ca1ca18dd69e.png)
![unicode](https://cloud.githubusercontent.com/assets/1729598/14485805/e4f9d0a4-018b-11e6-8fbd-e45d474c9ab2.png)

**Comment by ashkulz** [comment]
This should be fixed via something similar to [changes in PR 2858](https://github.com/wkhtmltopdf/wkhtmltopdf/pull/2858/commits/6b649435ea0d2ffb14d71d22084e5dd42b8dcbbd), but applied to `wkhtmltopdf_set_object_setting` instead.

**Comment by neohope** [comment]
Thank you so muchu @ashkulz !

**Comment by ashkulz** [comment]
@neohope: so did you compile and verify it? If so, can you submit a PR?

**Comment by neohope** [comment]
It took me one night to download the souce code from github. Bad GWF.

It worked.

![patched](https://cloud.githubusercontent.com/assets/1729598/14515346/e4d23c6a-022b-11e6-8816-d24d8b834f9a.png)

**Comment by ashkulz** [comment]
[`0.12.4`](http://wkhtmltopdf.org/downloads.html#stable) has been released, which should contain the fix for this issue. Please report back if it is not solved with the above version.
