### ISSUE TITLE
Not able to set page borders to entire pdf page

### ISSUE THREAD

**Issue by vinodkumar1080** [wkhtmltopdf/wkhtmltopdf#2890]
Hi,
Is there  any option to set border to each pdf page like we set margins using
```
--margin-bottom
--margin-left 
--margin-right 
--margin-top 
```
???
Scenario:
my page consists of header and footer and dynamic content page like grid(the number of rows may vary each time), and i tried to set border to entire pdf page using css, but the border is rendering upto where the content ends. i need this border till the footer section

header, footer are added using --header-html, --footer-html switches

Thanks In advance
Please see image below.
![d3d1c4eeefdb64c97a9e026564170e4fbdb891bd2618f9fd46 pimgpsh_thumbnail_win_distr](https://cloud.githubusercontent.com/assets/15869922/14599771/e8800f9c-0576-11e6-87c5-8f7a3eca48b7.jpg)

**Comment by vinodkumar1080** [comment]
Rectified in another way.

**Comment by sanjay205** [comment]
@vinodkumar1080 
Can u please tell how did u rectified to add borders to page??

**Comment by leoncottell** [comment]
I managed to fix this using an absolutely positioned header that covers the whole page -

--header-html = pdfHeader.html, 

then in pdfHeader.html I've got

<!DOCTYPE html>
<div style="position: absolute; top: 0px; left: 0; right: 0; height: 1050px; border: 2px solid black; border-radius: 10px;"></div>

**Comment by jatinagarwalmykaarma** [comment]
@severn-leon @vinodkumar1080 Can you please share how you resolved this problem. Thanks in advance.
