### ISSUE TITLE
Segmentation fault -- possibly caused by image

### ISSUE THREAD

**Issue by mihaiscurtucb** [wkhtmltopdf/wkhtmltopdf#2895]
OS: Ubuntu 14.04 (first noticed on Amazon Linux)
Version: 0.12.2.1 (also happens on 0.12.3) with patched Qt

Html files: https://gist.github.com/mihaiscurtucb/e8b5b014970d4bfef196fba6abbc18fa

Options:

``` bash
wkhtmltopdf \
--header-spacing 15 \
--page-size letter \
--margin-bottom 8 \
--footer-spacing 8 \
--header-html h.html \
--footer-html f.html \
amr.html o.pdf
```

Commenting this <img> makes it run:

``` html
<img src="https://images.chinookbook.com/assets/chinookbook_logo_6000_print_quality.png" class="cb-logo" width="220" alt="Chinook Book">
```

**EDIT** Should be mentioned that this is an example of a report that is generated (with sensitive data obfuscated). The header image is there in all reports, but just some cause the seg fault. I couldn't spot a pattern at this time.

**Comment by alloylab** [comment]
is this still an issue on 0.12.5?
