### ISSUE TITLE
any example of --cookie?

### ISSUE THREAD

**Issue by brucejcw** [wkhtmltopdf/wkhtmltopdf#2897]
any example of --cookie? I have multi cookies

**Comment by goody9807** [comment]
me too!

**Comment by caohm** [comment]
--cookie <name> <value>

**Comment by bernig** [comment]
It works for me with :
`--cookie 'mycookiename' 'mycookievalue'`

If you have multiple cookies, just repeat the `--cookie 'name' 'value'`.

**Comment by jplevene** [comment]
Is there a way to set the cookie to a domain? For example I browse to www.domain.com but want to enable the same cookies for sub.domain.com (called by the page using Ajax for example)?
