### ISSUE TITLE
Invalid letter-spacing 

### ISSUE THREAD

**Issue by lorond** [wkhtmltopdf/wkhtmltopdf#2899]
Test html:

```html
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <title>Test</title>
    <style type="text/css">
        h3{ text-align: center; }
        .spacing-1px { letter-spacing: 1px; }
        .spacing-10px { letter-spacing: 10px; }
    </style>
</head>
<body>
    <h3>no letter-spacing</h3>
    <h3 class="spacing-1px">letter-spacing: 1px</h3>
    <h3 class="spacing-10px">letter-spacing: 10px</h3>
</body>
</html>
```

Expected result (chrome):
![chrome-spacing](https://cloud.githubusercontent.com/assets/1833263/14674122/facdcd66-070a-11e6-9b92-2b9a1e6a9731.png)

Actual result (wkhtmltopdf.exe test.html test.pdf):
![wkhtmltopdf-spacing](https://cloud.githubusercontent.com/assets/1833263/14674165/476371bc-070b-11e6-99ae-2ae95c27ef8d.png)

Same thing for other units, like pt, etc.

**Comment by NicoBarbaros** [comment]
put dpi to 96 and it should work, at least it did for me

**Comment by FabriceGaudin** [comment]
Setting dpi to 96 (in wkhtmltopdf options) worked for me as well

**Comment by tejastank** [comment]
Solution: https://stackoverflow.com/a/46034207/1635700

**Comment by Tomsgu** [comment]
Does this work on `0.12.5`? I cannot reproduce this issue there.

**Comment by tejastank** [comment]
@Tomsgu take normal page without any css, add some text in html page, than add some tags complexity. than print and check. if works, it mean your css making problem.

During my research I had found that wkhtmltopdf and when new PDF generated it had some additional  css, that's causes issue.

Note: I had done PDF to HTML than lot more surprise detected. So first do normal test than upgrade test level.  I hope you figure-out issue.

**Comment by Tomsgu** [comment]
>  take normal page without any css, add some text in html page, than add some tags complexity. than print and check. if works, it mean your css making problem.

What do you mean by this? I just copy your example and it has no issue described here. I am not going to put any tags complexity.

@tejastank that means `0.12.5` fixed your issue? If you have any other problems please feel free to open a new issue.
