### ISSUE TITLE
Unicode characters and transparent PNG

### ISSUE THREAD

**Issue by FlandersBurger** [wkhtmltopdf/wkhtmltopdf#2901]
I seem to have to choose between transparent PNGs with version 0.12.3.2 or Unicode characters with version 0.12.2.1 but I need both to work.
Unicode characters work perfectly in the alpha release (0.13.0) again but images have not been implemented.
Arabic and Thai seem to work fine but Punjabi, Chinese, Japanese do not for example.

in regards to the unicode characters, I have tried all the suggestions but nothing works with 0.12.3.2
- added `<meta charset='UTF-8'>`
- added UTF-8 Encoding in the wkhtmltopdf options
- added simplified and traditional chinese fonts, neither worked, only showed squares.
- tried Noto Sans, still squares

any ideas?

**Comment by ashkulz** [comment]
What seems to be the issue in `0.12.3.2`? Please include a detailed test case which can show the problem.

**Comment by Tomsgu** [comment]
Closing as there is no response since 2016.
