### ISSUE TITLE
Segmentation fault without any details

### ISSUE THREAD

**Issue by JerryBels** [wkhtmltopdf/wkhtmltopdf#2902]
Hello guys,

I'm trying to get wkhtmltopdf to work on my Gentoo server.

Gentoo version : 1.6.14 - x86_64

So I downloaded the 64 bits last version and untar. Set chmod. Tried to move it and ln in /usr/local/bin

```
Segmentation fault
```

Tried with the original executable directly, same. Tried to install dependencies urw-fonts, libXext and libXrender through emerge, as far as I can tell it installed well but doesn't change anything - same error. Tried with the 32 bits version as well - same error. No details, just this.

Any help would be greatly appreciated !

[EDIT] It's even worse than that ! Launching 

```
wkhtmltopdf -V
```

Gives the same error !

**Comment by alloylab** [comment]
is this still an issue on 0.12.5?
