### ISSUE TITLE
Python implementation

### ISSUE THREAD

**Issue by Stevo3** [wkhtmltopdf/wkhtmltopdf#2905]
Hi.
I have been using pdfkit / wkhtmltopdf with python 2.7 trying to use various functionalities but keep hitting the same error - 'option'  specified in incorrect location.
I have various options enabled for trials, some have to be commented out to allow the pdf to complete being created.
options={
    'page-size': 'A4',
    #'margin-top': '0',
    #'margin-right': '0',
    #'margin-bottom': '0',
    #'margin-left': '0',
    'zoom': '1.2',
    'javascript-delay': '3000',
    'load-error-handling': 'ignore',
    'cookie': 'logged_in' 'y',
    'cookie-jar': 'cookies.txt',
    'encoding': "UTF-8",
    'username': 'steve38'
    #'cookie': 'BrowserCookie' '45a25ef1-3703-4d4d-8874-d6467f564700'
}

Also.
'--cookie <name> <value>  Set an additional cookie (repeatable), value should be url encoded' is it possibe to use this without --cookie-jar ??  how would pdfkit / wkhtmltopdf find the path to the cookies if --cookie-jar (below is not set) ?  if --cookie-jar is set the cookie is overwritten as below. 

There seems to be no way to login to a site using pdfkit / wkhtmltopdf  so I created cookies with urllib then use '--cookie-jar <path> Read and write cookies from and to the supplied cookie jar file'  eg 'cookie-jar': 'cookies.txt', but pdfkit / wkhtmltopdf  doesn't read initially so not logged in the login cookies are overwriten by pdfkit / wkhtmltopdf with guest cookies.

Regards 
Stevo

**Comment by alloylab** [comment]
is this still an issue on 0.12.5?
