### ISSUE TITLE
Responsive SVG (from adobe illustrator) are not rendered

### ISSUE THREAD

**Issue by catalinonutu3** [wkhtmltopdf/wkhtmltopdf#2906]
I've encountered cases in which some SVGs disappear after converting to PDF and concluded that if I exported those PFD with Adobe Illustrator using the `Responsive` option turned on, the assets will not be visible in the PDF.
Turning the option off solved my issue ([see here](http://i.imgur.com/35g7hYJ.png)).

**Comment by PhilterPaper** [comment]
Well, "responsive" SVG graphics are probably hauling along some CSS and JS to implement that, and maybe WebKit is getting confused by it. It often seems to have trouble with cutting-edge CSS and JS. Is it possible for you to draw your graphics at one size and level of detail appropriate for PDF publishing? If you _also_ want to publish for Web use, can you save separate versions for PDF and Web? In general, does wkHTMLtoPDF have problems with responsive web pages, or just Illustrator's?

As to *why* one would request that vector graphics be "responsive", my best guess would be that at small scales, one wants less detail in the picture so it's not so cluttered? This would be like hinting in a font to draw less stuff at small font sizes. Do you have to tell Illustrator what to draw at different scales, or does it try to figure it out for you?

**Comment by Tomsgu** [comment]
Closing as there is no feedback. Please feel free to re-open the issue if you have more details on @PhilterPaper's questions.
