### ISSUE TITLE
Unable to convert the outlook email body , an HTML file  with Korean font to pdf using  wkhtmltopdf exe

### ISSUE THREAD

**Issue by ajnreddy** [wkhtmltopdf/wkhtmltopdf#2907]
I am giving print of the email body with Korean font, after converting html to pdf the Korean fonts are junk characters in pdf file.  the file is in  Unicode format.
Is this the limitation of the wkhtmltopdf tool.

**Comment by TaronSaribekyan** [comment]
Be sure that you have tag `<meta charset="utf-8">` in head of your html. 
Also set parameter --encoding to utf-8

**Comment by ashkulz** [comment]
Please post a complete, reproducible test case with command-line parameters and details of environment to investigate this issue.

**Comment by ajnreddy** [comment]
Thanks for your suggestion Ashish.
