### ISSUE TITLE
Ability to set document properties

### ISSUE THREAD

**Issue by geekdad1** [wkhtmltopdf/wkhtmltopdf#2911]
I have a medical application that requires us to be able to force documents to print single sided.  This is a standard for drug related orders in a hospital that they cannot be printed double sided.  In order to force that I need to be able to set the document properties through wkhtmltopdf.  Is that possible?  Can you put it in as a feature if not?  It's kind of urgent

**Comment by PhilterPaper** [comment]
Wouldn't that be a *printer* property, rather than a document property? If you have printers capable of double-sided printing, they should have a configuration setting for single-sided. You might even be able to create a "new" printer with that pre-set, or if single-sided printing is the norm, change the settings on the existing printer setup. Make users have to go through the printer dialog to enable double-sided printing, so they can't do it casually/accidentally.

**Comment by geekdad1** [comment]
According to adobe it's also a document property that you can set.  If you can do that, it's takes the owness on the busy end user from having to make changes or decisions about everything they print.  See this blog post for more details.  https://forums.adobe.com/thread/1695766

 

Doug

**Comment by PhilterPaper** [comment]
Ah, learn something new every day. Taking the onus off the user for selecting printer settings would be a good thing, and that's probably something that wkHTMLtoPDF could be taught to do (provided that this is generic for all printers). Note that you would probably have to warn users not to override the 1-sided print setting (maybe in a header or footer).

**Comment by geekdad1** [comment]
In a hospital setting, people are busy, lives are at stake, and mistakes can have disatrous results.  Anything we can do to make things happen automatically is a win.

 

Any idea what would be involved in making this happen?  Timeline?

 

Doug

**Comment by ashkulz** [comment]
You can easily [post-process the PDF](http://stackoverflow.com/a/23201241) to add that preference. Adding it to wkhtmltopdf is not going to be easy, as it will require changing Qt to support setting this option.

**Comment by geekdad1** [comment]
Thanks for your input.  pdftk doesn't appear to have it, but I've sent in a request.  PDF::API2 doesn't seem to have it either.  Javascript doesn't appear to have a way of setting printer properties.  It may end up being up to the users to get it right, but that's not the best solution.  I'll keep digging.

 

Doug
