### ISSUE TITLE
Issue with https on MAC OS

### ISSUE THREAD

**Issue by arjunsuresh** [wkhtmltopdf/wkhtmltopdf#2912]
Hi, 
I'm not able to download images via https from my server- the server SSL certificate is recognized in chrome and mozilla and I'm able to access it via wget also. But wkhtmltopdf does no seem to work. Any way out? I'm able to print google via https.

`parambara:Book asuresh$ wkhtmltopdf "https://gateoverflow.in" a.pdf 2>&1 
Loading pages (1/6)
Error: Failed loading page https://gateoverflow.in (sometimes it will work just to ignore this error with --load-error-handling ignore)
Exit with code 1 due to network error: SslHandshakeFailedError
parambara:Book asuresh$ wkhtmltopdf "https://google.com" a.pdf 2>&1 
Loading pages (1/6)
Counting pages (2/6)                                               
Resolving links (4/6)                                                       
Loading headers and footers (5/6)                                           
Printing pages (6/6)
Done                                                                      
parambara:Book asuresh$ wget "https://gateoverflow.in"  
--2016-04-27 22:34:14--  https://gateoverflow.in/
Resolving gateoverflow.in... 104.27.189.78, 104.27.188.78, 2400:cb00:2048:1::681b:bd4e, ...
Connecting to gateoverflow.in|104.27.189.78|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: 'index.html.1'

index.html.1                               [ <=>                                                                        ]  55.04K  --.-KB/s    in 0.1s    

2016-04-27 22:34:15 (406 KB/s) - 'index.html.1' saved [56363]`

**Comment by arjunsuresh** [comment]
I found that the issue has something to do with cloudfare CDN as disabling it made my site work with wkhtmltopdf. But why is it working with all browsers, curl and wget and not just with wkhtmltopdf?

**Comment by ashkulz** [comment]
This is probably due to the outdated OpenSSL library used on OS X, which is probably not updated/supported -- see #2150.

**Comment by challgren** [comment]
Resolving this would be helpful for me.
