### ISSUE TITLE
wkhtmltopdf that output HTML dom after JS execution

### ISSUE THREAD

**Issue by dotnetcomgazio** [wkhtmltopdf/wkhtmltopdf#2915]
Is it possible for debug to add an option that output the Dom after JS execution ?

wkhtmltopdf --debug test.html http://website-with-js.com/ output.pdf

**Comment by PhilterPaper** [comment]
You want to display the DOM (internal page structure) rather than the finished human-readable page? wkHTMLtoPDF uses WebKit to render the page, so by the time wkHTMLtoPDF gets control, all it sees (as far as I can tell) is the finished product (rendered page).

There are debuggers around that can show you the DOM -- perhaps they can be dumped as HTML themselves! For example, the Firebug plug-in to Firefox can show a page's DOM. If what you're looking to do is debug a conversion problem, that might be your best bet.

**Comment by dotnetcomgazio** [comment]
thx for your reply,

It's for automated test tool, with the dumped rendered content in html we can search special contents on

**Comment by PhilterPaper** [comment]
OK, you want the DOM dumped into some kind of searchable format, not necessarily a PDF document? I just did a very quick Google of **convert DOM to XML** and **convert DOM to text**, and it looks like there may be some tools out there to do such things. Have you investigated these? If you don't need the entire DOM, but just certain parts, there may be Javascript to dump selected objects, or ways to extract this from the HTML.

What is the original data format that you can get your hands on? If it's a browser page generated by a test tool, can you simply save the HTML into a file and search that? I would think that much easier than converting the page into PDF and then searching that. Don't forget about toolkits like **Selenium** that can explore the DOM and extract data from it.

I trust that you've confirmed that the data you're looking for is actually *in* the HTML somewhere, perhaps just not conveniently formatted?

**Comment by dotnetcomgazio** [comment]
Exactly, the DOM dumped in a file.
We only find phantomjs or other like Selenium... It's not very interresting right now for us.

We search if it's possible with wkhtmltopdf, in our system we have an pdf production, for control, we just need a simple text search (on a PDF isn't very good)

Actualy, we search to find a text on a dom generated by javascript.

With the --run-script, we can't made a .js that echo the generated Dom ?

**Comment by dotnetcomgazio** [comment]
I just trie that:
```wkhtmltopdf.exe --run-script "var file=new File('c:/test.html');file.open('w');file.writeln(document.getElementsByTagName('html')[0].innerHTML);file.close();" http://google.com google.pdf```
That output
```Loading pages (1/6)
Counting pages (2/6)
Resolving links (4/6)
Loading headers and footers (5/6)
Printing pages (6/6)
Done```
But didn't work create my c:\test.html with the Dom inside... (run in administrator)

Probably a security feature

**Comment by dotnetcomgazio** [comment]
Ok, we have to use PhantomJS or Selenium
wkhtmltopdf isn't made for that

thx PhilterPaper
