### ISSUE TITLE
Can you finish alpha version 

### ISSUE THREAD

**Issue by phofstetter** [wkhtmltopdf/wkhtmltopdf#2916]
Hi there

I am using the stable version on windows and we have big issues here. The arial font is not showing correctly. Roboto woff file does this correctly. The blocking issue is that the chinese font SimSun is not generating correctly. We used the alpha version then the fonts display correctly. 
The missing parts on the alpha here is the header and footer needs to be done and also the feature --disable-smart-shrinking

Is there a possibility that you integrate those functionalities. If we need to pay some money for, let me know your estimate.

**Comment by ashkulz** [comment]
@phofstetter: can you list out the functionalities you would consider important? Also, would like to know which OSes do you plan to use it on -- for Linux, is headless support important for you or you are OK to run it via xvfb?

**Comment by phofstetter** [comment]
Here the Wishlist of functions to implement:
- Windows Server 2008 R2, 64 Bit
- Header and Footer including
--page-size A4
--orientation Portrait
-T 10mm -L 24mm -B 17mm 
--dpi 300 
--disable-smart-shrinking 
--title 

Here a source in HTML that we use:
[sample.zip](https://github.com/wkhtmltopdf/wkhtmltopdf/files/272419/sample.zip)

**Comment by ByronWLong** [comment]
I've also been hoping for a release of the Alpha version, as it works with our Angular application without modifications, but we needed headers and footers for specific pages. I went with switching back to the stable version for this one document, and had to work around the deficiencies in the earlier WebKit on a case-by-case basis, but if header and footer support worked in the new WebKit version, I could go back to using a single version of wkhtmltopdf.

We use CentOS 7, and have been fine with using xvfb.

**Comment by jorrit** [comment]
It would be nice to have an alpha release with a patched Qt because I need external links. Is that possible?

**Comment by pierre-weceipt** [comment]
It would be really nice to have an alpha version with the footer/header changes. 

I don't now if we can use your qt repositories  ([qtwebkit](https://github.com/wkhtmltopdf/qtwebkit) or [qtbase](https://github.com/wkhtmltopdf/qtbase)) and compile a custom version. I wanted to try this but don't want to spend too much time without knowing if it can succeed?

**Comment by ashkulz** [comment]
Please see #3217 on what needs to be done for porting the custom Qt.
