### ISSUE TITLE
Error on Windows 2008 server - "QEventDispatcher: Failed to create QEventDispatcherWin32 internal window

### ISSUE THREAD

**Issue by romanusss** [wkhtmltopdf/wkhtmltopdf#2917]
Hi All,

I have wkhtmltopdf version 0.12.3 running on a Windows 2008 R2 server. and the same issue on Windows 2012 server. But it works fine on an other computer on Windows 10.
wkhtmltopdf.exe works fine in cmd.
But i have this issue in my code when it is executed 

_RuntimeException in AbstractGenerator.php line 338:_
The **exit status code '1'** says something went wrong:
stderr: "**QEventDispatcher**: Failed to create **QEventDispatcherWin32 **internal window: 8

**Qt: Could not initialize OLE (error 80070583)
QEventDispatcher: Failed to create QEventDispatcherWin32 internal window: 8**

Qt: INTERNALL ERROR: failed to install GetMessage hook
"
stdout: ""
command: D:\wamp\www\webgestion\laravel\vendor\wemersonjanuario\wkhtmltopdf-windows\bin\64bit\wkhtmltopdf.exe --lowquality --margin-bottom "8mm" --margin-left "8mm" --margin-right "8mm" --margin-top "8mm" --orientation "portrait" --page-size "a4" --no-outline --enable-javascript --javascript-delay "2000" --no-stop-slow-scripts --footer-html "C:\Windows\TEMP\knp_snappy57232475334219.93510771.html" --footer-spacing "0" "C:\Windows\TEMP\knp_snappy572324752f7311.56002062.html" "C:\Windows\TEMP\knp_snappy57232475334212.17428474.pdf".

...
i doesn't find any sugestions about this error.  Could you help me ? any idea ?

(i use PHP, Laravel 5.2, Snappy , Wamp 2.5)

(Sorry for my english)

**Comment by ashkulz** [comment]
If it works from the command-line but not from PHP, it's likely the result of some anti-virus/security mechanism causing the failure. Can't help you with that, sorry.

**Comment by cclarke6264** [comment]
We're experiencing the same problem - did you find the cause and/or the fix ?

**Comment by sjsolutionsdev** [comment]
Yes i fix it.
Windows Server 2012 R2 security causing the failure.
'System' user must have R/W access to the folderS containing the dll and exe.

**Comment by cclarke6264** [comment]
Thanks for the reply.
The IIS Pool user did have the R/W access required so this wasn't the problem for us.
Fixed it by rebooting the server - must've been some bad memory.

**Comment by ShaoChi** [comment]
I had a lot of "ghost" wkhtmltopdf.exe processes running, killing those fixed this issue.
