### ISSUE TITLE
CSS opacity results in dramatically larger PDFs

### ISSUE THREAD

**Issue by serogers** [wkhtmltopdf/wkhtmltopdf#2919]
When a PDF includes elements with CSS opacity < 1, the file-size and time to generate dramatically increases. 

Using [this test HTML](https://gist.github.com/serogers/ab8e46ec8ae6cc0e3135808380c14d08), I get the following results when running `wkhtmltopdf test.html result.pdf`:

**With CSS opacity**
Size: `546 kb`
Time: `0m3.278s`

**Without CSS opacity**
Size: `15 kb`
Time: `0m0.732s`

Increasing the number of pages makes using opacity untenable, even though wkhtmltopdf renders partially transparent elements just fine. A recent test with an 18 page PDF resulted in a 13.1mb file that took 12 minutes to generate. Whereas the opacity-free version was 181kb and took 4 seconds to generate. I didn't find this behavior mentioned anywhere so it may not be a common use case, but it was quite surprising for us.

These tests were conducted on CentOS 6 and OSX 10.11.3, using wkhtmltopdf `v0.12.2.1 (with patched qt)` and `v0.12.3`.

**Comment by ashkulz** [comment]
This is a known issue, see #1510.
