### ISSUE TITLE
Temp PDF files are not removed after execution

### ISSUE THREAD

**Issue by SavchenkoVV** [wkhtmltopdf/wkhtmltopdf#2921]
Analog #1981 

OS: Fedora 23.
Version wkhtmltopdf: 0.12.3

After executions there are empty files like wktemp-03826486-9653-4bf4-a6b6-fc1efafea100.html 
in /tmp directory

**Comment by ashkulz** [comment]
Are you using the binaries from the download page or the packaged version? Please post a complete test case which can reproduce this issue.

**Comment by SavchenkoVV** [comment]
Use packaged version from Fedora Repo.

Test with files - no tmp files after execution.(Sorry, not tested before) .

Problem with execute from java.(Send data to input stream)

```
Runtime runtime = Runtime.getRuntime();
Process process = runtime.exec(new String[]{"wkhtmltopdf", "-", "test.pdf"});
OutputStream outStream = process.getOutputStream();
outStream.write("<html><body>Test</body></html>".getBytes("UTF-8"));
outStream.close();
process.waitFor();
```

**Comment by ashkulz** [comment]
Can you confirm if it happens with the binaries from the official page?

**Comment by SavchenkoVV** [comment]
Yes, 64bit linux version from http://wkhtmltopdf.org/downloads.html not remove tmp files, when processing inputstream.

Problem only with processing from java code.
From linux console, wthen processing files - no problems.

**Comment by ashkulz** [comment]
Can you post a complete example program (along with javac command line) which will reproduce the issue?

**Comment by SavchenkoVV** [comment]
Found bug in my code, witch kill wkhtml process...

Very sorry. :(
