### ISSUE TITLE
Chinese characters could not be displayed

### ISSUE THREAD

**Issue by emanlee** [wkhtmltopdf/wkhtmltopdf#2923]
Hi All, we tried the following web pages, however, they all could not be correctly converted to pdf:
c:\wkhtmltopdf.exe http://www.edu.cn c:\csdn.pdf
c:\wkhtmltopdf.exe http://www.csdn.net c:\csdn.pdf
c:\wkhtmltopdf.exe http://117.34.117.252/tie/ c:\csdn2.pdf

The results look like this snap (The upward parts of characters did not display):
[http://117.34.117.252/tie/topdf.jpg](http://117.34.117.252/tie/topdf.jpg)

**Comment by emanlee** [comment]
It seems that this issue is not connected with character coding (tried UTF-8, GB2312, entirely failed).

**Comment by emanlee** [comment]
Only English characters work.

**Comment by ashkulz** [comment]
running the last command seems to work for me, giving this result.

![csdn2](https://cloud.githubusercontent.com/assets/854352/15111474/df594f98-1604-11e6-8f9f-fe66acb36f3d.png)

maybe you need to install the necessary fonts?

**Comment by donsantana** [comment]
Hi ashkulz
I'm working with wkhtmltopdf on Laravel 5.4 and I'm having problem to generate pdf with chineses characters. 
Could you help me please?

**Comment by Leslie-Fang** [comment]
@donsantana Have you solved this problem? I have got a exactly same problem
