### ISSUE TITLE
Rows are getting repeated at the end of the page.

### ISSUE THREAD

**Issue by ashutoshideaphora** [wkhtmltopdf/wkhtmltopdf#2925]
Hi,

I am trying to get the raw text from pdf generated using wkhtmltopdf using pdfbox.
There are rows which are getting repeated in two pages and not visible in any one of them or split 
at both occurences.
e.g.   In attached pdf if you select text at end of page 3 and starting of page 4, you can see "8 References" getting repeated twice.
And end of Page 7 and starting of Page 8 
As a result I am getting same row repeated twice in my raw text file.

[Democracy.pdf](https://github.com/wkhtmltopdf/wkhtmltopdf/files/250265/Democracy.pdf)

**Comment by ashkulz** [comment]
So, if I understand you correctly -- display is correct but the extracted text is not correct? You'll have to extract the visibility information via PDFBox and decide whether to include that in the output or not.

**Comment by PhilterPaper** [comment]
As i understand the report, some lines are being visibly *split* across two pages, with sometimes just a pixel off the top or bottom of the rendered line. This is resulting in the text source (line in the PDF file) being repeated. It sounds like the rendering engine (WebKit) may be doing OK, but wkHTMLtoPDF is failing to assign a page-bottom or -top line to one **or** the other, but **not** both. If a line does not completely fit at the bottom of a page, wkHTMLtoPDF needs to take care to remove it from the first page, and only put it on the second.

**Comment by ashkulz** [comment]
@PhilterPaper: I don't think that's the case. If you see the PDF, it looks like this:
![screenshot at 2016-05-16 00 04 59](https://cloud.githubusercontent.com/assets/854352/15276050/049c9572-1afa-11e6-9d0d-a4af6edf3451.png)
but if you select the text it looks like this:
![screenshot at 2016-05-16 00 05 33](https://cloud.githubusercontent.com/assets/854352/15276053/167a6300-1afa-11e6-89be-e54a693fd57a.png)
I suspect it's a quirk of the way rendering is done: it finds that the text cannot be rendered without cutting, so lays it out and hides it and re-renders it on the next page. Not something that I can really do much about, hence the comment about finding the visibility information.

**Comment by ashutoshideaphora** [comment]
Hi @ashkulz ,

There are cases when text is split on both the pages (visible on both) that means it was rendered on the both pages.
![screenshot from 2016-05-16 10 33 58](https://cloud.githubusercontent.com/assets/17851497/15281013/d32a70c6-1b54-11e6-8429-20c8db54785d.png)
![screenshot from 2016-05-16 10 34 04](https://cloud.githubusercontent.com/assets/17851497/15281012/d32a5622-1b54-11e6-8472-8fd9df046ff2.png)

I was going through the code and was trying to figure out where wkhtmltopdf is setting the visibility information. What I found was in pdfconverter.cc, spoolPage(int page) method calls 
webPrinter->spoolPage(page+1) for each page which sends the text and its pixel coordinates(x,y) to qpainter.cpp, QPainter::drawText(const QPointF &p, const QString &str, int tf, int justificationPadding). Where str has the raw text for that page, tf is some integer value, justificationpadding = 0 and p has the coordinates.
For the cases when texts are getting repeated in the pdf coordinates are also getting repeated. I could not find out where wkhtmltopdf is setting the visibility information.

**Comment by ashkulz** [comment]
Without selecting, does it appear repeated?

**Comment by ashutoshideaphora** [comment]
Its not repeated but split. In the second screen shot you can clearly see the split line, but on selecting the text its showing repeated.

**Comment by ashkulz** [comment]
Post a repeatable test case.

**Comment by ashutoshideaphora** [comment]
@ashkulz Its not getting repeated but either split or erased from one of the occurrence.
What I was trying to say is even if it is erased QPainter is printing the text on the page which is not completely fit for it.
If this is the case that it has to print and there is no other way, Can you help me with how wkhtmltopdf is hiding the already printed text and I can try to prevent it from printing or reading the text from either of the occurrence.
