### ISSUE TITLE
make --viewport-size set environment variable for patched qt

### ISSUE THREAD

**Issue by nmors** [wkhtmltopdf/wkhtmltopdf#2926]
We should make **--viewport-size** argument set the environment variable that is used for patched qt under Linux. This will change actually make the screen resolution changeable, without having to set environmnet variable manually, which will be a little bit cleaner

See:

https://github.com/wkhtmltopdf/qt/pull/24

**Comment by ashkulz** [comment]
Nope, viewport-size and the screen size are two different things. Also, it is quite possible that the initialization will happen before there is a chance to set the variable, it is always better to do it before calling the conversion process.
