### ISSUE TITLE
ToC always created

### ISSUE THREAD

**Issue by Pepozzo** [wkhtmltopdf/wkhtmltopdf#2927]
Hi!

I'm using wkhtmltopdf 0.12.3.2 on Windows Server 2008.

I'm running wkhtmltopdf with a very simple PHP exec command, like this one:
`wkhtmltopdf mypage.html newpdf.pdf 2>&1`

PDF is created well, except for the table of content that is created even if i don't want it.

Anyone experienced this problem?

**Comment by alloylab** [comment]
is this still an issue on 0.12.5?
