### ISSUE TITLE
How to combine multiple HTMLs into 1 PDF

### ISSUE THREAD

**Issue by n2vball** [wkhtmltopdf/wkhtmltopdf#2928]
I save multiple HTMLs locally and would like to combine several of the files into 1 PDF. 

Is there a GLOBAL OPTION that allows me to specify multiple HTM files (OBJECTS) to combine into 1 PDF output file? I see that there is an OPTION for a table of contents so I was wondering if that is for just 1 HTM to PDF or if that allowed for multiple HTMLs to create the PDF.

Thanks

**Comment by ahjstone** [comment]
You might have a look into these alternative options:
http://forums.debian.net/viewtopic.php?f=10&t=64708&p=372623#p373373
http://www.linuxquestions.org/questions/linux-software-2/merge-of-html-files-into-a-single-html-or-pdf-284545/

**Comment by PhilterPaper** [comment]
Doesn't wkHTMLtoPDF allow you to specify multiple HTML input files, to be output as a single PDF? Is that not what you're looking for?

**Comment by n2vball** [comment]
WkHTMLtoPDF does not allow for multiple URL or pages. The website actually defines 1 HTML into 1 PDF.

I have been able to create a work around. I save the each separate HTML webpage as a HTM Web Page only file. Since I can define the file name, I have the file name begin with a common grouping ID like 0001 or 0123 etc...

0001 BCBS Jones BR 20160510.htm
0001 Texas Jones BR 20160510.htm

After they are saved, I use a Command Prompt to combine the files before I wkHTMLtoPDF  the file to PDF
Copy 0001*.htm  0001 Jones BR 20160510.htm

Then I can run

wkHTMLtoPDF C:\0001 Jones BR 20160510.htm c:\0001 Jones BR 20160510.PDF

It is all scripted and is faster than I expected.
The combining of the 2 htm files take less than 1 minute for at least 300 files.
Creating the PDF takes about 2 seconds each PDF.

The only issue I have is that the combination process does not have a page break between the different HTML files. I do not know how to combine them to make sure there is a hard page break between files. BUT IT WORKS

Thanks for your help.

Patrick

**Comment by ashkulz** [comment]
If you're using the distro-provided packages, yes it is not present. If you use the downloads from the website, it should work.
