### ISSUE TITLE
page numbers not showing after TOC

### ISSUE THREAD

**Issue by markkempe** [wkhtmltopdf/wkhtmltopdf#2929]
Im using the tool via command line:

D:\wwwroot\onsite.nerdsdevelopment.com\wkhtmltopdf\bin>wkhtmltopdf toc --footer-
center "[page] of [toPage]" d:\wwwroot\onsite.nerdsdevelopment.com\testdoc\sampl
e.htm d:\wwwroot\onsite.nerdsdevelopment.com\testdoc\test.pdf

You can see the output here

http://onsite.nerdsdevelopment.com/testdoc/test.pdf

You will see that the TOC show, but the first 'page' has no page number at the bottom. I can't seem to get any page after the TOC to have a page number

The source file (in txt format) is here - https://onsite.nerdsdevelopment.com/testdoc/sample.txt

thanks for any help

**Comment by markkempe** [comment]
Sorry I should add I have the latest version downloaded from http://wkhtmltopdf.org/downloads.html, 0.12.3.2 
on windows 2012 64bit

**Comment by markkempe** [comment]
Would someone be willing to help and paid for their service?

**Comment by ashkulz** [comment]
Solution [posted on the mailing list](https://groups.google.com/d/msg/wkhtmltopdf-general/DWVE5NCjozU/rK0PyM7mBQAJ): use the command line
```
wkhtmltopdf --footer-center "[page] of [toPage]" toc page.html page.pdf
```
