### ISSUE TITLE
Install on Xenial 16.04

### ISSUE THREAD

**Issue by gplume** [wkhtmltopdf/wkhtmltopdf#2933]
Hi There,
I've just installed a fresh development machine and trying to figure how I could install a patched-qt version of wkhtmltopdf...
If the maintainer could create at least an install from source scheme for Xenial it would be great..
Thanks.

**Comment by ashkulz** [comment]
Just download the binaries from the [downloads page](http://wkhtmltopdf.org/downloads.html#stable) and extract/run them.

**Comment by gplume** [comment]
Thanks for your answer.
You mean that I should install the linux generic version ?
The problem is that I don't know where to extract this directory (bin/include/lib/share).
Thanks for hepl.

**Comment by ashkulz** [comment]
It's generally best to extract it in `/opt`, `/srv` or `/usr/local` -- not in `/usr`. Because the binaries are standalone, you can even bundle it as a part of your application package and use it from there.

**Comment by gplume** [comment]
Ok, thanks a lot, it does work well :)

**Comment by mzalazar** [comment]
I don't know why the source code is available... if it does not compile.

**Comment by joshuapinter** [comment]
Just to help others, here is what my installation steps were installing 0.12.3 on Ubuntu 16.04: 

```bash
cd ~
wget https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.3/wkhtmltox-0.12.3_linux-generic-amd64.tar.xz
tar vxf wkhtmltox-0.12.3_linux-generic-amd64.tar.xz 
cp wkhtmltox/bin/wk* /usr/local/bin/
```

And you can confirm with:

```bash
$ wkhtmltopdf --version
wkhtmltopdf 0.12.3 (with patched qt)
```

Btw, I chose 0.12.3 instead of 0.12.4 because of a strange page sizing issue, discussed here: 
https://github.com/wkhtmltopdf/wkhtmltopdf/issues/3226
