### ISSUE TITLE
Hyperlink(anchor tag) is not supported in the header and footer part

### ISSUE THREAD

**Issue by sathak** [wkhtmltopdf/wkhtmltopdf#2936]
Hi,

Hyperlink(anchor tag) is not supported in the header and footer part.can any one help me out of this.

**Comment by PhilterPaper** [comment]
That's an unusual request. Headers and footers are normally non-interactive parts of a document, added to the rest of the document by the formatter (e.g., wkHTMLtoPDF), and not found in the original [HTML] source. I'm trying to think of a situation where it would be useful to have a hyperlink in the header or footer. I suppose it might be used for some sort of navigation: to top of document, to end of document, to chapter beginning/end, etc. Is that the sort of thing you would be using it for, if the normal bookmark navigation doesn't suffice? Remember that a header or footer is given only as a _template_, so it would be difficult to put a unique link in it (i.e., it would have the same link on every page, to a large degree).

If someone wants to put the effort into it, I'm sure it could be done, but what are you trying to accomplish with this capability?

**Comment by sathak** [comment]
if the PDF design have some external links for particular page or entire PDF in header,how could you do that design?

**Comment by PhilterPaper** [comment]
As I said, I'm sure it could be done, to permit _some_ inline (non-block) HTML tags in the definition for headers and footers, and to treat this HTML like document input text, if someone felt this capability would be important enough to be worth adding. Could you give an example or two of what kind of things you would do with links in headers and footers? That might "sell" the idea to someone to actually put in the time and effort to implement it.

By the way, have you tried `--header-html` and `--footer-html` flags yet? Maybe they'll already do what you want.

**Comment by sathak** [comment]
I called the wkhtmltopdf engine from JSReport API for that scenario its not working in header and footer part.

**Comment by ashkulz** [comment]
@sathak: Please reopen with a minimal, reproducible test case which demonstrates the issue from the command-line. Otherwise, it could very well be a problem with the JSReport bindings.
