### ISSUE TITLE
wkhtmltopdf.exe -> pattern are not drawn correctly

### ISSUE THREAD

**Issue by giuliotn** [wkhtmltopdf/wkhtmltopdf#2937]
I saw that if the values are big in viewBox, the pattern is not scaled correctly.
another, the specify pattertransform=scale(2.0) not working

instead with wkhtmltoimage.exe the output image it's OK
[example.zip](https://github.com/wkhtmltopdf/wkhtmltopdf/files/258083/example.zip)

the version is  0.12.3.2

**Comment by alloylab** [comment]
is this still an issue on 0.12.5?
