### ISSUE TITLE
Missing required dependencies for centos

### ISSUE THREAD

**Issue by nmors** [wkhtmltopdf/wkhtmltopdf#2939]
I had to:

```
yum install urw-fonts libXext libXrender fontconfig libfontconfig.so.1 libXrender.so.1 libXext.so.6 libz.so.1 libstdc++.so.6
```

Only some of these are listed

Linux ed-app-dev 2.6.32-431.el6.x86_64 #1 SMP Fri Nov 22 03:15:09 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux

# cat /etc/redhat-release 
CentOS release 6.7 (Final)

**Comment by ashkulz** [comment]
It's a binary package, the exact command will vary from distro to distro. As per the website, dependencies are: `zlib, fontconfig, freetype, X11 libs (libX11, libXext, libXrender)`. You have mentioned:

Library | Comments
--- | ---
| urw-fonts | only required if you use default PDF fonts
| libXext libXrender libXrender.so.1 libXext.so.6 | covered above
| fontconfig libfontconfig.so.1 | covered above
| libz.so.1 | covered above
| libstdc++.so.6 | required by basically everything

Not sure what you expect me to document additionally.

**Comment by nmors** [comment]
When switching to the rhel compiled binary, i had to run also;
yum install libpng libjpeg

I had to install these packages all explicitly.. simply installing the packages recommended as per docs did not resolve dependencies for me.. just letting you know..

Maybe this will help someone else who ran into the same issue. This is centos6.7 in aws by the way

**Comment by nmors** [comment]
When making request to SSL using your recommended binary for centos 6.7 ('Linux, Stable'), I am getting this error:

```
QSslSocket: cannot call unresolved function SSLv23_client_method
QSslSocket: cannot call unresolved function SSL_CTX_new
QSslSocket: cannot call unresolved function SSL_library_init
QSslSocket: cannot call unresolved function ERR_get_error

wkhtmltopdf exited with code 1 [STACK TRACE]:Error: QSslSocket: cannot call unresolved function SSLv23_client_method
QSslSocket: cannot call unresolved function SSL_CTX_new
QSslSocket: cannot call unresolved function SSL_library_init
QSslSocket: cannot call unresolved function ERR_get_error

wkhtmltopdf exited with code 1
```

This also seems to be a dependecy problem, I raised here: #2938 

openssl is already installed

**Comment by ashkulz** [comment]
Can you paste the [dependencies reported on your system](http://stackoverflow.com/a/6242792)? libpng and libjpeg are compiled/linked statically, so you should not need to install them.
