### ISSUE TITLE
how and where wkhtmltopdf processes the height and width of the header, footer and content

### ISSUE THREAD

**Issue by luzfcb** [wkhtmltopdf/wkhtmltopdf#2940]
@ashkulz First, thank you for accepting my pull-request, and thank you for this project.
I'm having problems correctly position the contents of header, footer and content because they are dynamically generated by my system.

it was not clear to me how exactly wkhtmltopdf sets the header and footer height and the header and footer initial position in relation of the Paper .

currently, to get to show the contents of header and footer, I have to set for wkhtmltopdf

`--print-media-type --margin-top "61.5mm" --margin-left "1.0mm" --margin-right "3.5mm" --margin-bottom "47.5mm" --page-size A4`

the problem is that it does not work perfectly, because, depending on the content height of the header and  footer, the size and proportion of all document (HEADER + FOOTER + CONTENT) can change.

the way in header and especially footer is positioned in relation to the page is strange.

I will make a minimum HTML that demonstrates this...

1 - where in the source code of wkhtmltopdf processes the height and width of the header, footer and content?

2 - why apparently header and footer, appear to have the starting points `top`, `left`, `right` and `bottom` defined outside of the paper size limits?

![wkhtmltopdf_paper3](https://cloud.githubusercontent.com/assets/807599/15169721/cb0bc712-1714-11e6-9a55-694c5b306240.png)

**Comment by alloylab** [comment]
is this still an issue on 0.12.5?

**Comment by alloylab** [comment]
We are closing this out since we haven't heard from you. If you are still having this issue please feel free to re-open it. Thanks.
