### ISSUE TITLE
TOC - Table of content should repeat each page

### ISSUE THREAD

**Issue by sreedharprabhu** [wkhtmltopdf/wkhtmltopdf#2942]
TABLE OF CONTENT text is visible only on the first page, how to repeat the same text for all the table of content pages.
Current pdf file
[example_wkhtmltopdf_toc_current.pdf](https://github.com/wkhtmltopdf/wkhtmltopdf/files/258712/example_wkhtmltopdf_toc_current.pdf)

Expected pdf file
[example_wkhtmltopdf_toc_expected.pdf](https://github.com/wkhtmltopdf/wkhtmltopdf/files/258713/example_wkhtmltopdf_toc_expected.pdf)

**Comment by ashkulz** [comment]
That's not how the TOC is supposed to work.
