### ISSUE TITLE
<!DOCTYPE html> breaks position:fixed

### ISSUE THREAD

**Issue by asemahle** [wkhtmltopdf/wkhtmltopdf#2943]
The following HTML should display the word "Hello" using position:fixed.

``` html
<!DOCTYPE html>
<html lang="en">
<head>
    <style> 
        div {
            position: fixed;
            top:200px;
            left:200px;
        }
    </style>
</head>
<body>
    <div> 
        Hello
    </div>
</body>
</html>
```

When I run `wkhtmltopdf in.html out.pdf`, the result is a blank PDF.

But, if I remove `<!DOCTYPE html>`, then the PDF renders correctly.

Is this a known bug?

NOTE: I'm on Windows 10 (64 bit), using the wkhtmltopdf from the `wkhtmltox-0.12.3.2_msvc2013-win64.exe` installer.

**Comment by ashkulz** [comment]
Does this work on the `0.13 alpha` build?
