### ISSUE TITLE
How to put total number of page to pdf content

### ISSUE THREAD

**Issue by hoangbhvd** [wkhtmltopdf/wkhtmltopdf#2944]
Is it possible to put total number of page to body of html. I used jquery in script of footer-html but nothing happens.
<html>
  <head>
    <script>
      function number_pages() {
        var vars={};
        var x=document.location.search.substring(1).split('&');
        for(var i in x) {var z=x[i].split('=',2);vars[z[0]] = decodeURIComponent(z[1]);}
        var x=['frompage','topage','page','webpage','section','subsection','subsubsection'];
        for(var i in x) {
          var y = document.getElementsByClassName(x[i]);
          for(var j=0; j<y.length; ++j) y[j].textContent = vars[x[i]];
        }
    	
    	document.getElementById('page-num').innerHTML = vars.topage; 
      }
    </script>
  </head>
  <body style="border:0; margin: 0;" onload="number_pages()">
	  <table style="width: 100%">
	    <tr>
	      <td class="section"></td>
	      <td style="text-align:center">
	        Page <span class="page"></span> of <span class="topage"></span>
	      </td>
	    </tr>
	  </table>
  </body>
</html>
Thanks a lot.

**Comment by ashkulz** [comment]
Can you post a reproducible testcase?
