### ISSUE TITLE
"L" and "I" letters are displayed always bold

### ISSUE THREAD

**Issue by Pepozzo** [wkhtmltopdf/wkhtmltopdf#2945]
I'm using wkhtmltopdf 0.12.3 on Ubuntu Server 14.04 environment.

I'm facing this issue trying to generate a PDF from HTML.
![cattura](https://cloud.githubusercontent.com/assets/3300906/15209207/221354f0-1830-11e6-85c3-e722a5c74ed1.JPG)

As you can see, capital "i" and "l" are displayed bold.

This problem is not showing trying to generate the same PDF from the same HTML on a Windows Server machine.

Any suggestion?

**Comment by PhilterPaper** [comment]
Does a PDF generated on the Windows machine show the same problem on the Ubuntu machine? How about vice-versa: Ubuntu-generated PDF showing "bold" letters on a Windows machine? I doubt it's anything to do with wkHTMLtoPDF, or even QT, but most likely a poorly written font and/or renderer on the Ubuntu system. How does the original HTML show on the two systems?

**Comment by ashkulz** [comment]
Depends on the font. If you print it, does it look the same or looks OK? Due to high resolution, sometimes it looks bad -- zooming in 200-400% will reveal that there is no difference but at lower zoom levels it looks odd.

**Comment by twhaley3** [comment]
I am experiencing the same issue. I am using wkHTMLtoPDF on a windows system.

**Comment by ashkulz** [comment]
That's a kerning issue, not all fonts are designed to work well at low DPI screens. Using a font which is optimized for reading on screen will look OK.
