### ISSUE TITLE
target="_blank" links

### ISSUE THREAD

**Issue by denya-vs** [wkhtmltopdf/wkhtmltopdf#2947]
When wkhtmltopdf generate pdf, it cut taget attribute.
In result pdf links open in same tab in browser.
I use wkhtmltopdf 0.12.3 (with patched qt) on ubuntu 14.04.

**Comment by ashkulz** [comment]
I don't think that is supported by the PDF specification. If it is so, would appreciate a pointer to the particular section so that I can investigate the possibility.

**Comment by seanthebean** [comment]
Apparently it is possible to force links to open in a new tab/window using Acrobat Reader (by executing JavaScript, I think). See https://forums.adobe.com/thread/509409. Would it be feasible to check for `target="_blank"` in the HTML, and then edit the link as specified in that article?

**Comment by anupmaurya484** [comment]
hello there, i'm used  wkhtmltopdf plugin and i try to open the external link other tab but open the same tab  on this pdf so please would you help, how to do open the link other tabs.

`<a href="https://homeinspectortech.com" target="_blank"> Click on this site</a> `

Thank you.

**Comment by irfanvikki** [comment]
i'm using wkhtmltopdf version 0.12.5.0 but i'm unable to open external links in a new tab. My exteranl links are opened in the same tab.
<a href="https://homeinspectortech.com" target="_blank"> Click on this site</a>

**Comment by aliriocastro** [comment]
I think it's more how Chrome understands the <a> rather than the PDF.

**Comment by amorimlucas** [comment]
I also have this issue. Was it ever solved?
