### ISSUE TITLE
line break in pre.code block

### ISSUE THREAD

**Issue by lisongmin** [wkhtmltopdf/wkhtmltopdf#2948]
Can not copy code in pdf to other text editor with original format, the lines are break.

Line will be broken if there is more than 3 spaces in "DejaVu Sans Mono" font,
or 6 spaces in Arail font. 

test case is below:
https://gist.github.com/lisongmin/6260b0a01b55fc12448dd9e711c46844

```
$ wkhtmltopdf /tmp/line_break.html /tmp/c.pdf
Loading pages (1/6)
Counting pages (2/6)
Resolving links (4/6)
Loading headers and footers (5/6)
Printing pages (6/6)
Done
```

```
$ wkhtmltopdf --version
wkhtmltopdf 0.12.3 (with patched qt)
```

**Comment by PhilterPaper** [comment]
Check to make sure that you don't actually have a **tab** in those long runs of spaces, and also read http://stackoverflow.com/questions/4611591/code-vs-pre-vs-samp-for-inline-and-block-code-snippets for some discussion on `<code>`, `<pre>`, and `<samp>` tag usage. After checking that your HTML code is proper (you might also want to run it through the W3C validator), are you still having problems with runs of spaces being broken?

**Comment by lisongmin** [comment]
Thanks for quick reply.

yes, I'm sure no tab in it. 
and the html running well in firefox.

The problem only in the pdf .  When I select text from pdf, spaces more than 3 are not selectable.
show below:

![20160515t215721_969x334_scrot](https://cloud.githubusercontent.com/assets/2513062/15274594/81de749a-1ae8-11e6-95f7-98257cd8ecfd.png)

**Comment by PhilterPaper** [comment]
So your circled spaces are selectable in a browser (HTML) but not in a PDF? As this is `<pre>` and `<code>`, runs of normal spaces do not appear to be collapsed down to single spaces. I wonder if WebKit *is* collapsing them down, and then re-expanding them in some way (perhaps through tabs)? That would seem to be a glitch or bug in WebKit. Can you use a tool such as PDFtk to uncompress the stream and see if these are (as in the original source, I presume) runs of x20 spaces, or are they turned into tabs? 

Are you using Adobe Reader to display and interact with the PDF?  I wonder if your PDF reader is having some sort of problem, and the PDF itself is perfectly fine. Even if wkHTMLtoPDF replaced some runs of spaces with tabs, shouldn't those still be selectable in the PDF reader?

**Comment by lisongmin** [comment]
That's right, it is a dpf reader problem. No problem in Adobe Reader.

I'm using evince as pdf reader which cause the bug.

thanks very much.

**Comment by ashkulz** [comment]
Thanks @PhilterPaper, I notice you have been commenting on a lot of issues. Appreciate it hugely :+1:
