### ISSUE TITLE
Wkhtmltopdf not generating my ReactJs App

### ISSUE THREAD

**Issue by marlon407** [wkhtmltopdf/wkhtmltopdf#2952]
Hi all, 
I am using wkhtmltopdf version 0.12.2.1 (with patched qt) and when I try to generate a PDF from my React App with the option --debug-javascript the following message is returned:

```
desenv01@desenv01-PC:~$ wkhtmltopdf --debug-javascript  http://localhost:3000/report/1 react-report.pdf
Loading pages (1/6)
Warning: undefined:0 TypeError: 'undefined' is not a function     
Warning: undefined:0 TypeError: 'undefined' is not an object
Warning: undefined:0 TypeError: 'undefined' is not an object
Warning: undefined:0 ReferenceError: Can't find variable: React
Counting pages (2/6)                                               
Resolving links (4/6)                                                       
Loading headers and footers (5/6)                                           
Printing pages (6/6)
Done
```

Then when I go see the pdf, nothing is generated.

So, I tried to use the version 0.13alpha and it seems to work nicely with ReactJs. It renders the information respecting the CSS for media print. However, I have a table which has a thead and tbody with several rows. When my PDF has more than 1 page, the thead is not being repeated on every page, only on the first one. The following CSS properties are being set on thead, tbody and th:

```
  thead { display: table-header-group !important; }
  tfoot { display: table-row-group }
  tbody { display: table-row-group }
  tr {
    page-break-inside: avoid !important;
    position: relative;
   }
```

This behaviour seems only to happen in version 0.13alpha. Even with a simple page (with no ReactJs), in version 0.13alpha, the thead does not repeat, but in version 0.12.2.1 it works fine. 

BTW, I tested on Ubuntu 14.01 and CentOS release 6.7 (Final).

I hope I was clear enough to explain my problem.. :D

**Comment by ashkulz** [comment]
You probably need a polyfill, see facebook/react#3609

**Comment by ashkulz** [comment]
Also, the wkhtmltopdf-specific patches have not been ported to 0.13 alpha.

**Comment by marlon407** [comment]
Yeah, that was exactly the error. I needed a polyfill indeed!
Thank you for the quick reply!

**Comment by developersoul** [comment]
What polyfill do you use? @marlon407

**Comment by marlon407** [comment]
@developersoul, these:
<script src="https://cdnjs.cloudflare.com/ajax/libs/es5-shim/4.5.7/es5-shim.min.js"></script>
 <script src="https://cdnjs.cloudflare.com/ajax/libs/es5-shim/4.5.7/es5-sham.min.js"></script>
 <script src="https://cdnjs.cloudflare.com/ajax/libs/json3/3.3.2/json3.min.js"></script>
 <script src="https://cdnjs.cloudflare.com/ajax/libs/es6-shim/0.34.2/es6-sham.min.js"></script>
 <script src="https://wzrd.in/standalone/es7-shim@latest"></script>

**Comment by needcaffeine** [comment]
Sadly this didn't work for me with 0.12.3. Still getting blank pages.

**Comment by marlon407** [comment]
@needcaffeine  are you getting any error when running with  '--debug-javascript'?

**Comment by needcaffeine** [comment]
Okay, so a few things.

The es7-shim link above was broken. I replaced it with `npm install es7-shim` and linked to that file, which made it so that the PDF got generated, but all the text was missing. The PDF contained just images and layout divs (they have a background color). Changing the Google Font to instead be just sans-serif results in text getting printed. Looks awful, but it's all there at least.

So I went up to 0.12.4, and now the entire PDF got generated, but with the wrong DPI. This seems to be a known bug: #3241.

Ideally I'd get this to work in 0.12.3, because that's the version our server uses.

**Comment by RaulTsc** [comment]
Also having issues trying to generate a pdf from a React component, it outputs a lot of blank space for some reason.

@needcaffeine would you by any chance have 15 mins to take a quick look together, maybe you have some ideas?

**Comment by lod** [comment]
Update because this was the best reference I found.
I got wkhtmltopdf working by putting the following in my index.html


    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/es5-shim/4.5.10/es5-shim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/json3/3.3.2/json3.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/es6-shim/0.35.3/es6-sham.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/es7-shim/6.0.0/es7-shim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/babel-polyfill/6.16.0/polyfill.min.js"></script>


It is probably possible to optimise this list but that isn't required for my use case.

**Comment by cooervo** [comment]
thanks to @lod , but only the last polyfill is needed

**Comment by raykudo** [comment]
```
$ wkhtmltoimage -V
wkhtmltoimage 0.12.5 (with patched qt)

$ wkhtmltoimage --images --disable-smart-width --custom-header 'User-Agent' 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36' --custom-header-propagation --enable-javascript --javascript-delay 10000 --load-error-handling ignore --no-stop-slow-scripts --debug-javascript --width 1024 --height 1024 --enable-plugins http://web.archive.org/ sample.jpg
Loading page (1/2)
Warning: undefined:0 ReferenceError: Can't find variable: Set     
Warning: undefined:0 TypeError: 'undefined' is not a function
libpng warning: iCCP: known incorrect sRGB profile           ] 62%
Rendering (2/2)                                                    
Done        
```

This command generates a picture with only the header and footer of http://web.archive.org/. 
```<div id="react-wayback-search">...</div>``` part is not rendered and missing. I guess it's something to do with React, ES6 or 7. What can I do if it's not my own website? I can use a polyfill for wkhtmltoimage with any command options to compensate for the undefined fucntion?
