### ISSUE TITLE
Agularjs.js -> Unable to parse JSON string

### ISSUE THREAD

**Issue by RazorNguyen** [wkhtmltopdf/wkhtmltopdf#2953]
I used a stable version to export a page using angular framework. It throws a exception "Unable to parse JSON string" at angular.js file and never reach to $window.status statement. But Alpha version works well, just having minor issue is displaying black-white color.

I wondering "unable to parse JSON string" issue is a bug of Agular framework or webkit or wkhtmltopdf?

**Comment by ashkulz** [comment]
You probably need a polyfill, as the WebKit version used is very old.

**Comment by RazorNguyen** [comment]
Could you help me how to upgrade Webkit version to the latest?

**Comment by ashkulz** [comment]
@RazorNguyen: use the 0.13 alpha builds, but please note that a lot of wkhtmltopdf-specific features will not work (they haven't been ported to it yet).
