### ISSUE TITLE
Character set is not displayed correctly 

### ISSUE THREAD

**Issue by Techem8** [wkhtmltopdf/wkhtmltopdf#2954]
Hi,
I have a problem with the character set representation on various Linux Redhat systems.
On local machine everything works fine:

![local-host](https://cloud.githubusercontent.com/assets/19433013/15365355/368b1428-1d20-11e6-9935-de78f14f5ff9.png)
System: Linux 2.6.32-504.16.2.el6.x86_64 #1 SMP Tue Mar 10 17:01:00 EDT 2015 x86_64 x86_64 x86_64 GNU/Linux

On Linux Server the same looks like that:

![server](https://cloud.githubusercontent.com/assets/19433013/15365393/667ecd32-1d20-11e6-82a6-5d06ca04f2ae.png)
System:
Linux 2.6.32-573.1.1.el6.x86_64 #1 SMP Tue Jul 14 02:46:51 EDT 2015 x86_64 x86_64 x86_64 GNU/Linux

On both systems the file encoding is set to:
input filename -->  2000.html: text/html; charset=iso-8859-1
outputfilename --> 2000.html.pdf: application/pdf; charset=binary

wkhtmltopdf version: wkhtmltox-0.12.3_linux-generic-amd64.tar.xz

Does anyone have an idea what could be causing that.

Kind regards
Lili

**Comment by PhilterPaper** [comment]
What fonts are being used here? I'm wondering if you are specifying a font that exists on the local machine, but not on the server. Servers are often set up with minimal collections of fonts. In your page HTML, do the font-family entries have a generic fallback (serif, sans-serif, monospace, etc.)?

**Comment by ashkulz** [comment]
This is typically due to missing font packages, install the `urw-fonts` package. If that doesn't work, examine what other font packages are installed on your development machine.

**Comment by Techem8** [comment]
Hi,

Thanx for supporten me.

Your right on Server configuration the fonts are not installed.
After installing it works fine.

Kind regards
Lili

Von: Ashish Kulkarni [mailto:notifications@github.com]
Gesendet: Donnerstag, 19. Mai 2016 7:56
An: wkhtmltopdf/wkhtmltopdf
Cc: Lah, Liljana; Author
Betreff: [Newsletter]: Re: [wkhtmltopdf/wkhtmltopdf] Character set is not displayed correctly (#2954)


Closed #2954<https://github.com/wkhtmltopdf/wkhtmltopdf/issues/2954>.
