### ISSUE TITLE
IBM AIX system don't work

### ISSUE THREAD

**Issue by zhihongzzh** [wkhtmltopdf/wkhtmltopdf#2955]
on IBM AIX system don' work

**Comment by ashkulz** [comment]
Can you provide details on what doesn't work? As I don't have an AIX system, can't help you without details.

**Comment by zhihongzzh** [comment]
thanks ,it's will must use IBM AIX rebuild?

**Comment by ashkulz** [comment]
@zhihongzzh: I'm sorry, but I don't get what you want.
