### ISSUE TITLE
Add Ubuntu Xenial (16.04) to Releases

### ISSUE THREAD

**Issue by stramel** [wkhtmltopdf/wkhtmltopdf#2960]
Would love to see a deb release for Xenial (16.04) for 0.13.x

**Comment by ashkulz** [comment]
Distro-specific packages have been deprecated in favor of the distro-agnostic tarball since `0.12.3`. The targets will be removed from the build script in the near future.

**Comment by kayakyakr** [comment]
@ashkulz if that's the case, is there a way to get a distro-agnostic tarball for 0.13.x? Right now the only pre-built instances available are all target-specific.

Though it does seem like 0.13 has been largely abandoned which is a shame as I need the capabilities of qt webkit 5.

**Comment by jwilliams-ecometrica** [comment]
@ashkulz We would also be interested in a distro-agnostic tarball for 0.13x.

**Comment by stramel** [comment]
Anyone looking for cross-platform solution, I would highly recommend some form of Chrome-headless since it runs on every OS and has a much more up-to-date browser engine. Check out https://github.com/GoogleChrome/puppeteer

**Comment by jwilliams-ecometrica** [comment]
Hi @stramel, 

Thanks for the suggestion but that's not really what we were looking for.

**Comment by stramel** [comment]
@jwilliams-ecometrica Mind telling me your use-case? I feel like it replaces this tool

**Comment by jwilliams-ecometrica** [comment]
@stramel, 

Sure it's basically rendering a react template straight to pdf on a server.

**Comment by mamiu** [comment]
@jwilliams-ecometrica 
Absolutely no problem with puppeteer! Have a look at it.

**Comment by kayakyakr** [comment]
Haven't found a reasonable headless-chrome ruby library yet. There's a Selenium driver for it, but it doesn't seem to support PDF printing. That is a little cleaner an implementation than the tarball that I'm dragging around.
