### ISSUE TITLE
mass conversions

### ISSUE THREAD

**Issue by dconradda** [wkhtmltopdf/wkhtmltopdf#2963]
Greetings - I have several thousand html files on my computer that I would like to convert to pdf files. I was hoping wkhtmltopdf would be able to do this 

Specs: using v0.12.3 on Mac OSx ElCapitan 10.11.3

Some solutions that I've tried: 
wkhtmltopdf *.html *.pdf
for f in *.html; do ./wkhtmltopdf "$f" $f.pdf"

Does the original file have to be http? Can it be a file on my computer?

**Comment by rruchte** [comment]
For a simple shell solution, this will do the trick:

for f in *.html;do wkhtmltopdf $f $f.pdf;done

Wkhtmltopdf can load HTML documents over http or https in addition to html files on the filesystem.

wkhtmltopdf http://google.com google.pdf
wkhtmltopdf https://google.com google_https.pdf

**Comment by ashkulz** [comment]
If what @rruchte doesn't serve your purpose, please describe your problem in more detail.

**Comment by dconradda** [comment]
that did the trick @rruchte thank you!

**Comment by dconradda** [comment]
I'm also attempting this on Windows 7 and the script returned the message "f was unexpected at this time". Should I adjust the script for command prompt?

**Comment by ashkulz** [comment]
@dconradda: use the equivalent batch command, type `FOR /?` in a command prompt for examples.

**Comment by dconradda** [comment]
Thank you @ashkulz - I tried the commands 
FOR /? *.html;do wkhtmltopdf $f $f.pdf;done 
and FOR /? *.html wkhtmltopdf *.pdf
But neither command is working.
