### ISSUE TITLE
wkhtmltopdf can't load assets

### ISSUE THREAD

**Issue by halimchaibi** [wkhtmltopdf/wkhtmltopdf#2964]
Hi,
After upgrading from 0.10 version to the last stable version (0.12.3) wkhtmltopdf is no longer able to load assets.
Warning: Failed to load http://10.0.5.31/wa/assets/application-c68e7808d31c2fe4d4ec4060176f21b1fa2664857ef9eeb8f5930dcc67ad76ce.js

**Comment by ashkulz** [comment]
Please produce a public, reproducible test case which can be investigated. Alternatively, post some network dumps which identify it as a problem with wkhtmltopdf and not your connectivity.
