### ISSUE TITLE
wkhtmltopdf Exit with code 1 due to network error: UnknownNetworkError

### ISSUE THREAD

**Issue by halimchaibi** [wkhtmltopdf/wkhtmltopdf#2965]
We use wkhtmltopdf to export as pdf a part of our content web site.
We need to access the web site using https.
We start having an issue with wkhtmltopdf after disabling support for the export and null cipher suites in out proxy to meet some security standard.
wkhtmltopdf Exit with code 1 due to network error: UnknownNetworkError
Thank you

**Comment by ashkulz** [comment]
Is this with the latest version of wkhtmltopdf? If so, then you probably need to upgrade your OpenSSL packages on Linux.

**Comment by spstratis** [comment]
What if this issue is on a windows machine?
