### ISSUE TITLE
Unable to load adobe.com using this code

### ISSUE THREAD

**Issue by archanakanakamedala** [wkhtmltopdf/wkhtmltopdf#2966]
I am trying to use the given wrapper for adobe.com, and its taking forever to complete the request and is not giving the output. Waiting at "var output = p.StandardOutput.ReadToEnd();"  Any suggestions?

![adobetopdf](https://cloud.githubusercontent.com/assets/19556870/15513315/ec7402c8-2198-11e6-8850-8760aa2cd363.png)

**Comment by archanakanakamedala** [comment]
Also another question is does wkhtmltopdf work with javascript based files?

**Comment by ashkulz** [comment]
Please post an actual command-line which fails to work.
