### ISSUE TITLE
Use SimHei Font in css cause render incorrect

### ISSUE THREAD

**Issue by gongqf** [wkhtmltopdf/wkhtmltopdf#2967]
```html
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title>wkhtmltopdf test</title>
    <style type="text/css">
        body{
            font-size:32pt;
        }
        .sun{
            font-family:SimSun,"宋体";
        }
        .hei{
            font-family:SimHei,"黑体";
        }
    </style>
</head>
<body>
    <div class="sun">SimSun 宋体 abcEDF 0123</div>
    <div class="hei">SimHei 黑体 abcEDF 0123</div>
    <div class="sun">SimSun 宋体 abcEDF 0123</div>
    <div>SimSun 宋体 abcEDF 0123</div>
</body>
```

![image](https://cloud.githubusercontent.com/assets/751931/15526054/8e505628-2261-11e6-8ee8-99b61042b544.png)
in win7x64 chrome 50

![image](https://cloud.githubusercontent.com/assets/751931/15526163/53948a94-2262-11e6-8864-2d0deb89adae.png)
use wkhtmltopdf 0.12.3.2 x86 version
use SimHei font, display incorrect

![image](https://cloud.githubusercontent.com/assets/751931/15526214/a2aa7184-2262-11e6-87c0-982592ba469c.png)
not use SimHei,only use SimSun font in css

![image](https://cloud.githubusercontent.com/assets/751931/15526224/c3b30864-2262-11e6-807a-e1352f9ed865.png)
use wkhtmltopdf 0.13.0-alpha-7b36694 x64 version

**Comment by ashkulz** [comment]
A detailed explanation in words summarizing the problems would be more helpful, as I don't read chinese and it's hard for me to figure out what's wrong.

**Comment by gongqf** [comment]
Wkhtmltopdf 0.12.3.2 32bit with the html files converted into pdf, if you do not specify a font in css or use SimSun fonts (fonts are SimSun windows 7 Chinese version of the operating system default font used by the browser), converted into a pdf file, SimSun Chinese text font rendering is correct.
Once the increase in the use of a SimHei font (another Chinese font) in css, the converted pdf files, specified as SimHei font text is garbled (non-Chinese characters), and the text rendering is not specified SimHei font.
This problem has troubled me for a long time, cause I can not use two or more kinds of Chinese fonts in html file.
Conversion test html file and pdf content rendered in a screenshot in question.

Unfortunately, due to poor English proficiency, use google translation from above.

**Comment by vicktoliam** [comment]
@gongqf 那你解决了字体问题不。我现在被微软雅黑搞得好头疼。。。我已然感觉到你是中国人

**Comment by gongqf** [comment]
@vicktoliam 没有，现在没办法，0.12.3版本至少在windows平台下是无解的。0.13版本稍微好点，但也有问题。

**Comment by vicktoliam** [comment]
@gongqf 主要是他不同版本呈现不同。用最新版本的导出的自动缩放 disableshrinking没用 但是字体是对的。老版本不缩放 字体如果是雅黑的话间距就出问题了 要不加QQ一块讨论下？

**Comment by gongqf** [comment]
@vicktoliam 0.12.3我是用zoom 2 缩放才正常

**Comment by vicktoliam** [comment]
[4d839e60-719e-4b52-a39e-34728c8eee82.pdf](https://github.com/wkhtmltopdf/wkhtmltopdf/files/358864/4d839e60-719e-4b52-a39e-34728c8eee82.pdf)
http://www.jianlipro.com/resume.html?m_id=29704 我字体已经加载到了 只是间距无法调整 你可以看一下

**Comment by gongqf** [comment]
@vicktoliam 你这个是微软雅黑字体，不是黑体。另，你是用那个版本？什么平台下转pdf的？

**Comment by vicktoliam** [comment]
微软雅黑简直是无解的。我也是windows环境下。我写的.net的接口

**Comment by dengzhichao** [comment]
@vicktoliam 您好，我看到您的标点符号是正常出现在字的右下角的，我的出现在字的中间位置，请问您是如何处理的。
![2016-11-14 17 00 13](https://cloud.githubusercontent.com/assets/15209805/20258712/de8899cc-aa8b-11e6-9d7f-5475cc87b390.png)

**Comment by vicktoliam** [comment]
你这个用的是圆角标点吧。

**Comment by woosungchu** [comment]
Someone please translate those chinese... none without chinese people what's going on this issue...

**Comment by dengzhichao** [comment]
@vicktoliam 折腾好久终于折腾出来了，句号在中间问提是字体问题，你们加载SImHei问题： 
answer is here :https://actom.me/blog/font-face-%e8%a7%a3%e5%86%b3wkhtmltopdf%e7%9a%84%e4%b8%ad%e6%96%87%e6%98%be%e7%a4%ba%e9%97%ae%e9%a2%98.html

**Comment by alloylab** [comment]
have you tried this on 0.12.5?

**Comment by Tomsgu** [comment]
I am closing this issue since there is no feedback and comments are not in english. Please feel free to re-open the issue if it still doesn't work in `0.12.5` version.
