### ISSUE TITLE
Insert a Page break

### ISSUE THREAD

**Issue by n2vball** [wkhtmltopdf/wkhtmltopdf#2968]
Is there a way for wkhtmltopdf to insert a page break based on a phrase/term or code that is printed in the HTML.

I have source issues with wkhtmltopdf  being to create a PDF directly from the web HTML so I have to save webpage as an Webpage Only HTML file. When I run wkhtmltopdf against the local drive a PDF is created just as it would be in the WEB HTML but I need the PDF to have a page break separation at a certain part of the HTML. I am looking to see if a specific phrase/term/word in the PDF could trigger the "Page Break".

The phrase/term/word would be like...

www.Thiswebpag.com

So every time this phrase was in the HTML, there would be a page break that followed the phrase and then the content after the phrase would be on a separate page until the end or until the next time the phrase came up.

I hope that makes sense.

**Comment by ashkulz** [comment]
If you can create a `<DIV>`, you can use `page-break-after: always` on that to enforce this.

**Comment by martinko2009** [comment]
but if div is float, page-break-after: always doest work.How can I resolve this.

**Comment by viswa18** [comment]
page-break-after: always not works for me.. if any solution, please post here.
