### ISSUE TITLE
Debug pfd

### ISSUE THREAD

**Issue by Stefan3001** [wkhtmltopdf/wkhtmltopdf#2969]
Hi,

I would like to know what webkit engine WKHtmltopdf is using and what version of it? Also it would be interesting for to know if you have any tips regarding debugging since I'm experiencing some issues in the created PDF (some stuff looks different than in the source HTML file).

Thanks in advance!

Best Regards
Stefan

**Comment by ashkulz** [comment]
It uses an old version of WebKit (equivalent to Chrome 12). You can use [QtWeb](http://www.qtweb.net/) to see how pages would roughly look like in this version.
