### ISSUE TITLE
Error when running command

### ISSUE THREAD

**Issue by dconradda** [wkhtmltopdf/wkhtmltopdf#2971]
Greetings -
1) I just installed v0.12.3.2 on Windows 7 (64-bit)
2) opened cmd.exe and changed to the directory that holds the html files
3) typed in "wkhtmltopdf *.html *.pdf"
4) getting the error that 'wkhtmltopdf' is not recognized as an internal or external command, operable program or batch file. 

I also tried adding .exe to the end of wkhtmltopdf and excluding the *.html and *.pdf

Thank you in advance! I have a lot of html files to convert. Thank you!

**Comment by PhilterPaper** [comment]
It's looking for wkhtmltopdf.exe or .bat or .com, according to the %PATH% environmental variable. Depending on where wkhtmltopdf.exe was installed, you may need to add a directory entry to PATH.

**Comment by dconradda** [comment]
The .exe was installed in the Programs folder.

**Comment by PhilterPaper** [comment]
It's not finding it. Either you put it in the wrong place, or in a place that's not listed in %PATH%. Check where you put it, if it is in fact runnable there, and if PATH lists that directory. It has to be one of those things.

**Comment by dconradda** [comment]
Its located here: C:\Program Files (x86)\wkhtmltopdf\bin\wkhtmltopdf.exe @PhilterPaper

**Comment by dconradda** [comment]
I moved it over to C:\Windows and now I get an error after running C:\Windows\wkhtmltopdf\bin\wkhtmltopdf.exe *.html *.pdf
Exit with code 1 due to network error: HostNotFoundError

It works if I specify a file, like in C:\Windows\wkhtmltopdf\bin\wkhtmltopdf.exe 2.html 2.pdf

**Comment by PhilterPaper** [comment]
When it was in C:\Program files (x86)\ **wkhtmltopdf\bin\**, did you have that entry in PATH (*not* just C:\Program Files (x86), but the full path)?

**Comment by dconradda** [comment]
had the full path. But I've since moved it over to C:\Windows\wkhtmltopdf\bin\wkhtmltopdf.exe
