### ISSUE TITLE
shell_exec strange errors

### ISSUE THREAD

**Issue by hezhez** [wkhtmltopdf/wkhtmltopdf#2974]
Hi !

When i try to run simple command - "xvfb-run /usr/local/bin/wkhtmltoimage http://website.com 1.jpg" from ssh cli, everything works great, but if i take the same command and put it inside shell_exec i get those errors:

xkbcommon: ERROR: failed to add default include path auto
Qt: Failed to create XKB context!
Use QT_XKB_CONFIG_ROOT environmental variable to provide an additional search path, add ':' as separator to provide several search paths and/or make sure that XKB configuration data directory contains recent enough contents, to update please see http://cgit.freedesktop.org/xkeyboard-config/ .
1   0x18b2e37 /usr/local/bin/wkhtmltoimage() [0x18b2e37]
2   0x18f5ed5 /usr/local/bin/wkhtmltoimage() [0x18f5ed5]
3   0x16d7b93 /usr/local/bin/wkhtmltoimage() [0x16d7b93]
4   0x17fee02 /usr/local/bin/wkhtmltoimage() [0x17fee02]
5   0x4ce569 /usr/local/bin/wkhtmltoimage() [0x4ce569]
6   0x49ebf9 /usr/local/bin/wkhtmltoimage() [0x49ebf9]
7   0x469de1 /usr/local/bin/wkhtmltoimage() [0x469de1]
8   0x46c9f0 /usr/local/bin/wkhtmltoimage() [0x46c9f0]
9   0x43a8fb /usr/local/bin/wkhtmltoimage() [0x43a8fb]
10  0x43e876 /usr/local/bin/wkhtmltoimage() [0x43e876]
11  0x43f2af /usr/local/bin/wkhtmltoimage() [0x43f2af]
12  0x43f4a5 /usr/local/bin/wkhtmltoimage() [0x43f4a5]
13  0x45a8a7 /usr/local/bin/wkhtmltoimage() [0x45a8a7]
14  0x44267e /usr/local/bin/wkhtmltoimage() [0x44267e]
15  0x42a2c9 /usr/local/bin/wkhtmltoimage() [0x42a2c9]
16  0x7fcc7cf28d5d /lib64/libc.so.6(__libc_start_main+0xfd) [0x7fcc7cf28d5d]
17  0x42add1 /usr/local/bin/wkhtmltoimage() [0x42add1]

It driving me crazy !

Any ideas ?

**Comment by ashkulz** [comment]
If it works from the command-line, you'll have to ensure you have a similar environment/setup when running under PHP.

**Comment by hezhez** [comment]
Can you please explain what do you mean by saying - "similar environment/setup when running under PHP" ?

If i write in php - shell_exec('wkhtmltopdf -version') i get correct output, so the shell_exec() is working good, can you explain me the specific error i wrote ?

**Comment by ashkulz** [comment]
@hezhez: when running under PHP, you are running as the `wwwroot` user with a more limited environment. A lot of distributions also enforce hardened settings, which cause the difference between running as a normal user and from within PHP.

**Comment by hezhez** [comment]
I'm running it as root, and still having the same problem... are you reconsigning the error ?
