### ISSUE TITLE
Memory leaks?

### ISSUE THREAD

**Issue by ly0** [wkhtmltopdf/wkhtmltopdf#2975]
wkhtmltopdf 0.12.2.1 (with patched qt)

I just found the consume of memory is raising raising raising by wkhtmltopdf.
and my server, boooooom

**Comment by ashkulz** [comment]
And boooom, an issue without any details gets closed!

**Comment by steffenbrem** [comment]
Also having memory issues with this library

**Comment by alexrayu** [comment]
Also have this issue. When mass-generating PDFs for Drupal 8 via a Drush script, I have memory usage slowly increase with each converted file, until it starts raising 'Out of memory' errors.

**Comment by Verurteilt** [comment]
Also getting this issue up to 3GB of RAM to create 22 PDFS of 2 pages everyone
