### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by arantoun** [wkhtmltopdf/wkhtmltopdf#2980]
Dear Friends. 

I am using wkhtmltopdf in my installation of ERPNext / Frappe. 

When converting a quotation to pdf I am getting time outs and nginx throws 504 error. 

I checked in my system logs and I found the error below in my /var/log/syslog/ 

Jun  4 16:20:09 erp kernel: [  775.675088] wkhtmltopdf[2158]: segfault at 3c097f0 ip 0000000003c097f0 sp 00007ffd988e0fc8 error 15

I am running the latest version of ERPnext on Ubuntu 14.04 server

I installed all possible versions of wkhtmltopd 0.12.2.1 and 0.12.3

I am really frustrated as this is stopping our work and i really appreciate if someone can help me to debug this error and find the root cause and fix it. 

Thanks a lot 
Ara

**Comment by alloylab** [comment]
is this still an issue on 0.12.5?

**Comment by tiwiex** [comment]
same issue here. slowing work down. arhhhhh.
