### ISSUE TITLE
Can't create a pdf file from these urls.

### ISSUE THREAD

**Issue by timlee1** [wkhtmltopdf/wkhtmltopdf#2981]
Why can't wkhtmltopdf create a pdf file from these urls?
What shall I do?
Thanks.

$ cat urls
http://web.mta.info/metrocard/
http://web.mta.info/metrocard/mcgtreng.htm
http://web.mta.info/nyct/fare/FaresatAGlance.htm
http://web.mta.info/metrocard/EasyPayXpress.htm
http://web.mta.info/metrocard/zipmaps.htm
http://web.mta.info/metrocard/easyuse.htm
http://web.mta.info/metrocard/where_accept.htm
http://web.mta.info/nyct/fare/rfindex.htm
http://web.mta.info/metrocard/EasyPayXpress.htm
http://web.mta.info/metrocard/merchant_index.htm
http://web.mta.info/metrocard/problems.htm
https://efixmetrocard.mtanyct.info/
http://web.mta.info/metrocard/problems.htm#expired
http://web.mta.info/metrocard/tourism/mc_promotions.htm
http://web.mta.info/metrocard/balanceprotection.htmt

$ wkhtmltopdf --javascript-delay 10000 $(cat urls) all.pdf
Loading pages (1/6)
Warning: SSL error ignored  
Error: Failed loading page http://web.mta.info/metrocard/tourism/mc_promotions.htm (sometimes it will work just to ignore this error with --load-error-handling ignore)
Warning: A finished ResourceObject received a loading progress signal. This might be an indication of an iframe taking too long to load.
Warning: Received createRequest signal on a disposed ResourceObject's NetworkAccessManager. This might be an indication of an iframe taking too long to load.
Error: Failed loading page http://web.mta.info/metrocard/tourism/mc_promotions.htm (sometimes it will work just to ignore this error with --load-error-handling ignore)
Error: Failed loading page http://web.mta.info/metrocard/balanceprotection.htm (sometimes it will work just to ignore this error with --load-error-handling ignore)
Warning: A finished ResourceObject received a loading progress signal. This might be an indication of an iframe taking too long to load.
Warning: Received createRequest signal on a disposed ResourceObject's NetworkAccessManager. This might be an indication of an iframe taking too long to load.
QFont::setPixelSize: Pixel size <= 0 (0)
Warning: Failed to load https://efixmetrocard.mtanyct.info/Library/images/nyct.png (ignore)
Error: Failed loading page http://web.mta.info/metrocard/ (sometimes it will work just to ignore this error with --load-error-handling ignore)
Warning: A finished ResourceObject received a loading progress signal. This might be an indication of an iframe taking too long to load.
Warning: Received createRequest signal on a disposed ResourceObject's NetworkAccessManager. This might be an indication of an iframe taking too long to load.
Error: Failed loading page http://web.mta.info/metrocard/problems.htm#expired (sometimes it will work just to ignore this error with --load-error-handling ignore)
Warning: A finished ResourceObject received a loading progress signal. This might be an indication of an iframe taking too long to load.
Error: Failed loading page http://web.mta.info/metrocard/ (sometimes it will work just to ignore this error with --load-error-handling ignore)
Error: Failed loading page http://web.mta.info/nyct/fare/rfindex.htm (sometimes it will work just to ignore this error with --load-error-handling ignore)
Warning: A finished ResourceObject received a loading progress signal. This might be an indication of an iframe taking too long to load.
Error: Failed loading page http://web.mta.info/metrocard/merchant_index.htm (sometimes it will work just to ignore this error with --load-error-handling ignore)
Warning: Received createRequest signal on a disposed ResourceObject's NetworkAccessManager. This might be an indication of an iframe taking too long to load.
Warning: A finished ResourceObject received a loading progress signal. This might be an indication of an iframe taking too long to load.
Warning: Received createRequest signal on a disposed ResourceObject's NetworkAccessManager. This might be an indication of an iframe taking too long to load.
Warning: Received createRequest signal on a disposed ResourceObject's NetworkAccessManager. This might be an indication of an iframe taking too long to load.
Warning: Received createRequest signal on a disposed ResourceObject's NetworkAccessManager. This might be an indication of an iframe taking too long to load.
Warning: Received createRequest signal on a disposed ResourceObject's NetworkAccessManager. This might be an indication of an iframe taking too long to load.
Exit with code 1 due to network error: ProtocolUnknownError

**Comment by alloylab** [comment]
is this still an issue on 0.12.5?
