### ISSUE TITLE
huge files when embedding fonts

### ISSUE THREAD

**Issue by fommil** [wkhtmltopdf/wkhtmltopdf#2983]
as an example, download http://unintelligible.org/onlisp/onlisp.html and change the CSS section to the following (download the two referenced truetype files, they are both libre fonts) and run

```
wkhtmltopdf --page-width 20.25cm \
            --page-height 27cm \
            --margin-top 15mm \
            --margin-bottom 15mm \
            onlisp.html onlisp.pdf
```

and get a **huge** (500MB or so for me) output file.

It would appear that embedded fonts are being duplicated, is this a known issue? I couldn't find any options in the man page or extended options to optimise embedding of fonts.

This makes changing the default font incredibly difficult.

Another, somewhat related, use case I have is that I'd like to use Palatino (which I believe is part of the PDF specification and wouldn't need to be embedded) but there is no way to specify it as a font except embedded and that results in huge files.

```
    <style type="text/css">
      @font-face {
        font-family: Hack;
        src: url(/home/fommil/.fonts/Hack-Regular.ttf) format('truetype');
      }

      @font-face {
        font-family: AbhayaLibre;
        src: url(/home/fommil/.fonts/AbhayaLibre-Regular.ttf) format('truetype');
      }

      table {
        margin-left:auto; 
    margin-right:auto;
      }

      pre { font-family: Hack; }

      .example {
            border: 1px solid black;
            background-color: #eeeeee;
            padding: 13px;
            page-break-inside: avoid
        }

        center {
            font-size: 10pt;
            font-style: italic;
        }

        html {
         font-family: AbhayaLibre;
         margin: 0 2em 0 2em;
         font-size:14pt;
        }

        p { text-align: justify; }

        hr {
            height: 1px;
            border-top: 3px solid black;
        }

        h1 {
            page-break-before: always;
            font-size: 18pt;
        }

        h2{
            font-size: 16pt;
        }

    </style>
```

**Comment by ashkulz** [comment]
What is the version you are using? on which platform?

**Comment by fommil** [comment]
Debian Testing, latest in repo.

**Comment by alloylab** [comment]
have you tried this on 0.12.5?

**Comment by fommil** [comment]
Nope, but I'm happy to close in any case because I'm unlikely to have the time to fix this.
