### ISSUE TITLE
Table row border invisible in zoom 100%

### ISSUE THREAD

**Issue by dinesh-kutung** [wkhtmltopdf/wkhtmltopdf#2984]
Hi, I'm trying to convert from html to pdf in this if I am having a table that contains a border to each row, but when the pdf in 100 % zoom the row line is invisible when it zoom to 150 % all the row lines are visible. I have attached the zoom 100 % and 150 % screenshot please find the attachment. Please tell me a solution for this. Thanks in advance.
![image](https://cloud.githubusercontent.com/assets/16792003/15814746/34a0185a-2be6-11e6-80b3-8244a66ae7a5.png)
![image](https://cloud.githubusercontent.com/assets/16792003/15814761/5935e96a-2be6-11e6-84e9-5012b4ab69bf.png)

**Comment by darthnorman** [comment]
There is no real solution, you would have to make the lines thicker.

**Comment by Tomsgu** [comment]
Closing as there is no real example so the issue cannot be reproduced, but it seems that there is no real solution as @darthnorman noted.
