### ISSUE TITLE
wkhtmltopdf Failed when printing non-utf-8 encoded document

### ISSUE THREAD

**Issue by pangjac** [wkhtmltopdf/wkhtmltopdf#2989]
Hi,
I am running wkhtmltopdf  from macbookair.
## The error message I got is below :

/home/ubuntu/anaconda2/lib/python2.7/site-packages/pdfkit/pdfkit.pyc in to_pdf(self, path)
    114 
    115         if 'Error' in stderr.decode('utf-8'):
--> 116             raise IOError('wkhtmltopdf reported an error:\n' + stderr.decode('utf-8'))
    117 
    118         if exit_code != 0:

IOError: wkhtmltopdf reported an error:
Loading pages (1/6)
QPainter::begin(): Returned false
Error: Unable to write to destination                              
## Exit with code 1, due to unknown error.

I checked the issues before and found one similar print error. It is solved by assuming that all linux,mac,unix encoding is 'utf-8' (While windows is not always as so) and ignore all non utf-8 encodings.

However, I still met this error when running on my macbook air. The website I used to print is "https://scholar.google.com/scholar_case?case=9617616702966850975&q=engelmayer+copyright+infringement&hl=en&oe=ASCII&as_sdt=4,33,75,82,84,89,94,95,99,105,107,119,122,138,145,147,152,157,158,162,286,287,288,289,349,350,351,352,379,380".  

I print another similar one successfully, fyi. " https://scholar.google.com/scholar_case?case=4846686068624186102&q=engelmayer+copyright+infringement&hl=en&oe=ASCII&as_sdt=4,33,75,82,84,89,94,95,99,105,107,119,122,138,145,147,152,157,158,162,286,287,288,289,349,350,351,352,379,380
"

Thanks for any clues/help!!

**Comment by alloylab** [comment]
is this still an issue on 0.12.5?
