### ISSUE TITLE
Opacity returns an error

### ISSUE THREAD

**Issue by tychovbh** [wkhtmltopdf/wkhtmltopdf#2993]
I have an image in my page with style attribute opacity. $pdf->addPage($page) is fine, but at $pdf->send('file.pdf') i get the following error (When I remove opacity it works fine):

Loading pages (1/6)
[>                                                           ] 0%
[======>                                                     ] 10%
[==========>                                                 ] 18%
[==============>                                             ] 24%
[===============>                                            ] 26%
[=================>                                          ] 29%
[==================>                                         ] 31%
[====================>                                       ] 34%
[=====================>                                      ] 36%
[======================>                                     ] 38%
[========================>                                   ] 41%
[=========================>                                  ] 43%
[===========================>                                ] 46%
[============================>                               ] 48%
[============================================================] 100%
Counting pages (2/6)  
[============================================================] Object 1 of 1
Resolving links (4/6)  
[============================================================] Object 1 of 1
Loading headers and footers (5/6)  
Printing pages (6/6)
[>                                                           ] Preparing
[============================================================] Page 1 of 1
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted

**Comment by alloylab** [comment]
is this still an issue on 0.12.5?

**Comment by cykus** [comment]
> is this still an issue on 0.12.5?

yes
