### ISSUE TITLE
Footer displayed as Page cannot be displayed

### ISSUE THREAD

**Issue by pthota** [wkhtmltopdf/wkhtmltopdf#2994]
Hi,

The pdf generated from server using wkhtmltopdf having the Footer displayed as **Page cannot be displayed**
The server is a 64-bit OS.
It has 64-bit wkhtmltopdf exe file version 0.12.2.4

Please provide me suggestions to fix this issue.

Thanks,
pthota

**Comment by alloylab** [comment]
is this still an issue on 0.12.5?
