### ISSUE TITLE
Page break of nested table

### ISSUE THREAD

**Issue by dnprock** [wkhtmltopdf/wkhtmltopdf#3002]
I have a nested table HTML and `page-break-insde: avoid;` attribute doesn't break the page correctly. Here's a public demo:

wkhtmltopdf "https://calendar-staging.smartsheetlabs.com/calendars/9c6c43e7-cfbc-4ce4-ba9d-b35835f7b299?pdf_token=ZG5Y-NC64VXQzF9Viw4UmA&starting_date=2013-09-01&view=monthly" ~/Downloads/calendar.pdf

You can view the page with this URL:

https://calendar-staging.smartsheetlabs.com/calendars/9c6c43e7-cfbc-4ce4-ba9d-b35835f7b299?pdf_token=ZG5Y-NC64VXQzF9Viw4UmA&starting_date=2013-09-01&view=monthly

The `page-break-inside` attributes are added to `tr` tags. See image.

![screen shot 2016-06-14 at 10 43 14 am](https://cloud.githubusercontent.com/assets/497205/16053264/e9c2fb44-321c-11e6-92f5-402380ab6200.png)

**Comment by dnprock** [comment]
I ended up converting my table structure into divs. Using css style copy, I can create divs that look like table. page-break-inside attribute works with printing divs. Close this issue.

**Comment by joshjacobson** [comment]
What does "using css style copy" mean?

**Comment by mainpal1** [comment]
@dnprock What does "using css style copy" mean?

**Comment by dnprock** [comment]
That means I create overlay divs that mimic the look of the table. Then I hide the table and print the divs. To make divs look exactly like table, I copy CSS styling. Some excerpt from my code below:

`
var rowDivsContent = $('<div id="print-rows-content"></div>');
$('#table').find('tr').each(function() {
  var row = $('<div class="print-row"></div>');
  var rowHeight = $(this).height();
  row.width($(this).width());
  row.height(rowHeight + 5);
  row.css("z-index", 999);
  row.css("float", 'left');

  // copy cells
  $(this).find("td").each(function() {
    var cell = $('<div class="print-cell">' + $(this).html() + '</div>');
    row.append(cell);
    var cssText = window.getComputedStyle($(this)[0]).cssText;
    cssText = cssText.replace(/-[a-z]*-text-fill-color:[^;]*;/, '');
    cell[0].style.cssText = cssText;
    cell.css('position', 'absolute');
    cell.css("z-index", 999);
    cell.css('left', $(this).offset().left - 16);
    cell.width($(this).width());
  });

  rowDivsContent.append(row);
  $(this).css("visibility", "hidden");
});
`
