### ISSUE TITLE
Installation fails on Ubuntu 15.01 because of libicu52 dependency

### ISSUE THREAD

**Issue by andreimoment** [wkhtmltopdf/wkhtmltopdf#3003]
The full message:

Dependency is not satisfiable: libicu52(>=52.1-3ubuntu0.2)

sudo apt-get install -y libicu52

 results in 

Package libicu52 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'libicu52' has no installation candidate

**Comment by ashkulz** [comment]
Please use the latest version `0.12.3` which should work across distributions.
