### ISSUE TITLE
Incorrect architecture specification in CONTROL file for i386 DEB build

### ISSUE THREAD

**Issue by Pleskan** [wkhtmltopdf/wkhtmltopdf#3004]
Hello!

You have placed wrong architecture specification for i386 Debian-based systems 
you had written  _Architecture: amd64_ in _CONTROL_ file of package in i386 Debian/Ubuntu package.

Fix them, please!
Regards!

**Comment by Tomsgu** [comment]
@Pleskan is this still an issue?

**Comment by Pleskan** [comment]
I had not made tests about it since that time, thus I don't know.
Sorry!

**Comment by Tomsgu** [comment]
Ok, please feel free to re-open this issue if you face it in a newest versions.
