### ISSUE TITLE
Image Getting Blur on Top Left Corner of Page

### ISSUE THREAD

**Issue by rohitsachaan** [wkhtmltopdf/wkhtmltopdf#3005]
The image is in main file not in header one. At the same time it looks fine on web but after converting it into PDF file it gets blurry, but why it is doing so?

I use following CSS on image:
.image-wrapper {
    padding: 0px;
    right: 0px;
    width: 40px;
    margin-left: auto;
    height: 40px;
}
.image-wrapper img {
    height: 40px;
}

The Screen Shot of Pdf:
![forum](https://cloud.githubusercontent.com/assets/14106289/16080509/d1fb87dc-3326-11e6-96a0-bce551a863be.png)

I'd like to know if this is a limitation of wkhtmltopdf and if others have came across the similar problem?

**Comment by PhilterPaper** [comment]
This is the "SONY" logo block that you're talking about? If you're displaying it at 40px x 40px, perhaps the scaling is too much? What is the original size of this image? Maybe you could try supplying a file that's already closer to 40x40, or even *at* that size, and see if it makes any difference.

**Comment by rohitsachaan** [comment]
Yes am talking about the "SONY" logo block. The original size of image is 500px x 500px. And I just tried with exact the same size of 40px x 40px, but its not working.
Could you suggest something else @PhilterPaper for this issue ?

**Comment by PhilterPaper** [comment]
Did you use a quality photo editor to shrink it down from 500x500 to 40x40? Something like The GIMP or PhotoShop? Does the resulting small image display sharply in a browser? If it does, that would indeed suggest some sort of problem with wkHTMLtoPDF. You might also try other image formats (GIF vs PNG vs JPEG). Maybe wkHTMLtoPDF has trouble rendering whatever image format you happen to be using -- and watch your color model -- RGB is universally supported, but CMYK may give problems.

**Comment by rohitsachaan** [comment]
@PhilterPaper 
Yes I used PhotoShop to create the image. The image is displaying fine in the browser as well. I tried both png and jpeg formats, but problem still persists(the svg format is working fine but I need to use some common formats). My color Model is RGB.

There might be some problem in rendering wkHTMLtoPDF.

Can anyone suggest me something on this issue?

**Comment by PhilterPaper** [comment]
Just to confirm, you scaled it *down* to 40x40 using a high-quality setting in PhotoShop, and it looks fine in a browser, but bad in PDF? It's pointless to give a 500x500 image and expect it to be automatically scaled down to 40x40 (by either WebKit or a browser) and still be just as sharp as PhotoShop's result. Browsers generally do a mediocre job of scaling images, as they have to do it on the fly at high speed, and use simple algorithms.

**Comment by rohitsachaan** [comment]
@PhilterPaper 
Yes I did scaling in Photoshop, it works fine in browser but not in PDF. 
Ant other Suggestions ?

**Comment by rohitsachaan** [comment]
Some CSS Properties related to table border in page creating issue & make that image blurry.

Thank You Everybody for Your Suggestions.
