### ISSUE TITLE
DPI Argument not reflecting in PDF

### ISSUE THREAD

**Issue by agtruworth** [wkhtmltopdf/wkhtmltopdf#3007]
When I pass DPI argument to generate PDF then PDF quality and size not reflecting. Always produce same output. I am using Window-7 32 bit system.
Below is cmd command 

c:>wkhtmltopdf --dpi 600 test.html test.pdf

**Comment by SkYneT54** [comment]
Have you solved this issue ?

**Comment by toleabivol** [comment]
Same for me (ubuntu 16.04 tested with latest 0.12.4 and 0.13.0-alpha-7b36694)

**Comment by Tomsgu** [comment]
Closing as a duplicate of #2579.
