### ISSUE TITLE
Element automatically goes down 

### ISSUE THREAD

**Issue by nicubarbaros** [wkhtmltopdf/wkhtmltopdf#3010]
Please access this link. 
[http://stackoverflow.com/questions/37877760/element-automatically-goes-down-wicked-pdf-rails-html-to-pdf](url)

Copy and paste into a new tab.
Thank you.

**Comment by darthnorman** [comment]
Probably because the element floats: http://stackoverflow.com/a/3886376

**Comment by Tomsgu** [comment]
Closing as the link doesn't work and there is poor information given.
