### ISSUE TITLE
How to solve repeating thead tfoot repeating overlapped with contents

### ISSUE THREAD

**Issue by viswa18** [wkhtmltopdf/wkhtmltopdf#3013]
I have convert a html that contains table. I need thead and tfoot on every page. But it repeats but it overlapped with other table rows. How to solve this issue. Let me know your concern on this.
Thanks.

**Comment by viswa18** [comment]
[test.zip](https://github.com/wkhtmltopdf/wkhtmltopdf/files/324776/test.zip)

**Comment by rohitsachaan** [comment]
@viswa18 
Here you go...

[Repeating Header.zip](https://github.com/wkhtmltopdf/wkhtmltopdf/files/325489/Repeating.Header.zip)

**Comment by viswa18** [comment]
@rohitsachaan  Thanks for your reply. It does not work for me. I have used wkhtmltopdf 0.12.2.4 (with patched qt). Which version u have used?
Thanks

**Comment by viswa18** [comment]
@rohitsachaan Can you please convert the attached files and send the results?
[THEAD-TFOOT.zip](https://github.com/wkhtmltopdf/wkhtmltopdf/files/327426/THEAD-TFOOT.zip)

**Comment by Suiname** [comment]
Is there a way to completely disable the table headers?  I'd rather they just don't display.

**Comment by viswa18** [comment]
Yes. But cannot disable with wkhtmltopdf 0.12.2.4 (with patched qt). If u dont need this u can use without patched versions.

**Comment by rohitsachaan** [comment]
@viswa18 
I used wkhtmltox-0.12.3.2.

& here you go, the files you want to be converted in the same manner.

[THEAD-TFOOT.zip](https://github.com/wkhtmltopdf/wkhtmltopdf/files/329574/THEAD-TFOOT.zip)

**Comment by viswa18** [comment]
@rohitsachaan  Thanks for your reply. I ll check with my end and update here.

**Comment by viswa18** [comment]
I also installed wkhtmltox-0.12.3.2 and convert those htmls to pdf but it does not work for me
[testwithborder.pdf](https://github.com/wkhtmltopdf/wkhtmltopdf/files/329669/testwithborder.pdf)

**Comment by rohitsachaan** [comment]
@viswa18 
Can you share the markup here you are using.?

**Comment by viswa18** [comment]
@rohitsachaan 
[tablewithborder.zip](https://github.com/wkhtmltopdf/wkhtmltopdf/files/329701/tablewithborder.zip)

**Comment by viswa18** [comment]
@rohitsachaan After apply the given styles in my markup that is working fine.Thank you man. You saved my day.... :-)

**Comment by viswa18** [comment]
@rohitsachaan If that html has only thead it does not work. Can you please check that in your end and let me know the result. Attachment has html that contains only thead for a table.
[TheadOnly.zip](https://github.com/wkhtmltopdf/wkhtmltopdf/files/338712/TheadOnly.zip)

**Comment by rohitsachaan** [comment]
@viswa18  It works at my end. I think you forget to put the style in your head section.

table{word-break: break-word;}
tr{page-break-inside: avoid !important;}

Or you can look into the code of html page.

[Only-Thead.zip](https://github.com/wkhtmltopdf/wkhtmltopdf/files/341347/Only-Thead.zip)

Hoping that it will help you.

**Comment by viswa18** [comment]
@rohitsachaan  Now I have used this in my markup. But still not working.

table{word-break: break-word; }
tr{page-break-inside: avoid !important;}

I dont want to change font and its size. 
Please try without that and let me know the results.

Thanks in advance.

**Comment by rohitsachaan** [comment]
@viswa18 Well its working fine at my end. Are you sure that there is no contradiction in css.

You can have look I did it in same manner.

[TheadOnly.zip](https://github.com/wkhtmltopdf/wkhtmltopdf/files/345912/TheadOnly.zip)

**Comment by viswa18** [comment]
@rohitsachaan Thanks for your update it is working for me. But it I remove the border It overlaps with other row. Please check this case. Please find the html files not working for me. 
[TestHTMLs.zip](https://github.com/wkhtmltopdf/wkhtmltopdf/files/347321/TestHTMLs.zip)

**Comment by rohitsachaan** [comment]
@viswa18 its working fine at my end I think while you are applying in your real project some properties of CSS are contradict with these properties please check it once.

PDF files : [TestHTMLs.zip](https://github.com/wkhtmltopdf/wkhtmltopdf/files/349751/TestHTMLs.zip)

**Comment by viswa18** [comment]
@rohitsachaan please try with some other viewport size. Example 1024X0

**Comment by viswa18** [comment]
@rohitsachaan Let me know your view port sizes. If I have changed my view port sizes. No changes in output. Please try in some other view port sizes and share the results.

**Comment by rohitsachaan** [comment]
@viswa18 I tried in different view-port sizes but it is working fine at my end.

Are you able to send me any sample markup with different view-port sizes in which you want results.?

**Comment by viswa18** [comment]
@rohitsachaan view-port sizes was not working in my end. All view-port produces same result. Let me know your concern.

**Comment by rohitsachaan** [comment]
@viswa18 you can have look on the following issue they might help you with view-port:

#34, #43 & #1502

**Comment by rohitsachaan** [comment]
@viswa18 is your issue "repeating thead tfoot repeating overlapped with contents" resolved..?
If yes then please close this issue.

Thank You.!

**Comment by viswa18** [comment]
@rohitsachaan Thank you so much..

**Comment by vdelrio** [comment]
Hi @rohitsachaan I'm having some troubles to make this work with a single large cell. I'm attaching the sample html and generated pdf.

[test.zip](https://github.com/wkhtmltopdf/wkhtmltopdf/files/3428392/test.zip)

I'm generating the pdf file as:
```
wkhtmltopdf --header-spacing 2 --footer-spacing 2 test.html test.pdf
```
Thanks in advance!

**Comment by DaniyalAkbar** [comment]
I was using Bootstrap classes in my HTML. So I had a div with the class='card'. I removed this class and it worked for me.
