### ISSUE TITLE
CSS background issue

### ISSUE THREAD

**Issue by jplevene** [wkhtmltopdf/wkhtmltopdf#3015]
Applied to a table cell, the following CSS didn't work:

```
.td .manual {
    background: repeating-linear-gradient(
        45deg,
        #ddd,
        #ddd 5px,
        #999 5px,
        #999 10px
    );

```

I even **!important** it which made no difference.

**Comment by darthnorman** [comment]
try it again, this time with the -webkit- prefix

**Comment by PhilterPaper** [comment]
Is your CSS selector correct? What is the HTML to which this is applied? Do you have separate "td" and "manual" classes at different levels, or is "td" supposed to be the td _tag_? Is this `<td class="manual">`? If so, the selector should be `td.manual`.

**Comment by jplevene** [comment]
The CSS and selector is ok as it works fine on all browsers.
"`.td .manual`" is a typo for this report only. This wasn't the selector I used, I actually used a cell with a class.  I should have just written `td.manual` as the selector for this example.

**Comment by jplevene** [comment]
using -webkit helped, however alignment was all over the place.  My selector is (selectors worded better):
```
.row_class .specific_td_class {
	background: repeating-linear-gradient(
		45deg,
		#ddd,
		#ddd 5px,
		#999 5px,
		#999 10px
	);
	background: -webkit-repeating-linear-gradient(
		45deg,
		#ddd,
		#ddd 5px,
		#999 5px,
		#999 10px
	);
}
```
As I said, adding -webkit- fixed the bug, but the new bug is that it hasn't drawn correctly.

**Comment by Tomsgu** [comment]
Closing as the initial issue was resolved. Please open a new issue with a complete details how to reproduce the bug and what is the expected output.
