### ISSUE TITLE
Issue in rendering the header/footer in ubuntu 14.04

### ISSUE THREAD

**Issue by karthikror** [wkhtmltopdf/wkhtmltopdf#3020]
Hi,
I am using the below version gems to render my PDF
wicked_pdf - 0.11.0
wkhtmltopdf - 0.1.2
wkhtmltopdf-binary - 0.9.9.3.
 working platform - RoR

Below is my controller cod

```
render :pdf => "#{@route.route_name} report", 
:template => 'reports/index.pdf.erb',
page_size: "A4",
:header => {:html => { :template=> 'reports/footer.html.erb'}
}
```

I am trying to render the header in the PDF pages. It works absolutely fine in Ubuntu 12.04, but not in 14.04.

Please help me out in this.

**Comment by alloylab** [comment]
is this still an issue on 0.12.5?
