### ISSUE TITLE
td appear in thead on page break

### ISSUE THREAD

**Issue by trifail** [wkhtmltopdf/wkhtmltopdf#3024]
Hi !

I'm using windows 10 (64 bits) with wkhtml 0.12.3.2 (with patched qt) with node.js 4.4.1

I have a td cell that overlap with the thead on the second page. The problem is caused when the td has a "colspan" attribute. The first <tr> that contains this td and the second are correctly showed. But the content of the <td> is not showed. It appears on the thead : 

![bug-display](https://cloud.githubusercontent.com/assets/11834051/16488102/1909dce2-3ecf-11e6-84b1-5c93eb74c898.PNG)

As you can see, the td is duplicated and appears on the thead. td content should appear at least on one of the td with the red line.

Here is the html code that I used (without the css) : 

[content.zip](https://github.com/wkhtmltopdf/wkhtmltopdf/files/341357/content.zip)

Is there a solution ?

Thank you

**Comment by rohitsachaan** [comment]
@trifail You can put this style in your head section:

table{word-break: break-word;}
tr{page-break-inside: avoid;}

[content.zip](https://github.com/wkhtmltopdf/wkhtmltopdf/files/341445/content.zip)

Hope this will help you.

**Comment by trifail** [comment]
@rohitsachaan Thank you for your answer !
It seems to work in this case, unfortunately it depends onthe number of lines of the table ! For example, if I remove a line, the overlap reappears !

So, I think the "rowspan" is the problem, the only way would be to encompass the two or three or x <tr>s that are concerned by a <td rowspan"2/3/x"> and force webkit not to cut those <tr>.
I tried to encompass the <tr>s with <tbody> and apply some workaround I find on issues : 
 
```
<style>
    table,
    tbody {
        word-break: break-word;
    }
    thead {

        display: table-header-group
    }
    tfoot {
        display: table-row-group
    }
    thead:before,
    thead:after {
        display: none;
    }
    tbody,
    tr {
        page-break-inside: avoid !important;
        break-inside: avoid;
        -webkit-column-break-inside: avoid;
    }

</style>
```

If we find how to force the "tbody" to not be cut, I think it will resolve the problem...

This style is directly in the html file "content"

[content.zip](https://github.com/wkhtmltopdf/wkhtmltopdf/files/343086/content.zip)


The content_bug.html file has one <tr> in less. 
I have added the css files to ensure we have the same view.

Thank you for your help !

**Comment by rohitsachaan** [comment]
@trifail I looked into your markup you want to treat two rows as one row. Am wondering is there any tag available to group table rows. One way I can suggest that you can put a table under row when you want two consecutive rows not to break.
