### ISSUE TITLE
build static library in windows

### ISSUE THREAD

**Issue by naderi4** [wkhtmltopdf/wkhtmltopdf#3035]
how to build wkhtmltopdf as static library (.lib only without dll)
for visual studio

**Comment by MacGritsch** [comment]
Is there no info here?
I have found same questions in other forums and the suggest to check the following link but it is dead (moved from goggle to github): http://code.google.com/p/wkhtmltopdf/wiki/compilation

**Comment by ashkulz** [comment]
That's not really a supported scenario -- you can try to hack the build system if you want to achieve that.
