### ISSUE TITLE
Building from source in CentOS 7

### ISSUE THREAD

**Issue by hcngac** [wkhtmltopdf/wkhtmltopdf#3038]
Hi,
I have issues with building from source with CentOS 7

```
sudo scripts/build.py setup-schroot-centos7
This can only be run on a 64-bit Debian/Ubuntu distribution, aborting.
```

Can you help me in resolving this error? Thank You!

**Comment by joelbarnard** [comment]
Hello, 

I just wanted to build it on the local system that I was running it on.
I tried using 'posix-local' to build it, and it appears to be working.

I believe the schroot stuff is if you want to target a different system type than you are currently on.

**Comment by hcngac** [comment]
It seems I'm drunk and didn't saw that it was for targeting CentOS but not building on CentOS.
Thank you for your quick answer!
