### ISSUE TITLE
set a javascript variable that can be accessed in the footer

### ISSUE THREAD

**Issue by mewalig** [wkhtmltopdf/wkhtmltopdf#3048]
is there any way to make the below work?

file.html:

```
 <html>
 <body>
 <script> var sometext="hi" </script>
```

footer.html:

```
 <html>
 <body>
 <script> document.write(sometext); // this does not work because var sometext is not found
 </script>
```

---

For example:

file.html:

```
 <html>
 <body>
 <script> wkhtmltopdf_vars['sometext'] ="hi" </script> // set a value that will be pre-seeded into the JS engine when the footer is rendered
```

footer.html:

```
 <html>
 <body>
 <script> document.write(wkhtmltopdf_vars['sometext']); // this would be cool
 </script>
```

**Comment by anowell** [comment]
Not sure, but does it work if you attach the var to the `window` instead? `window.sometext="hi"`

**Comment by mewalig** [comment]
unfortunately that doesn't work either

**Comment by chris-scheurle** [comment]
`input.html:`
```html
<html>
	<head><title>File</title></head>
	<body>
		<pre>Some content</pre>
	</body>
	<script>
		var vars = {};
		vars.sometext = "Hi!"
		document.cookie = 'vars=' + encodeURIComponent(JSON.stringify(vars));
		window.status = 'FOOBAR';
	</script>
</html>
```
`footer.html`
```html
<html>
	<head><title>Footer</title></head>
	<body>
		<pre>Footer: <script>
			try{
				var vars = JSON.parse(decodeURIComponent(document.cookie.replace(/(?:(?:^|.*;\s*)vars\s*\=\s*([^;]*).*$)|^.*$/, "$1")));
			}
			catch(e){
				var vars = {};
			}
			document.write(vars.sometext);
		</script></pre>
	</body>
</html>
```

`html2pdf.sh`
```bash
#!/bin/bash

# run: . html2pdf.sh input.html output.pdf

if [[ "$#" > 1 ]]; then
	cookieJar="${TMPDIR}pdf-cookies$(date +%s)${RANDOM}.txt"
	wkhtmltopdf --cookie-jar "${cookieJar}" --debug-javascript --no-stop-slow-scripts --window-status 'FOOBAR' "$1" "$2"
	wkhtmltopdf -B 20mm --cookie-jar "${cookieJar}" --debug-javascript --no-stop-slow-scripts --footer-html 'footer.html' --window-status 'FOOBAR' "$1" "$2"
	if [[ -f "${cookieJar}" ]]; then
		rm -f "${cookieJar}"
	fi
else
	echo "2 parameters expected, only got $#" 1>&2
fi
```

`output.pdf`
![screenshot](https://cloud.githubusercontent.com/assets/6209236/17782041/17c7050c-6572-11e6-8817-9075cde484cd.png)

This works on Mac OS X 10.11.6. `wkhtmltopdf`has to be called twice because `footer.html` seems to run *before* the code in `input.html` gets executed.

**Comment by anowell** [comment]
clever use of cookies. I presume the order issue means that if you can get away with doing your shared variable initialization in the footer, then you could still just run `wkhtmktopdf` once...

**Comment by Tomsgu** [comment]
Closing as answers were provided.

**Comment by mewalig** [comment]
Why was this closed? Answers were provided, but none of them solved the problem.

**Comment by Tomsgu** [comment]
Hi @mewalig,
it was closed, because usually when somebody trying to help, it is a good to also answer that this doesn't work for me. I haven't seen that answer so I thought it was resolved.

What is wrong with @chris-scheurle answer? What does not work for you?
