### ISSUE TITLE
outlineDepth is documented, but not settable in C-bindings

### ISSUE THREAD

**Issue by anowell** [wkhtmltopdf/wkhtmltopdf#3055]
While the value is initialized in `PdfGlobal` to 4, attemptiont to set `outlineDepth` via `wkhtmltopdf_set_global_setting` segfaults.

I presume it's just missing the `WKHTMLTOPDF_REFLECT(outlineDepth)` in [`pdfsettings.cc`](https://github.com/wkhtmltopdf/wkhtmltopdf/blob/0.12.3.x/src/lib/pdfsettings.cc#L120) to pair with the `outline` setting.

**Comment by ashkulz** [comment]
Fixed via #3291
