### ISSUE TITLE
ugly font rendering in wkhtmltopdf

### ISSUE THREAD

**Issue by graingert** [wkhtmltopdf/wkhtmltopdf#3062]
See this file: https://github.com/graingert/bad-fonts-wkhtmltopdf/blob/master/wkhtmltopdf.pdf

Preview ![pdf-render](https://cloud.githubusercontent.com/assets/413772/17405835/ff3be53a-5a58-11e6-84e0-012917333745.png)

You can see the O's and D's are missing some points.

also look at the reference render from google chrome:
![reference render from google chrome](https://raw.githubusercontent.com/graingert/bad-fonts-wkhtmltopdf/master/google-chrome.png)

Interestingly wkhtmltoimage works correctly:

![wkhtmltoimage](https://raw.githubusercontent.com/graingert/bad-fonts-wkhtmltopdf/master/wkhtmltoimage.png)

**Comment by graingert** [comment]
You can generate the HTML used to create these here: https://github.com/graingert/bad-fonts-wkhtmltopdf/blob/master/index.js

**Comment by PhilterPaper** [comment]
There have been many complaints about rendering of characters where curves get straight segments. If you haven't done so already, you may want to search for those reports and see if there were any fixes in them.

**Comment by graingert** [comment]
duplicate of https://github.com/wkhtmltopdf/wkhtmltopdf/issues/2999
