### ISSUE TITLE
toc argument doesn't work with any other arguments present

### ISSUE THREAD

**Issue by UmbrellaProject** [wkhtmltopdf/wkhtmltopdf#3066]
wkhtmltopdf 0.12.3 (with patched qt) / CentOS 6.6, 64bit

when using "./wkhtmltopd toc test.html test.pdf" pdf is generated with toc
but when using "./wkhtmltopd toc --page-size Letter --margin-bottom 0in test.html test.pdf"
nothing happens (shows the help screen)

does anyone have the same issue? am I doing something wrong ?

**Comment by pfcloutier** [comment]
I think the order of the parameter matter. If you put the 'toc' at the end it works.

**Comment by alloylab** [comment]
is this still an issue on 0.12.5?

**Comment by Tomsgu** [comment]
Closing as there is no response since July.
