### ISSUE TITLE
Allow space in filename and PATH

### ISSUE THREAD

**Issue by MiniEggs512** [wkhtmltopdf/wkhtmltopdf#3070]
Windows

How does one write to a PDF file (or read html file) in a folder that has spaces in it's name ?

I have tried the standard command prompt style

wkhtmltopdf "c:\Some Folder\my.html" "c:\Some Other Folder\my.pdf"

Thanks

**Comment by rage299** [comment]
Have the same problem. Do you have already a solution?

**Comment by MiniEggs512** [comment]
In the end I just renamed it in my code to replace spaces with ^ and then reamed it back afterward

**Comment by PhilterPaper** [comment]
Note that on the Windows _command line_ a single backslash \ _should_ be OK (as a directory separator), with or without ". Just be careful if you're defining _strings_ with " (within a language), as a \ is usually treated as an **escape** and may 1) not be recognized as a directory separator, 2) may eat the following character if the escape code means something.

I assume that this is in Windows, and the original command was on the DOS/Windows command line. In that case, it ought to have worked.
