### ISSUE TITLE
[Question] Need help with some queries

### ISSUE THREAD

**Issue by ahmadhasankhan** [wkhtmltopdf/wkhtmltopdf#3071]
Hi,

I was just playing around `wkhtmltopdf` and it is really good but couple of things I am not able to figure-out whether we can do it in wkhtmltopdf or not, I would really appreciate if someone can help me with this .
1. Lets say, I have 10 pages of HTML and headers & footers are not there on HTML pages, but I want to add header and footer on every page while generating PDF, is there any way around ?  
2. Is there any way to add page number & page count on every page ?

Thanks
Ahmad

**Comment by HugCoder** [comment]
Try adding custom switches to wkhtmltopdf. Something like this:
`"--print-media-type --footer-center \"This is the footer!\" --footer-right \"Page: [page] of [toPage]\" --footer-line --footer-font-size 7"`
There are plenty more switches, which are documented in various places, that can be used.

**Comment by chris-scheurle** [comment]
If you want to to do a little more styling or customization on your own (taken from [the official wkhtmltopdf documentation page](http://wkhtmltopdf.org/usage/wkhtmltopdf.txt)):
> Headers and footers can also be supplied with HTML documents. As an example one could specify `--header-html header.html`, and use the following content in `header.html`:
> 
> ```html
> <html><head><script>
> function subst() {
> var vars={};
> var x=window.location.search.substring(1).split('&');
> for (var i in x) {var z=x[i].split('=',2);vars[z[0]] = unescape(z[1]);}
>     var x=['frompage','topage','page','webpage','section','subsection','subsubsection'];
>     for (var i in x) {
>         var y = document.getElementsByClassName(x[i]);
>         for (var j=0; j<y.length; ++j) y[j].textContent = vars[x[i]];
>     }
> }
> </script></head><body style="border:0; margin: 0;" onload="subst()">
> <table style="border-bottom: 1px solid black; width: 100%">
> <tr>
>     <td class="section"></td>
>     <td style="text-align:right">
>         Page <span class="page"></span> of <span class="topage"></span>
>     </td>
> </tr>
> </table>
> </body></html>
> ```
> As can be seen from the example, the arguments are sent to the header/footer html documents in get fashion.

and:

> In header and footer text string supplied to e.g. `--header-left`, the following variables will be substituted.
> * `[page]`       Replaced by the number of the pages currently being printed
> * `[frompage]`   Replaced by the number of the first page to be printed
> * `[topage]`     Replaced by the number of the last page to be printed
> * `[webpage]`    Replaced by the URL of the page being printed
> * `[section]`    Replaced by the name of the current section
> * `[subsection]` Replaced by the name of the current subsection
> * `[date]`       Replaced by the current date in system local format
> * `[isodate]`    Replaced by the current date in ISO 8601 extended format
> * `[time]`       Replaced by the current time in system local format
> * `[title]`      Replaced by the title of the of the current page object
> * `[doctitle]`   Replaced by the title of the output document
> * `[sitepage]`   Replaced by the number of the page in the current site being converted
> * `[sitepages]`  Replaced by the number of pages in the current site being converted

I hope that helps. :smile:
