### ISSUE TITLE
Request: URL title as filename for PDF

### ISSUE THREAD

**Issue by mrdc** [wkhtmltopdf/wkhtmltopdf#3074]
Hi,

Would be nice to have an option to save an url with it's title as filename for PDF.

**Comment by SDP190** [comment]
I will also ask for the same thing!!! it is very important, in particular for batch operations!!!

See this post [](url), and what i commented there.

**Comment by Tomsgu** [comment]
Closing as @ashkulz already refused the idea [here](https://github.com/wkhtmltopdf/wkhtmltopdf/issues/3268#issuecomment-270284511).
