### ISSUE TITLE
wkhtmltopdf does not work in windows 2003 server standard edition R2 (32 bit)

### ISSUE THREAD

**Issue by sheringeorge7** [wkhtmltopdf/wkhtmltopdf#3080]
Dear All,
The wkhtmltopdf gives the following error when tried run on Windows 2003 server (standard edition R2 (32 bit)). I tried deploying the latest version (v 0.12.3.2 - 32 bit)  but some reasons it does not work as expected. 

The specified executable is not a valid application for this OS platform

Just wondering any workaround or resolution for this one? Any help is greatly appreciated

Sherin

**Comment by poizan42** [comment]
Windows Server 2003 R2 was EOL'ed 14-07-2015 so you shouldn't be using it anymore.

**Comment by rsteinwand** [comment]
You installed the wrong version. Check the downloads folder again for Windows (MinGW-w64).

Agreed. No way you should be running this for anything other than testing.

**Comment by sheringeorge7** [comment]
Dear All,
Thank you very much for your responses.
This server is owned by one of our client who is not ready to upgrade due
to some reasons.
Yes, I saw the MinGW-w64 version but being alpha release I was  bit
hesitant to install it.

​

**Comment by rsteinwand** [comment]
Below it are older versions that are not alpha.

**Comment by ashkulz** [comment]
Use the `0.12.4` MinGW binaries, which should work on Windows 2003.
