### ISSUE TITLE
Empty pdf when saving a website to pdf

### ISSUE THREAD

**Issue by omrivm** [wkhtmltopdf/wkhtmltopdf#3086]
Hi,
When i use wkhtmltopdf 0.12.3.2 (with patched qt) on windows 7 64bit to save the following website to pdf i get an empty pdf file: https://www.clearmash.com/skn/c6/Site

I'm not sure why... https? absolute positions? javascript? dynamic dom building?

This is my command line:
"C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe" https://www.clearmash.com/skn/c6/Site --enable-javascript --javascript-delay 5000 --no-stop-slow-scripts --viewport-size 1280x1024 e:\PDFTest\test.pdf

Any help will be appreciated! :)

**Comment by alloylab** [comment]
is this still an issue on 0.12.5?
