### ISSUE TITLE
SSL Control - Specify Client Certificate

### ISSUE THREAD

**Issue by jasonparallel** [wkhtmltopdf/wkhtmltopdf#3090]
Is there anyway to specify a client pki cert? An equivalent to wget's ‘--certificate=file’.

**Comment by gxof** [comment]
Hi,

How did you solve that? Did you find out a workaround?

Thanks

Gerald

**Comment by ashkulz** [comment]
A release candidate [is available](https://wkhtmltopdf.org/downloads.html#release-candidate) which includes the fixes made in your PR #3206 -- please test and report your findings before the final release.
