### ISSUE TITLE
wkhtmltopdf anchor text having HTML. issue

### ISSUE THREAD

**Issue by mohsinjaved** [wkhtmltopdf/wkhtmltopdf#3092]
wkhtmltopdf 0.12.3.2 (with patched qt) -- Windows 8

If I include some html inside anchor tag then the generated pdf doesn't make it clickable.

**e.g** `<a href="#BarChart"><div><span>TreeMap!</span></div></a>`

**Command :** wkhtmltopdf.exe --enable-internal-links D:\A.html D:\test.pdf

Can anyone help me in this regard ?

----------------------- HTML -----------------------

```
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<style type="text/css" media="screen,print">
  .break{
    display: block;
    clear: both;
    page-break-after: always;
}
</style>
</head>
<body>
<a href="#BarChart"><div><span>TreeMap!</span></div></a>
<div class="break"></div>
<a name="BarChart">nbsp</a>
<a href="#TextChart">Bar Chart!</a>
<div class="break"></div>
<a name="TextChart">nbsp</a>
<a href="#PieChart">Text Chart !</a>
<div class="break"></div>
<a name="PieChart">PieChart</a>
</body>
</html>

```
---------------------------------END--------------------------

Resultant Pdf is attached herewith.

[test.pdf](https://github.com/wkhtmltopdf/wkhtmltopdf/files/440802/test.pdf)

**Comment by myleslee** [comment]
Making the content inside that <a> tag display as *inline* should resolve the issue:  
~~~
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<style type="text/css" media="screen,print">
  .break{
    display: block;
    clear: both;
    page-break-after: always;
}
.inline {
  display: inline;
}
</style>
</head>
<body>
<a href="#BarChart"><div class="inline"><span>TreeMap!</span></div></a>
<div class="break"></div>
<a name="BarChart">nbsp</a>
<a href="#TextChart">Bar Chart!</a>
<div class="break"></div>
<a name="TextChart">nbsp</a>
<a href="#PieChart">Text Chart !</a>
<div class="break"></div>
<a name="PieChart">PieChart</a>
</body>
</html>
~~~
see proof here:
[link.pdf](https://github.com/wkhtmltopdf/wkhtmltopdf/files/441072/link.pdf)

**Comment by mohsinjaved** [comment]
It worked !!! 
Thanks
