### ISSUE TITLE
Html rendering issues

### ISSUE THREAD

**Issue by viswa18** [wkhtmltopdf/wkhtmltopdf#3098]
Hi,

I have some rendering issues in HTML to PDF. Please let me know your concern on this. see the buttons in PDF document. I have attached input and output document for reference.
In browser it looks fine.
[test.zip](https://github.com/wkhtmltopdf/wkhtmltopdf/files/449163/test.zip)

Thanks in advance.

**Comment by PhilterPaper** [comment]
That's not much information to go on. wkHTMLtoPDF version, operating system, command line used, etc.? What exactly is the problem -- I see the browser and PDF produce somewhat different results, neither of them good. Is the browser version exactly what you want? If nothing else, you should set a nice color for the link text, and turn off the underline (`text-decoration: none`). Then there's the matter of the cell borders or padding causing gaps.

What are you trying to accomplish here by going through such contortions to create a push button? Are you trying to get an arbitrary text label on a button with some graphical background? I would think that there are easier ways of doing this. Perhaps a `<button>` element with a background image? You might experiment with that. Do some research on creating form buttons before inventing such a complex way of doing it.
