### ISSUE TITLE
table border stretched to fill the page

### ISSUE THREAD

**Issue by seth9009** [wkhtmltopdf/wkhtmltopdf#3099]
I have an odd problem (i think) basically i have a table that will stretch across 2 pages, all works fine but on the first page under the last TD/TR the border color (i know it's the border color because i've changed it to red on one of my tests) will stretch to fill the gap all the way to the page end please see the attached image

![printpage](https://cloud.githubusercontent.com/assets/1761153/18161178/88f64900-7039-11e6-9570-0ab82026f472.jpg)

P.S. the gray horizontal line is actually the page divider when i view the PDF in chrome so u can see in my screen shot the end of first page and the start of the second page

does anyone seen this before ? any idea how to fix it ?

Thanks a lot!

**Comment by qrlodhi** [comment]
Maybe share some test data to reproduce it if you can...?

**Comment by seth9009** [comment]
Thank you for your reply, can u be more specific about the test data ? all i have is just a simple html page that i want to print, nothing fancy just html.

After some more testing the black box is given by table BG color (black) i've removed that but i still have left / right borders it seems that the table is stretched to fill the page

P.S. i have no JS code to do that .. is just plain html, i would be happy to share some code just let me know what exactly

**Comment by qrlodhi** [comment]
Sorry, by test data I meant the HTML file and wkhtmltopdf command that can reproduce this issue.

**Comment by PhilterPaper** [comment]
I saw that problem in 0.12.2.4 (Windows, with patched QT), where the next row is moved to the next page, but left and right borders were still drawn (on an empty space) to the bottom of the page. Supposedly this was fixed in a later release (0.13... still alpha?).

**Comment by Tomsgu** [comment]
Closing as there is no feedback from the author. Without minimal html example is hard to reproduce the issue. Please feel free to re-open it if you can provide more information.
