### ISSUE TITLE
Text shadow on rotated text

### ISSUE THREAD

**Issue by ridller** [wkhtmltopdf/wkhtmltopdf#3100]
Hi,

I'm having an issue while generating some pdf's when it comes to rotated text with a shadow, the shadow is being cut, althou it's showing correctly in the html.

HTML
![image](https://cloud.githubusercontent.com/assets/5556509/18173066/18b90836-7060-11e6-875f-dacceeac9709.png)

PDF
![image](https://cloud.githubusercontent.com/assets/5556509/18173025/e077ac48-705f-11e6-8fa1-b46f5855d97d.png)

Is there a fix/workaround for this?

**Comment by alloylab** [comment]
is this still an issue on 0.12.5?
