### ISSUE TITLE
message "Error: unable to write to destination"

### ISSUE THREAD

**Issue by klauspetzel** [wkhtmltopdf/wkhtmltopdf#3101]
Using the correct command line I'm getting this error message. The program installed itself in C:/program files/wkhtmltopdf/ and I am using Windows 7. Where am I going wrong?

**Comment by PhilterPaper** [comment]
More information needed: wkHTMLtoPDF version, actual command line used, a small sample that shows the problem, etc. 

The error message suggests that the program can't **open** the output file, or if it can, it can't **write** to that file. Double check _where_ it's trying to write to (valid path and file name -- do you have unquoted spaces or invalid characters within the path or file?). Does that file already exist, perhaps with Read-Only permissions? Are you doing something other than writing to a local file?

**Comment by nineoclick** [comment]
Normally, command line output cannot write on "c:\Program Files\foo\bar\" without required permissions. So I do not think it is a problem with wkhtmltopdf.

**Comment by Tomsgu** [comment]
Closing as there is no additional information and no feedback.
