### ISSUE TITLE
Header is not rendering

### ISSUE THREAD

**Issue by tiborsaas** [wkhtmltopdf/wkhtmltopdf#3102]
Hello,

Goal: I'd like to have a CV printed, where on the front page I want zero height header or disabled. On the second page I want to have spacing on the top. 

I've seen other tickets, but I can't even load content to my header. This is my `header.html`

```html
<!DOCTYPE html>
<html>
<head>
    <style>
        body {
            background: tomato;
            color: #fff;
            padding: 2rem;
        }
    </style>
<body>
    <p>Header.This should be shown in every page</p>
    <p class="header-element">HEADER 2 This should not be show on last page</p>
</body>
</html>
````

What's sure is that the HTML got read, because the background has the tomato color:

![image](https://cloud.githubusercontent.com/assets/342688/18210915/270b4850-713b-11e6-9459-30631ba204a9.png)

I'm loading it like this:

![image](https://cloud.githubusercontent.com/assets/342688/18210923/3d2de46c-713b-11e6-8b39-cfccf8e8af4d.png)

    c:\dev\github\node-cv>wkhtmltopdf --version
    wkhtmltopdf 0.12.3.2 (with patched qt)

Thanks

**Comment by samcorcos** [comment]
It looks like you're missing the closing `</head>` tag

**Comment by tiborsaas** [comment]
Thanks, that might be it, but the solution turned out to be to abandon all hope and go with a white background :)
