### ISSUE TITLE
Concurrency issues generating pdf.

### ISSUE THREAD

**Issue by night91** [wkhtmltopdf/wkhtmltopdf#3103]
Sometimes when I am generating pdf with wkhtmltopdf with several threads. I get as result in some threads the result from others threads. It means the supposed .pdf rendered in some thread, had the information from other .pdf rendered with other thread.

**Comment by weebl2000** [comment]
Also experiencing this problem, anyone know if there is a way to work around this?

**Comment by alloylab** [comment]
@weebl2000 ok thanks for letting me know... I am going to close this issue out then. If you have any other issues please let us know
