### ISSUE TITLE
Sessions working strangely

### ISSUE THREAD

**Issue by Harsh-Gupta** [wkhtmltopdf/wkhtmltopdf#3105]
Suppose i create a session -> session_1 in browser_1 window(on my pc) and 
second session -> session_2 in ,other, browser_2 window(on my pc) .

so when i try to execute

> > exec(" Path_to_wkhtmltoimage --cookie PHPSESSID session_1 My_url Save_to_path ");

in my file.php file, present on my server, on browser_1 . It doesn't execute (instead goes into an infinte loop, i guess, returning to some error 503 after some time around 5-10 mins) .
However it works fine if i run the same command in cmd on server.
And also it works fine if i run file.php, with same command as above, on browser_2 window ,that saves the screenshot image .

similarly, if i run

> > exec(" Path_to_wkhtmltoimage --cookie PHPSESSID session_2 My_url Save_to_path ");

in my file.php file on my server on browser_2 . it doesn't execute. But executes correctly in browser_1.

"file.php" is attached .
[file.txt](https://github.com/wkhtmltopdf/wkhtmltopdf/files/453504/file.txt)

please tell me , where am i doing wrong !!

sorry for confusion , if any.
Thanks in advance.

**Comment by Tomsgu** [comment]
Please ask for example in stackoverflow. This is a question about PHP more than wkhtmltopdf.
