### ISSUE TITLE
0.12.3 not working when --proxy is last argument

### ISSUE THREAD

**Issue by WiktorKlosowski** [wkhtmltopdf/wkhtmltopdf#3106]
Using wkhtmltopdf (linux 0.12.3). When proxy is last parameter new version is not working.

./wkhtmltopdf --proxy http://user:password@proxy:80 --print-media-type - - < a.html > a.pdf
working ok

./wkhtmltopdf --print-media-type - - --proxy http://user:password@proxy:80 < a.html > a.pdf
Loading pages (1/6)
QPainter::begin(): Returned false============================] 100%
Error: Unable to write to destination
Exit with code 1, due to unknown error.

When using old version (linux  0.9.6) everything is working fine
./wkhtmltopdf --proxy http://user:password@proxy:80 --print-media-type - - < a.html > a.pdf
working ok
./wkhtmltopdf --print-media-type - - --proxy http://user:password@proxy:80 < a.html > a.pdf
working ok

**Comment by alloylab** [comment]
is this still an issue on 0.12.5?
