### ISSUE TITLE
Amharic text

### ISSUE THREAD

**Issue by Alantoo** [wkhtmltopdf/wkhtmltopdf#3107]
Hello!
When I converted HTML page with Amharic text the text in created PDFs have wrong font.
I checked all versions of wkhtmltopdf and the same result.
Result PDF and source HTML page are attached.
[test.zip](https://github.com/wkhtmltopdf/wkhtmltopdf/files/454970/test.zip)
[result.pdf](https://github.com/wkhtmltopdf/wkhtmltopdf/files/454960/result.pdf)
Thank you in advance.

**Comment by PhilterPaper** [comment]
It doesn't appear to me to be the wrong _font_, just a very poor _rendering_ of this particular font. A lot of each character is cut off. You might search on other instances of poor rendering of text, or try to find another Amharic font and see if that renders any better.

**Comment by Alantoo** [comment]
Thank you for response.
There used Arial font. I guess this font should be rendered fine. In the browser all looks good.
I tried to use font from Amharic site but nothing changed - PDfsa looks the same bad.

**Comment by PhilterPaper** [comment]
I think that PDF uses separate font files, and not necessarily the same ones as your browser does. It's never been clearly explained to me. That _might_ explain why your browser renders OK but the PDF doesn't. The font wkHTMLtoPDF is using might have a very poor implementation of Amharic script. I can't tell for sure, but it looks like the PDF file is trying to embed the font in it. 

Maybe someone with more in-depth font experience can explain this.

**Comment by Alantoo** [comment]
Okay. Thank you for answer.

**Comment by Alantoo** [comment]
Fixed by specifying font family Ebrima.
