### ISSUE TITLE
Multiple pages - content problem on page break

### ISSUE THREAD

**Issue by dev1ms** [wkhtmltopdf/wkhtmltopdf#3112]
Hello fellas,

I have a BIG problem to generate a PDF file with table of contents and graphics. All my HTML files are big and need to page break to insert all content.
The problem is when occurs the break to the next page, the contents aren't reallocated to the next page, i mean, the content are cutted or misconfigured... like the images bellow:

![print1](https://cloud.githubusercontent.com/assets/22085835/18367481/bb10cef2-75f1-11e6-841b-e3cb551f8eb1.png)
In this image, the content of table are misconfigured. I mean, the <thead> are printed again and the other lines come above it.

![print2](https://cloud.githubusercontent.com/assets/22085835/18367546/0f643d7c-75f2-11e6-8bc6-c42a0266e15d.png)
All graphics have five lines of measures. In this image, the Wkhtmltopdf cut the 2 first lines of the graphic, when the correct is reallocate all graphic to the next page.

The command to generate the file is: wkhtmltopdf --orientation Landscape --page-size A4 --margin-top 60 --footer-html "/path/to/footer/footer.html" --title "Titulo: do PDF" "/path/to/body/body.html" -

Can i do something to solve this problem?

If needs anything else, please, let me know!

Thx for now and good coding for us! .o/

**Comment by wuhuanhost** [comment]
<table> elements use css style `page-break-inside:avoid; `  **Avoid insert page breaks in elements**

**Comment by PhilterPaper** [comment]
There are two problems shown here, both of which are well known and have been reported many times:

1. First row of a new page overlaying the table heading.
2. Characters in last row of content on a page are split across pages.

**Comment by dev1ms** [comment]
Hello PhilterPaper!!

Thanks for advice! I seek for these topics, but don't found it! :(
Can u put the link to these?

**Comment by PhilterPaper** [comment]
Here are some recently active reports:
1. #1524, #1770, #3024, #2756, #2679 
2. #2678, #2491

**Comment by dev1ms** [comment]
Hello fellas,

Thanks for help!! I have added the css "page-break-inside:avoid" into the information table and put my charts into a table->tr->td.. now is everything fine, working like a swiss clock! 

\o/

**Comment by Mr-liu-yang** [comment]
please help me ,i find this issue ,  i try  added the css "page-break-inside:avoid" into the information table ,but it's working bad!
![hhhh](https://user-images.githubusercontent.com/31237992/43389884-6c395422-941f-11e8-9c7a-b3eb4dd90b33.png)
