### ISSUE TITLE
Colour inconsistency and sharpness issues between browsers and readers

### ISSUE THREAD

**Issue by Resurg3nt** [wkhtmltopdf/wkhtmltopdf#3116]
![wkhtml2](https://cloud.githubusercontent.com/assets/22156658/18448495/4e4b5672-7923-11e6-885f-1ef6ca443e7a.png)

![wkhtml1](https://cloud.githubusercontent.com/assets/22156658/18448499/51f74b96-7923-11e6-829f-808f492bdafe.png)

So as the above images demonstrate, I am having a problem with a PDF I am generating which does use colours, tables and images. 

The images and colours and contrast and text are great and correct when using Foxit PDF reader,  and when viewing it in Adobe PDF Reader the contrast is off, the text is blurred, and the images are horrendous.

It displays great in Chrome and Internet Explorer and Opera, and looks crappy in Firefox. 

Command line arguments:- 

--dpi 600 --no-pdf-compression --margin-left 1cm --margin-top 1cm --margin-bottom 1cm --margin-right 1cm --page-width 17cm --page-height 24cm

Resultant file is only 70kb. I have changed the dpi and no pdf compression arguments, dropped them etc. No effect.

Whats the problem here?

**Comment by Resurg3nt** [comment]
The problem seems to lie in the use of zoom and smart-shrinking.

**Comment by Tomsgu** [comment]
Closing as it seems to be resolved.
