### ISSUE TITLE
Add images header and footer

### ISSUE THREAD

**Issue by lihuamei** [wkhtmltopdf/wkhtmltopdf#3118]
Dear authors,
     When I use wkhtmltopdf software, I want to add image on header and footer which start by the third page, how can I attritive it, thanks!

**Comment by samcorcos** [comment]
An issue ticket is really not the place to ask. Try [stackoverflow](https://stackoverflow.com/search?q=wkpdftohtml).

**Comment by Tomsgu** [comment]
See samcorcos comment.
