### ISSUE TITLE
Delay output

### ISSUE THREAD

**Issue by morgan3d** [wkhtmltopdf/wkhtmltopdf#3122]
I have documentation pages with Mathjax in them which take up to two seconds for Mathjax to load and then process the page. I'd like to give wkhtmltopdf an argument telling it to wait for these lingering Javascript processes to finish (even with a hardcoded timeout).

**Comment by navbhu** [comment]
@morgan3d  Did you try [--javascript-delay](http://wkhtmltopdf.org/usage/wkhtmltopdf.txt) this option?

**Comment by morgan3d** [comment]
That works great, thank you.
