### ISSUE TITLE
wkhtmltopdf --help does not show all options 

### ISSUE THREAD

**Issue by morgan3d** [wkhtmltopdf/wkhtmltopdf#3123]
At least on the OS X build, very few of the options from http://wkhtmltopdf.org/usage/wkhtmltopdf.txt are shown by wkhtmltopdf --help (the options do work, though).

**Comment by navbhu** [comment]
@morgan3d  you have to use -H or --extended-help  to display all options. It is mentioned in your link.

**Comment by morgan3d** [comment]
I'm terribly sorry, thank you!

I recommend specifically repeating that option at the bottom of the help page...say right under the link that sends people here. I skimmed the page and piped it through "grep javascript" without ever noticing the extended help option...and thus spammed you.
