### ISSUE TITLE
tr {page-break-inside:void. } doesnt work on 0.13.0 and letter-spacing on 0.12.3.2

### ISSUE THREAD

**Issue by concepta-thiago** [wkhtmltopdf/wkhtmltopdf#3129]
Hello there, 

i have two issues here, 
1 - related to page-break-inside:voide in the tr elemn
2 - letter spacing not working

i have a table with many rows, and im using a page-break-inside:void in the tr

the page-break-inside:void was working fine on windows version 0.12.3.2 (letter spacing doesnt works)
but then i updated to the version 0.13.0-alpha (letter spacing works ) and the page-break-inside:void stoped working (it still works if i put this in a div, but it doesnt inside the table tr)

does anyone knows any work around to make the `page-break-inside:void` works on version 0.13.0-alpha 
or to make the letter spacing works on 0.12.3.2?

**Comment by PhilterPaper** [comment]
Did you _really_ use "void" in the CSS? It's never been valid. Your choices are _auto, **a**void, initial, inherit_. 

I don't know about the letter-spacing. Can you give us an example of your CSS usage?

**Comment by concepta-thiago** [comment]
Im sorry i typed wrong many times and didn`t even notice,
i`m do using `avoid``
here is  my CSS

tr {
    page-break-inside: avoid;
}

p {
    letter-spacing: 1px; 
}

**Comment by PhilterPaper** [comment]
There has been much discussion on _page-break-inside_ and the many cases where there are problems with it. Have you read the bug reports and discussions?

When you say that _letter-spacing_ isn't working, what are the symptoms? Your example is to **add** one pixel between the letters in a paragraph. That's a rather small amount to be visible. Does going to some absurdly large amount (say, 50px) have visible effect? By the way, the usual suggestion to use a length related to the font _size_, such as **.5em**. That should scale properly with font size changes.
