### ISSUE TITLE
Silent windows installer

### ISSUE THREAD

**Issue by AmsterdamFilho** [wkhtmltopdf/wkhtmltopdf#3131]
This is a feature request.

In case one wants to embed wkhtmltopdf in his application, a silent installer for Windows would be nice. It would also be nice if the installer added the bin folder to Windows PATH environment variable, so the executable could run from anywhere in the command line.

**Comment by PhilterPaper** [comment]
Two issues here: 1) Are you allowed to embed wkHTMLtoPDF for redistribution? Check the license. 2) A lot of people don't like applications being silently installed on their systems. At the least, inform the user and get permission before doing the installation.

**Comment by AmsterdamFilho** [comment]
As of issue 1, it's LPGL V3, so I think there is no problem to embed the wkHTMLtoPDF Windows installer in the application installer, call it during installation, and invoke the EXE programmatically in case a user wants a PDF file. I think that does not violate the license.
As of issue 2, that is definitely a good heads up.

**Comment by ashkulz** [comment]
wkhtmltopdf uses [NSIS](http://www.silentinstall.org/nsis).

**Comment by AmsterdamFilho** [comment]
Thanks.
