### ISSUE TITLE
Compile the source code of the project wkhtmltopdf by using Visual Studio 2013

### ISSUE THREAD

**Issue by errorize** [wkhtmltopdf/wkhtmltopdf#3133]
Hey buddy, you do a great contribution to the world! I am new to develop Qt project, which means I am try familiarizing myself with Qt hard. I wish you can give others and me an example of wkhtmltopdf which is compiled by Visual Studio 2013 or as a solution. Thank you.

**Comment by ashkulz** [comment]
See the Windows build instructions in `INSTALL.md`.
