### ISSUE TITLE
Odoo Wkhtmltopdf failed (error code: -6)

### ISSUE THREAD

**Issue by alaltelal** [wkhtmltopdf/wkhtmltopdf#3139]
When i print an RFQ, or a PO, I get this error. I am using Odoo 8 on Ubuntu Server 16.04

Wkhtmltopdf failed (error code: -6). Message: The switch --header-spacing, is not support using unpatched qt, and will be ignored.The switch --header-html, is not support using unpatched qt, and will be ignored.The switch --footer-html, is not support using unpatched qt, and will be ignored.QXcbConnection: Could not connect to display

Is this an issue with Wkhtmltopdf having not loaded properly or a template consraints issue?

**Comment by CainCobain** [comment]
Hi, I was wondering if u found out the solution for this error because I have the same . 
Thank you and have a nice day .

**Comment by lucasub** [comment]
Also my odoo installation with debian jessie and the sid have the same error. 
Thank you in advance.
Luca

**Comment by fidelo74** [comment]
try  this, it works : https://gist.github.com/tejastank/45b6eba13fb38e24110218e3ce50129b
