### ISSUE TITLE
Negative letter-spacing breaks positioning

### ISSUE THREAD

**Issue by eithed** [wkhtmltopdf/wkhtmltopdf#3142]
Hello,

I've encountered an issue where negative letter-spacing on individual elements breaks the positioning of entire element set. For example:

![1](https://cloud.githubusercontent.com/assets/795678/18838090/061fd0a4-83fe-11e6-8b89-dd01cad83fc4.png)

with following markup:

`<div style='letter-spacing: -3.6px'>Victoria S<span class="_ _3"></span>ponge......£2</div>`

will render like this:

![2](https://cloud.githubusercontent.com/assets/795678/18838112/17565032-83fe-11e6-92de-de0ab2351883.png)

As you can see not only is the letter-spacing not rendered correctly, but it affects positioning as well

**Comment by alloylab** [comment]
is this still an issue on 0.12.5?
