### ISSUE TITLE
Default height of the document is not page height, but zero

### ISSUE THREAD

**Issue by Glurak** [wkhtmltopdf/wkhtmltopdf#3144]
The problem:
Have a html code with just one image of height=100%
On PC in any major browser, it stretches the image to browser window height.
With wkhtmltopdf, I expect the image to be stretched to the height of one page, but nope, it is generated with zero height.

Probable cause and solution:
default height of document in wkhtmltopdf is zero and will be zero until some contents overflows. Make it the height of output media (eg A4 document, unless else), like PC browsers do with window size.

Workaround (not solution):
Download source code and somehow inject css code into it that explicitly sets document height corresponding to chosen media format and DPI.

**Comment by alloylab** [comment]
is this still an issue on 0.12.5?
