### ISSUE TITLE
Blank space added in the middle of a table

### ISSUE THREAD

**Issue by giordy** [wkhtmltopdf/wkhtmltopdf#3146]
I'm facing a strange issue in a report. 
For some reason wkhtmltopdf is adding a blank space in the middle of the table, as you may see in this image:

![issue](https://cloud.githubusercontent.com/assets/6016950/18908668/cd2e5670-8570-11e6-9701-99b1815d9339.png)

Here you can find some example code to reproduce the issue:
[example-code.zip](https://github.com/wkhtmltopdf/wkhtmltopdf/files/497648/example-code.zip)
I'm using the latest stable version of wkhtmltopdf, namely: _wkhtmltopdf 0.12.3 (with patched qt)_.
The command I'm using to generate the PDF file is:
`wkhtmltopdf --footer-center [page] --footer-font-size 10 --header-spacing 5 -B 10 -T 25 --image-dpi 300 --image-quality 80 --header-html header.html doc.html doc.pdf`

I tried to experiment with the CSS code and the HTML quite extensively, however the gap seems to appear all the time.

Any idea why this might be happening?

Thanks a lot for your work on wkhtmltopdf, it's a great tool :)

**Comment by GabLeRoux** [comment]
You should try to add some css background colors to see if this is inside a `tr` or a, a `td` or if this is part of the table itself. I'm having a similar issue for some rows only after a few pages. Let us know if you found something

**Comment by Tomsgu** [comment]
The bug seems to be resolved. I can't reproduce it in 0.12.5 version. Please feel free to re-open this issue if it still happens to you in a newest stable version.

**Comment by bhaveshselarka** [comment]
Still facing the same issue.

**Comment by divdax** [comment]
i have the same issue after page break with 0.12.5
