### ISSUE TITLE
Generating PDF card is not moving

### ISSUE THREAD

**Issue by liangyangtao** [wkhtmltopdf/wkhtmltopdf#3148]
This text is translated by the translation software：

I am a Chinese, I try to run htmltopdf

Eg:

```
        wkhtmltopdf Http://www.sina.com.cn/ c:/sina.pdf 
```

Encountered a problem, running half is not in the implementation of the

Please give a feasible solution, thank you

original text

我是中国人，我尝试运行htmltopdf  

eg：

wkhtmltopdf http://www.sina.com.cn/ c:/sina.pdf

遇到了问题， 运行一半不在执行了

请给出一个可行解决方案，谢谢

**Comment by liangyangtao** [comment]
![a](https://cloud.githubusercontent.com/assets/5389893/18978077/3557a94a-86f2-11e6-8fa6-189aad4d3292.jpg)
![b](https://cloud.githubusercontent.com/assets/5389893/18978078/355a046a-86f2-11e6-87c2-dedd11f4e8ce.jpg)

**Comment by liangyangtao** [comment]
English

Please note that time, have been a long time, has been stuck

Chinese
请注意时间，都过了很长时间了，一直卡着没动

**Comment by PhilterPaper** [comment]
You might want to first deal with the **Pixel size <= 0** error, as that may be triggering the infinite loop. There have been a number of issues raised regarding this message, so you might want to search the issues. One person reported that upgrading to version 0.12.3 solved the problem for them.
