### ISSUE TITLE
Cannot access Odoo - only via localhost:8069

### ISSUE THREAD

**Issue by alaltelal** [wkhtmltopdf/wkhtmltopdf#3150]
I have a weird issue that I cannot replicate. I have Odoo 8 on Ubuntu Server 16.04. I can access Odoo via localhost:8069 when at the servers console. I cannot access via 192.168.1.111:8069 via the server console or any other machine on the network. I also cannot access via external IP. I can ping the servers IP just fine from any other machine on LAN. I can access the servers Apache html via local network. I have port forwarded 8069 and opened the routers firewall. I had a failed install and configuration of Nginx, but was removed. Any ideas I am missing?

**Comment by ashkulz** [comment]
Ask via the Odoo support channels?
