### ISSUE TITLE
would this be expected to convert? vuejs.org/guide/

### ISSUE THREAD

**Issue by chrisamow** [wkhtmltopdf/wkhtmltopdf#3152]
I'm doing this from the python pdfkit
pdfkit.from_url('http://vuejs.org/guide/', 'vuejs_guide.pdf')
and it will only convert the first entry in the contents (Installation) - 7 pages. Also the contents pane on the left overlaps the main text [(http://i.imgur.com/Ix7kHnn.png)](http://i.imgur.com/Ix7kHnn.png)
Are frameworks like vue (since they did their website using their own stuff) too complicated to expect pdf rendering?  I didn't see this in any faqs that I found so sorry if this is too obvious.

**Comment by Tomsgu** [comment]
Closing as this is not a pdfkit. There are some js limitations. E.g. ES6 isn't supported.
