### ISSUE TITLE
Is there a way to generate pdf and print on preprinted paper

### ISSUE THREAD

**Issue by nrusta** [wkhtmltopdf/wkhtmltopdf#3153]
I have a scenarios where i want to develop a solution for client. Client already have pre- printed stationary on which they need more data to be printed in specific positions. 
Is there a way I can achieve same by WkHtmltoPdf? If yes, then can you please lead me to some example.

**Comment by Tomsgu** [comment]
Hi,

I am going through an old issues. I am closing this one, because nobody gave you an answer and I expect that you've resolved it. If not please feel free to open a question in stackoverflow.
