### ISSUE TITLE
pdf corrupted when div is straddling two pages

### ISSUE THREAD

**Issue by fugarte** [wkhtmltopdf/wkhtmltopdf#3157]
Hello

My Symfony project has a KnpSnappy bundle which uses wkhtmltopdf to generate pdf files with headers and footers.
When a div has few contents (I mean the div is not high enougth), it could be between the end of one page and at the beginnning of the other page : the pdf file is generated but it can't be opened : the file is corrupted.

To avoid the problem I've included in the div a h3 tag with a 40 px margin-top : the  pdf file is correctly generated with the div content totally at the end of a page or totally at the beginning of the next page.

I couldn't reproduce the problem using command lines to generate the pdf file.

**Comment by alloylab** [comment]
have you tried this?

`div{
	page-break-inside: avoid !important;
}`

**Comment by fugarte** [comment]
I've tried it but the problem didn't disappear. By the way, I thank you for your comment.

**Comment by fugarte** [comment]
I've tried it but the problem didn't disappear. By the way, I thank you for your comment.

**Comment by fugarte** [comment]
The problem was present with version 0.12.3.
I've installed wkhtmltopdf 0.12.4 and the problem has disappeared.
