### ISSUE TITLE
The pagination bug when having long table

### ISSUE THREAD

**Issue by sadkilo** [wkhtmltopdf/wkhtmltopdf#3159]
I have a long table ,when with no --print-media-type running wkhtmltopdf;
To second page , the table head and body is overlapped; but when with  --print-media-type; it is ok。
but I don`t like with  --print-media-type , because it will lost the background-color。
Someone can tell me what should i do?

ps: I use 0.12.3.2 (window x64)

**Comment by sadkilo** [comment]
I have solved this problem by myself, 
use option [--user-style-sheet "export.css"]
set the css:
tr{page-break-inside:avoid;}

**Comment by flyDream123** [comment]
thank you very much for resolving my problem.
