### ISSUE TITLE
how to get wkhtmltopdf process start and end time to show loader

### ISSUE THREAD

**Issue by sachinshinde2802** [wkhtmltopdf/wkhtmltopdf#3161]

**Comment by Bastiengrsd** [comment]
If you have find a solution for this issue please tell me ! I search this too

**Comment by Tomsgu** [comment]
Hi,

I am going through an old issues. I am closing this one, because nobody gave you an answer and I expect that you've resolved it. If not please feel free to open a question in stackoverflow.
