### ISSUE TITLE
background image width in japanese encoding

### ISSUE THREAD

**Issue by by-axis41** [wkhtmltopdf/wkhtmltopdf#3162]
The PDF header background image width / height seems to be flipped versus the HTML ( wkhtmltopdf  v  0.12.3 "stable" binary, Mac OSX 10.11.6 (15G1004) )  when I try the "sample" Japanese from  http://generatedcontent.org/post/45384206019/writing-modes   ...

[sample-japanese.pdf](https://github.com/wkhtmltopdf/wkhtmltopdf/files/528046/sample-japanese.pdf)

This is using a CSS background image for the article header element with Japanese text ...

header {
  width: 100%;
  height: 34rem;
  margin-bottom: 8rem;
  background-image: url(https://dl.dropbox.com/u/444684/OpenWebDemos/css3writingModes/images/2752501599_bdfb7a9258_b.jpg);
  background-size: 100% auto;
  -ms-writing-mode: tb-rl;
  -webkit-writing-mode: vertical-rl;
  -moz-writing-mode: vertical-rl;
  -ms-writing-mode: vertical-rl;
  writing-mode: vertical-rl;
}

**Comment by alloylab** [comment]
is this still an issue on 0.12.5?
