### ISSUE TITLE
Width of pdf depends on the environment where it is created

### ISSUE THREAD

**Issue by kobruleht** [wkhtmltopdf/wkhtmltopdf#3165]
wkhtmltopdf 0.12.3.2 is used to create pdf files in Windows 7 x64 and Windows 10 x64 from same html with options:

```
C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe --lowquality -L 0mm -R 0mm -T 0mm -B 0mm --dpi 96 --zoom 1.6 - -
```

exe file is invoked from from ASP.NET MVC 4 controller.

In Windows 10 developement computer running from Visual Studio/IIS Express text zoom is less and there is appox 2 cm right margin (empty space)

In Windows 7 production computer runnning from IIS pdf zoom is bigger and text ends in right edge of page.

html code used to generate pdf and wkhtml version are same in both Windows computers. 

However result pdf sizes are different: 36663 and 30814 bytes.

Same zoom level/dpi produduces different pdf is different computers.

Posted also in

http://stackoverflow.com/questions/40043886/how-to-produce-same-width-pages-in-wkhtmltopdf-in-different-computers

Here is testcase:

[testcase.zip](https://github.com/wkhtmltopdf/wkhtmltopdf/files/530166/testcase.zip)

it contains two rows with same text:

```
<!DOCTYPE html>
<html>
<head>
    <style>
        * {
            margin: 0;
            padding: 0;
        }

         html, body {
            height: 100%;
            width: 100%;
        }

        .row {
            position: relative;
            clear: both;
           }

        .field {
            font-family: "Times New Roman";
            font-size: 10pt;
            background-color: transparent;

            overflow: hidden;
            word-break: break-all;
            z-index: 2;
        }

         @page {
            visibility: hidden;
            margin: 0;
            height: auto;
            size: portrait;
 ;
        }

.field, .image {
            position: absolute;
        }
    </style>
</head>
<body><div class='row' style='min-height:0.54cm'><div class='field' style='left:1.97cm;'>left 2cm.......................................................................................................................................................................................right 2 cm</div>
</div>

<div class='row' style='min-height:0.54cm'><div class='field' style='left:1.97cm;'>left 2cm.......................................................................................................................................................................................right 2 cm</div>
</div>
</body>
</html>
```

In windows10.pdf created in windows 10 both lines are in same row.
In  windows7.pdf created in windows 7 lides are wrapped into tow rows.
Pdf sizes are very different: windows10.pdf size is 7878 and windows7.pdf size is 5991

**Comment by alloylab** [comment]
is this still an issue on 0.12.5?

**Comment by ohcibi** [comment]
@alloylab i had rendering issues on macos so I came across this issue and tested if those are gone in docker container..... The issues are in fact worse but the rendering result is clearly completely different. So yes, still an issue.
