### ISSUE TITLE
Knowing if a third-party asset can not be loaded.

### ISSUE THREAD

**Issue by micheal-swiggs** [wkhtmltopdf/wkhtmltopdf#3167]
At the moment we have the following for custom fonts:

```
@font-face {     
    font-family: 'MuseoSansRounded-300.otf';     
    src: url('/home/shared/custom-font.otf') format('opentype');     
    font-weight: normal;     
    font-style: normal;   
}
```

We had an issue where where we were unable to access our font files and consequently the generated PDFs were not styled correctly. Is it possible to know if a wkhtmltopdf can not access font files. Ideally I would prefer that wkhtmltopdf stops working and returns an error. I have tried `--load-media-error-handling abort` but this doesn't seem to work.

**Comment by alloylab** [comment]
is this still an issue on 0.12.5?
