### ISSUE TITLE
Chinese characters in string cause string to be duplicated

### ISSUE THREAD

**Issue by epdejager** [wkhtmltopdf/wkhtmltopdf#3169]
Hi there,

We have a new client who have some Chinese text in the html we are trying to convert to svg. 

However, any Chinese text present in the string (which is a `<tspan>` inside a `<text>`) seems to cause the string to be repeated multiple times in the output svg by whktmltomiage. The string is repeated at least 3 times, but up to 6 times it seems, depending on the platform (Ubuntu or OSX for example). These duplicated strings are at the same y coordinate but at a different x coordinate to the original.

I'm doing my testing with `wkhtmltoimage 0.12.3` on `OS X El Capitan 10.11.6`. 

We have found that putting `<tspan>`'s around the Chinese text solves the problem on OS X but not on for example `12.04 ubuntu precise` - on the latter it just decreases the duplication from 6 to 4 times.

I've attached an html (actually its an svg but that's what's inside our html) file that demonstrates the problem.
[original.svg.zip](https://github.com/wkhtmltopdf/wkhtmltopdf/files/532950/original.svg.zip)
Here is the output the above gives when running through wkhtmltoimage
[output.svg.zip](https://github.com/wkhtmltopdf/wkhtmltopdf/files/533018/output.svg.zip)

Does anyone know of a way around this?

Thanks so much,
Eliza.

**Comment by alloylab** [comment]
is this still an issue on 0.12.5?
