### ISSUE TITLE
column-count

### ISSUE THREAD

**Issue by bavanyo** [wkhtmltopdf/wkhtmltopdf#3172]
Is there any word on when column-count will be supported?
Right now the workaround in https://github.com/wkhtmltopdf/wkhtmltopdf/issues/1872 is all we have....

**Comment by rohitt-webonise** [comment]
Yeah Also needed this to work, in pringting landscape pdf pages.

**Comment by alecasciaro** [comment]
Is there any news about column-count  support ?

**Comment by jonathanpa** [comment]
:+1:

**Comment by Tomsgu** [comment]
There aren't any news. Please continue here: #2266
