### ISSUE TITLE
Text selection and presentation broken in chrome preview

### ISSUE THREAD

**Issue by SuperSeb92** [wkhtmltopdf/wkhtmltopdf#3173]
When opening a preview of the pdf in chrome, text is broken into pieces and often not rendered with the proper kerning

I've tried using wkhtmltopdf both on my mac with the OSX download, and on ubuntu trusty built from source.

Apparent with the bare:
`wkhtmltopdf http://google.com google.pdf`

![image](https://cloud.githubusercontent.com/assets/9269477/19626759/dcc34ece-992f-11e6-97df-759f11a93b2c.png)

**Comment by alloylab** [comment]
is this still an issue on 0.12.5?

**Comment by SuperSeb92** [comment]
Nope, looks like it's resolved 👍

**Comment by alloylab** [comment]
Great! If you have any other issues please let us know.
