### ISSUE TITLE
Recieved "not a valid Win32 application" error

### ISSUE THREAD

**Issue by cfprogrammer** [wkhtmltopdf/wkhtmltopdf#3174]
I installed "wkhtmltox-0.12.3.2_msvc2013-win32.exe" on to a windows2003 server and got the not a valid Win32 application error.  tried installing a couple of times and redownloaded at least 3 times.

Then I installed "wkhtmltox-0.12.2.4_mingw-w64-cross-win32.exe" ran fine the first time

**Comment by ashkulz** [comment]
It clearly states `for Windows Vista or later; bundles VC++ Runtime 2013` -- Windows 2003 is no longer supported by Microsoft.
