### ISSUE TITLE
Turkish letters are not showing in PDF

### ISSUE THREAD

**Issue by amitRosenberg** [wkhtmltopdf/wkhtmltopdf#3175]
I am trying to create a pdf from html using version :  wkhtmltopdf 0.12.3 (with patched qt)
this is the HTML:
<!DOCTYPE html>
<html><head></head> <body><u>Giriș:</u></body></html>
tried both commands with no success
1) ./wkhtmltopdf --orientation 'Portrait' --page-size 'A4' --encoding 'utf8' --header-html '/tmp/test_pdf.html' '/tmp/empty_file.html'  '/tmp/test_pdf.pdf'
2)  LANG=en_US.UTF-8; ./wkhtmltopdf --orientation 'Portrait' --page-size 'A4' --encoding 'utf8' --header-html '/tmp/test_pdf.html' '/tmp/empty_file.html'  '/tmp/test_pdf.pdf'

After those options failed i tried to replace the special char with its code '&#351;'
and reran both the commands with no success
in both tests with both commands i keep getting this car as missing

**Comment by amitRosenberg** [comment]
can anyone help with this?

**Comment by PhilterPaper** [comment]
Please use "code" markup (Markdown styling), so all that stuff isn't run together. You can enclose that block of text with backticks, or indent 4 spaces, with a blank line before and after it. Use the "Preview" tab to check that it works.

The letter in question is one that I think Microsoft handles in a funny way ("smart quotes" set). The first thing to check is whether you accidentally edited your source with a Windows code set (e.g., CP-125x) rather than UTF-8. If you did, fix your text in a proper editor and try again.

**Comment by amitRosenberg** [comment]
No i am working with linux and the text is set to UTF-8 only

**Comment by PhilterPaper** [comment]
So, any place in your HTML input where the character 'ş' appears, produces something else in the PDF? Is it an empty space, a string of two or three accented characters, or something else? Does the HTML page display correctly (suggesting that the character is correct in it)? Is it only this one character? 

The only thing I can think of at the moment is that the font file you're using for generating the PDF either does not have that character, or it has it in the wrong place for UTF-8. You might check the encoding of the font file and see if it's not UTF-8, or possibly even CP-125x. As I said before, I think this character is treated a bit oddly in character sets, and might cause problems. Offhand, I don't know how you would check for if and where 'ş' is present in the font -- maybe you can find some utility that can dump the font file?

**Comment by rjasdf** [comment]
Adding this to the top of the html solved it for me:

`<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />`

**Comment by Tomsgu** [comment]
Closing as the solution was found.
