### ISSUE TITLE
how to config low quality?

### ISSUE THREAD

**Issue by alvy-singer** [wkhtmltopdf/wkhtmltopdf#3176]
here is my code

```
pdf = pdfkit.from_url(url, False)
```

size of the pdf file is too large, time of send to user is too long
so  I want change the quality of pdf ,how to config?
I use

```
options = {
      'lowquality': True
  }
```

but error:

```
Error: Failed loading page http://true (sometimes it will work just to ignore this error with --load-error-handling ignore)
Exit with code 1 due to network error: HostNotFoundError     ] 55%
```

how to do this?thank you

**Comment by alloylab** [comment]
have you tried this?

`options = {
    'lowquality': ''
    }
 `
based on the quiet option from documntation below... this seems to be more logical 
https://pypi.python.org/pypi/pdfkit

**Comment by ashkulz** [comment]
This looks like a bug/usage issue with `pdfkit`.
