### ISSUE TITLE
output a blank pdf

### ISSUE THREAD

**Issue by pc10201** [wkhtmltopdf/wkhtmltopdf#3177]
I use windows and centos latest wkhtmltopdf version

I ran 

wkhtmltopdf test.html test.pdf

But test.pdf is blank.

the test.html is in the attachment

[out.zip](https://github.com/wkhtmltopdf/wkhtmltopdf/files/552409/out.zip)

**Comment by alloylab** [comment]
is this still an issue on 0.12.5?
