### ISSUE TITLE
pixelated fonts when generating PDF on Ubuntu machine

### ISSUE THREAD

**Issue by jurchiks** [wkhtmltopdf/wkhtmltopdf#3179]
I'm trying to generate a PDF invoice, but I'm having weird font issues on the server.
The HTML: https://gist.github.com/jurchiks/7fc2f60e43246d09081364703ff8c87c
Output on dev (Windows 10) + server (Debian Wheezy): https://snag.gy/BcX0Wl.jpg
Font list on the server (`fc-list`): https://gist.github.com/jurchiks/4c91fde4fed0a73129ce78178dd17988
As you can see, the font is pixelated on the server for some reason. Does anyone know what is the reason and how I could fix this?

I suppose it's worth noting I'm not very good with Linux and know nothing about its font system.

**Comment by jurchiks** [comment]
@alloylab good job noticing this after 2 years, lol.

**Comment by alloylab** [comment]
Only started helping out recently, what version are you running?

**Comment by jurchiks** [comment]
I don't work at the place where I had this issue anymore.
