### ISSUE TITLE
Set Page Load timeout? 

### ISSUE THREAD

**Issue by opie** [wkhtmltopdf/wkhtmltopdf#3182]
Hello,

I've been using WKTHMLTOPDF for some time to load a collage of ~10 webpages to capture and record the weather at a given moment in time (for archival purposes).  I have a script which calls WKHTMLTOPDF (v12.1.1 - yes I know it is old).

Occasionally one of the websites (usually Environment Canada's Lightening map) doesn't load properly and can take 5 to 30 minutes.   

Is there a means to specify a timeout value for the maximum amount of time a given page can take before completing it's download?  

I have all the urls in a file calls cmds.txt and call it as follows:

wkhtmltopdf --footer-left [webpage] --footer-font-size 6 --load-error-handling ignore --javascript-delay 60000 --read-args-from-stdin  0<cmds.txt 2>>wkhtmltopdfErrors.txt

Thanks,

Owen

**Comment by alloylab** [comment]
is this still an issue on 0.12.5?
