### ISSUE TITLE
Really slow performance on RHEL

### ISSUE THREAD

**Issue by israbbani** [wkhtmltopdf/wkhtmltopdf#3183]
I have a docker package that spawns a node server running wkhtmltopdf. The wkhtmltopdf version is 0.12.3 and the NodeJS version is 5.3.0. 

If I run this setup on a virtual machine (Ubuntu 16.04 or CentOS 7) through virtual box, wkhtmltopdf takes about 15 seconds to render a PDF. 

However, if I deploy this package to an AWS RHEL 7.2 server, wkhtmltopdf takes about 90 seconds to render. The server has a very powerful GPU installed with the latest drivers from Nvidia. I've logged processing times and the wkhtmltopdf binary takes around 90 seconds to render the pdf page and pipe it back. 

Does anyone have any idea why this is happening?

**Comment by PhilterPaper** [comment]
Does the Graphics Processing Unit get involved at all if the output is _not_ going to the display? Is the CPU reasonably powerful, and not loaded down with other tasks?

**Comment by israbbani** [comment]
The CPU is an Intel Xeon. It is much much better than the one on my laptop that is being used by the virtual machine. I don't know if the GPU gets involved or not if there's no output going to a display. I thought we'd tack on a GPU just to see if it improved performance and it did not

**Comment by alloylab** [comment]
@israbbani I have had similar peformance issues... now my setup is not exactly the same as yours... but I achieved faster wkhtmltopdf rendering with changing the --dpi to 72.... are you using the standard DPI setting?  Also, how are you calling the wkhtmltopdf binary? from NodeJS?

**Comment by Tomsgu** [comment]
Is this still true in a `0.12.5` version?

**Comment by ashkulz** [comment]
Closing this issue as there was no feedback from the reporter for a long time. Please feel free to reopen the issue with details if this is still a problem.
