### ISSUE TITLE
Auto login on windows authenticated sites

### ISSUE THREAD

**Issue by viswa18** [wkhtmltopdf/wkhtmltopdf#3184]
I have convert share point site, which is using windows authentication. I have convert that site with my username and password, it is works well. For each time I need to specify username and password. Instead of this can we store credentials for auto login. Is there any feature around this.

Please let me know any option for this.

Thanks in advance.

**Comment by ARUPorendaw** [comment]
I would also like this feature

**Comment by ashkulz** [comment]
Looks like you need to call `setUser` with an empty password for NTLMv2 authentication according to [this answer on StackOverflow](http://stackoverflow.com/a/17858218). Probably a new flag needs to be introduced for this.

**Comment by carloshpdoc** [comment]
Hi people, can someone help me? please!!!

I execute on PHP + Apache+Windows and generates this error.: wkhtmltopdf Authentication Required Error

**Comment by ARUPorendaw** [comment]
It sounds like the web page you are trying to access is restricted. You may need to include the username and password flags.

**Comment by carloshpdoc** [comment]
Thanks for the reply, but i can't do by apache?
