### ISSUE TITLE
Version 13 with patched Qt?

### ISSUE THREAD

**Issue by HosseinAgha** [wkhtmltopdf/wkhtmltopdf#3185]
Because of some major issues in version 12, I can only use 13 for my special use case.
The main reason that I use WKHtmlToPDF is to have headers and footers on every page and this feature needs a patched QT.
I couldn't build version 13 for Windows nor CentOS. plus I don't know how to build it with patched Qt.

1 - Is there a version 13 binary with patched Qt out there?
2- If not. Can someone guide me on how to build for Windows or CentOS? 
The build guide and make file are not sufficient for building new versions and there are a lots of dependency errors.

**Comment by ashkulz** [comment]
See [@poizan42's work](https://github.com/poizan42/wkhtmltopdf/releases/tag/0.13-qt5.6-alpha1) which is Windows-only. If you have errors, open an issue with the exact errors you are facing.

**Comment by pankajniet** [comment]
viewport-size option is not working on windows.

> wkhtmltopdf --viewport-size 1920x1080  --dpi 300 .\149829_0_0.html .\141850_dqsd.pdf
Qt: Untested Windows version 10.0 detected!
The switch --viewport-size, is not support using unpatched qt, and will be ignored.Loading page (1/2)
Printing pages (2/2)
Done

How to compile it with qt support?
