### ISSUE TITLE
letter-spacing doesn't work properly, not even with --dpi 96

### ISSUE THREAD

**Issue by PaulInCambridge** [wkhtmltopdf/wkhtmltopdf#3187]
Example html: 
[TestLetterSpacing.txt](https://github.com/wkhtmltopdf/wkhtmltopdf/files/565498/TestLetterSpacing.txt)

Chrome screenshot:
![testletterspacingchrome](https://cloud.githubusercontent.com/assets/23195610/19914009/35ebfff2-a09f-11e6-81e8-0f14131d1332.jpg)

wkhtmltopdf pdf (from command line):
[TestLetterSpacing.pdf](https://github.com/wkhtmltopdf/wkhtmltopdf/files/565512/TestLetterSpacing.pdf)

wkhtmltopdf pdf  with --dpi96 (from command line):
[TestLetterSpacingDpi96.pdf](https://github.com/wkhtmltopdf/wkhtmltopdf/files/565514/TestLetterSpacingDpi96.pdf)

--dpi96 (as suggested in response to previous queries about this) makes it less bad, but it still doesn't work properly.  It would be a boon if this could be fixed, thanks.

**Comment by alloylab** [comment]
is this still an issue on 0.12.5?
