### ISSUE TITLE
SVG dominant-baseline

### ISSUE THREAD

**Issue by t1geomatika** [wkhtmltopdf/wkhtmltopdf#3188]
HI, 

To begin, thanks for your work really helpful.

I have a problem using wkhtmtoimage to render an svg file into a png image.

The property dominant-baseline of the svg is not interpreted, so my labels are drawed with y offset.

My file is the following : 
<svg xmlns="http://www.w3.org/2000/svg" id="OpenLayers_Layer_Vector_13_svgRoot" style="display: block;" width="1394" height="835" viewBox="0 0 1394 835">
   <g id="OpenLayers_Layer_Vector_13_root" style="visibility: visible;" transform="">
      <g id="OpenLayers_Layer_Vector_13_vroot">
         <circle id="OpenLayers_Geometry_Point_84" cx="405.6232462101616" cy="276.76394079299644" r="0" fill="#FFFF00" fill-opacity="1" stroke="#FFFF00" stroke-opacity="1" stroke-width="5.000696189441697" stroke-linecap="round" stroke-linejoin="round" stroke-dasharray="none" />
         <path id="OpenLayers_Geometry_Polygon_106" d=" M 407.5029573389329,268.7639407599345 542.5029573098291,268.7639407599345 542.5029573098291,304.76394075201824 407.5029573389329,304.76394075201824 407.5029573389329,268.7639407599345 z" fill-rule="evenodd" fill="#FF0000" fill-opacity="0" stroke="#FF0000" stroke-opacity="0.8" stroke-width="5.000696189441697" stroke-linecap="round" stroke-linejoin="round" stroke-dasharray="none" />
      </g>
      <g id="OpenLayers_Layer_Vector_13_troot">
         <text id="OpenLayers_Feature_Vector_85_label" x="405.6232462101616" y="276.76394079299644" fill="#FF0000" font-family="times" font-size=" 25.003480947208484px" font-weight="normal" font-style="normal" pointer-events="visible" text-anchor="start" dominant-baseline="central">
            <tspan id="OpenLayers_Feature_Vector_85_label_tspan_0" x="405.6232462101616" dy="0em">Text here</tspan>
         </text>
      </g>
   </g>
   <defs id="OpenLayers_Layer_Vector_13_defs">
      <symbol id="OpenLayers_Layer_Vector_13-move" viewBox="-12 -12 24 24">
         <polygon points="1 , 1 3 , 1 3 , 2 4 , 0 3 , -2 3 , -1 1 , -1 1 , -3 2 , -3 0 , -4 -2 , -3 -1 , -3 -1 , -1 -3 , -1 -3 , -2 -4 , 0 -3 , 2 -3 , 1 -1 , 1 -1 , 3 -2 , 3 0 , 4 2 , 3 1 , 3 1 , 1" />
      </symbol>
      <symbol id="OpenLayers_Layer_Vector_13-resize" viewBox="-9 -9 18 18">
         <polygon points="0 , 3 3 , 3 3 , 0 2 , 1 -1 , -2 0 , -3 -3 , -3 -3 , 0 -2 , -1 1 , 2 0 , 3" />
      </symbol>
   </defs>
</svg>

I'm using the latest stable version 0.12.3.2

**Comment by alloylab** [comment]
is this still an issue on 0.12.5?
