### ISSUE TITLE
Different Rendering Results on Two Servers

### ISSUE THREAD

**Issue by z38601** [wkhtmltopdf/wkhtmltopdf#3189]
We have two servers in our web farm with identical specs: Windows Server 2008 R2 Standard SP1, 16GB RAM, Intel Xeon CPU E5-2670 @ 2.60 GHz (4 processors)

Each is running the same version of wkhtmltopdf 0.12.3.2 (with patched qt).

However, we are getting two different results on these servers when the PDF is generated from the same target web page. I've attached examples of the output from both servers as well as the target HTML page (uploaded here as Form.txt, but download it and change the extension to .htm to see it in the browser).

Only the example from server 1 renders correctly. There is a vendor section on the last page that starts with Date Vendor Contacted: 10/6/2016. All of the fields in that section are highlighted in blue boxes. That section is visible as expected on the PDF generated on the first server. The PDF generated on server 2 does not display that section at all.

I have uninstalled and reinstalled wkhtmltopdf on the second server, but it did not change the result. We did have an older version of the product installed on the two servers, but we upgraded to the latest version about a week and a half ago to correct the problem we're seeing on server 2, which worked great on my desktop installation and on server 1.

What could be causing the PDFs to render differently on two identical servers running the same version of wkhtmltopdf?

[server01_output.pdf](https://github.com/wkhtmltopdf/wkhtmltopdf/files/567006/server01_output.pdf)
[server02_output.pdf](https://github.com/wkhtmltopdf/wkhtmltopdf/files/567005/server02_output.pdf)
[Form.txt](https://github.com/wkhtmltopdf/wkhtmltopdf/files/567010/Form.txt)

**Comment by ablazko** [comment]
Hi there!

version: `wkhtmltox-0.13.0-alpha-7b36694_linux-trusty-amd64.deb`

I'm going through a similar issue too. Rendering the exactly same html file in my local computer (mac os) and my server (ubuntu 14.05) give me different result. In my case, the image (logo) do not print properly (printed with transparency degree - and there is no opacity level defined in html) and background colors of all html divs just don't show up. And so far this is the better I could get (when rendering from ubuntu).
Rendering from my mac os I got a perfect result (pdf is exactly the same as the html)!

I spent a lot of time to discover that in my ubuntu server was missing a lot of fonts (verdana, arial, avenir next, etc) that I use in html source file and this was causing me a lot of pain. After I installed these fonts all the bugs was solved, except these two I've mentioned above.

A third bug is that at the end of my pdf is being printed a 'runtime code'. I still don't know how to avoid this too.

Still looking for a solution for these matters. I'll be glad if someone could me point an direction.

[file-pdf-output.pdf](https://github.com/wkhtmltopdf/wkhtmltopdf/files/623195/file-pdf-output.pdf)
[file-html-source.txt](https://github.com/wkhtmltopdf/wkhtmltopdf/files/623196/file-html-source.txt)

**Comment by Romain** [comment]
Hi all,
I'm also facing the same issue.
I just reinstalled WKHTMLTOPDF on my server (Ubuntu 16.04) using `apt-get install wkhtmltopdf`
Any hint would be awesome.

**Comment by Romain** [comment]
I got it.
I manually installed WKHTMLTOPDF using the source files, and it fixed the problem.
I still have discrepencies with regards to the DPI / Zoom but I can deal with this, as long as I've got my styles in place...

**Comment by ablazko** [comment]
Hi @Romain,
Nice to hear that you found a way to solve your issues.
Would you write the steps or point any source about the steps (commands) do install wkhtmltopdf using the source files?

It happens that I'm noobie in linux commands. I don't even know where to start.

**Comment by ablazko** [comment]
Hi @Romain, thanks for your reply! Really appreciate!

But before I started to run these codes I'd like to say that I found a solution for my problem. This is what I did:

**1. The issue regarding the 'logo (.png)'**
**Solution:** just inserted an image attribute to the div tag around the image --> `opacity:0.95`.
This make the html to have a `class="figure"` attribute, and wkhtmltopdf now do recognize the .png properly.

**2. The issue regarding the 'background colors of div's'**
**Solution:** just inserted an `!important` tag after the background argument.
**Example:** `background-color:rgba(0,0,0,0.1) !important`
wkhtmltopdf now do recognize the background color properly.

**3. The issue regarding 'Date Vendor Contacted: 10/6/2016'**
**Solution:** just inserted an `--javascript-delay 1000` argument when calling wkhtmltopdf.
**Example:** `xvfb-run wkhtmltopdf --margin-top '5mm' --margin-bottom '5mm' --margin-left '5mm' --margin-right '5mm' --no-stop-slow-scripts --page-size A4 --javascript-delay 1000  file-html-source.html  file-pdf-output.pdf`
This argument forces the routine to wait 1 second till actually write the information into the document. That message then is not printed in the final pdf.

**Page Break stone**
One thing that could be helpful to others too and I'd like to share is how to define the exact point in the document that must have a **page break**, so you can have more control above the outcome.
This command line is indeed recognized by wkhtmltopdf:

`<div style="page-break-after: always;"></div>`

**Comment by Tomsgu** [comment]
I think this was resolved in `0.12.5` if I am not wrong. Can somebody try it with this version?

**Comment by Tomsgu** [comment]
Closing as there is no feedback. Please feel free to re-open the issue if the problem persists.
