### ISSUE TITLE
<thead> section on table overlapping <tbody> on second page.

### ISSUE THREAD

**Issue by jpmg90** [wkhtmltopdf/wkhtmltopdf#3194]
I'm using the Html to PDF to render some data within a table, When the table has enough rows to start a second page, the table header overlaps the table body rows. [I was able to prevent this by removing the <thead> tags, but I would like to be able to show the header on the second page without issues. 

![image](https://cloud.githubusercontent.com/assets/1234050/20111885/9e13fcb4-a5af-11e6-92a5-22ce8764cdc0.png)

I've tried other page sizes and several options was wasn't sure how to resolve this. When using a browser the Header prints fine on the second page.

**Comment by ashkulz** [comment]
Unfortunately, that's a known issue #1524.
