### ISSUE TITLE
Korean not showing but Japanese and Chinese are ok

### ISSUE THREAD

**Issue by kngatmdsol** [wkhtmltopdf/wkhtmltopdf#3200]
using Version 0.12.3.2 windows 64-bit on Windows 10 to convert the following simple html file to PDF but the Korean is blank.  Command: wkhtmltopdf.exe c:\temp\h4.html c:\temp\h4.pdf

Strangely the "Bleeding Edge" alpha version works.

<!DOCTYPE html>
<html>
<head>
<meta charset='UTF-8'/>
<body>
<p>
ENGLISH  日本語  한국어  简体中文
</p>
</body>
</html>

**Comment by alloylab** [comment]
is this still an issue on 0.12.5?
