### ISSUE TITLE
still maintained and actively developed?

### ISSUE THREAD

**Issue by DanielRuf** [wkhtmltopdf/wkhtmltopdf#3201]
@ashkulz Is wkhtmltopdf still actively developed and maintained at the moment?

The last commit was 6 months ago and there are many bugs in the latest releases.
Can anyone recommend a better alternative?

Unfortunately there are no more commits from collaborators / contributors with push rights.

**Comment by ashkulz** [comment]
Not really, I don't have time to devote to it recently. Nobody has stepped up with code contributions other than possibly @poizan42.

**Comment by poizan42** [comment]
Unfortunately I don't have much time to devote either, only what I'm doing for my employer. The version at https://github.com/cBrain-dk/wkhtmltopdf has been updated to use the newest qt webkit, but only supports Windows.

**Comment by Epskampie** [comment]
As an alternative tou might try phantomjs, or electron. Phantomjs is easiest, since electron cannot truly run in headless mode, but electron's webkit /chromium version is much newer, which means support for newer webstandards.

**Comment by DanielRuf** [comment]
Ok, thanks for the information. @poizan42 I will try your version.

**Comment by Sicos1977** [comment]
@poizan42 do you have a compiled static Windows version somewhere... it tried to find it in your GitHub repro but only found the source code. Otherwise I have to setup a complete Qt system to compile it myself.

**Comment by poizan42** [comment]
I have made a release here: https://github.com/poizan42/wkhtmltopdf/releases/tag/0.13-qt5.6-alpha1
I'll upload a 32-bit build as well once it's done building

**Comment by Sicos1977** [comment]
I don't hope it is to much to ask but could you make a small tutorial about how to setup Qt. Yesterday I tried to compile your code myself but I kept failing due to errors. I want to do some active development with wkHtmlToPdf.

**Comment by poizan42** [comment]
You shouldn't set any Qt up. But you need to have the following installed:

* Visual Studio 2015 (the community edition should do)
* Python 2
* Ruby
* Perl
* Cygwin with make installed
* NSIS

Then clone the git repository and init the submodules as well with `git submodule update --init --recursive`

Then you just have to run the build script in scripts/build.py:

    scripts/build.py msvc2015-win64

- or msvc2015-win32 if you want the 32-bit build. Note that creation of the NSIS installer package is disabled if you clone from my repository. If you want it you should edit the build.py script and replace `make_package = False` with `make_package = True`

**Comment by ashkulz** [comment]
FWIW `0.12.4` has been released and I'll be evaluating @poizan42's changes.

**Comment by Sicos1977** [comment]
Thanks :+1:

**Comment by poizan42** [comment]
@ashkulz do you want me to split my changes into a series of small pull requests? I think some of them might be a bit too experimental, such as https://github.com/cBrain-dk/qtwebkit-5-wk/commit/911b4683f6121a7eba866e873a6101c154e07551 - we only use wkhtmltopdf to convert emails and attached documents on emails and a few customer defined templates. Amongst other things this means that we don't use javascript, so we have never tested whether a change like that could cause problems with sites with javascript.

**Comment by ashkulz** [comment]
@poizan42: I'm currently rewriting the build system as it has grown too complicated and making a release is time-consuming. So any changes related to that will have to wait till I'm done in a few days :smile:

Where I'd really appreciate the help is to make self-contained changes which can be upstreamed in Qt. As I see it, there are only a few changes in qtbase:
1. headless support (mostly useful for Linux)
2. PDF enhancements (links, hyperlinks, outlines, forms, misc fixes)
3. image printing improvements
4. SVG enhancements

While I'm comfortable in trying to upstream 1 and 2, you'd be the best person to do 3 (and possibly 4, or we can drop it for now).

**Comment by ashkulz** [comment]
Please leave this issue closed and raise separate issues for whatever questions you have.

**Comment by DanielRuf** [comment]
@ashkulz Ok. Just thought it would be good to keep it open as there is an ongoing discussion about the forks and merge requests which should be normally a seperate issue but also affect the current status of the development.
