### ISSUE TITLE
convert html to pdf (img inside the html) (URL has no schema set, use file:// for files)

### ISSUE THREAD

**Issue by khaledwj90** [wkhtmltopdf/wkhtmltopdf#3203]
i got an error as below when i generate pdf using html with an image inside the html. 

"HTML file"
<h2>Logging Analysis</h2>
<img src="file:///C:\Users\xxxx\Desktop\xxxxxxxxxxx\20161120004353.png">
---------------------------------------

i got below error :
<jinja2.environment.Environment object at 0x07F67DD0>
Loading pages (1/6)
QNetworkAccessFileBackendFactory: URL has no schema set, use file:// for files
QNetworkAccessFileBackendFactory: URL has no schema set, use file:// for files
Counting pages (2/6)                                               
Resolving links (4/6)                                                       
Loading headers and footers (5/6)                                           
Printing pages (6/6)
Done

**Comment by alloylab** [comment]
is this still an issue on 0.12.5?
