### ISSUE TITLE
Blank PDF on both Windows 10 and Linux Centos 64bit OS

### ISSUE THREAD

**Issue by Jimbobnz** [wkhtmltopdf/wkhtmltopdf#3204]
wkhtmltopdf https://fonts.google.com/specimen/Inconsolata test.pdf

Version : 0.12.3.2 for windows and 0.12.3 for Linux
Expected to see somthing no errors.

> C:\Users\James\Documents>wkhtmltopdf https://fonts.google.com/specimen/Inconsolata text.pdf
Loading pages (1/6)
Counting pages (2/6)
Resolving links (4/6)
Loading headers and footers (5/6)
Printing pages (6/6)
Done

**Comment by Jimbobnz** [comment]
I think I've found a work around solution but it will do for now.
https://blog.shaharia.com/use-google-web-fonts-for-wkhtmltopdf-tools-to-convert-html-to-pdf/

Also I found specifiying fonts which exist on the OS.

To view the list of available fonts on linux use the following command 

> fc-list

**Comment by mikerockett** [comment]
It could be because the page is rendered with Angular and the font resources are not loaded in a standard way, making reference to the full URL of the font files in question... Just a thought.

**Comment by alloylab** [comment]
is this still an issue on 0.12.5?

**Comment by Tomsgu** [comment]
Closing as solution was provided.
