### ISSUE TITLE
generate PDF IOError

### ISSUE THREAD

**Issue by khaledwj90** [wkhtmltopdf/wkhtmltopdf#3205]
i'm trying to generate the pdf file and it's working on my computer but when i installed my software on another computer i got below error: 

IOError: wkhtmltopdf exited with non-zero code  -1073741515. error : 

whats that mean ??

**Comment by ashkulz** [comment]
Looks like you are using a wrapper, please report only if you get a problem from the command-line.

**Comment by dgoldb2** [comment]
> Looks like you are using a wrapper, please report only if you get a problem from the command-line.

Can you explain this "using a wrapper", please?  I am still causing wkhtmltopdf to crash from IDLE with a very simple example.

IOError: wkhtmltopdf exited with non-zero code -1073741515. error:

File "c:\program files (x86)\arcgis\desktop10.4\arcpy\pdfkit\api.py", line 72, in from_string
    return r.to_pdf(output_path)
