### ISSUE TITLE
Missing parts of MathJax LaTeX formulas in PDF

### ISSUE THREAD

**Issue by christianhueser** [wkhtmltopdf/wkhtmltopdf#3210]
First of all, thanks a lot for releasing a new wkhtmltopdf version v0.12.4. :+1: 

Regarding the versions v0.12.x of wkhtmltopdf LatTeX formulas rendered by MathJax v2.6.1 appear to be incomplete and missing parts of the formulas in generated PDF documents.

Please have a look onto the following screenshots:

![screenshot-incomplete-formulas-1](https://cloud.githubusercontent.com/assets/6921832/20562089/2c09a086-b182-11e6-8261-7b8cce99bb80.png)

![screenshot-incomplete-formulas-2](https://cloud.githubusercontent.com/assets/6921832/20562097/325f6cd6-b182-11e6-9bdb-dbf175291b9e.png)

This is possibly associated with the following issue: #2813

On the contrary, version v0.13-alpha is displaying LaTeX formulas correctly.

![screenshot-complete-formulas-1](https://cloud.githubusercontent.com/assets/6921832/20562469/126d2e16-b184-11e6-87c1-8edd10ae0bdc.png)

![screenshot-complete-formulas-2](https://cloud.githubusercontent.com/assets/6921832/20562481/18a9faf2-b184-11e6-83af-780e8c635c22.png)

Unfortunately, version v0.13-alpha does not support all command-line options which version v0.12.4 supports.

My set-up:
Operating System: Scientific Linux 7, Ubuntu 14.04 LTS
wkhtmltopdf: 0.12.1, 0.12.3.2, 0.12.4, 0.13-alpha
MathJax: 2.6.1

**Comment by ashkulz** [comment]
You'll have to wait for 0.13 as this is related to browser engine. What issues are you facing with 0.13?

**Comment by christianhueser** [comment]
Sorry, I was not very precise. Version 0.13-alpha is lacking support for command-line options like
--header-html
--footer-html
--no-header-line
--no-footer-line
--header-spacing
--footer-spacing
--no-pdf-compression

**Comment by ashkulz** [comment]
Okay, so it'll work with 0.13. No fixed plans for it as yet, although I'm planning to evaluate [changes made by @poizan42](https://github.com/poizan42/wkhtmltopdf/releases/tag/0.13-qt5.6-alpha1) for merging (Windows-only, as that's what he required).

**Comment by christianhueser** [comment]
Dear @ashkulz,

unfortunately, I stumbled upon another PDF with MathJax (v2.7.0) LaTeX formulas which are incomplete and are lacking parts of the formulas, respectively. This time it is generated by version v0.13-alpha on a linux machine. 

This is a screenshot of what is there in the PDF document:
![screenshot-mathjax-broken](https://cloud.githubusercontent.com/assets/6921832/21589231/03b1513c-d0f0-11e6-9422-6c1bb7195085.png)

But actually it should look like this:
![screenshot-mathjax-complete](https://cloud.githubusercontent.com/assets/6921832/21589660/6b543c6a-d0f4-11e6-865c-f0fe0add31a7.png)

Thus, the issue seems not to be fixed in v0.13-alpha for linux yet, while this issue has also been observed in older v0.12.x releases for linux.

Is there any workaround known to avoid this? Thanks in advance.

**Comment by christianhueser** [comment]
Alright, I managed to find the reason for the broken MathJax formulas. I added the following MathJax configurations to the HTML processed by wkhtmltopdf:

```
<script type="text/x-mathjax-config">
    MathJax.Hub.Config({
        ...
        "HTML-CSS": {
            ...
            webFont: null
            ...
        }
        ...
    });
</script>
```

After removing these MathJax configurations or selecting a particular font as web-font the formulas are displayed as expected. 

Hence, this is not an issue of wkhtmltopdf but a misconfiguration of MathJax. I also verified that this is a non-issue even for version v0.12.4. I am very sorry to have brought up this issue.

**Comment by christianhueser** [comment]
Dear @ashkulz ,

I would like to revisit the topic covered by this issue and previous comments and kindly ask you to share your opinion about how I would like to circumvent the problem of missing command-line options for header and footer html.

Instead of going completely without headers and footers I was thinking of removing the margins and provide header and footer html as part of the body of the document. Clearly, one has to know when a page-break occurs, so that in this case a header and footer can be inserted into the html.

My first thought was to use some sort of callback function which may already exist in the software for inserting header and footer html. Could you please point me to the right position in the source code where this page-break and header and footer insertion happens? In that case I could extend the functionality without enabling the respective command line options. But agreed this would most probably lead to a very fragile implementation, so enabling header and footer html command line options seems to be a better solution.

In case I would go for (1) enabling the header and footer html command line options for v0.13-alpha by myself or (2) using some sort of callback function I mentioned above to implement my own header / footer mechanism, what do you think would be the necessary steps to do so?

If by any chance you can make a vague prediction when version v0.13 stable will be released, I could make a better decision whether it's worth developing my own version or waiting until the next stable version.

Thank you very much in advance for any contribution to this issue.
