### ISSUE TITLE
Unable to convert Javascript plot

### ISSUE THREAD

**Issue by nathanielatom** [wkhtmltopdf/wkhtmltopdf#3211]
I'm trying to convert a javascript plot:
http://bokeh.pydata.org/en/latest/docs/gallery/image_rgba.html

Since there's a slight delay before the plot shows up when loading with Chrome, I thought it might be a javascript timeout causing the problem, but the plot portion still does not get rendered using:
`wkhtmltopdf --no-stop-slow-scripts --javascript-delay 3000 http://bokeh.pydata.org/en/latest/docs/gallery/image_rgba.html out.pdf`

**Comment by ashkulz** [comment]
Try increasing the `--javascript-delay` to around `45000` and see if it works. Experiment till you find a value which works.

**Comment by nathanielatom** [comment]
I tried it with a delay of `300000` and it still didn't load the plot. The delay for the plot to load in chrome is < 1 second.

**Comment by ashkulz** [comment]
Can you try it with `0.13` and see if it gets rendered?

**Comment by nathanielatom** [comment]
Are there any `0.13` builds yet for OS X? I couldn't find any. I also tried building from source, and ran into #3218

**Comment by nathanielatom** [comment]
I was able to try out `0.13` on a windows computer (using the mingw version) and I'm happy to say `wkhtmltopdf --no-stop-slow-scripts --javascript-delay 3000 http://bokeh.pydata.org/en/latest/docs/gallery/image_rgba.html out.pdf` now works :D
