### ISSUE TITLE
Issues while extracting  text from pdf.

### ISSUE THREAD

**Issue by Manoj51** [wkhtmltopdf/wkhtmltopdf#3212]
I have generated a pdf in Devanagari script from HTML. However, i am facing issues while copying the text from pdf file. 

First line from the sample pdf :  
वे ब चे कूल नह जाते थे। पूरा दन मैदान म घूमते थे।

[sample.pdf](https://github.com/wkhtmltopdf/wkhtmltopdf/files/611265/sample.pdf)

If you observe the pdf, many variations are lost while copying.

What might be the problem here?.

**Comment by ashkulz** [comment]
Did you generate it wkhtmltopdf? It doesn't look like it. On the other hand, it looks like font-embedding is being done incorrectly for the font -- characters which can't be embedded are rendered as graphics and show properly but can't be copied (if you notice, it is the joined letters which disappear).

**Comment by Manoj51** [comment]
I use wicked_pdf which generates pdf from wkhmtltopdf. As you identified correctly, the problem comes with joined letters. I researched a bit and found out that there has to be inbuilt information(tounicode map) to get back the exact text. I was wondering if wkhtmltopdf can be used to include 'tounicode' map .

**Comment by ashkulz** [comment]
@Manoj51: please post the source HTML/CSS, as your PDF shows it is being created by "cairo 1.13.1 (http://cairographics.org)".

**Comment by Manoj51** [comment]
Sorry for the mixup. For showing a sample page, I used another software to extract only one page from the original pdf. Here is the original pdf generated from the wkhtmltopdf : 
[FullSample.pdf](https://github.com/wkhtmltopdf/wkhtmltopdf/files/615603/FullSample.pdf)

The first sample is 3rd page from this FullSample.
