### ISSUE TITLE
Falied to convert if html has two DOM element  which one has font-family property but other is not

### ISSUE THREAD

**Issue by woosungchu** [wkhtmltopdf/wkhtmltopdf#3214]
I have used wkhtmltopdf very long time with no any problem.
But user reported converting pdf is not working in specific font named '궁서' 

Most of browser  support this popular font and printed well in webserver page.
The process is when httpRequest has been sent Webserver run wkhtmltopdf and return converted pdf.
like this...
  C:/Program Files/wkhtmltopdf/bin/wkhtmltopdf.exe --load-error-handling ignore --load-media-error-handling ignore --javascript-delay 1000 "http://mysite.com/request.do?index=100000509930" C:/testfile.pdf

I have tested with clean html like number two in the picture and it return well. 
but the html include '궁서' font rendered by Webserver is not working

version is '0.12.4' 

-------------------------------------------------------------------
I think I found what is the main problem..

look picture below...

![pdfissue3](https://cloud.githubusercontent.com/assets/13829340/20617230/1f60e998-b32b-11e6-8ef1-8a788babab68.PNG)
![pdfissue2](https://cloud.githubusercontent.com/assets/13829340/20617231/1f623852-b32b-11e6-8744-f79554530925.PNG)

**Comment by woosungchu** [comment]
The error was broken font name in css file..... 

If you have same error like mine, check your font-family attribute in css file .

**Comment by woosungchu** [comment]
I think if you don't have default or wrong font-family like above you may stuck on this kind of error

**Comment by woosungchu** [comment]
I spend a lot of time to figure out this fundamental problem and hope to share this process to other stuck on this kind of problem

Situation
- I have three 'A B C' Window server with their each different font problem when they use wkhtmltopdf.
- However, all A,B,C  server show fonts well in all rendered web page  (browser - IE, Chrome)
Process
1. '궁서' font is broken in pdf file when use wkhtmltopdf in server A
2. I fixed broken font-name in css file like above and it works ! but ...
3.  '궁서' font is broken in pdf file when web page have '굴림' font in server A
4.  And '궁서' font is broken again in server B even I fixed broken css file!
5. A,B server have same source code, but they show different error
6. As this situation, I think this error has relevant with font **file** of Window and both window has different font file.
7. I use **@font-face** as other issue saying...

`@font-face {
  font-family: '궁서';
  src: url(../fonts/koreanFont/UnGungseo.ttf);
  src: url(../fonts/koreanFont/UnGungseo.eot?#iefix) format('embedded-opentype'),
       url(../fonts/koreanFont/UnGungseo.woff2) format('woff2'),
       url(../fonts/koreanFont/UnGungseo.woff) format('woff'),
       url(../fonts/koreanFont/UnGungseo.ttf) format('truetype');	  
  font-style: 궁서;
  font-weight: 400;
}
@font-face {
  font-family: '궁서체';
  src: url(../fonts/koreanFont/UnGungseo.ttf);
  src: url(../fonts/koreanFont/UnGungseo.eot?#iefix) format('embedded-opentype'),
       url(../fonts/koreanFont/UnGungseo.woff2) format('woff2'),
       url(../fonts/koreanFont/UnGungseo.woff) format('woff'),
       url(../fonts/koreanFont/UnGungseo.ttf) format('truetype');	  
  font-style: 궁서체;
  font-weight: 400;
}`

however, server A keeps not working... 

**why? you should add all fonts file that rendered web page have!
If your os doesn't have any single of font that web page has, other font would be broken!!!!!!!
**

`@font-face {
  font-family: '굴림';
  src: url(../fonts/koreanFont/Gulim.ttf);       
  font-style: 굴림;
}
@font-face {
  font-family: '굴림체';
  src: url(../fonts/koreanFont/GulimChe.ttf);       
  font-style: 굴림체;
}
@font-face {
  font-family: '돋움';
  src: url(../fonts/koreanFont/Dotum.ttf);       
  font-style: 돋움;
}
@font-face {
  font-family: '돋움체';
  src: url(../fonts/koreanFont/DotumChe.ttf);       
  font-style: 돋움체;
}`

and it goes well...


Conclusion.
if you have font error, you should see whether your OS(operating system) have all of various font that document has or not what you want to convert, if there is even one font is empty, other font would be broken. 
As browsers such as IE, chrome and others may support default fonts like '궁서','바탕','굴림','돋움', HTML pages what your server render would show fonts well . That's why your pages show font well but converted pdf didn't

--I don't have long experience enough to make sure this long opinion 100% but hope to help other if it may helpful

**Comment by woosungchu** [comment]
@ashkulz  
I am sorry to bother you. Never and No offence against your Invalid label :)
If you don't mind I just want to get confirmed whether I am looking this problem in right direction and solved fine or not. 

Thank you very much about maintaining this awesome open source!

**Comment by ashkulz** [comment]
I just marked it as Invalid because you closed the issue with a solution .. I don't really have a clue about such fonts, as I can't read that language...
