### ISSUE TITLE
Problem with no proxy

### ISSUE THREAD

**Issue by denics** [wkhtmltopdf/wkhtmltopdf#3216]
Dear all, I am having a problem with a specific configuration where I should specify the no_proxy variable. is it possible? At the moment I can do:

```./wkhtmltopdf --proxy http://myproxy.com:8080 www.google.com test.pdf```

and it works fine, but 

```./wkhtmltopdf --proxy http://myproxy.com:8080 www.mycompany.com test.pdf```

will fail.

**Comment by ashkulz** [comment]
I think you are looking for `--bypass-proxy-for` option, e.g. `--bypass-proxy-for www.mycompany.com`.

**Comment by ashkulz** [comment]
This was added by @elerch in #2355 and released in `0.12.3`.
