### ISSUE TITLE
0.13.0-alpha Build from Source Fails on OS X 10.12

### ISSUE THREAD

**Issue by nathanielatom** [wkhtmltopdf/wkhtmltopdf#3218]
Following the build instructions for the `0.13` branch results in a Python build error: 

```
...
Making install in tests
make[3]: Nothing to be done for `install-exec-am'.
make[3]: Nothing to be done for `install-data-am'.
make[3]: Nothing to be done for `install-exec-am'.
 /usr/local/bin/gmkdir -p '/Users/Atom/wkhtmltopdf/static-build/osx-cocoa-x86-64/deplibs/share/doc/xz'
 /usr/bin/install -c -m 644 AUTHORS COPYING COPYING.GPLv2 NEWS README THANKS TODO doc/faq.txt doc/history.txt doc/xz-file-format.txt doc/lzma-file-format.txt '/Users/Atom/wkhtmltopdf/static-build/osx-cocoa-x86-64/deplibs/share/doc/xz'
 /usr/local/bin/gmkdir -p '/Users/Atom/wkhtmltopdf/static-build/osx-cocoa-x86-64/deplibs/share/doc/xz/examples'
 /usr/bin/install -c -m 644 doc/examples/00_README.txt doc/examples/01_compress_easy.c doc/examples/02_decompress.c doc/examples/03_compress_custom.c doc/examples/04_compress_easy_mt.c doc/examples/Makefile '/Users/Atom/wkhtmltopdf/static-build/osx-cocoa-x86-64/deplibs/share/doc/xz/examples'
 /usr/local/bin/gmkdir -p '/Users/Atom/wkhtmltopdf/static-build/osx-cocoa-x86-64/deplibs/share/doc/xz/examples_old'
 /usr/bin/install -c -m 644 doc/examples_old/xz_pipe_comp.c doc/examples_old/xz_pipe_decomp.c '/Users/Atom/wkhtmltopdf/static-build/osx-cocoa-x86-64/deplibs/share/doc/xz/examples_old'
Traceback (most recent call last):
  File "scripts/build.py", line 1320, in <module>
    main()
  File "scripts/build.py", line 1317, in main
    globals()['build_%s' % BUILDERS[config]](final_config, basedir)
  File "scripts/build.py", line 1209, in build_osx
    build_qt(get_dir('qt'), 'make -j%d' % CPU_COUNT, '../../../qt/configure %s' % configure_args)
NameError: global name 'build_qt' is not defined
```

**Comment by nathanielatom** [comment]
I haven't tested, but it looks like `build_posix_local` would have the same problem

**Comment by ashkulz** [comment]
It hasn't been adapted yet, as I don't have a Mac.

**Comment by inferiorhumanorgans** [comment]
Correct, the "local POSIX" build doesn't work either.  Replacing build_qt with the relevant build_qtmodule invocations appears to be a good start.  Also:

* With Qt5 there's no more carbon build, so configure will balk on `-carbon` and `-cocoa` being passed (`-no-dwarf2` also went away)
* Qt5 doesn't build on OSX with `-no-accessibility`
* Also needed are: `-no-evdev` and `-no-pulseaudio`
* I added /usr/local/{lib,include} to the seach paths for ICU (this should be pulled in by the build script instead
* I needed to remove `-xrender`, but there may be better ways around this.

IMO it would be good to test even just the generic POSIX stuff (as this would help other platforms, like *BSD).

Current stopping point is:

```
Encountered 3 configuration warning(s):

 ! QtQuick module not found, QML APIs will not be built
 ! Missing GStreamer or QtMultimedia, disabling HTML5 media element support
 ! QtWebKitQml will not be build. It is not supported with static linking

The WebKit build was disabled for the following reasons: 
    * QtWebKit cannot be built as a static library on this platform. Check your configuration in qtbase/config.summary. 

```

**Comment by ashkulz** [comment]
@inferiorhumanorgans: do you have a patch where you can share the work-in-progress? I don't have a Mac, so any progress on that front would be great :+1:

**Comment by inferiorhumanorgans** [comment]
No patch yet because it doesn't even come close to building.  Is e03f1d19f0543546fde2bbbb587e3b8c012a4cbb the proper version to be working from?

**Comment by inferiorhumanorgans** [comment]
Update: I've moved on to writting a thin wrapper around webkitgtk.  We'll see how it goes, but it's much easier to find prepackaged binaries for this library on OSX and FreeBSD.

**Comment by ashkulz** [comment]
@inferiorhumanorgans: good luck :+1:

**Comment by inferiorhumanorgans** [comment]
As it turns out a current version of webkit2gtk is available from MacPorts, but it also builds quite easily by hand (on Mavericks it just needs clang 3.8).

**Comment by nathanielatom** [comment]
Has there been any progress on this / at what point is the build at currently? I don't know a ton about Qt but I could try to build (and debug) the latest code if pointed in the right direction.

**Comment by ashkulz** [comment]
Nope, not much progress has been made.
