### ISSUE TITLE
0.12.3, error: 'SSLv3_server_method' was not declared in this scope

### ISSUE THREAD

**Issue by alloylab** [wkhtmltopdf/wkhtmltopdf#3219]
Has anyone experienced this issue when trying to compile 0.12.3?

In file included from ssl/qsslsocket_openssl_symbols.cpp:47:0:
ssl/qsslsocket_openssl_symbols.cpp: In function 'const SSL_METHOD* q_SSLv3_client_method()':
ssl/qsslsocket_openssl_symbols_p.h:169:39: error: 'SSLv3_client_method' was not declared in this scope
     ret q_##func(arg) { funcret func(a); }
                                       ^
ssl/qsslsocket_openssl_symbols.cpp:231:1: note: in expansion of macro 'DEFINEFUNC'
 DEFINEFUNC(const SSL_METHOD *, SSLv3_client_method, DUMMYARG, DUMMYARG, return 0, return)
 ^~~~~~~~~~
ssl/qsslsocket_openssl_symbols.cpp: In function 'const SSL_METHOD* q_SSLv3_server_method()':
ssl/qsslsocket_openssl_symbols_p.h:169:39: error: 'SSLv3_server_method' was not declared in this scope
     ret q_##func(arg) { funcret func(a); }
                                       ^
ssl/qsslsocket_openssl_symbols.cpp:237:1: note: in expansion of macro 'DEFINEFUNC'
 DEFINEFUNC(const SSL_METHOD *, SSLv3_server_method, DUMMYARG, DUMMYARG, return 0, return)
 ^~~~~~~~~~
make[1]: *** [Makefile:18077: .obj/release-static/qsslsocket_openssl_symbols.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [Makefile:272: sub-network-make_default-ordered] Error 2

**Comment by ashkulz** [comment]
How did you try to compile this? On which platform? Without such information, any issue cannot be addressed. Also note that the current release is `0.12.4` and previous releases are not supported.

**Comment by alloylab** [comment]
It was a typo, meant 0.12.4

**Comment by alloylab** [comment]
I am trying to compile wkhtmltopdf with patched qt on Alpine Linux 3.4

**Comment by ashkulz** [comment]
Did the generic linux binaries not work for you? How were you trying to compile it? Please post the exact command-lines you used and the full compilation log.
