### ISSUE TITLE
PNG images and div background colors not printed properly

### ISSUE THREAD

**Issue by ablazko** [wkhtmltopdf/wkhtmltopdf#3223]
Hi,

version: `wkhtmltox-0.13.0-alpha-7b36694_linux-trusty-amd64.deb`

When rendering the html source file (see attached) in my server (`ubuntu 14.05`) I got different results in the output (also attached). But if I render the exactly same html source file in my local computer (`mac os x86_64-apple-darwin13.4.0`) the output result if perfect (pdf output exactly as the html), except about the logo image!

You'll see differences between HTML and PDF versions in the IMAGE (upper left corner) and all the titles backgrounds (supposed to be light gray).

Also, at the end of the pdf you'll notice a 'runtime message code' that is not supposed to be there too!

Hopefully someone can figure it out what's is going on!

[file-pdf-output-macos.pdf](https://github.com/wkhtmltopdf/wkhtmltopdf/files/623236/file-pdf-output-macos.pdf)
[file-pdf-output-ubuntu.pdf](https://github.com/wkhtmltopdf/wkhtmltopdf/files/623237/file-pdf-output-ubuntu.pdf)
[file-html-source.txt](https://github.com/wkhtmltopdf/wkhtmltopdf/files/623215/file-html-source.txt)

**Comment by alloylab** [comment]
have you tried v0.12.5?

**Comment by alloylab** [comment]
We are closing this out since we haven't heard from you. If you are still having this issue please feel free to re-open it. Thanks.
