### ISSUE TITLE
SVG content is not handled through JavaScript

### ISSUE THREAD

**Issue by remigarcia** [wkhtmltopdf/wkhtmltopdf#3224]
Hi,

I'm facing a problem with SVG included in an HTML page.
Here's the example :
```html
<!DOCTYPE html>
<html>
<head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"></head>
<body>
    <svg id="svg-tag" xmlns="http://www.w3.org/2000/svg" width="100px" height="50px">
        <text x="10" y="20">SVG Text Example</text>
    </svg>

    <script>
    	(function() {
            console.log(document.getElementById('svg-tag').innerHTML);
	})();
    </script>
</body>
</html>
```

On any browser, the console outputs the svg content.
When trying to convert the html page to pdf through wkhtmltopdf with this command : 
`wkhtmltopdf-amd64 --enable-javascript --javascript-delay '1000' --debug-javascript 'test.html' 'test.pdf'`
I got this output :

> Loading pages (1/6)
Warning: file:///home/remigarcia/wkhtmltopdf-test/test.html:10 undefined
Counting pages (2/6)                                               
Resolving links (4/6)                                                       
Loading headers and footers (5/6)                                           
Printing pages (6/6)
Done

That make the SVG not handleable through pure JavaScript or libraries like jQuery or Snap.svg.
Did I pass next to something usefull in the doc ? Or is this a wkhtmltopdf issue ?

Environment : wkhtmltopdf-amd64 (0.12.3 or 0.12.4) on Ubuntu 16.04.

Thanks

**Comment by alloylab** [comment]
is this still an issue on 0.12.5?

**Comment by alloylab** [comment]
We are closing this out since we haven't heard from you. If you are still having this issue please feel free to re-open it. Thanks.
