### ISSUE TITLE
Special characters like smiley and others are appearing when using in exec() in php

### ISSUE THREAD

**Issue by abhishekno1** [wkhtmltopdf/wkhtmltopdf#3225]
When i create pdf using wkhtmltopdf in command everything works fine but when i do same thing in php using exec() and shell_exec() command it is not working as it should be

![s1](https://cloud.githubusercontent.com/assets/22130423/20826482/3bf2e4c4-b891-11e6-8920-465aa6283fac.PNG)

Please check!

**Comment by alloylab** [comment]
We are closing this out since we haven't heard from you. If you are still having this issue please feel free to re-open it. Thanks.
