### ISSUE TITLE
Installation failed Windows 10-64

### ISSUE THREAD

**Issue by kklepper** [wkhtmltopdf/wkhtmltopdf#3228]
### This is my system:

![wkhtmltox3](https://cloud.githubusercontent.com/assets/6130319/20849971/5c8b2f32-b8d9-11e6-8125-bcaa3e6b11ee.PNG)

### This is the download:

![wkhtmltox2](https://cloud.githubusercontent.com/assets/6130319/20850001/8b356d3e-b8d9-11e6-932b-d71120bf2bff.PNG)

### This is one of many error messages:

![wkhtmltox](https://cloud.githubusercontent.com/assets/6130319/20850015/95feca26-b8d9-11e6-9ede-f5f45966744a.PNG)

### This is the result - empty directory:

![wkhtmltox1](https://cloud.githubusercontent.com/assets/6130319/20850020/97a9df82-b8d9-11e6-8eda-71fb350624a2.PNG)

### What am I going to do?

**Comment by kklepper** [comment]
It does not help to install anywhere else - same symptoms. So it is not a problem of rights (which is obvious because installation is done as administrator).

**Comment by kklepper** [comment]
It does not help to install anywhere else - same symptoms. So it is not a problem of rights (which is obvious because installation is done as administrator).

**Comment by kklepper** [comment]
## Same with wkhtmltox-0.12.4_msvc2015-win32.exe and different drive:
### First default:
![wkhtmltox32](https://cloud.githubusercontent.com/assets/6130319/20853240/027e940e-b8eb-11e6-8d37-f19e78380d1c.PNG)

### Progress log:

![wkhtmltox32-1](https://cloud.githubusercontent.com/assets/6130319/20853244/063a5178-b8eb-11e6-8703-72ba88e8d35c.PNG)

### Same with second partition:

![wkhtmltox32-3](https://cloud.githubusercontent.com/assets/6130319/20853247/08c28172-b8eb-11e6-9afa-dd63ff2af15d.PNG)

### Progress log:

![wkhtmltox32-4](https://cloud.githubusercontent.com/assets/6130319/20853249/0a3b01b4-b8eb-11e6-9038-c67885bf457a.PNG)

Needless to say that there is no reason for not being able to write.

**Comment by Tomsgu** [comment]
@kklepper Is this still an issue in 0.12.5 version?

**Comment by kklepper** [comment]
Thank you very much for the reminder! Works like a breeze. Great!
