### ISSUE TITLE
Automatic chapter numbering for headings <h?>

### ISSUE THREAD

**Issue by mema-github** [wkhtmltopdf/wkhtmltopdf#3231]
Currently I use the xsl stylesheet option to automatically add chapter numbers to a certain level of headings. These show up in the toc and in front of the headings on the content pages. However, these do not appear in the outline/bookmarks (e.g. bookmarks sidebar of Adobe reader).
It would be great if either an option for chapter numbering could be implemented or the outline could be modified to also use the added numbers from the xsl stylesheet.

**Comment by alloylab** [comment]
is this still an issue on 0.12.5?

**Comment by alloylab** [comment]
We are closing this out since we haven't heard from you. If you are still having this issue please feel free to re-open it. Thanks.
