### ISSUE TITLE
HTML form not  converted to PDF form

### ISSUE THREAD

**Issue by chinoygupta** [wkhtmltopdf/wkhtmltopdf#3232]
I have an input HTML which contains a simple form which has an input field. I am using wkhtmltopdf from commandline with the "--enable-forms" option. For a simple text field, it is converted to editable fields in PDF. But if I add any border related style elements to the input field, the generated PDF doesnot have any editable fields. wkhtmltopdf version is 0.12.4 and I am running it on Wiindows 7 64 bit.

`Enter Text: <input type="text" name="t1" id="t1" style="border: none"/><br />`

**Comment by alloylab** [comment]
is this still an issue on 0.12.5?

**Comment by DunhamGitHub** [comment]
Still an issue
