### ISSUE TITLE
--page-size specified in incorrect location

### ISSUE THREAD

**Issue by abhijayghildyal** [wkhtmltopdf/wkhtmltopdf#3234]
This is a part of my shell script, where ${1} is 'input.html' and ${2} is 'output.pdf':

    wkhtmltopdf "${1}" "${2}" --page-size letter --dpi 150 --margin-top 0.2in --margin-bottom 0.2in --margin-left 0.2in --margin-right 0.2in

When I ran the above, I got the following error:

    --page-size specified in incorrect location

version:  wkhtmltopdf 0.12.0 final

**Comment by PhilterPaper** [comment]
It wants command-line arguments in a specific order. Just run "wkhtmltopdf" by itself to get a help summary. Basically, you'll want to move the input **"${1}"** and output **"${2}"** to the end.

**Comment by abhijayghildyal** [comment]
Thanks. When I had updated to 0.12.0 it had stopped working. This works in the following manner now:

    wkhtmltopdf --page-size letter --dpi 150 --margin-top 0.2in --margin-bottom 0.2in --margin-left 0.2in --margin-right 0.2in "${1}" "${2}"
