### ISSUE TITLE
Missing background image when invoked with stdin

### ISSUE THREAD

**Issue by paulrosen** [wkhtmltopdf/wkhtmltopdf#3235]
I am trying to figure out the difference between these two commands:

This prints the background image correctly:
```
/usr/local/bin/wkhtmltopdf --page-size letter --print-media-type 
    --footer-left All\ rights\ reserved.\ Page\ \[page\]\ of\ \[toPage\] 
    --footer-font-size 7 --header-font-size 7 --margin-bottom 20 --margin-top 20 
    --margin-left 15 --margin-right 15 --footer-spacing 10 --header-spacing 5 
    --header-right Prepared\ for\ Testing https://myserver.com/testing.html testing.pdf
```

This prints a nearly identical PDF except it doesn't have the background image:
```
/usr/local/bin/wkhtmltopdf --page-size letter --print-media-type 
    --footer-left All\ rights\ reserved.\ Page\ \[page\]\ of\ \[toPage\] 
    --footer-font-size 7 --header-font-size 7 --margin-bottom 20 --margin-top 20 
    --margin-left 15 --margin-right 15 --footer-spacing 10 --header-spacing 5 
    --header-right Prepared\ for\ Testing - -
```
(I captured the data that would be sent to stdin in the first example and saved it to testing.html - so wkhtmltopdf is getting the same data either way, it is just being delivered differently.)

(Context: the first command is executed by me on the command line of my server. The second command is generated by PDFkit's middleware and is on a Rails application.)

Thanks.

**Comment by ashkulz** [comment]
If the background-image is being referenced via a relative path, then it is unlikely to work in the second case -- there is no base URL.

**Comment by paulrosen** [comment]
No, it's an absolute path. I inlined the following on my page just to be sure. (Note that I see the correct output when looking at the original page in a browser and clicking "print".)

```
<style>
    @media print {
        .main-content {
            background: url(https://myserver.com/assets/myimage-00000.png) repeat-y !important;
        }
    }
</style>
```
