### ISSUE TITLE
build debian package for 0.12.4 on xenial64

### ISSUE THREAD

**Issue by steenzout** [wkhtmltopdf/wkhtmltopdf#3237]
Hello,

  I'm trying to build the debian package for Ubuntu 16.04 for an old version 0.12.4.

  these are the commands I used:

```
$ sudo scripts/build.py setup-schroot-generic
$ ./scripts/build.py linux-generic-amd64
```

  I managed to setup the chroot environment without any problems and the build also works except
I can't find the debian package anywhere.
  I did the exact same steps for Ubuntu 14.04 and I got the same result: no debian package.

  am I missing a step?

cheers

**Comment by steenzout** [comment]
looking at the git history it seems package building was removed.

if I contributed with #3209 do you think we could have the .package files being provided for each release?

**Comment by ashkulz** [comment]
Yes, let's continue the conversation there. I removed package building was because of a few reasons (it's even in the download FAQ):
1. It was becoming difficult to manage; creating a chroot environment, updating/testing it became too much effort for a single release
2. Generic linux build looked like it was working on most distributions (but see #3001)
3. I didn't have a good internet connection...

**Comment by steenzout** [comment]
@ashkulz as a note when the build finishes on `xenial`, if I execute the binary I get:

```
$ wkhtmltopdf --version
wkhtmltopdf: error while loading shared libraries: libXrender.so.1: cannot open shared object file: No such file or directory
```

```
$ locate libXrender.so
/var/chroot/wkhtmltox-generic-amd64/usr/lib64/libXrender.so
/var/chroot/wkhtmltox-generic-amd64/usr/lib64/libXrender.so.1
/var/chroot/wkhtmltox-generic-amd64/usr/lib64/libXrender.so.1.3.0
/var/chroot/wkhtmltox-generic-i386/usr/lib/libXrender.so
/var/chroot/wkhtmltox-generic-i386/usr/lib/libXrender.so.1
/var/chroot/wkhtmltox-generic-i386/usr/lib/libXrender.so.1.3.0
```

I don't really understand why `chroot` has a `i368` setup since my vbox is a `x86_64` but
that shouldn't be the issue.

if I install these apt packages the build worked:
- build-essential
- libssl-dev
- openssl
- xorg

could you please confirm I need to install the above apt packages to be able to successfully build the software?

**Comment by steenzout** [comment]
ok, I just need to have the `xorg` package installed?

**Comment by ashkulz** [comment]
Yep. Look at the git history (runtime_packages in the build script)

**Comment by ashkulz** [comment]
specifically 45290e2ccb710f41aac2c75cd0252347fec629cf. Are you working on the vagrant branch?

**Comment by steenzout** [comment]
@ashkulz I'll start this weekend.

**Comment by ashkulz** [comment]
Thanks, I've pushed a few updates. The provisioning should be OK, build script needs work...

**Comment by steenzout** [comment]
@ashkulz for most of the environments (linux and mac) this would be much easier to setup using ansible than with bash scripts.
