### ISSUE TITLE
Unexplained table cell spacing for a table spanning multiple pages

### ISSUE THREAD

**Issue by miqid** [wkhtmltopdf/wkhtmltopdf#3243]
Hello there,

I've been trying to debug some unexplained occurrences of white space that manifest themselves within table cells.

Below are links to a sample HTML file passed to wkhtmltopdf and the resulting output:

```bash
wkhtmltopdf sample.html sample.pdf
```

[sample.html](https://gist.github.com/miqid/73a3c10ff1200b7ceb216b7ae9cac080) | [sample.pdf](https://github.com/wkhtmltopdf/wkhtmltopdf/files/641380/sample.pdf)

I've styled the HTML file to highlight the unexplained white space in yellow. One particularly strange observation is how the white space is variable in height.

My original use case for wkhtmltopdf is through [jsreport](https://github.com/jsreport/jsreport) as the choice of rendering engine. I eventually ruled out jsreport as being a culprit in causing the white space problem because undesirable results were still being produced even when executing the wkhtmltopdf executable (0.12.4, 64-bit, Windows 10) directly. The template I've linked here and the one I actually used in testing with jsreport are slightly different (i.e. removed jsrender templating syntax which I was using to repeat table rows).

Could anybody please shed some light onto why white space with variable heights are being randomly inserted into large tables?

**Comment by alloylab** [comment]
is this still an issue on 0.12.5?

**Comment by miqid** [comment]
@alloylab, I ran my original example through version 0.12.5 and the problem still exists. I've attached the output I'm getting below:

[sample.pdf](https://github.com/wkhtmltopdf/wkhtmltopdf/files/2130331/sample.pdf)

**Comment by Tomsgu** [comment]
The problem seems to be somewhere with a normalize css code. When I delete them everything works fine. You can try to test what element is responsible for this behaviour.

**Comment by Tomsgu** [comment]
The problem seems to be:
```css
body {
    margin: 0
}
```
