### ISSUE TITLE
signatures/hashes for binaries?

### ISSUE THREAD

**Issue by rosenmoore** [wkhtmltopdf/wkhtmltopdf#3246]
We're looking to deploy wkhtmltopdf, but we would like to trust that the compiled binaries are really from your project.  As it is, the 3rd party site that hosts the binaries (gna.org) doesn't support HTTPS.  It would be nice to verify the authenticity of the binaries.  Perhaps one of the following options will work for you?

 * Uploading the hashes to Github (which we can download over HTTPS and verify against the binary)
 * Signing the downloads with GPG and upload your public key to the github page

**Comment by ashkulz** [comment]
Yeah, although the checksums are hosted at gna.org they aren't signed. I'll look into signing them via GPG for future releases.

**Comment by ashkulz** [comment]
I've added the SHA256 checksums on the [release page](https://github.com/wkhtmltopdf/wkhtmltopdf/releases/tag/0.12.4) for now.

**Comment by rosenmoore** [comment]
Fantastic!  Thanks!

**Comment by ashkulz** [comment]
Packages for 0.12.5 [are available](https://wkhtmltopdf.org/downloads.html#stable) using signed checksums.
