### ISSUE TITLE
Missing fonts in Ubuntu 14

### ISSUE THREAD

**Issue by EcoFreak** [wkhtmltopdf/wkhtmltopdf#3248]
In Win10 i'm getting all fonts correctly added to the pdf, like so:

![image](https://cloud.githubusercontent.com/assets/3418386/21181687/fe9b8f26-c1f6-11e6-8978-f7b2c1c7ff1f.png)
![image](https://cloud.githubusercontent.com/assets/3418386/21181691/04277388-c1f7-11e6-9f51-3bbf6b5d7ced.png)

But in Ubuntu 14, not so much:

![image](https://cloud.githubusercontent.com/assets/3418386/21181698/121ff1ea-c1f7-11e6-9749-d07abb84575e.png)

![image](https://cloud.githubusercontent.com/assets/3418386/21181704/17b45e70-c1f7-11e6-8612-bad7025b4cea.png)

Any ideas on how to fix the problem?
Both are on wkhtmltopdf 0.12.4 (with patched qt)

**Comment by ashkulz** [comment]
Are the fonts installed properly? A minimal reproducible test case would be helpful.

**Comment by EcoFreak** [comment]
Hi @ashkulz I didin't install any fonts in any of the OS (Win 10 and Ubuntu 14)

**Comment by EcoFreak** [comment]
@ashkulz I've installed the fonts in the ubuntu system but still no luck. Any ideias?

**Comment by EcoFreak** [comment]
@ashkulz How can I provide a test case? HTML file and configs used?

**Comment by PhilterPaper** [comment]
If you're using @font-face in CSS to access these fonts, be sure to read up on several bug reports here about missing font variants. Apparently you have to do some kludgey workarounds (modifying the fonts) to get it to work. If that doesn't fix it, perhaps you didn't install the fonts correctly, or they're corrupted. Do any of the fonts you installed work OK?

**Comment by EcoFreak** [comment]
@PhilterPaper  Yes, I'm using @font-face .
In Windows all works ok, I don't even have all fonts installed.
Can you explain or reference an issue on how to modify the fonts in order to have them working. 

Currently my fonts are:
`@font-face {
    font-family: 'titillium_bdbold';
    src: url('/fonts/titillium-bold-webfont.eot');
    src: url('/fonts/titillium-bold-webfont.eot?#iefix') format('embedded-opentype'),
         url('/fonts/titillium-bold-webfont.woff2') format('woff2'),
         url('/fonts/titillium-bold-webfont.woff') format('woff'),
         url('/fonts/titillium-bold-webfont.ttf') format('truetype');
    font-weight: normal;
    font-style: normal;
}

@font-face {
    font-family: 'titilliumlight';
    src: url('/fonts/titillium-light-webfont.eot');
    src: url('/fonts/titillium-light-webfont.eot?#iefix') format('embedded-opentype'),
         url('/fonts/titillium-light-webfont.woff2') format('woff2'),
         url('/fonts/titillium-light-webfont.woff') format('woff'),
         url('/fonts/titillium-light-webfont.ttf') format('truetype');
    font-weight: normal;
    font-style: normal;
}

@font-face {
    font-family: 'titilliumregular';
    src: url('/fonts/titillium-regular-webfont.eot');
    src: url('/fonts/titillium-regular-webfont.eot?#iefix') format('embedded-opentype'),
         url('/fonts/titillium-regular-webfont.woff2') format('woff2'),
         url('/fonts/titillium-regular-webfont.woff') format('woff'),
         url('/fonts/titillium-regular-webfont.ttf') format('truetype');
    font-weight: normal;
    font-style: normal;
}

@font-face {
    font-family: 'titilliumbold';
    src: url('/fonts/titillium-semibold-webfont.eot');
    src: url('/fonts/titillium-semibold-webfont.eot?#iefix') format('embedded-opentype'),
         url('/fonts/titillium-semibold-webfont.woff2') format('woff2'),
         url('/fonts/titillium-semibold-webfont.woff') format('woff'),
         url('/fonts/titillium-semibold-webfont.ttf') format('truetype');
    font-weight: normal;
    font-style: normal;
}


@font-face {
  font-family: 'Gill Sans MT Pro Light';
  src: url('/fonts/GillSansMTPro-Light.eot');
  src: url('/fonts/GillSansMTPro-Light.eot?#iefix') format('embedded-opentype'),
  url('/fonts/GillSansMTPro-Light.woff') format('woff'),
  url('/fonts/GillSansMTPro-Light.ttf') format('truetype');
  font-weight: 300;
  font-style: normal;
}

@font-face {
  font-family: 'Gill Sans MT Pro Medium';
  src: url('/fonts/GillSansMTPro-Medium.eot');
  src: url('/fonts/GillSansMTPro-Medium.eot?#iefix') format('embedded-opentype'),
  url('/fonts/GillSansMTPro-Medium.woff') format('woff'),
  url('/fonts/GillSansMTPro-Medium.ttf') format('truetype');
  font-weight: 500;
  font-style: normal;
}
`

**Comment by PhilterPaper** [comment]
I found one discussion: #2435, there may be others but that should get you started to see if you're having the same problem.

**Comment by EcoFreak** [comment]
I manage to find where the problem was. I was setting the fonts without specifying the correct font-weith attribute. Apparently the QT Webkit does not discover the manage to discover that the font-weight being used by default (normal) does not exist in the font selected and just chooses another font.
After updating the font-weitght where required, all worked correcly. 

Hope this will help anybody ;) 

Thanks 👍
