### ISSUE TITLE
Large memory usage to generate footer/header in all pdf page

### ISSUE THREAD

**Issue by wedercm** [wkhtmltopdf/wkhtmltopdf#3251]
Hi, I work in a rails application that needs to geneate a pdf document with footer/header in all pages. I'm using wkhtmltopdf gem with WickedPdf gem. My problem occurs when I try to genarete with 60 pages, and application, and application uses about 700MB of memory, but when I try to genarete pdf document without footer/header there is no problem with memory. Follows below my Wickedpdf with some wkhtmltopdf configuration.

```
WickedPdf.config = (WickedPdf.config || {}).merge({
  :layout      => "print",
  :disposition => "inline",
  :margin      => { top: 25, bottom: 15, left: 7, right: 7 },
  :dpi         => "300",
  :header      => { spacing: 20, html: {template: 'layouts/print/header.pdf.erb'} },
  :footer      => { spacing: 5, html: {template: 'layouts/print/footer.pdf.erb'} }
})
```

**Comment by alloylab** [comment]
what version are you running?

**Comment by alloylab** [comment]
We are closing this out since we haven't heard from you. If you are still having this issue please feel free to re-open it. Thanks.
