### ISSUE TITLE
wkhtmltopdf has been working fine for months. Now it will not load the same urls as before.

### ISSUE THREAD

**Issue by j0emcginnis** [wkhtmltopdf/wkhtmltopdf#3258]
wkhtmltopdf has been working fine for months. Now it will not generate the pdfs and load the same urls as before. 

Some times it loads the url, but will not display the images. Other times it errors out with the 'Failed loading page' error. Nothing has changed with the html or the server config. I can also access the links public and all of the html is displaying correctly.

Not sure what is happening nor how to debug the issue.

Thanks in advance!!

**Comment by PhilterPaper** [comment]
If you're sure that you haven't changed anything, and all the resources you're trying to load are in exactly the same place and haven't had any restrictions (e.g., hotlink protection) added to them, all I can think of is that your host (if this is running on a server) or ISP has made some security-related changes that restrict access (such as certain system calls opening remote pages via HTTP). You can ask them, but often they won't tell you (or confirm) what security measures they've taken.

Are these problems solidly consistent, or do they seem to come and go? Regarding possible timeouts, if running on a PC, have you scanned for malware/viruses that might be slowing you down? This is only with remote (HTTP access) pages, and not local files? These remote pages load in a browser with no problems or errors logged, or with any evident changes to them (e.g., now https)?
