### ISSUE TITLE
Print html to pdf, when there has thead in the table, thead will  block some of the content

### ISSUE THREAD

**Issue by df257** [wkhtmltopdf/wkhtmltopdf#3261]
![image](https://cloud.githubusercontent.com/assets/7835444/21449030/e9525292-c923-11e6-8a39-3712cd961316.png)

**Comment by df257** [comment]
![qq 20161223152545](https://cloud.githubusercontent.com/assets/7835444/21449050/2b9435f8-c924-11e6-8159-d1567a539887.png)

**Comment by PhilterPaper** [comment]
A `<thead>` overlapping the first row or two has been discussed many times. Search for "overlap" and "thead". Unfortunately, at this time there does not seem to be a solution for the problem.

**Comment by PavelKushnirskiy** [comment]
Take a look
https://github.com/wkhtmltopdf/wkhtmltopdf/issues/1524
