### ISSUE TITLE
build.py fails with "command failed: exit code 25856" on OSX

### ISSUE THREAD

**Issue by mcmc8680** [wkhtmltopdf/wkhtmltopdf#3263]
Hello,

As I wanted to try this program called wkhtmltopdf on my OSX 10.11.6; but i run it with a problem:

I follow the steps of "install.md":
-   git clone --recursive https://github.com/wkhtmltopdf/wkhtmltopdf.git
-   git pull
-   git submodule update
-   sudo gem install fpm --no-ri --no-rdoc

then enter the build comment:
-   ./scripts/build.py osx-cocoa-x86-64

Then, there are the following items in the folder "static-build":
1. jpegsrc.v9b.tar.gz
2. libpng-1.6.26.tar.gz
3. xz-5.2.2.tar.gz
4. osx-cocoa-x86-64 [folder]

Eventually it stopped with
>...
> generators/win32/msbuild_objectmodel.cpp:1974:13: warning: 7 enumeration values not handled in switch: 'NETUnknown', 'NET2002',
>       'NET2003'... [-Wswitch]
>     switch (version)
>             ^
> 27 warnings generated.
> This is the Qt for Mac OS X Open Source Edition.
> 
> You are licensed to use this software under the terms of
> the Lesser GNU General Public License (LGPL) versions 2.1.
> 
> You have already accepted the terms of the  license.
> 
> header created for /Users/z????????n/wkhtmltopdf/static-build/osx-cocoa-x86-64/qt/src/corelib/global/qconfig.h (2)
> Creating qmake. Please wait...
> OpenSSL support cannot be enabled due to functionality tests!
>  Turn on verbose messaging (-v) to ../../../qt/configure to see the final report.
>  If you believe this message is in error you may use the continue
>  switch (-continue) to ../../../qt/configure to continue.
> ../../../qt/configure -opensource -confirm-license -fast -release -static -graphicssystem raster -webkit -exceptions -xmlpatterns -system-zlib -system-libpng -system-libjpeg -no-libmng -no-libtiff -no-accessibility -no-stl -no-qt3support -no-phonon -no-phonon-backend -no-opengl -no-declarative -no-script -no-scripttools -no-sql-ibase -no-sql-mysql -no-sql-odbc -no-sql-psql -no-sql-sqlite -no-sql-sqlite2 -no-mmx -no-3dnow -no-sse -no-sse2 -no-multimedia -nomake demos -nomake docs -nomake examples -nomake tools -nomake tests -nomake translations -silent -no-framework -no-dwarf2 -xrender -openssl -largefile -no-rpath -cocoa -platform unsupported/macx-clang --prefix=/Users/z????????n/wkhtmltopdf/static-build/osx-cocoa-x86-64/qt -I /Users/z********n/wkhtmltopdf/static-build/osx-cocoa-x86-64/deplibs/include -L /Users/z????????n/wkhtmltopdf/static-build/osx-cocoa-x86-64/deplibs/lib
> command failed: exit code 25856
> z????????ndeMBP:wkhtmltopdf z????????n$

any ideas what I am missing or whats wrong?

**Comment by ashkulz** [comment]
OpenSSL is no longer supported on OS X. If you install the version from brew, you have to [pass special flags](http://stackoverflow.com/q/38670295) to link to it. The travis target currently disables OpenSSL for that reason.
