### ISSUE TITLE
Page smaller than HTML

### ISSUE THREAD

**Issue by krlosgilson** [wkhtmltopdf/wkhtmltopdf#3264]
When I convert an HTML page to PDF, the dimensions of the content are much smaller than the original page. Should I use some parameter to be exactly the same size when I print the page in HTML?

**Comment by PhilterPaper** [comment]
Two things to look at: 1) what page size are you using (--size such as A4 or letter)? 2) take a look at recent reports of pages being scaled down for unknown reasons (font size, etc. much smaller than expected).

**Comment by krlosgilson** [comment]
The command I am using is only: `wkhtmltopdf file.html file.pdf`, that is, I am not using any specific parameters to inform the paper type. My 'file.html' file when printing through any browser, the dimensions are normal for an A4 page. After conversion, the generated PDF file is more or less occupying half of the page. Do you suggest that I use what parameters? How can I be checking the recent pages report? Sorry for English, I'm using a translator.

![screenshot_1](https://cloud.githubusercontent.com/assets/24833043/21569720/49e79278-ce9e-11e6-99bb-37d513f5727c.jpg)
![screenshot_2](https://cloud.githubusercontent.com/assets/24833043/21569728/5502167e-ce9e-11e6-9ac1-7ff6b8bb4813.jpg)

**Comment by PhilterPaper** [comment]
You might try adding the flags `--size A4` and `--disable-smart-shrinking` to the command, and see if this has the desired effect. Then read up on reports of fonts and other things being scaled unexpectedly small.

**Comment by krlosgilson** [comment]
@PhilterPaper, I used the two parameters you recommended, although the '-s A4' has no effect, because the default is already this, the second parameter '--disable-smart-shrinking' was able to solve the problem and now the PDF file is really As the original HTML. Thanks for the availability and dedicated time.
