### ISSUE TITLE
Cannot install headless in Alpine

### ISSUE THREAD

**Issue by Yajo** [wkhtmltopdf/wkhtmltopdf#3265]
Following instructions from stable section of [downloads page](http://wkhtmltopdf.org/downloads.html), open a shell in alpine (`docker run -it --rm alpine sh`) and install it:

```
apk add --no-cache zlib fontconfig freetype libx11 libxext libxrender
wget -O- http://download.gna.org/wkhtmltopdf/0.12/0.12.4/wkhtmltox-0.12.4_linux-generic-amd64.tar.xz | tar -xJf -
mv wkhtmltox/bin/* /usr/local/bin/
mv wkhtmltox/include/* /usr/local/include/
mv wkhtmltox/lib/* usr/local/lib/
mv wkhtmltox/share/man/man1/* /usr/local/share/man/man1/
```

Now, if you try to run it:

```
$ wkhtmltopdf --help
sh: wkhtmltopdf: not found
```

**Comment by ashkulz** [comment]
Looks like an installation issue, you may need to restart your shell.

**Comment by Yajo** [comment]
I restarted the shell and it happens the same. Even when specifying full path:

```
# /usr/local/bin/wkhtmltopdf 
sh: /usr/local/bin/wkhtmltopdf: not found
```

**Comment by mwalsher** [comment]
I'm having the same issue. My Dockerfile has:

```
RUN apk add --update --no-cache \
    libgcc libstdc++ libx11 glib libxrender libxext libintl \
    libcrypto1.0 libssl1.0 \
    fontconfig ttf-dejavu ttf-droid ttf-freefont ttf-liberation ttf-ubuntu-font-family

RUN curl -L -O http://download.gna.org/wkhtmltopdf/0.12/0.12.4/wkhtmltox-0.12.4_linux-generic-amd64.tar.xz \
  && tar -xf wkhtmltox-0.12.4_linux-generic-amd64.tar.xz \
  && mv wkhtmltox/bin/* /usr/local/bin/ \
  && mv wkhtmltox/include/* /usr/local/include/ \
  && mv wkhtmltox/lib/* usr/local/lib/ \
  && mv wkhtmltox/share/man/man1/* /usr/local/share/man/man1/
```

When I try to run it:

```
bash-4.3# /usr/local/bin/wkhtmltopdf
bash: /usr/local/bin/wkhtmltopdf: No such file or directory
```

Perhaps I'm missing something?

**Comment by fredriktid** [comment]
I'm also experiencing "not found" after an apparently successful installation on Alpine in a Docker environment.

Do you think it's possible re-open this issue?

**Comment by HosseinAgha** [comment]
Same problem here i'm installing wkhtmltox-0.12.4_linux-generic-amd64.tar.xz on linux alpine

**Comment by mikehaertl** [comment]
I have the same issue. @ashkulz Would you consider reopening this issue? It seems to affect many developers and so far we don't have a solution. It seems the precompiled wkhtmltopdf binaries don't work on Alpine.

The error message is pretty weird and misleading though. Could it be some missing library?

**Comment by mikehaertl** [comment]
Ok, see #3739: Alpine does not support GNU libc. So the precompiled binaries will not work. Also see https://github.com/gliderlabs/docker-alpine/issues/219

**Comment by ashkulz** [comment]
Currently working on a reworked packaging system in the [wkhtmltopdf/packaging](https://github.com/wkhtmltopdf/packaging) repository, you can download preview builds [for some distros](https://builds.wkhtmltopdf.org/0.12.5-dev/). Will accept PRs for Alpine support :smile:

**Comment by sunilplivo** [comment]
Any updates on this? Was anyone able to install wkhtmlpdf on docker image with Alpine?

**Comment by ashkulz** [comment]
See wkhtmltopdf/packaging#2, someone still needs to do the work for it to happen.

**Comment by pierresomos** [comment]
there is wkhtmltopdf alpine package, so to install you just need to type `apk add wkhtmltopdf`

**Comment by nweber-taekni** [comment]
Hello, 

I used the build released on the official Alpine Repo and I'm faced to an issue, the footer and header are not displayed. 

Someone else already had the same issue ?

Alpine : 3.10
Wkhtmltopdf: 0.12.5

**Comment by jan-kaczorowski-ynd** [comment]
I'm experiencing the very same
0.12.5 -> working but no footer, which in my case is a no-go
0.12.4 -> tried to install -> got `not found` error mentioned above.

**Comment by nweber-taekni** [comment]
Hi, 

I have solve my problem with this docker image : surnet/alpine-wkhtmltopdf:3.10-0.12.5-full as base image and including the binary in my final image.

COPY --from=wkhtmltopdf_image /bin/wkhtmltopdf /usr/local/bin/wkhtmltopdf
COPY --from=wkhtmltopdf_image /bin/wkhtmltoimage /usr/local/bin/wkhtmltoimage
COPY --from=wkhtmltopdf_image /bin/libwkhtmltox* /usr/local/bin/

**Comment by jan-kaczorowski-ynd** [comment]
I have eventually solved in a very similar manner to above in my `Dockerfile`:
```
FROM madnight/docker-alpine-wkhtmltopdf as wkhtmltopdf_image
FROM ruby:2.6.2-alpine
...
RUN apk update freetype freetype-dev ttf-freefont
...
COPY --from=wkhtmltopdf_image /bin/wkhtmltopdf /usr/bin/
...
```
