### ISSUE TITLE
Unknown long argument --cover

### ISSUE THREAD

**Issue by niyingg** [wkhtmltopdf/wkhtmltopdf#3267]
I want to add a cover  but this version give me the  tips is that Unknown long argument --cover.

**Comment by cal1801** [comment]
I am having this issue as well. I can't figure out what is causing it.

**Comment by Tomsgu** [comment]
Closing as there is no information to be able to help. Without complete command it's hard to see what you pass to the `--cover` argument. Please comment or re-open if you have more information.
