### ISSUE TITLE
WkHtmlToImage QPainter::combinedTransform: Painter not active || Height problems

### ISSUE THREAD

**Issue by enemijs1** [wkhtmltopdf/wkhtmltopdf#3269]
Hi, it gives me an error, while converting html to image if a html is very long, it sometimes cant calcuate the height. Are there any fix? Could it be timeout 20 ? 

What can couse this problem ? 

```
    $ImageOptions = array(
        	'format'=>'jpg',
        	'width' => 793,
        );

        $image = new WkHtmlToImage($ImageOptions);
        $image->addPage($html);

```
QPainter::combinedTransform: Painter not active
QPainter::combinedTransform: Painter not active
QPainter::setRenderHint: Painter must be active to set rendering hints

**Comment by ashkulz** [comment]
Looks like you're using some wrapper, please post the sample HTML and command line options (else ask the author of the wrapper).
