### ISSUE TITLE
I got an empty PDF document but in browser is normal 

### ISSUE THREAD

**Issue by wfso** [wkhtmltopdf/wkhtmltopdf#3273]
html document content is following:

```html
<!DOCTYPE HTML>
    <html lang="zh-hans">
    <head>
    <meta charset="UTF-8">
    <title>index</title>
      <style>
        .main {
          position:absolute;
          top:0;
          left:0;
          overflow-y:auto;
          bottom:0;
          right:0;
        }
      </style>
    </head>
    <body>
    <div class="main">
      --allow
      <br />
      --allow
      <br />
      --allow
      <br />
      --allow
      <br />
      --allow
      <br />
      --allow
      <br />
      --allow
      <br />
      --allow
    </div>
    </body>
    </html>
```

If you understand Chinese, you can to http://www.jianshu.com/p/57c897cfaa27 check my return after doing the experiment results. 

The experimental conclusion is that this kind of circumstance is associated with the following properties 
```css
          position:absolute;
          top:0;
          overflow-y:auto;
```

**Comment by wfso** [comment]
Version 0.12.3.2 and 0.12.4 has this problem

**Comment by samami** [comment]
fwiw, I had <!DOCTYPE html> in my document and it would render an empty doc, but when I removed that line, it worked fine.

`<!DOCTYPE html>
<html>
<head>
<style>
@page {
  size: 3in 3in;
  border: 1px;
}
h2 {
    position: fixed;
    left: 100px;
    bottom: 100px;
}
#mydiv {
    font-variant: small-caps;
    font-size: 1.5em;
    font-weight: bold;
    position: fixed;
    left: 200px;
    bottom: 200px;
    
}

</style>
</head>
<body>

<h2>This is a heading with an absolute position</h2>
<div id="mydiv">
<p>With absolute positioning, an element can be placed anywhere on a page. The heading below is placed 100px from the left of the page and 150px from the top of the page.</p>
</div>
</body>
</html>`

**Comment by Tomsgu** [comment]
It's most likely connected with #3939. The overflow seems to be the problem.

**Comment by Tomsgu** [comment]
Closing as it's a problem with overflow attribute. This issue is reported already.
