### ISSUE TITLE
Outline destination not conforming PDF spec

### ISSUE THREAD

**Issue by torakiki** [wkhtmltopdf/wkhtmltopdf#3275]
This is an page destination created by wkhtmltopdf
```
10 0 obj  
[0 /XYZ 33  
813.500000  0]     
endobj
```
This is not conforming the PDF spec where the first item is __not__ a page number but 
> page is an indirect reference to a page object.

so the previous example should be something like 
```
10 0 obj   
[22 0 R /XYZ 33  
813.500000  0]   
endobj
```

**Comment by ashkulz** [comment]
@torakiki: can you post a sample HTML which generates incorrect PDF output and the correct PDF using some PDF editing tool, so that I can understand what changes need to be made?

**Comment by torakiki** [comment]
This is the html file I used (renamed to txt to allow GitHub upload) [test.txt](https://github.com/wkhtmltopdf/wkhtmltopdf/files/693039/test.txt). You can open the resulting PDF with a text editor and you can see page destinations are written as I mentioned before, the first element of the destination array is the page number but it should be the page reference so instead of `0` you should have `5 0 R` if 5 is the object number of the first page object.

**Comment by ashkulz** [comment]
@torakiki: would help if you uploaded screen shots, as that would save time for me :smile:

**Comment by torakiki** [comment]
@ashkulz  of what?

**Comment by ashkulz** [comment]
PDF Editor where it shows what is wrong and what has to be corrected...

**Comment by torakiki** [comment]
There is no error message or screen to show. Most PDF Editor or Readers are smart enough to workaround this on the fly so the user won't notice any error message, nevertheless the generated PDF is not conforming the specs so, even though it's probably low prio, it should probably be fixed. 
In my case I found the issue because our PDF library was going through the fallback branch of execution, the one where we apply the workaround.

**Comment by ashkulz** [comment]
Okay, so this is more of a PDF validation issue, I thought it was not working at all.

**Comment by ashkulz** [comment]
What platform do you generally test this library? In case I make a patch, would you be able to check/verify the fix?

**Comment by torakiki** [comment]
@ashkulz I'm on Linux and sure, I can test the fix

**Comment by kkthek** [comment]
@ashkulz: It is more than a validation issue because it causes PDFs to be merged without preserving the bookmarks. I'm am **very** interested in a fix.

**Comment by quique** [comment]
@ashkulz : No, this is not merely a pedantic validation issue; I got actually bitten by this bug  :-(

My project generates a PDF file using wkhtmltopdf, and then merges it with a different PDF file using pdftk.  Because of this bug, outlines do not work on the resulting PDF  :-(

Run this command on any PDF generated by wkhtmltopdf:
`pdftk foo.pdf dump_data output foo.info`
and you will notice that `BookmarkPageNumber` always has the value `0`.  On PDFs generated with other tools, pdftk shows the correct value.

The PDF spec says that the target of a bookmark/outline entry contains the *object ID* of the target page.   While it is true that the *page number* still works in some PDF viewers, the PDF is not actually correct, and breaks projects like kkthek's or mine.

**Comment by ashkulz** [comment]
Can you try the following patch to Qt and see if it works for you?
```diff
diff --git a/src/gui/painting/qprintengine_pdf.cpp b/src/gui/painting/qprintengine_pdf.cpp
index f6d6e1c..5a08cb7 100644
--- a/src/gui/painting/qprintengine_pdf.cpp
+++ b/src/gui/painting/qprintengine_pdf.cpp
@@ -1524,7 +1524,7 @@ void QPdfEngine::addAnchor(const QRectF &r, const QString &name)
     QRectF rr = d->pageMatrix().mapRect(r);
     uint anchor = d->addXrefEntry(-1);
     d->xprintf("[%d /XYZ %s \n",
-               d->pages.size() - 1,
+               d->pages.back(),
                qt_real_to_string(rr.left(), buf));
     d->xprintf("%s 0]\n",
                qt_real_to_string(rr.bottom(), buf));
```

**Comment by quique** [comment]
Thanks for your quick answer, but this patch didn't fix the problem (rather the opposite).

pdftk still reports all the BookmarkPageNumber fields as having value 0, and now the PDF viewer cannot even work around it.

**Comment by mpseidel** [comment]
Observing the same here

**Comment by qweluke** [comment]
Any news on this? Having the same issue :/

**Comment by qweluke** [comment]
@ashkulz can you fix this issue? or maybe there's already a solution for this?

**Comment by Jaudouard** [comment]
This is preventing me from merging pdf created vu wkhtmltopdf.
I loose all bookmarks after a merge.

Is there any news on this issue?

**Comment by ashkulz** [comment]
I'd appreciate if someone who faces this issue could post a series of commands (possibly using `pdftk`) which generates a PDF which demonstrates this bug, so that it's easier to verify any fix which might be developed.

**Comment by marcvinyals** [comment]
Here is a fix (not creating a pull request since the relevant qt repo seems to be read-only):
```patch
diff --git a/src/gui/painting/qprintengine_pdf.cpp b/src/gui/painting/qprintengine_pdf.cpp
index a906e3243b..e3ebcff5b9 100644
--- a/src/gui/painting/qprintengine_pdf.cpp
+++ b/src/gui/painting/qprintengine_pdf.cpp
@@ -1522,8 +1522,8 @@ void QPdfEngine::addAnchor(const QRectF &r, const QString &name)
     char buf[256];
     QRectF rr = d->pageMatrix().mapRect(r);
     uint anchor = d->addXrefEntry(-1);
-    d->xprintf("[%d /XYZ %s \n",
-               d->pages.size() - 1,
+    d->xprintf("[%d 0 R /XYZ %s \n",
+               d->pages.back(),
                qt_real_to_string(rr.left(), buf));
     d->xprintf("%s 0]\n",
                qt_real_to_string(rr.bottom(), buf));
```

To check that it works:
```console
$ wkhtmltopdf https://doc.qt.io/archives/qt-4.8/qpoint.html /tmp/qpoint-bug.pdf
$ pdftk /tmp/qpoint-bug.pdf dump_data_utf8 | grep BookmarkPageNumber | head
BookmarkPageNumber: 0
BookmarkPageNumber: 0
BookmarkPageNumber: 0
BookmarkPageNumber: 0
BookmarkPageNumber: 0
BookmarkPageNumber: 0
BookmarkPageNumber: 0
BookmarkPageNumber: 0
BookmarkPageNumber: 0
BookmarkPageNumber: 0
$ wkhtmltopdf https://doc.qt.io/archives/qt-4.8/qpoint.html /tmp/qpoint-fix.pdf
$ pdftk /tmp/qpoint-fix.pdf dump_data_utf8 | grep BookmarkPageNumber | head
BookmarkPageNumber: 1
BookmarkPageNumber: 1
BookmarkPageNumber: 1
BookmarkPageNumber: 1
BookmarkPageNumber: 1
BookmarkPageNumber: 1
BookmarkPageNumber: 1
BookmarkPageNumber: 2
BookmarkPageNumber: 2
BookmarkPageNumber: 3
```

**Comment by ashkulz** [comment]
Thanks for the patch, @marcvinyals! I've unarchived the repository, can you create a PR there so I can merge it?

**Comment by marcvinyals** [comment]
Sure! https://github.com/wkhtmltopdf/qt/pull/48
