### ISSUE TITLE
I just updated to 0.12.4 and the page shrinks

### ISSUE THREAD

**Issue by mtaysic** [wkhtmltopdf/wkhtmltopdf#3276]
Hello and thank you for this wonderful tool!

I wanted to let you know of a issue I am seeing. I am on OSX and I upgraded from 0.12.3 to 0.12.4. I didn't change any of the settings I send to wkhtmltopdf. 

Here they are: 
{ 'javascript-delay':5000, 'margin-left': '4mm', 'margin-right': '4mm', 'page-size':'Letter' }

What happened was that the page was shrunk to 1/4 of the size with the update. I tried to use the disable-smart-shrinking option and also the zoom : 1 option. Neither solved the issue but reinstalling 0.12.3 worked for me. 

Let me know if I am missing something. Thank you.

**Comment by ashkulz** [comment]
It's a known issue -- see #3241
