### ISSUE TITLE
Resolution issue on OSX

### ISSUE THREAD

**Issue by joao-quiterio** [wkhtmltopdf/wkhtmltopdf#3277]
When I run "wkhtmltopdf http://google.com google.pdf" on a fresh install of wkthmltopdf 0.12.4 for OSX 64bits on a Mac running macOS Sierra I get the following [output](https://github.com/wkhtmltopdf/wkhtmltopdf/files/694193/googe.pdf) (seems like it was zoomed-out 10x)

**Comment by ashkulz** [comment]
Duplicate of #3241, please track that issue instead.
