### ISSUE TITLE
Custom fonts not working in  wkhtmltopdf 0.12.2.1 (with patched qt)?

### ISSUE THREAD

**Issue by nageshnallapu** [wkhtmltopdf/wkhtmltopdf#3278]
I am using  Proxima_nova regular and bold fonts ,for html these fonts are working fine.But when it comes to  the pdf generation the fonts are appearing different.

- How to resolve this issue?

- Whether this wkhtmltopdf 0.12.2.1 supports custom fonts or not?
below is the sample code I used in css
`<style>
@font-face {
    font-family: "proxima_nova_rgbold";
    src: url(data:font/woff;base64,d09GRgABAAAAA ...==)  format("WebOpenFont"),
          url(data:font/ttf;base64,AAEAAAATAQAAB...==format("truetype");    
         font-weight: normal;
        font-style: normal;
   }`
I am working on Linux 3.13.0-62-generic x86_64 version  and running the exec command in php.

**Comment by MitchellBouwman** [comment]
Hi @nageshnallapu, you can place `@import` in your CSS file and include it. ;)

**Comment by nageshnallapu** [comment]
Thanks @MitchellBouwman ,I got it now.

**Comment by MitchellBouwman** [comment]
@nageshnallapu Nice mate ;)

**Comment by Tomsgu** [comment]
Closing as it was resolved.

**Comment by bhagujava** [comment]
> Thanks @MitchellBouwman ,I got it now.

Could you please explain here? I am facing same issue.

Much appreciated.

**Comment by MitchellBouwman** [comment]
> > Thanks @MitchellBouwman ,I got it now.
> 
> Could you please explain here? I am facing same issue.
> 
> Much appreciated.

Check out how to include fonts like they do on fonts.google.com using the @import statement!
