### ISSUE TITLE
Space above header in 0.12.4.0

### ISSUE THREAD

**Issue by dsmalko** [wkhtmltopdf/wkhtmltopdf#3279]
After upgrading to 0.12.4.0 from 0.12.3.2 a space/margin appeared above header. Height of space depends on height of header. I've tested with simple html files, only text and breaks.

**Comment by avif** [comment]
I've experienced the same issue, adding these page params fixed it:
 --no-stop-slow-scripts --javascript-delay 1000

So the full command would be something like this:
```
wkhtmltopdf\
 -T 20mm -B 20mm  -L 0 -R 0\
 https://facebook.com\
 --header-html https://twitter.com\
 --footer-html https://instagram.com\
 --no-stop-slow-scripts --javascript-delay 1000\
 ~/test.pdf
```

Please note that using these urls will generate some warnings

**Comment by Tomsgu** [comment]
Closing as there is no feedback since 2017 and solution was provided.
