### ISSUE TITLE
how can you show total records per page on a table spanning multiple pages

### ISSUE THREAD

**Issue by faceless105** [wkhtmltopdf/wkhtmltopdf#3282]
This isn't an issue but a task that's very specific to wkhtmltopdf. I'm generating a report that has a table that can span multiple pages. The current one I'm testing has 594 rows. I'm using the table footer <tfoot> and I'd like the display the number of records per page in the footer as it makes checking the data a lot quicker.

After seeing that I could use $_GET to place the page number in the page footer, I thought each page was broken and processed in their separate pieces, so I thought I could just use JS to count the number of rows, but it's returning a count for the entire table that spans multiple pages, not just the current page. Is something like this even possible?

Like I said, I know this isn't an issue where somethings broken, but it is a task that's pretty specific to this community/implementation of the code.

**Comment by Tomsgu** [comment]
What you can do is to calculate how many rows fits to one page. (it works if you have constant row height) and display this number in a footer (page*CONST_ROWS_ON_PAGE). After you put page-break to be sure there will be nothing more on this page.

**Comment by Tomsgu** [comment]
Closing as the aswers were provided.
