### ISSUE TITLE
add page isn't always adding the page

### ISSUE THREAD

**Issue by faceless105** [wkhtmltopdf/wkhtmltopdf#3283]
I'm having an issue with a report generator that'll generate multiple pages that aren't always being added to the report. The issue seems to be, it sometimes only takes the first page or it takes all of them. I also can't stress the SOMETIMES enough as this seems intermittent and can't figure out why.

Here's a code snippet that should show how this is being used.

`
$baseOptions = array(
	'orientation' => 'landscape',
	'margin-bottom' => 10,
	'margin-top' => 40,
	'margin-left'   => 0,
	'margin-right'   => 0
);
		
$attempts = $this->generatePdf($baseOptions, $pages, $fileName);

protected function generatePdf($baseOptions, $pages, $fileName, $attempts = 1){
		
		$pdf = new Pdf();
		$pdf->setOptions($baseOptions);
		$pageCountVirtual = count($pages);
		
		foreach($pages as $pageNum => $page){
			
			$options = array(
				'header-html' => OUTPUT_PATH.'output/html/reports/'.$fileName."-$pageNum-head.html",
				'footer-html' => OUTPUT_PATH.'output/html/reports/'.$fileName."-$pageNum-footer.html"
			);
			
			$pdf->addPage(OUTPUT_PATH.'output/html/'.$fileName."-$pageNum-content.html", $options); //is there a way to verify this has been added?
		}
		
		$pdfCheck = $pdf->saveAs(OUTPUT_PATH.'output/pdf/'.$fileName.".pdf");
		
		if(!$pdfCheck || $attempts >= 10) {
			if(!$pdfCheck){
				echo $pdf->getError();
			}
			else{
				echo "Too many failed attempts ($attempts). Please check your document structure and computer settings.\n\n";
			}
			return false;
		}
		else{
			$this->imagick->clear(); //clear the cache
			$this->imagick->pingImage(OUTPUT_PATH.'output/pdf/'.$fileName.".pdf");
			$pageCheck = $this->imagick->getNumberImages();
			if($pageCheck < $pageCountVirtual){ //since virtual pages may be split into multiple print pages, it stands to reason, that the print page count should never be less than the virtual page count.
				//this can give false positives. If one virtual page comes out to 17 print pages, and there are a total of 4 virtual pages, this will always give a false positive when it only converted the first virtual page.
				$at = ($attempts += 1);
				$attempts = $this->generatePdf($baseOptions, $pages, $fileName, $hos_code, $at);
			}
			return $attempts;
		}
		
	}`

I came up with a recursive function to try and detect failed writes and try again, it isn't perfect but it has definitely helped. I have comments explaining the false positive where I won't be able to catch missed pages.

"this can give false positives. If one virtual page comes out to 17 print pages, and there are a total of 4 virtual pages, this will always give a false positive when it only converted the first virtual page."

In reality, I'm not sure why sometimes only the first addPage() is being added. It seems if it can add a second page then it always adds all the pages. If it cuts off, it will always cut off anything after the first addPage().

My reports at their longest have ~28 pages for a PDF page count, and are composed of I believe 4 virtual pages (only 4 calls to the addPage, which is where I ran into my false positive issue). If you have any input into what can or might cause this, I'd really appreciate it. This is proving to be very problematic.

**Comment by alloylab** [comment]
We are closing this out since we haven't heard from you. If you are still having this issue please feel free to re-open it. Thanks.
