### ISSUE TITLE
HTML & PDF is not exactly the same. Text is not rendering exactly

### ISSUE THREAD

**Issue by black007php** [wkhtmltopdf/wkhtmltopdf#3285]
I have a html file & I want to convert the HTML to exact PDF on the fly.
I am using Wkhtmktopdf to convert HTML to PDF.

**Here is the HTML file url
http://web2print.orgfree.com/web2print/pdf.html**

**And here is the output PDF url
http://web2print.orgfree.com/web2print/pdfs/sample_html.pdf**

My requirements
1.The red dashed border around the HTML/PDF is Cut margin **(Bleed)**.
2.The green dashed border around the HTML/PDF is Safe margin (The texts won't exceed this box).
3.Actual PDF size is 8.5 x 11 inches.
4.The bleed area should be 0.25inch long from all the 4 edges of the document. So, 0.25 x 4 = 1 inch. Then the Output PDF size would become (8.5 + 0.5) = 9 inches & (11 + 0.5) = 11.5 inches. (see the attached pdf)
5.So the resulting PDF should be 9 x 11.5 inches in size.
6.Also the safe margin should be 0.25inch long from all the 4 edges of the **Bleed not from the document**. (see the attached pdf).
7.The PDF should have 300dpi.

My System Architecture
Windows 7
Wkhtmltopdf (Windows (MSVC)	0.12.4)
Browsers - Chrome
Server - Apache & PHP 7.0

_**The issues need to be fixed
1.The actual text in the HTML is not rendered exactly in the PDF. Compare the HTML & PDF (see the attached screenshot).
2.The bleed does not have 0.25inch from all the 4 edges of the document. (see the attached screenshot).
3.The Safe margin does not have 0.25inch from all the 4 edges of the bleed. (see the attached screenshot).**_

Here is the Whkhtmltopdf command
**-B 0 -L 0 -R 0 -T 0 --page-width 228.6mm --page-height 292.1mm --zoom 2 --print-media-type --encoding utf8**

**Issues screenshot
http://web2print.orgfree.com/web2print/issues.png**

Any help would be appreciated. @antialize @ashkulz @pruiz @npinchot @pussbb @sodabrew @theirix @mn4367 @poizan42 @renan

**Comment by alloylab** [comment]
is this still an issue on 0.12.5?
