### ISSUE TITLE
How to skip external resources from loading

### ISSUE THREAD

**Issue by viswa18** [wkhtmltopdf/wkhtmltopdf#3294]
I have a html document, that has lots of external resources such as images. Due to slow network connection conversion takes more time to finish. How can I skip external resources from loading. Is there any option to convert the html in offline. It would greatly increase the performance. Can we execute the conversion in offline mode. Is there way to disable network connection at the time of conversion in wkhtmltopdf

Thanks.

**Comment by BravoTango86** [comment]
Probably not ideal but I have managed to get around this by setting a proxy argument with an invalid address, eg **-p http://127.0.0.1:0** which seems to work.  It would be great to have something built in though!
