### ISSUE TITLE
How to download the latest built dll files (wkhtmltox_32.dll and wkhtmltox_64.dll)?

### ISSUE THREAD

**Issue by wpfpro** [wkhtmltopdf/wkhtmltopdf#3301]
Sorry but I'm looking for these files to be ready to be downloaded. I have no experience of dealing with C and C++ projects (and looks like the solution here cannot be opened with Visual Studio, it's fairly strange to me). I'm using the OpenHtmlToPdf lib which wraps wkhtmltopdf but the dll files wrapped there are not updated (their file version is 0.12.1.2 and last modified in 2014 which is about 3 years ago). 

The old dll files don't render CSS linear-gradient background correctly (the color stop's offset is misplaced and randomly placed, also the color region appears to be scattered randomly, it's totally a mess). I've not tested other kind of gradient background as well as some advanced feature of CSS3 (but the most necessary requirement is gradient background support, some other advanced feature could not be used currently).

 So I hope the latest ones would have fixed those bugs. Please give me the latest version of already built dlls. Thank you so much!

**UPDATE:**
After Googling around, I've found a newer version (0.12.2.1 and last modified in 2015) but still the bug has not been fixed. To help visualize what the bug is, please see this snapshot http://imgur.com/a/mmqxK
The CSS3 here applies a simple linear-gradient background to all even rows (<tr>), it is like this:

_tr:nth-child(2n) { 
  background:-webkit-linear-gradient(bottom, red 20%, green 100%);
}_

**Comment by ashkulz** [comment]
Don't know where you got the files, but it's always named `wkhtmltox.dll` -- check the wrapper you are using and ask them to update.
