### ISSUE TITLE
HTML Generated for footer options

### ISSUE THREAD

**Issue by andrewjlow** [wkhtmltopdf/wkhtmltopdf#3303]
Hi there,

Would anyone know what is the HTML and/or CSS classes generated when using the footer options **--footer-center** and **--footer-right**? I just like to be able to apply specific CSS to these options.

I do understand I can use **--footer-html** however I found using the above footer options are more appropriate for my situation.

Thank you for your assistance in this matter.

**Comment by kreediam** [comment]
+1 I've been looking for the same thing.

**Comment by NiR-** [comment]
From what I understand of the code, I think it does not rely on any CSS property. [See here](https://github.com/wkhtmltopdf/wkhtmltopdf/blob/master/src/lib/pdfconverter.cc#L640) and [here](https://github.com/wkhtmltopdf/wkhtmltopdf/blob/master/src/lib/pdfconverter.cc#L635). This is also why there's only the font name & its size configurable.
