### ISSUE TITLE
Wkhtmltopdf

### ISSUE THREAD

**Issue by anga20** [wkhtmltopdf/wkhtmltopdf#3304]
Both 0.12.0 and 0.12.1-dev generate an empty white page for particuler url in my localhost ,but image is working fine i try to download as pdf it returing only white page pls help

**Comment by anga20** [comment]
hai any one know how to fix this issues

**Comment by Tomsgu** [comment]
Upgrade to `0.12.5`. If you have still the problem please add a new issue with a !!detailed!! explanation. Html file and explanation what you expect to be an output.
