### ISSUE TITLE
I can't execute de file from a website in iis7

### ISSUE THREAD

**Issue by DFMERA** [wkhtmltopdf/wkhtmltopdf#3305]
Hi.
I am trying to use the .exe file executing it from a website in iis7. The file is located in the bin folder of the site, but it doesn'y work, Do I need a special configuration in IIS 7?

Thanks.

**Comment by alloylab** [comment]
is this still an issue on 0.12.5?

**Comment by alloylab** [comment]
We are closing this out since we haven't heard from you. If you are still having this issue please feel free to re-open it. Thanks.
