### ISSUE TITLE
How can I create “2 steps version” release wkhtmltopdf in qt project?

### ISSUE THREAD

**Issue by mcmc8680** [wkhtmltopdf/wkhtmltopdf#3307]
Hello,

I already download wkhtmltopdf source code in Mac and ubuntu.
And, I use QT5.5 open this wkhtmltopdf.pro to build this executable file in release folder.
That is only “2 steps version” wkhtmltopdf and it is useful for me.
(because it suppose to load tiff image in html.)

But now, I want to execute those file in another computer without QT5.5.
The file can not work.
I hope that QT5.5 is not installed in another computer.(that is too big)

How can I create this executable “2 steps version” wkhtmltopdf for another computer?

If you have any idea, please tell me how to work.
Thanks a lot.

**Comment by mcmc8680** [comment]
I already fix this problem in ubuntu.
The file "wkhtmltopdf" can not work because the references of libraries are wrong.
Just execute the following command to fix.
`export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:./` 

So I write a simple shell script "topdf.sh" for me.
`export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:./`
`./wkhtmltopdf ${1} ${2}`

But the problem still exists in Mac (OS X 10.11.6).
If anyone has any idea, please tell me how to work.
Thanks a lot.

**Comment by iman4000** [comment]
@mcmc8680 where are you exactly when run " ./ "? which directory i mean?

**Comment by ashkulz** [comment]
Not really sure what you mean, please reopen if you can provide more information.
