### ISSUE TITLE
Links pointing to wrong paths.

### ISSUE THREAD

**Issue by Manoj51** [wkhtmltopdf/wkhtmltopdf#3308]
I created a pdf file from the [html file](https://drive.google.com/open?id=0B6SVqGaVrTblSGFEUW1CRlFxTWs).

Some of the links in the pdf file are pointing to wrong paths. Under the section "Illustration attributions"  in the pdf file, the links "going to buy a book 1", "jaya bachchan", "Moru24" all point to the link "Nina Sabnani". [Incorrect.pdf](https://github.com/wkhtmltopdf/wkhtmltopdf/files/729200/Incorrect.pdf)

If I modify some text before it (from "cover page" to "cover page page"), the links are pointing to correct paths. [Correct.pdf](https://github.com/wkhtmltopdf/wkhtmltopdf/files/729203/Correct.pdf)

I am confused as what exactly might be the problem here.

Thanks.

**Comment by PhilterPaper** [comment]
I see you have a URL Query String of **search[query]=**. Is that a legal URL? Even if it is, it's possible that it's a recent addition and is confusing WebKit. Also, you could try replacing **jaya%20bachchan** with **jaya+bachchan** and see if that makes any difference.

**Comment by Tomsgu** [comment]
Closing as there is no feedback since 2017.
