### ISSUE TITLE
Two issue errors when open wkhtmltopdf.pro by using QT5.5 on Windows.

### ISSUE THREAD

**Issue by mcmc8680** [wkhtmltopdf/wkhtmltopdf#3309]
Hello,

I already download wkhtmltopdf source code in the different OSs.
And, in Mac and ubuntu, I use QT5.5 open this wkhtmltopdf.pro to build this executable file in release folder.
But, when I Build wkhtmltopdf.pro by using QT5.5 in Window 10(64-bit),
QT show me error message in issue.

```
cannot find -lwkhtmltox
error:Id returned 1 exit status
```
The kit is Qt5.5.1-MinGW_32bit.

I try to fix this problem all day, but I fail.
If you have any idea, please tell me how to work.
Thanks a lot.

**Comment by alloylab** [comment]
is this still an issue on 0.12.5?

**Comment by ashkulz** [comment]
The currently recommended approach is to use the wkhtmltopdf/packaging repository. Please open an issue there if you want to discuss it further.
