### ISSUE TITLE
Provide later version of wkhtmltopdf rpm than 0.12.1 for centos

### ISSUE THREAD

**Issue by greglint** [wkhtmltopdf/wkhtmltopdf#3310]
Hi,

The latest version of the wkhtmltopdf rpm is 0.12.1: http://download.gna.org/wkhtmltopdf/0.12/0.12.2.1/

Could the rpms be updated for other versions too, like 0.12.4? http://download.gna.org/wkhtmltopdf/0.12/0.12.4/

Thanks.

**Comment by elico** [comment]
Is this good?

http://ngtech.co.il/repo/centos/7/x86_64/wkhtmltox-0.12.4-1.el7.centos.x86_64.rpm

**Comment by CloCkWeRX** [comment]
@elico if you could perhaps provide the steps to go from .tar.gz to .rpm, that might work - we can maybe turn that into a pull request and add in something like Travis, so its easy to produce releasable artifacts.

**Comment by elico** [comment]
@CloCkWeRX What I did was to write this RPM spec which is not the regular  way:
http://ngtech.co.il/repo/centos/7/SRPMS/wkhtmltox-0.12.4-1.el7.centos.src.rpm

Providing enough time I would be able to create a docker\jenkins job that will do that.

**Comment by Tomsgu** [comment]
`0.12.5` binary exists for Centos. See https://wkhtmltopdf.org/downloads.html.
