### ISSUE TITLE
Not rendered the separator between tags <th>

### ISSUE THREAD

**Issue by semenov-k** [wkhtmltopdf/wkhtmltopdf#3316]
Hello. When converting to pdf not rendered the separator between tags <th>,  that has the attribute rowspan = 2. Examples below.

wkhtmltopdf    0.12.1-2
wkhtmltopdf    0.12.2.4

[src.zip](https://github.com/wkhtmltopdf/wkhtmltopdf/files/736802/src.zip)

**Comment by PhilterPaper** [comment]
Does it work any differently for `<td>` elements (i.e., the problem is specifically with `<th>`)? Does removing the `border-collapse` attribute make any difference? In either case, is the problem only when `rowspan` is used?

**Comment by 22140505** [comment]
@semenov-k 
Hello, I have the same problem as you. Have you solved it? How to solve it? Thank you very much.

**Comment by semenov-k** [comment]
@22140505 
Hi! I just downgrade version of the library to previous. I forgot which exactly the version because it was 2 years ago).

**Comment by 22140505** [comment]
I've found a simple way.
Replace "border-collapse: collapse" with other styles.
