### ISSUE TITLE
wkhtmltopimage delivers a small white picture for http://www.caballoscriollos.com.uy/  

### ISSUE THREAD

**Issue by kklepper** [wkhtmltopdf/wkhtmltopdf#3317]
Windows 10 pro 64, default install, default command

```
D:\>"C:\Program Files\wkhtmltopdf\bin\wkhtmltoimage.exe" http://www.caballoscriollos.com.uy/ d:/tmp/caballoscriollos.jpg
Loading page (1/2)
Rendering (2/2)
Done
```
Loading is very fast -- which is unprobable as this uy address loads very slowly. Result is

![caballos](https://cloud.githubusercontent.com/assets/6130319/22406953/09705e24-e65d-11e6-813e-ecfccd626336.PNG)

Should be something like (taken from https://web-capture.net/de/convert.php)

![caballoscriollos](https://cloud.githubusercontent.com/assets/6130319/22406980/b3d81ff0-e65d-11e6-91b8-82e5490e7a04.jpg)

**Comment by alloylab** [comment]
We are closing this out since we haven't heard from you. If you are still having this issue please feel free to re-open it. Thanks.
