### ISSUE TITLE
Header is overlapping page content on the 2nd page and beyond

### ISSUE THREAD

**Issue by Albin-John** [wkhtmltopdf/wkhtmltopdf#3319]
Header is overlapping page content on the 2nd page and beyond ?

**Comment by milarepa** [comment]
I have this issue also, been trying to satisfy it with CSS, but have not found a solid solution...

**Comment by PhilterPaper** [comment]
Page header or table heading? Table headings (thead) overlapping rows is a long-known problem, but I haven't heard of page headers or footers overlapping body text. Can you give some examples so it could be reproduced? What versions of everything, and what command line?

**Comment by milarepa** [comment]
I have actually solved this problem, thanks for your quick response. I was mis-using the header-spacing as the pdf export code well embedded in a custom application and there were a lot of other things happening around the wkhtmltopdf operations. All is working as expected now, thanks.
:)

**Comment by mostafafcis** [comment]
I have this issue also,  but have not found a solid solution...headers overlapping when using rowspan 
can you help me

**Comment by PhilterPaper** [comment]
@mostafafcis are you talking about _table_ headings (`<thead>`) overlapping row content, or _page_ headers overlapping page content? The first case has been reported and discussed many times -- you should be asking in one of those discussions, rather than hijacking another one. If it _is_ a page header, the discussion should be here.

**Comment by mostafafcis** [comment]
@PhilterPaper try this i want to repeat header of table so row text overlapping into header. can you help me 
i am uisung latest version
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<body>
<style>
thead { display: table-header-group }
tfoot { display: table-row-group }
tr { page-break-inside: avoid }
thead tr th { border:1px solid;background-color:gray;height: 1.1cm; }
</style>
    <h1>Header</h1>
    <div>
        <span id="filterModeLabel" class="FilterMode">Show all</span>
        <table>
        <thead>
            <tr >
                <th>FirstName</th><th>LastName</th>
            </tr>
        </thead>
        <tbody>
            <tr>
<td> 
       

تعني البيئة المعيشية المستدامة، وتعني وفقاً للمعايير الدولية ترشيد استهلاك الموارد الطبيعية والتناغم مع البيئة بشكل يسمح باستدامة هذه الموارد، والإقلال من نسب التلوث لأقل حد ممكن، بما يسمح برفع جودة حياة المواطنين، في نفس الوقت الحفاظ على قاعدة الموارد اللازمة لحاجات الأجيال القادمة.<br>
	<br>
	وقد تضمنت الأهداف السبعة عشرة للتنمية المستدامة التي حددتها الأمم المتحدة خلال الفترة من 2015 إلى 2030، ستة أهداف ترتبط مباشرة بركيزة "البيئة المعيشية المستدامة"، وهي: المياه النظيفة والنظافة الصحية، طاقة نظيفة وبأسعار معقولة، مدن ومجتمعات محلية مستدامة، العمل المناخي، الحياة تحت الماء، الحياة في البر.<br>
	<br>
	وقد ضمنت الركيزة 4 برامج تنموية رئيسية هي:<br>
	<br>
	* الحفاظ على سلامة البيئة الهوائية<br>
	<br>
	* تحسين كفاءة إدارة المخلفات والنفايات<br>
	<br>
	* الاسراع في توفير الرعاية السكنية للمواطنين<br>
	<br>
	* توظيف الطاقات المتجددة &nbsp; تعني البيئة المعيشية المستدامة، وتعني وفقاً للمعايير الدولية ترشيد استهلاك الموارد الطبيعية والتناغم مع البيئة بشكل يسمح باستدامة هذه الموارد، والإقلال من نسب التلوث لأقل حد ممكن، بما يسمح برفع جودة حياة المواطنين، في نفس الوقت الحفاظ على قاعدة الموارد اللازمة لحاجات الأجيال القادمة.<br>
	<br>
	وقد تضمنت الأهداف السبعة عشرة للتنمية المستدامة التي حددتها الأمم المتحدة خلال الفترة من 2015 إلى 2030، ستة أهداف ترتبط مباشرة بركيزة "البيئة المعيشية المستدامة"، وهي: المياه النظيفة والنظافة الصحية، طاقة نظيفة وبأسعار معقولة، مدن ومجتمعات محلية مستدامة، العمل المناخي، الحياة تحت الماء، الحياة في البر.<br>
	<br>
	وقد ضمنت الركيزة 4 برامج تنموية رئيسية هي:<br>
	<br>
	* الحفاظ على سلامة البيئة الهوائية<br>
	ببابابابل<br>
	* تحسين كفاءة إدارة المخلفات والنفايات<br>
	<br>
	* الاسراع في توفير الرعاية السكنية للمواطنين<br>
	<br>
	* توظيف الطاقات المتجددة

            
         
        
           
تعني البيئة المعيشية المستدامة، وتعني وفقاً للمعايير الدولية ترشيد استهلاك الموارد الطبيعية والتناغم مع البيئة بشكل يسمح باستدامة هذه الموارد، والإقلال من نسب التلوث لأقل حد ممكن، بما يسمح برفع جودة حياة المواطنين، في نفس الوقت الحفاظ على قاعدة الموارد اللازمة لحاجات الأجيال القادمة.<br>
	<br>
	وقد تضمنت الأهداف السبعة عشرة للتنمية المستدامة التي حددتها الأمم المتحدة خلال الفترة من 2015 إلى 2030، ستة أهداف ترتبط مباشرة بركيزة "البيئة المعيشية المستدامة"، وهي: المياه النظيفة والنظافة الصحية، طاقة نظيفة وبأسعار معقولة، مدن ومجتمعات محلية مستدامة، العمل المناخي، الحياة تحت الماء، الحياة في البر.<br>
	<br>
	وقد ضمنت الركيزة 4 برامج تنموية رئيسية هي:<br>
	<br>
	* الحفاظ على سلامة البيئة الهوائية<br>
	<br>
	* تحسين كفاءة إدارة المخلفات والنفايات<br>
	<br>
	* الاسراع في توفير الرعاية السكنية للمواطنين<br>
	<br>
	* توظيف الطاقات المتجددة &nbsp; تعني البيئة المعيشية المستدامة، وتعني وفقاً للمعايير الدولية ترشيد استهلاك الموارد الطبيعية والتناغم مع البيئة بشكل يسمح باستدامة هذه الموارد، والإقلال من نسب التلوث لأقل حد ممكن، بما يسمح برفع جودة حياة المواطنين، في نفس الوقت الحفاظ على قاعدة الموارد اللازمة لحاجات الأجيال القادمة.<br>
	<br>
	وقد تضمنت الأهداف السبعة عشرة للتنمية المستدامة التي حددتها الأمم المتحدة خلال الفترة من 2015 إلى 2030، ستة أهداف ترتبط مباشرة بركيزة "البيئة المعيشية المستدامة"، وهي: المياه النظيفة والنظافة الصحية، طاقة نظيفة وبأسعار معقولة، مدن ومجتمعات محلية مستدامة، العمل المناخي، الحياة تحت الماء، الحياة في البر.<br>
	<br>
	وقد ضمنت الركيزة 4 برامج تنموية رئيسية هي:<br>
	<br>
	* الحفاظ على سلامة البيئة الهوائية<br>
	ببابابابل<br>
	* تحسين كفاءة إدارة المخلفات والنفايات<br>
	<br>
	* الاسراع في توفير الرعاية السكنية للمواطنين<br>
	<br>
	* توظيف الطاقات المتجددة

            
         
        
           
تعني البيئة المعيشية المستدامة، وتعني وفقاً للمعايير الدولية ترشيد استهلاك الموارد الطبيعية والتناغم مع البيئة بشكل يسمح باستدامة هذه الموارد، والإقلال من نسب التلوث لأقل حد ممكن، بما يسمح برفع جودة حياة المواطنين، في نفس الوقت الحفاظ على قاعدة الموارد اللازمة لحاجات الأجيال القادمة.<br>
	<br>
	وقد تضمنت الأهداف السبعة عشرة للتنمية المستدامة التي حددتها الأمم المتحدة خلال الفترة من 2015 إلى 2030، ستة أهداف ترتبط مباشرة بركيزة "البيئة المعيشية المستدامة"، وهي: المياه النظيفة والنظافة الصحية، طاقة نظيفة وبأسعار معقولة، مدن ومجتمعات محلية مستدامة، العمل المناخي، الحياة تحت الماء، الحياة في البر.<br>
	<br>
	وقد ضمنت الركيزة 4 برامج تنموية رئيسية هي:<br>
	<br>
	* الحفاظ على سلامة البيئة الهوائية<br>
	<br>
	* تحسين كفاءة إدارة المخلفات والنفايات<br>
	<br>
	* الاسراع في توفير الرعاية السكنية للمواطنين<br>
	<br>
	* توظيف الطاقات المتجددة &nbsp; تعني البيئة المعيشية المستدامة، وتعني وفقاً للمعايير الدولية ترشيد استهلاك الموارد الطبيعية والتناغم مع البيئة بشكل يسمح باستدامة هذه الموارد، والإقلال من نسب التلوث لأقل حد ممكن، بما يسمح برفع جودة حياة المواطنين، في نفس الوقت الحفاظ على قاعدة الموارد اللازمة لحاجات الأجيال القادمة.<br>
	<br>
	وقد تضمنت الأهداف السبعة عشرة للتنمية المستدامة التي حددتها الأمم المتحدة خلال الفترة من 2015 إلى 2030، ستة أهداف ترتبط مباشرة بركيزة "البيئة المعيشية المستدامة"، وهي: المياه النظيفة والنظافة الصحية، طاقة نظيفة وبأسعار معقولة، مدن ومجتمعات محلية مستدامة، العمل المناخي، الحياة تحت الماء، الحياة في البر.<br>
	<br>
	وقد ضمنت الركيزة 4 برامج تنموية رئيسية هي:<br>
	<br>
	* الحفاظ على سلامة البيئة الهوائية<br>
	ببابابابل<br>
	* تحسين كفاءة إدارة المخلفات والنفايات<br>
	<br>
	* الاسراع في توفير الرعاية السكنية للمواطنين<br>
	<br>
	* توظيف الطاقات المتجددة

            
         
        
           

 </td>

<td >Test</td></tr>
           
        </tbody>
<tfoot><tr><td></td></tr></tfoot>
    </table>
    </div>
</body>
</html>

**Comment by PhilterPaper** [comment]
As I said, there are many bug reports open already regarding a thead table header overlapping a row's data. Please read through them and continue your questions in one of those threads. This one appears to be for a _page header_ overlapping page text, due to improper use of header-spacing.
