### ISSUE TITLE
Tool crashes when trying to convert to PDF

### ISSUE THREAD

**Issue by erezpaz** [wkhtmltopdf/wkhtmltopdf#3321]
Hi

When i am trying to run wkhtmltopdf  and convert my HTML to PDF in latest version, in 89% i get an error from windows that wkhtmltopdf stop working and need to close. I tried it on difrent servers and got same results (Windows 10 and Windows 2012). I did see that is will work ok if I will put HTML stand alone without ist css and scripts.

C:\Users\erezp>"C:\Program Files (x86)\wkhtmltopdf\bin\wkhtmltopdf.exe" "C:\Stuf
f\Dropbox\EnsureDR\EnsureDR\Working Files\EDRFC\TMP\NasRpt.html" "C:\Stuff\Dropb
ox\EnsureDR\EnsureDR\Working Files\EDRFC\TMP\NasRpt.pdf"
Loading pages (1/6)
QFont::setPixelSize: Pixel size <= 0 (0)                     ] 49%
QNetworkAccessFileBackendFactory: URL has no schema set, use file:// for files
QNetworkAccessFileBackendFactory: URL has no schema set, use file:// for files
QNetworkAccessFileBackendFactory: URL has no schema set, use file:// for files
QNetworkAccessFileBackendFactory: URL has no schema set, use file:// for files
QNetworkAccessFileBackendFactory: URL has no schema set, use file:// for files
QNetworkAccessFileBackendFactory: URL has no schema set, use file:// for files
[=====================================================>      ] 89%

**Comment by jgreaves8** [comment]
@erezpaz Check for relative CSS or image links and change them to absolutes if you can. For CSS use a CDN etc.

**Comment by Tomsgu** [comment]
Please try a new version of wkhtmltopdf. It should give you more information about the errors. Anyway without more information we can't reproduce this issue. Please feel free to re-open it if you have more details.

**Comment by vpalmer** [comment]
Posting here in case others happen across this thread -- I had the `QNetworkAccessFileBackendFactory: URL has no schema set, use file:// for files` error too, and eventually figured out that it was being caused by embedded video content in the HTML I was extracting.
