### ISSUE TITLE
0.12.4 not rendering CODE tags as monospaced on Red Hat 7.2

### ISSUE THREAD

**Issue by harpingon** [wkhtmltopdf/wkhtmltopdf#3322]
Simple HTML file:

< HTML>
< HEAD>
< /HEAD>
< BODY>
< CODE>
Hello world
< /CODE>
< /BODY>
< /HTML>

No stylesheets involved - I had to add extra SPACE character after the opening tag to prevent the html being rendered in the issue page, but you get the idea of the html.

Renders as proportional using 0.12.4, but when using 0.11.0rc1 it renders correctly as fixed font

PDF information from 0.11.0rc1 shows the use of LiberationMono as a font,  in 0.12.4 it shows NimbusSanL-Regu

Following liberation fonts are installed:
`fc-list | grep Liberation
/usr/share/fonts/liberation/LiberationSerif-Italic.ttf: Liberation Serif:style=Italic
/usr/share/fonts/liberation/LiberationSans-Bold.ttf: Liberation Sans:style=Bold
/usr/share/fonts/liberation/LiberationMono-Bold.ttf: Liberation Mono:style=Bold
/usr/share/fonts/liberation/LiberationSerif-BoldItalic.ttf: Liberation Serif:style=Bold Italic
/usr/share/fonts/liberation/LiberationSerif-Regular.ttf: Liberation Serif:style=Regular
/usr/share/fonts/liberation/LiberationSerif-Bold.ttf: Liberation Serif:style=Bold
/usr/share/fonts/liberation/LiberationMono-Italic.ttf: Liberation Mono:style=Italic
/usr/share/fonts/liberation/LiberationSans-BoldItalic.ttf: Liberation Sans:style=Bold Italic
/usr/share/fonts/liberation/LiberationMono-Regular.ttf: Liberation Mono:style=Regular
/usr/share/fonts/liberation/LiberationSans-Italic.ttf: Liberation Sans:style=Italic
/usr/share/fonts/liberation/LiberationMono-BoldItalic.ttf: Liberation Mono:style=Bold Italic
/usr/share/fonts/liberation/LiberationSans-Regular.ttf: Liberation Sans:style=Regular
`

Command line invocation is

wkhtmltopdf simple.html simple.pdf

Where simple.html is the above HTML file.

strace output from version 11:
`strace -F -f -o foo ./wkhtmltopdf-11 simple.html simple.pdf

grep -i liberation foo
6760  access("/etc/fonts/conf.d/59-liberation-mono.conf", R_OK) = 0
6760  stat("/etc/fonts/conf.d/59-liberation-mono.conf", {st_mode=S_IFREG|0644, st_size=482, ...}) = 0
6760  open("/etc/fonts/conf.d/59-liberation-mono.conf", O_RDONLY|O_CLOEXEC) = 9
6760  access("/etc/fonts/conf.d/59-liberation-sans.conf", R_OK) = 0
6760  stat("/etc/fonts/conf.d/59-liberation-sans.conf", {st_mode=S_IFREG|0644, st_size=832, ...}) = 0
6760  open("/etc/fonts/conf.d/59-liberation-sans.conf", O_RDONLY|O_CLOEXEC) = 9
6760  access("/etc/fonts/conf.d/59-liberation-serif.conf", R_OK) = 0
6760  stat("/etc/fonts/conf.d/59-liberation-serif.conf", {st_mode=S_IFREG|0644, st_size=485, ...}) = 0
6760  open("/etc/fonts/conf.d/59-liberation-serif.conf", O_RDONLY|O_CLOEXEC) = 9
6760  stat("/usr/share/fonts/liberation", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
6760  open("/usr/share/fonts/liberation", O_RDONLY|O_CLOEXEC) = 7
6760  lstat("/usr/share/fonts/liberation/LiberationMono-Regular.ttf", {st_mode=S_IFREG|0644, st_size=108476, ...}) = 0
6760  open("/usr/share/fonts/liberation/LiberationMono-Regular.ttf", O_RDONLY) = 8
6760  lstat("/usr/share/fonts/liberation/LiberationSans-Regular.ttf", {st_mode=S_IFREG|0644, st_size=139628, ...}) = 0
6760  open("/usr/share/fonts/liberation/LiberationSans-Regular.ttf", O_RDONLY) = 8
`
Shows LiberationMono being opened

But on 0.12.4:
`strace -F -f -o foo ./wkhtmltopdf-12 simple.html simple.pdf

grep -i liberation foo
6770  access("/etc/fonts/conf.d/59-liberation-mono.conf", R_OK) = 0
6770  stat("/etc/fonts/conf.d/59-liberation-mono.conf", {st_mode=S_IFREG|0644, st_size=482, ...}) = 0
6770  open("/etc/fonts/conf.d/59-liberation-mono.conf", O_RDONLY|O_CLOEXEC) = 9
6770  access("/etc/fonts/conf.d/59-liberation-sans.conf", R_OK) = 0
6770  stat("/etc/fonts/conf.d/59-liberation-sans.conf", {st_mode=S_IFREG|0644, st_size=832, ...}) = 0
6770  open("/etc/fonts/conf.d/59-liberation-sans.conf", O_RDONLY|O_CLOEXEC) = 9
6770  access("/etc/fonts/conf.d/59-liberation-serif.conf", R_OK) = 0
6770  stat("/etc/fonts/conf.d/59-liberation-serif.conf", {st_mode=S_IFREG|0644, st_size=485, ...}) = 0
6770  open("/etc/fonts/conf.d/59-liberation-serif.conf", O_RDONLY|O_CLOEXEC) = 9
6770  stat("/usr/share/fonts/liberation", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
6770  open("/usr/share/fonts/liberation", O_RDONLY|O_CLOEXEC) = 7
`

The font appears not to be opened.

There are no more font packages I can install on Red Hat 7. 

[simple.html.txt](https://github.com/wkhtmltopdf/wkhtmltopdf/files/747588/simple.html.txt)

**Comment by alloylab** [comment]
is this still an issue on 0.12.5?

**Comment by alloylab** [comment]
We are closing this out since we haven't heard from you. If you are still having this issue please feel free to re-open it. Thanks.
