### ISSUE TITLE
.BuildPdf(ControllerContext); Load Error Handling

### ISSUE THREAD

**Issue by anacrust** [wkhtmltopdf/wkhtmltopdf#3323]
I appreciate any help. I'm trying to convert a view to PDF and then stream that as an email attachment without saving it to the DB.

I keep getting an error at the line:  var applicationPDFData = actionPDF.BuildPdf(this.ControllerContext);
I've also tried: byte[] applicationPDFData = actionPDF.BuildPdf(ControllerContext);

If I do a GET: http://localhost:54324/Trade/TradePDF/17
the PDF shows up fine.

If I use the same code below but do say a:
var actionPDF = new ActionAsPdf("Index") //some route values)
The code works fine. 

Here's a chunk of my code:
```
var actionPDF = new ActionAsPdf("TradePDF", new { id = id }) //some route values)
{
  FileName = IdStr + ".pdf",
  PageSize = Size.A4,
  PageOrientation = Rotativa.Options.Orientation.Portrait,
  PageMargins = { Left = 1, Right = 1 }
};
//byte[] applicationPDFData = actionPDF.BuildPdf(ControllerContext);
 var applicationPDFData = actionPDF.BuildPdf(this.ControllerContext);
 //create the attachment from a stream. Be sure to name the data with a file and 
 //media type that is respective of the data
Stream stream = new MemoryStream(applicationPDFData);
Attachment data = new Attachment(stream, "application/pdf");
mail.Attachments.Add(data);
```

        public ActionResult TradePDF(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Trade trade = db.Trades.Find(id);
            if (trade == null)
            {
                return HttpNotFound();
            }
            return new ViewAsPdf(trade);
        }

Error:
Error: Failed loading page http://localhost:54324/trade/TradePDF/18 (sometimes it will work just to ignore this error with --load-error-handling ignore)
Exit with code 1, due to unknown error.

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.Exception: Error: Failed loading page http://localhost:54324/trade/TradePDF/18 (sometimes it will work just to ignore this error with --load-error-handling ignore)
Exit with code 1, due to unknown error.

Stack Trace:
[Exception: Error: Failed loading page http://localhost:54324/Trade/TradePDF/17 (sometimes it will work just to ignore this error with --load-error-handling ignore)
Exit with code 1, due to unknown error.
]
   Rotativa.WkhtmltopdfDriver.Convert(String wkhtmltopdfPath, String switches, String html) +1007
   Rotativa.WkhtmltopdfDriver.Convert(String wkhtmltopdfPath, String switches) +63
   Rotativa.AsPdfResultBase.CallTheDriver(ControllerContext context) +102
   Rotativa.AsPdfResultBase.BuildPdf(ControllerContext context) +250
   Adactics.Controllers.<Confirm>d__10.MoveNext() in C:\Users\Matth\OneDrive\Documents\Visual Studio 2015\Projects\Adactics_CF0\Adactics\Adactics\Controllers\TradeController.cs:281
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +92
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +58
   System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() +28
   Adactics.Controllers.<Create>d__4.MoveNext() in C:\Users\Matth\OneDrive\Documents\Visual Studio 2015\Projects\Adactics_CF0\Adactics\Adactics\Controllers\TradeController.cs:110
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +92
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +58
   System.Web.Mvc.Async.TaskAsyncActionDescriptor.EndExecute(IAsyncResult asyncResult) +97
   System.Web.Mvc.Async.<>c__DisplayClass37.<BeginInvokeAsynchronousActionMethod>b__36(IAsyncResult asyncResult) +17
   System.Web.Mvc.Async.WrappedAsyncResult`1.CallEndDelegate(IAsyncResult asyncResult) +10
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult) +32
   System.Web.Mvc.Async.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d() +50
   System.Web.Mvc.Async.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f() +225
   System.Web.Mvc.Async.<>c__DisplayClass33.<BeginInvokeActionMethodWithFilters>b__32(IAsyncResult asyncResult) +10
   System.Web.Mvc.Async.WrappedAsyncResult`1.CallEndDelegate(IAsyncResult asyncResult) +10
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult) +34
   System.Web.Mvc.Async.<>c__DisplayClass2b.<BeginInvokeAction>b__1c() +26
   System.Web.Mvc.Async.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult) +100
   System.Web.Mvc.Async.WrappedAsyncResult`1.CallEndDelegate(IAsyncResult asyncResult) +10
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult) +27
   System.Web.Mvc.Controller.<BeginExecuteCore>b__1d(IAsyncResult asyncResult, ExecuteCoreState innerState) +13
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +29
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
   System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult) +36
   System.Web.Mvc.Controller.<BeginExecute>b__15(IAsyncResult asyncResult, Controller controller) +12
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +22
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
   System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult) +26
   System.Web.Mvc.Controller.System.Web.Mvc.Async.IAsyncController.EndExecute(IAsyncResult asyncResult) +10
   System.Web.Mvc.MvcHandler.<BeginProcessRequest>b__5(IAsyncResult asyncResult, ProcessRequestState innerState) +21
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +29
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
   System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult) +28
   System.Web.Mvc.MvcHandler.System.Web.IHttpAsyncHandler.EndProcessRequest(IAsyncResult result) +9
   System.Web.CallHandlerExecutionStep.OnAsyncHandlerCompletion(IAsyncResult ar) +129

**Comment by luzfcb** [comment]
Would probably be useful if you report which version of wkhtmltopdf you are using.

```
wkhtmltopdf --version
```

**Comment by anacrust** [comment]
Version: wkhtmltopdf 0.12.2.1 (with patched qt)
Downloaded via Nuget: Rotativa v1.6.4
Ty!

**Comment by anacrust** [comment]
Hello,

I apologize.
Version: wkhtmltopdf 0.12.2.1 (with patched qt)
Downloaded via Nuget: Rotativa v1.6.4
Ty!

Thank you,
Matt Bymaster
2822 SW 4th St.
Boynton Beach, FL 33435
Email: mattbymaster@gmail.com
Cell: 561-601-0952
