### ISSUE TITLE
it works on server but the result is deformed on clients 

### ISSUE THREAD

**Issue by jnoruzi** [wkhtmltopdf/wkhtmltopdf#3325]
Hi there
wkhtmltopdf Version : 0.12.2.1
We switched to new server (Windows Server 2012 R2) ,without any change in our asp.net MVC application (we copied web site folder to new server and created website in IIS).
**but when trying to generate pdf on clients' PCs, the view is deformed and instead of 1 page, generates 2 page pdf.** 
**when trying on server (localhost) it works perfect but this problem is for clients.**
in our old server (Windows Server 2008) there was no any problem.
**what can be the reason?**

**Comment by alloylab** [comment]
is this still an issue on 0.12.5?

**Comment by alloylab** [comment]
We are closing this out since we haven't heard from you. If you are still having this issue please feel free to re-open it. Thanks.
