### ISSUE TITLE
Font unicode wkhtmltopdf 

### ISSUE THREAD

**Issue by thomike** [wkhtmltopdf/wkhtmltopdf#3326]
can you help mejust want to render html to pdf but when have unicode text not read and just show 􀀀􀀀-􀀀􀀀􀀀􀀀􀀀􀀀 􀀀􀀀􀀀􀀀􀀀 􀀀􀀀 􀀀 􀀀􀀀􀀀􀀀􀀀􀀀 

![ccccccc](https://cloud.githubusercontent.com/assets/25576856/22635318/2bca37de-ec65-11e6-986f-f450aba91226.PNG)

The unicode font japanese, fullwidth, Math bold, Math bold italic please help
My wkhtmltopdf run by windows 7 32bit

**Comment by alloylab** [comment]
is this still an issue on 0.12.5?

**Comment by alloylab** [comment]
We are closing this out since we haven't heard from you. If you are still having this issue please feel free to re-open it. Thanks.

**Comment by ClickerVinod** [comment]
i have same issue im using https://github.com/barryvdh/laravel-snappy with laravel  and this package composer require h4cc/wkhtmltopdf-amd64 0.12.x

![image](https://user-images.githubusercontent.com/17634341/77184474-e7fef900-6af5-11ea-904d-e91ae66a1bb4.png)
