### ISSUE TITLE
Help Author, Subject, Keyword On Meta

### ISSUE THREAD

**Issue by jeacksmcione** [wkhtmltopdf/wkhtmltopdf#3330]
can you help me for setting Author, Subject, Keyword On Meta PDF?
on my case just show tittle for the pdf im run wkhtmltopdf 0.12.3.2 (with patched qt) run by windows 7

thanks for your help

**Comment by alloylab** [comment]
is this still an issue on 0.12.5?

**Comment by alloylab** [comment]
We are closing this out since we haven't heard from you. If you are still having this issue please feel free to re-open it. Thanks.
