### ISSUE TITLE
Failed loading page if file has no typical extension

### ISSUE THREAD

**Issue by naitsirch** [wkhtmltopdf/wkhtmltopdf#3331]
I have got this error

    wkhtmltopdf /var/tmp/plpATT4SC /var/tmp/plpp7j7b5
    Loading page (1/2)
    Error: Failed loading page file:///var/tmp/plpATT4SC (sometimes it will work just to ignore this error with --load-error-handling ignore)
    Exit with code 1, due to unknown error.

But the same works if I add the correct file extensions:

    wkhtmltopdf /var/tmp/plpATT4SC.html /var/tmp/plpp7j7b5.pdf
    Loading page (1/2)
    Printing pages (2/2)                                               
    Done

It would be nice if this behaviour could be fixed (loading all extensions or even without file extension) or at least be documented.

I saw this [stackoverflow answer](http://stackoverflow.com/a/6558147/1119601) which helped me to fix it.

**Comment by alloylab** [comment]
is this still an issue on 0.12.5?

**Comment by naitsirch** [comment]
Sorry I do not have the environment anymore to test this issue. If you cannot reproduce it anymore, just close it ;-)

**Comment by J-N-K** [comment]
I can confirm that this is still a problem with `wkhtmltopdf 0.12.5 (with patched qt)` installed yesterday from `wkhtmltox_0.12.5-1.stretch_amd64.deb` .

```
$htmlfile = tempnam('/tmp', 'IMSH');
$pdffile = tempnam('/tmp', 'IMSP');

$handle = fopen($htmlfile, 'w');
fwrite($handle, $html);
fclose($handle);

shell_exec("xvfb-run wkhtmltopdf --disable-smart-shrinking $htmlfile $pdffile");
```

should work, but gfenerates a load error.

```
$htmlfile = tempnam('/tmp', 'IMSH').'.html';
$pdffile = tempnam('/tmp', 'IMSP');

$handle = fopen($htmlfile, 'w');
fwrite($handle, $html);
fclose($handle);

shell_exec("xvfb-run wkhtmltopdf --disable-smart-shrinking $htmlfile $pdffile");
```

works like a charm.

**Comment by jneves** [comment]
Can also confirm on 0.12.6

**Comment by ashkulz** [comment]
So, you have to use a proper extension for local files. When you access via HTTP, you get the `Content-Type` HTTP header which tells wkhtmltopdf that this is HTML. With a local filename, the extension does that job -- just trying to parse any random filename doesn't work with QtWebKit. While this limitation can probably be removed, it's much simpler to generate a proper extension.

**Comment by jneves** [comment]
Maybe a specific error in that case?

If you're documenting the behaviour, a recommendation to "always add an extension to temporary file names" would be welcome.

Thanks a lot for your work.

**Comment by vicmortelmans** [comment]
just to note: I bumpted into this same issue, because I pipe the HTML into wkhtmltopdf (using `-` in the command line i.o. the filename)
