### ISSUE TITLE
Formatting Problem with Fraction

### ISSUE THREAD

**Issue by khkremer** [wkhtmltopdf/wkhtmltopdf#3332]
I have a document that uses percentages with fractions. The HTML code comes out of a publishing system, so I don't have any control over how things are formatted. The string "33 1/3%" occurs a few times in the document, and there seems to be a variation in how close the "1/3" part is to the "33" - in some instances, the two elements are actually overlapping. I cannot share the original document, but I was able to create "pseudo-lorem-ipsum" version of the portion of the document that triggers this problem. 

This happens with both 0.12.3 and 0.12.4 on a Mac running Mac OS X 10.11.6.

Here is a screen shot of two instances of this percentage:

![2017-02-10_12-10-55](https://cloud.githubusercontent.com/assets/7128773/22837040/ebcc0380-ef8c-11e6-8a25-377defd31316.png)

The HTML  and PDF files are here: 

[percentage.pdf](https://github.com/wkhtmltopdf/wkhtmltopdf/files/767384/percentage.pdf)
[percentage.html.zip](https://github.com/wkhtmltopdf/wkhtmltopdf/files/767386/percentage.html.zip)

I tried to verify this on Windows as well, but it looks like I am running into issue #3260 and all bets are off regarding what's right and what's wrong.

**Comment by alloylab** [comment]
is this still an issue on 0.12.5?

**Comment by alloylab** [comment]
We are closing this out since we haven't heard from you. If you are still having this issue please feel free to re-open it. Thanks.
