### ISSUE TITLE
Superscript/Subscript on table page split headers 

### ISSUE THREAD

**Issue by boyddotee** [wkhtmltopdf/wkhtmltopdf#3336]
I'm experiencing an issue with subscript &lt;sub&gt; and superscript &lt;sup&gt;, on tables that span multiple pages with the desired table headers being copied page to page as expected but the above mentioned content disappears. Using wkhtmltopdf 0.12.4 and 0.12.3 running on Windows 64bit.

First thead

![image](https://cloud.githubusercontent.com/assets/25767851/22926654/787f7b70-f2a5-11e6-90f9-5c97e04ea3a6.png)

at Split

![image](https://cloud.githubusercontent.com/assets/25767851/22926709/bbe38eec-f2a5-11e6-9d55-939cfe1c801d.png)

Does anyone know a solution to this?

Many thanks,

Chris.

**Comment by alloylab** [comment]
is this still an issue on 0.12.5?

**Comment by alloylab** [comment]
We are closing this out since we haven't heard from you. If you are still having this issue please feel free to re-open it. Thanks.
