### ISSUE TITLE
wkhtmltopdf not woring without sslv3

### ISSUE THREAD

**Issue by tipo94** [wkhtmltopdf/wkhtmltopdf#3337]
I removed sslv3 from my site and i cannot load pdf file with wkhtmltopdf anymore. As soon as I put back sslv3 eveything work fine. I tried with few versions of wkhtmltopdf including the last one available for download but it is not working with any of the versions I tried.

**Comment by alloylab** [comment]
is this still an issue on 0.12.5?

**Comment by alloylab** [comment]
We are closing this out since we haven't heard from you. If you are still having this issue please feel free to re-open it. Thanks.
