### ISSUE TITLE
Multi-Page-Spanning Table: Header is Blank on all but First Page

### ISSUE THREAD

**Issue by ChristianTheMinery** [wkhtmltopdf/wkhtmltopdf#3338]
EDIT: Upon further investigation, I've determined that these empty rows are the `<thead>` element, displaying as entirely blank. The `<th>` elements are retaining their border styles, but not their background-color styles or any of the actual text within them. Very strange.

----------------------

I'm noticing a strange empty row being added after a page break SOMETIMES in my PDF's, but not always. I don't mean randomly - it always occurs in the same place - but I mean that similar rows, after page breaks, do NOT display this bizarre extra row.

![extra-row](https://cloud.githubusercontent.com/assets/23169829/22940655/b8521720-f2b0-11e6-9bac-6a6445fbad77.png)

What would be causing this?

**Comment by ChristianTheMinery** [comment]
Just a quick update: I've determined that these empty rows are the <thead> element trying to display on every page, but they appear to be for... some reason?

**Comment by alloylab** [comment]
is this still an issue on 0.12.5?

**Comment by alloylab** [comment]
We are closing this out since we haven't heard from you. If you are still having this issue please feel free to re-open it. Thanks.
