### ISSUE TITLE
Using with Highchart Problem

### ISSUE THREAD

**Issue by arikansm** [wkhtmltopdf/wkhtmltopdf#3339]
Hi,
i am using wkhtmltoimage for taking image of highchart chart. But there is a problem. 
In the browser, my page rendering normaly but wkhtmltoimage picture missing some details! 
Some lines doesnt displayed. I attached the outputs.

Command: wkhtmltoimage --enable-javascript --enable-local-file-access --no-stop-slow-scripts --width 804 --height 408 --quality 100 --javascript-delay 1000 hostaddress filepath

How can i solve this.

Thnx.

![in browser](https://cloud.githubusercontent.com/assets/25176945/22962719/6d08596c-f357-11e6-845b-be52c69c87be.PNG)
![wkhtmltoimage output](https://cloud.githubusercontent.com/assets/25176945/22962720/6d0879f6-f357-11e6-846c-7f29e91caee5.jpg)

**Comment by alloylab** [comment]
is this still an issue on 0.12.5?

**Comment by alloylab** [comment]
We are closing this out since we haven't heard from you. If you are still having this issue please feel free to re-open it. Thanks.
