### ISSUE TITLE
0.13 Run Headless on Linux

### ISSUE THREAD

**Issue by nathanielatom** [wkhtmltopdf/wkhtmltopdf#3341]
I couldn't find another issue that tracked this. 

What's the current state and what is still required for linux to run headless in 0.13?

**Comment by graingert** [comment]
@nathanielatom I think this is as far as it's got: https://github.com/wkhtmltopdf/wkhtmltopdf/issues/3089

**Comment by Tomsgu** [comment]
Closing as 0.13 is in alpha and not everything were ported. You can find more details here: https://github.com/wkhtmltopdf/wkhtmltopdf/blob/0.13/README.md
