### ISSUE TITLE
Export to PDF Fonts are very small

### ISSUE THREAD

**Issue by DarshanKsheerasagar** [wkhtmltopdf/wkhtmltopdf#3342]
Hello Sir,

After Exporting to PDF the PDF fonts are very small . What is the issue...? Is there Option for this..?

**Comment by khkremer** [comment]
Are you on a Mac? If so, take a look here #3241

**Comment by Jmuccigr** [comment]
Can someone close this and the other dupes of the font-size issue?

**Comment by DarshanKsheerasagar** [comment]
Reply is very late ....

**Comment by DarshanKsheerasagar** [comment]
Its Windows Operating System Win 7 64-bit
