### ISSUE TITLE
0.12.4  unpatched error

### ISSUE THREAD

**Issue by waniumesh25** [wkhtmltopdf/wkhtmltopdf#3344]
Hi 
I have downloaded latest version from http://wkhtmltopdf.org/downloads.html

I am trying to pass header & footer to generate Pdf but it gives me error  unpatched qt
command I am trying which am trying to run 
wkhtmltopdf -q  --header-html http://google.com --footer-html http://google.com http://google.com test.pdf

Error I am getting : 
The switch --header-html, is not support using unpatched qt, and will be ignored.The switch --footer-html, is not support using unpatched qt, and will be ignored.wkhtmltopdf:

Please can you help me where can I find latest version with qt patched 

Thanks,
Umesh

**Comment by YingzhiLin** [comment]
I meet the same problem at ubuntu linux 14.04 and I solved it with the step.

1. sudo apt-get install wkhtmltopdf -y
2. download from the the https://wkhtmltopdf.org/downloads.html, choose the stable linux x64 edition.
3. unpack it to the location you need and run it.

**Comment by alloylab** [comment]
is this still an issue on 0.12.5?

**Comment by Tomsgu** [comment]
This issue should be fixed in new versions.
