### ISSUE TITLE
Input tag in footer does not convert into PDF form fields.

### ISSUE THREAD

**Issue by ngockimhoang** [wkhtmltopdf/wkhtmltopdf#3353]
I tried to convert html to pdf using --enable-forms --footer-html footer.html. My footer.html contains the the <input> tag which i will populate with the page number.
However that <input> tag is converted into PDF form fields. So I cannot access it using some pdf edit library.

I am using version 0.12.4.

Is it really a bug or it's just by design?

**Comment by alloylab** [comment]
is this still an issue on 0.12.5?

**Comment by alloylab** [comment]
We are closing this out since we haven't heard from you. If you are still having this issue please feel free to re-open it. Thanks.
