### ISSUE TITLE
configuring PDF metadata from CLI

### ISSUE THREAD

**Issue by efx** [wkhtmltopdf/wkhtmltopdf#3355]
I was unable to find an answer for this in the documentation.

When I open the PDF using preview on mac, I see the following:
<img width="228" alt="screen shot 2017-02-25 at 8 34 21 am" src="https://cloud.githubusercontent.com/assets/472721/23331504/57f9d15a-fb35-11e6-8ffb-5c63acc45d8e.png">
I would like to customize these fields. Is this possible using flags passed to the `wkhtmltopdf` binary?

**Comment by ashkulz** [comment]
You can customize the title using `--title`, others are not supported right now.
