### ISSUE TITLE
table on multiple pages

### ISSUE THREAD

**Issue by remco-pc** [wkhtmltopdf/wkhtmltopdf#3356]
If i have a table which has to be on multiple pages, sometimes the text after the pagebreak on the firstline isnt positioned right. sometimes it is a bit to low and will be positioned on line 2 so the text messes up (line 1 and 2 throught eachother).

**Comment by glexey** [comment]
Second this.

**Comment by jeaye** [comment]
I'm having this issue as well. Page breaks can shift text in table cells downward, into the table cell underneath.

**Comment by PhilterPaper** [comment]
Are you talking about the `<thead>` text overlapping the first table row on the page? If so, this has been discussed many, many times before.

**Comment by remco-pc** [comment]
No i am talking about text in text, like it is not respecting a line-height style, so the first line of text is going through the second line. This happens only with the first line, but over several pages

**Comment by adamlytics** [comment]
I'm seeing what PhilterPaper is reporting, the <thead> text overlaps the first row of the next page, if the table bleeds over.  My fix is to remove <thead> when this is exporting the page to PDF.

**Comment by torinaki** [comment]
I had similar problem and it was solved with following CSS styles:
```html
<style type="text/css">
    table { page-break-inside:auto }
    tr    { page-break-inside:avoid; page-break-after:auto }
    thead { display:table-header-group }
    tfoot { display:table-footer-group }
</style>
```
http://stackoverflow.com/questions/1763639/how-to-deal-with-page-breaks-when-printing-a-large-html-table

**Comment by Tomsgu** [comment]
Duplicate of #1524.
Please read the this issue. You can find some workarounds that can improve a situation, since there is no real fix yet.

**Comment by superuser-chi** [comment]
Just remove the <thead>

**Comment by superuser-chi** [comment]
Remove the <thead> element that wraps the table header
