### ISSUE TITLE
UTF8 Special Characters in Form

### ISSUE THREAD

**Issue by ErnstTmp** [wkhtmltopdf/wkhtmltopdf#3361]
Hello,
I am trying to create a PDF form out of a html that can be filled out with UTF8 special characters, like öäü.
I am using wkhtmltopdf 0.12.4 on Ubuntu.

Command line is  --page-size A4 --print-media-type --minimum-font-size 12 --disable-smart-shrinking --enable-forms --encoding UTF8.

The UTF special chars can be entered in the form fields in the generated PDF, but as soon as the field is left, the chars vanish, see attached images.

Thank you very much for your help and kind regards

Ernst

![afterleaving](https://cloud.githubusercontent.com/assets/17543131/23451946/7f67c988-fe62-11e6-8498-7363de8c0961.png)
![entering](https://cloud.githubusercontent.com/assets/17543131/23451947/7f6884b8-fe62-11e6-91ef-4901ed4030e3.png)

**Comment by alloylab** [comment]
is this still an issue on 0.12.5?

**Comment by Tomsgu** [comment]
Closing as there is no response. The issue misses also a minimal test case so we can reproduce it. Please feel free to re-open it if you have more details.
