### ISSUE TITLE
Need for X server inside of docker container

### ISSUE THREAD

**Issue by jondoe1337** [wkhtmltopdf/wkhtmltopdf#3362]
When running inside of a docker container (Ubuntu 14.04.2 LTS with wkhtmltopdf 0.9.9-4) running the test: `wkhtmltopdf http://google.com google.pdf` 
Results in:
`wkhtmltopdf: cannot connect to X server`
Is this a version problem?

**Comment by efx** [comment]
@jondoe1337 You actually don't need to run a full Xserver within the container. You can simulate X connection using the xvfb tool. See my comment in 3119. For a base container to run xvfb checkout: https://github.com/metal3d/docker-xvfb

**Comment by jondoe1337** [comment]
We already used xfvb. But under certain circumstances xfvb crashes...

Anyways - saying that it is headless but it needs a framebuffer is irritating.

**Comment by efx** [comment]
interesting, would love to hear more about those details as we are prototyping using xvfb. The documentation might be somewhat misleading, but as I understand it this tool is not headless.

**Comment by jondoe1337** [comment]
Well the Readme.md says `These run entirely "headless" and do not require a display or display service.`

We run the xvfb inside of a node.js application which is started with our own Dockerfile. 

I would only suggest to add a note in the Readme.

**Comment by ashkulz** [comment]
@jondoe1337: you're probably running the distribution version of wkhtmltopdf, which doesn't use the patched Qt. You'll need to use the version from the downloads page.
