### ISSUE TITLE
Setting --custom-header with 'Host: domain.tld' does not change anything.

### ISSUE THREAD

**Issue by Ousret** [wkhtmltopdf/wkhtmltopdf#3365]
### Issue
Exit with code 1 due to network error: ContentNotFoundError

### Context
My website domain name is also my reverse dns. So getting anything from domain.tld will return 404.
So, in order to fix it I've to set Host: domain.tld 

### wget
wget --header "Host: domain.tld" http://domain.tld/target-ressource.html will work.
wget http://domain.tld/target-ressource.html won't work.

Any help would be very much appreciated :)
Thank.

**Comment by ashkulz** [comment]
That's a very weird setup. Do you have an example location, because the Host header is set automatically most of the time?

**Comment by Ousret** [comment]
Hi,

I do agree, this is weird. But also very common.
Nginx proxy is listening on eth0 with X.X.X.X, and since the host file contain 127.0.0.1 domain.tld 
It would make the request on the local interface and Nginx would redirect it to default virtual host.

I can't change the host file and the reverse, so I've to deal with this.

**Comment by Ousret** [comment]
I think I'm got it wrong.. for X reason(s) wget use ipv4 when adding 'Host: domain.tld' and ipv6 when no headers is set.

curl does the request on ipv6 no matter headers.

ipv4 is working and ipv6 isn't.
This issue has nothing to do with wkhtmltopdf. Sorry.
