### ISSUE TITLE
Custom font with Font face not working (wkhtmltoimage)

### ISSUE THREAD

**Issue by BraveFart** [wkhtmltopdf/wkhtmltopdf#3373]
Hello,

I'm trying to use a custom font in my html template that I render into an image using wkhtmltoimage but it seems that the font isn't working.
I tried .ttf and .woff fonts but nothing worked for me.
I also would like to know if it's possible to show emojis with maybe a font like: [emojione](https://github.com/Ranks/emojione/)
I'm using version 0.12.2.1 under windows
This is my template:
```html
<!DOCTYPE html>
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <style type="text/css">
		
		@font-face {
	            font-family: 'Lato-Semibold';
	            src: url('Lato-Semibold.ttf');
		    font-weight: normal;
                    font-style: normal;
		}

		.text{
			font-size:  24px;
			font-family: 'Lato-Semibold';
		}
		</style>
	</head>
	<body>
		<div>
			<span class="text">oefizfn zuu nfzejnf jzen f			</span>
			<span>oefizfn zuu nfzejnf jzen f</span>
		</div>
	</body>
</html>
```

**Comment by PhilterPaper** [comment]
Have you read all the bug reports regarding use of @font-face, and no hits on any of those? "Isn't working" is a rather vague description of the problem.

**Comment by BraveFart** [comment]
Thank you @PhilterPaper for the comment, I ended up using google font and that did the job.
