### ISSUE TITLE
[0.12.4] very high resolution on Sierra

### ISSUE THREAD

**Issue by WayneUong** [wkhtmltopdf/wkhtmltopdf#3376]
I did a fresh install on a new Mac and test with:
`wkhtmltopdf google.com test.pdf`

The result has very high resolution:

[test.pdf](https://github.com/wkhtmltopdf/wkhtmltopdf/files/826260/test.pdf)

**Comment by khkremer** [comment]
Take a look here: #3241

**Comment by Tomsgu** [comment]
Closing as it's a duplicate of #3241.
