### ISSUE TITLE
Exit with code 1 due to network error: ContentOperationNotPermittedError

### ISSUE THREAD

**Issue by ashishmohap** [wkhtmltopdf/wkhtmltopdf#3377]
Hi,
I have installed wkhtmltopdf in server and it was working fine without SSL i.e(http unsecured url). After implementing ssl in server, the pdf download is not working and just a blank page is printed with 403 Forbidden message in the header. I got the error message while compiling in command line as **Exit with code 1 due to network error: ContentOperationNotPermittedError**. Can you please help on how to fix this issue ?

**Comment by alloylab** [comment]
is this still an issue on 0.12.5?

**Comment by Tomsgu** [comment]
This should be resolved in a new version. Please feel free to re-open if you still experience this issue.
