### ISSUE TITLE
When using C3js svg modifications are not recognized after initialization

### ISSUE THREAD

**Issue by cjbuchmann-work** [wkhtmltopdf/wkhtmltopdf#3379]
So I'm not sure if this points to a more systemic issue, but here's my use case.

I'm using C3js to render charts, using the 'title' attribute
from (http://c3js.org/samples/chart_donut.html)
Something very similar to 

```javascript
var chart = c3.generate({
    data: {
        ...,
        type : 'donut',
        oninit: function (d, i) { $('.c3-chart-arcs-title').html('initialized'); },
        onrendered: function (d, i) { $('.c3-chart-arcs-title').html('rendered'); },
    },
    donut: {
        title: "created"
    }
});
```

You can also easily substitute `d3.select` instead of jQuery to obtain the same result.

with a simple ruby script to load our rails environment and execute a url request

```ruby
#!/usr/bin/env ruby
require 'bundler'

# load the rails env since we want to use activerecord and other sruff.
ENV['RAILS_ENV'] = ARGV.first || ENV['RAILS_ENV'] || 'development'
require File.expand_path(File.dirname(__FILE__) + "/../config/environment")

class UrlSource < IMGKit::Source
  def initialize(url)
    @source = url
  end

  def to_s
    @source.gsub '&', '\\\\&'
  end
end

url = "REDACTED"

kit = IMGKit.new(url, height: [350].max, width: 310, 'javascript-delay' => 2000)
# This is a workaround for a bug in IMGKit, see https://github.com/csquared/IMGKit/pull/86
kit.source = UrlSource.new(url)
kit.to_file('/tmp/file.png')
```

In browser this ends up rendering a donut chart with the final title 'rendered'.

Using this library, the rendered image shows 'created' instead of 'rendered'. I've been able to confirm that the 'oninit' and 'onrendered' methods do actually get called, and I'm able to update plain html, but my svg updates do not seem to be reflected in the generated image.

Browser : 
![screen shot 2017-03-08 at 10 38 14 am](https://cloud.githubusercontent.com/assets/16126902/23718232/87de3424-03eb-11e7-9905-e17b248277a6.png)

Generated Image
![file](https://cloud.githubusercontent.com/assets/16126902/23718310/d861a61a-03eb-11e7-94a5-97574ec11cc5.png)

I tried adding a `javascript-delay` thinking that maybe it was just taking a few seconds, but a delay of even 30 seconds for static data still wasn't loading that content.

**Comment by alloylab** [comment]
is this still an issue on 0.12.5?

**Comment by Tomsgu** [comment]
Closing as there is no feedback. Please re-open this issue if you have more information like:
- version specification
- command you use to generate a pdf (with javascript-delay)
