### ISSUE TITLE
<img> src that contains a query param and returns 404 generate error

### ISSUE THREAD

**Issue by egh** [wkhtmltopdf/wkhtmltopdf#3380]
Including an `<img src="...">` where the `src` contains an `&` or `?` and returns a 404 produces an error, even if `-load-error-handling` and `-load-media-error-handling` are set to `ignore`:

Steps to reproduce:

```
$ cat > test.html <<EOS
<html>
  <head/>
  <body>
    <img src="https://www.example.com/image.png?foo=bar&amp;bar=baz">
  </body>
</html>
EOS

$ wkhtmltopdf  --load-error-handling ignore --load-media-error-handling ignore  test.html test.pdf
Loading page (1/2)
Printing pages (2/2)                                               
Done                                                           
Exit with code 1 due to network error: ContentNotFoundError
```
Expected result: exit status of 0, no error reported.

Actual result: exit status of 1, error reported.

Note the following, nearly identical command works:

```
$ cat > test.html <<EOS
<html>
  <head/>
  <body>
    <img src="https://www.example.com/image.png">
  </body>
</html>
EOS

$ wkhtmltopdf  --load-error-handling ignore --load-media-error-handling ignore  test.html test.pdf
Loading page (1/2)
Warning: Failed to load https://www.example.com/image.png (ignore)
Printing pages (2/2)                                               
Done
```

The only difference is the presence of the the query parameter.

Environment: Debian testing, wkhtmltopdf 0.12.3.2

**Comment by alloylab** [comment]
is this still an issue on 0.12.5?

**Comment by egh** [comment]
It doesn't seem to be. Thank you!
```
λ wkhtmltopdf --version
wkhtmltopdf 0.12.5 (with patched qt)
$ cat > test.html <<EOS
<html>
  <head/>
  <body>
    <img src="https://www.example.com/image.png?foo=bar&amp;bar=baz">
  </body>
</html>
EOS
$ wkhtmltopdf --version
wkhtmltopdf 0.12.5 (with patched qt)
$ wkhtmltopdf  --load-error-handling ignore --load-media-error-handling ignore  test.html test.pdf
Loading pages (1/6)
Warning: Failed to load https://www.example.com/image.png?foo=bar&bar=baz (ignore)
Counting pages (2/6)                                               
Resolving links (4/6)                                                       
Loading headers and footers (5/6)                                           
Printing pages (6/6)
Done
$ file test.pdf 
test.pdf: PDF document, version 1.4
````

**Comment by mmaynar1** [comment]
I've been running into this issue myself. As was speculated, I'm pretty sure this was fixed in 0.12.5. I believe this is the commit for it: https://github.com/wkhtmltopdf/wkhtmltopdf/pull/3593

**Comment by PhilterPaper** [comment]
If you change **`&amp;`** to **`&`** in the `<img>` tag, does it make any difference? Or was that a cut and paste typo? Is this image.png file actually generating a PNG-format image file on-the-fly (on the server) and delivering it to the browser? I trust that it works in a browser. Other than possible time-out issues with the image generation, I wouldn't think that wkHTMLtoPDF would care where the image comes from.

**Comment by asartem** [comment]
<img src=\"https://cdn.shopify.com\" />  doesn't work because of domain of 3rd level - cdn. Tere is a ContentNotFound Error in response. While <img src=\"https://shopify.com\" />   passes validation.
This issue should be escalated as a blocker bug I think.

**Comment by Mykola-Veryha** [comment]
I got the same bug on 0.12.5
