### ISSUE TITLE
How to convert dynamic data loading html invoice(created using AngularKS) to PDF ?

### ISSUE THREAD

**Issue by chanakaDe** [wkhtmltopdf/wkhtmltopdf#3381]
I have a NodeJS rest api. And front end from AngularJS. And all the data is loading from MySQL database. I just need to create an invoice from server loaded data. This is the PDF report in need to generate. I created this in my Angular front end and now i'm using some front end technologies to render PDF. But the problem is when screen size changing, it's not rendering perfect and sometimes it's a blank sheet. So I need to implement wkhtmltopdf fot this. Server side pdf generation. 

So how can I do this ? Do I need to make a HTML page inside the REST Server ?
![screenshot from 2017-03-09 08-56-05](https://cloud.githubusercontent.com/assets/7803591/23738134/3df51076-04bd-11e7-8103-6ac11e9c1f13.png)

And this is my front end. So please tell me how can I do this ? Do I need to use any templating engine inside node js to make a HTML page ? Because I can't use Angular syntax inside node server.

**Comment by chanakaDe** [comment]
And this is how I'm generating the PDF now.
http://stackoverflow.com/questions/42584134/how-to-generate-pdf-from-dynamically-loading-data-with-angularjs
I posted this in stackoverflow and still no good. Please give me a solution for this.

**Comment by sgwatgit** [comment]
Send your HTML back up to the server (via something like `document.documentElement.outerHTML`), save that to an .html file, and then run the `wkhtmltopdf.exe` application against that file path with a path of the pdf file you wish to create.

Once the pdf is created, respond to the AngularJS app with the PDF content or a link to the generated file on the server.

**Comment by Tomsgu** [comment]
Closing as the stackoverflow issue was resolved. Also answers were provided.
