### ISSUE TITLE
wkhtmltopdf architecture

### ISSUE THREAD

**Issue by dside99** [wkhtmltopdf/wkhtmltopdf#3382]
Hello,

I am going to use it in dot net visual studio. I would like to learn how wkhtmltopdf works. The html to pdf transfomation works locally on my pc/server or it requires external web communication?

Regards,
Dimitris

**Comment by fredrikljung93** [comment]
Wkhtmltopdf does not need any external web communication. You will not need an internet connection to render a local html file. The program uses Qt WebKit rendering engine to render the file on your machine.
