### ISSUE TITLE
Installation instructions for Linux are missing

### ISSUE THREAD

**Issue by multiwebinc** [wkhtmltopdf/wkhtmltopdf#3383]
I just downloaded 0.12.4 for Linux from http://wkhtmltopdf.org/downloads.html and I noticed that nowhere on the page or in the downloaded file are there instructions how to install it. I just guessed you had to copy the extracted subfolders to /usr/, which worked, but other people may not know what to do.

**Comment by juvyc** [comment]
Is there any configuration for this? just a like a normal linux installer that has /.configuraton ? It's hard to install manually because the folder /usr/ is not accessible.

**Comment by Tomsgu** [comment]
There is a new repository `wkhtmltopdf/packaging` where you can find installation instructions.
