### ISSUE TITLE
For a same HTML documents, pdf pages renders differently

### ISSUE THREAD

**Issue by NicSil** [wkhtmltopdf/wkhtmltopdf#3389]
In the following document, the first page seems to be bold.
[doc.zip](https://github.com/wkhtmltopdf/wkhtmltopdf/files/841613/doc.zip)

![image](https://cloud.githubusercontent.com/assets/9283001/23940669/2483acda-0966-11e7-961d-773ea78deb7e.png)

**Comment by alloylab** [comment]
is this still an issue on 0.12.5?

**Comment by Tomsgu** [comment]
It's working well in `0.12.5`. Please feel free to re-open this if you still experience the issue in a newest stable version.
