### ISSUE TITLE
Any plan for wkhtmltopdf to switch from QtWebKit to QtWebEngine?

### ISSUE THREAD

**Issue by Dunge** [wkhtmltopdf/wkhtmltopdf#3391]
Since Qt 5.2, the development effort switched from QtWebKit (used by wkhtmltopdf) to [QtWebEngine](https://wiki.qt.io/QtWebEngine), which use Chromium internally and is much more up-to-date with recent HTML5 standards.

I'm currently struggling with rendering my website to pdf that is using FlexBox and HighChart with the html5 canvas boost module, and QtWebKit just don't cut it.

They even made the [porting procedure](http://doc.qt.io/qt-5/qtwebenginewidgets-qtwebkitportingguide.html) quite easy.

I'm sure wkhtmltopdf could gain a lot from making this switch.

**Comment by ashkulz** [comment]
See `Unavailable Qt WebKit API` -- `QWebElement` is required for some of the functionality that wkhtmltopdf provides. There's an [updated QtWebKit](https://github.com/annulen/webkit/wiki) which is getting [merged upstream](http://code.qt.io/cgit/qt/qtwebkit.git/log/?h=wip/next) and likely to be released soon, which is what this project will upgrade to.

**Comment by Dunge** [comment]
Thanks for the quick reply
