### ISSUE TITLE
Support viewport-size in version 0.13 alpha

### ISSUE THREAD

**Issue by nathanielatom** [wkhtmltopdf/wkhtmltopdf#3392]
What's required to support the viewport-size switch in version 0.13 alpha? I'm not super familiar with Qt, but if it's a relatively simple task, I may be able to work on a PR.

I need 0.13 alpha for the javascript in my html to render. With the default viewport size wkhtmltopdf renders the mobile version, which is not suitable for pdf.

**Comment by alloylab** [comment]
is this still an issue on 0.12.5?

**Comment by Tomsgu** [comment]
You can see a release plan for `0.13` [here](https://github.com/wkhtmltopdf/wkhtmltopdf/blob/0.13/README.md#release-plan). In alpha this is still not available.
