### ISSUE TITLE
Iframe with "overlay" inside isn't displayed correctly

### ISSUE THREAD

**Issue by kvitozev** [wkhtmltopdf/wkhtmltopdf#3394]
You can see the normal behavior of iframe: https://gyazo.com/10f3a6c6cce56298e4626b05ace2edb5

Basically, it's a preview from Facebook, representing carousel post. The "overlay" effect is visible when user places the cursor at active element (the other elements will have that effect).

The generated PDF looks like this: https://gyazo.com/2b5f435bd64a90270065f46f907c1fc1

Any suggestions how to fix this?

What I tried so far?
- Increasing a time before "start processing" - it doesn't work.
- Adding "pointer-events: none;" applied to all elements - it doesn't work.

**Comment by alloylab** [comment]
is this still an issue on 0.12.5?

**Comment by Tomsgu** [comment]
Closing as there is no feedback. Please re-open the issue if you have more information like minimal html test case and details of your version.
