### ISSUE TITLE
Viewport / window size trouble

### ISSUE THREAD

**Issue by grembo** [wkhtmltopdf/wkhtmltopdf#3399]
I'm trying to render output from kibana/elasticsearch using wkhtmltopdf 0.12.4, but there seem to be viewport issues, so the page is rendered like the screen was much wider than the configured resolution. The example used for testing can be found [here](http://demo.elastic.co/beats/app/kibana#/dashboard/Packetbeat-Dashboard), Safari or Chrome are good to see what the page is supposed to like.

I went through a couple of test cases, it seems like the only way to get a result close to what I would expect is to wrap the page in a fixed size iFrame - which is a bit ugly IMHO (also in terms of allowing wkhtml to ignore x-frame-options). In case of wkhtmltoimage I also tried Xvfb/--use-xserver, but this didn't make a difference either.

See below for a script that allows to reproduce all test cases I went through, the output filename tells you my thoughts on the result.

```sh
#!/bin/sh

# Prepare supporting html documents
echo >empty.html
cat >framed.html<<EOF
<html>
<body style="margin:0px;border0px;">
<iframe style="width:1920;height:1080;border:0px;" 
  src="http://demo.elastic.co/beats/app/kibana#/dashboard/Packetbeat-Dashboard">
</body>
</html>
EOF

# pdf test cases
wkhtmltopdf \
  --javascript-delay 20000 \
  "http://demo.elastic.co/beats/app/kibana#/dashboard/Packetbeat-Dashboard" \
  notgood.pdf

wkhtmltopdf \
  --viewport-size 1920x1080 \
  --javascript-delay 20000 \
  "http://demo.elastic.co/beats/app/kibana#/dashboard/Packetbeat-Dashboard" \
  stillnotgood.pdf

wkhtmltopdf \
  --header-html "empty.html" \
  --javascript-delay 20000 \
  "http://demo.elastic.co/beats/app/kibana#/dashboard/Packetbeat-Dashboard" \
  nope.pdf

wkhtmltopdf \
  --viewport-size 1920x1080 \
  --header-html "empty.html" \
  --javascript-delay 20000 \
  "http://demo.elastic.co/beats/app/kibana#/dashboard/Packetbeat-Dashboard" \
  quitegood.pdf

wkhtmltopdf \
  --viewport-size 1920x1080 \
  --javascript-delay 20000 \
  "framed.html" \
  bestresult.pdf

# image testcases
wkhtmltoimage \
  --javascript-delay 20000 \
  "http://demo.elastic.co/beats/app/kibana#/dashboard/Packetbeat-Dashboard" \
  notreally.jpg

wkhtmltoimage \
  --width 1920 \
  --crop-h 1080 \
  --javascript-delay 20000 \
  "http://demo.elastic.co/beats/app/kibana#/dashboard/Packetbeat-Dashboard" \
  quiteoff.jpg

wkhtmltoimage \
  --width 1920 \
  --crop-h 1080 \
  --javascript-delay 20000 \
  "framed.html" \
  bestresult.jpg

```

**Comment by MrDolch** [comment]
You may also want to us the flag --disable-smart-shrinking which disables "the intelligent shrinking strategy used by WebKit that makes the pixel/dpi ratio none constant".

**Comment by alohaninja** [comment]
@MrDolch is correct - assigning `--viewport-size` does not change anything unless you also assign `--disable-smart-shrinking` which is enabled by default
