### ISSUE TITLE
Silent Windows installer is not silent when not running elevated

### ISSUE THREAD

**Issue by gabrielweyer** [wkhtmltopdf/wkhtmltopdf#3400]
I downloaded `wkhtmltox-0.12.4_msvc2015-win64.exe` and tried to install it silently via the command line:

```
wkhtmltox-0.12.4_msvc2015-win64.exe /S /D=C:\Program Files\wkhtmltopdf
```

As mentioned in #3131 the installer is using [NSIS](http://nsis.sourceforge.net/Docs/Chapter3.html#installerusagecommon). I'm using the options described in the documentation.

![not-unattented](https://cloud.githubusercontent.com/assets/2101647/24087896/87e0eebc-0d78-11e7-842a-8148d8ae4dcf.gif)

Typing this command will trigger the `UAC` dialog (which can't be captured by ScreenToGif).

If I run this command in an elevated prompt it works as expected.

**Comment by ashkulz** [comment]
That's because of `RequestExecutionLevel admin` in the installer, it's best to install it system-wide. If you need to automate that, it's best to use something like `choco install wkhtmltopdf` or use `runas` to run under elevated privileges.
