### ISSUE TITLE
nfs errors for kalyptorisk.com from version 0.12.3

### ISSUE THREAD

**Issue by jimvanderveen** [wkhtmltopdf/wkhtmltopdf#3401]
Our nfs server has been showing errors such as this:
```
rpc.mountd[2538]: authenticated mount request from OurNFSserver:864 for /homesrv/kalyptorisk.com (/homesrv)
rpc.mountd[2538]: can't stat exported dir /homesrv/kalyptorisk.com: No such file or directory
```
coming from servers using wkhtmltopdf_binary_gem. This is wrapping `wkhtmltopdf` version 0.12.3, looks like the `kalyptorisk.com` reference has been fixed in version 0.12.4

Feel free to close this issue. I opened it to get the error strings added to the github history, and hopefully save some other users the time we spent tracking this down.

**Comment by ashkulz** [comment]
Can you point which binary is giving this issue and how to track it? That was my previous organization, and I don't think there is anything which should be causing this.

**Comment by jimvanderveen** [comment]
Sure. It is https://github.com/zakird/wkhtmltopdf_binary_gem
The most recent version is wrapping wkhtmltopdf version 0.12.3.1 but we also found the same problem on 0.12.3

Please let me know if you need any further information. It looks like this issue was fixed in wkhtmltopdf version 0.12.4, but the binary gem has not yet been updated.

**Comment by ashkulz** [comment]
I meant, this is present in which binaries, e.g. 32-bit/64-bit Linux or in macOS as well? Also, how did you trigger this and in which logs should I check to verify how the build environment escaped into the binary?

**Comment by ashkulz** [comment]
@jimvanderveen: any tips on how I can verify it? I wouldn't want to release 0.12.5 without verifying how this happened.

**Comment by jimvanderveen** [comment]
Sorry, I didn't have a chance to follow up on that yesterday, but I will get that info to you later today.

**Comment by jimvanderveen** [comment]
We just did the following, once we found the errors showing up in the log files on our nfs server:
```
$ find . -type f -exec grep -Hni kalyptorisk {} \;
Binary file ./local/lib/ruby/gems/2.3.0/gems/wkhtmltopdf-binary-0.12.3/bin/wkhtmltopdf_linux_x86 matches
Binary file ./local/lib/ruby/gems/2.3.0/gems/wkhtmltopdf-binary-0.12.3/bin/wkhtmltopdf_linux_amd64 matches
Binary file ./apps/roadmap/shared/bundle/ruby/2.3.0/gems/wkhtmltopdf-binary-0.12.3.1/bin/wkhtmltopdf_linux_x86 matches
Binary file ./apps/roadmap/shared/bundle/ruby/2.3.0/gems/wkhtmltopdf-binary-0.12.3.1/bin/wkhtmltopdf_linux_amd64 matches
Binary file ./apps/roadmap/shared/bundle/ruby/2.3.0/gems/wkhtmltopdf-binary-0.12.3/bin/wkhtmltopdf_linux_x86 matches
Binary file ./apps/roadmap/shared/bundle/ruby/2.3.0/gems/wkhtmltopdf-binary-0.12.3/bin/wkhtmltopdf_linux_amd64 matches
```
As far as I know, we did not see anything in the logs on our web/ruby server.

**Comment by ashkulz** [comment]
Something of the build environment has leaked into the binary. The question becomes -- how to identity and disable that? For 0.12.4 it may be trying something which isn't immediately obvious. Is there some self contained repro you can share as I don't use nfs that much?
