### ISSUE TITLE
Using wkhtmltopdf in C# to print html files in batches

### ISSUE THREAD

**Issue by hemantom** [wkhtmltopdf/wkhtmltopdf#3406]
I would like to convert larg number of html files from a directory to PDF using C#.
How to pass input file name and output file name which contains spaces. 
Eg  wkhtmltopdf  'test file.html' 'test file.pdf'
This is working using command prompt but not working in C#. Please help how to pass file names with spaces in it.  The exe is taking spaces in file name as delimiter.

**Comment by PhilterPaper** [comment]
As you found on the command line, wrapping names in quotation marks (usually double " marks) works. You'll have to show us the C# code you're using, for anyone to take a whack at it. If you're passing the whole command line to some sort of "exec" or "system" call, you'll probably need to escape the quotation marks \" within the string, so they don't disappear during processing. You'll also have to be careful about whether ' or " for quotes are proper.

**Comment by hemantom** [comment]
thanks for reply. The issue was with quotation marks.

**Comment by Tomsgu** [comment]
Closing as this is more question for e.g. stackoverflow.
