### ISSUE TITLE
write wkhtmltox installer log to file

### ISSUE THREAD

**Issue by ronsh77** [wkhtmltopdf/wkhtmltopdf#3409]
Hi,

I'm trying to run the installer via command-line in silent mode and make it write the log of the installer to a file. How can I do it?

I have tried many syntaxes similar to this:
`wkhtmltox-0.12.4_msvc2015-win64.exe /S /LOG="log.txt"`

Thanks.

**Comment by alloylab** [comment]
We are closing this out since we haven't heard from you. If you are still having this issue please feel free to re-open it. Thanks.
