### ISSUE TITLE
Output html styled with bootstrap3 to pdf and fit on one standard letter page during print

### ISSUE THREAD

**Issue by gregoryprice** [wkhtmltopdf/wkhtmltopdf#3410]
Here is the html:
[test_bol.html.txt](https://github.com/wkhtmltopdf/wkhtmltopdf/files/880740/test_bol.html.txt)

I am using bootstrap3 to create a bol document. This is typically printed on a 8.5 x 11 letter page and a couple of the box sizes need to be rendered exactly to be a certain width x height. The entire document should fit on one page but when calling wkhtmltopdf, the output pdf is shrunk pretty badly and all the nice div boxes styled with the bootstrap grid system are not being styled or positioned correctly. What is the solution? this is all written in python. Attached is the output html. 
[out.pdf](https://github.com/wkhtmltopdf/wkhtmltopdf/files/880738/out.pdf)

**Comment by alloylab** [comment]
is this still an issue on 0.12.5?

**Comment by Tomsgu** [comment]
It's most likely, because you have broken html file. Try to check it here: https://validator.w3.org .
