### ISSUE TITLE
About PDF layout issues

### ISSUE THREAD

**Issue by 741052366com** [wkhtmltopdf/wkhtmltopdf#3414]
I am from China, my English is relatively poor, I do not know if I describe you can understand that I am trying to describe the next one.

I use xkhtmltopdf when my html is the presence of horizontal and vertical web pages, i know - directions can be set. But this setting is a single, I want two kinds of coexistence, how do?
For example, can the first page to the third page be vertical, the fourth page is horizontal? Thank you

**Comment by alloylab** [comment]
is this still an issue on 0.12.5?

**Comment by Tomsgu** [comment]
This is not supported at the moment. See Feature request: #1564.
