### ISSUE TITLE
Render PDF only if div element value is expected in html

### ISSUE THREAD

**Issue by sid88in** [wkhtmltopdf/wkhtmltopdf#3415]
Hey Guys!

I have a use case to generate pdf ONLY if the hidden pixel value in the div element returns true. So I am exploring run-scripts to execute javascript (wkhtmltopdf --run-script "" https://url output.pdf).  
In the run script I am thinking about checking the value of the div element and if it doesn't succeed keep looping. If it does not succeed then generate a blank page.  

Is this approach correct? I am still trying to figure out how would we make wkhtmltopdf generate pdf if the pixel value is true and not otherwise (or blank).

**Comment by alloylab** [comment]
is this still an issue on 0.12.5?

**Comment by Tomsgu** [comment]
It's quite difficult to help you if you haven't attached html file, neither your script, neither your command line arguments. Please feel free to ask in stackoverflow if you have more questions about it.
