### ISSUE TITLE
0.12.4 issue output PDF getting too large

### ISSUE THREAD

**Issue by keerthi16** [wkhtmltopdf/wkhtmltopdf#3417]
Old version looks good - link to pdf -> [0.12.3](https://www.docdroid.net/q1kUNCX/google-0123.pdf.html)

New version zoomed - link to pdf -> [0.12.4](https://www.docdroid.net/4xBWq9X/google-0124.pdf.html)

**Comment by greyby** [comment]
That is a bug #3241

**Comment by Tomsgu** [comment]
Duplicate of #3241.
