### ISSUE TITLE
Page Break Not Proper showing 

### ISSUE THREAD

**Issue by DarshanKsheerasagar** [wkhtmltopdf/wkhtmltopdf#3418]
Hello ,

I am using page-break-after:always; on my html and exporting to pdf when export it not properly page break showing . so many white space showing can you tell me how remove the white space.
Below is the image 

![pdfimage](https://cloud.githubusercontent.com/assets/24871149/24642407/c96cc448-1924-11e7-8fbd-6934a12acc81.JPG)

**Comment by DarshanKsheerasagar** [comment]
Any One Help me @tobinibot @awt @haberbyte @mmb

**Comment by DarshanKsheerasagar** [comment]
No One is there to Reply ....

**Comment by haberbyte** [comment]
It is not really clear to me what the issue is.

The page-break-after: always works in all of my use cases, not sure what your white space problem on the Screenshot is.

You would probably get more luck with a response if you provide an easy to reproduce test or source input to share.

**Comment by DarshanKsheerasagar** [comment]
Thank You So Much @haberbyte Sir.

**Comment by anandhuded2** [comment]
Facing same problem since 2days. Page break not working properly it is taking white space at the beginning of the page then data is getting printed.

**Comment by anandhuded2** [comment]
Hi Darhsan,

If you found any solution to it please mention it over here because I am also facing same problem.
