### ISSUE TITLE
But wkhtmltopdf doesn't create directories

### ISSUE THREAD

**Issue by mohittyagi6677** [wkhtmltopdf/wkhtmltopdf#3420]
But wkhtmltopdf doesn't create directories . For example, If the output path(where we want to save our PDF) is "C:\Personal\Directory\file.pdf" and if the "Directory" folder is not present, then it gives the error: "unable to write to destination".
This could be a issue as we have to take care of this first , and then call wkhtmltopdf

**Comment by PhilterPaper** [comment]
_Most_ applications don't create directories themselves. That's unusual behavior, although it certainly could be done. I don't know if you could "catch" the error above and create the missing director(ies), or if you'd have to take each output path given (here \Personal\Directory\) and test that \Personal exists (if not, mkdir), then test if \Personal\Directory exists (if not, mkdir). Some operating systems let you mkdir a whole chain of missing directories, and others make you do it one level at a time.

It might certainly be cleaner to take care of it first, in your batch file or other script, if it's going to be a common occurrence, or if it's likely to be rare, make the user do it.

**Comment by mohittyagi6677** [comment]
@PhilterPaper thanks for the quick reply, now since you have confirmed , i will certainly take care of this. -)

**Comment by DarshanKsheerasagar** [comment]
Hello @PhilterPaper 

Rowspan in table when export to pdf not working ...
