### ISSUE TITLE
Fails with latest version of Highcharts 

### ISSUE THREAD

**Issue by esorribas** [wkhtmltopdf/wkhtmltopdf#3423]
Process returns a 'segmentation fault' error when runs with --print-media-type and latest version of Highcharts.

I can´t show an example URL beause is running on non-public site.

**Comment by esorribas** [comment]
Highcharts version: 5.0.9
Example URL of error: https://manager.e-encuesta.com/v2/view-report/pRRCpdEUmqht1L62uogX1Q

Thanks

**Comment by alloylab** [comment]
is this still an issue on 0.12.5?

**Comment by esorribas** [comment]
It's seems fixed, thanks
