### ISSUE TITLE
Converted PDFs finish with "Loading [Contrib]/a11y/accessibility-menu.js"

### ISSUE THREAD

**Issue by duncan-bayne** [wkhtmltopdf/wkhtmltopdf#3424]
I'm using wkhtmltopdf in the following fashion:

```
/usr/local/bin/wkhtmltopdf \
  --footer-center [page]/[topage] \
  --footer-font-size 8 \
  --footer-font-name "Open Sans" \
  ./review.html \
  review.pdf
```

... and the resultant output contains an odd box about `accessibility-menu.js`:

![pdf](https://cloud.githubusercontent.com/assets/65949/24789143/ea39e8ee-1bb4-11e7-93c1-b342bada5d03.png)

System properties:

```
➜  ~ /usr/local/bin/wkhtmltopdf --version
wkhtmltopdf 0.12.4 (with patched qt)
➜  ~ uname -a
FreeBSD x220 11.0-RELEASE-p8 FreeBSD 11.0-RELEASE-p8 #0: Wed Feb 22 06:12:04 UTC 2017     root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC  amd64
```

**Comment by duncan-bayne** [comment]
I can work around the problem with the `--disable-javascript` flag but that's a pretty blunt instrument.

**Comment by ashkulz** [comment]
You might want to experiment with different values of --javascript-delay

**Comment by duncan-bayne** [comment]
Ended up being happy enough with the workaround; please feel free to close this.
