### ISSUE TITLE
Image quality in wkhtmltox-0.13.0-alpha-7b36694_linux-jessie-amd64

### ISSUE THREAD

**Issue by Dingo64** [wkhtmltopdf/wkhtmltopdf#3425]
Just a quick note. Not sure if this is a bug or a design choice.
Anyway:

Realase wkhtmltox-0.13.0-alpha-7b36694_linux-jessie-amd64.deb on Debian Jessie x64 cannot be run because it says "QXcbConnection: Could not connect to display"
So I run it with  xvfb-run. The fonts are rendered nicely but images are terrible. It looks like they are resampled using Nearest Neighbour method.

So I grabbed release wkhtmltox-0.12.4_linux-generic-amd64.tar.xz unpacked on Windows and just uploaded the binary wkhtmltoimage to my Debian Jessie x64. It runs great without xvfv-run and the quality of the images is perfect.

So perhaps the problem is not with wkhtmltoimage 0.13 but rather with xvfb? Not sure but it surely doesn't run headless so it's a bit pain in the ass.

**Comment by alloylab** [comment]
did you try the patched qt version?

**Comment by Tomsgu** [comment]
@Dingo64 exactly. It doesn't run headless. Please see: https://github.com/wkhtmltopdf/wkhtmltopdf/tree/0.13#release-plan Headless build will be in 0.13 beta.
