### ISSUE TITLE
some special characters rendering with 'Â' prefixed

### ISSUE THREAD

**Issue by LonerganOnline** [wkhtmltopdf/wkhtmltopdf#3429]
Html Input
![html-render](https://cloud.githubusercontent.com/assets/5843951/24909928/f32bd3d4-1ebd-11e7-99a8-6e1ddb736d84.PNG)

image output
![image-output](https://cloud.githubusercontent.com/assets/5843951/24909932/f5dd1174-1ebd-11e7-9f1e-a4af376edc3c.PNG)

All fonts used are linked to in the their google fonts css in the html.
`<link href="https://fonts.googleapis.com/css?family=Open+Sans|Roboto+Slab|Source+Serif+Pro|Cutive|Karma|Roboto|Source+Sans+Pro|Ubuntu|Play|PT+Sans+Caption|Michroma|Andika|Lobster|Bangers|Chewy|Special+Elite|Fredericka+the+Great|Finger+Paint|Cinzel+Decorative|Love+Ya+Like+A+Sister|Sail|Sonsie+One|Peralta|Handlee|Pinyon+Script|Niconne|Gochi+Hand|Itim|Droid+Sans+Mono|Anonymous+Pro" rel="stylesheet" type="text/css"> 
`

**Comment by PhilterPaper** [comment]
You entered your text in UTF-8 (multiple bytes for non-ASCII characters), but are rendering it in PDF as a single byte encoding such as Latin-1 (ISO-8859-1). Does your HTML declare the encoding? Did you throw the right command-line switches?

**Comment by LonerganOnline** [comment]
@PhilterPaper thank you adding in the character encoding meta tag to the html passed in solved the issue.
