### ISSUE TITLE
Page break for TD element

### ISSUE THREAD

**Issue by GentlemanK** [wkhtmltopdf/wkhtmltopdf#3435]
Last line gets cut off and breaks over to next page.

Here is the sample html file I am using. 
http://s000.tinyupload.com/index.php?file_id=23944558487334389019

This is how PDF is looking
https://i.stack.imgur.com/D5VDn.jpg

I am just passing html file and pdf filename as a parameter to wkhtmltopdf.exe
I am using 0.12.4 version of wkhtmltopdf.exe

**Comment by PhilterPaper** [comment]
First of all,  what exactly are you trying to accomplish here? I see fixed width empty columns and fixed height empty rows -- wouldn't you be better off using "margins" to give yourself blank space around your content? Then, you seem to be missing `</td>` on your sample, but that may be a copy-and-paste typo. What are you doing with a `<table>` that couldn't better be done with `<div>`s and CSS? I take it you are trying to get some bulk text nicely paginated, and that text includes some HTML markup, so simple text-to-PDF formatters aren't going to do the job.

There are CSS attributes to specify page breaks within a table, usually before or after a _row_, but reports are that they don't work well in wkHTMLtoPDF. There have also been reports before of text in a line being vertically split (as you show) in a table row. Switching to divs _might_ cure this.

**Comment by GentlemanK** [comment]
I will make necessary changes in HTML and try. Thanks.
