### ISSUE TITLE
converting HTML file causes errors and no text in pdf

### ISSUE THREAD

**Issue by jbcripe68** [wkhtmltopdf/wkhtmltopdf#3437]
When I try this command line under Windows I see:

c:\tmp\htmlexample>"C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe" item1.html
 item1.pdf
Loading pages (1/6)
Counting pages (2/6)
Warning: Received createRequest signal on a disposed ResourceObject's NetworkAcc
essManager. This might be an indication of an iframe taking too long to load.
Warning: Received createRequest signal on a disposed ResourceObject's NetworkAcc
essManager. This might be an indication of an iframe taking too long to load.
Warning: Received createRequest signal on a disposed ResourceObject's NetworkAcc
essManager. This might be an indication of an iframe taking too long to load.
Resolving links (4/6)
Loading headers and footers (5/6)
Printing pages (6/6)
Done
Exit with code 1 due to network error: ContentNotFoundError

The included item1.html can be loaded in Chrome and IE with no problems.

The created PDF is cutoff after the first page and has no text displayed.  When I run wkhtmltopdf from Linux connect to a nodeJS server for the page I see the text but the first page is still cutoff.  I have attached a zip with the html, style sheets and output pdf
[htmlexample.zip](https://github.com/wkhtmltopdf/wkhtmltopdf/files/922496/htmlexample.zip)

**Comment by PhilterPaper** [comment]
Have you tried using a command-line flag to tell it to give more time to load? If indeed some iframe content is taking too long, a flag to tell it to give Javascript more time to load might help with that. I don't think there's a separate flag for iframe content, but the JS time flag could help.

**Comment by jbcripe68** [comment]
Same results:

c:\tmp\htmlexample>"C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe" --javascri
pt-delay 10000 item1.html item1.pdf
Loading pages (1/6)
Counting pages (2/6)
Warning: Received createRequest signal on a disposed ResourceObject's NetworkAcc
essManager. This might be an indication of an iframe taking too long to load.
Warning: Received createRequest signal on a disposed ResourceObject's NetworkAcc
essManager. This might be an indication of an iframe taking too long to load.
Warning: Received createRequest signal on a disposed ResourceObject's NetworkAcc
essManager. This might be an indication of an iframe taking too long to load.
Resolving links (4/6)
Loading headers and footers (5/6)
Printing pages (6/6)
Done
Exit with code 1 due to network error: ContentNotFoundError

**Comment by jbcripe68** [comment]
Also tried by enabling our proxy:

c:\tmp\htmlexample>"C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe" -p http://
XXX.XXX.XXX.XXX:80 item1.html item1.pdf
Loading pages (1/6)
Counting pages (2/6)
Warning: Received createRequest signal on a disposed ResourceObject's NetworkAcc
essManager. This might be an indication of an iframe taking too long to load.
Warning: Received createRequest signal on a disposed ResourceObject's NetworkAcc
essManager. This might be an indication of an iframe taking too long to load.
Warning: Received createRequest signal on a disposed ResourceObject's NetworkAcc
essManager. This might be an indication of an iframe taking too long to load.
Resolving links (4/6)
Loading headers and footers (5/6)
Printing pages (6/6)
Done
Exit with code 1 due to network error: ContentNotFoundError

**Comment by PhilterPaper** [comment]
OK, I don't see any iframes or links to external resources. All your resources are local? Anything that seems to take a long time to load? Are you missing any resources (images, etc.) that might be delaying the completion of the load process?

**Comment by jbcripe68** [comment]
If you load the index.html into a browser you will see after the header it is the same two list items over and over.  The same errors occur if there is only one item, I just added multiple to show that the output gets cut off after the first page.  All images and styles are local and included in the attachment.  

I notice if I remove the line 

<link rel="Stylesheet" href="./css/style.css">

from the <head> block the conversion works fine.  Of course I need the styling, so what is causing the problem in style.css???

**Comment by PhilterPaper** [comment]
Is `./css` pointing to the right place when you're doing a local (file-based) conversion? Maybe you could try giving an absolute address (/var/www/... or whatever) and see if that makes any difference.

**Comment by jbcripe68** [comment]
If you look at the example item1.pdf you can see that the style sheet is used during the conversion as some of the styles are applied, so it must be something inside the css

**Comment by PhilterPaper** [comment]
Looking _in_ the styles.css file, I see references to a lot of background image files that don't seem to exist. Are they present on your system, and you just removed most of them from public display? If they're really missing, that could be causing your problem.

**Comment by jbcripe68** [comment]
Good point.  I (painfully) found all the references to local files that were not present and created them.  After fixing I still see the same problem.  Here is another zip with all the files in .css present and the output with (as item1.html) and without (as item2.html) and the respective pdfs when running

**Comment by jbcripe68** [comment]
After getting an unobfuscated version of the css file and using divide and conquer I was able to determine that this entry was causing only the first page of the PDF to be built:

body,
html {
  height: 100%;
  overflow: hidden;
}

Any ideas why???  I still get these warnings/errors, but at least I have a full PDF:

Loading pages (1/6)
libpng warning: iCCP: known incorrect sRGB profile           ] 52%
Counting pages (2/6)
Resolving links (4/6)
Loading headers and footers (5/6)
Printing pages (6/6)
Done
Exit with code 1 due to network error: ContentNotFoundError

**Comment by PhilterPaper** [comment]
So item2.html is the same as item1.html, except that the CSS link is removed? item1.pdf has the background images specified in CSS, but not the foreground images, and no text, while item2.pdf is missing the background images, but otherwise has all the content? Modifying the CSS to remove the body & html "height" and "overflow" attributes allows item1.html to be successfully converted? Can you narrow it down to one or the other of those attributes?

You say you have the entire PDF -- is nothing missing, even with that ContentNotFoundError? If you haven't done so already, you might want to search this GitHub ticket area for other reports of ContentNotFoundError and what causes it. Do you get that error on both item1 and item2?

**Comment by Tomsgu** [comment]
Closing as there is no feedback. Please re-open it if you can provide answer to @PhilterPaper questions.
