### ISSUE TITLE
all available wkhtmltopdf buildpacks for heroku are broken

### ISSUE THREAD

**Issue by davideghz** [wkhtmltopdf/wkhtmltopdf#3438]
They all point to download.gna.org/.. but the download is no longer available there.

Can anybody point me to a correct buildpack, or maybe suggest how and what to change in to the following buildpacks in order to work? I guess it would be enough to change the download URL but I don't know what a correct URL looks like

https://github.com/dscout/wkhtmltopdf-buildpack/blob/master/bin/compile

https://github.com/barsoom/wkhtmltopdf-buildpack/blob/master/bin/compile

https://github.com/rafaelp/heroku-buildpack-wkhtmltopdf/blob/master/bin/compile

https://github.com/neofreko/wkhtmltopdf-buildpack/blob/master/bin/compile

**Comment by PhilterPaper** [comment]
Look at #3390. Hosting has been bouncing around a bit, but may be on [fr.]wkhtmltopdf.org.

**Comment by davideghz** [comment]
ouch, didn't see that. Anyway I think one can just change the links used in the linked buildpacks with the current self-hosted-download-links and things should work.. just, I'm a completely n00b with compiling stuff and I don't know which link shall I use in which way.

It would be great if one of you could take a quick look into the heroku buildpacks linked above and pointing me in the right direction :)

**Comment by davideghz** [comment]
[This](https://github.com/dscout/wkhtmltopdf-buildpack/pull/19) looks promising, maybe you can take a look at the the PR there?

**Comment by ashkulz** [comment]
Nothing much I can do here. `gna.org` is still up, but there is no guarantee when it will go offline.

**Comment by davideghz** [comment]
for your info https://github.com/dscout/wkhtmltopdf-buildpack/pull/19
