### ISSUE TITLE
Genetate blocks instead of Chinese Character in docker's centos

### ISSUE THREAD

**Issue by Givemeablock** [wkhtmltopdf/wkhtmltopdf#3439]
..ah,I am working for a company project now,and when I install centos in docker for virtual environment,I find that the wkhtmltopdf generate blocks instead of chinese fonts.I hava made lots of try,once I just install Xvfb and it generate normally when it is in bash.But when it comes to my porject,generate on website and download,it got really bad result.Here is the usage in my project:
`config = pdfkit.configuration(wkhtmltopdf="/usr/local/bin/wkhtmltopdf")`
`pdf = pdfkit.from_string(content, False, options=options, config=config)`
Is there any solutions for this problem?Thank you.I will be very appreciate it if any solution.

**Comment by PhilterPaper** [comment]
So you have Chinese text in UTF-8, and in a browser it displays OK, but the PDF shows only "tofu" (blocks with hex digits inside them)? Is this two different installations of wkHTMLtoPDF, one of which produces a good PDF (local usage) and one produces the tofu (HTML over the web)? Or is it one installation that works for local files, but over the web it fails to produce a good PDF? If two installations, it sounds like you might have your CJK fonts properly installed on one, but not on the other. If one installation, have you confirmed that a browser shows the Chinese text correctly, suggesting that the encoding declaration (as UTF-8) and so on is set up correctly?

**Comment by Givemeablock** [comment]
Thanks for your reply.It seems like I only install on wkHTMLtoPDF in docker's centos.I am not sure what's the problem.You mean it is the lack of the fonts that caused the problem.So what should I install my fonts on,in my ubuntu system or in docker's centos?And in my website,the pdf text generate in a text-editor where i got pdf container from it.Is it possible the problem of the editor:http://wangeditor.github.io/.

**Comment by PhilterPaper** [comment]
If your wkHTMLtoPDF installation can't see the fonts you want, while a browser or wkHTMLtoPDF in Ubuntu does, it sounds like you need to install the fonts in docker's centos. If this is a virtual environment, it may not be sharing things like fonts between the outside Ubuntu system and centos. That's all I can think of.

**Comment by Tomsgu** [comment]
Closing as answers were provided and there is no feedback from the author.
