### ISSUE TITLE
HTML <table> rendering anomaly

### ISSUE THREAD

**Issue by michael-deVries** [wkhtmltopdf/wkhtmltopdf#3448]
See first line of page 3.  HTML rendering by multiple browsers (IE, FF, Chrome, Edge) is flawless.  While this is just a test, we are considering using wkhtmltopdf for tabular invoice data.  Are we just being stupid?  :)

[1.pdf](https://github.com/wkhtmltopdf/wkhtmltopdf/files/958484/1.pdf)

Edit:
Found an answer here: #3356

nuts and bolts of it...  add this to html (or css):
`<style type="text/css">`
`table { page-break-inside:auto }`
`    tr    { page-break-inside:avoid; page-break-after:auto }`
`    thead { display:table-header-group }`
`    tfoot { display:table-footer-group }`
`</style>`

Check comment by torinaki on Mar 23

**Comment by NiR-** [comment]
@michael-deVries Since [a similar issue has been labeled with "Invalid"](https://github.com/wkhtmltopdf/wkhtmltopdf/issues/3159), I think this will be never resolved by wkhtmltopdf and I think it's not due to wkhtml itself but rather to Qt.

Thus, could you close your issue now you solved it?
