### ISSUE TITLE
It is getting stuck on Loading page 100%

### ISSUE THREAD

**Issue by jhonplanner** [wkhtmltopdf/wkhtmltopdf#3451]
Os : window 10 
Wkhtmltopdf version : 0.12.4

It is taking too long to generate PDF. and sometime stuck on 100% as shown in attachment. 

see attached snapshot. 
![image](https://cloud.githubusercontent.com/assets/23046372/25515645/98cdb2ce-2c03-11e7-9d40-8c244b068dd7.png)

**Comment by jhonplanner** [comment]
behaviour is random, sometime stuck on 100% as shown in my above comment, and sometime it is taking too long with network errors as attached. 
![image](https://cloud.githubusercontent.com/assets/23046372/25516116/358e7a06-2c06-11e7-9231-aad688368a03.png)

duplicate of #2822

**Comment by sanmai** [comment]
If you have to use an older version of wkhtmltopdf like 0.9.6 and it just stucks loading local .html, chances are you have some protocol relative urls like so:

    <img src="//example.com/test.png">

If you fix them before feeding a file to wkhtmltopdf, problem goes away. Like so:

    <img src="https://example.com/test.png">

It seems like there's no other way to fix this. See #1746
