### ISSUE TITLE
WKHTMLTOPDF working directly in shell but not working with PHP exec

### ISSUE THREAD

**Issue by devacctgmailcom** [wkhtmltopdf/wkhtmltopdf#3459]
Hi All

I am using WKHTMLTOPDF to generate PDF. Its working fine when I call it in shell and produces PDF without any error.

But when I use same command in PHP exec. It states:
"Fontconfig error: Cannot load default config file"
It generates a file with size 0 bytes and when I open this file it shows as corrupted file.

Fontconfig is installed and updated already. I am using this on CentOS 7.

Thanks

**Comment by devacctgmailcom** [comment]
Is there anybody to help me please?

**Comment by Tomsgu** [comment]
You can use `KnpLabs/snappy` php library. Internally it executes binary through [Process component](http://symfony.com/doc/current/components/process.html) from Symfony. 

You can find some inspiration there. I don't think there is an issue with it.
