### ISSUE TITLE
Content-Security-Policy issue

### ISSUE THREAD

**Issue by nikolagrujic-zz** [wkhtmltopdf/wkhtmltopdf#3461]
I'm having problems with generating pdf from html that has embedded iFrame inside, although loading html itself is not a problem, wkthmltopdf is throwing errors. 

After turning on the **--debug-javascript** option, I'm seeing these errors **Warning: :1 Refused to load script from "customUrlOfTheScriptHere" because of Content-Security-Policy.** As a result I get pdf but without rendered iFrame.

This is happening with versions **0.12.3 (with patched qt)** and **0.12.4 (with patched qt)**. 

I tried downgrading to older versions **0.12.3.2** and **0.12.1** and I don't have this issue with Content-Security-Policy and generating resulting pdf (iFrame is rendered as it should) but I need patched qt version so downgrading doesn't work for me. Can I try some workaround or option which will prevent or skip these errors and help me render iFrame and pdf properly?

**Comment by alloylab** [comment]
is this still an issue on 0.12.5?

**Comment by Tomsgu** [comment]
Closing as there is no response. Please feel free to re-open the issue if you have still the same problem in `0.12.5`.
