### ISSUE TITLE
Is it possible to make the pdf selection disabled?

### ISSUE THREAD

**Issue by AndreiAnufrijev** [wkhtmltopdf/wkhtmltopdf#3462]
I would like to generate the pdf from html which should be protected against editing. Is that possible?
Thank you

**Comment by tobya** [comment]
Usually you can't edit a pdf anyway?

**Comment by Tomsgu** [comment]
It's not possible in wkhtmltopdf at the moment. But you can generate a pdf and then protected it with a different tool.
