### ISSUE TITLE
Table header and footer are overlapping with dynamic data  

### ISSUE THREAD

**Issue by kiran3010p** [wkhtmltopdf/wkhtmltopdf#3465]
Hello,

We are facing issue with table header and footer are overlapping with dynamic data. We have 
<header>
<some table data>
<group header>
<group sub header>
<group data>
<totals>
<footer>
while <group data> is not fitted in one page it will move to next page. In this scenario <header> is over lapping with <group data>.
Can any one suggest the solution.

**Comment by DocOlson** [comment]
Check this out: https://github.com/wkhtmltopdf/wkhtmltopdf/issues/3448
