### ISSUE TITLE
Static build has 20 dynamic dependencies

### ISSUE THREAD

**Issue by rrshaban** [wkhtmltopdf/wkhtmltopdf#3468]
I'm working to create a static-linked binary of wkhtmltopdf to run within a sandbox. It appears in `scripts/build.py` that many, if not all, `-static` flags are enabled. But running `ldd` on the final binary produces a list of 20 shared dependencies, listed below:

```
$ ldd static-build/linux-generic-amd64/wkhtmltox/bin/wkhtmltopdf
        linux-vdso.so.1 =>  (0x00007ffcf5bea000)
        libXrender.so.1 => /usr/lib/x86_64-linux-gnu/libXrender.so.1 (0x00007f9102bf8000)
        libfontconfig.so.1 => /usr/lib/x86_64-linux-gnu/libfontconfig.so.1 (0x00007f91029b5000)
        libfreetype.so.6 => /usr/lib/x86_64-linux-gnu/libfreetype.so.6 (0x00007f9102708000)
        libXext.so.6 => /usr/lib/x86_64-linux-gnu/libXext.so.6 (0x00007f91024f6000)
        libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007f91021bd000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f9101fb7000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f9101daf000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f9101b91000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f9101809000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f9101500000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f91012e9000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f9100f20000)
        /lib64/ld-linux-x86-64.so.2 (0x0000558b3cae2000)
        libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007f9100cf6000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f9100ada000)
        libpng16.so.16 => /usr/lib/x86_64-linux-gnu/libpng16.so.16 (0x00007f91008a8000)
        libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007f9100686000)
        libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007f9100480000)
        libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007f910027a000)
``` 

Some of these appear to be unused:

```
$ ldd -u static-build/linux-generic-amd64/wkhtmltox/bin/wkhtmltopdf
Unused direct dependencies:
        /usr/lib/x86_64-linux-gnu/libXrender.so.1
        /usr/lib/x86_64-linux-gnu/libfontconfig.so.1
        /usr/lib/x86_64-linux-gnu/libfreetype.so.6
        /usr/lib/x86_64-linux-gnu/libXext.so.6
        /usr/lib/x86_64-linux-gnu/libX11.so.6
        /lib/x86_64-linux-gnu/libdl.so.2
        /lib/x86_64-linux-gnu/librt.so.1
        /lib/x86_64-linux-gnu/libm.so.6
        /lib/x86_64-linux-gnu/libgcc_s.so.1
        /lib64/ld-linux-x86-64.so.2
```

Are these dependencies for Qt? Why are the unused dependencies also being linked? How can I staticallly link the required dependencies?

Any insight would be much appreciated.

thanks,
Razi

**Comment by rrshaban** [comment]
Further investigation suggests these dynamic dependencies are from X11. Continuing to look into this.

**Comment by rrshaban** [comment]
I managed to build a truly static version of wkhtmltopdf (no dynamic dependencies) by re-running the final compile step (after  `qmake...` and `make...` called in `build.py`) from working directory `wkhtmltopdf/static-build/linux-generic-amd64/app/src/pdf`, as below:

> g++ -Wl,-O1,**-Bstatic** -o ../../bin/wkhtmltopdf outputter.o manoutputter.o htmloutputter.o textoutputter.o arghandler.o commondocparts.o commandlineparserbase.o commonarguments.o progressfeedback.o loadsettings.o logging.o multipageloader.o tempfile.o converter.o websettings.o reflect.o utilities.o pdfsettings.o pdfconverter.o outline.o tocstylesheet.o imagesettings.o imageconverter.o pdf_c_bindings.o image_c_bindings.o wkhtmltopdf.o pdfarguments.o pdfcommandlineparser.o pdfdocparts.o moc_progressfeedback.o moc_multipageloader_p.o moc_converter_p.o moc_pdfconverter_p.o moc_imageconverter_p.o moc_pdf_c_bindings_p.o moc_image_c_bindings_p.o moc_converter.o moc_multipageloader.o moc_utilities.o moc_pdfconverter.o moc_imageconverter.o qrc_wkhtmltopdf.o   **-static-libgcc** -L/home/kbuilder/wkhtmltopdf/static-build/linux-generic-amd64/qt/lib -L/home/kbuilder/wkhtmltopdf/static-build/linux-generic-amd64/qt/plugins/codecs -lqcncodecs -L/home/kbuilder/wkhtmltopdf/static-build/linux-generic-amd64/deplibs/lib -L/home/kbuilder/wkhtmltopdf/static-build/linux-generic-amd64/qt/lib -lqjpcodecs -lqkrcodecs -lqtwcodecs -lQtWebKit -L/usr/X11R6/lib -lQtSvg -lQtXmlPatterns -lQtGui -ljpeg -lpng -lXrender -lfontconfig **-lexpat** -lfreetype -lXext -lX11 **-lxcb -lXau -lXdmcp** -lQtNetwork -lQtCore -lz -lm -ldl -lrt -lpthread


The primary differences are bolded above and listed below for convenience:
-BStatic
-static-libgcc
-lexpat
-lxcb
-lXau
-lXdmcp


I'm sure there's a way to enable these flags in QMake, but I'd rather not work through the labyrinth that is build.py again, so I will leave this information here in the hope that it will inform the next person to need an actually-static binary.

**Comment by chris001** [comment]
@rrshaban 
Some users have reported missing runtime dynamic dependencies causing `wkhtmltopdf` to fail, here:
https://github.com/Yenthe666/InstallScript/issues/80#issuecomment-366622217
* The solution, on ubuntu 16.04 at least, might be to install 3 dependencies, command `apt install xvfb libxrender1 fontconfig`. Does this sound right to you?
* Ideally, the released binary would be built to be truly static and not depend on anything dynamically at runtime.
*  Similar result as you got for `ldd -u`, with `whtmltopdf` 0.12.4 (the newest version), installed from prebuilt generic linux release, downloaded from this github repo:
```
ldd -u /usr/local/bin/wkhtmltopdf
Unused direct dependencies:
        /usr/lib/x86_64-linux-gnu/libXrender.so.1
        /usr/lib/x86_64-linux-gnu/libfontconfig.so.1
        /usr/lib/x86_64-linux-gnu/libfreetype.so.6
        /usr/lib/x86_64-linux-gnu/libXext.so.6
        /usr/lib/x86_64-linux-gnu/libX11.so.6
        /lib/x86_64-linux-gnu/libz.so.1
        /lib/x86_64-linux-gnu/libdl.so.2
        /lib/x86_64-linux-gnu/librt.so.1
        /lib/x86_64-linux-gnu/libm.so.6
        /lib/x86_64-linux-gnu/libgcc_s.so.1
        /lib64/ld-linux-x86-64.so.2
```

**Comment by ashkulz** [comment]
This is close to impossible, as there will always be a dependency on the host OS for providing font related configuration and discovery.

Currently working on a reworked packaging system in the [wkhtmltopdf/packaging](https://github.com/wkhtmltopdf/packaging) repository, you can download preview builds [for linux](https://builds.wkhtmltopdf.org/0.12.5-dev/) which move back to a distro-specific package approach.
