### ISSUE TITLE
Text does not render when minor changes are made to HTML

### ISSUE THREAD

**Issue by littletreex** [wkhtmltopdf/wkhtmltopdf#3471]
This is a very strange issue, and I cannot understand why it would occur. This could be a bug, or I missing something.

I have a portlet with an actions div (buttons that show up in the title bar of the portlet). If I leave this div and it's anchor tag within the printable code, everything comes out fine. However, if I remove the anchor from this div, NONE of the text in the page renders. 

This is the line of code in question:
`<div class="actions"><a class="btn green" href="/util/closeOut"><i class="fa fa-arrow-left"></i> Back to Log</a></div>`

It doesn't make sense to me why removing this one anchor from a rather complex html page would break the PDF generation such that no text would render at all. I have attached a screenshot of both instances of rendering for reference.

Text not rendering after remove the aforementioned anchor tag:

![wkhtmltopdf-notext](https://cloud.githubusercontent.com/assets/20190185/26013507/c20d062a-3726-11e7-84f0-dee53bfcf359.JPG)

Text renders fine once if I leave the anchor tag alone:
![wkhtmltopdf-withtext](https://cloud.githubusercontent.com/assets/20190185/26013506/c1bb370a-3726-11e7-951a-e7043d91b87f.JPG)

The problem is that his anchor tag is a navigation button and makes no sense for it to print in the report.

I had this same problem with removing my footer. Ultimately, this was solved by using `--print-media-type`. In other words, I had to leave the footer in the code, but using the `@media print` css, the footer is set to `display:none`. 

I guess I could go through and set each offending element to `display:none`, but without an understanding of why this is happening, I could make many changes and not know which element was the key to keeping it working.

UPDATE: Adding `style="display:none;"` to the anchor tag DID NOT fix the problem. Also, if I simply remove the link text, the rendering issue resurfaces. So, leaving an empty `<a>` is not sufficient.

**Comment by littletreex** [comment]
With a bit more testing on this, I've discovered a bit more about this issue.

I went through ALL of the styles applied to the anchor in question, and turn them off one by one. It appears that this style must be applied to either the anchor in question, or one of it's parents:
`font-weight: 600;`

I tried different values of the `font-weight` and none work. It **must** be `font-weight:600;`. 

This `font-weight` is within a properly closed div (since I was finally able to remove the anchor), so it makes no sense to me why it would have such an impact on the text rendering. In other words, this style isn't some how leaking into child elements.

Specifically, the code in question is as follows:
```
    <div class="caption" style="font-weight: 600;"> 
        Blah blah blah header info    
        <div class="tools"></div>
    </div>
```

Why would this bit of code dictate the entire documents visibility of text when converted to a PDF?

**Comment by PhilterPaper** [comment]
Perhaps whatever font you're using doesn't have a 600 weight entry. Is it possible to change the font-weight from **600** to **bold**?

**Comment by littletreex** [comment]
I believe you are misunderstanding the problem I am having. However, to be clear I have no issues rendering `font-weight: 600`, or any other value (in the browser).

The problem is **not** that I have issues when I set this div to **600**, the problem is that if i set it to **anything else** the text on my page does not render (in the PDF, it displays fine in the browser). 

Please refer to the images in my first post to see an example of the problem, and my second post points out that the div in question is closed and placed in the middle of the code. It is above most everything else, but the elements that follow it are not children of the div that is causing the issue.

I point out the "closed div" because it the font in one self contained div **should not** have any effect on **ALL** the text within the page. It would be understandable, if by changing this value there were issues with the text contained inside the div, but there is no good reason why it should effect things outside of it. Also, this page displays just fine in the browser regardless of the settings I choose.

**Comment by littletreex** [comment]
I solved this issue by excluding any linked versions of the font (Open Sans), and using `@font-face` to point to a local folder containing the truetype version. I still believe there to be some other issue, since there were circumstances (leaving seemingly random elements in place) where I could still render this page even with the linked fonts. However, adding the font locally does seem to consistently solve the problem.

**Comment by PhilterPaper** [comment]
Does this "fa" class automatically include the **(/UTIL/CLOSEOUT)** text and the frame around the whole thing? It _does_ seem odd that removing the entire thing would have effects around it.

I asked about the 600 weight because it sounded like if you were _not_ using exactly 600, it wasn't finding the desired text (whereas using "bold" probably would use the 600 weight font file). Perhaps I misunderstood you. Is that independent of the anchor entry issue? Anyway, (without the anchor text) it looks like it is getting the right characters (with regards to widths), but only the $ are printing out. Are the $'s in the same typeface and weight as the other text? Maybe it was still using some default font to get the widths. Very strange indeed.

Could it be that there was a time-out when attempting to access a remote font file? Did you try any sort of loading delay flag (normally used for Javascript execution)? Are you being excluded by some access or permissions issue from getting to that font (but browsers are let in)?

If you have it working now, you may want to drop the issue, but it would always be nice to know just what happened.

**Comment by littletreex** [comment]
`<i class="fa fa-arrow-left"></i>` is an icon from "font awesome". The `fa` class as well as `fa-arrow-left` are the needed classes to make icons display properly. For that matter, the $ symbols are also font awesome icons. (If you're not familiar with font awesome, you should check it out).

This means that this particular class has no bearing on this issue. It also is the reason that the dollar signs still print; it's because they are icons and not text using the 'Open Sans' font.

I believe that the problem really just has to do with how wkhtmltopdf loads or interprets the font. I did note elsewhere that it does not seem to play nice with `<link></link>` style web fonts (which is what I was originally doing).

However, what makes this so odd, is that there were circumstances in which the text would show up just fine, which means on some level linking the web font does in fact work. To better illustrate the issue, take a look at this trimmed down html code below. As you can see the elements in question were seemingly in "random" places within the code, and removing these elements caused the text render issue. That's what makes it so weird. Why would those particular divs be required with the specific font settings in order for the entire page to render properly or not. 

```
<!DOCTYPE html>
<html lang="en">
    <head>
        <!-- All the usual css and meta data here -->
    </head>
    <body class="page-container-bg-solid">
        <div class="page-wrapper">
            <div id="page-content">
                <div class="portlet">

                    <!-- Removing the anchor tag within the following div would cause the issue -->
                    <div class="portlet-title">
                        <div class="caption">
                            Vieweing Close Out for store 6 from 2016-12-06 14:41:52.660
                            <div class="tools"></div>
                        </div>
                        <div class="actions"><a class="btn" href="/util/closeOut">a</a></div>
                    </div>
                    <!-- the only workaround was to apply the font-weight:600 to the 'caption' div -->

                    <div class="portlet-body">
                        <!-- main content of portlet goes here -->
                    </div>
                </div>
            </div>
        </div>

        <!-- oddly enough removing the following div (which is the page footer), also caused the problem. -->
        <!-- I didn't want the actual footer styling in the print out, so the only work around was to set the font-size and font-weight -->
        <div style ="font-size: 13px;   font-weight: 300;">
            <div class="container-fluid"> 
                <!-- removing this div also causes the text render problem. I never did find the styles needed to prevent it -->
            </div>
        </div>
        
    </body>
</html>
```

Given that it is still a bit baffling as to why this would happen, I think that the take away is that it can be solved by adding the font in question locally. I will close this issue, since there is at least a solid code solution available.

**Comment by MRayp** [comment]
i have same issue with farsi font! my pdf render most of the times just fine, but not always and i dont know what is the situation! however if i try to regenerate pdf it works well. i tried different fonts and also put all (eot, woff2, woff, ttf). have no idea what to do...
