### ISSUE TITLE
Convert HTML to PDF using wkhtmltopdf, docker in ASP.NET Core

### ISSUE THREAD

**Issue by mskuratowski** [wkhtmltopdf/wkhtmltopdf#3475]
I'm trying to convert HTML to PDF using wkhtmltopdf in my ASP.NET Core app. 
I've added a wkhtmltopdf.exe to my project and marked as a Copy to an output to always.

Here's my code:
```
var htmlContent = receiptBody;
var wkhtmltopdf = new FileInfo(@"/app/Configuration/Wkhtmltopdf/wkhtmltopdf.exe");
var converter = new HtmlToPdfConverter(wkhtmltopdf);
var pdfBytes = converter.ConvertToPdf(htmlContent);
```

The file has been founded but on:

`var pdfBytes = converter.ConvertToPdf(htmlContent);`

I'm getting an error:

System.Exception: Cannot generate PDF: Broken pipe --->
System.IO.IOException: Broken pipe

I run my app using Docker https://hub.docker.com/r/microsoft/aspnetcore/ and here is my dockerfile:

```
FROM microsoft/aspnetcore:1.1.2 ARG source WORKDIR /app 
ENV ASPNETCORE_URLS http://project-test:80 
EXPOSE 80 
COPY ${source:-obj/Docker/publish} . 
RUN apt-get update 
RUN apt-get install-y libgdiplus 
ENTRYPOINT ["dotnet", "ProjectTest.dll"]
```

Maybe should somehow install wkhtmltopdf for linux?

**Comment by andrewduan** [comment]
Sorry for adding something here. I have the same problem "broken pipe" issue.
I have installed wkhtmltopdf 0.12.4 version on Ubuntu 16.4. The application runs on .net core 2.

Hopefully it could get fixed soon.

**Comment by EbarriosCode** [comment]
I'm having the same problem someone knows if it's resolved

**Comment by ashkulz** [comment]
Looks like the command did not run properly, try running it directly and see if it works. Also, if you are using Ubuntu 16.04 use the distro-specific builds from https://builds.wkhtmltopdf.org/

**Comment by saisiva249** [comment]
Is this issue resolved, iam having the same issue and not able to solve this, i have ran application in windows and the same deployed the application in Linux, which is not working. 

```
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /app

COPY . ./

RUN dotnet restore "PDFWebAPI/PDFWebAPI.csproj"

RUN dotnet publish  "PDFWebAPI/PDFWebAPI.csproj" -c Release -o out

FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app


EXPOSE 8080

COPY --from=build /app/out/ ./
ENV ASPNETCORE_URLS=http://*:8080
ENTRYPOINT ["dotnet", "PDFWebAPI.dll"]
```

this is working in windows whereas it is not working in Linux.

Thanks in advance.
