### ISSUE TITLE
wkhtmltopdf 0.12. Win10 Familly - HostNotFoundError

### ISSUE THREAD

**Issue by artofit** [wkhtmltopdf/wkhtmltopdf#3478]
Hi,

Until recently, execution wkhtmltopdf  was running without problem.
I had some Win10 automatic update.
Now if I excecute wkhtmltopdf I get:
`E:\>wkhtmltopdf.exe --footer-spacing 5 --footer-font-size 8 --footer-left "Phil" --footer-right "[page]/[topage]" -L 16mm -R 16mm -T 18mm -B 18mm --no-background --zoom 1.45 "CV.htm" "CV.pdf"
Loading pages (1/6)
Error: Failed loading page http: (sometimes it will work just to ignore this error with --load-error-handling ignore)
Exit with code 1 due to network error: HostNotFoundError

`E:\>``
I tried to execute in admin console, to see if there were some change, without success.
Same if I had  

> --load-error-handling  ignore

Couldn't find a solution.

RMK:
https://github.com/wkhtmltopdf/wkhtmltopdf/issues/2532
https://github.com/wkhtmltopdf/wkhtmltopdf/issues/2451

**Comment by rsov** [comment]
try removing the `--footer-right` option

**Comment by NiR-** [comment]
Hello @artofit, could you copy/paste CV.htm here please?

**Comment by alloylab** [comment]
is this still an issue on 0.12.5?

**Comment by Tomsgu** [comment]
Closing as there is no response from the author and there is not enough information to reproduce the issue.
