### ISSUE TITLE
Generate PDF how to link page?

### ISSUE THREAD

**Issue by wonderaa** [wkhtmltopdf/wkhtmltopdf#3479]
Generate PDF how to paging?

**Comment by wonderaa** [comment]
Generate PDF how to paging?

**Comment by NiR-** [comment]
What do you mean? Could you provide more explanations about what you intend to do or even a small test case please?

**Comment by alloylab** [comment]
is this still an issue on 0.12.5? also what version? and os?

**Comment by Tomsgu** [comment]
Closing as the issue doesn't make any sense.
