### ISSUE TITLE
Paper size vs DPI looks incorrect while rendering

### ISSUE THREAD

**Issue by pimjansen** [wkhtmltopdf/wkhtmltopdf#3484]
I run below command to create the actual PDF

`/vagrant/vendor/bin/wkhtmltopdf-amd64 --lowquality --dpi '72' --margin-bottom '55' --margin-left '0' --margin-right '0' --margin-top '34.395833333' --page-size 'A4' --encoding 'UTF-8' --user-style-sheet '/vagrant/skin/frontend/default/css/contract.css' --footer-html '/tmp/knp_snappy5925400bb49047.53578967.html' --header-html '/tmp/knp_snappy5925400bb49255.87457934.html' --header-spacing '34.395833333'  '/tmp/knp_snappy5925400bb48916.70619564.html' '/tmp/knp_snappy5925400bb48e22.64069958.pdf'`

As you can see the settings are set to 72 DPI and the page size to A4. Technically this means that the width of the document should be 595px.

The image below however shows it is rendered completely different. It looks like still 96DPI is used instead

![pdf_size](https://cloud.githubusercontent.com/assets/1457219/26393242/889a359c-4069-11e7-991e-fc9820fe109b.png)

**Comment by danger89** [comment]
version of used wkhtmltopd? Distribution?  Version?

**Comment by alloylab** [comment]
is this still an issue on 0.12.5?
