### ISSUE TITLE
Reminder: anchors / internal links not working [solution]

### ISSUE THREAD

**Issue by benedekh** [wkhtmltopdf/wkhtmltopdf#3486]
It is just a reminder to future self and everyone, who is struggling with the problem: "anchors, internal links not working in wkhtmltopdf 0.12.4 (or maybe earlier versions also)"

__Problem:__

If you have an anchor whose content is empty, then [they will be removed by WebKit](https://github.com/wkhtmltopdf/wkhtmltopdf/issues/1554#issuecomment-36514510). (Thank you @ashkulz for pointing it out!)

```html
<a name="here"></a>
....
I want to go <a href="#here">there.</a>
```

__Solution:__

Put anything within the anchor, and it should work now:

```html
<a name="here">&nbsp;</a>
....
I want to go <a href="#here">there.</a>
```

This issue is linked to #1554, #2949, #2153 and maybe to some other PRs and issues also that I have not found yet.

__Acknowledgement:__

I would like to say a huge thank you to @ashkulz for pointing out the issue with WebKit. I would also like to say thank you any contributor who fixes (or has already fixed, e.g. @rpedela in #2949) this problem in a PR.

**Comment by allenwu1973** [comment]
Thanks! You saved my day. I found setting display to block with CSS also fix this.

```css
a:empty {
  display: block;
}
```

**Comment by benedekh** [comment]
@allenwu1973 I'm glad I could help you :-)

**Comment by asmshaon** [comment]
> Thanks! You saved my day. I found setting display to block with CSS also fix this.
> 
> ```css
> a:empty {
>   display: block;
>   position: absolute; /* see #4404 */
> }
> ```

This works for me, thanks a lot
