### ISSUE TITLE
The line weight display different on different server 

### ISSUE THREAD

**Issue by voathnak** [wkhtmltopdf/wkhtmltopdf#3493]
I'm having issue that I use the same border  1px  solid black, but on the ubuntu server display thinner than my local mac os. And I'm using the same version of wkhtmltopdf 0.12.2.1 (with patched qt)

**Comment by daudmalik06** [comment]
@voathnak  ,try this new library which uses chrome cli as browser so no more these kind of issues , very simple interface , easy to install
https://github.com/daudmalik06/PhpChromeToPdf

**Comment by alloylab** [comment]
is this still an issue on 0.12.5?

**Comment by Tomsgu** [comment]
`0.12.2.1` is an old version, so I am closing this. Please feel free to re-open if you still experience this in a new version.
