### ISSUE TITLE
 wkhtmltopdf General › Wordpress and wkthmltopdf - I need support

### ISSUE THREAD

**Issue by ToBulk** [wkhtmltopdf/wkhtmltopdf#3494]
I would like to integrate wkhtmltopdf with my Wordpress template realhomes wkhtmltopdf.

http://realhomes.inspirythemes.biz/property/401-biscayne-boulevard-miami/

And this Wordpress plugin:

https://wordpress.org/plugins/tags/wkhtmltopdf/

I now have points where hang.

1.) how do I generate the process to save the page as PDF? The pdf name should be the name!

`  ?>
        
        <span class="printer-icon"><a href="  ????? <i class="fa fa-print"></i><?php _e('','framework'); ?></a></span>`

2.) "How/where" I create an individual PDF template? (Header, footer, selected content)?

**Comment by daudmalik06** [comment]
@ToBulk ,try this new library which uses chrome cli as browser so no more these kind of issues , very simple interface , easy to install
https://github.com/daudmalik06/PhpChromeToPdf

**Comment by Tomsgu** [comment]
Please refer to plugin you use or use stackoverflow for these kind of questions.
