### ISSUE TITLE
Tiny radiobuttons and checkboxes

### ISSUE THREAD

**Issue by sandergroen** [wkhtmltopdf/wkhtmltopdf#3501]
When I print a document with form elements (radiobuttons, checkboxes) I get tiny form elements when using version 0.12.4 in version 0.12.3 everything works just fine. I have tried to use svg images instead but this does not give me a better result. Do I forget an parameter or something or is this a bug?

**Comment by daudmalik06** [comment]
@sandergroen ,try this new library which uses chrome cli as browser so no more these kind of issues , very simple interface , easy to install
https://github.com/daudmalik06/PhpChromeToPdf

**Comment by sandergroen** [comment]
@daudmalik06 , thanks for your response. I'm using Ruby not PHP so I will not be able to use your library. Using the headless Chrome browser is interesting but I miss the features that wkhtmltopdf has for adding a cover page and page headers and footers etc.

**Comment by alloylab** [comment]
is this still an issue on 0.12.5?

**Comment by sandergroen** [comment]
@alloylab I have just tested the 0.12.5 version. It is not an issue anymore in 0.12.5.
