### ISSUE TITLE
Page break not cleanly separating content

### ISSUE THREAD

**Issue by W4RH4WK** [wkhtmltopdf/wkhtmltopdf#3503]
In my PDF output the content at the start of one page is also partly visible on the previous page. See these screenshots for example. As this does not happen when printing via Chromium I do not suspect an error with my CSS.

    $ wkhtmltopdf --version
    wkhtmltopdf 0.12.4 (with patched qt)

![screenshot_2017-06-03_18-47-44](https://cloud.githubusercontent.com/assets/328798/26755443/9f8428ae-488d-11e7-9ab8-e27fab229db6.png)

![screenshot_2017-06-03_18-47-52](https://cloud.githubusercontent.com/assets/328798/26755444/a193ea8a-488d-11e7-9343-29856b936d30.png)

![screenshot_2017-06-03_18-48-55](https://cloud.githubusercontent.com/assets/328798/26755445/a45080bc-488d-11e7-8a25-06e678bf3fb7.png)

**Comment by PhilterPaper** [comment]
This problem, with a line being split between two pages, has been reported many times (#2141, #2261, et al.). I don't think any consistent solution has been found.

**Comment by W4RH4WK** [comment]
Sorry, I searched for this issue before posting but somehow did not find the two related issues mentioned. Closing this as it is a duplicate.
