### ISSUE TITLE
Website down

### ISSUE THREAD

**Issue by belcloud** [wkhtmltopdf/wkhtmltopdf#3508]
Hello

We have noticed the website wkhtmltopdf.org is down.

Is there any reason for that?

Regards
Dan

**Comment by lpuccini** [comment]
also repositories (http://downloads.wkhtmltopdf.org) are not reachable

**Comment by aviaks** [comment]
Yes, it's not responding, all automation builds allso fail..

**Comment by cosmostail** [comment]
any ETA when it is back? I had several packages failures including the php-phing.. do they all use same provider?

**Comment by EvanMcEwen** [comment]
Also having issues.

**Comment by myoung34** [comment]
Its back. Start caching your packages ASAP

**Comment by lwchkg** [comment]
Just an idea: is it feasible to set up a free CloudFlare CDN service to speed up the website? (This should also reduce downtime too with CloudFlare's cache.)

**Comment by ashkulz** [comment]
I've set up a monitoring service [status.wkhtmltopdf.org](https://status.wkhtmltopdf.org/) now, so if it happens again I'll be notified ASAP. The server I was hosting it on got rebooted and the VM did not come back on. I got offers from Fastly and BunnyCDN, but yet to configure it properly ... will try to switch downloads.wkhtmltopdf.org to use a CDN and use CloudFlare for the website sometime this weekend.

**Comment by hanshenrik** [comment]
I'm experiencing extremely slow downloads today. The website was also down for parts of the day. Could this be in relation to this issue?

**Comment by gsdevme** [comment]
@ashkulz Seems like the website isn't stable can you take a look at https://github.com/wkhtmltopdf/wkhtmltopdf/issues/3518 please

**Comment by myoung34** [comment]
I recommend packaging up the files you need and hosting them in S3 until they become more stable. I recently packaged it up into our AWS base AMI and am surviving this wave

**Comment by ashkulz** [comment]
See #3518 -- releases are now hosted on Github.

**Comment by bfouts-kindred** [comment]
This article really came through for me today. The website is down again due to SSL issues and this got me unblocked. Thanks all.
