### ISSUE TITLE
Columns

### ISSUE THREAD

**Issue by GeneralGorgonzola** [wkhtmltopdf/wkhtmltopdf#3511]
Hi,

It is possible to "automagically" break text into columns in HTML using some styling, such as this:

.text3columns {
    -webkit-column-count: 3;
    -moz-column-count: 3;
    column-count: 3;
    -webkit-column-gap: 40px;
    -moz-column-gap: 40px;
    column-gap: 40px;
} 

For instance (some pseudocode here, sorry I am new to this):

div class="text3columns"
Lots and lots of text that goes on forever.....
/div

But it doesn't seem to work when converting the HTML to PDF?
It all ends up on one line.

It may be my mistake - is there a way?

Kind regards

**Comment by ChristianYeah** [comment]
#1872

**Comment by GeneralGorgonzola** [comment]
Works perfectly, thanks.
