### ISSUE TITLE
Download server down

### ISSUE THREAD

**Issue by dseravalli** [wkhtmltopdf/wkhtmltopdf#3518]
For the last 6 hours or so I have not been able to download releases from https://wkhtmltopdf.org/downloads.html and the website is very slow to load in general.

**Comment by gsdevme** [comment]
Yeah +1, can the binary releases to attached to the github perhaps here https://github.com/wkhtmltopdf/wkhtmltopdf/releases ? likely going to be a more stable solution.

**Comment by morriswinkler-simplesurance** [comment]
+1

**Comment by splatEric** [comment]
+1

**Comment by morriswinkler-simplesurance** [comment]
Looks like GNA is gone 

there are some mirrors
http://repo-install.vtech.fr/wkhtmltopdf/0.12/0.12.3/wkhtmltox-0.12.3_linux-generic-amd64.tar.xz

**Comment by gsdevme** [comment]
I can't find a mirror either, I happen to have a copy of 0.12.2.1 for CentOS 6.. Ive put it here for now https://github.com/usemarkup/wkhtmltopdf-rpm

**Comment by hanshenrik** [comment]
+1

**Comment by mrigesh** [comment]
+1

**Comment by graingert** [comment]
@ashkulz ^

**Comment by graingert** [comment]
I managed to extract 0.12.4 from the server with a download manager and hacking /etc/hosts https://github.com/graingert/wkhtmltopdf/releases/download/0.12.4/wkhtmltox-0.12.4_linux-generic-amd64.tar.xz

**Comment by chikien276** [comment]
Any mirror download link for windows guys ?

**Comment by graingert** [comment]
@chikien276 there's 4 different files. I'm kicking them off now....

You can download the files yourself with https://addons.mozilla.org/en-Gb/firefox/addon/downthemall/

**Comment by ashkulz** [comment]
Hmm, need to create a permanent solution (second time the server went down). Will set it up in an hour or two, have to copy from backup.

**Comment by graingert** [comment]
@ashkulz please just use github releases

**Comment by ashkulz** [comment]
People use old releases too, see above.

**Comment by graingert** [comment]
@ashkulz yes, can you also add the old releases to github releases.

**Comment by gsdevme** [comment]
Yeah please just attach to Github and even for old releases that will be the most stable thing to do in my eyes. If Github goes down its ok I know about it.. its "frontpage" news in the developer world.

**Comment by ashkulz** [comment]
Okay, all releases after `0.12.0` have been added to Github. Will bring the website backup over the weekend along with the obsolete releases (not sure if anyone is using them).

**Comment by gsdevme** [comment]
Im sure I can speak for everyone thanks alot @ashkulz

**Comment by graingert** [comment]
Here's a torrent with everything in http://itorrents.org/torrent/EFF821EB0E60EF1760DACC95A386CFE33F9FB94F.torrent

**Comment by ashkulz** [comment]
@graingert: now that everything is on Github, hopefully it should not be required.

Reopening this till the website issue is sorted out. I'd switch to Github Pages, but it would fail to load for quite a few people due to earlier HSTS settings.

Does anyone really want the obsolete downloads?

**Comment by graingert** [comment]
@ashkulz you could use cloudflare + github pages.

**Comment by graingert** [comment]
@ashkulz or gitlab pages, because they support custom x509 certs.

**Comment by ashkulz** [comment]
Okay, website is back up. If anybody needs the obsolete downloads, I'll think of uploading them somewhere.

**Comment by graingert** [comment]
@ashkulz any chance you can configure 308 redirects from the old download URLs?

**Comment by ashkulz** [comment]
@graingert: I've put HTTP `301` redirects in place (not sure `308` would be accepted by all clients, and it's GET anyway). I should also get feedback on how many people are trying to download the obsolete versions due to the 404 reports.

**Comment by graingert** [comment]
@ashkulz I'm getting direct downloads, with no 301. Eg https://downloads.wkhtmltopdf.org/0.12/0.12.4/wkhtmltox-0.12.4_linux-generic-amd64.tar.xz

**Comment by ashkulz** [comment]
It's working as designed :smile: as it does a 301 to the appropriate Github URL, which can start a direct download. e.g. see https://downloads.wkhtmltopdf.org/0.12/0.12.4/ vs your URL (there are a total of 2 redirects: 1 from wkhtmltopdf.org to github.com and from there to S3).

**Comment by ashkulz** [comment]
Thanks for the suggestion, though... anyone who hasn't updated to the Github URLs would still work. I should've thought about this instead of going down the self-hosting route.

**Comment by graingert** [comment]
@ashkulz ah I found the issue, I still had the /etc/hosts hack from https://github.com/wkhtmltopdf/wkhtmltopdf/issues/3518#issuecomment-309048531

**Comment by ashkulz** [comment]
Yeah, still have to shut that server down (which isn't in DNS).

**Comment by ashkulz** [comment]
It's offline now.

**Comment by TH-code** [comment]
I am in need of the https://downloads.wkhtmltopdf.org/obsolete/osx/wkhtmltopdf-0.9.9-OS-X.i368 , are the obsolete downloads also coming to github, so far not right? Or am I impatient?

**Comment by graingert** [comment]
@TH-code you should just try the upgrade.

**Comment by TH-code** [comment]
I'm dealing with an old codebase where upgrade is not an option.

**Comment by ashkulz** [comment]
Okay, bringing them back is a pain as there is no easy way to remap URLs to github, leave alone creating releases here. I'll look into this tomorrow morning.

**Comment by TH-code** [comment]
You could wait to see if I'm the only one needing them. I have so far not been able to find them anywhere, so I would expect more people will come looking. For my project I have a workaround (don't rebuild it), but its not a future proof one.

**Comment by graingert** [comment]
Give the new version a go, just for me?

**Comment by TH-code** [comment]
Will try when I can.

**Comment by ashkulz** [comment]
Okay, now all URLs (including the above) should work. I've created a separate repository to host the downloads.

**Comment by TH-code** [comment]
Thank you so much! Perfect!

**Comment by ashkulz** [comment]
For the record, the final nginx config is (in case I need it later):
```
rewrite ^/$               https://github.com/wkhtmltopdf/wkhtmltopdf/releases                    permanent;
rewrite ^/0.12/(.*)/$     https://github.com/wkhtmltopdf/wkhtmltopdf/releases/$1                 permanent;
rewrite ^/0.12/(.*)$      https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/$1        permanent;
rewrite ^/obsolete/(.*)/$ https://github.com/wkhtmltopdf/obsolete-downloads/releases/$1          permanent;
rewrite ^/obsolete/(.*)$  https://github.com/wkhtmltopdf/obsolete-downloads/releases/download/$1 permanent;
```

**Comment by graingert** [comment]
Stick it in git?

**Comment by ashkulz** [comment]
I don't expect to keep it around forever, hopefully people will migrate the links in a month or two.

**Comment by morriswinkler-simplesurance** [comment]
Just as a side note, it is possible to keep archives up for round about 25 years.

https://www.kernel.org/pub/linux/kernel/Historic/

**Comment by graingert** [comment]
Those guys have a lot of cash

**Comment by morriswinkler-simplesurance** [comment]
just saying 😚

**Comment by graingert** [comment]
> I don't expect to keep it around forever, hopefully people will migrate the links in a month or two.


@ashkulz it would be better to keep https://downloads.wkhtmltopdf.org/ because you have control over the redirects.

If you want to move the file hosting again you can just adjust the redirects and people will still be able to download the files.

**Comment by moylop260** [comment]
@ashkulz for webkit 0.12.1 and 0.12.2 I didn't find the `wkhtmltox-0.12.*_linux-generic-amd64.tar.xz` file.
Is possible added them?

In order to avoid a `if` validation to change the url and the process to install it:
 - `if [[ ${WKHTMLTOPDF_VERSION} == "0.12.1" ]] then...`
