### ISSUE TITLE
Windows Crash with Exception code: 0xc0000005

### ISSUE THREAD

**Issue by hugo-ruivo-dw** [wkhtmltopdf/wkhtmltopdf#3519]
I am getting randomly crashes with the following exception code when generating in command line when executing with:

`wkhtmltopdf.exe --header-html header.html --header-spacing 10 --dpi 96 --disable-smart-shrinking --enable-local-file-access --load-error-handling ignore --no-stop-slow-scripts --orientation Landscape --page-width 297 -B 10 -L 0 -R 0 -T 40 --zoom 1 body.html out.pdf`

I am using version 0.12.3.1

The crash occurs when using last version 0.12.4 too, but it is not as often as with version 0.12.3.1, for example in 10 runs with version 0.12.3.1 crashes 9 times but 0.12.4 crashes 2 times only.

**Comment by hugo-ruivo-dw** [comment]
Duplicated with: #2894

**Comment by ashkulz** [comment]
This should be fixed with `0.12.5-rc`, see #2711 for details.
