### ISSUE TITLE
Mirror Links

### ISSUE THREAD

**Issue by vinayakkulkarni** [wkhtmltopdf/wkhtmltopdf#3521]
First of all, this is a dope tool that I heavily use to create pdf's (using it via laravel-snappy), Kudos on that. 👏 

But last few hours, all my CI tests are failing thanks to 💩  wkhtmltopdf servers.

Does anyone has it hosted on a mirror site / location where one can download without 100% dependency on the wkhtmltopdf website? 

<img width="1119" alt="screen shot 2017-06-16 at 5 09 13 pm" src="https://user-images.githubusercontent.com/19776877/27225153-90611836-52b6-11e7-84b3-449bfab654fb.png">

**Comment by vinayakkulkarni** [comment]
I guess this is duplicate of #3518, but can someone provide mirror links?

**Comment by graingert** [comment]
@vinayakkulkarni I've got mirror links of the 64 bit linux URLs. https://github.com/wkhtmltopdf/wkhtmltopdf/issues/3518#issuecomment-309048531

**Comment by ashkulz** [comment]
See #3518, releases are now hosted on Github.
