### ISSUE TITLE
Documentation website is default nginx page

### ISSUE THREAD

**Issue by micmeemac** [wkhtmltopdf/wkhtmltopdf#3522]
![screen shot 2017-06-16 at 9 12 26 pm](https://user-images.githubusercontent.com/875098/27241305-897524fa-52d8-11e7-8e88-0728450e5377.png)

**Comment by justin-gerhardt** [comment]
If you need access for the moment a copy is achieved by archive.org. You can access it [here.](https://web.archive.org/web/20161118214348/http://wkhtmltopdf.org:80/docs.html)

**Comment by trewpog** [comment]
Try this. from the official page on github

https://github.com/wkhtmltopdf/wkhtmltopdf/releases

**Comment by ashkulz** [comment]
See #3518
