### ISSUE TITLE
i can not download your last relase

### ISSUE THREAD

**Issue by elba7r** [wkhtmltopdf/wkhtmltopdf#3524]
i can not download your latest relase 12.4 there is a problem , please check it !!!

**Comment by webular** [comment]
FYI  - I was able to download from the way back machine:


[https://web.archive.org/web/20170221142642/http://wkhtmltopdf.org/downloads.html](url)

**Comment by trewpog** [comment]
Try this. from the official page on github

https://github.com/wkhtmltopdf/wkhtmltopdf/releases

**Comment by ashkulz** [comment]
See #3518
