### ISSUE TITLE
sign SHA256SUM files.

### ISSUE THREAD

**Issue by graingert** [wkhtmltopdf/wkhtmltopdf#3525]
gpg --detach-sign SHA256SUMS

**Comment by graingert** [comment]
If it were not for the fact that

> SHA256 file is still downloadable from https://downloads.wkhtmltopdf.org/0.12/0.12.3/

It would have been impossible to share files found from the web as a temporary solution for those needing the file in https://github.com/wkhtmltopdf/wkhtmltopdf/issues/3518

**Comment by ashkulz** [comment]
Is that still a concern now that it's on github? Most projects releasing on Github don't even publish checksums...

**Comment by graingert** [comment]
@ashkulz I think it's different for browsers.

**Comment by ashkulz** [comment]
I'd still have to publish the gpg key, deal with key rotation, etc. Makes sense for a bigger project, just not this one I feel...

**Comment by ashkulz** [comment]
`0.12.5` was signed with a GPG key, and I'll sign the sha256sums file as well once the binaries are uploaded.

not sure how to share the key, is there a recommended practice for that?

**Comment by ashkulz** [comment]
Packages for 0.12.5 [are available](https://wkhtmltopdf.org/downloads.html#stable) using signed checksums.
