### ISSUE TITLE
Compiling on Ubuntu 16.04 with armhf architecture

### ISSUE THREAD

**Issue by Patrick-M90** [wkhtmltopdf/wkhtmltopdf#3535]
Hi Community,

can anybody help me installing wkhtmltopdf on a Ubuntu 16.04 armhf system?

I tried a lot of possible solutions from google, but allways ended up with wkhtmltopdf -V saying that it's not patched.

Maybe somebody can give me a step-by-step guide?

Thanks in advance.

**Comment by ashkulz** [comment]
Please open a new issue in [wkhtmltopdf/packaging](https://github.com/wkhtmltopdf/packaging) if you want to continue this discussion.
