### ISSUE TITLE
svg from mathjax was shrink in pdf ,scale is invalid

### ISSUE THREAD

**Issue by sunjingwu** [wkhtmltopdf/wkhtmltopdf#3537]
v: 0.12.4
os: windows 10
mathjax v:2.7.0

jax: ["input/TeX","output/SVG"],
[html doc](http://smillence.com/svg.html)
[pdf doc](http://smillence.com/svg.pdf)

**Comment by Tomsgu** [comment]
Closing as links are not working and the issue has no additional information.
