### ISSUE TITLE
breaks when using HTTPS

### ISSUE THREAD

**Issue by nickcom** [wkhtmltopdf/wkhtmltopdf#3539]
I've been using wkhtmltopdf for over a year on a site under HTTP. I needed to switch things over to HTTPS and now the PDF's aren't generated properly. It seems to be a timing thing because sometimes the PDFs are generated, but they are incomplete or missing formatting. Usually however, the resulting PDF's can not be opened. 

The site converts an HTML report to a page, and this HTML report loads just fine now that HTTPS is being used. No code changes have been done other than switching the site to HTTPS.

Are there any config changes necessary to wkhtmltopdf under HTTPS?

**Comment by vohoailen** [comment]
Could you post your website url for testing? I'm using wkhtmltopdf with https and it works fine with me.

**Comment by PhilterPaper** [comment]
> It seems to be a timing thing because sometimes the PDFs are generated

Generating SSL-encrypted content at the server takes a little longer than non-SSL, and decrypting it on the receiving end also takes a little longer. Maybe you are _just_ going over some time-out limit most of the time. Have you tried one of the command-line switches to allow more time for rendering? Usually they're used to allow more time for Javascript processing, but it might work for you.

**Comment by nickcom** [comment]
Thanks for your replies. I believe it is something to do with the HTTPS delay, however I have tried the --javascript-delay option which didn't help. It is weird because when I run in terminal I can see the process takes a while to run, compared to say outputting google.com, but it just appears that is is writing to PDF while the page is still loading. I've got around this by loading a HTTP (not HTTPS) version of the PDF on the server, and download that copy over HTTPS. This means HTTPS integrity is intact, but it doesn't answer the question of why using the HTTPS version of the report fails when the HTTP version does not.

**Comment by vohoailen** [comment]
Do you try to use --no-stop-slow-scripts option to ask wkhtmltopdf render slow scripts?

**Comment by daudmalik06** [comment]
@nickcom yeah it happens some time try this new library which uses chrome as browser so no more these kind of issues , very simple interface , easy to install
https://github.com/daudmalik06/PhpChromeToPdf

**Comment by Tomsgu** [comment]
Https problems were fixed in 0.12.5. Please re-open if it doesn't work for you.

**Comment by zachgarcia1** [comment]
is this getting pushed soon? or is there a known fix? i'm having problems with https as well but everything seems to be working locally on my vagrant machine.

**Comment by zachgarcia1** [comment]
or is is only available through wget and not composer?

**Comment by samiramaspl** [comment]
> Https problems were fixed in 0.12.5. Please re-open if it doesn't work for you.

Hello I have same issue on HTTPs. It was thrown SSL errors before but after updating version 0.12.5 now errors were resolved but css including with https inside html content is not working there is no effect of css inside content.

what changes I have to do if I want to allow css with HTTPs inside content ?

**Comment by PhilterPaper** [comment]
This is a totally different problem than has been discussed. Do not hijack the discussion -- start a new one.
