### ISSUE TITLE
Building for PPC64LE under Ubuntu 16.04

### ISSUE THREAD

**Issue by sarahkemp** [wkhtmltopdf/wkhtmltopdf#3540]
I'm trying to build wkhtmltopdf from the source because the binaries available on https://wkhtmltopdf.org/downloads.html will not run on my system: 
 ```
$ ./wkhtmltopdf --version
    -bash: ./wkhtmltopdf: cannot execute binary file: Exec format error
```

I can run the official repo version, but it doesn't have the patched qt, so I can't use the html headers I need. I followed the directions in install.md:
* Running Ubuntu 16.04 on a PPC64LE machine
* Logged in as a normal user with sudo privileges
* Working directory is the user's home directory (unencrypted, in the standard location)
* git cloned --recursive the repo at https://github.com/wkhtmltopdf/wkhtmltopdf.git - it arrived at ~/wkhtmltopdf
* git pulled and updated submodules
* there is plenty of space on the hard drive
* Entered the ~/wkhtmltopdf directory:
```
$ sudo scripts/build.py setup-schroot-generic
    ******************* generic-amd64
    [104:111] Copy from cache: xz-libs-4.999.9-0.5.beta.20091007git.el6.x86_64.rpm .
    
    Execute postcmd of *-release package
    chroot: failed to run command ‘rpm’: Exec format error
    Running post-install script /usr/lib/rinse/common/10-resolv.conf.sh:
    Running post-install script /usr/lib/rinse/common/15-mount-proc.sh:
    Running post-install script /usr/lib/rinse/common/20-dev-zero.sh:
    Running post-install script /usr/lib/rinse/centos-6/post-install.sh:
      Bootstrapping yum
      cleaning up...
    chroot: failed to run command ‘/usr/bin/yum’: Exec format error
      post-install.sh : done.
    Installation complete.
    chroot: failed to run command ‘yum’: Exec format error
    chroot /var/chroot/wkhtmltox-generic-amd64 yum clean all
    command failed: exit code 32256
```
* Despite failures in previous command, I tried to proceed:
```
$ scripts/build.py linux-generic-amd64
    W: No chroots are defined in ‘/etc/schroot/schroot.conf’ or ‘/etc/schroot/chroot.d’
    E: wkhtmltox-generic-amd64: Chroot not found
    command inside chroot failed: exit code 256
```

Obviously I don't know what I'm doing, and I'm definitely not sure compiling from the source would even work if I could get it to complete. However, I am confident that I would not recognize the difference between a trivial problem and an insurmountable one in the course of building wkhtmltopdf - but I'm hoping someone here would.

I have looked at the mailing list for this repo and the forums for Linux on Power, but all I can find are unanswered questions on this subject. Can I run wkhtmltopdf (with patched qt) under Ubuntu 16.04 on a PPC64LE machine?

Thank you for reading.

**Comment by pmack** [comment]
The chroot setup script, as far as I can determine, only supports i386 and x86_64 as architectures. The error you're getting is the system trying to execute a i386/x86_64 binary on ppc hardware (exec format error). Take a look at the 'other' section in the installation documentation. It seems like you should be using the 'posix-local' target instead.

**Comment by sarahkemp** [comment]
Thank you for your response. I did manage to build it using the posix-local target after installing libx11-dev, libxext-dev, libxrender-dev, libssl-dev,l libpng-dev, and libjpeg-dev. Unfortunately I get a segmentation fault on execution.

```
~/wkhtmltopdf$ ./static-build/posix-local/app/bin/wkhtmltopdf http://google.com google.pdf
Loading pages (1/6)
Segmentation fault (core dumped)                             ] 10% 
```

I made the change to qt/src/3rdparty/webkit/Source/JavaScriptCore/wtf/PageAllocationAligned.cpp suggested in this Power on Linux thread: https://www.ibm.com/developerworks/community/forums/html/topic?id=94177684-c459-4d4a-b689-8201deac74a0 but it didn't help.

**Comment by sarahkemp** [comment]
I am using Ubuntu 16.04, not CentOS. I'd be happy to try out a build but I don't know what to do with an RPM. I created an issue in wkhtmltopdf/packaging: https://github.com/wkhtmltopdf/packaging/issues/6

Thank you for trying this out, I know it's not the most common setup.

**Comment by ashkulz** [comment]
Please see the [latest release](https://github.com/wkhtmltopdf/packaging/releases) which has packages for a lot of ppc64le targets. Please add a comment if you face any problems in using the packages :+1:

**Comment by ashkulz** [comment]
A release candidate for the **0.12.6** release is [now available for download](https://wkhtmltopdf.org/downloads.html#release-candidate), which should contain changes which possibly address this issue.

Would appreciate downloading the package and reporting back if any issues are encountered during testing. Assuming all goes well, I plan to release 0.12.6 on the 2-year anniversary of the previous release i.e. June 11, 2020.
