### ISSUE TITLE
The operation cannot be completed due to security reasons. Please inform the system admin. ( doc type: ir.filters, Operation: read)

### ISSUE THREAD

**Issue by JoseOliveira1975** [wkhtmltopdf/wkhtmltopdf#3546]
Hello all,

I am starting to work with Odoo 8, and I have this issue mention on the subject. The only person that can create an opportunity is the Admin user. All other users with the same configuration that the Admin have, cannot create an opportunity. Everytime that the users try, we get the error message.
I searched a lot in the foruns but I couldn't found any solution.

Just to mention that we can see the opportunities, and also we can edit the ones that are created by the Admin user, we cannot create new ones.

Can I have some help on this?

Thanks in advance.
Regards,
José Carlos

**Comment by JoseOliveira1975** [comment]
Hi

Can anyone help me on this issue, please?

Thanks.
Regards,
José Carlos

**Comment by JoseOliveira1975** [comment]
Hi all,

I really need some help, please.

Regards.
José Carlos

**Comment by NiR-** [comment]
@JoseOliveira1975 The message you report [does not come from wkhtml](https://github.com/wkhtmltopdf/wkhtmltopdf/search?utf8=%E2%9C%93&q=The+operation+cannot+be+completed+due+to+security+reasons.&type=) but rather [from Odoo itself](https://github.com/odoo/odoo/search?utf8=%E2%9C%93&q=The+operation+cannot+be+completed+due+to+security+reasons.&type=). You should ask for help on [its repository](https://github.com/odoo/odoo). Could you close this issue please?

**Comment by JoseOliveira1975** [comment]
Ok I will close the isue.

Thanks.
