### ISSUE TITLE
wkhtmltopdf css table problem

### ISSUE THREAD

**Issue by germanboy** [wkhtmltopdf/wkhtmltopdf#3553]
I use footer.html , header.html and use border in main html code. But when I use border table side lines  be longer than table. How can I fix it ?
http://i.imgur.com/lI8Yy85.png

**Comment by daudmalik06** [comment]
@germanboy  you can also try  this new library which uses chrome as browser so no more these kind of issues , very simple interface give it a try
https://github.com/daudmalik06/PhpChromeToPdf

**Comment by Tomsgu** [comment]
- Can you post an example? 
- What version are you using?
- What OS?

**Comment by PhilterPaper** [comment]
I think I reported that back in mid-2015, but I can't find the report number now. It happened whenever a table needed to be _split_ across pages, and the left and right borders carried right down to the bottom of the page, even though the cell had no content printed. I don't know if it was ever fixed. I vaguely recall having been using CSS to suppress breaking _within_ a table row.

**Comment by Tomsgu** [comment]
You're right @PhilterPaper. It seems to be #2486. I am closing the issue then, because there are no more information in this one that we can verify if they are the same.
