### ISSUE TITLE
Word break

### ISSUE THREAD

**Issue by Prem-Rexx** [wkhtmltopdf/wkhtmltopdf#3554]
While converting HTML to PDF Word tore and word breaking is coming. For that we guys are doing manual work while generating  PDF.

**Comment by daudmalik06** [comment]
you can also use this new library which uses chrome as browser so no more these kind of issues , very simple interface give it a try
https://github.com/daudmalik06/PhpChromeToPdf

**Comment by Prem-Rexx** [comment]
Dear Dawood,

   I have tried PhpChrometoPdf also. But still i got the same error. We
need solution using by wkhtmltopdf, In that can you help me?

 * Error Screenshot : *

   [image: Inline image 1]

   While generating HTML to PDF,Text cut-off is happening at bottom. How
can i resolve that thing? Can you help me in this case?

*Note :* I am using  wkhtmltopdf 0.12.4 (with patched qt)

Thanks in Advance.

Regards,
Prem

**Comment by daudmalik06** [comment]
alright can you provide a screenshot of error ?
or way to reproduce that error?
Thanks :)

**Comment by Prem-Rexx** [comment]
FYKI,

Find below attachment and see 184th content, text cut-off is coming. That
is the exact problem for me.

Regards,
Prem

**Comment by daudmalik06** [comment]
unfortunately i can't see any attachment :)
can you verify it your self ?

**Comment by Prem-Rexx** [comment]
I have attached again, Can you check it now,

--
Regards,
Prem

**Comment by Prem-Rexx** [comment]
Dear Dawood,

Do you got the attachment?

--
Regards,
Prem

**Comment by haroonmalik123** [comment]
@Prem-Rexx  Nope dear ...

**Comment by daudmalik06** [comment]
@Prem-Rexx  nope dear , try using desktop version of github

**Comment by Prem-Rexx** [comment]
![error](https://user-images.githubusercontent.com/29976172/28062846-dbde937a-664c-11e7-808c-b2299ef3892d.png)

**Comment by Prem-Rexx** [comment]
Dawood,

I think now you will get the screen-shot.

**Comment by daudmalik06** [comment]
yeah can you provide the source or link of the table ?

**Comment by Prem-Rexx** [comment]
Few minutes. I will send you ASAP.. Going for Meeting. Sorry

**Comment by Tomsgu** [comment]
Please see #2486, #1524, #2141.
