### ISSUE TITLE
Multipage table issues

### ISSUE THREAD

**Issue by mscha** [wkhtmltopdf/wkhtmltopdf#3557]
https://www.mscha.org/tmp/multipagetable.html has a (you guessed it) multipage table, with a `<thead>` that appears on every printed page.

Converted to PDF with wkhtmltopdf 0.12.4 (with patched qt); precompiled binary from the site; using --print-media-type .
Result: https://www.mscha.org/tmp/multipagetable.pdf

Two issues:

1. Rows are split between two pages.  (Example on last row of page 1, this is the top part of the first row on page 2.)
2. The `<thead>` is indeed repeated on every page, but the data is rendered on top of the header, instead of below it.

For comparison, Google Chrome on Windows, using Print / Save to PDF, generates https://www.mscha.org/tmp/multipagetable-chrome.pdf ; which doesn't have these issues.

**Comment by zavagli** [comment]
hi
1. did you try with...
https://css-tricks.com/almanac/properties/p/page-break/
on td or tr....

 td, tr {
    page-break-inside: avoid;
  }

2. you need  --margin-top

**Comment by mscha** [comment]
Thanks for the tip.
In fact, adding 
`td, tr {
    page-break-inside: avoid;
}`
fixed not only the first issue, but somewhat surprisingly also the second.

**Comment by zavagli** [comment]
top 👍

**Comment by daudmalik06** [comment]
you can also use this new library which uses chrome as browser so no more these kind of issues , very simple interface give it a try
https://github.com/daudmalik06/PhpChromeToPdf

**Comment by Tomsgu** [comment]
See also #1524.
