### ISSUE TITLE
PDF generator returned error code -1073741515!

### ISSUE THREAD

**Issue by ninoraccoon** [wkhtmltopdf/wkhtmltopdf#3558]
Hello in a specific instace of my aplication asp.net wkhtmltopdf report this error every time, i cheked a correct version of wkhtmltopdf.exe, tha the file is not bloqued in properties and tha have installed Visual C++ Redistributable Packages for Visual Studio 2013, what other thik can i check, thanks.

**Comment by Tomsgu** [comment]
Please see #3205.
