### ISSUE TITLE
Instructions for building docker image from source

### ISSUE THREAD

**Issue by mdagost** [wkhtmltopdf/wkhtmltopdf#3560]
I really wanted to be able to do a full compilation from source and end up with a re-useable docker image.  This was non-trivial though because of how the build uses a chroot environment and the `mount` and `umount` commands.  I eventually got this working using some docker-in-docker magic and figured I'd leave this here for posterity for others who encounter this.  If you'd like to add it to the README or install instructions somehow, that would be fine with me:

Start the outer docker container with the docker-in-docker image:
```
docker run --privileged --name outer-docker -d docker:dind
```

Start one inner container to run docker in that we\'ll use for building our image by hand:
```
docker run --privileged -it --rm --link outer-docker:docker docker:17.03 sh
```

Start a second inner container to run docker in so that we can commit our image when we\'re done building it:
```
docker run --privileged -it --rm --link outer-docker:docker docker:17.03 sh
```

In the first inner docker, get inside an interactive ubuntu container:
```
docker run --privileged -it ubuntu:14.04 /bin/bash
```

and then run all of the commands below:

```
apt-get update && apt-get install -y git python make g++ schroot openssl build-essential xorg libssl-dev

# wkhtml wants to be installed by a non-root user...
useradd --create-home wkhtml
usermod -aG sudo wkhtml
echo "wkhtml ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

cd /home/wkhtml && git clone --recursive https://github.com/wkhtmltopdf/wkhtmltopdf.git
cd /home/wkhtml/wkhtmltopdf && export SUDO_USER=wkhtml && scripts/build.py setup-schroot-generic
cd /home/wkhtml/wkhtmltopdf && scripts/build.py linux-generic-amd64
cp static-build/linux-generic-amd64/wkhtmltox/bin/* /usr/local/bin
cd /home/wkhtml/ && rm -rf wkhtmltopdf/
```

Now, from the second inner docker container do

```
docker ps
```

You should see ouput like this:

```
/ # docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
108320d8b32d        ubuntu:14.04        "/bin/bash"         2 hours ago         Up 3 hours                              stupefied_snyder
```

Grab the container ID from this output.  Finally, commit the built image and push it to a remote repository:

```
docker commit <CONTAINER_ID> remote_repository_name/wkhtml:latest
docker login
docker push remote_repository_name/wkhtml:latest
```

Voila!

**Comment by Craicerjack** [comment]
This seems unnecessarily complicated. Running 2 different containers inside another. There are simpler docker containers out there. (on dockerhub/cloud)

**Comment by macropin** [comment]
The root issue is two fold: The existing build scripts are overly complex and make use of `chroot`, and secondly Docker does not support `--privileged` mode for build operations. See https://github.com/moby/moby/issues/1916 

So this will never build cleanly in Docker unless the build scripting is changed, or the Docker devs give us priv'd builds.

**Comment by macropin** [comment]
@mdagost This Dockerfile works, and you could probably wrap it all up using DnD

```
FROM debian:latest

# Ref: https://github.com/wkhtmltopdf/wkhtmltopdf/blob/0.12.4/INSTALL.md

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update
RUN apt-get -y install git sudo schroot python

RUN groupadd builder --gid 500 \
 && useradd -m builder --uid 500 --gid 500

RUN echo "builder ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

USER builder

RUN cd ~ && git clone --recursive https://github.com/wkhtmltopdf/wkhtmltopdf.git \
 && cd wkhtmltopdf \
 && git checkout 0.12.4 \
 && git submodule update

## Then run these commands in the container running in priv'd mode (via docker exec)
# cd ~ && sudo ~builder/wkhtmltopdf/scripts/build.py setup-schroot-generic
# cd wkhtmltopdf && ./scripts/build.py linux-generic-amd64

##  then manually copy out your build
# docker cp builder:/home/builder/wkhtmltopdf/static-build/wkhtmltox-0.12.4_linux-generic-amd64.tar.xz ./
```

**Comment by Tomsgu** [comment]
Closing as there is a solution for it. There are also quite a few docker images on docker hub, where you can find different approaches.
