### ISSUE TITLE
wkhtmltopdf works on Mac, but ignores CSS on linux (knp_snappy)

### ISSUE THREAD

**Issue by jakenoble** [wkhtmltopdf/wkhtmltopdf#3563]
I am using `wkhtmltopdf` to generate PDFs from HTML. This works perfectly on my local machine, a Mac. I am also using the KnpSnappyBundle for Symfony.

But on my Linux server it failed to use CSS at all.

Also on Linux just using the `wkhtmltopdf` command fails, because it 'cannot connect to X server'.

The way around this I have found is to install `xvfb` and then in the binary config in KnpSnappyBundle set it to `xvfb-run wkhtmltopdf`

```
    knp_snappy:
        pdf:
            enabled:    true
            binary:     xvfb-run wkhtmltopdf
            options:    []
```

But on th server there is no CSS. Have I missed something on my server's config for getting wkhtmltopdf to work properly with CSS.

Images do work on the Linux server though.

**Comment by daudmalik06** [comment]
@jakenoble there are always some problems with wkhtmltopdf for this purpose born new library which uses chrome headless as a back-end try this 
https://github.com/daudmalik06/PhpChromeToPdf

or you can directly use google chrome headless if want to.

**Comment by cordoval** [comment]
your problem is the css url or link is not loaded while building the pdf
you can fix this by just plugging it correctly

**Comment by Tomsgu** [comment]
Closing as there is no response.
