### ISSUE TITLE
wkhtmltopdf can't output vis.js

### ISSUE THREAD

**Issue by LiangJ** [wkhtmltopdf/wkhtmltopdf#3564]
vis.js's timeline can't output when using wkhtmltopdf.

**Timeline Page:**
http://visjs.org/showcase/projects/midas/index.html
![a](https://user-images.githubusercontent.com/2550918/28239175-37206f4e-6998-11e7-9eab-2ee69f7285b2.png)

**Command:**
![c](https://user-images.githubusercontent.com/2550918/28239170-fd4a8b74-6997-11e7-872a-8597caf25d78.png)

**Result:**
![b](https://user-images.githubusercontent.com/2550918/28239184-788cb730-6998-11e7-81ac-9b7c725799c4.png)

**Comment by LiangJ** [comment]
conclusion:

Debug with qtweb browser.
QT haven't support bind method.

Polyfill:
https://cdn.polyfill.io/v2/polyfill.js?features=requestAnimationFrame,Function.prototype.bind&unknown=polyfill

**Comment by jgsogo** [comment]
Hi @LiangJ , did you find a way to use wkhtmltopdf/image with vis.js? I'm trying this polyfill (probably I don't know how to use it) and it doesn't work. Any help would be appreciated, Thanks!
