### ISSUE TITLE
wkhtml not producing the contents inside iframe.

### ISSUE THREAD

**Issue by lijoev** [wkhtmltopdf/wkhtmltopdf#3565]
I am stuck in my production because of the issue noted below
I am using a linux server and i installed wkhtml. i have a url which includes some charts and bar diagrams. In that page bar diagram and one pie chart is built using iframe url in my html. When i try to make pdf using wkhtml the bardiagram and the pie chart which is built using iframe  is not appearing in the pdf all other data is appearing. Please help me i am stuck.

**Comment by Tomsgu** [comment]
Please try to ask on stackoverflow.
