### ISSUE TITLE
support in non latin fonts (Hebrew) in centos 

### ISSUE THREAD

**Issue by ohadperry** [wkhtmltopdf/wkhtmltopdf#3566]
I'm trying to enable export html to pdf in my language (hebrew).
The html and export work fine on my local machine (Mac).

On the remote machine(Centos7)
The html works with the hebrew fonts but the export to pdf outputs this 

<img width="376" alt="screen shot 2017-07-17 at 9 02 35" src="https://user-images.githubusercontent.com/2236337/28256883-05ef0e34-6acf-11e7-9e97-a313241846cc.png">

Tried 
1. 
```
<head>
        <meta name="pdfkit-page-size" content="Legal"/>
        <link rel="stylesheet" href="/static/webapp/plugins/manual/pdf.css">
        <meta charset="UTF-8">
    </head>
``` 

2. Tried: Sudo yum install curl cabextract xorg-x11-font-utils fontconfig
3. Tried: Sudo yum install liberation-sans-fonts
4.  https://gist.github.com/drakakisgeo/7591660 
    1. sudo yum install dejavu-lgc-sans-fonts

none worked. 

the output of locale 
```
[my_user@ip-172-31-34-70 ~]$ locale
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=en_US.UTF-8
```
any suggestions?
@ashkulz ?

**Comment by ohadperry** [comment]
The answer is that the remote server didn't have the right fonts. 


I have also solved this by just copying `Arial.ttf` from my local mac in `/Library/Fonts` 

    scp -i "$STAGING_CERT_PATH" Arial.ttf root@"$STAGING_IP":/usr/share/fonts/local/

to my remote server to `/usr/share/fonts/local` (created the `local` dir myself). 

then `fc-cache -v` to update and it worked

**Comment by khadervali** [comment]
I tried the same but, Even it's not working for me ,
The same steps i followed from above but it's not working for me please help me out from this issue.

**Comment by ohadperry** [comment]
which os is the remote server?

**Comment by khadervali** [comment]
Centos 7

**Comment by ohadperry** [comment]
can you send the output of `ls -ltra /usr/share/fonts/local` in the remote server?

**Comment by khadervali** [comment]
[root@ip-10-0-1-89 ~]# ls -ltrA /usr/share/fonts/local
total 360
-rwxr-xr-x 1 root root 364676 Aug 28 17:06 Arial.ttf

**Comment by ohadperry** [comment]
sorry, no idea for now..

**Comment by NiR-** [comment]
Did you installed following packages on your server: `xorg-x11-server-Xvfb xorg-x11-fonts-Type1 xorg-x11-fonts-75dpi`?
