### ISSUE TITLE
Facing problem with the page break.

### ISSUE THREAD

**Issue by anandhuded2** [wkhtmltopdf/wkhtmltopdf#3571]
Hi,

I am facing problem with the page break using tr and table tags.
using div tag page break not at all working if I make use of tr tag it showing whitespace please resolve this issue . This is my 3rd day on the same issue.

**Comment by NiR-** [comment]
Hello @anandhuded2, 

A trick solving your problem has already been proposed [here](https://github.com/wkhtmltopdf/wkhtmltopdf/issues/3159). It should work. Please use search functionality next time.
