### ISSUE TITLE
Links overlap each other

### ISSUE THREAD

**Issue by biggless** [wkhtmltopdf/wkhtmltopdf#3572]
Version:
```
wkhtmltopdf 0.12.3 (with patched qt)
```
Source:
```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <ul>
      <li>
        <a href="https://google.com/">Link 1</a>
        X X X X X X X X X X X X X X X X X X X X X X X X X X X
        <a href="https://yahoo.com/">Link Link Link Link Link Link Link Link 2</a>
      </li>
    </ul>
  </body>
</html>
```
In this case link 2 is overlapping link 1.
[result.pdf](https://github.com/wkhtmltopdf/wkhtmltopdf/files/1161945/result.pdf)

Is there any way to fix this?

**Comment by GentlemanK** [comment]
Do you mind adding a <br> tag?

![image](https://user-images.githubusercontent.com/27438421/28736027-fe79f37c-73b5-11e7-9e8d-6fdb09839f64.png)

**Comment by spettifer** [comment]
I have experienced this problem also. Inserting a break tag in between the links is not a suitable solution since this is a paragraph of content. Will there not be any kind of fix for it? This only happens when the second link wraps to another line - two complete links on one line works just fine.
