### ISSUE TITLE
Running headless on Linux with 0.12.4

### ISSUE THREAD

**Issue by MicWit** [wkhtmltopdf/wkhtmltopdf#3574]
On your download pages, you have the statement: 

> Please note that the above linux builds are not headless, and will require running under xvfb.

When we installed wkhtmltopdf 0.12.1, we found this to be true, but when we installed 0.12.4, we found we were able to uninstall xvfb and it still worked. I tested this on my Ubuntu install and used the unset display command to make X Server unavailable to wkhtmltopdf and it still worked fine. Down the track I would like to install this to some other servers that I do not have the option of installing xvfb to (cpannel accounts) and so I was wondering if since 0.12.4 this statement is not true (and should be removed from the downloads page) and it can run headless without X Server?

**Comment by NiR-** [comment]
Hello @MicWit,

As of now, this statement is only under "Bleeding Edge" section so I guess 0.12.4 does not require xvfb, and that only apply to 0.13 version ;)
