### ISSUE TITLE
Deceptive site ahead

### ISSUE THREAD

**Issue by timohofmeijer** [wkhtmltopdf/wkhtmltopdf#3575]
The download links for MacOS (at least release 0.12.4 and 0.12.3) throw a big red warning (in Chrome and Safari) containing the following message:
>Attackers on github-production-release-asset-2e65be.s3.amazonaws.com may trick you into doing something dangerous like installing software or revealing your personal information (for example, passwords, phone numbers or credit cards).

**Comment by ashkulz** [comment]
Nothing much I can do about that.
