### ISSUE TITLE
Crash when open with specific margin values

### ISSUE THREAD

**Issue by pkelbern** [wkhtmltopdf/wkhtmltopdf#3576]
I tring to run the wkhtmltopdf and it crashes when I pass -T 30 -B 23 as arguments.
With -B 24, for example, it works perfectly

Using Windows 8.1
command line:

`wkhtmltopdf.exe -T 30 -B 23 -O Landscape --footer-html c:\temp\TempDir\footer.html --header-html c:\temp\TempDir\header.html c:\temp\TempDir\body.html c:\temp\tempdir\out.pdf`

[Relatorios.zip](https://github.com/wkhtmltopdf/wkhtmltopdf/files/1174814/Relatorios.zip)

**Comment by Tomsgu** [comment]
Can you try it in 0.12.5? In linux it works ok.

**Comment by PhilterPaper** [comment]
A few long shots, but is there any difference if you specify explicit units (e.g., 30mm)? I'm not sure if all wkHTMLtoPDF versions support units, or just assume they're mm. Any difference if you move some of the flags and such to later in the command line? If changing "23" to "24" works, that's unlikely. Can you make sure you don't have a file named "23" somewhere (perhaps accidentally created)?

**Comment by pkelbern** [comment]
The error was on 0.12.4
It was fixed on 0.12.5 in Windows also. So I'm closing this issue
