### ISSUE TITLE
Possible to remove margins only on cover page?

### ISSUE THREAD

**Issue by zakiaziz** [wkhtmltopdf/wkhtmltopdf#3579]
I'm making a call something like this:
```
$ wkhtmltopdf --lowquality --margin-bottom '0mm' --margin-left '0mm' --margin-right '0mm' --margin-top '0mm' --orientation 'landscape' --title 'Test.pdf' --footer-html 'footer.html' --header-html 'header.html' cover 'cover.html' 'body.html' 'test.pdf'
```
The command takes out the margins on the cover page but also the margins and the header/footer on the body. Is it possible to remove only the margins on the cover page?

**Comment by ajtis** [comment]
Please check: https://github.com/wkhtmltopdf/wkhtmltopdf/issues/3635
