### ISSUE TITLE
why the height value is not equal with in wkhtmltopdf?

### ISSUE THREAD

**Issue by xiranst** [wkhtmltopdf/wkhtmltopdf#3582]
i try to use wkhtmltopdf to create a pdf file with url. in the firefox, i use javascript to print the height of a div is 112.75px, but when i use `‘/usr/bin/wkhtmltopdf --lowquality http://www.example.com/demo.html demo.pdf’`, but i got the div height value is 480:
`Warning: Javascript alert: 480 `
where is wrong?

**Comment by NiR-** [comment]
Could you provide a little html & css reproducer, and your wkhtmltopdf version please? There could be multiple reasons for your div to be wider.

**Comment by Tomsgu** [comment]
Closing as there is no response since 2017.
