### ISSUE TITLE
Missing fonts

### ISSUE THREAD

**Issue by SevenGuns** [wkhtmltopdf/wkhtmltopdf#3586]
![issues1](https://user-images.githubusercontent.com/23354928/28823426-13f572a2-76f0-11e7-937c-f9cc62269332.jpeg)
![issues2](https://user-images.githubusercontent.com/23354928/28823429-15f7269a-76f0-11e7-9900-3dd64a79afa6.jpeg)

first by wkhtmltopdf, second by chrome, some Chinese fonts missed.

**Comment by PhilterPaper** [comment]
If the bottom picture is Chrome, it looks like Chrome is the one missing a font. Could you clarify what you're seeing, and how you got these lists?

If these are photos of a monitor screen, next time please crop them.

**Comment by 6101234** [comment]
![image](https://user-images.githubusercontent.com/20124747/29109401-707a43f6-7d15-11e7-8540-0616115b9c0d.png)
@PhilterPaper

**Comment by 6101234** [comment]
<!DOCTYPE  >

<html  >
<head >
  
    <style>
    body{
font-family:'Microsoft YaHei'; font-size:24px;
}

    </style>
</head>
<body>
<br />
<br />
<br />
<br />
    微软雅黑 Microsoft YaHei
</body>
</html>

**Comment by PhilterPaper** [comment]
What are we seeing here? The Chinese text appears to be pretty much the same in both, while the Latin text is a serif font in wkHTMLtoPDF and a sans-serif font in Chrome.
