### ISSUE TITLE
ContentOperationNotPermittedError for --footer-html parameter, showing 403 forbidden in pdf

### ISSUE THREAD

**Issue by devacctgmailcom** [wkhtmltopdf/wkhtmltopdf#3590]
I am using this command to generate pdf:
`exec('/PATH/wkhtmltopdf --load-media-error-handling ignore --load-error-handling ignore --viewport-size "1200x1350" --dpi 300 --page-width "175mm" --page-height "205mm" --margin-bottom "10mm" --margin-top "10mm" --header-spacing "3" --footer-spacing "3" --footer-html "https://MYSITE/pdf-page-footer.php" "/PATH/Hdhss - Shhss, Dhdh, Hdhd, MA - Hfhd.html" "/PATH/Hdhss - Shhss, Dhdh, Hdhd, MA - Hfhd.pdf"');`

I am using exact command at two places. One file is in same directory, where html and pdf files are. 
Another file is outside of this dir.

Inside first PHP file, working fine and generating footer html.
But in second php file, showing this error.
In pdf it shows 403 forbidden. And command returns this error:
`Exit with code 1 due to network error: ContentOperationNotPermittedError`

I tried it with these ways:
1. In html, I tried relative paths. Also used absolute paths. I also tried with urls for css/js/image files.
2. In command I tried absolute/relative and urls.

Can you please help to resolve this problem?
Thanks

**Comment by NiR-** [comment]
Did you try to open `https://MYSITE/pdf-page-footer.php` in your browser? Isn't there any 403 error returned by the page itself or one of its img/script/style/...?

**Comment by Tomsgu** [comment]
Closing as there is no response since 2017.
