### ISSUE TITLE
Can't render this HTML into a PDF through wkHTMLtoPDF?

### ISSUE THREAD

**Issue by nicefellow1234** [wkhtmltopdf/wkhtmltopdf#3591]
I am trying to convert the following HTML page into PDF but when the file is rendered so the pdf file is full empty nothing is in there.

Can anyone please confirm to me that why it's not getting rendered into PDF?

**NOTE :**  The HTML has all base 64 images and base base 64 SVG shapes in there along base 64 fonts too. It's just one HTML file and has no external files. Every asset is in there in the HTML file.

What I want to know is that how can I render it, It's Okay I can convert some stuff from base 64 within there  to normal files if that could fix the the issue?

HTML LINK : https://huntedhunter.com/venue_report/latest.html

Regards,

**Comment by Tomsgu** [comment]
The svg problems was discussed many times here. The html link is also not active.
