### ISSUE TITLE
switch to headless chromium rendering

### ISSUE THREAD

**Issue by graingert** [wkhtmltopdf/wkhtmltopdf#3595]
You can now generate a reasonable PDF with chrome/chromium out of the box:

https://developers.google.com/web/updates/2017/04/headless-chrome#create_a_pdf_dom

however there's a few issues like you can't configure page size/orientation or DPI: https://bugs.chromium.org/p/chromium/issues/detail?id=741049

**Comment by Sicos1977** [comment]
I made this for Windows --> https://github.com/Sicos1977/ChromeHtmlToPdf

**Comment by os1r1s110** [comment]
@Sicos1977 Do you support setting custom header/footer as wkhtmltopdf or only enabling/disabling such as available from chrome headless cli tools with the flag?

**Comment by Sicos1977** [comment]
Setting a custom header is not in the tool but can be easily added. In the tool I use the same code that puppeteer uses. So it is similar but I only implemented the part to make PDF's

**Comment by ashkulz** [comment]
Although that's an option many people would find suitable, not sure why it is present in this bugtracker.

**Comment by graingert** [comment]
@ashkulz I mean for this project to change to being a wrapper of headless chromium or a patched version of headless chromium

**Comment by ashkulz** [comment]
Ah ok, that would mean a complete change of browser engine ... effectively meaning a complete rewrite, which is unlikely to happen. I'm planning to base the next release on the [revived QtWebKit port](https://github.com/annulen/webkit).

**Comment by ironman1964** [comment]
Any news on the port to a newer version of QT ?
I have troubles with a page that contains jQuery scripting... the script is not executed !
