### ISSUE TITLE
OpenPrinter failed (Access is denied.) on Win 2008 R2 Standard

### ISSUE THREAD

**Issue by jmzagorski** [wkhtmltopdf/wkhtmltopdf#3597]
wkhtmltopdf on a 64-bit Windows Server 2008 R2 Standard stopped working within a c# application in IIS 6.1 (it had been running successfuly for a few years). I resorted to many different changes when I could not solve the problem such as upgrading the wkhtmltopdf  library from 0.12.1.1 to 0.12.4, restarting the server and changing folder permissions. When the C# and  wkhtmltopdf  directory are moved to a different but identical server, it works as expected. The standard error and the c# code are below. On the server that works I receive the same errors about the `URL has no schema set`, but I do not receive the `Access is Denied`. I imagine that is the root of the problem, but I have not been able to find what is causing that. I can provide the html file, but it is almost 1400 lines with most of the data stripped out. If i can provide any further information that would be great since this has affected a production environment and we have a temporary workaround.

`"Loading pages (1/6)\r\n[> 0%\r[======>] 10%\rQNetworkAccessFileBackendFactory: URL has no schema set, use file:// for files\r\nQNetworkAccessFileBackendFactory: URL has no schema set, use file:// for files\r\nQNetworkAccessFileBackendFactory: URL has no schema set, use file:// for files\r\n[==================>] 30%\r[====================>] 34%\r[======================>] 37%\r[========================>                                   ] 41%\r[=========================>] 43%\rQNetworkAccessFileBackendFactory: URL has no schema set, use file:// for files\r\n[==============================>] 51%\r[=======================================>] 66%\r[============================================================] 100%\rQWin32PrintEngine::initialize: OpenPrinter failed (Access is denied.)\r\nQWin32PrintEngine::initialize: OpenPrinter failed (Access is denied.)\r\nQPainter::begin(): Returned false\r\nError: Unable to write to destination\r\nExit with code 1, due to unknown error.\r\n"`

```
using HtmlAgilityPack;
using RouteCard.Domain.Services;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Text;

namespace Application.Services
{
  /// <summary>
  /// Converts HTML to PDF
  /// </summary>
  public class HtmlToPdfConverter : IPdfConverter
  {
    private const string HtmlToPdfExePath = "wkhtmltopdf.exe";
    private const string ExeDir = @"C:\Program Files\wkhtmltopdf\bin";

    /// <summary>
    /// Performs the conversion
    /// </summary>
    /// <param name="html">the html to convert</param>
    /// <param name="errors">the errors returns during the conversion</param>
    /// <returns>pdf in bytes</returns>
    public byte[] ConvertFromHtml(string html, out IEnumerable<string> errors)
    {
      errors = getAnyErrors(html);

      // set process start info 
      ProcessStartInfo sysPsi = new ProcessStartInfo();
      sysPsi.FileName = Path.Combine(ExeDir, HtmlToPdfExePath);
      sysPsi.WorkingDirectory = Path.GetDirectoryName(sysPsi.FileName);

      // run the conversion utility
      sysPsi.UseShellExecute = false;
      sysPsi.CreateNoWindow = true;
      sysPsi.RedirectStandardInput = true;
      sysPsi.RedirectStandardOutput = true;
      sysPsi.RedirectStandardError = true;

      StringBuilder args = new StringBuilder();
      // disable javascript
      args.Append("-n ");
      args.Append("-L 1mm -R 1mm -T 10mm -B 10mm");
      args.Append("--disable-smart-shrinking ");
      args.Append("--orientation Portrait ");
      args.Append("--outline-depth 0 ");
      args.Append("--page-size A4 ");
      // this tells wkhtmltopdf to use stdin and stdout
      args.Append(" - -");

      sysPsi.Arguments = args.ToString();

      // start the process
      Process sysProcess = Process.Start(sysPsi);

      try
      {
        // being to write to the memory stream 
        byte[] file;
        using (var ms = new MemoryStream())
        {
          using (StreamWriter stdin = sysProcess.StandardInput)
          {
            stdin.AutoFlush = true;
            stdin.Write(html);
          }

          sysProcess.StandardOutput.BaseStream.CopyTo(ms);
          errors = errors.Concat(new[] { sysProcess.StandardError.ReadToEnd() });
          file = ms.ToArray();
        }

        sysProcess.WaitForExit();
        sysProcess.StandardOutput.Close();
        sysProcess.StandardError.Close();

        // read the exit code, close process
        int returnCode = sysProcess.ExitCode;

        return file;

      }
      finally
      {
        sysProcess.Close();
        sysProcess.Dispose();
      }
    }

    private IEnumerable<string> getAnyErrors(string html)
    {
      HtmlDocument doc = new HtmlDocument();
      doc.LoadHtml(html);

      return doc.ParseErrors.Select(err => err.Reason);
    }
  }
}
```

**Comment by bitbonk** [comment]
We have the same problem. Any workaround?

**Comment by jmzagorski** [comment]
Unfortunately not. I had to redirect traffic for that application to our backup server where the program was working. We might have to find an alternative application since it is hard to debug the issue.

**Comment by bitbonk** [comment]
This is how I resolved the issue: https://github.com/dotnet/docfx/issues/1974#issuecomment-323366874

**Comment by ashkulz** [comment]
Please reopen if the workaround doesn't work, also try [this suggestion](https://github.com/wkhtmltopdf/wkhtmltopdf/issues/2782#issuecomment-377704398)

**Comment by jmzagorski** [comment]
@ashkulz 👍 your suggestion worked...thanks
