### ISSUE TITLE
Error: /bin/bash: wkhtmltopdf: command not found

### ISSUE THREAD

**Issue by salimakhtar786** [wkhtmltopdf/wkhtmltopdf#3602]
I installed wkhtmltopdf from the following commands:

    sudo apt-get update
    sudo apt-get install xvfb libfontconfig wkhtmltopdf
   

Following version installed successfully 
`
wkhtmltopdf 0.12.2.4
`

When I am creating PDF the following error showing in mup logs

    Error: /bin/bash: wkhtmltopdf: command not found

How to fix it?

**Comment by mati75** [comment]
Check first where you have installed wkhtmltopdf:
`whereis wkhtmltopdf`

**Comment by megamindbrian** [comment]
Then use xvfb-run wkhtmltopdf http://www.google.com google.pdf

That creates a new virtual frame buffer for rendering wkhtmlto*.  If you are on a headless server, you will have a lot of dependencies when installing xvfb, such as x11 and fonts.  If you already have a desktop, you can add :1 or :99 to whichever screen you are running your terminal and that will render using the existing session. e.g. ```DISPLAY=:1 wkhtmltopdf http://www.google.com google.pdf``` or ```wkhtmltopdf http://www.google.com google.pdf  --use-xserver```

https://stackoverflow.com/questions/20653202/wkhtmltopdf-use-xserver-option

**Comment by salimakhtar786** [comment]
I used the ` which wkhtmltopdf ` command and got the following:
```
/usr/local/bin/wkhtmltopdf
```
And I also checked the $PATH variable using `echo $PATH`  its giving the following output:
```
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
```


I run the following command 

```
wkhtmltopdf http://www.google.com google.pdf
```
Its working  and giving following output
```
Loading pages (1/6)
Counting pages (2/6)                                               
Resolving links (4/6)                                                       
Loading headers and footers (5/6)                                           
Printing pages (6/6)
Done      
```

**Comment by salimakhtar786** [comment]
After a long time facing this issue I decided to replace it by another converter.

I removed `wkhtmltopdf` and I installed [html-pdf][1] converter and then my problem has been solved. 

Thanks!

  [1]: https://github.com/marcbachmann/node-html-pdf
