### ISSUE TITLE
wkhtmltoimage outputs black picture for height > 30000 pixels

### ISSUE THREAD

**Issue by onriv** [wkhtmltopdf/wkhtmltopdf#3604]
as title. when using wkhtmltoimage convert a very long html page, it would contains some black block in the end.

![image](https://user-images.githubusercontent.com/1629055/29445020-a89384c0-8416-11e7-8163-b90d09bfcbcd.png)

the raw jpg picture size is 480 * 33331, it seems that problems happened when height > 30000 pixels

**Comment by alloylab** [comment]
What version? have you tried this on 0.12.5?

**Comment by alloylab** [comment]
We are closing this out since we haven't heard from you. If you are still having this issue please feel free to re-open it. Thanks.
