### ISSUE TITLE
How to change footer by page

### ISSUE THREAD

**Issue by nileshgpit** [wkhtmltopdf/wkhtmltopdf#3605]
wkhtmltopdf with snappy getting some issue. create html to pdf with 1000 participant in loop while looping 
 i want to different footer with some dynamic text per  employee . i am trying to many time but not possible form my site please help.

**Comment by Tomsgu** [comment]
Please read https://github.com/wkhtmltopdf/wkhtmltopdf/issues/2436#issuecomment-117197312.
