### ISSUE TITLE
Font not support convert html to pdf

### ISSUE THREAD

**Issue by nileshgpit** [wkhtmltopdf/wkhtmltopdf#3606]
using wkhtmltopdf with snappy  all font not supported like Japaneses, Marathi, Hindi etc.... 

i am also try to Unicode(UTF-8) wkhtmltopdf option but not working. please help.

**Comment by NiR-** [comment]
You provide too few elements to help you. Could you tell us which OS you use, which font package is installed and provide a minimal html file showing your problem please?

**Comment by nileshgpit** [comment]
I am using Linux OS, i am using default fond package Linux, also install Japaneses, Marathi, Hindi .ttf font on server.

**Comment by Tomsgu** [comment]
Closing as the issue misses important details and the author is not responding.
