### ISSUE TITLE
wkhtmltopdf shrinks original html when creating pdf

### ISSUE THREAD

**Issue by suvalkon** [wkhtmltopdf/wkhtmltopdf#3607]
I have tried everything with --disable-smart-shrinking, zoom factors, dpi to preserve the original html which prints nicely in an A4 size but is shrunk by a considerable factor when converting it.

The --disable-smart-shrinking actual expands the output so that it chops off the right part of the output.
After all the reading with similar problems I can't seem to get it to preserve the HTML settings that are present in the HTML file with CSS. The fonts used are Helvetica with different px settings and line heights.
The output looks good but shrunk by almost a third.

Version is 0.12.4 (with patched qt) running on windows 2012 Server R2.
I am using a python script with pdfkit but this does not seem to be able to pass the 'disable-smart-shrinking' as it crashes in pdfkit. I tested this by running 'wkhtmltopdf' directly from DOS.
Can anyone point me in the right direction to preserve the 1:1 ratio between html and Pdf.

**Comment by bhgames** [comment]
I'm having the same issue after upgrading to Mac OSX Sierra. Thank God my Heroku staging and AWS Beanstalk production still use the older version. I also can't get it to print a PDF 90% of the time - just hangs on OSX Sierra now.

**Comment by suvalkon** [comment]
The only thing I can do to get it close is apply the following options ...
config = pdfkit.configuration(wkhtmltopdf="D:\\Program Files\\wkhtmltopdf\\bin\\wkhtmltopdf.exe")
options = {
    'encoding': "UTF-8",
	'print-media-type': '',
	'page-size': 'A4',
	'margin-top': '5mm',
	'margin-bottom': '5mm',
	'margin-left': '5mm',
	'margin-right': '5mm',
	'zoom': '1.25'
}
This gets it pretty close with a bit of fiddling in the HTML.
The other thing one might do is make the HTML page larger than normal and leave the shrinking process to happen normally. So all the widths for elements expand to larger than what is normal and then put that HTML though wkhtmltopdf - this does work but is painful.
It would be nice if someone can solve this in a more elegant way?
