### ISSUE TITLE
PDF is not created correctly

### ISSUE THREAD

**Issue by nan008** [wkhtmltopdf/wkhtmltopdf#3608]
Snorby 2.6.3
OS: Cenots 7
Wkhtmltopdf 0.12.4 (with patched qt)

I am using wkhtmltopdf with Snorby 2.6.3 dashboard to pdf.

The pdf file is created but it is not readable as the words are blocks.

 There is no error in Snorby log. I tried wkhtmltopdf on its own with google page as well with the same result which I attached below

The package I am using

wkhtmltox-0.12.4_linux-generic-amd64.tar 11.37.16.xz

Command I am running:

$wkhtmltox/bin/wkhtmltopdf www.google.com /tmp/g2.pdf

![screen shot 2017-08-18 at 10 14 45](https://user-images.githubusercontent.com/18073067/29452443-4fb03906-83fe-11e7-833e-e03848c7595e.png)

Any help with this would be greatly welcomed

**Comment by NiR-** [comment]
Hello @nan008, looks like you miss some fonts. Have you installed following packages: `xorg-x11-fonts-Type1` and `xorg-x11-fonts-75dpi`?

**Comment by nan008** [comment]
Thnks so much @NiR- The packages I installed were not working for some reason so I installed other versions and now they are working perfectly
