### ISSUE TITLE
May I use it in CentOS 4.3?

### ISSUE THREAD

**Issue by DrJian** [wkhtmltopdf/wkhtmltopdf#3610]
Hi,
    If I wang to use Wkhtmltopdf in CentOS 4.3, Is is posiible for me ?use the wkhtmltopdf CentOS 5 release version. I'd like to receive your message, thx u so much

**Comment by NiR-** [comment]
I would say that's not possible because CentOS 4.3 is **really old**. You can try to compile wkhtml (and other libs) by yourself, but IMHO it would be really hard if not impossible. And I would bet you won't receive any support for this version.

**Comment by DrJian** [comment]
got it, thx for your reply!
