### ISSUE TITLE
wkhtmltoimage output text rendering chopped and low quality

### ISSUE THREAD

**Issue by rsiddle** [wkhtmltopdf/wkhtmltopdf#3611]
Here is a manual screenshot of the webpage. It shows the font with curves on the top of the letters 's', 'e', 'o', 'r'.

<img width="275" alt="screen shot 2017-08-21 at 14 21 16" src="https://user-images.githubusercontent.com/18415/29521247-984be93c-867c-11e7-9ab9-b036eb79235d.png">

```wkhtmltoimage --quality 100 http://localhost:3000/api/banner?id=12 test-12.png```

The output shows the top of the letters have been 'chopped' and the quality is heavily reduced, even with the `quality` set to 100.

<img width="214" alt="screen shot 2017-08-21 at 14 21 46" src="https://user-images.githubusercontent.com/18415/29521248-98630630-867c-11e7-924d-a367668ad9b0.png">

I'm not sure if this is related. However, trying to export to gif causes an error too:

```
wkhtmltoimage --quality 100 http://localhost:3000/api/banner?id=12 test-12.gif
Loading page (1/2)
Rendering (2/2)                                                    
Error: Could not save image                                       
Done                                                               
Exit with code 1, due to unknown error.
```

**Comment by NiR-** [comment]
Hello @rsiddle,

Did you search for similar issues? There's plenty of people complaining about same/similar issues. IIRC, some people suggested to use a `--zoom-factor` of 1.3.

Also what's your OS/linux distro?

**Comment by allenmackley** [comment]
Same issue.
