### ISSUE TITLE
getting hang for more than 5 pages pdf generation 

### ISSUE THREAD

**Issue by malakondareddy001** [wkhtmltopdf/wkhtmltopdf#3612]
i am using it in asp.net, to generate html to pdf but its working fine upto 5 page of pdf generation more than 5 pages it getting hang, please do the needful on urgent basis.
below is the text file and code:

[html0557.txt](https://github.com/wkhtmltopdf/wkhtmltopdf/files/1240979/html0557.txt)

//Determine inputs
                    if ((urls == null) || (urls.Length == 0))
                        throw new Exception("No input URLs provided for HtmlToPdf");
                    else
                        urlsSeparatedBySpaces = urls; //Concatenate URLs

                    string outputFolder = pdfOutputLocation;
                    string outputFilename = outputFilenamePrefix + "_" + DateTime.Now.ToString("yyyy_MM_dd_hh_mm_ss_fff") + ".PDF"; // assemble destination PDF file name

                    var p = new System.Diagnostics.Process()
                    {
                        StartInfo =
                    {
                        FileName = pdfHtmlToPdfExePath,
                        Arguments = ((options == null) ? "" : String.Join(" ", options)) + " " + urlsSeparatedBySpaces + " " + outputFilename,
                        UseShellExecute = false, // needs to be false in order to redirect output
                        RedirectStandardOutput = true,
                        RedirectStandardError = true,
                        RedirectStandardInput = true, // redirect all 3, as it should be all 3 or none
                        WorkingDirectory =outputFolder // HttpContext.Current.Server.MapPath(outputFolder)                        
            }
                    };

                    p.Start();

                    // read the output here...
                    var output = p.StandardOutput.ReadToEnd();
                    var errorOutput = p.StandardError.ReadToEnd();

                    // ...then wait n milliseconds for exit (as after exit, it can't read the output)
                    p.WaitForExit(60000);

                    // read the exit code, close process
                    int returnCode = p.ExitCode;
                    p.Close();

                    // if 0 or 2, it worked so return path of pdf
                    if ((returnCode == 0) || (returnCode == 2))
                        return outputFilename;
                    else
                        throw new Exception(errorOutput);

**Comment by alloylab** [comment]
is this still an issue on 0.12.5?

**Comment by alloylab** [comment]
We are closing this out since we haven't heard from you. If you are still having this issue please feel free to re-open it. Thanks.
