### ISSUE TITLE
PDF generation fails silently based on markup

### ISSUE THREAD

**Issue by mauu-alpha** [wkhtmltopdf/wkhtmltopdf#3617]
Im trying to convert this [file](https://drive.google.com/file/d/0B-y-icBC-InzNWJJN1o4Y05GdEk/view?usp=sharing) into pdf, but the process stops suddenly and the file generated is not valid.

This is how i run the command
```
wkhtmltopdf --page-size "Letter"  --encoding "UTF-8"  --margin-top "20" --margin-right "10" --margin-left "10" --margin-bottom "20"  ~/Desktop/TEST.htm ~/Desktop/TEST.pdf
```

This is the output
```
Loading pages (1/6)
Warning: SSL error ignored
Counting pages (2/6)
```

Im on `OSX Sierra`
```
wkhtmltopdf --version
wkhtmltopdf 0.12.3 (with patched qt)
```

If i dont pass the `--margin-bottom "20"` option, it works....

**Comment by Tomsgu** [comment]
Is it working in 0.12.5? If not please provide a **MINIMAL** example.

**Comment by mauu-alpha** [comment]
@Tomsgu i haven't tested with that version, but there is a link in my post, have you seen it ?
https://drive.google.com/file/d/0B-y-icBC-InzNWJJN1o4Y05GdEk/view

**Comment by Tomsgu** [comment]
Yeah I saw it @mauu-alpha. That's why I ask about a minimal example. Minimal means around 50 lines. Nobody is going to find something in such a long file.

**Comment by mauu-alpha** [comment]
Well sorry, thats the (not) working example that i have, i would love to help more but im not working in that project anymore. The need info tag seems misleading tho, thanks anyway.

**Comment by Tomsgu** [comment]
Yeah you're right it was misleading. I am closing the issue because it's not possible to find exact source of problem in such a huge file. Please feel free to re-open it if you will have more information or experience the same problem.
