### ISSUE TITLE
Negative sign "-" become square used in odoo 10 community, version 0.12.4

### ISSUE THREAD

**Issue by bunhin** [wkhtmltopdf/wkhtmltopdf#3623]
Hi,
I am using version 0.12.4 for odoo 10 report  in linux CentOs 7.3  (wkhtmltox-0.12.4_linux-generic-amd64.tar.xz),  but i found a little error that is the  negatif sign before number  such as in  "- 5000", it render to a smal square.

Please help how to solve it or what to check to make the negatif sign print as  -  not as sqaure  ?

Thanks,

**Comment by NiR-** [comment]
DId you installed following packages on your server: `xorg-x11-server-Xvfb xorg-x11-fonts-Type1 xorg-x11-fonts-75dpi`?

**Comment by bunhin** [comment]
Yes the packages above already installed.
Until now i still have this problem.  please help

**Comment by NiR-** [comment]
Strange... I just tried with following html snippet on CentOS 7.3 with same wkhtmltox version and I'm not able to reproduce the issue. Could you try it on your computer/server please?

```html
<html>
<head><meta charset="utf-8"></head>
<body><p>-5000</p></body>
</html>
```

And here is the list of font packages I've:
```
yum list installed | grep font
fontconfig.x86_64                        2.10.95-10.el7                 @base   
fontpackages-filesystem.noarch           1.44-8.el7                     @base   
libXfont.x86_64                          1.5.1-2.el7                    @base   
libfontenc.x86_64                        1.1.2-3.el7                    @base   
xorg-x11-font-utils.x86_64               1:7.5-20.el7                   @base   
xorg-x11-fonts-75dpi.noarch              7.5-9.el7                      @base   
xorg-x11-fonts-Type1.noarch              7.5-9.el7                      @base   
```

**Comment by bunhin** [comment]
Hi  NIR, 

Please info, what i have to do (what command to enter) to try with your script?

Here is my result for the list command for the installed font:

[root@OpenErp10 ~]# yum list installed | grep font
fontconfig.x86_64                       2.10.95-10.el7                 @base
fontconfig-devel.x86_64                 2.10.95-10.el7                 @base
fontpackages-filesystem.noarch          1.44-8.el7                     @base
ghostscript-fonts.noarch                5.50-32.el7                    @base
libXfont.x86_64                         1.5.1-2.el7                    @base
libfontenc.x86_64                       1.1.2-3.el7                    @base
msttcore-fonts-installer.noarch         2.6-1                          installed
xorg-x11-font-utils.x86_64              1:7.5-20.el7                   @base
xorg-x11-fonts-75dpi.noarch             7.5-9.el7                      @base
xorg-x11-fonts-Type1.noarch             7.5-9.el7                      @base

Please tell if there is problem with.

Thanks,

**Comment by NiR-** [comment]
I generated a PDF from the HTML code above with this command: `xvfb-run -a -s "-screen 0 1024x768x24" wkhtmltopdf /tmp/out/3623.html /tmp/out/3623.pdf`.

**Comment by bunhin** [comment]
I run in the root shell,  then open the pdf after download it,  yes it works  show  -5000

**Comment by bunhin** [comment]
So what is causing my problem here?

**Comment by PhilterPaper** [comment]
Is that an ASCII hyphen (x2D), or one of the Unicode special hyphens (U+2010, U+2011, U+2012) that perhaps your font doesn't cover? A soft (discretionary) hyphen (xAD) should be in almost all fonts. If it's one of the special hyphens, you may need to change fonts or edit the source to use a hyphen that your font has a glyph for.

**Comment by bunhin** [comment]
i have no idea, but the input is using normal keyboard of dash  (-)

**Comment by PhilterPaper** [comment]
Was that keyboard "-" used directly in the HTML you are converting, or did it go through some processing and converting that might have used one of the other hyphen characters? For example, you typed in a negative number (using the keyboard hyphen), which was then processed in some way and printed back out, this time using U+201x hyphen? Try looking at the page in a browser, and then in the browser turn Unicode (UTF-8) off (to Latin-1, etc.) if it's on, and see if the hyphen changes to a sequence of two or three characters. If it does, your hyphen got changed to a U+201x special hyphen that your font apparently doesn't support.

**Comment by bunhin** [comment]
Actually the document is generated from Odoo 10 community, (any report),  The odoo server itself running on CentOs 7.3,  i have try to use wkhtmlpdf version from 0.12.1, 0.12.2, 0.12.2.1, 0.12.3, and 0.12.4, all have same problem.

Last try i remove wkhtmltopdf from system, and see the html report is showing "-", and odoo said that wkhtmltopdf can't be foung.   Then i install again the wkhtmltopdf, and the "square" back again.  Then I remove msttcore fonts package from the system,  "the square" was not showing up but the "-" sign also not show up. (this is also not correct).  Then I re-install the msttcore fonts package,  but both the "square" and the negatif (-) did not show up.

if it is about fonts required is not installed, how do i know it? how to check?  and how do i know the right required font?   I have checked by hit Ctrl-D  in the pdf,  and go to the font tab,  but there is no information about missing fonts or something related, only show the fonts is used to render the documents.

Please share further step to solve.

**Comment by PhilterPaper** [comment]
I can't help you if you do everything _but_ answer the question I asked, and that is "is this '-' symbol the keyboard hyphen or is it one of the Unicode special hyphens?". Display the HTML page in your browser. Ask the browser what encoding it is displaying the page in. I suspect it will be UTF-8. If it is, change the encoding to Latin-1/CP-1252/Windows-1252/Western European and see if the hyphen turns into a sequence of 2 or 3 odd characters. If it does, that proves that it's using a Unicode special hyphen (U+201x) and the font that wkHTMLtoPDF is using doesn't have this character in it. Once we know what is going on, we can try to figure out a fix.

**Comment by bunhin** [comment]
Thank you PhilterPaper,
I will follow your trouble shooting guide, i very appreciate your help.
For your above guide here is what i do and get to feedback here:

1. I use mozilla firefox as browser
2. In the content section, go to fonts and color, i click the advance button and got the pop up that say:
3. Fonts for:  Latin
4. Propotional : Serif   Size: 16
5. Seri: Default (Times New Roman)
6. Sans-serif: Default (Arial)
7. Monospace: Default (Courier New)

I check for :  Allow pages to choose their own fonts, instead of your selections above
Text Encoding for legacy content
This text encoding is used for legacy content that fails to declare its encoding.
Fallback Text Encoding: Default for current local

The display shows  2 like rectangle box before the number
if i uncheck the "Allow pages to choose their own fonts, instead of your selections above" the result (after refreshing the page):
1. the odd square boxes is gone  but the negatif sign "-" do not show up.

I can not find selection option of UTF-8 for the field   "Text for:"

Please guide for further step. Thank you

**Comment by PhilterPaper** [comment]
This has nothing to do with selecting _fonts_. We're interested in the _encoding_.

Go to the page showing the negative sign (hyphen). Depending on your version of Firefox, you may need to press F10 to bring up a menu bar in the upper left. Select the **View** menu, and on that menu **Text Encoding**. Is "Unicode" preselected? If it is, your page is showing in UTF-8. Select some single byte encoding such as **Western** and see if that hyphen changes into 2 or 3 odd characters.

**Comment by bunhin** [comment]
I tried to correctly interpret "the page" that you mean, I did the followings, hope to get correctly "the page" you want to see.

I open the pdf page generated by odoo10 and wkhtmltopdf in mozilla firefox where the negatif sign is rendered into odds character (like 2 rectangles or squares), then go to view (in firefox menu) and find out that the text encoding link in the menu list  was greyed (can not be clicked / in active)

I open test.pdf page generated from converting the html script through command line above (where the negatif sign is showed correctly), go to firefox menu -- view  and find out the "text encoding" link also greyed (inactive)

I create an excel sheet,  create a simple subtraction 2 numbers in 2 different cell so the result become negatif,  also create an addition of 2 numbers where the result also negatif, and just direct input in a cell a negatif number (hypen followed by a number). Then save it in web page format, and in pdf format. I open the page with web format in firefox, go to view menu and find out the "text encoding" menu link is active, select it and find the "Western" is pre selected, all negatif signs show good, change to unicode  also all show ok.  Then I open the page saved with pdf format, negatif sign show ok, but in view menu the text encoding link also in active.

Then i go to odoo form page (html) that have negative number with negatif sign,  go to view menu and the text encoding menu item is active, select it and find out the unicode is preselected, change into "western" then the page become all blank

 Please guide me further step if it is not correctly get the page that you mean. Thank you.

**Comment by PhilterPaper** [comment]
You finally looked at the **HTML** page in the browser, one with the "negative" sign (-) in question, and were able to get to the Encoding menu selection. You changed it from Unicode (UTF-8) to "Western" (or Latin-1 or Windows-1252) and the whole page disappears? Changing it back to Unicode makes the page visible again? That is very strange. If the page is HTML, there ought to be _something_ displayed, even when in the wrong encoding. Were you looking at the **PDF** in the browser, or the **HTML** file?

Is it possible to produce a very small HTML file (and PDF from wkHTMLtoPDF) which show the negative number (and its different displays) and attach them here?

Are you producing the PDF directly from Odoo (and the spreadsheet), or are you converting the HTML (web page) to PDF via wkHTMLtoPDF? I'm confused by your description. If you can produce the PDF directly from Odoo, is that using wkHTMLtoPDF internally? What happens if you manually run wkHTMLtoPDF to convert the HTML into PDF... does it work correctly then?

**Comment by bunhin** [comment]
The report is generated from Odoo and odoo use wkhtmltopdf to convert it become pdf

**Comment by PhilterPaper** [comment]
1. What happens if you take the HTML web page and manually try to run wkHTMLtoPDF to convert it? Perhaps Odoo has an incorrectly-set switch. Can you get the command-line that Odoo is using?

2. Is the HTML web page using UTF-8 encoding, and if so, are these failing "negative" signs U+2010, U+2011, or U+2012 characters? That would be my guess as to what's happening, in that the font being used for PDF does not include this character, although the browser font _does_ include it.

If you can not answer these questions, which I have asked repeatedly, then I can not help any further with this.

**Comment by bunhin** [comment]
The issue is finally solved, after try to install many fonts,  the dejavu-sans-fonts  finally work.  Thanks for all help
