### ISSUE TITLE
Error on shared server

### ISSUE THREAD

**Issue by federicoprimomo** [wkhtmltopdf/wkhtmltopdf#3625]
Hi, at local tests the library works great, but when I put in a shared server, I get this problem.

```
Exception Details: Codaxy.WkHtmlToPdf.PdfConvertException: Html to PDF conversion of 'http://...' failed. Wkhtmltopdf output:
An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.
```
I tried with a simpler "hello world" html, and I get the same error.

I also tried creating a proccess calling the exe, and I get this error "-1073741790"

Any idea? Thanks.

**Comment by hakimio** [comment]
On a shared hosting most likely you are not allowed to execute arbitrary executables.

**Comment by Tomsgu** [comment]
Closing as there is no response from the author since September.
