### ISSUE TITLE
Large file causes QEventDispatcherWin32 error

### ISSUE THREAD

**Issue by slimjim96** [wkhtmltopdf/wkhtmltopdf#3626]
Windows (MinGW) | 0.12.4 - 64 Bit
Windows 2008 R2 Service Pack 1

I have a large file HTML file (76 MB) that gets to about 94% and then spits out the following message with around 1.4 GB memory in the process.

**QEventDispatcherWin32::registerTimer: Failed to create a timer (The current proc
ess has used all of its system allowance of handles for Window Manager objects.)**

I have tested the 'alpha' and it works but I need the html header option. Is there an ETA for the new one or any workaround?

Thanks so much for your tool and your help.

**Comment by NiR-** [comment]
Hello @slimjim96, 

Usually we ask a reproducer so we can test it on our own computer. But given the size of the html used to feed wkhtmltopdf, I guess that's not necessary...

IMHO what you're trying to do is not doable. You can't expect any browser engine to load that crazy amount of chars, let alone DOM nodes... You should try to open your HTML file in you favorite browser and see how many times it will take to render (if it doesn't even crashes), and how much memory it'll use. Thus, I think what you describe isn't related to wkhtmltopdf but rather to QtWebKit: it's not able to load an HTML of that size.

Just for "fun", I generated an HTML file with 76 millions of chars with following command:

```bash
TMPFILE=/tmp/test.html
echo -e '<!DOCTYPE html>\n<html><head><meta charset="utf-8"></head><body>' > $TMPFILE; perl -e 'print "Lorem ipsum dolor sit amet<br />"x2375000' >> $TMPFILE; echo '</body></html>' >> $TMPFILE
```

Here's the memory usage of Chromium, and the whole page wasn't even fully loaded:
![image](https://user-images.githubusercontent.com/557933/30094686-fbd83836-92cd-11e7-8525-d23b47ffaf89.png)

So, I think you have three ways to handle this:
* Use another html-based PDF generator that support such a crazy size for an HTML file, but I don't think you'd find one.
* Use a PDF generator, not "html-based".
* Split your HTML file into smaller chunks that wkhtml would be able to process.

**Comment by slimjim96** [comment]
Thanks so much for taking the time and running the tests. I will look for other options until the alpha release is completed. It did work in the bleeding edge but doesn't have the header feature enabled yet.
