### ISSUE TITLE
Converting page with relative links from stdin

### ISSUE THREAD

**Issue by bangnab** [wkhtmltopdf/wkhtmltopdf#3627]
I've successfully converted local html pages with relative links by invoking
`wkhtmltopdf page.html out.pdf`
However if I instead do:
`cat page.html | wkhtmltopdf - out.pdf`
then i get `"Warning: Failed to load file:///tmp/style.css (ignore)"`, because it's using `/tmp` as the current directory and of course the output pdf is not correct.

I haven't found any way to set the current directory and make this work. Did I miss something? If not could you add such an option?

**Comment by NiR-** [comment]
If you want to generate PDFs that way you should use absolute path rather than relative ones.

**Comment by bangnab** [comment]
I've solve my problem by adding a <base> tag at the very beginning of the html file. This is easy to do dynamically.

However I still think that it would be a useful feature to be able to specify what the working directory is, espceially when converting directly from stdin.

**Comment by NiR-** [comment]
How did you solved your problem? Using `<base></base>`?

**Comment by bangnab** [comment]
Yes. Sorry that got lost in my previous comment ;-)

**Comment by Tomsgu** [comment]
Closing as it is solved.
