### ISSUE TITLE
Nice to have: pdf security settings

### ISSUE THREAD

**Issue by Asugusto** [wkhtmltopdf/wkhtmltopdf#3630]
Hi,

I'm using wkhtmltopdf and it's awesome, but i think that is missing some of this configuration:

- Author
- CreationDate
- UserPassword
- OwnerPassword
- PermitAccessibilityExtractContent                
- PermitAnnotations
- PermitAssembleDocument
- PermitExtractContent
- PermitFormsFill
- PermitFullQualityPrint
- PermitModifyDocument
- PermitPrint

Those are just examples taken from: [PdfSharp](http://www.pdfsharp.com/PDFsharp/index.php?option=com_content&task=view&id=36&Itemid=47)

So, i'm generating the pdf with wkhtmltopdf, then read the output with PDFSharp and save the document with my own settings, will be great that this was native from wkhtmltopdf.

Regards!

**Comment by ashkulz** [comment]
This is best done by a post-processing tool run after wkhtmltopdf, as it would require changes in the Qt PDF generation library.
