### ISSUE TITLE
Windows authentication (ntlm)

### ISSUE THREAD

**Issue by cutter1703** [wkhtmltopdf/wkhtmltopdf#3638]
Hello,
how can i set up to use windows authentication?
If i pass a username and password i still get 401 1 in the IIS logs.

wkhtmltopdf.exe --username "DOMAIN\LOGIN" --password "PASSWORD" "URL" "OUTPUT.PDF"

Any help would be appreciated.

**Comment by ashkulz** [comment]
It's unlikely to be supported, better allow password authentication for a hardcoded user instead and use that.
