### ISSUE TITLE
Possibility to embed fonts

### ISSUE THREAD

**Issue by nielvrom** [wkhtmltopdf/wkhtmltopdf#3639]
have a question about generating PDFs with wkhtmltopdf. I know it's possible to use custom fonts in my html. But I think it's required that the operating system viewing the pdf has installed these fonts. Correct?

My question is whether it's possible to include these fonts in the PDF? So when the PDF is generated I can send it to a print office to print 50 copies. And they see the pdf exactly the same as I, without having these fonts installed.

**Comment by ashkulz** [comment]
They are embedded by default.
