### ISSUE TITLE
segmentation fault on particular documents

### ISSUE THREAD

**Issue by vladimir9876** [wkhtmltopdf/wkhtmltopdf#3641]
Hi,

we are having segfaults on some specific documents. We tried both 0.12.1 and 0.12.4, no difference.
I've compiled it with '--debug' option, so I can provide gdb 'bt' lines, if required.

Kind regards,
Vladimir

**Comment by golnazgh** [comment]
Hi,
Is it possible that you post these documents so I can reproduce the segmentation faults?

**Comment by Tomsgu** [comment]
Closing as there is no feedback and no information that helps to reproduce the issue.
