### ISSUE TITLE
Encoding option does not work

### ISSUE THREAD

**Issue by Gigex** [wkhtmltopdf/wkhtmltopdf#3646]
I have been trying to use wkhtmltopdf to convert a custom html page (with hebrew) into pdf.
My hebrew always comes out as black blocks so as a test (just to make sure my html wasn't the problem) i ran the program on the https://www.google.co.il/ which contains some hebrew in it and i got the same result (screenshot of result: https://prnt.sc/gjqav7).
Server information: Linux 4.8.6-x86_64-linode78 (CENTOS 6.9)
wkhtmltopdf version: 0.12.4 64-bit
I tried: "./wkhtmltopdf https://www.google.co.il google.pdf", 
"./wkhtmltopdf --encoding utf-8 https://www.google.co.il google.pdf", 
"./wkhtmltopdf --encoding UTF-8 https://www.google.co.il google.pdf",
"./wkhtmltopdf --encoding he_IL.utf8 https://www.google.co.il google.pdf"

All with the same result.

**Comment by NiR-** [comment]
I've already seen this sort of issue with CentOS and it's not due to buggy `--encoding` option but rather to missing fonts.

I tested https://www.google.co.il with CentOS 7 and I had no font issue. Here're the packages I installed: `yum install -y dejavu-sans-fonts urw-fonts xorg-x11-fonts-Type1 xorg-x11-fonts-75dpi`. And here's the complete list of font packages I've got:

```
# yum list installed | grep font
dejavu-fonts-common.noarch               2.33-6.el7                     @base   
dejavu-sans-fonts.noarch                 2.33-6.el7                     @base   
fontconfig.x86_64                        2.10.95-11.el7                 @base   
fontpackages-filesystem.noarch           1.44-8.el7                     @base   
libXfont.x86_64                          1.5.2-1.el7                    @base   
libXfont2.x86_64                         2.0.1-2.el7                    @base   
libfontenc.x86_64                        1.1.3-3.el7                    @base   
urw-fonts.noarch                         2.4-16.el7                     @base   
xorg-x11-font-utils.x86_64               1:7.5-20.el7                   @base   
xorg-x11-fonts-75dpi.noarch              7.5-9.el7                      @base   
xorg-x11-fonts-Type1.noarch              7.5-9.el7                      @base   
```

**Comment by alloylab** [comment]
have you tried this on 0.12.5?

**Comment by Gigex** [comment]
I'm sorry, i don't really remember what this is about, but i guess i
managed since this was a while ago. Thank you for the help anyway!
