### ISSUE TITLE
Are there any reasons to prefer wkhtmltopdf over puppeteer?

### ISSUE THREAD

**Issue by mamiu** [wkhtmltopdf/wkhtmltopdf#3650]
Like the title says: Are there any reasons to prefer wkhtmltopdf over puppeteer nowadays?

**Comment by arafatx** [comment]
Yes. If u use odoo. Depends on what application you use.

**Comment by tystol** [comment]
Is it possible to do content rich page headers/footers, including page numbers, using puppeteer? Last time I checked it wasn't.

**Comment by powerpete** [comment]
I made some simple tests fetching a website with about 30 pages. wkhtmltopdf takes about 60% of the time puppeteer takes.

**Comment by mamiu** [comment]
@powerpete wow, thanks! this is a clear difference.

@arafatx I highly use odoo, that's why I asked. :wink:

**Comment by Tomsgu** [comment]
Closing as answers were given.
