### ISSUE TITLE
The font natural size is different in 0.12.3 and 0.12.4

### ISSUE THREAD

**Issue by Segerega** [wkhtmltopdf/wkhtmltopdf#3651]
Hello. We just moved from 0.12.3 to 0.12.4 version. 
On previous version we had pixel perfect mockups, 
After moving to new version everything is moving out of the borders. 
Do you have any suggestions how to fix that?
Thanks

**Comment by Frederick888** [comment]
Same issue here. The HTML which used to be converted to a full page A4 PDF now gives approximately 1/5 blank at the bottom.

**Comment by Frederick888** [comment]
I think this is related to #2463. If I set `--zoom 1.28` (`1 / 0.78125 = 1.28`), it would be the same as `0.12.3`.

**Comment by Segerega** [comment]
Thank you very much, Frederick888 for reply. I will try this workaround and give you feedback. 
Regards

**Comment by danger89** [comment]
Would wkhtmltopdf milestone `0.12.5` fix the problems regarding the DPI under Linux?

**Comment by Tomsgu** [comment]
According to https://github.com/wkhtmltopdf/wkhtmltopdf/blob/master/CHANGELOG.md#v0125-2018-06-11 it is resolved in 0.12.5. Please feel free to re-open if the issue persists.
