### ISSUE TITLE
how to make wkhtmltopdf support the canvas of html5 with ChartJS

### ISSUE THREAD

**Issue by xiranst** [wkhtmltopdf/wkhtmltopdf#3654]
wkhtmltopdf version: 12.3,12.4,13 beta;
ChartJS is the latest version.

the canvas is working on web page, but it not work when create pdf with wkhtmltopdf.
how to solve it?

**Comment by kevinzzp** [comment]
make the canvas to img

**Comment by charuhasrocks** [comment]
@kevinzzp after making canvas to img pdf generated is empty.how to solve it? chart are not getting rendered.

**Comment by Sicos1977** [comment]
I don't know if you are on Windows but I made something the same as wkHtmlToPdf but then with Google Chrome as conversion engine. https://github.com/Sicos1977/ChromeHtmlToPdf

**Comment by charliereese** [comment]
I had this issue when using chart.js 2.7.1.

After switching to chart.js 2.6.0, the issue went away and I was able to PDF my charts. Seemingly, something added to chart.js after v2.6.0 has broken this.

If this doesn't work for you, try (1) adding length and width style attributes to a div that is the parent of the canvas container, or (2) making sure all of your file paths are absolute.

I'm a little late to the party, but hopefully this helps someone :)

**Comment by eldhotkuriakose** [comment]
Same issue here!
I am using chart.js 2.6.0 and added height and width attribute for canvas container. 
i need to generate graph from a radar type chart, Unfortunately it is not working.  
Any good hands here to help me out?

**Comment by charuhasrocks** [comment]
Actually there is no solution for it. It is working for some of the types for eg bar chart but not others.

**Comment by Tomsgu** [comment]
Please refer to #1964. There is no solution for it at the moment.
