### ISSUE TITLE
Exporting tabs within webpage to PDF additionally

### ISSUE THREAD

**Issue by willkochtitzky** [wkhtmltopdf/wkhtmltopdf#3656]
This is working great, but I have a question I can't figure out
I am trying to export about 150 web pages that look exactly like the URL below, but I need the tabs part of the way down the webpage to be exported as well.
https://oceanconference.un.org/commitments/?id=12930

i.e. where it says SDG 14 TARGETS, DELIVERABLES, RESOURCES MOBILIZED

It is only exporting the text from the firs tab on the page (the DESCRIPTION tab)
Does anyone know if it is possible to export as all of these tabs into the PDF?

Thanks!!!

**Comment by NiR-** [comment]
I guess you can create a print CSS and force each tab to be displayed using `display: block;` in that CSS.
