### ISSUE TITLE
Issue with table headers and page break

### ISSUE THREAD

**Issue by Zerajima** [wkhtmltopdf/wkhtmltopdf#3657]
When converting attached html file to pdf, first row after page break gets merged with table headers. I included both files, the original html and result of conversion to pdf.

This was tested with 0.12.4.0 version, 64-bit build on Windows 10.

[text.zip](https://github.com/wkhtmltopdf/wkhtmltopdf/files/1313371/text.zip)

**Comment by traday** [comment]
Check out [1524](https://github.com/wkhtmltopdf/wkhtmltopdf/issues/1524)
