### ISSUE TITLE
tables with <thead><tr> headers are overlapping starting from 2nd page

### ISSUE THREAD

**Issue by shradha1992** [wkhtmltopdf/wkhtmltopdf#3659]
I am using cakepdf mpdf 

- [ ]

**Comment by arashdalir** [comment]
I'd suggest going through similar issues posted. the answer is somewhere in this post:
https://github.com/wkhtmltopdf/wkhtmltopdf/issues/1524

**Comment by Tomsgu** [comment]
This is wkhtmltopdf not mpdf. Should be closed.
