### ISSUE TITLE
Complicated Server and Local Output with PDF by Wkhtmltopdf 0.12.x

### ISSUE THREAD

**Issue by tejastank** [wkhtmltopdf/wkhtmltopdf#3671]
OS : debian 7+

Point-A:  PDF generated in server 
[client-server-test3.pdf](https://github.com/wkhtmltopdf/wkhtmltopdf/files/1347242/client-server-test3.pdf)

Point-B: PDF generated in local linux 
[local-test3.pdf](https://github.com/wkhtmltopdf/wkhtmltopdf/files/1347243/local-test3.pdf)

Both generated perfect, but on point-A, space better latte very less as compare point-B produce best and perfect result.

How can I fix it ? Its really complicated to resolve 

I try dpi 96 too and Also tested with wkhtmltopdf 0.12.x and 0.13.x version too.

On server little space issue

**Comment by NiR-** [comment]
Could you add the command line used to generate those files please? I guess you have a X server installed on your local linux computer and `xvfb` on your server, right?

**Comment by tejastank** [comment]
Yes, added.

**Comment by tejastank** [comment]
This quite help to resolve, yes. 0.12 is needed with qt version 
https://gist.github.com/tejastank/45b6eba13fb38e24110218e3ce50129b
