### ISSUE TITLE
space in font name gives error 153 and Dictionary key must be a name object

### ISSUE THREAD

**Issue by puggan** [wkhtmltopdf/wkhtmltopdf#3672]
When using the font "OcrB", i get this object:
```
7 0 obj
<< /Type /Font
/Subtype /Type0
/BaseFont /OcrB Regular
/Encoding /Identity-H
/DescendantFonts Æ14 0 RÅ
/ToUnicode 15 0 R>>
endobj
```

The space on the /BaseFont-row gives error 153 in Adobe Acrobat Reader DC,
and the tool gives the error "Syntax Error (5317): Dictionary key must be a name object"

[font_example.zip](https://github.com/wkhtmltopdf/wkhtmltopdf/files/1349594/font_example.zip)

---

wkhtmltopdf Version: 0.12.1-2

uname -a: 

> Linux vagrant 3.16.0-4-amd64 #1 SMP Debian 3.16.43-2 (2017-04-30) x86_64 GNU/Linux

lsb_release -a:

> Distributor ID:	Debian
> Description:	Debian GNU/Linux 8.8 (jessie)
> Release:	8.8
> Codename:	jessie

**Comment by ashkulz** [comment]
A release candidate [is available](https://wkhtmltopdf.org/downloads.html#release-candidate) which includes the fixes made in PR wkhtmltopdf/qt#38 -- please test and report your findings before the final release.
