### ISSUE TITLE
broken flex-wrap and display: inline-block

### ISSUE THREAD

**Issue by Skippidar** [wkhtmltopdf/wkhtmltopdf#3673]
I'm trying to generate PDF from HTML where are 6 blocks with flex: 0 0 50% and parent block has flex-wrap:wrap (all have prefixes) but they are displayed in one line. No wraps. Also, there are 2 blocks with display:inline-block, but they display like display:block. This happens in wkhtmltopdf with patched qt, but in version vith unpatched qt everything is ok.

I'm trying to convert this page - https://granatland.ru/sluzhebnyie/pechat?id=156
patched qt generates this - https://drive.google.com/file/d/0B0oO1z1gfS78Q0RLYmpKenVMTEk/view
unpatched qt generates this - https://drive.google.com/file/d/0B0oO1z1gfS78Wk5tNFlyMDByNDg/view

**Comment by Skippidar** [comment]
I have no acces to this project anymore. So i cant tell u if that's still a problem

**Comment by Tomsgu** [comment]
Thanks for the feedback. Please feel free to re-open this issue if you have more information. There is also known issue in #3207.
