### ISSUE TITLE
Bad sha256sum for wkhtmltox-0.12.4_linux-generic-amd64.tar.xz

### ISSUE THREAD

**Issue by Gwerlas** [wkhtmltopdf/wkhtmltopdf#3674]
I downloaded the SHA256SUMS and wkhtmltox-0.12.4_linux-generic-amd64.tar.xz from the github release download page.

But the sums don't match (tested on mac and linux) :
% shasum -a 256 -c SHA256SUMS.dms
wkhtmltox-0.12.4_linux-generic-amd64.tar.xz: FAILED
shasum: WARNING: 1 computed checksum did NOT match
% shasum -a 256 wkhtmltox-0.12.4_linux-generic-amd64.tar.xz                                                           
7896a417fd1a47841274d6496c9cbe4328d73a2cad3f939fed2d40df3d3a12d2  wkhtmltox-0.12.4_linux-generic-amd64.tar.xz

Security issue or sums generation troubles ?

**Comment by ashkulz** [comment]
```
# sha256sum -b wkhtmltox-0.12.4_linux-generic-amd64.tar.xz 
049b2cdec9a8254f0ef8ac273afaf54f7e25459a273e27189591edc7d7cf29db *wkhtmltox-0.12.4_linux-generic-amd64.tar.xz

# shasum -a 256 -c SHA256SUMS 
wkhtmltox-0.12.4_linux-generic-amd64.tar.xz: OK
```

Maybe you got a corrupted download?

**Comment by Gwerlas** [comment]
Right, i tried again today. Sorry
