### ISSUE TITLE
Page Break

### ISSUE THREAD

**Issue by bhallar045** [wkhtmltopdf/wkhtmltopdf#3678]
Hi, I am using wkhtmltopdf and want a page break added in the PDF generated. 
Can you please help me with the same. Basically, I am looking for something which can be added as an option while generating pdf
Thanks in advance.

**Comment by M-Picco** [comment]
Hi. My solution to the same problem was to add the 'page-break-after' css property to the block you want to break the page after.

For, example, take the html:
```html
<div class="page">
    <div class="content">
        My content 1
    </div>
</div>
<div class="page">
    <div class="content2">
        My content 2
    </div>
</div>
```
Adding "page-break-after" to the "page" class should do the trick.

**Comment by YanaSavchenko** [comment]
I fixed the page-break problem by removing all "overflow:xxx" in css. that also fixed the problem when text was split between two pages. 

I hope this comment helps someone. Because I've spent like 2 hrs trying to make this thing work and couldn't find any solution in the internet.

**Comment by Tomsgu** [comment]
Closing as it was discussed here many times.
