### ISSUE TITLE
Still an active project?

### ISSUE THREAD

**Issue by lunij** [wkhtmltopdf/wkhtmltopdf#3679]
The last commits on master are from August but the last release is from November last year. Also there are more open issues than closed ones.

So is wkhtmltpdf still an actively maintained project and is it still recommended to use it in production?

**Comment by NachtRitter** [comment]
@ashkulz can you please tell when version 0.13 with patched qt will be released?

**Comment by megamindbrian** [comment]
It's still active. I love this tool.

**Comment by Sicos1977** [comment]
If you are on Windows can you then try this? It's something simular than wkHtmlToPdf but instead it uses the latest version of Google Chrome underwater.

https://github.com/Sicos1977/ChromeHtmlToPdf

**Comment by KuenzelIT** [comment]
Does anyone know something new about this question?

**Comment by ashkulz** [comment]
Currently working on a reworked packaging system in the [wkhtmltopdf/packaging](https://github.com/wkhtmltopdf/packaging) repository, you can download preview builds [for linux](https://builds.wkhtmltopdf.org/0.12.5-dev/). For OS X and Windows, trying to automate the build using vagrant so a release can be created easily.

Planning to release a `-rc` by next weekend, and a release after a week .. so expect May 15 for the 0.12.5 release. Upgrading to the latest Qt and QtWebKit is something I'm planning to tackle after that.

**Comment by ashkulz** [comment]
Packages for 0.12.5 are now available from the download page.

**Comment by Cruiser13** [comment]
Is there some expected release date for 0.13 stable?
The 0.13 alpha doc here https://github.com/wkhtmltopdf/wkhtmltopdf/blob/0.13/README.md#013-alpha has not been changed for three years now...
