### ISSUE TITLE
wkhtmltopdf undefined:0 TypeError: 'undefined' is not a function masonry

### ISSUE THREAD

**Issue by xxvii27** [wkhtmltopdf/wkhtmltopdf#3681]
I'm trying to convert a html page with masonry to pdf, but got this error. My guess there is a polyfill missing, anyone knows what it is? I'm using 0.12.3

**Comment by alloylab** [comment]
is this still an issue on 0.12.5?

**Comment by alloylab** [comment]
We are closing this out since we haven't heard from you. If you are still having this issue please feel free to re-open it. Thanks.

**Comment by zxj95121** [comment]
while I try to get html DOM ,it show error.

**Comment by bdyyang** [comment]
the same error, used webpack4
