### ISSUE TITLE
0.13-alpha for macOS

### ISSUE THREAD

**Issue by Drapegnik** [wkhtmltopdf/wkhtmltopdf#3688]
Hi! 
Is there any prebuilded version of `0.13-alpha` for `osx`?
Does [branch `0.13`](https://github.com/wkhtmltopdf/wkhtmltopdf/tree/0.13) ([this commit](https://github.com/wkhtmltopdf/wkhtmltopdf/commit/e03f1d19f0543546fde2bbbb587e3b8c012a4cbb)) correspond to `Linux` & `Windows` alpha builds from [here](https://wkhtmltopdf.org/downloads.html)?

Thanks.

**Comment by ashkulz** [comment]
That hasn't happened yet, but any such discussion should be carried out in [wkhtmltopdf/packaging](https://github.com/wkhtmltopdf/packaging).
