### ISSUE TITLE
Image Rendering Darker with High Resolution Images

### ISSUE THREAD

**Issue by 91juhwang** [wkhtmltopdf/wkhtmltopdf#3694]
[Wicked_pdf Issue(original)](https://github.com/mileszs/wicked_pdf/issues/699)
[Reproduced error (Referenced the wkhtmltopdf issue)](https://github.com/wkhtmltopdf/wkhtmltopdf/issues/2208)

Above is the opened issue in `wicked_pdf` gem, but it is more of a problem with `wkhtmltopdf`. 
The maintainer of `wicked_pdf` has made a comment with code examples in the second link of `wkhtmltopdf`. 

To summarize the issue, using `0.12.4` version of `wkhtmltopdf`, and everything works perfect EXCEPT with high resolution images. The images are rendered darker, and it is easily reproducible with high definition images. 

```html
<!doctype html>
<html>
  <head>
    <title>Darker images</title>
    <style>
      .cityscape {
        border: 10px solid #ffc40e;
      }
    </style>
  </head>
  <body>
    <img class="cityscape" src="https://images.datahubus.com/core_data/image/file/59e506/e7f50c/fd0324/f29cf3/3c496229-14b7-4530-8ef2-7e4273d9a20e_C72A5718.jpg" width="2400">
  </body>
</html>
```
Any idea as to why this is happening? 

Thank you very much for the awesome software and hard works!! :)

**Comment by mihkeln** [comment]
The large photo you are referencing has the following color profile: **ProPhoto RGB**. Once you convert that to **sRGB**, it will work fine. You can use ImageMagick for this.

**Comment by 91juhwang** [comment]
Like @Mihkeln said, this has been resolved! Thank you
