### ISSUE TITLE
Generated PDF returns bad mime type in php.

### ISSUE THREAD

**Issue by danielson317** [wkhtmltopdf/wkhtmltopdf#3699]
Using PHP Code to detect the mime type of the file is essential for web security. A pdf generated by wkhtmltopdf fails to return 'application/pdf' and instead returns '/unknown'. This cauld cause a lot of problems for web based applications. I could get around letting users download these files but they would never be allowed to upload them again.

PHP Code:
```
$file_info = new finfo(FILEINFO_MIME_TYPE);
$mime_type = $file_info->file($file_path);
// $mime_type always equals '/unknown'
```

**Comment by tomfortmuller** [comment]
Has a workaround for this been determined? I'm having the same issue. A PDF is generated on the server and downloaded by the client. If the client then uploads that same PDF, the detected mime type is application/octet-stream (same as unknown).

**Comment by Tomsgu** [comment]
- Do you still have this issue in 0.12.5?
- If yes, can you post a command that you're using?
- What OS do you have?

It works completely fine for me:
```bash
> wkhtmltopdf github.com /tmp/out.pdf
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
Loading page (1/2)
Printing pages (2/2)                                               
Done                                                           
> file --mime-type /tmp/out.pdf 
out.pdf: application/pdf
```

**Comment by PhilterPaper** [comment]
I don't think a PDF is responsible for declaring a MIME type for itself. A PDF can have MIME types for various embedded content (files, streams, etc.) but I don't see anything about a MIME type for the whole PDF. So, who would be responsible for labeling a PDF as application/pdf? Wouldn't that be part of the web application that's doing the downloading or providing the file for download?
