### ISSUE TITLE
Error "libpng warning: iCCP: known incorrect sRGB profile" and "Segmentation fault" with phpwkhtmltopdf ubuntu server

### ISSUE THREAD

**Issue by kamelj** [wkhtmltopdf/wkhtmltopdf#3702]
Dears,
I have this error:

> Loading pages (1/6)
> [>                                                           ] 0%
> [======>                                                     ] 10%
> [=================>                                          ] 29%
> [========================>                                   ] 41%
> libpng warning: iCCP: known incorrect sRGB profile
> [==========================>                                 ] 44%
> [====================================================>       ] 88%
> [============================================================] 100%
> Segmentation fault (core dumped)

I used it on: 
Ubuntu Server version 16 with PHP Nginx 
Wkhtmltobdf version  0.12.4
Phpwkhtmltopdf: https://github.com/mikehaertl/phpwkhtmltopdf
Chart.js version: 2.5.0

This issue appear with this javascript code for "chart.js":

```html
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.5.0/Chart.min.js"></script>
<script>
		var canvas = document.getElementById("barChart");
		var ctx = canvas.getContext('2d');

		ctx.canvas.width = 600;
		ctx.canvas.height = 300;

		// Global Options:
		Chart.defaults.global.defaultFontColor = 'black';
		Chart.defaults.global.defaultFontSize = 14;

		var data = {
		  labels: ["","الإختبار ","القياس و الهندسة","الاحتمالات الأول الثانوي",""],
		  datasets: [{
			  label: "الدرجة المئوية",
			  fill: false,
			  lineTension: 0,
			  backgroundColor: "rgba(0,0,0,0)",
			  borderColor: "black", // The main line color
			  borderCapStyle: 'line',
			  borderDash: [], // try [5, 15] for instance
			  borderDashOffset: 0.0,
			  borderJoinStyle: 'miter',
			  pointBorderColor: "black",
			  pointBackgroundColor: "white",
			  pointBorderWidth: 2,
			  pointHoverRadius: 8,
			  pointHoverBackgroundColor: "white",
			  pointHoverBorderColor: "white",
			  pointHoverBorderWidth: 2,
			  pointRadius: 4,
			  pointHitRadius: 10,
			  data: [null, 29,40,40,null],
			  spanGaps: true
			}]
		};

		var options = {
			responsive: true,
			maintainAspectRatio: false,
			scales: {
					yAxes: [{
						ticks: {
							max: 100,
							min: 0,
							stepSize: 15,
							scaleOverride : true,
							scaleStepWidth : 15,
						},
						scaleLabel: {
							 display: true,
							 labelString: 'الدرجة المئوية',
							 fontSize: 20 
						}
					}],
					xAxes: [{
						ticks: {
							fontSize: 12
						},
						afterFit: function(scale) {
							scale.height = 80;
						}
						/*scaleLabel: {
							display: true,
							labelString: 'الأختبارات',
							fontSize: 20
						},*/
					}]
				},
			legend: {
					display: false
				},
			animation: {
				duration: 1,
				/*onComplete: function(animation) {
					console.log('done');
				}*/
			}
		};

		// Chart declaration:
		var myBarChart = new Chart(ctx, {
			type: 'line',
			data: data,
			options: options
		});

		Chart.plugins.register({
			beforeDraw: function(chartInstance) 
			{
				var ctx = chartInstance.chart.ctx;

				var chart_height = chartInstance.chart.height;
				var chart_width = chartInstance.chart.width;

				var chart_top_padding = 7;
				var chart_xAxes_height = 80;
				var chart_left_padding = 75;

				var chart_height_padding_perc = .13 * chart_height;

				var chart_height_area = chart_height - chart_xAxes_height - chart_top_padding;

				ctx.fillStyle = "#7abd5e";
				var green_start = chart_top_padding;
				var green_width = .21 * chart_height_area;
				ctx.fillRect(chart_left_padding, green_start, chart_width, green_width);

				ctx.fillStyle = "#459ce9";
				var blue_start = green_width + green_start;
				var blue_width = .15 * chart_height_area;
				ctx.fillRect(chart_left_padding, blue_start, chart_width, blue_width);

				ctx.fillStyle = "#f5c758";
				var orange_start = blue_start + blue_width;
				var orange_width = .19 * chart_height_area;
				ctx.fillRect(chart_left_padding, orange_start, chart_width, orange_width);

				ctx.fillStyle = "#e53535";
				var red_start = orange_start + orange_width;
				var red_width = .45 * chart_height_area;
				ctx.fillRect(chart_left_padding, red_start, chart_width, red_width);
			}
		});
</script>
```

**Note: When I disable javascript, it's working fine but sure without chart.
I try this on OS x same everything and it was working fine.**

Any help or suggestions please :(

**Comment by saurabh-prohaktiv** [comment]
@kamelj any updates on this, were you able to fix it?

**Comment by Tomsgu** [comment]
Closing as there is no response since February.

**Comment by ArcUk** [comment]
We are also seeing this issue, does anyone know if there has been any work to address this? Thanks.

**Comment by Tomsgu** [comment]
Hi @kamelj and @ArcUk,
with `--debug-javascript` option i got a following error: 
> Warning: undefined:0 TypeError: 'null' is not an object           

Note that there are some limitations. Please see #1964.

**Comment by KaleabTessera** [comment]
Same Issue.

**Comment by Tomsgu** [comment]
@KaleabTessera what do you get if you run it with `--debug-javascript`?

**Comment by imxiny** [comment]
Same Issue. Thanks!

**Comment by bon** [comment]
Same issue. Not using javascript.

**Comment by chesucr** [comment]
On Windows 10 I am trying to convert to image the following [bokehjs](https://github.com/bokeh/bokeh) (another graphic javascript library) example that used to work years ago as it was written [here](https://github.com/wkhtmltopdf/wkhtmltopdf/issues/3211#issuecomment-280227189)

	wkhtmltoimage.exe --debug-javascript --no-stop-slow-scripts --javascript-delay 3000 http://bokeh.pydata.org/en/latest/docs/gallery/image_rgba.html out.png

And I also got a couple of warnings

	Warning: undefined:0 TypeError: 'undefined' is not an object
	libpng warning: iCCP: known incorrect sRGB profile

The image is printed, but the plot is not appearing

And I think that is also related to this issue, though, bokeh is used instead of `chart.js`

**Comment by jeorlie** [comment]
I also have this issue. Not using javascript only html tags and css codes.

**Comment by rizwanswati** [comment]
i have the same issue, been trying for 4 day.
libpng warning : iCCP: known incorrect sRGB profile,
--javascript-debug gives Warning: undefined:0 TypeError: 'null' is not an object

any solution?
my machine is windows 10
php/wkhtmltopdf

**Comment by dtgay** [comment]
Same issue here. PDF generation fails -- seems to be more than just a warning. I don't have an error like a `TypeError` or anything.

```
Loading pages (1/6)
libpng warning: iCCP: known incorrect sRGB profile====>      ] 89%
Warning: file:///var/folders/3v/6w3dkjm53t93pl421z69hxy40000gn/T/wktemp-0c867ccd-4ee2-49b2-bd39-1c6019839237.html:1570 [object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object]
```
