### ISSUE TITLE
wkhtml in rails with ckeditor and wicked_pdf

### ISSUE THREAD

**Issue by elisbresciani** [wkhtmltopdf/wkhtmltopdf#3703]
Then my application receives the data from a ckeditor field, and I want to generate a pdf of that field with others together. The text is going normal, but it's not rendering the images, I do not know why, a white square appears in place.
the PDF shows the image
![image](https://user-images.githubusercontent.com/26804018/32439353-6f0f878c-c2d5-11e7-9b30-2ce72f402208.png)
in normal html shows normal image
![image](https://user-images.githubusercontent.com/26804018/32439407-be6572c4-c2d5-11e7-8859-b291137f4fff.png)
so anyone has any idea what's going on?
I opened a question in wicked_pdf but nobody has any idea what's happening, I also opened in stackoverflow but no one answered me yet. please help me.

**Comment by Tomsgu** [comment]
Sorry but without additional information we cannot help you. Also I think better place is in wicked_pdf to ask, because there are a lot of wrappers and know about how every single one works is impossible.
