### ISSUE TITLE
Getting Win32 Exception

### ISSUE THREAD

**Issue by biplabcsarker** [wkhtmltopdf/wkhtmltopdf#3705]
Currently I have developed one application. I used this tools for View to PDF conversion in ASP.NET MVC Application. When I host this application in plesk, I am getting Win32 exception. I dont know what is the problem exactly. Please help me in this regard.

**Comment by ashkulz** [comment]
Try the fix suggested in [this comment](https://github.com/wkhtmltopdf/wkhtmltopdf/issues/2782#issuecomment-377704398).
