### ISSUE TITLE
wkhtmltopdf exited with non-zero code 1

### ISSUE THREAD

**Issue by maddy45** [wkhtmltopdf/wkhtmltopdf#3709]
Error comes when i tried to generate the report in MobSf, below is the error

pdf_error | "Cannot Generate PDF"
err_details | "wkhtmltopdf exited with non-zero code 1. error:\nUnknown long argument --no-outline\n\nName:\n  wkhtmltopdf 0.9.9\n\nSynopsis:\n  wkhtmltopdf [OPTIONS]... <input file> [More input files] <output file>\n  \nDescription:\n  Converts one or more HTML pages into a PDF document, *not* using wkhtmltopdf\n  patched qt.\n\nGeneral Options:\n      --collate                       Collate when printing multiple copies\n      --copies <number>               Number of copies to print into the pdf                                      file (default 1)\n      --extended-help                 Display more extensive help, detailing                                      less common command switches\n  -h, --help                          Display help\n  -O, --orientation <orientation>     Set orientation to Landscape or Portrait\n  -s, --page-size <size>              Set paper size to: A4, Letter, etc.\n      --password <password>           HTTP Authentication password\n  -p, --proxy <proxy>                 Use a proxy\n  -q, --quiet                         Be less verbose\n      --username <username>           HTTP Authentication username\n  -V, --version                       Output version information an exit\nReduced Functionality:\n  This version of wkhtmltopdf has been compiled against a version of QT without\n  the wkhtmltopdf patches. Therefore some features are missing, if you need\n  these features please use the static version.\n\n  Currently the list of features only supported with patch QT includes:\n\n * Printing more then one HTML document into a PDF file.\n * Running without an X11 server.\n * Adding a document outline to the PDF file.\n * Adding headers and footers to the PDF file.\n * Generating a table of contents.\n * Adding links in the generated PDF file.\n * Printing using the screen media-type.\n * Disabling the smart shrink feature of webkit.\n\nContact:\n  If you experience bugs or want to request new features please visit \n  <http://code.google.com/p/wkhtmltopdf/issues/list>, if you have any problems\n  or comments please feel free to contact me: see \n  <http://www.madalgo.au.dk/~jakobt/#about>\n\n"

**Comment by jpaulin** [comment]
Can you check memory footprint of the server while this crash happens?

**Comment by Tomsgu** [comment]
Closing as there is no response since 2017.
