### ISSUE TITLE
HTTP Headers

### ISSUE THREAD

**Issue by WillianBR** [wkhtmltopdf/wkhtmltopdf#3711]
I have downloaded your tool and I have to say, it's amazing.  I'm using to generate screen shot of sites do show on a dashboard.  But I missed something very important.   There is specific scanaries when I have to input a TOKEN, so the target web site will allow me to get the data.  Otherwise, the HTTP request will be redirected to a login page and it's this one I got  on PDF/JPG.

May be the  

> wkhtmltopdf/wkhtmltoimage

 can provide  options like wget/curl. E.g.:

> $ [**wkhtmltoimage**|**wkhtmltopdf**] **--post-data** 'goto=SomeUrlOrItemToGoOnSite&ExtraParameters=somestuff' **--header**="X-Auth-Token: _35ZCLXE4U79WDXV8WV0KUGO2XKB5T24G_" 

It's common the Single Sign On protected resource to use TOKEN to allow or deny access to specific resources.   I supose QtWebKit has options set this kind of data before a request.

**Comment by WillianBR** [comment]
About the **header** thing.  Let me be more specific.  It would be a command line option to parse the data and set it's value on the **[QNetworkRequest](http://doc.qt.io/qt-4.8/qnetworkrequest.html)** object, calling **[setRawHeader](https://wiki.qt.io/How_to_set_user_agent_in_Qt_application)**.

> $ [wkhtmltoimage|wkhtmltopdf] **--header**="_X-Auth-Token_: 35ZCLXE4U79WDXV8WV0KUGO2XKB5T24G" **--header**="_Set-Cookie_: sessionid=38afes7a8.219ffwef9w0f;EncodeKey=cafe70770100"


And that would be translated to:

> 
> QNetworkRequest.**setRawHeader**("_X-Auth-Token_", "_35ZCLXE4U79WDXV8WV0KUGO2XKB5T24G_");
> QNetworkRequest.**setRawHeader**("_Set-Cookie_", "sessionid=38afes7a8.219ffwef9w0f;EncodeKey=cafe70770100");
> 



I hope have made myself clear about the idea!

**Comment by alloylab** [comment]
is this still an issue on 0.12.5?

**Comment by Tomsgu** [comment]
There are already --post, --custom-header and --cookie options.
