### ISSUE TITLE
my webpage convert to pdf latex image disappear

### ISSUE THREAD

**Issue by xiaobai1993** [wkhtmltopdf/wkhtmltopdf#3714]
this web url `http://wwwdev.hskaoyan.com/wap/share/questionPdf` contains some math latex image, but When use `wkhtmltopdf http://wwwdev.hskaoyan.com/wap/share/questionPdf test.pdf` to create pdf in CentOS, the math latex does not exist in pdf. What the reason might be?

**Comment by PhilterPaper** [comment]
When I look at your HTML page, only the first MathLaTeX image show up for (1) in both sections. The others are just thin lines. Looking at the page source, I can display all the MathLaTeX images without problem. Do you see the same problem in a browser? Are you able to see the (1) images in PDF? I think I would address why we're not seeing the images in a browser, before worrying about PDF. If you rearrange the source so they're not all one one line of HTML, is there any difference? How about using an explicit height, rather than auto? The images might be squashed down to 0 height for some reason.

**Comment by xiaobai1993** [comment]
thanks for replying me.the html page should show like the following, and the html source and image source has never been changed since I post the first issue to you. I use google and Safari browser on Mac can normal display as the following picture, is it might be the net slow cause what you saw is different to me.may be refresh will be ok.
![image](https://user-images.githubusercontent.com/15193630/32764321-793c146e-c8ca-11e7-90bb-d31158d981ee.png)
and this is what the pdf look like

![image](https://user-images.githubusercontent.com/15193630/32764592-0e8143f4-c8cc-11e7-8b0c-851e8d1b562a.png)
I find these javascript cause the problem.
```
$(function(){
    // 屏幕宽度
    var width = $(window).width();
    var img = $("#share_topic img[alt=latex]").length;
    // 获取图片宽度
    for(var i=0;i<img;i++){
        var img_width = $("#share_topic img[alt=latex]").eq(i).width();
        if(width < 1080){
            $("#share_topic img[alt=latex]").eq(i).width(img_width*0.28);
        }else{
            $("#share_topic img[alt=latex]").eq(i).width(img_width*0.5);
        }
        $("#share_topic img[alt=latex]").eq(i).css({
            "height":"auto",
            "vertical-align":"middle",
        });
    }
})
```
the javascript code adjust the latex image's width for make latex and text appear to be coordinated.because the latex height is not sure, if set a explicit height，latex will be stretched or compressed.if I change the html tag's id to make the script make no sense, the html can be display and the latex also show in pdf like the follow, although it does not looks very well.the url without javascript adjust is  `http://wwwdev.hskaoyan.com/wap/share/questionPdf2`
![image](https://user-images.githubusercontent.com/15193630/32764534-9cd09124-c8cb-11e7-901a-321eb39d7050.png)

I also have tried add some javascript param include `javascript-delay`and `no-stop-slow-script`,
the problem can be resolved.and at the end, I install the latest windows's version. I find more confused,  `wkhtmltopdf http://wwwdev.hskaoyan.com/wap/share/questionPdf test.pdf` the html page with javascript adjust can convert to pdf with latex image like this:


![image](https://user-images.githubusercontent.com/15193630/32765067-6c3317e6-c8ce-11e7-91a7-de23c293153a.png).

but this is also not stable, the success percent is about %50, the fails is also the same as in linux，--latex disappear.

I also tried the delete the <h3> to test, but it seems does not matter about this question.could you give some directions or suggestions, any will be appreciated.by the way, the both of wkhtmltopdf in windows and centos version is 0.12.4.

**Comment by xiaobai1993** [comment]
last comment what I want to say is,I delete h3 tag,I am sorry

**Comment by xiaobai1993** [comment]
latest status, thank you, the problem was resolved, this help me

> Add: Also, you have <h3> enclosing entire paragraphs. It should not be used for that, and may be confusing wkHTMLtoPDF.
I only change h3 to span, it works well.Why before I delete h3 is no use? I do not know, but now It's works! thanks

**Comment by xiaobai1993** [comment]
accurately，I delete `<script src="https://code.jquery.com/jquery-3.0.0.min.js"></script>`,just add these script on the html, and change h3 to span
```
<script>
    $(function(){
        // 屏幕宽度
        var width = $(window).width();
        var img = $("#share_topic img[alt=latex]").length;
        // 获取图片宽度
        for(var i=0;i<img;i++){
            var img_width = $("#share_topic img[alt=latex]").eq(i).width();
            if(width < 1080){
                $("#share_topic img[alt=latex]").eq(i).width(img_width*0.28);
            }else{
                $("#share_topic img[alt=latex]").eq(i).width(img_width*0.5);
            }
            $("#share_topic img[alt=latex]").eq(i).css({
                "height":"auto",
                "vertical-align":"middle",
            });
        }
    })
</script>
```

**Comment by PhilterPaper** [comment]
OK, it sounds like it's working for you now. That's good. As to _why_ `<h3>` tags didn't work and had to be changed to `<span>s`, I wouldn't be surprised if WebKit (the renderer used by wkHTMLtoPDF) is quite old and rather fragile, breaking when you pass multiple lines with images and font changes to a "heading" tag. Also, there have been many problems reported with WebKit's handling of Javascript code, so something may have gone wrong there.

If you enclose HTML tags in code marks (backticks), you can put them in your post. The 'code' status disables the display of HTML in your browser.

**Comment by diaohancai** [comment]
> 最新状态，谢谢，问题已解决，这对我有帮助
> 
> > 添加：另外，你有 ### 附上整个段落。不应将其用于此目的，并且可能会使wkHTMLtoPDF感到困惑。
> > 我只将h3更改为span，效果很好。为什么在删除h3之前没有用？我不知道，但是现在可以了！谢谢

help~~ html with latex ，wkhtmltopdf does't work
