### ISSUE TITLE
Error: free(): invalid pointer

### ISSUE THREAD

**Issue by stephentt-me** [wkhtmltopdf/wkhtmltopdf#3716]
Install from official repo, first run `wkhtmltopdf http://google.com google.pdf` and I got this output/error. Tried many other URL, but same result.
```
wkhtmltopdf http://google.com google.pdf


libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
Loading page (1/2)
*** Error in `wkhtmltopdf': free(): invalid pointer: 0x00007faddd9d33c0 ***
[1]    4056 abort (core dumped)  wkhtmltopdf http://google.com google.pdf
```

```
# Version:
wkhtmltopdf 0.12.4

# OS: Arch Linux
uname -r
4.13.11-1-ARCH
```

**Comment by psi-4ward** [comment]
Same here

**Comment by ashkulz** [comment]
Looks like the official binary is not working on Arch Linux. Try the distro package or contribute a PR for Arch Linux support to [wkhtmltopdf/packaging](https://github.com/wkhtmltopdf/packaging).
