### ISSUE TITLE
Debian 8 vs. Debian 9 - are both capable of compiling wkhtmltopdf

### ISSUE THREAD

**Issue by jpaulin** [wkhtmltopdf/wkhtmltopdf#3717]
When the doc says that a strict requirement for compilation of 'wkhtmltopdf' is a Debian 8, is there some reason I could not compile on Debian 9 as well?

**Comment by ashkulz** [comment]
Yes, see [wkhtmltopdf/packaging](https://github.com/wkhtmltopdf/packaging) for an updated approach which would work in any linux environment which has docker.
