### ISSUE TITLE
Problem with rendering one, specific font

### ISSUE THREAD

**Issue by buszmen201** [wkhtmltopdf/wkhtmltopdf#3720]
Hi,
I'm trying to convert from html to PDF.
[This is](https://i.imgur.com/z2hfpaA.png) a compared source HTML with rendered PDF.

[Sample files:](http://www29.zippyshare.com/v/yEa5EiO7/file.html) : 
- html this is what i tried to render
- 2 css files linked in html
- rendered sample PDF

Snippet of code: 

``` python 3
import pdfkit
import os

#--------- CONFIG ----------#
path_wkthmltopdf = r'C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe'
config = pdfkit.configuration(wkhtmltopdf=path_wkthmltopdf)
#---------------------------#

path = open(os.path.join('2017-11-13_23-54-44', 'js_pc_19.html'), encoding="utf8")
path_fonts = open(os.path.join('2017-11-13_23-54-44', 'fonts.css')).read()
path_pdf = os.path.join('2017-11-13_23-54-44', 'js_pc_19.pdf')

pdfkit.from_file(path, path_pdf, configuration=config)

**Comment by PhilterPaper** [comment]
I can't process .rar archives, so I can't see in detail what's going on, but from the PDF output it would appear that the font you are specifying is missing some of the square bracket "building blocks" in what wkHTMLtoPDF is using, but has them in your browser. Any chance of updating your local font files to get a more complete set of mathematical operators? Unfortunately, I think this will be a matter of trial and error.

**Comment by buszmen201** [comment]
I'm figured out what is problem... I had multiple "diffrent" fonts with same "title" inside font, so wkHTMLtoPDF merged those files in one file and embed in PDF

Solution: Changed name in FontForge and working like charm, now i'm search a way to:
a) change font names on the fly (scripting via FF, not this repo)
b) set page size by size of dom element, not always A4 :/
