### ISSUE TITLE
Moved server, installed 0.12.3 and now PDFs don't work

### ISSUE THREAD

**Issue by 1stevengrant** [wkhtmltopdf/wkhtmltopdf#3721]
We had an app using `0.12.3` and it worked perfectly for producing our PDF reports. We installed it from the `gna` mirrors at the time.

We had to migrate server and tried installing  `0.12.3` and it works, kind of, but our formatting is all over the place and we're missing an important background image.

Running on `Ubuntu 16.04.3`

I will happily pay for someone to help fix it.

**Comment by Tomsgu** [comment]
- Is it still happening in 0.12.5?
- What is your exact issue? Can you post a minimal test case?
