### ISSUE TITLE
Not able to complete installation in python

### ISSUE THREAD

**Issue by me-one-click** [wkhtmltopdf/wkhtmltopdf#3722]
Dear All,

I had tried to install wkhtmltopdf installation is not getting completed  I had tried downloading a fresh copy from pypi but still the installation is giving error. Even tried with wkhtmltopdf 0.1 but no progress. 

[image of error](https://i.imgur.com/yhQvakK.jpg)

Did anyone else encountered this problem. Please Let me know how to install 

Regards
one-click

**Comment by jpaulin** [comment]
@me-one-click 

"Bad marshal data" hints that the Python (interpreter) is trying to execute code that is not meant for that particular version. There are actually 2 leads in that screen capture (image).

1.
When any Python 3.x.x interpreter tries to run code Python 2.x code, then it nags about all kinds of things, including (lack of) parentheses.

2.
.pyc files are pre-compiled "binary" files that might also contain compiled bytecode which is not suitable for the Python you're currently using. 

That's as far as I can open up this, hope someone gets it all right, or you get more leads into it. Cheers!

**Comment by ashkulz** [comment]
Nothing to do with wkhtmltopdf, please check with whatever wrapper you are using.
