### ISSUE TITLE
Qt: INTERNALL ERROR: failed to install GetMessage hook 

### ISSUE THREAD

**Issue by Xingorno** [wkhtmltopdf/wkhtmltopdf#3727]
Hello, 
    I am creating maser-slave system. when I run  the code, something wrong happenend.
I'm using QThreadPool to create an instance of QRunnable class for every incommingConnection. My problem is that, it fails and give me this message:

QEventDispatcher: Failed to create QEventDispatcherWin32 internal window: 7
Qt: INTERNALL ERROR: failed to install GetMessage hook
looking forward for your reply

**Comment by ashkulz** [comment]
Not clear on how this is related to wkhtmltopdf.
