### ISSUE TITLE
Is there a detailed UnknownContentError?

### ISSUE THREAD

**Issue by xbox1994** [wkhtmltopdf/wkhtmltopdf#3728]
When I exec this:
`wkhtmltopdf http://localhost/user/1 user1.pdf`
get an error like this:
`Exit with code 1 due to network error: UnknownContentError`

I don't know what happened. It is unacceptable if I throw this error to the user. So what I want to know is if wkhtmltopdf command line tool can output a detailed error the server side returned like this:
```
Exit with code 1 due to network error: UnknownContentError {
statusCode: 404,
body: { "error: this user id is not existed"}
}
```

**Comment by Tomsgu** [comment]
Duplicate of #2228.
