### ISSUE TITLE
wkhtmltopdf ignores all page-break-xxx css styles

### ISSUE THREAD

**Issue by ngrippa** [wkhtmltopdf/wkhtmltopdf#3729]
I have a view which contains `<div class = "page-break">` tags at various places. My css contains     
`.page-break { page-break-before: always; }`. But those tags do not seem to be applied to the pdf renderer. If I call the view manually and print with chrome it works beautifully and it does the page-breaks where they belong. If i render this view those tags seem to be completly ignored. Is this a known issue?

**Comment by zyxxt** [comment]
maybe you can try this: `page-break-after: always; `
