### ISSUE TITLE
Images are broken between pages

### ISSUE THREAD

**Issue by RaulTsc** [wkhtmltopdf/wkhtmltopdf#3730]
Hi guys,

Thanks for building a great framework! It saved us a lot of time.

We just have this tiny issue with it. It breaks images between pages and I can't fix it. I created this repository that has an example of html that can be used to reproduce the issue: https://github.com/RaulTsc/wkhtmltopdf-images-bug/blob/master/example.html

wkhtmltopdf --version: `wkhtmltopdf 0.12.4 (with patched qt)` on Mac OS X High Sierra but also in Docker.

Would be very grateful for any fix/workaround you might have.

Thanks!
Raul

**Comment by Tomsgu** [comment]
This was mentioned here many times. You can find some workarounds in issues #2029 #2486 #1524.
