### ISSUE TITLE
wkhtmltopdf does not print dynamical content in PDF

### ISSUE THREAD

**Issue by AreTor** [wkhtmltopdf/wkhtmltopdf#3731]
In my local machine, I am trying to convert an HTML page to a PDF with wkhtmltopdf, using phpwkhtmltopdf wrapper (I tried also with the command line), however the generated PDF contains the static HTML of the page only, without the Javascript generated html. Consider that:

- The HTML + Javascript displays correctly in the browser.
- I have already tried with the --javascript-delay option without success.

As an example consider this HTML + javascript code that generates a dummy table in the page:

```html
<!DOCTYPE html>
<html>
  <head>
    <title>My HTML</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script>
      document.onreadystatechange = () => {
        if (document.readyState === 'complete') {
          // create a table
          var tr, td;
          holder = document.createElement('table');
          my_ar = [10, 20, 30];
          // add first row
          for (var x = 0, len = my_ar.length; x < len; ++x) {
            // first row
            if (x === 0) {
              var titles = ['a', 'b', 'c'];
              tr = document.createElement('tr');
              holder.appendChild(tr);
              for (var i = 0, len1 = titles.length; i < len1; ++i) {
                td = document.createElement('th');
                td.innerHTML = titles[i];
                tr.appendChild(td);
              }
            }

            // add other rows
            tr = document.createElement('tr');
            holder.appendChild(tr);
            for (var i = 0, len2 = titles.length; i < len2; ++i) {
              td = document.createElement('td');
              td.innerHTML = my_ar[i];
              tr.appendChild(td);
            }
          }

          document.body.appendChild(holder);
        }
      }
    </script>
  </head>
  <body>
          <a id="print-link" href="path/to/getPdf.php">Print it!</a>
  </body>
</html>
```
This is my getPdf.php script to make the PDF, called by an `<a>` in the HTML page. The script is inspired by the example shown in the phpwkhtmltopdf page.
```php
include_once "./vendor/autoload.php";

use mikehaertl\wkhtmlto\Pdf;


$pdf = new Pdf;
$pdf->binary = 'path/to/bin/wkhtmltopdf';
$pageOptions = array(
    'javascript-delay' => 2000,
    'encoding'         => 'UTF-8',
  );

$pdf->addPage('/path/to/index.html', $pageOptions);

if (!$pdf->send('report.pdf')) {
  throw new Exception('Could not create PDF: '.$pdf->getError());
}
```
When I click on the print link, a PDF is returned containing the print link, but the table is not displayed.

**Comment by Tomsgu** [comment]
Please try to ask in phpwkhtmltopdf project or in stackoverflow. --javascript-delay option should normally works.

**Comment by Tomsgu** [comment]
I made a second view on this issue and the problem is on line 8. ES6 syntax is not supported at the moment, see: #3596. You can use `--debug-javascript` option to see if there is any error.

@BLecha what do you mean by not doing anything? Can you prove that this option doesn't do anything?

**Comment by BLecha** [comment]
@Tomsgu  Well again if you set javascript delay option it wont do anything.

**Comment by krishnuchoudhary** [comment]
Same issue I faced .I create dynamic table using html+javascript. can any one help what should i do.?
