### ISSUE TITLE
How can I trim the white space after creating the pdf?

### ISSUE THREAD

**Issue by DBHoskisson** [wkhtmltopdf/wkhtmltopdf#3733]
Thanks for this tool.

Is there an option to trim the white space from the resulting pdf?

**Comment by PhilterPaper** [comment]
What "white space" are you referring to? Are the margins too large? Depending on whether you can successfully reflow your page content, you might decrease your **margin** settings or reduce the **media size** for the output.

**Comment by Tomsgu** [comment]
Closing as there is no response since 2017.
