### ISSUE TITLE
wkhtmltopdf website is down

### ISSUE THREAD

**Issue by michelt** [wkhtmltopdf/wkhtmltopdf#3734]
Hello,

wkhtmltopdf.org seems to be down and downloads are not availables anymore. 
Seems to be a problem of ssl certificate.

Can you fix it quickly or send me wkhtmltox-0.12.3_linux-generic-amd64.tar.xz file ?

Thanks !

**Comment by robindwilliams** [comment]
You should be able to get them from here: https://github.com/wkhtmltopdf/wkhtmltopdf/releases

**Comment by michelt** [comment]
Thanks that's perfect. I let you decide if you want to close the ticket or now still the website is still down.

**Comment by robindwilliams** [comment]
I'll leave that to the devs, as I'm just a fellow user :-)

**Comment by artkay** [comment]
Well, `composer install` is failiing due to that - which is causing serious issue in our CI/CD pipeline:

```
Connecting to downloads.wkhtmltopdf.org (downloads.wkhtmltopdf.org)|104.31.78.17|:443... connected.
HTTP request sent, awaiting response... 526 Origin SSL Certificate Error
2017-11-22 19:58:49 ERROR 526: Origin SSL Certificate Error. 
```

@ashkulz is there any information on when it is going to be up?

**Comment by MDagni** [comment]
Looks like it's up now..

**Comment by ashkulz** [comment]
Sorry about that, the server hosting that had to be rebooted and I was on a trip without internet access.
