### ISSUE TITLE
OSError [Errno 5] Input/output error: In generate html to pdf in python.

### ISSUE THREAD

**Issue by sunbarve** [wkhtmltopdf/wkhtmltopdf#3736]
Run main.py in background and close the terminal then this error occurred, its works fine when terminal is open of main.py running.Get the following successful output when terminal is open and main file running. 
Loading pages (1/6)
Counting pages (2/6)                                               
Resolving links (4/6)                                                       
Loading headers and footers (5/6)                                           
Printing pages (6/6)
Done  

Here are the errors while run main.py in background and close the terminal.:::
Traceback (most recent call last):
File /home/ubuntu/upruf/model/user_details.py, line 2290, in saveApplication
pdfkit.from_string(maketemplate, path + username + '.pdf')
File /usr/local/lib/python3.5/dist-packages/pdfkit/api.py, line 72, in from_string
return r.to_pdf(output_path)
File /usr/local/lib/python3.5/dist-packages/pdfkit/pdfkit.py, line 164, in to_pdf
sys.stdout.write(stderr)
OSError: [Errno 5] Input/output error while handling path /v1/saveapplication

**Comment by Maytrovato** [comment]
I'm having the same issue on my prod environment but not on my local. Still looking for answers

**Comment by sunbarve** [comment]
@Maytrovato : I have solved my issues.
Raised this issues because of wkhtmltopdf print the result on console/terminal after successful execution.but when we logout from server wkthmltopdf does not get terminal for display output,so it through's this error.
 #for not print wkhtmltopdf output on terminal
 sys.stdout = open(os.devnull, 'w')
