### ISSUE TITLE
wkhtmltopdf page break / table header issue

### ISSUE THREAD

**Issue by denizalpaslan** [wkhtmltopdf/wkhtmltopdf#3737]
Hi,

wkhtmltopdf version : 0.12.4
os : win7

I'm converting html to pdf using jsreport-core wkhtmltopdf recipe and jsrender engine using the following options:

`                wkhtmltopdf:{
                    printMediaType: true,
                    marginTop: 25,
                    marginBottom: 16,
                    marginLeft: 15,
                    marginRight: 17,
                    footer: "some footer"
                }`

and also footer-spacing: 5 as a global option.

It seems to work fine but in some cases, it poorly breaks the tables into the next page. For example, in the second page, there are a small space between table header and the rows. Or sometimes there is only the table header in the second page (the last data row is rendered on page 1 but the header repeats on page 2 anyway).

My CSS for page breaks is like :

`    table { page-break-inside:auto; }
    tr    { page-break-inside:avoid; page-break-after:auto }
    thead { display:table-header-group }
    tfoot { display:table-footer-group }`

A sample screenshot is attached. Any idea?

![page_break](https://user-images.githubusercontent.com/17001502/33125897-7e9e8a70-cf93-11e7-99a3-f6498783c06e.png)

**Comment by NathanCH** [comment]
@denizalpaslan checkout this brief Github issue: #1524
