### ISSUE TITLE
Can't print 3 different images in one document - Progress text is included in front of %PDF

### ISSUE THREAD

**Issue by markusd1984** [wkhtmltopdf/wkhtmltopdf#3738]
I have 3 different images, which all individually print fine using 
`<img alt="" src="http://192.168.100.10/sites/default/files/images/Image1.png">`

Even if I use this three times the same image shows there three times.

But when I use the 3 individual images together, wkhtmltopdf failed to load the pdf.

Very strange as the images load fine individually, got the same rights, and I tried all combinations that using 3x `<img alt"" src=`... is not the issue. 

Any ideas, or similar experience? How bet to trouble shoot?

**Comment by Sicos1977** [comment]
I don't know if you are on Windows but I made something the same as wkHtmlToPdf but then with Google Chrome as conversion engine. https://github.com/Sicos1977/ChromeHtmlToPdf
