### ISSUE TITLE
sh: wkhtmltopdf: not found

### ISSUE THREAD

**Issue by arogarth** [wkhtmltopdf/wkhtmltopdf#3739]
Want to run wkhtmltopdf on alpine docker container. I installed all listed dependencies `apk add zlib fontconfig freetype libx11 libxext libxrender` and copy wkhtmltox recursivly to /usr/local/. The file `/usr/local/bin/wkhtmltopdf` exists but if I want to execute it I get 

```
sh: wkhtmltopdf: not found
```

What is the problem and what is missing??

Best regards,
Arogarth

**Comment by jpaulin** [comment]
I believe, that when the error starts with 'sh', it means your shell simply does not go through enough paths to find your executable. **Or**, that the executable file has not been set to have 'x' (execute) permissions. When it doesn't have executable bit set, then the shell does not consider the file to be runnable.

Check your OS's specific way of handling these.

In the end, when both of the above are ok, you could launch an interactive shell, and should be able to type:
`type wkhtmltopdf`
and get a reply from shell:
**wkhtmltopdf is /usr/local/bin/wkhtmltopdf**

Googling for 'setting PATH how alpine' and 'change permissions executable alpine' would yield most likely the results.

**Comment by mikehaertl** [comment]
I have the same issue. It definitely is not a problem of the path. It throws the same error message, even if the full path name is provided. And yes, the file exists and is executable.

**Comment by mikehaertl** [comment]
Ok, here's an update. The problem is, that Alpine does not support GNU libc. More details can be found in this issue: https://github.com/gliderlabs/docker-alpine/issues/219

So the hard truth is: No wkhtmltopdf on Alpine for now, at least no easy way.

**Comment by ashkulz** [comment]
Currently working on a reworked packaging system in the [wkhtmltopdf/packaging](https://github.com/wkhtmltopdf/packaging) repository, you can download preview builds [for some distros](https://builds.wkhtmltopdf.org/0.12.5-dev/). Will accept PRs for Alpine support :smile:

**Comment by nesv** [comment]
I'm sorry for commenting on an old, closed ticket.

In case anyone is looking to make wkhtmltopdf work in Alpine, the following packages need to be installed:

- libxrender
- libxext
- gcompat

**Comment by kk-r** [comment]
@nesv  Thanks a lot :clap: You save my day!

**Comment by mikehaertl** [comment]
@nesv @kk-r Are you sure this works stable? See https://github.com/wkhtmltopdf/packaging/issues/2
