### ISSUE TITLE
version 0.12.1 on Debian 9.2 (needed to run Odoo)

### ISSUE THREAD

**Issue by AlainVanUtterbeeck** [wkhtmltopdf/wkhtmltopdf#3741]
Are there plans for a wkhtmltox-0.12.1_linux-stretch-amd64.deb ?
Odoo requires wkhtmltopdf 0.12.1, and I don't succeed in getting that done on Debian 9.2

Thanks in advance for your assistance

**Comment by danger89** [comment]
I'm trying to setup such a thing currently....
https://github.com/danger89/wkhtmltopdf

**Comment by ashkulz** [comment]
Currently working on a reworked packaging system in the [wkhtmltopdf/packaging](https://github.com/wkhtmltopdf/packaging) repository, you can download preview builds [for linux](https://builds.wkhtmltopdf.org/0.12.5-dev/). Will create something for 0.12.1 if required, would appreciate fixing any issues with odoo before the 0.12.5 release.
