### ISSUE TITLE
#3001 but for a web app on Heroku.com

### ISSUE THREAD

**Issue by Monzoji** [wkhtmltopdf/wkhtmltopdf#3742]
I'm aware of this https://github.com/wkhtmltopdf/wkhtmltopdf/issues/3001
How to fix it for a web app deployed on heroku.com ? One doesn't have a direct access to his server, hence no capacity to install libraries.

**Comment by ashkulz** [comment]
Use the correct binary? See the preview builds [for next release](https://builds.wkhtmltopdf.org/0.12.5-dev/).
