### ISSUE TITLE
Provide AppImage of wkhtmltopdf for Linux (instead or alternatively to tarball releases)

### ISSUE THREAD

**Issue by TheAssassin** [wkhtmltopdf/wkhtmltopdf#3745]
Providing an [AppImage](http://appimage.org/) would have, among others, these advantages:

- Applications packaged as an AppImage can run on many distributions (including Ubuntu, Fedora, openSUSE, CentOS, elementaryOS, Linux Mint, and others)
- One app = one file = super simple for users: just download one AppImage file, [make it executable](http://discourse.appimage.org/t/how-to-make-an-appimage-executable/80), and run
- No unpacking or installation necessary
- No root needed
- No system libraries changed
- Works out of the box, no installation of runtimes needed
- Optional desktop integration with `appimaged`
- Optional binary delta updates, e.g., for continuous builds (only download the binary diff) using AppImageUpdate
- Can optionally GPG2-sign your AppImages (inside the file)
- Works on Live ISOs
- Can use the same AppImages when dual-booting multiple distributions
- Can be listed in the [AppImageHub](https://appimage.github.io/apps) central directory of available AppImages
- Can double as a self-extracting compressed archive with the `--appimage-extract` parameter

**Comment by probonopd** [comment]
At least for the Qt 5 build this should be rather straightforward given that the project is already building on Travis CI.

https://github.com/probonopd/linuxdeployqt has many examples on how to produce AppImages of Qt 5 based applications on Travis CI. It is literally almost a copy&paste operation.

**Comment by ashkulz** [comment]
Currently working on a reworked packaging system in the [wkhtmltopdf/packaging](https://github.com/wkhtmltopdf/packaging) repository, you can download preview builds [for linux](https://builds.wkhtmltopdf.org/0.12.5-dev/). Would appreciate PRs for this.

**Comment by TheAssassin** [comment]
@ashkulz please create an issue in the new repository and CC me there, I'll have a look.
