### ISSUE TITLE
Multi Columns CSS for rendering PDF

### ISSUE THREAD

**Issue by dj1encore** [wkhtmltopdf/wkhtmltopdf#3748]
This issue is listed in a number of Posts, However, no solution is provided.

Using CSS,

  .newsection { -webkit-column-count: 2; /* Chrome, Safari, Opera */
    -moz-column-count: 2; /* Firefox */
    column-count: 2;}

does not render PDF with Newspaper style columns.

Desired output shown below;

![capture](https://user-images.githubusercontent.com/34314341/33674379-4f47ef24-da7d-11e7-8c56-5a79310715c2.PNG)

**Comment by Tomsgu** [comment]
Duplicate of #3172. You're not helping by opening duplicated issues.

**Comment by richmahn** [comment]
@Tomsgu It is helpful when nothing is being done about this much needed feature

**Comment by yannoliv** [comment]
Any news?

**Comment by l2m2** [comment]
Any news again?

**Comment by l2m2** [comment]
Finally I implemented it with javascript. A bit complicated but works.

**Comment by jeannyjohanis** [comment]
Hi @l2m2, interested to know how you implemented this with javascript

**Comment by richmahn** [comment]
@l2m2 yeah, interested too.
