### ISSUE TITLE
How to suppress page breaks in a page ?

### ISSUE THREAD

**Issue by andr222** [wkhtmltopdf/wkhtmltopdf#3754]
My version of wkhtmltopdf is 0.12.4, running on Mageia 6 64bit (Linux)

I want to save exact visual copies of html pages.
An html page has no line breaks INSIDE the page, so I don't want page breaks added by wkhtmltopdf.
From time to time one encounters pdf files without page breaks, so it must be possible.
I tried setting --page-height with various values, with no effect.
Most web pages are relatively short, so the format A4 doesn't cause a page break. 
However some pages, such as
https://meteo.gc.ca/forecast/hourly/qc-96_metric_f.html
are quite long.
(In this case, wkhtmltopdf divides into 4 pages.)

In passing, it seems rather bizarre that a PRINT FORMAT is applied by default.
Why would one expect that the page saved would be printed ???

**Comment by andr222** [comment]
wxhtmltopdf documentation doesn't give the units required for the various options.
What are the units of **--page-height** ?
Also, **--page-size custom**
is not accepted in place of **--page-size A4**
 for example.
Yet **custom** is one of the options in the page referenced in help.

**Comment by PhilterPaper** [comment]
This request comes up from time to time. See #1627 and #3208 to start.

**Comment by andr222** [comment]
I discovered that using wkhtmltoimage 'url' *.png does exactly what I want.
An exact visual image of the html page, no matter what the length, with a very compact file size.
wkhtmltopdf 'url' *.pdf will split the page for longer source pages.
In my latest tests, a pdf output of the same source page was over twice as long, but still relatively small.
Using output *.svg produces enormous files (10 or 20 times as large), at least on some pages.

(I really don't understand why there is an assumption that the pdf file will be printed.  Almost everyone has a computer to display such files.  Also, many pdf files downloaded from internet have one or more very long pages.  I've some which displayed on over 10 screen pages, or about 5 print pages.)

Note that I'm not interested in retaining links for my most common use case.
Although retaining links would be very useful in some cases.
Thus having an option for wkhtmltopdf that outputs html pages without added page breaks would be a big plus for me as well as other users.

In any case, thanks for this very useful application.  Recent changes in Mozilla (Firefox & Seamonkey) browsers have made this invaluable.

BTW, it would be nice to have a wiki which covers how to use wkhtmltopdf & wkhtmltoimage, if possible.  Preferably one to which users could contribute.

**Comment by andr222** [comment]
Since images are almost but not always larger, typically at least 10 times as large, I would prefer pdf over image.  (It makes sense that pdf format would be smaller, since it can mix bitmap and/or vector images and text, corresponding to the source html page.)
As an alternative to **A4** (210x297), there is **Folio** (210x330), useful for an html page a little too long for A4.
There is also the option **custom**, for user-defined page sizes.
Is it possible to use it with wkhtmltopdf, and if so, what syntax is required ?
(examples of what doesn't work : **-s custom 210x333**  ..or..  **-s 210x333**  ..or..  **-s 210*333** )

If custom size doesn't yet work, it would make an excellent enhancement.

**Comment by ionalchemist** [comment]
Custom sizes work, but you have to pass it in via `--page-height` and `--page-width` commands followed by the number and unit. Thus for **210x333**, assuming it's millimeters, you would use:

`--page-width 210mm` and `--page-height 333mm`

to accomplish the custom size. On a final note, if you pass in these two variables, they will override `--page-size` if it is also declared.
