### ISSUE TITLE
How to fix space between letters while generating pdf with wkhtmotopdf.

### ISSUE THREAD

**Issue by softima** [wkhtmltopdf/wkhtmltopdf#3755]
iam getting space between letters while generating pdf with wkhtmotopdf.

Example Error : No change s since pre vious asse ssme nt
original is  : No changes since previous assessment

**Comment by PhilterPaper** [comment]
This problem has been reported before. I don't recall if a fix was found. You should search around older problem reports to see if you're getting the same kind of problem, and if a solution was found. More information needed: is this consistent with certain letters or letter combinations? You've checked that you don't have anything in-between the letters (a thin space, a soft hyphen, or anything else)? What wkHTMLtoPDF version, what operating system and version? A small sample HTML showing the problem and the command line used?

**Comment by daveherman71** [comment]
We had a similar problem using Version 0.12.4 on Windows Server 2012. We resolved it by changing the font to Roboto (https://fonts.google.com/specimen/Roboto).
