### ISSUE TITLE
How to avoid the covered next line text when splited pages?

### ISSUE THREAD

**Issue by charlilezar** [wkhtmltopdf/wkhtmltopdf#3758]
The tools works well, but i hava a little problem.

The text in <thead> will cover the original row content when appeared at next page.

Description:
I have a large table（more than 30 rows） and converted 2 pages of PDFs.  but the HTML content of <thead>repeated when the table is too large, caused the new first row was covered. How to seperate the <thead> and first row?  Appreciate for any suggestion！
table content like below:

<table >    
<thead>  <tr><th></th></tr></thead>
</table>

**Comment by PhilterPaper** [comment]
Use backticks (similar to a grave accent) to disable processing of `<thead>` etc. tags in your posts.

Is your complaint that table content is overlapping the header (or footer)? This has been discussed many, many times. Please read through the threads here and see if your case is the same.

**Comment by charlilezar** [comment]
@PhilterPaper  thanks.  I've resolved by reference of  #1524 . I tried remove the tag of <thead> or change to normal tag.  it worked.  The method of add style for <thead> : display:table-row-group also works.  Thanks again!
