### ISSUE TITLE
WKHtml2PDF.exe crashes

### ISSUE THREAD

**Issue by rixs** [wkhtmltopdf/wkhtmltopdf#3761]
I have a reproducible html2pdf example that crashes when I set the zoom factor to 0.99.
The same example does not crash when zoom factor is 0.95
I can provide you with code css and the like to reproduce this case.
I use Windows version 0.12.4.0 64 bit.

Can anyone tell me what this exit code below means?
Thank you.

this is my output:

Loading pages (1/6)
[>                                                           ] 0%
[===>                                                        ] 5%
[======>                                                     ] 10%
[===============>                                            ] 26%
[=================================>                          ] 55%
[=================================>                          ] 55%
[==================================>                         ] 58%
[=======================================>                    ] 65%
[============================================================] 100%
Counting pages (2/6)                                               
[==============================>                             ] Object 1 of 2
[============================================================] Object 2 of 2
Resolving links (4/6)                                                       
[==============================>                             ] Object 1 of 2
[============================================================] Object 2 of 2
Loading headers and footers (5/6)                                           
[>                                                           ] 0%
[>                                                           ] 2%
etc.

[==========================================================> ] 98%
[==========================================================> ] 98%
[============================================================] 100%
Printing pages (6/6)                                               
[>                                                           ] Preparing
[==>                                                         ] Page 1 of 25
[====>                                                       ] Page 2 of 25
[=======>                                                    ] Page 3 of 25
[=========>                                                  ] Page 4 of 25
[============>                                               ] Page 5 of 25
[==============>                                             ] Page 6 of 25
[================>                                           ] Page 7 of 25
[===================>                                        ] Page 8 of 25
[=====================>                                      ] Page 9 of 25
[========================>                                   ] Page 10 of 25
[==========================>                                 ] Page 11 of 25
[============================>                               ] Page 12 of 25
[===============================>                            ] Page 13 of 25
[=================================>                          ] Page 14 of 25
[====================================>                       ] Page 15 of 25
[======================================>                     ] Page 16 of 25
[========================================>                   ] Page 17 of 25
[=========================$
EXEC:  array (
)
**( exitcode : -1073741819 )**
"C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe" --disable-local-file-access --zoom 0.99 -d 300 -L 19 -R 13 --disable-smart-shrinking --print-media-type -T 40 --header-spacing 10 -B 17 --footer-spacing 4 cover "https://www.url.ch/bulletin/cover.php?h1=Rapport+d%27audit&status=&h2=Cit%C3%A9+du+Gen%C3%A9vrier&h3_1=Le+Gen%C3%A9vrier&h3_2=CH+1806+Saint-L%C3%A9gier&auditdate=L%27audit+du%3A%26nbsp%3B28%2F09%2F2017+-+29%2F09%2F2017" "C:\Apache2\bulletin\temp\generate0.57845400 1513854040.html" --header-html https://www.url.ch/bulletin/header.php --footer-html https://www.url.ch/bulletin/footer.php "C:\Apache2\shtdocs\bulletin\temp\pdf4E2F.tmp" 2>>C:\Apache2\shtdocs\bulletin\temp\logs.txt
done

**Comment by Sicos1977** [comment]
Exitcode : -1073741819 = 0xC0000005 hexadecimal and if you look that one up on Google.....

> The 0xC0000005 Access Violation error is quite common among all versions of Windows systems and it is fairly broad as it involves a batch of issues. As a rule, system returns this error code when you run a program that attempts to access the location not assigned for its use. When the error message is closed, usually the software will be closed as well. The error means the software want to use system memory improperly. The error code 0xC0000005 also happens to other situations with different messages such as when you attempt to install system, perform certain function, launch system built-in tools, etc. You may meet one of the following messages when the error occurs:
> 
> An application error has occurred and an application error log is being generated. Exception: access violation (0xC0000005), Address "The application failed to initialize properly (0xC0000005). Click OK to terminate the application"
> 
> The "Stop 0x0000008E (0xC0000005 ...) " combination on the blue screen

**Comment by Tomsgu** [comment]
Is this still happening in 0.12.5?

**Comment by Tomsgu** [comment]
Closing since there is no feedback from the author.
