### ISSUE TITLE
Including SVGs using <object> tags causes them to be blank out in the generated PDF

### ISSUE THREAD

**Issue by zahirkelloud** [wkhtmltopdf/wkhtmltopdf#3762]
It seems like there's an issue when html's `<object>` tags are used to include SVG files.

Example 1:
`<object data="path/to/example.svg" type="image/svg+xml"></object>`

The above example renders perfectly on the browser but the generated PDF is completely blank. Now, if you happen to be familiar with the Angular framework, Angular has the `ng-include` directive which allows you to include other html or SVG documents.
Example 2:
`<div ng-include="'path/to/example.svg'"></div>`
or 
`<div ng-include="'path/to/example.html'"></div>`

In this example, wkhtmltopdf would acknowledge the SVG just fine while generating the PDF but the downside is that the quality of the rendered SVG varies from one browser to another. For example, while it renders just fine on Safari, just lately, it is partially broken in chrome and firefox. It doesn't seem like it guarantees a cross-browser compatibility anymore. Hence, I switched from using `ng-includes` directives to using `<object>` tags.

FYI, I haven't tried using `<image>` tags yet.

Any thoughts? Thank you

**Comment by hakimio** [comment]
<img> tag should be used with images, not object.

**Comment by Tomsgu** [comment]
Does this work with img tag?

**Comment by hakimio** [comment]
@Tomsgu Yes, SVGs work fine when using "img" tag.

**Comment by Tomsgu** [comment]
Ok thanks for the feedback.

**Comment by DylanYoung** [comment]
Why was this one marked invalid?

**Comment by hakimio** [comment]
Because you are supposed to use "img" tag to include SVG images, not object.

**Comment by DylanYoung** [comment]
That is not the case:

https://stackoverflow.com/questions/4476526/do-i-use-img-object-or-embed-for-svg-files/27128309#27128309

https://www.w3.org/Graphics/SVG/IG/resources/svgprimer.html#SVG_in_HTML

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/object

**Comment by DylanYoung** [comment]
And more importantly:

https://stackoverflow.com/questions/8102528/how-do-you-access-the-contents-of-an-svg-file-in-an-img-element

**Comment by hakimio** [comment]
Well, that's how it works with `wkhtmltopdf` and it's not gonna change anytime soon, since the author no longer actively maintains the project. If you want to display svg in PDF generated with `wkhtmltopdf`, you'll have to use `img`.

**Comment by DylanYoung** [comment]
Then that's a bug and it should be left open so that those who might consider using this software are aware.  It is not invalid.

**Comment by DylanYoung** [comment]
And, just as important, so that those who are interested in maintaining the project know what needs to be done.
