### ISSUE TITLE
Bleeding edge doesn't update the browser engine used.

### ISSUE THREAD

**Issue by TurboLOL** [wkhtmltopdf/wkhtmltopdf#3767]
I got the stable build which didn't use the updated browser engine so I decided to get the bleeding edge build, but I still got the same layout as before and the layout of websites wasn't updated. The version I am using is 0.13.0-alpha-7b36694 and also when I check the version it says, "Qt: Untested Windows version 10.0 detected!" and I was wondering if that was the cause. Any feedback is appreciated.

**Comment by hakimio** [comment]
In case you haven't noticed, alpha releases are from 2015-07.

**Comment by TurboLOL** [comment]
Oh, thank you.
