### ISSUE TITLE
i am having issue with Jquery tooltip and Menu not showing in PDF, please look at attached images

### ISSUE THREAD

**Issue by saqibshaikh15** [wkhtmltopdf/wkhtmltopdf#3768]
![tooltip](https://user-images.githubusercontent.com/26177084/34524630-350b23bc-f06a-11e7-9afc-9adb2f49d3de.png)

![menu](https://user-images.githubusercontent.com/26177084/34524535-e454e2f0-f069-11e7-8cba-4390e2fc9dfa.png)

**Comment by Tomsgu** [comment]
Closing as there is no information about the issue.
