### ISSUE TITLE
-dev package

### ISSUE THREAD

**Issue by brycesteve** [wkhtmltopdf/wkhtmltopdf#3769]
I am trying to the C library from this package as a dependency on Ubuntu 16.04.  I wondered if there was such a package as wkhtmltopdf-dev or equivalent that will install the include files and library?

**Comment by ashkulz** [comment]
Currently working on a reworked packaging system in the [wkhtmltopdf/packaging](https://github.com/wkhtmltopdf/packaging) repository, you can download preview builds [for linux](https://builds.wkhtmltopdf.org/0.12.5-dev/).  This should have the include files and library by default.
