### ISSUE TITLE
How can I print the entire webpage instead of the beginning part, and the entire code snippets in it?

### ISSUE THREAD

**Issue by timlee1** [wkhtmltopdf/wkhtmltopdf#3773]
I would like to download and convert https://spring.io/guides/gs/maven/ into a pdf file

But I tried several options of `wkhtmltopdf` in the following commands, and they can only print the beginning part of the webpage

```
wkhtmltopdf  https://spring.io/guides/gs/maven/ "Building Java Projects with Maven.pdf"
 wkhtmltopdf -n https://spring.io/guides/gs/maven/ "Building Java Projects with Maven.pdf"
 wkhtmltopdf --no-stop-slow-scripts https://spring.io/guides/gs/maven/ "Building Java Projects with Maven.pdf"

```

How can I print the entire webpage?

Also notice the code snippets have horizontal scroll bar. Is it possible to print the entire code snippets?  

Thanks.

**Comment by andr222** [comment]
Note : meant 'outputting' instead of 'printing' in 2nd paragraph.  (Printing to screen, not paper.)

**Comment by hakimio** [comment]
Download the html, edit the styles locally to remove scrollbars in html and then generate PDF from local html.

**Comment by Tomsgu** [comment]
See above. Please feel free to re-open if the issue persists.
