### ISSUE TITLE
duplicate tag generated in svg file when there are mixed encoding characters

### ISSUE THREAD

**Issue by peijiinsg** [wkhtmltopdf/wkhtmltopdf#3775]
Hi,
I'm using wkhtmltoimage to convert html to svg. The encoding is set as utf-8.

I found that if the html has mixed encoding characters in a tag, then the final generated svg will duplicate this tag into different position.
e.g.: in html i have a div: <div>这里有中文 中文 中文</div>, as there are two whitespace in between tag, then in svg file, the text in <div> will be built three times.
<text fill="#c3c3c3" fill-opacity="1" stroke="none" xml:space="preserve" x="110" y="460" font-family="Times New Roman" font-size="11" font-weight="400" font-style="normal" 
 >这里有中文 中文 中文</text>
<text fill="#c3c3c3" fill-opacity="1" stroke="none" xml:space="preserve" x="220" y="460" font-family="Times New Roman" font-size="11" font-weight="400" font-style="normal" 
 >这里有中文 中文 中文</text>
<text fill="#c3c3c3" fill-opacity="1" stroke="none" xml:space="preserve" x="222.75" y="460" font-family="Times New Roman" font-size="11" font-weight="400" font-style="normal" 
 >这里有中文 中文 中文</text>

**Comment by alloylab** [comment]
have you tried this on 0.12.5?

**Comment by alloylab** [comment]
We are closing this out since we haven't heard from you. If you are still having this issue please feel free to re-open it. Thanks.
