### ISSUE TITLE
Multiple instances are running in Task Manager when running from IIS

### ISSUE THREAD

**Issue by radduri** [wkhtmltopdf/wkhtmltopdf#3778]
We have an issue with the wkhtmltopdf.exe. Sometime when we run this application in IIS then identified a 99% CPU utilization because of 4 multiple instances of wkhtmltopdf.exe and each one taking 24%. Can you please help on the configurations if i need to do any?

**Comment by Sicos1977** [comment]
I had something similar and avoided this by using Chrome to convert to pdf. See my project for this over here --> https://github.com/Sicos1977/ChromeHtmlToPdf

**Comment by ashkulz** [comment]
Can you reproduce it outside IIS?

**Comment by Tomsgu** [comment]
I am closing this as there is no response since April. Please feel free to re-open if the issue persists.
