### ISSUE TITLE
new release needed

### ISSUE THREAD

**Issue by DanielRuf** [wkhtmltopdf/wkhtmltopdf#3779]

**Comment by ashkulz** [comment]
Currently working on a reworked packaging system in the [wkhtmltopdf/packaging](https://github.com/wkhtmltopdf/packaging) repository, you can download preview builds [for linux](https://builds.wkhtmltopdf.org/0.12.5-dev/). For OS X and Windows, trying to automate the build using vagrant so a release can be created easily.

Planning to release a `-rc` by next weekend, and a release after a week .. so expect May 15 for the 0.12.5 release. Upgrading to the latest Qt and QtWebKit is something I'm planning to tackle after that.

**Comment by ashkulz** [comment]
Packages for 0.12.5 are now available from the download page.
