### ISSUE TITLE
viewport-size does nothing?

### ISSUE THREAD

**Issue by DanielRuf** [wkhtmltopdf/wkhtmltopdf#3780]
Changing the value and setting `--disable-smart-shrinking` does not change the output at all.
Is there any working example for this?

**Comment by lexon0011** [comment]
I have the same problem. Any news for this issue?

**Comment by DanielRuf** [comment]
In general I would suggest using puppeteer in new (Node.js) projects s wkhtmltopdf is not actively maintained or developed anymore as it seems.

**Comment by speeddragon** [comment]
I'm working with Elixir, and I was using wkhtmltopdf because was the most download module (it's a wrapper to wkhtmltopdf) to generate PDF in Elixir. I've tested puppeteer, and it works fine. I will try to create a wrapper to puppeteer in Elixir.
