### ISSUE TITLE
Chartjs in pdf doesn't work

### ISSUE THREAD

**Issue by SnowDiamond** [wkhtmltopdf/wkhtmltopdf#3781]
Hi! Could you please help me with integrating Chart.js? I'm trying to render Chart.js in pdf, and it doesn't work for some reasons, just empty page. I tried setting `javascript_delay: 5000` and also `no_stop_slow_scripts: true` with no luck. 

Here is my code:

reports/show.pdf.slim:
```slim
doctype html
html
  head
    meta content=("text/html; charset=utf-8") http-equiv="Content-type"
    = javascript_include_tag "https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.1/Chart.bundle.js"

  body
    canvas id="myChart" width="200" height="200"

    javascript:
      var ctx = document.getElementById("myChart");
      var myChart = new Chart(ctx, {
          type: 'bar',
          data: {
              labels: ["Red", "Blue", "Yellow"],
              datasets: [{
                data: [12, 19, 3],
                backgroundColor: ['rgba(255, 99, 132, 0.2)', 'rgba(54, 162, 235, 0.2)', 'rgba(255, 206, 86, 0.2)']
              }]
          }
      });
```

reports_controller.rb:
```ruby
class ReportsController < ApplicationController
  def show
    respond_to do |format|
      format.pdf do
        render pdf: "pdf",
          template: 'reports/show.pdf',
          javascript_delay: 5000
      end
    end
  end
end
```

P.S. With option `show_as_html: true` Chart.js works perfect.

**Comment by wenbo** [comment]
With option show_as_html: true Chart.js works perfect, but what you see is just html, not PDF.
Have you got the PDF that generated using wkhtmltopdf from html with Chartjs please. 

now I got the following error:

```
➜  322 git:(master) ✗ wkhtmltopdf --debug-javascript  --enable-javascript  index.html chartjs.pdf
Loading pages (1/6)
Warning: undefined:0 TypeError: 'undefined' is not a function
Warning: undefined:0 TypeError: 'undefined' is not a function
Counting pages (2/6)
Resolving links (4/6)
Loading headers and footers (5/6)
Printing pages (6/6)
Done
➜  322 git:(master) ✗
```

**Comment by SnowDiamond** [comment]
@wenbo Thank you for advice! Probably that error inside Chart.js and not in my code.

I solved the problem. For some reasons Chart.js doesn't work with `slim`, I changed my view to `erb` and it works.

**Comment by wenbo** [comment]
@SnowDiamond 
After you changed your view to erb,  can you generate PDF using wkhtmltopdf smoothly please. I'm still confronted with the error message which said:
```
Warning: undefined:0 TypeError: 'undefined' is not a function
```
and it seems like the same issue with below one.
https://github.com/c3js/c3/issues/552
