### ISSUE TITLE
Measuring header/footer height with request attributes

### ISSUE THREAD

**Issue by srggroup** [wkhtmltopdf/wkhtmltopdf#3783]
Hi!

I'm using not fully static contents in footer. There are some parts in the content which depends on the replace attributes (get parameters) of the background request. But there are an other request which is measuring the footer's height (in `pdfconverter.cc line 215`). 
This request doesn't contain these parameters, so the measured height will be different. 

Is it impossible to include the replace attributes (especially the custom attributes) in this request as well?

wkhtmltopdf version: `0.12.4 (with patched qt)`
OS: Ubuntu 16.04.3

**Comment by alloylab** [comment]
We are closing this out since we haven't heard from you. If you are still having this issue please feel free to re-open it. Thanks.
