### ISSUE TITLE
Cannot parse pdf from a vue project

### ISSUE THREAD

**Issue by wonderFF** [wkhtmltopdf/wkhtmltopdf#3787]
My project used vue framework, and it can't work at develop environment,  I ran this command and couldn't get the result
```
wkhtmltopdf --page-size A4 --javascript-delay 5000 http://localhost:8889/#/reportdetail 400.pdf
```

**Comment by PhilterPaper** [comment]
What happened? Did it blow up with an error message, did it time out, did it finish but produce a blank or incomplete PDF, or something else? That URL can be browsed successfully? Perhaps wkHTMLtoPDF doesn't like something about localhost and/or that port and/or "#" as the path? Can you at least save the HTML to a local file and try processing that, to rule out that the HTML is bad?

**Comment by summerDan** [comment]
![qq 20180508103430](https://user-images.githubusercontent.com/38314158/39735001-3ae91376-52ac-11e8-8fca-c129678d69f3.png)
![qq 20180508103506](https://user-images.githubusercontent.com/38314158/39735007-3e60b9aa-52ac-11e8-87c3-e301294f7854.png)

Requirements: Generate a pdf on the page;
Currently vue is built, the referenced components are echarts (of course vcharts/vue-schart/vue-echarts, etc. have all been tried).
Generate pdf with tools (tool is wkhtmltopdf)
The current problem is: the page diagram shows normal, the generated pdf chart does not show up
Give a simple example code to solve
Thank you

**Comment by LDWX** [comment]
@wonderFF 兄弟，你的问题解决了没？我也遇到这个问题了，跪求啊

**Comment by LDWX** [comment]
@summerDan 兄弟，请问你的项目后来能导出pdf了吗？你也是vue项目吧，我的导出来是空白呀

**Comment by alloylab** [comment]
We are closing this out since we haven't heard from you. If you are still having this issue please feel free to re-open it. Thanks.

**Comment by SeanBurt** [comment]
> @summerDan 兄弟，请问你的项目后来能导出pdf了吗？你也是vue项目吧，我的导出来是空白呀
I also have this problem, so how solve it?

**Comment by diaohancai** [comment]
@LDWX 大兄弟，vue页面的pdf打印解决了嘛？？

**Comment by diaohancai** [comment]
@LDWX 大兄弟，vue页面的pdf打印解决了嘛？？

**Comment by LDWX** [comment]
已经解决了，用了服务端渲染




------------------&nbsp;Original&nbsp;------------------

**Comment by diaohancai** [comment]
> 已经解决了，用了服务端渲染
> […](#)
> ------------------&nbsp;Original&nbsp;------------------ From:&nbsp;"diaohancai"<notifications@github.com&gt;; Date:&nbsp;Sun, Oct 20, 2019 02:28 PM To:&nbsp;"wkhtmltopdf/wkhtmltopdf"<wkhtmltopdf@noreply.github.com&gt;; Cc:&nbsp;"沈鑫-前端工程师"<969187979@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;; Subject:&nbsp;Re: [wkhtmltopdf/wkhtmltopdf] Cannot parse pdf from a vue project (#3787) @LDWX 大兄弟，vue页面的pdf打印解决了嘛？？ — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

大兄弟，请问你还用wkhtmltopdf解决的嘛？
我现在有vue项目，需要用到pdf打印，发现样式问题大，而且echarts图表打印不出来。
你项目中是如何使用wkhtmltopdf的？
指点一下，非常感谢

**Comment by htlshu** [comment]
@LDWX Only use service render？What else methods？

**Comment by diaohancai** [comment]
> @LDWX Only use service render？What else methods？

As I know, wkhtmltopdf only support service render

**Comment by balbatross** [comment]
Super late to the party but for future reference https://programmer.group/html-to-pdf-graphic-report-practice.html

Options for vue + wkhtmltopdf seem to be limited to SSR or Bundling to ES5
