### ISSUE TITLE
Anchor target _blank not working inside pdf content using wkhtmltopdf

### ISSUE THREAD

**Issue by tsrinu03** [wkhtmltopdf/wkhtmltopdf#3788]
i am converting html to pdf using wkhtmltopdf
i have html code like 
 < a title="On click  points will deduct." href="http://website.com" target="_blank" class="view-pdf" >Click here</ a >"
After convert to pdf when i click on "Click here" website link opening in same tab. But need to open another tab because given target="_blank"
target blank not working inside pdf. please help on this

**Comment by alloylab** [comment]
have you tried this on 0.12.5?

**Comment by alloylab** [comment]
We are closing this out since we haven't heard from you. If you are still having this issue please feel free to re-open it. Thanks.

**Comment by pbriet** [comment]
Hi there,

I get the very same issue with 0.12.5

```
wkhtmltopdf --version
wkhtmltopdf 0.12.5 (with patched qt)
```

Thanks,

**Comment by idMolotov** [comment]
Have the same issue `target="_blank"` is not working for the links inside PDF content.

```
wkhtmltopdf --version
wkhtmltopdf 0.12.6.1 (with patched qt)
```
