### ISSUE TITLE
Html table with wide width

### ISSUE THREAD

**Issue by nicdnepr** [wkhtmltopdf/wkhtmltopdf#3792]
I have html  table with 30+columns, it has 100% width
I use landscape
But table cuts in result pdf
Is it possible wkhtmltopdf  set auto width?

**Comment by alloylab** [comment]
have you tried this on 0.12.5?

**Comment by nicdnepr** [comment]
No because it's old project
Is it solve in new version?

**Comment by alloylab** [comment]
I would need a testcase to understand the issue and see

**Comment by nicdnepr** [comment]
OK I try to test it

**Comment by Tomsgu** [comment]
So is this fixed @nicdnepr?

**Comment by nicdnepr** [comment]
I dont have time to test it
