### ISSUE TITLE
wkhtmltopdf does not work with Chartjs 

### ISSUE THREAD

**Issue by wenbo** [wkhtmltopdf/wkhtmltopdf#3796]
when run the following command, what I got is just blank PDF, nothing in the PDF just blank.  But in browser, you can see the chart that rendered by Chartjs.

```
$ wkhtmltopdf --debug-javascript  --enable-javascript  index.html chartjs.pdf
Loading pages (1/6)
Counting pages (2/6)
Resolving links (4/6)
Loading headers and footers (5/6)
Printing pages (6/6)
Done
$ wkhtmltoimage --version
wkhtmltoimage 0.12.4 (with patched qt)
```

the index.html source code: 
```
<html>
  <head>
    <title>chartJS PDF</title>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.1/Chart.min.js"></script>
  </head>
  <body>
<canvas id="myChart" width="400" height="400"></canvas>
<script>
Function.prototype.bind = Function.prototype.bind || function (thisp) {
  var fn = this;
  return function () {
    return fn.apply(thisp, arguments);
  };
};

var ctx = document.getElementById("myChart").getContext('2d');
ctx.canvas.width = 400;
ctx.canvas.height = 400;
var myChart = new Chart(ctx, {
    type: 'bar',
    data: {
        labels: ["Red", "Blue", "Yellow", "Green", "Purple", "Orange"],
        datasets: [{
            label: '# of Votes',
            data: [12, 19, 3, 5, 2, 3],
            backgroundColor: [
                'rgba(255, 99, 132, 0.2)',
                'rgba(54, 162, 235, 0.2)',
                'rgba(255, 206, 86, 0.2)',
                'rgba(75, 192, 192, 0.2)',
                'rgba(153, 102, 255, 0.2)',
                'rgba(255, 159, 64, 0.2)'
            ],
            borderColor: [
                'rgba(255,99,132,1)',
                'rgba(54, 162, 235, 1)',
                'rgba(255, 206, 86, 1)',
                'rgba(75, 192, 192, 1)',
                'rgba(153, 102, 255, 1)',
                'rgba(255, 159, 64, 1)'
            ],
            borderWidth: 1
        }]
    },
    options: {
        scales: {
            yAxes: [{
                ticks: {
                    beginAtZero:true
                }
            }]
        }
    }
});
</script>
  </body>
</html>
```
other similar issue: 
https://github.com/wkhtmltopdf/wkhtmltopdf/issues/1964

Anyone who has clue with this issue please help.

**Comment by wenbo** [comment]
Found the answer, thanks to the following post:
https://stackoverflow.com/questions/42561036/wkhtmltopdf-does-not-render-chart-js-2-5-0-graph

**Comment by dfriedmann** [comment]
> It might be because wkhtmltopdf uses QtWebKit which has problems with `Function.prototype.bind`. I had the same issue while using Chart.js via Chartkick (a Rails gem).
> 
> ```js
> Function.prototype.bind = Function.prototype.bind || function (thisp) {
>   var fn = this;
>   return function () {
>     return fn.apply(thisp, arguments);
>   };
> };
> ```
> 
> This Polyfill should enable you to use the latest version of Chart.js with `wkhtmltopdf`. You just have to include/add it to some HTML you want to render with wkhtmltopdf

Yes, thank you Chris Seelus for this answer. We had struggled for a couple of days why our chart.js graphs did not show in wkhtmltopdf files!

**Comment by cseelus** [comment]
Updated to 0.12.5 and unfortunately this Polyfill breaks PDF generation completely …

**Comment by altjx** [comment]
Does anyone have any updates on this by chance? For some reason, my chart shows up just perfectly fine using wkhtmltopdf version 0.12.5, but not 0.12.5 (with patched qt). I can't figure out what the "with patched qt" even means and how to get rid of that.

**Comment by cseelus** [comment]
[StackOverflow: How to install wkhtmltopdf with patched qt?](https://stackoverflow.com/questions/34479040/how-to-install-wkhtmltopdf-with-patched-qt) 

As I could not go that route, having my app hosted on Heroku, I switched to [ApexCharts](https://github.com/styd/apexcharts.rb). 
Another reason I prefer ApexCharts is, that it produces SVG charts. SVG is a vector graphics format, that is much better suited to PDF embedding than HTML Canvas Chart.js generates (which looks pixelated/blurry by default within PDF files).

**Comment by altjx** [comment]
Good to know. I realized that my issue has all boiled down to me using docker (I believe at least). In docker, I am forced to use 0.12.4 with `xvfb-run` to get charts to display in the PDF. However, the drawback is that my css doesn't all get rendered. For example, this gets completely ignored when using `xvfb-run` with `wkhtmltopdf`:

```
<style>
	p, ul {
		color: #545658;
		font-size: 12pt;
		font-family: "Arial";
		font-weight: 500;
	}

	* {
		font-family: "Arial";
	}
</style>
```

Instead, it renders in some weird font like Courier.

**Comment by itsmeJithin** [comment]
You can check [here](https://github.com/itsmeJithin/wkhtmltopdf-chartjs-working-demo)

**Comment by Oriphiel** [comment]
> 
> 
> [StackOverflow: How to install wkhtmltopdf with patched qt?](https://stackoverflow.com/questions/34479040/how-to-install-wkhtmltopdf-with-patched-qt)
> 
> As I could not go that route, having my app hosted on Heroku, I switched to [ApexCharts](https://github.com/styd/apexcharts.rb).
> Another reason I prefer ApexCharts is, that it produces SVG charts. SVG is a vector graphics format, that is much better suited to PDF embedding than HTML Canvas Chart.js generates (which looks pixelated/blurry by default within PDF files).

How you make work with ApexCharts?. I try and cant get the charts.

**Comment by joshuapinter** [comment]
We were running into an issue with using `jCanvas` for drawing elements on an image before rendering the PDF, but only after upgrading from 0.12.3 to 0.12.5. 

Upgrading to 0.12.6 fixed the issue for us.

**Comment by cjaoude** [comment]
> As I could not go that route, having my app hosted on Heroku, I switched to [ApexCharts](https://github.com/styd/apexcharts.rb).

Hi Chris @cseelus ,

We encountered the same issue with Chartjs + wkHtmlToPdf. Like you I don't want to mess with the wkHtmlToPdf install. Did ApexChartsJs resolve the issue for you? Was there any unexpected issues with wkHtmlToPdf + Apex? 

Tnx.

**Comment by cseelus** [comment]
HI @cjaoude, so far I'm quite happy with Apexcharts. Depending on your use case, you might have to adapt a few CSS rules though. Setting it up using the Rubygem is quite trivial, so I would just give it a try ;-)

This is what i had to do, to display the charts inside PDFs, the way I intended. Your mileage may vary, depending on the page width you set for your PDFs and other factors:
```sass
div[id^="chart-"]
  width: 990px // Force charts to be 100% wide
.apexcharts-canvas
  width: 970px!important

.apexcharts-svg
  position: relative
  .apexcharts-legend
    text-align: center
    position: absolute
    bottom: 10px
    top: initial!important
    left: 50%!important
    right: initial!important
    width: 500px
    margin-left: -250px
    .apexcharts-legend-series
      display: inline-block

.apexcharts-gridline,
.apexcharts-series path,
.apexcharts-xaxis-tick,
.apexcharts-xaxis line
  stroke-dasharray: 999!important

.apexcharts-bar-area
  min-height: 1px!important
```

**Comment by cjaoude** [comment]
@cseelus so ApexCharts works with wkhtmltopdf? you just had to monkey around the CSS? i'll give it a try. Decided to try Puppeteer and that's whole other headache, it doesn't like the js files.

**Comment by josh-core** [comment]
I could be late to the party, but I've had many similar problems and found 4 changes I had to make.

1. Add this pollfil to the page: <script src="https://cdnjs.cloudflare.com/ajax/libs/babel-polyfill/7.12.1/polyfill.min.js" integrity="sha512-uzOpZ74myvXTYZ+mXUsPhDF+/iL/n32GDxdryI2SJronkEyKC8FBFRLiBQ7l7U/PTYebDbgTtbqTa6/vGtU23A==" crossorigin="anonymous"></script>
2. Use the CDN link from here: https://cdnjs.com/libraries/Chart.js/2.9.4
3. Disable animations. If you don't you could end up with half the chart displaying
4. Wrap the canvas element in a div with the same width and height style applied

All of those things finally got a basic chart to render. FYI I'm using the WkHtmlToPdfDotNet nuget package for asp.net 3.1.

Also as an aside, if you are also using this nuget package, set BlockLocalFileAccess to false for the LoadSettings object. It says it defaults to false, but the underlying wkhtmltopdf attribute changed, so the default nolonger works.

**Comment by Ribeiro-Tiago** [comment]
@josh-core does using the babel polyfill instead of the other mentioned above worked for you ? 
```JavaScript
Function.prototype.bind = Function.prototype.bind || function (thisp) {
  var fn = this;
  return function () {
    return fn.apply(thisp, arguments);
  };
};
```

I'm running into an issue of segmentation fault 11 when I have the polyfill, but without the polyfill the charts don't work xD

I'm running 12.5 patched

**Comment by josh-core** [comment]
@Ribeiro-Tiago. I haven't run into that particular error, but no, that code didn't help me but the cdn script did. Also remember to wrap the canvas in a did with the same height and width applied. 

As I mentioned before I used WkHtmlToPdfDotNet, which had several events I could wire up to write the output of warnings and errors to the dot.net dev console to find the exact problem.

**Comment by Ribeiro-Tiago** [comment]
yeah I tried that but didn't work :(

I did find a [solution](https://github.com/wkhtmltopdf/wkhtmltopdf/issues/3242#issuecomment-337944125) that works with the the .bind polyfil on v12.5 patched which is to add this: 
```JavaScript
var super$setLineDash = CanvasRenderingContext2D.prototype.setLineDash;
CanvasRenderingContext2D.prototype.setLineDash = function override$setLineDash(segments) {
    if (segments.length === 0) {
        segments = [0];
    }
    super$setLineDash.bind(this)(segments);
};
```

**Comment by alekbless** [comment]
Any examples rendering [ApexChart](https://apexcharts.com/) in pdf with wkhtmltopdf?

**Comment by ravillarreal** [comment]
> HI @cjaoude, so far I'm quite happy with Apexcharts. Depending on your use case, you might have to adapt a few CSS rules though. Setting it up using the Rubygem is quite trivial, so I would just give it a try ;-)
> 
> This is what i had to do, to display the charts inside PDFs, the way I intended. Your mileage may vary, depending on the page width you set for your PDFs and other factors:
> 
> ```sass
> div[id^="chart-"]
>   width: 990px // Force charts to be 100% wide
> .apexcharts-canvas
>   width: 970px!important
> 
> .apexcharts-svg
>   position: relative
>   .apexcharts-legend
>     text-align: center
>     position: absolute
>     bottom: 10px
>     top: initial!important
>     left: 50%!important
>     right: initial!important
>     width: 500px
>     margin-left: -250px
>     .apexcharts-legend-series
>       display: inline-block
> 
> .apexcharts-gridline,
> .apexcharts-series path,
> .apexcharts-xaxis-tick,
> .apexcharts-xaxis line
>   stroke-dasharray: 999!important
> 
> .apexcharts-bar-area
>   min-height: 1px!important
> ```

can you provide a code snippet to see if apexcharts works with wkhtmltopdf?
