### ISSUE TITLE
Can support for PDF properties be added

### ISSUE THREAD

**Issue by Bilal-S** [wkhtmltopdf/wkhtmltopdf#3798]
Thanks for this project.
We were looking at ways to add PDF properties such as document description and custom meta data to the PDF similar to what is described here:
https://helpx.adobe.com/acrobat/using/pdf-properties-metadata.html

I was not able to not find a way to either encode this in HTML via tags or via command line in C lib or command line options.
Can support for PDF properties be added?
Thanks in advance,
B.

**Comment by hakimio** [comment]
This was requested a long time ago and the author of wkhtmltopdf said no:
https://github.com/wkhtmltopdf/wkhtmltopdf/issues/2000
You'll need some other utility to specify metadata.
