### ISSUE TITLE
Exception in Wkhtml2pdf.php line 334

### ISSUE THREAD

**Issue by frankleenDev** [wkhtmltopdf/wkhtmltopdf#3802]
Exception in Wkhtml2pdf.php line 902:
WKHTMLTOPDF didn't return any data

![error](https://user-images.githubusercontent.com/29050725/35704244-e368c1f6-07af-11e8-8e04-a4c92a953955.png)

**Comment by frankleenDev** [comment]
Wkhtmltopdf is an executable application and I'm hosting my project on godaddy which I'm sure is running linux platform is that an issue in any way and if so, shifting to a linux application would require libraries...?
How do I solve this, Please assist.

**Comment by frankleenDev** [comment]
@ashkulz

**Comment by jasonparallel** [comment]
I don't think Wkhtml2pdf.php is part of wkhtmltopdf. Maybe this project? https://github.com/mikehaertl/phpwkhtmltopdf

Your question is a bit confusing. You have to install wkhtml2pdf or use the C library.
