### ISSUE TITLE
CSS style compatibility problem

### ISSUE THREAD

**Issue by jinzhanyougithub** [wkhtmltopdf/wkhtmltopdf#3807]
Excuse me, is this style supported?
white-space: pre-wrap;

**Comment by jinzhanyougithub** [comment]
I'm using wkhtmlpdf version is wkhtmltopdf-0.12.3

**Comment by jinzhanyougithub** [comment]
![_15171557415636 1](https://user-images.githubusercontent.com/19453557/35846782-f511b362-0b52-11e8-97ef-1d60c30d8a45.png)

**Comment by jinzhanyougithub** [comment]
![_7610bc24-a042-4c98-b363-52cc82ba5e5b](https://user-images.githubusercontent.com/19453557/35846815-0e5959e2-0b53-11e8-91a9-f11f03906d7c.png)

**Comment by Tomsgu** [comment]
Closing as the author can test it by himself.
