### ISSUE TITLE
Printing: strange top margin on first page

### ISSUE THREAD

**Issue by acicovic** [wkhtmltopdf/wkhtmltopdf#3820]
Hi,

I pass an HTML document to wkhtmltopdf for conversion. Everything goes fine (the PDF is generated correctly), but when I print it, the first page always has a top margin which is not present in the displayed PDF. The second page gets printed with the correct top margin.

- The document's margin/padding CSS for body is set to 0.
- I've tried setting --margin-top and --margin-bottom to 0mm without any results

Page 2 always respects settings while page 1 does not, no matter what I've tried. Is this is a known thing and more importantly is there a way to fix it?

Thanks!

**Comment by PhilterPaper** [comment]
A long shot, but do you have a separately defined "cover" in the command, as opposed to a monolithic document starting at page 1? Maybe you have some different settings there, or maybe a "cover" is handled incorrectly.

It does seem strange that this margin would not show up in display, but only in printing. By any chance, is your print system set up to print the first page on _letterhead_ (forcing an extra top margin, even if it's blank paper)?

**Comment by acicovic** [comment]
@PhilterPaper thank you for your comment!

I have no cover whatsoever. I run wkhtmltopdf without commands (only source and destination file). I have no special print settings of any kind (I'll try to print elsewhere to see if it's related to the printer). I've tried printing from 2 different programs (Sumatra PDF and Foxit) and they exhibit the same behavior (normal display, printing with top margin on first page).

It's a very simple HTML document with styles specified within <head>. I see nothing that could explain this behavior. If you haven't encountered it perhaps it's a printer issue.

I'm open If there's any other feedback.

Thanks!

**Comment by acicovic** [comment]
When I printed on another printer everything went fine!

So I went to my printer settings, and well, mystery solved. This is really dumb.

While all those years I've been printing on A4 without any problems, my printer was set with US Letter Paper size! Due to the small paper size difference and that I don't print a lot I never realized it. Setting to A4 produced the desired result.

Sorry, and thank you for your time!

**Comment by PhilterPaper** [comment]
Reminds me of a story I once heard regarding A4 vs letter: at a Swedish nuclear power plant, disaster instructions were formatted and printed on A4 paper. Someone _copied_ the pages on a copier using (or set up for) US letter, and the last two (critically important) lines got chopped off. Fortunately, someone else happened to compare the two documents and realized what had happened! I don't know if it's true (or just an urban legend), but it's a good story.
