### ISSUE TITLE
HTTP 404.15 Length of the query string exceeds maximum

### ISSUE THREAD

**Issue by bucky86** [wkhtmltopdf/wkhtmltopdf#3822]
I'm encountering an unusual situation producing a PDF.  The following is a message contained within the PDF that was produced:
![image](https://user-images.githubusercontent.com/36659967/36448711-8855db8c-16dc-11e8-9da5-6f185b147c85.png)

After adding a max query string length to the web.config, I continue to receive an error message but slightly different this time.  I've gone as far as increasing the limit up to 3145728 with no success.
![image](https://user-images.githubusercontent.com/36659967/36448808-dd7e308c-16dc-11e8-9490-c00d9c5dc708.png)

With the modified web.config, Elmah reports the following query string:
![image](https://user-images.githubusercontent.com/36659967/36448897-3329ba1a-16dd-11e8-85a8-f21cc6d86b9c.png)
The string is long (just under 2500 characters), but not over the length set above.  The query string includes appended data for a given page in a &section parameter.  When I deleted data from the report to be sent to PDF or added additional whitespace between paragraphs, the PDF is produced without the error.  I'm guessing it's because the length of the query string is dropping below some threshold (perhaps 2048?).

At any rate, does anyone know how I can successfully increase the max query string length as the change to the web.config is not working?

**Comment by Tomsgu** [comment]
Closing as this is not a wkhtmltopdf issue.

**Comment by ccsousa01** [comment]
I had the same issue and it'ss true that this is not a concern of wkhtmltopdf. In my .NET application, I icreased the sized of the maxQueryStringLength   <httpRuntime targetFramework="x.x.x" **maxQueryStringLength**="16384" />  and needed to add a new security tag under system.webServer like so  <security>  <requestFiltering><requestLimits maxQueryString="16384" />     </requestFiltering> </security>
