### ISSUE TITLE
Break page visibility ???

### ISSUE THREAD

**Issue by Mickey3352** [wkhtmltopdf/wkhtmltopdf#3825]
I am trying to create a PDF from a large single HTML file. However even with top and bottom margin set to 0 I cannot avoid a small grey separation in the PDF output for each page.

Is it possible to generate PDF file without any break page separation for large HTML file ??

I am including image of my issue that would like to avoid.

![pagebreak](https://user-images.githubusercontent.com/36736434/36545013-33365f70-17e8-11e8-8d24-c36ca6ab82fd.jpg)

Michel

**Comment by Tomsgu** [comment]
Please refer to an existing issues #1524 and #2141 instead of creating a new one.
