### ISSUE TITLE
Set page orientation

### ISSUE THREAD

**Issue by clenondavis** [wkhtmltopdf/wkhtmltopdf#3828]
Hi guys, thank you for your time to sharing awesome codes to the community. I have been having some issue trying to implement the page orientation of the report page. I have readed and following the documentation, but I think i'm doing something wrong. I know is not the better code, i'm have been giving maintenance, i hope soon i refactor this code with better practice, but still I'll appreciate your help. Thank you

> **Stack**
> | MAC OS
> | Grails Version: 3.1.5
> | Groovy Version: 2.4.6
> | JVM Version: 1.8.0_152
> | wkhtmltopdf 0.12.4

**See the code bellows.**

```
package com.trendkite.app
import org.apache.commons.exec.*
/**
 * Created by austinarnold on 11/14/14.
 */
class PdfGenerator {
    static final String PDF_PROGRAM = "/usr/local/bin/wkhtmltopdf"
    static final String JS_DELAY_PARAM = "--javascript-delay"
    static final String JS_DELAY_MS= "8000"
    static final String PS_ORIENTATION = "--page-orientation L"
    static final String PS_ORIENTATION_LANDSCAPE = "L"

    public static File createPdf(String url) {
        CommandLine cmdLine = new CommandLine(PDF_PROGRAM)
        File f = new File(PDF_PROGRAM)
        if (!f.exists()) {
            throw new IOException("wkhtmltopdf app not found! Please ensure it is in the correct directory!")
        }
        cmdLine.addArgument(url)
        cmdLine.addArgument(JS_DELAY_PARAM)
        cmdLine.addArgument(JS_DELAY_MS)
        cmdLine.addArgument(PS_ORIENTATION)

        File output = new File(System.getProperty("java.io.tmpdir")+ "/" + UUID.randomUUID().toString() + ".pdf");
        final Map map = new HashMap()
        map.put("file", output)
        cmdLine.addArgument("\${file}")
        cmdLine.setSubstitutionMap(map)

        DefaultExecuteResultHandler resultHandler = new DefaultExecuteResultHandler()
        org.apache.commons.io.output.ByteArrayOutputStream stdout = new org.apache.commons.io.output.ByteArrayOutputStream()
        PumpStreamHandler psh = new PumpStreamHandler(stdout, stdout) //set same output stream for stdout and stderr

        Executor executor = new DefaultExecutor()
        executor.setStreamHandler(psh)
        executor.setExitValue(1) //for some reason, this process does not end cleanly with exit code 0
        ExecuteWatchdog watchdog = new ExecuteWatchdog(180000)//auto-kills process after 3 mins
        executor.setWatchdog(watchdog)
        executor.execute(cmdLine, resultHandler)
        resultHandler.waitFor()

        System.out.println(stdout.toString()) //this sends stdout and stderr to log file
        return output
    }
}
```

**Comment by jasonparallel** [comment]
I would guess your issue is with cmdLine. Try entering your command directly on the command line.

My guess would be 
cmdLine.addArgument("--page-orientation",false);
cmdLine.addArgument("L",false);

**Comment by clenondavis** [comment]
Thanks @jasonparallel for your answer. Let me check with your approach and then i'll let you know if this work.

**Comment by clenondavis** [comment]
@jasonparallel the documentation mention that in new release the page orientation option should be
`--orientation Landscape` 
Is my assumption correct? Thank you, i appreciate your time

**Comment by clenondavis** [comment]
@jasonparallel I get to know which is the issue. I setting the orientation as page option and this is global option. But my doubts now is how i can set via `cmdLine` or any way to set this option as global option. Do you have any idea?. I'll appreciate your help man. Thanks.

**Comment by clenondavis** [comment]
@jasonparallel in the global options, you can see this option `-O, --orientation <orientation>`

**Comment by clenondavis** [comment]
@jasonparallel my doubs will be how i'll add this `wkhtmltopdf -O Landscape https://thehackernews.com/ ./tt3.pdf` in grails code. This will be a big help man. Thanks for your time. I'm not a grails backend developer, I'm a Javascript developer, so i'll appreciate your time and your help to get this success.

**Comment by jasonparallel** [comment]
Try 
cmdLine.addArgument("-O",false);
cmdLine.addArgument("Landscape",false);

**Comment by clenondavis** [comment]
Hi @jasonparallel thanks for your help again, i appreciate your time. I already try that approach, and is still getting this issue. Thanks for your help man

> -O specified in incorrect location

**Comment by clenondavis** [comment]
Bingooooo @jasonparallel I already get to fix this. And know is working fine. Thanks for your help man. Its help me a lot. I'm very happy.

**Comment by jasonparallel** [comment]
Great. Find someone with a JS problem and pay it forward.

**Comment by jasonparallel** [comment]
@clenondavis You can also click close and comment to close the issue.

**Comment by clenondavis** [comment]
I already found the solution of this. The idea is when you are implementing cmdLine on groovy class, be sure to add global parameter before the url. 

```
cmdLine.addArgument("-O",false)
cmdLine.addArgument("Landscape",false)
cmdLine.addArgument(url)
```

If it needed i can add a pull request to the usage folder with those instructions unsing groovy class
