### ISSUE TITLE
Chinese Characters not working

### ISSUE THREAD

**Issue by jrdash** [wkhtmltopdf/wkhtmltopdf#3830]
hi,
we are using wkhtmltopdf tool for converting html to pdf. Tool not able to render Chinese characters in page. Attaching the simple html file for your reference. Yes this html file has not clear html as this page is out put of the outsystems tool. Let us know if any modification is  required in this page in order to work properly in wkhtmltopdf. thank you in advance. 

[LeapPage.txt](https://github.com/wkhtmltopdf/wkhtmltopdf/files/1755848/LeapPage.txt)

**Comment by shileislslsl** [comment]
your html page encode is not  right.

**Comment by alloylab** [comment]
have you tried this on 0.12.5?

**Comment by alloylab** [comment]
We are closing this out since we haven't heard from you. If you are still having this issue please feel free to re-open it. Thanks.
