### ISSUE TITLE
How to modify permissions

### ISSUE THREAD

**Issue by julienguillot77** [wkhtmltopdf/wkhtmltopdf#3837]
Hi everyone,

I would to know if there is a way to modify permissions of generated PDF like :

Modification of content
Commenting
Printing
High quality printing
Assemble document
Fill in forms
Copying of contents
Copying of contents for accessibility

Thank you for your answers !

**Comment by ed9** [comment]
Google is your friend, it has nothing to do with wkhtmltopdf from what I believe you're trying to do.

hint:
https://askubuntu.com/questions/27381/how-to-edit-pdf-metadata-from-command-line

**Comment by ashkulz** [comment]
It's better done in a tool which runs after the PDF generation,
