### ISSUE TITLE
CSS RGBA color causes long HTML to PDF render times

### ISSUE THREAD

**Issue by vedran-hibler** [wkhtmltopdf/wkhtmltopdf#3840]
Hi,

using CSS RGBA color on (specifically `<hr>`) HTML element causes PDF render to take about 10s. When RGBA is replaced with hex colors then same HTML render takes about 3-4s. There is also size difference between these two PDFs: 144kb with RGBA, 36kb without RGBA color. Both PDFs look the same only problem is with performances.

**Comment by PhilterPaper** [comment]
So, CSS such as `color: rgba(255,0,0,0.2);` takes much longer to render than something like `color: rgb(255,200,200);`? How about `color: rgba(255,200,200,1.0);`? IOW, does it depend at all on the opacity (alpha) value? Most importantly, when you say "render", you're talking about something like Adobe Reader _displaying_ the PDF, and not how long it takes wkHTMLtoPDF to _create_ the PDF?

If you are using the alpha channel _only_ to blend the line into a solid background color, a workaround might be to select a different final color and use rgb(). If you require true opacity (transparency), to let something beneath the HR to show through, that probably won't do the job. It's hard to believe that something like this would take that much more time, so there may be a problem in either WebKit or wkHTMLtoPDF's color code. I don't have my PDF spec handy, but does PDF and its viewer handle opacity, or is it something that has to be baked into a graphic (HR line) in some way? Can you look in the PDF and extract the code for the HR display, with rgba() and rgb(), and see if there's any clue there (particularly the huge size difference)? It sounds like wkHTMLtoPDF is creating an image of some sort, but even that shouldn't inflate render time _that_ much.

**Comment by Tomsgu** [comment]
Closing as there is no feedback since March.
