### ISSUE TITLE
--replace

### ISSUE THREAD

**Issue by Splathub** [wkhtmltopdf/wkhtmltopdf#3842]
Not sure if I'm using the option wrong or if it doesn't work. I've been using it like so
```js
options = {
    '--header-html': 'C:\\Users\\USerName\\Desktop\\header.html',
    "--replace": "number" "123456789"
}
 config = pdfkit.configuration(wkhtmltopdf=self.path_wk)
 p = pdfkit.from_file(htmldir, "C:\\Users\UserName\Desktop\TestPDF.pdf", options=options, configuration=config)
```

The header works fine, but once I add the option for replace I get the error below. The html file for the header is also properly setup for replace, i believe. Just added "number" in the array in the script, and have a span tag with class "number".

    raise IOError("wkhtmltopdf exited with non-zero code {0}. error:\n{1}".format(exit_code, stderr))
OSError: wkhtmltopdf exited with non-zero code 1. error:
You need to specify at least one input file, and exactly one output file
Use - for stdin or stdout

**Comment by Tomsgu** [comment]
Please try to ask in pdfkit itself. `--replace` option should work, so I think it's more related with your code or a wrapper.
