### ISSUE TITLE
why 0.12.4 stable version cannot get as package

### ISSUE THREAD

**Issue by SajithAthukorala** [wkhtmltopdf/wkhtmltopdf#3849]
why we cannot get the latest versions from package apt-get install ?

**Comment by macintoshplus** [comment]
Howto build the package ?
Howto build the headless version ?

**Comment by ashkulz** [comment]
That will be changing from 0.12.5, see [wkhtmltopdf/packaging](https://github.com/wkhtmltopdf/packaging) and the [preview binaries for linux](https://builds.wkhtmltopdf.org/0.12.5-dev/).
