### ISSUE TITLE
Blank PDF in local

### ISSUE THREAD

**Issue by iNaraku** [wkhtmltopdf/wkhtmltopdf#3851]
I have a problem with the press, my project is developed in ASP.NET MVC 5, everything worked fine until I changed my laptop, downloaded my TFS project and now the generated PDFs are shown blank in my local, but if the information is displayed correct on the server, I have the dll in the rotary folder as msvcp120.dll, msvcr120.dll, vccorlib120.dll, wkhtmltoimage.exe, wkhtmltopdf.exe, but I can not make it work locally

**Comment by alloylab** [comment]
what version?

**Comment by Tomsgu** [comment]
Closing because the issue is missing important information and there is no feedback from the author.
