### ISSUE TITLE
Issue with handling large Html String

### ISSUE THREAD

**Issue by eldhotkuriakose** [wkhtmltopdf/wkhtmltopdf#3854]
I am using htmltopdf library for creating PDF from dynamically generated html string. it is working fine with smaller html strings, but when html content is very large, library become fail to respond.

**Comment by PhilterPaper** [comment]
Can you give an example that demonstrates this problem? What is the cutoff point between "works" and "doesn't work"? Are you feeding wkHTMLtoPDF an entire page as one string? Is it possible to break it up into several smaller strings, or does that produce multiple PDFs? (I haven't used it in that manner)

**Comment by eldhotkuriakose** [comment]
Hi PhilterPaper  thanks for your quick replay, i am trying to create make pdf from html string it is created dynamically. i have tried by braking html strings to chunks of string but it creates multiple pdfs. i need a single file, that is why i am giving large string as input. sadly it is not working.

**Comment by PhilterPaper** [comment]
Can you tell us how large a string works, and how large fails? How many pages of PDF output? Perhaps you're running into a C++ or operating system memory limit. If that's the case, the only thing I can suggest is to break up the string into smaller strings, and glue together the resulting PDFs into one using a PDF utility. You will need to split it on chapters or some place where you don't mind it starting on a new page.

**Comment by Tomsgu** [comment]
Closing as there is no response from the author since March.
