### ISSUE TITLE
Strange grey bars on bottom and right-hand side of TextArea input

### ISSUE THREAD

**Issue by RossAWaddell** [wkhtmltopdf/wkhtmltopdf#3855]
All other aspects of my HTML to PDF conversion work fine, except for two TextArea inputs. Is there a reason why there are grey bars on the bottom and right-hand side?

**PDF**
![pdf_textarea](https://user-images.githubusercontent.com/29708900/37866326-9de213b2-2f5f-11e8-82e0-3670d943102f.png)

**HTML**
![html_textarea](https://user-images.githubusercontent.com/29708900/37866327-9def6882-2f5f-11e8-93fe-3a17cc065e58.png)

**Comment by RossAWaddell** [comment]
Turns out that even though the scrollbars are not visible in a browser (HTML), the conversion to PDF has them. Adding this to the textarea resolved it:

`style="overflow:hidden"`

**Comment by Tomsgu** [comment]
Closing as it seems to be resolved.
