### ISSUE TITLE
Inline Div Acting Blocks

### ISSUE THREAD

**Issue by abhishek6262** [wkhtmltopdf/wkhtmltopdf#3856]
Hello,

I'm trying to convert HTML to PDF and I'm facing a problem to align two div's vertically center. They are coming stacked over one-another just like these are blocks. I'm using Bootstrap version 3.3. As previewed in the attached image ("Da Manager", "Web Developer") is on one line and whereas ("Kashipur, India", "October 2017 - Present") line should be aligned vertically center but they're coming on the next line.

![capture4](https://user-images.githubusercontent.com/16699718/37999241-95eaf326-323f-11e8-8a8d-e6825a6f1228.JPG)

The next image attached is of wkhtmltoimage which performs well and aligns it vertically center.

![capture5](https://user-images.githubusercontent.com/16699718/37999295-d39cb5d8-323f-11e8-9774-cd56f73afd30.JPG)

Thanks.

**Comment by Tomsgu** [comment]
Without any html example is very hard to see the problem. Please feel free to re-open the issue if you can provide more information.
