### ISSUE TITLE
tbody row height

### ISSUE THREAD

**Issue by chipper95** [wkhtmltopdf/wkhtmltopdf#3862]
Hi.

I'm attempting to pdf a table that has rows in groups of two (surrounded by tbody elements), with some of the columns spanning both paired rows, and others appearing in each row. Example below.
<table>
     <tbody>
          <tr>
                 <td rowspan='2'>Test1</td>
                 <td>Test2</td>
                 <td rowspan='3'>Test3<br>Test4<br>Test5<br>Test6</td>
          </tr>
          <tr>
                 <td>Test7</td>
          </tr>
     </tbody>
</table>

When one of the spanned cells contains data that pushes the row height over what it normally is, only the second of the paired rows will increase in height on the pdf. Even with a css styling of 'height:50%' on both paired rows, the second will contain all of the added height (despite this not being the case when rendering the file in html).

Any help is appreciated.
Thanks.

**Comment by chipper95** [comment]
Yes. Downloaded the new build this morning, but I'm still seeing the issue.

**Comment by alloylab** [comment]
what os are you running? are you using the patched qt version?

**Comment by alloylab** [comment]
We are closing this out since we haven't heard from you. If you are still having this issue please feel free to re-open it. Thanks.
