### ISSUE TITLE
Can we convert  a html to a existing pdf file

### ISSUE THREAD

**Issue by kunluu** [wkhtmltopdf/wkhtmltopdf#3863]
convert the html into a existing pdf file added by the end.

(i am not good at English ,hope you understand my meaning)

**Comment by benedekh** [comment]
Hi @kunluu ,

What you could do is convert the HTML into a new PDF and then append both PDFs by a tool, e.g. [PDFtk](https://www.pdflabs.com/tools/pdftk-the-pdf-toolkit/).

**Comment by kunluu** [comment]
Thanks @benedekh
