### ISSUE TITLE
Drop X server run dependency

### ISSUE THREAD

**Issue by strk** [wkhtmltopdf/wkhtmltopdf#3865]
Is there any reason why wkhtmltopdf should depend on a running X server ?
I tend to think "no" (uninformed) so filing this ticket.
It's a very high dependency for a commandline tool ...

**Comment by hakimio** [comment]
Latest release works without it.

**Comment by PhilterPaper** [comment]
Does a Windows build _not_ require an X server, and a Linux/Unix build _does_? Perhaps there is something in a *nix library that assumes an X server (something common in the *nix universe), and might be coded around. At least, let's get straight on which builds require an X server and which don't.

**Comment by hakimio** [comment]
Version 0.12.4 works on linux without X server. I don't think windows version ever needed X server to run.

**Comment by macintoshplus** [comment]
I have the same problem, unable to run the wkhtmltopdf without X server on linux.

How To build without X server dependency ?

**Comment by hakimio** [comment]
@macintoshplus Just use prebuilt binary releases.

**Comment by macintoshplus** [comment]
Thanks, but I cannot install the package into debian 9. If possible, I prefer build a new version with the new library version.

The version with Qt5 do not have the patch for remove X11 dependency. But where is it?

If I use the X11 server, the generated PDF have the background and I cannot use it for stamp another PDF.

**Comment by hakimio** [comment]
@macintoshplus 
If you are not happy with the latest stable version on the [release page](https://github.com/wkhtmltopdf/wkhtmltopdf/releases), use the build instructions in [INSTALL](https://github.com/wkhtmltopdf/wkhtmltopdf/blob/master/INSTALL.md) file to compile the latest dev version.

**Comment by strk** [comment]
I'm using prebuilt binary releases (apt-get install wkhtmltopdf
in an Ubuntu 17.10 system) but they still have the dependency.

**Comment by macintoshplus** [comment]
@hakimio Thanks for your help for me.
How many time the static build can work without update need? This question is over the project status. No new version or news since two year, it's a long time and is not easy to replace an tool using in production.
If necessary, I can help but without the project manager it'is hard!

**Comment by macintoshplus** [comment]
@strk The prebuild is not into your distribution. You can drop the integrated build with the dependencies. Go to here: https://wkhtmltopdf.org/downloads.html
Download the version 32 or 64 bit and copy the content of the archive in your projet (or where you want).
For use it, call the binary with the full path.

**Comment by hakimio** [comment]
@strk That's because it's an old version in the ubuntu 17.10 repository. Use the the build available here on github.

**Comment by ashkulz** [comment]
The official builds don't have a dependency on X, distro packages have it. 0.12.5 will bring back the distro-specific builds via the `wkhtmltopdf/packaging` repository, you can download preview builds [here](https://builds.wkhtmltopdf.org/0.12.5-dev/).
