### ISSUE TITLE
How to deal with cors access？

### ISSUE THREAD

**Issue by bbhorse** [wkhtmltopdf/wkhtmltopdf#3868]
I have a local html，in html an ajax request need to access other server , i use wkhtmltopdf, but it's not work(because the cors.) , i need some help , thanks!

**Comment by hakimio** [comment]
Enable CORS in your server? That's not exactly wkhtmltopdf bug.

**Comment by alloylab** [comment]
@bbhorse did you resolve this?

**Comment by quakef4** [comment]
Hi,
Is possible disable or set "Access-Control-Allow-Origin" on request? I have same problem with local file.

**Comment by quakef4** [comment]
Hi,
Is possible disable or set "Access-Control-Allow-Origin" on request? I have same problem with local file. On browser access with CORS plugin. This set a request to Access-Control-Allow-Origin to " * " and it work fine. 

Thanks in advence
