### ISSUE TITLE
Option to cover watermark or background image in all pages.

### ISSUE THREAD

**Issue by sathi5a0** [wkhtmltopdf/wkhtmltopdf#3870]
Hi.
Is there any option to cover watermark or background image ever page of converted pdf, where given background image should be present in all the pages.

version : wkhtmltopdf 0.12.2.4 (with patched qt)
OS : Windows 10

It would be appreciated for your help
Thanks.

**Comment by metalshark** [comment]
Am currently using PDFTK to achieve this with the stamp tool after generating the PDF.

**Comment by alloylab** [comment]
We are closing this out since we haven't heard from you. If you are still having this issue please feel free to re-open it. Thanks.
