### ISSUE TITLE
CSS is not affecting generated PDF

### ISSUE THREAD

**Issue by tariq021** [wkhtmltopdf/wkhtmltopdf#3871]
I am using **OS: Ubuntu 16.04**. I have integrated this package in my laravel application. PDF is generating but no CSS affect on this generated file.

In **OS: windows**, Everything is working perfectly.

Here is original view

![screenshot-2018-4-4 industrial sourcing 4 0 with valeroo](https://user-images.githubusercontent.com/31202488/38303690-452a429a-37f6-11e8-8b23-b3ed1b166c4c.png)

Here is generated PDF
[mmm(4).pdf](https://github.com/wkhtmltopdf/wkhtmltopdf/files/1875385/mmm.4.pdf)

Color, Background color, font styling everything is removed. :-(

**Comment by tariq021** [comment]
I get the solution. CSS was affecting but color and background-color were not affecting the PDF. 
Just making all `color` and `background-color` properties `!important `works.

`p { color:grey !important; }`

Solved!

**Comment by Kaplan1984** [comment]
I also have this issue.
I'm not really satisfied with the solution because I'll have to write extra css rules.

OS: **Debian 9 (stretch)**
wkhtmltopdf: **0.12.3** (also tried 0.12.5)
