### ISSUE TITLE
Doesn't working with centos 7.4.1708 (version used 0.12.4)

### ISSUE THREAD

**Issue by lmanuel-exa** [wkhtmltopdf/wkhtmltopdf#3872]
Hello,

I have a problem wkhtml doesn't working with Centos 7.4.1708. I think that it's the openssl version the problem.
When I execute this command on Centos 7.2.1511 (openssl 1.0.1e) it's working:
  wkhtmltoimage http://google.com google.jpg
  Loading page (1/2)
  Rendering (2/2)                                                    
  Done

but when I execute this command on Centos 7.4.1708 (openssl 1.0.2k) doesn't working:
  wkhtmltoimage http://google.com google.jpg
  Loading page (1/2)
  QSslSocket: cannot resolve CRYPTO_num_locks                  ] 10%
  QSslSocket: cannot resolve CRYPTO_set_id_callback
  QSslSocket: cannot resolve CRYPTO_set_locking_callback
  QSslSocket: cannot resolve sk_free
  QSslSocket: cannot resolve sk_num
  QSslSocket: cannot resolve sk_pop_free
  QSslSocket: cannot resolve sk_value
  QSslSocket: cannot resolve SSL_library_init
  QSslSocket: cannot resolve SSL_load_error_strings
  QSslSocket: cannot resolve SSLv2_client_method
  QSslSocket: cannot resolve SSLv3_client_method
  QSslSocket: cannot resolve SSLv23_client_method
  QSslSocket: cannot resolve SSLv2_server_method
  QSslSocket: cannot resolve SSLv3_server_method
  QSslSocket: cannot resolve SSLv23_server_method
  QSslSocket: cannot resolve X509_STORE_CTX_get_chain
  QSslSocket: cannot resolve OPENSSL_add_all_algorithms_noconf
  QSslSocket: cannot resolve OPENSSL_add_all_algorithms_conf
  QSslSocket: cannot resolve SSLeay
  QSslSocket: cannot call unresolved function CRYPTO_num_locks
  QSslSocket: cannot call unresolved function CRYPTO_set_id_callback
  QSslSocket: cannot call unresolved function CRYPTO_set_locking_callback
  QSslSocket: cannot call unresolved function SSL_library_init
  QSslSocket: cannot call unresolved function SSLv23_client_method
  QSslSocket: cannot call unresolved function sk_num
  Segmentation fault (core dumped)

Can you help me ?

**Comment by hakimio** [comment]
Install older version of openssl which works with wkhtmltopdf?

**Comment by hakimio** [comment]
Older bug report: https://github.com/wkhtmltopdf/wkhtmltopdf/issues/3001

**Comment by ashkulz** [comment]
That will be changing from 0.12.5, see [wkhtmltopdf/packaging](https://github.com/wkhtmltopdf/packaging) and the [preview binaries for linux](https://builds.wkhtmltopdf.org/0.12.5-dev/).
