### ISSUE TITLE
Help for realease new version

### ISSUE THREAD

**Issue by macintoshplus** [wkhtmltopdf/wkhtmltopdf#3873]
Hi @ashkulz

I need wkhtmltopdf for debian 9 server with the headless option.

Actualy I use the version 0.12.1 but I cannot build the new version with the new jpeg and png library.
I have already work with Qt, C, C++ project and I have Linux Debian, Ubuntu and Windows environments for build if necessary.

Can you add me to the wkhtmltopdf org for help you to realease a new version working in the recent OS version ?

Thanks.

**Comment by ashkulz** [comment]
@macintoshplus: thanks for the offer! Can you test the packages I am building with the `wkhtmltopdf/packaging` repository, available [here](https://builds.wkhtmltopdf.org/0.12.5-dev/)? If you are willing to help in other areas of wkhtmltopdf as well, drop me a mail (it's in my profile).
