### ISSUE TITLE
High CPU and no PDF generated

### ISSUE THREAD

**Issue by lizhi1989** [wkhtmltopdf/wkhtmltopdf#3874]
When generating a html page from URL, which contain graph (highchart library), wkhtmltopdf is consuming nearly 100% CPU and is not generating the PDF. I have to kill it.
How to troubleshot?

**Comment by Obyri** [comment]
I am experiencing this issue to. I am using this on a server to generate pdf from cakephp rendered html. 
Every so often one of the output will fail with 100% cpu there is not log output it hangs during the percentage done output. There is no consistency to the issue. The same html page will render many times and then suddenly fail.

**Comment by alloylab** [comment]
What version are you running?

**Comment by alloylab** [comment]
We are closing this out since we haven't heard from you. If you are still having this issue please feel free to re-open it. Thanks.
