### ISSUE TITLE
Image is not displayed in server

### ISSUE THREAD

**Issue by jigarpancholi** [wkhtmltopdf/wkhtmltopdf#3877]
I have created a pdf file. In local, it is working properly and image is displayed in pdf. But in server image is not displayed. I have checked image path and it is perfect. I have attached screen shot which shows ```Warning: Failed to load 'image_path' (ignore)```.

Absolute path is like 'https://example.com/app/img/xyz.jpg'.
![question](https://user-images.githubusercontent.com/17808105/38768027-a9dc8d58-400a-11e8-9ce6-10f89c30f4e5.png)

**Comment by jigarpancholi** [comment]
I just came to know solution for this issue and it was my mistake. 
It was because my image was accessible directly in browser because ssl license was expired and browser throws an exception.
After that I checked by ```curl``` and I came to know.

**Comment by jigarpancholi** [comment]
Issue is only with ```https```. It is working fine with ```http``` url.

**Comment by jigarpancholi** [comment]
Tried but still getting same error.

**Comment by Tomsgu** [comment]
Is this working with wkhtmltopdf 0.12.5? What happens if you try `wget https://example.com/app/img/xyz.jpg`?

**Comment by hakimio** [comment]
SSL issue was fixed in 0.12.5.
