### ISSUE TITLE
Error while converting HTML to PDF

### ISSUE THREAD

**Issue by CTPLdev4** [wkhtmltopdf/wkhtmltopdf#3881]
I am getting the following error when trying to convert HTML to PDF:

**SetProcessDpiAwareness failed: "COM error 0x80070005  (Unknown error 0x0ffffffff80070005)"
Error: This version of wkhtmltopdf is build against an unpatched version of QT, and does not support more then one input document.
Exit with code 1, due to unknown error.**

I have already implemented the same in my previous project. But this is generating error here. What could be the possible reason?

I am using the following function:

`public bool HtmlToPdf(string Url, string pOutputPathwithName, string FileName, int margin, int pagesize, int Orientation, string exePath, string CustomMargin)
    {
        int returnCode = 0;
        string outputFolder = "";
        try
        {
            string outputFilename = "FILE" + "_" + DateTime.Now.ToString("yyyy-MM-dd-hh-mm-ss-fff") + ".PDF"; // assemble destination PDF file name
            string filename = FileName;
            Process p = new Process();
            p = new System.Diagnostics.Process();
            p.StartInfo.FileName = exePath;
            ////CTException.WriteDBLog("1", "Start- EXE Path ", exePath);
            //string switches = "--print-media-type ";
            string switches = "";

            switch (margin)
            {
                case 1:
                    switches += "--margin-top 1.27cm --margin-bottom 1.27cm --margin-right 1.27cm --margin-left 1.27cm ";
                    break;
                case 2:
                    switches += "--margin-top 1cm --margin-bottom 1cm --margin-right 1cm --margin-left 1cm ";
                    break;
                case 3:
                    switches += "--margin-top 1in --margin-bottom 1in --margin-right 0.75in --margin-left 0.75in ";
                    break;
                case 4:
                    switches += "--margin-top 1in --margin-bottom 1in --margin-right 2in --margin-left 2in ";
                    break;
                case 5:
                    switches += "--margin-top 1mm --margin-bottom 1mm --margin-right 1mm --margin-left 1mm ";
                    break;
                case 0:
                    {

                        string[] mMargin = CustomMargin.Split('~');
                        switches += "--margin-top " + mMargin[0] + "mm --margin-bottom " + mMargin[1] + "mm --margin-right " + mMargin[3] + "mm --margin-left " + mMargin[2] + "mm ";
                        break;
                    }
            }

            switch (pagesize)
            {
                case 1:
                    switches += "--page-size A4 ";
                    break;
                case 2:
                    switches += "--page-size Letter ";
                    break;
                case 3:
                    switches += "--page-size Legal ";
                    break;
                case 4:
                    switches += "--page-size Executive ";
                    break;
                case 5:
                    switches += "--page-size A4 ";
                    break;
                case 6:
                    switches += "--page-size A3 ";
                    break;
                case 7:
                    switches += "--page-size A5 ";
                    break;
            }
            //switches += "--page-width 1024px ";
            switch (Orientation)
            {
                case 1:
                    switches += "--orientation Portrait";
                    break;
                case 2:
                    switches += "--orientation Landscape";
                    break;
            }

            //switches += "--minimum-font-size 14 ";

            p.StartInfo.Arguments = switches + " " + Url + " " + filename;
            p.StartInfo.UseShellExecute = false;
            p.StartInfo.RedirectStandardOutput = true;
            p.StartInfo.RedirectStandardError = true;
            p.StartInfo.RedirectStandardInput = true;
            //////CTException.WriteDBLog("2", "Switches file info", p.StartInfo.FileName);
            FileInfo fileInfo = new FileInfo(p.StartInfo.FileName);
            p.StartInfo.WorkingDirectory = pOutputPathwithName;
            p.Start();
            ////CTException.WriteDBLog("3", "start", p.StartInfo.FileName);
            string output1 = p.StandardOutput.ReadToEnd();
            string errorOutput = p.StandardError.ReadToEnd();

            List<string> output = new List<string>();

            while (p.StandardOutput.Peek() > -1)
            {
                output.Add(p.StandardOutput.ReadLine());
            }

            while (p.StandardError.Peek() > -1)
            {
                output.Add(p.StandardError.ReadLine());
            }
            p.WaitForExit(60000);

            returnCode = p.ExitCode;
            p.Close();

            if ((returnCode == 0) || (returnCode == 2))
                outputFolder = outputFolder + outputFilename;
            else
            {
                CTException.WriteDBLog("Exception", "HtmlToPdf() " + returnCode, errorOutput);
                throw new Exception(errorOutput);
            }

        }
        catch (Exception ex)
        {
            CTException.WriteDBLog(strCodeFile, "HtmlToPdf()", ex.Message);
        }
        return (returnCode == 0 || returnCode == 2);
    }`

**Comment by hakimio** [comment]
This has nothing to do with wkhtmltopdf itself. It's windows related issue.

> Worth to mention that main reason why this error message comes is due to windows restriction of not being able to run GUI apps if the parent process is a service.
https://github.com/ariya/phantomjs/issues/14095

Pull request which fixed it for node-html-pdf:
https://github.com/marcbachmann/node-html-pdf/pull/295

**Comment by CTPLdev4** [comment]
I know it is a Windows issue. But what could be the possible solution to it?

**Comment by hakimio** [comment]
Don't run it as a service or spawn process detached?

**Comment by hakimio** [comment]
Or just use a wrapper -> https://github.com/codaxy/wkhtmltopdf
