### ISSUE TITLE
Command Error: )

### ISSUE THREAD

**Issue by lucasbflopes** [wkhtmltopdf/wkhtmltopdf#3884]
I'm using wkhtmltopdf in a RoR application and recently I've been having a problem when a single user tries to print a specific page; the others seem to be able to print just fine though. In addition, the problem only occurs in production. The error I got from the log is very plain and doesn't say much.  What is `Command Error: )` supposed to mean? I couldn't find an answer anywhere else.

```
RuntimeError (Failed to execute:
["/usr/local/bin/wkhtmltopdf", "-q", "--encoding", "UTF-8", "--orientation", "Portrait", "--page-size", "A4", "--margin-top", "20", "--margin-bottom", "15", "--header-html", "file:////tmp/wicked_header_pdf20180418-21430-k37394.html", "--footer-html", "file:////tmp/wicked_footer_pdf20180418-21430-1i1rfoi.html", "file:////tmp/wicked_pdf20180418-21430-1iuj7bw.html", "/tmp/wicked_pdf_generated_file20180418-21430-ebuat6.pdf"]
Error: PDF could not be generated!
 Command Error: ):
  app/controllers/application_controller.rb:46:in `set_current_usuario'
  /app/solides/shared/bundle/ruby/2.2.0/bin/unicorn:22:in `load'
  /app/solides/shared/bundle/ruby/2.2.0/bin/unicorn:22:in `<main>'
```

**Comment by hakimio** [comment]
Looks like an issue with either your 3rd party wrapper (wicked_pdf) or environment set-up (can the user running your perl script execute "/usr/local/bin/wkhtmltopdf"?).

**Comment by lucasbflopes** [comment]
@hakimio I don't know. It seems weird to me that it this issue only happens to occur with a particular document and just on the production server. There is no difference in setup aside OSes (I develop on mac and the server is linux).

**Comment by hakimio** [comment]
Can you manually run the command without the ruby wrapper? What output do you get?

**Comment by lucasbflopes** [comment]
The html files are generated at runtime so that the files used to compose the pdf, like `file:////tmp/wicked_header_pdf20180420-31485-1t0t18d.html`, do not exist on the disk. Is there a way to test it?

**Comment by hakimio** [comment]
I don't think the html files are the problem. Just use any other files.

**Comment by lucasbflopes** [comment]
The command works, but this is expected since the command is currently being ran several times a day on production.

**Comment by lucasbflopes** [comment]
I figure out what the problem was. There were some characters wkhtmltopdf wasn't capable of interpreting for some reason. I still don't know why it worked on mac but not on linux though. Anyway, I'm closing this issue.

**Comment by AdityaTiwari2102** [comment]
@lucasbflopes I'm facing the same kind of issue. Can you share your solution?
`RunTime Error: PDF could not be generated!`
