### ISSUE TITLE
Generic linux build for 0.12.2

### ISSUE THREAD

**Issue by maguba** [wkhtmltopdf/wkhtmltopdf#3885]
Version 0.12.2 doesn't have a generic build like wkhtmltox-0.12.2_linux-generic-amd64.tar.xz. Could it be made available? The links in the PDF are not working correct in the versions 0.12.4 e 0.12.3.

**Comment by ashkulz** [comment]
That's unlikely to ever happen, as it is an old version and the generic builds have their own issues (e.g. see #3001). Please create new issues for the exact problem you are facing.

**Comment by maguba** [comment]
Thanks for the answer. The problem is the links in the PDF that work in 0.12.2 and do not work in 0.12.4... without changing anything in the execution options between the versions #3894.
