### ISSUE TITLE
Binary releases for ARM64 platform

### ISSUE THREAD

**Issue by pavel-odintsov** [wkhtmltopdf/wkhtmltopdf#3886]
Hello!

Do you have any plans about ARM64/arch64 releases? It's rising server platform and would be nice to have them!

**Comment by ashkulz** [comment]
I'm open to making builds, but I don't have access to such machines. How do you cross-compile for it, and can it be run under qemu?

**Comment by pavel-odintsov** [comment]
Hello!

Thank you for fast response!

qemu in latest versions got pretty decent support for ARM64. Also, we use http://scaleway.com/ VMs for such purposes. They run native ARM64 and work fine.

**Comment by ashkulz** [comment]
Packages will need to be distro-specific, so which distros are commonly used? Also, not really sure how to use/set it up. I feel the discussion would better be handled in the [wkhtmltopdf/packaging](https://github.com/wkhtmltopdf/packaging) repository instead.

**Comment by MaitreDede** [comment]
Hi @ashkulz 

In my use case, I have RaspberryPi OS (raspbian) armhf and arm64, debian, ubuntu and alpine... either bare-metal or inside docker (with xvfb).
To answer #4088 : I would like to build pure raspberry pi clusters :)

**Comment by ashkulz** [comment]
@MaitreDede see wkhtmltopdf/packaging#66 -- an RC build with support for most common distros should complete in 2 hours or so.

**Comment by ashkulz** [comment]
Please see the [latest release](https://github.com/wkhtmltopdf/packaging/releases) which has packages for a lot of ARM64 targets. Please add a comment if you face any problems in using the packages :+1:

**Comment by ashkulz** [comment]
A release candidate for the **0.12.6** release is [now available for download](https://wkhtmltopdf.org/downloads.html#release-candidate), which should contain changes which possibly address this issue.

Would appreciate downloading the package and reporting back if any issues are encountered during testing. Assuming all goes well, I plan to release 0.12.6 on the 2-year anniversary of the previous release i.e. June 11, 2020.
