### ISSUE TITLE
Place above footer

### ISSUE THREAD

**Issue by Maofab** [wkhtmltopdf/wkhtmltopdf#3887]
Hello All and thank you in advance.
I have to do a bill. Maybe it will be on 1 or 2 pages. I can't know how many articles will be listed.I've made a footer which is on every page.
But I have to put informations always above the last footer.
I mean if I have one page and a few lines of text, informations have to be above the footer.
If I have 2 pages, informations have to be above the footer on the second page only.
So footer on all pages (that is ok) and informations just above the last footer.

[example_bill.txt](https://github.com/wkhtmltopdf/wkhtmltopdf/files/1928187/example_bill.txt)

Thanks a lot.
Fabien

**Comment by pcunha-lab** [comment]
I think this is not an issue.

Just place an absolute positioned div at the end of your document. It will be rendered only on the last page.

See if it helps: https://stackoverflow.com/questions/48829069/fixed-sticky-footer-for-print-only-for-last-page?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa

**Comment by Tomsgu** [comment]
Closing as there is no feedback. Feel free to comment if there is still an issue.
