### ISSUE TITLE
Running wkhtmltopfd as non root fails with core dump

### ISSUE THREAD

**Issue by kulbida** [wkhtmltopdf/wkhtmltopdf#3891]
This is basically it, running it as non privileged user crashes with
Trace/BPT trap (core dumped)                                 ] 10%

OS: OpenBSD

Please help to address. Thank you.

**Comment by alloylab** [comment]
what version of OpenBSD? what version of wkhtmltopdf? is patched QT?

**Comment by kulbida** [comment]
You can try to disable JavaScript in wkhtmltopdf. It helped to address an issue for me.

**Comment by Tomsgu** [comment]
Is this resolved than?

If not, can you please provide information that @alloylab asks?
