### ISSUE TITLE
Self compiled wkhtmltopdf sends wrong font query to fontconfig

### ISSUE THREAD

**Issue by mikehaertl** [wkhtmltopdf/wkhtmltopdf#3897]
I'm using a self-compiled version of wkhtmltopdf on Alpine, which is available here:

https://github.com/Surnet/docker-wkhtmltopdf

As I understand it, wkhtmltopdf uses fontconfig to resolve the CSS fonts into the fonts available on the system. It therefore sends a list of font names to fontconfig, depending on the CSS fonts.

But we encounter a weird issue: wkhtmltopdf always requests the same fonts from fontconfig, no matter which `font-family` is used in CSS.

More details can be found in the issue here, where I included debug output of fontconfig that I obtained with [FC_DEBUG=1](https://www.freedesktop.org/software/fontconfig/fontconfig-user.html):
https://github.com/Surnet/docker-wkhtmltopdf/issues/1

For comparison there's also the output for a precompiled version of wkhtmltopdf on Debian where the font query is fine.

Is there an obvious missing piece that could cause such a behavior?

**Comment by ashkulz** [comment]
Is it something specific to that docker image, or does it happen with other OSes?

**Comment by mikehaertl** [comment]
It's specific to that image. I need wkthmltopdf on Alpine and this version is the only one I could find.

wkhtmltopdf basically works - but it does not communicate correctly with fontconfig. The fonts are all available on the system and fontconfig could find them.

But wkhtmltopdf never includes any **Serif** or **Times New Roman** to the match string it sends to fontconfig.

**Comment by ashkulz** [comment]
Must be something about the way it is compiled, then. If you're using other distros, you can try the [resurrected distro-specific binaries](https://builds.wkhtmltopdf.org/0.12.5-dev/). I'd appreciate PRs for adding alpine support in [wkhtmltopdf/packaging](https://github.com/wkhtmltopdf/packaging) :smile:

**Comment by mikehaertl** [comment]
> Must be something about the way it is compiled, then.

Well, that's exactly what we try to figure out :). Any idea where to start looking or what could cause this is highly welcome. Also check the other issue where we already collected some information what we tried.

https://github.com/Surnet/docker-wkhtmltopdf/issues/1

**Comment by ashkulz** [comment]
It's exactly to handle stuff like this that I've created [wkhtmltopdf/packaging](https://github.com/wkhtmltopdf/packaging) -- don't want to mix up packaging/distro specific concerns over here. Not sure if I'll get time to look into it, though ... want to finish 0.12.5 first.

**Comment by mikehaertl** [comment]
Ok, so should I open an issue there instead? Then we can close this here.

**Comment by ashkulz** [comment]
Yep, let's discuss Alpine packaging over there.
