### ISSUE TITLE
Undesirable extra blank Page

### ISSUE THREAD

**Issue by ZAJDAN** [wkhtmltopdf/wkhtmltopdf#3899]
Hello,
I am using **phpwkhtmltopdf version 2.1.0**  with **wkhtmltopdf 0.12.2.1 (with patched qt)** and there I have the problem, that after each page is added one blank/empty page.
Probably it is problem in the wkhtmltopdf library. Do you have same experiences?
Thank You for any hint

**Comment by ashkulz** [comment]
Duplicate of #2279
