### ISSUE TITLE
wkhtmltopdf not compiling for Mac OS 10.12.6 (Sierra)

### ISSUE THREAD

**Issue by yukagi** [wkhtmltopdf/wkhtmltopdf#3902]
I'm trying to compile from source to see if the new version of Qt will resolve some rendering issues I'm having, but it's not compiling.

I'm trying to build with ```WKHTMLTOX_QT_CONFIG="remove:-openssl -no-openssl" scripts/build.py osx-cocoa-x86-64 -debug```

and it errors out with this:
```17 warnings generated.
make[2]: *** [release] Error 2
make[1]: *** [sub-WebKit-qt-QtWebKit-pro-make_default-ordered] Error 2
make: *** [sub-webkit-make_default-ordered] Error 2
make -j8
command failed: exit code 512
```

Any ideas where I should turn to next?

**Comment by ashkulz** [comment]
I'm currently working on a vagrant based build, see [wkhtmltopdf/packaging](https://github.com/wkhtmltopdf/packaging). Unfortunately, it's taking a bit of time as I'm trying to integrate [conan](https://conan.io/) to build the required dependencies -- which will help the Windows build as well.

Not sure what error you're getting, as the latest build [was successful](https://travis-ci.org/wkhtmltopdf/wkhtmltopdf/jobs/373154164) and it too [uses MacOS 10.12](https://docs.travis-ci.com/user/reference/osx/#Xcode-8.3).
