### ISSUE TITLE
data label of y axis only show one max label data in the highchart's line chart when the generated pdf file

### ISSUE THREAD

**Issue by dengyunbing** [wkhtmltopdf/wkhtmltopdf#3903]
we generate line chart in the html file using highchart lib, the y axis data label can show many lines number,
But when export to pdf with wkhtmltopdf, the y axis data label only show one max number, no other y axis label line numbers, you can see the difference between html.jpg and pdf.jpg in the attached files. 
![html](https://user-images.githubusercontent.com/38976551/39621456-711043d6-4fc1-11e8-944e-003721753608.jpg)
![pdf](https://user-images.githubusercontent.com/38976551/39621468-7c942d4e-4fc1-11e8-9946-0c6dbb751696.jpg)

**Comment by alloylab** [comment]
what os & version?

**Comment by alloylab** [comment]
We are closing this out since we haven't heard from you. If you are still having this issue please feel free to re-open it. Thanks.
