### ISSUE TITLE
crash at wkhtmltopdf_convert in QtCoreApplication

### ISSUE THREAD

**Issue by frankipl** [wkhtmltopdf/wkhtmltopdf#3904]
HI
I want to use wkhtmltopdf in my server application to generate pdf from html files.
I have encounteder very strange problem, my app is crashing when I'm settings QString in Singleton by using + sign instead of QString("%1").arg(my_string).
I have prepared example app available on Github it uses example pdf_c_api.c from
https://github.com/wkhtmltopdf/wkhtmltopdf
In file Zmienne.cpp I have variable (databasePath) initialized with + sign (app is crashing) and when I initialize it by QString.(arg) it is OK.
Second problem is that after pdf has been generated my app is using 100% of cpu, when I try to check what it is doing, its actually doing nothing:
`
strace -p 10753
strace: Process 10753 attached
restart_syscall(<... resuming interrupted poll ...>) = ? ERESTART_RESTARTBLOCK (Interrupted by signal)
`

My example is very basic, qt project, only converting html to pdf, it is available on github:
https://github.com/frankipl/pdf-test
I'm working on Linux 64Bit with Qt 5.10.1 and I'm using wkhtmltox-0.12.4_linux-generic-amd64.tar

I'm actually not sure what else can cause my app to crash, becaus when I added wkhtmltopdf to my real server application it is crashing all the time and I can't pin down where the problem is
`
1  __memmove_avx_unaligned_erms             memmove-vec-unaligned-erms.S 345  0x7ffff1cedf3f 
2  QString::reallocData(unsigned int, bool)                                   0x7ffff2db06d2 
3  QString::append(QString const&)                                            0x7ffff2db0ea4 
4  QString::operator+=                      qstring.h                    474  0x555555564727 
5  operator+                                qstring.h                    1341 0x55555556e3a2 
6  ??                                                                         0x7ffff53fcecc 
7  ??                                                                         0x7ffff5403842 
8  ??                                                                         0x7ffff5404305 
9  ??                                                                         0x7ffff5404c53 
10 ??                                                                         0x7ffff6e7f1a9 
11 ??                                                                         0x7ffff54182ff 
12 ??                                                                         0x7ffff6e7f1a9 
13 ??                                                                         0x7ffff6e858da 
14 ??                                                                         0x7ffff6e82a4b 
15 ??                                                                         0x7ffff66c4dec 
16 ??                                                                         0x7ffff66cafe5 
17 ??                                                                         0x7ffff6e6c00d 
18 ??                                                                         0x7ffff6e92cdb 
19 ??                                                                         0x7ffff6e93760 
20 ??                                                                         0x7ffff6e6f5a3 
21 ??                                                                         0x7ffff53e5b9f 
22 wkhtmltopdf_convert                                                        0x7ffff541320d 
23 PdfMgr::createPdf                        pdf-mgr.cpp                  57   0x555555595bb3 
24 ParkingServer::ParkingServer             parking-server.cpp           50   0x555555560aa7 
25 main                                     main.cpp                     41   0x555555560867 

`

Best Regards
Marek

**Comment by ashkulz** [comment]
I wouldn't recommend using wkhtmltopdf from a Qt application, as you've got two event loops in place. You're also using Qt 5 along with Qt 4 in the same binary, so it's best if you shell out to wkhtmlopdf.

**Comment by frankipl** [comment]
how about recompiling wkhtmltopdf with Qt 5 ?
