### ISSUE TITLE
page numbering in header/footer htmls with wkhtmltopdf issue

### ISSUE THREAD

**Issue by minhvuonghd** [wkhtmltopdf/wkhtmltopdf#3911]
I have code like wkhtmltopdf  help 

```html
<!doctype html>
  <html><head><script>
  function subst() {
      var vars = {};
      var query_strings_from_url = document.location.search.substring(1).split('&');
      for (var query_string in query_strings_from_url) {
          if (query_strings_from_url.hasOwnProperty(query_string)) {
              var temp_var = query_strings_from_url[query_string].split('=', 2);
              vars[temp_var[0]] = decodeURI(temp_var[1]);
          }
      }
      var css_selector_classes = ['page', 'frompage', 'topage', 'webpage', 'section', 'subsection', 'date', 'isodate', 'time', 'title', 'doctitle', 'sitepage', 'sitepages'];
      for (var css_class in css_selector_classes) {
          if (css_selector_classes.hasOwnProperty(css_class)) {
              var element = document.getElementsByClassName(css_selector_classes[css_class]);
              for (var j = 0; j < element.length; ++j) {
                  element[j].textContent = vars[css_selector_classes[css_class]];
              }
          }
      }
  }
  </script>
</head>
<body style="border:0; margin: 0;" onload="subst()">
  <table style="border-bottom: 1px solid black; width: 100%">
    <tr>
      <td class="section"></td>
      <td style="text-align:right">
        Page <span class="page"></span> of <span class="topage"></span>
      </td>
    </tr>
  </table>
  </body>

- </html>
```

BUT WHEN CONVERT PDF 

Page   **undefined**   of  **undefined**

i don't know   please help me. Thanks!

**Comment by ashkulz** [comment]
Can you please provide a complete testcase including all HTML/CSS files and command-line arguments?

**Comment by Tomsgu** [comment]
Closing as there is no response since May.

**Comment by Jacquers** [comment]
I'm getting this issue as well.

using the example html in the first post and just basic command-line usage, e.g.

wkhtmltopdf "C:\temp\sample.html" "C:\temp\sample.pdf"

Output:

C:\Program Files\wkhtmltopdf\bin>wkhtmltopdf.exe c:\temp\sample.html c:\temp\sample.pdf
Loading pages (1/6)
Counting pages (2/6)
Resolving links (4/6)
Loading headers and footers (5/6)
Printing pages (6/6)
Done

Sample file and output attached.

[sample.pdf](https://github.com/wkhtmltopdf/wkhtmltopdf/files/3417548/sample.pdf)

**Comment by Jacquers** [comment]
Figured it out.

The header needs to be a separate html file for this to work, then the numbering works. * Would be nice if it didn't need to be.

e.g. wkhtmltopdf.exe --header-html c:\temp\header.html c:\temp\report.html c:\temp\report.pdf

The other option is to call it with the header / footer arguments. 

e.g. wkhtmltopdf.exe --header-right "Page [page] of [toPage]" c:\temp\sample.html c:\temp\sample.pdf

From: https://wkhtmltopdf.org/usage/wkhtmltopdf.txt
