### ISSUE TITLE
CSS "page-break-..." property

### ISSUE THREAD

**Issue by Lex-90** [wkhtmltopdf/wkhtmltopdf#3913]
Hello,
I am using wkhtmltopdf to convert to PDF a single (large) html file. I noticed that the CSS "page-break-after" and the "page-break-before" properties are not rendered. Is supporting these properties a feature that you will add?
Thanks,
Alex

**Comment by hakimio** [comment]
I am using `page-break-after` and `page-break-inside` and they work just fine for me.

**Comment by alloylab** [comment]
@Lex-90 anymore info on this? What version are you running? patched qt version?

**Comment by alloylab** [comment]
We are closing this out since we haven't heard from you. If you are still having this issue please feel free to re-open it. Thanks.
