### ISSUE TITLE
0.13 - static binary linux amd64

### ISSUE THREAD

**Issue by andreaolivato** [wkhtmltopdf/wkhtmltopdf#3916]
Is there any way to have a static binary for amd64 on linux like for the stable version?

Otherwise I get the following error: 

`The switch --enable-external-links, is not support using unpatched qt, and will be ignored`

Alternatively, is there a way to build our own static binary on Centos? Tried running the building script but it only supports Ubuntu/Debian.

Many thanks

**Comment by ashkulz** [comment]
Nope, you can always use the distro-provided version -- that's effectively the 0.13 version.
