### ISSUE TITLE
Exit with code 1 due to network error: ContentNotFoundError

### ISSUE THREAD

**Issue by smartyjagadish** [wkhtmltopdf/wkhtmltopdf#3917]
Hi,

I am using this command. Can you please let me know what is the exact issue here. This error is coming 40% of times.

Client Says :{"source":"https://ph.via.com/itinerary/FMNPH30IK9RAZL","type":"url","uniqueId":"FMNPH30IK9RAZL","hasToc":false} for unique Id FMNPH30IK9RAZL
Got exception for unique Id FMNPH30IAW2RT6java.lang.RuntimeException: Process (/usr/local/bin/wkhtmltopdf --javascript-delay 1000 --page-size A4 --encoding utf-8 --print-media-type --image-quality 100 --load-error-handling ignore https://ph.via.com/itinerary/FMNPH30IAW2RT6/1&noPrice=true -) exited with status code 1:
Loading pages (1/6)
Warning: Failed to load https://d2r1yp2w7bby2u.cloudfront.net/js/a.js (ignore)
Counting pages (2/6)                                               
Resolving links (4/6)                                                       
Loading headers and footers (5/6)                                           
Printing pages (6/6)
Done                                                                      
Exit with code 1 due to network error: ContentNotFoundError

**Comment by gokulk16** [comment]
#2187 same issue. occurring many times, seriously in need of a  fix.

**Comment by smartyjagadish** [comment]
We are sending logo in html content. If that logo url is not accessible, At that time this error is coming. 
After we fixed that url, Issue fixed.

**Comment by alloylab** [comment]
I just tried it with 0.12.5 on OSX with the following command with no issue... attached is the result PDF

`wkhtmltopdf --javascript-delay 1000 --page-size A4 --encoding utf-8 --print-media-type --image-quality 100 --load-error-handling ignore "https://ph.via.com/itinerary/FMNPH30IAW2RT6/1&noPrice=true" test.pdf`

[test.pdf](https://github.com/wkhtmltopdf/wkhtmltopdf/files/2167714/test.pdf)

**Comment by alloylab** [comment]
what os and version are you running? is it patched QT?

**Comment by rainyman2012** [comment]
I had this problem before. and solve that like below.

![wkhtmltopdf](https://user-images.githubusercontent.com/9016471/82428191-66006180-9a9f-11ea-8314-bcc16379425d.png)

In the above example i had some "src" files and "url"s  that they refer to the static directory but the static directory didn't exist so wkhtmltopdf thrown me that error. for example:

src: url("file:///home/ehsan/Projects/Example/main/sib/**static**/WebYekan.eot");

and one more important thing i have to say is all the file paths in html files have to be an absolute path. do not use relative path at all. 

I hope this help you.
