### ISSUE TITLE
ProtocolUnknownError

### ISSUE THREAD

**Issue by devchacha** [wkhtmltopdf/wkhtmltopdf#3918]
Hello, I have issue got **code 1 due to network error: ProtocolUnknownError.**
I don't know how to fixed it cause I'm tried fixed everything on you all advice.
Please help ><  wkhtmltopdf version : 0.12.4
![capture](https://user-images.githubusercontent.com/38471605/40113542-03677706-5934-11e8-9d6a-7f4b4455ca18.JPG)

**In snappy.php**
![capture2](https://user-images.githubusercontent.com/38471605/40113718-93fea5be-5934-11e8-96fa-37c6338fd2ad.JPG)

**Comment by alloylab** [comment]
is this still an issue on on 0.12.5

**Comment by alloylab** [comment]
We are closing this out since we haven't heard from you. If you are still having this issue please feel free to re-open it. Thanks.

**Comment by devchacha** [comment]
Thank you so much, but now I decided to change to python

**Comment by ehtishamfaisal** [comment]
wkhtmltopdf: b'Exit with code 1 due to network error: ProtocolUnknownError\n'

**Comment by BenjaminHoegh** [comment]
same issue when called from python

**Comment by Sicos1977** [comment]
https://github.com/Sicos1977/ChromeHtmlToPdf
