### ISSUE TITLE
Header-html is not inserted at all

### ISSUE THREAD

**Issue by amra** [wkhtmltopdf/wkhtmltopdf#3919]
Wkhtmltopdf does not insert header, it just inserts footer only. 
Using `wkhtmltopdf 0.12.4 (with patched qt)`.

Command: `wkhtmltopdf --footer-html wk-footer.html --header-html wk-header.html wk-body.html wk-out.pdf`

Used files are attached in `test.zip`.
[test.zip](https://github.com/wkhtmltopdf/wkhtmltopdf/files/2010998/test.zip)

It's not possible to use other parameters, which insert header, because wkhtmltopdf is executed throw pandoc and there is just `header-html` and `footer-html` supported.

**Comment by hakimio** [comment]
You are missing `<!DOCTYPE html>` in your header and footer html.

**Comment by amra** [comment]
You are absolutely right!!! I tested that and it's working ;-)
It would be nice to add this information to the documentation.
