### ISSUE TITLE
The wkthmltopdf doesn't work in my project.

### ISSUE THREAD

**Issue by LDWX** [wkhtmltopdf/wkhtmltopdf#3924]
When I use static web page, the wkhtmltopdf work well.
But when I use fetch(a http request) in my project, I can only get a blank pdf file.

**Comment by ranadeepbhuyan** [comment]
@LDWX  this works for me, can you try to see if there is a delay in loading the webpage? it may time out.

**Comment by srisatyak** [comment]
I was also experiencing the same problem, Whem I was paasing a URL with parameters seperated by '&' it is not converting the page to pdf.

**Comment by alloylab** [comment]
What version?

**Comment by alloylab** [comment]
We are closing this out since we haven't heard from you. If you are still having this issue please feel free to re-open it. Thanks.
