### ISSUE TITLE
Javascript  give the wrong div height

### ISSUE THREAD

**Issue by vuongabc92** [wkhtmltopdf/wkhtmltopdf#3925]
Hi guys,

I'm currently facing a weird issue, I have tried many days to fix it but I can't.
For example I have a `<div>` and I want to get the div's height so I have a script: 
`document.getElementById('aaa').clientHeight`; (or in jquery `$('#aaa').height()`) but the div's height depends on the numbers of spacing in the div's content

`<div id="aaa">hahaha</div>`   ---> give 22px
`<div id="aaa">hahaha hihi</div>` ---> give 44px
`<div id="aaa">hahaha hihi hoho</div>` ---> give 66px

The html page displays on web browser is perfectly but when I generate to PDF I got the issue

it's weird right?
Someone please help me out!

Thanks a lot.

**Comment by alloylab** [comment]
We are closing this out since we haven't heard from you. If you are still having this issue please feel free to re-open it. Thanks.
