### ISSUE TITLE
Newest version generates cut-off PDF with same code and data

### ISSUE THREAD

**Issue by jmclulus** [wkhtmltopdf/wkhtmltopdf#3926]
Hello!  So, I've got an HTML page that is mostly tables and I'm having an issue where on one server we've got version 0.9.6 and with that version, the PDF looks perfect, aligned with the page... however with the EXACT same code and data, changing only the version of WKHTMLTOPDF to 0.12.4 causes the same code to generate a PDF with it's right side cut off... any ideas what I can do about this other than downgrade?

![wkhtmltopdf-v0 9 6](https://user-images.githubusercontent.com/33431251/40321606-723bdccc-5ce4-11e8-8377-843655108b19.PNG)
![wkhtmltopdf-v0 12 4](https://user-images.githubusercontent.com/33431251/40321610-741af5be-5ce4-11e8-893d-4b391e691bb2.PNG)

**Comment by alloylab** [comment]
We are closing this out since we haven't heard from you. If you are still having this issue please feel free to re-open it. Thanks.
