### ISSUE TITLE
10⁴ of the page is displayed as 10

### ISSUE THREAD

**Issue by x2009again** [wkhtmltopdf/wkhtmltopdf#3928]
Some characters cannot be displayed，like 10⁴

**Comment by PhilterPaper** [comment]
The superscript is missing? How is it defined in the original HTML: `<sup>4</sup>` or as a Unicode character such as `x2074`? If the latter, it's possible that the particular font file being used does not define superscripts.

**Comment by PhilterPaper** [comment]
Without knowing _how_ your HTML is trying to create the superscript, I can't begin to guess what's going on. Does this happen for all fonts you try it with, or just some?

**Comment by x2009again** [comment]
Really a font problem，I have solved it by using css:font-family: 'Open Sans', 'Helvetica Neue', Helvetica, Arial, sans-serif;
