### ISSUE TITLE
Any way to install the recent version of wkhtmltopdf in Ubuntu 14.04 server

### ISSUE THREAD

**Issue by gokulk16** [wkhtmltopdf/wkhtmltopdf#3929]
Is any ppa: or any repository to pick the version of `wkhtmltopdf` ?
any way to install with `apt-get `
Need v0.12.4 to be installed in ubuntu 14.04 server
`apt-get` way installs v0.12.0 (final), but need v0.12.4

**Comment by gokulk16** [comment]
@ashkulz can you please mention if any ways to install v0.12.4 in Ubuntu 14.04 by `apt-get`

**Comment by hakimio** [comment]
No, you can not install 0.12.4 via "apt-get" but you can just use pre-built binary distribution released here on github.

**Comment by gokulk16** [comment]
@hakimio yeah, tried installation with `wkhtmltox-0.12.4_linux-generic-amd64.tar.xz` but `./configure && make install` fails after extraction.

**Comment by gokulk16** [comment]
Thanks @hakimio @ashkulz .
` mv wkhtmltox/bin/wkhtmlto* /usr/bin `
This worked for me.

**Comment by giannidhooge** [comment]
@ashkulz Any reason why the `0.12.5` builds are removed from https://builds.wkhtmltopdf.org?

**Comment by ashkulz** [comment]
The final release is available from https://wkhtmltopdf.org/downloads.html

**Comment by oojacoboo** [comment]
```
wget https://downloads.wkhtmltopdf.org/0.12/0.12.5/wkhtmltox_0.12.5-1.stretch_amd64.deb \
    && dpkg -i ./wkhtmltox_0.12.5-1.stretch_amd64.deb \
    && apt-get install -f
```

```
Selecting previously unselected package wkhtmltox.
(Reading database ... 13172 files and directories currently installed.)
Preparing to unpack .../wkhtmltox_0.12.5-1.stretch_amd64.deb ...
Unpacking wkhtmltox (1:0.12.5-1.stretch) ...
dpkg-deb (subprocess): cannot copy archive member from './wkhtmltox_0.12.5-1.stretch_amd64.deb' to decompressor pipe: unexpected end of file or stream
dpkg-deb (subprocess): decompressing archive member: lzma error: unexpected end of input
dpkg-deb: error: subprocess <decompress> returned error exit status 2
dpkg: error processing archive ./wkhtmltox_0.12.5-1.stretch_amd64.deb (--install):
 cannot copy extracted data for './usr/local/lib/libwkhtmltox.so.0.12.5' to '/usr/local/lib/libwkhtmltox.so.0.12.5.dpkg-new': unexpected end of file or stream
Errors were encountered while processing:
 ./wkhtmltox_0.12.5-1.stretch_amd64.deb
```

**Comment by hakimio** [comment]
@oojacoboo Try 0.12.6 -> https://builds.wkhtmltopdf.org/0.12.6-dev/

**Comment by oojacoboo** [comment]
@hakimio I think I’m going to try PhantomJS first.  Maybe it’ll be more frustrating I don’t know, but wkhtmltopdf has been a nightmare with charting.

You can get something half-ass working with so many random issues.  It reminds me of working with Joomla 18 years ago.  You just fiddle with random shit until something works and then put a big alert to never touch it.

**Comment by hakimio** [comment]
@oojacoboo wkhtmltopdf has an old webkit engine. If you need a modern solution, go for [puppeteer](https://github.com/GoogleChrome/puppeteer).

**Comment by oojacoboo** [comment]
@hakimio, thanks.  This looks pretty good - will check it out!
