### ISSUE TITLE
issue with javascript date string parsing.

### ISSUE THREAD

**Issue by pgee70** [wkhtmltopdf/wkhtmltopdf#3931]
If you use javascript to render a date using a valid date string using the parsing constructor an invalid date is returned.
According the [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date) the date constructor:
var newDate = new Date('2018-01-01'); 
should work.
so with a test case: 

[Archive.zip](https://github.com/wkhtmltopdf/wkhtmltopdf/files/2042517/Archive.zip)

so using the test cases:
uname -v
Darwin Kernel Version 17.5.0: Fri Apr 13 19:32:32 PDT 2018; root:xnu-4570.51.2~1/RELEASE_X86_64
wkhtmltopdf --version
wkhtmltopdf 0.12.4 (with patched qt)
wkhtmltopdf test-works.html test-works.pdf
wkhtmltopdf does-not-work.html does-not-work.pdf

does-not-work.pdf shows an invalid date.

Hope this is helpful for the devs, or to someone else who has found that dates are not behaving as expected.  This error manifested for me in a high charts chart that did not print, and it took me several hours to pin down the issue.  When identified, the fix is easy.  Thought i would pass it along to help out.

Thanks for the project!

**Comment by hakimio** [comment]
From [MDN page](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/parse):

> Because of the variances in parsing of date strings, it is recommended to always manually parse strings as results are inconsistent, especially across different ECMAScript implementations where strings like "2015-10-12 12:00:00" may be parsed to as NaN, UTC or local timezone.
