### ISSUE TITLE
Error loading PDF when more than 40 pages

### ISSUE THREAD

**Issue by nemish-doshi** [wkhtmltopdf/wkhtmltopdf#3933]
Loading pages (1/6)
Warning: Received createRequest signal on a disposed ResourceObject's NetworkAccessManager. This might be an indication of an iframe taking too long to load.
Warning: Received createRequest signal on a disposed ResourceObject's NetworkAccessManager. This might be an indication of an iframe taking too long to load.
Counting pages (2/6)
Warning: Received createRequest signal on a disposed ResourceObject's NetworkAccessManager. This might be an indication of an iframe taking too long to load.
Warning: Received createRequest signal on a disposed ResourceObject's NetworkAccessManager. This might be an indication of an iframe taking too long to load.
Loading TOC (3/6)
Resolving links (4/6)
Loading headers and footers (5/6)
Printing pages (6/6)
Warning: Received createRequest signal on a disposed ResourceObject's NetworkAccessManager. This might be an indication of an iframe taking too long to load.
Warning: Received createRequest signal on a disposed ResourceObject's NetworkAccessManager. This might be an indication of an iframe taking too long to load.
Done
Exit with code 1 due to network error: ProtocolUnknownError

**Comment by nemish-doshi** [comment]
Hi Team,

We are using latest version 0.12.4.0

Thanks,
Nemish

**Comment by nemish-doshi** [comment]
Hi Team,

Any update on this issue?

Thanks,
Nemish

**Comment by PhilterPaper** [comment]
Being over 40 pages probably has very little to do with it. It sounds like it may be spending a lot of time loading external (offsite) resources, such as iframes, images, JS files, CSS files, etc. Is there a lot of Javascript code being processed? You might look at the several flags to increase time limits on processing JS and other things. I don't know if there are any flags specifically regarding iframes, which could be a problem if the other system is very slow to respond.

**Comment by nemish-doshi** [comment]
Hi Team,

We are loading many images in base64 format inside PDF and looks like few of the images are not getting loaded. HTML is generated properly but PDF generation is partial only.

Command which we are using is as below:

wkhtmltopdf.exe --header-html header.html --footer-html footer.html page pretoc.html toc --xsl-style-sheet styles.xsl posttoc.html output.pdf

Please see to it and let me know if you need any other input.

Thanks,
Nemish

**Comment by nemish-doshi** [comment]
Hi Team,

Issue got resolved after adding --javascript-delay 1000

So new command is as below:

wkhtmltopdf.exe --javascript-delay 1000 --header-html header.html --footer-html footer.html page pretoc.html toc --xsl-style-sheet styles.xsl posttoc.html output.pdf

Thanks,
Nemish
