### ISSUE TITLE
html. with 2 svg, one is not rendered

### ISSUE THREAD

**Issue by chris74a** [wkhtmltopdf/wkhtmltopdf#3934]
Hello,
 
I have a simple table with 2 svg. 
The html version render the 2 svg.

With wkhtmltopdf, the first is rendered, not the second one. The 2 svgs are existing, event the 2nd. https://localhost:44345/images/contract/ECPY-left.svg  returns 200 
I do not understand why the second one is not displayed.

Thanks

===Html Template

```

<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="initial-scale=1.0, user-scalable=no" />
  <title>CruiseContract</title>
</head>

<body>
  <table width="100%" border="0" cellspacing="0" cellpadding="0" style="font-family:'Arial', sans-serif; font-size: 14px;font-weight: normal;font-style: normal;
font-stretch: normal; line-height: normal; letter-spacing: normal; text-align: left; color: #24436f; margin:0 auto; width:1024px;">
    <thead>
      <tr>
        <td width="215px" style="padding-bottom:10px; padding-top:10px;"><a href="#"><img src="http://www.yotha.com/images/contract/yotha_logo.svg" alt="" /></a></td>

      </tr>
    </thead>
    <tbody>
      <tr>
        <td width="90px" valign="bottom"><img src="http://www.yotha.com/images/contract/ECPY-left.svg" height="900px" alt="" /></td>
      </tr>

    </tbody>
  </table>
  
</body>
</html>

```
====

**Comment by alloylab** [comment]
what os? what version? is it a patched qt version?

**Comment by Tomsgu** [comment]
Tried this on wkhtmltopdf 0.12.5 and it displays both. 
![wkhtmltopdf-test-case](https://user-images.githubusercontent.com/2694769/41482128-d4d30c76-70d4-11e8-9104-fda4799c5603.png)

**Comment by alloylab** [comment]
@Tomsgu just want to confirm that your issue is now resolved?

**Comment by Tomsgu** [comment]
@alloylab yes. I used the example provided by the author.
