### ISSUE TITLE
Feature request: specific CSS for vkhtmltopdf?

### ISSUE THREAD

**Issue by Darker** [wkhtmltopdf/wkhtmltopdf#3935]
In CSS, you can limit CSS styles for specific applications - for example you can remove link styles from print versions:
```
@media print {
    a {
       color: inherit;
       text-decoration: inherit;
   }
}
```
It would be neat to have something like that for vkhtmltopdf, for example:
```
@media pdf {
    /* hide form in pdf version */
    form.new-comment {
       display: none;
    }
}
```

**Comment by Darker** [comment]
I know there is no such media type. But my CSS hides link formating for print, but I don't want to hide them in PDF.

**Comment by ashkulz** [comment]
Use `--user-style-sheet` with your PDF specific CSS.
