### ISSUE TITLE
Server screen goes black

### ISSUE THREAD

**Issue by Dgallaher** [wkhtmltopdf/wkhtmltopdf#3941]
Hi
I have installed wkhtmltopdf 0.12.4 on 3 different windows server 2012 R2 servers

a few hours after using the software (normally during the night) my server screen becomes black and the only way to get it back is to do a hard reboot. I have this issue on 3 different servers. As a work around I set the servers to reboot nightly but ideally I would like to resolve the issue without the reboot.

**Comment by ashkulz** [comment]
Unrelated to wkhtmltopdf.

**Comment by Dgallaher** [comment]
the only servers that have this issue is the servers that have wkhtmltopdf

I had it on a 4th server and uninstalled wkhtmltopdf and the issue went away.

**Comment by ashkulz** [comment]
Correlation is not causation, can't help you unless you are able to prove that it happens due to wkhtmltopdf.

**Comment by Dgallaher** [comment]
denial is not resolution either,
is there any way to run this in debug or someway to generate a log file?
