### ISSUE TITLE
Pdf empty when use 'Segoe UI' font

### ISSUE THREAD

**Issue by mnesrine** [wkhtmltopdf/wkhtmltopdf#3943]
I had a strange problem when using wkhtmltopdf 0.12.4 (with patched qt) in Linux Ubuntu 16.04.4

If I use font-face 'Segeo UI', and the fonts is not available in the path defined in stylesheet,
the generated pdf does not contain a text and the pdf is empty (see attached issue_1.pdf).
In this case I noticed this warning
`Warning: Received createRequest signal on a disposed ResourceObject's NetworkAccessManager. This might be an indication of an iframe taking too long to load.`

However when I put the font in the good path, I had another issue of displaying columns
in the webpage (html) the columns are displaying one after the other in the same row (see attached html_page.png).
But in the pdf each column are displaying in one row it's take all the width (issue_2.pdf).

Notice that i had not this two issues when i use wkhtmltopdf 0.12.2.4

What are your impressions on it? 

[issue_1.pdf](https://github.com/wkhtmltopdf/wkhtmltopdf/files/2082142/issue_1.pdf)
[issue_2.pdf](https://github.com/wkhtmltopdf/wkhtmltopdf/files/2082144/issue_2.pdf)

![html_page](https://user-images.githubusercontent.com/25040416/41128033-c992c382-6aa4-11e8-86f7-29f54a1e9db7.png)

**Comment by alloylab** [comment]
is this an issue on 0.12.5?
