### ISSUE TITLE
Release a linux "generic" binary for 0.12.5

### ISSUE THREAD

**Issue by turicas** [wkhtmltopdf/wkhtmltopdf#3947]
Hi,
I'm maintaining a [wkhtmltopdf heroku buildpack](https://github.com/turicas/heroku-buildpack-wkhtmltopdf) and for the last version (0.12.4) I've used the Linux AMD64 generic binary, but this file is not available on the current release. Could you please provide it?

Thanks!

**Comment by ashkulz** [comment]
Please read the FAQ on why that's not possible.

**Comment by ashkulz** [comment]
For heroku, you can use the package for the underlying Ubuntu version (trusty/xenial) or extract the .deb package via `ar x` and `tar xf`.
