### ISSUE TITLE
Is it possible run wkhtmltopdf with multi threat processor mode

### ISSUE THREAD

**Issue by alexsaab** [wkhtmltopdf/wkhtmltopdf#3948]
Hi, 
I use wkhtmltopdf to generate PDF from HTML from PHP. I use for PDF generation 24 processor server. But when I generate PDF I saw that server use only one processor. Is it possiable generate 700-1000 pages PDF file (HTML also one file) in multiprocessor mode? 

Alex

**Comment by ashkulz** [comment]
Nope, it has to be laid out as a single page. yoy can split up HTML, run in parallel and combine using pdftk.
