### ISSUE TITLE
Font Rendering With Weird Artifacts

### ISSUE THREAD

**Issue by glenelkins1984** [wkhtmltopdf/wkhtmltopdf#3949]
Hi

I am using Lora-Regular font embedded into the CSS as WOFF and it looks perfectly fine on the screen but when I run through wkhtmltopdf some letters have strange artefacts on them.

Here is how it should look (how the browser shows it -Safari and Chrome on Mac):

![browser](https://user-images.githubusercontent.com/40242581/41362585-a5774f34-6f29-11e8-86f3-f683c3aa5dec.png)

This is how it looks from wkhtmltopdf, you can see there is some strange things going on with the font:

<img width="1010" alt="wk" src="https://user-images.githubusercontent.com/40242581/41362579-a0822de6-6f29-11e8-9582-dcaefb2e3929.png">

Running the following command on CentOS 7:

wkhtmltopdf -O landscape -B 0 -L 0 -R 0 -T 0 --page-width 481.27 -d 300 --page-height 346.86 --print-media-type --image-quality 100 --no-pdf-compression --javascript-delay 5000 https://www.example.com/test.html test.pdf

**Comment by alloylab** [comment]
@glenelkins1984 how did you install it? is it a patched QT version?

**Comment by miguelbaldi** [comment]
Same problem on fedora 28

**Comment by alloylab** [comment]
@miguelbaldi what version? how did you install it? is it a patched QT version?

**Comment by PhilterPaper** [comment]
Sounds like the same problem as #2022 and many other reports.
