### ISSUE TITLE
TOC font-size

### ISSUE THREAD

**Issue by marcrib** [wkhtmltopdf/wkhtmltopdf#3951]
Hi, I need change font-size in TOC
Global styling not working
```
* {
  font-size:8px !important;
}
```

**Comment by alloylab** [comment]
what os? what version? is it a patched qt version?

**Comment by halkosajtarevic** [comment]
@marcrib a global styling does only work if you specify it in your custom xsl. to start, you can `wkhtmltopdf --dump-default-toc-xsl > default.xsl` then set your styling in the xsl and after that, call wkhtmltopdf with your xsl specified `wkhtmltopdf toc --xsl-style-sheet default.xsl`

**Comment by marcrib** [comment]
Thanks @halkosajtarevic
