### ISSUE TITLE
Total Page [topage] is not correct with "toc", higher than actual number of pages 

### ISSUE THREAD

**Issue by rob215x** [wkhtmltopdf/wkhtmltopdf#3952]
First, I'd like to reference two other similar issues:
 #3889 
 #3831 

I've been using wkhtmltopdf for a long time on a client's web site. I tried several others for the particular client but wkhtmltopdf was the only one that didn't crash AND did exactly what I needed it to do. The client recently moved his site to a new server and I had to reinstall wkhtmltopdf.

Previously, I was using wkhtmltox-0.12.2.1_linux-centos6-amd64.rpm and it worked flawlessly since 2015.

Today, I installed wkhtmltox-0.12.5-1.centos7.x86_64.rpm and it works but the total pages is wrong. The PDF has 52 pages but page numbering is "## of 57". I realize this is a fairly complex PDF to generate, but as I said, it used to work accurately.

The command I'm using is: (paths are modified to protect the client)

  /path/to/wkhtmltopdf --disable-smart-shrinking --margin-left '15mm' --footer-center '[doctitle] - page [page] of [topage]' --page-size 'letter' --print-media-type cover 'https://path/to/cover.php' toc 'https://path/to/page-that-generates-catalog.php' '/path/to/print_catalog.pdf'

The catalog is public on the internet so you can see it [here](https://budgetvideo.com/pdf2/print_catalog20180613.pdf)

I'm using "page-break-before:always;" and "page-break-inside:avoid;" in my CSS but I tried it with a different stylesheet without those and I still got the same result. 

**Here's the interesting part!**
If I remove "toc" from my command, there is STILL a Table of Contents but my page total is now correct!! Example [here](https://budgetvideo.com/pdf2/print_catalog20180613b.pdf)

So, my guess is, depending on which version of the PDF viewer you have, the viewer is adding its own TOC which makes the page total incorrect if you include it in your command???

**Comment by ashkulz** [comment]
can you post the HTML/CSS somewhere? This could be a regression from the changes made for fixing #2711

**Comment by rob215x** [comment]
You can see the html/css source [here](https://budgetvideo.com/print-catalog-html)

Normally I don't use html tables for layout but in this case it was easier to handle the columns and page breaks with tables.

**Comment by rob215x** [comment]
Also, please note this is a live catalog and the client may add or remove products daily, which affects the total pages in the catalog. Today, the client asked me to adjust the font sizes in the CSS which brought the page count from 52 to 57. The two PDF links in my original post are date-specific copies that will not change over time.

**Comment by ashkulz** [comment]
Can you check results of PR #3962 available from https://builds.wkhtmltopdf.org/0.12.6-dev/ and let me know if it helps things?

**Comment by ashkulz** [comment]
@rob215x: please reopen if you still face an issue with the 0.12.6-dev builds.

**Comment by faheemhameed** [comment]
@ashkulz do we have a dev build for Mac OS X?

**Comment by ashkulz** [comment]
Yes, it's available for all platforms -- see https://builds.wkhtmltopdf.org and download the file with "macos-cocoa" in the name.

**Comment by faheemhameed** [comment]
OMG. Thanks. I had checked this page but missed it late last night.

**Comment by arjunsuresh** [comment]
I'm still having issue after using 12.6 dev version. Now, blank pages are inserted at end from pages 492-556 (actual content is only up to page 492) and TOC links are broken - they link to 556. Only difference between 12.5 and 12.6 is that blank pages are now coming at end.

**Comment by ashkulz** [comment]
A release candidate for the **0.12.6** release is [now available for download](https://wkhtmltopdf.org/downloads.html#release-candidate), which should contain changes which possibly address this issue.

Would appreciate downloading the package and reporting back if any issues are encountered during testing. Assuming all goes well, I plan to release 0.12.6 on the 2-year anniversary of the previous release i.e. June 11, 2020.

**Comment by arjunsuresh** [comment]
Actually this issue is still there (0.12.6 released version on Ubuntu 20.04). Blank pages coming at end of PDF. [Example](https://drive.google.com/file/d/1yLQ3jNb42UsQy28fQJ6Hg9x0W72cQXlv/view?usp=sharing)

In the image above mouse over in PDF is showing page number 357 and the printed page number is 384. Overall PDF has 651 pages on contents but 760 pages are printed, the rest being blank. The TOC printed page number is somehow including these blank pages too. Until page 289 everything is fine and then it slowly starts getting messy. Trying to debug has not resulted in anything yet.
