### ISSUE TITLE
TOC is not generated

### ISSUE THREAD

**Issue by mpazdnikova** [wkhtmltopdf/wkhtmltopdf#3953]
Hello,

I've encountered an issue with TOC generation on a new 0.12.5 version. 
Table of content is not generated at all when specifying toc parameter (with custom .xsl document or without it). 
The simplest way to reproduce:  ```wkhtmltopdf toc "result.html" "result.pdf"```
And the result.html is just:
```
<!DOCTYPE html>
<html lang="en">
<body>
  <div>
    <h1>Level 1</h1>
    <h2>Level 2</h2>
  </div>
</body>
</html>
```
Everything worked with  0.12.5 RC I've downloaded like a couple of weeks ago. 

One more thing: my initial document has footer with page numbers so the cover page is number 1 and the next page has number 3. It seems that table of contents is generated but is not drawn right. 

My OS is Windows 10 version 1709.

Thanks in advance for your help.

**Comment by ashkulz** [comment]
What is the content of my.xsl?

**Comment by mpazdnikova** [comment]
Oops, it seems my.xsl was really missing so please ignore the second part of my message about the error, I'm removing it from the message. No errors now, it's just not generated.

**Comment by ashkulz** [comment]
Can you attach the PDF with 0.12.5 final and RC with the HTML and command-line mentioned above?

**Comment by mpazdnikova** [comment]
Sure! 
[result_RC.pdf](https://github.com/wkhtmltopdf/wkhtmltopdf/files/2101963/result_RC.pdf)
[result_final.pdf](https://github.com/wkhtmltopdf/wkhtmltopdf/files/2101965/result_final.pdf)

**Comment by ashkulz** [comment]
Okay, can you tell me the exact RC -- was it 0.12.5-0.20180529.138.rc~37e9f91 or 0.12.5-0.20180604.140.rc~6f77c46? I suspect a regression due to changes in #2711

**Comment by mpazdnikova** [comment]
According to the installer name it was 0.12.5-0.20180529.138.rc... 
That's pity. I've decided to move to a newer version partially because of that fix.

**Comment by ashkulz** [comment]
Am traveling right now, will look into this after Monday...

**Comment by hakimio** [comment]
@ashkulz 
This seems like a major issue. Any idea when this might be fixed?

**Comment by ashkulz** [comment]
Mid next week.

**Comment by ashkulz** [comment]
Can you check results of PR #3962 available from https://builds.wkhtmltopdf.org/0.12.6-dev/ and let me know if it works?

**Comment by hakimio** [comment]
@ashkulz Yes, it seems to fix the issue.

**Comment by ashkulz** [comment]
Great, I'll try to get the final release out by first week of July or earlier.

**Comment by metasean** [comment]
@ashkulz - Out of curiosity is there an ETA for when this fix will be in an available MacOS Cocoa build?  (i.e. it looks like Windows and Linux users can just grab an appropriate alpha build, but there isn't an alpha build for MacOS)

**Comment by ashkulz** [comment]
There is an alpha build for macOS on the link posted above.

**Comment by lwchkg** [comment]
If 0.12.6 will not be released shortly, I think you should advise people to download 0.12.4 instead of 0.12.5 in the website.

**Comment by obrejla** [comment]
Hello @ashkulz, 
do you plan to release `0.12.6` with this fix soon? Because this bug is absolutely critical and I don't think that users will want to use older 0.12.4. Thanks a lot!

**Comment by luketarplin** [comment]
I would also like to see a 0.12.6 release to fix what is a critical regression for us. Also downgrading to 0.12.4 is not an option for us due to SSL v3 issues with that version.

**Comment by hakimio** [comment]
@luketarplin For now you can try the dev build linked above.

**Comment by luketarplin** [comment]
@hakimio Yes I know thanks, I was hoping that if a build of 0.12.6 was released I could get away without having to build from source myself as it seems an involved process when compared to just pulling the built package... I guess for now I will have no choice but to do that though.

**Comment by luketarplin** [comment]
@hakimio Ah sorry I had missed that, I'm already part of the way through a source build :( I'll try the dev binary next. Thanks

**Comment by smartman** [comment]
0.12.6-dev last build is half a year ago. Any plans to release it? It does not feel comfortable having dev versions in production system because TOC is not generated.

**Comment by hakimio** [comment]
@smartman this project doesn't seem to be supported anymore. Might be a good time to move to something like [Puppeteer](https://github.com/GoogleChrome/puppeteer) or Chrome Headless.

**Comment by gabbyfebriana-sc** [comment]
Hi @ashkulz just wondering if the 0.12.6 will be released anytime soon? We're really looking forward to use the TOC feature in a stable version. Thanks!

**Comment by ashkulz** [comment]
I'm hoping to have a `rc` build out this weekend and release it soon after that.

**Comment by toineKeistoer** [comment]
@ashkulz, any news on the new release?

**Comment by leonelgoncalves** [comment]
So if I understand correctly the TOC we'll need to find another way of generating the TOC?

**Comment by hakimio** [comment]
@leonelgoncalves No, just use 0.12.6-dev from https://builds.wkhtmltopdf.org/0.12.6-dev/

**Comment by sandergroen** [comment]
We are six months later and there is still no new version released. I know it is hard to release sooner because everyone is busy.
Using a dev build is not a proper solution because it is not stable yet and since there is no stable release there is no wrapper of version 0.12.6 for Ruby which I use in my projects.
Is there a some workaround for this issue to make get the TOC to work in version 0.12.5.0?

**Comment by hakimio** [comment]
No, if you have to use stable version, either use older 0.12.4 release or migrate to Puppeteer or WWW::Mechanize::Chrome.

**Comment by sandergroen** [comment]
@hakimio, Puppeteer is not an option since it has no support for cover pages and table of contents see [https://github.com/GoogleChrome/puppeteer/issues/1778](https://github.com/GoogleChrome/puppeteer/issues/1778). I'm not sure about WWW::Mechanize::Chrome I i haven't tried that yet.

**Comment by zearg** [comment]
@ashkulz Any news on potential release date of 0.12.6 ?

**Comment by ashkulz** [comment]
A release candidate for the **0.12.6** release is [now available for download](https://wkhtmltopdf.org/downloads.html#release-candidate), which should contain changes which possibly address this issue.

Would appreciate downloading the package and reporting back if any issues are encountered during testing. Assuming all goes well, I plan to release 0.12.6 on the 2-year anniversary of the previous release i.e. June 11, 2020.

**Comment by Jc-L** [comment]
0.12.6rc1 fixes the missing TOC issue (while testing windows 64bits builds 0.12.4, 0.12.5, 0.12.6rc1, only 0.12.5 had the bug).
