### ISSUE TITLE
RPM Package for rhel in ppc64le

### ISSUE THREAD

**Issue by eugenepptech** [wkhtmltopdf/wkhtmltopdf#3955]
Hi Sir,

Would like to have rpm package for rhel in ppc64le. Anyone can advice? Very appreciate.

**Comment by ashkulz** [comment]
@eugenepptech: please open a PR in [wkhtmltopdf/packaging](https://github.com/wkhtmltopdf/packaging) instead -- look at `build.yml` and create a `centos7-ppc64le` target which has `qemu: true` and uses `ppc64le/centos:7` as the base docker image. As I don't have the hardware, I can't really test the build even if it is successful.

**Comment by ashkulz** [comment]
I've created a package for pcc64le -- see https://builds.wkhtmltopdf.org but can't confirm that it works, as I don't have access to the hardware. Please submit a PR to the wkhtmltopdf/qt repository if you need to patch Qt to get it working.

**Comment by ashkulz** [comment]
Please see the [latest release](https://github.com/wkhtmltopdf/packaging/releases) which has packages for a lot of ppc64le targets. Please add a comment if you face any problems in using the packages :+1:

**Comment by ashkulz** [comment]
A release candidate for the **0.12.6** release is [now available for download](https://wkhtmltopdf.org/downloads.html#release-candidate), which should contain changes which possibly address this issue.

Would appreciate downloading the package and reporting back if any issues are encountered during testing. Assuming all goes well, I plan to release 0.12.6 on the 2-year anniversary of the previous release i.e. June 11, 2020.
