### ISSUE TITLE
Using custom header option for authorization

### ISSUE THREAD

**Issue by bartek4c** [wkhtmltopdf/wkhtmltopdf#3956]
How can I pass a bearer token into the tool using custom header option? I was trying to use
 --custom-header Authorization Bearer -token-
and
--custom-header Authorization "Bearer -token-"
but was successful in neither of them.

**Comment by ashkulz** [comment]
If I run `wkhtmltopdf  --custom-header Authorization "Bearer TOKEN" http://httpbin.org/bearer foo.pdf`, it generates a valid PDF.

**Comment by bartek4c** [comment]
Here is my test:
`wkhtmltopdf --custom-header Authorization "Bearer TOKEN" page "https://localhost:44382/controller/action/id" "C:\Users\My Name\AppData\Local\Temp\b77cf779-3356-454c-8125-2d75ab7bbda3.pdf"`
I point to a controller that does not require authorization and am trying to examine the request within the action method. Unfortunately the breakpoint doesn't get hit, instead, a pdf renders in my temp folder. The PDF has a message saying "AuthenticationFailed: IDX10803: Unable to obtain configuration from: 'https://login.microsoftonline.com/tfp///v2.0/.well-known/openid-configuration'."

On the other hand if I execute `wkhtmltopdf --custom-header Authorization "TOKEN" page "https://localhost:44382/controller/action/id" "C:\Users\My Name\AppData\Local\Temp\b77cf779-3356-454c-8125-2d75ab7bbda3.pdf"` the action in the controller executes and the TOKEN is mapped to the HeaderAuthorization field in the Request object as expected.

**Comment by ashkulz** [comment]
Whatever is running on `localhost` can't be debugged, sorry. If you can reproduce the error with a public site or testcase, please reopen the issue with details -- otherwise it is most likely an issue in your server-side stack.
