### ISSUE TITLE
Version 0.12.5 hooray - fixes https issues and others

### ISSUE THREAD

**Issue by Mike-Thomson** [wkhtmltopdf/wkhtmltopdf#3957]
The new release this month fixes problems generating PDFs with https sites. A whole pile of problems I was having are now resolved - great stuff. Thank you dev team

By the way - am developing in windows using NGINX and winNMP with deployment site a VPS running Ubuntu 18.04, nginx, php 7.2. Both environments work great with Whtmltophp and it is so much faster that using TCPDF library.

**Comment by ashkulz** [comment]
Thanks a lot for the feedback!
