### ISSUE TITLE
Footer missing - QPainter::begin(): Returned false Error: Unable to write to temp location

### ISSUE THREAD

**Issue by eherrera** [wkhtmltopdf/wkhtmltopdf#3959]
Hello,
I'm trying to generate a pdf with a php wrapper (KnpLabs/snappy) in windows and **the footer is missing**. 
**Logs:**
`Loading pages (1/6) [> ] 0% [======> ] 10% [==============================> ] 50% [============================================================] 100% QPainter::begin(): Returned false Error: Unable to write to temp location [======> ] 10% [==============================> ] 50% [============================================================] 100% Counting pages (2/6) [============================================================] Object 1 of 1 Resolving links (4/6) [============================================================] Object 1 of 1 Loading headers and footers (5/6) [======> ] 10% [==============================> ] 50% [============================================================] 100% Printing pages (6/6) [> ] Preparing [============================================================] Page 1 of 1 Done`
**Command:**
`"C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe" --lowquality --encoding "UTF-8" --load-error-handling "ignore" --load-media-error-handling "ignore" --footer-html "http://localhost/footer/footer_5b242af6e11f6.html" --footer-line "input.html" "output.pdf"`
**Version:**
wkhtmltox-0.12.4_msvc2015-win64.exe

From the command line it works fine.

**Comment by alloylab** [comment]
If it works fine with the command line then you need to reach out KnpLabs/snappy regarding the php wrapper

**Comment by eherrera** [comment]
OK. Thanks.
