### ISSUE TITLE
How I can avoid page break between two specific rows?

### ISSUE THREAD

**Issue by vedmant** [wkhtmltopdf/wkhtmltopdf#3960]
I have a table where two rows have linked data and I'd like to not have a page break between them. I tried to put that rows into separate `<tbody>` containers with `page-break-inside: avoid;` it didn't work, page-break-after or before doesn't work either.

I have html something like this:

    <table>
      <tbody>
      <tr>
        <td>1</td>
        <td>2</td>
        <td>3</td>
      </tr>
      
      <tr>
        <td>4</td>
        <td>5</td>
        <td>6</td>
      </tr>
      </tbody>
      
      <tbody>
      <tr>
        <td>1</td>
        <td>2</td>
        <td>3</td>
      </tr>
      
      <tr>
        <td>4</td>
        <td>5</td>
        <td>6</td>
      </tr>
      </tbody>
    </table>

**Comment by hakimio** [comment]
If it doesn't fit in one page, there is no way to force it to be in one page. Otherwise, it should work.

**Comment by vedmant** [comment]
@hakimio Yes, I have large table for 100+ pages, that's just an example, I have thousands of tbody blocks. The point is that it should not break this two rows inside `tbody` when I set `page-break-inside: avoid;` for `tbody`. But it breaks page between that rows anyway.

**Comment by Mindavi** [comment]
A solution to this is descibed [here](https://stackoverflow.com/questions/27753255/page-break-not-working-with-tbody-issue).

It basically comes down to tbody not being a block element, while page-break-inside only applies to block-level elements. There is a solution in there, but it isn't perfect.

**Comment by vedmant** [comment]
@Mindavi Thanks for example, but solution with tbody:after doesn't work (jsfiddle.net/abhitalks/DTcHh/3054 still breaks page on the middle of second tbody screencast.com/t/M5pzpMEIJq0j), changing tbody display to block will break the table layout.

**Comment by Mindavi** [comment]
I don't think an easy solution to this problem can be found. I've heard of some people that used javascript to get everything correct (but have no idea how or where anymore). I'd really love to see a solid solution for this as well.

**Comment by gowikel** [comment]
I had the same issue and I didn't found a good solution to break a table, so at the end, we ended with a for loop that counts the number of printed rows. Each x rows (defined by a parameter), it closes the table, creates a div with a break table and opens the table again.

It is dirty, but it worked.

**Comment by Swiftkilla** [comment]
I have hacked this before, try something like so:

Inside of your `<table>` add an extra div -
```<div class="force-pb">White space here caused by forced page break</div>```

and in you css -
```.force-pb { page-break-after: always; }```

I would like to note that I don't guarantee the output of the PDF as I'm certain each case will have it's different quirks.

**Comment by Tomsgu** [comment]
Please refer to an existing issue #2141 instead of creating a new one.

**Comment by vedmant** [comment]
Nothing really worked so far, tried all proposed solutions.

**Comment by Tomsgu** [comment]
Closing as this was discussed here many times. And #2141 is still open and verified. Please continue there.
