### ISSUE TITLE
Segmentation fault with 12.5 on using quotes in CSS

### ISSUE THREAD

**Issue by arjunsuresh** [wkhtmltopdf/wkhtmltopdf#3961]
Hi, when I use 
quotes: "\201C""\201D""\2018""\2019";
in my CSS the latest release is giving segmentation fault. 12.4 works fine here.

**Comment by ashkulz** [comment]
which OS/distro?

**Comment by arjunsuresh** [comment]
It is Ubuntu 18.04

**Comment by ashkulz** [comment]
Duplicate of #3945
