### ISSUE TITLE
wkhtmltopdf delete dotted pagination

### ISSUE THREAD

**Issue by wildnano** [wkhtmltopdf/wkhtmltopdf#3963]
Hi,

I have added this option to get pagination in my pdf file 
**$pdf->setOptions((['footer-center','[page]/[toPage]']));**
It works very well but I get something like that --1/ 2   ...  --2/2
I'd like to delete the both dotted lines. Can you help me. 
Thanks

**Comment by Tomsgu** [comment]
You should ask in a community around a wrapper you're using, not here.
