### ISSUE TITLE
Latest bleeding edge for Mac OS X

### ISSUE THREAD

**Issue by faheemhameed** [wkhtmltopdf/wkhtmltopdf#3967]
Dear there,

Just would like to know, when can I expect a downloadable package of wkhtmltopdf (latest bleeding edge with Qt 5.4.2) for Mac OS X?

Thanks for your great work.

We would like to make a pdf using css flex for our report.

Many thanks,
Hameed

**Comment by ashkulz** [comment]
I'm currently working on using Qt 5.11 and QtWebKit 5.212 alpha, so there's no ETA as such -- I'm trying for end of next month for a beta release.
