### ISSUE TITLE
ConnectionRefusedError in Docker

### ISSUE THREAD

**Issue by jvandenrym** [wkhtmltopdf/wkhtmltopdf#3968]
When generating the pdf in Docker I get the error:
`ConnectionRefusedError`

[Link to Dockerfile](https://gist.github.com/jvandenrym/647077fc3d2e1f3669da2abf03cad2f0)
[Link to docker-compose.yml](https://gist.github.com/jvandenrym/203038fc18932391708b8b4f393ab2e4)

`Use dnsmasq to point localhost to *.*.loc`

**Comment by Tomsgu** [comment]
Try to download your html by wget. Anyways you should go to the stackoverflow to ask similar issues. This doesn't seem to be connected with this library.

**Comment by jvandenrym** [comment]
Sure, it is a docker issue or a network issue (local/VM) which causes wkthmltopdf to  output  this error: ConnectionRefusedError
Would be great to have FAQ which addresses these issues. Stackoverflow is a great resource but not always a guarantee to a solution.

**Comment by Tomsgu** [comment]
To be more precise. In the same place where you execute the wkhtmltopdf binary try to instead download the html by wget command to see if there is any error. Most likely the error appear from the docker setup. 

But again this is not a docker neither drupal forum. StackOverflow is not a guarantee but it has far more guarantee than asking here.

**Comment by Gu3** [comment]
> When generating the pdf in Docker I get the error:
> `ConnectionRefusedError`
> 
> [Link to Dockerfile](https://gist.github.com/jvandenrym/647077fc3d2e1f3669da2abf03cad2f0)
> [Link to docker-compose.yml](https://gist.github.com/jvandenrym/203038fc18932391708b8b4f393ab2e4)
> 
> `Use dnsmasq to point localhost to *.*.loc`

Hi ! 
sorry to dig up the issue, but : do you have found a solution ?

**Comment by sh-ogawa** [comment]
Hi
Isn't the loading of css in a state where it cannot be referenced from the docker container?
When lending on docker-compose, the following relationship seems to hold.
×: http: //localhost/your.css
〇: http: // {docker-service-name} /your.css

I ran into the same problem, but the above solved it.
please confirm.
