### ISSUE TITLE
Renders incorrect width. Content does not use the whole page.

### ISSUE THREAD

**Issue by juhasim** [wkhtmltopdf/wkhtmltopdf#3969]
wkhtmltopdf 0.12.3 works fine.
wkhtmltopdf 0.12.4 and 0.12.5 do not fill the whole content area as expected.

See test.html below, and attached pdf files. The div sizes are exactly 1/4 and 1/1 of the A4 page size.

Ubuntu 18.04 LTS (64 bit)

```
<html>
  <head></head>
  <body>
    <div style="position: relative; top: 0mm; left: 0mm; width: 210mm; height: 297mm; background-color: lightblue"/>
    <div style="position: relative; top: 0mm; left: 0mm; width: 105mm; height: 148.5mm; background-color: blue"/>
  </body>
</html>
```

[test_0_12_5.pdf](https://github.com/wkhtmltopdf/wkhtmltopdf/files/2119418/test_0_12_5.pdf)
[test_0_12_3.pdf](https://github.com/wkhtmltopdf/wkhtmltopdf/files/2119419/test_0_12_3.pdf)
[test_0_12_4.pdf](https://github.com/wkhtmltopdf/wkhtmltopdf/files/2119420/test_0_12_4.pdf)

**Comment by hakimio** [comment]
Disable smart shrinking and set all margin command line arguments to 0.

**Comment by juhasim** [comment]
This also produces the incorrect output that takes two pages with 0.12.3 and 0.12.5 and does not fill the page with 0.12.4:
`wkhtmltopdf --disable-smart-shrinking --margin-top 0 --margin-left 0 --margin-bottom 0 --margin-right 0 test.html output.pdf`

The most annoying thing is that the behaviour changes from version to version and when our production server updates Ubuntu packages, wkhtmltopdf package update may break the printouts.

See attached pdf files.
[wkhtmltopdf-0.12.5.pdf](https://github.com/wkhtmltopdf/wkhtmltopdf/files/2122408/wkhtmltopdf-0.12.5.pdf)
[wkhtmltopdf 0.12.4.pdf](https://github.com/wkhtmltopdf/wkhtmltopdf/files/2122409/wkhtmltopdf.0.12.4.pdf)
[wkhtmltopdf-0.12.3.pdf](https://github.com/wkhtmltopdf/wkhtmltopdf/files/2122410/wkhtmltopdf-0.12.3.pdf)

**Comment by hakimio** [comment]
"body" element by default has 8px margin. You haven't removed that in your CSS.

**Comment by hakimio** [comment]
"body" element has 8px margin by default. You haven't removed it in your CSS.

**Comment by juhasim** [comment]
Thank, removing body margin fixes PDF with 0.12.5.
But it does not help with 0.12.3 and 0.12.4.

Leaving `--disable-smart-shrinking` out breaks the layout.

**Comment by hakimio** [comment]
I've tested with 0.12.5 and `--disable-smart-shrinking`. The pdf looks perfectly fine.
Why does it matter how it looks with 0.12.3 and 0.12.4?

**Comment by juhasim** [comment]
True, that those older versions cannot be fixed. Just for information that those behave differently.

Why does smart-shrinking override absolute widths and heights – and should that be considered as a bug in 0.12.5?

**Comment by Tomsgu** [comment]
Closing as it is resolved.

**Comment by Haxel0rd** [comment]
Hello
this "smart-shrinking" feature had cost me two days of debugging
and i was close to switching away from wkhtml2pdf. Please make
this behavior more clear in future versions. Other than that,
its nice this tool exists, thank you for developing it.
Cheers.
