### ISSUE TITLE
Wrong page number in TOC

### ISSUE THREAD

**Issue by arjunsuresh** [wkhtmltopdf/wkhtmltopdf#3971]
Hi, I'm trying to compile HTML to PDF and in actual there are 492 pages. But in TOC it reports 556 pages and the page numbers in TOC are wrong from about page number 283 (till then it is perfect). From 283 onwards, after each new section page number is getting additional increments and final page number becomes 556 instead of 283. The issue is happening on Ubuntu 18.04 for version 12.4 but also happens on 12.5

wkhtmltox-0.12.4_linux-generic-amd64/wkhtmltox/bin/wkhtmltopdf --javascript-delay 1650000 -T 20mm -B 20mm --header-html header.html --header-spacing 3  --footer-spacing 6 --footer-html footer.html   --title "Book" --no-stop-slow-scripts   --load-error-handling ignore --disable-toc-back-links  --debug-javascript toc --disable-toc-links  1-20e.html 1-20e.pdf
Loading pages (1/6)
Counting pages (2/6)                                               
Loading TOC (3/6)                                                           
Resolving links (4/6)                                              
Loading headers and footers (5/6)                                           
Printing pages (6/6)                                               
[====================================================>       ] Page 492 of 556

**Comment by Tomsgu** [comment]
Looks like a dup of #3952.

**Comment by arjunsuresh** [comment]
Thanks :+1:  Trying the Dev version 12.6 fixed it, but created blank pages from page number 493-556. This is not a problem for me though.

**Comment by Tomsgu** [comment]
Great, please refer to the duplicated issue when there is still a problem.
