### ISSUE TITLE
The switch --disable-smart-shrinking, is not support using unpatched qt, and will be ignored

### ISSUE THREAD

**Issue by faheemhameed** [wkhtmltopdf/wkhtmltopdf#3972]
Hi there,

I am using the version: wkhtmltopdf 0.13.0-alpha-7b36694

When I try to run the following: 

wkhtmltopdf.sh --disable-smart-shrinking --dpi 75 test.html test.pdf

Content of wkhtmltopdf.sh
`xvfb-run -a -s "-screen 0 1920x1200x24" wkhtmltopdf "$@"`

I get the following error:

> The switch --disable-smart-shrinking, is not support using unpatched qt, and will be ignored.

Do we have the patched qt version of  wkhtmltopdf 0.13.0-alpha-7b36694 ?

I am trying to use --disable-smart-shrinking as the A4 size css content (width: 21cm) does fill the whole width of the page. It fills around 75% of the page.

This version does works well with the css flex though.

Please help!!

Many thanks,
Hameed

**Comment by Tomsgu** [comment]
How did you install the wkhtmltopdf? What OS do you have?

**Comment by faheemhameed** [comment]
I am using Centos 7. 

I have downloaded this from the download page:

https://wkhtmltopdf.org/downloads.html

https://bitbucket.org/wkhtmltopdf/wkhtmltopdf/downloads/wkhtmltox-0.13.0-alpha-7b36694_linux-centos7-amd64.rpm

Thanks..

**Comment by Tomsgu** [comment]
According to [this](https://github.com/wkhtmltopdf/wkhtmltopdf/blob/0.13/README.md) it seems that there is no 0.13.0-alpha with patched qt.

**Comment by faheemhameed** [comment]
Also

> The switch --header-html, is not support using unpatched qt, and will be ignored.The switch --footer-html, is not support using unpatched qt, and will be ignored.Loading page (1/2)

This means the unpatched qt version basically not usable.

How can I patch wkhtmltopdf with qt easily? Are there simple steps?

**Comment by ashkulz** [comment]
From the download page, with respect to the 0.13 builds:

>  Please note that this is a work-in-progress and **not all the features have been ported to it yet**, so do not expect any support for any bugs you may encounter.

**Comment by faheemhameed** [comment]
Noted well. Thanks.
