### ISSUE TITLE
Getting page related details in the main content instead of header / footer

### ISSUE THREAD

**Issue by faheemhameed** [wkhtmltopdf/wkhtmltopdf#3973]
Hi there,

Is it possible at all to get the page number, total pages etc in the main template html instead of header / footer html?

Thanks.

**Comment by Tomsgu** [comment]
Please ask e.g. on stackoverflow. This is an issue tracker for improving a wkhtmltopdf. 
What I found in 2 minutes in google: 
https://stackoverflow.com/a/20317775/3422586
https://stackoverflow.com/a/16651296/3422586
