### ISSUE TITLE
Characters within table grids unexpectedly overflowing

### ISSUE THREAD

**Issue by FrancoBor** [wkhtmltopdf/wkhtmltopdf#3979]
First of all, wanna say thank you so much!

Any idea why rendering with wkhtmltopdf the enclosed (zipped) 
"testo1.htm" gave me slightly different result than the same file rendered by any browser?
See the enclosed screenshots.
Am i missing any important parameter?

[testo1.zip](https://github.com/wkhtmltopdf/wkhtmltopdf/files/2135758/testo1.zip)
![wkhtmltopdf](https://user-images.githubusercontent.com/40590481/41892714-7406ac66-7919-11e8-904b-3740e5a91400.jpg)
![firefox](https://user-images.githubusercontent.com/40590481/41892715-742ad79e-7919-11e8-8f61-efbf54661cb9.jpg)
![chrome](https://user-images.githubusercontent.com/40590481/41892716-745028be-7919-11e8-8aee-7457a4a9f55c.jpg)
![ie](https://user-images.githubusercontent.com/40590481/41892717-7475f5da-7919-11e8-896e-7d97284fa3bd.jpg)

Thank you again
Franco

**Comment by FrancoBor** [comment]
Sorry, forgot to mention:
Version: wkhtmltopdf 0.12.5 (with patched qt)
O.S.: win7

**Comment by Tomsgu** [comment]
Hmm strange thing is that I have the same bad result in chromium (archlinux) as well. So I would bet that it's related with your html.
![2018-06-29-155530_3600x1080_scrot](https://user-images.githubusercontent.com/2694769/42096269-19c16356-7bb5-11e8-80ef-e0b348e47b92.png)

**Comment by halkosajtarevic** [comment]
it seems that the internal QT-WebKit implementation uses default `box-sizing: border-box` so 50px is too small for your Quantita-column (it is 61px wide) - try changing the column width

**Comment by FrancoBor** [comment]
Sadly i have no control over the html and/or xml+xsl code. I just need to render it in pdf as cleanly as i can.
The strange thing is that all 4 major windows browsers render it perfectly (see images above)
Thank you anyway, guys!
Take care :-)
