### ISSUE TITLE
Javascript not executing on CentOS

### ISSUE THREAD

**Issue by kundansharma7** [wkhtmltopdf/wkhtmltopdf#3984]
I want to execute javascript code before exporting to pdf. When I execute the code on Ubuntu, its working fine but on CentOS , javascript is running when the page is being previewed in the broswer,but doesn't run when i download the PDF file (on the server).

I am also using 'javascript-delay': "15000".
But it doesn't work.

I am using the following version of the library in my local system (Ubuntu 16.10). Using this version, I am able to generate proper PDF file.
> wkhtmltopdf 0.12.3.2

But for centos, the javascript is not being executed before PDF export.
The following version is available:
> wkhtmltopdf 0.12.3 (with patched qt)

**Comment by Tomsgu** [comment]
There is already 0.12.5 version. Is it happening in this one as well?

**Comment by kundansharma7** [comment]
@Tomsgu @Tomsgu ok I will try to install that package. But, I am using Ubuntu 16.10. And when I am trying to install wkhtmltopdf the latest version is 0.12.3.

**Comment by alloylab** [comment]
@kundansharma7 download the last version from here, https://wkhtmltopdf.org/downloads.html

**Comment by Tomsgu** [comment]
@kundansharma7 any update on this? Minimal test case is needed if the issue still persists.

**Comment by Tomsgu** [comment]
Closing as there is no feedback. Please re-open if you can provide minimal test case, so we can reproduce the issue.
