### ISSUE TITLE
Keeping Image Aspect Ratio

### ISSUE THREAD

**Issue by YuliG42** [wkhtmltopdf/wkhtmltopdf#3985]
Hi,

Sorry, I'm fairly new to this, so I am not sure if this is an issue or if I am missing something.
I have an HTML with Titles and Pictures and I am trying to render it into a sensible PDF which breaks the pages in a considerate manner.

In the HTML I use
`.AttImage{height:948px; width: 646px; object-fit: contain; vertical-align: top;}
`
And the image is rendered properly, but when I use wkhtmltopdf the image is stretched into the height and width specified.

This is the CMD line I use is simple and without any parameters but the source HTML and the destination PDF.

My mkhtmltopdf version is: wkhtmltopdf 0.12.5 (with patched qt)

I am attaching the original HTML and the printed PDF and the two images (they just need to be in the same place as the html).
[Image 1](https://user-images.githubusercontent.com/40653351/42015983-55e9b8dc-7ab2-11e8-98a0-80fc22545ff3.JPG)
[Image 2](https://user-images.githubusercontent.com/40653351/42015984-560f3e68-7ab2-11e8-90ea-86928535fa01.JPG)
[PDFReport.pdf](https://github.com/wkhtmltopdf/wkhtmltopdf/files/2143987/PDFReport.pdf)
[HTMLToPrint.txt](https://github.com/wkhtmltopdf/wkhtmltopdf/files/2144005/HTMLToPrint.txt)

Am I doing something wrong here? I need the images to keep the scale and fit either the height or the width to the dimensions specified.

**Comment by PhilterPaper** [comment]
If you give the height **and** width of an image, both a browser and wkHTMLtoPDF should stretch it to those dimensions. If the ratio doesn't match the original aspect ratio, the image will be distorted. If you're trying to **scale** up (or down) and image so that its height **or** width matches the given dimension (but preserve its aspect ratio), that's something else. Is that what you're trying to do?

**Comment by YuliG42** [comment]
Hi @PhilterPaper ,
Thanks so much for taking the time!
I am working on Chrome running on a fairly new computer. And indeed I am always scaling down so the max-height/max-width did the trick of keeping the aspect ratio.
Unfortunately the contain does not work, I find some of the pictures smaller in width and height than the containing div, and I know for a fact that they are larger than the div. But the result is close enough to what I need so I am not going to put any more time into it.

Thanks again!!
Yuli.

**Comment by cpbotha** [comment]
The root cause here is that wkhtmltopdf simply does not support the `object-fit` CSS property, see for example https://github.com/mileszs/wicked_pdf/issues/686
