### ISSUE TITLE
Code block displayed with scrollbar in PDF

### ISSUE THREAD

**Issue by mbound** [wkhtmltopdf/wkhtmltopdf#3986]
0.12.5 appears to render code blocks with a scrollbar showing in the PDF and the overflowing text hidden, which makes it unreadable. 
In 0.12.4 the same file wraps the overflowing text instead (correct behaviour). 
Or is there an option to configure this behaviour?

**Comment by Tomsgu** [comment]
Similar issues #3855 #2538 #3936. Please try to search first before opening a new issue. Without any example it's hard to see.

**Comment by SDP190** [comment]
I have the same problem too, While similar issues was already referenced, they was for earliar versions, and was fixed at that time, but now the problem started again with current version, so @Tomsgu why close issue?

**Comment by Tomsgu** [comment]
#2538, #3491 #3939 doesn't seem to be fixed...

Do you think it make sense to have multiple duplicates of one issue and maintain all of them? Especially with poor details (no example, html, os specification).
