### ISSUE TITLE
page size in Wkhtmltopdf

### ISSUE THREAD

**Issue by hashmatkhattak** [wkhtmltopdf/wkhtmltopdf#3992]
I want to create pdf file with page size(5x5) from html using Wkhtmltopdf in laravel 5.4. 
How i can do? 
plz guide me thanks

**Comment by Tomsgu** [comment]
Please try to ask in stackoverflow. This is an issue tracker. And this project has nothing to do with Laravel in addition. You should look if there is any wrapper.
