### ISSUE TITLE
v0.12.5 - Windows 10 x64 - Can't create ToC.

### ISSUE THREAD

**Issue by arieradle** [wkhtmltopdf/wkhtmltopdf#3993]
v0.12.5 - Windows 10 x64 - EXE installer

Can't create ToC.

Not observed in v0.12.4

**Comment by Tomsgu** [comment]
Can you provide a minimal example and command you're running? 
What is the exact issue?

**Comment by arieradle** [comment]
The command line is `wkhtmltopdf toc test.html test.pdf`

Take any HTML example with that contains <h?> elements

**Comment by alloylab** [comment]
@arieradle can you attached the test.html file?

**Comment by Tomsgu** [comment]
Duplicate of #3953, please use the dev build until there is final release of 0.12.6

**Comment by ashkulz** [comment]
A release candidate for the **0.12.6** release is [now available for download](https://wkhtmltopdf.org/downloads.html#release-candidate), which should contain changes which possibly address this issue.

Would appreciate downloading the package and reporting back if any issues are encountered during testing. Assuming all goes well, I plan to release 0.12.6 on the 2-year anniversary of the previous release i.e. June 11, 2020.
