### ISSUE TITLE
Background colour stops with the content

### ISSUE THREAD

**Issue by angelo-moreira** [wkhtmltopdf/wkhtmltopdf#3994]
I am trying to convert an HTML to a PDF document with wkhtmltopdf.

Command I am running is `wkhtmltopdf ./test.html test.pdf`

Software version:
```
    wkhtmltopdf -V
    wkhtmltopdf 0.12.5 (with patched qt)
```
The content is dynamic therefore I don't really know where it will end.

Unfortunately when the content renders to the second page the background stops with the content.

HTML below, any help would be fully appreciated and make an old developer happy after struggling so much :)

```
    <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
     "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
    <html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    
    <head>
      <title>Testing PDF</title>
    
      <link href="https://fonts.googleapis.com/css?family=Lato:400,700" rel="stylesheet">
    
      <style>
        html {
          height: 100%;
          background: #f3f8fb;
        }
    
        body {
          font-family: "Lato", sans-serif;
          color: black;
          background: #f3f8fb;
        }
      </style>
    </head>
    
    <body>
    
      <p>This is a test with lots of dynamic content</p>
      <p>This is a test with lots of dynamic content</p>
      <p>This is a test with lots of dynamic content</p>
      <p>This is a test with lots of dynamic content</p>
      <p>This is a test with lots of dynamic content</p>
      <p>This is a test with lots of dynamic content</p>
      <p>This is a test with lots of dynamic content</p>
      <p>This is a test with lots of dynamic content</p>
      <p>This is a test with lots of dynamic content</p>
      <p>This is a test with lots of dynamic content</p>
      <p>This is a test with lots of dynamic content</p>
      <p>This is a test with lots of dynamic content</p>
      <p>This is a test with lots of dynamic content</p>
      <p>This is a test with lots of dynamic content</p>
      <p>This is a test with lots of dynamic content</p>
      <p>This is a test with lots of dynamic content</p>
      <p>This is a test with lots of dynamic content</p>
      <p>This is a test with lots of dynamic content</p>
      <p>This is a test with lots of dynamic content</p>
      <p>This is a test with lots of dynamic content</p>
      <p>This is a test with lots of dynamic content</p>
      <p>This is a test with lots of dynamic content</p>
      <p>This is a test with lots of dynamic content</p>
      <p>This is a test with lots of dynamic content</p>
      <p>This is a test with lots of dynamic content</p>
      <p>This is a test with lots of dynamic content</p>
      <p>This is a test with lots of dynamic content</p>
      <p>This is a test with lots of dynamic content</p>
      <p>This is a test with lots of dynamic content</p>
      <p>This is a test with lots of dynamic content</p>
      <p>This is a test with lots of dynamic content</p>
      <p>This is a test with lots of dynamic content</p>
      <p>This is a test with lots of dynamic content</p>
      <p>This is a test with lots of dynamic content</p>
      <p>This is a test with lots of dynamic content</p>
      <p>This is a test with lots of dynamic content</p>
      <p>This is a test with lots of dynamic content</p>
      <p>This is a test with lots of dynamic content</p>
      <p>This is a test with lots of dynamic content</p>
      <p>This is a test with lots of dynamic content</p>
      <p>This is a test with lots of dynamic content</p>
    
    
    </body>
    
    </html>
```

**Comment by PhilterPaper** [comment]
If I understand you, you're saying that when the output text (and document body) end halfway down the second page, so does the body's background color? And you'd like to keep the background color going down to the end of the page? 

Short of printing on colored paper stock :), you might look at HTML and CSS (and maybe JS) for "column balancing" tricks to keep columns of equal height. Maybe something from there could be used to force a page to full media height, even if the content ends early. You've got to find a way to convince the rendering engine that document content goes all the way to the bottom of each page, without causing spillover onto an empty page. If it's OK to use an external utility to crop off an empty end page, you might add a full page worth of empty lines to the end of your document. With enough work, there could even be a way to automatically detect an empty page and invoke the utility to trim it off.

**Comment by angelo-moreira** [comment]
Thank you for your reply @PhilterPaper an empty page with extra spaces seems a good "hacking" alternative, do you happen to know any software that could do that from the command line? This is for a webservice that needs to produce some invoices.

**Comment by PhilterPaper** [comment]
Which "that" are you asking about? I think you would have to modify the webservice invoice-writer to pad it with enough blank lines to force the last page to be fully background colored. Or, you could custom-write something to take a PDF and **pad out the last page** to a full page, using a library such as PDF::Builder (make sure the original document is PDF 1.4 or lower). 

Are these invoices frequently printed, and thus should fit on standard printer pages? If not, maybe you could look at the requests for "print to a single page" capability (or just choose a larger paper size) so that the invoice just fits the "paper". Of course, if it ends up being printed, it will probably still end half way down the page.

If your request is for a command line tool to trim off page(s), look at something like PDFtk. You could just tell it to extract the first two pages of an invoice, or whatever. I don't think it can look at a PDF and decide that it needs to trim off a last page.

**Comment by angelo-moreira** [comment]
hehe, "that" meant adding white spaces in the end of the page but you guessed it and your reply was perfect :)

Thank you I'll investigate PDFtk

**Comment by nareshchaudhary37** [comment]
I have made one workaround of this situation. It may help for you.

```
<script>
  const portraitHeightPx = 1326.6141732; //px
  const landscapeHeightPx = 922.20472441; //px
  const isPortrait = true; // dynamic boolean value
  var bodyHeight = 0;
  var totalPages;
  if (isPortrait) {
      totalPages = Math.ceil(document.body.scrollHeight / portraitHeightPx);
      bodyHeight = portraitHeightPx * totalPages;
  } else {
      totalPages = Math.ceil(document.body.scrollHeight / landscapeHeightPx);
      bodyHeight = landscapeHeightPx * totalPages;
  }
  // Fill up remaining space
  if(bodyHeight) {
      document.body.style.height =  bodyHeight + "px";
  }

</script>
```
