### ISSUE TITLE
Cannot create TOC (get outline instead)

### ISSUE THREAD

**Issue by PhilippSalvisberg** [wkhtmltopdf/wkhtmltopdf#3995]
## Problem

I'm using `wkhtmltopdf 0.12.5 (with patched qt)` within `CentOS 7.5`. I try to create a TOC for a HTML document but end up always with an outline only.

## How to Reproduce

Here are the steps to reproduce the issue.

### 1. Create toc.css

```
wkhtmltopdf --dump-default-toc-xsl > toc.xsl
```

### 2. Create pdf

Using the unmodified `toc.xsl` created previously.

```
toc --xsl-style-sheet toc.xsl https://github.com/wkhtmltopdf/wkhtmltopdf sample.pdf                                
```

### 3. The Result

Here's a screenshot of the first page:

![sample-page1](https://user-images.githubusercontent.com/3883171/42387695-68029e7a-8143-11e8-8569-94c6a3048629.png)

And here the PDF:

[sample.pdf](https://github.com/wkhtmltopdf/wkhtmltopdf/files/2171103/sample.pdf)

## Question

I'd like to produce a TOC as page 0 similar to the following:

```
Table of Contents

wkhtmltopdf/wkhtmltopdf ..........................................1
   Join GitHub today .............................................1
   README.md .....................................................2
   ...
```

How do I need to call wkhtmltopdf to get a TOC and an outline?

Every help is very much appreciated. 
Thank you.

**Comment by PhilippSalvisberg** [comment]
Looks like this issue is a duplicate of #3953, #3989 and #3993.
I've installed 0.12.4. Then the TOC is generated as expected.

**Comment by ashkulz** [comment]
A release candidate for the **0.12.6** release is [now available for download](https://wkhtmltopdf.org/downloads.html#release-candidate), which should contain changes which possibly address this issue.

Would appreciate downloading the package and reporting back if any issues are encountered during testing. Assuming all goes well, I plan to release 0.12.6 on the 2-year anniversary of the previous release i.e. June 11, 2020.
