### ISSUE TITLE
Text Not Printing in some cases

### ISSUE THREAD

**Issue by bobbyngwu** [wkhtmltopdf/wkhtmltopdf#3998]
Hi, I am experiencing some issues. When I try to convert some Html to pdf, the text does not appear. However the charts and other images print fine. This works fine when running the application locally, but when deployed to the server it does not in some cases. In most of the cases, everything prints fine, but in some scenarios, it is unable to paint the text.

The error captured from the Log is 
Warning: Received createRequest signal on a disposed ResourceObject's NetworkAccessManager. This might be an indication of an iframe taking too long to load.
![no text image](https://user-images.githubusercontent.com/10573649/42507822-6ef87cd8-843e-11e8-984a-9d94bf4ae56f.PNG)
![with text image](https://user-images.githubusercontent.com/10573649/42507824-6f0f4fee-843e-11e8-977f-ea93a59c3f89.PNG)

Just to add these are the options I have included

{ " --enable-javascript", " --no-stop-slow-scripts", " --javascript-delay 10000", " --window-status report_ready", " --load-media-error-handling ignore", " --load-error-handling ignore", " --debug-javascript" }

**Comment by PhilterPaper** [comment]
Is this a different font used in the missing text? Maybe it's missing on the PDF reader machine in some cases. That's the first thing I'd check.

**Comment by bobbyngwu** [comment]
Thanks Phil for your reply, but it is not. Like I said, on the same production server, sometimes it will print the entire report fine, but then in some reports, it would not, especially if there are a lot of charts to be drawn, which is where I suspect the delay is happening.

However, I was thinking this has to do with IIS (version 7) on the Production Server, as my development machine is running off IISExpress. I have however deployed the application to my local IIS (Version 10), it works fine on my local IIS. 

I just don't know what the issue is... I am just thinking why will the time related issue happen on IIS7 but not on IIS10 or IISExpress...

**Comment by bobbyngwu** [comment]
Okay quick update. Deployed same application to a different server running IIS8 and it works perfectly. I think it will be worth mentioning that there might be some compatibility issues with IIS7.

Tested this on IIS10 and IIS8 and they all work fine, but not on IIS7. Will update this thread if I find more information

**Comment by PhilterPaper** [comment]
Yeah, I wouldn't be surprised if Microsoft server products (especially older ones such as IIS7) were a little buggy when it came to doing unconventional things such as running the wkHTMLtoPDF application. Anyway, you have a fix for it now, so things are good.

**Comment by Tomsgu** [comment]
Closing as it seems to be fixed.
