### ISSUE TITLE
rendering results Mac OS - Linux

### ISSUE THREAD

**Issue by simdoor** [wkhtmltopdf/wkhtmltopdf#4002]
Hello,
I have issues with rendering identical HTML when running wkhtmltopdf on my dev environment (mac os) and production server (Linux) .

I cannot share the actual PDF, but I have noticed that I get different results even when running a command as simple as
`wkhtmltopdf http://www.google.com google.test.pdf`

Mac OS: wkhtmltopdf 0.12.4 (with patched qt)
Linux: wkhtmltopdf 0.12.5-rc (with patched qt)

I wonder if everyone gets the same results as in the attached files

[google.linux.pdf](https://github.com/wkhtmltopdf/wkhtmltopdf/files/2184113/google.linux.pdf)
[google.macos.pdf](https://github.com/wkhtmltopdf/wkhtmltopdf/files/2184114/google.macos.pdf)

**Comment by halkosajtarevic** [comment]
try setting `--dpi 96` on both

**Comment by simdoor** [comment]
@halkosajtarevic thanks for reply  
unfortunately it does not fix the issue. however after upgrading my local version to 0.12.5 it looks like I am getting the same output as in production server
