### ISSUE TITLE
wktemp files are not removed after wkhtmltoimage execution

### ISSUE THREAD

**Issue by AmirMingaliev** [wkhtmltopdf/wkhtmltopdf#4003]
Hi everyone!

There is an issue when tmp files don't be deleted after execution `wkhtmltoimage`. So this problem takes huge part of memory on production. I believe the issue is related to https://github.com/wkhtmltopdf/wkhtmltopdf/issues/1981, which seems was fixed in https://github.com/wkhtmltopdf/wkhtmltopdf/pull/3930. But the issue still exists on `wkhtmltoimage` in `0.12.5` version, so it seems that fix was only for `wkhtmltopdf`.

**Comment by Tomsgu** [comment]
This is already reported here: #3498. But good to know that it's still an issue in `0.12.5`
