### ISSUE TITLE
Chartist bar not rendering in pdf.

### ISSUE THREAD

**Issue by Riotsmurf** [wkhtmltopdf/wkhtmltopdf#4007]
I am having issues getting a pdf to render a bar chart. In the test-html the chart works.
I am assuming im missing something in my options to render the svg.

Chart js.
```html
<script type="text/javascript">

    new Chartist.Bar('#monthlyChart',
        {
            labels: ['1','2','3','4','5','6','7','>7'],
            series: [[Math.random(), Math.random(), Math.random(), Math.random(), Math.random(), Math.random(), Math.random()]]
        },
        {
            seriesBarDistance: 10,
            width: 500,
            height: 500,
            showLabel: true,
            animation: false
        }
    );

</script>
```
Tag its bound to:
```html
<div class="ct-chart" id="monthlyChart"></div>
```

cdns for chartist:
```html
<link rel="stylesheet" href="http://cdn.jsdelivr.net/chartist.js/latest/chartist.min.css">
<script src="http://cdn.jsdelivr.net/chartist.js/latest/chartist.min.js"></script>
```

I am using Laravel-Snappy to start the pdf, but the command out come is correct to wkhtmltopdf which is why i am asking here. 
Options:
```php
$pdf = \PDF::loadHTML($view);
$pdf->setOption('enable-javascript', true);
$pdf->setOption('javascript-delay', 5000);
$pdf->setOption('images', true);
$pdf->setOption('enable-smart-shrinking', true);
$pdf->setOption('margin-bottom', 3);
$pdf->setOption('margin-left', 3);
$pdf->setOption('margin-right', 3);
$pdf->setOption('margin-top', 0);
```

Any advice would be great. I recreated this issue only using this code. So it should be repeatable.

**Comment by Riotsmurf** [comment]
Found that wkhtmltopdf cannot render foreignObject tags

**Comment by lowegreg** [comment]
@Riotsmurf I'm having this exact issue!  What do you mean by 

> Found that wkhtmltopdf cannot render foreignObject tags

Any idea on how to proceed?  I'm trying to render bar graphs in python django...

Cheers,
Greg

**Comment by Riotsmurf** [comment]
@lowegreg I switched to a different chart library like c3(depends on d3) and others that use SVG but don't use foreignObjects. Also one thing to note is that wkhtmltopdf does not run js that has es6 syntax. Must be es5. Thats how i solved my issue.

**Comment by Riotsmurf** [comment]
Changed all my lets to vars and removed any functions that was introduced in es6. then worked fine

**Comment by Tomsgu** [comment]
Why not use e.g. [babel](https://babeljs.io/)?

**Comment by mmontalvo** [comment]
Solved it using https://github.com/wkhtmltopdf/wkhtmltopdf/issues/3695
