### ISSUE TITLE
v3 webservice - env variable for athenapdf cli command? how to enable "window-status" plugin?

### ISSUE THREAD

**Issue by benjhess** [wkhtmltopdf/wkhtmltopdf#4009]
Hi there,
in v2 we had WEAVER_ATHENA_CMD env variable to set athenapdf cli command. How can this be done in v3 webservice? I try to enable the "window-status" plugin... Maybe this can be set via query string params? I found no documentation about this and also nothing in the code of v3 or v3-wip branch.

what i tried so far:
`docker run --rm -e WEAVER_ATHENA_CMD="athenapdf --plugin=window-status" -p 8080:8080 arachnysdocker/athenapdf-service:3`

curl -L http://localhost:8080/process?uri=http://192.168.1.228:9191&fetcher=http > test.pdf

This outputs a pdf but does not wait for window.status. Also, athenapdf seems to ignore css. Output pdf has no css styles applied... :(
Would be nice if someone could help me here :)

**Comment by ashkulz** [comment]
This is wkhtmltopdf, not athenapdf.

**Comment by benjhess** [comment]
sry, wrong tab. shame on me^^
