### ISSUE TITLE
Some problems about watermark

### ISSUE THREAD

**Issue by 4o4-Not-Found** [wkhtmltopdf/wkhtmltopdf#4011]
I set `--header-html` parameter to complete the operation similar to watermark.
Its results are different from my expectations.
Some style do not work.
For example `transform:rotate(-20deg);` and font-family.
I'm a back end so i don't know why it doesn't work.
if somebody know why, tell me plz.
if u have an example,it's the best!!
```html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Insert title here</title>
</head>
<style type="text/css">
	.waterMark {
		text-align:center;
		position:absolute;
		width:100%;
		height:100%;
		z-index:-9999;
		pointer-event:none;
		font-size:5em;
		font-weight:bold;
		font-family:Consolas;
		color:#EDEDED
	}
	.waterMark-inner{
		transform:rotate(-20deg);
		line-height:200px
	}
</style>
<body>
	<div class="waterMark">
		<div class="waterMark-inner">WaterMark</div>
		<div class="waterMark-inner">WaterMark</div>
	</div>
</body>
</html>
```

**Comment by Tomsgu** [comment]
What do you expect to be an output? It works completely fine in 0.12.5.
![watermark](https://user-images.githubusercontent.com/2694769/42988538-478f476e-8bfd-11e8-97cf-ccf7756ef920.png)
What version do you have? Patched or unpatched? OS?

**Comment by 4o4-Not-Found** [comment]
thanks for re!
I just want to make the font of the watermark a little skew.
There is this style on HTML, but I change to PDF, and this style is lost.
Running on windows, version is 0.12.5
this is my html, the style is work.
![image](https://user-images.githubusercontent.com/28617648/42991951-c13fa482-8c39-11e8-928c-
7a65d5095a1d.png)

this is after changed,the style is not work on PDF.
![image](https://user-images.githubusercontent.com/28617648/42992071-18e6fee2-8c3a-11e8-810b-542437150bc8.png)

Could u show me your html resource?
i think something wrong on my html..

**Comment by Tomsgu** [comment]
Hmm that’s strange I used your html example and it gave me the output from the previous comment.

Can you show the html that you use?

**Comment by 4o4-Not-Found** [comment]
@Tomsgu 

`<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>WaterMark</title>
</head>
<script src="js/jquery-1.11.1.min.js" type="text/javascript" charset="utf-8"></script>	
<style type="text/css">
	.waterMark {
		text-align:center;
		position:absolute;
		width:100%;
		height:100%;
		z-index:-9999;
		pointer-event:none;
		font-size:5em;
		font-weight:bold;
		font-family:Consolas;
		color:#EDEDED
	}
	.waterMark-inner{
	transform:rotate(-20deg);
		line-height:200px;
		margin-top:200px;
	}
</style>
<script type="text/javascript">
	$(function(){
		$.ajax({
			url:'noBody/waterMark/query.do',
			type:'POST',
			dataType:'json',
			success:function(data){
				if(data) {
					var message = data.message;
					$('.waterMark-inner').append(data.message);
				}
			},
			error:function(){}
		});
	});
</script>
<body>
	<div class="waterMark">
		<div class="waterMark-inner"></div>
		<div class="waterMark-inner"></div>
		<div class="waterMark-inner"></div>
	</div>
</body>
</html>`

**Comment by Tomsgu** [comment]
I don't have `js/jquery-1.11.1.min.js` and `noBody/waterMark/query.do` resource in my localhost.

**Comment by 4o4-Not-Found** [comment]
This operation only detects the content of the watermark to be displayed from the background. Is this the reason why the operation is asynchronous?

**Comment by Tomsgu** [comment]
I could reproduce the issue. It seems to be a problem in patched version on linux as well.
