### ISSUE TITLE
page break not working properly

### ISSUE THREAD

**Issue by kenh12d** [wkhtmltopdf/wkhtmltopdf#4014]
wkhtmltopdf version: 0.12.5
OS: Windows 10.0.14393 build 14393

This is the command I was using wkhtmltopdf.exe --print-media-type -T 0 -B 0 -L 0 -R 0 

I added css style 
`@media print {`
`		.new-page {`
`			page-break-before: always;`
`		}`
`	}`

and use
 `<div class="new-page"></div>` 
to break page. This works when I print it in the browsers (tested on Chrome, Edge and IE) but doesn't work with wkhtmltopdf. The html file was attached. Thanks.

[test.zip](https://github.com/wkhtmltopdf/wkhtmltopdf/files/2212203/test.zip)

**Comment by Tomsgu** [comment]
This was discussed here many times. Please use the search functionality.

**Comment by kenh12d** [comment]
Yes, I searched the issue and lots of them marked as duplicated without info about the original issue and some point to a very closed but different issue. Can you please show me which is the original issue so that I can subscribe to it? Thanks.

**Comment by Tomsgu** [comment]
There is this question every month or even week. So with a search #2982, #223 and around 10 opened issues about tables that can help as well to read the comments.
