### ISSUE TITLE
Creating Different Footer  and Header for Each PDF Page

### ISSUE THREAD

**Issue by sathi5a0** [wkhtmltopdf/wkhtmltopdf#4023]
Hi.

I need to create PDF documents having multiple pages with different Footer and Header. I didn't find any solution for this. Can some one help me to achive this

version : wkhtmltopdf 0.12.2.4 (with patched qt)
OS : Windows 10

It would be appreciated for your help
Thanks.

**Comment by Mr-liu-yang** [comment]
options = {'--footer-center': '第[page]页,共[topage]页',
            '--footer-font-size': '9',}
options has add this params is ok

**Comment by Tomsgu** [comment]
This is an issue tracker. Please use e.g. stackoverflow platform if you have any questions.
