### ISSUE TITLE
Issues with page-break-inside

### ISSUE THREAD

**Issue by antoniogarcez** [wkhtmltopdf/wkhtmltopdf#4028]
Hi,

I have a table with a lot of rows and I do not want to break a page inside of a row so I use this:

`page-break-inside: avoid !important;`

But the result is this:
[result.pdf](https://github.com/wkhtmltopdf/wkhtmltopdf/files/2248457/result.pdf)

Can you help me?

**Comment by antoniogarcez** [comment]
I had put in `tr` element.

But now, I was testing another solution and I have noticed that appears some white lines in the middle of the page.

I use this style to my test:
`tr {
    background-color: red !important;
}`

Result:
[result2.pdf](https://github.com/wkhtmltopdf/wkhtmltopdf/files/2248901/result2.pdf)

**Comment by Leti** [comment]
OK.. I also use it in tr and it works for me..
did you try to change pdfmarginbottom value ?

**Comment by antoniogarcez** [comment]
Yes, I changed it to 0

**Comment by antoniogarcez** [comment]
I already solved my problem however, I had to use a different approach.

I was using `--print-media-type` to format my output file but after remove this property and change my CSS file, it worked perfectly.
