### ISSUE TITLE
Undefined variable "Plotly" when rendering a plotly graph to pdf

### ISSUE THREAD

**Issue by karlKoxed** [wkhtmltopdf/wkhtmltopdf#4029]
Ubuntu version 18.04 (Bionic)

wk version: wkhtmltox_0.12.5-1.bionic_amd64.deb

It did work with unpatched Qt, update required to include headers/footers, now graphs are not rendered.
--debug-javascript displays Undefined variable: "Plotly"

Thanks in advance

**Comment by karlKoxed** [comment]
As of today running sudo apt-get install wkhtmltopdf fixes the issue. 
Although "The switch --footer-center, is not support using unpatched qt, and will be ignored". 
I've tried several 'patched Qt' versions, none worked.

**Comment by karlKoxed** [comment]
so apparently something was added in the patched qt versions that broke this functionality, tried several fixes (referencing js script in html among others, with no luck).
Was this intentional? Any ideas on how to avoid this?

**Comment by Tomsgu** [comment]
Can you post a minimal test example so we can reproduce the issue?

**Comment by Tomsgu** [comment]
Closing as there is no feedback.
