### ISSUE TITLE
Html size limit

### ISSUE THREAD

**Issue by nerkez** [wkhtmltopdf/wkhtmltopdf#4031]
I can't convert html files bigger than 250KB. Is there some limitation?

**Comment by Tomsgu** [comment]
No there should not be limitation.

**Comment by PhilterPaper** [comment]
While there is no fixed, formal limit, you _could_ very easily be running out of virtual memory space on whatever machine you're running wkHTMLtoPDF on. I would assume it reads the entire HTML + JS + CSS into memory, and your example might be using huge amounts of JS or CSS (250kB of HTML doesn't seem all that large). Or, the JS might be doing a _lot_ of work with the DOM, chewing up a lot of memory. You might check how much VM you have available, and see if you can increase it.

**Comment by Tomsgu** [comment]
Closing this issue since the question is very general and answers were already provided.
