### ISSUE TITLE
Network Error - Failed to load http://true ?

### ISSUE THREAD

**Issue by ayoadedeji** [wkhtmltopdf/wkhtmltopdf#4033]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/anaconda/lib/python3.6/site-packages/pdfkit/api.py", line 26, in from_url
    return r.to_pdf(output_path)
  File "/anaconda/lib/python3.6/site-packages/pdfkit/pdfkit.py", line 156, in to_pdf
    raise IOError('wkhtmltopdf reported an error:\n' + stderr)
OSError: wkhtmltopdf reported an error:
Loading pages (1/6)
Error: Failed to load http://true/, with network status code 3 and http status code 0 - Host true not found
Warning: Failed loading page http://true (ignored)
Error: Failed to load http://true/, with network status code 3 and http status code 0 - Host true not found
Error: Failed loading page http://true (sometimes it will work just to ignore this error with --load-error-handling ignore)

I am trying to generate a pdf of a webpage using React.js and Plotly.js and I have fixed all issues (through use of polyfills) directly related to the webpage. However, I am getting this one random error that "http://true/" is not available, which is breaking everything, even though I am not trying to make a pdf of that url directly or trying to access that url in any of the scripts or css that are uploaded on the webpage. Does anyone have an idea why wkhtmltopdf is initially trying to access "http://true"? Also, I have used '--load-error-handling' and '--load-media-error-handling' tags and set them to ignore to see if that would change anything, but nothing changed.

**Comment by PhilterPaper** [comment]
Well, 'true' sounds like a boolean (true/false) value in Javascript (or maybe Python) that somehow is being used as a domain name or entire URL. The code thinks it's working with a URL string, but all it has is something saying "yes, there is a string". Does this site work OK in a browser (probably ruling out a Javascript problem)? Is any of this code written by you, or is it all "standard" wkHTMLtoPDF and Python from a reliable source?

**Comment by theayoad** [comment]
Everything is standard wkHTMLtoPDF and Python sourced from [Python-PDFkit](https://github.com/JazzCore/python-pdfkit). I was able to fix the issue; however, I still don't know why the "http://true/" error was occurring. I found that whenever I set the "--debug javascript" or "no-stop-slow-scripts" to True, the "http://true/" error popped up. Once I removed those tags, the error went away.

**Comment by ayoadedeji** [comment]
Everything is standard wkHTMLtoPDF and Python sourced from [Python-PDFkit](https://github.com/JazzCore/python-pdfkit). I was able to fix the issue; however, I still don't know why the "http://true/" error was occurring. I found that whenever I set the "--debug javascript" or "no-stop-slow-scripts" to True, the "http://true/" error popped up. Once I removed those tags, the error went away.

**Comment by Tomsgu** [comment]
Nice to hear that you could fix the issue. About the http://true you have most likely a bug in your javascript as @PhilterPaper explained. It's nothing connected with wkhtmltopdf.
