### ISSUE TITLE
Port external not working

### ISSUE THREAD

**Issue by luizmagao** [wkhtmltopdf/wkhtmltopdf#4034]
I am creating a pdf but with the external access to the link with port 8080 does not work, why?

**Comment by luizmagao** [comment]
https://gist.github.com/luizmagao/8c42cae47ec0a6b62dea380e05e83d9e

Verify in cod.

**Comment by Tomsgu** [comment]
Please refer to the wrapper or framework you use. Your issue has nothing to do with wkhtmltopdf itself.

**Comment by luizmagao** [comment]
I'm sorry you, but the wk is not working effectively. (Y)

**Comment by Tomsgu** [comment]
Yeah, but it's not enough to say it's not working to consider it as an issue. Your example is in addition in PHP. This is the command line tool. The input is html and output pdf.
