### ISSUE TITLE
Does pdfkit limit the size of HTML to PDF?

### ISSUE THREAD

**Issue by Mr-liu-yang** [wkhtmltopdf/wkhtmltopdf#4035]
i have a large html,i want turn it to pdf with pdfkit, but it cannot write full html to pdf

**Comment by Mr-liu-yang** [comment]
who can help me ?

**Comment by Tomsgu** [comment]
You should first read a documentation and then if you have any problem ask e.g. in stackoverflow (but of course with **detailed explanation**). Also this is not a `pdfkit`.
