### ISSUE TITLE
Application Error : The application was unable to start correctly (0xc000007b)

### ISSUE THREAD

**Issue by varunHo** [wkhtmltopdf/wkhtmltopdf#4037]
I have upgraded wkhtmltopdf.exe from 0.12.4 to 0.12.5 on local and it works fine; but when the exe is copied on server and triggered from command prompt it throws Application Error : The application was unable to start correctly (0xc000007b).

**Are there any required dlls that I need to install as part of 0.12.5 upgrade (from 0.12.4)?**

**Comment by Tomsgu** [comment]
You can see more information in wkhtmltopdf/packaging repository on how the windows binary is built. Please post the issue to the packaging repository if you will not find an answer. Also additional information like OS of the server would help.
