### ISSUE TITLE
external link only clickable if text is url

### ISSUE THREAD

**Issue by inikhil24** [wkhtmltopdf/wkhtmltopdf#4038]
Hello,

I am currently using wkhtmltopdf to do a basic conversion from html to pdf, below is the sample html code

`1)` `<a href="www.google.com">Go To Google</a> // produces unclickable link`
 2) `<a href="www.google.com">www.google.com</a> // produces clickable link for www.google.com`
 3) `<a href="www.google.com">www.yahoo.com</a> // produces clickable link for www.yahoo.com`

is this the expected behavior or something is wrong here?
how do we make the first option workable?
I'm using wkhtmltopdf 0.12.2.4 and on Linux Mint 18.

Thanks,
Nikhil

**Comment by inikhil24** [comment]
following html produces a unclickable Go to Google link

`<a href="https://www.google.com">Go to Google</a>`

**Comment by Tomsgu** [comment]
Most likely it's because of an old version. Can you try to update to `0.12.5` https://wkhtmltopdf.org/downloads.html?

**Comment by inikhil24** [comment]
version update did solved the issue.
can you point me where i can download the latest executable of wkhtmltopdf?
Thanks.

**Comment by Tomsgu** [comment]
Good to hear that. There is no executable for `0.12.5` due to problems problems: #3001. There is also an issue where you can find more information about it https://github.com/wkhtmltopdf/packaging/issues/8

**Comment by giorni** [comment]
This is still an issue. I am using version 0.12.5 with Debian 9, downloaded directly from website. I have `https` links and when I use something not as the link itself for the content text, it is not clickable. It does style the text as a link though, with with blue color and underline.

**Comment by giorni** [comment]
My bad. It is not a problem with wkhtmltopdf. I generate pages separated and then I merge using GhostScript. Links stop working only after merge. More details can be found [here](https://tex.stackexchange.com/questions/456896/set-the-print-flag-on-links-with-hyperref-to-preserve-them-with-ghostscript-9), for reference.

**Comment by rajeshkr7** [comment]
@inikhil24 , I am using the latest version (0.12.6) but it still not working for me.
[Issue](https://github.com/wkhtmltopdf/wkhtmltopdf/issues/5004)

can you put your code or any change that you have made ?

Thanks
