### ISSUE TITLE
provide linux-generic-amd64 package

### ISSUE THREAD

**Issue by pescobar** [wkhtmltopdf/wkhtmltopdf#4039]
Hi,

for version 0.12.4 and older you provided a binary package "linux-generic-amd64" but this is no longer provided in latest version 0.12.5

In EasyBuild we were using the generic package to install wkhtmltopdf without admin privileges
https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/w/wkhtmltopdf/wkhtmltopdf-0.12.3-Linux-x86_64.eb#L20

would it be possible that the generic binary package is provided in future releases?

**Comment by Tomsgu** [comment]
The issue is already here: https://github.com/wkhtmltopdf/packaging/issues/8.
