### ISSUE TITLE
wkhtmltopdf exited with non-zero code -15. error:

### ISSUE THREAD

**Issue by rohit-taneja** [wkhtmltopdf/wkhtmltopdf#4051]
Can you tell the meaning of exit code 15 OR When will someone get this error ?

# Software Info:
* OS : Ubuntu 14.04.3 LTS
* wkhtmltopdf : 0.12.2.1 (with patched qt)
* pdfkit : 0.6.1
* python : 3.4.3

**Comment by Tomsgu** [comment]
After a short googling i found:
>'exit status -15' means 'the process was terminated' - usually this means the computer ran out of memory and decided to kill ecm

Anyway, `0.12.2.1` is an old version, so I am closing this issue.

**Comment by rohit-taneja** [comment]
@Tomsgu  Do we have defined exit codes for wkhtmltopdf? As Exit Codes mean different in different context. I found that Exit Code 15 means SIGTERM for process termination in Linux and I couldn't find this ran out of memory after googling. Can you please send me the link/google search term

**Comment by Tomsgu** [comment]
The actual error code is **143**. 128 +15, so you can find some google results [here](https://www.google.com/search?source=hp&ei=Lh98W5acGuvCgAbtuqQ4&q=linux+exit+code+143&oq=linux+exit+code+143&gs_l=psy-ab.3..0j0i22i30k1l2.82.6106.0.6345.34.24.7.1.1.0.288.3153.2j10j6.18.0....0...1c.1.64.psy-ab..8.26.3205.0..35i39k1j0i13k1.0.dChTDLaLmJY). 

There are no documented exit codes. It was requested [here](https://github.com/wkhtmltopdf/wkhtmltopdf/issues/1502#issuecomment-35705833) and [here is the answer](https://github.com/wkhtmltopdf/wkhtmltopdf/issues/1502#issuecomment-35705833). But these are exit codes in context of wkhtmltopdf (qtwebkit), not in a linux context. There is also issue #3197.
