### ISSUE TITLE
 wkhtmltopdf command was not found in your classpath

### ISSUE THREAD

**Issue by tczaqss** [wkhtmltopdf/wkhtmltopdf#4055]
c.g.j.w.w.c.WrapperConfig - Initialized with default configurations.
java.lang.RuntimeException: wkhtmltopdf command was not found in your classpath. Verify its installation or initialize wrapper configurations
 with correct path/to/wkhtmltopdf

**Comment by Tomsgu** [comment]
This is a cli tool. Please try to find help somewhere else if you're using java.
