### ISSUE TITLE
TOC page is not created

### ISSUE THREAD

**Issue by guillaumefortin** [wkhtmltopdf/wkhtmltopdf#4056]
I installed 0.12.5 using centos6 and centos7 rpm with different arguments combinations and I naver have the TOC page in my PDF. Tried many examples supposed to work.

**Comment by Tomsgu** [comment]
Duplicate of #3953. It was fixed, but there is no stable release yet.

**Comment by ashkulz** [comment]
A release candidate for the **0.12.6** release is [now available for download](https://wkhtmltopdf.org/downloads.html#release-candidate), which should contain changes which possibly address this issue.

Would appreciate downloading the package and reporting back if any issues are encountered during testing. Assuming all goes well, I plan to release 0.12.6 on the 2-year anniversary of the previous release i.e. June 11, 2020.
