### ISSUE TITLE
Wkhtmltopdf on JSF - Results differs between JSF Application and command line interface

### ISSUE THREAD

**Issue by Kap-Code** [wkhtmltopdf/wkhtmltopdf#4057]
Hi,
I have to generate PDF in JSF application, so i used the Wkhtmltopdf API. Before using it in JAVA, at first, i have tried to use the API on a command line interface directly (Linux) and it works perfectly.
Structure look like that:
![pdf_print_cmdline](https://user-images.githubusercontent.com/42544020/44510766-d48b7200-a6b5-11e8-9d4e-0664cf91e9bd.png)

The problem appears when i try to execute this command in JAVA (ie "Process process = Runtime.getRuntime () .exec (cmdline)"). The rendering of the PDF differs from the command line version: the API doesn’t print all elements of the HTML page:
![fail_pdf_print_java](https://user-images.githubusercontent.com/42544020/44510798-ee2cb980-a6b5-11e8-9336-4474200dff50.png)

I think that it is limited on the number of lines it prints (or somethink like that) : for example, if i delete the content of one purple frame, the last purple frame appears with it content. I did several research on various forums to find a solution, but i did not find anything about "this" problem. Could you help me, please?

It's a simplified version of the structure of my html page without css:
```
<html>
<meta http-equiv="Content-Type" content="text/html;CHARSET=UTF-8" />
<style>
</style>
<body>
	<div class="pdf">
		<table style="width: 100%;">
			<tr>
				<th>...</th>
				<th>...</th>
			</tr>
		</table>
		<table style="width: 100%;">
			<tr>
				<th>
					<table style="width: 100%; table-layout: fixed;">
						<tr>
							<th>...</th>
						</tr>
						<tr>
							<th>...</th>
						</tr>
					</table>
				</th>
				<th>
					<table style="width: 100%; table-layout: fixed;">
						<tr>
							<th>...</th>
						</tr>
						<tr>
							<th>...</th>
						</tr>
					</table>
				</th>
				<th>
					<table style="width: 100%; table-layout: fixed;">
						<tr>
							<th>...</th>
						</tr>
						<tr>
							<th>...</th>
						</tr>
						<tr>
							<th>...</th>
						</tr>
					</table>
				</th>
			</tr>
		</table>
		<table style="width: 100%;">
			<tr>
				<th style="width: 10%;">...</th>
				<th style="width: 80%;">...</th>
				<th style="width: 10%;">...</th>
			</tr>
		</table>
	</div>
</body>
</html>
```

•	Command line interface- Terminal :
`export QT_XKB_CONFIG_ROOT=/usr/share/X11/xkb && xvfb-run wkhtmltopdf -O Landscape /path/file.html /path/file.pdf`

•	Command line interface – JSF :
```
String[] cmdline = { "sh", "-c", "export QT_XKB_CONFIG_ROOT=/usr/share/X11/xkb && xvfb-run wkhtmltopdf -O Landscape /path/file.html /path/file.pdf" };
Process process = Runtime.getRuntime().exec(cmdline);
```

Thank you for your time.

**Comment by Tomsgu** [comment]
Is your version 0.12.5? If it is you don't need to use `xvfb`. I don't think this is the right place for this question since it seems to be more problem with java.

**Comment by Kap-Code** [comment]
Hi @Tomsgu 
Thank you for your help. The version I was using was 0.13.alpah. I just installed the 0.12.5 (I also removed xvbf). The result remains unchanged. I will follow your advice and ask for help assuming it's a JAVA problem, thanks.

**Comment by Tomsgu** [comment]
Ok, that makes sense to use it with 0.13 alpha. Please let us know when you think the problem is on wkhtmltopdf side.
