### ISSUE TITLE
Unknown Long Argument error

### ISSUE THREAD

**Issue by Ajji11** [wkhtmltopdf/wkhtmltopdf#4058]
I'm trying run this command:

`wkhtmltopdf --header-right='[page]/[toPage]' c:\bop.htm c:\result.pdf`

and getting this error

`Unknown long argument --header-right='[page]/[toPage]'`

**Comment by Tomsgu** [comment]
What about `wkhtmltopdf --header-right '[page]/[toPage]' c:\bop.htm c:\result.pdf`

**Comment by Ajji11** [comment]
that works, thank you!
