### ISSUE TITLE
Exit with code 1 due to network error: UnknownNetworkError，

### ISSUE THREAD

**Issue by adelewyr** [wkhtmltopdf/wkhtmltopdf#4059]
i use wkhtmltopdf on https://doc.embedded-wizard.de/welcome-to-embedded-wizard?v=9.00

But there was an error

```
wkhtmltopdf.exe https://doc.embedded-wizard.de/welcome-to-embedded-wizard?v=9.00 out.pdf
Loading pages (1/6)
libpng warning: iCCP: known incorrect sRGB profile ] 70%
Error: Failed to load https://www.youtube.com/embed/XaZJ2kx79pc?rel=0&controls=0&showinfo=0&autoplay=1&loop=1&playlist=XaZJ2kx79pc, with network status code 99 and http status code 0 - Connection timed out
Error: Failed to load https://www.youtube.com/embed/BJ6oXZlA7X8?rel=0, with network status code 99 and http status code 0 - Connection timed out
Counting pages (2/6)
Resolving links (4/6)
Loading headers and footers (5/6)
Printing pages (6/6)
Done
Exit with code 1 due to network error: UnknownNetworkErro
```

I think its because there have youtue video on this page caused this error
but how can i fix it?

**Comment by adelewyr** [comment]
environment:
wkhtmltopdf 0.12.5

**Comment by Tomsgu** [comment]
What version of 0.12.5 do you use? What OS do you have? I tried both patched and unpatched versions on linux and it gives me no error and pdf is generated.

**Comment by adelewyr** [comment]
@Tomsgu 
sorry i forget it
i am work on windows7
and i use wkhtmltox-0.12.5-1.msvc2015-win32.exe
use `--load-error-handling ignore` and `--load-media-error-handling ignore` as a workaround is not useful for me,have same error
may be the GFW is the reason because you can't watch a youtube video in china

**Comment by Tomsgu** [comment]
Ah ok I see that's indeed a problem. I think with `--disable-external-links` you can fix the issue here, but it's not quite useful if you need to load other external links. (in this case the pdf looks good) 

`wkhtmltopdf.exe --print-media-type --disable-external-links h
ttps://doc.embedded-wizard.de/welcome-to-embedded-wizard?v=9.00 test.pdf`

**Comment by adelewyr** [comment]
@Tomsgu 
thanks for your help！the pdf has created。
although the error is still appear，but i use `try except` to skip this error,
I put the code in my VPC run in the United States,and there has no error
so i think it is a country bug

**Comment by Tomsgu** [comment]
Good to hear. Another solution can be to download a page and remove invalid links from it.
