### ISSUE TITLE
Accept Cookies bar on website

### ISSUE THREAD

**Issue by hoge6b01** [wkhtmltopdf/wkhtmltopdf#4075]
Hi,
I always get the 'accept cookies' bar printed in the output pdf. I accepted the cookies in Chromium and FF, but didn't help. 
I couldn't find any solution.
BR

**Comment by Tomsgu** [comment]
You can use your own css style to hide the accept cookies bar. 

```bash
# e.g.
wkhtmltopdf --user-style-sheet /tmp/a.css google.com a.pdf
```

**Comment by Tomsgu** [comment]
Closing as the answer was given and there is no feedback from the author.
