### ISSUE TITLE
Rendering issues for Thai

### ISSUE THREAD

**Issue by wachirawitc** [wkhtmltopdf/wkhtmltopdf#4076]
**Hi** wkhtmltopdf develop,

I am use **wkhtmltopdf 0.12.5** to generator PDF report. 
But some characters in **Thai language** is in **incorrect on Windows os**.

Try with command **wkhtmltopdf.exe https://th.wikipedia.org/wiki/%E0%B8%99%E0%B9%89%E0%B8%B3 test.pdf**

![screen-shot-2561-09-09-at-23 03 38](https://user-images.githubusercontent.com/11304347/45266453-51279a00-b485-11e8-8e20-1107e2025143.jpg)

![screen-shot-2561-09-09-at-23 03 45](https://user-images.githubusercontent.com/11304347/45266454-54bb2100-b485-11e8-80f8-22eded2f4369.jpg)

Sample result 
[mac.pdf](https://github.com/wkhtmltopdf/wkhtmltopdf/files/2364416/mac.pdf)

[windows.pdf](https://github.com/wkhtmltopdf/wkhtmltopdf/files/2364418/windows.pdf)

Now I'm working on a solution [#2087](https://github.com/wkhtmltopdf/wkhtmltopdf/issues/2087)  **_but not work._**

**Comment by PhilterPaper** [comment]
Is this a TrueType or OpenType font being used? It would include GSUB and GPOS instructions to properly substitute and position ligatures. If it works for most characters, it might be a defective font file (try installing another, if you can find one). If nothing is working properly, it might be the rendering engine (WebKit) that doesn't handle GSUB and GPOS correctly. I need information on implementing GSUB and GPOS in Indic languages myself for a project, so I welcome more info here.

**Comment by PhilterPaper** [comment]
Did you find a solution, or at least, any useful information? Or did you just give up on this and go to some other product?
