### ISSUE TITLE
Generate pdf for blog pages which are not yet published

### ISSUE THREAD

**Issue by wildnano** [wkhtmltopdf/wkhtmltopdf#4078]
Hi,
I need to generate pdf for pages which are not yet published.
I can preview the page from admin side.
I'd like to convert this url to pdf
I added these lines but it doesn't work.
$pdf->setOptions((["username" => 'username']));
$pdf->setOptions((["password" => 'password']));
How can I do ?

Thanks

**Comment by PhilterPaper** [comment]
Have you searched on StackOverflow and on GitHub issues for how to do this (log into a webpage)? There's been quite a bit of discussion on the subject. There _might_ be more actions needed to get to the desired content once you've signed on.

**Comment by Tomsgu** [comment]
Closing as there is no feedback. Please use stackoverflow for these kind of issues. PHP wrappers are also not in scope of this project.
