### ISSUE TITLE
Bulma CSS - @media problems

### ISSUE THREAD

**Issue by fabiociconi** [wkhtmltopdf/wkhtmltopdf#4085]
Hi,
Rotativa is losing some features in Bulma css, such as @media, it completely ignores.

Example":

@media screen and (min-width: 769px), print
.column.is-one-third, .column.is-one-third-tablet {
    flex: none;
    width: 33.3333%;
}

**Comment by Tomsgu** [comment]
At first use `wkhtmltopdf --print-media-type` if you want use @media print.

Second flex is not working in 0.12.x branch. See https://github.com/wkhtmltopdf/wkhtmltopdf/issues/1522 https://github.com/wkhtmltopdf/wkhtmltopdf/issues/3207
