### ISSUE TITLE
Provides only blank pdf while using angular and node api

### ISSUE THREAD

**Issue by VjRagss** [wkhtmltopdf/wkhtmltopdf#4086]
It works fine with other urls

**Comment by viswa18** [comment]
@VjRagss  can you provide more details, it will be helpful. If possible share your input URL/ HTML file.

**Comment by cyyeap** [comment]
It might be worth downloading QtWeb - Portable Web Browser to check if your url renders on the browser which wkhtmltopdf uses.

**Comment by Tomsgu** [comment]
No information (reproducible example, description of the problem, etc.). We can hardly decipher what the issue really is.

**Comment by mateusfmello** [comment]
I have the same problem, I detailed in #5293
