### ISSUE TITLE
Are you planning to release software for ubuntu arm64 platform?

### ISSUE THREAD

**Issue by zouweibing525** [wkhtmltopdf/wkhtmltopdf#4088]
I'm try to use this software with ubuntu 18.04 arm64 platform，build it form source package，but it is do not work，so pull this question. Are you planning to release software for ubuntu arm64 platform?

**Comment by Tomsgu** [comment]
I don't think there is a plan to support arm64, but you can make a request (or get more information) in [wkhtmltopdf/packaging](https://github.com/wkhtmltopdf/packaging) project.

**Comment by mamarmite** [comment]
Running odoo natively on a raspberry pi on ubuntu or another distro.

**Comment by ashkulz** [comment]
Please see the [latest release](https://github.com/wkhtmltopdf/packaging/releases) which has packages for a lot of ARM64 targets. Please add a comment if you face any problems in using the packages :+1:

**Comment by ashkulz** [comment]
A release candidate for the **0.12.6** release is [now available for download](https://wkhtmltopdf.org/downloads.html#release-candidate), which should contain changes which possibly address this issue.

Would appreciate downloading the package and reporting back if any issues are encountered during testing. Assuming all goes well, I plan to release 0.12.6 on the 2-year anniversary of the previous release i.e. June 11, 2020.
