### ISSUE TITLE
SharePoint online apps

### ISSUE THREAD

**Issue by GilesKern** [wkhtmltopdf/wkhtmltopdf#4090]
wkhtmltopdf Version: 0.12.4 (with patched qt)
Operating System and Version: Windows Server 2012 R2 Datacenter

When trying to generate PDF for a SharePoint online app (add-in) the login screen is displayed.

The PDF conversion works fine if it's a SharePoint online page, using the settings --cookie-jar  c:\token.jar 
token.jar containing the SPOIDCRL cookie. But it's not working for an app. 

Any ideas ?

Giles Kern

**Comment by Tomsgu** [comment]
This is out of scope of this project. You can try to ask on stackoverflow where you can get a better answer from people who has experience with SharePoint.
