### ISSUE TITLE
Css3 not supported

### ISSUE THREAD

**Issue by do7a15** [wkhtmltopdf/wkhtmltopdf#4092]
Wkhtmltopdf is not rendering the html to pdf with css3 missing some properties, like: rotate, calc, inline-block...
transform: rotate(45deg);
display: inline-block; 
width: calc(50% - 32px);

**Comment by MaceWindu** [comment]
Well, CSS3 wasn't in webkit in 2011 (version, used by wkhtmltopdf)

**Comment by MaceWindu** [comment]
Don't use unsupported css features or use other tools. E.g. https://github.com/Sicos1977/ChromeHtmlToPdf

**Comment by do7a15** [comment]
> Don't use unsupported css features or use other tools. E.g. https://github.com/Sicos1977/ChromeHtmlToPdf

I have simil issue https://github.com/wkhtmltopdf/wkhtmltopdf/issues/4093

**Comment by hakimio** [comment]
If you need the latest and the greatest css, html and js features use [Puppeteer](https://github.com/GoogleChrome/puppeteer).

**Comment by Tomsgu** [comment]
Closing as duplicate of #3300.
