### ISSUE TITLE
The exit status code '139' says something went wrong:Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by raj69869** [wkhtmltopdf/wkhtmltopdf#4096]
The exit status code '139' says something went wrong:stderr: "Loading pages (1/6)[> ] 0%[======> ] 10%[=======> ] 13%[============> ] 21%Warning: SSL error ignored Warning: SSL error ignoredWarning: SSL error ignoredWarning: SSL error ignored[===================> ] 32%[======================> ] 38%[========================> ] 41%[===========================> ] 45%[============================> ] 48%[==================================> ] 58%[========================================> ] 67%[===========================================> ] 72%[===============================================> ] 79%[================================================> ] 81%[==================================================> ] 84%[===================================================> ] 86%[============================================================] 100%Segmentation fault (core dumped)"stdout: ""command: /usr/local/bin/wkhtmltopdf --lowquality --dpi '96' --margin-bottom '0mm' --margin-left '0mm' --margin-right '0mm' --margin-top '0mm' --page-size 'a4' --encoding 'utf-8' --enable-javascript --javascript-delay '5000' --enable-smart-shrinking --no-stop-slow-scripts '/tmp/knp_snappy5ba20835c07db2.66738521.html' '/var/www/vhosts/emfi.eu/dev.emfi.eu/public/temp_cover_pdf/Argentina_COVER_REPORT_EN_20180919082926.pdf'.
--
in AbstractGenerator.php (line 378)
at AbstractGenerator->checkProcessStatus(139, '', 'Loading pages (1/6)[> ] 0% [======> ] 10% [=======> ] 13% [============> ] 21% Warning: SSL error ignored Warning: SSL error ignoredWarning: SSL error ignoredWarning: SSL error ignored[===================> ] 32% [======================> ] 38% [========================> ] 41% [===========================> ] 45% [============================> ] 48% [==================================> ] 58% [========================================> ] 67% [===========================================> ] 72% [===============================================> ] 79% [================================================> ] 81% [==================================================> ] 84% [===================================================> ] 86% [============================================================] 100% Segmentation fault (core dumped)', '/usr/local/bin/wkhtmltopdf --lowquality --dpi \'96\' --margin-bottom \'0mm\' --margin-left \'0mm\' --margin-right \'0mm\' --margin-top \'0mm\' --page-size \'a4\' --encoding \'utf-8\' --enable-javascript --javascript-delay \'5000\' --enable-smart-shrinking --no-stop-slow-scripts \'/tmp/knp_snappy5ba20835c07db2.66738521.html\' \'/var/www/vhosts/emfi.eu/dev.emfi.eu/public/temp_cover_pdf/Argentina_COVER_REPORT_EN_20180919082926.pdf\'')

i have putt script in html page when ever getting this type of issue.
can you please help me ?

**Comment by raj69869** [comment]
i have used Wkhtmltopdf version is 0.12.5 (with patched qt) and Ubuntu version 16.04.04.
any one can help me for this issue ?

**Comment by Tomsgu** [comment]
Please ask in stackoverflow if you have these kind of questions. Also without any example is hard to tell what is wrong.
