### ISSUE TITLE
Table cells' padding, margin and border not being styled

### ISSUE THREAD

**Issue by GCSBOSS** [wkhtmltopdf/wkhtmltopdf#4099]
Table cells don't seem to be affected by any "spacing related" CSS rules. Adding padding, border or margin to `td`, `th` or `tr` has no effect at all. Other styles work fine.

> wkhtmltopdf 0.12.5 (with patched qt) running Windows 10.

Bug was ignored in #1920.

Wrongly marked as fixed (without any reference to code or PR) in #3567.

**Comment by Tomsgu** [comment]
Ah sorry. I marked the issue as fixed according to (this)[https://github.com/wkhtmltopdf/wkhtmltopdf/issues/3567#issuecomment-405847657] comment. I thought it was fixed in 0.12.5. I am reopening the first issue and mark this one as duplicate to not make confusions.
