### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by leonscut** [wkhtmltopdf/wkhtmltopdf#4102]
I was invoke wkhtmltopdf  through java Runtime on a redhat 6 sever,
It's work fine in most case,but sometimes I have java.IOException: error=2   No such file or directory error.Anyone know how this happend? The error Stack was 
exp info:java.io.IOException: java.io.IOException: error=2, No such file or directory
exp stack:
Line148_java.lang.UNIXProcess.<init>
Line65_java.lang.ProcessImpl.start
Line452_java.lang.ProcessBuilder.start
Line593_java.lang.Runtime.exec
Line431_java.lang.Runtime.exec
Line328_java.lang.Runtime.exec

**Comment by Tomsgu** [comment]
Please ask your question in stackoverflow. The issue seems to be with java, not with wkhtmltopdf itself.
