### ISSUE TITLE
Apply page background cololr in WKHTMLTOPDF

### ISSUE THREAD

**Issue by sathishkumar94** [wkhtmltopdf/wkhtmltopdf#4103]
Hi Team,

Im trying to apply page background color. Seems cant able to apply page background color in wkhtmltopdf url.

Do we have option to generate pdf using wkhtmltopdf url?

Like ,
wkhtmltopdf [GLOBAL OPTION]... [OBJECT]... <output file>

**Comment by Tomsgu** [comment]
Hi @sathishkumar94 ,

Please ask your question in stackoverflow. This is not a help desk.
