### ISSUE TITLE
font-face make all font-family not work, and fonts conflict

### ISSUE THREAD

**Issue by qijianjun** [wkhtmltopdf/wkhtmltopdf#4104]
I found strange fonts render problem and be confused. I  then test for hours and find two prolems about font support:

1. When there is a font-face rule and applied to some elements, then all other elements with a class of font-family will not be rendered as statement, they just be rendered with the default font.
2. Some fonts conflict. When I delete all font-face rules, leave only classes with font-family, I found some of them conflict: one will make another not work as expected.

I will describe the two problems below.

**My env:**
Msys2 on Windows 10.
```
qi@qi-pc MSYS /D/coding/convert-pdf
$ uname -a
MSYS_NT-10.0 qi-pc 2.11.1(0.329/5/3) 2018-09-10 14:19 x86_64 Msys

qi@qi-pc MSYS /D/coding/convert-pdf
$ wkhtmltopdf.exe -V
wkhtmltopdf 0.12.5 (with patched qt)
```

Problem #1:
There are 4 @font-face related css items, the first three are icon-fonts, and the last one use a local ttf file. There are also 4 elements that apply the rules.
I also have 3 font-family rules without font-face: font-yy / font-kt / font-fs. They use fonts shipped with Windows, and should display as below:
![image](https://user-images.githubusercontent.com/612912/46024709-f6936c80-c119-11e8-9805-32e4a72fb67a.png)
The problem is: if any of four font-face related _rules/css file_ applied to the corresponding element (ie. the rule and the element not commented out at the same time), the font-yy, font-kt, font-fs will not work, the elements with these classes will be rendered with the default font, as below:
**eg. the fontawesome element rendered**
![image](https://user-images.githubusercontent.com/612912/46024876-42deac80-c11a-11e8-9af3-6637a4b449e7.png)

```html
<!DOCTYPE html>
<html lang="zh-Hans">
<head>
	<meta charset="UTF-8">
    <title>demo-1</title>
    <link rel="stylesheet" href="static/css/font-awesome.min.css">  <!-- #1 font-face define -->
    <link rel="stylesheet" href="static/css/iconfont.css">  <!-- #2 font-face define -->
    <link rel="stylesheet" href="static/css/share.min.css">  <!-- #3 font-face define -->
    <script src="static/js/social-share.min.js"></script>
    <style>
    /* #4 font-face define */
    @font-face {
        font-family: test;
        src: url('./simhei.ttf');
    }

    .font-test {
        font-family: test;
    }
    .font-fs {
        font-family: STFangsong, FangSong, "华文仿宋", "仿宋";
    }
    .font-yy {
        font-family: YouYuan, "幼圆";
    }
    .font-kt {
        font-family: STKaiti, Kaiti, "华文楷体", "楷体";
    }
    </style>
</head>
<body>
    <!-- #1 font-face apply -->
    <i class="fa fa-fw fa-book"></i>
    <!-- #2 font-face apply -->
    <i id="mark-type-icon" class="icon iconfont icon-official"></i>
    <!-- #3 font-face apply -->
    <a class="social-share social-share-icon icon-facebook"></a>
    <!-- #4 font-face apply -->
    <p class="font-test">甲乙丙丁戊己庚辛壬癸，子丑寅卯辰巳午未申酉戌亥。</p>
    <!-- the following 3 lines have class with fonts shipped with Windows -->
    <p class="font-yy">甲乙丙丁戊己庚辛壬癸，子丑寅卯辰巳午未申酉戌亥。</p>
    <p class="font-kt">甲乙丙丁戊己庚辛壬癸，子丑寅卯辰巳午未申酉戌亥。</p>
    <p class="font-fs">甲乙丙丁戊己庚辛壬癸，子丑寅卯辰巳午未申酉戌亥。</p>
</body>
</html>

```

Problem 2:
I define four font-family related rules: _font-pt / font-kt / font-yy / font-fs_, and 4 p elements each with one of the four classes. I commented out some (one or two or there) p elements and convert pdf files, and got 15 pdfs, below are the files distribution. 8 of them are normal, and the other 7 result with error.

| show n p-elements | combinations | error |
| ---               | :---         | :---: |
| 4                 | 1            | 1     |
| 3                 | 4            | 4     |
| 2                 | 6            | 2     |
| 1                 | 4            | 0     |
|                   | 15           | 7     |

I fonud when font-pt and font-yy both exist, the element with font-yy class display abnormal; when font-fs and font-kt both exists, the element with font-fs be rendered with font-kt. Below are pics and the html:
**pt-kt-yy, yy abnormal**:
![image](https://user-images.githubusercontent.com/612912/46023845-1e81d080-c118-11e8-8a6f-1d8fd1e2ce53.png)
**pt-yy, yy abnormal**:
![image](https://user-images.githubusercontent.com/612912/46024054-94863780-c118-11e8-90b2-16db4bfdfe78.png)
**pt-kt-fs, fs abnormal, rendered as kt**:
![image](https://user-images.githubusercontent.com/612912/46023984-6b65a700-c118-11e8-8338-4164f1789dde.png)
**kt-fs, fs abnormal, rendered as kt**:
![image](https://user-images.githubusercontent.com/612912/46024126-b1bb0600-c118-11e8-9b3d-e1a71bfc6883.png)
pt-kt-yy-fs, yy and fs abnormal:
![image](https://user-images.githubusercontent.com/612912/46024246-ef1f9380-c118-11e8-9a47-f249f02f4961.png)

```
<!DOCTYPE html>
<html lang="zh-Hans">
<head>
	<meta charset="UTF-8">
    <title>demo2</title>
    <style>
        .font-pt {
            font-family: "SimSun", "宋体";
        }
        .font-kt {
            font-family: "STKaiti", "Kaiti", "华文楷体", "楷体";
        }
        .font-yy {
            font-family: "YouYuan", "幼圆";
        }
        .font-fs {
            font-family: "STFangsong", "FangSong", "华文仿宋", "仿宋";
        }
    </style>
</head>
<body>
    <p class="font-pt">甲乙丙丁戊己庚辛壬癸，子丑寅卯辰巳午未申酉戌亥。</p>
    <p class="font-kt">甲乙丙丁戊己庚辛壬癸，子丑寅卯辰巳午未申酉戌亥。</p>
    <p class="font-yy">甲乙丙丁戊己庚辛壬癸，子丑寅卯辰巳午未申酉戌亥。</p>
    <p class="font-fs">甲乙丙丁戊己庚辛壬癸，子丑寅卯辰巳午未申酉戌亥。</p>
</body>
</html>

```

**Comment by qijianjun** [comment]
I changed to the Ubuntu version, and the problem solved, so it seems to be a platform related problem.

**Comment by Tomsgu** [comment]
Closing as the problem seems to be not in wkhtmltopdf.
