### ISSUE TITLE
Abandon this project and support Puppeteer?

### ISSUE THREAD

**Issue by garygreen** [wkhtmltopdf/wkhtmltopdf#4106]
So it seems this project has become pretty stagnant over the last few years - release 0.13 has been in the making for over 2 years and yet to be be given any official release.

Now that [Puppeteer](https://github.com/GoogleChrome/puppeteer) has been in the ecosystem for a while, is it about time wkhtmltopdf is officially abandoned in favour of that project? It doesn't seem logical to continue to support it when there are other modern and up to date alternatives out there that run on webkit.

Of course all the hard work on this project over the years has been much appreciated, I've personally used this in many personal and commercial projects, but that's also why I think it would be good to officially declare where wkhtmltopdf stands.

👍

**Comment by PhilterPaper** [comment]
An interesting proposition.

Many of wkHTMLtoPDF's problems and limitations seem to stem from its use of an old WebKit engine, that can't be easily swapped out for an up-to-date version. Is my reading of this correct? I'm not sure exactly where WK ends and this project begins, but is Puppeteer similar in architecture? That is, loading the page and running the Javascript to update the DOM. Then I suppose it could either directly read the DOM and do the PDF rendering from there, or it could have the WK or Chromium engine do much of the work for print media (printing), and catch it before it actually starts outputting to the file. Is this how wkHTMLtoPDF (and perhaps Puppeteer) work? 

Depending on what the rendering engine offers for media sizes and margins, you might get a lot of work done for free. Of course, things like proper kerning, ligatures, and hyphenation (paragraph shaping) might not be supported by a browser engine. In that case, falling back to directly reading the HTML might give more control. Of course, then you have to do something about the Javascript yourself, and carefully apply all the CSS. The upside is that you could embed special comments to direct the print output (e.g., rotate this page with a wide table) that you might not be able to do if you have to wait for the browser rendering engine to provide you with almost fully-digested HTML+JS+CSS. Maybe you could get to the DOM after JS has been run, and even after the engine has decided what CSS applies to any element, and do the rest of the rendering (to PDF) yourself.

Just some thoughts on the subject. I once played with something called HTMLDOC, which directly read an HTML file (but ignored any JS or CSS). Adding CSS support didn't look too bad, but once I got to thinking about what to do with Javascript, I decided to try something already on the shelf. Anyway, has anyone else done some blue-sky thinking about a better way to convert HTML into PDF?

**Comment by yaningwang123** [comment]
I used version 0.13 and checked the check box to show "x" after printing. Then I used 0.12.5, the checkbox problem did not, but the transparency of the background failed。

**Comment by giannidhooge** [comment]
Another important [missing item](https://github.com/GoogleChrome/puppeteer/issues/2167) in Puppeteer is that javascript is not evaluated in headers/footers. This makes it impossible to hide the header and/or footer on a specific page. 
There was a [hacky way](https://github.com/GoogleChrome/puppeteer/issues/2089#issuecomment-379934407) to do this, but due to [a bug](https://github.com/GoogleChrome/puppeteer/issues/2480#issuecomment-429579047) in chrome it's not possible at this time.

**Comment by lkraider** [comment]
Also internal document links don't work in Puppeteer https://github.com/puppeteer/puppeteer/issues/4687

**Comment by ashkulz** [comment]
Please see the [project status](https://wkhtmltopdf.org/status.html) -- you should be only using it with trusted HTML/JS.
