### ISSUE TITLE
static build

### ISSUE THREAD

**Issue by hello983834** [wkhtmltopdf/wkhtmltopdf#4108]
Could you please provide static binaries again?
We have problems with the dynamic builds because they do not support the libraries we use.

You can statically link 100% of all libraries used by wkhtml with the only exception of getaddrinfo() from glibc, but this function is usually always ABI compatible.

_Originally posted by @hello983834 in https://github.com/wkhtmltopdf/wkhtmltopdf/issue_comments#issuecomment-424670026_

**Comment by Tomsgu** [comment]
Please continue here: https://github.com/wkhtmltopdf/packaging/issues/8 .
