### ISSUE TITLE
Not generating Table of contents

### ISSUE THREAD

**Issue by XavierImengine** [wkhtmltopdf/wkhtmltopdf#4111]
Command:
`Invoke-Command  -ScriptBlock {& 'C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe' toc 'https://www.google.com' D:\google.pdf}` (powershell)

Installer:
`wkhtmltox-0.12.5-1.msvc2015-win64.exe` 

result:
`NOT generating any Table of content`

output:
```
Loading pages (1/6)
Warning: SSL error ignored
Warning: SSL error ignored
Warning: SSL error ignored
Warning: SSL error ignored
Counting pages (2/6)
Loading TOC (3/6)
Resolving links (4/6)
Loading headers and footers (5/6)
Printing pages (6/6)
Done
```

Installer:
`wkhtmltox-0.12.4_msvc2015-win64.exe`

result:
`generating table of content correctly`

output:
```
Loading pages (1/6)
Warning: SSL error ignored
Warning: SSL error ignored
Warning: SSL error ignored
Warning: SSL error ignored
Counting pages (2/6)
Loading TOC (3/6)
Resolving links (4/6)
Loading headers and footers (5/6)
Printing pages (6/6)
Done

```

**Comment by Tomsgu** [comment]
Hi,
It’s a known bug that was fixed already. Unfortunately there is no stable release 0.12.6 yet. See #3953

**Comment by ashkulz** [comment]
A release candidate for the **0.12.6** release is [now available for download](https://wkhtmltopdf.org/downloads.html#release-candidate), which should contain changes which possibly address this issue.

Would appreciate downloading the package and reporting back if any issues are encountered during testing. Assuming all goes well, I plan to release 0.12.6 on the 2-year anniversary of the previous release i.e. June 11, 2020.
