### ISSUE TITLE
Size other than pixel are not producing correct output

### ISSUE THREAD

**Issue by CPASimUSante** [wkhtmltopdf/wkhtmltopdf#4113]
I'm using wkhtmltopdf 0.12.4 (with patched qt) in a Symfony project (but it's irrelevant here because the vanilla wkhtmltopdf shows the issue), on a Debian 8 server.

My goal is to create sticker sheets pdf. 
My sheet is A4, and i want in this test page 2 columns of half page width : 

```
<!DOCTYPE html>
<html lang="fr">
<head>
  <meta charset="utf-8">
</head>
<body style="margin:0;padding:0">
  <div style="background-color:red;width:99%;height:1400px;border:solid #000 1px">
    <div style="background-color:green;display:inline-block;padding:0;margin:0;width:105mm;height:297mm">col1</div>
    <div style="background-color:yellow;display:inline-block;padding:0;margin:0;width:105mm;height:297mm">col2

</div>
  </div>
</body>
</html>
```
and i test it 

wkhtmltopdf --page-size A4 -B 0 -L 0 -R 0 -T 0 test.html output.pdf
i've also tried 
wkhtmltopdf --page-width 210mm --page-height 297mm -B 0 -L 0 -R 0 -T 0 test.html output.pdf

and i also tried the width in inches.
They all give the same output : 
[output.pdf](https://github.com/wkhtmltopdf/wkhtmltopdf/files/2445460/output.pdf)

Is something wrong with the settings in the wkhtmltopdf or in the css or is it a bug ?

**Comment by PhilterPaper** [comment]
First of all, what results are you _expecting_, as opposed to what you got? Should the yellow and green fill the entire width of the page? In my Reader, the red is about 215mm wide and the other two colors are 95mm wide each, at 100% scale.

Keep in mind that pixels (px) are a device-dependent measurement -- different on any display or printer. You might get some control by setting the dpi (dots per inch), to turn them into an absolute measurement like pt or in. Finally, there are relative measurements such as % and em.

**Comment by CPASimUSante** [comment]
well, i indeed expect that the green and the yellow block fill the full width of the page : For A4 size (210mm), setting 2 blocks of 105mm should be the solution ... Am i wrong ?

**As i stated, (and put in my example) i used mm (and also tried the inches equivalent)** but with no luck.
Nowhere have i used here px measurement for width (in the example i have set the height in px to show the full A4 height, but if i remove this height, the width doesn't change)

I gave the test html, the wkhtmltopdf version i use and the command i used : if you obtain on your side a half green / half yellow page, maybe there is a problem on my configuration. I'm really sorry if i missed something obvious.
How would you achieve what i need : 2 halves with absolute measurements (millimeter, inch are ok too)

Thank you for taking the time to go through my problem

**Comment by CPASimUSante** [comment]
Well, after some investigation it seems that the problem lies in the default value : the pdf is correct if i add the --disable-smart-shrinking option.

**Comment by christoferd** [comment]
--disable-smart-shrinking
