### ISSUE TITLE
 Failed to load http://true/

### ISSUE THREAD

**Issue by dinhducit** [wkhtmltopdf/wkhtmltopdf#4116]
> 2018-10-07 20:37:40.049  INFO 88172 --- [nio-8080-exec-6] : Start generate pdf file
> Loading pages (1/6)
> [>                                                           ] 0%
> [===>                                                        ] 5%
> [======>                                                     ] 10%
> 
> Error: Failed to load http://true/, with network status code 3 and http status code 0 - Host true not found
> 
> Error: Failed loading page http://true (sometimes it will work just to ignore this error with --load-error-handling ignore)
> [======>                                                     ] 10%
> [======>                                                     ] 11%
> [=======>                                                    ] 13%
> [=========>                                                  ] 15%
> [=========>                                                  ] 16%
> [==========>                                                 ] 17%
> Warning: undefined:0 TypeError: 'undefined' is not a function     
> [==========>                                                 ] 18%
> [===========>                                                ] 19%
> [============>                                               ] 20%
> [============>                                               ] 20%
> [============>                                               ] 21%
> [============>                                               ] 21%
> [=============>                                              ] 22%
> [=============>                                              ] 22%
> [=============>                                              ] 23%
> [=============>                                              ] 23%
> [==============>                                             ] 24%
> [==============>                                             ] 24%
> [===============>                                            ] 25%
> [===============>                                            ] 26%
> [===============>                                            ] 26%
> [================>                                           ] 27%
> [================>                                           ] 28%
> [================>                                           ] 28%
> [=================>                                          ] 29%
> [=================>                                          ] 29%
> [==================>                                         ] 30%
> [==================>                                         ] 31%
> [===================>                                        ] 32%
> [===================>                                        ] 33%
> [====================>                                       ] 34%
> [=====================>                                      ] 35%
> [=====================>                                      ] 35%
> [=====================>                                      ] 36%
> [======================>                                     ] 37%
> [======================>                                     ] 38%
> [=======================>                                    ] 39%
> [========================>                                   ] 40%
> [========================>                                   ] 41%
> [=========================>                                  ] 42%
> [=========================>                                  ] 43%
> [=========================>                                  ] 43%
> [==========================>                                 ] 44%
> [===========================>                                ] 45%
> [===========================>                                ] 46%
> [============================>                               ] 47%
> [============================>                               ] 48%
> [=============================>                              ] 49%
> [=================================>                          ] 55%
> Exit with code 1 due to network error: HostNotFoundError
> 

I faced that issue, by I don't know why, I used java code to try to export an angular 6 page.
`Process pr = rt.exec(new String[] { exportProgramCommand, "--javascript-delay", "5000", "--debug-javascript", "true", "http://localhost:4200/", fileName });`

Please advice.

**Comment by xiegeo** [comment]
```
      --debug-javascript              Show javascript debugging output
      --no-debug-javascript           Do not show javascript debugging output
                                      (default)
```

You don't need "true" here since `--debug-javascript` does not take an argument.

**Comment by dinhducit** [comment]
@xiegeo thanks for your feedback.
I updated process to:
`Process pr = rt.exec(new String[] { exportProgramCommand, "--javascript-delay", "5000", "--debug-javascript", url, fileName });`
and I got new issue:

> Start generate pdf file
> http://localhost:4200/download/1e9d53fe-3170-4a4e-8231-473eb9e86075
> Loading pages (1/6)
> [>                                                           ] 0%
> [======>                                                     ] 10%
> [======>                                                     ] 10%
> [=======>                                                    ] 13%
> [=============>                                              ] 22%
> [==========================>                                 ] 44%
> [=============================>                              ] 49%
> [==============================>                             ] 50%
> Warning: undefined:0 TypeError: 'undefined' is not a function     
> [============================================================] 100%
> Counting pages (2/6)                                               
> [============================================================] Object 1 of 1
> Resolving links (4/6)                                                       
> [============================================================] Object 1 of 1
> Loading headers and footers (5/6)                                           
> Printing pages (6/6)
> [>                                                           ] Preparing
> Done                                           

But the HTML run without error on a browser:
     
<img width="891" alt="screen shot 2018-10-08 at 16 51 59" src="https://user-images.githubusercontent.com/13290578/46602596-d6e94480-cb1a-11e8-8428-1aff96301e4e.png">

Please advice.

**Comment by xiegeo** [comment]
From a quick search, Angular 6 supports webkit/safari 7 and up, but wkhtmltopdf is on webkit 5. 

Try prerendering the html https://angular.io/guide/universal

**Comment by Tomsgu** [comment]
Closing as there is nothing we can do about it until rendering engine will be updated.
