### ISSUE TITLE
Wkhtmltopdf with centos server, crash output  

### ISSUE THREAD

**Issue by tejastank** [wkhtmltopdf/wkhtmltopdf#4127]
https://stackoverflow.com/questions/52741292/wkhtmltopdf-with-centos-server-crash-output-text

![test](https://user-images.githubusercontent.com/311413/46743133-08eada00-ccc6-11e8-8209-9958870c031e.png)

exact same PDF issue.

How this happen ?

**Comment by Tomsgu** [comment]
Can you post more information about the issue?
- What is your OS exactly
- What is your wkhtmltopdf version? Try 0.12.5.
- Post a minimal test example. It's not enough to just post an image.

If you post a stackoverflow link, please continue there. Without additional details we can't help here.

**Comment by tejastank** [comment]
@Tomsgu Very disappointed on your words, anyhow below details for you, in case you able to resolve.

CentOS Linux release 7.5.1804 (Core)

Command Used:

sudo wkhtmltopdf --encoding 'utf-8' https://www.google.co.in/ test.pdf

system command locale

locale

LANG=en_IN
LC_CTYPE="en_IN"
LC_NUMERIC="en_IN"
LC_TIME="en_IN"
LC_COLLATE="en_IN"
LC_MONETARY="en_IN"
LC_MESSAGES="en_IN"
LC_PAPER="en_IN"
LC_NAME="en_IN"
LC_ADDRESS="en_IN"
LC_TELEPHONE="en_IN"
LC_MEASUREMENT="en_IN"
LC_IDENTIFICATION="en_IN"
LC_ALL=


CentOS Linux release 7.5.1804 (Core)

**Comment by Tomsgu** [comment]
It seems the font is missing in your system. Be sure to have installed these two packages: `xorg-x11-fonts-75dpi` `xorg-x11-fonts-Type1`

**Comment by tejastank** [comment]
@Tomsgu great thanks for right direction.

I had fired below command

sudo yum install fontconfig libXrender libXext xorg-x11-fonts-Type1 xorg-x11-fonts-75dpi freetype libpng zlib libjpeg-turbo

This resolved my issue.

Thanks,
Tejas Tank,
SnippetBucket.com
