### ISSUE TITLE
0.12.5 regression: errors during generation

### ISSUE THREAD

**Issue by victorovich2004** [wkhtmltopdf/wkhtmltopdf#4129]
This example from help:
wkhtmltopdf toc http://qt-project.org/doc/qt-4.8/qstring.html qstring.pdf
produces many loading errors, but on 0.12.4 everything is totally clean!

**Comment by Tomsgu** [comment]
This is most likely because of a known bug that was resolved here #3953. Can you try it in the dev 0.12.6 version?

**Comment by victorovich2004** [comment]
where can I find link to **binaries** for 0.12.6 ???

**Comment by Tomsgu** [comment]
@victorovich2004 any updates on this?

**Comment by victorovich2004** [comment]
Sorry, don't have a time to setup buid environment.
With binaries it is easy to reproduce a bug. Simply execute:
wkhtmltopdf toc http://qt-project.org/doc/qt-4.8/qstring.html qstring.pdf

**Comment by hakimio** [comment]
0.12.6 binaries -> https://builds.wkhtmltopdf.org/0.12.6-dev/

**Comment by ashkulz** [comment]
A release candidate for the **0.12.6** release is [now available for download](https://wkhtmltopdf.org/downloads.html#release-candidate), which should contain changes which possibly address this issue.

Would appreciate downloading the package and reporting back if any issues are encountered during testing. Assuming all goes well, I plan to release 0.12.6 on the 2-year anniversary of the previous release i.e. June 11, 2020.
