### ISSUE TITLE
Pages numbers in TOC are incorrect

### ISSUE THREAD

**Issue by victorovich2004** [wkhtmltopdf/wkhtmltopdf#4142]
I have a big PDF document created from a lot of .html's, some pages are included into the TOC. But near to the end of file page numbers displayed in TOC are not identical to page numbers they are refer actually. The difference can be 1-15 pages on a 1000-pages document. For example, real page number is 505 (displayed in footer), but in TOC I see 500 (less than real).
Version: 0.12.4 (in 0.12.5 TOC is unaccesible)
OS: Windows
Source file canno be attached because of confidentiality.
**Is it known bug?**

**Comment by Tomsgu** [comment]
This was fixed in 0.12.6 #3952
Toc not generated was fixed in 0.12.6 too #3953 

All you can find when you use search issues functionality.

**Comment by ashkulz** [comment]
A release candidate for the **0.12.6** release is [now available for download](https://wkhtmltopdf.org/downloads.html#release-candidate), which should contain changes which possibly address this issue.

Would appreciate downloading the package and reporting back if any issues are encountered during testing. Assuming all goes well, I plan to release 0.12.6 on the 2-year anniversary of the previous release i.e. June 11, 2020.
