### ISSUE TITLE
wkhtmltopdf for Windows fails while Mac version succeed

### ISSUE THREAD

**Issue by mcgitty** [wkhtmltopdf/wkhtmltopdf#4147]
**wkhtmltopdf version(s) affected**: 0.12.5 

**OS information**
Win32/Win64

**Description**
Both 32-bit and 64-bit Windows version failed to convert a public site while the Mac version works fine. The command window output of the run also differs greatly, suggesting the Windows ones only have 2 steps compared to the 6 steps for Mac.

**How to reproduce**
wkhtmltopdf http://www.dopdf.com/ dopdf.pdf

**Expected behavior**
Loading pages (1/6)
...
Printing pages (6/6)
Done

**Unexpected behavior**
REM Failed with Windows version
wkhtmltoimage http://www.dopdf.com/ dopdf.pdf
Loading page (1/2)
...
Rendering (2/2)
Warning: Received createRequest signal on a disposed ResourceObject's NetworkAccessManager. This might be an indication of an iframe taking too long to load.
...
Error: Failed to load about:blank, with network status code 301 and http status
code 0 - Protocol "about" is unknown
Exit with code 1, due to unknown error.

**Possible Solution**  
None

**Comment by PhilterPaper** [comment]
If you ran the *image program for Windows, it probably will behave differently (e.g., 2 steps instead of 6) than the *pdf program you ran on Mac. You're not comparing McIntoshes to McIntoshes here. Does wkHTMLtoPDF on Windows fail, and/or does wkHTMLtoImage on Mac work?

**Comment by mcgitty** [comment]
Sorry, it must've been command line auto-complete that ran `wkhtmltoimage` as shown in the log. The Windows version of `wkhtmltopdf` also ran fine with 6 steps.

**Comment by PhilterPaper** [comment]
Still, wkHTMLtoImage should have run correctly, but if you're not using it, it's up to you whether to pursue it any further.
