### ISSUE TITLE
HTML Tables not displaying correctly over 2 or more pages

### ISSUE THREAD

**Issue by tychovbh** [wkhtmltopdf/wkhtmltopdf#4160]
**wkhtmltopdf version(s) affected**: x.y.z 
wkhtmltopdf 0.12.3 (with patched qt)

**OS information**
Chrome browser

**Description**
I'm trying to convert a html table to a pdf. The table is a loop of data. When the table goes to a second page because it is big. Sometimes table information from page 1 is displayed over the table information in page 2. It overlaps.

**Expected behavior**
The table should be displayed perfectly over 2 pages or more pages.

**Images**
In the images you can see that text from the first page is also shown on the second page overlapping other teksts.
<img width="930" alt="screen shot 2018-10-28 at 13 29 21" src="https://user-images.githubusercontent.com/5880561/47618751-98113380-dab5-11e8-8d0d-d2156b3ac111.png">

<img width="862" alt="screen shot 2018-10-28 at 13 29 31" src="https://user-images.githubusercontent.com/5880561/47618752-98113380-dab5-11e8-92a1-8fb190d9b722.png">

<img width="892" alt="screen shot 2018-10-28 at 13 29 40" src="https://user-images.githubusercontent.com/5880561/47618753-98113380-dab5-11e8-8da2-28dcdac14e14.png">

**Comment by PhilterPaper** [comment]
Do a search on table headings (thead) and you will find much discussion already on the subject. Duplicate.
