### ISSUE TITLE
Background image in header is displayed on top of the content

### ISSUE THREAD

**Issue by cdegallaix** [wkhtmltopdf/wkhtmltopdf#4164]
Hello,

I am trying to set a full page background image following the solution described in this issue: [https://github.com/wkhtmltopdf/wkhtmltopdf/issues/3880](https://github.com/wkhtmltopdf/wkhtmltopdf/issues/3880). 

In short, I create a header html file with the image in it and that image cover the entire page. As it is defined in the header, it is correctly repeated on every pages.

It is working fine but I cannot make the image defined in the header to be displayed behind the pdf content. The header content is always rendered on top of the content (see attachments). 

Is there any solution in order to force the content to always be on the top?

Here is a file without a background applied
[without_background.pdf](https://github.com/wkhtmltopdf/wkhtmltopdf/files/2534341/without_background.pdf)

Here is a file with a background applied (it renders the image on top of the company info)
[with_background.pdf](https://github.com/wkhtmltopdf/wkhtmltopdf/files/2534330/with_background.pdf)

Any ideas ?

**Comment by xiesamgh** [comment]
hi @cdegallaix , did you find a solution? I'm facing the completely same trouble.
