### ISSUE TITLE
Why does the 0.12.5 version not release the Linux generic version, or it is based on the SUSE 12.2 release?

### ISSUE THREAD

**Issue by lcycbm** [wkhtmltopdf/wkhtmltopdf#4178]
wkhtmltopdf has its own dedicated repository for packaging. Please open your
packaging-related issue at https://github.com/wkhtmltopdf/packaging

Thanks!

**Comment by Tomsgu** [comment]
It was discussed many times. Go to packaging repository and search for your answer in issues.
