### ISSUE TITLE
Unnecessary Space in tr  

### ISSUE THREAD

**Issue by UIPankaj** [wkhtmltopdf/wkhtmltopdf#4182]
**wkhtmltopdf version(s) affected**: wkhtmltox-0.12.5-1.msvc2015-win64

**OS information**
Windows

**Description**
Getting unnecessary space in tr when I am using div inside td

**How to reproduce**
this is the structure of tr which I am repeating.It work fine when we remove all the div from td and place data simply inside the td. 
<tr>
<td style="">
<div align="right" style="margin-top: 3px;margin-bottom: 3px;">0001</div>
</td>
<td style="">
<div align="left" style="margin-top: 3px;margin-bottom: 3px;"></div>
</td>
<td style="">
<div align="left" style="margin-top: 3px;margin-bottom: 3px;">123123hkgyug123</div>
</td>
<td style="">
<div align="left" style="margin-top: 3px;margin-bottom: 3px;"></div>
</td>
<td style="">
<div align="left" style="margin-top: 3px;margin-bottom: 3px;">Rush hour</div>
</td>
<td style="">
<div align="right" style="margin-top: 3px;margin-bottom: 3px;">22,481</div>
</td>
<td style="">
<div align="center" style="margin-top: 3px;margin-bottom: 3px;;white-space: nowrap;">09-13-2017</div>
</td>
<td>
<div align="right" style="margin-top: 3px;margin-bottom: 3px;">
<div>264195</div>
</div>
</td>
<td>
<div align="right" style="margin-top: 3px;margin-bottom: 3px;">$54.27</div>
</td>
<td>
<div align="right" style="margin-top: 3px;margin-bottom: 3px;">$0.00</div>
</td>
<td>
<div align="right" style="margin-top: 3px;margin-bottom: 3px;">$0.00</div>
</td>
<td>
<div align="right" style="margin-top: 3px;margin-bottom: 3px;">$0.00</div>
</td>
</tr>

![templateblankspacetr](https://user-images.githubusercontent.com/43956603/48757802-f51e9480-ecc3-11e8-8a71-0878f915d909.png)

**Comment by PhilterPaper** [comment]
Reported at least twice before: #3766 and #3405. Perhaps those can give a clue to a fix.

**Comment by UIPankaj** [comment]
Thanks for the reply,
yes solution there, that we need to use inline-block elements instead of block elements.
So this is the limitation we have.

**Comment by vielhuber** [comment]
All those tickets are closed. But the problem persists in 0.12.5 with patched qt.
Does anybody have an update on this?

**Comment by assendk** [comment]
my workaround: my cell/td has a class, i draw a div inside the table cells/column and set inline-block style. The unexpected space is gone
.td_class div {
            display: inline-block;
        }
