### ISSUE TITLE
Chinese character unicode encoding problem

### ISSUE THREAD

**Issue by zhangjianzhi1989** [wkhtmltopdf/wkhtmltopdf#4202]
**wkhtmltopdf version(s) affected**: 0.12.5 (with patched qt)

**OS information**

mac os 10.11.6

**Description**

The unicode encoding of Chinese characters is different in html and pdf.

On the left is the html code，On the right is the pdf code.

行（\u884c）---- ⾏（\u2f8f）
方（\u65b9）---- ⽅（\u2f45）
人（\u4eba）---- ⼈（\u2f08）

Html encoding is utf-8.

Open pdf file with Adobe Acrobat Reader DC.

**Comment by PhilterPaper** [comment]
For all three characters, the Unicode standard shows the 2F__ characters (on the right) in the "Kangxi Radicals" section, and lists the "HTML code" equivalent (on the left) in "CJK Unified Ideographs" with an "approximately equal" sign. Visually they certainly _look_ the same, but I couldn't tell you if they are in fact interchangeable _in the language_. So the question at hand is "does any software have the right to transform certain CJK Ideographs to their (visually equivalent) Kangxi forms?"

As for _who_ is doing it, are you confident that the HTML (CJK Unified Ideographs) is what's being fed into wkHTMLtoPDF, and some file transfer didn't change it to Kangxi behind your back? (before it got to wkHTMLtoPDF)

**Comment by zhangjianzhi1989** [comment]
@PhilterPaper - thank you very much for your reply，I think my problem has been solved.
