### ISSUE TITLE
The wkhtmltopdf.org certificate has expired

### ISSUE THREAD

**Issue by charlieegan3** [wkhtmltopdf/wkhtmltopdf#4208]
It appears to have expired today `Valid from September 20, 2018 to December 19, 2018`

**Comment by egyptianbman** [comment]
I switched to using the github release links: https://github.com/wkhtmltopdf/wkhtmltopdf/releases/tag/0.12.5

**Comment by whiny-nil** [comment]
It looks like the site is back up, so thanks for taking care of that!

**Comment by charlieegan3** [comment]
We also switched to the GH releases. Thanks for fixing! :slightly_smiling_face:
