### ISSUE TITLE
Global option - "--copies" is simply not working when generating a pdf. 

### ISSUE THREAD

**Issue by faiyeah** [wkhtmltopdf/wkhtmltopdf#4211]
**wkhtmltopdf version(s) affected**: 
wkhtmltopdf 0.12.5 (with patched qt)
                 
**OS information**
Darwin Fais-MacBook-Pro.local 17.7.0 Darwin Kernel Version 17.7.0: Fri Nov  2 20:43:16 PDT 2018; root:xnu-4570.71.17~1/RELEASE_X86_64 x86_64 i386

Per my experiment, the same issue happened even in CentOS 7.4 (with the same version of wkhtmltopdf)

**Description**
Global option - "--copies" is simply not working when generating a pdf. No matter how many copies specified, the number of outputted pages and the size of the resulting file keeps the same. 

**How to reproduce**
Fais-MacBook-Pro:clouderp-master faiyeah$ wkhtmltopdf --collate --copies 10 www.google.com.hk google.pdf
Loading pages (1/6)
Counting pages (2/6)                                               
Resolving links (4/6)                                                       
Loading headers and footers (5/6)                                           
Printing pages (6/6)
Done                            

**Expected behavior**
I would expect there are 10 pages with the identical content, however, only 1 page is outputted. For the problematic output file, please see the attachment in this ticket.

**Comment by PhilterPaper** [comment]
Is `--copies` supposed to put multiple copies into the PDF itself, or to tell the _printer_ to print that many copies? I can't imagine why you'd want to put 10 identical pages into a PDF file, rather than telling the printer to produce 10 copies of a single page. Which way are you expecting it to work? More importantly, does it produce 10 pages on a printer, rather than in the file?

**Comment by faiyeah** [comment]
Well, the copies option looks confused to me.

I really intend to produce a 10 identical pages into the pdf file (this is due to my application need), and thought the copies option is the right way to do so.

It would be nice if someone can clarify the expected behavior of this option. 

Many thanks.

Best regards,
Ryan Chan
- sent from my iPhone

**Comment by PhilterPaper** [comment]
PDF (1.7) defines a **NumCopies** entry in Viewer Preferences, to prefill a print dialog with the number of copies desired. However, I don't see that defined in the wkHTMLtoPDF code.

The help file certainly _does_ say, "Number of copies to print into the pdf file (default 1)", but from CHANGELOG.md's "correctly pass --copies to underlying QPrinter" I'm interpreting that to mean "number of copies to print" into some place in the PDF file -- it really makes no sense to duplicate a page N times to get N copies.

If you really need to have N identical pages in a PDF, it can be done. You could produce a single page and then use one of many PDF utilities (e.g., PDFtk) to merge multiple PDF files together, perhaps even N at once, if N isn't unreasonably large. I'm guessing that you have some utility that operates on the combined PDF file to modify individual pages?

**Comment by faiyeah** [comment]
Thanks for your clarification. 

If your interpretation is correct, this issue would be invalid. However, I would recommend a description update in the help file to avoid future confusion. It is difficult for a user to relate this option to the prefilled print copies in pdf 1.7 without your clarification. 

“It really makes no sense to duplicate a page N times to get N copies.” - well. This is my application logic to require this. I may not the right one to judge whether if the library makes sense to support this. But it is true that there are plenty of workarounds in my application levels and it works well. 

Please close this issue accordingly and thanks for your help again.

Many thanks.

Best regards,
Ryan Chan
- sent from my iPhone

**Comment by PhilterPaper** [comment]
As you opened it, you should be able to close it yourself. I certainly can't.
