### ISSUE TITLE
Square character issue for Urdu language to wkhtmltopdf

### ISSUE THREAD

**Issue by virajdhamal** [wkhtmltopdf/wkhtmltopdf#4213]
**wkhtmltopdf version(s) affected**:  0.12.5

**OS information**
Ubuntu 16.04

**Description**
I have installed wkhtmltopdf on Ubuntu 16.04. Whenever i generate PDF for Urdu text using wkhtmltopdf some square characters are displayed in PDF. As per my analysis this is not an UTF-8 issue because PDF get generate correctly for English, Marathi, Hindi, Arabic and Oriya languages. I have also installed ttf-Nafees font on ubuntu. Still square characters get displayed in PDF.

I have try same thing on ubuntu desktop 16.04. Everything working fine on it but when i try it on ubuntu server 16.04 its not working.

Sample image is given below for reference.
![urdu](https://user-images.githubusercontent.com/43602973/50587467-16b69280-0ea4-11e9-8b5b-eb6b41bea6e4.png)

**How to reproduce**
Add Urdu text on html page and generate pdf for this page

**Expected behavior**
Urdu text displayed properly after PDF generation

**Comment by PhilterPaper** [comment]
Sounds a lot like #2349. Same questions as I asked there.

**Comment by virajdhamal** [comment]
Thank for reply PhilterPaper. I have added 
`font-family: 'Jameel Noori Nastaleeq','Alvi Nastaleeq','Pak Nastaleeq','Nafees Web Naskh','Urdu Naskh Asiatype',Tahoma,'Lucida Grande',Verdana,Arial,Sans-Serif;` 
on html page. After that issue get resolved. Installed fonts not get referred before this.

**Comment by kavishatalsania** [comment]
Hi @virajdhamal,

I've install font-nafees in my machine.
https://ubuntu.pkgs.org/16.04/ubuntu-main-amd64/fonts-nafees_1.2-5ubuntu1_all.deb.html

Also add font-family `font-family: 'Arial Black, NafeesNastaleeq, NafeesWeb, NafeesRegular';` still some characters are not rendering properly.

I am doing anything wrong? 

Any help is appreciated.

**Comment by virajdhamal** [comment]
Hi @kavishatalsania ,
Please follow the steps given below -

1.  Install ttf-indic-fonts-core on ubuntu server. 

2. Create css file with script given below-
div, table, tr, td, span, p, label, th {  
 		 font-family: 'Jameel Noori Nastaleeq','Alvi Nastaleeq','Pak Nastaleeq','Nafees Web Naskh','Urdu Naskh Asiatype',Tahoma,'Lucida Grande',Verdana,Arial,Sans-Serif;
	}

    (You can add required tags in css as per your requirement)

3. Pass above css file path to wkhtmltopdf commands using --user-style-sheet {filepath} attribute
e.g. --user-style-sheet {filepath}/wkhtmltopdfFontFamily.css

4. Use patched qt version of wkhtmltopdf

5. After doing above steps still issue in generating pdf the add fonts given below on ubuntu server and check again-

- alvi_Nastaleeq.ttf

- alvi_Nastaleeq_Lahori_shipped.ttf

- ARABTYPE.TTF

- asunaskh.ttf

- Fajer Noori Nastalique.ttf

- Jameel Noori Nastaleeq Kasheeda.ttf

- Jameel Noori Nastaleeq.ttf

- Nafees Nastaleeq v1.02(VOLT project).ttf

- Pak Nastaleeq (Beta Release).ttf
