### ISSUE TITLE
Qt WebEngine

### ISSUE THREAD

**Issue by bparker06** [wkhtmltopdf/wkhtmltopdf#4224]
According to https://trac.webkit.org/wiki/BuildingQtOnLinux:

`QT is no longer a supported port of WebKit since 2013`

And given that WebKit is no longer even a part of the Qt source... are there plans to move over to WebEngine instead?

**Comment by vildric** [comment]
Would like to know too...

**Comment by ashkulz** [comment]
Not really, Puppeteer is a better solution (which works right now, without some features). I'm planning to upgrade to QtWebKit 2.212 and see if I can upgrade to the latest WebKit version, if time permits :man_shrugging:

**Comment by blshkv** [comment]
Hello. 

I'm trying to migrate all packages from WebKit to WebEngine and wkhtmltopdf is the only package left which requires webkit. Could you consider supporting both optionally?

https://doc.qt.io/qt-5/qtwebenginewidgets-qtwebkitportingguide.html
