### ISSUE TITLE
Only convert HTML to PDF the first time

### ISSUE THREAD

**Issue by IvanRio** [wkhtmltopdf/wkhtmltopdf#4226]
**wkhtmltopdf version(s) affected**: 0.12.5

**OS information**
Windows 10 Pro

**Description**
I'm trying to convert HTML files into PDF files using the C++ library.
I call a function that has all the functionality (init-create-convert-deinit) 
but only generate the first PDF correctly. 

The rest of calls the PDF is generated but does not convert HTML tags, ie the rest of times the PDF has only plain text

Any ideas?

Thank you in advance

**How to reproduce**
extern "C" __declspec(dllexport) wchar_t* ConvertHtmlToPDF2()
{

	wkhtmltopdf_global_settings * gs;
	wkhtmltopdf_object_settings * os;
	wkhtmltopdf_converter * c;

	wkhtmltopdf_init(true);
	CString sVersion=wkhtmltopdf_version();

	gs = wkhtmltopdf_create_global_settings();
	wkhtmltopdf_set_global_setting(gs, "out", "D:\\buzon\\Borrar\\prueba3.pdf");
	wkhtmltopdf_set_global_setting(gs, "margin.top", "0");
	wkhtmltopdf_set_global_setting(gs, "margin.bottom", "0");
	wkhtmltopdf_set_global_setting(gs, "load.cookieJar", "myjar.jar");

	os = wkhtmltopdf_create_object_settings();	
	wkhtmltopdf_set_object_setting(os, "page", "D:\\buzon\\Borrar\\carta4.html");

	c = wkhtmltopdf_create_converter(gs);

	wkhtmltopdf_add_object(c, os, NULL);

	if (!wkhtmltopdf_convert(c))
	{
		CString strError=_T("Convertion failed!");
	}

	wkhtmltopdf_destroy_converter(c);
 	wkhtmltopdf_destroy_object_settings(os);
	wkhtmltopdf_destroy_global_settings(gs);

	wkhtmltopdf_deinit();
 }

**Comment by PhilterPaper** [comment]
When you say "the first PDF", does that mean that you are calling this in a loop or concurrently? I think I've seen this before, and the problem was that the code was non-reentrant, so external files all had the same name and were overwriting each other (or something to that effect). The first thing would be to check that unique file names (both temporary and output) are being used for each invocation of the code. You can't run the second conversion until the first has finished, and so on.

**Comment by IvanRio** [comment]
Thanks for the answer, but that's not the solution.

I don't call the second time until the first time is over, and I always delete the output file before calling the second time.

Any other idea of what it might be?

To me the only thing that has occurred to me is to create a separate dll and that my program loads it and unload it that once I call it, for that way it is always the first time.


________________________________
De: Phil Perry <notifications@github.com>
Enviado: Saturday, January 12, 2019 4:50:32 AM
Para: wkhtmltopdf/wkhtmltopdf
Cc: IvanRio; Author
Asunto: Re: [wkhtmltopdf/wkhtmltopdf] Only convert HTML to PDF the first time (#4226)


When you say "the first PDF", does that mean that you are calling this in a loop or concurrently? I think I've seen this before, and the problem was that the code was non-reentrant, so external files all had the same name and were overwriting each other (or something to that effect). The first thing would be to check that unique file names (both temporary and output) are being used for each invocation of the code. You can't run the second conversion until the first has finished, and so on.

**Comment by PhilterPaper** [comment]
> The rest of calls the PDF is generated but does not convert HTML tags, ie the rest of times the PDF has only plain text

Can you elaborate on this? Is it _ignoring_ HTML tags (treating them as plain text, and they appear in the PDF), or is is simply _stripping out_ HTML tags, leaving only plain text? Does this apply to all tags, or just some? I still have no idea why it would work the first time, and fail every time after. What is needed to "reset" to the "first" time? Some length of time, a reboot, or something else? That might give a clue. You've confirmed that nothing "left over" from the first run (command line debris or data files) is messing up subsequent runs?

**Comment by brwsoftware** [comment]
I experienced something similar.

If I converted a number of html files in a loop, the first one would convert properly and the others would display unformatted html.

I had written a win32 desktop application to experiment with wkhtmltopdf.

I was able to resolve this by calling **wkhtmltopdf_init** during application startup and **wkhtmltopdf_deinit** at shutdown.

For example:
**The issue would occur when doing something like the following:**
```
MyWindow::OnButtonClick()
{
   wkhtmltopdf_init
   for(int I=0; I< 50; I++)
   {
      do the conversion...   
   }
   wkhtmltopdf_deinit
}
```
**If I did the following, all files converted properly**
```
MyApp::OnStartup()
{
   wkhtmltopdf_init
}

MyWindow::OnButtonClick()
{
   for(int I=0; I< 50; I++)
   {
      do the conversion...   
   }
}

MyApp::OnShutdown()
{
   wkhtmltopdf_deinit
}

```

Hope this helps.

**Comment by IvanRio** [comment]
Thanks for the information, but it keeps failing me, I put "**wkhtmltopdf_init**" inside my "**InitInstance**" i.e. it only runs once when starting the application and I haven't put "wkhtmltopdf_deinit", and we continue as always, it only generates the pdf correctly the first time.

Any other idea would be appreciated

**Comment by brwsoftware** [comment]
Nothing really comes to mind.
If you want to upload your code I'd be happy to take a look.

**Comment by IvanRio** [comment]
This is the function I call "ConvertHtmlToPDF", the first time it does well and the following times the generated pdf has the plain text.
The function "wkhtmltopdf_init(true);" is only found in InitInstace so that it is only called once.
I have also tried having the function "wkhtmltopdf_init(true);" and "wkhtmltopdf_deinit();" at the beginning and end of my function "ConvertHtmlToPDF" and it does the same.

`void CPDFConverterApp::ConvertHtmlToPDF()
{
	try
	{

	wkhtmltopdf_global_settings * gs;
	wkhtmltopdf_object_settings * os;
	wkhtmltopdf_converter * c;

	CString sVersion=wkhtmltopdf_version();

	/*
	 * Create a global settings object used to store options that are not
	 * related to input objects, note that control of this object is parsed to
	 * the converter later, which is then responsible for freeing it
	 */
	gs = wkhtmltopdf_create_global_settings();
	/* We want the result to be storred in the file called test.pdf */
	wkhtmltopdf_set_global_setting(gs, "out", "D:\\buzon\\Borrar\\prueba3.pdf");

	wkhtmltopdf_set_global_setting(gs, "margin.top", "0");
	wkhtmltopdf_set_global_setting(gs, "margin.bottom", "0");

	wkhtmltopdf_set_global_setting(gs, "load.cookieJar", "myjar.jar");
	/*
	 * Create a input object settings object that is used to store settings
	 * related to a input object, note again that control of this object is parsed to
	 * the converter later, which is then responsible for freeing it
	 */
	os = wkhtmltopdf_create_object_settings();
	/* We want to convert to convert the qstring documentation page */
	wkhtmltopdf_set_object_setting(os, "page", "D:\\buzon\\Borrar\\carta4.html");


	/* Create the actual converter object used to convert the pages */
	c = wkhtmltopdf_create_converter(gs);

	/*
	 * Add the the settings object describing the qstring documentation page
	 * to the list of pages to convert. Objects are converted in the order in which
	 * they are added
	 */
	wkhtmltopdf_add_object(c, os, NULL);

	const char *html = "<b>foo</b>bar";
	wkhtmltopdf_add_object(c, os, html);

	/* Perform the actual conversion */
	const unsigned char *data = NULL;
	unsigned long len=0;
	if (!wkhtmltopdf_convert(c))
	{
		CString strError=_T("Convertion failed!");
	}
	else
	{
		int pepe=0;
		len = wkhtmltopdf_get_output(c, &data);
		pepe++;
	}


	/* Output possible http error code encountered */
	nada=wkhtmltopdf_http_error_code(c);

	/* Destroy the converter object since we are done with it */
	wkhtmltopdf_destroy_converter(c);
 	wkhtmltopdf_destroy_object_settings(os);
	wkhtmltopdf_destroy_global_settings(gs);

	}
	catch(CException* e)
	{
		TCHAR errorDetalle[TAM_ERRORMESSAGE];
		e->GetErrorMessage(errorDetalle, TAM_ERRORMESSAGE);
		e->Delete();
	}
	
}
`

**Comment by TwilightShaw** [comment]
I have also encountered the problem, do you have a solution?

**Comment by IvanRio** [comment]
No, no solution for the moment
