### ISSUE TITLE
Extra space is added in rows with image in cell

### ISSUE THREAD

**Issue by hamster18** [wkhtmltopdf/wkhtmltopdf#4237]
**wkhtmltopdf version(s) affected**: x.y.z 

**OS information**

**Description**

**How to reproduce**

**Expected behavior**

**Possible Solution**

**Comment by hamster18** [comment]
Hi all,

Im currently testing wkhtmltopdf (0.12.5-1) to generate a pdf from a html table.
The table contains an image in every one cell of the row. But I am having an issue, the row gets an extra white space in the output PDF.

This is the command I used: 
"wkhtmltopdf -s A4 -O landscape --header-right [page]/[topage] --disable-smart-shrinking -L 5mm -R 5mm sample.html sample.pdf"

Output [[sample.pdf](https://github.com/wkhtmltopdf/wkhtmltopdf/files/2794591/sample.pdf)] file.

Html [[sample.txt](https://github.com/wkhtmltopdf/wkhtmltopdf/files/2794600/sample.txt)] file.

Sample row with space added: 
![issueextraspace](https://user-images.githubusercontent.com/47018844/51724686-7c5c0000-2099-11e9-9d51-f902f9d9107c.PNG)

Any idea please?

**Comment by PhilterPaper** [comment]
You've checked that this one row has no extra line ends or carriage returns or runs of extra spaces? The row is in the middle of the page, and not at the end near a page break? I think I've seen reports before of extra vertical space on a row (text rows), but don't recall what the solution was.

**Comment by hamster18** [comment]
> You've checked that this one row has no extra line ends or carriage returns or runs of extra spaces? The row is in the middle of the page, and not at the end near a page break? I think I've seen reports before of extra vertical space on a row (text rows), but don't recall what the solution was.

Thank you for your reply @PhilterPaper .
The html looks fine, no page break or extra spaces. 
The issue is already solved by changing the table tag to div.
