### ISSUE TITLE
Why does wkhtmltoimage.exe call AWS?

### ISSUE THREAD

**Issue by rgelb** [wkhtmltopdf/wkhtmltopdf#4254]
When I run this command:

wkhtmltoimage.exe "https://www.xome.com/QWidget/addressImage.aspx?zip=94066&widget=price-history&propertyAddress=115%20Madison%20Ave" foo.jpg

I see calls to AWS.  Why is that?  What exactly is being sent to AWS?  I assumed all the work was being done locally?

https://i.imgur.com/QaKc2i5.png

**Comment by PhilterPaper** [comment]
Have you checked whether any CSS or Javascript files being referenced within the input file live on AWS? Try widening the column showing AWS to see if you can get the complete URL.

**Comment by rgelb** [comment]
You are absolutely correct. Some back end functionality was moved to aws and I want aware off it. My bad. Closing ticket.
