### ISSUE TITLE
Highlighting text is not smooth

### ISSUE THREAD

**Issue by roshanhadal** [wkhtmltopdf/wkhtmltopdf#4266]
**wkhtmltopdf version(s) affected**: wkhtmltopdf 0.12.5 (with patched qt) 

**OS information**
MacOS 10.14.3 and Windows 10 

**Description**
I notice that the text selection in generated PDF is not smooth. Even in the attached screenshot, you can notice that there are multiple light and dark selections.

**How to reproduce**
wkhtmltopdf  --margin-bottom 20.0 --margin-top 20.0 --margin-left 25.0 --margin-right 25.0  --footer-spacing 5  --header-spacing 5 --footer-font-size 8 --orientation Portrait --page-size A4 --no-header-line   --no-footer-line   --enable-forms  --minimum-font-size 11  --page-size A4  --orientation Portrait --footer-right [page]/[toPage] --page-offset 0 /mnt/html2pdf/html/sample2.html /Users/roshanhadal/Desktop/sample-html/manual2.pdf

**Expected behavior**
A clear highlighting as shown in attachment 2.
<img width="1394" alt="highligh-issue-attc1" src="https://user-images.githubusercontent.com/8522615/53417338-683e5200-39fb-11e9-8ae7-0ca8875eea0d.png">
<img width="360" alt="highlight-proper-attc2" src="https://user-images.githubusercontent.com/8522615/53417339-683e5200-39fb-11e9-86e3-0c2aed1be1e2.png">

**Possible Solution**

**Comment by PhilterPaper** [comment]
It looks like the character backgrounds are translucent, and varying overlap among them is causing lighter and darker backgrounds. Can you narrow this down to PDFs produced _only_ on certain platforms, and/or _displayed_ only on certain platforms? It doesn't seem to be a widespread problem. Is there anything odd or different about the HTML used to produce this text? Can you look at the PDF itself and see if character spacing is being adjusted character-by-character, rather than one long run of text?

**Comment by roshanhadal** [comment]
We are primarily running on Ubuntu 16.04. However, the issue exists on Windows and Mac as well. The HTML is simple, rather there are no HTML tags. Its plain text that I have used in order to eliminate any issue with HTML. The PDF generated opens and highlights properly in Acrobat Reader. I am rendering the PDF in my web app using PDF.js. However, I have tried opening other PDFs (not generated by wkhtmltopdf) in my app using PDF.js and they behave as expected w.r.t highlighting. I am not sure how to check the character spacing as you mentioned below. Can you give me pointers?

> Can you look at the PDF itself and see if character spacing is being adjusted character-by-character, rather than one long run of text?

**Comment by PhilterPaper** [comment]
You would have to use an editor (such as ViM or Notepad++) that can display the content _inside_ the PDF file. If you see something like `(Hello World! This is a sentence.) Tj`, it's not doing individual character spacing. If you see `(He) 40 (l) 20 (l) 27 ... ) TJ` style, it is. If you see only binary gibberish, you will first need to uncompress the data stream with a utility such as PDFtk.

I'm confused by your description of the problem existing on all platforms, however it's fine in Acrobat Reader. I'm asking if it's only PDFs produced by wkHTMLtoPDF, or other sources show the same problem? Do some PDF _readers_, such as Acrobat Reader, display a given PDF OK, while others (PDF.js?) don't? That would suggest that the problem is with the PDF reader, not wkHTMLtoPDF. Is it some combination of the source (wkHTMLtoPDF) _and_ reader (PDF.js) that only shows the problem?

**Comment by roshanhadal** [comment]
Below is the content of the PDF after uncompressing using PDFtk. This is in a totally different form compared to what you have stated. I have also attached the entire file so that you can take a look.

> 8 -14 Td <0001> Tj
> 11.5468750 0 Td <0002> Tj
> 7.09375000 0 Td <0003> Tj
> 4.43750000 0 Td <0003> Tj
> 4.43750000 0 Td <0004> Tj
> 8 0 Td <0005> Tj
> 4 0 Td <0006> Tj
> 15.0937500 0 Td <0004> Tj
> 8 0 Td <0007> Tj
> 5.32812500 0 Td <0003> Tj
> 4.43750000 0 Td <0008> Tj
> 8 0 Td <0009> Tj
> 5.32812500 0 Td <0005> Tj
> 4 0 Td <000A> Tj
> 9.76562500 0 Td <000B> Tj
> 8 0 Td <000C> Tj
> 4.43750000 0 Td <000D> Tj
> 6.21875000 0 Td <0005> Tj
> 4 0 Td <000C> Tj
> 4.43750000 0 Td <000D> Tj
> 6.21875000 0 Td <0005> Tj
> 4 0 Td <000E> Tj
> 7.09375000 0 Td <0005> Tj
> 4 0 Td <000D> Tj
> 6.21875000 0 Td <0002> Tj
> 7.09375000 0 Td <000F> Tj
> 8 0 Td <0010> Tj
> 4.43750000 0 Td <0002> Tj
> 7.09375000 0 Td <000F> Tj
> 8 0 Td <0011> Tj
> 7.09375000 0 Td <0002> Tj
> 7.09375000 0 Td <0012> Tj

To answer your doubt in the second para, yes, it is only PDFs produced by wkHTMLtoPDF which is showing the issue. If I open other PDFs in PDF.js they are highlighting fine. Considering the attached file, I am guessing the problem could be in the way I am using wkHTMLtoPDF.

[edit-manual2.pdf](https://github.com/wkhtmltopdf/wkhtmltopdf/files/2922881/edit-manual2.pdf)

**Comment by PhilterPaper** [comment]
`<nnnn> Tj` is writing a single character at a time (nnnn is the hex glyph ID), and the `delta-x delta-y Td` before it appears to be individually placing each character, or at least, adjusting its position. You used TTF (?), so glyph ID format is not surprising. However, the individual placement/adjustment/kerning is a little odd. This was just "plain text" 'Hello World!'? No CSS to do odd things? Just for fun, you might try this again with a "core" font (don't specify a TTF font) and see if it behaves the same way.

**Comment by roshanhadal** [comment]
Yes, it was plain text. I didn't use any CSS. I tried attached HTML with Google Fonts assuming it picked WOFF2. But still the same issue. I used below command. Do you see any issue with command? I am new to wkHtmlToPdf and sorry if I am asking some basic questions.

Can you generate and share a sample PDF from your setup? I would like to see if that gets rendered and highlighted properly in my app?

`wkhtmltopdf  --margin-bottom 20.0 --margin-top 20.0 --margin-left 25.0 --margin-right 25.0  --footer-spacing 5  --header-spacing 5 --footer-font-size 8 --orientation Portrait --page-size A4 --load-error-handling ignore --load-media-error-handling ignore --no-header-line   --no-footer-line   --enable-forms  --minimum-font-size 11  --page-size A4  --orientation Portrait --footer-right [page]/[toPage] --page-offset 0 sample3.html sample3-core.pdf`

[sample3-html.txt](https://github.com/wkhtmltopdf/wkhtmltopdf/files/2923468/sample3-html.txt)

**Comment by PhilterPaper** [comment]
Your edit-manual2.pdf displays fine in Adobe Acrobat Reader, as does the sample3-core.pdf I built from your sample3.html and the command line you gave. Highlighting selection of text is smooth (per word, not per character). Latest wkHTMLtoPDF (0.12.5) on Win10 64 bit.

[sample3-core.pdf](https://github.com/wkhtmltopdf/wkhtmltopdf/files/2923717/sample3-core.pdf)

All I can guess is that PDF.js isn't working right.

**Comment by roshanhadal** [comment]
Thanks, Phill for all the support! Let me check on the PDF.js. Even I feel there could be something related to it. I will circle back once I have figured out.

**Comment by roshanhadal** [comment]
Hi,
I raised the issue with other groups. OCR optimization of PDF solved the issue. Thought of sharing this with you to see if there is an option in WkHtmlToPdf to handle the same. Or can this be enhanced? I am attaching the PDF for your reference.

[sample3-core-optimized.pdf](https://github.com/wkhtmltopdf/wkhtmltopdf/files/2927440/sample3-core-optimized.pdf)

**Comment by PhilterPaper** [comment]
OCR? I thought you were producing this from HTML. Anyway, the "optimized" version is considerably different from the original (and is PDF 1.6 rather than 1.4), but behaves the same on selecting (highlighting) text. I have no idea what this "optimization" did, or how it might apply to wkHTMLtoPDF.

**Comment by roshanhadal** [comment]
We are generating from HTML. OCR Optimization was applied on the PDF generated and that seemed to resolve the highlighting issue. The OCR Optimization is a paid plugin in Adobe Acrobat Reader.

**Comment by roshanhadal** [comment]
Hi,
We were able to resolve this by upgrading PDF.js viewer to the latest version in 1.10.x series. We didn't upgrade to the newer 2.x version due to other incompatibilities. Thanks for all the support. I am closing this issue.
