### ISSUE TITLE
How can I get a standalone version of wkhtmltopdf on linux?

### ISSUE THREAD

**Issue by MassMessage** [wkhtmltopdf/wkhtmltopdf#4287]
On Windows it's pretty easy to have the wktmltopdf in a folder alongside the dll files  and I call from cmd.exe or even my a script program and it works fine.
But on Ubuntu/linux, how can I archive that? 
extracting the .deb files to a folder doesn't make it callable as windows. It always claims some .so file is missing.

**Comment by PhilterPaper** [comment]
Does Linux have some sort of _path_ definition for where to find shared libraries (.so files)? It sounds like either you have to extend that path to look in another place (the subdirectory) or you need to put the .so files in the proper location (in both cases, assuming that they come with wkHTMLtoPDF).

**Comment by MassMessage** [comment]
> Does Linux have some sort of _path_ definition for where to find shared libraries (.so files)? It sounds like either you have to extend that path to look in another place (the subdirectory) or you need to put the .so files in the proper location (in both cases, assuming that they come with wkHTMLtoPDF).

The so files did come with the wkHTMLtoPDF in the lib folder. I'm not much experience with UNIX systems so I looked up at the equivalent of Windows' PATH and found LD_LIBRARY_PATH. I did set it by using export and env commands to the path where the .so files are located but it still claims the .so files are missing.

**Comment by MassMessage** [comment]
For some reason, the binaries I've dried did not work so I tried to compile from source code by myself. I didn't manage to make a static binary but setting LD_LIBRARY_PATH to the path where the .so files were located did work. So I just passed that extra variable when calling the wkhtmltopdf utility and it worked fine.

**Comment by ashkulz** [comment]
@MassMessage: good that you got it working, normally one of the packages works for most people.
