### ISSUE TITLE
reference is invalid or unsupported ASP.Net Core 2.1

### ISSUE THREAD

**Issue by anking** [wkhtmltopdf/wkhtmltopdf#4313]
When i try to make a reference for the 64 bit version of this file(libwkhtmltox.dll) in my Core 2.1 project i have this error coming up for me:
![image](https://user-images.githubusercontent.com/9019734/55327418-15bbdf80-5458-11e9-9123-cdad7fd0946e.png)

Therefore when i publish my project I have to manually copy this dll in executables directory.
Is there a way this can be fixed? Or is there a version that is compatible with core 2.1?

**Comment by ashkulz** [comment]
Try one of the .NET wrappers, as this is a C DLL.
