### ISSUE TITLE
Pages background depends on the desktop theme. (Should be always white.)

### ISSUE THREAD

**Issue by lockywolf** [wkhtmltopdf/wkhtmltopdf#4316]
**wkhtmltopdf version(s) affected**: wkhtmltopdf 0.12.3.2

**OS information**
Slackware-current, 
Linux delllaptop.lockywolf.net 4.19.32 #1 SMP Wed Mar 27 13:21:48 CDT 2019 x86_64 Intel(R) Core(TM) i5-2520M CPU @ 2.50GHz GenuineIntel GNU/Linux
XFCE 4.12
Dark theme (important!)

**Description**
PDFs of pages with white background are generated with dark background.

**How to reproduce**
Set up a dark theme in XFCE (or, I guess, your DE).
Generate a pdf from a page with just text on white background, and some CSS.

**Expected behavior**
Background should be white.

**Possible Solution**  
There is something in CSS like 'inherit background from the operating system', which was deprecated in CSS3 but is still used... or something like that.

There is a reddit thread with a guy complaining about the same problem. They tried to solve it, but didn't really manage.

https://www.reddit.com/r/linuxquestions/comments/39c65c/how_come_desktop_theme_influences_the_output_of/

**Comment by PhilterPaper** [comment]
> Generate a pdf from a page with just text on white background, and some CSS.

When you say "white background", are you _explicitly_ specifying the background-color, or just _expecting_ a default of white? Have you carefully checked all your CSS to see if there is anything for `body` (or major page `div`'s) giving a background-color of _transparent_ or _inherit_(?) ? You're not giving a background image, are you?

My CSS book says that _transparent_ is the default background, but most PDF readers I've seen default to white. What are you using for a reader? Does your PDF behave the same way on different readers?

**Comment by lockywolf** [comment]
Wow, so many questions.

>>When you say "white background", are you explicitly specifying the background-color, or just expecting a default of white? 

I didn't find any way to specify background in wkhtmltopdf, but I did try the --no-background option, with no effect.

>>Have you carefully checked all your CSS to see if there is anything for body (or major page div's) giving a background-color of transparent or inherit(?) ? 

I am not competent in enough in CSS to do that. But I am attaching the html file, so maybe that will help.

>>You're not giving a background image, are you?

Explicitly -- no.

>>What are you using for a reader?

I am attaching screenshots of various readers: okular-pdf, xpdf-pdf, chromium-html and konqueror-html, and additionally mupdf-android-pdf.
I hope, the names are self-explanatory.

Konqueror is the only browser which is actually inheriting the background, which makes the page hard to read. But this isn't the point, as far as I understand, as to my understanding, it should be inherited from the _target_ system, which can be reasonably assumed to be a white A4 plain paper.

>>Does your PDF behave the same way on different readers?

Yes. 

>>How does the original HTML/CSS behave in browsers?
Indeed it has a dark background on Konqueror, but not Chrome.
![Screenshot_2019-04-05_09-04-20-okular-whitesource-blackreader](https://user-images.githubusercontent.com/2077025/55598814-41f09c80-5787-11e9-9662-10048807cc4b.png)
![Screenshot_2019-04-05_09-05-39-okular-blacksource-blackreader](https://user-images.githubusercontent.com/2077025/55598816-41f09c80-5787-11e9-8a65-c2d653b28884.png)
![Screenshot_2019-04-05_09-08-47-originalhtml-chromium-blackreader](https://user-images.githubusercontent.com/2077025/55598817-42893300-5787-11e9-8648-d42007be9b83.png)
![Screenshot_2019-04-05_09-09-58-xpdf-blackource-blackreader](https://user-images.githubusercontent.com/2077025/55598818-42893300-5787-11e9-9a38-9a3a586ae009.png)
![Screenshot_2019-04-05_09-10-29-xpdf-whitesource-blackreader](https://user-images.githubusercontent.com/2077025/55598820-4321c980-5787-11e9-8a19-bd3a2cbd0034.png)
![Screenshot_2019-04-05_09-27-33-okular-whitesource-whitereader](https://user-images.githubusercontent.com/2077025/55598821-4321c980-5787-11e9-87b2-53d7d239950b.png)
![Screenshot_2019-04-05_09-28-03-blacksource-whitereader](https://user-images.githubusercontent.com/2077025/55598822-43ba6000-5787-11e9-8e23-ac524e1b6cd6.png)
![Screenshot_2019-04-05_09-28-48-chromium-originalhtml](https://user-images.githubusercontent.com/2077025/55598823-43ba6000-5787-11e9-8374-580b98c7750d.png)
![Screenshot_2019-04-05_09-29-23-xpdf-blacksource-whitereader](https://user-images.githubusercontent.com/2077025/55598824-4452f680-5787-11e9-99e5-608baba2977a.png)
![Screenshot_2019-04-05_09-30-06-xpdf-whitesource-whitereader](https://user-images.githubusercontent.com/2077025/55598825-4452f680-5787-11e9-80e0-5491169d7517.png)
![Screenshot_2019-04-05_09-31-22-konqueror-whitetheme](https://user-images.githubusercontent.com/2077025/55598826-44eb8d00-5787-11e9-856c-ca94eff4cd1a.png)
![Screenshot_2019-04-05_09-32-18-konqueror-blacktheme](https://user-images.githubusercontent.com/2077025/55598827-44eb8d00-5787-11e9-9fb4-691f054fcc82.png)
![android-blacksource](https://user-images.githubusercontent.com/2077025/55598828-461cba00-5787-11e9-9aa1-01b281108b64.jpg)
![android-whitesource](https://user-images.githubusercontent.com/2077025/55598829-46b55080-5787-11e9-86da-1183c73b8261.jpg)

[pirates.zip](https://github.com/wkhtmltopdf/wkhtmltopdf/files/3046036/pirates.zip)

**Comment by PhilterPaper** [comment]
I tried your .htm file on Firefox, Chrome, IE, and Edge; and all browsers gave white background. I converted it to PDF using wkHTMLtoPDF 0.12.5 and viewed it in Adobe Acrobat Reader DC (free) and the background was white. A few HTML tags have a **style=** attribute with CSS, and many HTML tags have a **class=** attribute, but there are no .css files linked in and no `<style>` in the `<head>`. So, the `<body>`, including its background color, should be the default (transparent), which should be white, unless your browsers and PDF readers are set up in a non-standard way, to actually show through the desktop under them! Is this the only PDF file to show this behavior, and the only HTML to show this behavior, or do others? There are lots of missing CSS classes, but at worst, they should fall back to default values. Do you know for sure that you built your PDF with or without CSS (.css files or `<style>` tags), because without any CSS, it seems to have the expected white background.

**Comment by lockywolf** [comment]
>I tried your .htm file on Firefox, Chrome, IE, and Edge; and all browsers gave white background.

Did you actually try this with a dark theme? I am not aware of any Windows dark themes, but I believe they should exist. On my Linux machine I used Adwaita and XFCE-dusk.

Konqueror uses the old KHTML engine, which WebKit was initially based on, but by ldd-ing, I didn't find any references to khtml.

**Comment by PhilterPaper** [comment]
I'm on Win10, so I don't switch themes. However, I _do_ have wallpaper (images) over the desktop, and some of them are quite dark -- still see just a white background in both any browser and in Acrobat Reader, regardless of the wallpaper image. Have you confirmed that you don't have some odd (possibly default) setting in your browser and PDF reader that says to _not_ put a white background on any content, but to let the desktop show through?

**Comment by ashkulz** [comment]
This is probably caused by #2084 -- please see it for further discussion. You probably have a missing `background` definition in your CSS.

**Comment by lockywolf** [comment]
Look, I may know what a CSS is, but I wouldn't expect an average user to know this word.

In any case, the background of a plain A4 white sheet of paper is white.

**Comment by ashkulz** [comment]
Please refer to the [default UA CSS for Chrome](https://chromium.googlesource.com/chromium/blink/+/master/Source/core/css/html.css) -- it doesn't define white as the background (except for form elements). As linked above, there are use cases for having non-white background so I'm not really sure it makes sense to revert that part. If the page CSS explicitly specifies a `background-color` it **should** be honored -- if it doesn't, please let me know. If you don't control the page, you can always use `--user-style-sheet` to override that.

**Comment by lockywolf** [comment]
I believe chrome does so! Because chrome is expected to be displaying pages on different platforms!

When I'm converting an html to a pdf, I don't mean "please make a pdf of how this file would look on this particular machine". 

I mean, "please, typeset this file for being printed on a plain white sheet of paper, regardless of the machine on which it is typeset".

If I wanted to view this file on a computer with Chrome, I would use a computer and Chrome.

Yes, I believe, green, blue, black, red and other colours of A4 paper exist, but they are vastly overwhelmed by white.

**Comment by ashkulz** [comment]
@lockywolf wkhtmltopdf uses a browser engine as well, so expectations are a bit complicated. As I said earlier, please reopen the issue if explicitly specifying the `background-color` doesn't help. Please note that you have to change the CSS to support printing anyway (`@media print`), so this is just one more thing to set up there (or in a user stylesheet).

**Comment by daddy33** [comment]
Hello,
just got this issue, using dark gtk and qt style (qt5ct). Easiest workaround for me:
`env QT_STYLE_OVERRIDE=fusion wkhtmltopdf ...`

**Comment by buncis** [comment]
@daddy33 can u elaborate more on that? I have this same issue
