### ISSUE TITLE
Is there any possible way to get 0.12.6-dev binary for Alpine Linux?

### ISSUE THREAD

**Issue by akeuk** [wkhtmltopdf/wkhtmltopdf#4319]
I've used [0.12.6-dev](https://builds.wkhtmltopdf.org/0.12.6-dev/) on Ubuntu for solve disappeared TOC but now I want to change OS to Alpine Linux to reduce docker image size.

I'm trying to use [docker-alpine-wkhtmltopdf-patched-qt](https://github.com/aantonw/docker-alpine-wkhtmltopdf-patched-qt) that pull this [wkhtmltopdf](https://github.com/wkhtmltopdf/wkhtmltopdf) source code to build wkhtmltopdf binary but got 0.12.5.

**Comment by ashkulz** [comment]
You can try [this](https://github.com/Surnet/docker-wkhtmltopdf), which was linked from wkhtmltopdf/packaging#2. Unfortuntely, the patches haven't been sent as a PR yet so an official build is unlikely till that happens.

**Comment by tonyellow** [comment]
I would also need this. Lot of people are waiting on the release of 0.12.6.
