### ISSUE TITLE
wkhtmltopdf automatic chapter numbering

### ISSUE THREAD

**Issue by begonaalvarezd** [wkhtmltopdf/wkhtmltopdf#4324]
Hello! 

I would like to add **numbers** to all my sections (in content and TOC) but I cannot find anything (documentation, examples...) about this. Seems like it is possible using the `XSL-stylesheet` but I cannot make it work. Something like:

    <h1>Title</h1>
    <h2>Subtitle</h2>
    <h3>Subsubtitle</h3>

And the expected result is

    1 Title
    1.1 Subtitle
    1.1.1 Subsubtitle

I have tried both:

`<xsl:number format="1. " count="item" level="multiple"/>`
`<xsl:number format="1. " count="outline:item/outline:item" level="multiple"/>`

But they return ` The element with local name number does not exist in XSL-T`. Any idea how to achieve the chapter numbering?

My XSL is:

    <?xml version="1.0" encoding="UTF-8"?>
    <xsl:stylesheet version="2.0"
                    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                    xmlns:outline="http://wkhtmltopdf.org/outline"
                    xmlns="http://www.w3.org/1999/xhtml">
      <xsl:output doctype-public="-//W3C//DTD XHTML 1.0 Strict//EN"
                  doctype-system="http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"
                  indent="yes"/>
      <xsl:template match="outline:outline">
        <html>
          <head>
            <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
            <style>
                [... style]
            </style>
          </head>
          <body>
            <h1 class="book-toc-title">Table of Contents</h1>
            <ol class="book-toc-list">
              <xsl:number format="1. " count="item" level="multiple"/>
              <xsl:apply-templates select="outline:item/outline:item"/>
            </ol>
          </body>
        </html>
      </xsl:template>
    
      <xsl:template match="outline:item[count(ancestor::outline:item)&lt;=6]">
        <li class="book-toc-item level_{count(ancestor::outline:item)}">
          <xsl:if test="@title!=''">
            <div class="book-toc-item-inner">
    
              <span class="book-toc-item-pagenum">
                <xsl:value-of select="@page"/>
              </span>
    
              <a class="book-toc-item-title">
                <xsl:if test="@link">
                  <xsl:attribute name="href">
                    <xsl:value-of select="@link"/>
                  </xsl:attribute>
                </xsl:if>
    
                <xsl:if test="@backLink">
                  <xsl:attribute name="name">
                    <xsl:value-of select="@backLink"/>
                  </xsl:attribute>
                </xsl:if>
    
                <span class="text">
                  <span class="text-inner">
                    <xsl:value-of select="@title"/>
                  </span>
                </span>
              </a>
    
            </div>
          </xsl:if>
    
          <ol class="book-toc-list">
            <xsl:comment>added to prevent self-closing tags in QtXmlPatterns</xsl:comment>
            <xsl:apply-templates select="outline:item"/>
          </ol>
        </li>
      </xsl:template>
    </xsl:stylesheet>

Thank you very much!

**Comment by ashkulz** [comment]
If you change the default TOC stylesheet to use `ol` instead of `ul`, you can get numbered items. Not sure you can get the nested numbers correctly, though (you'll get an indented 1, not 1.1).

**Comment by begonaalvarezd** [comment]
If I am not wrong, that will only work in TOC but not in the PDF content headings. 

See [this example](https://ingeniamc.com/support/download/559). The numbers are working both in TOC and in the every heading. This is exactly what I would like to achieve, I could pre-parse all HTML pages and add numbers by myself, but I would like to know if it is achievable using this library.

Thanks!

**Comment by ashkulz** [comment]
If I see that PDF on Linux, I get something like this:

![Screenshot at 2019-04-10 14-15-24](https://user-images.githubusercontent.com/854352/55864958-1c0a3400-5b9b-11e9-983b-14730486bbd8.png)

The TOC has numbers but the outline doesn't, which would be possible via my suggestion.

**Comment by begonaalvarezd** [comment]
The outline is not numbered, which for me is not a problem. The thing is that the numbers **also** appear in the content:

![Screenshot from 2019-04-10 11-04-18](https://user-images.githubusercontent.com/3624944/55866947-b9586e80-5b81-11e9-8ba4-82f3df82030d.png)

Is it possible to achieve that using the this XSL file?

**Comment by ashkulz** [comment]
Can you at least try changing the XSLT file and seeing what gets generated?

**Comment by begonaalvarezd** [comment]
Sure I did it and it works for the TOC, not for the content, maybe I am doing something wrong

**Comment by ashkulz** [comment]
Oh, by content you mean the actual headings? No that won't get affected, sorry (there's no way to change the actual content dynamically).

**Comment by begonaalvarezd** [comment]
That is a pity! Will parse the HTML files myself then and add them the numbering. Thanks!

**Comment by icaroscherma** [comment]
I'm trying to output the numbers on the ToC but they're not showing up.
Does it has a regression on v0.12.6 x86-64?

`toc-style.xsl`:
```XSL
<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet
  version="2.0"
  xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
  xmlns:outline="http://wkhtmltopdf.org/outline"
  xmlns="http://www.w3.org/1999/xhtml"
>
  <xsl:output
    doctype-public="-//W3C//DTD XHTML 1.0 Strict//EN"
    doctype-system="http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"
    indent="yes"
  />
  <xsl:template match="outline:outline">
    <html>
      <head>
        <title>Table of Contents</title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,500" />
        <style>
          body {
            font-family: 'Roboto', sans-serif;
            font-weight: 300;
          }
          h1 {
            text-align: center;
            font-size: 24px;
            font-weight: 500;
            margin-bottom: 2rem;
          }
          div {
            border-bottom: 1px dashed rgb(200,200,200);
            padding: .5rem 0;
          }
          span {
            float: right;
          }
          ol {
            font-size: 20px;
            padding-left: 0em;
          }
          ol ol {
            font-size: 90%;
            padding-left: 1em;
          }
          a {
            text-decoration:none;
            color: #000;
          }
        </style>
      </head>
      <body>
        <h1>Table of Contents</h1>
        <ol><xsl:apply-templates select="outline:item/outline:item"/></ol>
      </body>
    </html>
  </xsl:template>
  <xsl:template match="outline:item">
    <li>
      <xsl:if test="@title!=''">
        <div>
          <a>
            <xsl:if test="@link">
              <xsl:attribute name="href"><xsl:value-of select="@link"/></xsl:attribute>
            </xsl:if>
            <xsl:if test="@backLink">
              <xsl:attribute name="name"><xsl:value-of select="@backLink"/></xsl:attribute>
            </xsl:if>
            <xsl:value-of select="@title" />
          </a>
          <span> <xsl:value-of select="@page" /> </span>
        </div>
      </xsl:if>
      <ol>
        <xsl:comment>added to prevent self-closing tags in QtXmlPatterns</xsl:comment>
        <xsl:apply-templates select="outline:item"/>
      </ol>
    </li>
  </xsl:template>
</xsl:stylesheet>
```
