### ISSUE TITLE
wkhtmltopdf exited with non-zero code -9

### ISSUE THREAD

**Issue by singhravi1** [wkhtmltopdf/wkhtmltopdf#4325]
wkhtmltox_0.12.5-1.bionic_amd64.deb 

**OS information**
ubuntu 18.04 (docker image)

**Description**
While creating some(not all)  pdf's i'm getting this error.

**How to reproduce**

> I think maybe this is because of an image of large size (in my case it was 5.2 MB)

Create a pdf from html (using pdfkit.from_string() function).
Html contains Two image fields with href to image link (with image size more than 5 MB) and two input fields.
Run the task to create pdf within the container. Put memory limit on the container to 300 MB.
It gives the error as 
`OSError: wkhtmltopdf exited with non-zero code -9. error: Loading pages (1/6) [> ] 0% [======> ] 10% [==========> ] 17% [============> ] 20% [=============> ] 23% [===============> ] 25% [=================> ] 29% [===================> ] 32% [=====================> ] 35% [======================> ] 38% [========================> ] 41% [==========================> ] 44% [===========================> ] 46% [============================> ] 48% [=====================================================> ] 89% [============================================================] 100% Counting pages (2/6) [============================================================] Object 1 of 1 Resolving links (4/6) [============================================================] Object 1 of 1 Loading headers and footers (5/6) Printing pages (6/6) [> ] Preparing [============================================================] Page 1 of 1`

**Expected behavior**
Pdf should be created just fine

**Possible Solution**  
I think it is because of memory outage for my docker container
Is it? What do you guys think?

**Comment by ashkulz** [comment]
The reproductions instructions are incomplete, please post a reproducible test case.

**Comment by singhravi1** [comment]
Hi @ashkulz 
I've updated my issue description. Please check.

**Comment by ashkulz** [comment]
It appears you're using pdfkit, please open a issue in their repository instead. If you believe it's an error in wkhtmltopdf, then please reproduce it from the command-line and post a minimal, reproducible testcase as a zip so that it can be verified.

**Comment by singhravi1** [comment]
@ashkulz Okay, i'll report this to PdfKit. 
Can you please give you thoughts on 'This could be because of shortage of memory?'
Thank You

**Comment by ashkulz** [comment]
Not sure, please try to reproduce locally.

**Comment by vinhntb** [comment]
@ashkulz 
I got same issue with convert multiple html to one pdf. I set limit memory then got same the issue and increase 100MB to container, it's fine. These html have image and highcharts.
> wkhtmltox_0.12.5-1 alpine docker
