### ISSUE TITLE
jpg & gif shown as blue box of question mark in converted PDF

### ISSUE THREAD

**Issue by gillmylady** [wkhtmltopdf/wkhtmltopdf#4334]
**wkhtmltopdf version(s) affected**: 0.12.3

**OS information**
linux

**Description**
When I have a html with images in jpg or gif, they cannot be rendered correctly and shown as a blue box with question mark instead. I might have seen that gif is not supported, but what about jpg? 

**How to reproduce**
download html and jpg from https://www.sec.gov/Archives/edgar/data/320193/000032019319000032/0000320193-19-000032-index.htm

wkhtmltopdf copyofreference8-kform8xkq.htm a.pdf

**Expected behavior**
jpg should be shown in converted pdf

**Possible Solution**  
is my version too old?

**Comment by PhilterPaper** [comment]
wkHTMLtoPDF has always worked with JPEG and GIF images. It's telling you it can't find the image file. The sec.gov page converts properly. What are you trying to convert with this copyofreference8 file? Where is it? Did you download it separately, as well as any other images and other files it references, in the proper directory structure?

**Comment by gillmylady** [comment]
This is interesting. I’m 100% sure I have the jpg file in the same location, and with correct name. And, if It works if I use a png file...

Sent from my iPhone

On Apr 17, 2019, at 19:20, Phil Perry <notifications@github.com<mailto:notifications@github.com>> wrote:


wkHTMLtoPDF has always worked with JPEG and GIF images. It's telling you it can't find the image file. The sec.gov<http://sec.gov> page converts properly. What are you trying to convert with this copyofreference8 file? Where is it? Did you download it separately, as well as any other images and other files it references, in the proper directory structure?
