### ISSUE TITLE
Ubunto PDF creation error

### ISSUE THREAD

**Issue by JuliusHamvie** [wkhtmltopdf/wkhtmltopdf#4339]
**wkhtmltopdf version(s) affected**: wkhtmltopdf 0.12.2.4

**OS information**
Ubunto 16.04.6 LTS od DigitalOcean

**Description**
I use PDFKit to produce a PDF via a Django-application. The creation of the PDF is not working. It gives me that error:

wkhtmltopdf exited with non-zero code 1. error: The switch --header-left, is not support using unpatched qt, and will be ignored.Unknown long argument -- Another time it gave me an error that the screen was not found.

On my local machine everything works.

I already installed wkhtmltopdf and xvfb on Ubunto but it is still not working.

**How to reproduce**
I use python code to trigger that event:
```
 # Options + Create PDF
        path = os.getcwd() + "/" + timestamp
        header = "test"
        options = {
            'page-size': 'A4',
            'margin-top': '12','margin-right': '12',
            'margin-bottom': '12',
            'margin-left': '12',
            'encoding': "UTF-8",
            'header-left': header,
            'header-font-size' : '10',
        #'no-outline':None
        }
        pdfkit.from_url(url, path, options=options)
```

**Expected behavior**

Creation of a PDF in the path.

Thank you very much in advance!
**Possible Solution**

**Comment by PhilterPaper** [comment]
What version of wkHTMLtoPDF is this setup running? Perhaps it's a _very_ old one without support for header-* flags? Can you tell (debug) what the command line passed to wkHTMLtoPDF was? If it includes `--header-left='test'` then it sounds like it was set up correctly, but wkHTMLtoPDF doesn't recognize that flag. Can you try running the desired wkHTMLtoPDF by itself on the OS command line, and see if it works with that flag?

**Comment by JuliusHamvie** [comment]
Thank you for your message!
The version is: 0.12.2.4
It is all working on my local machine (MacOS 10.14.2)
It must have something todo with the server setup..

**Comment by JuliusHamvie** [comment]
Hello, It worked out in the end. There was an issue with the naming convention on the ubuntu server. So, avoid "- ä ü ö" etc. Thank you very much!

**Comment by PhilterPaper** [comment]
I seem to recall hearing something about filenames and/or header/footer content having problems with non-ASCII text -- maybe that's what you're seeing. It might be worth a look around these discussions to see if someone came up with a workaround.
