### ISSUE TITLE
Error(1) when installing onto Debian 9.8

### ISSUE THREAD

**Issue by prep-gh** [wkhtmltopdf/wkhtmltopdf#4348]
**OS information**
Debian 9.8

**Description**
sudo apt-get install wkhtmltopdf

Errors were encountered while processing:
 /tmp/apt-dpkg-install-0y8g4U/3-libqt5webkit5_5.7.1+dfsg-1_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

<br/>
wkhtmltopdf --version

wkhtmltopdf: error while loading shared libraries: libQt5WebKitWidgets.so.5: cannot open shared object file: No such file or directory
<br/>

**How to reproduce**
sudo apt-get install wkhtmltopdf

I also ran these, then retried the install ...
sudo apt-get remove wkhtmltopdf
sudo apt autoremove 
sudo apt-get install wkhtmltopdf

same error.

**Comment by ashkulz** [comment]
That's an issue with the official debian package, install the version from the downloads page.
