### ISSUE TITLE
local paths falsely interpreted as remote paths

### ISSUE THREAD

**Issue by betz0r** [wkhtmltopdf/wkhtmltopdf#4355]
**wkhtmltopdf version(s) affected**: 0.12.5 (with patched qt)

**OS information**
Ubuntu 14.04.6 LTS

**Description**
Local paths are transformed to remote paths, pdf creation fails.

**How to reproduce**
```
wkhtmltopdf --encoding 'UTF-8' --margin-right '10' --margin-left '15' --margin-top '15' --margin-bottom '10' --title 'TITLE' --lowquality --enable-local-file-access '/var/www/virtual/DOMAIN/phptmp/tmp_wkhtmlto_pdf_fpyCig.html' '/var/www/virtual/DOMAIN/phptmp/tmp_wkhtmlto_pdf_bIKIxu.html' --footer-center '[sitepage] / [sitepages]' --footer-font-size '10' --footer-spacing '0' --header-right 'TITLE' --header-center 'TITLE' --header-font-size '9' --header-spacing '2' '/var/www/virtual/DOMAIN/phptmp/tmp_wkhtmlto_pdf_X9dxNI.pdf'

Error: Failed to load http://var/www/virtual/DOMAIN/phptmp/tmp_wkhtmlto_pdf_fpyCig.html, with network status code 3 and http status code 0 - Host var not found
Error: Failed loading page http:///var/www/virtual/DOMAIN/phptmp/tmp_wkhtmlto_pdf_fpyCig.html (sometimes it will work just to ignore this error with --load-error-handling ignore)
Error: Failed to load http://var/www/virtual/DOMAIN/phptmp/tmp_wkhtmlto_pdf_bIKIxu.html, with network status code 3 and http status code 0 - Host var not found
Error: Failed loading page http:///var/www/virtual/DOMAIN/phptmp/tmp_wkhtmlto_pdf_bIKIxu.html (sometimes it will work just to ignore this error with --load-error-handling ignore)
Exit with code 1 due to network error: HostNotFoundError
```
DOMAIN and TITLE are a placeholders, dont hang yourself on those.

**Expected behavior**
local paths should be used as such and not transformed to remote paths

**Possible Solution**  
nope.jpg

**Comment by PhilterPaper** [comment]
Have you tried prepending **file://** to the beginning of the names (file:///var/www/... etc.)? Maybe that will help. Although you _would_ think it should accept file paths as files... Even before that, try removing the quotes around the files (shouldn't be needed unless you have spaces within the names).

**Comment by betz0r** [comment]
Thank you for your response, i will try to edit https://github.com/mikehaertl/phpwkhtmltopdf as i use this library as a layer inbetween php and wkhtml2pdf.

**Comment by betz0r** [comment]
Error was not related to this. Closing.
