### ISSUE TITLE
Display line below the footer

### ISSUE THREAD

**Issue by UIPankaj** [wkhtmltopdf/wkhtmltopdf#4367]
Right now we are able to add line above the footer.html content but as per the requirement we need to display footer content then line then page no. 
![sampleIm](https://user-images.githubusercontent.com/43956603/58098509-571a7100-7bf7-11e9-9d96-237fe436242a.PNG)

**Comment by PhilterPaper** [comment]
Isn't the page number and any decoration such as the "footer line" considered to be part of the entire footer? I think you will need to rewrite your footer code to include those two items.

**Comment by UIPankaj** [comment]
Thank you for your quick response.
I am adding footer content through HTML so according to you I need to add Footer line as well as manage page number in footer HTML.
sample code: --margin-bottom 30mm  --footer-html "D:\pdf\footer.html" 
Let consider I am able to manage footer line by using border bottom but
**How to manage page number from HTML section**

**Comment by UIPankaj** [comment]
Got the solution

<script>
function subst() {
  var vars={};
  var x=document.location.search.substring(1).split('&');
  for(var i in x) {var z=x[i].split('=',2);vars[z[0]] = unescape(z[1]);}
  var x=['frompage','topage','page','webpage','section','subsection','subsubsection'];
  for(var i in x) {
    var y = document.getElementsByClassName(x[i]);
    for(var j=0; j<y.length; ++j) y[j].textContent = vars[x[i]];
  }
}
</script>
<table style="border-top: 1px solid black; width: 100%">
  <tr>
    <td class="section"></td>
    <td style="text-align:right">
      Page <span class="page"></span> of <span class="topage"></span>
    </td>
  </tr>
</table>
**Source** **stackoverflow.com**

By using above script and HTML we are able to show page number inside the HTML.
Got the solution.
Thanks

**Comment by PhilterPaper** [comment]
I think you would have done better with using a `<div>` to build this, rather than a `<table>`, but if it works for you, fine. Also, aren't there some special field symbols you can use in header and footer HTML files to have the page number and page count substituted? You may be going through a lot of extra work for very little gain, but again, if it works for you...
