### ISSUE TITLE
SSRF vulnerability with wkhtmltopdf due to iframe

### ISSUE THREAD

**Issue by vijayvsgit** [wkhtmltopdf/wkhtmltopdf#4368]
Hi,

I am using wkhtmltopdf(0.12.1) in one of my projects. I could simulate Server side Request Forgery by sending an HTML with iFrame tags pointing to aws ec2 metadata endpoints. 

Does this vulnerability exists even in the latest stable release version ?

I read here [https://github.com/wkhtmltopdf/wkhtmltopdf/issues/2924](url) that wkhtmltopdf should not be used for untrusted HTML content. Does this hold true for the latest release as well?

**Comment by ashkulz** [comment]
Yes, it uses an outdated browser engine so shouldn't be used with untrusted content.

**Comment by vijayvsgit** [comment]
Is this fixed in the latest version?
