### ISSUE TITLE
Including submodules in release tar

### ISSUE THREAD

**Issue by revathi-murali** [wkhtmltopdf/wkhtmltopdf#4369]
Is it possible to include submodules as well in the release tar.gz. I am using the tar.gz of `v0.12.5` and I could not find the submodules being included in it

**Comment by ashkulz** [comment]
It was being generated till `0.12.4`, but nobody seemed to be using it so it wasn't ported over when switching to the packaging approach. Please reopen in the packaging repository with your use case if you really need it.
