### ISSUE TITLE
wkhtml RHEL 6 Support

### ISSUE THREAD

**Issue by muratballikaya** [wkhtmltopdf/wkhtmltopdf#4374]
Hello,

We wanted to use wkhtmltopdf for conversion of html to pdf. 
We've chosen CENTOS 7 version assuming that it is closest to RHEL 6 which we wanted to install on.
While installing we encountered some missing dependency such as  xorg-x11-fonts-75dpi, libpng15...

What version of wkhtmltopdf should we use for RHEL6?

Thanks,

**Comment by ashkulz** [comment]
Please use the CentOS 6 version, which corresponds to RHEL 6.
