### ISSUE TITLE
Summation (and other operators) misalgined

### ISSUE THREAD

**Issue by ferrall** [wkhtmltopdf/wkhtmltopdf#4378]
**wkhtmltopdf version(s) affected**:  0.12.5,

**OS information** Windows 10

**Description** Operators in display mode not vertically aligned 

**How to reproduce**
HTML HEADER
<pre><code>
<script type="text/x-mathjax-config"> MathJax.Hub.Config( 
    {tex2jax: {inlineMath: [["$","$"],["\\(","\\)"]],processEscapes: true},
    CommonHTML: {
        scale : 180
        },
    TeX: {
          packages: ['base','eplain'],
          equationNumbers: {autoNumber:"all"} ,
    }});</script>
<script type="text/javascript" async src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-AMS_CHTML">
</script>
</pre></code>
END OF HEADER
HTML BODY
<pre></code>
$$E\sum_{t=0}^{39} {0.95}^t \biggl[ U(a_t,e_t,m_t)+\zeta(a_t)\biggr]$$
</code></pre>
END OF BODY

<pre><code>
"C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe" -B 1.25in -L 1.25in -R 1.25in -T 1.25in --dpi 600  --page-size Letter --print-media-type vellip.html vellip.pdf
<code></pre>

**Output PDF for wkhtmltopdf with misaligned summation sign:**
[vellip.pdf](https://github.com/wkhtmltopdf/wkhtmltopdf/files/3258539/vellip.pdf)

**Expected behavior**
**PDF output from Print to PDF with correct alignment**
[vellip-Print-to-PDF.pdf](https://github.com/wkhtmltopdf/wkhtmltopdf/files/3258551/vellip-Print-to-PDF.pdf)

**Possible Solution**

**Comment by arjunsuresh** [comment]
\biggl and \biggr doesnot work well with wkhtmltopdf -- not sure why. You can use \left and \right instead which works well.

**Comment by ferrall** [comment]
Thanks for the reply.
I changed all uses of "bigs" to \left and \right.  The problem I point out remains.  

However, I tried some more changes to the TeX, and I believe I have resolved the problem.
Placing the operator itself inside brackets seems to fix the display:
`$$E{\sum}_{t=0}^{39} {0.95}^t \biggl[ U(a_t,e_t,m_t)+\zeta(a_t)\biggr]$$`
This is not required by plain TeX, so this would seem to be an issue with wkhtmltopdf that could be fixed.
