### ISSUE TITLE
Disable page breaks

### ISSUE THREAD

**Issue by LaranIkal** [wkhtmltopdf/wkhtmltopdf#4382]
Hello,

I just want to convert a large html file to pdf avoiding page breaks, I mean my output pdf file must be without page breaks.

How can I achieve that using wkhtmltopdf.exe ?

I saw and tested --page-size and --page-height parameters but I always get a page break.

Thank you in advance for your help.

Regards

**Comment by soundasleep** [comment]
Does the CSS include any page break directions? They might be overriding page size config.

**Comment by PhilterPaper** [comment]
Do you mean that you want your output on one long "sheet of paper" (lots of scrolling needed on screen, or print on roll paper), regardless of how much content there is? That has been requested many times (do a search). The best you may be able to do is specify a page length of up to 200 inches, print the PDF on it, and use a utility to crop off blank paper at the bottom. 200 inches (14400pt) is the PDF limit, unless User Units are supported somewhere. Some writers and readers will allow larger pages, but Adobe products will fail to read them.

**Comment by LaranIkal** [comment]
> Do you mean that you want your output on one long "sheet of paper" (lots of scrolling needed on screen, or print on roll paper), regardless of how much content there is? That has been requested many times (do a search). The best you may be able to do is specify a page length of up to 200 inches, print the PDF on it, and use a utility to crop off blank paper at the bottom. 200 inches (14400pt) is the PDF limit, unless User Units are supported somewhere. Some writers and readers will allow larger pages, but Adobe products will fail to read them.

Thank you for your solution.

What I did is that in the data source I count the number of pages and multiply for the page length( like letter length ) having now the total of inches for my big PDF page.

Regards.
