### ISSUE TITLE
Could not connect to a X Display

### ISSUE THREAD

**Issue by lmccarty19** [wkhtmltopdf/wkhtmltopdf#4383]
I try running  ./cool-retro-term
But it gives me

QStandardPaths: XDG_RUNTIME_DIR not set, default to '/tmp/runtime-(My username)'
qt.qpa.screen: QXcvConnection: Could not connect to display
Could not connect to any X display.

Anything I can do?
I'm on Ubuntu, Linux. I just want to use Cool-Retro-Term

**Comment by ryanrca** [comment]
Ive got the same error, just converting from html to .pdf. 
I'm running this command:
`/usr/local/bin/wkhtmltopdf --lowquality --page-size 'letter' '/tmp/knp_snappy5d8802d6907308.23041875.html' `

**Comment by ashkulz** [comment]
Did you use the version from the website rather than the package provided by the distribution? if should work without an X display if so. For the distro-provided packages, you have to run in under xfvb.
