### ISSUE TITLE
Link to PGP key should display the key fingerprint

### ISSUE THREAD

**Issue by imgx64** [wkhtmltopdf/wkhtmltopdf#4387]
**Description**  
On the [Downloads](https://wkhtmltopdf.org/downloads.html) page, clicking on the key fingerprint (`86DA...`) goes to a pgp.mit.edu search page for the key. But the search results don't actually show the fingerprint. This can be fixed by adding `&fingerprint=on` to the search URL, like so:
https://pgp.mit.edu/pks/lookup?search=ashish+kulkarni+open+source&op=vindex&fingerprint=on

Or better yet, link directly to the key itself:
https://pgp.mit.edu/pks/lookup?search=0x86DA3091E25554F156F214F6A86EF3CB8C64CF2A&op=vindex&fingerprint=on

**Comment by ashkulz** [comment]
Thanks, @imgx64! I prefer to use the search URL as the key ID may get changed in future.
