### ISSUE TITLE
How to build wkhtmltox library to develop c++ program based on wkhtml functinality  on Ubuntu environmnet?

### ISSUE THREAD

**Issue by ercjethava** [wkhtmltopdf/wkhtmltopdf#4390]
We use GitHub issues only to discuss about wkhtmltopdf bugs and new features. For
this kind of questions about using wkhtmltopdf, please use
any of the support alternatives shown in https://wkhtmltopdf.org/support.html or 
post an issue on https://stackoverflow.com/.

Thanks!

**Comment by ashkulz** [comment]
I'm not sure what is your question?
