### ISSUE TITLE
limit size of command line 

### ISSUE THREAD

**Issue by gmisterk** [wkhtmltopdf/wkhtmltopdf#4391]
As you know, cmd.exe is limited to 8191 characters

There is some possibilities but no way for me :

1) reduce the path of each urls.
2) put argument in a text file and run like this : wkhtmltopdf.exe < myurls.txt

option 2 is a good solution, but wkhtmltopdf don't have this second option (use text file for urls input)

Any suggestion ? or help

see here for more info about this limitation  :[ https://support.microsoft.com/en-us/help/830473/command-prompt-cmd-exe-command-line-string-limitation]( https://support.microsoft.com/en-us/help/830473/command-prompt-cmd-exe-command-line-string-limitation)

**Comment by PhilterPaper** [comment]
Have you tried `wkhtmltopdf --read-args-from-stdin < myurls.txt` ? Something like that might work. I'm not sure if it's looking for actual STDIN (requiring the < ) or directly reads the file.

**Comment by holmedor** [comment]
I'm triying this in a Windows 10 environment and it fails, any help?

**Comment by ashkulz** [comment]
This should be working as @PhilterPaper mentioned, if you encounter a problem please provide a working test case with exact CLI arguments that you used.

**Comment by holmedor** [comment]
Hi, 

I have 2 html files and 1 txt file:

D:\test>dir
 El volumen de la unidad D es Datos
 El número de serie del volumen es: 5AD7-183F

 Directorio de D:\test

2020-06-10  10:51    <DIR>          .
2020-06-10  10:51    <DIR>          ..
2020-06-10  10:48               166 file1.html
2020-06-10  10:48               168 file2.html
2020-06-10  10:24                75 myurls.txt
               3 archivos            409 bytes
               2 dirs  172.851.728.384 bytes libres

D:\test>

Content of txt is:

file:///D:/test/file1.html
file:///D:/test/file2.html
D:\test\file1y2.pdf

If I type next command, I get the pdf file OK:

D:\test>"C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf" file:///D:/test/file1.html file:///D:/test/file2.html D:\test\file1y2.pdf
Loading pages (1/6)
Counting pages (2/6)
Resolving links (4/6)
Loading headers and footers (5/6)
Printing pages (6/6)
Done

D:\test>
D:\test>dir
 El volumen de la unidad D es Datos
 El número de serie del volumen es: 5AD7-183F

 Directorio de D:\test

2020-06-10  11:33    <DIR>          .
2020-06-10  11:33    <DIR>          ..
2020-06-10  10:48               166 file1.html
**2020-06-10  11:33            17.771 file1y2.pdf**
2020-06-10  10:48               168 file2.html
2020-06-10  10:24                75 myurls.txt
               4 archivos         18.180 bytes
               2 dirs  172.851.707.904 bytes libres

But with these commands, I get nothing:

1. 
D:\test>"C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf" --read-args-from-stdin < myurls.txt
You need to specify at least one input file, and exactly one output file
Use - for stdin or stdout

Name:
  wkhtmltopdf 0.12.5 (with patched qt)

Synopsis:
  wkhtmltopdf [GLOBAL OPTION]... [OBJECT]... <output file>

Document objects:
[...]

2.
D:\test>"C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf" --read-args-from-stdin myurls.txt
just the cursor blinking...

Please could you tell me what I am doing wrong?

I want to generate a pdf with 300 html files and I can't do it using a txt file and with one line command maybe 50 html files per pdf only...

THANKS!!!
