### ISSUE TITLE
How can I build a static-linked binary?

### ISSUE THREAD

**Issue by arielnmz** [wkhtmltopdf/wkhtmltopdf#4393]
**Description**
I need to use this in a production environment with limited capabilities, basically I'm just permitted to use whatever is there already, it's a Fedora 27 box. It'd be good if I could just compile on my local Fedora box and beam up the whole binary to the server. How can I go about it? Moreover, are there any plans on building docker images for using it (not just for packaging), so one can just do:

`$ docker run --rm wkhtmltopdf wkhtmltopdf ... > out.pdf`

**Comment by ashkulz** [comment]
You can create a docker image of your own easily, just install a package on a supported OS. There are also quite a few docker images floating around. If you're talking specifically of Fedora 27, it's easy to build a binary yourself -- see the packaging repository.
