### ISSUE TITLE
PDF filename of output is named "*.pdf?" 

### ISSUE THREAD

**Issue by gabedot** [wkhtmltopdf/wkhtmltopdf#4397]
**wkhtmltopdf version(s) affected**: 
wkhtmltopdf 0.12.5 (with patched qt)

**OS information**
MacOS 10.14.5

**Description**
getting wrong filename: "78.pdf?"
why this weird question mark?

**How to reproduce**
wkhtmltopdf https://somewebsite /Volumes/SSD/Users/username/Documents/Projekt\ 2019-05/78.pdf

**Expected behavior**
getting a pdf named 78.pdf

**Comment by ZAJDAN** [comment]
it depends from where (which path/directory) You trigger the wkhtmltopf  ...maybe doesn know where is
directory '2019-05'

tray to pass full path:
wkhtmltopdf https://somewebsite /Volumes/SSD/Users/username/Documents/Projekt  /somePath/2019-05/78.pdf

**Comment by gabedot** [comment]
well it produces the pdf, so it finds the directory.
the pdf filename is just kind of weird and opening it after getting rid of this question mark shows a pdf as desired.

**Comment by PhilterPaper** [comment]
@ZAJDAN I think the directory in question is **Projekt 2019-05**. The escape \ is for the embedded space.

So the output PDF is produced correctly, and just the name is strange (with a ? added to the end)? This doesn't happen if your path is, say, **Projekt_2019-05** (no escapes used)?

**Comment by ashkulz** [comment]
@gabedot is this still an issue? If so, please post an actual URL so that it can be reproduced.
