### ISSUE TITLE
Custom Fonts not working on Azure App Service

### ISSUE THREAD

**Issue by MDzyga** [wkhtmltopdf/wkhtmltopdf#4398]
**wkhtmltopdf version(s) affected**: 0.12.5

**OS information**
Azure App Service

**Description**
When I generate PDF with custom fonts (they are localized in Fonts folder) locally, everything works correctly.
When I deploy my solution on Azure App Service, PDF is generated with Arial fonts, instead of my custom fonts.

I tried to solve this issue like in this article https://stackoverflow.com/questions/10611828/use-custom-fonts-with-wkhtmltopdf but it didn't work (with the same custom font).

**How to reproduce**

_Fonts.css_
```
@font-face {
    font-family: 'TT Norms Medium';
    src: url(./Fonts/TTNorms-Medium.ttf) format('truetype');
}

@font-face {
    font-family: 'TT Norms ExtraBold';
    src: url(./Fonts/TTNorms-ExtraBold.ttf) format('truetype');
}

.tray-clip-title {
    font-size: 31px;
    font-weight: 900;
    font-family: 'TT Norms ExtraBold';
}

.tray-clip-subtitle {
    margin-top: -5px;
    font-size: 29px;
    font-weight: 900;
    font-family: 'TT Norms Medium';
}
```

_HTML_
```
<html>
  <head>
    <link href="file:///pathToFont.css" rel="stylesheet" type="text/css" />
  </head>
  <body>
     <div class='tray-clip-title'> Title</div>
     <div class='tray-clip-subtitle'> Subtitle</div>
  </body>
</html>
```
**Expected behavior**
I expect that generated file will use custom fonts

**Comment by pedroreys** [comment]
This is a limitation of the APIs available in the Azure App Service sandbox environment.

From the [Azure Sandbox docs](https://github.com/projectkudu/kudu/wiki/Azure-Web-App-sandbox#unsupported-frameworks):

> Known issue for all PDF generators based on wkhtmltopdf or phantomjs: custom fonts are not rendered (system-installed font is used instead) because of sandbox GDI API limitations that present even in VM-based Azure Apps plans (Basic or higher).
