### ISSUE TITLE
bug in c lib

### ISSUE THREAD

**Issue by RekGRpth** [wkhtmltopdf/wkhtmltopdf#4403]
**wkhtmltopdf version(s) affected**: 0.12.6-dev 

**OS information**
alpine 3.10

**Description**
when wait about 1 minute after done, QNetworkAccessM... thread hangs

**How to reproduce**
1) apply diff
```diff
diff --git a/examples/pdf_c_api.c b/examples/pdf_c_api.c
index 4b12650..5288d57 100644
--- a/examples/pdf_c_api.c
+++ b/examples/pdf_c_api.c
@@ -108,6 +108,7 @@ int main() {
 
        /* We will no longer be needing wkhtmltopdf funcionality */
        wkhtmltopdf_deinit();
+       getchar();
 
        return 0;
 }
```
2) compile
```sh
gcc -I../include pdf_c_api.c -o pdf_c_api -lwkhtmltox -Wall -ansi -pedantic -ggdb
```
3) run
```sh
./pdf_c_api
```
4) wait about 1 minute after done and watch htop with threads shown

**Expected behavior**
thread must not hangs!

**Possible Solution**  
I don't know

**Comment by ashkulz** [comment]
I don't think wkhtmltopdf builds on alpine, see wkhtmltopdf/packaging#2.

**Comment by RekGRpth** [comment]
I also tried prebuild https://pkgs.alpinelinux.org/package/v3.10/community/x86_64/wkhtmltopdf-dev and result is same :(
