### ISSUE TITLE
consuming too much memory

### ISSUE THREAD

**Issue by spectrelb** [wkhtmltopdf/wkhtmltopdf#4405]
wkhtmltopdf 0.12.5
macos sierra 10.12.5  Memory: 16GB

i am from shanghai china 

I used wkhtmltopdf to generate the PDF file, which generated 168 pages. The memory usage is about 8gb. Why is it so memory intensive? I don't know how to optimize, please help me

I used the command
/usr/local/bin/wkhtmltopdf --header-line --header-spacing 5  --footer-center page  --page-size A4  test.html  aa.pdf

**Comment by ashkulz** [comment]
Memory is cheap nowadays, especially on servers -- it also depends on which HTML/CSS features you are using. Please try to create a minimal test case which shows memory usage being too high.
