### ISSUE TITLE
Cannot generate PDF: libpng warning: iCCP: known incorrect sRGB profile (exit code: 255)

### ISSUE THREAD

**Issue by Sasireka2198** [wkhtmltopdf/wkhtmltopdf#4410]
I'm using Nreco pdf  generator to create pdf file with images in a .Net 4.5 MVC framework.
It was working fine. But now I'm getting following exception. not sure why
{
	"ClassName": "System.Exception",
	"Message": "Cannot generate PDF: libpng warning: iCCP: known incorrect sRGB profile (exit code: 255)",
	"Data": null,
	"InnerException": {
		"ErrorCode": 255,
		"Message": "libpng warning: iCCP: known incorrect sRGB profile (exit code: 255)",
		"Data": {},
		"InnerException": null,
		"StackTrace": "   at NReco.PdfGenerator.HtmlToPdfConverter.CheckExitCode(Int32 exitCode, String lastErrLine, Boolean outputNotEmpty)\r\n   at NReco.PdfGenerator.HtmlToPdfConverter.InvokeWkHtmlToPdf(PdfSettings pdfSettings, String inputContent, Stream outputStream)\r\n   at NReco.PdfGenerator.HtmlToPdfConverter.GeneratePdfInternal(WkHtmlInput[] htmlFiles, String inputContent, String coverHtml, String outputPdfFilePath, Stream outputStream)",
		"HelpLink": null,
		"Source": "NReco.PdfGenerator",
		"HResult": -2146233088
	},
	"HelpURL": null,
	"StackTraceString": "   at NReco.PdfGenerator.HtmlToPdfConverter.GeneratePdfInternal(WkHtmlInput[] htmlFiles, String inputContent, String coverHtml, String outputPdfFilePath, Stream outputStream)\r\n   at NReco.PdfGenerator.HtmlToPdfConverter.GeneratePdf(String htmlContent, String coverHtml, Stream output)\r\n   at NReco.PdfGenerator.HtmlToPdfConverter.GeneratePdf(String htmlContent, String coverHtml)\r\n   at PrintLib.Printer.Convert_HtmlTags(List`1 p_RowList, List`1 p_imageList, List`1 p_emptyRows, String p_headerText) in C:\\Projects\\BestBuy Changes\\PrintLib\\Controls\\Printer.cs:line 240\r\n   at PrintLib.Printer.Print_ToPDF(List`1 p_fields, String p_headerText) in C:\\Projects\\BestBuy Changes\\PrintLib\\Controls\\Printer.cs:line 170\r\n   at ENSAFE_BusinessLogicLayer.BusinessLogic.IssueManager.<>c__DisplayClass12_1.<DownloadObservationsReport>b__1() in C:\\Projects\\BestBuy Changes\\INCIO\\ENSAFE_SupportLayer\\ENSAFE_BusinessLogicLayer\\Issue Processing\\IssueManager.cs:line 386",
	"RemoteStackTraceString": null,
	"RemoteStackIndex": 0,
	"ExceptionMethod": "8\nGeneratePdfInternal\nNReco.PdfGenerator, Version=1.1.15.0, Culture=neutral, PublicKeyToken=231663d50a41b451\nNReco.PdfGenerator.HtmlToPdfConverter\nVoid GeneratePdfInternal(NReco.PdfGenerator.WkHtmlInput[], System.String, System.String, System.String, System.IO.Stream)",
	"HResult": -2146233088,
	"Source": "NReco.PdfGenerator",
	"WatsonBuckets": null
}

**Comment by ashkulz** [comment]
Please open issue in NReco.PdfGenerator repository.
