### ISSUE TITLE
Debian Buster .deb package

### ISSUE THREAD

**Issue by anirbanmu** [wkhtmltopdf/wkhtmltopdf#4416]
Debian Buster is the new Debian stable release (https://www.debian.org/News/2019/20190706) and is now released. Will there be a .deb package for Buster as there is for Stretch?

**Comment by ashkulz** [comment]
Debian 9 package should work as-is, but support has been added already in wkhtmltopdf/packaging#29 -- I'll try to upload it over the weekend.

**Comment by anirbanmu** [comment]
Got it, thank you!

**Comment by fliespl** [comment]
Hi @ashkulz, is there a buster deb file available somewhere? :)

**Comment by ashkulz** [comment]
Nope, but you can build it easily and I believe the Debian 9 deb works as-is.
