### ISSUE TITLE
QT Make Error Debian 10

### ISSUE THREAD

**Issue by whoshonky** [wkhtmltopdf/wkhtmltopdf#4417]
Make error under Debian 10.

Following packages, previous to configure and make, have been installed: openssl build-essential libssl-dev libxrender-dev git-core libx11-dev libxext-dev libfontconfig1-dev libfreetype6-dev fontconfig git p7zip-full python python-yaml docker

wkhtmltopdf version: latest

Configure runs clean.

Make throws the following error:

`
ssl/qsslsocket_openssl_symbols.cpp: In function ‘bool q_resolveOpenSslSymbols()’:
ssl/qsslsocket_openssl_symbols.cpp:364:11: error: ‘_q_CRYPTO_free’ was not declared in this scope
     if (!(_q_##func = _q_PTR_##func(libs.first->resolve(#func)))     \
           ^~~
ssl/qsslsocket_openssl_symbols.cpp:825:5: note: in expansion of macro ‘RESOLVEFUNC’
     RESOLVEFUNC(CRYPTO_free)
     ^~~~~~~~~~~
ssl/qsslsocket_openssl_symbols.cpp:364:11: note: suggested alternative: ‘CRYPTO_free’
     if (!(_q_##func = _q_PTR_##func(libs.first->resolve(#func)))     \
           ^~~
ssl/qsslsocket_openssl_symbols.cpp:825:5: note: in expansion of macro ‘RESOLVEFUNC’
     RESOLVEFUNC(CRYPTO_free)
     ^~~~~~~~~~~
ssl/qsslsocket_openssl_symbols.cpp:364:23: error: ‘_q_PTR_CRYPTO_free’ was not declared in this scope
     if (!(_q_##func = _q_PTR_##func(libs.first->resolve(#func)))     \
                       ^~~~~~~
ssl/qsslsocket_openssl_symbols.cpp:825:5: note: in expansion of macro ‘RESOLVEFUNC’
     RESOLVEFUNC(CRYPTO_free)
     ^~~~~~~~~~~
ssl/qsslsocket_openssl_symbols.cpp:364:23: note: suggested alternative: ‘_q_PTR_RSA_free’
     if (!(_q_##func = _q_PTR_##func(libs.first->resolve(#func)))     \
                       ^~~~~~~
ssl/qsslsocket_openssl_symbols.cpp:825:5: note: in expansion of macro ‘RESOLVEFUNC’
     RESOLVEFUNC(CRYPTO_free)
     ^~~~~~~~~~~
make[1]: *** [Makefile:18390: .obj/release-shared/qsslsocket_openssl_symbols.o] Error 1
make[1]: Leaving directory '/opt/qt-wkhtmltopdf/src/network'
make: *** [Makefile:279: sub-network-make_default-ordered] Error 2
`

**Comment by ashkulz** [comment]
Did you use the target introduced in wkhtmltopdf/packaging#29? If not, please use it. If there's errors in the target, I'd appreciate discussion on the PR and not in this repository.

**Comment by whoshonky** [comment]
@ashkulz Thanks for the info.
I just cloned the git from [https://www.github.com/wkhtmltopdf/qt](url) and ran configure and make. Ran into the above errors during make.
Also tried the Debian 9.4 deb package as you suggested in [https://github.com/wkhtmltopdf/wkhtmltopdf/issues/4416](url) but that also throws an error:

`dpkg -i wkhtmltox_0.12.5-1.stretch_amd64.deb
dpkg: warning: 'ldconfig' not found in PATH or not executable
dpkg: warning: 'start-stop-daemon' not found in PATH or not executable
dpkg: error: 2 expected programs not found in PATH or not executable
Note: root's PATH should usually contain /usr/local/sbin, /usr/sbin and /sbin`

**Comment by ashkulz** [comment]
@whoshonky: that's not a supported way of compiling things, you have to use the correct flags (see the other repository). For the error you're getting, can you reproduce it in a clean docker container? If so, please add a comment on the PR with reproduction steps as I believe `ldconfig` should be present on root's `$PATH`.

**Comment by whoshonky** [comment]
@ashkulz Thanks for the response.
Found out what's happening with the above error. It's a sudo Debian 10 implementation issue. Doesn't happen under Debian 9 with sudo installed.

I'd really appreciate it if you could send me the link to the flags. I've been searching all over the wkhtmltopdf-QT repository and can't find it.
The INSTALL file points to documentation that's not in the doc file (which probably is a remnant of official QT). I don't think that the official QT documentation is the right place for me to look either. https://doc.qt.io/qt-5/linux-building.html That's pretty much what I did though.
Sorry for the inconvenience.

**Comment by ashkulz** [comment]
See [build.yml](https://github.com/wkhtmltopdf/packaging/blob/0.12/build.yml) in packaging repository.

**Comment by whoshonky** [comment]
Thanks @ashkulz
