### ISSUE TITLE
Internal link clickable area too narrow with css display property

### ISSUE THREAD

**Issue by aplqo** [wkhtmltopdf/wkhtmltopdf#4418]
**wkhtmltopdf version(s) affected**: 0.12.5 

**OS information**
Debian 10 and Debian 9

**Description**
If there is a `span` tag in `a` tag and the `span` tag has a css property `display`,the link clickable area is too narrow.
[test.pdf](https://github.com/wkhtmltopdf/wkhtmltopdf/files/3389368/test.pdf)

link "test1" in pdf:
![ ](https://user-images.githubusercontent.com/52119914/61178227-2fee8780-a61b-11e9-9ebe-f03199acdf1c.png)
link "test2" in pdf:
![ ](https://user-images.githubusercontent.com/52119914/61178230-3977ef80-a61b-11e9-9f98-da5880c6b9cb.png)

**How to reproduce**
Command: `wkhtmltopdf --enable-internal-links --enable-local-file-access --no-pdf-compression test.html link.html test.pdf` 
test.html:
```html
<!DOCTYPE html>
<html>
<head>
    <style>
        .t-lines {
            display: table
        }
        .t2{
            font-weight: bold
        }
    </style>
</head>
<body>
    <a href="link.html">
        <span class="t-lines">
            test1
        </span>
    </a>
    <p>
        These links works:
    </p>
    <a href="link.html">
        test2
    </a>
    <a href="link.html" class="t-lines">
        test3
    </a>
    <a href="link.html">
        <div class="t-lines">
            test4
        </div>
    </a>
    <a href="link.html">
        <span class="t2">
            test5
        </span>
    </a>
</body>
</html>
```
link.html:
```html
<!DOCTYPE html>
<html>
<head></head>
<body>Linked text</body>
</html>
```

**Expected behavior**
All links can be click on text.

**Comment by aplqo** [comment]
link "test1" in pdf:
![ ](https://user-images.githubusercontent.com/52119914/61178227-2fee8780-a61b-11e9-9ebe-f03199acdf1c.png)
link "test2" in pdf:
![ ](https://user-images.githubusercontent.com/52119914/61178230-3977ef80-a61b-11e9-9f98-da5880c6b9cb.png)

**Comment by ashkulz** [comment]
I think you'll have to use a different `display` value, as `table` essentially has zero width/height -- that comes from the descendants (tr, th).

**Comment by aplqo** [comment]
Thanks for replying.
I will try it.
