### ISSUE TITLE
Add ability to login to websites

### ISSUE THREAD

**Issue by learnseq** [wkhtmltopdf/wkhtmltopdf#4419]
**Description**
I was trying to convert a webpage on edx website, but I'm getting an error, I believe it requires me to logging first, then it will be able to convert the link.

This is the error that I've got:

Loading pages (1/6)
Counting pages (2/6)
Warning: Received createRequest signal on a disposed ResourceObject's NetworkAccessManager. This might be an indication of an iframe taking too long to load.
Warning: Received createRequest signal on a disposed ResourceObject's NetworkAccessManager. This might be an indication of an iframe taking too long to load.
QNetworkReplyImplPrivate::error: Internal problem, this method must only be called once.
QNetworkReplyImplPrivate::error: Internal problem, this method must only be called once.
Error: Failed to load about:blank, with network status code 301 and http status code 0 - Protocol "about" is unknown
Error: Failed to load about:blank, with network status code 301 and http status code 0 - Protocol "about" is unknown
Loading TOC (3/6)
Warning: Received createRequest signal on a disposed ResourceObject's NetworkAccessManager. This might be an indication of an iframe taking too long to load.
Warning: Received createRequest signal on a disposed ResourceObject's NetworkAccessManager. This might be an indication of an iframe taking too long to load.
Warning: Received createRequest signal on a disposed ResourceObject's NetworkAccessManager. This might be an indication of an iframe taking too long to load.
Warning: Received createRequest signal on a disposed ResourceObject's NetworkAccessManager. This might be an indication of an iframe taking too long to load.
Error: Failed to load about:blank, with network status code 301 and http status code 0 - Protocol "about" is unknown
Error: Failed to load about:blank, with network status code 301 and http status code 0 - Protocol "about" is unknown
Error: Failed to load about:blank, with network status code 301 and http status code 0 - Protocol "about" is unknown
Error: Failed to load about:blank, with network status code 301 and http status code 0 - Protocol "about" is unknown
Resolving links (4/6)
Loading headers and footers (5/6)
Printing pages (6/6)
Done

**Comment by ashkulz** [comment]
Login via alternate mechanism and pass the cookies and same User-Agent to wkhtmltopdf.

**Comment by learnseq** [comment]
Thanks for replying!

Could you please demonstrate a command line example on this could be done?

Have a good day

Kind regards

**Comment by ashkulz** [comment]
Just use the `--cookie` argument? You'll need to login first to the website (either via browser, or some automation library) and capture the cookies to pass.

**Comment by learnseq** [comment]
I tried and logged in, and when I tried to use the wkhtmltopdf, it came out
with the same error message.

I’m end user, new to programming, could you show me how is it done?

**Comment by ashkulz** [comment]
Please ask on StackOverflow rather than on this issue tracker, as you'll get better help there.
