### ISSUE TITLE
Rendering SSL pages broken by Ubuntu updates (libssl-dev)

### ISSUE THREAD

**Issue by mitchellkrogza** [wkhtmltopdf/wkhtmltopdf#4420]
**wkhtmltopdf version(s) affected**: x.y.z 
wkhtmltoimage 0.12.4 (with patched qt)

**OS information**
Ubuntu 16.04.2

**Description**
Recent updates from Ubuntu to libssl-dev libnss3 libnss3-nssdb have broken the ability to render ssl pages. I assume libssl-dev was the cause.

```
QSslSocket: cannot resolve CRYPTO_num_locks
QSslSocket: cannot resolve CRYPTO_set_id_callback
QSslSocket: cannot resolve CRYPTO_set_locking_callback
QSslSocket: cannot resolve sk_free
QSslSocket: cannot resolve sk_num
QSslSocket: cannot resolve sk_pop_free
QSslSocket: cannot resolve sk_value
QSslSocket: cannot resolve SSL_library_init
QSslSocket: cannot resolve SSL_load_error_strings
QSslSocket: cannot resolve SSLv3_client_method
QSslSocket: cannot resolve SSLv23_client_method
QSslSocket: cannot resolve SSLv3_server_method
QSslSocket: cannot resolve SSLv23_server_method
QSslSocket: cannot resolve X509_STORE_CTX_get_chain
QSslSocket: cannot resolve OPENSSL_add_all_algorithms_noconf
QSslSocket: cannot resolve OPENSSL_add_all_algorithms_conf
QSslSocket: cannot resolve SSLeay
QSslSocket: cannot call unresolved function CRYPTO_num_locks
QSslSocket: cannot call unresolved function CRYPTO_set_id_callback
QSslSocket: cannot call unresolved function CRYPTO_set_locking_callback
QSslSocket: cannot call unresolved function SSL_library_init
QSslSocket: cannot call unresolved function SSLv23_client_method
QSslSocket: cannot call unresolved function sk_num
QSslSocket: cannot call unresolved function SSLv23_client_method
QSslSocket: cannot call unresolved function SSL_library_init
```
My solution right now is I am using another component altogether. 
This has worked for over a year day in and day out without fail but now appears to be quite broken and unreliable.

**Comment by ashkulz** [comment]
Why not use `0.12.5`?

**Comment by mitchellkrogza** [comment]
That version had issues of its own on my Ubuntu 18.04.2 server so I gave up using it there too. `pip install webscreenshot` does a much better job for me now. This all worked for over 14 months for me and one ssl update broke it.

**Comment by mitchellkrogza** [comment]
Tried 0.2.15 on Ubuntu 16.04.2 this morning happy to report it has fixed that issue hope this does not happen again. Had some scripts very reliant on the binary and rewriting them right now was too much. Thanks @ashkulz
