### ISSUE TITLE
Support windows 2k 32bit version?

### ISSUE THREAD

**Issue by keny456789** [wkhtmltopdf/wkhtmltopdf#4423]
**Description**
Is wkhtmltopdf possible to support win 2k?

**Comment by ashkulz** [comment]
Try the MinGW-w64 version, but that's a very old OS so you're on your own 🤷‍♂

**Comment by keny456789** [comment]
> Try the MinGW-w64 version, but that's a very old OS so you're on your own 🤷‍♂
Thanks for your reply.
I just tried that. When I call it, It gives error, can it be fixed easily?
 
![image](https://user-images.githubusercontent.com/48779868/61509014-33b94a00-aa1f-11e9-8196-9af092089bdd.png)

**Comment by ashkulz** [comment]
Not sure, maybe use an older MinGW compiler? You'll have to experiment a bit with using a older version of mxe which supports Windows 2000 ... but then it's not likely to be using the latest libraries.

**Comment by keny456789** [comment]
I download wkhtmltox-0.12.5-1.mxe-cross-win32.7z. After extracting it,
There are folder _bin_ and _include_. What am I supposed to do to compile with mxe?
Sorry for asking that much question.

**Comment by ashkulz** [comment]
See wkhtmltopdf/packaging -- that's how the binaries get built.

**Comment by keny456789** [comment]
> See wkhtmltopdf/packaging -- that's how the binaries get built.

It seems a build for linux. Is there build for windows?
Is wkhtmltopdf.exe build by using visual studio C++?

**Comment by ashkulz** [comment]
It's a build **on** Linux, **for** Windows. Microsoft's compilers have dropped support for XP almost 2-3 versions back, forget Windows 2000. So you have to cross compile from Linux.

**Comment by keny456789** [comment]
I download windows installer **0.9.9** in obsolete download, it can be installed and run on windows 2000.
![2019-07-24_15h39_58](https://user-images.githubusercontent.com/48779868/61842224-fbf04d80-aec9-11e9-900e-50ec1fd97c38.png)
Thanks.

**Comment by ashkulz** [comment]
Ah, I thought you wanted the latest version working on it ... should've thought of them earlier 🤷‍♂
