### ISSUE TITLE
Display application change.

### ISSUE THREAD

**Issue by mgu1206** [wkhtmltopdf/wkhtmltopdf#4426]
When execute wkhtmltopdf from my application that based on Qt 5.9.5 eglfs by using QProcess..

Display change to whole black for few seconds..

after few seconds, it returns to my application.

I execute wkhtmltopdf like this..

**QStringList strlist;
strlist.push_back("test.html");
strlist.push_back("test.pdf");

QProcess process;
process.start("wkhtmltopdf", strlist);
process.waitForFinished();**

Is it wrong?

**Comment by mgu1206** [comment]
Noe I knew that wkhtmltopdf uses virtual x server.

then.. there is no way execute wkhtmltopdf on console without any window?

**Comment by ashkulz** [comment]
Please ask this on StackOverflow, as it seems to be more Qt related (calling a CLI application from it).
