### ISSUE TITLE
Header and Footer need margin to render. Intended behaviour?

### ISSUE THREAD

**Issue by KSneijders** [wkhtmltopdf/wkhtmltopdf#4429]
**wkhtmltopdf version(s) affected**: 0.12.5 (with patched qt)

**OS information**
Windows 10 Eduction

**Description**
Whenever I use `--header-html [page]` and `--margin-top: 0` together. The header will not be visible (rendered of screen?)

**How to reproduce**
header.html:

	<!DOCTYPE html>
	<html>
	<body>
		My header
	</body>
	</html>

page.html:

	<!DOCTYPE html>
	<html>
	<body>
		My awesome page
	</body>
	</html>

commands:

    // Render page and header
    wkhtmltopdf --header-html header.html page1.html test.pdf
    // Render only page
    wkhtmltopdf --margin-top 0 --header-html header.html page1.html test.pdf

**Expected behavior**
That the header is visible even when margin-top is set to 0.

**Comment by KSneijders** [comment]
Typed an entire report, clicked on "no thanks" when it asked me if there was anything simmilar and removed the entire report. I click submit because I didn't expect it to reset this....

**Comment by PhilterPaper** [comment]
With no header specified, wkHTMLtoPDF leaves a default top margin (about 4 lines). Adding a header (with no -T flag) reduces the top margin to the minimum amount needed to show the header. A larger margin (-T flag) gives extra space above the header text, while a smaller top margin starts cutting off the top of the header. A top margin of 0 hides the header.

Whether or not this was _intended_ behavior is unknown, considering how poorly documented this program is. Perhaps the intent was to have any (default or specified) top margin added _above_ the header, but someone misprogrammed it and ended up with the header _within_ the top margin (as well as the top margin being reduced to the absolute minimum)? That would be consistent with the observed behavior (the default margin disappearing), which suggests that what you're observing was **not** the intended behavior. We'll never know for sure unless the author of that code 'fesses up.

**Comment by KSneijders** [comment]
Thanks for the information! I wish this would get fixed. Luckily, I'm able to work around it by setting the `CSS` on the `body` element in the `header.html` to:

    body {
        position: absolute; 
        top: 100px; 
    }

**Comment by KSneijders** [comment]
@PhilterPaper I've used the workaround succesfully for the header. Do you perhaps know why this doesn't work for the footer? The footer only renders inside the `margin bottom`. The header just renders above the page which can be fixed by the `CSS` above...

**Comment by KSneijders** [comment]
I found another work-around. You can use `--header-spacing` and `--footer-spacing` with negative values to get the items in the screen. 

Example:

    wkhtmltopdf -T 0 -B 0 -L 0 -R 0 --header-spacing -30 --footer-spacing -30 ...

**Comment by ashkulz** [comment]
@KSneijders: this is intended behavior, although poorly documented. If you look at `pdfconverter.cc`, it "reserves" the header/footer height and writes it in the margin area -- the point is that the headers/footers are not part of the content area and need to be rendered separately. That's because there isn't support in the browser engine for such things (even CSS3 doesn't have it properly, I think) and wkhtmltopdf renders the header separately and injects it into a known area.

**Comment by KSneijders** [comment]
Thanks for the information! I appreciate the quick answers!

**Comment by KSneijders** [comment]
Thanks for the information! I appreciate the quick answers!

If I may ask, do you know where I can find an example for the `replace` functionality. I've tried everything I was able to find on the generated docs, github and SO.

**Comment by kavishatalsania** [comment]
I am using --header-html for rendering html. I've not given any top margin/padding to the header. Still some space is coming on header top. I don't want any space in top of the header.

Any help is appreciated!

**Comment by sfinck187** [comment]
Why do tables avoid the footer but not the header?

**Comment by cxdone** [comment]
> I am using --header-html for rendering html. I've not given any top margin/padding to the header. Still some space is coming on header top. I don't want any space in top of the header.
> 
> Any help is appreciated!

Any way to avoid the space in top of the header?
