### ISSUE TITLE
Header and Footer not displayed on Alpine release

### ISSUE THREAD

**Issue by nweber-taekni** [wkhtmltopdf/wkhtmltopdf#4431]
**wkhtmltopdf version(s) affected**: 0.12.5 (-r0)

**OS information**
Alpine : The header or footer are not displayed
Mac OS : The header and footer are displayed

**Description**
It's a Ruby on Rails project and I used wicked_pdf to generate the pdf structure.

After that the rendering is done by Wkhtmltopdf.
When I used wicked_pdf wrapper or direct command of Wkhtmltopdf, the footer is not displayed on Alpine.

I have try to add margin but without success.

**How to reproduce**
```
render pdf: "pdf-name", layout: "my-pdf.html.erb",
                 print_media_type: true,
                 page_size: 'A4',
                 margin: { bottom: 20 },
                 disposition: 'attachment',
                 #footer: {content: '<html><body><h1>TEST</h1></body></html>'} : Test with HTML in direct
                 footer: { html: { template: 'api/v1/pdf/footer.pdf.erb' } },
                 header: { right: '[page] of [topage]' }

```
Thanks in advance for your help,

BR

**Comment by nweber-taekni** [comment]
Hello, 

I find a solution to my problem with the docker image build with this repo : https://github.com/Surnet/docker-wkhtmltopdf

This image works in Alpine 3.10 with wkhtmltopdf 0.12.5.

**Comment by reiz** [comment]
It works for me now with the `surnet/alpine-wkhtmltopdf` image.
