### ISSUE TITLE
Exit with code 1 due to network error: ContentNotFoundError 

### ISSUE THREAD

**Issue by adikshirsagar** [wkhtmltopdf/wkhtmltopdf#4433]
wkhtmltopdf(pages=[html_path, ],
    ...:                     margin_top=0, margin_right=0,
    ...:                     margin_bottom=0, margin_left=0,
    ...:                     page_width='{}mm'.format(width),
    ...:                     page_height='{}mm'.format(height),
    ...:                     dpi=300, window_status='GOOGLEMAPLOADED',
    ...:                     output=pdf_path)

Exit with code 1 due to network error: ContentNotFoundError
---------------------------------------------------------------------------
CalledProcessError                        Traceback (most recent call last)
<ipython-input-26-4b99234f9869> in <module>()
      5                     page_height='{}mm'.format(height),
      6                     dpi=300, window_status='GOOGLEMAPLOADED',
----> 7                     output=pdf_path)

/home/vistabee/virtualenvs/vistabee/local/lib/python2.7/site-packages/wkhtmltopdf/utils.pyc in wkhtmltopdf(pages, output, **kwargs)
    108         pass
    109 
--> 110     return check_output(ck_args, **ck_kwargs)
    111 
    112 def convert_to_pdf(filename, header_filename=None, footer_filename=None, cmd_options=None):

/usr/lib/python2.7/subprocess.pyc in check_output(*popenargs, **kwargs)
    571         if cmd is None:
    572             cmd = popenargs[0]
--> 573         raise CalledProcessError(retcode, cmd, output=output)
    574     return output
    575 

CalledProcessError: Command '['/usr/local/bin/wkhtmltopdf', '--dpi', u'300', '--encoding', u'utf8', '--margin-bottom', u'0', '--margin-left', u'0', '--margin-right', u'0', '--margin-top', u'0', '--page-height', u'230mm', '--page-width', u'220mm', '--quiet', '--window-status', u'GOOGLEMAPLOADED', '/tmp/FI84li/source.html', '/tmp/FI84li/brochure-print.pdf']' returned non-zero exit status 1

Data:
html_path  = '/tmp/FI84li/source.html'  --- contains html code with images 
pdf_path = '/tmp/FI84li/brochure-print.pdf'

**Comment by Jacquers** [comment]
Take out the quiet flag, it will show you the actual underlying error. There is likely something missing, like a linked file. E.g. I had something similar and the html was missing a linked font file. The library is quite strict with having correct html to render.

**Comment by ashkulz** [comment]
Please reopen with command line example and actual HTML, as what @Jacquers said is correct 👍
