### ISSUE TITLE
not able to install latest version of UFT tool 14.53 as getting an error saying "cannot create wkhtmltopdf.exe" Access Denied. But I logged in as admin and installing the installer.exe file as admin too. Anyone faced this issue? please help if any solution found.

### ISSUE THREAD

**Issue by battula-chandrashekhar** [wkhtmltopdf/wkhtmltopdf#4434]
**wkhtmltopdf version(s) affected**: x.y.z 

**OS information**
Microsoft Windows (Office 360)

**Description**
- Registered for free trial of MicroFocus UFT 14.53
- tried to download both full installation package and Light version of installation package
- When clicked to install as Admin, getting error as "cannot create wkhtmltopdf.exe" Access Denied. "

**How to reproduce**
Same as above.

**Expected behavior**
UFT should have installed successfully with 60 day trial.

**Possible Solution**  
Looking for help in this area.
![UFT 14-53 version installation Issue](https://user-images.githubusercontent.com/53206888/62516135-d3f5d800-b841-11e9-8315-6ba8be7239c7.png)

**Comment by ashkulz** [comment]
Please get in touch with your vendor (`MicroFocus UFT 14.53`).
