### ISSUE TITLE
Install on Debian 9.9 fails due to unavailable dependencies

### ISSUE THREAD

**Issue by GameBurrow** [wkhtmltopdf/wkhtmltopdf#4438]
**wkhtmltopdf version(s) affected**: I've tried to install following versions

- (this one used to work) https://downloads.wkhtmltopdf.org/0.12/0.12.4/wkhtmltox-0.12.4_linux-generic-amd64.tar.xz

- https://downloads.wkhtmltopdf.org/0.12/0.12.5/wkhtmltox_0.12.5-1.stretch_amd64.deb

**OS information**
Docker php:7.2-fpm environment, Debian 9.9

**Description**
Can't install package manually on Debian 9.9 anymore. It's dependencies aren't available anymore.

```bash

The following packages have unmet dependencies:
 wkhtmltox : Depends: fontconfig but it is not installable
             Depends: libjpeg-turbo8 but it is not installable
             Depends: libx11-6 but it is not installable
             Depends: libxcb1 but it is not installable
             Depends: libxext6 but it is not installable
             Depends: libxrender1 but it is not installable
             Depends: xfonts-75dpi but it is not installable
             Depends: xfonts-base but it is not installable
E: Unable to correct problems, you have held broken packages.
```

**How to reproduce**
Try to install on php:7.2-fpm docker container

**Expected behavior**
It used to install without problems

**Comment by GameBurrow** [comment]
Looking more into it, looks like it's docker issue

**Comment by Toub** [comment]
See https://github.com/wkhtmltopdf/wkhtmltopdf/issues/2037#issuecomment-344423993
