### ISSUE TITLE
from STDIN and from file produce empty documents on Docker on AWS

### ISSUE THREAD

**Issue by stockersky** [wkhtmltopdf/wkhtmltopdf#4444]
**wkhtmltopdf version(s) affected**: 1.12.5 

**OS information**
Docker Buster-slim
wkhtmltopdf from the Buster Slim package
Docker deployed on AWS

**Description**
When Docker image is executed on my workstation, everything works fine.
When deployed on AWS (ECS), I can generated pdf and img from an url.
However, if input are from STDIN or local file, it produce blank page.

NOTE : I noticed that I don't need xvfb do generate documents from url. 

I also have some XDG_RUNTIME_DIR warning but they do not affect document from url.

**How to reproduce**
```
echo "<h1> hello world </h1>" | wkhtmltoimage - /tmp/test.png 
```

**Expected behavior**
should produce a document. Not a blank page.

**Possible Solution**  
I tried to solve the XDG_RUNTIME_DIR but did not succeed. Is this related?
```
StandardPaths: XDG_RUNTIME_DIR points to non-existing path '/bla/bla', please create it with 0700 permissions.
```
Whatever I created the dir with the right permission, it always complains...

**Comment by romeroyonatan** [comment]
I have the same issue with version 0.12.5

```bash
$ wkhtmltopdf -V
wkhtmltopdf 0.12.5
```

```bash
$ wkhtmltopdf --log-level info /tmp/j.html /tmp/j.pdf                                   
QStandardPaths: error creating runtime directory /tmp/runtime-root: File exists                                                                                        
Loading page (1/2)                                                                                                                                                     
Printing pages (2/2)                                                                                                                                                   
Done  
```

**Comment by stockersky** [comment]
Do you confirm that you cannot generate documents through STDIN pipe or that you only have the "QStandardPaths" error ?

I solved this with a workaround : I publish the page on local socket and get it the classical way. But it would have been more convenient to be able to use the STDIN way.

**Comment by vatanuki** [comment]
same issue for me, same image start in AWS get empty blank page, and same image on local machine docker works

wkhtmltopdf 0.12.5

**Comment by msirovy** [comment]
Same issue for me. Image started in baremetal centos 7. When I run wkhtmltopdf google.com google.pdf it works, when I run it via stdin, result is blank page.

**Comment by migueltg** [comment]
Same issue for me in ECS with centos 7 image

**Comment by michaljusiega** [comment]
Same issue related on dockerhub image as PHP 7.4 apache buster.

**Comment by TwanoO67** [comment]
Same issue here, it seems related with the libQT5Core, that seems shared between host and container.
Anyone would know how to force container to use lib not shared with the host ?

**Comment by simevo** [comment]
Same here on podman container inside CentOS7. Installing xvfb and setting XDG_RUNTIME_DIR does not help.

**Comment by rbalik** [comment]
Looks like we're running into this issue too. We're running with xvfb-run inside a docker container and the PDFs come back blank in AWS, but it works fine in a local docker environment. Any idea what might be causing it or a way to get around it? Inside the container, libQt seems to be the same version between both.

**Comment by devstu** [comment]
I am having the same problem but not using AWS, blank pdf. PHP 7.4.1 apache buster

**Comment by rbalik** [comment]
So we ended up fixing this by using 0.12.5 with a patched QT library. Can't use the version that is in the normal Debian repos. There's a package here that works: https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.5/wkhtmltox_0.12.5-1.stretch_amd64.deb

**Comment by devstu** [comment]
This worked for me and was a life-saver, Thank you!

**Comment by jamiebernardin** [comment]
yes, it worked.  thank you @rbalik !

**Comment by maurimiguel** [comment]
I'm having the same issue but the @rbalik solution with a patched QT library doesn't suit my case.

i'm using an archlinux docker image and running a docker container on AWS.

Everything works fine local but when  deployed on AWS (ECS) i got a black PDF page.

@stockersky did you find another workaround?

**Comment by ashkulz** [comment]
Please use the official binaries. If that doesn't work and you _have_ to use the distribution provided packages, please provide a reproducible test case.

**Comment by rubnov** [comment]
I am having a similar issue. Would appreciate your help:

Running in a docker container, python 3.8.5, pdfkit 0.6.1, and installing wkhtmltopdf in the docker file as follows: 
```
RUN apt-get install -y wget build-essential libgeos-dev libev-dev libssl-dev wkhtmltopdf
```
This installs the dist build `0.12.5-1 buster amd64` and my docker container shows the following info: 
```
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

$uname -m
x86_64
```
So the dist package seems to fit my architecture, and pdfkit indeed generates a valid pdf from html when running the container in my localhost (Mac OS X). However, it fails in production (Ubuntu 16.04), producing a blank-page pdf. 

SSH to the production host and testing this in a shell shows the error details: 

```
$ docker-compose -f <docker-compose.yml> run <container> python manage.py shell_plus
>>> import pdfkit
>>> html = open('sample.html', mode="r", encoding="utf-8")
>>> htmlstring = html.read()
>>> html.close()
>>> pdfkit.from_string(htmlstring, 'out.pdf')

OSError: wkhtmltopdf exited with non-zero code 1. error:
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
QStandardPaths: wrong ownership on runtime directory /tmp/runtime-root, -2 instead of 0
Exit with code 1, due to unknown error.
``` 

Following the suggestion above, I tried to download and install the official binary from the releases/downloads page. I've changed my Dockerfile to: 
```
# wkhtmltopdf
RUN mkdir -p /wkhtmltox
WORKDIR /wkhtmltox
RUN wget https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.5/wkhtmltox_0.12.5-1.buster_amd64.deb
ARG DEBIAN_FRONTEND=noninteractive
RUN dpkg -i ./wkhtmltox_0.12.5-1.buster_amd64.deb
RUN rm -r /wkhtmltox/
```

The above fails with the error:
```
Selecting previously unselected package wkhtmltox.
(Reading database ... 24789 files and directories currently installed.)
Preparing to unpack .../wkhtmltox_0.12.5-1.buster_amd64.deb ...
Unpacking wkhtmltox (1:0.12.5-1.buster) ...
dpkg: dependency problems prevent configuration of wkhtmltox:
 wkhtmltox depends on xfonts-75dpi; however:
  Package xfonts-75dpi is not installed.
 wkhtmltox depends on xfonts-base; however:
  Package xfonts-base is not installed.

dpkg: error processing package wkhtmltox (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 wkhtmltox
``` 

Why does this package have broken dependencies?  Am I installing it incorrectly?

Trying to resolve this, I added: 
```
RUN apt-get --assume-yes install xfonts-75dpi xfonts-base

```
to my Dockerfile before `dpkg` and was able to build the container. This even worked on my localhost, producing a valid pdf. However, it now fail again in production on Ubuntu 16.04 host with a different error: 

```
$ docker-compose -f <docker-compose.yml> run <container> python manage.py shell_plus
>>> import pdfkit
>>> html = open('sample.html', mode="r", encoding="utf-8")
>>> htmlstring = html.read()
>>> html.close()
>>> pdfkit.from_string(htmlstring, 'out.pdf')

OSError: wkhtmltopdf reported an error:
QFont::setPixelSize: Pixel size <= 0 (0)
QFont::setPixelSize: Pixel size <= 0 (0)
QFont::setPixelSize: Pixel size <= 0 (0)
QFont::setPixelSize: Pixel size <= 0 (0)
QFont::setPixelSize: Pixel size <= 0 (0)
QFont::setPixelSize: Pixel size <= 0 (0)
QFont::setPixelSize: Pixel size <= 0 (0)
QFont::setPixelSize: Pixel size <= 0 (0)
Exit with code 1 due to network error: HostNotFoundError
``` 

Please help me understand how to get wkhtmltopdf working.

**Comment by rubnov** [comment]
I ended up working around this issue by replacing `pdfkit.from_string()` with `pdfkit.from_file()`. Using the latter does not generate the `HostNotFoundError` error.
