### ISSUE TITLE
Embedded Pdf Conversion

### ISSUE THREAD

**Issue by ChrisSapphire** [wkhtmltopdf/wkhtmltopdf#4445]
I have html containing an embedded pdf using the html code below. The converted pdf only contains detail26 and detail27.
<object data="http://localhost:41367/UserImages/TopPosition.pdf" type="application/pdf" width="100%" height="100%" margin:"0px"></object>
<div id="detail26" style="font-family: Arial; font-size:44px; position:absolute; left:120px; top:120px; text-align: Left; z-index: 2; ">Text1</div>                    
<div id="detail27" style="font-family: Arial; font-size:44px; position:absolute; left:360px; top:360px; text-align: Left; z-index: 3; ">Text2</div>

Please see attached 
Test.html
[Test.html.txt](https://github.com/wkhtmltopdf/wkhtmltopdf/files/3516586/Test.html.txt)
 (code), 
TopPosition.pdf (embedded pdf), 
ManualTest.pdf (converted pdf)
CommandLine.txt (commandline used, version info, etc).
[TopPosition.pdf](https://github.com/wkhtmltopdf/wkhtmltopdf/files/3516583/TopPosition.pdf)
[ManualTest.pdf](https://github.com/wkhtmltopdf/wkhtmltopdf/files/3516578/ManualTest.pdf)
[CommandLine.txt](https://github.com/wkhtmltopdf/wkhtmltopdf/files/3516574/CommandLine.txt)

Thanks!

**Comment by ashkulz** [comment]
Embedded PDFs aren't recognized by wkhtmltopdf, you're better off combining PDFs with some other tool after you've done the conversion (e.g. `pdftk`).
