### ISSUE TITLE
Internal links not working

### ISSUE THREAD

**Issue by KevinMcCready** [wkhtmltopdf/wkhtmltopdf#4447]
This document was provided to me by the NZ Government who said there was nothing they could do it fix it. When I click on a link I get an error and can't easily find stuff in the pdf. 
![Gazette PDF wrongly formatted](https://user-images.githubusercontent.com/21234684/63318785-c7a66a80-c36b-11e9-82f8-6c423431304b.png)
Advice please.
[Gazette2018HearingAidRuels-go959.pdf](https://github.com/wkhtmltopdf/wkhtmltopdf/files/3518760/Gazette2018HearingAidRuels-go959.pdf)

**Comment by ashkulz** [comment]
Not sure what this has to do with this project?
