### ISSUE TITLE
Unwanted background color in output PDF

### ISSUE THREAD

**Issue by suushiemaniac** [wkhtmltopdf/wkhtmltopdf#4451]
**wkhtmltopdf version(s) affected**: 0.12.5

**OS information**
Manjaro Linux 18.0.4 "Illyria"
Linux Kernel 4.19.66

**Description**
When generating a PDF out of any HTML, the resulting PDF file has a dark background around the text, even though no such background was specified in the HTML. A custom CSS file was also **not** supplied.

![screenshot](https://i.postimg.cc/bJtPWyMk/wkhtmltopdf-background-issue.png)

The resulting PDF (with faulty background color) can be seen here: https://www.dropbox.com/s/zs628ai7fj45e03/wkhtmltopdf_background_issue.pdf?dl=0

**How to reproduce**
The following is a sample HTML that was generated from Markdown code through pandoc:
```html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="" xml:lang="">
<head>
  <meta charset="utf-8" />
  <meta name="generator" content="pandoc" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes" />
  <title>foofo</title>
  <style>
      code{white-space: pre-wrap;}
      span.smallcaps{font-variant: small-caps;}
      span.underline{text-decoration: underline;}
      div.column{display: inline-block; vertical-align: top; width: 50%;}
  </style>
  <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv-printshiv.min.js"></script>
  <![endif]-->
</head>
<body>
<h1 id="a-sample-file">A sample file</h1>
<p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum.</p>
<p>Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum.</p>
<p>Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.</p>
</body>
</html>
```

The original markdown is as follows:
```markdown
# A sample file

Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, 
sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. 

Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. 
Lorem ipsum dolor sit amet, consetetur sadipscing elitr,
sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat,
sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum.

Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.
```

…where pandoc was invoked as `pandoc -s --from markdown --to html5 --metadata pagetitle="foobar" "$MARKDOWN_FILE" -o "$HTML_FILE"`

**Expected behavior**
I expect the resulting PDF to be produced on a blank page, i.e. with white background.
A different background color should only be used iff I explicitly specify one.

**Possible Solution**  
I have a vague idea that this may be related to Xorg color profiles. Manjaro-i3 ships with a certain color theme already pre-installed (in `~/.Xresources`) but I am too unfamiliar with X-Server to be able to confirm this suspicion.

Also, I have taken a screenshot and picked the background color with GIMP. The hex value does not exactly correspond to any definition in `.Xresources`. But for my human eye, the color from the background and the system theme colors look virtually identical.

**Comment by PhilterPaper** [comment]
It works fine on my Win10 system with wkHTMLtoPDF 0.12.5 (patched qt) -- white background. I vaguely recall seeing a similar report about unexpected background colors a while back, and it was a local system issue (maybe Xorg). Maybe a thorough search of this ticket list will turn up the report in question, and its solution.

**Comment by suushiemaniac** [comment]
I was not able to find any online sources on the matter. Even a (somewhat) thorough search of closed tickets did not yield the desired results.

Eventually, I fixed the problem by chance because I installed wkhtmltopdf **with patched qt** because of another, completely unrelated issue. Now it just works, hooray!

**Comment by SecT0uch** [comment]
I have the exact same issue with `wkhtmltopdf 0.12.5-1` from the Arch community repo.

**Comment by ntd** [comment]
I had a similar issue in ArchLinux too (`wkhtmltopdf 0.12.16`). I have Qt5 configured with dark colors: the background turns back to white by selecting the default colors (with `qt5ct`) before generating the PDF .
