### ISSUE TITLE
Alignment changes

### ISSUE THREAD

**Issue by prabhakn** [wkhtmltopdf/wkhtmltopdf#4468]

**Comment by NOLFXceptMe** [comment]
This is not a `wkhtmltopdf` issue. The "Html View" you're talking about depends on the browser. On my browser (Firefox 69.0.1 on Linux), it renders just as seen in "Pdf View" above.

![Screenshot from 2019-10-01 22-39-33](https://user-images.githubusercontent.com/13779/66020634-8c37a980-e49c-11e9-96b4-b557273ea084.png)
