### ISSUE TITLE
0.12.6-dev QSslSocket errors Ubuntu 18.04

### ISSUE THREAD

**Issue by exptom** [wkhtmltopdf/wkhtmltopdf#4472]
Due to a number of rendering related errors in 0.12.5 I have to use 0.12.6-dev package (have been for over a year! hoping it might be properly released at some point.)

However I need to do a server upgrade to Ubuntu 18.04 and this now causes various "QSslSocket" errors when trying to render. I can see these are widely reported and the solution is "Upgrade to 0.12.5". The issues go away if I install libssl1.0-dev - which I don't want to do, I want the latest libssl-dev package installed.

For some reason even though 0.12.6-dev is newer than 0.12.5 the ssl errors are still present.

I am using the deb from here: https://builds.wkhtmltopdf.org/0.12.6-dev/
Specifically: wkhtmltox_0.12.6-0.20180618.3.dev.e6d6f54.bionic_amd64.deb

I am wondering if 0.12.6 is built differently to 0.12.5 and not built against the latest openssl lib?

**Comment by TejasAvinashShetty** [comment]
Same error here. was not present in the one downloaded from 
> sudo apt-get install wkhtmltopdf

i.e. the one without the Qt patch

**Comment by ashkulz** [comment]
Please see if the newer [0.12.6-dev snapshots](https://github.com/wkhtmltopdf/packaging/releases/tag/0.12.6-dev-20200124) fix it for you.

**Comment by ashkulz** [comment]
Please use the 0.12.6 release candidate, should be up in around 12-18 hours or so.
