### ISSUE TITLE
footer-html command argument removing header margin

### ISSUE THREAD

**Issue by mansoor945** [wkhtmltopdf/wkhtmltopdf#4474]
**wkhtmltopdf version(s) affected**: 0.12.5 (with patched qt)

**OS information**
Windows 10

**Description**
I only want to add the footer for the pdf using footer-html command argument and don't want to add the header for the pdf. The footer works fine but in the pdf, it removes the top margin and move all the content to top of the page.

I have attached the generated pdf in the attachment.
[test.pdf](https://github.com/wkhtmltopdf/wkhtmltopdf/files/3596983/test.pdf)

**How to reproduce**
wkhtmltopdf --footer-html "http://localhost:5000/footerurl" https://www.google.com test.pdf

**Expected behavior**
Footer works fine, but the margin for the header should be maintained.

**Comment by PhilterPaper** [comment]
There's been quite a bit of discussion about problems with margins in headers and footers. You might want to Google **site:github.com header margin** and read up on the wkHTMLtoPDF-related entries. I can't find the latest thread, but I seem to recall something about default margins (or padding) being overridden in certain cases when --header-html and/or --footer-html are used.

**Comment by mansoor945** [comment]
@PhilterPaper Thank you. --margin-bottom argument fixed the issue for me.
This [issue](https://github.com/wkhtmltopdf/wkhtmltopdf/issues/2561) helped me in fixing the issue.

**Comment by CarlosTorrecillas** [comment]
To me, applying `--margin-bottom 10` option made a multi-page pdf be reduced to just one and the footer misplaced (I'm on 0.12.5 Windows)
