### ISSUE TITLE
Add Page Number in Internal Link

### ISSUE THREAD

**Issue by zwadl** [wkhtmltopdf/wkhtmltopdf#4482]
**Description**
a flag that, if set, adds a page number to an internal link

**Example**  

for all links that look like this `<a href="#internal">LINKTEXT</a>` replace LINKTEXT with `<span data-pagenr="PAGENUMBER">LINKTEXT</span></a>` so you can do the rest with js and css...

nice to have: possibility to edit a template for internal links

**Comment by ashkulz** [comment]
That isn't generally possible, as if you change `LINKTEXT` it is quite possible that you'll have to redo the layout. I _think_ it's possible with a print-focused solution like PrinceXML or WeasyPrint but not supported by general browsers.
