### ISSUE TITLE
Problem with session scripts

### ISSUE THREAD

**Issue by alxx28** [wkhtmltopdf/wkhtmltopdf#4483]
The problem is that I am trying to print a scritpt like this from PHP:

system("C://\"Program Files\"//wkhtmltopdf//bin//wkhtmltopdf --post BYPASS yes --cookie sessionid $sessionID http://localhost/proyecto/hc/php/admisiones/ambulatorio/imprimir_ingreso.php?id_ingreso=55 hc.pdf");

But **imprimir_ingreso.php** at the beginning is like this:
session_start();
if (!isset($_SESSION['login'])) {
    header('Location:../../../index.php');
}

I don't get the desired page, how do I allow access to **imprimir_ingreso.php** with wkhtmltopdf?

**Comment by PhilterPaper** [comment]
Let's break this down into several pieces. I take it you're running on Windows? Is this PHP running on a local WAMPP stack? First, are you sure that you're successfully starting up and running wkHTMLtoPDF? `C://"Program Files"//wkhtmltopdf//bin//wkhtmltopdf` looks very strange. You don't need to double up /, but you would if you used \ instead. I think you want to put `\"` around the entire first term: `\"C:/Program Files/wkhtmltopdf/bin/wkhtmltopdf\"` (to treat the space as part of the single string). Finally, you might have to explicitly give the `.exe` file extension on the program (I'm not sure the normal command line .bat, .com, .exe search is done here).

Once you are sure that wkHTMLtoPDF is being run, do you have a way to test if your system knows how to handle `http://localhost`? Do you need a port number or anything like that?

Once you know that your system is reading and processing **imprimir_ingreso.php**, is that Location to the right place?

**Comment by alxx28** [comment]
It's running on wampserver, when I delete this part:
<?php
session_start();
if (!isset($_SESSION['login'])) {
    header('Location:../../../index.php');
}
?>
the pdf is generated with no problem.

**Comment by PhilterPaper** [comment]
So, is ../../../ where you would find index.php? `http://localhost/proyecto/hc/php/admisiones/ambulatorio/imprimir_ingreso.php` sounds like it would end up in ` http://localhost/proyecto/hc/` ... this works in a browser but not in wkHTMLtoPDF?
