### ISSUE TITLE
Debian stretch dependencies issue

### ISSUE THREAD

**Issue by inaz0** [wkhtmltopdf/wkhtmltopdf#4488]
Hi, 

I can't install the lastest version of wkhtmltopdf on my debian stretch because it ask for old packages that are not enable in this distribution.

The error:

> dpkg: dependency problems prevent configuration of wkhtmltox:
 wkhtmltox depends on libpng12-0; however:
  Package libpng12-0 is not installed.
 wkhtmltox depends on libssl1.0.0; however:
  Package libssl1.0.0 is not installed.

The package of installation used are **wkhtmltox_0.12.5-1.jessie_amd64.deb**

Best regards;

**Comment by gatiba** [comment]
You can install the missing dependencies adding a Xenial repository (temporarily):

sudo echo "deb http://mirrors.kernel.org/ubuntu/ xenial main" | sudo tee -a /etc/apt/sources.list && sudo apt-get update && sudo apt install -y --allow-unauthenticated libpng12-0

Then try to install it again!
Let me know if it works...

**Comment by inaz0** [comment]
Thanks work's for me !

**Comment by rafaeljusto** [comment]
> You can install the missing dependencies adding a Xenial repository (temporarily):
> 
> sudo echo "deb http://mirrors.kernel.org/ubuntu/ xenial main" | sudo tee -a /etc/apt/sources.list && sudo apt-get update && sudo apt install -y --allow-unauthenticated libpng12-0
> 
> Then try to install it again!
> Let me know if it works...

Thanks! To avoid the unauthenticated packages you could add the Ubuntu keys:

```sh
# sudo echo "deb http://mirrors.kernel.org/ubuntu/ xenial main" | tee -a /etc/apt/sources.list
# sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 40976EAF437D05B5
# sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 3B4FE6ACC0B21F32
# apt-get update
# apt-get install -y libpng12-0 libssl1.0.0
```

**Comment by ashkulz** [comment]
Strange, stretch uses OpenSSL 1.1 -- see wkhtmltopdf/packaging@ec3fdf4019eac97b3b57d83aabd7d12415bbb2a0. From the filename, you're trying to install a `jessie` binary on `stretch` -- which isn't going to work. Or am I missing something here?
