### ISSUE TITLE
help with Ubuntu 16.04

### ISSUE THREAD

**Issue by mikereape** [wkhtmltopdf/wkhtmltopdf#4495]
Hi

I'd be very grateful for any help with this.  I'm trying to get this running on WSL Ubuntu 16.04 x86_64. 
 This is all completely new to me.  I understand about the XDG_RUNTIME_DIR problem (tho don't know how to fix it) but the rest I haven't a clue about.  Why is it failing to get screen resources when there's no screen involved?  Do I need the relevant version of Qt running or something.

Thanks for any help.  Apologies if there's other info I should have provided and haven't

Here's the output:

mike@Zoostorm:/mnt/c/Users/Mike/OneDrive/Documents/Scans$ wkhtmltopdf Scans\ 6-25-081019-23_08.html Scans\ 6-25-081019-23_08.pdf
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-mike'
failed to get the current screen resources
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
Loading page (1/2)
QXcbConnection: XCB error: 170 (Unknown), sequence: 170, resource id: 90, major code: 146 (Unknown), minor code: 20
Printing pages (2/2)
QPainter::begin(): Returned false
Done
mike@Zoostorm:/mnt/c/Users/Mike/OneDrive/Documents/Scans$

**Comment by jesoonluo** [comment]
try add this to you bashrc
export QT_QPA_PLATFORM='offscreen'

**Comment by AdrienAdB** [comment]
@jesoonluo, thanks, it worked for me (Ubuntu 18.04)

**Comment by ashkulz** [comment]
Looks like you're using the distro-provided package instead of the one from the downloads page -- it's going to require xvfb running.

**Comment by gikwu1** [comment]
i have this same problem. 
Can someone help. This is on ubuntu 20

wkhtml error: QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-www-data' Exit with code 1 due to network error: UnknownNetworkError [string:Exception:private] => [code:protected] => 0 [file:protected]

**Comment by MxFlorin** [comment]
I have the same issue adding  export QT_QPA_PLATFORM='offscreen' to bashc did not help me. 
```

Dump => string(176) "QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-www-data'
qt.qpa.screen: QXcbConnection: Could not connect to display 
Could not connect to any X display.
"
```
