### ISSUE TITLE
bad kerning for fonts in output PDF

### ISSUE THREAD

**Issue by dandersson** [wkhtmltopdf/wkhtmltopdf#45]
This is the old [Issue #72 from Google Code](https://code.google.com/p/wkhtmltopdf/issues/detail?id=72), first reported in 2009. It still occurs with the dev branch of 0.12.0, tested with commit d6541feaaa8253516c92faae34293430efeb070a .

**What steps will reproduce the problem?**
1. Generate PDF from any HTML input with wkhtmltopdf via e.g.
   
   ```
   ./wkhtmltopdf test.html test.pdf
   ```
2. View it. Tested with Evince, Xpdf and Chrome's built-in PDF reader with similar results.

**What is the expected output? What do you see instead?**
_Expected:_ A PDF rendering similar to the one seen of the HTML document in a browser, specifically concerning the letter-spacing.

_Result:_ The kerning is way off. Sometimes too expanded, sometimes too condensed. See attached sample rendering of (from left to right):
1. an HTML document rendered by a browser (Chrome)
2. the resulting PDF rendered by Chrome's built-in PDF reader
3. the resulting PDF rendered by Evince

**What version of the product are you using? On what operating system?**
Dev branch of 0.12.0, tested with commit d6541feaaa8253516c92faae34293430efeb070a . Debian Sid, i386. Using the binary that resulted after building the Git revision with:

```
./build_linux.sh linux-i386
```

I have tested earlier versions of Wkhtmlpdf on Fedora (amd64) with identical results.

**Please provide any additional information below.**
I include the sample document and rendering below, but it happens with everything I throw to Wkhtmltopdf, so I don't think there are any specific "clues" in the minimal HTML code.
- [Generated PDF (semi-stable host)](http://510x.se/wkhtmltopdf/test.pdf)
- [Direct link to HTML document (semi-stable host)](http://510x.se/wkhtmltopdf/test.html)
- [HTML document at Pastebin](http://pastebin.com/rMWknFpd)
- Screenshot of rendering. Best viewed in full size. Note e.g. the whitespace after the letter "o" in the PDF renderings. ![wkhtmltopdf-sample-output](https://f.cloud.github.com/assets/3901008/2098351/04e09522-8f2b-11e3-87d6-018d3ce435ed.png)
- [Full `strace` output](http://pastebin.com/C7ra5yN2)
- [strace output, `grep`:ed for file I/O](http://pastebin.com/GN7aP460)

**Comment by nouknouk** [comment]
Hi,

FYI I also had the same kind of issue: rendering of little fonts were 'crappy' with wkhtmltoimage 0.12.2.1 (with patched qt) on a Debian 7.8

I found the following page about the differences of font configs between Debian and other derivated distros: 
  https://wiki.debian.org/Fonts (paragraph Subpixel-hinting and Font-smoothing).

For tests, I copied their sample XML content 'as is' in a file called "/etc/fonts/conf.d/100-wkhtmltoimage-special.conf"

Now the rendering is far better (cf screenshot before/after).

Hope it will help.
![wkhtmltoimage-config-font-before-after](https://cloud.githubusercontent.com/assets/4757213/7973919/aec45054-0a5b-11e5-8984-9e20466d29fe.png)

btw: many thanks for this amazing & highly usefull project.

**Comment by JensJI** [comment]
Hello

Sorry for writing in an very old issue, but maybe it could be informative.

I did also have problems with slighty different rendering of the font I'm using, and @r3mafe 's comment did help me.
I think what he means is, that if you use base64-encoded font in your stylesheet with the @font-face rule the generation of this (if you use a converter from TTF-file to base64-encoded string) is important, too, and some converters do a better job than others.

My stylesheet regarding the base64-encoded font was missing some things, and after regenerating the base64-encoded string incl. the stylesheet-bit the rendering was much better.

Thanks for the great software! The big work is much appreciated!

**Comment by cmrp** [comment]
Hello,
I had problems with slighty different rendering of the font like @JensJI . I tried to do use base64-encoded font but didn't work for me. My solution was change font-size because with specific sizes with word in bold there wasn't spacing.

I hope serve this information.

**Comment by KateWilkins** [comment]
No sure how or why but the --lowquality flag on the command line solved it for me and there didn't seem to be any noticeable drop in quality, in fact it made the output actually usable!

**Comment by jswing-mie** [comment]
Thank you nouknouk! I've been looking for this solution a **long** time.

https://wiki.debian.org/Fonts#Subpixel-hinting_and_Font-smoothing

Turns out it is not a wkhtmltopdf issue or even a webkit issue.  It's a Linux OS level font configuration issue.

**Comment by schungx** [comment]
`--zoom 1.3` works well in eliminating the obvious poor letter spacing.  It does not produce good kerning though.

Using it 0.12.2.4 on Windows 10.

**Comment by spung** [comment]
@KateWilkins wow thanks, that actually solved my kerning issues on OSX as well. So far I can't discern any difference in quality with/without that flag.

**Comment by andylemay** [comment]
Hi nouknouk, jswing-mie,

Please excuse my ignorance.  I tried as you said to create XML file and link it but it doesn't make any difference to wkhtmltopdf output.

Ubuntu 14.04.1, odoo 8

**Comment by jswing-mie** [comment]
@andylemay

It's possibly a difference in the distro so that link to Debian's wiki may not be useful to you. It worked for me on CentOS. Unfortunately, my knowledge on this subject ends with that wiki page so I have nothing left to offer.  Sorry.

**Comment by andylemay** [comment]
Here's the fix to the font smoothing / blocky fonts issue I was experiencing with Odoo 8.0 on Ubuntu 14.4.
This server was a bitnami build Odoo 8.0-12 (Odoo Version 8.0-20150423)

sudo apt-get remove xfonts-75dpi
sudo apt-get install xfonts-scalable

Beltran from Bitnami found this fix.  How long have I been trying to fix this!

**Comment by joelostblom** [comment]
On Arch Linux, the `wkhtmltopdf-static` (0.12.2.1-1) package from the `AUR` is compiled against the patched Qt-libraries and worked for me without any modifications (although note that I have the Ubuntu patched version of `cairo,` `freetype` and `fontconfig` since previously).

The `wkhtmltopdf` (0.12.2.1-2) package from the `ABS` is compiled against the unpatched Qt-libraries and none of the earlier suggested modifications (`--zoom 1.3`, `lowquality`, adding xml config files) alleviated the issues of disproportionate character spacing.

**Comment by erikverheij** [comment]
Adding the XML config file as suggested by @nouknouk solved it for me!

I'm on a AWS Linux AMI (based on CentOS/RHEL).

**Comment by MJBGO** [comment]
Perfect @nouknouk, works great ! Thanks :+1:

**Comment by juukie** [comment]
Thanks @nouknouk. Adding the XML did the trick for me. (on CentOS)

**Comment by jdavidbakr** [comment]
Just to chime in, I had a similar issue with the fonts rendering with wacky kerning and if copied and pasted from the generated PDF it would add spaces in random places.  In my case it was only happening on my production server but not on my development server (both EC2 instances running identical Amazon AMI distros).  I ran "sudo yum list installed | grep font" as a stab in the dark to see if there was something missing on the production machine that was not on the development machine, and two items showed up - ghostscript-fonts and urw-fonts.  I installed both of these on my development machine and now both PDFs render correctly.

**Comment by sjadema** [comment]
@nouknouk Thank you so much. Was having issues with font kerning in PhantomJS and this simple yet elegant solution fixed everything!

**Comment by AnderssonPeter** [comment]
Sadly this still seems to be a issue on windows tried both `0.12.1.0` and `0.12.3.2` both seem to have the same issue, but it only visible with small font sizes.

test.html:
```
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Test</title>
        <style>
        html {
          font-size: 10px;
        }
        body {
          font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
          font-size: 14px;
          line-height: 1.42857143;
          color: #333333;
          background-color: #fff;
        }
        .small
        {
            font-size: 0.8em;
        }
        </style>
    </head>
    <body>
        <h1>Test1</h1>
        <h2>Test2</h2>
        <h3>Test3</h3>
        Test4
        <div class="small">
            Namn small text name test ll11
        </div>
    </body>
</html>
```

Arguments: `wkhtmltopdf.exe test.html test.pdf --encoding UTF8 --disable-smart-shrinking`

**Browser output:**
![browser output](https://cloud.githubusercontent.com/assets/1308309/19961644/ff55e262-a1b3-11e6-8cb5-1bbe226da0e4.png)
**wkhtmltopdf output:**
![wkhtml output](https://cloud.githubusercontent.com/assets/1308309/19961647/02a8b552-a1b4-11e6-8c28-ec86c47c7fe5.png)

I have tried with and without the `--disable-smart-shrinking` different result but same issue, look at the m and a in small they have merged!

**Comment by benfavre** [comment]
Generally speaking the output of Fonts is handled at the system level.
I have had success tweeking my Ubuntu box with "infinality"

```
add-apt-repository ppa:no1wantdthisname/ppa
apt-get update
apt-get install fontconfig-infinality
/etc/fonts/infinality/infctl.sh setstyle win7

**Comment by rstarkov** [comment]
I am not sure whether this is applicable to wkhtmltopdf, but I recently had a kerning issue in Windows when Word was invoked from a service via COM. This issue was resolved by selecting a printer, namely "Microsoft XPS Document Writer", instead of relying on the default one.

I've not seen the internals of wkhtmltopdf, but I do wonder if that could help here. Surely Webkit has some sort of a printer setting; perhaps it will have the desired effect? I was skeptical about this myself, thinking "what could that possibly have to do with save-to-PDF", but it does in Word, so maybe it also does in Webkit?

**Comment by tumbudu** [comment]
<img width="280" alt="screen shot 2016-11-21 at 4 17 32 pm" src="https://cloud.githubusercontent.com/assets/308433/20479917/26749900-b006-11e6-8b42-9d3bffefb767.png">

In Html file only italic part is:
`<p class="TableContents">The characteristic  <math xmlns="http://www.w3.org/1998/Math/MathML"><msup><mi mathvariant="italic">eq</mi><mi>n</mi></msup></math>   of the matrix   <math xmlns="http://www.w3.org/1998/Math/MathML"><mfenced close="]" open="["><mtable><mtr><mtd><mn>3</mn></mtd><mtd><mn>1</mn></mtd><mtd><mn>1</mn></mtd></mtr><mtr><mtd><mrow><mi mathvariant="normal">−</mi><mn>1</mn></mrow></mtd><mtd><mn>5</mn></mtd><mtd><mrow><mi mathvariant="normal">−</mi><mn>1</mn></mrow></mtd></mtr><mtr><mtd><mn>1</mn></mtd><mtd><mrow><mi mathvariant="normal">−</mi><mn>1</mn></mrow></mtd><mtd><mn>3</mn></mtd></mtr></mtable></mfenced></math>  is</p>`

> wkhtmltopdf --window-status print-now -B 10 -L 5 -R 5 -T 10 /tmp/demo.html /tmp/demo.pdf

**Comment by chherren** [comment]
I have the same Problem like AndressonPeter.
I use wkhtmltopdf 0.12.3 on a Debian 7.9 Server.
I tried --disable-smart-shrinking and also diferent zoom-factors.
With the Font Arial it is verry bad. With the Font Verdana it looks a bit better.

Does everyone have an idea, how i can fix that problem?

[Test.pdf](https://github.com/wkhtmltopdf/wkhtmltopdf/files/701600/Test.pdf)

**Comment by AnderssonPeter** [comment]
@chherren try to avoid small font sizes as those seem to get the worst merging of chars but so far i haven't been able to eliminate the issue completely.

**Comment by punchi** [comment]
the solution that @nouknouk gives, worked for me too!! and I had to zoom 0.8 for CentOS (AWS Linux), working on Windows 7 @ashkulz any way to get a fix from the wkhtmltopdf side? at least a "FAQ" or like? I found the solution after many days with try/error and searching, as I'm working with a wrapper for Laravel too! (https://github.com/barryvdh/laravel-snappy) btw, thanks for the library! =)

**Comment by kylemacfarlane** [comment]
I was having this problem and followed the instructions of creating a `10-wkhtmltopdf.conf` but that then caused #2505 to manifest and incorrectly wrap some words. Both the kerning and the wrapping seems to be caused by the hinting settings.

I found the real solution was to upgrade freetype to 2.7 and all problems were fixed. I also have a box with freetype 2.5 installed that wasn't having problems but 2.7 has much better kerning so I'd advise going for the newest version you can.

**Comment by s5** [comment]
One thing that worked for me was using an SVG font instead of TTF or WOFF, at least for the Google Font Abril Fatface.

Notice the "o" and "e" when using TTF/WOFF:
<img width="278" alt="screenshot 2017-06-09 01 51 53" src="https://user-images.githubusercontent.com/928835/26968345-930ca538-4cb6-11e7-9195-0e4c639109c1.png">

And looks great with SVG:
<img width="248" alt="screenshot 2017-06-09 01 52 23" src="https://user-images.githubusercontent.com/928835/26968360-9c150cce-4cb6-11e7-86a4-03ab902b4eb8.png">

**Comment by KKSzymanowski** [comment]
I don't know if this is still relevant, but I solved the kerning issue on Windows 10 by setting the DPI to at least 200.

**Comment by stijnster** [comment]
@nouknouk I wish I could cuddle you!

**Comment by alqu** [comment]
@nouknouk Amazing! I fixed the bad kerning with the config both on Debian Jessie and CentOS 7. Cool.

**Comment by saltire** [comment]
The Debian page seems to have changed, so here's the XML mentioned in @nouknouk's answer:
```
<?xml version='1.0'?>
<!DOCTYPE fontconfig SYSTEM 'fonts.dtd'>
<fontconfig>
 <match target="font">
  <edit mode="assign" name="rgba">
   <const>rgb</const>
  </edit>
 </match>
 <match target="font">
  <edit mode="assign" name="hinting">
   <bool>true</bool>
  </edit>
 </match>
 <match target="font">
  <edit mode="assign" name="hintstyle">
   <const>hintslight</const>
  </edit>
 </match>
 <match target="font">
  <edit mode="assign" name="antialias">
   <bool>true</bool>
  </edit>
 </match>
 <match target="font">
  <edit mode="assign" name="lcdfilter">
   <const>lcddefault</const>
  </edit>
 </match>
</fontconfig>
```
It fixes the same issue with PDF rendering in PhantomJS, too. I was running an AWS Elastic Beanstalk machine, and used `.ebextensions` to add this file to the system.

**Comment by jishcat** [comment]
@KKSzymanowski Thank you for your comment:

> I solved the kerning issue on Windows 10 by setting the DPI to at least 200.

It worked for me too.  Definitely a problem, don't know why 96dpi is the default.

**Comment by SoTDarksoul** [comment]
Hi all, sorry for posting in a closed thread.

I tried everything that has been posted here but it seems my output doesn't match with my output version from Windows.

I'm on CentOS.

I created the file 05-wkhtmltopdf.conf but with or without it it doesn't change anything. 
The file contains the text from @saltire .
![image](https://user-images.githubusercontent.com/6214814/35688301-2a32c756-0771-11e8-9908-c60d926d15bb.png)

Am I missing something?

**Comment by vinhluan** [comment]
@s5 I'm having the same issue, but I can't seem to find the font in svg format. Could you tell me where do you get it please?

**Comment by mcmz** [comment]
See: https://github.com/wkhtmltopdf/wkhtmltopdf/issues/2022
Rendering in opentype format .otf did the trick for us.

**Comment by xmoles** [comment]
Hello 
Why happent this problem
![315ffe0d-f157-4c93-828d-9f46cb036938](https://user-images.githubusercontent.com/45140951/48671307-74766180-eb26-11e8-895f-37390de33127.jpeg)
](url)

**Comment by mayadafahim** [comment]
@vinhluan  how did you use the SVG file exactly to make it work

**Comment by rbk** [comment]
Found a solution to fix the kerning issue when using WKHTMLToPDF on AWS Lambda (Serverless) https://www.internalpointers.com/post/fixing-ugly-fonts-chrome-chromium-debian-xfce.

1. set two environment variables:
```
provider:
  name: aws
  runtime: python3.6
  environment:
    FONTCONFIG_PATH: '/var/task/fonts'
    FONTCONFIG_FILE: '/var/task/fonts/fonts.conf'
```

2. Put this in your fonts.conf file in your project.

```
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<fontconfig>
  <match target="font">
    <edit name="antialias" mode="assign"><bool>true</bool></edit>
  </match>
  <match target="font">
    <edit name="hintstyle" mode="assign"><const>hintnone</const></edit>
  </match>
  <match target="font">
   <edit mode="assign" name="hinting"><bool>false</bool></edit>
  </match>
</fontconfig>
```

**Comment by davehax** [comment]
> I don't know if this is still relevant, but I solved the kerning issue on Windows 10 by setting the DPI to at least 200.

This works on Azure App Service (Basic Tier or higher) as well 👍
