### ISSUE TITLE
Checkbox element differtent look between version 0.10.xx and 0.12.5

### ISSUE THREAD

**Issue by xivragis** [wkhtmltopdf/wkhtmltopdf#4500]
Centos 7/ Ubuntu 16.04/ Windows 7

OLD
![old](https://user-images.githubusercontent.com/56624393/66893553-a5893b80-efee-11e9-9fae-d904f67375cc.PNG)

NEW
![new](https://user-images.githubusercontent.com/56624393/66893554-a5893b80-efee-11e9-861a-84034eb09bf4.PNG)

is there any possibility to change this style to old one without editing html/css elements that i send to wkhtml ? Any switch in initial params will be great solution, but cant find any in documentation.

**Comment by ashkulz** [comment]
Version 0.10 is no longer supported. You can use the `--checkbox-svg` and `--checkbox-checked-svg` options in the latest release to use a different set of styles.
