### ISSUE TITLE
Multuthreading issues with wkhtmtopdf java

### ISSUE THREAD

**Issue by neha050** [wkhtmltopdf/wkhtmltopdf#4505]
I am using wkhtmtopdf v1.0.4. I know there are multithreading issues with wkhtmltopdf so I am using this library inside a synchronized block. 
Here is the code sample :

`synchronized public static boolean convertHtmlToPdf(String url , String filePath) {
HtmlToPdfObject o1 =   HtmlToPdfObject.forUrl(url).defaultEncoding("utf8").produceForms(true).
usePrintMediaType(true).enableIntelligentShrinking(true).loadImages(true);
		
return HtmlToPdf.create().pageSize(PdfPageSize.A4).orientation(PdfOrientation.PORTRAIT).compression(true).dpi(250).object(o1).convert(filePath);
	}`

In my application logs, i can constantly see following errors:

*** Error in `java': free(): invalid pointer: 0x00007f3dd40dd390 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x81499)[0x7f3e3a4fd499]
/tmp/io.woo.htmltopdf/wkhtmltox/0.12.4/libwkhtmltox.so(+0x200ae97)[0x7f3d0f2cfe97]
/tmp/io.woo.htmltopdf/wkhtmltox/0.12.4/libwkhtmltox.so(+0x200af39)[0x7f3d0f2cff39]
/tmp/io.woo.htmltopdf/wkhtmltox/0.12.4/libwkhtmltox.so(+0x1ffd0f7)[0x7f3d0f2c20f7]
/tmp/io.woo.htmltopdf/wkhtmltox/0.12.4/libwkhtmltox.so(+0x200aa17)[0x7f3d0f2cfa17]
/tmp/io.woo.htmltopdf/wkhtmltox/0.12.4/libwkhtmltox.so(+0x1efee29)[0x7f3d0f1c3e29]
/tmp/io.woo.htmltopdf/wkhtmltox/0.12.4/libwkhtmltox.so(+0x1effd35)[0x7f3d0f1c4d35]
/lib64/libpthread.so.0(+0x7de5)[0x7f3e3ae79de5]
/lib64/libc.so.6(clone+0x6d)[0x7f3e3a57abad]

**Comment by neha050** [comment]
Can someone please help

**Comment by ashkulz** [comment]
I think you're using some sort of wrapper, please report an issue with the library that you are using.

**Comment by neha050** [comment]
I have already mentioned I am using jar with wkhtmtopdf version 1.0.4.

**Comment by ashkulz** [comment]
There isn't a wkhtmltopdf version 1.0.4, and there isn't a JAR -- this is a native CLI and library, so you need to find out which wrapper you're using.
