### ISSUE TITLE
Add documentation of how to run wkhtmltopdf without an internet connection

### ISSUE THREAD

**Issue by nelson2005** [wkhtmltopdf/wkhtmltopdf#4506]
**Description**  

My build machine isn't routable to the internet, and each time I run wkhtmltopdf it tries to download files from the internet.

> Error: Failed to load https://cdnjs.cloudflare.com/ajax/libs/require.js/2.1.10/require.min.js, with network status code 3 and http status code 0 - Host  not found
> Error: Failed to load https://cdnjs.cloudflare.com/ajax/libs/jquery/2.0.3/jquery.min.js, with network status code 3 and http status code 0 - Host  not found
> Warning: Failed to load https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS_HTML (ignore)
> 

I didn't see any documentation about how to run without a net connection (did I miss it?  or maybe it's not possible?)
This was with v 0.12.5 on Windows, command line was `wkhtmltopdf.exe test.html test.pdf`

**Comment by NicTorgersen** [comment]
You'd have to host these files locally by editing your test.html file. Spin up a local webserver to handle those dependencies.

**Comment by securelinkmesvmc** [comment]
@NicTorgersen :
How can we create a local server for this

**Comment by ashkulz** [comment]
What @NicTorgersen said -- if your HTML contains those references, there'll be an attempt to fetch them.

**Comment by c33s** [comment]
@ashkulz would be cool to have a flag to let wkhtmltopdf continue without an error without fetching external data.

> This is part of the release notes, use --enable-local-file-access if you understand the security implications.

https://github.com/wkhtmltopdf/wkhtmltopdf/issues/4717#issuecomment-643744125

also would be cool to link the release notes and describe the security implications.

**Comment by Abhijit81** [comment]
I see the same error when I connect to company vpn, otherwise it doesnt show up. Any suggestion!
