### ISSUE TITLE
Add header and footer functions

### ISSUE THREAD

**Issue by swalikh** [wkhtmltopdf/wkhtmltopdf#4507]
Add a function to add header and footer

Demo:
 wkhtmltopdf  --header header.html  --footer footer.html  origin.html output.pdf

**Comment by martinnj** [comment]
According to documentation these are already in. :)
https://wkhtmltopdf.org/usage/wkhtmltopdf.txt
Search for `--header-html` or `--footer-html`.

**Comment by swalikh** [comment]
Thanks , Bro ~ ~
