### ISSUE TITLE
UnknownNetworkError

### ISSUE THREAD

**Issue by xiaolixi** [wkhtmltopdf/wkhtmltopdf#4511]
I want to know how to solve this problem.

```
C:\Users\df>wkhtmltopdf https://www.baidu.com/ D:\baidu.pdf
Loading pages (1/6)
Error: Failed to load https://www.baidu.com/, with network status code 99 and http status code 0 - Connection timed out
Error: Failed loading page https://www.baidu.com/ (sometimes it will work just to ignore this error with --load-error-handling ignore)
Exit with code 1 due to network error: UnknownNetworkError
```
My install package is wkhtmltox-0.12.5-1.mxe-cross-win64. And cannot use --load-error-handling ignore with Windows

**Comment by dkfjsdk** [comment]
从日志看，是网络问题，我这边没有复现。
![777](https://user-images.githubusercontent.com/57041250/67628034-0429a180-f89a-11e9-8cd1-0045e2e8a312.JPG)

**Comment by xiaolixi** [comment]
好的，可能是公司网络的限制

**Comment by xiaolixi** [comment]
> 从日志看，是网络问题，我这边没有复现。
> ![777](https://user-images.githubusercontent.com/57041250/67628034-0429a180-f89a-11e9-8cd1-0045e2e8a312.JPG)
