### ISSUE TITLE
encoding # in URL to %23

### ISSUE THREAD

**Issue by surferboy2** [wkhtmltopdf/wkhtmltopdf#4513]
I have a link in my html report that includes a # symbol that appears to be replaced by wkhtmltopdf with %23.  Not sure how to resolve as the %23 encoding is not handled by the site.

Original link in html:
![Screen Shot 2019-10-28 at 5 02 00 PM](https://user-images.githubusercontent.com/36051039/67726905-b2ba0900-f9a4-11e9-88b7-b5b5bf3008fa.png)

Link in final PDF output
![Screen Shot 2019-10-28 at 4 58 47 PM](https://user-images.githubusercontent.com/36051039/67726778-3cb5a200-f9a4-11e9-996b-20042b2a352e.png)

**Comment by ashkulz** [comment]
Duplicate of #4406
