### ISSUE TITLE
Process hangs when trying to read bytes from buffer to int. Wkhtmltopdf

### ISSUE THREAD

**Issue by 8m0** [wkhtmltopdf/wkhtmltopdf#4514]
My method creates PDF out of HTML content with Wkhtmltopdf program with Process. I can't find a reason why it hangs. When there is a big string with HTML, i suppose it hangs when there are 30 pages or more. But everything works fine if there are less pages. Wkhtmltopdf.exe process i can see at the Task Manager, it does not exit forever. When i stop my MVC project with hanged Wkhtmltopdf, it creates normally PDF like it would wait for something.. Manually, of course, Wkhtmltopdf creates everything without any problem.

`    
public IActionResult createPdf()
{
    string html = "content";

    Process p;
    ProcessStartInfo psi = new ProcessStartInfo();

    psi.FileName = "...\\wkhtmltopdf.exe";
    psi.WorkingDirectory = "...\\wkhtmltopdf\\bin";

    psi.UseShellExecute = false;
    psi.CreateNoWindow = true;
    psi.RedirectStandardInput = true;
    psi.RedirectStandardOutput = true;
    psi.RedirectStandardError = true;
    psi.StandardOutputEncoding = System.Text.Encoding.UTF8;
    psi.Arguments = "-O landscape --footer-left qwe --footer-center [page]/[topage] --footer-right --footer-font-size 9 --no-stop-slow-scripts --zoom 0.8 --dpi 300 - - ";

    p = Process.Start(psi);

    byte[] pdf = null;

    try
    {
        // Get PDF as bytes without temp files
        using(StreamWriter stdin = new StreamWriter(p.StandardInput.BaseStream, Encoding.UTF8))
        {
              stdin.AutoFlush = true;
              stdin.Write(html);
         }

         byte[] buffer = new byte[32768];
         using(var ms = new MemoryStream())
         {
              while(true)
              {
                   // HANGS HERE!!!
                   int read = p.StandardOutput.BaseStream.Read(buffer, 0, buffer.Length); 

                   if(read <= 0)
                   {
                       break;
                   }       
                   ms.Write(buffer, 0, read);
              }
              pdf = ms.ToArray();
          }      
    }
    ...
}
    `

**Comment by teyc** [comment]
Would this be relevant to your situation? https://stackoverflow.com/questions/12611350/started-process-hangs-when-redirected-output-is-relatively-big

**Comment by 8m0** [comment]
> Would this be relevant to your situation? https://stackoverflow.com/questions/12611350/started-process-hangs-when-redirected-output-is-relatively-big

Hi, thanks for the reaction. I don't think so. I don't use wait for exit before starting a process.

**Comment by 8m0** [comment]
Solved this problem this way: [merge separated pdfs](https://stackoverflow.com/questions/58542810/process-hangs-when-trying-to-read-bytes-from-buffer-to-int-wkhtmltopdf/58647310#58647310)

**Comment by ashkulz** [comment]
Cool, closing issue. I think using temp files would've been easier, but whatever works for you 👍
