### ISSUE TITLE
Is still actively maintained? What is the release workflow?

### ISSUE THREAD

**Issue by pedrofurtado** [wkhtmltopdf/wkhtmltopdf#4515]
:+1:

**Comment by ashkulz** [comment]
I haven't gotten the time lately, but the release is done via scripts in the `packaging` repository. Maybe you can clarify what you meant?

**Comment by neongrau** [comment]
Probably the question on the base webkit engine.
It's quite old now and CSS support and rendering issues that are long fixed in current webkit based browsers make it harder to use.
I've resorted to having a real old chromium browser build to get around.

**Comment by ashkulz** [comment]
QtWebKit was [recently revived](https://github.com/qtwebkit/qtwebkit), so I need to port the patches into it (as well as Qt) so that you can have an "official" build without patched Qt being required. Unfortunately, I haven't gotten the time so not sure on the timeline for that.

**Comment by willmtl** [comment]
@ashkulz Can we pay you to do it?

**Comment by ashkulz** [comment]
Answer to OP: it's all automated using Azure Pipelines, so while making a release can take time it doesn't have any manual intervention. I'm making a release candidate for the upcoming 0.12.6 release right now, will take at least 12-18 hours to complete.

@willmtl: that won't be possible. If you do want to show support, I'd request you to support https://github.com/qtwebkit/qtwebkit which is the engine on which this tool is based 👍
