### ISSUE TITLE
How to add image to header ?

### ISSUE THREAD

**Issue by vishal-brahmbhatt** [wkhtmltopdf/wkhtmltopdf#4517]
I am new to wkhtmltopdf. I am searching on web since last 3-4 hours but got nothing. How can I add image to header. I tried this

```
import pdfkit as pk

options = {
    'header-center': 'Header',
    'header-html': '<img src=\'logo.png\' />',
}

pk.from_file('indexref.html',
             'wkhtml2pdf doc test.pdf', options=options)

```

after doing this I am getting black PDF . 
Thanks!

**Comment by vishal-brahmbhatt** [comment]
`h`

**Comment by ankithryali** [comment]
header-html or footer-html needs a html file instead of string.
Please read [Documentation](https://wkhtmltopdf.org/usage/wkhtmltopdf.txt) for better understanding.

**Comment by ashkulz** [comment]
Please read the documentation or ask this question in the pdfkit repository.
