### ISSUE TITLE
Expired downloads.wkhtmltopdf.org certificate causing failed downloads 

### ISSUE THREAD

**Issue by giannidhooge** [wkhtmltopdf/wkhtmltopdf#4526]
**wkhtmltopdf version(s) affected**: all

**Description**

The SSL Certificate of `wkhtmltopdf.org` is expired since `Wednesday, 6 November 2019 at 10:59:47 Central European Standard Time`.

**How to reproduce**

Run `wget https://downloads.wkhtmltopdf.org/0.12/0.12.5/wkhtmltox_0.12.5-1.stretch_amd64.deb`

**Possible Solution**  

* Update SSL certificate
* Download with the `--no-check-certificate` (which feels dirty and unsafe)

**Comment by kwn** [comment]
Another workaround could be downloading the package directly from Github releases (https://github.com/wkhtmltopdf/wkhtmltopdf/releases).

```
wget https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.5/wkhtmltox_0.12.5-1.stretch_amd64.deb
```

**Comment by SimonErich** [comment]
The domain seems not to be reachable at all at the moment.
We had 3 aws pages crash because of this. We have implemented knplabs/snappy, that seems to try to download this from here. Since the download was not possible at server reinitialization time, the service did not start at all.
just leaving this here for anybody experiencing similar problems.
We just removed anything related to pdf creation form our pages as a dirty fix, but please take a look at the domain/server timeout problem.
Thank you guys

**Comment by SimonErich** [comment]
Small adition to that.
Now, that everything is up again, we just took some time to find alternatives and we are now downloading it from github directly, which works.

    2_install_wkhtmltopdf: 
        # see: https://wkhtmltopdf.org/downloads.html for updates 
        command: wget https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.4/wkhtmltox-0.12.4_linux-generic-amd64.tar.xz --dns-timeout=5 --connect-timeout=5
        test: test ! -f .wkhtmltopdf

**Comment by ashkulz** [comment]
There were two issues:
* SSL certificate expiry (which was resolved in ~1 hour, due to nginx not being restarted)
* Server downtime (this was due to a migration announced by our provider)

I don't expect any downtime in the future, please let me know if you face any issue.

**Comment by amrdruid** [comment]
@ashkulz Hello there, I can report that this happened that we had a bit of downtime. Is it worth to reopen the issue and see if it can be fixed?

**Comment by ashkulz** [comment]
@amrdruid it was fixed, see the linked issue.

**Comment by ashkulz** [comment]
Please note ba575ea7777a1cc2f3002a3feda4ee2a3e5b2664 -- I'm deprecating `downloads.wkhtmltopdf.org` and will remove the redirect in the future.
