### ISSUE TITLE
Different render between Debian 8 & Debian 9

### ISSUE THREAD

**Issue by reloxo95** [wkhtmltopdf/wkhtmltopdf#4527]
**wkhtmltopdf version(s) affected**: 0.12.5

**OS information**
Debian 8 & Debian 9

**Description**
I have two enviroments with similiar libraries but different OS, in env1 I have Debian 9 and in env2 Debian 8. The differente between them is than when I get the same PDF in env2 I get it with low quallity like pixeled fonts and maybe a little smaller than env1.

**Custom solution**
I was analyzing the behaviour of css classes and I discovered that en env1 css with class "#print-area" works fine but in env2 does not work.
I set the style directly on each class and works fine!! :dancing_men:  

Anybody with the same issue?, It is a known bug?, It is a own glitch?

Thanks in advance!!

**Comment by semente** [comment]
The # character isn't valid in CSS class names.
