### ISSUE TITLE
macOS cocoa app crashing after using wkhtmltopdf

### ISSUE THREAD

**Issue by hateom** [wkhtmltopdf/wkhtmltopdf#4531]
**wkhtmltopdf version(s) affected**: 0.12.5

**OS information**
macOS Catalina

**Description**
When generating pdf files using wkhtmltopdf library in my macOS cocoa application it works, the output file is generated but when the app goes in the background then as soon as it goes back in the foreground it's crashing with the error: 

Must construct a QApplication before a QPaintDevice

**How to reproduce**
Just use a simplest sample in Cocoa application.

**Expected behavior**
The application should not crash after the pdf is generated and the application is brought back to the foreground.

**Comment by ashkulz** [comment]
Are you using it as a library? If so, you shouldn't call init/deinit more than once -- it's not supported. See what the other wrappers do.

**Comment by hateom** [comment]
On top of that I was calling the library functions not from the main/UI thread. 
Now it seems to be working ok. Thanks for the reply.
