### ISSUE TITLE
composer安装wkhtmltopdf报出 cannot execute binary file

### ISSUE THREAD

**Issue by 715215778** [wkhtmltopdf/wkhtmltopdf#4533]
下载方式用的composer下载wkhtmltopdf，报出错误为（RuntimeException with message 'The exit status code '126' says something went wrong:
stderr: "sh: /Users/tal/Code/larabbs/vendor/h4cc/wkhtmltopdf-amd64/bin/wkhtmltopdf-amd64: cannot execute binary file）

conifg/snappy.php中使用的是'binary'  => base_path('vendor/h4cc/wkhtmltopdf-amd64/bin/wkhtmltopdf-amd64'),

请问各位有遇到过这个问题的吗？可以指导一下怎么解决吗？

**Comment by ashkulz** [comment]
Looks like a problem with the wrapper, please try to report to their repository.
