### ISSUE TITLE
Has anyone installed successfully on mips64?

### ISSUE THREAD

**Issue by tom-TangT** [wkhtmltopdf/wkhtmltopdf#4534]
Report error When i run ./scripts/build.py posix-local. but i had installed both make and gmake. 
![(QH9W69@$2MVO1THXRUG_OP](https://user-images.githubusercontent.com/52006536/69239140-888aee00-0bd4-11ea-847c-ea6fe6ce9156.jpg)
Is there something wrong with the qt version?
wkhtmltopdf -version:0.12.2
qt-version:4.8.7

**Comment by ashkulz** [comment]
@tom-TangT please see the approach used in wkhtmltopdf/packaging -- if there's a multiarch docker image, you can try to build for mips64 (there's one built for raspbian and ppc64le).

**Comment by tom-TangT** [comment]
Thanks for your response. But the packaging requires a kernel version higher than 4.8,the kernel version of the my machine is 3.10.Does it matter？------------------ 原始邮件 ------------------
发件人: "Ashish Kulkarni"<notifications@github.com>
发送时间: 2019年11月21日(星期四) 凌晨0:38
收件人: "wkhtmltopdf/wkhtmltopdf"<wkhtmltopdf@noreply.github.com>;
抄送: "tom-TangT"<2498825392@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [wkhtmltopdf/wkhtmltopdf] Has anyone installed successfully onmips64? (#4534)



@tom-TangT please see the approach used in wkhtmltopdf/packaging -- if there's a multiarch docker image, you can try to build for mips64 (there's one built for raspbian and ppc64le).
 
&mdash;

**Comment by tom-TangT** [comment]
Thanks for your response. But the packaging requires a kernel version higher than 4.8,the kernel version of the my machine is 3.10.Does it matter？

**Comment by ashkulz** [comment]
You can use a VM -- the reason for that requirement is wkhtmltopdf/packaging@fe12c55a33f6e70004b1e2b7e432892713570f41, which allows generic docker images to be used. If you have a suitable mip64 docker image (with `qemu-user-static` already in it), then you can revert that -- it should work with lower kernel versions.

Let's continue the discussion in that repository, once you've made some progress :+1:

**Comment by ashkulz** [comment]
@tom-TangT: support for ppc64le and 64-bit ARM was added in the upcoming 0.12.6, if you're interested would appreciate trying a build and creating a PR if any Qt changes are required.
