### ISSUE TITLE
need to add extra column in toc want to add page number dynamically

### ISSUE THREAD

**Issue by Anto1106** [wkhtmltopdf/wkhtmltopdf#4543]
current TOC is like this 
![image](https://user-images.githubusercontent.com/14937818/69811562-513fc100-1214-11ea-933a-c6ee52b8afc7.png)
need to create TOC such as this 
![image](https://user-images.githubusercontent.com/14937818/69811586-66b4eb00-1214-11ea-9408-5b7827cfe312.png)

**Comment by duranhumes** [comment]
One way I solved it was adding a custom element for each item in the loop like
`<span class="another-page"></span>`

I then used a placeholder like `Page 1 OF 'PAGE_TOTAL_COUNT'`

And then with `php` I counted how many times the custom element showed up and used that to replace the placeholder, so far it works.

```
$totalPages = \substr_count($snappy->html, 'span class="new-page"');
$html = \str_replace('PAGE_TOTAL_COUNT', $totalPages, $snappy->html);
$snappy->html = $html;
```

**Comment by ashkulz** [comment]
You can look to use the custom stylesheet XSL, but whatever works for you 😄
