### ISSUE TITLE
Debian format archive

### ISSUE THREAD

**Issue by xlievo** [wkhtmltopdf/wkhtmltopdf#4549]
OS: Debian GNU/Linux 10

RUN curl https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.5/wkhtmltox_0.12.5-1.buster_amd64.deb -O --progress
RUN dpkg -i wkhtmltox_0.12.5-1.buster_amd64.deb

dpkg-deb: error: 'wkhtmltox_0.12.5-1.buster_amd64.deb' is not a Debian format archive

**Comment by ashkulz** [comment]
You need to use `curl -L`, read the man page :joy:
