### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [wkhtmltopdf/wkhtmltopdf#4553]
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") like the following.
- [PageObject::clear](https://github.com/wkhtmltopdf/wkhtmltopdf/blob/4f1b79df10d91ec2cbd286c7b24b7604df30a8a4/src/lib/pdfconverter_p.hh#L83 "PageObject::clear function")
- [wkhtmltopdf_deinit](https://github.com/wkhtmltopdf/wkhtmltopdf/blob/e1d1db0c431c3299ad4991cc9afc686c3db78d4a/src/lib/pdf_c_bindings.cc#L328 "wkhtmltopdf_deinit function")

**Comment by ashkulz** [comment]
@elerch would appreciate a PR with those changes 👍

**Comment by elfring** [comment]
How do you think about to [use a development tool like “clang-tidy” for corresponding source code adjustments](https://clang.llvm.org/extra/clang-tidy/checks/readability-delete-null-pointer.html "Deletion of unnecessary null pointer checks")?

**Comment by ashkulz** [comment]
I'd be happy to add such a check as a part of Travis CI and have it run once beforehand :+1:
