### ISSUE TITLE
Print layout problem when product description is too long in qweb report

### ISSUE THREAD

**Issue by pradipyenpure7** [wkhtmltopdf/wkhtmltopdf#4555]
**wkhtmltopdf version(s) affected**: 0.12.5
Odoo version:11.0
**Description**
when I enter long text in my pdf report it skips 1st page and start printing from second page,Please help me out

[CLUDO_DEC_062_19-20 _R-1 (6).pdf](https://github.com/wkhtmltopdf/wkhtmltopdf/files/3948682/CLUDO_DEC_062_19-20._R-1.6.pdf)

**Comment by ashkulz** [comment]
Shouldn't you be asking this in the Odoo repository?

**Comment by fraxnet** [comment]
Was this problem ever solved?
