### ISSUE TITLE
Binary for version 0.12.5 having issue in libpng12.so.0

### ISSUE THREAD

**Issue by malavancs** [wkhtmltopdf/wkhtmltopdf#4561]
I'm running with AWS lambda environment. Upto version 0.12.4, there is no issue with libpng12.so.0
After upgrading to version 0.12.5 binary, I'm facing the following error.

> error while loading shared libraries: libpng12.so.0 "wkhtmltopdf"

Am I missing something here ?

**Comment by ashkulz** [comment]
You should use the CentOS 6 binaries.

**Comment by malavancs** [comment]
CentOS 6 binariers works fine
