### ISSUE TITLE
toc page return as empty

### ISSUE THREAD

**Issue by aswanivy** [wkhtmltopdf/wkhtmltopdf#4571]
**wkhtmltopdf version(s) affected**: x.y.z 
wicked_pdf(1.4.0)
wkhtmltopdf-binary (0.12.5)
**OS information**
Ubuntu 16.04

**Description**
i'm trying to generate a pdf with table of contents using wicked_pdf(1.4.0).But i am getting empty toc page.
toc: {
disable_dotted_lines: true,
disable_toc_links: true,
level_indentation: 1,
header_text: 'Contents',
text_size_shrink: 0.5
}

**How to reproduce**

**Expected behavior**
it should create contents with corresponding page numbers.

**Possible Solution**

**Comment by romarioliveira25** [comment]
same here!

**wkhtmltopdf version(s) affected:** 0.12.5
wicked_pdf(1.4.0)
wkhtmltopdf-binary (0.12.5)
**OS information**
Ubuntu 18.04

**Comment by YH-Smile** [comment]
same problem
Has the problem been solved?
my version:
wkhtmltox-0.12.5-1.msvc2015-win64.exe

html:
<html><head></head><body style="border:0; margin: 10;">
</br>
</br>
</br>
</br>
</br>

<hr>
<h1>1</h1>
<h1>2</h1>
<h1>3</h1>

</body></html>

pdf:
![image](https://user-images.githubusercontent.com/23691577/72265606-bd0caa80-3657-11ea-9702-77f8bd579e9b.png)

**Comment by aswanivy** [comment]
Problem Solved!

downgraded to
gem 'wkhtmltopdf-binary', '~> 0.12.3.1'
gem "wicked_pdf", '~> 1.1.0'

**Comment by ashkulz** [comment]
A release candidate for the **0.12.6** release is [now available for download](https://wkhtmltopdf.org/downloads.html#release-candidate), which should contain changes which possibly address this issue.

Would appreciate downloading the package and reporting back if any issues are encountered during testing. Assuming all goes well, I plan to release 0.12.6 on the 2-year anniversary of the previous release i.e. June 11, 2020.
