### ISSUE TITLE
Hyperlink to attached PDFs in a PDF document

### ISSUE THREAD

**Issue by ashishchandr70** [wkhtmltopdf/wkhtmltopdf#4573]
I have the following scenario - hopefully there is a solution for it (I have not been able to find a programmatic solution yet).

I have a plain text editor that I am using in a Qt application.
I export the text from plain text into an HTML using an existing template, and then wkhtmltopdf to convert the HTML document to PDF. I can create hyperlinks to files without issues so far.

My client now wants me to attach other PDFs to the generated PDF so I have the main PDF with PDF attachments. Additionally, they want me to hyperlink certain text in the PDF to the attached PDF(s).

Now, I know that using the PDFToolkit, I can attach PDFs to an existing PDF (don't think this is possible using wkhtmltopdf). But I am not sure about how to hyperlink from the main PDF to open one of the attached PDFs.

Any help would be greatly appreciated.

**Comment by PhilterPaper** [comment]
It's not clear to me exactly what you're trying to do. When you say "attach" a PDF (to an existing PDF), do you mean that you're _merging_ the two PDFs into one PDF? Whether links in one PDF pointing to another will successfully transfer probably depends on the tool you're using. Or is this "attachment" still a separate PDF file of some sort?

If you are starting with a plain text file and wish to create a PDF, you might want to look into building a tool based on the PDF::Builder library (Perl, on CPAN). It includes an example ("contrib") of reading in a text file and outputting a PDF. That is, skip the HTML stage. If your other files you want to merge into a single PDF are also plain text, a minor modification of this utility might do the job. However, you will still need to determine where you're making a link and its target, and invoking Builder library calls, so it's possible that formatting it as HTML might still be easier. 

If your additional content is already PDF files (not plain text or HTML), and you can't find a tool or utility to import the links correctly, I don't know what to suggest.

**Comment by ashishchandr70** [comment]
@PhilterPaper I am able to generate a PDF from the original text (Text -> HTML using HTML templates and then HTML -> PDF using wkhtmltopdf).

So far, so good.

Now, Once I have the finished PDF, I want to attach other PDFs (attach them not merge the attachments). This, I have discovered, is a feature made possible by the [PDF Toolkit ](https://www.pdflabs.com/tools/pdftk-the-pdf-toolkit/). So, now I have a PDF file, and in it are attached other PDF files.

Good so far.

Now, I want to open these attachments by clicking on certain keywords within the main PDF. That is what I am trying to find out - how to do that.

**Comment by ashishchandr70** [comment]
Hi - is anyone actively addressing issues/questions on this forum?

**Comment by ROBERT-MCDOWELL** [comment]
Hi,
I'm looking for the same feature with wkhtmltopdf.
to be more clear let's say I have some anchor links pointing to binary files on servers like images, pdf, applications etc... when I convert the html page I would like wkhtmltopdf to download the binary automatically and embed it into the pdf by attaching it in some way. Possible?
Thanks

**Comment by ashishchandr70** [comment]
I am closing this issue as I was able to get another third party library to do what I needed. @ROBERT-MCDOWELL I think you will need to take the same path (you probably have).

**Comment by ROBERT-MCDOWELL** [comment]
I found a trick to do it thanks

**Comment by HritikHS** [comment]
@ROBERT-MCDOWELL can you please share how did you do it or did you use any other library

**Comment by ROBERT-MCDOWELL** [comment]
it's an old issue, dunno remember what I did, I have to search in my code..

**Comment by ROBERT-MCDOWELL** [comment]
@HritikHS 
Ok I converted my hmtl page with wkhtml with fake links showing the name of the PDF file with a .TXT as extra extension (like mypdf.pdf.txt with a little note saying "See attached file" like this
<font class="paperClip">&#9733;</font>blasdf balbablablablablabal mypdf.pdf.txt<font style="font-size:9px">(See attached files. Note: remove the .txt extension after saved on your device)</font>
then I use cpdf --attach-file mypdf.pdf.txt  -i mypdf.pdf  -o mypdf.pdf to insert the file attached (can use multiple --attach-file options

**Comment by nechaurasia-fadv** [comment]
@ROBERT-MCDOWELL  Can you please help with above issue.  I have pdf where there are multiple attachment attached(Till year 2021 is was working fine). Now somehow my pdf is generated without the attachment. As such is there is no code change. But show how functionality is not working. Can you please some pointer on this.

**Comment by ROBERT-MCDOWELL** [comment]
without any logs or error message I can't help you.
