### ISSUE TITLE
0.12.6 is really needed !

### ISSUE THREAD

**Issue by mrdj07** [wkhtmltopdf/wkhtmltopdf#4578]
I really think you should take the time to build and release 0.12.6, I mean between 0.12.5 that can't generate  a TOC or 0.12.4 that crashes when adding footers and headers, we haven't got much choice here. 

The simple fact that you fixed the TOC problem could be a _great_ release !

Thanks for your hard work !

**Comment by stmlange** [comment]
+1, https://github.com/wkhtmltopdf/wkhtmltopdf/issues/3889 seems also be fixed with 0.12.6

**Comment by ashkulz** [comment]
I'm currently trying to automate the building of release binaries via Azure Pipelines (see wkhtmltopdf/packaging#49), as currently building them takes quite a bit of time (12+ hours) which makes me procrastinate on doing small, frequent releases. If that's automated, then I'm cool with releasing 0.12.6 as-is and doing follow-up releases as necessary.

**Comment by millzee01** [comment]
Hi, 
im using 0.12.5 on windows,  is there anything special i need to do to get up to 0.12.6?  reason is im getting "QNetworkReplyImplPrivate::error: Internal problem, this method must only be called once".  Which might be fixed in the latest release.

**Comment by ashkulz** [comment]
@millzee01 I don't think think it'll be fixed, please try using the MXE build as that seems to help some people :man_shrugging:

**Comment by millzee01** [comment]
Thanks @ashkulz ,  will do some testing.  
is the MXE build newer?

**Comment by ashkulz** [comment]
@millzee01: no, it's compiled differently.

Can someone give feedback on the [0.12.6 snapshot binaries](https://github.com/wkhtmltopdf/packaging/releases/tag/0.12.6-dev-20200124) and confirm it works for them?

**Comment by McShelby** [comment]
@ashkulz: The link seems to be a moving target because it's only valid for a day. So today it's https://github.com/wkhtmltopdf/packaging/releases/tag/0.12.6-dev-20200127

**Comment by ashkulz** [comment]
@McShelby: I'm still in the process of migrating all targets to Azure Pipelines, so yes till that time the tag is a bit unstable 🤷‍♂

**Comment by alexeygaidukov** [comment]
@ashkulz: Please, include commits for the pull request #4439 into 0.12.6.

**Comment by tonyellow** [comment]
Any news on this? When will 0.12.6 be officially released?

**Comment by ashkulz** [comment]
I'm planning to release it next week, a release candidate should be up in 12-18 hours (building packages for a total of 47 targets, so taking a bit of time).

**Comment by ashkulz** [comment]
A release candidate for the **0.12.6** release is [now available for download](https://wkhtmltopdf.org/downloads.html#release-candidate), which should contain changes which possibly address this issue.

Would appreciate downloading the package and reporting back if any issues are encountered during testing. Assuming all goes well, I plan to release 0.12.6 on the 2-year anniversary of the previous release i.e. June 11, 2020.

**Comment by harrywhite4** [comment]
Sweet. Was using that dev release, but will start testing out the release candidate today.
