### ISSUE TITLE
Latest release of wkhtmltopdf patched with QT for Alpine Linux

### ISSUE THREAD

**Issue by RyanPrice-King** [wkhtmltopdf/wkhtmltopdf#4581]
Can we have available a download for Alpine Linux patched with QT please. so it is not necessary to compile our own.

**Comment by ashkulz** [comment]
See wkhtmltopdf/packaging#2 -- someone needs to step up and submit a PR for the Qt patches required for working with musl.

**Comment by tonyellow** [comment]
I despirately need this to!
