### ISSUE TITLE
Digitally signed assemblies

### ISSUE THREAD

**Issue by ghernan99** [wkhtmltopdf/wkhtmltopdf#4585]
**Description**
Please digitally sign the assemblies delivered as part of your product (exe, dlls). Not only sign your assemblies with a strong name, but also digitally signed them with your certificate.

**Example**  
Not applicable.

**Comment by ashkulz** [comment]
I'm not sure what you're talking about, as this project only produces native DLL/EXEs, not .NET assemblies. If you're talking of code signing, that's not something I can really implement -- the next release will be fully automated and built on Azure Pipelines, and I don't have a certificate either.
