### ISSUE TITLE
Nodejs10.x support

### ISSUE THREAD

**Issue by nyel-dev** [wkhtmltopdf/wkhtmltopdf#4589]
AWS is now forcing users to use nodejs10.x. Apparently, wkhtmltopdf is not working on nodejs10.x. Any ways to fix this?

Previously working state:
nodejs8.10
AWS Lambda function

Ways to replicate:
Create lambda function that runs on nodejs10.x

**Comment by ashkulz** [comment]
Duplicate of #4523
