### ISSUE TITLE
html to pdf conversion issue on CentOS 6 using bleeding edge 0.13.0

### ISSUE THREAD

**Issue by kedarp274** [wkhtmltopdf/wkhtmltopdf#4592]
**wkhtmltopdf version(s) affected**: 0.13.0

**OS information**
Cent OS 6.10

**Description**
html to pdf conversion is failing  on Cent OS 6.10 when trying to use bleeding edge version 0.13.0 on terminal. No errors thrown (see screenshot attached)

We tried the same on Cent OS 7 and it works without any issue. 

**How to reproduce**
xvfb-run /usr/local/bin/wkhtmltopdf https://www.google.com test.pdf

**Expected behavior**
Application should generate a pdf file
![Capture](https://user-images.githubusercontent.com/43906370/72806432-2de92f00-3c23-11ea-924b-0bdde26cf96a.PNG)

**Possible Solution**

**Comment by ashkulz** [comment]
@kedarp274 that download isn't supported -- it hasn't been updated in 5 years and is anyway was a bleeding edge release -- where things aren't guaranteed to work :man_shrugging:
