### ISSUE TITLE
auto calculation of height for --header-html is broken

### ISSUE THREAD

**Issue by Req** [wkhtmltopdf/wkhtmltopdf#46]
There's something very fishy going on with version 0.12.0 feature --header-html installed from wkhtmltox-win32_0.12.0-03c001d.exe. I tried many tests on Windows 7, but didn't a single output as expected - **Nothing** worked as expected. For example:

```
c:\wkhtmltopdf12\bin>wkhtmltopdf.exe test-red.html test-red.pdf && test-red.pdf
... Done --> Nice PDF

c:\wkhtmltopdf12\bin>wkhtmltopdf.exe --header-html test-green.html test-red.html test-combo.pdf && test-combo.pdf
...  Done --> All white PDF

c:\wkhtmltopdf12\bin>wkhtmltopdf.exe test-red.html --header-html test-green.html test-combo2.pdf && test-combo2.pdf
... Done --> All white PDF
```

Both test-green and test-red are similar (Green <-> Red).
`<html> <head> <body style="background:Green;"> <p>TEST</p> </body> </html>`

Also, it crashes quite often; for example this resulted in a crash.

```
c:\wkhtmltopdf12\bin>wkhtmltopdf.exe www.google.com --header-html test-green.html gg.pdf && gg.pdf
Loading pages (1/6)
Counting pages (2/6)
Resolving links (4/6)
Loading headers and footers (5/6)
Printing pages (6/6)
[>                                                           ] Preparing
```

--> crash.

```
c:\wkhtmltopdf12\bin>wkhtmltopdf.exe --header-html test-green.html www.google.com gg.pdf && gg.pdf
```

--> Also crash, same output.

There were many different crashes and fail-outputs as well, all related to header-html, will add them here - should they become separate issues?

**Comment by tclancy** [comment]
For others seeing this behavior, make sure you set `--disable-smart-shrinking` to true (i.e., turn it off). That was biting me on Windows 7.
