### ISSUE TITLE
JavaScript is not executed at all with PDF format

### ISSUE THREAD

**Issue by arabakevin** [wkhtmltopdf/wkhtmltopdf#4606]
Given the following simple HTML code:

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta content="IE=Edge,chrome=1" http-equiv="X-UA-Compatible" />
    <meta content="width=device-width, initial-scale=1.0" name="viewport" />
  </head>
  <body>
    <p id="first-line">This is a line.</p>

    <script>
      let newDiv = document.createElement('div')
      newDiv.innerHTML = "Inserted line by JavaScript."
      document.body.insertBefore(newDiv, document.getElementById('first-line'))
    </script>
  </body>
</html>
```
Opening this page in my web browser. I can see the following.

<img width="321" alt="Capture d’écran 2020-02-05 à 07 21 06" src="https://user-images.githubusercontent.com/16837548/73816138-28294700-47e8-11ea-8a1c-735960106787.png">

When i'm running the following command:

```
wkhtmltopdf ./test.html ./test.pdf
Loading pages (1/6)
Counting pages (2/6)
Resolving links (4/6)
Loading headers and footers (5/6)
Printing pages (6/6)
Done
```

[test.pdf](https://github.com/mileszs/wicked_pdf/files/4157753/test.pdf)

So everything looks fine, but please see the attach PDF file.
Can you please help me to solve this issue ?

**Comment by arabakevin** [comment]
Hi,
Do you have any news/ideas or can i help you to help me ?
Missing details or informations ?
Thanks.

**Comment by peppe7119** [comment]
Hi,
I use different scripts for the generation of graphs (like google charts) to be inserted on pdf / images, and to run them I use the option:

`--javascript-delay 1000`

Time is expressed in milliseconds.
In my case I have no problems, both using version 0.12.4 and version 0.13alpha.
Try this and see if it's okay with you.

**Comment by PhilterPaper** [comment]
wkHTMLtoPDF 0.12.5 with patched QT fails for me, even with a delay of 10000. Possibly there's something newish in your Javascript that WebKit can't handle? Although, if it worked on 0.12.4... was that patched or unpatched?

**Comment by arabakevin** [comment]
i use the 0.12.4
and when i try to 
`wkhtmltopdf --javascript-delay 1000 ./test.html ./test.pdf`
I received the same PDF already upload above.
Thanks.

**Comment by arabakevin** [comment]
To solve this issue we need to replace "let" in "var.
Thanks.
Best.
