### ISSUE TITLE
External Links Unclickable (Alpha version).

### ISSUE THREAD

**Issue by Mellogab** [wkhtmltopdf/wkhtmltopdf#4614]
wkhtmltopdf version(s) affected**: 0.13

 I'm using  rotativa c# lib with wkhtmltopdf to convert the views in pdf. The all process works fine, but when i to try using external links in pdf, these links don't work.
The strangest thing, if i put the url in place of the description, the link works. But if I put the link in the href, it doesn't work.

<a href="https://google.com.br">some text</a> (Don't work)
<a href="some thing">https://google.com.br</a> (Work)

A way to fix this is to use the lastest stable version  (0.12.5).

**Comment by ashkulz** [comment]
Sorry, the 0.13 alpha version hasn't really been updated in 5 years and I haven't worked on it as such for quite a while ... plus it's an alpha version, so not guaranteed to be working 🤷‍♂️ 

I'll be updating the project status on the website in a week's time, just before the 0.12.6 release.
