### ISSUE TITLE
How tricky is it to update the version of webkit?

### ISSUE THREAD

**Issue by howardgrigg** [wkhtmltopdf/wkhtmltopdf#4625]
**Description**
I am using the binary and it is working well however newer features in webkit aren't rendering correctly - specifically CSS grid layout. 

Is there a way to update the version of webkit as a user of the software or does that need a proper release from you?

Thanks for maintaining such a great resource!

**Comment by ashkulz** [comment]
If you use the distro provided packages, they generally use the latest release available but don't have the patched Qt features. See #3217 on the gory details of what's required to update to the newer version 😄
