### ISSUE TITLE
Missing table of contents

### ISSUE THREAD

**Issue by troyeeee** [wkhtmltopdf/wkhtmltopdf#4643]
**wkhtmltopdf version(s) affected**: wkhtmltopdf 0.12.5 (with patched qt)
**OS information**

Linux troyee-pc 5.4.24-1-MANJARO #1 SMP PREEMPT Thu Mar 5 20:29:25 UTC 2020 x86_64 GNU/Linux
**Description**

I didn't get a page of contents when I generated a pdf with a 'toc' command, then I copied the command from the official document, I still couldn't get the table of contents.  
**How to reproduce**

I tried this:
<code>wkhtmltopdf toc http://qt-project.org/doc/qt-4.8/qstring.html qstring.pdf</code>
Then I got this:
[qstring.pdf](https://github.com/wkhtmltopdf/wkhtmltopdf/files/4357860/qstring.pdf)

**Expected behavior**

**Possible Solution**

**Comment by troyeeee** [comment]
I would be appreciate it if this issue could be solved.

**Comment by Lonerider2010** [comment]
Got the same problem and also interested in a solution. What I tried:
- produced an outline, which generated the pdf bookmarks without any problem,
- generated the xslt file with `--dump-default-toc-xsl`, which seems to be ok,
- generated a `toc.xml` with `--dump-outline`. which is also ok,
- generated a `toc.html` with the `default.xsl` and the `toc.xml`, which was also fine,
- then I generated the complete pdf containing `toc` with `--xsl-style-sheet default,xsl`, but got the same result as described by @troyeeee.

**Comment by panguangze** [comment]
> Got the same problem and am also interested in a solution. What I tried:
> 
> * produced an outline, which generated the pdf bookmarks without any problem,
> * generated the xslt file with `--dump-default-toc-xsl`, which seems to be ok,
> * generated a `toc.xml` with `--dump-outline`. which is also ok,
> * generated a `toc.html` with the `default.xsl` and the `toc.xml`, which was also fine,
> * then I generated the complete pdf containing `toc` with `--xsl-style-sheet default,xsl`, but got the same result as described by @troyeeee.
https://builds.wkhtmltopdf.org/0.12.6-dev/ This bug had been fixed in this version, but haven't release yet.

**Comment by Lonerider2010** [comment]
When will it be released?

**Comment by panguangze** [comment]
I don't know, but you can get the Installation package
 from this link https://builds.wkhtmltopdf.org/0.12.6-dev/

**Comment by Lonerider2010** [comment]
@panguangze thanks for this hint. I've tested V0.12.6 and it's fine for me. So if this version is released, the issue can be closed.
