### ISSUE TITLE
href to specific page number

### ISSUE THREAD

**Issue by Cowprod** [wkhtmltopdf/wkhtmltopdf#4645]
**Description**
I'm creating a table of content for pdf documents that are not generated with wkhtmltopdf.
TOC and documents are concatened with another tool.
I do not find a way to link a specific page of the final document from my TOC html code.

**Example**  
<a href="#realPage32">32 - My document</a>

regards

**Comment by ashkulz** [comment]
That's not possible, sorry. You're better off using a PDF library which can do this, as HTML =>PDF  can only depend on HTML links (rather than links to PDF pages).
