### ISSUE TITLE
QSslSocket: cannot resolve CRYPTO_num_locks

### ISSUE THREAD

**Issue by reinhardjung** [wkhtmltopdf/wkhtmltopdf#4655]
Hi

I love to migrate from one Provider to Kinsta (kinsta.com)...
If i run:
$/www/{ClientServer}/public/wp-content/plugins/toggl/wkhtmltox/bin/wkhtmltopdf --orientation Landscape --page-size A4 --zoom 1 --print-media-type  --quiet  --window-status ajaxComplete "https://marcweber.kinsta.cloud/?print=1&period_id=21&wp-cron-key=ea51fe64-bf83-4043-8f46-11f095bccff6" -

i got this Error:
QSslSocket: cannot resolve CRYPTO_num_locks
QSslSocket: cannot resolve CRYPTO_set_id_callback
QSslSocket: cannot resolve CRYPTO_set_locking_callback
QSslSocket: cannot resolve sk_free
QSslSocket: cannot resolve sk_num
QSslSocket: cannot resolve sk_pop_free
QSslSocket: cannot resolve sk_value
QSslSocket: cannot resolve SSL_library_init
QSslSocket: cannot resolve SSL_load_error_strings
QSslSocket: cannot resolve SSLv3_client_method
QSslSocket: cannot resolve SSLv23_client_method
QSslSocket: cannot resolve SSLv3_server_method
QSslSocket: cannot resolve SSLv23_server_method
QSslSocket: cannot resolve X509_STORE_CTX_get_chain
QSslSocket: cannot resolve OPENSSL_add_all_algorithms_noconf
QSslSocket: cannot resolve OPENSSL_add_all_algorithms_conf
QSslSocket: cannot resolve SSLeay
QSslSocket: cannot call unresolved function CRYPTO_num_locks
QSslSocket: cannot call unresolved function CRYPTO_set_id_callback
QSslSocket: cannot call unresolved function CRYPTO_set_locking_callback
QSslSocket: cannot call unresolved function SSL_library_init
QSslSocket: cannot call unresolved function SSLv23_client_method
QSslSocket: cannot call unresolved function sk_num
QSslSocket: cannot call unresolved function SSLv23_client_method
QSslSocket: cannot call unresolved function SSL_library_init
Error: Failed loading page https://marcweber.kinstacloud/?print=1&period_id=21&wp-cron-key=ea51fe64-bf83-4043-8f46-11f095bccff6 (sometimes it will work just to ignore this error with --load-error-handling ignore)
Exit with code 1 due to network error: UnknownNetworkError
QSslSocket: cannot call unresolved function CRYPTO_num_locks
QSslSocket: cannot call unresolved function CRYPTO_set_id_callback
QSslSocket: cannot call unresolved function CRYPTO_set_locking_callback

Kinsta Support, told me to as the Developer :-(

I hope you can help me and tell me what I can to or what Konsta can to to fix it?

thanx a lot in adv.

**Comment by thawkins** [comment]
+1, this is a blocker

**Comment by ashkulz** [comment]
Which version are you using?

**Comment by ashkulz** [comment]
No details provided, and please use the version matching with your OS/distro.
