### ISSUE TITLE
exit 1

### ISSUE THREAD

**Issue by foonlyboy** [wkhtmltopdf/wkhtmltopdf#4659]
**wkhtmltopdf version(s) affected**: x.y.z 
wkhtmltopdf 0.12.5 (with patched qt)

**OS information**
centos 3.10.0-957.21.2.el7.x86_64, Linux pro 5.3.0-46-generic #38~18.04.1-Ubuntu

**Description**
wkhtmltopdf stopped working
Exit with code 1, due to unknown error.

**How to reproduce**
echo 'test' | wkhtmltopdf --margin-top 0.75in - -
fails!

**Expected behavior**
echo 'test' | wkhtmltopdf --margin-top 19.05mm - -
works!

**Possible Solution**  
**Workaround**  
set margins explicitely to mm units

**Description**
I'm using wkhtmltodf via the ruby pdfkit.

The pdfkit gem sets the margins to some some default in units of inches:
aka: -margin-top 0.75in

This now fails hard. Not sure who is to blame.
While debugging this I also got:
Error: Currently all margin units must be the same! 

echo 'test' | wkhtmltopdf --margin-top 1mm - - # ok
echo 'test' | wkhtmltopdf --margin-top 1in - -   # fails
echo 'test' | wkhtmltopdf --margin-top 1px - -  # fails

Let's now search for the root cause.
I'll keep you updated.

Workaround for the pdfkit is:
explicitely specify the margins:

            kit   = PDFKit.new(
              html,
              margin_top:'19.05mm'
              margin_bottom:'0mm',
              margin_left:'0mm',
              margin_right:'0mm'
            )

**Comment by foonlyboy** [comment]
backlink to pdfkit:
https://github.com/pdfkit/pdfkit/issues/465

**Comment by ashkulz** [comment]
Looks like an issue in the `pdfkit` wrapper, can you report an actual commandline which fails?

**Comment by foonlyboy** [comment]
Hi Ashish

Thanks for your quick response.

I hope you can reproduce the bug with the command line given below.
There is no wrapper involved.


Please excuse that I didn't dig deeper, yet.
The workaround works perfectly for me.

It is defined in the css standard
how to calculate between cm/in/px

I'd have a look at the options parser first,
and how this trickles down.

I got it fixed for my case,
but the bug should not be closed.
The bug is still there!

Looks like you are hiding bugs.

Best regards
~eike






















Problem:
$ echo 'test' | wkhtmltopdf --margin-top 0.75in - -
Loading pages (1/6)
Error: Currently all margin units must be the same!
Exit with code 1, due to unknown error.


Workaround:
$ echo 'test' | wkhtmltopdf --margin-top 1mm - - > /dev/null
Loading pages (1/6)
Counting pages (2/6)
Resolving links (4/6)
Loading headers and footers (5/6)
Printing pages (6/6)
Done
