### ISSUE TITLE
Unicode support

### ISSUE THREAD

**Issue by muv1** [wkhtmltopdf/wkhtmltopdf#4662]
Using this file:

~~~html
<p>What’s the use?</p>
~~~

and this command:

~~~
wkhtmltopdf a.html a.pdf
~~~

I get this result:

~~~
Whatâ€™s the use?
~~~

**Comment by PhilterPaper** [comment]
You created the file (just one line?) with a Unicode (UTF-8) apostrophe, rather than an ASCII apostrophe. It's 3 bytes, not 1. You need to give more HTML in the file, including the fact that it's UTF-8 encoding, to get the apostrophe to be properly handled.

**Comment by muv1** [comment]
Yes thank you. Using something like this works as expected:

~~~html
<meta charset="utf-8">
<p>What’s the use?</p>
~~~

**Comment by PhilterPaper** [comment]
Good to hear. Don't forget to close this ticket if that's the answer you need.

**Comment by prdpspkt** [comment]
I've same problem. I'm developing a application in windows 10 and deploying it in Ubuntu 18.04. Both have same 0.12.5 (QT patched) version. In windows 10 installed font and 64 base encoded fonts both work well. But in Ubuntu both option doesn't work. It only renders black boxes. What might be the problem.

**Comment by muv1** [comment]
Seems this has gone off topic. @prdpspkt should post his concern as separate issue. Closing.

**Comment by muv1** [comment]
To anyone interested, I ended up using this instead:

<https://github.com/dompdf/dompdf>

**Comment by prdpspkt** [comment]
It just working fine for me. I just installed my font on server and activated. Its looks nice while I generate pdf report. It's great to be wkhtmltopdf as open source and free.
