### ISSUE TITLE
Bug: docs should mention whether it can convert an .html file to .pdf file

### ISSUE THREAD

**Issue by ORESoftware** [wkhtmltopdf/wkhtmltopdf#4667]
I find this very irritating to be honest. It seems like a common use case to convert an html file to pdf:

```bash
wkhtmltopdf  x.html x.pdf
```

but the docs only mention using websites like this?

```bash
wkhtmltopdf  abc.com x.pdf
```

is there a way to convert html files or does this only work with websites? I hear it uses puppeteer under the hood to download the html?

**Comment by PhilterPaper** [comment]
What version are you using? Looking at the help for 0.12.5 (patched qt), it clearly says a page object is `<input url/file name>`. Are there other docs you're looking at?

I can't tell you what it's using under the hood to download the HTML and related files.

**Comment by ashkulz** [comment]
Would appreciate a PR with updated text, as you're obviously in a better position to judge what would be best understood by someone new to the tool.
