### ISSUE TITLE
Unable to build in Windows when used with rust

### ISSUE THREAD

**Issue by last-Programmer** [wkhtmltopdf/wkhtmltopdf#4669]
I am trying to use the library https://github.com/anowell/wkhtmltopdf-rs in windows console application. I am not able to build successfully. This is the error i am getting

`/lowlevel.rs:92: undefined reference to wkhtmltopdf_init'``

i have the build.rs search for the library.

```
fn main() {
    println!(r"cargo:rustc-link-search=C:\Program Files\wkhtmltopdf\lib");
}
```
even after doing that i am getting the error.

Any help would be appreciated.

Thank You

**Comment by ashkulz** [comment]
Please open an issue with the upstream wrapper, as I can't really help you with Rust.
