### ISSUE TITLE
Filename Attribute?

### ISSUE THREAD

**Issue by WisconsinWildcat** [wkhtmltopdf/wkhtmltopdf#4672]
Is there a filename attribute option, so when the user goes to save the PDF file it can have a custom name instead of the name of the generating program?

**Comment by PhilterPaper** [comment]
Don't you normally give the output file name yourself on the command line? Or are you using some wrapper or toolkit that creates the output file name based on the input?

**Comment by ashkulz** [comment]
@WisconsinWildcat do you mean the output filename? That is specified on the CLI itself. If you mean the PDF title, I think you can use `--title` to specify it.
