### ISSUE TITLE
Footer height based on it's content

### ISSUE THREAD

**Issue by MomenYasser** [wkhtmltopdf/wkhtmltopdf#4673]
**wkhtmltopdf version(s) affected**: 0.12.2.1 

**Description**
The footer height is calculated based on the content of longest footer not based on current footer

Example: 

If we have 3 pages:

- Page 1 => Footer content height = 100px;
- Page 2 => Footer content height = 100px;
- Page 3 => Footer content height = 500px;

What actually happens is that: The three footers will be 500px

**Comment by ashkulz** [comment]
This is by design and cannot be changed, see [this comment](https://github.com/wkhtmltopdf/wkhtmltopdf/issues/4702#issuecomment-640563518).
