### ISSUE TITLE
Supporting more page sizes, or manual page size

### ISSUE THREAD

**Issue by bjornasm** [wkhtmltopdf/wkhtmltopdf#4683]
**Description**
Right now a number of page sizes is supported, however - several page sizes are not. Such as DL. There are many special use cases where this isn't as usable as preffered.
**Example**  

Implement a larger range of page sizes, or let users input height and width for custom size.

**Comment by ashkulz** [comment]
There is already `--page-width` and `--page-height` to use custom page sizes.
