### ISSUE TITLE
Could not find an IRouter associated with the ActionContext.

### ISSUE THREAD

**Issue by linliliu19** [wkhtmltopdf/wkhtmltopdf#4684]
I have an ASP.NET Core web application(with example ASP.NET Core Razor Pages content).
I put the following code into the PageModel
 
public async Task<IActionResult> OnPostGetPdfReportAsync()
        {
            return await _generatePdf.GetPdf("/Pages/PDFModel.cshtml", "Hello World");
        }
Here is my Pages/PDFModel.cshtml:

@model string
<!DOCTYPE html>
<html>
<body>
    <h1>@Model</h1>
</body>
</html>

When I run it, it gives the following error:
InvalidOperationException: Could not find an IRouter associated with the ActionContext. If your application is using endpoint routing then you can get a IUrlHelperFactory with dependency injection and use it to create a UrlHelper, or use Microsoft.AspNetCore.Routing.LinkGenerator.

**Comment by PhilterPaper** [comment]
Is this happening loading the page into a browser, or only when you feed the page to wkHTMLtoPDF? If the former, what does a .Net question have to do with wkHTMLtoPDF?

**Comment by ashkulz** [comment]
Please use StackOverflow for your .NET related questions.

**Comment by nick-kompas-cko** [comment]
Are you sure this is not a valid bug with wkHTMLtoPDF? If you google the internet you will find other people unable to make wkHTMLtoPDF work, even in the most simplest of cases.
For example here: https://groups.google.com/g/wkhtmltopdf-general/c/64FaQUfnwDU

Is there any evidence that wkHTMLtoPDF works at all for .NET core 3.1? I can't find any. Please re-open
