### ISSUE TITLE
Cannot display Graph in Pdf view But display fine when show as html

### ISSUE THREAD

**Issue by moeezsaiyam** [wkhtmltopdf/wkhtmltopdf#4691]
In my controller:

render template: 'qmcontrols/show',:type => 'application/pdf', pdf: "#{@project.identifier}_qmcontrol_#{@qmcontrol.id}",
        margin: {left: 15, right:  15 },
        :footer => {:center => "#{@project.name} / #{@location_details[0]['location_company']} / #{@qmcontrol.checkitem_location}", :right => '[page] / [topage]' },window_status: "FLAG_FOR_PDF"

show.pdf.erb:

head tag:
  <%= wicked_pdf_javascript_include_tag "plugin_assets/rtcharts/javascripts/chart.min.js" %>
  <%= wicked_pdf_javascript_include_tag "plugin_assets/rtcharts/javascripts/chart.helper.js" %>
  <%= wicked_pdf_stylesheet_link_tag "plugin_assets/rtcharts/stylesheets/rtdashboard.css" %>

body:

    <div class="current-situation-chart">
      <p style ="text-align: center;">Current Situation Chart Will be displayed here</p>
      <% charts = controlchart %>
      <div class="rtdashboard grid-container grid-cols-2">
        <% if charts.empty? %>
        <p class="nodata"><%= l(:label_no_data) %></p>
        <% else %>
            <% charts.each do |graph| %>
          <div>
            <%=  render partial: 'rtcharts/bar.html.erb',
                          formats: [:html],
                          locals: graph %>

          </div>
          <div id="base64">

          </div>
          <p id="p1">Hello World!</p>

            <% end %>
        <% end %>
      </div>
      <script type="text/javascript">
        setTimeout((function () {
          window.status = "FLAG_FOR_PDF";
          var canvas = document.getElementById('dashboard_bar_chart_actual_situation_control');
          var dataUrl = canvas.toDataURL();
          var image = document.createElement('img');
          image.src = dataUrl;
          document.getElementById("p1").innerHTML = "SHOW Base 64 in p tag "+dataUrl;
          // append to the DIV element
          document.getElementById("base64").appendChild(image);
      }), 10000);
      </script>
    </div>

It's working well when i do show_as_html:true and even show base 64 of canvas in a paragraph but when view in pdf It's not showing any graph nor any base64.
Please find the following attachments:
PDF VIEW:
![Screenshot from 2020-05-22 15-52-39](https://user-images.githubusercontent.com/42515773/82660727-540bf380-9c44-11ea-8d9e-87115aa46d1f.png)
VIEW_AS_HTML: true
![Screenshot from 2020-05-22 15-51-47](https://user-images.githubusercontent.com/42515773/82660732-553d2080-9c44-11ea-894f-3c4de53be9cf.png)

**Comment by moeezsaiyam** [comment]
Is there anyone to help?

**Comment by KaptenJon** [comment]
Did you try to add the jsdelay setting when rendering the page in wkhtml?

**Comment by moeezsaiyam** [comment]
Yes, I tried everything but it didn't work. At the last, I used web service "Quick Chart" that takes chart.js configuration using HTTP GET or POST requests and returns the base64 image that can be used as a source in the image tag.

Sample :

In Controller Filer:
@graphdata=”https://quickchart.io/chart?c={type:'bar',data:{labels:[2012,2013,2014,2015,2016],datasets:[{label:'Users',data:[120,60,50,180,120]}]}}”

In View File:
<img src= <%= @graphdata %> > #return with image of graph

**Comment by ken-wong** [comment]
I face the same problem.
I do not think your solution is the right way.

**Comment by KaptenJon** [comment]
I found a solution in another github thread. Use an javascript loader hack like this:
		function init() {
			google.charts.load('current', { 'packages': ['corechart'] });
			var interval = setInterval(function () {
				if (
					google.visualization !== undefined
						&& google.visualization.DataTable !== undefined
						&& google.visualization.LineChart !== undefined
				) {
					clearInterval(interval);
					drawLineChart();
					window.status = 'ready';
				}
			}, 100);
		}
	</script>
</head>
<body onload="init()">
