### ISSUE TITLE
is there a version for my pi4 arm-hf to install wkhtmltox-0.12.1_

### ISSUE THREAD

**Issue by GarethHards** [wkhtmltopdf/wkhtmltopdf#4695]
is there a version for my pi4 arm-hf to install wkhtmltox-0.12.1_

**Comment by ashkulz** [comment]
Why you do you need `0.12.1` specifically? You should be able to make builds for yourself once wkhtmltopdf/packaging#66 is merged.

**Comment by ashkulz** [comment]
Also, you're welcome to test the build I just posted on wkhtmltopdf/packaging#50

**Comment by ashkulz** [comment]
A release candidate for the **0.12.6** release is [now available for download](https://wkhtmltopdf.org/downloads.html#release-candidate), which should contain changes which possibly address this issue.

Would appreciate downloading the package and reporting back if any issues are encountered during testing. Assuming all goes well, I plan to release 0.12.6 on the 2-year anniversary of the previous release i.e. June 11, 2020.
