### ISSUE TITLE
print style does not effect when using GetByteArrayViewInHtml

### ISSUE THREAD

**Issue by jlprasantha** [wkhtmltopdf/wkhtmltopdf#4700]
I added a stylesheet with @media print {
    body {
        background-color: red;
    }
}

Html file link the style sheet with media='print'

and generated a pdf using  this.generatePdf.GetByteArrayViewInHtml(this.htmlView, invoiceList[0]);
This generated the pdf but it does not style as the print media type

Can you please let me know whats wrong here?

**Comment by ashkulz** [comment]
Looks like you aren't using wkhtmltopdf directly, please ask the issue in the repository for the wrapper you're using.
