### ISSUE TITLE
HTML5 video tag supported?

### ISSUE THREAD

**Issue by luiscastillocr** [wkhtmltopdf/wkhtmltopdf#4701]
Hi fellows,

I am using [imgkit](https://github.com/jarrekk/imgkit) to generate images out from some HTML files, some of these HTML files have iframes pointing to Instagram posts with embedded videos on them, the image renders just fine except for the video, it just shows a white space where the video is supposed to be, I can discard is a loading timing issue since other HTML files with images are rendered correctly, I could also discard a javascript loading issue since I am passing a fair amount of time using `javascript-delay` and `no-stop-slow-scripts` to make sure any JS have time enough to be executed

I also tried upgrading my webkit installation and installing some browser codecs but at this point, i ran out of ideas.

any advice is appreciated

**Comment by ashkulz** [comment]
Sorry, you can't embed videos in PDFs. Although that _may_ be possible if you generate directly via Adobe Acrobat -- that support isn't present in most browser engines. I just now tried it with Chrome 83, and it too doesn't embed the video :man_shrugging:
