### ISSUE TITLE
 I want to show the footer only on the last page,but it still taking space in other pages.

### ISSUE THREAD

**Issue by xsliang** [wkhtmltopdf/wkhtmltopdf#4702]
**wkhtmltopdf version(s)** wkhtmltoimage 0.12.5 (with patched qt)

**Description**

Hi
 I want to show the footer only on the last page,but it still taking space in other page.
I try to:
1. use set style "display:none" to hide the div

or

2. use remove div element 

all of the methods taking space in other pages. And when I use footer, and the actual margin top and buttom are dissapears. #2436

actually, I think the problem is The footer height is calculated based on the content of longest footer not based on current . #4673

thank you very much.

this is my footer.html
```
<!DOCTYPE html>
<html>

<head>
    <script>
        window.onload = function () {
            var vars = {};
            var x = document.location.search.substring(1).split("&");
            for (var i in x) {
                var z = x[i].split("=", 2);
                vars[z[0]] = unescape(z[1]);
            }
            var _body = document.body;
            var _div;
            //if current page number == last page number
            if (vars["page"] == vars["topage"]) {
                document.querySelectorAll(".extra2")[0].setAttribute("style","height:100px;");
                document.querySelectorAll(".extra2")[0].setAttribute("class","showDiv");
                document.querySelectorAll(".extra1")[0].setAttribute("class","displayNoneDiv");
            }
            else{
                document.querySelectorAll(".extra2")[0].setAttribute("class","displayNoneDiv");
            }
        };
    </script>

    <style>
        .extra {
            color: red;
        }
        .showDiv{
            display:block;
        }
        .displayNoneDiv{
            display:none;
        }
    </style>

</head>

<body>
    <div class="extra1">aaaaaaaaaaaaaaa</div>
    <div class="extra2">bbbbbbbbbbbbbbb</div>
</body>

</html>
```

**Comment by bhaveshselarka** [comment]
@ashkulz Many times it's required to have like this feature and its breaks.

like. The different headers for each page but the same footer in all the pages. page count completely wrong as well.

Is there any way to do this?

Thanks.

**Comment by ashkulz** [comment]
This is by design, you can't really have a dynamic footer size. The way rendering works, you first create a render tree and then start laying it out on every page. This can only happen if you know the size of the output area in which you're rendering to (the content area for wkhtmltopdf). If you want it dynamic for every page, you would need to rerun layout and render again _after every page_, which is not supported by any browser engine that I know of -- although it _may_ be supported by print-focussed tools such as PriceXML and/or WeasyPrint.
