### ISSUE TITLE
Expired GPG Signing Key

### ISSUE THREAD

**Issue by gfdusc** [wkhtmltopdf/wkhtmltopdf#4704]
Hello,
the key used for signing release packages has expired.

http://keys.gnupg.net/pks/lookup?op=vindex&fingerprint=on&search=0xA86EF3CB8C64CF2A

Best,

**Comment by ashkulz** [comment]
I'm not sure if you saw the [0.12.6-rc release](https://github.com/wkhtmltopdf/packaging/releases/0.12.6-rc) -- it explicitly mentions that there won't be any signing keys used for future releases, as they're all generated via an automated run on Azure Pipelines.

**Comment by ashkulz** [comment]
Thank you for the concern shown, though! Do let me know if you have any suggestions on the approach taken.
