### ISSUE TITLE
wkhtmltopdf generates unportable pdf for google.com

### ISSUE THREAD

**Issue by trsoluti** [wkhtmltopdf/wkhtmltopdf#4705]
**wkhtmltopdf version(s) affected**: 0.12.5

**OS information**
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

**Description**
Note: this does not seem to be a problem with wkhtmltopdf per se, but something has changed in the underlying world and has exposed a problem in the pdf generation.

If I create a simple PDF with wkhtmltopdf on my Debian installation, e.g. `wkhtmltopdf www.google.com google.pdf`, the pdf that is generated can be read on Debian, but on Mac OS it displays garbage for the text. (see attached).

using `strings | grep -I fontname` to look at the pdf shows that wkhtmltopdf is generating blank font names:

/FontName /QICAAA+
/FontName /QOCAAA+
/FontName /QUCAAA+
/FontName /QADAAA+FreeSerif
/FontName /QGDAAA+DroidSansFallback

(The FreeSerif and DroidSans are from language-local (Chinese and Thai) text on my region's Google home page)

`fc-match sans-serif` produces:
`DejaVuSans.ttf: "DejaVu Sans" "Book"`

**How to reproduce**
`wkhtmltopdf www.google.com`

You can also reproduce this with a very simple html page:
```html
<!doctype html><html><head></head><body><p>hello, font not specified</p><p style="font-family sans-serif">hello sans serif</p><p style="font-family:arial">hello, arial font</p></body></html>
```

**Expected behavior**
pdf should be portable to all operating systems

**Possible Solution**  

[google-12.5.pdf](https://github.com/wkhtmltopdf/wkhtmltopdf/files/4751626/google-12.5.pdf)

**Comment by ashkulz** [comment]
Can you add the exact URL for the country-specific site? I see a different site when I go to `https://www.google.com`...

**Comment by trsoluti** [comment]
You can try [https://www.google.com.sg](https://www.google.com.sg)

**Comment by ashkulz** [comment]
Hmm, looks like you're using the package supplied by the distribution. Do the binaries installed from the homepage work for you? Because this is what I get when I use them:

[google.pdf](https://github.com/wkhtmltopdf/wkhtmltopdf/files/4751991/google.pdf)

**Comment by trsoluti** [comment]
I checked the fonts in your version of the google page and there's no sans-serif font. You can try the simple html script I put in the problem report for a simpler situation.

I made sure I was using the version from the .deb I downloaded, and that version uses the patched Qt. Note the problem appeared when I updated Debian (sometime in the last year, I haven't used wkhtmltopdf in that long), as the version (0.12.3 patched) was working fine before and stopped working with the exact same symptoms as the 0.12.5 version.

Whose responsibility is it to identify the font for the pdf text, wkhtmltopdf or Qt? Under what circumstances will it come up with a blank file name? If I can patch my Debian to work around the problem I can produce my company annual reports from Odoo...

Thanks for taking a look at this. All the best.

**Comment by ashkulz** [comment]
With the HTML snippet you posted earlier, I get [4705.pdf](https://github.com/wkhtmltopdf/wkhtmltopdf/files/4752089/4705.pdf) -- which has both serif and sans-serif fonts embedded.

The font embedding is done deep inside Qt, so I strongly suspect a bug there. When I ran
```
docker run --rm -t -v$PWD:/out debian:bullseye sh -c "apt-get update && apt-get install -y wkhtmltopdf xvfb && xvfb-run wkhtmltopdf https://www.google.com /out/4705_qt5.pdf"
```
I got [4705_qt5.pdf](https://github.com/wkhtmltopdf/wkhtmltopdf/files/4752145/4705_qt5.pdf) -- but this doesn't have any fonts at all, not sure if the fonts need to be installed locally?

**Comment by trsoluti** [comment]
Okay! Resolved the issue on my Debian system. To restore whatever had been corrupted, I needed to run:
```
dpkg-reconfigure fontconfig-config
dpkg-reconfigure fontconfig
```
Then wkhtmltopdf works fine.

I'll close the problem now, but you should (somehow) pass it on the Qt that they can generate empty font names in the PDF document under some circumstance.

Thanks for your help.

**Comment by ashkulz** [comment]
Great that you got it sorted :+1:
