### ISSUE TITLE
Feature to add header, body and footer based on the html code provided.

### ISSUE THREAD

**Issue by Pooraa-Chaitanya** [wkhtmltopdf/wkhtmltopdf#4707]
We are provided with html code of header, body and footer in the form of string. Based on the string values, generate the pdf document.

header := "<HTML><body>Header</body></html>"
body := "<HTML><body>Body</body></html>" 
footer := "<HTML><body>Footer</body></html>"

fund convertHtmlToPdf(header string, body string, footer string){
generatePdf(header, body, footer);
}

**Comment by ashkulz** [comment]
Please ask this on StackOverflow or on the wrapper you're using.
