### ISSUE TITLE
Warning: Blocked access to file: Worked in 0.12.5

### ISSUE THREAD

**Issue by Vatiken** [wkhtmltopdf/wkhtmltopdf#4717]
> C:\Users\servi\Desktop\Python\pdfkit>wkhtmltopdf output.html o.pdf
Loading pages (1/6)
Warning: Blocked access to file C:/Users/servi/Desktop/Python/pdfkit/logo.png
Warning: Blocked access to file
Error: Failed to load about:blank, with network status code 301 and http status code 0 - Protocol "about" is unknown
Error: Failed to load about:blank, with network status code 301 and http status code 0 - Protocol "about" is unknown
Counting pages (2/6)
Resolving links (4/6)
Loading headers and footers (5/6)
Printing pages (6/6)
Done
Exit with code 1 due to network error: ProtocolUnknownError

Windows 10 - 64 Bit
My actual program uses Pdfkit in Python 3 to generate pdf invoices. Everything works great on our development computer which is using 0.12.5, but won't work on 0.12.6

I've removed all reference to local images from the html and the conversion works as expected.

**Comment by ashkulz** [comment]
This is part of the release notes, use `--enable-local-file-access` if you understand the security implications.

**Comment by bkravchenko** [comment]
--enable-local-file-access is not working on OS X 10.15. 

this is the command being used: wkhtmltopdf "/private/var/folders/kd/qm_szc4x2w3524fw4p854_1m0000gn/T/Jun-24-2020-09-54-26.html" "some.pdf" --enable-local-file-access

I am getting the same error report by Vatiken

**Comment by madamadami** [comment]
I've got the same problem as @bkravchenko did on macOS 10.15.7. Using pdfkit for python, I've set
```
wkhtmltopdf_options = {
    'enable-local-file-access': None,
    'javascript-delay': 2000000
}
```
but I think, local file access still isn't enabled; did I set it correctly at all?

**Comment by devkbsc** [comment]
In which file you have modified or added these code ?

```
wkhtmltopdf_options = {
    'enable-local-file-access': None,
    'javascript-delay': 2000000
}
```

**Comment by madamadami** [comment]
I added the the variable wkhtmltopdf_options directly to my python programm and finally called `pdfkit.from_string(html, 'export/pdf/' + filename + '.pdf', options = wkhtmltopdf_options)`.

**Comment by adozee** [comment]
I am still facing the issue. Tried the fix suggested by @madamadami . System is stuck and pdf is not generated .

**Comment by j4ggr** [comment]
> I am still facing the issue. Tried the fix suggested by @madamadami . System is stuck and pdf is not generated .

I had the same problem that the system stucked. After removing the option `'javascript-delay': 2000000` it worked.
So just use:
```
options = {'enable-local-file-access': None}
pdfkit.from_string(html, 'filename.pdf', options=options)
```

**Comment by devkbsc** [comment]
> > I am still facing the issue. Tried the fix suggested by @madamadami . System is stuck and pdf is not generated .
> 
> I had the same problem that the system stucked. After removing the option `'javascript-delay': 2000000` it worked.
> So just use:
> 
> ```
> options = {'enable-local-file-access': None}
> pdfkit.from_string(html, 'filename.pdf', options=options)
> ```

Could you please detail what you did ? which file you have modified! 

INSTANCE OF THIS ERROR : 
In my case, i get this error only on the MAC Webserver when i try to generate a PDF file in the SYMFONY /PHP Environment. 

Which file in the system i shall edit ?

**Comment by j4ggr** [comment]
There is no file to modify. My code sample is just about how to use it in a python file with the pdfkit library.

**Comment by maguluri-venkat** [comment]
not working for me also. tried both ways

**Comment by pedrosimarrosantamaria** [comment]
@j4ggr  you saved me , thank u :) 👍

**Comment by asmshaon** [comment]
This is working for Laravel SnappyPdf

```php
        $pdf->setOptions([
            'enable-local-file-access' => true,
            'footer-center' => '[page]',
            'margin-top' => 10,
            'margin-bottom' => 10,
        ]);
