### ISSUE TITLE
Image using local file path rendered properly in html but not in pdf

### ISSUE THREAD

**Issue by ASL07** [wkhtmltopdf/wkhtmltopdf#4723]
**wkhtmltopdf version(s) affected**:  0.12.6 (with patched qt)

**OS information**
Os X
**Description**
I have this in my .md file 
`<img src="/Users/developer/Documents/md/img/file.jpg"/>`

The image gets rendered properly in the .html file, but when I convert to pdf using 
wkhtmltopdf file.html file.pdf, then the image is not shown in the pdf file (just a blank line instead)

There are no errors in the cmd output, please see the output below:
```
Loading pages (1/6)
Counting pages (2/6)                                               
Resolving links (4/6)                                                       
Loading headers and footers (5/6)                                           
Printing pages (6/6)
Done            
```       

I have also tried using relative path and even using a local http server and using a url path instead of file path

Thanks

**Comment by ashkulz** [comment]
This is because of a breaking change in `0.12.6` -- you'll need to use `--enable-local-file-access` to allow that.

**Comment by ASL07** [comment]
Hello,

This is still happening even if I use 
`wkhtmltopdf file.html --enable-local-file-access file.pdf`

**Comment by ASL07** [comment]
Hi @ashkulz,
Could you have a look at this? Thank you

**Comment by ashkulz** [comment]
Does `wkhtmltopdf --enable-local-file-access file.html file.pdf` work for you?

**Comment by aleuarore** [comment]
Hello,
does anyone know how to implement this in c++? I'm using the c++ library.

Thanks in advance.

**Comment by san9443** [comment]
@ashkulz could you please help where to write / include this html comment "wkhtmltopdf --enable-local-file-access file.html file.pdf " I am struggling to find solution. Please advice.
