### ISSUE TITLE
--header-right [page] NOT working in latest build

### ISSUE THREAD

**Issue by MelJunk** [wkhtmltopdf/wkhtmltopdf#4728]
**wkhtmltopdf version(s) affected**: 0.13.0.0

**OS information**
Windows Server 2012 R2

**Description**
The switch --header-right, is not support using unpatched qt, and will be ignored.

**How to reproduce**
wkhtmltopdf.exe --header-right [page] mytest1.html mytest1.pdf

**Expected behavior**
Should put the page number in the top right corner of the resulting PDf file
Worked in c 0.12.4.0

**Possible Solution**

**Comment by ashkulz** [comment]
@MelJunk: 0.13 hasn't been worked on in a long while, see the project status on the website. If you're using a binary for that, it's almost 5 years old and not completed -- please use the current stable version.

**Comment by MelJunk** [comment]
Thank you for your reply. Does version 12.6 support --javascript-delay? I have an issue with a html file containing a chart, wont convert the chart to PDF with v12.6, however it works when using v13.0.

See attached the html file I am testing against (note I had to rename to .txt to upload it).
[mytest1.txt](https://github.com/wkhtmltopdf/wkhtmltopdf/files/4804426/mytest1.txt)
