### ISSUE TITLE
cannot download 0.12.1.3

### ISSUE THREAD

**Issue by RumenTD** [wkhtmltopdf/wkhtmltopdf#4729]
vesion: 0.12.1.3
system: ubuntu 18.04 LTS
details: wget https://builds.wkhtmltopdf.org/0.12.1.3/wkhtmltox_0.12.1.3-1~bionic_amd64.deb
--2020-06-19 11:40:18--  https://builds.wkhtmltopdf.org/0.12.1.3/wkhtmltox_0.12.1.3-1~bionic_amd64.deb
Resolving builds.wkhtmltopdf.org (builds.wkhtmltopdf.org)... 107.174.217.167
Connecting to builds.wkhtmltopdf.org (builds.wkhtmltopdf.org)|107.174.217.167|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-06-19 11:40:19 ERROR 404: Not Found.

**Comment by ashkulz** [comment]
That wasn't an official release, please use [0.12.1.4-2](https://github.com/wkhtmltopdf/packaging/releases/tag/0.12.1.4-2).
