### ISSUE TITLE
generate PDF doesn't works anymore with google JS API

### ISSUE THREAD

**Issue by runerod** [wkhtmltopdf/wkhtmltopdf#4733]
Hi guys,

Currently i'm not able to generate charts in PDF anymore (worked until few weeks...). It just don't generate charts. (text, and image are ok).

The code was this :
```
    <script type="text/javascript" src="http://www.google.com/jsapi"></script>

    <script type="text/javascript">
        spandata = document.getElementsByClassName("spandata")
        spandatadate = document.getElementsByClassName("spandatadate")
        function init() {
            google.load("visualization", "1.1", {
                packages: ["corechart"],
                callback: 'drawCharts'
            });
        }
        function drawCharts() { // PROCESS OF GENERATING CHARTS... }
    </script>
```
Because they closed the HTTP url and redirected this one to a new (below), I changed the URL to

`<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>`

doesn't work on PDF (work on web, with same data, same HTML template)

My controller which generate the PDF looks like this (data and filter are 2 PHP arrays)

```
$headerHtml = view()->make('pdf.header', compact('data'))->render();
$footerHtml = view()->make('pdf.footer', compact('data'))->render();

         
$pdf = \PDF::loadView('pdf.report', compact('data', 'filter'))->setPaper('a4', 'portrait');
$pdf->setOption('enable-javascript', true);
$pdf->setOption('javascript-delay', 5000);
$pdf->setOption('enable-smart-shrinking', true);
$pdf->setOption('no-stop-slow-scripts', true);
$pdf->setOption('margin-left',0);
$pdf->setOption('margin-right',0);
$pdf->setOption('margin-top',0);
$pdf->setOption('margin-bottom',0);
$pdf->setOption('margin-top', '40mm');
$pdf->setOption('margin-bottom', '30mm');
$pdf->setOption('header-html', $headerHtml);
$pdf->setOption('footer-html', $footerHtml);
```

The "funny" fact here is that where I show the charts on the webpage (not in PDF), it works.

So, what's the point ? Could it be so unloaded JS library before rendering ? 

wkhtmltopdf 0.12.5 (tested on wkhtmltopdf 0.12.4 (with patched qt) too, didn't work)

**Comment by runerod** [comment]
Finally able to get this work...  Thanks to https://github.com/barryvdh/laravel-snappy/issues/255#issuecomment-628815194
```
<script type="text/javascript" src="http://www.google.com/jsapi"></script>

    <script type="text/javascript">

        spandata = document.getElementsByClassName("spandata")
        spandatadate = document.getElementsByClassName("spandatadate")
        function init() {
          google.charts.load('current', {packages: ['corechart']});
          var interval = setInterval(function() {
            if ( google.visualization !== undefined && google.visualization.DataTable !== undefined && google.visualization.PieChart !== undefined ){ clearInterval(interval);
              window.status = 'ready';
              drawCharts();
            }
          }, 100);
        }



        function drawCharts() { // PROCESSING ... }
</script>
```

**Comment by ritesh-indexnine** [comment]
I tried above solution mentioned at https://github.com/barryvdh/laravel-snappy/issues/255#issuecomment-628815194 as well 
But after some days i'm getting error - **'undefined' is not a function ×**
@runerod

**Comment by marcelolinhares** [comment]
I am in same situation of @ritesh-indexnine, it was working, but in last 3 days i am getting error 'undefined i not a function x'.

Anyone can fix this?

**Comment by marcelolinhares** [comment]
> I tried above solution mentioned at [barryvdh/laravel-snappy#255 (comment)](https://github.com/barryvdh/laravel-snappy/issues/255#issuecomment-628815194) as well
> But after some days i'm getting error - **'undefined' is not a function ×**
> @runerod

Did you fix this @ritesh-indexnine ?

**Comment by ritesh-indexnine** [comment]
@marcelolinhares not fixed yet. Please comment solution here when you found, i will do the same :), Thanks!
@runerod @tobinibot @awt

**Comment by narcisrm** [comment]
@ritesh-indexnine @marcelolinhares To fix this, change the version of google charts to a previous one, seems like the july update introduced this error. 
Change `google.charts.load('current', {packages: ['corechart', 'line']});` 
to `google.charts.load('48', {packages: ['corechart', 'line']});`
You can check all the versions [here](https://developers.google.com/chart/interactive/docs/release_notes#Releases).

**Comment by ritesh-indexnine** [comment]
Thanks @narcisrm changing google charts version to **47** fixed it.
@marcelolinhares @runerod

**Comment by dalisay** [comment]
Encountered this issue recently. I have tried all the workarounds to fix the loading issue - setOnLoadCallback, delays, setInterval, setTimeout. Also tried upgrading the wkhtml version.

What worked for me is explicitly define the Google Charts version number to use. In my case version 44.

`<script>google.load("visualization", "44", {packages:["corechart"]});</script>`

Note: using version "1" now means you are using the current version. Per Google document - "All 'jsapi' requests are now being redirected to the new loader. If you were loading version '1' or '1.0', you will now be loading 'current'."
