### ISSUE TITLE
I am working with Angstrom ,and I want to install wkhtmltopdf onto it.How can I complete this task??

### ISSUE THREAD

**Issue by AnekaIjantkar** [wkhtmltopdf/wkhtmltopdf#4736]
We use GitHub issues only to discuss about wkhtmltopdf bugs and new features. For
this kind of questions about using wkhtmltopdf, please use
any of the support alternatives shown in https://wkhtmltopdf.org/support.html or 
post an issue on https://stackoverflow.com/.

Thanks!

**Comment by ashkulz** [comment]
Please ask this on StackOverflow or do some research yourself.
