### ISSUE TITLE
[Font Weight] Support of the font weight specified on @font-face

### ISSUE THREAD

**Issue by Hideman85** [wkhtmltopdf/wkhtmltopdf#4738]
I have a issue with font-weight the exported document don't handle that value correctly and use the latest definition for everything.
I'm using the latest `wkhtmltopdf 0.12.6 (with patched qt)` on linux.

Test case:
 - Result: [test.pdf](https://github.com/wkhtmltopdf/wkhtmltopdf/files/4814970/test.pdf)
 - Expected result (from browser) [image.png](https://user-images.githubusercontent.com/16165119/85323054-a3ee0c80-b4c7-11ea-8783-e5c8444bf749.png)
 - Source: [FontsWeight.zip](https://github.com/wkhtmltopdf/wkhtmltopdf/files/4814980/FontsWeight.zip)

**Comment by ashkulz** [comment]
Can you try if it's better using TTF fonts? I think sometimes there are issues with `WOFF` fonts, due to the outdated browser engine.

**Comment by Hideman85** [comment]
Same output tried with OTF & TTF converted from the WOFF one. There is the updated test case: [OpenType fonts.zip](https://github.com/wkhtmltopdf/wkhtmltopdf/files/4831785/OpenType.fonts.zip)

**Comment by kgoyal000** [comment]
> Same output tried with OTF & TTF converted from the WOFF one. There is the updated test case: [OpenType fonts.zip](https://github.com/wkhtmltopdf/wkhtmltopdf/files/4831785/OpenType.fonts.zip)

I tried using base64 font and it worked well for me you can use https://transfonter.org/ to convert to base64

**Comment by Hideman85** [comment]
![image](https://user-images.githubusercontent.com/16165119/85787933-735adc80-b72c-11ea-869c-53d82ed9343c.png)
I tried with a fresh compiled `wkhtmltopdf 0.12.7-dev (with patched qt)` when you mean fixed with v0.13 should I do something wit the branch 0.13 (5 years ago)?

What is your current environment?

**Comment by ashkulz** [comment]
@Hideman85 if you install the distro-provided wkhtmltopdf (e.g. on Debian 10) and run under `xvfb-run`, this would probably work (but without the patched Qt features). I've renamed the label to be more clear 👍

**Comment by Hideman85** [comment]
This is a issue for me I also need outline, toc and header/footer features.

**Comment by ashkulz** [comment]
Please read the [project status](https://wkhtmltopdf.org/status.html) for a detailed explanation.

**Comment by Hideman85** [comment]
Thank you it was a very nice reading :) unfortunately I can't help you for the development.

**Comment by ashkulz** [comment]
Not expecting that :smile: I wrote up the status page so that I don't have to write it again and again, and people do understand why it's not something that's going to happen quickly.

**Comment by Hideman85** [comment]
Understand and you do already a great job to care about the development of this project it's look like without your contribution this project would be already archived.

At this moment do you see any workaround that I can use for having my rendering working? also with nested table :pray: ?
I look around the recommendations you made on that page but there is no lib that support everything I need yet.

**Comment by ashkulz** [comment]
I think PrinceXML should do what you want, but it's a commercial solution :man_shrugging:

**Comment by Hideman85** [comment]
Outch $3800 the license this is not feasible.

There is nothing I can do as working solution with this lib?
For example for the font I can create different font-family for each font-weight I need.
But for table I looked around and I didn't found any good reply even if my case is relatively simple (break where you want just not break a line of text I mean not ~~like this~~)

**Comment by ashkulz** [comment]
I think someone else mentioned using SVG fonts, maybe try that as well?

**Comment by Hideman85** [comment]
That's a working workaround :+1:

**Comment by ashkulz** [comment]
Since there's a workaround, I'll close this issue. I'll try to document it on the website in the near future.

**Comment by Hideman85** [comment]
Note: A strange behavior that I didn't saw immediately is that svg font make the text non-selectable (like an image) but the woff font the text selection (and copy) was working.

For now you have to choice between having the support of font-weight or a selectable/copyable text (in qt-patched version)
