### ISSUE TITLE
No wkhtmltopdf executable found: "b''"

### ISSUE THREAD

**Issue by paragjp** [wkhtmltopdf/wkhtmltopdf#4739]
I am using Python 3.x and want to generate pdf from URL. install pdftoolkit and wkhtmlpdf and included path into system variables.

import pdfkit

pdfkit.from_url('http://google.com', 'out.pdf')

Path is ....Files\JetBrains\PyCharm Community Edition 2019.2\bin;;C:\Microsoft VS Code\bin;C:\Users\parag_ysz8lqe\AppData\Roaming\npm;C:\Docker Toolbox;c:\Program Files\wkhtmltopdf\bin;

But when I am executing getting following error

FileNotFoundError                         Traceback (most recent call last)
C:\ProgramData\Anaconda\lib\site-packages\pdfkit\configuration.py in __init__(self, wkhtmltopdf, meta_tag_prefix)
     20         try:
---> 21             with open(self.wkhtmltopdf) as f:
     22                 pass

FileNotFoundError: [Errno 2] No such file or directory: b''

During handling of the above exception, another exception occurred:

OSError                                   Traceback (most recent call last)
<ipython-input-1-e3ef1cc46c29> in <module>
      1 import pdfkit
      2 
----> 3 pdfkit.from_url('http://google.com', 'out.pdf')

C:\ProgramData\Anaconda\lib\site-packages\pdfkit\api.py in from_url(url, output_path, options, toc, cover, configuration, cover_first)
     22 
     23     r = PDFKit(url, 'url', options=options, toc=toc, cover=cover,
---> 24                configuration=configuration, cover_first=cover_first)
     25 
     26     return r.to_pdf(output_path)

C:\ProgramData\Anaconda\lib\site-packages\pdfkit\pdfkit.py in __init__(self, url_or_file, type_, options, toc, cover, css, configuration, cover_first)
     40 
     41         self.source = Source(url_or_file, type_)
---> 42         self.configuration = (Configuration() if configuration is None
     43                               else configuration)
     44         try:

C:\ProgramData\Anaconda\lib\site-packages\pdfkit\configuration.py in __init__(self, wkhtmltopdf, meta_tag_prefix)
     25                           'If this file exists please check that this process can '
     26                           'read it. Otherwise please install wkhtmltopdf - '
---> 27                           'https://github.com/JazzCore/python-pdfkit/wiki/Installing-wkhtmltopdf' % self.wkhtmltopdf)

OSError: No wkhtmltopdf executable found: "b''"

Tried lot of things but still error continues. Can you pl help me ?

**Comment by ashkulz** [comment]
Please ask this question in `pdfkit` repository.
