### ISSUE TITLE
how to apply a custom scale for the page?

### ISSUE THREAD

**Issue by FaberWim** [wkhtmltopdf/wkhtmltopdf#4741]
Hi, I'm new to wkhtmlopdf and converted a .aspx page to a pdf. That works awesome, but I want to resize the page.  I need to resize the page to 48%. How can I do that?

Thanks!

Wim

**Comment by xoco70** [comment]
did you find a solution ?

**Comment by FaberWim** [comment]
Unfortunately not Julien.

Outlook voor Android<https://aka.ms/AAb9ysg> downloaden
________________________________
