### ISSUE TITLE
Fatal error compiling builtin function 'apply': Segmentation fault

### ISSUE THREAD

**Issue by vuongabc92** [wkhtmltopdf/wkhtmltopdf#4743]
**wkhtmltopdf version(s) affected**: 0.12.5

**OS information**
Docker Windows golang:alpine:latest

**Description**

Hello guys, wkhtmltopdf is a great project, it helped me a lot,  but currently, I got an issue and I have googled a lot but no uses, please help!!
Currently, I'm developing on Docker that was installed on Windows, it's quite simple:

`FROM golang:alpine AS builder

RUN apk update \
 && apk add --no-cache xvfb ttf-freefont fontconfig \
 && apk add --no-cache wkhtmltopdf

RUN env GO111MODULE=on go get github.com/cortesi/modd/cmd/modd

COPY ./go.mod /
COPY ./go.sum /

RUN go mod download`

everything is fine but when I run command: `wkhtmltopdf https://google.com google.pdf` I got an error:
#Fatal error compiling builtin function 'apply': Segmentation fault

How can I get rid of it, please give me some solution.

Thank you very much.

**Comment by ashkulz** [comment]
wkhtmltopdf with Qt patches isn't supported on Alpine yet, see wkhtmltopdf/packaging#2. You'll have to log an issue with the Alpine project, or alternatively use the `debian:buster` base image.
