### ISSUE TITLE
header/footer html read from stdin

### ISSUE THREAD

**Issue by lbenedetto** [wkhtmltopdf/wkhtmltopdf#4748]
**Description**
`--footer-html` and `--header-html` should accept `-` as input the same way `-` can be used to specify stdin as the source of the main document html.

**Example**  
`wkhtmltopdf --footer-html - - -`
Read footer html from stdin until EOF.
Then, read main document html from stdin until EOF.
Then write output pdf to stdout.

**Comment by ashkulz** [comment]
There is only 1 stream -- how can you read until multiple EOF? Just create tempfiles and delete them after use.

**Comment by lbenedetto** [comment]
> how can you read until multiple EOF
stdin isn't permanently closed just because some program wrote EOF to it. Just reopen your connection and read until the next EOF.

A terminal can keep providing input after the user enters the EOF escape, and a file can have more data written to it.

https://stackoverflow.com/questions/19749982/repeatedly-reading-to-eof-from-stdin

So I think it should be possible. Regardless, it is an implementation detail. The real request is that we can provide a footer without creating a temp file. In whichever way you think it best to implement it. 

There could be a special separator character that isn't EOF, or there could be `--footer-div` which would take a div id to extract from the main html and reuse as footer, ect

**Comment by ashkulz** [comment]
@lbenedetto if you think it's possible, will appreciate a PR which implements it.
