### ISSUE TITLE
Port to Arch Linux (Manjaro distro)

### ISSUE THREAD

**Issue by angel-ayala** [wkhtmltopdf/wkhtmltopdf#4759]
**Description**
It would be great if have binary code for use with Manjaro, or any other Arch based distro, I could help if you tell me what must be modified.

**Example**  
Prevent the message of 
`./wkhtmltopdf:53:in '<main>': **Invalid platform, must be running on Ubuntu 16.04/18.04/20.04 CentOS 6/7/8, Debian 9/10, or intel-based Cocoa macOS (missing binary: ./wkhtmltopdf_manjaro__amd64). (RuntimeError)** `

**Comment by angel-ayala** [comment]
there is and already version in the [AUR repo](https://aur.archlinux.org/packages/wkhtmltopdf-static/), but i'm intend to use with the [wkhtmltopdf-binary gem](https://rubygems.org/gems/wkhtmltopdf-binary/versions/0.12.4), how can be merged?

**Comment by ashkulz** [comment]
Shouldn't you open an issue in wkhtmltopdf-binary gem?

**Comment by ashkulz** [comment]
If you want an ArchLinux build, you can try to create one -- see the packaging repository, you should be able to create a docker based build.
