### ISSUE TITLE
wkhtmltopdf executable not found on arm64 or aarch64 devices

### ISSUE THREAD

**Issue by tathastu871** [wkhtmltopdf/wkhtmltopdf#4760]
We use GitHub issues only to discuss about wkhtmltopdf bugs and new features. For
this kind of questions about using wkhtmltopdf, please use
any of the support alternatives shown in https://wkhtmltopdf.org/support.html or 
post an issue on https://stackoverflow.com/.

Thanks!

I have verified that after installing it with pip3 install wkhtmltopdf no executable was generated in linux arm64 device, however it shows succesfull installation and also gets imported in python but while trying to use it directly or with weasyprint or pdfkit then no executble error found.

Also in real no executble was there in system and hence workaround providing path to executable in syntax also cannot be done.

**Comment by ashkulz** [comment]
I think you need to open an issue with the wrapper you're using, as wkhtmltopdf has packages for arm64/aarch64: see the downloads on the website.

**Comment by prcongithub** [comment]
Is arm64 supported with lambda layers?

**Comment by ashkulz** [comment]
@prcongithub there's an open PR, see wkhtmltopdf/packaging#108

**Comment by prcongithub** [comment]
I created a lambda layer using public.ecr.aws/sam/build-ruby2.7:1-arm64 and https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6-1/wkhtmltox-0.12.6-1.amazonlinux2.$(arch).rpm
Its working fine for us on AWS Lambda with Arch64 running on Graviton processors.
