### ISSUE TITLE
Exception Details: NReco.PdfGenerator.WkHtmlToPdfException: Exit with code 1 due to network error: ContentAccessDenied (exit code: 1)

### ISSUE THREAD

**Issue by luckybuy** [wkhtmltopdf/wkhtmltopdf#4761]
**wkhtmltopdf version(s) affected**: 1.2.0.0

**OS information**

**Description**

var htmlToPdf = new NReco.PdfGenerator.HtmlToPdfConverter();
var pdfBytes = htmlToPdf.GeneratePdf("&lt;html&gt;&lt;body&gt;&lt;h1&gt;Hello&lt;/h1&gt;&lt;/body&gt;&lt;html&gt;");

**How to reproduce**
call function var pdfBytes = htmlToPdf.GeneratePdf("&lt;html&gt;&lt;body&gt;&lt;h1&gt;Hello&lt;/h1&gt;&lt;/body&gt;&lt;html&gt;");

**Expected behavior**

call below function and return bytes to pdfBytes
var pdfBytes = htmlToPdf.GeneratePdf("&lt;html&gt;&lt;body&gt;&lt;h1&gt;Hello&lt;/h1&gt;&lt;/body&gt;&lt;html&gt;");

**Possible Solution**  

Maybe window security. We need to change window security, policy...

**Comment by ashkulz** [comment]
Please open an issue in NReco.PdfGenerator repository, as this has nothing to do with wkhtmltopdf.
