### ISSUE TITLE
get an unexpected white page at the end page

### ISSUE THREAD

**Issue by alenzar** [wkhtmltopdf/wkhtmltopdf#4768]
**wkhtmltopdf version(s) affected**: 0.12.6

**OS information**
ubuntu16

**Description**
got an unexpected white page at the end ,and it has a wrong page number on toc.

**How to reproduce**
only uniq url and content got this white page ,and along with next  errors:

Warning: Received createRequest signal on a disposed ResourceObject's NetworkAccessManager. This might be an indication of an iframe taking too long to load.
Error: Failed to load about:blank, with network status code 301 and http status code 0 - Protocol "about" is unknown

**Expected behavior**
expect to get a detail log to know how the wrong white page generated

**Possible Solution**

**Comment by PhilterPaper** [comment]
Sometimes you can get an extra blank page at the end if there is invisible content, such as a `<div>`, extending beyond the last printed content. Try putting "END OF TEXT" at the very, very end of the HTML document (just before `</body>`) and see if it appears on the empty page.

**Comment by alenzar** [comment]
Very good advice! I finally solved it. 
With the method of "END OF TEXT", I confirmed  the html elements, css styles and finally find 301 error may lead some exception problems. When removed the 301 error  which  caused by  customized fonts files, the last white page is gone.
