### ISSUE TITLE
error while loading shared libraries: libfontconfig.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by dunebaud** [wkhtmltopdf/wkhtmltopdf#4775]
**wkhtmltopdf version(s) affected**: wkhtmltox_0.12.6-1.bionic_i386.deb 

**OS information**
Ubuntu 18.04

**Description**
The following message pop up when trying to create a pdf:
`wkhtmltopdf: error while loading shared libraries: libfontconfig.so.1: cannot open shared object file: No such file or directory
`
Looking for solution, I have also:
`sudo apt-get install libfontconfig1 fontconfig libfontconfig1-dev`
But this doesn't change anything.

**How to reproduce**
Just run `wkhtmltopdf "www.google.be" test.pdf`

**Comment by Sliwson** [comment]
I see you run `sudo apt-get install libfontconfig1 fontconfig libfontconfig1-dev` but have you tried just  `sudo apt-get install libfontconfig`?

**Comment by dunebaud** [comment]
@Sliwson Thank you for your help, but yes I did... (and re-did to double check)... without luck.

**Comment by ashkulz** [comment]
What is the output of `uname -a`?

**Comment by dunebaud** [comment]
5.3.0-62-generic #56~18.04.1-Ubuntu

**Comment by ashkulz** [comment]
Can I have the full line, please? I think you're using the 32 bit .deb on a 64 bit machine.

**Comment by dunebaud** [comment]
Sorry, here it is;
Linux baudomen 5.3.0-62-generic #56~18.04.1-Ubuntu SMP Wed Jun 24 16:17:03 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by ashkulz** [comment]
Yup, you've installed the wrong .deb -- install the amd64 version.

**Comment by dunebaud** [comment]
You saved my day... it is working. Don't know how to close this bug!
