### ISSUE TITLE
How to install 0.12.6 (with patched qt) on Debian 8?

### ISSUE THREAD

**Issue by ngekoding** [wkhtmltopdf/wkhtmltopdf#4780]
Hi, nice to found this awesome work.

I was try in my local development with MacOS and everything working well, I use `wkhtmltopdf 0.12.6 (with patched qt)`.

But, the problem is, when I trying to install on the production server (**Debian 8**) the package can't installed.

I was tried many tutorials, but no one is working.

Can anyone tell me how to install wkhtmltopdf 0.12.6 (with patched qt) on Debian 8?

Thanks in advance

**Comment by ashkulz** [comment]
See the [0.12.6-1 release](https://github.com/wkhtmltopdf/packaging/releases/0.12.6-1) -- Debian 8 is now EOL, and hence not supported. You can try to make the changes yourself by referring to wkhtmltopdf/packaging@62ff784f6e520c40b359cdf947c33ac18d04c187 but there won't be any official releases.
