### ISSUE TITLE
Svg show: 'undefined in' PDF file.

### ISSUE THREAD

**Issue by huangjinshe** [wkhtmltopdf/wkhtmltopdf#4786]
**wkhtmltopdf version(s) affected**: 0.12.6

**OS information**
Windows 10

**Description**
I'm using JsBarcode library generate barcode image in HTML, but after I convert it to PDF I saw the image not clear, very blurry, so I decide use <svg> replace <img>.

It's all fine in HTML page, but after I converted to PDF, the svg not show up, only display a string: `undefined`.

This is the HTML page :
![problem1](https://user-images.githubusercontent.com/3822799/88860285-f4c2f480-d22d-11ea-92c5-b5cf3aa93eb2.png)

This is the PDF file:
![problem2](https://user-images.githubusercontent.com/3822799/88860292-fb516c00-d22d-11ea-8461-2f105e0214cc.png)

I'm using javascript dynamically generated the svg , I doubt that's the problem source. because If I use the static HTML page which already generated svg tag by js in the page  and convert, all fine.

Is there any possibility to fix this? Thank you.

This is the HTML page for test:
[Barcode.zip](https://github.com/wkhtmltopdf/wkhtmltopdf/files/4997808/Barcode.zip)

**Comment by beroso** [comment]
I think SVG innerHTML and outerHTML is not supported on the current wkhtmltopdf Webkit engine.

You can work around this problem by using XMLSerializer. I tested with your code and it worked this way:
```js
newTable = newTable.replace('${Image}', new XMLSerializer().serializeToString(newSVG));
```

**Comment by huangjinshe** [comment]
@beroso , It worked. Really thanks!
