### ISSUE TITLE
 wget: unable to resolve host address ‘downloads.wkhtmltopdf.org’

### ISSUE THREAD

**Issue by krystofbe** [wkhtmltopdf/wkhtmltopdf#4787]
wget: unable to resolve host address `downloads.wkhtmltopdf.org`

```
 --2020-07-30 10:42:26--  https://downloads.wkhtmltopdf.org/0.12/0.12.5/wkhtmltox_0.12.5-1.stretch_amd64.deb
Resolving downloads.wkhtmltopdf.org (downloads.wkhtmltopdf.org)... failed: Name or service not known.
wget: unable to resolve host address ‘downloads.wkhtmltopdf.org’
```
https://downforeveryoneorjustme.com/downloads.wkhtmltopdf.org

is `downloads.wkhtmltopdf.org` still an official link?

**Comment by ashkulz** [comment]
Nope, see ba575ea7777a1cc2f3002a3feda4ee2a3e5b2664. It shouldn't be linked from anywhere on the website, if you see it linked would appreciate reporting about that.

**Comment by Nazar84** [comment]
It is linked
https://gist.github.com/srmds/2507aa3bcdb464085413c650fe42e31d#wkhtmltopdf-0125---ubuntu-1804-x64
