### ISSUE TITLE
PHP Packagist library not updated to latest version

### ISSUE THREAD

**Issue by javabudd** [wkhtmltopdf/wkhtmltopdf#4789]
**wkhtmltopdf version(s) affected**: > 0.12.4

**OS information**
All

**Description**
The PHP Packagist repository has not been updated in quite some time, and does not have auto updates configured. 0.12.5 and 0.12.6 are not accessible using `composer`.

https://packagist.org/packages/h4cc/wkhtmltopdf-amd64

**How to reproduce**
```
  composer require h4cc/wkhtmltopdf-amd64@0.12.6
  Problem 1
    - The requested package h4cc/wkhtmltopdf-amd64 ^0.12.6 exists as h4cc/wkhtmltopdf-amd64[0.11.0-RC1, 0.12.0, 0.12.1, 0.12.2.1, 0.12.3, 0.12.4, de
v-master] but these are rejected by your constraint.
```

**Expected behavior**
0.12.5 and 0.12.6 are available through packagist

**Possible Solution**  
use `dev-master`

**Comment by javabudd** [comment]
Incorrect repo

**Comment by garbinmarcelo** [comment]
> Incorrect repo

Which one did you use? Did you manage to define the last version to install via composer?

**Comment by javabudd** [comment]
> 
> 
> > Incorrect repo
> 
> Which one did you use? Did you manage to define the last version to install via composer?

I ended up using h4cc/wkhtmltopdf-amd64 dev-master and pulling in Linux binaries from this repo.

This issue might help: https://github.com/h4cc/wkhtmltopdf-amd64/issues/43

**Comment by allanlaal** [comment]
for googlers:
https://github.com/h4cc/wkhtmltopdf-amd64 has been abandoned
so use: https://github.com/lissonpsantos2/wkhtmltopdf-amd64
