### ISSUE TITLE
Parameter length limit issue

### ISSUE THREAD

**Issue by adamdomjan** [wkhtmltopdf/wkhtmltopdf#4795]
I am using wkhtmltopdf on a page requiring GET/POST parameters to generate the contents. I have tried both GET and POST methods, the problem comes up either way: If the parameter length exceeds circa 30kBytes I get the following error:

2020-08-06 16:59:46,795 - GCD - DEBUG - Traceback (most recent call last):
  File "C:\PythonWorkspace\gap\gcdapp\drift_monitoring.py", line 129, in check_config_drift
    create_diffdoc(system_config['DEFAULT']['route_diff'], savepoint_report, current_report, system_config['DEFAULT']['system'], hostname, diff_dir)
  File "C:\PythonWorkspace\gap\gcdapp\drift_monitoring.py", line 44, in create_diffdoc
    controllers.create_local_pdf(route, params, diffdoc_path)
  File "C:\PythonWorkspace\gap\gcdapp\controllers.py", line 79, in create_local_pdf
    utils.url_post_to_pdf(url, params, file_path, path_wkhtmltopdf)
  File "C:\PythonWorkspace\gap\gcdapp\utils.py", line 127, in url_post_to_pdf
    pdfkit.from_url(url, output_path, configuration=config, options=pdfkit_options)
  File "C:\PythonWorkspace\gap\venv\lib\site-packages\pdfkit\api.py", line 26, in from_url
    return r.to_pdf(output_path)
  File "C:\PythonWorkspace\gap\venv\lib\site-packages\pdfkit\pdfkit.py", line 128, in to_pdf
    result = subprocess.Popen(args, stdin=subprocess.PIPE, stdout=subprocess.PIPE,
  File "C:\BLKDeveloper\Python38_64bit\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\BLKDeveloper\Python38_64bit\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 206] The filename or extension is too long

Here is the code producing the error:

def url_post_to_pdf(url, params, output_path, path_wkhtmltopdf):
    config = pdfkit.configuration(wkhtmltopdf=path_wkhtmltopdf)
    post_param_list = []
    for key, value in params.items():
        post_tuple = (key, json_minify(json.dumps(value)))
        post_param_list.append(post_tuple)
    pdfkit_options = {
        'encoding': 'UTF-8',
        'javascript-delay': '10000',
        'post': post_param_list
    }
    pdfkit.from_url(url, output_path, configuration=config, options=pdfkit_options)
    log.debug('%s - PDF created.' % (output_path))

If the parameter length goes below 30 kB it starts working again, stumped as to why.

**Comment by adamdomjan** [comment]
Looks like it has a problem opening the subprocess in pdfkit.py line 128:

result = subprocess.Popen(args, stdin=subprocess.PIPE, stdout=subprocess.PIPE,
                                  stderr=subprocess.PIPE)

What could be going wrong here?

**Comment by ashkulz** [comment]
Looks like a subprocess and/or Windows limitation, not really related to wkhtmltopdf.

**Comment by adamdomjan** [comment]
Indeed, a lengthy troubleshooting revealed that when the parameters used to launch the wkhtmltopdf program were too long – longer than 32767 characters, to be exact.
 
Apparently when launching a program with command line arguments Windows stores the parameter length in a 16-bit USHORT variable. 65535 divided by the 2-byte character length is responsible for the limit of 32767 characters.
 
This Windows API limitation can be circumvented by providing parameters from an external file. Thanks for your attention, case closed :-)
