### ISSUE TITLE
Some HTMLs missing in final PDF file

### ISSUE THREAD

**Issue by shunf4** [wkhtmltopdf/wkhtmltopdf#4813]
**wkhtmltopdf version(s) affected**: 0.12.6

**OS information**
Microsoft Windows [Version 10.0.18363.900] (x64)

**Description**
Some (Sometimes all) HTMLs randomly missing in final PDF file.

**How to reproduce**
- Download [android-javadocs.zip](https://github.com/wkhtmltopdf/wkhtmltopdf/files/5149991/android-javadocs.zip)
- Unzip it and enter the uncompressed directory
- run `wkhtmltopdf --read-args-from-stdin < args.txt` multiple times, observing the size and number of pages of produced PDF file

The size of `a.pdf` differs each time; sometimes 4,200+ KiB while sometimes only 2,700- KiB. When it has obviously smaller size, open it and find some HTML files missing, like `./android/accessibilityservice/AccessibilityService.html` in my attempt.

When there are more HTML files as input, most of the time the output is a PDF with only one blank page.

**Expected behavior**
The output should be consistent and complete.

**Possible Solution**  
None

**Comment by PhilterPaper** [comment]
I'm consistently getting a message that `resources/fonts/dejavu.css` is missing. Running your example, I _do_ see differences in file size. I added `--javascript-delay 2000` to the command line, and now the size is consistent, at 62 pages of output. Try that.

**Comment by shunf4** [comment]
@PhilterPaper Oh, thanks. Didn't notice that there'a an option for controlling the time of rendering. Missing `dejavu.css` should be OK, as it is also missing when the HTML is opened in the desktop browser and it renders normally.

And I discovered that for more files (550+), 2000ms is not enough. Around 6,700+ pages is output when delay is set to 60,000ms, but less than 500 is output when it's 2000ms. Is it expected by design? Seems like when there are more concurrency tasks, they block each other, so more delay time is needed.

**Comment by PhilterPaper** [comment]
There _might_ be some delay introduced on each page if each is trying to pull in dejavu.css, and failing. Just for giggles, you might try supplying that file and seeing if it makes much difference.

A 6700+ page PDF? Really? That seems rather large to try to handle or read, much less produce. Imagine trying to do the entire _Encyclopedia Britannica_ in one go! Anyway, I don't know how much it's trying to handle concurrently (if anything), so I can't tell you if it's by design.

**Comment by shunf4** [comment]
I removed the reference to dejavu.css, still the same with a short `--javascript-delay`.

I'm making a PDF document for javadoc-generated HTMLs, and I'm just curious if I could integrate all of them into one file. Actually most of the pages in that huge PDF are from two HTML files indexing all of the Java classes. It seems if the number concurrent tasks could be limited, we will not need to specify a too long delay and other things will get better too. Thanks!
