### ISSUE TITLE
no characters rendered

### ISSUE THREAD

**Issue by MathiasWeisheit** [wkhtmltopdf/wkhtmltopdf#4836]
**wkhtmltopdf version(s) affected**: 0.12.6-r0 

**OS information**
alpine linux

**Description**
no characters are included, only squares are visible
[test2.pdf](https://github.com/wkhtmltopdf/wkhtmltopdf/files/5274275/test2.pdf)

**How to reproduce**
alpine docker image
apk add wkhtmltopdf
wkhtmltopdf https://wkhtmltopdf.org/ test2.pdf

**Expected behavior**
a pdf with the real charactes should be generated

**Possible Solution**  
perhaps some packages ar missing:
libgcc libstdc++ libx11 glib libxrender libxext libintl 
ttf-dejavu ttf-droid ttf-freefont ttf-liberation ttf-ubuntu-font-family

**Comment by PhilterPaper** [comment]
What kind of characters are tofu'd? Does this happen with ASCII text, or only with multibyte characters? What does the HTML specify for font to use, and the encoding? Does the entry of your text match that encoding? I.e., if you specify UTF-8 encoding in HTML but your editor produces Latin-1 text, then anything non-ASCII will be tofu'd.

**Comment by MathiasWeisheit** [comment]
A google search listet me a docker-image project. The owner installed the following libs: libgcc libstdc++ libx11 glib libxrender libxext libintl ttf-dejavu ttf-droid ttf-freefont ttf-liberation ttf-ubuntu-font-family
No it works. Do you know which of these libs are necessary?

**Comment by MathiasWeisheit** [comment]
> 
> 
> What kind of characters are tofu'd? Does this happen with ASCII text, or only with multibyte characters? What does the HTML specify for font to use, and the encoding? Does the entry of your text match that encoding? I.e., if you specify UTF-8 encoding in HTML but your editor produces Latin-1 text, then anything non-ASCII will be tofu'd.

https://github.com/madnight/docker-alpine-wkhtmltopdf/blob/master/Dockerfile

**Comment by MathiasWeisheit** [comment]
Now it works. Do you know which of these libs are necessary?

**Comment by PhilterPaper** [comment]
Perhaps you were missing all the fonts that wkHTMLtoPDF tried to use (or they were already installed, but in an unexpected place)? That might explain why the `ttf-*` libraries helped. I don't know about the other libraries -- I don't think you'd get an executable if any of them were missing.

**Comment by MathiasWeisheit** [comment]
we have installed ttf-dejavu and now it works
thanks a lot
