### ISSUE TITLE
Piping data changes resources schema to file:///

### ISSUE THREAD

**Issue by andreasph** [wkhtmltopdf/wkhtmltopdf#4856]
**wkhtmltopdf version(s) affected**: 0.12.6

**OS information**

macOS Mojave and Debian buster docker based image

**Description**

We have a golang microservice where we run a command that can be narrowed down to:
```
echo "<img src=\"https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png\">" | /usr/local/bin/wkhtmltoimage --quality 100 --format jpeg --width 150 --height 350 - -
````
the real src url is not relevant

We run this with `exec.Command()` in golang with piping (so there are two separated command, the echo one and the one for wkhtmltoimage, that communicates through `exec.Cmd.StdoutPipe())`

I can see that wkhtmltoimage try to access `file:///https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png`, prepending the file schema to the url. this doesn't happen if I run the command directly from cli in a terminal

**How to reproduce**

See above

**Expected behavior**

Resources with a schema defined should not be prepended with a `file:///` schema

**Possible Solution**

**Comment by oliverbenns** [comment]
In the exec package you will want to use [StdinPipe](https://golang.org/pkg/os/exec/#Cmd.StdinPipe) instead of piping with echo.

```go
	cmd := exec.Command(wkHtmlToImageCmd, args...)

	stdin, err := cmd.StdinPipe()
	if err != nil {
		return nil, err
	}

	io.WriteString(stdin, "<img src=\"https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png\">")
	stdin.Close()

	bytes, err := cmd.CombinedOutput()
``

**Comment by andreasph** [comment]
@oliverbenns great thanks, works like a charm!
