### ISSUE TITLE
How to persistence image base64 width and height ?

### ISSUE THREAD

**Issue by darmawan01** [wkhtmltopdf/wkhtmltopdf#4858]
Version : `wkhtmltopdf 0.12.4`
SO        : `Linux`
Got the difference image size with base64 type, 

Here is the result with chrom print pdf (ctrl+p)

![image](https://user-images.githubusercontent.com/23370707/96961299-817c0680-152e-11eb-9cd1-c9f5544384c1.png)

Here is the result generated by   go `wkhtmltopdf`.

![image](https://user-images.githubusercontent.com/23370707/96961343-a07a9880-152e-11eb-95b1-c7e8ca048001.png)

is issues from html. or something i have mis in setup ??

**Comment by darmawan01** [comment]
sorry wrong repo

**Comment by darmawan01** [comment]
i have try to generate manually with `wkhtmltopdf omama.html omama.pdf` the result is not like what i expected. 

maybe someone has the solution

**Comment by darmawan01** [comment]
Use option `--disable-smart-shrinking`

![image](https://user-images.githubusercontent.com/23370707/96964955-8ee8bf00-1535-11eb-843b-0b78ec726fcc.png)

The banner getting out of the box

**Comment by PhilterPaper** [comment]
You're not giving us enough information to go on here.  Is the rule below the image (`<hr>`?) changing size, or is just the image changing size? And when you use `--disable-smart-shrinking`, does the rule shrink and not the image, or is the rule the same size and the image is larger? It would be very helpful to attach your .html file showing this problem. Do you have the original image as a separate file, and try that to see if there is any difference between using the image file and the in-line base64 image? Finally, version 0.12.4 is quite old. You might want to upgrade to 0.12.6 and see if it makes any difference, before spending a lot of time on this.

**Comment by darmawan01** [comment]
Here is my html, i use base64 as image. when generating the pdf, looks like it change all of font resolution

[omama.html.zip](https://github.com/wkhtmltopdf/wkhtmltopdf/files/5436624/omama.html.zip)

**Comment by PhilterPaper** [comment]
Comparison of widths:
 
- HTML in browser: image is 156mm, "Hal ... 056" line: 65mm, QRcode: 22mm
- PDF with default Smart Shrinking: image is 143mm (92%), "Hal ... 056" line: 59mm (91%), QRcode: 20mm (91%)
- PDF with Disable Smart Shrinking: image is 177mm (113%), "Hal ... 056" line: 74mm (114%), QRcode: 26mm (118%)

All displays are at 100% zoom (life size). It looks like the scaling with and without Smart Shrinking is roughly consistent. Don't forget that the horizontal rule is the line length (_much_ longer in the HTML browser), and I notice that it shrinks from 167mm to 158mm when Smart Shrinking is _disabled_. That seems rather odd, but it might explain the change in relative size, or at least give you a clue where to look.

**Comment by darmawan01** [comment]
i am little confusing, how to solve it

**Comment by darmawan01** [comment]
this issues because of my html. i was fix the margin and solve this problem
