### ISSUE TITLE
Error: Invalid argument @ io_fread

### ISSUE THREAD

**Issue by joshuapinter** [wkhtmltopdf/wkhtmltopdf#4859]
**wkhtmltopdf version(s) affected**: 0.12.6

**OS information**
macOS 10.14

**Description**
Trying to generate a fairly large PDF with the following command: 

```bash
/Users/me/.rbenv/versions/2.6.5/bin/wkhtmltopdf --enable-local-file-access --disable-smart-shrinking --orientation Portrait --page-size Letter --margin-top 27 --margin-bottom 19 --header-html file:////var/folders/9n/vjrv4bzs7fxf6crkdc84tf740000gn/T/wicked_header_pdf20201023-55115-le3quo.html --footer-html file:////var/folders/9n/vjrv4bzs7fxf6crkdc84tf740000gn/T/wicked_footer_pdf20201023-55115-1o98lhe.html file:////var/folders/9n/vjrv4bzs7fxf6crkdc84tf740000gn/T/wicked_pdf20201023-55115-1am8ara.html /var/folders/9n/vjrv4bzs7fxf6crkdc84tf740000gn/T/wicked_pdf_generated_file20201023-55115-qwkucc.pdf
```

This command fails with the following: 

```bash
Error: Invalid argument @ io_fread - /var/folders/9n/vjrv4bzs7fxf6crkdc84tf740000gn/T/wicked_pdf_generated_file20201023-55115-qwkucc.pdf
```

I've never encountered this type of error before and there is very little of it on the inter webs, so want to get your input and see if you can point me in the right direction, etc.

**How to reproduce**
Tough to reproduce without the html content but I may be able to after an initial assessment of the error message.

**Expected behavior**
Generate the PDF without error.

**Possible Solution**  
No idea yet.

**Comment by PhilterPaper** [comment]
Two things to check:
1. I notice that your other files on the command line use the prefix `file:///`, but the output .pdf file doesn't. Have you tried adding `file:///` in front of `/var/...`? If this thing is operating through a server or browser, it might need "file".
2. I assume that you've checked your file path there and it is properly formatted and _does_ exist (except for the output file itself). No typos, etc.?

**Comment by joshuapinter** [comment]
Thanks for the reply @PhilterPaper!

1. Good eye. This command is generated via `wicked_pdf` gem for Rails and this only affects very large PDFs (smaller ones with the same `file:///` omission work fine) but I'll give it a try and see if it affects anything.

2. Yes. Again, works totally fine for small and medium sized PDFs. Only on larger PDFs does this occur. And it only occurs once the generated PDF in the temp location is upwards of 2 GBs.

**Comment by PhilterPaper** [comment]
Does the filesystem in question have a size limit for files? Some older systems might be as small as 2GB (2.147GB), and the result may be a truncated or corrupted file. If only large files are being affected, you might want to look into that. Also, the entire filesystem may have a size limit of a few GB, and there is not enough room left for one large file... also something to ask about.

**Comment by joshuapinter** [comment]
@PhilterPaper First off, thanks for responding here and your suggestions.

I've spent the last 2 days digging deep into this and discovered it was not an issue with `wkhtmltopdf` itself but with the Rails wrapper gem we use called `wicked_pdf`, which generates the HTML and passes that to `wkhtmltopdf`. 

And, yes, it has to do with file sizes and memory.

In short, the problem command in `wicked_pdf` was `string_file.write(string)` found [here](https://github.com/mileszs/wicked_pdf/blob/master/lib/wicked_pdf.rb#L44): 

```ruby
def pdf_from_string(string, options = {})
  options = options.dup
  options.merge!(WickedPdf.config) { |_key, option, _config| option }
  string_file = WickedPdfTempfile.new('wicked_pdf.html', options[:temp_path])
  string_file.binmode
  string_file.write(string)
  string_file.close

  pdf = pdf_from_html_file(string_file.path, options)
  pdf
ensure
  string_file.close! if string_file
end
```
Using `string_file.write(string)` reads the entire contents of `string` into memory before first writing it to the `string_file`. 

For large files, this causes `Errno::EINVAL` errors like `Invalid argument @ io_fread` and `Invalid argument @ io_write`.

To fix this, I read the `string` in chunks and wrote them to `string_file` like so: 

```ruby
stringIO = StringIO.new( string )
until stringIO.eof?
  string_file.write( stringIO.read( 1024*1024 ) ) # Write 1 MB chunks at a time to avoid Errno::EINVAL errors like `Invalid argument @ io_fread` and `Invalid argument @ io_write`.
end
```

I'm working on a PR to `wicked_pdf` that fixes this and at least shows a more helpful error message when it occurs. 

I'm closing this now 📕. Thanks again for the help @PhilterPaper!

**Comment by PhilterPaper** [comment]
Ah yes, sometimes it's the simplest things! Glad you got to the bottom of it.
