### ISSUE TITLE
PDF generation fails with exitstatus=134 intermittently

### ISSUE THREAD

**Issue by abhishek77in** [wkhtmltopdf/wkhtmltopdf#4861]
**wkhtmltopdf version(s) affected**: 0.12.5 and 0.12.6 

**OS information**
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

**Description**
I am running into an issue where the PDF printing is failing intermittently (about 1% of the times) but works after the job is re-tried. I am trying to debug the issue but only thing I can see is **exitstatus=134** and I feel there is not much to go on from here.

Also raised an issue with PDFKit gem but don't think the issue is with the gem itself - https://github.com/pdfkit/pdfkit/issues/482

**How to reproduce**
I am trying to reproduce the issue, but since it's intermittent and does not happen upon retry, it is very difficult to track this down. Have been facing this for more than 1.5 years in production now.

**Expected behavior**
PDF printing should have worked without reattempts.

**Possible Solution**  
Found an issue with same exitstatus=134 and solution, https://github.com/barryvdh/laravel-snappy/issues/122#issuecomment-381343940

**Comment by abhishek77in** [comment]
If someone can tell what exitstatus=134 is related to, it will further help me in trying to fix the issue. Thanks.

**Comment by PhilterPaper** [comment]
Can you clarify what you mean by "printing"? Is this the _creation_ of a PDF from HTML, via wkHTMLtoPDF? Or is it the _printing_ of the resulting PDF from a reader such as Adobe Acrobat Reader? If it's the latter (actual printing of a PDF), I'm not sure how we can help you, especially if it's intermittent.

**Comment by abhishek77in** [comment]
Hi @PhilterPaper Sorry about the confusion. The issue with PDF generation, and not with physical printing. I use `pdfkit` gem to generate PDFs. Here is the error output from my application:
```
vendor/bundle/ruby/2.6.0/gems/pdfkit-0.8.4.1/lib/pdfkit/pdfkit.rb:73:in `to_pdf': command failed (exitstatus=134): /app/vendor/bundle/ruby/2.6.0/gems/wkhtmltopdf-heroku-2.12.5.0/bin/wkhtmltopdf-linux-amd64 --encoding UTF-8 --dpi 300 --header-spacing 3 --page-size A4 --margin-top 81.0 --margin-bottom 68.0 --margin-left 0 --margin-right 0 --header-html /app/tmp/LabReport-L1-BabyAmara\(1YRS-F\)-25-10-2020\ header20201025-4-1wb3iw7.html --footer-html /app/tmp/LabReport-L1-BabyAmara\(1YRS-F\)-25-10-2020\ footer20201025-4-w1oxfj.html - - (RuntimeError)
    from app/models/lab_report_pdf.rb:28:in `to_pdf'
    from app/models/lab_report.rb:46:in `save_as_pdf'
```

I will try to reproduce the issue, it's intermittent but it happens often with some effort I may reproduce it, I thought exit status might itself be sufficient to point in some direction. 

I am using `Standard 1x` (512mb ram) dyno worker from Heroku - https://www.heroku.com/dynos, could this issue be related to server capacity (cpu & ram)?

**Comment by PhilterPaper** [comment]
I'm not sure what the return code means, but for intermittent failures, the first thing I'd consider is that you're right on the edge of some sort of timeout, and occasionally fail to complete in time. Have you tried `--javascript-delay <milliseconds>`? Start with 10000 (10 seconds run time) and reduce it until you start getting failures again.

**Comment by abhishek77in** [comment]
Hi @PhilterPaper upon further investigation, I could find errors being present in my worker log.

Error: **Failed to load <local_file_url> with network status code 3 and http status code 0 - Host app not found**, as this file (<local_file_url> ) is present on the local machine (the worker itself), can this be fixed by making use of `--enable-local-file-access` option?

```
==============================] 100% Error: Failed to load http://app/tmp/LabReport-L1-BabyAmara(1YRS-F)-28-10-2020 header20201027-4-1j971uo.html?page=1&section=ENDOCRINOLOGY&sitepage=1&title=&subsection=&frompage=1&subsubsection=&isodate=2020-10-27&topage=1&doctitle=&sitepages=1&webpage=-&time=7:19 PM&date=10/27/20, with network status code 3 and http status code 0 - Host app not found
28 Oct 2020 00:49:04.953468 <190>1 2020-10-27T19:19:04.777778+00:00 app worker.1 - - Error: Failed loading page http:///app/tmp/LabReport-L1-BabyAmara(1YRS-F)-28-10-2020 header20201027-4-1j971uo.html?page=1&section=ENDOCRINOLOGY&sitepage=1&title=&subsection=&frompage=1&subsubsection=&isodate=2020-10-27&topage=1&doctitle=&sitepages=1&webpage=-&time=7:19 PM&date=10/27/20 (sometimes it will work just to ignore this error with --load-error-handling ignore)
28 Oct 2020 00:49:04.953449 <190>1 2020-10-27T19:19:04.778262+00:00 app worker.1 - - Error: Failed to load http://app/tmp/LabReport-L1-BabyAmara(1YRS-F)-28-10-2020 footer20201027-4-1nvgq46.html?page=1&section=ENDOCRINOLOGY&sitepage=1&title=&subsection=&frompage=1&subsubsection=&isodate=2020-10-27&topage=1&doctitle=&sitepages=1&webpage=-&time=7:19 PM&date=10/27/20, with network status code 3 and http status code 0 - Host app not found
28 Oct 2020 00:49:04.953468 <190>1 2020-10-27T19:19:04.778321+00:00 app worker.1 - - Error: Failed loading page http:///app/tmp/LabReport-L1-BabyAmara(1YRS-F)-28-10-2020 footer20201027-4-1nvgq46.html?page=1&section=ENDOCRINOLOGY&sitepage=1&title=&subsection=&frompage=1&subsubsection=&isodate=2020-10-27&topage=1&doctitle=&sitepages=1&webpage=-&time=7:19 PM&date=10/27/20 (sometimes it will work just to ignore this error with --load-error-handling ignore)
28 Oct 2020 00:49:04.953160 <190>1 2020-10-27T19:19:04.780042+00:00 app worker.1 - - QPaintDevice: Cannot destroy paint device that is being painted
28 Oct 2020 00:49:04.953123 <190>1 2020-10-27T19:19:04.780043+00:00 app worker.1 - - pure virtual method called
28 Oct 2020 00:49:04.953141 <190>1 2020-10-27T19:19:04.780044+00:00 app worker.1 - - terminate called without an active exception
28 Oct 2020 00:49:04.953104 <190>1 2020-10-27T19:19:04.783011+00:00 app worker.1 - - Aborted
28 Oct 2020 00:49:04.953182 <190>1 2020-10-27T19:19:04.816666+00:00 app worker.1 - - 4 TID-ouae5q4jw SaveReportAsPdfJob JID-fbdc5c4b3ed1c197e3fe6940 INFO: fail: 1.888 sec
28 Oct 2020 00:49:04.953554 <190>1 2020-10-27T19:19:04.816746+00:00 app worker.1 - - 4 TID-ouae5q4jw WARN: {"context":"Job raised exception","job":{"class":"SaveReportAsPdfJob","args":["LabReport",1,1],"retry":5,"queue":"default","jid":"fbdc5c4b3ed1c197e3fe6940","created_at":1603826301.916179,"enqueued_at":1603826301.9165263},"jobstr":"{\"class\":\"SaveReportAsPdfJob\",\"args\":[\"LabReport\",1,1],\"retry\":5,\"queue\":\"default\",\"jid\":\"fbdc5c4b3ed1c197e3fe6940\",\"created_at\":1603826301.916179,\"enqueued_at\":1603826301.9165263}"}
28 Oct 2020 00:49:04.953589 <190>1 2020-10-27T19:19:04.816747+00:00 app worker.1 - - 4 TID-ouae5q4jw WARN: RuntimeError: command failed (exitstatus=134): /app/vendor/bundle/ruby/2.6.0/gems/wkhtmltopdf-heroku-2.12.6.0/bin/wkhtmltopdf-linux-amd64 --encoding UTF-8 --dpi 300 --header-spacing 3 --page-size A4 --margin-top 81.0 --margin-bottom 68.0 --margin-left 0 --margin-right 0 --header-html /app/tmp/LabReport-L1-BabyAmara\(1YRS-F\)-28-10-2020\ header20201027-4-1j971uo.html --footer-html /app/tmp/LabReport-L1-BabyAmara\(1YRS-F\)-28-10-2020\ footer20201027-4-1nvgq46.html - -
28 Oct 2020 00:49:04.953204 <190>1 2020-10-27T19:19:04.816827+00:00 app worker.1 - - 4 TID-ouae5q4jw WARN: /app/vendor/bundle/ruby/2.6.0/gems/pdfkit-0.8.4.1/lib/pdfkit/pdfkit.rb:73:in `to_pdf'
28 Oct 2020 00:49:04.953145 <190>1 2020-10-27T19:19:04.816828+00:00 app worker.1 - - /app/app/models/lab_report_pdf.rb:29:in `to_pdf'
--
```

**Comment by abhishek77in** [comment]
Hi @PhilterPaper I was able to run 50 jobs repeatedly without any errors after enabling the local file access, may be this would resolve the issue.

**Comment by PhilterPaper** [comment]
Ah, I read your "intermittent failures" as running the _same_ job, most often it ran but sometimes it didn't. Now it sounds like they're different jobs, and the ones that fail are using local files. Much different.

**Comment by abhishek77in** [comment]
No success. I have also tried changing `http` to `file`, but still getting the same error - 

` Error: Failed loading page file:///app/tmp/LabReport-L1-BabyAmara(1YRS-F)-28-10-2020 header20201028-4-12imxqc.html?page=1&section=ENDOCRINOLOGY&sitepage=1&title=&subsection=&frompage=1&subsubsection=&isodate=2020-10-28&topage=1&doctitle=&sitepages=1&webpage=-&time=3:55 AM&date=10/28/20 (sometimes it will work just to ignore this error with --load-error-handling ignore)`

**(sometimes it will work just to ignore this error with --load-error-handling ignore)** - Is their anything I can do about this? It sounds like this error is very much expected to be raised intermittently.

**Comment by abhishek77in** [comment]
@PhilterPaper I have been using ruby's `Tempfile` to pass header and footer html, just like mentioned here - https://github.com/pdfkit/pdfkit/wiki/Adding-header-and-footers. But I was also closing the file before using it, which I think is getting garbage collected. Switching from `Tempfile` to `File` I did not get any error for over 100 pdfs, now this must have been the issue.

**Comment by abhishek77in** [comment]
The tempfiles were getting garbage collected by ruby, was able to reproduce this with the help of - https://www.hilman.io/blog/2016/01/tempfile/

Closing this issue. Thanks for all the support :)

**Comment by pallymore** [comment]
thanks for the update @abhishek77in - glad it's resolved 😄
