### ISSUE TITLE
Unwanted white space in tables

### ISSUE THREAD

**Issue by SanderRossel** [wkhtmltopdf/wkhtmltopdf#4868]
**wkhtmltopdf version(s) affected**: 0.12.6 (with patched qt)

**OS information**
Windows 10 Pro

**Description**
I get some extra white space in tables. It's looks like a bigger line height (almost as big as an actual line) and the values in the row don't align properly either. It looks fine in my browser (Chrome).

This one is weird, the -0,040 is aligned higher than all other values on that line and there's a bigger space under the line.
![Messed up row 1](https://user-images.githubusercontent.com/11377612/98002423-09df8e80-1dee-11eb-9801-3bdcc14b003c.png)

This one is almost like there's an extra (empty) row, except the -0,040 (again) is aligned weird.
![Messed up row 2](https://user-images.githubusercontent.com/11377612/98002471-0c41e880-1dee-11eb-89fe-c3670fcf5293.png)

**How to reproduce**
run "wkhtmltopdf test.html output.pdf" in the Windows command prompt and see the output file.
My test.html looks as follows: [test.txt](https://github.com/wkhtmltopdf/wkhtmltopdf/files/5482060/test.txt)
(I can't upload .html files, so change the extension manually.)

Looking forward to your response, thanks.

**Comment by jllodra** [comment]
Same

**Comment by psy1064** [comment]
```
"tr {                                               \r\n"
"   page-break-inside: avoid;                       \r\n"
"   page-break-after: avoid;                        \r\n"
"   page-break-before: avoid;                       \r\n"
"}   
```

**Comment by SanderRossel** [comment]
@psy1064 Thanks, this fixed the issue after almost six months!

**Comment by psy1064** [comment]
> @psy1064 Thanks, this fixed the issue after almost six months!

how did you fix that problem?

**Comment by SanderRossel** [comment]
> > @psy1064 Thanks, this fixed the issue after almost six months!
> 
> how did you fix that problem?

By adding the page-break-inside/after/before: avoid; CSS bit you suggested.

**Comment by psy1064** [comment]
> > > @psy1064 Thanks, this fixed the issue after almost six months!
> > 
> > how did you fix that problem?
> 
> By adding the page-break-inside/after/before: avoid; CSS bit you suggested.

Thanks 😊
