### ISSUE TITLE
Parse Error while using Hyphenopoly

### ISSUE THREAD

**Issue by FuV-hv** [wkhtmltopdf/wkhtmltopdf#4873]
Hi, hope you can help solving this issue. Thanks in advance! Horst

**wkhtmltopdf version(s) affected**: 0.12.6 

**OS information**
WinSRV2016 Standard with IIS 10 as Webserver

**Description**
We are using Hyphenopoly to hyphenate HTML. This works perfect in browser. Using same HTML with wkhtmltopdf  ends up in a parse error and generates a PDF without hyphenation. Printing it from browser to PDF works with hyphenation.

wkhtmltopdf.exe --debug-javascript http://localhost/test.htm C:\inetpub\wwwroot\localhost\test.pdf
Loading pages (1/6)
Warning: http://localhost/Hyphenopoly/Hyphenopoly_Loader.js:10 SyntaxError: Parse error
Counting pages (2/6)
Resolving links (4/6)
Loading headers and footers (5/6)
Printing pages (6/6)
Done

source in Hyphenopoly_Loader.js:
/* first nine lines are all comments */
line 10: ((w, d, H, o) => {
line 11:    "use strict";

**How to reproduce**
Install: Hyphenopoly (https://github.com/mnater/Hyphenopoly)
Here are (only the main) .js from Hyphenopoly for a quicker first step
[Hyphenopoly.zip](https://github.com/wkhtmltopdf/wkhtmltopdf/files/5506130/Hyphenopoly.zip)

Check this test.htm in Browser: [test.zip](https://github.com/wkhtmltopdf/wkhtmltopdf/files/5506111/test.zip)

Run: wkhtmltopdf.exe --debug-javascript http://localhost/test.htm C:\inetpub\wwwroot\localhost\test.pdf

**Expected behavior**
Execute Hyphenopoly to hyphenate HTML

**Possible Solution**  
Give more debug information / execute Hyphenopoly code

**Comment by mnater** [comment]
Hi

Creator of Hyphenopoly here.
Looks like wkhtmltopdf uses a fork of qt 4.8 that reached end of life in 2015. Hyphenopoly uses modern JavaScript syntax (e.g. the arrow function causing the parse error) that isn‘t supported on old engines.

If this project isn‘t migrating to a recent version of qt/webkit you could try an older version of Hyphenopoly: https://github.com/mnater/Hyphenopoly/tree/legacy

**Comment by FuV-hv** [comment]
Hi, thanks a lot for your response, explanation and solution!

Do I understand that the latest release of the legacy tree / Version 3.x.x (https://github.com/mnater/Hyphenopoly/archive/v3.4.0.zip) is the recommended download?

Thanks for the support ...

**Comment by mnater** [comment]
I have just tested this. This does not work either, because Hyphenopoly uses `const` and `let`, but wkhtmltopdf does not support this either.
I'm sorry that I didn't test this earlier and that I gave false hopes here.

The last way out would be to transpile Hyphenopoly to ES3 (e.g. using [babel](https://babeljs.io)), but I don't know if it is worth the effort...

**Comment by FuV-hv** [comment]
Many thanks for your commitment! Unfortunately, I don't know enough about this to make the change myself.

Is it enough if I send all javascript through babel? Then I will gladly take over the conversion and testing.

**Comment by mnater** [comment]
Don't we file the screw here until the hammer fits on it?

The author of wkhtmtopdf recommends to use other tools for pages with dynamic scripts (c.f. https://github.com/wkhtmltopdf/wkhtmltopdf/blob/master/docs/status.md) I have tried "pupeteer". It works perfectly with the current Hyphenopoly...

**Comment by FuV-hv** [comment]
Thanks a lot for your efforts! I'll go for puppeteer and found WeasyPrint too (in the same status.md). Second has a nice "feature" to our environment: A .Net-wraper. We are rendering PDF out of HTML that is generated by our tool. The tool is a .Net application. If there will be upcoming questions I'll come back. For now, you helped me a lot. Thanks!
