### ISSUE TITLE
Page not completely loaded

### ISSUE THREAD

**Issue by wachalala** [wkhtmltopdf/wkhtmltopdf#4877]
Hello,

I have a little issue to convert a big page to a pdf.

When you load the page with your navigator (https://membre.mycake.fr/premium/print.php?page=complet&membre=x&type=dl&device=1&ip=91.174.98.225) you have about 450 pages.

When i execute the commande below, it convert only 39 pages.

`wkhtmltopdf "https://membre.mycake.fr/premium/print.php?page=complet&membre=x&type=dl&device=1&ip=91.174.98.225" premium/test.pdf`

Any idea on where the problem can probably came ?

Thank you :)

**Comment by PhilterPaper** [comment]
I tried a number of things. It's consistently dying on page 39, right where it's supposed to show the photo of the Coconut Sponge Cake. Specifying the page height and width to smaller or larger than A4 changed the dead margin around the pages, but didn't solve the original problem. The image shows as "RGB color" JPEG, which seems to be the same as the other photos (I thought for a moment that maybe this image was 32 bit JPEG, as reported in #4874, but it doesn't seem to be). I tried `--javascript-delay 15000`, but it didn't help (wasn't a timeout). I even chopped out all the other pages from the HTML file (saved from the site) and just displayed the 5 pages for this recipe. wkHTMLtoPDF (0.12.5 with patched qt, on Windows 10) converted it perfectly (just this recipe alone). So, I don't think it's an unusual image format or an error in this recipe's HTML markup... it must be something cumulative over the previous 38 or so pages, but I can't figure out what.

What I _do_ know is that looking at all those pictures of delicious cakes has made me very hungry. I'm tempted to eat the remaining half Chocolate-Chocolate Chip Pudding cake sitting on my kitchen counter...

**Comment by wachalala** [comment]
Hello @PhilterPaper ,

Thank you for your fast and complete answer !
I made some tests, i remove the coconut sponge cake to check if the problem was from that recipe or image.

So now, i have 60 pages but it's stop juste after the "White Cake" title this time.
So i don't think the problem was the image but a strange error :/

Is there a way to check some log about why the process stopped ?

I'm glad to know that you love the picture :D, I hope you didn't finish the cake last time !!

**Comment by wachalala** [comment]
I have dowloaded Qt web and i had the same issue.

I correct an html error (duplicate ID) and everything work fine now...

Thank you @PhilterPaper for your help :D
