### ISSUE TITLE
Chinese Characters Missing

### ISSUE THREAD

**Issue by joel-st** [wkhtmltopdf/wkhtmltopdf#4879]
**wkhtmltopdf version(s) affected**: ^2.4

**OS information**
Linux Webserver | PHP 7.3

**Description**
Not possible to use Chinese characters in PDF. All other characters looking good, just not possible to get the chinese chars.

**How to reproduce**
We create PDF's by the following template:
[English](https://references.vzug.com/de/?lb_template=left&lb_lang=en)
[Chinese](https://references.vzug.com/de/?lb_template=left&lb_lang=zh-hans)

The generated PDF's are well except the chinese characters:
[English](https://bit.ly/3nwcjDj)
[Chinese](https://bit.ly/2IzKT0M) 

**Expected behaviour**
Normal appearance of Chinese characters.

**Possible Solution**  
Wait until document is ready. I've added the `--window-status ready` flag.

```
return new Pdf(
	[
		'binary'         => '/usr/local/bin/wkhtmltopdf -O Landscape --window-status ready',
		'ignoreWarnings' => true,
		'margin-top'     => 0,
		'margin-bottom'  => 0,
		'margin-left'    => 0,
		'margin-right'   => 0,
		'disable-smart-shrinking',
	]
);
```
Then on each PDF template before closing the `body` tag, I've added `<script>window.status = 'ready';</script>`

Thank you for any hint or help!

**Note** I've already tried it by replacing the custom font with a system font – no luck

**Comment by arron-rgb** [comment]
Did you install any Chinese font on it your server?

Check the path '/usr/share/fonts/zh_CN'

**Comment by PhilterPaper** [comment]
Some CJK fonts don't permit embedding (either subset or full) in a PDF. In such cases, you may need to make sure the platform you're displaying the PDF on also has the font installed (in a place that the Reader will be looking for it). This would severely limit your distribution of the PDF, so you may end up changing the font used so that you can use an embedable subset of the font.

**Comment by joel-st** [comment]
> Did you install any Chinese font on it your server?
> 
> Check the path '/usr/share/fonts/zh_CN'

Thank you @arron-rgb I will check this out. No such thing as zh_CN in the fonts folder on the web server. I already got in contact with the support. I will inform if it continues.

> Some CJK fonts don't permit embedding (either subset or full) in a PDF. In such cases, you may need to make sure the platform you're displaying the PDF on also has the font installed (in a place that the Reader will be looking for it). This would severely limit your distribution of the PDF, so you may end up changing the font used so that you can use an embedable subset of the font.

Thank you @PhilterPaper regarding your input, i've created a smaller test site to have the possibilities to check this out. [Here](https://wkhtmltopdf.sayhello.works/) I've made a template with two paragraphs. One styled with a custom font, the other just with `font-family: sans-serif;`. Both paragraphs missing the Chinese Characters. Do you agree, that here it cannot be a permission problem of the font?

**Comment by PhilterPaper** [comment]
> Do you agree, that here it cannot be a permission problem of the font?

Did you check both _specific_ fonts used (custom font, "sans-serif") for what sort of license they're under and whether they have any sort of redistribution limits that wkHTMLtoPDF is obeying? There's no guarantee that wkHTMLtoPDF is actually obeying any limits on embedding a font (or subset of that font); I just offer that as a possibility. If the pages display CJK text on the _same machine_ as was used to produce them, that would suggest that the Reader is able to read the local copy of the font, but the font was not embedded. If it won't even display on the same machine, it's still possible that the font is located somewhere non-standard that the HTML browser knows how to find it, but the PDF Reader can't find it. 

There are always lots of possibilities when a desired text cannot be displayed, or displays only tofu's (empty boxes). I trust that you have the right encoding declared in the source HTML (likely yes, if a browser displays it OK). CJK text isn't necessarily UTF-8; it can be any number of other multibyte encodings (SJIS, for example), and the font has to be compatible with that.

**Comment by joel-st** [comment]
It seems to be a font specific issue. To come to this point, I tried several things:

- Convert the font to woff with transfonter
- Convert the font to woff with fontsquirrel
- Check the suspicious Characters in the Font Application on my computer (Chinese Chars result in squares)
– After converting the font with fontsquirrel, wkhtmltopdf also prints the Chinese Chars as squares. 

Since the squares are visible, and this shows it is a font specific issue, I will close this issue.

**Comment by PhilterPaper** [comment]
Sounds good. Just be careful with using WOFF fonts -- check that PDF text is still selectable and copyable. I've heard of WOFF fonts sometimes being drawn as graphics instead of text, resulting in the text being visible, but not selectable.
