### ISSUE TITLE
Loading Pages (1/6) very slow.

### ISSUE THREAD

**Issue by Jacquers** [wkhtmltopdf/wkhtmltopdf#4915]
I'm not sure exactly what changed on my PC as this used to be fast, but lately it takes 15-20 seconds for this step. The rest of the steps are still fast. When I turn off my internet connection all steps are fast. Or when I run it in Windows Sandbox it's fast, with or without internet connectivity.

I have some theories:

- Antivirus (Webroot SecureAnywhere). I have no control over this as our network admin controls it and I can't turn it off
- Windows Smartscreen. Tried turning it off and it makes no difference.

Windows 10 64 bit.
Running wkhtmltopdf from the command line. The web page is very basic.

Any ideas would be appreciated. Thanks.

**Comment by Jacquers** [comment]
I think I may have tracked it down to spoolsv.exe

**Comment by KrullBorg** [comment]
same here on gnu/linux: stopping cups and then it worked again very fast

**Comment by 8ctopus** [comment]
Same here, changing the default printer to an online fixed the slowness.
