### ISSUE TITLE
Warning: Failed loading page file

### ISSUE THREAD

**Issue by rajeshkr7** [wkhtmltopdf/wkhtmltopdf#4924]
**wkhtmltopdf version(s) affected**:0.12.4 (with patched qt) 

**OS information**
Ubuntu 18.04.3 LTS (Bionic Beaver)

**Description**
I have am using 4 files(header, mail file, body,footer) to create a pdf with this command
```
wkhtmltopdf -B 50 -T 110mm --header-html header.html --footer-html footer.html mainfile.html body.html output.pdf
```
When I run this command it generate around 500 (506) pages out of 1500 pages correctly but after that it gives error
```
 Warning: Failed loading page file:///var/www/development/rajesh/Raj-header.html?page=1162&section=&sitepage=1162&title=test page&subsection=&frompage=1&subsubsection=&isodate=2021-01-12&topage=1165&doctitle=test page&sitepages=1164&webpage=Raj.html&time=1:16 PM&date=1/12/21 (ignored)
```
and generate pdfs without header and footer after that (506 +) just include blank section in every page for those header and footer.

**How to reproduce**
I guess by creating 4 temp.html having lots of repeated data, which can create around 500-1000 pages.

**Expected behavior**
It should return pages with no header and footer but a blank space in every page.

**Possible Solution**  
Looking for that.

Thanks

**Comment by PhilterPaper** [comment]
#2754 sounds like it might be the same (exceed max file handles per process).

**Comment by rajeshkr7** [comment]
@PhilterPaper thank you very much man, you are always a life saver.
It solve the problem but I am still getting lots for error, just because I have use 
```
"--load-error-handling", "ignore"
```
I could only se ERR on output screen
![err](https://user-images.githubusercontent.com/73538448/104353620-1ab72980-552e-11eb-96a1-dc4ff331176e.png)

**Comment by PhilterPaper** [comment]
You're probably still not reading the files, if you've run out of file handles. With all those "ERR"s, are you getting a good PDF out of it?

There's no reason that wkHTMLtoPDF should be keeping all those copies of header and footer HTML files open after a page is done, and possibly not even of open/reading/close repeatedly (why not just once?).

**Comment by rajeshkr7** [comment]
@PhilterPaper  yes I am getting all 1026 pages with header and footer.

**Comment by rajeshkr7** [comment]
Getting again the same issue.
```
$processWkhtmltopdf = new Process(['wkhtmltopdf', "-B", "50", "-T", "110mm","--load-error-handling", "ignore",  "--header-html", $header, "--footer-html", $footer, $htmlFileWithPath, $body, $file]);
````
![wkhtmltopdf](https://user-images.githubusercontent.com/73538448/111585537-78dde280-87e5-11eb-80e3-6d6db729c266.png)

**Comment by rajeshkr7** [comment]
**I upgrade the version to 12.6.1
Now getting this
![wkhtmltopdf-12-6](https://user-images.githubusercontent.com/73538448/111590969-cc076380-87ec-11eb-87d6-a29761e85415.png)
**

**Comment by rajeshkr7** [comment]
After adding **"--enable-local-file-access"**
getting same old Error: **Exit with code 1 due to network error: ContentAccessDenied**

```
Error: Failed to load file:///var/www/development/rajesh/automation-pdf/ancd/20210318130345/11117388Baja-header.html?page=1164&section=&sitepage=1164&title=Bank&subsection=&frompage=1&subsubsection=&isodate=2021-03-18&topage=1165&doctitle=Bank&sitepages=1164&webpage=icici/20210318130345/11117388Baja.html&time=1:45 PM&date=3/18/21, with network status code 201 and http status code 0 - Error opening /var/www/development/rajesh/automation-pdf/ancd/20210318130345/11117388Baja-header.html: Too many open files

````
