### ISSUE TITLE
Cannot render local image from HTML to PDF

### ISSUE THREAD

**Issue by fantazac** [wkhtmltopdf/wkhtmltopdf#4926]
**wkhtmltopdf version(s) affected**: 0.12.6 

**OS information**
Windows 10

**Description**
I use NReco Pdf Generator, which uses WkHtlmToPdf. I am working with Rider in C#. When trying to add an image to the resulting pdf file, the image is always an empty blank rectangle. I have looked at a lot of threads on forums to see if someone had a fix and I could not find anything sadly.

**How to reproduce**
I have used pdf generation from an HTML file and from a string. In all cases, the result was an empty rectangle. Here are most if not all the lines I tested to add an image (with the <> at start and end of course):
img src="C:\Users\Direct\Path\To\Image\logo.jpg"
img src="\C:\Users\Direct\Path\To\Image\logo.jpg"
img src="C:/Users/Direct/Path/To/Image/logo.jpg"
img src="/C:/Users/Direct/Path/To/Image/logo.jpg"

Here is the mentioned empty rectangle:
![image](https://user-images.githubusercontent.com/16083566/104970300-f38eab00-59b8-11eb-9d40-e5e3ae351a31.png)

**Expected behavior**
The image shows correctly.

**Possible Solution**  
I do not have a solution for this so far.

**Comment by PhilterPaper** [comment]
Try `--enable-local-file-access`.

**Comment by fantazac** [comment]
It might sound dumb, but where should I write this?

**Comment by PhilterPaper** [comment]
On the command line. It's a flag.

The default behavior up through 0.12.5 was to read local files, but that was changed in 0.12.6 to requiring explicit permission from the user (on the command line).

**Comment by fantazac** [comment]
I see. I tested some things and figured out i needed to add `"--enable-local-file-access"` to HtmlToPdfConverter -> CustomWkHtmlArgs if using the NReco Pdf Generator package.

Thanks a lot for the help!
