### ISSUE TITLE
width of whitespace between words is too small

### ISSUE THREAD

**Issue by cuanpub** [wkhtmltopdf/wkhtmltopdf#4929]
**wkhtmltopdf version(s) affected**: wkhtmltox_0.12.6-1.xenial_amd64.deb

**OS information**
Ubuntu 16.04 64-bit

**Description**
width of whitespace between words is too small, please see it attached images.

i searched issue lists and could not find any similar issue.

![case](https://user-images.githubusercontent.com/54624373/105189376-dcde8480-5b6f-11eb-84cb-4e2e502b087e.png)

![Screenshot from 2021-01-20 22-34-30](https://user-images.githubusercontent.com/54624373/105189403-e4059280-5b6f-11eb-816d-65ccb215adb1.png)

**Comment by PhilterPaper** [comment]
Have you double-checked that in creating the HTML source, possibly by gluing lines together, that you didn't leave out a space between one word (say, at the end of a line) and the next (say, at the beginning of the next line)? That's the most likely cause.

**Comment by cuanpub** [comment]
> Have you double-checked that in creating the HTML source, possibly by gluing lines together, that you didn't leave out a space between one word (say, at the end of a line) and the next (say, at the beginning of the next line)? That's the most likely cause. Or, somehow you ended up with not a regular space, but a "thin" or even a "zero width" space, such as during a copy-and-paste?

i found it is caused by "<span> tag", like content as

`went up from Egypt to the <span>Negev</span>, with his wife and everything he had`

the space width before "<span> tag" became very small, in some cases almost zero.

still have no idea how to solve this issue, any idea pls?

**Comment by PhilterPaper** [comment]
Offhand, no ideas, although way at the back of my mind there's something nagging at me about `<span>` related problems I've heard of somewhere. You might search these issues for "span" if you haven't.

By the way, do you have some style= or CSS (or even Javascript) defined for your `<span>`? It's useless to just have `<span>word</span>` if it doesn't modify the text presentation in some way. Perhaps if it's "empty" that could be confusing wkHTMLtoPDF.

**Comment by cuanpub** [comment]
duplicated with  #2372, close this one.

**Comment by PhilterPaper** [comment]
It's not just a plain `<span>`, you've got a span wrapped inside an anchor (link) wrapped by an `<object>`. What does the object do?

I'm not sure what is supposed to happen when you put a border on what's normally an inline element (span) -- maybe that could be confusing wkHTMLtoPDF. You may want to look at using `border-inline` instead, but that may be recent enough that wkHTMLtoPDF will have problems with it anyway. You might also be able to change the `<span>` to a `<div>` with "inline" placement and a bottom border.

**Comment by cuanpub** [comment]
> It's not just a plain `<span>`, you've got a span wrapped inside an anchor (link) wrapped by an `<object>`. What does the object do?
> 
> I'm not sure what is supposed to happen when you put a border on what's normally an inline element (span) -- maybe that could be confusing wkHTMLtoPDF. You may want to look at using `border-inline` instead, but that may be recent enough that wkHTMLtoPDF will have problems with it anyway. You might also be able to change the `<span>` to a `<div>` with "inline" placement and a bottom border.

i just tried set 'dpi':200, and it works ok according to [this](https://stackoverflow.com/questions/34241932/letter-spacing-is-too-large-with-wkhtmltopdf/46034207#46034207)

not know the underlying method, but it's just fine for my usage at this moment.

thanks a lot!
