### ISSUE TITLE
conflict border-radius border solid

### ISSUE THREAD

**Issue by bebiangel** [wkhtmltopdf/wkhtmltopdf#4942]
**wkhtmltopdf version(s) affected**: wkhtmltopdf 0.12.6

**OS information**
window

**Description**
test.html:
```
<html>

<head>
    <style>
        div {
            background-color: #c9d6df;
            color: #ffffff;
            margin: 0 10px;
            width: 32px;
            height: 32px;
            border-radius: 8px;
            border: none;
            padding: 4px;
        }

        div.active {
            background-color: #52616b;
            border: solid 2px #292e33;
            padding: 2px;
            border-radius: 4px;
        }
    </style>
</head>
<body>
<div>1</div>
<div class="active">2</div>
</body>
</html>
```
- I have a problem when converting the above html.
- I want to fill in the space between the borders that occur during conversion.

in browser:
![image](https://user-images.githubusercontent.com/25598926/106872414-9e6fca80-6716-11eb-8e4a-234c9e93910f.png)

after conversion: 
![image](https://user-images.githubusercontent.com/25598926/106872009-3325f880-6716-11eb-97a0-b35a1ee62a7b.png)

have any idea? Thanks

**Comment by PhilterPaper** [comment]
It appears that the difference is that in the PDF, the fill color was drawn with the larger border radius (that should have been overridden). Can you tell if the problem is in wkHTMLtoPDF or in your PDF reader? You might want to try the PDF on a number of different PDF Readers, in case the one you're using has a bug. I have seen differences between Adobe Acrobat Reader DC, Xpdf, and Firefox's PDF reader. You might also want to uncompress the streams (such as with PDFtk) and browse around the PDF to see what PDF commands were given -- such as, is it drawing the rectangle and its fill separately, or together in one PDF operation?

**Comment by bebiangel** [comment]
> It appears that the difference is that in the PDF, the fill color was drawn with the larger border radius (that should have been overridden). Can you tell if the problem is in wkHTMLtoPDF or in your PDF reader? You might want to try the PDF on a number of different PDF Readers, in case the one you're using has a bug. I have seen differences between Adobe Acrobat Reader DC, Xpdf, and Firefox's PDF reader. You might also want to uncompress the streams (such as with PDFtk) and browse around the PDF to see what PDF commands were given -- such as, is it drawing the rectangle and its fill separately, or together in one PDF operation?

**Comment by bebiangel** [comment]
> It appears that the difference is that in the PDF, the fill color was drawn with the larger border radius (that should have been overridden). Can you tell if the problem is in wkHTMLtoPDF or in your PDF reader? You might want to try the PDF on a number of different PDF Readers, in case the one you're using has a bug. I have seen differences between Adobe Acrobat Reader DC, Xpdf, and Firefox's PDF reader. You might also want to uncompress the streams (such as with PDFtk) and browse around the PDF to see what PDF commands were given -- such as, is it drawing the rectangle and its fill separately, or together in one PDF operation?

I used adobe acrobat reader and other pdf readers look the same.
I think it's a problem with wkhtmltopdf.
Suddenly I thought of another way, so I changed it and tested it.
When I gave a border with **box-shadow**, it looked normal without blank space, so I applied this.

thank you for the reply.
