### ISSUE TITLE
white space in table

### ISSUE THREAD

**Issue by psy1064** [wkhtmltopdf/wkhtmltopdf#4985]
**wkhtmltopdf version(s) affected**: 0.12.6

**OS information**
Windows 10

**Description**
When Convert html to pdf in qt and windows console application, table gets white space. 
It's the same issue as the "#4868" issue.
![html_whitespace](https://user-images.githubusercontent.com/29459131/114118938-a15c8680-9924-11eb-801f-bab2421a9ccd.png)

**How to reproduce**

**Expected behavior**

**Possible Solution**

**Comment by assendk** [comment]
It may help if you set fixed width in pixels to your main container. If doesn't work try to set some child divs too.

**Comment by psy1064** [comment]
I tried to convert this html code to pdf. 

html code : 
`<HTML>                                
	<HEAD>                                                                                   
<meta http-equiv="Content-Type" content="text/html" charset="utf-8"/>
</HEAD>                                 
<BODY>       

    <TABLE STYLE='WIDTH:100%' border='0' > 
      <TR>                     
        <TH>No.</TH>           
        <TH> Colum0</TH> 
        <TH> Colum1</TH> 
        <TH> Colum2</TH> 
        <TH> Colum3</TH> 
        <TH> Colum4</TH> 
        <TH> Colum5</TH> 
        <TH> Colum6</TH> 
        <TH> Colum7</TH> 
        <TH> Colum8</TH> 
        <TH> Colum9</TH> 
        <TH> Colum10</TH> 
        <TH> Colum11</TH> 
        <TH> Colum12</TH> 
        <TH> Colum13</TH> 
      </TR>                    <TR>  
  <TD>1</TD> 
  <TD> 100 </TD> 
  <TD> 100 </TD> 
  <TD> 100 </TD> 
  <TD> 100 </TD> 
  <TD> 100 </TD> 
  <TD> 100 </TD> 
  <TD> 100 </TD> 
  <TD> 100 </TD> 
  <TD> 100 </TD> 
  <TD> 100 </TD> 
  <TD> 100 </TD> 
  <TD> 100 </TD> 
  <TD> 100 </TD> 
  <TD> 100 </TD> 
</TR> 
<TR>  
  <TD>2</TD> 
  <TD> 100 </TD> 
  <TD> 100 </TD> 
  <TD> 100 </TD> 
  <TD> 100 </TD> 
  <TD> 100 </TD> 
  <TD> 100 </TD> 
  <TD> 100 </TD> 
  <TD> 100 </TD> 
  <TD> 100 </TD> 
  <TD> 100 </TD> 
  <TD> 100 </TD> 
  <TD> 100 </TD> 
  <TD> 100 </TD> 
  <TD> 100 </TD> 
</TR> 

<TR>  
  <TD>95</TD> 
  <TD> 100 </TD> 
  <TD> 100 </TD> 
  <TD> 100 </TD> 
  <TD> 100 </TD> 
  <TD> 100 </TD> 
  <TD> 100 </TD> 
  <TD> 100 </TD> 
  <TD> 100 </TD> 
  <TD> 100 </TD> 
  <TD> 100 </TD> 
  <TD> 100 </TD> 
  <TD> 100 </TD> 
  <TD> 100 </TD> 
  <TD> 100 </TD> 
</TR> 
<TR>  
  <TD>96</TD> 
  <TD> 100 </TD> 
  <TD> 100 </TD> 
  <TD> 100 </TD> 
  <TD> 100 </TD> 
  <TD> 100 </TD> 
  <TD> 100 </TD> 
  <TD> 100 </TD> 
  <TD> 100 </TD> 
  <TD> 100 </TD> 
  <TD> 100 </TD> 
  <TD> 100 </TD> 
  <TD> 100 </TD> 
  <TD> 100 </TD> 
  <TD> 100 </TD> 
</TR> 
</TABLE>
</BODY>
</HTML>`

qt code :
`int PdfUtilDlg::ConvertHtmlToPdf()
{
    wkhtmltopdf_global_settings * gs;
    wkhtmltopdf_object_settings * os;
    wkhtmltopdf_converter * c;

    wkhtmltopdf_init(false);

    gs = wkhtmltopdf_create_global_settings();
    wkhtmltopdf_set_global_setting(gs, "out", "C:\\Temp\\test.pdf" );

    wkhtmltopdf_set_global_setting(gs, "page-size", "A4" );
    wkhtmltopdf_set_global_setting(gs, "orientation", "Portrait" );

    os = wkhtmltopdf_create_object_settings();
    wkhtmltopdf_set_object_setting(os, "page", "C:\\Temp\\test.html" );

    c = wkhtmltopdf_create_converter(gs);
    wkhtmltopdf_set_progress_changed_callback(c, progress_changed);
    wkhtmltopdf_set_phase_changed_callback(c, phase_changed);

    wkhtmltopdf_add_object(c, os, NULL);

    if (!wkhtmltopdf_convert(c)) {
        qDebug() << "Conversion failed!";
        nResult = -1;
    }
    wkhtmltopdf_destroy_converter(c);
    wkhtmltopdf_deinit();

    return 0;
}`

pdf result : [test.pdf](https://github.com/wkhtmltopdf/wkhtmltopdf/files/6309312/test.pdf)

**Comment by psy1064** [comment]
resolve this problem. Add style code ```                            "tr {                                               \r\n"
                            "   page-break-inside: avoid;                       \r\n"
                            "   page-break-after: avoid;                        \r\n"
                            "   page-break-before: avoid;                       \r\n"
                            "}               
```
