### ISSUE TITLE
language and image support

### ISSUE THREAD

**Issue by AndrewHopperKainos** [wkhtmltopdf/wkhtmltopdf#4990]
Hi guys

Was wondering if it would be possible to implement other languages (non english text) into the solution such as russina, chinese and japanese etc?

Also, is there any possibility of the inclusion of image support within tables? I tried this and it does not seem to get the source before rendering

**Comment by PhilterPaper** [comment]
Could you clarify what you mean by "implement other languages"? Are you talking about the wkHTMLtoPDF external stuff, such as the command-line flags in a non-English language, or do you mean non-Latin text in the HTML (specified by the _encoding_)? As far as I know, all sorts of encodings are used successfully every day. What have you tried that has failed? Don't forget to specify the encoding in the HTML.

Images can be shown within table cells with normal `<img>` tags. What have you tried that has failed? Don't forget that if you are using _local_ image files, to give the command-line flag `--enable-local-file-access`.

**Comment by AndrewHopperKainos** [comment]
Hey bud,

Sorry for the delay in coming back.

So I checked this again and looked it from the most simple, dozy HTML page that I could create. 

Basically nothing apart from a 2 column table with some non latin text in it, see below

`<!DOCTYPE html>
<html>
<body>

<table style="width:100%">
  <tr>
    <th>Firstname</th>
    <th>Lastname</th>
    <th>Age</th>
  </tr>
  <tr>
    <td>alice</td>
    <td>Smith</td>
    <td>50</td>
  </tr>
  <tr>
    <td>Eve</td>
    <td>เคลม, เกษียณอายุ, ประกัน, ค่ารักษา, ค่ารักษาพยาบาล, ขั้นตอนการเคลมค่ารักษาพยาบาลเมื่อเกษียณอายุ, ขั้นตอนการเคลม</td>
    <td>94</td>
  </tr>
</table>

</body>
</html>`

But the text presented for me in the generated png is not as above. It is more like wingdings or something.

Do I need to install OS language packs or something for wkhtml to use?

![image](https://user-images.githubusercontent.com/32295423/118553645-7a317a00-b758-11eb-8977-c0360da6e265.png)

Now, bear with me as I am trying to learn all of this but I am no passing any parameters at all here. I am just calling wkhtmltoimage with <from> and <to> values, that is it so I fully expect I am missing something.

 .\wkhtmltoimage.exe "test.html" "test.png"

Thanks in advance
Andy

**Comment by AndrewHopperKainos** [comment]
Hi guys, non-issue on the language thing as I just found that my code was stripping out the head tag and associated encoding which is obvs super required.

The image issue is still ongoing and will chase that later
