### ISSUE TITLE
Font color is not applied 

### ISSUE THREAD

**Issue by jeevasusej** [wkhtmltopdf/wkhtmltopdf#4995]
**wkhtmltopdf version(s) affected**: 0.12.6 

**OS information**: Azure Linux and Windows

**Description**
I am using base64 fonts and used embeded. 

```
 @font-face {
                  font-family: 'abc';
                  src: url(data:application/x-font-woff;charset=utf);
                      -fs-pdf-font-embed: embed;
    -fs-pdf-font-encoding: Identity-H;
                  }

.header-1 {
     color:red!important;
}
```

I have used CSS as above. But in pdf rendering, I am always getting black color. I am not getting any color that I have mentioned.
I have used color name and also color code.

**Comment by PhilterPaper** [comment]
What have you done to isolate the problem? Have you checked that your CSS **header-1** class is being picked up, such as by adding some other property such as **background-color: purple;**? Of course, you have `class="header-1"` where you want this to appear? Do you have any other **!important** entries that might be overriding this one? Can we see a little bit of HTML to see how you're using this?

**Comment by jeevasusej** [comment]
I have checked. no other extra entries are applied. I am not sure why it is happening. 
I have tried with toc.xsl.
In that, for the header and the numbers, the font color is applied. But not for the headers. 
I don't know what is happening. I have cross checked the css. No other extra entries applied with the font color. 
But background color is working without an issue.

**Comment by jeevasusej** [comment]
Extremely sorry. 
I have loaded the StyleA and StyleB.
After applying the StyleA, Even if I change anything in StyleB, there is no change. 
I have modified the styles in StyleA and It worked as expected.

I missed to see the mistake.
