### ISSUE TITLE
Two errors about convert html to pdf (img inside the html)

### ISSUE THREAD

**Issue by StrollStars** [wkhtmltopdf/wkhtmltopdf#5018]
**wkhtmltopdf version(s) affected**: 0.12.6

**OS information**: Win7 32bit

**Description**
like https://github.com/wkhtmltopdf/wkhtmltopdf/issues/3203

Log:
> wkhtmltox\wkhtmltopdf.exe -n --enable-local-file-access 2021-6-5-15-34-34-5339525198376.html 1.pdf
Loading pages (1/6)
QNetworkAccessFileBackendFactory: URL has no schema set, use file:// for files
QNetworkAccessFileBackendFactory: URL has no schema set, use file:// for files
QNetworkAccessFileBackendFactory: URL has no schema set, use file:// for files
QNetworkAccessFileBackendFactory: URL has no schema set, use file:// for files
QNetworkAccessFileBackendFactory: URL has no schema set, use file:// for files
QNetworkAccessFileBackendFactory: URL has no schema set, use file:// for files
QNetworkAccessFileBackendFactory: URL has no schema set, use file:// for files
QNetworkAccessFileBackendFactory: URL has no schema set, use file:// for files
QNetworkAccessFileBackendFactory: URL has no schema set, use file:// for files
QNetworkAccessFileBackendFactory: URL has no schema set, use file:// for files
QWin32PrintEngine::initialize: OpenPrinter failed (RPC ????????á?)%
QWin32PrintEngine::initialize: OpenPrinter failed (RPC ????????á?)
Counting pages (2/6)
Resolving links (4/6)
Loading headers and footers (5/6)
Printing pages (6/6)
Done

There are 10 images in html.
The pdf is generated and looks fine, how can I do?

**Comment by PhilterPaper** [comment]
So you get one "URL has no schema" error for each image? Can you give us an example of one of the image calls (whether `<img>` tag, CSS background, or maybe something else)? Let's take care of that one first, and then investigate the OpenPrinter failure. The PDF appears to be produced correctly, and you just want to clean up these nuisance messages?

**Comment by StrollStars** [comment]
@PhilterPaper 
> So you get one "URL has no schema" error for each image?

I think so, because the number of errors is the same as the number of pictures. I tested again and found that the absolute path would be wrong, and there would be no error in the relative path. But the other mistake is still there.

> you just want to clean up these nuisance messages?

I'm afraid there's a potential problem I can't find.

**Comment by StrollStars** [comment]
@PhilterPaper I mean the "URL has no schema" error occurred if the images path in html is Absolute Path, if I change the Absolute Path to Relative Path, the "URL has no schema" error is gone. Why is that?

**Comment by PhilterPaper** [comment]
I don't know what it's doing. I've never seen this on 0.12.5. If you have access to the original HTML source, you could try adding `file://` in front of an absolute path and see if the schema warning goes away. A relative path carries the risk of having to change all the paths if you run wkHTMLtoPDF from a different directory. Why it would need a schema for absolute paths and not for relative, I can't answer.

As for the other (OpenPrinter) warning, I haven't seen that either. Is this 0.12.6 built from source, or is it a prebuilt one? With or without patched qt? Perhaps if you could supply a small sample that shows these problems, I could try reproducing it on Win10 and 0.12.5 (with patched qt), and maybe narrow down the possibilities. By the way, Windows 7 is quite long of tooth now, and hasn't gotten any security updates from the Evil Empire in many years. You're taking a huge risk if you have it connected to the Internet.

**Comment by StrollStars** [comment]
@PhilterPaper I downloaded version 0.12.5 from [github](https://github.com/wkhtmltopdf/wkhtmltopdf/releases/tag/0.12.5) and version 0.12.6 from [wkhtmltopdf](https://wkhtmltopdf.org/downloads.html) and found no difference in output between the two versions, whether win7 or Win10. Win7 has two "QWin32PrintEngine:::initialize: OpenPrinter failed" errors, and Win10 doesn't. But the "QNetworkAcces FileBackEndFactory: URL has no schema set" error is on both platforms.

This is a [test.zip](https://github.com/wkhtmltopdf/wkhtmltopdf/files/6657393/test.zip) that I used to test, you need to modify the path of the images which in html.

It's hard for me to modify the image path which in html, because I have a lot of html files to work with.

BTW, the certificates of 0.12.5 is outdated, so I can't verify the file such as MD5SUMS.

**Comment by PhilterPaper** [comment]
I was able to get it to run on Win10 0.12.5 (with patched qt), but it's a little odd. Is this the PDF you're looking for: 
[test-5018.pdf](https://github.com/wkhtmltopdf/wkhtmltopdf/files/6664637/test-5018.pdf) ?

I changed the img src to "/my absolute path/your file name.ext". The odd thing is that Firefox refuses to show the images unless I add `file:://C:` to the beginning of the path, but then wkHTMLtoPDF refuses to convert it (with file:// or C:)! I also removed the **!800.png** suffix on the .png files (both the actual file name and img src); I don't know if this is absolutely necessary, but it worked here. Firefox seemed to show the images a bit large, so maybe that's necessary for the browser (but not wkHTMLtoPDF)?

If you have a separate D: disk, I think there's some command in Windows to map D: to C:/some_path/ -- you may need to use that if you can't get wkHTMLtoPDF to accept the drive letter.

Hopefully that will help you track down the problem on your local configuration. Good luck!

**Comment by PhilterPaper** [comment]
The protocol specification is `file://`. What comes after that is, I think, either a drive letter and full path, or a relative _or_ absolute (starting with /) path. It doesn't seem to work consistently between a Windows browser and wkHTMLtoPDF, so who knows what is going on. I think that `file:///` means the third / is the filesystem root directory. If you can find a reliable change to your HTML that allows wkHTMLtoPDF to work correctly, you might consider writing a filter utility to modify the HTML source on-the-fly to the correct "src" format. That's ugly, but if that's all that works... You might also try inserting a `<basedir>` tag into the HTML source, which might be an easier-to-write filter. I don't see anything on the command line that would help, but maybe there is something.

**Comment by StrollStars** [comment]
@PhilterPaper Thank you for your help. There is a risk to modify HTML. I want to convert directly.

**Comment by ArrowRaider** [comment]
How do you get this verbose logging?  I have some images that do not display and there is no log for why it isn't working.

**Comment by StrollStars** [comment]
@ArrowRaider When the command is executed, the command prompt window displays information. For example it displays 6 steps if everything works. Do you do not display images before or after conversion? It may be easier to upload files to solve the problem.

**Comment by Eesha-Jain** [comment]
Here is a great video! This integrates both HTML + CSS + images into a PDF: https://www.youtube.com/watch?v=zmJV6VN2h2E . Hopefully this helps with your error

**Comment by StrollStars** [comment]
@Eesha-Jain Thank you very much, but I gave up the conversion to pdf solution.

**Comment by Eesha-Jain** [comment]
Alright, hopefully your solution still works!!
