### ISSUE TITLE
Links in the footer is not working

### ISSUE THREAD

**Issue by sasivarsha** [wkhtmltopdf/wkhtmltopdf#5026]
**wkhtmltopdf version(s) affected**: 0.12.5

**OS information**
ubuntu 14

**Description**
Links given in the footer not redirecting 

**How to reproduce**
<a href="www.google.com" target="_blank" rel="noopener">google</a>

**Expected behavior**
It should redirect to the specified link (given in the href)

**Possible Solution**

**Comment by sasivarsha** [comment]
After Updating the wkhtmltopdf version also , still facing the issue.

OS : ubuntu 20
wkhtmltopdf version(s) affected: 0.12.6

Referred from the below 

https://github.com/wkhtmltopdf/wkhtmltopdf/issues/4038

**Comment by PhilterPaper** [comment]
You might search the other tickets. I seem to recall seeing reports that header and footer HTML files are plain text always, and ignore (or treat as ordinary text) all markup tags, or maybe support only _some_ tags. Anyway, this sounds familiar.

**Comment by sasivarsha** [comment]
Hi @PhilterPaper ,

Thanks for your response.

I tried all other solutions suggested from other tickets. But that is not working.

Please suggest any other solution to fix this.

**Comment by PhilterPaper** [comment]
I see the problem. HTML tags _are_ recognized and processed, and the correct PDF objects created, **_but_** the coordinates of the header's link (the /Annot /Rect box) are listed as _above_ the top of the MediaBox! For example, the page is 842pt tall, but the link in my header is listed as being up to 866pt. Although the header and link can be seen, the click area is off page. This is definitely a bug in wkHTMLtoPDF that needs to be fixed before you can put links in a header HTML file. I tried it with a footer, and it's working fine for me, _so long as I **don't** specify -T or -B margins._ I can see that when I put a footer in, with a bottom margin, that the active _link_ is actually a bit _above_ the displayed link, and sometimes may be hidden under other content.

In both cases, I'm seeing the header or footer link coordinates are wrong, and (for header) they are above the MediaBox.

**Comment by sasivarsha** [comment]
Hi @PhilterPaper ,

Seems it is working fine if we are not giving the margin top property.

Thank you for your solution.
