### ISSUE TITLE
Unwanted linebreaks when Mathjax is used inside formatted environment

### ISSUE THREAD

**Issue by arjunsuresh** [wkhtmltopdf/wkhtmltopdf#5030]
**wkhtmltopdf version(s) affected**: 0.12.6 (only with Qt patch)

**OS information**
Ubuntu 20.04

**Description**
When Mathjax equations are added inside bold,italics,underlined etc formats, a line break is happening before the equation gets rendered. 
![Screenshot from 2021-06-27 21-11-48](https://user-images.githubusercontent.com/4791823/123558073-1025df00-d7b2-11eb-9bda-0daff51455f9.png)

**How to reproduce**
The below code can be saved to "test.html" and the following command executed
`wkhtmltopdf --javascript-delay 6000 test.html testa.pdf`
```
<html>
<head>
          <meta http-equiv="content-type" content="text/html;charset=utf-8">

<script  type="text/x-mathjax-config">  MathJax.Hub.Config({
    tex2jax: {
      inlineMath: [ ['$','$'], ["\\(","\\)"] ],
     config: ["MMLorHTML.js"],
      jax: ["input/TeX"],
      processEscapes: true
    },
  });


</script><script  async type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>

</head>
<body>
        <p> <strong>Hi $x^2$</strong></p>
        <p> <b>Hi $x^2$</b></p>
        <p> <i>Hi $x^2$</i></p>
</body>
</html>
```
**Expected behavior**
As shown on Chrome
![Screenshot from 2021-06-27 21-09-22](https://user-images.githubusercontent.com/4791823/123558015-b2919280-d7b1-11eb-8738-a80112d22aed.png)

**Comment by shashankrustagi** [comment]
![Screenshot 2021-06-28 at 2 06 31 AM](https://user-images.githubusercontent.com/26660782/123558766-a3acdf00-d7b5-11eb-92fd-f8f081fb5512.png)

your code is working fine in my computer. 
I am using MacOSX
Screenshot attached

**Comment by arjunsuresh** [comment]
Its browser right? Did you make PDF from it?

**Comment by shashankrustagi** [comment]
Yes sir, how to make Pdf from it, shall i export it to pdf?

**Comment by arjunsuresh** [comment]
Please see the steps I had mentioned to reproduce the issue -- it wont show on browser.

**Comment by shashankrustagi** [comment]
![Screenshot 2021-06-28 at 3 23 43 AM](https://user-images.githubusercontent.com/26660782/123560513-45d1c480-d7c0-11eb-90f4-bcc87175e274.png)

Reproduced the steps.
Working fine sir.
Thanks
Shashank

**Comment by arjunsuresh** [comment]
Wow. Interesting. It's not working on MacBook pro. Might be display resolution?

**Comment by shashankrustagi** [comment]
Sir, I am using Macbook Air, as well as Macbook Pro, if you want, I can send you results from Pro as well.

**Comment by arjunsuresh** [comment]
No, I got the issue. You should try a larger javascript-delay. Or can you change `$x^2$` to `$\frac{x^2}{9}$`?

**Comment by shashankrustagi** [comment]
But sir , on my device it is working fine. I will still change and let you know

**Comment by shashankrustagi** [comment]
![Screenshot 2021-06-28 at 4 08 40 AM](https://user-images.githubusercontent.com/26660782/123561537-89c7c800-d7c6-11eb-9423-6a1a04e1e763.png)

By doing $\frac{x^2}{9}$ it is moving to next line.
This means, this issue is also not resolved.

**Comment by arjunsuresh** [comment]
Yes. Earlier it was fine for you because it was only partially rendered. Only when fully rendered, the unwanted newline is coming.

**Comment by shashankrustagi** [comment]
Yes sir, I am doing something like increasing JS delay. and checking.

**Comment by shashankrustagi** [comment]
![Screenshot 2021-06-28 at 4 16 52 AM](https://user-images.githubusercontent.com/26660782/123561708-ae706f80-d7c7-11eb-9f5f-b22e4f333399.png)

Sir, see this, I have included the Hi, inside the latex $$ and this is the result.
Now, i think we should find, ways to make it italic, bold etc inside the latex.

**Comment by shashankrustagi** [comment]
![Screenshot 2021-06-28 at 4 21 50 AM](https://user-images.githubusercontent.com/26660782/123561833-5ede7380-d7c8-11eb-8ceb-e7c50df24048.png)

<html>
<head>
          <meta http-equiv="content-type" content="text/html;charset=utf-8">

<script  type="text/x-mathjax-config">  MathJax.Hub.Config({
    tex2jax: {
      inlineMath: [ ['$','$'], ["\\(","\\)"] ],
     config: ["MMLorHTML.js"],
      jax: ["input/TeX"],
      processEscapes: true
    },
  });


</script><script  async type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>

</head>
<body>
        <p> <strong> $  \textbf{Hi} \quad \frac{x^2}{9}$</strong></p>
        <p> <b> $ \textbf {Hi} \quad \frac{x^2}{9}$</b></p>
        <p> <i> $\textit{Hi} \quad \frac{x^2}{9}$</i></p>
</body>
</html>

Thanks sir,
working fine.

**Comment by arjunsuresh** [comment]
That's not a "solution".

**Comment by shashankrustagi** [comment]
OK sir. Let me try

**Comment by yefl2064** [comment]
update MathJax-2.7.9  resolved
