### ISSUE TITLE
how to know the page height in pixel?

### ISSUE THREAD

**Issue by langsz** [wkhtmltopdf/wkhtmltopdf#5036]
I want to know the A4 page content's height in pixel so that I can calculate the elements' height to avoid  the texts ,images, tables, etc be truncated into two pages. 
 Anyone know how to do?

Thanks!

**Comment by PhilterPaper** [comment]
An A4 page is 595 _points_ wide by 842 _points_ high (google `paper sizes` to get other standard sizes). Do you actually want _pixels_, which depend on the dpi setting, or _points_? Points are an absolute size, while pixels depend on the resolution.

**Comment by langsz** [comment]
> An A4 page is 595 _points_ wide by 842 _points_ high (google `paper sizes` to get other standard sizes). Do you actually want _pixels_, which depend on the dpi setting, or _points_? Points are an absolute size, while pixels depend on the resolution.

Thank you. I use the default setting which dpi is 96. I also made some tests, it is difficult to quantify an exact figure of the height which use a fixed width(1000). It will change when there are images or tables in it.

**Comment by langsz** [comment]
> An A4 page is 595 _points_ wide by 842 _points_ high (google `paper sizes` to get other standard sizes). Do you actually want _pixels_, which depend on the dpi setting, or _points_? Points are an absolute size, while pixels depend on the resolution.

Thank you. I use the default setting which dpi is 96. I also made some tests, it is difficult to quantify an exact figure of the height which use a fixed width(1000px). It will change when there are images or tables in it.

**Comment by langsz** [comment]
Ok, well, I found the solution the generate a perfect PDF now
