### ISSUE TITLE
Trying to print canvas built with fabricjs, I get a blank canvas

### ISSUE THREAD

**Issue by samael205** [wkhtmltopdf/wkhtmltopdf#5037]
**wkhtmltopdf version(s) affected**: x.y.z 
0.12.6
**OS information**

Windows 10 64 bits

**Description**

I have a tool made in canvas, using fabricjs, and I am doing tests to print said canvas in PDF, and I have opted for this tool. My first test has been to go to the official website https://www.fabricjs.com of the framework, and try to print it.

The canvas goes blank, and only the interface prints
**How to reproduce**

Call wkhtmltopdf.exe with the following parameters:

`--javascript-delay 10000 --enable-javascript --no-stop-slow-scripts "https://www.fabricjs.com"`

**Expected behavior**

The canvas is expected to print as it appears on the page.

**Possible Solution**

**Comment by PhilterPaper** [comment]
wkHTMLtoPDF is printing either to the specified output file (a .pdf file at the end of the command line) or to STDOUT. I don't think it knows anything about a "canvas". Do you have some sort of setup where STDOUT is captured to a canvas? Would you do better to directly specify an output file? Remember, what is output is the PDF _code_, not the graphics and text as it appears in a PDF reader.

**Comment by samael205** [comment]
The name of the file is specified but I have not included it in the example, sorry. 
[Sample.pdf](https://github.com/wkhtmltopdf/wkhtmltopdf/files/6802624/Sample.pdf)

I am attaching the pdf output of the fabricjs.com page, and a link to the page itself so that you can see how it should be printed

**Comment by PhilterPaper** [comment]
I get a warning from my browser that the SSL certificate is for github.com, but I proceeded anyway. You might want to figure that out at some point (why would some random site be using GitHub's cert?). Running wkHTMLtoPDF, I get a couple SSL error messages, which may be related to that. However, a PDF _is_ produced, containing most of the page except for the animated images in the center column. I suspect that it may be using advanced Javascript features that aren't supported by WebKit (such as animated images). Does it work OK for you on (at least _some_) other sites?

**Comment by samael205** [comment]
I don't know how it works on other sites, but with sejda.com I have been able to print the canvas in PDF, which means that it is not impossible to do.

**Comment by PhilterPaper** [comment]
When you say you are outputting to a "canvas", and printing that canvas, please explain how that differs from outputting to a PDF _file_, and displaying/printing the PDF through a PDF Reader of some sort? I'm wondering if your "canvas" is actually storing text and graphics at some low level (like a paint program), while a PDF file (which wkHTMLtoPDF outputs) is a collection of object definitions to define text and graphics operations (in a PDF Reader). If so, they're not going to be compatible.

**Comment by samael205** [comment]
At general levels, what it does is a general screenshot of the screen, with all the graphics that are presented on the canvas and it shows them in the PDF as is.

If you mean that wkhtmltopdf directly uses the html tags to generate the graphics within the new PDF then it is not supported, since the HTML5 canvas has its own definition engine.

We are not talking about an SVG that has a complete and complex xml structure to print it, if not that everything is encompassed within a <canvas> tag and through low-level sentences as you say, it is represented on the screen to be able to see it, I suppose than with html5 engine

**Comment by PhilterPaper** [comment]
Look inside a PDF (.pdf) file with any text editor. You will see a series of "objects" defined, each defining some aspect of text or graphics. For example, object 22 might be defining the "Times Roman" font table mapping Latin-1 byte values to standard glyph names. Object 35 might be some commands to output a graphics _stream_, which defines things like the drawing color, pen width, dash pattern, and various drawing primitives (normally **compressed**, so it will just appear to be gibberish). Neither HTML(5) nor SVG are involved, except as _input_ to wkHTMLtoPDF.

This is what wkHTMLtoPDF outputs. It knows nothing about a "canvas", just that it writes to an output _file_. Then you use a PDF Reader (e.g., Adobe Acrobat Reader, Firefox browser, etc.) to render those text and graphics commands (in the file) onto virtual or real paper. If your "canvas" support understands PDF, it might be able to translate to whatever text and graphics commands it natively supports. If not, the PDF commands (objects) are probably just nonsense to it, and little or nothing will be displayed. PDF is intended to be placed in a text file, and rendered using a Reader. Can you just output to a .pdf file and use a Reader to view it?

**Comment by samael205** [comment]
Thanks for all the clarification. We have come to the conclusion that we cannot use this tool for our needs. We will look for another, or external products that are already in operation.

**Comment by Sicos1977** [comment]
If you can install Chrome on your server than you could try this --> https://github.com/Sicos1977/ChromeHtmlToPdf

I made that because I also had problems with wkHtmlToPdf
