### ISSUE TITLE
latex rendering error

### ISSUE THREAD

**Issue by lirizhong97** [wkhtmltopdf/wkhtmltopdf#5046]
We use GitHub issues only to discuss about wkhtmltopdf bugs and new features. For
this kind of questions about using wkhtmltopdf, please use
any of the support alternatives shown in https://wkhtmltopdf.org/support.html or 
post an issue on https://stackoverflow.com/.

os: ubuntu 18.04
wkhtmltopdf: wkhtmltopdf 0.12.6 (with patched qt)
command: wkhtmltopdf https://katex.org ./out.pdf
issue: latex rendering error.

Please giving any suggestions.

Thanks!

**Comment by PhilterPaper** [comment]
What "latex rendering error"? wkHTMLtoPDF expects HTML input, not LaTeX. I wouldn't be surprised if this KaTeX site involved some fairly advanced Javascript libraries, which will likely give the ancient WebKit rendering engine in wkHTMLtoPDF some problems.

**Comment by lirizhong97** [comment]
Firstly thank you for reply ASAP. Let me explain again and show you more detail. Actually, The Latex  would be completely html content finally by some javascript and css library. So we can treat them as html input to wkhtmltopdf. 
So wkhtmltopdf should work correctly to rending out The Math Tax on PDF, which should be like on web browser.
But actually it does not. 

Secondly, I change to use another html to pdf convert library, it works well, which using higher version webkit engine and work   
perfectly as web browser.

Finnaly, I think the root reason is the webkit engine version is too low.

Hopely for reply, thank you again.

**Comment by PhilterPaper** [comment]
I haven't looked at the KaTeX code, but I suspect it's some pretty heavy Javascript. Unfortunately, the WebKit used in wkHTMLtoPDF is very old, and doesn't support a lot of recent JS updates. The Number One thing wkHTMLtoPDF needs is a port to a current level of WebKit, or some other rendering engine that can easily be plugged in and upgraded. I suspect the main holdup in this is that wkHTMLtoPDF is just too intertwined with the internals of WebKit to easily separate it out.

I'm not sure how it would be done, but it sounds like we need to grab the output of Chrome or another rendering engine just before it gets bitmapped and sent to the screen (or virtual printer). Most engines are capable of printing to a file or printer, so other than adding headers and footers, and a title page and TOC, you'd think that most of the work would already be done for us. That may not be as simple as it sounds!

**Comment by lirizhong97** [comment]
Thank you. Yes, It's not a simple work. Hopely I can see some version of wkhtmltopdf can do this job. I wish someone can do this and I will try to do if i'm free, cuz this is value.
