### ISSUE TITLE
pdf with blank pages

### ISSUE THREAD

**Issue by Sienna-Milady** [wkhtmltopdf/wkhtmltopdf#5051]
**wkhtmltopdf version(s) affected**: 0.12.6 (with patched qt)

**OS information**

OS: Ubuntu 21.04 hirsute
Kernel: x86_64 Linux 5.11.0-25-generic
DE: LXQt 0.16.0

**Description**

Converting html to pdf for [this forum post](https://forum.zettelkasten.de/discussion/561/three-layers-of-evidence) results in a pdf with blank pages.

**How to reproduce**

1. Run `wkhtmltopdf https://forum.zettelkasten.de/discussion/561/three-layers-of-evidence System2019ThreeLayersEvidence.pdf` in a terminal.
2. Open the resulting pdf.
3. Notice that it has blank pages.

**Expected behavior**

The pdf should look as if I had taken a screenshot of the web page.

**Comment by rafaeldev** [comment]
Hi @Sienna-Milady 
If you do not need a specific feature from `0.12.6`, uses `0.12.5` version.

**Comment by Sienna-Milady** [comment]
Hi, @rafaeldev. Thanks for commenting. I've migrated from wkhtmltopdf, so I'll just close this issue.

**Comment by JonMurphy** [comment]
> Hi, @rafaeldev. Thanks for commenting. I've migrated from wkhtmltopdf, so I'll just close this issue.

Hi @Dilan-Zelsky - I am experience the same issue - LOTS of blank pages.  What did you migrate to?

**Comment by Dilan-Zelsky** [comment]
@JonMurphy Mozila Firefox's print function. It works anywhere and is user-friendly. Just hit `Ctrl+P` and there you go. I hope it helps you.
