### ISSUE TITLE
cannot render the text around by the comma

### ISSUE THREAD

**Issue by langsz** [wkhtmltopdf/wkhtmltopdf#5057]
e.g. 
<p>0:12334:</p>

it will display in pdf as below:
0口

(口 means it cannot render the font)
 who know what happen?

**Comment by PhilterPaper** [comment]
That's not a "tofu" character (meaning it can't render the glyph for this font). That looks more like a CJK character, although decimal 12334 (x302E) doesn't seem to match my Unicode guide. So anyway, it looks like `:12334:` was interpreted as some sort of escape sequence for a glyph or entity. About the closest I can come is the Kangxi radical U+2F1E or possibly U+2F1D.

**Comment by langsz** [comment]
if text is :{numbers}:, e.g. :0x11222FDD:, :12345678:, all render as a "tofu" in PDF.

**Comment by PhilterPaper** [comment]
My point was that the box-like symbol you showed does not appear to be a "tofu". Was this copy-pasted from the PDF result, or did you type in a CJK character using your keyboard, that you thought looked _close_ to a tofu?

I tried your examples using wkHTMLtoPDF 0.12.5 from the Windows 10 command line, and they displayed correctly (no "tofu" or other symbol, just the digits between colons). I cannot reproduce the problem you're reporting. Does the following code produce the error for you?
```
<html>
<head>
<title>comma tofu</title>
</head>
<body>
<p>123456  :0x11222FDD:   :12345678:</p>
<p>12334  :0x302E:   :12334:</p>
</body>
</html>
```

**Comment by langsz** [comment]
It is markdown emoji font! which will generate as a image but there is no font file.
