### ISSUE TITLE
How to create a version for Debian 11 (bullseye)

### ISSUE THREAD

**Issue by domainfun** [wkhtmltopdf/wkhtmltopdf#5092]
https://wkhtmltopdf.org/downloads.html lists "The current stable series is 0.12.6, which was released on June 11, 2020", including  for Debian 10 (buster).

https://wkhtmltopdf.org/status.html also states in Future Plans that "I’ll do a final 0.12.7 release by Aug 2020".

I have also checked https://github.com/wkhtmltopdf/packaging/releases and https://github.com/wkhtmltopdf/packaging/releases/0.12.6-1 and cannot see a version for Debian 11 (bullseye).

Would it please be possible to create a 0.12.7 release (or even a 0.12.6 release) for Debian 11 (bullseye)?

I'm no expert at C++ or QT and have never used Azure, but if there is anything I can help with please do let me know.

Or perhaps someone could provide a link to some instructions as to one would go about building a version for Debian 11 (bullseye) from source?

Many thanks.

**Comment by ashkulz** [comment]
Builds have been published to the website: see wkhtmltopdf/wkhtmltopdf@e59bfcce3e8db83341264bdd75d996319402ccff.
