### ISSUE TITLE
wkhtmltopdf not work in production server

### ISSUE THREAD

**Issue by ajaiau0** [wkhtmltopdf/wkhtmltopdf#5095]
**wkhtmltopdf version(s) affected**: x.y.z 

**OS information**
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"

**Description**
wkhtmltopdf is perfectly work in local machine with python,but in live server the CSS not working,clasing the every pages in HTML page.i try to CSS in inline and other ways but its not worked,with wkhtmltopdf i cant work in production.i didn't understand the issue .
 no any other errors while generating the pdf,but after the pdf is not exactly by the HTML,every pages and images are not work properly after generate pdf.

**Comment by fatso83** [comment]
This is not enough information to do anything about. "It does not work" does not tell what the error is or how to reproduce it.

What does "clasing the every pages" mean? Crashing?
