### ISSUE TITLE
Missing Build for Ubuntu 22.04

### ISSUE THREAD

**Issue by ADVALAKI** [wkhtmltopdf/wkhtmltopdf#5189]
**wkhtmltopdf version(s) affected**: x.y.z 

**OS information**
Ubuntu 22.04

**Description**
can not able to install package

**How to reproduce**
download wkhtmltopdf bionic , and try to install

**Expected behavior**
should properly installed

**Possible Solution**  
Build for ubuntu 22.04 is missing.

**Comment by progmancod** [comment]
+1

**Comment by jcdrubay** [comment]
+1

**Comment by kesturbo** [comment]
`cd /tmp

wget http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.0g-2ubuntu4_amd64.deb

wget https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6-1/wkhtmltox_0.12.6-1.bionic_amd64.deb

sudo apt install ./libssl1.1_1.1.0g-2ubuntu4_amd64.deb

sudo apt install ./wkhtmltox_0.12.6-1.bionic_amd64.deb`

**Comment by patrickfabrizius** [comment]
Thanks @kesturbo - you saved my night.

**Comment by ashkulz** [comment]
Duplicate of wkhtmltopdf/packaging#114

**Comment by ashkulz** [comment]
Builds for 22.04 have been published to the website: see wkhtmltopdf/wkhtmltopdf@e59bfcce3e8db83341264bdd75d996319402ccff.

**Comment by pauladesh** [comment]
sudo wget http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.0g-2ubuntu4_amd64.deb
sudo dpkg -i libssl1.1_1.1.0g-2ubuntu4_amd64.deb
