### ISSUE TITLE
App doesn't work. Windows server 2022 in docker container

### ISSUE THREAD

**Issue by takylemo909** [wkhtmltopdf/wkhtmltopdf#5204]
**wkhtmltopdf version(s) affected**: 0.12.4, 0.12.6 

**OS information**
Windows Server 2022.
Image in docker. mcr.microsoft.com/windows/server:ltsc2022

**Description**
The binary doesn't work, even doesn't show the version of app. Also, I tried different versions of windows containers nano/full/etc.
![image](https://user-images.githubusercontent.com/51309418/170224195-f98f8708-73d7-4dc9-89ee-b9e384104147.png)

**How to reproduce**
1) Run container in docker:
Docker run -it mcr.microsoft.com/windows/server:ltsc2022 cmd
2) copy wkhtmltopdf to container(docker cp)
3) run wkhtmltopdf or wkhtmltopdf--version

**Expected behavior**
Shows the version of app, and help and can generate pdf's

**Comment by Hp93** [comment]
I'm having similar issue, have you been able to fix it?

**Comment by youyzilla** [comment]
> I'm having similar issue, have you been able to fix it?

need to install wkhtmltopdf by using choco

 choco install wkhtmltopdf -y
