### ISSUE TITLE
No proper alignment when converted to pdf

### ISSUE THREAD

**Issue by san59deep** [wkhtmltopdf/wkhtmltopdf#5227]

**Comment by Sicos1977** [comment]
https://github.com/Sicos1977/ChromeHtmlToPdf

**Comment by san59deep** [comment]
@Sicos1977  can you please send the link to download chromehtmltopdf.exe file?

**Comment by Sicos1977** [comment]
See the readme on the githib page

**Comment by Sicos1977** [comment]
https://github.com/Sicos1977/ChromeHtmlToPdf#pre-compiled-binaries

**Comment by san59deep** [comment]
@Sicos1977 the colour is important for my requirment and the there is page break and merging of the lines for clear view please go through the images attached.

![colour missing](https://user-images.githubusercontent.com/101329210/177929954-e2c89ecb-33e1-41b5-b0a1-2a4a29631b7a.PNG)

NO COLOUR AND MERGING OF LINES


![page break1](https://user-images.githubusercontent.com/101329210/177929996-2dbd0cb8-e3d8-4919-b62d-c9c46418753d.PNG)

PAGE BREAK

Can you please guide me in resolving this issue?

**Comment by Sicos1977** [comment]
By default background printing is disabled use this option to enable it and I don't know what you mean with merging of lines

```c#
        /// <summary>
        ///     Print background graphics. Defaults to false.
        /// </summary>
        [Option("print-background", Required = false, Default = false, HelpText = "Print background graphics")]
        public bool PrintBackground { get; set; }
```

**Comment by san59deep** [comment]
please see the marked portion for getting the clear view of overlapping.

![marked overlap](https://user-images.githubusercontent.com/101329210/177934296-a5a375de-f309-4f72-9352-6a10485a4bb0.png)

**Comment by san59deep** [comment]
@Sicos1977 can you help me in avoiding page break?

**Comment by Sicos1977** [comment]
You want everything on one page?

**Comment by san59deep** [comment]
1 Page content should remain in 1 page itself, it should not go to second page that's my requirement sir.

**Comment by Sicos1977** [comment]
If you want everything on one page then you can use the option

```c#
        /// <summary>
        ///     The paper size to use, when this option is set is will override <see cref="PaperWidth" /> and
        ///     <see cref="PaperHeight" />
        /// </summary>
        [Option("paper-format", Required = false, Default = PaperFormat.Letter,
            HelpText = "Paper format to use, when set then this will override --paper-width and --paper-height")]
        public PaperFormat PaperFormat { get; set; }
```

Set it to

```c#
/// <summary>
///     Fit the page to the width and height of the content it is displaying
/// </summary>
FitPageToContent
```

**Comment by san59deep** [comment]
@Sicos1977 page break got resolved sir , but the overlapping still exists can you guide me in that?

**Comment by Sicos1977** [comment]
I have no idea how to resolve that since that is something Chrome does. So you probably need to fix something in the HTML that you are using

**Comment by san59deep** [comment]
@Sicos1977  Thank you sir, all the issues are resolved, the product is awesome.
