### ISSUE TITLE
Non english characters are not getting converted into PDF correctly

### ISSUE THREAD

**Issue by vaibhav-filesanywhere** [wkhtmltopdf/wkhtmltopdf#5254]
**wkhtmltopdf version(s) affected**: 0.12.6

**OS information**
Windws 11/ Windows Server 2019

**Description**
Non english (Hindi language) characters are not getting converted to PDF

**How to reproduce**
a) I have below html page:
https://filestoragecenter.com/facorp50/Policeverification.html
b) to convert into PDF using below command:
wkhtmltopdf.exe https://filestoragecenter.com/facorp50/Policeverification.html "E:\Release\Police.PDF"

**Expected behavior**
Way HTML is displaying in browser is not coming in PDF, all non english characters are appearing as black box.

**Comment by Sicos1977** [comment]
https://github.com/Sicos1977/ChromeHtmlToPdf

**Comment by vaibhav-filesanywhere** [comment]
Thank you Sicos and appreciate your quick response, your library solved my purpose
